### ISSUE TITLE
fRO | buyAuto bug

### ISSUE THREAD

**Issue by allanon** [OpenKore/openkore#10]
fRO requires that a packet be sent to acknowledge buy and sell transactions. Until that packet is sent, the character cannot move. As a workaround, the character can either relog or teleport.

This broke sellAuto (and manual sell as well) until a fix was committed:
https://github.com/OpenKore/openkore/blob/master/src/Network/Receive/fRO.pm

But while selling now works, buying is still broken in the same way. It has been confirmed that the exact same packet (09D4) should be sent when buying is complete.

Please fix buyAuto and preferably the "buy" command as well.

**Comment by itsrachelfish** [comment]
Fixed by pull request #64
