### ISSUE TITLE
Stuck during route_Tool Dealer / iRO

### ISSUE THREAD

**Issue by Koflex** [OpenKore/openkore#100]
Hello, I am using the iRO_update version, 1 month ago was not happening these STUCK errors now when the kore talk to any NPC Tool Dealer, this locking and is looped , wanted to know if it was from the ( recvpackets ) until redid the process of the extractor, and tried to update ( fields ), but without success.

Oh, I think I understand where Kore will autobuy / sell it ends up giving Stuck route , googled about it but could not comprender as correct .

http://forums.openkore.com/viewtopic.php?f=56&t=18916

Initiating auto-sell.
Calculating auto-sell route to: Morroc Ruins(moc_ruins): 114, 63
Tool Dealer: Type 'store' to start buying, or type 'sell' to start selling
Ready to start selling items
Done talking with Tool Dealer.
Auto-sell sequence completed.
Calculating auto-storage route to: Morroc Town(morocc): 156, 97
Stuck at moc_ruins (116,63), while walking from (116,63) to (159,37).
Stuck during route.

I am using a macro to relog when Kore get stuck, but if they can help me how to fix these errors, whether they are related to the npc or other factors.

Thank you Gentlemen

**Comment by raijinbuster** [comment]
this happens in geffen and comodo too.
so it seems the error should be around the buy or sell function.

**Comment by Maythamk** [comment]
i have same problem in payon, any suggest ?
