### ISSUE TITLE
Cannot detect weight

### ISSUE THREAD

**Issue by tronix04** [OpenKore/openkore#1000]
openkore cant detect when its overweight and cant trigger autostorage, it just keep on killing mobs and looting items...

itemsTakeAuto 2
itemsTakeAuto_party 0
itemsGatherAuto 0
itemsMaxWeight 89
itemsMaxWeight_sellOrStore 48
itemsMaxNum_sellOrStore 99
cartMaxWeight 7900
itemsTakeAuto_new 0
itemsTakeGreed 0

saveMap payon
saveMap_warpToBuyOrSell 1
saveMap_warpChatCommand
memo1
memo2
memo3
memo4

storageAuto 1
storageAuto_npc payon 181 104
storageAuto_distance 5
storageAuto_npc_type 1
storageAuto_npc_steps
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 50

**Comment by kaliwanagan** [comment]
Closing because we don't support phRO.

**Comment by tronix04** [comment]
its not phro, im playing iro re:start

**Comment by tronix04** [comment]
nvm, i change job my acolyte to priest, ang its working again...
