### ISSUE TITLE
Bot not storing certain items in storage

### ISSUE THREAD

**Issue by jepejepe** [OpenKore/openkore#1001]
I noticed that my bot was only storing certain items and did some trial and error. I made sure my code was correctly placed in items_control.txt and was pretty sure it was right since I was already using the same codes before the anti bot patch.

Monster's Feed 0 1 0
Cyfar 0 1 0

Situation: Bot was 55% overweight due to having a lot of items, but we're going to concentrate more on the 150 monster's feed and around 150 cyfars which I wanted to store. 

I ran the bot, but instead of triggering the autostorage code, it decided to just calculate the route to lockmap. I added a few items such as Iron Ore( as well as Iron Ore 0 1 0 in items_control ), it stored only the Ores, but not the Cyfar and Monster's Feed.

I then thought that maybe the auto storage would only trigger beyond 55%, so I then added items that weren't nudging which in this case is Monster's Feed and Cyfar in my inventory just incase it was a matter of overweight % and not the name of the item, and pushed my weight to 58%.  Still no auto storage. I then decided to add a few more items such as Rotten Fish and Orange Juice, as well as adjusting the items_control yet again. The bot triggered the auto storage only for the rotten fish and Orange Juice. 

![a](https://user-images.githubusercontent.com/31201253/29700391-b4cf8fce-8996-11e7-9357-2233b3f60320.PNG)

**Comment by jepejepe** [comment]
As you can see from the screenshot above, It stored the Orange Juice and the Rotten Fish. It completely ignored the Cyfar and Monster Feed that I wanted to store inside my storage, and decided to move to the lockmap.

**Comment by Nipodemos** [comment]
try to use the ID of item man, who knows heheh
it might solve your issue
```
528 0 1 0 # monster feed
7053 0 1 0  #cyfar
```

**Comment by jepejepe** [comment]
yeah i was hopeful that it'd work, but it didn't lol. I even tried "Monster Feed 0 1 0"

**Comment by jepejepe** [comment]
Same goes for Monster Feed 50 0 0 0 1, it's not getting any monster's feed from cart as well.

**Comment by alisonrag** [comment]
items_control:
line 442:
Monster's Feed 0 0 1

line 373:
Cyfar 0 0 1

if you are setting the auto storage for these items before the mentioned lines they are been override

**Comment by jepejepe** [comment]
Thank you! I never had any issues with the override before the patch so i'd assume it'd be the same case with this.
