### ISSUE TITLE
Openkore closes automatically

### ISSUE THREAD

**Issue by Fruitard** [OpenKore/openkore#1002]
### Summary:

bot was working fine few days back before antibot was implemented. after downloading and installing the latest openkore. this error keep closes my bot automatically

### Impact:

i can't make it work like how it should be.

### Expected Behavior:

botting normally like how it should before antibot was implemented.

### Actual Behavior:

bot automatically closes and this error.txt pops out

```
OpenKore version what-will-become-2.1
@ai_seq = macro
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2017_08_25
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)

Error message:
Can't use string (""spearman scroll 10" 0 0 0
") as a HASH ref while "strict refs" in use at src/Log.pm line 254.

Stack trace:
Can't use string (""spearman scroll 10" 0 0 0
") as a HASH ref while "strict refs" in use at src/Log.pm line 254.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x59678fc)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		next if (!defined($_));
* 		$_->{'func'}->($type, $domain, $level, $currentVerbosity, $message, $_->{'user_data'}, $near, $far);
  	}
```

### Steps to Reproduce:

will have to reopen the bot every now and then.

is this a bug or only I am encountering it?
@Henrybk if you can see please

**Comment by alisonrag** [comment]
Spearman scroll are used where?

**Comment by Nipodemos** [comment]
it seems that in itemscontrol.txt this item : **spearman scroll 10** is written wrong...
is there a " in the beggining of the name?

**Comment by alisonrag** [comment]
maybe double quotes

**Comment by Fruitard** [comment]
but it is only happening to 1 of my bot, im trying to removed all the unwanted stuff inside itemcontrol.txt and will update and see if it happens again.

**Comment by Fruitard** [comment]
after editing the itemcontrol.txt a new error came out.

```
OpenKore version what-will-become-2.1
@ai_seq = macro
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2017_08_25
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)

Error message:
Can't use string ("") as a HASH ref while "strict refs" in use at src/Log.pm line 254.

Stack trace:
Can't use string ("") as a HASH ref while "strict refs" in use at src/Log.pm line 254.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x5a46744)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		next if (!defined($_));
* 		$_->{'func'}->($type, $domain, $level, $currentVerbosity, $message, $_->{'user_data'}, $near, $far);
  	}
```

**Comment by Fruitard** [comment]
@alisonrag are you encountering any of the above mentioned problems? if not can you pass me your files to let me try it out, I am using the github latest openkore version but still these problems are popping out every now and then.

**Comment by alisonrag** [comment]
did you use any macros?
im current using the last github version

**Comment by Fruitard** [comment]
@alisonrag yes I am using macro to bypass somethings. I don't think that is the reason why I encounter these errors.

**Comment by koynro** [comment]
I assume this is from your 'reload all' after adding a macro for ```automacro reload {
        console /Cannot calculate a route from .* to/i
        call {
        do reload all
        }
}
```

I was getting this as well. Not sure if I still am because I have other issues.


The end of the file seems to be what it errors on, regardless of what it says. (Mine says `Zargon 0 0 1` for example).

I did add a newline to the end of the file, which _may_ be helping?

**Comment by Fruitard** [comment]
it helped after you used captical Z Zargon in the items_control.txt?

**Comment by Fruitard** [comment]
it is working fine now after i removed this macro
```
automacro reload {
        console /Cannot calculate a route from .* to/i
        call {
        do reload all
        }
}
```
please close this topic. Thanks for the help!

**Comment by ChrstphrR** [comment]
Great that you discovered that the macro was causing the crashes!

Thank you for posting up a solution to follow up, @Fruitard

**Comment by koynro** [comment]
This issue should not be closed. The macro isn't an issue. 'Reload All' should be able to be called by a macro and not cause a crash. Also, the macro is a temp fix for a different issue (unless the autosell/autobuy buy has been fixed which I don't believe it has).

@ChrstphrR

**Comment by Fruitard** [comment]
@koynro actually this macro isn't needed anymore as most of the autosell/autobuy are fixed, I am currently using the latest github version and it is working perfectly fine without `reload all`
