### ISSUE TITLE
iRO Restart Bot not auto buying after when it goes back to town due to death/overweight

### ISSUE THREAD

**Issue by keithit110** [OpenKore/openkore#1003]
I am botting in iRO REstart and i set my buyauto to buy awakening potion and fly wing on a NPC. If i trigger the buyauto manually by going Command>auto buying and it works. When the bot is in the town due to death/overweight, it doesnt initiate to buy.  As per the wiki link, my config should buy when the bot is in town. May i know what im missing? Im attaching my auto buy config

http://openkore.com/index.php/BuyAuto

buyAuto Awakening Potion{
	npc yuno_in01 25 34
	distance 5
	minAmount 
	maxAmount 10
	}

**Comment by khan2terror** [comment]
Sorry Bro if i wont even know how to answer your question. i just wanna ask you a favor if you can share your bot program. XD been searching for a working bot for some time now. thank you in advance. GL

**Comment by alisonrag** [comment]
@khan2terror 

https://github.com/OpenKore/openkore/archive/master.zip

**Comment by alisonrag** [comment]
continue in #1006
