### ISSUE TITLE
saveMap_warpToBuyOrSell

### ISSUE THREAD

**Issue by bebox123** [OpenKore/openkore#1004]
Hi! I just noticed that even when it is enabled it doesn't use butterfly wing. The Kore identifies the normal butterfly wing as "Novice Butterfly Wing" but when I logged in the account I don't have the Novice Butterfly Wing only the normal one which can be bough to any tool dealer. I tried saving the map where I suppose to saved but nothing happens. I usually use this before the update but now I don't know what happen, maybe in portals.txt?

**Comment by alisonrag** [comment]
type
i on console and get the index of item
type item desc INDEXOFITEM
get the correct ID and post here, i dont have any account on iro to test

**Comment by alisonrag** [comment]
maybe you can try #410

**Comment by bebox123** [comment]
Thank you so much for helping me. I'll try this one now.

**Comment by alisonrag** [comment]
any update?

**Comment by alisonrag** [comment]
closed because the owner not replied
