### ISSUE TITLE
Automacro not trigger

### ISSUE THREAD

**Issue by r421** [OpenKore/openkore#1005]
###### Summary: 
I use automacro when bot reach specific map to move to other map like this
```
automacro hunting {
location gef_fild10
exclusive 1
call {
do move gef_fild14
}
timeout 10
}
```

###### Expected Behavior:
Bot should move to target map when reach set map
###### Actual Behavior:
Bot walking around without trigger the macro

**Comment by alisonrag** [comment]
automacro hunting {
location gef_fild10
exclusive 1
run-once 1
timeout 10
call {
do move gef_fild14
release hunting
}
}
