### ISSUE TITLE
iRO:Restart Stuck/DC on autoBuy/autoSell

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#1006]
###### Affected configuration(s)/ file(s):
```AI openkore```
###### Expected Behavior: 
Openkore do the autosell, autostorage and autobuy without error

###### Actual Behavior: 
many people are experiencing problems, stuck/dc in any of this process

###### Steps to Reproduce: 
normally in iRO:ReStart after death openkore doesn't do the cited proccess or when buy to many items we got dc and after sell, npc doesn't send the sell packet and openkore disconect

Latest github version.
OS: windows, unix distribuition

References:
#719 
#873 
#928
#945  
#973 
#979
#989  
#1003 
#1015 
#1042 
#1072 
#1109

**Comment by phamtrong204** [comment]
#873: is it same as this video? https://www.youtube.com/watch?v=nxTB6AgkVrg (after changed map, it is a collision with a portal, which kore 've just moved out)

**Comment by alisonrag** [comment]
In this case openkore is tracing a route that passes through the portal

**Comment by Zelecktor** [comment]
This also happens on iRo Chaos
I dont know why AI makes this secuence, I have a normal config autostorage, autobuy and autosell
It is like.

Autostorage - AutoBuy - Autostorage - AutoSell - Autostorage - Autosell (yes x2) - Autostorage ---> Route to lock map

**Comment by troymark901** [comment]
I encounter another issue while using cart. when u transfer item to your cart there is issue(17). saying that "you are using hacking tool or something illegal." i forgot the exact sentence.

**Comment by sctnightcore** [comment]
#1042

**Comment by Glikadin** [comment]
Was the solution found? Autobuy still not working.

**Comment by ChiNTooT** [comment]
i'm having problem in aldebaran and geffen
while buying potions, keep on disconnecting
is there a solution on this issue now?

**Comment by Bombahee** [comment]
i'm having problem in aldebaran and geffen
while buying potions, keep on disconnecting
is there a solution on this issue now?

**Comment by Glikadin** [comment]
I see a lot of working bots, so the solution to the problem exists.

**Comment by oleokoong** [comment]
all my bot work perfectly except the one overide config by macro...keep looping between storage buy n sell...i add reload all and relog into macro line still  same result..
#1072

**Comment by Bombahee** [comment]
@oleokoong did you try botting in aldebaran? can't buy potion and bot due to dc issue

**Comment by oleokoong** [comment]
`[Sep 8 22:29:33 2017.59] [connection] You are now in the game
[Sep 8 22:29:33 2017.61] [console] Your Coordinates: 165, 258
[Sep 8 22:29:33 2017.23] [parseMsg_statuslook] You are now: UNKNOWN_STATUS_993 (Duration: 511.273s)
[Sep 8 22:29:33 2017.24] [parseMsg_statuslook] You are now: UNKNOWN_STATUS_994 (Duration: 1711.294s)
[Sep 8 22:29:33 2017.24] [party] Allowed other player invite to Party
[Sep 8 22:29:33 2017.24] [console] Other players are not allowed to view your Equipment.
[Sep 8 22:29:33 2017.24] [info] Achievement 200005 added.
[Sep 8 22:29:33 2017.25] [info] Achievement 220023 added.
[Sep 8 22:29:33 2017.25] [info] Achievement 220024 added.
[Sep 8 22:29:33 2017.25] [info] Achievement 220025 added.
[Sep 8 22:29:33 2017.25] [info] Achievement 220030 added.
[Sep 8 22:29:33 2017.25] [info] Achievement 220031 added.
[Sep 8 22:29:33 2017.25] [info] Achievement 230201 added.
[Sep 8 22:29:33 2017.25] [info] Achievement 240000 added.
[Sep 8 22:29:33 2017.26] [info] Achievement 240001 added.
[Sep 8 22:29:33 2017.26] [info] Achievement 240002 added.
[Sep 8 22:29:33 2017.26] [info] Achievement 240003 added.
[Sep 8 22:29:33 2017.71] [info] =========================== Server Infos ===========================
[Sep 8 22:29:33 2017.71] [info] EXP Rates: 150% (Base 100% + Premium 0% + Server 50% + Plus %) 
[Sep 8 22:29:33 2017.71] [info] Drop Rates: 125% (Base 100% + Premium 0% + Server 25% + Plus %) 
[Sep 8 22:29:33 2017.71] [info] Death Penalty: 50% (Base 100% + Premium 0% + Server -50% + Plus %) 
[Sep 8 22:29:33 2017.71] [info] =====================================================================
[Sep 8 22:29:33 2017.71] [parseMsg_statuslook] You are no longer: UNKNOWN_STATUS_993
[Sep 8 22:29:33 2017.72] [parseMsg_statuslook] You are no longer: UNKNOWN_STATUS_994
[Sep 8 22:29:38 2017.74] [route] Calculating lockMap route to: Sograt Desert(moc_fild06)
[Sep 8 22:29:45 2017.56] [route] Calculating auto-storage route to: Morroc Town(morocc): 160, 258
[Sep 8 22:29:45 2017.60] [route] Calculating auto-storage route to: Morroc Town(morocc): 160, 258
[Sep 8 22:29:49 2017.94] [npc] NPC image: kafra_04.bmp
[Sep 8 22:29:49 2017.94] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:29:49 2017.94] [npc] Kafra Employee: Welcome. Kafra is always here to help you.
[Sep 8 22:29:49 2017.94] [npc] Kafra Employee: How can I help you?
[Sep 8 22:29:50 2017.77] [skill] Player Rakkick (6) is casting Item Appraisal on himself (Delay: 0ms)
[Sep 8 22:29:51 2017.19] [list] ------ Responses (Kafra Employee) ------
#  Response
0  Use Save Service
1  Use Storage Service
2  Use Warp Service
3  Use Cart Service
4  Check Other Information
5  Quit
6  Cancel Chat
----------------------------------------
[Sep 8 22:29:53 2017.22] [inventory] Inventory Item Removed: Free Ticket for Kafra Storage (3) x 1
[Sep 8 22:29:53 2017.18] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:29:53 2017.18] [npc] Kafra Employee: Here, let me open
[Sep 8 22:29:53 2017.18] [npc] Kafra Employee: your Storage for you.
[Sep 8 22:29:53 2017.18] [npc] NPC Kafra Employee (1): Done talking
[Sep 8 22:29:54 2017.21] [ai_npcTalk] Done talking with NPC Kafra Employee (1).
[Sep 8 22:29:54 2017.44] [route] Calculating auto-sell route to: Morroc Town(morocc): 150, 246
[Sep 8 22:29:54 2017.91] [storage] Storage closed.
[Sep 8 22:29:54 2017.91] [success] Storage logged
[Sep 8 22:29:55 2017.76] [npc] NPC image: kafra_04.bmp
[Sep 8 22:29:55 2017.80] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:29:55 2017.81] [npc] Kafra Employee: Welcome. Kafra is always here to help you.
[Sep 8 22:29:55 2017.82] [npc] Kafra Employee: How can I help you?
[Sep 8 22:29:57 2017.17] [list] ------ Responses (Kafra Employee) ------
#  Response
0  Use Save Service
1  Use Storage Service
2  Use Warp Service
3  Use Cart Service
4  Check Other Information
5  Quit
6  Cancel Chat
----------------------------------------
[Sep 8 22:29:59 2017.16] [inventory] Inventory Item Removed: Free Ticket for Kafra Storage (3) x 1
[Sep 8 22:29:59 2017.15] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:29:59 2017.16] [npc] Kafra Employee: Here, let me open
[Sep 8 22:29:59 2017.16] [npc] Kafra Employee: your Storage for you.
[Sep 8 22:29:59 2017.16] [npc] NPC Kafra Employee (1): Done talking
[Sep 8 22:30:00 2017.19] [ai_npcTalk] Done talking with NPC Kafra Employee (1).
[Sep 8 22:30:00 2017.33] [route] Calculating auto-sell route to: Morroc Town(morocc): 150, 246
[Sep 8 22:30:00 2017.90] [storage] Storage closed.
[Sep 8 22:30:00 2017.90] [success] Storage logged
[Sep 8 22:30:00 2017.96] [npc] NPC image: kafra_04.bmp
[Sep 8 22:30:00 2017.96] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:30:00 2017.96] [npc] Kafra Employee: Welcome. Kafra is always here to help you.
[Sep 8 22:30:00 2017.97] [npc] Kafra Employee: How can I help you?
[Sep 8 22:30:02 2017.18] [list] ------ Responses (Kafra Employee) ------
#  Response
0  Use Save Service
1  Use Storage Service
2  Use Warp Service
3  Use Cart Service
4  Check Other Information
5  Quit
6  Cancel Chat
----------------------------------------
[Sep 8 22:30:04 2017.31] [inventory] Inventory Item Removed: Free Ticket for Kafra Storage (3) x 1
[Sep 8 22:30:04 2017.20] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:30:04 2017.20] [npc] Kafra Employee: Here, let me open
[Sep 8 22:30:04 2017.20] [npc] Kafra Employee: your Storage for you.
[Sep 8 22:30:04 2017.21] [npc] NPC Kafra Employee (1): Done talking
[Sep 8 22:30:05 2017.24] [ai_npcTalk] Done talking with NPC Kafra Employee (1).
[Sep 8 22:30:05 2017.43] [route] Calculating auto-sell route to: Morroc Town(morocc): 150, 246
[Sep 8 22:30:05 2017.92] [storage] Storage closed.
[Sep 8 22:30:05 2017.93] [success] Storage logged
[Sep 8 22:30:06 2017.96] [npc] NPC image: kafra_04.bmp
[Sep 8 22:30:06 2017.98] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:30:06 2017.99] [npc] Kafra Employee: Welcome. Kafra is always here to help you.
[Sep 8 22:30:06 2017.10] [npc] Kafra Employee: How can I help you?
[Sep 8 22:30:07 2017.91] [skill] Player Rakkick (6) is casting Item Appraisal on himself (Delay: 0ms)
[Sep 8 22:30:08 2017.56] [list] ------ Responses (Kafra Employee) ------
#  Response
0  Use Save Service
1  Use Storage Service
2  Use Warp Service
3  Use Cart Service
4  Check Other Information
5  Quit
6  Cancel Chat
----------------------------------------
[Sep 8 22:30:10 2017.52] [inventory] Inventory Item Removed: Free Ticket for Kafra Storage (3) x 1
[Sep 8 22:30:10 2017.20] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:30:10 2017.20] [npc] Kafra Employee: Here, let me open
[Sep 8 22:30:10 2017.20] [npc] Kafra Employee: your Storage for you.
[Sep 8 22:30:10 2017.20] [npc] NPC Kafra Employee (1): Done talking
[Sep 8 22:30:11 2017.23] [ai_npcTalk] Done talking with NPC Kafra Employee (1).
[Sep 8 22:30:11 2017.43] [route] Calculating auto-sell route to: Morroc Town(morocc): 150, 246
[Sep 8 22:30:11 2017.92] [storage] Storage closed.
[Sep 8 22:30:11 2017.92] [success] Storage logged
[Sep 8 22:30:12 2017.66] [npc] NPC image: kafra_04.bmp
[Sep 8 22:30:12 2017.73] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:30:12 2017.74] [npc] Kafra Employee: Welcome. Kafra is always here to help you.
[Sep 8 22:30:12 2017.74] [npc] Kafra Employee: How can I help you?
[Sep 8 22:30:14 2017.20] [list] ------ Responses (Kafra Employee) ------
#  Response
0  Use Save Service
1  Use Storage Service
2  Use Warp Service
3  Use Cart Service
4  Check Other Information
5  Quit
6  Cancel Chat
----------------------------------------
[Sep 8 22:30:16 2017.44] [inventory] Inventory Item Removed: Free Ticket for Kafra Storage (3) x 1
[Sep 8 22:30:16 2017.22] [npc] Kafra Employee: [Kafra Employee]
[Sep 8 22:30:16 2017.22] [npc] Kafra Employee: Here, let me open
[Sep 8 22:30:16 2017.22] [npc] Kafra Employee: your Storage for you.
[Sep 8 22:30:16 2017.22] [npc] NPC Kafra Employee (1): Done talking
[Sep 8 22:30:17 2017.24] [ai_npcTalk] Done talking with NPC Kafra Employee (1).`

**Comment by Glikadin** [comment]
Sad

**Comment by Glikadin** [comment]
Still not work.

**Comment by sctnightcore** [comment]
#1180

**Comment by Naozumi2k** [comment]
I'm experiencing the same problem from time to time.
Openkore get stuck with error "Stuck during route."
Reloging several times usually solve that

**Comment by oleokoong** [comment]
Just increased buy sell and auto storage time out

**Comment by fadreus** [comment]
In IRO Chaos there are possibilities when disconnecting on `route` for `autobuy` `autosell` `autostorage` the sequence didn't resume (stuck). I solved mine by using `doCommand ai clear` in `config.txt` along with macro to enable `doCommaind` and disable it once it resume.

> Just increased buy sell and auto storage time out

This should work (for iRO Chaos). I tempted to reduce timeout to make mine work faster but instead it disconnect more often.

> Autostorage - AutoBuy - Autostorage - AutoSell - Autostorage - Autosell (yes x2) - Autostorage ---> Route to lock map

I experience this too sometimes (some of them because my messed up `maxAmount` in `config.txt` and `items_control.txt`), my solution is using macro `do autosell`.
Using command `autosell` will only doing `autobuy` and `autostorage` and then to `lockMap` (_if they are at town doing nothing or just on `route`_).

As long as kore work fine with `ai manual`, I fix everything with `macro`.
Not an elegant solution but it get the job done 😁😁😁

**Comment by Naozumi2k** [comment]
This route stucks not always associated with autostorage/autobuy.
I get this error sometimes on characters without autostorage settings. I'm just starting openkore, it's loads, than I enter move command and get bot stucks..

**Comment by fadreus** [comment]
For nub like me, 

> Commands::run("relog");

relog is kore command right? will it work if I replace with `ai clear` the same as kore command?
My macro took few seconds to enable and disable, if it work this would be better.
Relog took me around 10 seconds. 😌
Hehehee..

**Comment by fadreus** [comment]
#1335

**Comment by lututui** [comment]
Try #1621

**Comment by Fadreus** [comment]
Re:Start gone for good.
Is this still relevant?

**Comment by c4c1n6kr3m1** [comment]
@Glikadin do you still have problem DC after bought something from Cat Paw Shrimp Merchant ?
this kind NPC only sent single 09D4 on iRO
while normal NPC sent double 09D4 , and this double 09D4  is hardcoded on misc.pm

**Comment by Nipodemos** [comment]
closing this since iRO Restart is dead
