### ISSUE TITLE
A chat pops up when moving out from morocc. Map change locker. iRO:RESTART

### ISSUE THREAD

**Issue by SecretNinjaWarrior** [OpenKore/openkore#1007]
When moving from morocc to moc_fild12, a chat pops up that prevents a bot from moving to the next map.
The bot will be stuck ON TOP of the portal making it very obvious that it is a bot.
Forced NPC Conversation

config: autoTalkCont 1

> Calculating lockMap route to: Sograt Desert(moc_fild18)
> Unknown #50006: Do you want to move?
> : Type 'talk cont' to continue talking
> ------ Responses (Unknown #50006) ------
> #  Response
> 0  Yes
> 1  No
> 2  Cancel Chat
> ----------------------------------------
> itself: Type 'talk resp #' to choose a response.

**Comment by ristrettojoe1** [comment]
Same issue from 23 days ago
#835

**Comment by lututui** [comment]
@Henrybk maybe it's time to pull request autoTalkDatabase

**Comment by sctnightcore** [comment]
reactOnNPC talk resp @resp(/Yes/i) {
type responses
msg_0 /Do you want to move?/i
}

**Comment by SecretNinjaWarrior** [comment]
I have no reactOnNPC on my config. 

But I used this macro and I was able to move to the next map

automacro AvoidStuck {
console /Do you want to move/
run-once 1
call AntiStuck
}

macro AntiStuck {
pause 2
do talk resp 0
pause 1
release AvoidStuck
}

**Comment by butasnacondom** [comment]
hi i know this topic is closed but i just need some clarification with the new dialogue going out of morocc...
where do i put the codes that you contributed? because i tried putting it in my config and sadly it didnt work. thank you and respect to all you guys

**Comment by SecretNinjaWarrior** [comment]
If you've downloaded the latest openkore, you simply need to:
1. make a macros.txt under the folder "controls"
2. Then input my code in the "macros.txt" that you made
```
automacro AvoidStuck {
console /Do you want to move/
run-once 1
call AntiStuck
}
macro AntiStuck {
pause 2
do talk resp 0
pause 1
release AvoidStuck
}
```
3. That's the only thing I did, fairly simple.

> | openkore folder
> .....| control folder
> ..........| config.txt
> ..........| items_control.txt
> ..........**| macros.txt**
> ..........| mon_control.txt
> ..........| priority.txt
