### ISSUE TITLE
openkore the server has denied your connection problem.

### ISSUE THREAD

**Issue by kaotikus1** [OpenKore/openkore#1008]
I am new to github and also first time to use openkore.. Now, I been trying to make the bot work for 2 days with minimal amount of sleep, and still cant get it to work, im dumb.. I already visited a lot of forum posts and searched about how to connect to the server, extract the recvpackets and etc but still doesnt work.. the server i want to try to bot is OdinRO, a mid rate one.. Please if there is anyone who can guide me through it, please help me.. I can provide the data needed.. THanks!

**Comment by sctnightcore** [comment]
OdinRO have gamegurad ? 
http://openkore.com/index.php/ServerType

**Comment by kaliwanagan** [comment]
Closed for not following the issue template.

**Comment by kaotikus1** [comment]
No, OdinRo has no gameguard at all
