### ISSUE TITLE
IRO:ReStart Using Merchant skill "Appraisal Item" in a macro / command line will caused DC

### ISSUE THREAD

**Issue by tellmewhy99** [OpenKore/openkore#1009]

**Comment by alisonrag** [comment]
server?

**Comment by tellmewhy99** [comment]
sorry, irostart

**Comment by c4c1n6kr3m1** [comment]
update your bot

**Comment by tellmewhy99** [comment]
the latest build, anyone having this issue too?

**Comment by nemisawesome** [comment]
I was able to reproduce the issue on a version that was a few days old, but the current release version no longer has the issue. Double check your version and/or re-update.

**Comment by tellmewhy99** [comment]
cheers for this information, I will pull a copy and try again. Will close this once confirmed

**Comment by alisonrag** [comment]
are the latest version working?
