### ISSUE TITLE
iRO:RESTART route to anthell01 from Prontera

### ISSUE THREAD

**Issue by SecretNinjaWarrior** [OpenKore/openkore#1010]
Summary: 
I deleted this code in portals.txt
Basically anything related to cmd_fild08

```
# Anthell
#anthell01 35 267 moc_fild20 161 144
#anthell02 171 170 moc_fild20 333 315
#moc_fild20 156 143 anthell01 35 263
#moc_fild20 337 315 anthell02 168 170
#anthell01 35 267 cmd_fild08 335 355
#anthell02 171 170 cmd_fild08 344 82
#cmd_fild08 335 355 anthell01 35 263
#cmd_fild08 348 82 anthell02 171 170
```
and then I added this to portals.txt which I manually mapped with /where

```
moc_fild02 101 18 moc_fild04 317 376
moc_fild04 221 328 anthell01 35 262
```

But when I ran the bot, it went from Prontera (savepoint) > Kafra warp going to morocc > moc_fild12 > then to cmd_fild08

I'd like to avoid cmd_fild08 because my low level bots can't go through the Sandmans & Kobold Archers

Can anyone help me? Thanks!

**Comment by c4c1n6kr3m1** [comment]
delete another portal 
i'm sure you missed it
did you edit correct portals.txt?

**Comment by SecretNinjaWarrior** [comment]
I see.
I edited the portals.txt under the tables folder before

Now I edited portals.txt under the iRO > restart folder
Now the bot says:

> Calculating lockMap route to: Ant Hell(anthell01)
> Cannot calculate a route from prontera (115,72) to

Here is my portals.txt

```
moc_fild01 101 18 moc_fild04 317 376
moc_fild04 221 328 anthell01 35 262
moc_fild05 375 208 moc_fild04 26 206
moc_fild06 376 316 moc_fild05 24 153
moc_fild07 379 201 moc_fild06 28 201
```

**Comment by SecretNinjaWarrior** [comment]
In IRO RE:START World Map, these map doesn't exist. Does that have to do anything with going to anthell01?
My bot is currently at moc_fild06, a map not in the IRO RE:START World Map, and the bot doesn't move at all even though I commanded it to move xx yy in a valid cell inside the map

**Comment by c4c1n6kr3m1** [comment]
all portals your bot going through, should list on portals.txt.
fix your self, you know what to do.

what worldmap ? do u mean maps.txt ? yes it should list there

**Comment by SecretNinjaWarrior** [comment]
Yes. I already input all the portals that I go through it portals.txt, the bot can't find its way to anthell01
What I mean by World Map is "Ctrl+~" in game. The maps are not there, maybe it has something to do with that?
The bot doesn't move when it is on a map that doesn't exist in the "World Map"

**Comment by c4c1n6kr3m1** [comment]
it does not relate with "that world map"
try this, do u see tables\old ?
copy all files inside "tables\old" and paste on your tables\iro\restart
make a backup first, do it on your own risk

**Comment by sctnightcore** [comment]
#787

**Comment by SecretNinjaWarrior** [comment]
Haven't tried that yet. However, I manually mapped xx yy portals from Prontera to Anthell01 but it says it cannot find a route to anthell01

**Comment by SecretNinjaWarrior** [comment]
Used this code
```
moc_fild01 101 18 moc_fild04 317 376
moc_fild04 221 328 anthell01 35 262
moc_fild05 375 208 moc_fild04 26 206
moc_fild06 376 316 moc_fild05 24 153
moc_fild07 379 201 moc_fild06 28 201
```
worked for me. I was able to get to anthell01 from Prontera.
Deleted portals that has cmd_fild08 & anthell in them because there is actually no portals in cmd_fild08 to get to anthell
