### ISSUE TITLE
Bot predicts where the monster will move ?

### ISSUE THREAD

**Issue by koodpzok** [OpenKore/openkore#1011]
Why does the bot always move in front of the monster, then attack? For ex. if a monster is moving to location Y, the bot will be already waiting at location Y. It wont attack the monster while it is moving. I remember the old openkore was not like this.

**Comment by Mortimal** [comment]
@koodpzok It was... openkore doing this because your client doing this, when u click on monster your char moving to the same position monster does.

**Comment by koodpzok** [comment]
i mean when the bot click at the monster as it moves to another location, instead of attacking that monster immediately, it clicked on the ground near the location that the monster would move towards. And this makes many ppl easily notice that THIS CHARACTER IS A BOT. :/ The old kore would never click on the ground as i remember

**Comment by joecabezas** [comment]
nope, this is how the client works afaik, kore was always like this
