### ISSUE TITLE
Re:Start Error Code: 10060

### ISSUE THREAD

**Issue by r421** [OpenKore/openkore#1012]
###### Summary: 
Bot keep saying this:
![image](https://user-images.githubusercontent.com/26808551/29747272-e525055a-8b26-11e7-82ea-4f6398f1072c.png)

I try login using client just smooth login no stuck or error message display.

Did server change to new IP?

###### Affected configuration(s)/ file(s):
it normal before
###### Expected Behavior:
Bot should connect to the server
###### Actual Behavior:
Bot not connect to the server

**Comment by SecretNinjaWarrior** [comment]
SERVER?

**Comment by r421** [comment]
Sorry, forgot to mention. it Ragnarok Re:START

**Comment by SecretNinjaWarrior** [comment]
Do you have more than 15 bots? Because I think the limit of accounts per IP address is 15. If you got more than 15, you'll get this error

**Comment by r421** [comment]
Really? 5 bot on total. 2 on separate VM and other 3 on separate VM

**Comment by kapyogg1** [comment]
i am having the same issue.. after the server disconnection earlier today

**Comment by alisonrag** [comment]
try to use vpn, iro are blocking some ips randomly

**Comment by javieremaciass** [comment]
which vpn for exaple u know?

**Comment by sctnightcore** [comment]
@javieremaciass  www.google.com > free vpn

**Comment by javieremaciass** [comment]
@sctnightcore Friend, I used and tried several already (the hotspot shield, wtfast, etc) and he had bad experiences with everyone, so the recommended recommendation (which would serve as the contribution for all), well day buddy.
