### ISSUE TITLE
IRO Restart Disconnect after teleport or changing maps

### ISSUE THREAD

**Issue by cuckoo94** [OpenKore/openkore#1013]
Hi, my bots always get disconnected from map server after using fly wing or changing maps, i don't know what could it be, please if someone can help i'd really appreciate it.
If i need to post my config or something just ask, Thanks!

**Comment by SecretNinjaWarrior** [comment]
What does the console say?

**Comment by cuckoo94** [comment]
discconected from map server connecting to account server in 33 seconds...

**Comment by javieremaciass** [comment]
do u recommend a vpn ?

**Comment by brylle0714** [comment]
cuckoo94 i have the same problem

**Comment by alisonrag** [comment]
have you tryied to update your openkore to last version?

**Comment by alisonrag** [comment]
closed because the owner of issue did not answered
