### ISSUE TITLE
iRO Re:Start Rodex in macro disconnecting

### ISSUE THREAD

**Issue by kidbreaker22** [OpenKore/openkore#1017]
###### Summary:
 Basically when I'm trying to implement the rodex in my macro and after sending and closes the mail, my bot disconnects. I don't know if this is a bug or it is just my macro

###### Expected Behavior: 
Successfully sends a mail to the person whom last pm me.

###### Actual Behavior: 
Disconnects during/after sending a mail from rodex system.

Code:
automacro GiveButterflyWing {
	pm "need tele"
	exclusive 1
	call {
	 pause 1
	 do rodex open 
	 do rodex write $.lastpm
	 do rodex settarget $.lastpm
	 do rodex settitle tele
	 do rodex setbody for you
	 do rodex setzeny 0
	 do rodex add 3 1 
	 do rodex send
	 pause 1
	}
}

![untitled](https://user-images.githubusercontent.com/31119522/29755426-b32f35e0-8b65-11e7-99b7-54c5d5ca6a73.png)

**Comment by kidbreaker22** [comment]
I might as well as since I don't know how, how can I make my macro read the ID number of the new mail I just got from my other bot? Since for some reason sometimes my bot gets tele from Lutie to Izlude bottom right and can't get out without any items. 

![untitled1](https://user-images.githubusercontent.com/31119522/29755656-2d54b900-8b69-11e7-888f-49aa2f3515c0.png)

**Comment by lucasbradok** [comment]
i think its send the wrong packet.  Get disconnect after the rodex send.
not my image but get dced
![image](https://user-images.githubusercontent.com/31176013/29817841-fbe40bf0-8c8f-11e7-81d5-8f0c259e4f90.png)

@Henrybk can you look at this when you have time?

**Comment by japs28** [comment]
@lucasbradok try to make tittle and body message longer, got mine working.
ex>
settitle asdada dssad
setbody asdsad sadada

**Comment by alisonrag** [comment]
are you tested with tittle and body different?

**Comment by kidbreaker22** [comment]
@alisonrag I have tested with title and body message longer and it did worked compare to just a short messages if that what you're asking.

**Comment by alisonrag** [comment]
continue in #1090
