### ISSUE TITLE
Bot uses new morocc on Re:start

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#1020]
As the title says the bot uses the new morocc map for re:start which i think is a big source of the problems people are reporting.  If the bot goes anywhere near the middle it gets stuck and requires you to manually walk it away.  This should be updated so its not a problem.

**Comment by Mortimal** [comment]
@Zexeta  Please post some logs with u encountering this.

**Comment by Zexeta** [comment]
A log of what?  I check the bot and its spamming cannot calculate route and its towards the middle of the map in morocc.  I assume it ends up there to move around the mass amount of people and then since the map doesn't actually match up it gets stuck on something and sits there.  If you load up wxstart you can plainly see its using the newer morocc map which the server does not use.  So when you get to the center of the map where you shouldn't be able to go(according to which map the bot uses) it doesn't know what to do.

**Comment by Mortimal** [comment]
just rename maps then morocc-old.fld.gz to morocc.fld.gz and try

**Comment by oleokoong** [comment]
It work with rename Morocc-old to morocc .. I did it last week and no problems at all

**Comment by Zexeta** [comment]
I know that fixes it, im saying there are a ton of complaints about this happening and it might want to get baked into the updates so we don't have 20 posts linked together saying the the bots are stuck.

**Comment by oleokoong** [comment]
Openkore support multi type server..

**Comment by Zexeta** [comment]
Obviously....... but surely there is a way to set it to use the other field file to avoid this problem.  I find it funny i try to make a post to avoid the spam threads saying bots are stuck and i get a dumb response like "it supports multi type server".

**Comment by oleokoong** [comment]
Wish someone will implement this feature like the tables folder function for specific server..

**Comment by alisonrag** [comment]
Kore does not manage old Episodes well

**Comment by Mortimal** [comment]
@oleokoong only plugin will be usefull... i already took an order for one so cant do this to...

**Comment by SecretNinjaWarrior** [comment]
Hello all
I tried to do this: 
just rename maps then morocc-old.fld.gz to morocc.fld.gz(leave this renamed to sms) and try

But there is already "morocc.fld.gz" on the same folder. Should I overwrite it or what?

**Comment by LeHartx** [comment]
The west morocc portal has an npc notification asking whether to move or not. All character there are stuck.

**Comment by lucasbradok** [comment]
@LeHartx just use this plugin https://github.com/Henrybk/Plugins/tree/master/autoTalkDatabase

whos getting this error just delete all morocc.fld.gz from fields and fields/EP15.2 and fields/EP14.3 folder and and just rename this morocc-old.fld to morocc.fld.gz or morocc_mem.fld to morocc.fld.gz
