### ISSUE TITLE
i cant run 15 or more bots in my PC iRO restart...

### ISSUE THREAD

**Issue by bakitwhy69** [OpenKore/openkore#1022]
is there a reason why i can't run 15 or more bot in my PC? 
I get an error every time i try to run the 15 and 16th bot.. 

the error i get is:
Couldn't connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (error code 10060) 

is there any solution for me to be able to run more bots? my PC can handle maybe atleast 100 bots at a time. 

Thanks.

**Comment by Mortimal** [comment]
omg

**Comment by bakitwhy69** [comment]
but i heard some people are running more than 15 bots in their PC.. thats why im curious if its really possible. and if yes, how are they able to do it... @Mortimal

**Comment by troymark901** [comment]
anyone can do auto storage and not disconnecting?

**Comment by oleokoong** [comment]
i can open window start.exe up to 80ID back in 2012..

**Comment by Mortimal** [comment]
@oleokoong *back in 2012..* it was great times yeah?
@bakitwhy69 vpn or proxy isn't it obvious?

**Comment by Mortimal** [comment]
@troymark901 u using latest openkore from github?

**Comment by troymark901** [comment]
@mortimal ok i will check.

**Comment by 10201244054** [comment]
Try proxifier and make rule for another .exe, u might need vpn
