### ISSUE TITLE
ASking for help on extracting Receive packets using PEEK

### ISSUE THREAD

**Issue by acepartacus** [OpenKore/openkore#1025]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by acepartacus** [comment]
[ragna.zip](https://github.com/OpenKore/openkore/files/1261409/ragna.zip)

**Comment by sctnightcore** [comment]
link you server ?

**Comment by acepartacus** [comment]
@sctnightcore http://skyrealmragnarok.com/

here's the config and the recvpackets that i got, i obtained 1 from peek and 1 from another extractor, both dont work tho, here's the screenshot also 

![image](https://user-images.githubusercontent.com/29881490/29840047-206a5d8c-8d33-11e7-8efb-12981671f41e.png)


this one is from peek that I configured
[PacketLengths_20120410.txt](https://github.com/OpenKore/openkore/files/1261496/PacketLengths_20120410.txt)
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1261497/recvpackets.txt)

server details

ip 104.238.206.57
port 6900
version 42
master_version 1
serverType kRO_RagexeRE_2012_04_10a
serverEncoding Western
charBlockSize 144
addTableFolders kRO/RagexeRE_2012_04_10a;kRO

im using xkore 1

thank you btw

**Comment by acepartacus** [comment]
additional info @sctnightcore it knows my coordinates, but it cant move then after a while it will disconnect.

let me know if there are additional infos that i can provide to help also.

cheers!

**Comment by alisonrag** [comment]
Your servertype are wrong try another or use peview to get the right servertype

**Comment by sctnightcore** [comment]
use with xkore 0 and 3

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/29856338-5ca25392-8d7c-11e7-8fd4-20f004b3c4f3.png)
xkore 0 is work XD

**Comment by acepartacus** [comment]
Thank you @sctnightcore

**Comment by acepartacus** [comment]
Hi @sctnightcore  can you send me your config? im getting timeout :( using xkore 0
![image](https://user-images.githubusercontent.com/29881490/29871162-669ea6a2-8dbd-11e7-85e2-2e8cfb7e3b3f.png)

**Comment by sctnightcore** [comment]
Take a look at yourself. XD

**Comment by acepartacus** [comment]
@sctnightcore  i'm sorry im confused, what do you think should i check? is it the recvpackets? config? servers?

**Comment by sctnightcore** [comment]
[skyrealmragnarok.com]
ip 104.238.206.57
port 6900
version 42
master_version 1
serverType kRO_RagexeRE_2012_04_10a
serverEncoding Western
charBlockSize 144
addTableFolders kRO

1.del recvpackets.txt in kRO
2.move you recvpacket to kRO

**Comment by acepartacus** [comment]
@sctnightcore I followed your steps, also completed the fld creation

![image](https://user-images.githubusercontent.com/29881490/29879837-cec00b3e-8dd8-11e7-810e-52f1df6b8f93.png)

OpenKore version what-will-become-2.1
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2017_08_24
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)

Error message:
Illegal division by zero at src/Interface/Wx/MapViewer.pm line 411.

Stack trace:
Illegal division by zero at src/Interface/Wx/MapViewer.pm line 411.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x63ec814)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	
* 	($self->{view}{xscale}, $self->{view}{yscale}) = (
  		$self->{bitmap}->GetWidth / $self->{field}{width},

**Comment by acepartacus** [comment]
update it's working when I dont use the updated field, i use the default only from the openkore in github, but the items are in korean, 

![image](https://user-images.githubusercontent.com/29881490/29880376-30056898-8dda-11e7-925e-668a0fb11d8f.png)

**Comment by acepartacus** [comment]
update it's now fixed, added the translate kro english folder

**Comment by acepartacus** [comment]
Thank you so much for your help @sctnightcore

**Comment by alisonrag** [comment]
can we close this?

**Comment by acepartacus** [comment]
yes @alisonrag thanks
