### ISSUE TITLE
[bug] command "storage get" causing crash

### ISSUE THREAD

**Issue by Guiim** [OpenKore/openkore#1027]
###### Summary: 
After starting the dialog with kafra, and using the command "storage get" without indicating the rest of the command, it crashes openkore. Both in the wx interface and in openkore.pl
###### Affected configuration(s)/ file(s):
The storage get command
###### Impact:
crash and close interface wx or console cmd 
###### Expected Behavior:
Should return the correct way to use the command
storage get
ex: Syntax Error in function 'storage get' (storage)
Usage: storage get <storage index item#> <(amount)>
###### Actual Behavior:
When the command is used without indicating the index of the item and without the quantity the error is generated
###### Steps to Reproduce:
Use the storage get command without indicating the item index in the inventory After starting the dialog with kafra and opening the storage.
storage get
###### Additional Details:

error.txt
OpenKore version what-will-become-2.1
@ai_seq = storageAuto items_take route
Network state = 5
Network handler = Network::DirectConnection
Revision: git:ba20aeb_2017-08-30 ctime:2017_08_02
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)

Error message:
Assertion failed!
 at C:/Users/xxxxx/Desktop/openkore/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('') called at src/InventoryList.pm line 246
	InventoryList::getMultiple('InventoryList::Storage=HASH(0x9cf12cc)', undef) called at src/Commands.pm line 4719
	Commands::cmdStorage_get(undef) called at src/Commands.pm line 4636
	Commands::cmdStorage('storage', 'get') called at src/Commands.pm line 303
	Commands::run('storage get') called at src/functions.pl line 998
	main::parseInput('storage get') called at src/functions.pl line 63
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x7bbad4c)') called at C:\Users\xxxxx\Desktop\openkore\openkore.pl line 97
	main::__start() called at C:\Users\xxxxx\Desktop\openkore\openkore.pl line 212

Stack trace:
Assertion failed!
 at C:/Users/xxxxx/Desktop/openkore/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('') called at src/InventoryList.pm line 246
	InventoryList::getMultiple('InventoryList::Storage=HASH(0x9cf12cc)', undef) called at src/Commands.pm line 4719
	Commands::cmdStorage_get(undef) called at src/Commands.pm line 4636
	Commands::cmdStorage('storage', 'get') called at src/Commands.pm line 303
	Commands::run('storage get') called at src/functions.pl line 998
	main::parseInput('storage get') called at src/functions.pl line 63
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x7bbad4c)') called at C:\Users\xxxxx\Desktop\openkore\openkore.pl line 97
	main::__start() called at C:\Users\xxxxx\Desktop\openkore\openkore.pl line 212
 at C:/Users/xxxxx/Desktop/openkore/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('') called at src/InventoryList.pm line 246
	InventoryList::getMultiple('InventoryList::Storage=HASH(0x9cf12cc)', undef) called at src/Commands.pm line 4719
	Commands::cmdStorage_get(undef) called at src/Commands.pm line 4636
	Commands::cmdStorage('storage', 'get') called at src/Commands.pm line 303
	Commands::run('storage get') called at src/functions.pl line 998
	main::parseInput('storage get') called at src/functions.pl line 63
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x7bbad4c)') called at C:\Users\xxxxx\Desktop\openkore\openkore.pl line 97
	main::__start() called at C:\Users\xxxxx\Desktop\openkore\openkore.pl line 212

**Comment by pussbacon** [comment]
is your openkore up to date? and what server

**Comment by alisonrag** [comment]
is the same of #913, kore need to check the input data before execute the command

**Comment by guilhermeferreira1** [comment]
@alisonrag Actually, the error is also generated when the "storage add" command is used without having the complete syntax.

@pussbacon The version is informed below the "Additional Details" error occurs on any server.

**Comment by alisonrag** [comment]
fixed
