### ISSUE TITLE
Unable to find recvpackets and servertype for version 56

### ISSUE THREAD

**Issue by acepartacus** [OpenKore/openkore#1031]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by acepartacus** [comment]
site is http://zirvro.com/

**Comment by Mortimal** [comment]
go to forums - Private servers, post there

**Comment by acepartacus** [comment]
@Mortimal i thought it's moving here in github?

**Comment by acepartacus** [comment]
Hi @sctnightcore may I ask for help on this one? thanks :) 

ip 116.251.223.136
port 56384
master_version 1
version 56
serverType kRO_RagexeRE_2015_12_02
serverEncoding Western
charBlockSize 144

Connecting to Account Server...
Connecting (116.251.223.136:56384)... connected
Disconnecting (116.251.223.136:56384)...disconnected
Connect failed, something is wrong with the login settings:
version: 56
master_version: 1
serverType: kRO_RagexeRE_2015_12_02
Relogging in 30 seconds...
Connecting to Account Server...
[reconnect] Login retry number 2, setting reconnect timeout to 64 seconds.
Connecting (116.251.223.136:56384)... connected
Disconnecting (116.251.223.136:56384)...disconnected
Connect failed, something is wrong with the login settings:
version: 56
master_version: 1
serverType: kRO_RagexeRE_2015_12_02
Relogging in 30 seconds...

**Comment by 10201244054** [comment]
@acepartacus can you set the debug to 2 in config.txt? and try paste the packet here

**Comment by sctnightcore** [comment]
client hash ?

**Comment by sctnightcore** [comment]
#1018

**Comment by sctnightcore** [comment]
@acepartacus  hello are you here ?

**Comment by acepartacus** [comment]
Hi @sctnightcore  ,

Sorry I just came back from a long vacation.

Btw where did you get the kRO_RagexeRE_2016_02_03, folder and the .pm file does not exist with the newly downloaded one from github.


Thanks!

**Comment by sctnightcore** [comment]
#1067

**Comment by sctnightcore** [comment]
@acepartacus  get it

**Comment by acepartacus** [comment]
@sctnightcore  upon testing 

here's what happen : 
![image](https://user-images.githubusercontent.com/29881490/30034358-64acd1c4-91d3-11e7-8508-6b0cbc324f40.png)

Then this is my servers.txt 
ip 116.251.223.136
port 56384
master_version 1
version 56
serverType kRO_RagexeRE_2016_02_03
serverEncoding Western
charBlockSize 147
addTableFolders kRO
clientHash 620912C50D6A4584362D59DAB1BFE0A4
sendCryptKeys 0x3E1411AF,0x7CFA1BDE ,0x6C744497

I added a RagexeRE_2016_02_03 in the send and receive
this is in the receive , I created a .pm file 

+package Network::Receive::kRO::RagexeRE_2016_02_03;
 +
 +use strict;
 +use base qw(Network::Receive::kRO::RagexeRE_2016_01_27);
 +
 +1;
 +=pod
 +0x0369 => actor_action
 +0x096A => actor_info_request
 +0x0811 => actor_look_at
 +0x0368 => actor_name_request
 +0x0202 => buy_bulk_buyer
 +0x0817 => buy_bulk_closeShop
 +0x0815 => buy_bulk_openShop
 +0x0360 => buy_bulk_request
 +0x0940 => character_move
 +0x0361 => friend_request
 +0x0872 => homunculus_command
 +0x0947 => item_drop
 +0x0835 => item_list_res
 +0x095A => item_take
 +0x0819 => map_login
 +0x093E => party_join_request_by_name
 +0x083C => skill_use
 +0x0438 => skill_use_location
 +0x095D => storage_item_add
 +0x0954 => storage_item_remove
 +0x0873 => storage_password
 +0x0437 => sync
 +
 +
 +
 +=cut

then in the send

+#########################################################################
 +#  OpenKore - Packet sending
 +#  This module contains functions for sending packets to the server.
 +#
 +#  This software is open source, licensed under the GNU General Public
 +#  License, version 2.
 +#  Basically, this means that you're allowed to modify and distribute
 +#  this software. However, if you distribute modified versions, you MUST
 +#  also distribute the source code.
 +#  See http://www.gnu.org/licenses/gpl.html for the full license.
 +########################################################################
 +
 +package Network::Send::kRO::RagexeRE_2016_02_03;
 +
 +use strict;
 +use base 'Network::Send::kRO::RagexeRE_2016_01_27';
 +
 +sub new {
 +	my ($class) = @_;
 +	my $self = $class->SUPER::new(@_);
 +	
 +	my %packets = (
 +		'0369' => ['actor_action', 'a4 C', [qw(targetID type)]],
 +		'096A' => ['actor_info_request', 'a4', [qw(ID)]],
 +		'0811' => ['actor_look_at', 'v C', [qw(head body)]],
 +		'0368' => ['actor_name_request', 'a4', [qw(ID)]],
 +		'0202' => ['buy_bulk_buyer', 'a4 a4 a*', [qw(buyerID buyingStoreID itemInfo)]], #Buying store
 +		'0817' => ['buy_bulk_closeShop'],			
 +		'0815' => ['buy_bulk_openShop', 'a4 c a*', [qw(limitZeny result itemInfo)]], #Selling store
 +		'0360' => ['buy_bulk_request', 'a4', [qw(ID)]], #6
 +		'0940' => ['character_move','a3', [qw(coords)]],
 +		'0361' => ['friend_request', 'a*', [qw(username)]],# len 26
 +		'0872' => ['homunculus_command', 'v C', [qw(commandType, commandID)]],
 +		'0947' => ['item_drop', 'v2', [qw(index amount)]],
 +		'0835' => ['item_list_res', 'v V2 a*', [qw(len type action itemInfo)]],
 +		'095A' => ['item_take', 'a4', [qw(ID)]],
 +		'0819' => ['map_login', 'a4 a4 a4 V C', [qw(accountID charID sessionID tick sex)]],
 +		'093E' => ['party_join_request_by_name', 'Z24', [qw(partyName)]],
 +		'083C' => ['skill_use', 'v2 a4', [qw(lv skillID targetID)]],
 +		'0438' => ['skill_use_location', 'v4', [qw(lv skillID x y)]],
 +		'095D' => ['storage_item_add', 'v V', [qw(index amount)]],
 +		'0954' => ['storage_item_remove', 'v V', [qw(index amount)]],
 +		'0873' => ['storage_password'],
 +		'0437' => ['sync', 'V', [qw(time)]],		
 +	);
 +	
 +	$self->{packet_list}{$_} = $packets{$_} for keys %packets;
 +	
 +	my %handlers = qw(
 +		actor_action 0369
 +		actor_info_request 096A
 +		actor_look_at 0811
 +		actor_name_request 0368
 +		buy_bulk_buyer 0202
 +		buy_bulk_closeShop 0817
 +		buy_bulk_openShop 0815
 +		buy_bulk_request 0360
 +		character_move 0940
 +		friend_request 0361
 +		homunculus_command 0872
 +		item_drop 0947
 +		item_list_res 0835
 +		item_take 095A
 +		map_login 0819
 +		party_join_request_by_name 093E
 +		skill_use 083C
 +		skill_use_location 0438
 +		storage_item_add 095D
 +		storage_item_remove 0954
 +		storage_password 0873
 +		sync 0437
 +	);
 +	
 +	while (my ($k, $v) = each %packets) { $handlers{$v->[0]} = $k}
 +	
 +	$self->{packet_lut}{$_} = $handlers{$_} for keys %handlers;
 +	
 +#	$self->cryptKeys(, , );
 +
 +
 +	return $self;
 +}
 +
 +1;

![image](https://user-images.githubusercontent.com/29881490/30034402-b1c13194-91d3-11e7-8ea0-99a2d4498cce.png)

updated the recvpackets from the pastebin https://pastebin.com/8ZUJ80Qa

**Comment by sctnightcore** [comment]
https://github.com/sctnightcore/openkore/tree/patch-17

**Comment by acepartacus** [comment]
![image](https://user-images.githubusercontent.com/29881490/30034659-59ac5414-91d5-11e7-91c9-f8be9a00957f.png)

![image](https://user-images.githubusercontent.com/29881490/30034677-81d7b4a6-91d5-11e7-9ca6-b994872e6b56.png)

same error, I downloaded from your link, then just changed the servers.txt, left all the others untouched

**Comment by acepartacus** [comment]
@sctnightcore

**Comment by sctnightcore** [comment]
error ?

**Comment by acepartacus** [comment]
@sctnightcore 

![image](https://user-images.githubusercontent.com/29881490/30034788-54f63308-91d6-11e7-8bd1-3c122bcfad9a.png)

**Comment by sctnightcore** [comment]
wait to fix it

**Comment by sctnightcore** [comment]
download new agin 
server.txt fix :  serverType kRO_RagexeRE_2016_02_03a

**Comment by acepartacus** [comment]
upon changing to 03a @sctnightcore  new error : 
![image](https://user-images.githubusercontent.com/29881490/30035070-ccc49b20-91d8-11e7-8c94-5049ab349573.png)

**Comment by sctnightcore** [comment]
wait dude

**Comment by acepartacus** [comment]
oki @sctnightcore ill just wait, just tell me if i need to download or change anything :)

**Comment by sctnightcore** [comment]
#1070
[zirvro.com]
ip 116.251.223.77
port 56384
master_version 1
version 56
serverType kRO_RagexeRE_2016_02_03a
serverEncoding Western
charBlockSize 147
addTableFolders kRO
clientHash 620912C50D6A4584362D59DAB1BFE0A4
sendCryptKeys 0x3E1411AF,0x7CFA1BDE ,0x6C744497

**Comment by sctnightcore** [comment]
#1070

**Comment by acepartacus** [comment]
@sctnightcore 

![image](https://user-images.githubusercontent.com/29881490/30036097-baf51460-91e2-11e7-988a-16202216c88c.png)

**Comment by acepartacus** [comment]
should i try to update the send and receive?

**Comment by sctnightcore** [comment]
@acepartacus  wait

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/30036222-5f1ad5a0-91db-11e7-8f27-52f06824bb08.png)
work ! 
https://pastebin.com/8ZUJ80Qa  = recvpackets

**Comment by acepartacus** [comment]
ok, should I download this https://github.com/sctnightcore/openkore/tree/patch-17

and then just update the servers.txt? or should I still update the recv packets?

**Comment by sctnightcore** [comment]
no download : https://github.com/sctnightcore/openkore/tree/patch-18

**Comment by acepartacus** [comment]
working now ! you da mvp!! @sctnightcore  

![image](https://user-images.githubusercontent.com/29881490/30036294-71a4be80-91e4-11e7-9c95-cac1ac11e5c4.png)

**Comment by acepartacus** [comment]
@sctnightcore  question, i extracted the maps and did the gat to fld conversion but this still happens in the gold room

![image](https://user-images.githubusercontent.com/29881490/30046763-b79e29a2-923f-11e7-9d0c-3977f1be0826.png)

**Comment by acepartacus** [comment]
it's ok now i removed the extracted gat to fld and let the default ones go 
![image](https://user-images.githubusercontent.com/29881490/30046847-35c5aabc-9240-11e7-9b92-73a1cf8e3eed.png)

**Comment by sctnightcore** [comment]
@acepartacus  table > portal
