### ISSUE TITLE
Ragnarok Re:Start Timeout on Account Server 8/30/17

### ISSUE THREAD

**Issue by sparda824** [OpenKore/openkore#1039]
Anyone knows a fix? Thanks

**Comment by alisonrag** [comment]
update to last version

**Comment by don00000** [comment]
How can i update it to last version?

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/archive/master.zip
please say if are working to you, so we can close this issue

**Comment by don00000** [comment]
Thanks! You da Real MVP alisonrag!!

**Comment by alisonrag** [comment]
thanks <3

**Comment by kapyogg1** [comment]
sorr to put some comment here bud sadly it is not working on me.. :(

**Comment by mhakulit** [comment]
supperrrrrr thanks master
