### ISSUE TITLE
Openkore has stop working ?

### ISSUE THREAD

**Issue by Junezavr** [OpenKore/openkore#1043]
Iro restart open wxstart.exe has stop working !!!!! I open bot 15-30 minute help me pls.

**Comment by Junezavr** [comment]
https://ibb.co/dhXbxQ

**Comment by sctnightcore** [comment]
download new openkore on github

**Comment by Junezavr** [comment]
Thx If not lost or I not use VPN  am Thai VPN about?

**Comment by sctnightcore** [comment]
TH:ลองโหลดตัวใหม่ครับ เเล้วเเค๊ปตรง ERROR หน้าการทำงานมาว่าเป็นตรงไหนจะได้ถูก
EN:Try loading again The screen capture ERROR page to work on exactly where it will be.

**Comment by Junezavr** [comment]
อ๋อครับ ถ้าไม่ได้เดียวถ่ายให้ครับ อาการตอนนี้คือ เปิดบอทได้ไม่นาน มันขึ้น has stop working เดวลองโหลดตัวใหม่ครัช

**Comment by Junezavr** [comment]
![has](https://user-images.githubusercontent.com/22251521/29952267-889c0516-8ef2-11e7-91c6-7eaec77a482b.jpg)

**Comment by sctnightcore** [comment]
TH:ลองใช้ START ไปก่อนครับ สาเหตุไม่รู้ด้วยสิ ลองปิดโปรเเกรมสเเกรนไวรัสดู

**Comment by Junezavr** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	wxstart.exe
  Application Version:	0.0.0.0
  Application Timestamp:	4c592cb9
  Fault Module Name:	wxmsw28u_core_gcc_wxp_binary_11_6.dll
  Fault Module Version:	2.8.11.0
  Fault Module Timestamp:	4cab55a0
  Exception Code:	c0000005
  Exception Offset:	000a4690
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1054
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by sctnightcore** [comment]
@allanon come here

**Comment by Junezavr** [comment]
![untitled](https://user-images.githubusercontent.com/22251521/29960196-d5db8342-8f24-11e7-9f8c-16922efd7f24.jpg)

**Comment by alisonrag** [comment]
its seem more windows problem than wxstart problem

**Comment by Junezavr** [comment]
I try another machine and it's about vpn

**Comment by Junezavr** [comment]
Is it possible that you do not use vpn
