### ISSUE TITLE
Justdance has created a new booking ( index : )

### ISSUE THREAD

**Issue by KingRagna** [OpenKore/openkore#1045]
Any one seeing these on all bot logs? 

Justdance has created a new booking ( index : )

Deleted reserved group index. 

Please help to clarify whether this is some sort of keyloggings or just ignorable message.

**Comment by alisonrag** [comment]
is just this:
http://irowiki.org/wiki/Party#Search_System

**Comment by KingRagna** [comment]
Thanks sir @alisonrag

**Comment by alisonrag** [comment]
u are welcome
