### ISSUE TITLE
Bots stuck in yuno unavailable area by warp trolls.

### ISSUE THREAD

**Issue by Dalamar6** [OpenKore/openkore#1046]
I have tried to correct this with a macro to use teleport to return; but it just tries and fails to route incessantly without even attempting to hit the teleport automacro.

Correct behavior would be the bot using teleport, fly wing, b wing, etc...and macro shouldn't be over ridden by bot-freezing failed routing.

Oddly though a quit macro did work recently, maybe the troll didn't use the unavailable area though I didn't look.

**Comment by SecretNinjaWarrior** [comment]
What is your macro?

**Comment by Dalamar6** [comment]
automacro avoidwarptroll {
location yuno
timeout 2
call avoidwarptroll_r
}

macro avoidwarptroll_r {
do autostorage
}

**Comment by SecretNinjaWarrior** [comment]
Do something like

automacro avoidwarptroll {
console /Cannot calculate route from yuno/
timeout 2
call avoidwarptroll_r
}

macro avoidwarptroll_r {
do tele 2
OR 
do is Butterfly Wing
release avoidwarptroll_r
}

This macro is not complete but the idea is there. Search in google or openkore forums on similar automacros like using Bwing when autostorage

However, when u run out of bwings and get stucked then u'll be fooked especially when u don't notice your bot getting stuck. A gm will ban you from there.

**Comment by lututui** [comment]
allowedMaps all,the,maps,your,bot,can,be
allowedMaps_reaction 0 #for respawning

**Comment by Dalamar6** [comment]
SNW's macro didn't work

**Comment by SecretNinjaWarrior** [comment]
```
####	AVOID YUNO	####
automacro AvoidYuno {
   console /Cannot calculate route from yuno/

   overrideAI 1
   run-once 1

   call  {
      do tele 2
      
      release AvoidYuno
   }
}
```
This is what I use. My bots are acolyte so I don't need bwings or fly wings.
Do note that I'm not a pro in botting. Just tryin to help
