### ISSUE TITLE
RE : start Dc after identify

### ISSUE THREAD

**Issue by OceanoPrimordial** [OpenKore/openkore#1050]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary:  
bot can not identify (use magnifier)
###### Impact:
I'm trying to use identify and everytime i got dc.
i'm doing by is number of item and then "identify" after that openkore disconect. Tried with macro and also failed. i'm using the latest version.
macro id {
$id = @inventory (Magnifier)
do is $id
pause 1
do identify 0
}

**Comment by c4c1n6kr3m1** [comment]
Update your bot, download all files from the latest

**Comment by alisonrag** [comment]
the same error are reported before
just dowmload the latest and clean version from here:
https://github.com/OpenKore/openkore/archive/master.zip

**Comment by OceanoPrimordial** [comment]
![identify](https://user-images.githubusercontent.com/15941534/29995645-b7c3d850-8fc4-11e7-9659-a2f09fe96852.jpg)
I downloades the newest openkore and instaled in a new folder. same problem

**Comment by denucles** [comment]
same here, they updated the anti-bot i think

**Comment by moneyisgod** [comment]
Is u playing in official or private servers ?

**Comment by alisonrag** [comment]
@moneyisgod iRO Restart, the same problem with rodex and identify was reported before

**Comment by c4c1n6kr3m1** [comment]
@OceanoPrimordial @denucles try the latest
if error still persist try mine https://github.com/c4c1n6kr3m1/openkore/commit/79aeb51fd49323c143e27c3d1260b8e2cf7aca95

**Comment by OceanoPrimordial** [comment]
@c4c1n6kr3m1 thx now is working.

**Comment by alisonrag** [comment]
@c4c1n6kr3m1 
could you make a pull request?

your code is the right way to do this

**Comment by alisonrag** [comment]
fixed in #1073
