### ISSUE TITLE
Openkore was closed after got "Can't use string (""spearman scroll 10" 0 0 0 ") as a HASH ref while "strict refs" in use at src/Log.pm line 254."

### ISSUE THREAD

**Issue by duoh** [OpenKore/openkore#1056]
Here is what written in error.log.
OpenKore version what-will-become-2.1
@ai_seq = macro
Network state = 5
Network handler = Network::DirectConnection
Revision: git:661bd41_2017-09-02 ctime:2017_09_01
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)

Error message:
Can't use string (""spearman scroll 10" 0 0 0
") as a HASH ref while "strict refs" in use at src/Log.pm line 254.

Stack trace:
Can't use string (""spearman scroll 10" 0 0 0
") as a HASH ref while "strict refs" in use at src/Log.pm line 254.
 at src/Misc.pm line 4552
	Misc::parseReload('all') called at src/Commands.pm line 4140
	Commands::cmdReload('reload', 'all') called at src/Commands.pm line 303
	Commands::run('reload all') called at plugins/macro/Macro/Utilities.pm line 463
	Macro::Utilities::processCmd('reload all') called at plugins/macro/Macro/Utilities.pm line 517
	Macro::Utilities::callMacro() called at plugins/macro/Macro/Automacro.pm line 815
	Macro::Automacro::automacroCheck('log', 'ARRAY(0x69a63c4)') called at plugins/macro/Macro/Automacro.pm line 620
	Macro::Automacro::consoleCheckWrapper('error', 'console', 0, 1, 'Cannot calculate a route from c_tower3 (57,175) to \x{a}', 'HASH(0x4ef713c)', 'AI::CoreLogic::__ANON__', 'Actor::processTask') called at src/Log.pm line 254
	Log::processMsg('error', 'Cannot calculate a route from c_tower3 (57,175) to \x{a}', undef, undef, undef, 'HASH(0x36a0c84)', 'HASH(0x36a0dc4)') called at src/Log.pm line 324
	Log::error('Cannot calculate a route from c_tower3 (57,175) to \x{a}') called at src/AI/CoreLogic.pm line 89
	AI::CoreLogic::__ANON__('Task::MapRoute=HASH(0x69870dc)', 'HASH(0x69b0dec)') called at src/Actor.pm line 833
	Actor::processTask('Actor::You=HASH(0x3cfb02c)', 'route', 'onError', 'CODE(0x44e4dfc)') called at src/AI/CoreLogic.pm line 93
	AI::CoreLogic::iterate() called at src/functions.pl line 770
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4231bd4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		next if (!defined($_));
* 		$_->{'func'}->($type, $domain, $level, $currentVerbosity, $message, $_->{'user_data'}, $near, $far);
  	}

**Comment by alisonrag** [comment]
are u using something with reload command?

**Comment by duoh** [comment]
yes I put it in automacro, here it is:
automacro reloadWhenStuck {
	console /Cannot calculate a route from/
	exclusive 1
	call {
		do reload all
	}
}

**Comment by Fruitard** [comment]
@duoh remove that and it wil work just fine, i encountered this problem awhile back also.

**Comment by duoh** [comment]
@Fruitard , thanks for your confirmation. It seems to work now.
I have changed reload all to relog instead to prevent stuck routing.
