### ISSUE TITLE
iRO Skills/Status

### ISSUE THREAD

**Issue by FireflySkye** [OpenKore/openkore#106]
AB_PRAEFATIO#PRAEFATIO# - all caps
AB_LAUDAAGNUS#Laudaagnus# - spacing #Lauda Agnus#
AB_LAUDARAMUS#Laudaramus# - spacing #Lauda Ramus#
AB_SECRAMENT#Secrament# - spelling #Sacrament#

GC_COUNTERSLASH#쒫Counter_Slash# - korean char

RA_DETONATOR#DETONATOR# - all caps
RA_CAMOUFLAGE#CAMOUFLAGE# - all caps

NC_ACCELERATION#cceleration# - missing letter #Acceleration#
NC_REPAIR#epair# missing letter #Repair#
NC_DISJOINT#FAW_divest# NC_DISJOINT#FAW_Divest# 

WA_SWING_DANCE#SWING_DANCE# - all caps

GN_CARTBOOST#Cart_Boost# - #Geneticist_Cart_Boost#
GN_MIX_COOKING#"Mixed_Cooking# - quotation mark #Mixed_Cooking#

statusnametable
missing
EFST_GN_CARTBOOST Geneticist Cart Boost
EFST_ON_PUSH_CART Cart
EFST_STOP Standby

EFST_CLAN_INFO Clan Info
EFST_SWORDCLAN Sword Clan
EFST_ARCWANDCLAN Arc Wand Clan
EFST_GOLDENMACECLAN Golden Mace Clan
EFST_CROSSBOWCLAN Crossbow Clan

**Comment by itsrachelfish** [comment]
Hey there, thanks for making this issue!

If you want to update any of the tables files, you can do so on github right in your browser. :heart: 

There's a little :pencil2: pencil icon when viewing any of the source files like: https://github.com/OpenKore/openkore/blob/master/tables/iRO/items.txt
Or: https://github.com/OpenKore/openkore/blob/master/tables/iRO/official/skillnametable.txt

When you click that, you can make changes for us to approve in a pull request. :smile:

**Comment by FireflySkye** [comment]
Oh. Okay. Thanks for the info. Lol, sorry I'm new here.
