### ISSUE TITLE
"any work in progress (NPC dialog, manufacturing...)quit and try again.# RE:Start Odin when using teleport (im using teleport belt)

### ISSUE THREAD

**Issue by black1e04** [OpenKore/openkore#1062]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
please use the template and fill with steps to reproduce, it will be better if you post a image with error

**Comment by lucasbradok** [comment]
just paste in your macros.txt
automacro fix_tele {
   console /any work in progress/
   timeout 5
   call {
      pause 1
      do warp cancel
      pause .2
      do ai on
      pause .2
      do reload config
      pause .2
      do reload macros
      release all
   }
}

**Comment by Dalamar6** [comment]
People need to stop regurgitating the one above...it's slow and gets you killed

automacro fix_tele {
console /any work/
timeout 1.5
call thefix
}

macro thefix {
pause .1
do warp cancel
pause .1
do ai on
pause .1
do reload macros
release all
}

you probably don't need the ai on or reload macros part either...

**Comment by ncplay91** [comment]
I looked at macros.txt files in Openkore folder.. and I found 4 of them..
which macro.txt should I put this script?

**Comment by fadreus** [comment]
Simply use this

```
automacro CancelTeleport {
console /any work in progress/
call {
do warp cancel
}
}
```

No need fancy stuff, no need release, no need timeout, no need ai.

**Comment by ncplay91** [comment]
@fadreus 

There's no macros.txt in control folder... so should I make one?

**Comment by fadreus** [comment]
@ncplay91 Read here http://openkore.com/index.php/Macro_plugin
