### ISSUE TITLE
Autostorage non saveable kafra problem

### ISSUE THREAD

**Issue by pussbacon** [OpenKore/openkore#1066]
Server: Re:Start
Problem: Autostorage to kafra without save option

storageAuto 1
storageAuto_npc izlu2dun 106 58
storageAuto_distance 5
storageAuto_npc_type 2
storageAuto_npc_steps c r0 n
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 50

my command

line that it showing
NPC image: kafra_02.bmp
Kafra Employee: [Kafra Employee]
Kafra Employee: Welcome. Kafra is always here to help you.
Kafra Employee: How can I help you?
------ Responses (Kafra Employee) ------
#  Response
0  Use Storage Service
1  Use Cart Service
2  Quit
3  Cancel Chat
----------------------------------------
Kafra Employee: [Kafra Employee]
Kafra Employee: I'm sorry.
Kafra Employee: Carts are only for Merchant class characters.
NPC Kafra Employee (0): Done talking
Done talking with NPC Kafra Employee (0).

**Comment by alisonrag** [comment]
the correct is:
`storageAuto_npc_type 3`

**Comment by pussbacon** [comment]
It worked. Do you mind telling me the types of npc type so I will be aware next time?

**Comment by alisonrag** [comment]
http://openkore.com/index.php/StorageAuto_npc_type
