### ISSUE TITLE
Can't connect to Openkore if my bot starts in Al De Baran

### ISSUE THREAD

**Issue by kidbreaker22** [OpenKore/openkore#1068]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary: 

My Openkore gives an error and won't connect when my bot it opens from Al De Baran, but it works when in other maps.

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Expected Behavior:

To successfully open Openkore

###### Actual Behavior:

Gives an error in error.txt and won't open it unless I clear out my macro.txt

[macros.txt](https://github.com/OpenKore/openkore/files/1274537/macros.txt)
[errors.txt](https://github.com/OpenKore/openkore/files/1274538/errors.txt)
![untitled](https://user-images.githubusercontent.com/31119522/30024678-e2cc3798-9142-11e7-988f-35e86e2830e6.png)

**Comment by alisonrag** [comment]
are u using any macro?

**Comment by c4c1n6kr3m1** [comment]
@kidbreaker22 can u try disabled automacro repair ?
or try add this line as condition
'''eval  $::char->inventory->size() > 0'''

**Comment by kidbreaker22** [comment]
@alisonrag yes my macro is in that macros.txt file on top of the picture

**Comment by kidbreaker22** [comment]
@c4c1n6kr3m1 I will try that later but I need my repair macro just in case my weapon breaks. Also can you explain that line for me with the eval? You think its my repair automacro is giving me problems here?

**Comment by kidbreaker22** [comment]
@c4c1n6kr3m1 adding the condition with the eval works! So it is my repair macro fault. But can you please still explain what does that mean so i can understand it better? 

Thank you very much :)

**Comment by alisonrag** [comment]
`eval $::char->inventory->size() > 0`
evaluation of value will test if size of inventory are bigger than 0
