### ISSUE TITLE
Temporary Solution: Cannot calculate a route

### ISSUE THREAD

**Issue by Yakbi** [OpenKore/openkore#1069]
Paste this in your macros.txt or make a notepad name it macros if you dont have one in your control folder.

automacro restart {
console /Cannot calculate a route/
call {
do relog 5
pause 1
do reload all
}
}

**Comment by pussbacon** [comment]
where do I paste this?

**Comment by lucasbradok** [comment]
@Yakbi i think its the better solution

automacro reload {
console /Cannot calculate a route/
timeout 60
call {
do reload 10
}
}

@pussbacon in your macros.txt inside the control folder.

**Comment by tronix04** [comment]
@lucasbradok 
how did you get macros.txt to work? i thought they replaced "macros.txt" with the new "eventMacros.txt" and console trigger is no longer working...

**Comment by tronix04** [comment]
oooooh! nvm still working...

**Comment by jholz27** [comment]
why my bot still said  Cannot calculate a route im @ izlude and planning to go @ pay_fild04

**Comment by Yakbi** [comment]
@jholz27 Use this instead. 100% Working!

> automacro restart {
console /Cannot calculate a route/
call {
do relog 5
pause 1
do reload all
}
}

**Comment by blakbord** [comment]
what did you guys do to trigger console? it gives me error..

**Comment by fadreus** [comment]
It's issue with portal and LOS, rather than reloading all, simply reload portal.

Example
```
automacro Route {
console /Cannot calculate a route/
call {
do relog 10
do reload portal
}
```

If we can't fix this, hoping there is perm solution like each time kore trying to calculate, it will reload portal without need to use macro or something.

**Comment by fadreus** [comment]
#1369

**Comment by blazasin** [comment]
Hi Guys , 

Found a fix to this problem(ofcourse the above macro also works) .

Server - IRO-RE

2 of my bots were running one was able to move fine do storage and sell stuffs and another was stuck moving from sell route to storage(may it be any other action as well) i tried to download the latest config file and manually configure the correct skills essential for the bot to perform also check the portals route and route weights to avoid unnecessary walking , auto storage and auto sell configs and it fixed the issue. It maybe that there are lot of unnecessary skills/un-used blocks which may cause this problem , am not sure , but the config change fixed my issue . Try doing it and let me know if any problems come up .

Happy botting :dancing_men:

**Comment by asiphm** [comment]
Hey guys. Sometimes my bot go to unthinkable place and remain in a state of "Cannot calculate route..." even with using this macro. So i made some addition : 

automacro Route {
console /Cannot calculate a route/
call {
$id = @inventory(Butterfly Wing)
       do is $id
       pause 1
do relog 10
do reload portal
}
}

This macro will use butterfly wings before reloading the portal just in case your bot is stuck somewhere even reloading doesn't help. If there's syntax error please correct me. still waiting for the macro to trigger.

**Comment by lututui** [comment]
Try #1621
