### ISSUE TITLE
Autostorage non stop loop between autobuy,autosell,autostorage

### ISSUE THREAD

**Issue by oleokoong** [OpenKore/openkore#1072]
###### Summary: 
Server IRO Restart
Autostorage non stop loop between autobuy,autosell,autostorage until zeny below requirement to open storage.

and i restart the start.exe, kore stop loop..but its doest check zeny,  and keep try to open kapra.
[npc] Kafra Employee: [Kafra Employee]
[npc] Kafra Employee: I'm afraid you do not have enough money.
[npc] Kafra Employee: Storage service costs 40 Zeny.
[npc] NPC Kafra Employee (2): Done talking
[ai_npcTalk] Done talking with NPC Kafra Employee (2).

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Steps to Reproduce:
use macro to overide config
tested with other town such as morooc, with same result
	do conf storageAuto 1
	do conf storageAuto_npc izlude 134 88
	do conf sellAuto 1
	do conf sellAuto_npc izlude_in 115 61

###### Summary:
i will check this issue time to time to provide more details.

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
continue in #1006
