### ISSUE TITLE
Please Help Me Sir

### ISSUE THREAD

**Issue by geedabalyuwayen** [OpenKore/openkore#1075]
\
![27780778-7dbd135c-5ffd-11e7-9a0c-671c945ccc82](https://user-images.githubusercontent.com/31650561/30054282-6ec56e98-91e0-11e7-8869-a436633c87f7.png)

please help sir.

Generating session Admin Password...

Checking for new portals... none found

Connecting to Account Server...
Connecting (202.57.117.44:6900)... couldn't connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (error code 10060)

**Comment by alisonrag** [comment]
pRO are not supported yet
