### ISSUE TITLE
Unable to find correct server settings, cause is probably dynamic ip?

### ISSUE THREAD

**Issue by acepartacus** [OpenKore/openkore#1078]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by acepartacus** [comment]
Hi @sctnightcore , do you think this one is accessible?

https://aerogaming.org/

turbo server,

I tried checking the server details via the clientinfo.xml and wireshark and unfortunately it seems to be not working not sure if it is caused by wrong server type

**Comment by alisonrag** [comment]
post your configuration

**Comment by acepartacus** [comment]
Hi @alisonrag 

[ae]
ip 184.105.208.11
port 6900
master_version 6
version 23
serverType 	kRO_Sakexe_2008_09_10a
serverEncoding Western
charBlockSize 147
addTableFolders translated/kRO_english;kRO


this is based from here : 

![image](https://user-images.githubusercontent.com/29881490/30084967-2a02c0a2-92c7-11e7-8032-7ed020bddb3d.png)
![image](https://user-images.githubusercontent.com/29881490/30084981-374eb996-92c7-11e7-8dc7-2f6313eb8f38.png)


Regards

**Comment by acepartacus** [comment]
I also found this clientinfo.xml in update.grf which contains this 

<balloon>aeRO Gaming Ragnarok Online</balloon>
    <address>aerogamer.dyndns.org</address>
    <port>4300</port>
    <version>23</version>
    <langtype>1</langtype>

**Comment by alisonrag** [comment]
you can fill the ip address with aerogamer.dyndns.org

**Comment by acepartacus** [comment]
![image](https://user-images.githubusercontent.com/29881490/30085371-a6fc895c-92c8-11e7-980c-2f646c937b16.png)

**Comment by acepartacus** [comment]
![image](https://user-images.githubusercontent.com/29881490/30085512-626e1912-92c9-11e7-94a4-4b29d95d361e.png)

**Comment by moneyisgod** [comment]
clientHash maybe is enabled, or secureLogin.

**Comment by acepartacus** [comment]
@sctnightcore  your thoughts on this one??

**Comment by sctnightcore** [comment]
well wait

**Comment by sctnightcore** [comment]
server use with harmony 
i'm sorry
You can sniff login packet send to server is bypass it

**Comment by acepartacus** [comment]
oh i see, so currently there's still no bypass to harmony? :( anyway thank you for your help guys! u still the mvp
