### ISSUE TITLE
Openkore gets stuck

### ISSUE THREAD

**Issue by septiis** [OpenKore/openkore#108]
Seems to hav a problem with my bot getting stuck inside buildings cant calculate a way out

**Comment by ChrstphrR** [comment]
You are going to have to give more detail to have anyone confirm this as an issue.

**Comment by septiis** [comment]
well I've set the bot to auto sell stuff at the trader in veins he finds the way in but not the way out've the map!

**Comment by mseifer** [comment]
Happens after bot sells, it gets stuck during route , happens whatever you have items for selling or not
![stuck](https://cloud.githubusercontent.com/assets/9919596/15988381/c46a647e-304e-11e6-9fb4-5b3f4b871989.JPG)

**Comment by ChrstphrR** [comment]
@septiis @mseifer neither of you have noted what server you're using, but mseifer's post made me remember something.

Can you both update and see if the issue is solved?  allanon noted a change on iRO, where he added a packet that terminates the sell sequence, like how fRO works.  Without it, openkore gets stuck after successfully selling, because iRO's servers are expecting one more message from the client side to say it's "done".

https://github.com/OpenKore/openkore/pull/105#issuecomment-224359727

**Comment by septiis** [comment]
im on iro

**Comment by mseifer** [comment]
sorry, forgot to say its IRO, will try to update later and say if it works, thanks alot!

**Comment by mseifer** [comment]
@ChrstphrR Downloaded the svn and it works correctly,  thanks a lot for your help!

**Comment by ChrstphrR** [comment]
@septis  Try updating to a more current release of the code here on Github, it sounds like your problem is like mseifer's.   If you're still having problems, we can dig deeper.

**Comment by septiis** [comment]
ive downloaded the latest files for openkore on here unless there is a even newer code somewhere?

**Comment by itsrachelfish** [comment]
@septiis You downloaded the .zip archive from here on GitHub? When?

Which server are you playing on? iRO renewal or classic? As @ChrstphrR pointed out, there is a new packet that needs to be sent on iRO after talking to an NPC, that might be your issue.

Can you give us more information, like which NPC you are talking to, what map you're on, and where you're trying to move to?

Thanks :)

**Comment by mseifer** [comment]
@septiis 
dont download it from openkore svn get it from github, it works

**Comment by septiis** [comment]
https://github.com/OpenKore/openkore that's where I downloaded it from!

**Comment by itsrachelfish** [comment]
This is fixed I guess? :sweat_smile:
