### ISSUE TITLE
So is XKore 1 still not working in Ragnarok: Restart?

### ISSUE THREAD

**Issue by Shougen** [OpenKore/openkore#1081]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Actual Behavior:
Game Stops responding right before the bot can program a random destination on the map you are currently in and the client stops as if you got disconnected from the client because of your internet connection
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
not yet, we have anther issue about this
