### ISSUE TITLE
disconnect after command refine #

### ISSUE THREAD

**Issue by MingFaiYau** [OpenKore/openkore#1082]
Hi all , 
i am useing opeknore in private server..and i want to write a macro for refine weapon,
After i use the skills weaponrefile and refine# 
it idle 2~3s and disconnect...

what can i do in this case?..
thanks a lot

**Comment by sctnightcore** [comment]
well = =

**Comment by c4c1n6kr3m1** [comment]
May be you need to sniff  the packet sent from client while refining

**Comment by fuuliem** [comment]
i have some problem here the picture

![eror refine](https://user-images.githubusercontent.com/31885948/30320934-71f9c8a8-97de-11e7-8770-69f86cb71673.JPG)

and my config l

> autoRefine Cutter [3] {
> 	refineStone Phracon
> 	refineNpc prt_in 63 60
> 	npcSequence c w1 r3 w1 c w1 r0 w1 c
> 	zenny 50
> 	maxRefine 7
> 	disabled 0
> }
>

**Comment by lututui** [comment]
servertype?

**Comment by fuuliem** [comment]
iRo: Restart @lututui

**Comment by alisonrag** [comment]
we have the same problem with rodex send, refine and previously with identify

**Comment by Ziomm** [comment]
I'm getting this error too, it crashes after it has to switch to the next equipment to upgrade.
Error: https://pastebin.com/iBQYBZpV
Image: https://i.imgur.com/Un5G0Xn.png

Anyone manage to solve this?
