### ISSUE TITLE
cannot connect to map 

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1083]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

## ------------------ Bug Report Template ------------------
![image](https://user-images.githubusercontent.com/23263315/30079142-6b67e356-92a9-11e7-833b-114af2fe2704.png)

**Comment by alisonrag** [comment]
please post wit 
debug 2
debug packet sent 1
debug packet receiced 1

**Comment by sctnightcore** [comment]
https://pastebin.com/h1qYJd27 @alisonrag

**Comment by alisonrag** [comment]
please can you post the server info and the respective network servertype that you are working?

**Comment by sctnightcore** [comment]
@alisonrag  i test my server 
![image](https://user-images.githubusercontent.com/23263315/30132219-de1fe83c-9379-11e7-9efe-edf78b964538.png)
servertybe2017 I'm testing it.
but i cannot connect to map
