### ISSUE TITLE
After Server maintenance of RO REstart Cannot Connect in map server :D

### ISSUE THREAD

**Issue by kenneth543** [OpenKore/openkore#1085]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
please dont make this section your personal forum
@allanon updated a few minutes ago, just redownload the openkore

**Comment by kapyogg1** [comment]
still can't connect after downloading latest openkore
