### ISSUE TITLE
SVN ERROR

### ISSUE THREAD

**Issue by geosper** [OpenKore/openkore#1086]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

## ------------------ Bug Report Template ------------------
ERROR MESSAGE:
OpenKore version what-will-become-2.1
@ai_seq = attack route
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2017_09_07
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)

Error message:
Illegal division by zero at src/Misc.pm line 4358.

Stack trace:
Illegal division by zero at src/Misc.pm line 4358.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x5df16ac)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		if ($config{$prefix . "_hp"} =~ /^(.*)\%$/) {
* 			return 0 unless (inRange(($monster->{hp} * 100 / $monster->{hp_max}), $1)); 
  		} else {

**Comment by JRdaud** [comment]
I have this same problem, too!

**Comment by lututui** [comment]
Which server?

**Comment by JRdaud** [comment]
Odin, but finally I realized after looking at src/misc.pm
The section line mentioned about checking monster condition, and for this case, obviously the target monster HP.
Therefore I just removed the number after **target_hp** (make sure KOre dont perform check on monster HP) on one of my attackskillslot that was previously using it, and voila my problem solved, altough its more like a workaround.

**Comment by alisonrag** [comment]
use #1300
