### ISSUE TITLE
Hi, i cant connect to my bot please help me

### ISSUE THREAD

**Issue by nestie23** [OpenKore/openkore#1088]
![image](https://user-images.githubusercontent.com/31718702/30145045-69b7889a-93c1-11e7-8625-5e71ff649355.png)

**Comment by nestie23** [comment]
i try, but my server is pRO loki, it cant connect, can you teach me as
well, Please

**Comment by nestie23** [comment]
please help me to config the pRO(loki) Please :(,

**Comment by imic23** [comment]
No working bot for PHRO has been released.

**Comment by nestie23** [comment]
ok thnx, please update me if already release, Thank You

**Comment by nestie23** [comment]
up
