### ISSUE TITLE
Disconnect after "rodex send"

### ISSUE THREAD

**Issue by VBPardini** [OpenKore/openkore#1090]
![xvdfbdfbdfb](https://user-images.githubusercontent.com/31735457/30168675-7e7363cc-93c0-11e7-8a13-d90dd21f1fa8.png)

I have tryied many forms in "rodex settitle" and "rodex setbody"

**Comment by sctnightcore** [comment]
server ?

**Comment by VBPardini** [comment]
Iro chaos (renewal)

**Comment by alisonrag** [comment]
is this issue a reality yet?

**Comment by mseifer** [comment]
This is still happening when connected with xkore2 I guess with xkore 3 the same happens

**Comment by sctnightcore** [comment]
@mseifer  open new issues with you problem

**Comment by CoffeeParser** [comment]
The same issue occured to me on the private server http://ggamerz-ro.com/
Here are the reproduction steps:
rodex open
rodex write mail CharacterName
rodex settarget CharacterName
rodex settitle hello my friend
rodex setbody this is the message
rodex add 10 1
rodex setzeny 120
rodex send -> **the disconnect happens here**

I would like to fix it on my own, can someone point me into a direction on how to debug the issue? I assume it has something to do with wrong packets.
