### ISSUE TITLE
Avoid GM on iRO Restart

### ISSUE THREAD

**Issue by Yakbi** [OpenKore/openkore#1091]
Paste this on avoid.txt 
(Extracted from Ragnarok Restart data.grf (clientinfo.xml) on September 8, 2017)

> 231656	1 0
1650302	1 0
1650315	1 0
1650298	1 0
1650304	1 0
1650317	1 0
4025205	1 0
4031694	1 0
4245510	1 0
4245514	1 0
3642489	1 0
4527144	1 0
4695803	1 0
1650290	1 0
1650306	1 0
1650319	1 0
1650300	1 0
1650309	1 0
1650320	1 0
4025207	1 0
4112623	1 0
4245511	1 0
4245515	1 0
4527131	1 0
4531823	1 0
4695802	1 0
1650292	1 0
1650310	1 0
1650330	1 0
1650303	1 0
1650312	1 0
527214	1 0
4025208	1 0
4245507	1 0
4245513	1 0
4245517	1 0
4527132	1 0
4695819	1 0
4695739	1 0
1650297	1 0
1650313	1 0
1650296	1 0
231656	1 0
1650314	1 0
527215	1 0
4025209	1 0
4245509	1 0
4245512	1 0
3642487	1 0
4527155	1 0
4695820	1 0
4695717	1 0

-------------------------------------------------------

In config.txt

> avoidGM_namePattern ^([a-z]?ro)?-?(Sub)?-?\[?GM\]?
avoidGM_near 2
avoidGM_near_inTown 1
avoidGM_talk 1
avoidGM_reconnect 1800
avoidGM_ignoreList

> avoidList 1
avoidList_inLockOnly 0
avoidList_reconnect 1800

**Comment by bebox123** [comment]
Well for me this is useless because the bot can't detect totally hidden GM characters.

**Comment by Yakbi** [comment]
Overall, there's no way to avoid a GM , but you can try to start a resistance kore.
By the way, what can you suggest mate? @bebox123

**Comment by bebox123** [comment]
I suggest put breaktime on it.

**Comment by lowkeeme** [comment]
I would just like to make sure @bebox123, are you referring to this:

autoBreakTime {
	startTime
	stopTime
}

Also, should I download the plugin or just set it on under that?

**Comment by alisonrag** [comment]
plase post this informations in:
http://forums.openkore.com
