### ISSUE TITLE
eventMacro error

### ISSUE THREAD

**Issue by blakbord** [OpenKore/openkore#1097]
I follow these instructions here
[http://openkore.com/index.php/EventMacro](url)
then it gives me fatal error

**Comment by blakbord** [comment]
here's what it says..
![untitled](https://user-images.githubusercontent.com/29995779/30209820-79bd501a-94cc-11e7-9601-9f6f10d0fd9d.png)

in my config.txt I added this
eventMacro_orphans reregister_safe
eventMacro_file eventMacros.txt
eventMacro_CheckOnAI auto

in my control folder I added eventMacros.txt

**Comment by lututui** [comment]
This is the manual for EventMacro: http://wiki.openkore.com/index.php/EventMacro
There's no condition called `pm`. You are looking for PrivMsg
