### ISSUE TITLE
fields storage format (.fld -> .fld.gz)

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#11]
OpenKore supports gzip-compressed field files (.fld.gz).I suggest fields file is stored in compressed form. Size OpenKore is reduced by 70 MB!

**Comment by itsrachelfish** [comment]
:+1:

**Comment by ya4ept** [comment]
I have the right to create a new branch?

**Comment by itsrachelfish** [comment]
@ya4ept I just added you as a member of the team, you'll need to check your email to accept

**Comment by ya4ept** [comment]
I have only read access to repositories "OpenKore / openkore"

**Comment by itsrachelfish** [comment]
Sorry about that! I've updated the permissions for the developers team and also moved you to the project leads team.

**Comment by windhamwong** [comment]
Can I join back to the team and have the permission as well pls?

**Comment by ya4ept** [comment]
I still do not have rights to the repository "OpenKore / openkore"
![img1](https://cloud.githubusercontent.com/assets/7117363/13443259/6f7fbe56-e011-11e5-9d87-296c3e08a0d7.JPG)

**Comment by itsrachelfish** [comment]
LOL dude I fixed it SORRY

please can you get on IRC

**Comment by itsrachelfish** [comment]
Resolved as of 8c912e89588f95a461e02c657df4b4366b98288f
