### ISSUE TITLE
How to get console message using eventMacro

### ISSUE THREAD

**Issue by drunkenhammer** [OpenKore/openkore#1100]
I tried reading the documentation but there are no things for eventmacro. macro has it but eventMacro doesn't what is the keyword condition for console /(insert test)/

**Comment by Henrybk** [comment]
There is none

**Comment by drunkenhammer** [comment]
Are there any alternates. I want to write a automacro for novice quest and i want to know if the bot dies because it deletes my eventmacro

**Comment by Nipodemos** [comment]
you can put an condition that he is 50% hp (when you dies as an novice you always start with 50% of hp)
and a condition that checks the position.
since it always revive at the same spot, you can use as an condition, like this:

```
automacro ifDieWhileLevelingto12 {
	CurrentHP >= 50%
	IsInCoordinate 95 21
	InMap new_1-3, new_2-3, new_3-3
	exclusive 1
	call {
	    do move &rand(103,105) &rand(36,38)
	    do talk &npc(/Trainer/) 
	    do talk resp 0
	    do talk resp /5/
    }
}
```

recommend check this coordinate, since this macro above was made for server bRO, it can be diffferent on your server

**Comment by drunkenhammer** [comment]
And also when the bot can't calculate a route to x or if the bot cant talk to npc

**Comment by alisonrag** [comment]
@Henrybk  
event macro work with hooks?
like old macro plugin?
`hook packet\vender_blbla`

**Comment by Nipodemos** [comment]
@alisonrag it has a condition SimpleHookEvent, but it dont save values like in the old macro plugin

**Comment by alisonrag** [comment]
in this case we can use hook when your character die

**Comment by c4c1n6kr3m1** [comment]
what about eval ?
does it have eval as a condotion ?

**Comment by Nipodemos** [comment]
You cannot use eval either

**Comment by alisonrag** [comment]
@drunkenhammer 
use:
`SimpleHookEvent self_died`
