### ISSUE TITLE
Timeout on Map Server Ragnarok Restart

### ISSUE THREAD

**Issue by deffyjam93** [OpenKore/openkore#1102]
I always get this when log in 30 secs in i don't know how to fix it kinda new to OpenKore. I have the latest version

![newtothis](https://user-images.githubusercontent.com/31779811/30230582-e99008be-94b4-11e7-8355-251b92f3bb82.PNG)

**Comment by sctnightcore** [comment]
xkore 1 ? or 3 ?

**Comment by deffyjam93** [comment]
xkore 1

**Comment by sctnightcore** [comment]
@deffyjam93  now xkore0 is work ! try

**Comment by deffyjam93** [comment]
just put xkore to 0?

**Comment by sctnightcore** [comment]
yep

**Comment by deffyjam93** [comment]
@sctnightcore 
![newtothis](https://user-images.githubusercontent.com/31779811/30233060-316ffec6-94c1-11e7-8810-4745f4929052.PNG)

**Comment by sctnightcore** [comment]
![capture](https://user-images.githubusercontent.com/23263315/30233303-dadcd4ea-951e-11e7-808e-5e59a2fed89c.PNG)
@deffyjam93 
`XKore 0`

**Comment by deffyjam93** [comment]
@sctnightcore maybe my IP is wrong?

**Comment by sctnightcore** [comment]
ip wrong !
download new openkore Again

**Comment by deffyjam93** [comment]
@sctnightcore yep, now its working thank you very much =D
