### ISSUE TITLE
Can Some one hep me

### ISSUE THREAD

**Issue by Jeffgomz** [OpenKore/openkore#1104]
Hi can someone help me in bot, if its possible that the bot can use skill hide if  the status blind active? then continue attack if the blind gone.. please help , my bot always die if its blind..

**Comment by Nipodemos** [comment]
http://openkore.com/index.php/UseSelf_skill

and you put whenStatusActive EFST_HEALTHSTATE_BLIND

**Comment by alisonrag** [comment]
please read the documentation as @Nipodemos sayd
in openkore/tables folder you can search for status
