### ISSUE TITLE
IRO Restart new_2-1 werp point change NPC 

### ISSUE THREAD

**Issue by kou90258** [OpenKore/openkore#1105]
###### Additional Details:
IRO Restart new_2-1 werp point change NPC 

new_2-1 npc talk list
Hold it there! I have a message that I will only display this one time after you answer some questions correctly.
Information about the GM team!

1.The ONLY way to become a GM is to be hired by our California Office.We do not recruit players to be GMs!
2.The GM team will NEVER ask for your password!
3.If someone demands a ransom to keep your acconut in good standing they aer not member ofthe GM tame.
DO NOT PAY THEM! The GM team will never ask you to contact them outside the ticket system.
If they are demanding via instsnt media ignore them!

4.The GM team will NEVER ask you to install and use Teamviewer!
5.You will always be able to see a GM team member in a chat room if they are there.
They have no special way to be invisible!

6.The GM team will always be willing to show the GM sprite. If they refuse they can be ignored.

Questionaire #1
Does the GM team recruit players to be GMs?
yes 
no r1

Questionaire #2
Will the GM team ask you for password??
yes 
no r1

Questionaire #3
will the gm team demand cash from you,in game or via instant messsgers or social media?
no r0
yes

Questionaire #4 
Should you install Teamviewer because a GM asks you to?
no r0
yes

Questionaire #5
Can a GM team member be invisible in a cht room?
Maybe 
NO r1
Yes 

Questionaire #6
Can you ask to see the GM sprite in order to verify a GM's identity?
NO
Yes r1

next talk werp map

**Comment by kou90258** [comment]
macro code 
automacro Sprakki_talk {
location new_2-1 52 111
run-once 1
timeout 30 
call {
do move new_2-1 145 112
}
}

automacro Gramps_talk {
location new_2-1 145 112
run-once 1
timeout 30 
call {
do talknpc 148 112 c c c c c c c c c r1 c c r1 c c r0 c c r0 c c r1 c c r1 c c n
do talknpc 148 112 c n
}
}


automacro Sprakki_2-2_talk {
location new_2-2 100 9
run-once 1
timeout 30 
call {
do move new_2-2 100 25
do talknpc 100 29 c c c c c n
do talknpc 100 29 c c r0 c c n
}
}

automacro Brabe_2-2talk {
location new_1-2 100 100
run-once 1
timeout 30 
call {
do talknpc 100 105 c c c c c c c c c c c c c n
do eq 1
do eq 2
do eq 3
do eq 4
do eq 5
do eq 6
do eq 7
do talknpc 100 105 c c c c c c c c c c c n
do move new_1-2 111 113

}
}

automacro Jinha_2-2talk {
location new_2-2 111 113
run-once 1
timeout 30 
call {
do talknpc 115 120 c r0 c c c 
do talknpc 115 120 c r1
do talknpc 100 105 c c c c 
do talknpc 100 105 c r1
}
}

automacro Chocolat_2-2talk {
location new_2-2 41 172
run-once 1
timeout 30 
call {
do talknpc 33 172 c c c n
do talknpc 30 176 c c c c c c c c c c c c c c c r4 n
do talknpc 33 176 c c c c c n
do talknpc 36 176 c c n
do conf attackAuto 1
do talknpc 33 172 c c c c c n

}
}

automacro Brabe_2-3talk {
location new_1-3 96 20
run-once 1
timeout 30 
call {
do talknpc 96 30 c c c c c n
do conf attackAuto 2
}
}

**Comment by alisonrag** [comment]
this is not a issue, please use forum for this problem
