### ISSUE TITLE
cannot calculate a route bot

### ISSUE THREAD

**Issue by jholz27** [OpenKore/openkore#1106]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

## ------------------ Bug Report Template ------------------
RAGNAROK SERVER: iRO RESTART

I am Trying to bot my Lvl 21 Thief at Pay_fild04 my savemap is Izlude.
after running my bot the bot said " cannot calculate a route from izlude "
I dont know what to do after please help me with my problem thanks!

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/archive/master.zip

**Comment by jholz27** [comment]
thanks!

**Comment by joecabezas** [comment]
please somebody with permissions close this
