### ISSUE TITLE
Timeout on Map Server Ragnarok Restart. Again.

### ISSUE THREAD

**Issue by 2326555** [OpenKore/openkore#1107]
When i start openkore i see this message:

```
Closing connection to Character Server
Disconnecting (128.241.92.138:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.135:4500)... connected
Timeout on Map Server, connecting to Account Server...
Connecting to Account Server...
Connecting (128.241.92.138:4500)... connected
Timeout on Account Server, reconnecting. Wait 30 seconds...
```

**My actions:**

1.  **Download latest version** from this https://github.com/OpenKore/openkore/archive/master.zip
or this https://github.com/OpenKore/openkore
2.  **Add server with new IP:**
```
[iRO Restart]
ip 128.241.92.133
port 6800
master_version 1
version 18
serverType iRO_Classic
serverEncoding Western
addTableFolders iRO/Classic;iRO
charBlockSize 145
```
3. **Set Xkore to 0**
```
XKore 0
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe
```
4. **Read GitHub** and try all the solutions that I found for this problem.
5. **Read forums** openkore.com and try all the solutions that I found for this problem.

Probably, i`m so stupid for this.

Please, can you tell me what i must do with this problem?

Thank you!

P.S. Sorry for my english.

**Comment by sctnightcore** [comment]
download new openkore !

**Comment by 2326555** [comment]
@sctnightcore , i download openkore few minutes ago. I type links when i get new version.
https://github.com/OpenKore/openkore/archive/master.zip
https://github.com/OpenKore/openkore

Maybe exist different new version from other places? (No sarcasm)

**Comment by sctnightcore** [comment]
@allanon  @alisonrag

**Comment by 2326555** [comment]
It`s work! Thank you!

**Comment by weed0403** [comment]
wxstart works for me. but how come it doesn't use potion to his/herself.

**Comment by 013631** [comment]
Help IDK what i can do, i update all up said, idk waht happen now

![image](https://user-images.githubusercontent.com/37887901/38065706-e1b6868a-32c1-11e8-8a92-1762d0efc7bc.png)
