### ISSUE TITLE
Is there a way to bypass Harmony?

### ISSUE THREAD

**Issue by acepartacus** [OpenKore/openkore#1108]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by Mortimal** [comment]
Maybe...

**Comment by Nipodemos** [comment]
every security system in this world have a breach
you just have to found out that breach and use it 😄

**Comment by sctnightcore** [comment]
sniff idloginpacket  > send to server > XD

**Comment by alisonrag** [comment]
officially we don't have a way, but if you search on internet maybe someone is selling the solution
