### ISSUE TITLE
Use teleport props or teleport skills problems

### ISSUE THREAD

**Issue by kou90258** [OpenKore/openkore#1112]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary: 
Use https://github.com/OpenKore/openkore  Ver. 2017/09/10

config.txt
teleportAuto_useSkill 0
teleportAuto_useItemForRespawn 1
teleportAuto_item1 Novice_Fly_Wing

When the props do not have teleportAuto_item1 Novice_Fly_Wing the specified items, and the role of skills in teleport or can use teleport equipment, then openkore will automatically switch to skills, there warp list and teleport but did not warp list closed. At this time there will be Any work in progress (NPC dialog, manufacturing ...) quit and try again.

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

See to https://github.com/OpenKore/openkore/blob/master/src/Network/Send/ServerType0.pm line 1113.

@sub sendWarpTele
	debug "Sent ". ($skillID == 26 ? "Teleport" : "Open Warp") . "\n", "sendPacket", 2

and 
https://github.com/OpenKore/openkore/blob/master/src/Commands.pm line 5533.
@sub cmdWarp {

} elsif ($map eq 'cancel') {
		message T("Attempting to cancel the warp portal\n"), 'info';
		$messageSender->sendWarpTele(27, 'cancel');

###### Impact:
unknown

###### Expected Behavior:
unknown

###### Actual Behavior:
1.Any work in progress (NPC dialog, manufacturing ...) quit and try again.
2.stuck

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:

**Comment by Mortimal** [comment]
Can u try

```
teleportAuto_useSkill 0
teleportAuto_useItemForRespawn 0
teleportAuto_item1 Novice Fly Wing
```

if not check **items.txt** for **12323#Novice_Fly_Wing#**
is it there?

if yes try without **teleportAuto_item1 Novice Fly Wing** kore must do it automatically
