### ISSUE TITLE
Quest List Bug?

### ISSUE THREAD

**Issue by kidbreaker22** [OpenKore/openkore#1114]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary: 
My quest status is incomplete according to my bot but I finished the quest already and I think when you type in quest list in console command, it shows a little bug.

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Expected Behavior:
&questStatus(7122) should be complete

###### Actual Behavior:
&questStatus(7122) is incomplete and there is an extra 0/1 in the quest list

###### Steps to Reproduce:

![untitled](https://user-images.githubusercontent.com/31119522/30252966-ac27624c-9649-11e7-8e90-75da6493a4da.png)
My quest list is Poring Quest where you kill it one time and I did, but it says the quest is still incomplete.

automacro PoringQuestKill {
	QuestActive 7122
	MobNear /Poring/i
	exclusive 1
	call {
		log &questStatus(7122)
		do a $.MobNearLastBinId  if (&questStatus(7122) == incomplete)
		if (&questStatus(7122) == complete) {
			do ai manual
			do move 96 28
			do talknpc 96 30 c c c c c c c n 
			do move 102 37 
			do talknpc 97 41 c r2 c c c n 
			pause 0.5
			do talknpc 101 41 c r2 c c n 
			pause 0.5
			do talknpc 105 41 c r2 c c n 
			pause 0.5
			do talknpc 105 41 c c r0 c c c c c r0 c c n 
			pause 0.5
			do eq Novice Adventurer's Suit [1]
			do eq Novice Cutter [3]
			do eq Thief Manual
			do mconf Poring 0 0 0
			do mconf Lunatic 1 0 1
			do mconf Picky 1 0 1
			do mconf Willow 1 0 1
			do ai auto
		}
	}
}

**Comment by Mortimal** [comment]
is it private or iro?

**Comment by c4c1n6kr3m1** [comment]
Try read issue #605

**Comment by kidbreaker22** [comment]
@Mortimal its iro Restart

**Comment by kidbreaker22** [comment]
@c4c1n6kr3m1 someome said that method no longer works, so had to do QuestHuntOngoing and other conditions from eventmacro. But when i do use it from eventmacro the quest list shows me this instead of just Poring 1/1. I fixed it by relogging it but i feel like it is a bug.

**Comment by c4c1n6kr3m1** [comment]
If you read that issue , the problem is iro re have new packet  with different structure
I never try eventmacro but i try to check what u said and i did not found this packet on eventmacro source, so it is not recognized ,atm
Whoever said to you, may be he did say for other server, not iro re
But as allanon said it is not impossible to drive new packet to old style quest
so if you can repair the logic on bot source code than you can use it

**Comment by c4c1n6kr3m1** [comment]
@kidbreaker22 you can test this file
it will show you the quest properly
https://github.com/c4c1n6kr3m1/openkore/commit/30536736d3b4a5ed177cfc9533ac54f2aa581a57

**Comment by lututui** [comment]
@kidbreaker22 please try #1276

**Comment by alisonrag** [comment]
UPDATED IN #1276
