### ISSUE TITLE
PartyAutoShare error

### ISSUE THREAD

**Issue by LynxDrain** [OpenKore/openkore#1116]
When Set to PartyAutoShare 1 or 2 the console keep spamming party config
![untitled](https://user-images.githubusercontent.com/31833442/30254607-6e35e734-96c5-11e7-96f3-697abaa4df7d.jpg)

**Comment by SecretNinjaWarrior** [comment]
The party share, it's a boolean..... is it not 0 or 1 only?

**Comment by LynxDrain** [comment]
yea when it set to 0 its okay but my party setup not even share,, when set to 1,, its error like in the picture,,
i try with 1 and 2 and have same issue

**Comment by Mortimal** [comment]
what ai_partyShareCheck in timeouts.txt? it must be 60

**Comment by c4c1n6kr3m1** [comment]
Party share limit is 15 level difference

**Comment by LynxDrain** [comment]
Its my aco lv 7 and my merchant lv 8
Yea its iro server.. im not sure about timout.txt coz i didnt change anything in there.  i haven't check it..i'm not in front of my pc now.. but i'll check it later.. 
Thanks for reply i will try later

**Comment by c4c1n6kr3m1** [comment]
Update your bot

**Comment by alisonrag** [comment]
plase use the latest version of openkore, and dont use custom timeouts.txt

https://github.com/OpenKore/openkore/archive/master.zip
