### ISSUE TITLE
Console condition in eventMacro?

### ISSUE THREAD

**Issue by joecabezas** [OpenKore/openkore#1117]
Hello community, maybe I am missing something, but how can I trigger an automacro in eventMacro plugin that triggers with console text as condition?

in macro plugin, you can use `console <text>`[1] as an automacro condition, why this is not the case in eventMacro?

[1] http://openkore.com/index.php/Macro_plugin#Conditions_2

**Comment by alisonrag** [comment]
eventmacro does not have this condition. 
be more specific and we can hel you with another alternative

**Comment by joecabezas** [comment]
thanks, being more specific, here is what I am want to port to autoMacro:

```
automacro auto_lex_aeterna {
    console /Player (.*) \((\d+)\) is casting (.*) on Monster (.*) \((\d+)\).*/i
    call {
        do sm "Lex Aeterna" $.lastMatch5
    }
}
```

there is an alternative for this in autoMacro?

**Comment by Mortimal** [comment]
You can do it with my update #1118

```
automacro auto_lex_aeterna {
    SimpleHookEvent is_casting
    call {
        do sm "Lex Aeterna" $.SimpleHookEventLastTargetID
    }
}
```

**Comment by joecabezas** [comment]
thanks!, I am going to try it

is there a way to specify in the arguments of kore, the eventMacros file? like:

kore.exe --event_macros=path

or at least a way to specify other file than eventMacros file in the config.txt?

**Comment by lututui** [comment]
I don't know if you can (I think you can) specify another file,  but you can !include any file you want from eventMacros.txt

http://openkore.com/index.php/!include

I'm closing this as the main issue was solved
