### ISSUE TITLE
Can't open Ragnarok with Openkore sametime?

### ISSUE THREAD

**Issue by xStryker1Zz** [OpenKore/openkore#1120]
Hi everyone.
When i need to open Ragnarok server with Openkore on iRO i cant login because says im already logged on Openkore so how can i playing the server while openkore is working?

**Comment by xStryker1Zz** [comment]
Hi everyone.
When i need to open Ragnarok server with Openkore on iRO i cant login because says im already logged on Openkore so how can i playing the server while openkore is working?

**Comment by sctnightcore** [comment]
x0 is work !

**Comment by Nipodemos** [comment]
you are trying to log at the same account in openkore and ragnarok at the same time?

**Comment by lututui** [comment]
You can't have two or more clients on the same account at once
