### ISSUE TITLE
[EventMacro.pl] Problem with ( ) in conditions

### ISSUE THREAD

**Issue by Mortimal** [OpenKore/openkore#1123]
###### Summary:
When there is  ( ) inside any condition as part of a string if statement works incorrect

###### Affected configuration(s)/ file(s):
Runner.pm -> sub parse_and_check_condition_text (and subs it is calling) -> line 1212
###### Impact:
Getting error in comparison statements
###### Expected Behavior:.
Condition must be met
###### Actual Behavior:
Condition not met
###### Steps to Reproduce:
```
macro testme{
  $va1 = isatext
  log $va1
  $va2 = (isatext)
  log $va2
  if ($va1 == "isatext") {
   log correct
  }
  if ($va2 == "(isatext)") {
   log error here
  }
}
```

###### Summary:
Need to be rewritten all logic of conditions parsing
###### Affected configuration(s)/ file(s):
Runner.pm -> sub parse_and_check_condition_text (and subs it is calling) -> line 1212
###### Benefits:
1 You fix this...
2 Bug disappear...
3 .........
4 Profit!

**Comment by Nipodemos** [comment]
#2368 fixed this issue.
