### ISSUE TITLE
Can't talk to NPC in Priest Job Change Map 

### ISSUE THREAD

**Issue by kidbreaker22** [OpenKore/openkore#1126]
Basically trying to make a macro for priest job change in iRO:ReStart but I can't talk to NPC "Peter S. Alberto" for both positions. Is this a bug because of this I can't make a macro for priest job change.

![untitled](https://user-images.githubusercontent.com/31119522/30406477-f7d53b24-98bf-11e7-9957-885505a5aa8c.png)

**Comment by xxchuckzxc** [comment]
how come your openkore is working mine is not :( is there any update?  thanks

**Comment by holoc** [comment]
@kidbreaker22 You also included your character's name in a public forum...

**Comment by kidbreaker22** [comment]
@xxchuckzxc there is already an update check in commits

**Comment by kidbreaker22** [comment]
@holoc lol i forgot about it dont really mind getting banned its just a dummy account

**Comment by Nipodemos** [comment]
show us your macro

**Comment by kidbreaker22** [comment]
@Nipodemos well my macro isn't the problem here. The problem is that I can't talk to the NPC with or without my macro it gives me this error.

**Comment by Nipodemos** [comment]
its a hidden npc? its an invisible npc? 

this erros happen when the first talk command doesn't work , and the rest is spammed
so , when you click on the npc, which error is showing??

**Comment by kidbreaker22** [comment]
@Nipodemos Not hidden nor invisible NPC, in game the NPC is in position 24 187.

The error is basically what it says on command but yeah spammed.
"Error in function 'talk' (Talk to NPC)
You are already talking with an npc"

I'm pretty sure my character is not talking to any NPC before I tried talking to this NPC "Peter S. Alberto"

**Comment by don00000** [comment]
Where is the update? I downloaded the new Openkore but Its not working.

**Comment by kidbreaker22** [comment]
@don00000 in tables/iRo and tables/servers.txt basically just change those two

**Comment by don00000** [comment]
@kidbreaker22 what should i put? can you post it here please

**Comment by kidbreaker22** [comment]
@don00000 just copy and paste those two from the downloaded openkore to your original openkore

**Comment by don00000** [comment]
@kidbreaker22 aight thanks man!

**Comment by kidbreaker22** [comment]
@don00000 no problem anytime!

**Comment by SecretNinjaWarrior** [comment]
![priest job change ques](https://user-images.githubusercontent.com/30432735/30411056-4a29daa2-9941-11e7-982e-5a5f87f1de78.jpg)
This is the problem.

**Comment by SecretNinjaWarrior** [comment]
"In this room, you must wait for one minute until you can speak to Peter S. Alberto. This is not a bug but instead part of the quest"

**Comment by SecretNinjaWarrior** [comment]
PRIEST JOB CHANGE QUEST:
"In this room, you must wait for one minute until you can speak to Peter S. Alberto. This is not a bug but instead part of the quest"
Source: http://irowiki.org/wiki/Priest_Job_Change_Guide

You're welcome. I hope we continue to help each other in github community

**Comment by kidbreaker22** [comment]
@SecretNinjaWarrior i know we have to wait for a minute before i can do anything. I waited for a long time and if you look at the console i did do "move 23 185". The fact that my character moved means that im done waiting for that one minute. Now the next step is to talk to the NPC if im playing in RO client but when i tried with openkore it gives me this error.

**Comment by SecretNinjaWarrior** [comment]
I see. You should post your macro then if the problem isn't the 1 minute wait time.

**Comment by Nipodemos** [comment]
i also think you should post your macro here

**Comment by Nipodemos** [comment]
at least the automacro that handle this specific part

**Comment by c4c1n6kr3m1** [comment]
Just wait 45 seconds
Seems they forgot to put talk close? so u need to wait after map changed

**Comment by kidbreaker22** [comment]
automacro PriestJobChange {
	JobLevel = 50
	exclusive 1
	run-once 1
	call {
		if ($.job == Acolyte) {
			do ai manual
			do tele 2
			pause 2
			do move prt_church 16 37
			#do talknpc 16 41 c r0 c c c c r0 c c c c c c c c c r0 c 
			do talknpc 16 41 c r0 c
			pause 70
			do move 23 185
			do talknpc job_prist 24 187 c c c c r0 c c c c c c r0 c n c n 
			do move job_prist 24 53
			do a 0
			pause 5
			do a 1
			pause 5
			do a 2 
			pause 5
			do move 24 62
			do a 0
			pause 5
			do a 1
			pause 5
			do move 25 72
			do a 0
			pause 5
			do a 1
			pause 5
			do a 2 
			pause 5
			do move 23 81
			do a 0
			pause 5
			do a 1
			pause 5
			do move 23 90
			do a 0
			pause 5
			do a 1
			pause 5
			do a 2 
			pause 5
			do move 168 44
			do talknpc 168 45 c c c c c r1 n 
			do move 168 79
			do talknpc 168 80 c c c r1 c c r1 c n 
			do move 168 113
			do talknpc 168 114 c c c r1 c c r1 c n 
			do move 168 149
			do talknpc 168 150 c c c c c c c c r1 c n 
			do move 98 105
			do ai auto
		}
	}
}

**Comment by Nipodemos** [comment]
`do talknpc job_prist 24 187 c c c c r0 c c c c c c r0 c n c n #here is where it gets error#`

Wrong
you don't put the npc name, you just put the coordinates
like this:
`do talknpc 24 187 c c c c r0 c c c c c c r0 c c `
 
and you dont need the 'n' in the end

and have two 'n' s !!!! also wrong

**Comment by kidbreaker22** [comment]
@Nipodemos okay i see now it works, i dont know why it didnt work when i tried talking to the npc manually through wxstart in the picture without my macro.

Also i put 'n' cause it says 'n' is when you want to press close button while talking to the npc so i put 'n'. also i have two 'n' because after the first close button, a conversation pops up already so i added 'c n' after the first 'n'
