### ISSUE TITLE
Help identifying inventory index for RODEX add command

### ISSUE THREAD

**Issue by Kraigen** [OpenKore/openkore#1127]
Would appreciate any help. What I'm trying to do is if I immediately loot a bow, the automacro triggers and opens mail and sends it over to my Smith to upgrade. Overall it's working fine aside from the fact that in order to use "rodex add" command correctly, it has the be the inventory index number. Which means I can't specifically add just "Composite Bow [4]. Now if I add for example do rodex add 8, it's possible that it sends a different item instead of the bow. How can I get it to input the number in which the bow is at once I pick it up?

```
automacro MailBow {
      inventory "Composite Bow [4]" >= 1
      call {
      do rodex open
      do rodex write name
      do rodex settarget name
      do rodex settitle abcdefg
      do rodex setbody abcdefg
      do rodex add ###Composite Bow [4] has to be indexed number in inventory (i) command###
      do rodex send
      do reload macros.txt
      }
      run-once 1
}

```

**Comment by Kraigen** [comment]
Nevermind, figured it out. Just used $list

**Comment by Nipodemos** [comment]
`use @inventory(Composite Bow [4])`

like this:
```
automacro MailBow {
      inventory "Composite Bow [4]" >= 1
      call {
      do rodex open
      do rodex write name
      do rodex settarget name
      do rodex settitle abcdefg
      do rodex setbody abcdefg
      do rodex add @inventory(Composite Bow [4]) 
      do rodex send
      do reload macros.txt
      }
      run-once 1
}


this command gets the current index of the item

**Comment by Kraigen** [comment]
Hi @Nipodemos. Thanks for the answer. I wasn't able to add the code in to my previous comment. I forgot to mention that I've used 

$list = @inventory(Composite Bow [4])
do rodex add $list

and only 

@inventory(Composite Bow [4]) to show like your code above.

Like my previous comment states, it does say it attaches. But it doesn't actually "send" the item. It stays in my inventory, my Smith gets an empty mail and it keeps looping back since it sees I still have the bow with me.

Adding amount  of item Composite Bow [4] (10) to rodex mail.
Sending rodex mail.
You lost 2,500 zeny.
