### ISSUE TITLE
well looks like bot killer strikes 

### ISSUE THREAD

**Issue by droneronin** [OpenKore/openkore#1129]
so i signed out for maint now i come back to set up a farm while i go out

Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 95 29 04 00 (272789)
MAP Name: iz_dun02.gat
MAP IP: 128.241.92.135
MAP Port: 4505
-----------------------------
Closing connection to Character Server
Disconnecting (128.241.92.138:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.135:4505)... connected
Timeout on Map Server, connecting to Account Server...

so this is restart and i know they are aggressively trying to anti-bot so its not a surprise 
but my productivity, any fixes would be appreciated

**Comment by LordEdward** [comment]
Just download the new openkore.

**Comment by drunkenhammer** [comment]
have you updated the openkore. every server maintence changes some of the files

**Comment by alisonrag** [comment]
just update your openkore
