### ISSUE TITLE
Multiple event macro files

### ISSUE THREAD

**Issue by drunkenhammer** [OpenKore/openkore#1130]
is there anyway to load more than 1 eventmacro, the one big macro file is so large that i can't find certain functions on my notepad anymore. Any way to do so.

Also: is there any way that if a bot gets teleported by gm or portal how can i disarm my bot (don't attack, chat then disconnect). my bots got banned because the gm did tp test and got sent to sec_pri

**Comment by Mortimal** [comment]
!include ?

**Comment by lututui** [comment]
EventMacro supports !include

http://openkore.com/index.php/!include
