### ISSUE TITLE
You failed to use item :Fire_Arrow_Quiver

### ISSUE THREAD

**Issue by Junezavr** [OpenKore/openkore#1131]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by Junezavr** [comment]
**can not open use Fire_Arrow_Quiver**

**Comment by Mortimal** [comment]
Fire Arrow Quiver ?

**Comment by Junezavr** [comment]
http://bit.ly/2y0zWKF

**Comment by Mortimal** [comment]
dont_use_underlines_in_names <- Dont do like this

**Comment by Junezavr** [comment]
Sorry i do not know

**Comment by Junezavr** [comment]
my config
useSelf_item Fire Arrow Quiver {
    inInventory Fire Arrow < 50
}
openkore
You failed to use item Fire Arrow Quiver

**Comment by Mortimal** [comment]
do command
i u
is there that item?

**Comment by Nipodemos** [comment]
tru use the ID of the item instead of the name

**Comment by Junezavr** [comment]
thx @Nipodemos
