### ISSUE TITLE
Hi! Xkore 3 not working in RO:Restart. please help.

### ISSUE THREAD

**Issue by icewafu05** [OpenKore/openkore#1133]
my bot freeze after 5 secs and this below details from console:

Proxying to [International - iRO: Re:Start]
[reconnect] Login retry number 2, setting reconnect timeout to 62 seconds.
Connecting (128.241.92.133:6800)... connected
Proxying to [International - iRO: Re:Start]
[reconnect] Login retry number 3, setting reconnect timeout to 130 seconds.
Connecting (128.241.92.133:6800)... connected
Proxying to [International - iRO: Re:Start]
[reconnect] Login retry number 4, setting reconnect timeout to 182 seconds.
Connecting (128.241.92.133:6800)... connected

**Comment by Mortimal** [comment]
it wont work... only xkore 0 supported

**Comment by icewafu05** [comment]
ok thank you. How about xkore 2 Sir?

**Comment by Nipodemos** [comment]
as he said, ONLY xkore 0 is supported,
1, 2 and 3 DOES NOT work

unfortunaly :-( , very sad

**Comment by Ziomm** [comment]
xkore 0 stopped working as well, you can take 2 steps and the client will freeze on you.

**Comment by alisonrag** [comment]
continue in #1227
