### ISSUE TITLE
Used RO Tools to extract packet  - how do I read the output (im a noob)

### ISSUE THREAD

**Issue by chranyu** [OpenKore/openkore#1137]
I'm new to openkore (and to github pls be gentle) and read the threads concerning how to operate it (I'm currently working on XKore 1). I've went all the way until my character enters the game. The only error I get from openkore is the packet tokenizer unknown switch that keeps popping in my openkore window. I already know the solution since you guys have already mentioned updating recvpackets.txt. Since this is the case, I've downloaded JCV's RO Tools (outdated I know) and upon using it, I've managed to extract a file. This is how I set it up: 

![ro tool](https://user-images.githubusercontent.com/31950777/30464332-926e730a-9a03-11e7-9598-8497801499f1.png)

This is what I extracted from it:
[disasm.txt](https://github.com/OpenKore/openkore/files/1305145/disasm.txt)

Question:
1) Is this file usable?
2) Is this what needs to be put in recvpackets.txt?

BTW: I'm playing in pRO Thor server

**Comment by lututui** [comment]
Try PEEK by Yommy: http://forums.openkore.com/viewtopic.php?f=6&t=207278

Also, the ragexe might be compressed/protected (how big is it in MB?)

**Comment by chranyu** [comment]
ragexe is 7484kb.. thx I'll try PEEK and post the result.. much appreciated

**Comment by chranyu** [comment]
PEEK didn't work. I guess its protected. I'll do the tedious process of reverse engineering (will have to research and practice the whole process) thx @lututui for your help.. again the threads were very helpful and hopefully I can contribute something in here as well.

**Comment by sctnightcore** [comment]
link server ? 
i will test it

**Comment by kurtkatorse** [comment]
@sctnightcore, this server wanted chranyu to have, https://www.ragnarokonline.com.ph/
its release late July, but since then no one can release/share in public. here in github a bot that is working on that mention server. even they are a instruction in openkore forums.

**Comment by alisonrag** [comment]
continue in #1225
