### ISSUE TITLE
how to teleport search mob?

### ISSUE THREAD

**Issue by gr4ndmasterz** [OpenKore/openkore#1140]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

i tried going through the manual but my bot doesnt seem to auto tele to search for monster.

below is my code.

teleportAuto_hp 15
teleportAuto_sp 0
teleportAuto_idle 1
teleportAuto_portal 0
teleportAuto_search 0
teleportAuto_minAggressives 0
teleportAuto_minAggressivesInLock 0
teleportAuto_onlyWhenSafe 0
teleportAuto_maxDmg 500
teleportAuto_maxDmgInLock 0
teleportAuto_deadly 1
teleportAuto_useSkill 1
teleportAuto_useChatCommand
teleportAuto_allPlayers 0
teleportAuto_notPlayers
teleportAuto_atkCount 0
teleportAuto_atkMiss 10
teleportAuto_unstuck 0
teleportAuto_lostTarget 0
teleportAuto_dropTarget 0
teleportAuto_dropTargetKS 0
teleportAuto_attackedWhenSitting 0
teleportAuto_totalDmg 0
teleportAuto_totalDmgInLock 0
teleportAuto_equip_leftAccessory
teleportAuto_equip_rightAccessory Belt [Creamy] [1]
teleportAuto_lostHomunculus
teleportAuto_useItemForRespawn
teleportAuto_item1
teleportAuto_item2

**Comment by Nipodemos** [comment]
There is a plug-in for this 
Look for tele-search in needs-review folder inside plugins folder

**Comment by lututui** [comment]
There's no need for plugin.

http://wiki.openkore.com/index.php/TeleportAuto_search

Tell which monsters to search for in mon_control (there's an example in the link), set the monsters amount in teleportAuto_search and turn on teleportAuto_idle

**Comment by gr4ndmasterz** [comment]
thank you so much .
