### ISSUE TITLE
PRo Extreme: New Loki - Account Server Timeout

### ISSUE THREAD

**Issue by emosinxrhenz** [OpenKore/openkore#1142]
So i have been experimenting various things to make this openkore work on PRo Extreme: New Loki. The pre-configured setting in this lastest download for the IP and stuff is i think wrong as i am experiencing error 10060. I used wireshark and login manually to ragna and got a different IP. Now that i got the new IP, i edited the server.txt and replace it with the IP that i got, not i am able to connect to new loki server, but now i am stuck at account server timeout.

![ip issue](https://user-images.githubusercontent.com/31973023/30515173-98aef2d2-9b55-11e7-8af4-688455cad8fa.JPG)

Your prompt replies would be very much helpful

**Comment by jonelle1990** [comment]
hi can you share the new ip address so i can help you to configure it

**Comment by yllor06** [comment]
Hi Jonell,

Is the pRO Thor sever is ready to BOT?

*Regards,*
*ROLLY H. LUMIGUEN*
Project Electrical Engineer
Property Development Division

EMPIRE EAST LAND HOLDINGS, INC.
20thF The World Centre, 330 Sen. Gil Puyat Ave., Makati City
Tel. Nos.: 823.0307 or 804.3563
Mobile No. 0917-8847187
E-mail: *rollylumiguen*.eelhi@gmail.com <emildeleon.eelhi@gmail.com>
Project E-mail: rwpp3.eelhi@gmail.com

**Comment by jonelle1990** [comment]
or if you want bot try to message this https://web.facebook.com/rophbot/

**Comment by emosinxrhenz** [comment]
hello jonelle, this is what i got

[Philippines - pRO: New Loki]
ip 139.99.113.156
port 6900
master_version 62
version 24
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverType pRO
patchserver wpatch.ragnarok.com.ph
patchpath /patch50
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
serverEncoding Tagalog
charBlockSize 144
gameGuard 1
recvpackets recvpackets.txt
addTableFolders pRO
pinCode 1

**Comment by jonelle1990** [comment]
where did u get the info of the server?

**Comment by yakisoba2009** [comment]
![image](https://user-images.githubusercontent.com/32344188/30938927-6066145c-a40e-11e7-85d0-58a5b32f6b4c.png)

**Comment by alisonrag** [comment]
continue in #1225

**Comment by babypogi** [comment]
ello emosinxrhenz can i have a copy of your config.txt thank you

**Comment by drayl666** [comment]
@yakisoba2009 Was just wondering, how is it that all of the working configs are showing the packets that are being sent, I haven't seen any topic/s through okore about this though.

**Comment by dhavenice00** [comment]
![4](https://user-images.githubusercontent.com/34276943/33612667-4606edae-da0d-11e7-9486-5ea39c02ef8a.png)
Im Stock here

**Comment by dhavenice00** [comment]
pls help me!

**Comment by dhavenice00** [comment]
![4](https://user-images.githubusercontent.com/34276943/33614760-3378ac6c-da13-11e7-8867-28db4bf5c645.png)
im stock in here! can somebody help me figure this out. pls

**Comment by kureinai0013** [comment]
I'm stock here! Help me [please...]
![bot](https://user-images.githubusercontent.com/38703548/40739748-0e714d82-6458-11e8-8028-42cb05e76ea2.jpg)
