### ISSUE TITLE
[eventMacro] PMs dont trigger at all

### ISSUE THREAD

**Issue by steveWin32** [OpenKore/openkore#1143]
So i want to make a macro that could trade with all of my bots but there is a problem

macro Trade {
do pm (username1) move prontera (x) (y)
do pm (username2) move prontera (x) (y)
do pm (username3) move prontera (x) (y)
do pm (username4) move prontera (x) (y)
do pm (username5) move prontera (x) (y)
do pm (username6) move prontera (x) (y)
do pm (username7) move prontera (x) (y)
do pm (username8) move prontera (x) (y)
do pm (username9) move prontera (x) (y)
do pm (username10) move prontera (x) (y)
do pm (username11) move prontera (x) (y)
do pm (username12) move prontera (x) (y)
...
}

Only 3 of the usernames were able to get the pm messages but 9 of them won't get it. It seems like the bot did nothing for the entire macro. I even tried adding spaces after (y) but didnt do a thing. However when i manually spam the same pm to one of my bot, the bot recieves every message such as Test. I typed Test over 100 times and the other bot gets the pm but not this.

**Comment by Mortimal** [comment]
u tried pause between commands? maybe it is problem loss problem?

**Comment by lututui** [comment]
*Sight*

Since you did not provide the actual eventMacro, I can only suggest some things:

1- You could include a log in between every command to help debugging, something like:

```
do pm personA message
log sent pm to personA
do pm personB message
log sent pm to personA
do pm personB message
log sent pm to personB
...
```

That way you would know when it's happening

2- Set debug to 3 in config.txt, so eventMacro plugin will dump debug information on the console

**Comment by drunkenhammer** [comment]
@lututui @Mortimal I tried log, it doesnt pm but the log still works. Pause doesnt help, still same problem

**Comment by Nipodemos** [comment]
I don't think parenthesis is good, try to quote the name of the character (ex: pm "username1" move prontera x y )

Another option is use bus commands

**Comment by drunkenhammer** [comment]
i tried pause 60 and it works but its soooo slow.  But ok still better than nothing

**Comment by Nipodemos** [comment]
do as lututui said:

2- Set debug to 3 in config.txt, so eventMacro plugin will dump debug information on the console

copy and paste here, so we can see whats happening, and we will problably find the error

(i'm wonderind, you are calling more than 10 bots to move to the same place at the same time? or that was just an example?)

**Comment by drunkenhammer** [comment]
```
[eventMacro] Checking macro 'tempMacro0', line index '12' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername1) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername1) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '12'.
[eventMacro] Line script 'do pm &eval($partyusername1) party403436x'.
Received packet: 09DF Handler: private_message_sent
(username1) is not online
[eventMacro] Checking macro 'tempMacro0', line index '13' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername2) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername2) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '13'.
[eventMacro] Line script 'do pm &eval($partyusername2) party403436x'.
Received packet: 09DF Handler: private_message_sent
(username2) is not online
AI: eventMacro | 1
[eventMacro] Checking macro 'tempMacro0', line index '14' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername3) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername3) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '14'.
[eventMacro] Line script 'do pm &eval($partyusername3) party403436x'.
Received packet: 09DF Handler: private_message_sent
(username3) is not online
[eventMacro] Checking macro 'tempMacro0', line index '15' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername4) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername4) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '15'.
[eventMacro] Line script 'do pm &eval($partyusername4) party403436x'.
AI: eventMacro | 1
[eventMacro] Checking macro 'tempMacro0', line index '16' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername5) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername5) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '16'.
[eventMacro] Line script 'do pm &eval($partyusername5) party403436x'.
[eventMacro] Checking macro 'tempMacro0', line index '17' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername6) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername6) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '17'.
[eventMacro] Line script 'do pm &eval($partyusername6) party403436x'.
AI: eventMacro | 1
[eventMacro] Checking macro 'tempMacro0', line index '18' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername7) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername7) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '18'.
[eventMacro] Line script 'do pm &eval($partyusername7) party403436x'.
[eventMacro] Checking macro 'tempMacro0', line index '19' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername8) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername8) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '19'.
[eventMacro] Line script 'do pm &eval($partyusername8) party403436x'.
AI: eventMacro | 1
[eventMacro] Checking macro 'tempMacro0', line index '20' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername9) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername9) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '20'.
[eventMacro] Line script 'do pm &eval($partyusername9) party403436x'.
Sent Sync
Received packet: 007F Handler: received_sync
Received Sync
[eventMacro] Checking macro 'tempMacro0', line index '21' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername10) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername10) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '21'.
[eventMacro] Line script 'do pm &eval($partyusername10) party403436x'.
AI: eventMacro | 1
[eventMacro] Checking macro 'tempMacro0', line index '22' for a macro command.
[eventMacro] Script 'do pm &eval($partyusername11) party403436x'.
[eventMacro] Next valid macro command found: 'do pm &eval($partyusername11) party403436x'.
[eventMacro] Executing macro 'tempMacro0', line index '22'.
[eventMacro] Line script 'do pm &eval($partyusername11) party403436x'.
[eventMacro] Macro 'tempMacro0' got to the end of its script.
[eventMacro] Macro 'tempMacro0' finished.
[eventMacro] Clearing queue
[eventMacro] Macro 'tempMacro0' is now deleting itself from AI queue.
AI:  | 1
```

Heres the script as you can see, only 3 private messages work. Though it doesn't matter for bot as the bot can pm the same message infinite time unlike the actual client that limits same text to up to 2 times. After the 4th username, the Received packet: 09DF Handler: private_message_sent no longer appears at all.

@Nipodemos no this is a actual code i have (i have 12 bots). I have 12 bots and i dislike hitting each and every worker the same macro such as moving that to location 12 times.

**Comment by c4c1n6kr3m1** [comment]
I remember have the same problem with macro long time ago
I thought it's server problem, but i never dig

**Comment by joecabezas** [comment]
this is why bus system was made, don't use PM

**Comment by joecabezas** [comment]
use bus system, it will solve your problem immediately, and without the server limitations for pm players

**Comment by alisonrag** [comment]
after some time we found the code that block pms to avoid spam, so this is the openkore default behavior.

**Comment by Nipodemos** [comment]
haha i never would have thought that
