### ISSUE TITLE
Packet Parser: Unknown switch: 0AB8???

### ISSUE THREAD

**Issue by gr4ndmasterz** [OpenKore/openkore#1144]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

## ------------------ Bug Report Template ------------------
Im not sure why this keep coming up ? is this a problem or can be ignored?

**Comment by alisonrag** [comment]
Nobody knows what this packet does. If you figure it out, please let us know on the issue.
