### ISSUE TITLE
Potion usage

### ISSUE THREAD

**Issue by Atrendy** [OpenKore/openkore#1145]
Hey there , this is the first time im using a bot so now i figured out how my characters starts using potions but for some reason he still dies its a level 12 swordmen but shouldn't the bot always use a potion when he gets too low on life ?

useSelf_item Novice Potion,Red Potion,Orange Potion,Yellow Potion,White Potion,Monster's Feed,Pet Food {
	hp < 40%
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	aggressives 0
	monsters
	notMonsters
	stopWhenHit 0
	inLockOnly 1
	notWhileSitting 1
	notInTown 1
	timeout 0
	disabled 0
	inInventory
	manualAI 0

Also can someone explain me what i have to do that my bot also picks up all items X.x

P.S : Sry when this is the wrong place to ask these questions =X

**Comment by Nipodemos** [comment]
If I do remember correctly , the hp condition don't have the " < " sign , don't need this one 

hp 40

Don't need the percentage too 

2 problem: this link explain : https://www.google.com.br/url?sa=t&source=web&rct=j&url=http://openkore.com/index.php/Items_control.txt&ved=0ahUKEwjNjo2miq3WAhXCxpAKHd0tDHAQFggfMAA&usg=AFQjCNHbb4fct4FqshI-L3F_ov1QL1Cu1A

**Comment by gr4ndmasterz** [comment]
i use this and it seems to work

useSelf_item Novice Potion, Potato, Carrot, Red Herb, Green Herb, Apple, Meat, Milk, Yellow Herb, Orange {
	hp < 40%
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
}

**Comment by alisonrag** [comment]
Working
