### ISSUE TITLE
iRO anti GM?

### ISSUE THREAD

**Issue by mhakulit** [OpenKore/openkore#1148]
can anyone help me ? all of my bot caught once again 😂 i think avoid txt doesn't work at all if the GM is completely invisible and cannot detected by openkore . thanks

**Comment by gr4ndmasterz** [comment]
mayb u r running a lot of bot with the same ip then gm will most likely suspect u.

**Comment by Nipodemos** [comment]
on iroRestart you don't have much you can do... 
when GM use perfect hide, it's impossible for openkroe to detect....

**Comment by drunkenhammer** [comment]
never bot for a long consecutive period of time. Make your bot dc every few hours.

**Comment by r421** [comment]
If you setting more than 1 bot on 1 pc/server and you do form a party leveling that just make they really easy to identify that you are botting. Some advice I can give:

1. Do not form party for leveling and make it auto follow. 
2. Do not party with any other player when you are botting.
3. Just leveling alone, if you need heal do some macro script to call your priest to heal when needed (this is why they do battle priest).
4. Do not bot on reported map, maybe someone just really piss off with bot (check on warpportal calling airstrike).
5. Do not form multiple party on one pc/server. Even you are using client and party with some bot you also will get caught.
6. GM will call all from single source/ip. If GM around make sure you do have good macro to avoid GM like to do something, example: ai off and open chatroom put title AFK or something more humanize.
7. Always optimize your bot and do not only copy paste script.
8. Do not bot 24H, please use breakTime in config and check PDT time make sure you not bot on their working hour. 

Good luck

**Comment by alisonrag** [comment]
this is not a issue
