### ISSUE TITLE
View Pet. 

### ISSUE THREAD

**Issue by Jeffgomz** [OpenKore/openkore#1150]
can someone help me if im trying to view my pet in bot it doesnt appearing but i have already 'ISIS'
it always appear blank can someone explain how it will work please help iRO:Restart

**Comment by c4c1n6kr3m1** [comment]
What do u mean ?
you can type "pet s" to see your pet

**Comment by Jeffgomz** [comment]
![pet](https://user-images.githubusercontent.com/30304551/30616066-ac00877e-9d99-11e7-9f5d-ce2d582bd16c.png)
this one can u check it plz

**Comment by c4c1n6kr3m1** [comment]
use at your own risk
try this code
https://github.com/c4c1n6kr3m1/openkore/commit/9357d07c5d1dd68e25cf947d5f8fe4c0467776e4#diff-b50d60f9dcc7ac34a214be4f9a5a3321

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1  SO Nice !!! PR pls

**Comment by Jeffgomz** [comment]
sorry sir im not good editing files, if its updated sir in new openkore i will download again, if its ok just re upload it sir thx

**Comment by c4c1n6kr3m1** [comment]
go to that link, download the Pet.pm ( https://github.com/c4c1n6kr3m1/openkore/raw/9357d07c5d1dd68e25cf947d5f8fe4c0467776e4/src/Interface/Wx/StatView/Pet.pm )
then put it in your openkore source folder src\Interface\Wx\StatView\ to replace the old file

**Comment by sctnightcore** [comment]
PR !!!! XD

**Comment by Jeffgomz** [comment]
thx c4c1n6kr3m1 <3 i will close this issue ^_^
