### ISSUE TITLE
pRO THOR sever

### ISSUE THREAD

**Issue by yllor06** [OpenKore/openkore#1151]
Pardon me if my issue is in the wrong place, please just advise me to remove. 

Is the lastest version able to work in the pRO thor server, I've downloaded the latest version but  I can't find the pRO thor server. Is there any way to have it work in that server? Thanks in advance.

**Comment by vbcatapat** [comment]
pRO is still under development and its not yet included in the latest version of openkore.

**Comment by yllor06** [comment]
thanks for the update bruh

**Comment by krampotsky12** [comment]
can i use OpenKore on ZenRo, VanRo and iRO? if yes can I get a copy of a config/bot thank you

**Comment by vlade08** [comment]
is there any update about pRO? cant find the IP for the server Thor

**Comment by yakisoba2009** [comment]
connected but stuck here

![image](https://user-images.githubusercontent.com/32344188/30938607-3319bf86-a40d-11e7-9154-52a90fa64779.png)

**Comment by yakisoba2009** [comment]
[Philippines - pRO : /ThorLoki]
#116.93.119.116
ip 139.99.113.156
port 6900
master_version 15
version 24
serverType pRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders pRO
charBlockSize 144
pinCode 1

**Comment by alisonrag** [comment]
continue in #1225
