### ISSUE TITLE
ROPH BOT NEW VERS. PLS NEWBIE

### ISSUE THREAD

**Issue by uknowme99** [OpenKore/openkore#1153]
Baka meron pong nkkpag bot d2 willing to pay mag papaturo lng po .. ^_^ ROPH po manila AREA

**Comment by Mortimal** [comment]
#1151

**Comment by jonelle1990** [comment]
ako meron akong bot sa roph message mo kami dito https://web.facebook.com/rophbot/

**Comment by jonelle1990** [comment]
if you want bot try to message this group https://web.facebook.com/rophbot/
