### ISSUE TITLE
can connect to restart server after update.

### ISSUE THREAD

**Issue by gr4ndmasterz** [OpenKore/openkore#1156]
hey can anyone help me as i cant connect to restart server after todays update

Closing connection to Character Server
Disconnecting (128.241.92.138:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.137:4513)... connected
Timeout on Map Server, connecting to Account Server...

**Comment by Nipodemos** [comment]
just wait to merge the new updatw, and should work

**Comment by gr4ndmasterz** [comment]
ok , so just wait for the update from the contributors right?

**Comment by Nipodemos** [comment]
right

**Comment by gr4ndmasterz** [comment]
ok thanks

**Comment by don00000** [comment]
any update?

**Comment by sctnightcore** [comment]
wait

**Comment by oleokoong** [comment]
There is some change in new rag.exe , the automated updates doesn't work properly..
Just wait for devs fix it manually

**Comment by LeHartx** [comment]
there's a new icon change in the .exe as well. :+1:

**Comment by jonelle1990** [comment]
any update?

**Comment by Kraigen** [comment]
I'm pretty sure if there are any updates, you'd see the time changed on the latest commit. Can't people just be patient and wait instead of asking every hour?

**Comment by jeandelima** [comment]
https://github.com/OpenKore/openkore/commit/2793fde799815d156a2f2cce5bba78f90a60c95e?diff=unified

Just tried and nothing..

**Comment by jonelle1990** [comment]
jsut wait their fixing it

**Comment by extatix1989** [comment]
it works now.. just update the file :)

**Comment by jonelle1990** [comment]
what you do @extatix1989

**Comment by extatix1989** [comment]
i saw the update that allanon did and redownloaded the whole thing or just hte tables folder. I redownloaded the whoel thing though

**Comment by oleokoong** [comment]
if you dont know which file has been change... Just redownload whole folder

**Comment by exxcrete** [comment]
just redownload the whole thing. or the table folder. but if you are not sure what you are doing may as well just download the whole files.

**Comment by alisonrag** [comment]
IRO UPDATED IN LASTEST VERSION
