### ISSUE TITLE
IdRO Character Delete Problem

### ISSUE THREAD

**Issue by BigPaps** [OpenKore/openkore#116]
Dear mate,

i've problem with deleting character on idRO server.

here's screen shot :
![openkore](https://cloud.githubusercontent.com/assets/19914808/16018566/31823f92-31cf-11e6-80cc-4d4245a39cc7.png)

![rpe](https://cloud.githubusercontent.com/assets/19914808/16019330/a8b6a2a8-31d2-11e6-936a-9d8b29d0812d.png)

time format is messed up.

old idRO deletion method didn't use deletion time,
now, charcater deletion is using time (1 min), after delete time reached, we need to enter pin/secret code. someone told me that idRO character deletion method is like iRO server.

**Comment by BigPaps** [comment]
here's packet received from server.
![rpe](https://cloud.githubusercontent.com/assets/19914808/16019305/8d57c14a-31d2-11e6-97a4-7a470aeec047.png)

**Comment by cydh** [comment]
Dude, https://github.com/OpenKore/openkore/pull/97

**Comment by itsrachelfish** [comment]
@BigPaps Hey there! We have been looking for someone who plays on idRO and is willing to test the pull requests that @cydh has been making.

Would you be willing to check out the code in #97 and make sure it works? Once you've tested cydh's changes, I'd be happy to merge the pull request. :smiley:

**Comment by BigPaps** [comment]
thanks for ur reply, i've already test pull request from @cydh made, it works... thanks for awesome job.. sorry for my bad english..

**Comment by denzastro** [comment]
ada yg punya link download plugin buat delete char dan buat char server idro?

**Comment by itsrachelfish** [comment]
@denzastro This issue has been fixed as of 5397294a50b52f2707177352a605d4cf8ee438e6

Please download the latest version of OpenKore to use the character delete

**Comment by mfauziracing** [comment]
hey i have a problem when i deleting the character, openkore always timeout on character select server. is it normal? any solution?
i use the latest version of Openkore.
thanks before.

**Comment by cydh** [comment]
Normal, there is timeout on char select, u cant stay in char select forever.

**Comment by mfauziracing** [comment]
@denzastro link plugins to auto delete and auto create char. : http://forums.openkore.com/viewtopic.php?f=34&t=211155. its work for auto create char, but still error when deleting character coz there is timeout on character select server. hope @cydh can help :)
