### ISSUE TITLE
Unable to Inject NetDirect.dll Re:Start

### ISSUE THREAD

**Issue by carlengz** [OpenKore/openkore#1160]
was trying to use my old bot folder (xkore1-2-3 working) but with an updated src/tables and server config.
but im getting error Unable to Inect - (RO DIRECTORIES) - netdirect.dll i like using kore with character on my vision so i can manual use it sometimes. Anyone who got a fix or what to do would be very appreciated. Thank you!

**Comment by carlengz** [comment]
also tried using the new whole folder of update kore github i can connect but i think it's not injected with the client because it doesnt show that i need to open client its just connecting to the game and working like xkore0.

**Comment by VCSNDBX** [comment]
Just restart your PC

**Comment by carlengz** [comment]
it's also not working. xkore3 xD i wanted to play Manual or Automatic option with CLient

**Comment by fadreus** [comment]
Check your setting:

- Run as administrator `start.exe`

- `config.txt` Xkore 1

Note: Besides XKore 0, other can't be used right now.
More infor on XKore recently, refer #1174

**Comment by alisonrag** [comment]
continue in #1227
