### ISSUE TITLE
iRO Chaos Renewal - timeout on account server

### ISSUE THREAD

**Issue by siolasilen** [OpenKore/openkore#1161]
Dear Dev Team,
Help me, Openkore keep timeout on account server,

IRO Chaos Renewal server.

Thanks Dev team.

**Comment by hendra814** [comment]
same me too get this problem.

**Comment by jomarlorica** [comment]
yes they change their IP i think? anyone can do it? i cant connect my openkore timeout dscounted issue

**Comment by phoebuss** [comment]
They change some packet identifier. As far as I know, the map login key word is now 0x45A1. I can get my char logged in the map server but got DCed several seconds after that.

**Comment by okeyb** [comment]
They change some packet identifier. As far as I know, the map login key word is now 0x45A1. I can get my char logged in the map server but got DCed several seconds after that.

**Comment by jomarlorica** [comment]
yes. lets wait for the @Dev Team and @Github for this.

**Comment by userix** [comment]
Having the same issue too

**Comment by jomarlorica** [comment]
@Dev @Github any reply?

**Comment by Baimonza** [comment]
Help me Time Out Server

**Comment by Baimonza** [comment]
![help me](https://user-images.githubusercontent.com/32193462/30738270-c7a613ce-9fb3-11e7-893f-61b0d7b03ae1.jpg)
@sctnightcore

Help me !!!

**Comment by jomarlorica** [comment]
@allanon here's our problem hehehe time out server. cant connect

**Comment by ragnarokfan** [comment]
https://ibb.co/cQk5jQ

having the same issue

**Comment by sctnightcore** [comment]
@Baimonza  wait dude

**Comment by krampotsky12** [comment]
can anyone give me a copy of the bot? Thank you

**Comment by Baimonza** [comment]
@sctnightcore Thx you ^^"

**Comment by bunnyy00** [comment]
no bot no life, can't do vending... same problem, timeout on connections

**Comment by krampotsky12** [comment]
@sctnightcore bro where can i download a copy of the bot? Thanks

**Comment by Nereaver** [comment]
Any Info on how we can fix this yet or what we can do to help fix this problem?

**Comment by Vespertine32** [comment]
@sctnightcore can i have a copy of a working bot please? thanks

**Comment by sctnightcore** [comment]
WAIT !!!! 

OK ?

**Comment by astraz** [comment]
new anti bot

**Comment by fadreus** [comment]
@Baimonza (B*y*b*`Th**) @ragnarokfan (C**il*aS**c**st) You guys might as well wanna hide anything with "ID" in it.. Anyone can trace it back to you. It's called "ID" for reasons.

**Comment by astraz** [comment]
http://ropd.info/?account=5396651
http://ropd.info/?account=5401223
LOL

**Comment by fadreus** [comment]
Exactly. The whole point censoring is kindda.... useless,
LOL xD

**Comment by Hikaron** [comment]
wowwie, xD lol, guys u really scrwed it up lmao

**Comment by robt101** [comment]
can anyone give me a copy of the bot? Thank you

**Comment by Baimonza** [comment]
- -*

**Comment by Nipodemos** [comment]
@robt101 NOOO
Just wait, it is not released yet

**Comment by sctnightcore** [comment]
WTF HAHA XD

**Comment by ragnarokfan** [comment]
thanks for pointing it out astraz however please remove your comments because we are just heling in the info of the community...

**Comment by Baimonza** [comment]
Now the program is not working.

@sctnightcore

**Comment by leuystaveras** [comment]
wait the developers will solve the problem.

**Comment by fadreus** [comment]
Problem solved.
TortoiseSVN didn't update properly, but can manually update the files.

Thanks Dev Team.

**Comment by Baimonza** [comment]
Thanks Dev Team.

TEST WAIT

**Comment by cloaking** [comment]
@Dev Team
@allanon 

Sir, this now the problem after updating my text files.
 the program always  "Disconnected from Map Server, connecting to Account Server ..."

What should I do with this?

Thanks

**Comment by fadreus** [comment]
@cloaking 

If you are using TortoiseSVN, the files didn't update properly for now.
Go to #1165  & add manually (after updating with TortoiseSVN)

Update
-tables/servers.txt
-tables/iRO/recvpackets.txt

Added new files
-tables/iRO/sync.txt
-tables/iRO/shuffle.txt

It worked for me.
Mine are running normally.

**Comment by Baimonza** [comment]
@fadreus


I ask for the solved file of recvpackets.txt.

**Comment by fadreus** [comment]
@Baimonza 

I copied from here:
https://github.com/OpenKore/openkore/blob/42def930848c851f14a6355568da3a169394e3c7/tables/iRO/recvpackets.txt

**Comment by Baimonza** [comment]
@fadreus Thx you

**Comment by cloaking** [comment]
@Dev Team
@allanon 
@fadreus 

Thanks guys, it's working but under observation for a long run.

**Comment by gilchan** [comment]
@allanon 
@sctnightcore 

Kore is running ok so far.
However, XKore still has the time out on map server issue.

**Comment by sctnightcore** [comment]
well wait allanon fix it

**Comment by plokislokis** [comment]
THOR also getting same issue

**Comment by cloaking** [comment]
@gilchan

Sir, do your path "...\openkore-master\tables\iRO" has the file shuffle.txt & sync.txt if not paste this to the said path.
hoping to run this ok.

[sync.txt](https://github.com/OpenKore/openkore/files/1325419/sync.txt)
[shuffle.txt](https://github.com/OpenKore/openkore/files/1325420/shuffle.txt)

**Comment by gilchan** [comment]
@cloaking

Yes, both the files are in.

**Comment by icecreamkings** [comment]
hi guys im just wondering after updated the files and added the sync.txt with shuffle.txt still didn't work for me. sorry can anyone help ?

**Comment by cloaking** [comment]
@icecreamkings 

If you are using TortoiseSVN, the files didn't update properly for now.
Go to #1165 & add manually (after updating with TortoiseSVN)

Update
-tables/servers.txt
-tables/iRO/recvpackets.txt

Added new files
-tables/iRO/sync.txt
-tables/iRO/shuffle.txt

It worked for me.
Mine are running normally.

by @fadreus

**Comment by cloaking** [comment]
@gilchan

Sir, do you do the manual updating for the files?

If you do disregard this message and try to wait for the response of the Dev Team.

Thanks

**Comment by ir0n** [comment]
Hi, has the ready-to-use version been updated on http://wiki.openkore.com/index.php/Links#Downloads ?

Or I only be able to do a manual update at this moment?

**Comment by krampotsky12** [comment]
does anyone knows a config for pRO bot? Thanks

**Comment by lowkeeme** [comment]
It still not working and how can we update using to TortoiseSVN? Any help?

**Comment by siolasilen** [comment]
i've tried the solution above from @fadreus,
i can login but item and equipment not showed and automaticaly disconnected again.
:D lol!

**Comment by icecreamkings** [comment]
@cloaking 
thankyou very much it's working for me

**Comment by siolasilen** [comment]
for some reason after i edit the recvpackets.txt it's working now.
still testing for longrun

**Comment by plokislokis** [comment]
@siolasilen  what recvpackets.txt did u use?

**Comment by fadreus** [comment]
@sctnightcore mentioned you guys can download from the updated files from Branch: iro_update
https://github.com/OpenKore/openkore/tree/iro_update
@allanon already update the files there.

**Comment by lowkeeme** [comment]
I tried to download and run the latest update @fadreus however I am getting the same issue:

![untitled](https://user-images.githubusercontent.com/30202014/30770058-5b5d62a2-a059-11e7-8226-6e53ec316acf.png)

**Comment by lowkeeme** [comment]
It's working now. I re-follow the instructions carefully:

Update
-tables/servers.txt
-tables/iRO/recvpackets.txt

Added new files
-tables/iRO/sync.txt
-tables/iRO/shuffle.txt

Works perfectly fine now. Will provide an update after a couple hours if any other issues occur.

**Comment by tiger778** [comment]
no working for me

**Comment by siolasilen** [comment]
@plokislokis the one mentioned by @fadreus,
just copy and paste to your recvpackets

**Comment by olracthor** [comment]
Still doesn't work for Thor, dunno what to do, maybe wait for further updates? 💃

**Comment by fadreus** [comment]
@olracthor 
based on #1165 I believe by adding  _**sendCryptKeys 0x54B63C85, 0x3BD55046, 0x4060068C**_ into your servers.txt under thor server would solve the problem.

**Comment by fadreus** [comment]
@olracthor 
According to @allanon at #1165 , solution for Thor server is to set CryptKeys in `servers.txt`

**Comment by 4n0nym3** [comment]
@siolasilen i got the same problem. my inventory is empty and got dc . what did u change on the recvpackets.txt? thank you.

@fadreus i've followed the instructions from @lowkeeme and updated the files from iro_update, but now, my inventory is empty and then it got dc after a few seconds. thank you.

**Comment by ragnarokfan** [comment]
I dc and timeout after using xkore 1 but in xkore 0 it works wonders

**Comment by blazasin** [comment]
Hi Guys , 

I have downloaded the latest Openkore master from Github and updated the text files mentioned by @lowkeeme and still getting the "timeout on map server error"
Kindly update all files and upload under Openkore master so ppl will find it easy to just update their config files and use Openkore

Thanks in Advance :)

![image](https://user-images.githubusercontent.com/32217722/30771892-ea66d00e-a06e-11e7-9dda-f9d6c55d3bca.png)

**Comment by lowkeeme** [comment]
@blazasin, I just followed the instructions of @fadreus, get the recvpackets here:
https://github.com/OpenKore/openkore/blob/42def930848c851f14a6355568da3a169394e3c7/tables/iRO/recvpackets.txt

and the cryptkeys here:
https://github.com/OpenKore/openkore/blob/master/tables/servers.txt

copy and paste the details on the documents inside the ffg:
-tables/servers.txt
-tables/iRO/recvpackets.txt

Then download this 2 text files: sync.txt and shuffle.txt from the link above and paste it inside your -tables/iRO/ folder.

Mine is fully working now. Just follow the instructions carefully.

**Comment by 4n0nym3** [comment]
@lowkeeme i've added/updated 4 files from iro_update branch.
1. Updated recvpackets.txt from [https://github.com/OpenKore/openkore/blob/iro_update/tables/iRO/recvpackets.txt](url)
2. Updated servers.txt from [https://github.com/OpenKore/openkore/blob/iro_update/tables/servers.txt](url)
3. Added new file (shuffle.txt) from [https://github.com/OpenKore/openkore/blob/iro_update/tables/iRO/shuffle.txt](url)
4. Added new file (sync.txt) from [https://github.com/OpenKore/openkore/blob/iro_update/tables/iRO/sync.txt](url)

still i got dc after login few seconds on map server.

**Comment by lowkeeme** [comment]
Well, the last resort I had done is I downloaded the updated Openkore and had done the said process @4n0nym3. If it still doesn't work, my advice is for you to wait with the other devs for an update or to give you a hand if it is possible.

**Comment by Vespertine32** [comment]
I have also tried the steps and i also get dc'd like @4n0nym3, i tried replacing all files from the the newly updated folder with the exception of replacing the config.txt and shop.txt but i am still getting the "Timeout on Map Server, connecting to Account Server..."

**Comment by ir0n** [comment]
Thank you so much @lowkeeme for you step-by-step instructions above (and also thanks to all developers/contributors). I am quite new here and your instructions is easy to understand for newbie like me.

Not sure whether this will be helpful for other newbies like me - 

1. use Google Chrome when copy&paste code in recvpacket and server
2. use Notepad++ (not notepad!) >> search google where to download them.

What I did (please refer to @lowkeeme instructions above).

1. download sync file >>> https://github.com/OpenKore/openkore/files/1325419/sync.txt
2. download shuffle file >>> https://github.com/OpenKore/openkore/files/1325420/shuffle.txt
3. update recvpacket and server

If this might help for newbie, I upload the edited recvpacket and server files here for you to download >>> http://www.filedropper.com/recvpacketsserver >> So you guys can just download and extract to the correct folder  (please refer to @lowkeeme instructions above).

Hope this help!

**Comment by Vespertine32** [comment]
@ir0n it worked now! i think its because i used normal notepad. Thanks alot

**Comment by fadreus** [comment]
Didn't know there are still newbies among us for game more than a decade old.
Here to make things much more easier for newbies, download these 2;

[iRO.zip](https://github.com/OpenKore/openkore/files/1326493/iRO.zip)
[servers.txt](https://github.com/OpenKore/openkore/files/1326495/servers.txt)

Extract iRO ZIP, servers.txt and replace them in`tables`.
*For non-newbie, go to `Branch: iro_update`, download everything, extract and only replace `tables.` (_Or everything, your choice)._

Do note that beside `XKore 0,` other stlll having some issues.

**Comment by 4n0nym3** [comment]
@ir0n i've followed ur advice using notepad++ and it works. thank you.
@fadreus i'm new with github. i didn't know that we can choose what to download from branch. i thought it will always the same. thank you for the enlightenment.

**Comment by ir0n** [comment]
@fadreus Thank you! For me, I just came back to play RO (and bot) last month after last played it ten years ago. The game is not new to me but I am not familiar with github/bot and technical term/instruction that you were discussion above T_T.

Tried hard to rstudy and follow them before posting any question though.

**Comment by dopcha93** [comment]
i did everything you guys told, but i still getting disconnect from maps servers 5 sec after i enter...

**Comment by 4n0nym3** [comment]
@dopcha93 just download the openkore-iro_update.zip from https://github.com/OpenKore/openkore/tree/iro_update then extract it.
you just need to copy your old files from control folder to the new one (openkore-iro_update).

**Comment by kifa15** [comment]
Thx you very much @iron and @lowkeeme. Now can start botting back

**Comment by fadreus** [comment]
Eah..? Why do I felt like I'm scolding someone? O,O"!!

**Comment by blazasin** [comment]
You guys are awesome , its perfectly working fine now ; Thanks a bunch !! kudos to ya all :dagger: 
@fadreus @4n0nym3 @ir0n @allanon 

I think we can close this thread now
:)

**Comment by leuystaveras** [comment]
Here is the openkore link that works...  [https://codeload.github.com/OpenKore/openkore/zip/iro_update](https://codeload.github.com/OpenKore/openkore/zip/iro_update)

**Comment by jomarlorica** [comment]
This patch again they change and i cant connect again. Please help @allanon @Dev

**Comment by jomarlorica** [comment]
Help us again @github @Dev @allanon

**Comment by tonyostark** [comment]
up
