### ISSUE TITLE
Willing To Pay for Gepard Shield bypass - ClassicRO bots https://classicro.net/

### ISSUE THREAD

**Issue by archilles89** [OpenKore/openkore#1163]
As per title.

**Comment by Nipodemos** [comment]
you can't do this here, can't sell and can't buy

**Comment by Hikaron** [comment]
I can sell you my body if you're willing to pay...

**Comment by moneyisgod** [comment]
I can sell you my body if you're willing to pay...

**Comment by sctnightcore** [comment]
I can sell you my body if you're willing to pay...
