### ISSUE TITLE
Time Out Map server  Chaos Re

### ISSUE THREAD

**Issue by Baimonza** [OpenKore/openkore#1167]
Help Me !! 

Download New Update

Time Out MAP
![666666](https://user-images.githubusercontent.com/32193462/30756617-a60702cc-9ff5-11e7-88bd-5e5d5fdebc37.jpg)
 Server !!

**Comment by sctnightcore** [comment]
wait !

**Comment by Baimonza** [comment]
@sctnightcore 

OK i Wait

**Comment by Hikaron** [comment]
sctnightcore, where do I download it?

**Comment by Hikaron** [comment]
@sctnightcore  Hey, where do I download it?

**Comment by userix** [comment]
How do I download the new files manually?  I don't have Tortoise SVN.  Thanks.

**Comment by lowkeeme** [comment]
I tried to manually update by adding the 2 files from #1161 which are: sync.txt and shuffle.txt but it still doesn't work and I am still getting timeout on account server. Am I doing something wrong?

**Comment by userix** [comment]
I have updated all files as stated in #1165  but still having Map Server disconnecting issue

**Comment by blazasin** [comment]
@allanon  @dev team , I have done all that is stated but still the same disconnected from map server error :(

**Comment by dacz2016** [comment]
how about iro thor server? any update? thank you

**Comment by Charles808** [comment]
@dacz2016  I'm in Thor server. Updating to branch : iro_update has solved the problem.
