### ISSUE TITLE
iRO CHAOS Can't cast a Skill 

### ISSUE THREAD

**Issue by cloaking** [OpenKore/openkore#1168]
@Dev Team
@allanon 

Sir, why is it the bot can't cast skill on mobs with prefix "Solid, Swift, Furious, etc."?
I already copy  the name of the mobs in monsters.txt but still it only do the normal attack.

Thanks in advance.

**Comment by c4c1n6kr3m1** [comment]
May be you've made a mistake

**Comment by lututui** [comment]
Don't tag dev or github.
