### ISSUE TITLE
Can someone take a peek on the reopen Chinese RO server?

### ISSUE THREAD

**Issue by MLNC** [OpenKore/openkore#1170]
Chinese RO is reopened. 
Can someone take a peek on that?
Here's the website: http://ro.zhaouc.com/

I just started to learn openkore. I was stucked by:
Timeout on Account Server, reconnecting. Wait 30 seconds...

Is that caused by the server.txt or the recvpackets.txt?

**Comment by sctnightcore** [comment]
welll -*- private server ? 

link download mini pls

**Comment by MLNC** [comment]
Download link: http://d1.zhaouc.net/RO20170914.zipIt's he new Chinese official server.
          
            
            On Sep 23 2017, at 3:26 am, sctnightcore <notifications@github.com> wrote:
            
            
              welll -*- private server ?
link download mini pls

**Comment by MLNC** [comment]
Download link: http://d1.zhaouc.net/RO20170914.zip   It's he new Chinese official server.

**Comment by rAthenaCN** [comment]
I need OpenKore  too, for CRO official server.

CRO clientinfo.xml
```
<?xml version="1.0" encoding="euc-kr" ?>

<clientinfo>

	<desc>Ragnarok Client Information - China Test</desc>
	<servicetype>china</servicetype>
	<servertype>primary</servertype>
	<hideaccountlist></hideaccountlist>
	
	<connection>
		<display>普隆德拉</display>
		<desc>None</desc>
		<port>6900</port>
		<domain>acc.ro.zhaouc.com:6900</domain>
		<version>1</version>
		<langtype>3</langtype>
		<registrationweb>http://ro.zhaouc.com/</registrationweb>
		<aid>
			<admin>100006</admin>
			<admin>100007</admin>
		</aid>
	</connection>

</clientinfo>
tinfo> 
```

**Comment by c4c1n6kr3m1** [comment]
do this first http://openkore.com/index.php/Connectivity_Guide

**Comment by sctnightcore** [comment]
Chinese official server. @c4c1n6kr3m1

**Comment by MLNC** [comment]
I followed the Connectivity Guide but still confused with serverType, charBlockSize and a few things. Can someone help please

**Comment by rAthenaCN** [comment]
![01](https://user-images.githubusercontent.com/19231012/30780358-3b45675c-a13b-11e7-80dd-a873e0c0110b.png)
Using WPE will be Shielded by nProtect GameGuard.

**Comment by sctnightcore** [comment]
poseidon ! 
http://openkore.com/index.php/Poseidon

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/30820901-9d2ddacc-a24d-11e7-9ab7-542816e962b4.png)

20Hour ! WTF 

someone can register id for me ?  @rAthenaCN  @MLNC

**Comment by alisonrag** [comment]
the first thing  you need to know is if client is protected by something like themida, after  you will need to study the structure of the hexed to get the packets, after you will need to write a code to get the packets and the codes of servertype like in bro/iro.
you can use as base to update:
https://github.com/lututui/bRO-Updates
https://gist.github.com/allanon/d8181ceaf6380da6d8fa4fddf1885706

**Comment by sctnightcore** [comment]
I think it would be like twRO ! 
i want download for test it !

**Comment by rAthenaCN** [comment]
@sctnightcore OK! I will upload full game to google for U.

**Comment by sctnightcore** [comment]
@rAthenaCN  ty sir you have discord ? add me sctnightcore#1063

**Comment by sctnightcore** [comment]
I want to help cRO but I can not pull a packet. HAHA
```
1Please run RO clinet.
Press ENTER to continue...
PID:3308
Step 1 - Read process memory to vector
Done.
Step 2a - Find the GetPacketSize function call
Address: 006F1551
Step 2b - Go Inside the GetPacketSize function
Address: 007CA300
Step 2c - Look for g_PacketLenMap reference and the pktLen function call followi
ng it
Address: 007CA330
Step 2d - Extract the g_PacketLenMap assignment
g_PacketLenMap reference: B9:BC:E1:DE:00
Step 3a - Find the InitPacketMap function call using g_PacketLenMap
Address: 009FBEC5
Step 3b - Go inside InitPacketMap
Address: 008AD370
Step 3c - Look for InitPacketLenWithClient call
Address: 008AD3BB
Step 3d - Go inside InitPacketLenWithClient
Address: 008AD840
Step 4a - Look for the first call
Address: 008AD84C
Step 4b - Go inside
Address: 008B4970
Step 4c - Look for ret
Address: 008B77E0
Step 4d - Look for call pattern 1
Pattern 1: 008AD790
Step 4e - Look for call pattern 2
Pattern 2: 008AD0D0
Step 5a - Get Client date
Client date: 20170919
Step 5b - Extract packet length
pattern 2 header not found.
Press ENTER to exit...
```

**Comment by sctnightcore** [comment]
//login packet ! 
send = 0xac, 0x0a > rev =  0xc9, 0x0a

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/30851033-a3fb90d6-a2d1-11e7-8f3c-54069384f815.png)
well well -*-

**Comment by lututui** [comment]
Oh! Another server with nProtect GameGuard!

FUN!

Ok, not really. You guys are probably going to need to use Poseidon or XKore 2

**Comment by alisonrag** [comment]
Need to use poseidom or xkore 2
Hexed is packed by themida

**Comment by caryshen** [comment]
@sctnightcore 
Can U show ur cro server.txt to me?

**Comment by moran212** [comment]
Who can help us in China CRO @alisonrag

**Comment by moran212** [comment]
@lututui  Can you help us?

**Comment by sctnightcore** [comment]
miss loginpacket!

**Comment by moran212** [comment]
@sctnightcore   Help us think of a way

**Comment by holymessenger** [comment]
lututui, alisonrag and  sctnightcore are really very warm-hearted. they are willing to share their precious time and knowledge with the strangers.

**Comment by dcyxxt** [comment]
following~

**Comment by sctnightcore** [comment]
Go #1519

**Comment by leilei007** [comment]
I still unknown packets for a link to download the complete OP under control
