### ISSUE TITLE
Packet Tokenizer: Unknown switch: 8605

### ISSUE THREAD

**Issue by loybuckz** [OpenKore/openkore#1171]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary: 
Receving error Packet Tokenizer: Unknown switch: 8605
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
private server ? idk

**Comment by loybuckz** [comment]
pRO Loki server

**Comment by lututui** [comment]
8605 is not a valid packet for Ragnarok. It's probably encrypted and/or recvpackets is quite incorrect

**Comment by alisonrag** [comment]
continue in #1225
