### ISSUE TITLE
Iro Chaos New Job Error 

### ISSUE THREAD

**Issue by Baimonza** [OpenKore/openkore#1173]
New Job Doram 

Error 

Help Me !

![doram](https://user-images.githubusercontent.com/32193462/30773923-dee6d87e-a0a4-11e7-8bcd-02c01e76d4e4.jpg)

**Comment by c4c1n6kr3m1** [comment]
what map is that? try to get out from that map using iro client

**Comment by alisonrag** [comment]
the current map is not supported, please provide more information so wecan add the new map

**Comment by sctnightcore** [comment]
**No updates. For a long time**
I closed issues.
