### ISSUE TITLE
xKore 1 Timeout on Map Server

### ISSUE THREAD

**Issue by FireflySkye** [OpenKore/openkore#1174]
I first noticed this on RE:Start server now in iRO Renewal server. Unable to move upon login to character then Timeout on Map Server. How to fix this one? >.<

**Comment by alisonrag** [comment]
xKore 1 and xKore 3/proxy not have support to encryptMessageID

**Comment by c4c1n6kr3m1** [comment]
so, X2

**Comment by elitecasaj00** [comment]
I am having no luck with xKore 2, either – are all but 0 broken?

**Comment by sctnightcore** [comment]
i want xKore 3 too ! HAHA

**Comment by alisonrag** [comment]
@sctnightcore 
i'm working on it, but its hard to openkore work together with client when encryptMessageID is in use, in every packet the Key change

**Comment by sctnightcore** [comment]
well  ! @alisonrag

**Comment by carlengz** [comment]
@fadreus Thank you for tagging me here.

So any xkore 3 is not working on re:start? :/

**Comment by alisonrag** [comment]
continue in #1227
