### ISSUE TITLE
[question][eventMacro] conditons and regexp

### ISSUE THREAD

**Issue by joecabezas** [OpenKore/openkore#1177]
Hello, community, how can I capture groups in conditions using eventMacro?

```
automacro bus_test {
    BusMsg /position (\d+) (\d+)/
    call {
    	log first group: $1
    }
}
```
if I receive a bus message "position 12 34", how can I make this automatro logs: "first group: 12" ?

thanks

**Comment by Nipodemos** [comment]
unfortunaly you can't =/

but you can use this sub:

```perl
sub getText {
    my ($text) = @_;
    $text =~ /position (\d+) (\d+)/
    return "$1 $2";
}
```

this way you can get the coordinate in a perfect way

you can use the sub this way:

```
automacro bus_test {
    BusMsg /position (\d+) (\d+)/
    call {
        $coord = getText("$.BusMsgLastMsg")
    	log position is: $coord
    }
}
```

**Comment by joecabezas** [comment]
well, there is room for improvements, after checking code in eventMacro:

BaseMsg.pm
```
sub get_new_variable_list {
	my ($self) = @_;
	my $new_variables;
	
	my $actor = $monsters{$self->{id}};
	
	$new_variables->{".".$self->{name}."Last"."Name"} = $self->{source};
	$new_variables->{".".$self->{name}."Last"."Msg"} = $self->{message};
	
	use Log qw(message);
	use Data::Dumper;
	message Dumper(\$new_variables);
	
	return $new_variables;
}
```

it prints:

```
$VAR1 = \{
            '.BusMsgLastName' => 'dummy',
            '.BusMsgLastMsg' => 'position 12 34'
          };
```

it shall also include any regexp matches, like:

```
$VAR1 = \{
            '.BusMsgLastName' => 'dummy',
            '.BusMsgLastMsg' => 'position 12 34',
            '.BusMsgLastMatch0' => '12',
            '.BusMsgLastMatch0' => '34',
          };
```

But I do not know how to make this improvement yet, I do not like perl too much :(

**Comment by Nipodemos** [comment]
that is my dream man, to make such thing possible, i do understand a little bit of perl
but this is to far yet...

but i've managed to do something you can use!!
the new thing i am implementing is:

if ($.BusMsgLastMsg =~ /position (\d+) (\d+)/ {
    # now it saves the values in $.lastMatchx  (where x is the number )
    log x = $.lastMatch1
    log y = $.lastMatch2
}

i think it solves you problem right?

**Comment by joecabezas** [comment]
great, thanks!, I am closing this
