### ISSUE TITLE
iRO Loki Crypt

### ISSUE THREAD

**Issue by suhery** [OpenKore/openkore#1178]
It seems they also apply renewal anti bot to classic. Timeout on map server. I have try to use renewal crypt key, copy shuffle.txt, sync.txt, and recvpacket.txt. It doesn't work.

**Comment by c4c1n6kr3m1** [comment]
no , it isn't, yet
the ip is 128.241.92.203
try to separate classic table folder from iro table

**Comment by kimer19** [comment]
how about in chaos ?

**Comment by suhery** [comment]
Thanks for pointing it out c4c1n6kr3m1. I think we should move shuffle.txt and sync.txt to separated renewal folder.

**Comment by kimer19** [comment]
Thanks for the reply , my bot is okay now i download the latest openkore

**Comment by tftgigo** [comment]
@kimer19  Hi Sir, can you share what bot are you using?

**Comment by sctnightcore** [comment]
download the latest openkore ! @tftgigo

**Comment by kimer19** [comment]
​
 openkore-master (1).zip
<https://drive.google.com/file/d/0By4LyVpgcEYtVkRoTU1DY3lOTmM/view?usp=drive_web>
​

**Comment by sctnightcore** [comment]
@kimer19  del dude !!!!
@tftgigo 
![image](https://user-images.githubusercontent.com/23263315/30803313-594f3b64-a213-11e7-9dc3-28a3c1923260.png)

**Comment by suhery** [comment]
I solved this issue by creating blank shuffle.txt and sync.txt in Classic folder. This way renewal, classic, and restart can work correctly.

**Comment by c4c1n6kr3m1** [comment]
@suhery Yes that would work too
I try different  approach on pull #1193

So with table like this
```addTableFolders iRO/Classic;iRO```
It will only search shuffle.txt on iRO/Classic folder, but not on iRO folder
