### ISSUE TITLE
[eventMacros] automacros not triggered on ai manual

### ISSUE THREAD

**Issue by joecabezas** [OpenKore/openkore#1179]
A simple automacro using `eventMacros` like:

```
automacro test {
    PubMsg /hi/
    call {
    	log PubMsg detected
    }
}
```
is not triggered when `ai` is set to `manual`

`ai manual`

but using `macros` plugin works without problems, is this a design decision?, how to make automacros to be triggered on manual ai?, thanks

**Comment by Nipodemos** [comment]
macro are not checked on manual ai, to make then checkable, just use a parameter:
```
automacro test {
    PubMsg /hi/
    checkOnAI auto, manual
    call {
    	log PubMsg detected
    }
}
```

the possible values are **auto**, **manual** and **off**

**Comment by joecabezas** [comment]
minor typo:

`checkOnAI auto, manual`

now it works, thanks!
