### ISSUE TITLE
iRO CHaos Renewal - autobuyng dont work.

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#1180]
Hello. Autobuing on iRO Re:tart stop working a month ago.
Yesterday I had to update openkore on iRO Chaos Renewal through GitHub, result: autobuyng dont work. I do not know why no one is working on this problem. 

```
- Responses (Cat Paw Shrimp Merchant) --
#  Response
0  Buy
1  Sell
2  Cancel
3  Cancel Chat
----------------------------------------
------------ Store List (Harive#Äµµð»óÀÎ) ------------
#  Name                    Type                  Price
0  Carrot                  Usable Heal             15z
1  Shrimp                  Usable Heal            500z
2  Nepeta Cataria          Usable Heal             15z
------------------------------------------------------
NPC Cat Paw Shrimp Merchant (0): Done talking
Done talking with NPC Cat Paw Shrimp Merchant (0).
Npc did not respond.
```

**Comment by shaohui89** [comment]
Hello. I have issues with buying red potions from tool dealer at izlude and prontera. Anyone care to share the coordinates or settings?

**Comment by Glikadin** [comment]
Use this in control.txt (This is an example):

```
buyAuto Red Potion {
	minAmount
	maxAmount 50
	npc aldeba_in 94 56
	npc_steps b e
	distance 8
	label BuyReds
	passive
}
```

http://openkore.com/index.php/BuyAuto

**Comment by Glikadin** [comment]
Still not work.

**Comment by sctnightcore** [comment]
```
buyAuto Red Potion {
	minAmount 1 
	maxAmount 50
	npc aldeba_in 94 56
	distance 8
}
```

test it ! @Glikadin

**Comment by Glikadin** [comment]
@sctnightcore No no no, i have other problem:
`Npc did not respond.`

Bot are stuck. It started after recent updates, autobuying dont work.

**Comment by sctnightcore** [comment]
![untitled](https://user-images.githubusercontent.com/23263315/30806195-f97d91ac-a21e-11e7-96c2-8f00740fe7f7.png)
WORK !

**Comment by Glikadin** [comment]
@sctnightcore You can give me your bot in archive? Just delete username, pasword and macros.txt

**Comment by Glikadin** [comment]
http://i.piccy.info/i9/ee70d323b830a33a5c57ce2b157e2e43/1506339449/142880/1180957/OpenStuck.jpg

**Comment by Glikadin** [comment]
![openstuck](https://user-images.githubusercontent.com/20753532/30806720-95a778ce-a1ff-11e7-9924-b9efa8025fee.jpg)

**Comment by Glikadin** [comment]
Still dont work. To start an autobuying, I use this code in macros.txt:
```
automacro CheckState {
	timeout 600
	disabled 1
		location comodo
		call {
		lock CheckBadlocation
		lock CheckWeight
		pause @rand(5,7)
		do ai on
		do move @rand(187,192) @rand(144, 152) comodo
		pause @rand(1,2)
		do talknpc 195 150 c r0 n
		pause @rand(1,2)
		do autostorage
		pause 1
		do autosell
		pause 1
		if ($.zeny < 50000) {
		do relog 36000
		log =====================
		log     Zeny is Over
		log =====================
		}
		pause @rand(1,2)
		do autobuy
		pause @rand(1,2)
		release CheckWeight
		release CheckBadlocation
		pause @rand(1,2)
		stop
		}
}
```

**Comment by Glikadin** [comment]
config.txt :
```
########################## Buy Auto ############################

buyAuto Nepeta Cataria {
	minAmount
	maxAmount 3000
	npc comodo 103 136
	npc_steps r0
	distance 8
	label BuyNepeta
	passive
}

buyAuto Berserk Potion {
	minAmount
	maxAmount 15
	npc cmd_in01 79 182
	npc_steps b e
	distance 8
	label BuyBerserk
	passive
}

buyAuto Fly Wing {
	minAmount
	maxAmount 200
	npc cmd_in01 79 182
	npc_steps b e
	distance 8
	label BuyWing
	passive
}

buyAuto Butterfly Wing {
	minAmount
	maxAmount 3
	npc cmd_in01 79 182
	npc_steps b e
	distance 8
	label BuyButterfly
	passive
}
```

**Comment by sctnightcore** [comment]
```
buyAuto Nepeta Cataria {
	standpoint
	distance 5
	minAmount 1
	maxAmount 3000
	npc comodo 103 136
	batchSize
	disabled 0
}


buyAuto Nepeta Cataria {
	standpoint
	distance 5
	minAmount 1
	maxAmount 15
	npc cmd_in01 79 182
	batchSize
	disabled 0
}

buyAuto Fly Wing {
	minAmount 1
	maxAmount 15
	npc cmd_in01 79 182
	npc_steps b e
	distance 8
}

buyAuto Butterfly Wing {
	minAmount 1 
	maxAmount 3
	npc cmd_in01 79 182
	npc_steps b e
	distance 8
}
```

test it XD

**Comment by Glikadin** [comment]
What plugins do you use? Maybe there is a problem in them?

**Comment by sctnightcore** [comment]
`loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder`


openkore latest !

**Comment by Glikadin** [comment]
Npc did not respond. T________________________T

**Comment by sctnightcore** [comment]
npc_steps r0 << i think is wrong !

**Comment by Glikadin** [comment]
Its Cat merchant , non-standard npc_steps

**Comment by sctnightcore** [comment]
npc_steps b e

**Comment by Glikadin** [comment]
NPC requires a response to be selected, but the given instructions don't match that (current step: b).
=\

**Comment by sctnightcore** [comment]
NPC requires a response to be selected, but the given instructions don't match that (current step: b).
Using method '0' defined on config key 'npcWrongStepsMethod' to deal with the error.
Cleaning all remaining conversation steps, please input more steps using commands.


HAHA idk why HAHA

**Comment by Glikadin** [comment]
Hmmmm . where is npcWrongStepsMethod ? Its in config.txt ?

**Comment by Glikadin** [comment]
I am testing npcWrongStepsMethod "1" and "0" .Still not work T_____________T

**Comment by Glikadin** [comment]
![openstuck](https://user-images.githubusercontent.com/20753532/30809576-e6e0d3b0-a20a-11e7-84b4-50679a0b5f57.jpg)

Not respond all Tool dealers =\

**Comment by sctnightcore** [comment]
http://openkore.com/index.php/NPC_conversation_codes

**Comment by Glikadin** [comment]
I using "npc_steps b e" the same as you. Problem in another =\

**Comment by Glikadin** [comment]
I found the solution:
![openstuck](https://user-images.githubusercontent.com/20753532/30810900-26e7ac46-a20f-11e7-9692-4903b3b9b8f2.jpg)

```
buyAuto Nepeta Cataria {
	minAmount 1
	maxAmount 3000
	npc comodo 103 136
	npc_steps r0 w5
	distance 6
	label BuyNepeta
	passive
}

buyAuto Berserk Potion {
	minAmount 1
	maxAmount 15
	npc cmd_in01 79 182
	npc_steps b w5
	distance 6
	label BuyBerserk
	passive
}

buyAuto Fly Wing {
	minAmount 1
	maxAmount 200
	npc cmd_in01 79 182
	npc_steps b w5
	distance 6
	label BuyWing
	passive
}

buyAuto Butterfly Wing {
	minAmount 1
	maxAmount 3
	npc cmd_in01 79 182
	npc_steps b w5
	distance 6
	label BuyButterfly
	passive
}
```
Bot disconnects and gets errors, but can buy items. Thx for help!

**Comment by sctnightcore** [comment]
#1006

**Comment by alisonrag** [comment]
continue in #1006
