### ISSUE TITLE
[question][bus] bus system and other languajes

### ISSUE THREAD

**Issue by joecabezas** [OpenKore/openkore#1181]
open question:

is it possible to write standalone scripts and send messages to the bus system in other languajes like python?

what I want to achieve running a python script that sends messages to the bus, so kore instances receive messages

**Comment by joecabezas** [comment]
after some days of investigation on this I was able to send bus messages over websocket, by making my own plugin basing in in the webMonitor plugin in the needs-review folder

I am still working on this plugin and making it available soon

**Comment by Nipodemos** [comment]
sorry for can't help you, i do know a little about perl, but use other languages i know nothing 😞 
if you release this it will surely be helpful! thanks in advance

**Comment by joecabezas** [comment]
thanks!, yesterday I finished the websocket plugin, and it works great, also, it comes with a new command "wsmsg" so you can send messages from the bot to any other application connected to the websocket

is still under fine tuning, and it have A LOT of debug logging (since I never worked before with sockets), and I plan to release it on december or so :)
