### ISSUE TITLE
Prontera map - Iro Renewal

### ISSUE THREAD

**Issue by Fvegini** [OpenKore/openkore#1182]
Prontera .fdl looks like outdated for Iro-Renewal server.

I tried with the 3 files inside the openkore (fields root, fields EP 14.1 and fields EP 15.1)

Some houses changed place, so the bot was trying to move inside the unwalkable sprites.

I extracted the .gat from SRC (looks like the old prontera map was renamed inside to pprontera)
and converted it to .fdl and the bot started to walk correctly.... just with the WXSTART the shown map wasn't updated... I couldn't find how to uptade it too.

Here is the new .fld

[prontera.zip](https://github.com/OpenKore/openkore/files/1327601/prontera.zip)

**Comment by c4c1n6kr3m1** [comment]
make a backup , delete the old one first, 
-prontera.fld or prontera.fld.gz
-prontera.dist
-map\prontera.xpm
or
you can edit resnametable.txt inside your tables folder, and add something like this
```prontera.gat#prontera_new.gat#```
and rename your new prontera.fld to prontera_new.fld

**Comment by nizdi** [comment]
Still not working, can`t understand why, I did extracted from data.grf too and keeps trying to walk throught unwalkable cells.

**Comment by Fadreus** [comment]
@nizdi 
![image](https://user-images.githubusercontent.com/32188494/37563232-165927c0-2ab7-11e8-966b-728228405597.png)

![image](https://user-images.githubusercontent.com/32188494/37563249-4b4d8868-2ab7-11e8-9a4d-6242d0a21dbe.png)

Mine working just fine. You sure you do it correctly?

**Comment by nizdi** [comment]
Thanks for the elusive anwser. I did something wrong, i did deleted the old one prontera, but did not deleted .dist file, which defines unwalkable cells. Thanks for the help my friend!

**Comment by Fadreus** [comment]
I simply download the provided file by Fvegini and just follow c4c1n6kr3m1's 2nd suggestion (edit resnametable.txt & renaming the file). I didn't delete anything. >w<

But glad it worked. There ain't 1 solution to every problem in this world. =D
