### ISSUE TITLE
[bRO Thor] Problem with "talk"/Problemas conversar com NPC 

### ISSUE THREAD

**Issue by tiranossaur** [OpenKore/openkore#1187]
Oi pessoal, estou tendo problemas com talk, ele fala tudo certinho, mas para conforme na imagem, quando eu entro na mao e realizo a mesma sequencia de conversa, a ultima conversa fica aquele botao "fechar" eu acho que é essa parte que o kore ta enroscando, e não entra para fazer a quest do arruaceiro. Ja tentei talk cont, talk end, talk x, talk num, talk resp, não passa disso. 

Meu config ta xkore 0 (uso poseidon), tambem testei com autoTalkCont 1 e autoTalkCont 0.

Obrigado des de já :)

![image](https://user-images.githubusercontent.com/14037089/30882430-ea7f9246-a2d6-11e7-9f39-ce73c734d989.png)

**Comment by joecabezas** [comment]
minor comment, please, keep issues in english please

**Comment by tiranossaur** [comment]
Sorry my bad.
I'm in troubles with "talk", I'm doing rogue quest, when I enter in portal that needs to talk with to enter, the conversation goes ok, but in the last part of conversation the portals talk appears the message like a button to close conversation, the openkore is ignoring it i think, then he never get pass the portals, he get stuck because he doesnot click in the "close" button of talking.

Sorry again for bad english, I hope u understand that i was trying to say. Thanks anyways

**Comment by lututui** [comment]
Hm. I wonder why it's saying `itself`

**Comment by tiranossaur** [comment]
I just downloaded the github last version of openkore, and tested, and I got the same error.

I try with different versions of openkore i tried from 13 august and give the same error.

![image](https://user-images.githubusercontent.com/14037089/30893596-020ec522-a30d-11e7-80e9-8e5cc6dd6db9.png)

Thanks for response :)

**Comment by koodpzok** [comment]
I also have a similar problem. When i reached the point where close button appeared, the bot clicked on it. However, thats not the end of the conversation (But the bot thought it was). Another window popped up. So any command sent after would result in errors.

**Comment by tiranossaur** [comment]
I just enter in the acc to show where the kore stops look:

![image](https://user-images.githubusercontent.com/14037089/30894094-a44b8b52-a30f-11e7-9020-db327f06d372.png)

**Comment by c4c1n6kr3m1** [comment]
inside timeout.txt , we'll found
ai_npc_talk_wait_to_answer 1.5
ai_npc_talk_wait_after_close_to_cancel 0.5
ai_npc_talk_wait_after_cancel_to_destroy 0.5

try lower ai_npc_talk_wait_after_close_to_cancel & ai_npc_talk_wait_after_cancel_to_destroy, make it 0, will it help ?

**Comment by tiranossaur** [comment]
I reduce the timeouts but still stuck in the same problem. :(
