### ISSUE TITLE
Ragnarok PH loki bot error pls. help

### ISSUE THREAD

**Issue by rz172000** [OpenKore/openkore#1188]
![1111111](https://user-images.githubusercontent.com/31846357/30894921-e16575fa-a357-11e7-9d2b-e9a8c33f7380.jpg)

**Comment by notsobotuser** [comment]
stop trying HAHHAHAHA

**Comment by rz172000** [comment]
but its possible in this server?

**Comment by yakisoba2009** [comment]
![image](https://user-images.githubusercontent.com/32344188/30938456-a7d50d0e-a40c-11e7-8725-1c90420adc0b.png)
  connected but stuck here

**Comment by yakisoba2009** [comment]
![image](https://user-images.githubusercontent.com/32344188/30938531-df985cc8-a40c-11e7-8f45-e8131b2e6e4a.png)
connected but stuck here

**Comment by alisonrag** [comment]
continue in #1225
