### ISSUE TITLE
IRO - Restart Character stuck and constantly disconnecting 

### ISSUE THREAD

**Issue by Nivlala** [OpenKore/openkore#1189]
My character in IRO-Restart is stuck in prontera after teleporting and constantly disconnecting from map server. 
I had tried downloading openkore again. 
First it was stuck in route, now it just constantly disconnects after a minute or so.
Have read all the past issues posted but can't find a solution to it. 
=========================== Server Infos ===========================
EXP Rates: 125% (Base 100% + Premium 0% + Server 25% + Plus %) 
Drop Rates: 100% (Base 100% + Premium 0% + Server 0% + Plus %) 
Death Penalty: 100% (Base 100% + Premium 0% + Server 0% + Plus %) 
=====================================================================
You are no longer: UNKNOWN_STATUS_993
You are no longer: UNKNOWN_STATUS_994
Disconnected from Map Server, connecting to Account Server in 46 seconds..
This is all i see on the console.
Would appreciate if someone would help me with this issue. 
Thanks in advance

**Comment by sctnightcore** [comment]
download new openkore

**Comment by Nivlala** [comment]
I downloaded the new Openkore from https://github.com/OpenKore/openkore 
but the i got 
Timeout on Map Server, connecting to Account Server in 30 seconds...
Incoming data left in the buffer:
================================================
83 bytes   Sep 27 14:27:32 2017
  0>  31 01 BB 49 03 00 2B 39    20 43 4D 20 7C 20 4F 72    1..I..+9 CM | Or
 16>  69 20 7C 20 43 61 72 64    73 00 00 00 00 00 00 00    i | Cards.......
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00                                              ...
Only 83 bytes in the buffer, when 0131's packet length is supposed to be 168590956 (wrong recvpackets?)
Disconnecting (128.241.92.137:4512)...disconnected
And got disconnected continuously after that.

**Comment by sctnightcore** [comment]
well i will test

**Comment by Nivlala** [comment]
Thanks so much !

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/30905426-f4a44866-a39e-11e7-8d0c-6dbe76779098.png)
i'm ok

**Comment by Nivlala** [comment]
I read on the Openkore wiki and it says that i can extract the recvpacket.txt to solve the issue. But how does that work?

**Comment by sctnightcore** [comment]
@Nivlala  recvpacket for ?

**Comment by Nivlala** [comment]
I got no idea hahah. kind of lost at what to do

**Comment by sctnightcore** [comment]
download new openkore and test again

**Comment by Nivlala** [comment]
I downloaded and tried on my other characters too. 
Could it be due to me logging in to the actual RO server then back to Openkore? 
Cause that what happened to my other characters.

**Comment by sctnightcore** [comment]
xkore 0 ?

**Comment by Nivlala** [comment]
All i see is a stuck character and 
Disconnected from Map Server, connecting to Account Server in 34 seconds...
You are no longer: UNKNOWN_STATUS_993
You are no longer: UNKNOWN_STATUS_994
Stuck at prontera (143,97), while walking from (143,97) to (153,255).
Stuck during route.
Disconnected from Map Server, connecting to Account Server in 30 seconds...

Would this help? 
http://openkore.com/index.php/Packet_Length_Extractor
But i have no clue how that works. 
I tried it multiple times.

**Comment by sctnightcore** [comment]
Do you use xkore 3?

**Comment by Nivlala** [comment]
I got no idea. hahaha i kind of just started using openkore this week. 
This is the control file text. 

# Please Read the Users Manual
# The Manual is located at http://wiki.openkore.com/index.php?title=Manual

######## Login options and server-specific options ########

master International - iRO: Re:Start
server 0
username 
password 
loginPinCode
char 1

# Poseidon Settings (http://wiki.openkore.com/index.php/PoseidonServer)
# They must be the same as Query Server config in Poseidon.txt
poseidonServer 127.0.0.1
poseidonPort 24390

bindIp
forceMapIP

# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore
XKore 1
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe

# XKore 2 / Proxy configuration
XKore_listenIp 127.0.0.1
XKore_listenPort 6901
XKore_publicIp 127.0.0.1
XKore_ID

# It is not advised to set secureAdminPassword if you're using Xkore 2
secureAdminPassword 1
adminPassword wepetwis
callSign
commandPrefix ;
callSignGM 0
inGameAuth 0

pauseCharServer 0
pauseMapServer 0
ignoreInvalidLogin 0
secureLogin_requestCode

# Opening cash shop when connected to map server (recv/ST0)
whenInGame_requestCashPoints 0

message_length_max 80

######## Main configuration ########

alias_heal sp 28

allowedMaps
allowedMaps_reaction 1

attackAuto 2
attackAuto_party 1
attackAuto_onlyWhenSafe 0
attackAuto_followTarget 1
attackAuto_inLockOnly 1
attackAuto_notInTown 1
attackDistance 1.5
attackDistanceAuto 0
attackMaxDistance 2.5
attackMaxRouteDistance 100
attackMaxRouteTime 4
attackMinPlayerDistance 2
attackMinPortalDistance 4
attackUseWeapon 1
attackNoGiveup 0
attackCanSnipe 0
attackCheckLOS 0
attackLooters 0
attackChangeTarget 1
aggressiveAntiKS 0

autoMoveOnDeath 0
autoMoveOnDeath_x
autoMoveOnDeath_y
autoMoveOnDeath_map

attackEquip_topHead
attackEquip_midHead
attackEquip_lowHead
attackEquip_leftHand
attackEquip_rightHand
attackEquip_leftAccessory
attackEquip_rightAccessory
attackEquip_robe
attackEquip_armor
attackEquip_shoes
attackEquip_arrow

#You need the breakTime plugin: http://wiki.openkore.com/index.php?title=BreakTime
autoBreakTime {
	startTime
	stopTime
}

autoConfChange {
	minTime
	varTime
	lvl
	joblvl
}

autoMakeArrows 0

autoRestart 0

autoRestartMin 10800
autoRestartSeed 3600

autoRestartSleep 1
autoSleepMin 900
autoSleepSeed 900

autoResponse 0
autoResponseOnHeal 0

autoSpell
autoSpell_safe

avoidGM_namePattern
avoidGM_near 0
avoidGM_near_inTown 0
avoidGM_talk 0
avoidGM_reconnect 1800
avoidGM_ignoreList

avoidList 1
avoidList_inLockOnly 0
avoidList_reconnect 1800

cachePlayerNames 1
cachePlayerNames_duration 900
cachePlayerNames_maxSize 100

clientSight 20

dcPause 1
dcOnDeath 0
dcOnDualLogin 0
dcOnDisconnect 0
dcOnEmptyArrow 0
dcOnMaxReconnections 0
dcOnMute 0
dcOnPM 0
dcOnZeny 0
dcOnStorageFull 1
dcOnPlayer 0
dcOnServerShutDown 0
dcOnServerClose 0
dcOnJobLevel
dcOnLevel

follow 0
followCheckLOS 0
followTarget
followEmotion 1
followEmotion_distance 4
followFaceDirection 0
followDistanceMax 6
followDistanceMin 3
followLostStep 12
followSitAuto 0
followBot 0
followRandom 0
followRandomDistance 4

itemsTakeAuto 2
itemsTakeAuto_party 0
itemsGatherAuto 2
itemsMaxWeight 89
itemsMaxWeight_sellOrStore 48
itemsMaxNum_sellOrStore 99
cartMaxWeight 7900
itemsTakeAuto_new 0
itemsTakeGreed 0

lockMap
lockMap_x
lockMap_y
lockMap_randX
lockMap_randY

route_escape_reachedNoPortal 1
route_escape_randomWalk 1
route_escape_shout
route_avoidWalls 1
route_randomWalk 1
route_randomWalk_inTown 0
route_randomWalk_maxRouteTime 75
route_maxWarpFee
route_maxNpcTries 5
route_teleport 0
route_teleport_minDistance 150
route_teleport_maxTries 8
route_teleport_notInMaps
route_step 15
route_tryToGuessMissingPortalByDistance 1

runFromTarget 0
runFromTarget_dist 6

saveMap
saveMap_warpToBuyOrSell 1
saveMap_warpChatCommand
memo1
memo2
memo3
memo4

shopAuto_open 0
shop_random 0
shop_useSkill 1

sitAuto_hp_lower 40
sitAuto_hp_upper 100
sitAuto_sp_lower 0
sitAuto_sp_upper 0
sitAuto_follow 0
sitAuto_over_50 0
sitAuto_idle 1
sitAuto_look
sitAuto_look_from_wall
sitTensionRelax 0

statsAddAuto 0
statsAddAuto_list
statsAddAuto_dontUseBonus 0
statsAdd_over_99 1

skillsAddAuto 0
skillsAddAuto_list

tankMode 0
tankModeTarget

teleportAuto_hp 10
teleportAuto_sp 0
teleportAuto_idle 0
teleportAuto_portal 0
teleportAuto_search 0
teleportAuto_minAggressives 0
teleportAuto_minAggressivesInLock 0
teleportAuto_onlyWhenSafe 0
teleportAuto_maxDmg 500
teleportAuto_maxDmgInLock 0
teleportAuto_deadly 1
teleportAuto_useSkill 3
teleportAuto_useChatCommand
teleportAuto_allPlayers 0
teleportAuto_notPlayers
teleportAuto_atkCount 0
teleportAuto_atkMiss 10
teleportAuto_unstuck 0
teleportAuto_lostTarget 0
teleportAuto_dropTarget 0
teleportAuto_dropTargetKS 0
teleportAuto_attackedWhenSitting 0
teleportAuto_totalDmg 0
teleportAuto_totalDmgInLock 0
teleportAuto_equip_leftAccessory
teleportAuto_equip_rightAccessory
teleportAuto_lostHomunculus
teleportAuto_useItemForRespawn
teleportAuto_item1
teleportAuto_item2

dealAuto 1
dealAuto_names
partyAuto 1
partyAutoShare 0
partyAutoShareItem 0
partyAutoShareItemDiv 0
guildAutoDeny 1

verbose 1
showDomain 0
showDomain_NPC parseMsg_presence
showDomain_Shop list
squelchDomains
verboseDomains
beepDomains
beepDomains_notInTown
friendlyAID
showTime
showTimeDomains
showTimeDomainsFormat
wx_map_maxAutoSize 300
wx_map_monsterSticking 1
wx_map_npcSticking 1
wx_map_playersSticking 1
wx_map_portalSticking 5
wx_map_route
wx_npcTalk
wx_captcha
showAllDamage 0
manualURL http://wiki.openkore.com/index.php?title=Manual
forumURL http://forums.openkore.com

logChat 1
logPrivateChat 1
logPartyChat 1
logGuildChat 1
logSystemChat 1
logEmoticons
logConsole 1
logAppendUsername 1
logAppendServer 0
monsterLog 0
logDead 1

chatTitleOversize 0
shopTitleOversize 0

sleepTime 10000

ignoreAll 0
itemHistory 0
autoTalkCont 1
noAutoSkill 0
portalCompile 1
portalRecord 2
missDamage 0

tankersList

repairAuto 0
repairAuto_list

status_mapProperty 0
status_mapType 0

removeActorWithDistance
monster_filter

######## Mercenary Support ########

mercenary_attackAuto 2
mercenary_attackAuto_party 1
mercenary_attackAuto_notInTown 1
mercenary_attackAuto_onlyWhenSafe 0
mercenary_attackDistance 1.5
mercenary_attackMaxDistance 2.5
mercenary_attackMaxRouteTime 4
mercenary_attackCanSnipe 0
mercenary_attackCheckLOS 0
mercenary_attackNoGiveup 0
mercenary_attackChangeTarget 1

mercenary_followDistanceMax 10
mercenary_followDistanceMin 3

mercenary_route_step 15

mercenary_tankMode 0
mercenary_tankModeTarget

mercenary_teleportAuto_hp 10
mercenary_teleportAuto_maxDmg 500
mercenary_teleportAuto_maxDmgInLock 0
mercenary_teleportAuto_deadly 1
mercenary_teleportAuto_unstuck 0
mercenary_teleportAuto_dropTarget 0
mercenary_teleportAuto_dropTargetKS 0
mercenary_teleportAuto_totalDmg 0
mercenary_teleportAuto_totalDmgInLock 0
mercenary_teleportAuto_attackedWhenSitting 0

######## Homunculus Support ########

homunculus_attackAuto 2
homunculus_attackAuto_party 1
homunculus_attackAuto_notInTown 1
homunculus_attackAuto_onlyWhenSafe 0
homunculus_attackDistance 1.5
homunculus_attackMaxDistance 2.5
homunculus_attackMaxRouteTime 4
homunculus_attackCanSnipe 0
homunculus_attackCheckLOS 0
homunculus_attackNoGiveup 0
homunculus_attackChangeTarget 1

homunculus_followDistanceMax 10
homunculus_followDistanceMin 3

homunculus_route_step 15

homunculus_tankMode 0
homunculus_tankModeTarget

homunculus_runFromTarget 0
homunculus_runFromTarget_dist 6

homunculus_StandByAuto 0
homunculus_teleportAuto_hp 10
homunculus_teleportAuto_maxDmg 500
homunculus_teleportAuto_maxDmgInLock 0
homunculus_teleportAuto_deadly 1
homunculus_teleportAuto_unstuck 0
homunculus_teleportAuto_dropTarget 0
homunculus_teleportAuto_dropTargetKS 0
homunculus_teleportAuto_totalDmg 0
homunculus_teleportAuto_totalDmgInLock 0
homunculus_teleportAuto_attackedWhenSitting 0

# Turn on/off homunculus autofeeding
homunculus_autoFeed 1
# Feed homunculus when meet the hunger value (homunculus_hunger > homunculus_return)
homunculus_hunger 15
# Return homunculus when meet the hunger value
homunculus_return 11
# In Wich maps should we allow feeding? (leave empty for any map)
homunculus_autoFeedAllowedMaps

# Turn on/off pet autofeeding
pet_autoFeed 1
# Feed pet when meet the hunger value
pet_hunger 25
# Return pet when meet the hunger value
pet_return 20

######## Block options ########
# You can copy & paste any block multiple times. So if you want to
# configure two attack skills, just duplicate the attackSkillSlot block.

attackSkillSlot {
	lvl 10
	dist 1.5
	maxCastTime 0
	minCastTime 0
	hp
	sp > 10
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	previousDamage
	stopWhenHit 0
	inLockOnly 0
	notInTown 0
	timeout 0
	disabled 0
	monsters
	notMonsters
	monstersCount
	maxAttempts 0
	maxUses 0
	target_hp
	target_whenStatusActive
	target_whenStatusInactive
	target_deltaHp
	inInventory
	isSelfSkill 0
	equip_topHead
	equip_midHead
	equip_lowHead
	equip_leftHand
	equip_rightHand
	equip_leftAccessory
	equip_rightAccessory
	equip_robe
	equip_armor
	equip_shoes
	equip_arrow
	manualAI 0
}

attackComboSlot {
	afterSkill
	waitBeforeUse
	dist 1.5
	isSelfSkill 1
	target_hp
	target_deltaHp
	monsters
	notMonsters
	monstersCount
}

doCommand {
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout
	disabled 0
	inInventory
	inCart
	inMap
	manualAI 0
}

useSelf_skill {
	lvl 10
	maxCastTime 0
	minCastTime 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
}

useSelf_skill_smartHeal 1

partySkillDistance 0..8

partySkill {
	lvl 10
	dist 3
	maxCastTime 0
	minCastTime 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	manualAI 0
	target
	target_hp
	target_isJob
	target_isNotJob
	target_whenStatusActive
	target_whenStatusInactive
	target_aggressives
	target_monsters
	target_timeout 0
	target_deltaHp
	target_dead 0
	inInventory
	isSelfSkill 0
}

monsterSkill {
	target
	maxUses
	# Skill Use Conditions, including isSelfSkill
	# Self Conditions
	# Target Monster Conditions
}

autoSwitch_default_rightHand
autoSwitch_default_leftHand
autoSwitch_default_arrow

# NOTE: In the case of two handed weapons, or no Shield,
#       duplicate the weapon name for 'rightHand'
# To attack with bare hands, specify "[NONE]" (without the quotes) for rightHand

autoSwitch {
	rightHand
	leftHand
	arrow
	distance
	useWeapon
}

equipAuto {
	topHead
	midHead
	lowHead
	leftHand
	rightHand
	leftAccessory
	rightAccessory
	robe
	armor
	shoes
	arrow
	monsters
	notMonsters
	monstersCount
	weight 0
	whileSitting 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
}

useSelf_item {
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout
	disabled 0
	inInventory
	manualAI 0
}

######## Autostorage/autosell ########

buyAuto {
	npc
	standpoint
	distance 5
	price
	minAmount 2
	maxAmount 3
	batchSize
	disabled 0
}

sellAuto 0
sellAuto_npc
sellAuto_standpoint
sellAuto_distance 5
sellAuto_npc_steps s

storageAuto 0
storageAuto_npc
storageAuto_distance 5
storageAuto_npc_type 1
storageAuto_npc_steps
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 50

npcTimeResponse
npcWrongStepsMethod 0

getAuto {
	minAmount
	maxAmount
	passive
}

######## Debugging options; only useful for developers ########

debug 0
debugPacket_unparsed 0
debugPacket_received 0
debugPacket_ro_sent 0
debugPacket_sent 0
debugPacket_exclude
debugPacket_include
debugPacket_include_dumpMethod
debugDomains
logToFile_Debug
logToFile_Errors
logToFile_Messages
logToFile_Warnings
history_max 50
macro_orphans terminate

**Comment by sctnightcore** [comment]
`XKore 1
`

NOW ! XKORE 0 is WORK!!!

**Comment by Nivlala** [comment]
# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore
XKore 0
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe

Like that?

**Comment by sctnightcore** [comment]
yes

**Comment by Nivlala** [comment]
Still the same issue hahaha

**Comment by oleokoong** [comment]
Reset your ip, because your connection laggy

**Comment by Nivlala** [comment]
Oh my its working now! Thanks alot people! Esp sctnightcore!
