### ISSUE TITLE
[iRO Chaos] Error "Did not received the buy result from server after buy packet was sent."

### ISSUE THREAD

**Issue by userix** [OpenKore/openkore#1190]
Getting the following error: "Did not received the buy result from server after buy packet was sent."

everytime the bot goes to buy stuff from the NPC, but the purchase still goes through successfully.

Using the latest version of openkore.

**Comment by sctnightcore** [comment]
Have an image?

**Comment by userix** [comment]
![image](https://user-images.githubusercontent.com/20689010/30902090-e56f2a9e-a31e-11e7-89d6-5bf9bfc5bbd1.png)

**Comment by userix** [comment]
![image](https://user-images.githubusercontent.com/20689010/30902102-ebd42d6c-a31e-11e7-8963-ffbe8ce36b5d.png)
This is a screenshot from the log file.  It already scrolled past the console history in openkore.

**Comment by sctnightcore** [comment]
I think it should be normal because trading is complete.

**Comment by userix** [comment]
Cool Thanks!  side question: is there a way to block the logging of certain NPC chat?  

Sep 26 22:45:00 2017][C] [prontera 116, 71] I am looking for the hero who returned from the expedition...

Everytime I walk by this NPC, it says this.

**Comment by Glikadin** [comment]
![openstuck](https://user-images.githubusercontent.com/20753532/30915381-52110a52-a39f-11e7-8d6e-b9bd3feb803a.jpg)
Autobuy works very bad. I cant buy Nepeta Cataria from a cat paw seller and use macros:
```
...
	if (@invamount(Nepeta Cataria) < 6000) {
		do move 92 53 aldeba_in
		pause 1
		do talk 0
		pause 2
		do talk resp 0
		pause 1
		do buy 2 10000
		pause 2
		do talk no
		pause 2
	}
...
```

Other tool dealers give an error , but buing items possibly.

**Comment by lordzpipo** [comment]
Using latest version from git, still got this problem, or i missing something?

@sctnightcore

**Comment by bunnyy00** [comment]
![dc](https://user-images.githubusercontent.com/25070736/32448363-a7874fea-c349-11e7-8c9e-d0a60bddd855.png)

This is my auto-buy config:

######## Autostorage/autosell ########

buyAuto arrow {
	npc geffen_in 77 167 Tool Dealer
	standpoint
	distance 5
	price
	minAmount 80
	maxAmount 5000
	batchSize
	disabled 0
}

sellAuto 0
sellAuto_npc
sellAuto_standpoint
sellAuto_distance 5
sellAuto_npc_steps s

storageAuto 1
storageAuto_npc geffen 120 62 Kafra Employee
storageAuto_distance 5
storageAuto_npc_type 1
storageAuto_npc_steps
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 50

I am using the latest openkore 3 November 2017, but sill having this issue , after buying arrow, kore will keep disconnected and reloging and doing the same thing.

Does anyone know how to fix this? Thanks!
@sctnightcore please help

**Comment by bunnyy00** [comment]
![dc2](https://user-images.githubusercontent.com/25070736/32448666-7adb5774-c34a-11e7-9d70-ab890381d6d4.png)

**Comment by sctnightcore** [comment]
Download new openkore and test again ! .

**Comment by lututui** [comment]
If this is happening on other servers other than iRO Chaos, please disclose

**Comment by Fadreus** [comment]
Solved.

**Comment by emsjustin** [comment]
This happen when the timeouts file didn't have this lines:

ai_buyAuto_wait_after_packet_giveup 15
ai_sellAuto_wait_after_packet_giveup 15

Probably using an old timeouts.txt

**Comment by alisonrag** [comment]
iRO updated and since from some moment in 2019 this error stoped to happens
