### ISSUE TITLE
[iRO Chaos] "[teleToDest] There are config keys not defined, plugin won't be activated."

### ISSUE THREAD

**Issue by userix** [OpenKore/openkore#1192]
[Sep 27 09:26:51 2017.68] Loading tables\iRO\quests.txt...
[Sep 27 09:26:52 2017.20] Loading tables\iRO\msgstringtable.txt...
[Sep 27 09:26:52 2017.28] Loading tables\hateffect_id_handle.txt...
[Sep 27 09:26:52 2017.31] Loading tables\hateffect_name.txt...
[Sep 27 09:26:52 2017.34] Loading control\macros.txt...
[Sep 27 09:26:52 2017.36] [macro] hooking to AI_pre
**[Sep 27 09:26:52 2017.37] [teleToDest] There are config keys not defined, plugin won't be activated.**
[Sep 27 09:26:52 2017.37] All files were loaded

Been getting the bolded error message in bold since I updated to the newest version of openkore.

**Comment by fadreus** [comment]
If you are using that plugin, check your `config.txt` either to use or not
If you are not using it, simply delete that plugin or disabled it in `sys.txt`

Refer here
https://github.com/OpenKore/openkore/tree/master/plugins/teleToDest

**Comment by sctnightcore** [comment]
plugins\teleToDest\readme.txt
