### ISSUE TITLE
pRO server got this far

### ISSUE THREAD

**Issue by yakisoba2009** [OpenKore/openkore#1194]
What seems to be the problem?
![image](https://user-images.githubusercontent.com/32344188/30938835-0c271f4e-a40e-11e7-8dca-21cda064c25d.png)

![image](https://user-images.githubusercontent.com/32344188/30938780-d5c425fa-a40d-11e7-9c63-a4459a203182.png)

**Comment by bebox123** [comment]
![image](https://user-images.githubusercontent.com/30216263/30942946-a7b3d3e0-a3e5-11e7-8c33-a7368fd8a10b.png)

Mine is like this but I had some logs here to show to you proof that this was working before the update and now it's not working in xkore 1. This is in ROPH btw.

**Comment by yakisoba2009** [comment]
How about in xkore 0? Also not working? How were you able to inject netredirect?

**Comment by alisonrag** [comment]
continue in #1225

**Comment by imthemenace** [comment]
bebox123 what is your config can you share it it here or pm me your config tnx
