### ISSUE TITLE
Disconnected from server.

### ISSUE THREAD

**Issue by gr4ndmasterz** [OpenKore/openkore#1197]
I downloaded the updated bot but somehow after sometime , it keeps on disconnecting.

Disconnected from Map Server, connecting to Account Server in 43 seconds... Connecting to Account Server... Connecting (128.241.92.133:6800)... connected Disconnecting (128.241.92.133:6800)...disconnected The server has denied your connection for unknown reason (18). Timeout on Account Server, reconnecting. Wait 30 seconds...

**Comment by NandoPrates** [comment]
me too

**Comment by frostbitez88** [comment]
Same problem here

**Comment by blakbord** [comment]
same here..

**Comment by hendo916** [comment]
[Sep 27 17:10:26 2017.66] You have gained 387/235 (0.15%/0.14%) Exp
[Sep 27 17:10:26 2017.66] Item Appeared: Well-baked Cookie (0) x 1 (70, 124)
[Sep 27 17:10:27 2017.85] Unknown #51388 uses Arrow Repel on Player MalboroRED (0) (Dmg: Miss) (Delay: 1296ms)
[Sep 27 17:10:30 2017.72] Failed to take Well-baked Cookie (0) from (71, 123) to (70, 124)
[Sep 27 17:10:30 2017.29] Target died
[Sep 27 17:10:31 2017.25] Disconnected from Map Server, connecting to Account Server in 30 seconds...
[Sep 27 17:11:01 2017.26] Connecting to Account Server...
[Sep 27 17:11:01 2017.27] Connecting (128.241.92.133:6800)... [Sep 27 17:11:01 2017.32] connected
[Sep 27 17:11:01 2017.45] Disconnecting (128.241.92.133:6800)...[Sep 27 17:11:01 2017.45] disconnected
[Sep 27 17:11:01 2017.46] The server has denied your connection for unknown reason (18).
[Sep 27 17:11:13 2017.33] Timeout on Account Server, reconnecting. Wait 31 seconds...
[Sep 27 17:11:44 2017.34] Connecting to Account Server...
[Sep 27 17:11:44 2017.36] [reconnect] Login retry number 2, setting reconnect timeout to 74 seconds.
[Sep 27 17:11:44 2017.36] Connecting (128.241.92.133:6800)... [Sep 27 17:11:44 2017.41] connected
[Sep 27 17:11:44 2017.56] Disconnecting (128.241.92.133:6800)...[Sep 27 17:11:44 2017.57] disconnected
[Sep 27 17:11:44 2017.57] Error: The server still recognizes your last connection


Here is what my log looks like as I am having the same issue. Thanks for all you do !

**Comment by kaguluhan** [comment]
I found out that the problem lies on picking up items. So better check it out.

**Comment by don00000** [comment]
Any update?

**Comment by geosper** [comment]
I tried setting the items takeauto to 0 and my bot is not disconnecting, I think the problem is upon picking up loots like kaguluhan said

**Comment by don00000** [comment]
@geosper so you wouldn't be able to take the items after killing the monster?

**Comment by oleokoong** [comment]
If you want to gain level, just temporary disable pickup... devs is working on it

**Comment by luanfx** [comment]
Same problem here.

**Comment by don00000** [comment]
Still getting disconnected after 3-5monsters :(

**Comment by don00000** [comment]
I'll just wait for the official release :)

**Comment by Glikadin** [comment]
Same problem

**Comment by ponxponx** [comment]
any update for iro restart ???

**Comment by popano** [comment]
Chill man. Devs are working on it.

**Comment by blakbord** [comment]
waiting for the updates.. :)

**Comment by jonelle1990** [comment]
always Dc when picking up items any updates of this ?

**Comment by jokerjester10** [comment]
just wait, be patient and don't spam, they already know what's happening.

**Comment by drunkenhammer** [comment]
We all got items/zenys from the previous weeks (assuming they are farmers). We should just take a break from botting for now.

**Comment by something990** [comment]
any update?
i also got the same issue :)

**Comment by Naozumi2k** [comment]
I've got the solution!
Simply remove the line
`0362 0367`
from tables/iRO/Restart/shuffle.txt in the end of file and restart openkore!

**Comment by hendo916** [comment]
For me at least that did not help as i am still getting disconnected on looting.

**Comment by geosper** [comment]
i tried deleting 0362 0367 by ctrl+F and set itemsTakeAuto 2 i think its working

You are now attacking Monster Thief Bug (0)
[ 45/100] You attack Monster Thief Bug (0) (Dmg: 169) (Delay: 400ms)
[ 45/100] You attack Monster Thief Bug (0) (Dmg: 164) (Delay: 400ms)
[ 45/100] Monster Thief Bug (0) attacks you (Dmg: 61) (Delay: 288ms)
[ 36/100] You attack Monster Thief Bug (0) (Dmg: 161) (Delay: 400ms)
You used Item: Red Potion (6) x 1 - 147 left
Inventory Item Removed: Red Potion (6) x 1
Target died
You have gained 157/177 (0.30%/0.53%) Exp
Item Appeared: Mushroom Spore (0) x 1 (21, 151)
Item Appeared: Worm Peeling (1) x 1 (22, 149)
Item Appeared: Red Herb (2) x 1 (20, 150)
Item Appeared: Rat Tail (3) x 1 (21, 151)
Item Appeared: Animal Skin (4) x 1 (22, 149)
Item added to inventory: Mushroom Spore (13) x 1 - Event
Item added to inventory: Red Herb (15) x 1 - Usable Heal
Item added to inventory: Rat Tail (12) x 1 - Event

**Comment by ewankOwz** [comment]
^tried this step. seems to be working fine i guess.

**Comment by sctnightcore** [comment]
@Naozumi2k  work ?

**Comment by Sby-EasyStuff** [comment]
I don't have the `0362 0367` line in **tables/iRO/Restart/shuffle.txt** and _ItemsTakeAuto_ is setted on 2 but it still doesn't work :(

**Comment by browniezzz** [comment]
Deleting 0362 0367 in tables/iRO/Restart/shuffle.txt and it works.
Nice work
Thank you

**Comment by hendo916** [comment]
I want to correct my post as this does work for me now ; i deleted it in the tables/iRO/shuffle.txt by mistake . So good job thanks for the fix!

**Comment by Bombahee** [comment]
it works deleting these numbers, 0362 0367

0362 0367 <--- just being curious, what are these numbers for? is it safe to delete this?

**Comment by hideman012** [comment]
not work

**Comment by hideman012** [comment]
i try remove it yes not work

**Comment by hideman012** [comment]
ahh maybe i wrong i will do again
thx @jfzhou90

**Comment by hideman012** [comment]
i do together does work

**Comment by something990** [comment]
yup... its working thanks :D

**Comment by CShigaki** [comment]
Is there any fix to this for bRO?
