### ISSUE TITLE
Adding Strawberry lib path to @INC in openkore

### ISSUE THREAD

**Issue by joecabezas** [OpenKore/openkore#1198]
I have installed `Protocol::Websocket` via Strawberry perl in windows, but after starting openkore via wxstart.exe, it says:

`
WebSocket server failed to start: Can't locate Protocol/WebSocket.pm in @INC (@INC contains: plugins/webMonitor plugins/macro plugins/eventMacro src src/deps ...
`

but it does not mention the Strawberry location, how can I add it to the @INC?

already tried:

- adding a system env variable:

name: `PERL5LIB`
value: `C:\strawberry\perl\lib;C:\strawberry\perl\site\lib;C:\strawberry\perl\vendor\lib`

**Comment by alisonrag** [comment]
add in main .pl of plugin

`use lib 'C:/strawberry/perl/site/lib';`

**Comment by joecabezas** [comment]
Other thing I tried

  - modify start.pl

replace line:
```
push @INC, "." if (!$hasCurrentDir);
```

with:
```push @INC, "." if (!$hasCurrentDir);
push @INC, "C:\strawberry\perl\lib";
push @INC, "C:\strawberry\perl\site\lib";
push @INC, "C:\strawberry\perl\vendor\lib";
```

opened wxstart.exe, same error

**Comment by joecabezas** [comment]
@alisonrag

that worked, but it has to be a way to do it without modifying the plugin code :/

**Comment by NandoPrates** [comment]
try openkore.pl

**Comment by joecabezas** [comment]
@NandoPrates what of the options?, @alisonrag suggestion?

**Comment by joecabezas** [comment]
well I was able to add paths into @INC with your help, thanks!
