### ISSUE TITLE
Opencore stuck and no attacking (ubuntu)

### ISSUE THREAD

**Issue by shacalif** [OpenKore/openkore#1201]
Hi guys, I have the following behavior. I installed openkore in **ubuntu** and after some time (minutes or sometime a couple of hours) my char get stuck and don't attack anything only my slave attack. The same config files works pretty fine on Windows client. 

When I run two instances of openkore on the same linux box the problem is worst, stuck almost always but on Windows I don't see any problems.

Of course everything is configured to autoattack, randomroute, etc...

Please check the attached picture, left window is the ubuntu terminal (ssh to linux box) and right is the Windows client.

![issue](https://user-images.githubusercontent.com/32203940/30962637-eceb3daa-a420-11e7-82f7-beaddbf16bbf.jpg)

Do I'm missing something?

Versions:
4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
This is perl 5, version 22, subversion 1 (v5.22.1)
libcurl 7.47.0

Latest openkore cloned with git

Thanks in advance!!

**Comment by joecabezas** [comment]
I have no idea wat it can be happening, but I suggest you to re upload the images with `debug 1` set in config.txt, good luck!

**Comment by lututui** [comment]
What's `aiv` at that moment?

**Comment by alisonrag** [comment]
any update?

**Comment by alisonrag** [comment]
closed because the owner of issue do not provided more informations
