### ISSUE TITLE
Pserver Connection Issue

### ISSUE THREAD

**Issue by KiyoHD** [OpenKore/openkore#1207]
First of all im trying to get it running on YunaRO.
Followed the whole tutorial to get it running for Pserver.
I think the problem is the Servertype. I got from PE Explorer this date 2013_08_06
so i need to fill in kRO_RagexeRE_2013_08_06a as the servertype right?
Error: Cant load servermessage write 'kRo'.

I tried from another tutorial the other "Servertypes"
# 0 = normal server, 1 = oRO, 2 = pRO, 3 = eAthena/Freya,
# 4 = new Freya, 5 = new eAthena, 6 = new oRO
# 7 = Aegis 10.x with padded packets, 8 = kRO
# 9 = eAthena, 10 = vRO, 11 = euRO
Error: Connection failed, please check the login settings.

Both didn't worked, first time for me doing this followed all as stated from openkore site and others too.
Hope you could give me any suggestions or if i get wrong server informations maybe the right ones.

Thanks in advance.

**Comment by sctnightcore** [comment]
well -*- 
use with RagexeRE_2013_08_07a !

**Comment by KiyoHD** [comment]
Thank you^^ but now this:

Please start the Ragnarok Online client (ragexe.exe)
Ragnarok Online client found
Waiting for the Ragnarok Online client to connect to X-Kore

after that nothing happens anymore :D..

**Comment by sctnightcore** [comment]
xkore 0 ! 

test it !
