### ISSUE TITLE
Timeout to map server iRO Chaos

### ISSUE THREAD

**Issue by ragnarokfan** [OpenKore/openkore#1208]
![image](https://user-images.githubusercontent.com/32195383/30991719-dc8876a6-a4ae-11e7-8969-407c3f853340.png)

**Comment by Nipodemos** [comment]
updated openkore???
type **version** on console, what shows up?

**Comment by ragnarokfan** [comment]
*** OpenKore what-will-become-2.1 ( version ctime:2017_09_28 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

**Comment by shacalif** [comment]
Same here, they (iRO) changed something with today maintenance.

Just wait for an openkore update.

**Comment by ragnarokfan** [comment]
If I did just study computer programming, I would really like to help... I'm trying to decode these codes myself but...... no skills lol

**Comment by sctnightcore** [comment]
download new openkore ! and test Again !

**Comment by ragnarokfan** [comment]
![image](https://user-images.githubusercontent.com/32195383/30992997-5332224c-a4b5-11e7-82a3-4234a7cb49f0.png)

what does this mean?

**Comment by ragnarokfan** [comment]
I am still timing out sir...

**Comment by ragnarokfan** [comment]
I already downloaded the latest one but still the same it is timing out on the map server..

**Comment by appapie** [comment]
Timeout on map server for me also.  Today's maintenance update definitely did something again like last week.

**Comment by sctnightcore** [comment]
sry ! I referenced wrong

**Comment by ragnarokfan** [comment]
I tried packet sniffing but to no avail lol

**Comment by sctnightcore** [comment]
http://www.playragnarok.com/news/newslist.aspx#n991

wait allanon fix !

**Comment by Rovejoe** [comment]
Me too have the same problem. after new updates for IRO  when i start bot in the morning it show me "Timeout on map server, connecting to account server " seem like GM always updates new patch .. hahha

**Comment by Charles808** [comment]
I'm in iRO Thor Server. I have the same issue, but after updating to branch : iro_update, everything working again.

**Comment by Zelecktor** [comment]
yes please!!! i have the same issue. We need updates asap!

**Comment by sctnightcore** [comment]
#1209 @Zelecktor

**Comment by riyuno828** [comment]
Hi Everyone, this is my first time bot. myself also facing this timeout problem... hope will have new update soon =D

**Comment by heavenrealms** [comment]
Hi, I'm new here. I was wondering did u guys fixed this issue yet?
I've tried #1209 but I'm still getting the timeout error ;(

**Comment by sctnightcore** [comment]
@heavenrealms  download new openkore ! and test again

**Comment by heavenrealms** [comment]
@sctnightcore fixed it! Thanks !

**Comment by harhail666** [comment]
HI do you have an update bot for IRO
