### ISSUE TITLE
Iro Chaos New Patchnotes 09-28-2017 Time out Server

### ISSUE THREAD

**Issue by Baimonza** [OpenKore/openkore#1210]
![timeout](https://user-images.githubusercontent.com/32193462/30995535-17a8ea64-a4e5-11e7-8430-c44c9b9bab4d.jpg)

**Time Out Map Server**

**Comment by sctnightcore** [comment]
wait allanon to fix it !

**Comment by Baimonza** [comment]
ok

**Comment by lowkeeme** [comment]
Yeah, same here.

![untitled](https://user-images.githubusercontent.com/30202014/30997112-2716637e-a4f8-11e7-8885-3fdd572178be.png)

Let's just wait for the fix of the developers.

**Comment by jomarlorica** [comment]
still they change the system again. @github @allanon  @dev need your help hehe

**Comment by topekismail** [comment]
same prob here...
need help plssss...
T_T

**Comment by jomarlorica** [comment]
lets wait. they will updated us if its done

**Comment by hakunamatata11** [comment]
wow ty allanon

**Comment by Rovejoe** [comment]
@hakunamatata11 you know how to change  ?

**Comment by fadreus** [comment]
Thanks for the quick update allanon ^^
Here how to update (For dummies).

- Click #1209 

- Click `iRO renewal crypt keys`

- Click `View` for all changed files

- Copy - Paste - Save in your openkore folder

**Comment by hakunamatata11** [comment]
yes its work 10000000000%!!!!. thx @allanon  @fadreus ^^

**Comment by hakunamatata11** [comment]
btw saya orang indo. makasih

**Comment by Rovejoe** [comment]
@allanon @fadreus thnks. work ! thnks help.

**Comment by jomarlorica** [comment]
@fadreus @allanon sorry im noob on this. can you update the file like the link of openkore for us to download the whole file of openkore like this one you made.  https://github.com/OpenKore/openkore thanks a lot!

**Comment by ir0n** [comment]
Work totally fine! Thank you developers!

@jomarlorica You can see https://github.com/OpenKore/openkore/pull/1209 for further help.

**Comment by Glikadin** [comment]
Download the update on GitHub pls

**Comment by VBPardini** [comment]
![image](https://user-images.githubusercontent.com/31735457/31038659-76c6c4bc-a54e-11e7-9296-4d0c449f5aa3.png)

no luck :/

**Comment by Rovejoe** [comment]
@VBPardini why ? u already test ? im still ok ..

**Comment by VBPardini** [comment]
@Rovejoe I don't know, i just download the lastest version and....
![image](https://user-images.githubusercontent.com/31735457/31041061-d813bd30-a565-11e7-9f4e-352895c5fa90.png)

**Comment by Rovejoe** [comment]
@VBPardini no update for openkore .. u need manual update that .. so far, me ok, bcoz me update it manually ..

**Comment by VBPardini** [comment]
@Rovejoe Do you have a link for a manually update tutorial?

**Comment by Rovejoe** [comment]
@VBPardini nope

**Comment by FireflySkye** [comment]
@VBPardini page up. Read it.

**Comment by VBPardini** [comment]
@FireflySkye I see @fadreus post, but i already copy and past the "1406 code lines" in tables/iRO/recvpackets.txt and...
![image](https://user-images.githubusercontent.com/31735457/31042638-edb0092e-a582-11e7-9a84-ddc326922586.png)

**Comment by fadreus** [comment]
Of course it didn't work.
You update one file only.
There are six files, only four for renewal.

LOL

**Comment by turdoftheweek** [comment]
@VBPardini go back to #1209 and check the other files to update there is 4 files in total that you need to change

**Comment by dersheys** [comment]
Hi guys, I already changed the four files, double-checked it, read all the threads, yet I'm still time out on MapServer. Any help please?

**Comment by kimer19** [comment]
same issue @dersheys  i already changed the all files too 
help us thanks

**Comment by fadreus** [comment]
It suppose to work..
Chaos Server: 1300+ Player (no bot) and now server 2100+ (after fix).
Check and re-check, check again.
Sometimes missing 1 letter, number, symbol or incorrect path can cause the whole thing to malfunction.
Don't use mixed of files (getting from friends etc) or download from elsewhere (modded by other) unless you know what you are doing..

Even asking for help, I think dev team will suggest you to download the latest one and apply this fix (You can donwload tables from Branch: iro_update until they merge pull to master if in doubt something else you changed).

And make sure to use XKore 0.

**Comment by ir0n** [comment]
@kimer19 @dersheys 

See lowkeemee comments here https://github.com/OpenKore/openkore/pull/1209 and follow

**Comment by dersheys** [comment]
Hi guys, I followed exactly lowkeemee's comments previously and tried again but it's still a timeout.
I'm using it on my mac, via my Mac terminal program, so im not sure what XKore version is about. 

@ir0n  i didn't have notepad++ as per lowkeemee's instructions but i downloaded a similar coding app for mac.

Thanks, any help will really be appreciated :)

**Comment by fadreus** [comment]
Why you guys so weird, download stuff to just open document text file.
NopePad/WordPad is fine. Breast Pad / Mouse Pad won't work though.
Since you don't know XKore, I think you use the default setting = 0

About Mac.. Hmm.. Expensive stuff sure works differently..
Hahahahaha.. Good luck with Mac. Can't help with that.

Not sure if anyone else can help, it's pretty much the same thing to do.
If it didn't work, something wrong at your stuff there. Just download Latest Kore from master branch and then download tables from iro_update branch.

If that not working, try running at other computer.
If else fail, it's time to move on.
Don't use illegal program XD Hahahahaha.. JK :P

**Comment by ir0n** [comment]
@dersheys Not sure whether these TXT might work with yours  

http://www.filedropper.com/servers_4
http://www.filedropper.com/iro

**Comment by kimer19** [comment]
@dersheys  my bot's is working now :D try to recopy and paste the following updated files (go here)
![bot](https://user-images.githubusercontent.com/32207042/31061485-e57f9608-a75c-11e7-8b03-3221e37a4631.jpg)



@fadreus thanks guys

**Comment by icewater99** [comment]
any ideas for this stuck
![untitled](https://user-images.githubusercontent.com/31179151/31070115-da2b152e-a767-11e7-982e-776300578610.png)

**Comment by fadreus** [comment]
@icewater99 Wrong server bro.
This iRO Chaos, not pRO New Chaos.

You might wanna take a look on what they call "Pixel Bot".
I heard it's working on pRO.
From what I've read, there is no update for pRO.
