### ISSUE TITLE
[eventMacro] Condition InInventory and InInventoryID not workiing correctly

### ISSUE THREAD

**Issue by Nipodemos** [OpenKore/openkore#1215]
###### Summary: 
InInventory condition is being true when it should not be
###### Affected configuration(s)/ file(s):
eventMacro.txt
InInventory.pm
###### Impact:
one macro that i use, is triggered when it's not supposed to trigger... making the bot go to the wrong place in the wrong time
###### Expected Behavior:
this macro be triggeres only once, when you dont have the item "Emblema do Grupo Valhalla" in inventory
###### Actual Behavior:
Even when this item is on inventory, it keeps triggering, should not do this
![image](https://user-images.githubusercontent.com/11494727/31022903-a13bfb92-a510-11e7-983d-7d508f6bc0df.png)
the item it is on inventory
###### Steps to Reproduce:
```
automacro EdenJoinMoveNpc {
	InInventory "Emblema do Grupo Valhalla" = 0
	InInventoryID 2414 = 0 #novice shoes
	exclusive 1
	BaseLevel >= 12
	ConfigKeyNot EdenMember yes
	NpcNotNear /Lenore|Lime/
	JobIDNot 0 #novice
	call {
		do move moc_para01 &rand(33,35) &rand(25,27) #good position Eden
	}
}

automacro EdenJoinTalkNpc {
	InInventory "Emblema do Grupo Valhalla" = 0
	ConfigKeyNot EdenMember yes
	exclusive 1
	NpcNear /Lenore|Lime/
	call {
		do talk $.NpcNearLastBinId
		do talk resp 1
		do talk resp 0
		do talk text lolol
		do talk text lolol
		do talk resp 4
		do iconf 6219 0 0 0 #Emblema do Grupo Valhalla
		do conf -f EdenMember yes
	}
}
```

also, this is what shows when you check status of the automacro:
```
eventMacro auto EdenJoinMoveNpc
[eventMacro] Printing information about automacro 'EdenJoinMoveNpc'.
Number of conditions: '6'
Has event type condition: 'no'
Number of true conditions: '5'
Number of false conditions: '1'
Is triggered: '0'
----  Parameters   ----
1 - priority: '0'
2 - overrideAI: '0'
3 - disabled: '0'
4 - time: '1506698347'
5 - delay: '0'
6 - orphan: 'terminate'
7 - macro_delay: '1'
8 - run-once: '0'
9 - timeout: '0'
10 - CheckOnAI: 'auto'
11 - repeat: '1'
12 - call: 'tempMacro43'
13 - exclusive: '1'
----  Conditions   ----
1 - InInventoryID: 'true'
2 - InInventoryID: 'true'
3 - BaseLevel: 'true'
4 - ConfigKeyNot: 'true'
5 - JobIDNot: 'true'
6 - NpcNotNear: 'false'
----  AI check states   ----
Check on AI off: 'no'
Check on AI manual: 'no'
Check on AI auto: 'yes'
----  End   ----
```
Notice that in this automacro the only false option is the npcnotNear, because it is already near the bot

and the other automacro:

```
eventMacro auto EdenJoinTalkNpc
[eventMacro] Printing information about automacro 'EdenJoinTalkNpc'.
Number of conditions: '3'
Has event type condition: 'no'
Number of true conditions: '3'
Number of false conditions: '0'
Is triggered: '1'
----  Parameters   ----
1 - priority: '0'
2 - overrideAI: '0'
3 - disabled: '0'
4 - time: '1506697422'
5 - delay: '0'
6 - orphan: 'terminate'
7 - macro_delay: '1'
8 - run-once: '0'
9 - timeout: '0'
10 - CheckOnAI: 'auto'
11 - repeat: '1'
12 - call: 'tempMacro44'
13 - exclusive: '1'
----  Conditions   ----
1 - InInventory: 'true'
2 - ConfigKeyNot: 'true'
3 - NpcNear: 'true'
----  AI check states   ----
Check on AI off: 'no'
Check on AI manual: 'no'
Check on AI auto: 'yes'
----  End   ----
```

@Henrybk you can look this when you have free time plz?

**Comment by fadreus** [comment]
@Henrybk Can you also take a look at quest condition and `&questCompleteCount` too?
Right now I'm using macro to trigger eventMacro to make it work around but if possible I prefer to use eventMacro only. 

Issues with `QuestHuntCompleted` & `&questCompleteCount` 
Last time I use `QuestHuntCompleted` as **condition**, each time after taking quest _(kill count 0)_ it will trigger `QuestHuntCompleted.`

Then I do macro log `&questStatus` to see what openkore define this quest, even with kill count 0, it see as `complete` _(not 0/150, just 0)_ while it suppose to be `incomplete,` right after I killed 1 (_kill count form 0 become 1/150)_ then only it show incomplete.

Is it due servertype or I just have to deal with it?
I didn't see anyone talking about this and I just remembered about this recently.

**Comment by c4c1n6kr3m1** [comment]
Looks like old map change problem, when inventory is  cleared, not ready.

**Comment by Nipodemos** [comment]
which means the problem is on openkore, in the inventory part?

**Comment by c4c1n6kr3m1** [comment]
Try to reproduce first
