### ISSUE TITLE
[plugin][development] tips to test plugin without connecting

### ISSUE THREAD

**Issue by joecabezas** [OpenKore/openkore#1218]
hello, I am developing a plugin, and I wat to call my iterate function, but I want to avoid connecting to the actual game which already happend when hook `mainLoop_post` is called

there is any other way (or hook) to test my plugin loop, without connecting game server?

**Comment by joecabezas** [comment]
maybe just a while()

**Comment by joecabezas** [comment]
yeah a simple while() works fine for now, but wonder if there is a loop before game server connection for plugins to work even when trying to relog

**Comment by alisonrag** [comment]
http://openkore.com/index.php/Hook

start3 or initialized should be used

**Comment by joecabezas** [comment]
but that is not a loop, just a hook, I am using start3 to initialize my plugin, but need the loop without connecting to the game

**Comment by joecabezas** [comment]
closing this, got it working with a temporal while(1), thanks
