### ISSUE TITLE
My bot stuck in pay_fild01 and it doesnt move at all i borrow pictures here with the same problem with me because i dont have pics pls is there anyone here could help me to find a way to fix it?

### ISSUE THREAD

**Issue by aldebfabian05** [OpenKore/openkore#1219]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by fadreus** [comment]
didyoujustwriteeverythingatthetitlenotinthebody?yousaidgotpicturewhereisthepicture?
whydontyougivemoredetailorsimplyreadtheprevioussectionatforumthereortryusegoogle.onedoesnotsimplywriteeverthingatthetitleandleavethebodysection.oryoucantryreadwhatyoujustpostwhatdoyouexpectpeopletohelpyouifyoudonthelpyourselfhelpuseunderstandyouorlearnthebasicyaohahahahaha

**Comment by sctnightcore** [comment]
server ?

**Comment by aldebfabian05** [comment]
ROPH new chaos

Haha! I dont know how to post the picture omg!

**Comment by fadreus** [comment]
![untitled](https://user-images.githubusercontent.com/32188494/31056910-8648df14-a70c-11e7-9f7a-8288dd853e06.png)

**Comment by sctnightcore** [comment]
No development pRO  ! 
Close your issue.
