### ISSUE TITLE
Error: Packet Tokenizer: Unknown switch: 0AE0

### ISSUE THREAD

**Issue by bjron01** [OpenKore/openkore#1220]
Hi Guys,

Can you anyone help me. I encountered this error "Packet Tokenizer: Unknown switch: 0AE0" when i run the bot. this is the first i run it. maybe i missed something.

I try to run the packet extractor also encounter error "Cannot find the packet length function"

Connecting to Account Server...
Connecting (128.241.92.133:6800)... connected
Packet Tokenizer: Unknown switch: 0AE0

Thanks in advance for your help.

**Comment by sctnightcore** [comment]
iRO restart ?

**Comment by bjron01** [comment]
Yes I restart iRO and i also restart my PC but still doesn't work. the same error.

**Comment by bjron01** [comment]
I download opencore from here https://github.com/OpenKore/openkore but still doesn't work. 

can you confirm if the link above is where I can download the latest version? if not, can you provide me a link where i can download the newer version?

**Comment by sctnightcore** [comment]
download ! = https://github.com/OpenKore/openkore  
![image](https://user-images.githubusercontent.com/23263315/31057208-230043e6-a709-11e7-9620-b41daa4b0d04.png)

**Comment by kutchibashi** [comment]
its not working. i've already download the following link, but it says connecting to map server. please help.

**Comment by bjron01** [comment]
@sctnightcore Yes i downloaded from here https://github.com/OpenKore/openkore but still doesn't work.
  here's some details of my bot.
Server:
[Ragnarok - Re:Start]
ip 128.241.92.133
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 144

Config
master Ragnarok - Re:Start
server
username 
password 
loginPinCode 
char

**Comment by sctnightcore** [comment]
@bjron01  Do not modify server.txt. !

**Comment by kutchibashi** [comment]
@sctnightcore ive already download the new openkore. and its the same. cant connect on map server

**Comment by bjron01** [comment]
I modify the server.txt so i can connect to PH RO Server.
[Ragnarok - Re:Start]
ip 128.241.92.133
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 144

Is there something wrong with the details of server.txt?

**Comment by fadreus** [comment]
I can see few problems here.
iRO RE:Start doesn't mean restart your bot, ro and PC 😂😂😂
If you wanna modify servers.txt for pRO, better take a look at what people call "Pixel Bot".

**Comment by sctnightcore** [comment]
HAHAHA WTF @fadreus

**Comment by lututui** [comment]
You guys trying to use the server iRO_Restart for pRO? That's not goint to work.

**Comment by alisonrag** [comment]
continue #1225
