### ISSUE TITLE
xKore 1 and xKore 3 not have suport to encryptMessageID

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#1227]
###### Summary: 
openkore xkore 1 and xkore 3 not have suport to encryptMessageID

###### Affected configuration(s)/ file(s):
network\xkore
network\xkoreProxy

###### Impact:
no one can connect to a server that need encryptMessageID 

###### Expected Behavior:
connect to servers using encryptMessageID

###### Actual Behavior:
kore not work with encryptMessageID when we connect to a server that need.

###### Steps to Reproduce: 
Just try to use xKore 1 or 3 in a server that have crypt keys

References:
#1174 
#1160 
#1133 
#977 
#540 

innitial support:
https://github.com/alisonrag/openkore/commit/3034f398f7aed74835c24ec24b171d2ee8a0ba88

bug in map with players when login, kore lost itself in keys or maybe in packet '-'

**Comment by joecabezas** [comment]
what help do you guys need, never used xkore before

**Comment by bebox123** [comment]
[console.txt](https://github.com/OpenKore/openkore/files/1350562/console.txt)

This is the logs that I got, it is in xkore 1, however after the update of Philippine Ragnarok Online it seems that xkore 1 won't connect anymore as seen down below the italicized text.

**Comment by alisonrag** [comment]
@joecabezas 
i have started just, you can start trying to connect with the following files 
https://github.com/alisonrag/openkore/commit/506c8cb1538874b1f1d3178a0044e80c091392dc

**Comment by Raguto** [comment]
If I am able to use xKore 1 on Restart after this gets fixed then I will try to help as well, just tell me what I need to do as I do not know, I don't mind dedicating some time to this.

**Comment by sctnightcore** [comment]
#1227

**Comment by corexkore** [comment]
@bebox123 kindly upload your openkore folder(don't forget to remove user account) and lemme check your settings. I'll see what I can do

**Comment by bebox123** [comment]
@corexkore  the whole folder? Really bruh? Haha and you joined 2 hours ago.

**Comment by Mustardfreedom** [comment]
Would really be nice to have this resolved eventually. xkore seems to be a pretty niche thing. As alisonrag say this started happening when Re-Start started using cryptkeys a bit back. My guess is that xkore was just overlooked when the encrypted packets were found.

**Comment by alisonrag** [comment]
@all 
start from here
https://github.com/alisonrag/openkore/commit/3034f398f7aed74835c24ec24b171d2ee8a0ba88

**Comment by elitecasaj00** [comment]
@alisonrag – xKore 3 is hit and miss:  I was able to run xKore 3 long enough to kill a single monster and on reloading the client and OK, I was able to again run xKore 3 long enough to gather an item.  Other times, I simply receive a timeout disconnect.

[console.txt](https://github.com/OpenKore/openkore/files/1354510/console.txt)

**Comment by sctnightcore** [comment]
#1236

**Comment by alisonrag** [comment]
Working with bRO:
https://github.com/alisonrag/openkore/tree/xkore-proxy-cryptkeys

Need test in iRO, maybe some packets are different

**Comment by elitecasaj00** [comment]
You're a god; I will test this later tonight.

**Comment by Youtouchmytralala** [comment]
@alisonrag You are a real master. Just check at iRO re:start xkore1. It successfully hooks client now and not disconnect.

**Comment by mseifer** [comment]
gets up to char select then after selecting it disconnects

Disconnecting (128.241.92.130:4500)...disconnected
Closing connection to Character Server
Connecting (128.241.92.131:4503)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
[reconnect] Login retry number 2, setting reconnect timeout to 69 seconds.
Connecting (128.241.92.162:6800)... connected

**Comment by elitecasaj00** [comment]
xKore 3 is timing out after character select; see attached
[console.txt](https://github.com/OpenKore/openkore/files/1364131/console.txt)

**Comment by alisonrag** [comment]
Are the xkore 0 working?
I only supose that the mda keys are wrong

**Comment by elitecasaj00** [comment]
xKore 0 is not working - timing out on map server

**Comment by Raguto** [comment]
I tried xkore 1 on restart and it's not working there either, I move once and then it does the timeout.

**Comment by alisonrag** [comment]
Xkore 1,2,3 are sensitive only work if xkore 0 are working perfect

**Comment by alisonrag** [comment]
@allanon can you help us with the update of iro ymir?

**Comment by Fvegini** [comment]
I can connect with xkore 0 in Iro - Renewal - Chaos! -- Using the files from iro-update branch
With xkore 2, I  got "disconnected from server" in character selection screen
With xkore 1, the kore recognizes the opened client, but can't connect with it!

**Comment by bebox123** [comment]
@Fvegini  the one in your xkore 1 procedure is also my problem in phRO. If that hooks up then I can run the bot smoothly as I already connected it previously before the new server went up.

**Comment by Pachu1985** [comment]
xkore 2 works like a charm in iRO:Restart if the character is female. on my male character, it swaps the gender when i open ragexe and then i get a disconnected from server when trying to connect to map server

**Comment by elitecasaj00** [comment]
Can confirm, xKore 2 works flawlessly with female characters.

**Comment by Youtouchmytralala** [comment]
xkore 0 works for re:start. xkore 1 - dc after connecting to map server. xkore 2 cant hook the client.

**Comment by mseifer** [comment]
Hello, any update on this or can already lose hope? 

thank you!

**Comment by alisonrag** [comment]
@mseifer 
i'm working on this.
current i'm here:

xkore 1:
no changes:

xkore 2:
bRO: working and fixed the unknow map error in character select screen
iRO: working male and female character
private servers: working

xkore 3:
bRO: working perfectly
iRO: working with dc after some seconds (trying to figure out what is doing this)
private servers:  not tested yet

**Comment by elitecasaj00** [comment]
Thanks for male characters with xKore 2 - much appreciated

**Comment by Fvegini** [comment]
@alisonrag 

Thanks man... but I must be doing somthing wrong then. (Or the version you`re working on isn't commited yet)

When I try to use xkore 2 on iro-chaos, the ragnarok client shows a female character with wrong hair style and color in an "Unknown" map... if I try to connect it anyway, the client show a "Disconected from server" and return to login screen.

My openkore.xml looks this:

<?xml version="1.0" encoding="euc-kr" ?>
<clientinfo>
    <servicetype>america</servicetype><servertype>primary</servertype><extendedslot></extendedslot>
    <connection>
        <display>XK2 [6901]</display><address>127.0.0.1</address>
        <port>6901</port>
        <version>1</version>
    </connection>
    <connection>
        <display>Poseidon</display> <address>127.0.0.1</address>
        <port>6900</port>
        <version>1</version>
    </connection>
</clientinfo>


In the original clientinfo.xml the "version" is 18 and has extra information like <aid> and <yellow> <langtype> <registrationweb> <agencyPort>

I tried to add and remove a few combinations of them, but nothing changed.

**Comment by alisonrag** [comment]
@elitecasaj00  @Fvegini 
try this branch:
https://github.com/alisonrag/openkore/commits/iro-xkore2-fix-male-character

**Comment by elitecasaj00** [comment]
xKore 2 confirmed working with male character; thanks for update

**Comment by Fvegini** [comment]
@alisonrag 

Worked 100% with the new files thanks for them and thanks for the tip of the original xml!

**Comment by elitecasaj00** [comment]
Ragexe is not responding after the new update – anyone else seeing the same thing?

**Comment by Fvegini** [comment]
Here, after the last update, openkore is still connecting with xkore2, but the ragnarok client seems weird!
Sometimes it syncs with the kore actions, sometimes it remains idle, and at some moment it just "teleport" to the actual character location and keep stopped!
Really weird

**Comment by MasterOfBytes** [comment]
For me xCore 1 is still not working. It shows nothing. Means no inventory, skills, etc.. Can't move.
xCore 0 has no problem. I downloaded a fresh copy of openkore to check if there are any problems with mine, but no, doesn't work neither.

**Comment by alisonrag** [comment]
@MasterOfBytes 
the fix for xkore 3 is here:
#1290 

for xkore 1 in future i will work around

**Comment by sctnightcore** [comment]
#1322

**Comment by KnightSickle** [comment]
Any news on xkore 1? I cant get xkore 2 nor 3 to work and not being able to actually see the game UI is really bad

**Comment by alisonrag** [comment]
@KnightSickle 
are the xkore 0 working?
xkore 1,2,3 will only work if xkore 0 is working

**Comment by KnightSickle** [comment]
@alisonrag Yes it is, using it right now, its just that i have no idea how to setup 2 nor 3 so im expecting a fix to 1 since that is the most simple apparently. There arent really any user-friendly guides and i dont want to bother people about it, but every time i try to start xkore 2 nothing happens the bot just starts as if it was xkore 0 and when i try to use xkore 3 the bot asks me to start ragnarok on the localhost but it doesnt seem to recognize it when i do so after i start it nothing else happens on the console.

**Comment by Pachu1985** [comment]
I'm using xkore 2 on iRO:RE and it works like a charm, even with multiple clients. Did you configure the shortcut to Ragexe.exe with the correct parameters? Did you edit the clientinfo.xml? I can try help you configure xkore 2

**Comment by sctnightcore** [comment]
#1339

**Comment by ShadowCold** [comment]
@Pachu1985 
Can you please tell us a step by step what you did? When you say did you configure the shortcut what do you mean by that? or the clientinfo?

I'm sorry im bit new to this. oKore 0 works fine for me but with the number of GM's about I would like to see what is going on when im boting and using my slave.

Regards

**Comment by mseifer** [comment]
When setting XKore 3 and connecting with the client, it disconnects after selecting server:

Waiting Ragnarok Client to connect on (localhost:6901)
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
[reconnect] Login retry number 2, setting reconnect timeout to 67 seconds.
Connecting (128.241.92.162:6800)... connected
---------- Account Info ----------
----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  513    128.241.92.155  4500
1   Chaos                 2367   128.241.92.130  4500
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (128.241.92.162:6800)...disconnected

**Comment by Pachu1985** [comment]
@ShadowCold 
I don't think this is the place for that. Leave me your forum username and i will PM there since i can't find a way to send PM here

**Comment by MysticFurur0RE** [comment]
pachu u can help me? for me dont work... i use the guide of https://wiki.wetfish.net/xkore but not work in xkore2

**Comment by alisonrag** [comment]
fix in #1347

**Comment by cowan26** [comment]
Im seeking for help. 
Playing Official server Ragnarok MYSG . 
ive some issue that i cannot go through in. 
Im really need help about this Connection ragnarok client to xkore.
![bot roa](https://user-images.githubusercontent.com/36547669/36339668-dc164b32-1405-11e8-979f-9c2f868b8d33.jpg)

**Comment by sctnightcore** [comment]
@cowan26  dont work in mRO :p

**Comment by cowan26** [comment]
come on bro. i saw too many people botting around. please help :(

**Comment by fadreus** [comment]
@cowan26 That working bot is from personal individual who make it work, not from official openkore release. If you want, go find them.

And please remember this.
Github for fix bug, not for help.
Need help, go forum.

**Comment by cowan26** [comment]
@fadreus bro aku betul2 perlukan pertolongan ni. Aku dah comment dkt forum tapi xde yg jawab 😣😣
