### ISSUE TITLE
Packet Tokenizer: Unknown switch: 0009 on MAP LOGIN

### ISSUE THREAD

**Issue by jgamer0606** [OpenKore/openkore#1229]
Hi Guys,

Please help me here =(

![ss](https://user-images.githubusercontent.com/32477333/31113142-5f59ebb6-a84a-11e7-9afb-2fd4b742c900.PNG)

SERVER: new pRO server.

**Comment by fadreus** [comment]
#1225 

Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* **Check if an issue already exists for your request**
* Please post in English if possible

**Comment by jgamer0606** [comment]
This is fixed.

**Comment by chongtabs** [comment]
please share.

**Comment by chongtabs** [comment]
can you share your config or server hehe i cant login in the server it always dc into word i cant find the IP of thor server.txt please... thanks

**Comment by imthemenace** [comment]
please share with me also the config for loki server tnx email me at imbugzdmenace@gmail.com tnx rok on guys
