### ISSUE TITLE
Continious disconnection on MAP SERVER

### ISSUE THREAD

**Issue by jgamer0606** [OpenKore/openkore#1232]
Please help.

SERVER: NEW ROPH

![helpmap](https://user-images.githubusercontent.com/32477333/31118255-5efbd782-a85f-11e7-9675-afab9ae2fcd8.PNG)

**Comment by fadreus** [comment]
#1225 

Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* **Check if an issue already exists for your request**
* Please post in English if possible

**Comment by sctnightcore** [comment]
#1232

**Comment by jgamer0606** [comment]
Hi @fadreus,

I already tried and read those reference you gave but no luck =(.

**Comment by fadreus** [comment]
My point is similar issue already exist.
No development for pRO.
You can close your issue.

*Jeez, I already going all the trouble **enlarging** and **highlighting** the text. Seem to be ineffective LOL 🤣🤣🤣

**Comment by jgamer0606** [comment]
@fadreus  Then this place is not the right place to ask a question and this is not a request =). LOL

**Comment by alisonrag** [comment]
use #1225
