### ISSUE TITLE
RO:Restart dont run with XKore1 setting :(

### ISSUE THREAD

**Issue by pmaurice1991** [OpenKore/openkore#1236]
Hello, my bot runs perfectly, but when i use XKore 1 Setting this Error appears:

You are no longer: UNKNOWN_STATUS_993
You are no longer: UNKNOWN_STATUS_994
Berechne Zufallsroute nach: Prontera Field (prt_fild07): 171, 152
Stuck at prt_fild07 (249,57), while walking from (249,57) to (171,152).
Problem beim Berechnen der Route.
Berechne Zufallsroute nach: Prontera Field (prt_fild07): 85, 23
Timeout - Map Server, waiting actions for the Ragnarok Online client

Can anyone help?
Thanks alot

**Comment by sctnightcore** [comment]
xkore0 work ! 

#1227

**Comment by alisonrag** [comment]
continue in #1227
