### ISSUE TITLE
Recievepackets.txt and server.txt fot this vanilla version of rAthena

### ISSUE THREAD

**Issue by ragnarokfan** [OpenKore/openkore#1237]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary: 
I have been trying to bot here in the vanilla version of rathena verion but I can't seem to figure out how...

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:
In depth testing of bot behavior can be done offline

###### Expected Behavior:
Will not be rejected to server when connecting

###### Actual Behavior:
Kept having the error of "Rejected from server" if doing offline only

All I want is to have a FS Priest follow me while I kill mobs using openkore...

For reference how do you bot this version?
The diffed exe for this is kRO_2015_11_04a, I tried packet sniffing but I failed miserably...

https://rathena.org/board/topic/109823-ragnarok-online-complete-offline-pack-2017-make-your-ro-server-in-less-then-5-minutes/

**Comment by sctnightcore** [comment]
well -*-

**Comment by ragnarokfan** [comment]
I'll try and I will see what comes up thanks..

**Comment by ragnarokfan** [comment]
![adad](https://user-images.githubusercontent.com/32195383/31211192-d4e84566-a99f-11e7-8c01-3392de435d57.JPG)
![grfhddgf](https://user-images.githubusercontent.com/32195383/31211193-d558d718-a99f-11e7-99ba-7566e00532dd.JPG)

I get these errors.... Hmm....

**Comment by sctnightcore** [comment]
tables > kRO !

**Comment by ragnarokfan** [comment]
![image](https://user-images.githubusercontent.com/32195383/31224838-2bf38388-a9d8-11e7-94fa-d8abca9f2111.png)

So I did get this but cant extract packets with peek.. Might be me or the .exe

**Comment by sctnightcore** [comment]
http://herc.ws/board/topic/4912-peek-successor-to-yommys-packet-analyzer/ @ragnarokfan

**Comment by ragnarokfan** [comment]
![image](https://user-images.githubusercontent.com/32195383/31226759-063f82c4-a9e0-11e7-9589-b21d08e4c0e5.png)

 Got it.. ^_^ tried putting these info dunno if its correct but... please check?

![fdsfsf](https://user-images.githubusercontent.com/32195383/31227012-f13ef552-a9e0-11e7-9854-8f41ff4c9ae8.JPG)

But I still get this error....

![grfhddgf](https://user-images.githubusercontent.com/32195383/31227019-fb852680-a9e0-11e7-803f-6efd504f275f.JPG)

**Comment by ragnarokfan** [comment]
![image](https://user-images.githubusercontent.com/32195383/31227816-f24479e2-a9e3-11e7-9581-783965a249d7.png)

Now I'm getting this..

**Comment by sctnightcore** [comment]
check output on peek !

**Comment by ragnarokfan** [comment]
[2015-11-04aRagexe.zip](https://github.com/OpenKore/openkore/files/1359422/2015-11-04aRagexe.zip)

Oh God.... This is my .exe file Can you please try extracting this? My brain cannot comprehend now whats wrong haha

**Comment by lututui** [comment]
@ragnarokfan have you tried the recvpackets already in OpenKore for 2015-11-04a?

https://github.com/OpenKore/openkore/blob/master/tables/kRO/RagexeRE_2015_11_04a/recvpackets.txt
https://github.com/OpenKore/openkore/blob/master/tables/kRO/RagexeRE_2015_11_04a_b/recvpackets.txt

**Comment by ragnarokfan** [comment]
let me try...

**Comment by ragnarokfan** [comment]
Damn the a_b worked... ^_^ Thanks.....
