### ISSUE TITLE
autokach

### ISSUE THREAD

**Issue by rinehartxdd** [OpenKore/openkore#1238]
anyone using autokach plugin macro @iro restart odin server?
it`s kinda buggy i try to change the log but end up messing with the macro and make it didnt work at all
any of u guys have working well autokach plugin for this server?

**Comment by joecabezas** [comment]
never used it before but documentation links to a forum which is 404, so what is this?

**Comment by Mortimal** [comment]
this plugin was developed for ruRO 3-4 years ago... so yeah its buggy on other servers.... duh...

**Comment by fadreus** [comment]
What you are trying to achieve with that plugin anyway?
Looking at the files seems like to be related for doing quest and stuff.

**Comment by rinehartxdd** [comment]
well.. i`m trying to make my bot do change job by itself since its pain in my ass to change job by myself 1 by 1
kinda make it works already 
but it`s auto skill up really disturbing
any other recommended plugin to auto change job like this one?

**Comment by Mortimal** [comment]
no... read my previous response... u need to upgrade it to work on other servers...

**Comment by fadreus** [comment]
Yeah, update it for your own.
I would say 95% already written there, just need minor adjustment for your server.
I don't use plugin for quest. Just use macro/eventMacro.

**Comment by rinehartxdd** [comment]
@fadreus can u teach me the macro please senpai?
:(
i`m trying to make bot army to counter this nonstop ban by gm

**Comment by fadreus** [comment]
To learn macro, read the [macro wiki](http://openkore.com/index.php/Macro_plugin) and [tables\commanddescriptions.txt](http://openkore.com/index.php/Category:Console_Command).

For the expression, you can replace with anything similar if it didn't work or you don't understand what it do..

> counter this nonstop ban by gm

Good luck with that 😂😂😂😂😂😂
