### ISSUE TITLE
config onAction not work

### ISSUE THREAD

**Issue by Junezavr** [OpenKore/openkore#1239]
config
partySkill PR_GLORIA {
	lvl 5
	onAction attack <<< not work
	target_whenStatusInactive EFST_GLORIA
	isSelfSkill 1
	timeout 5
}
not work
partySkill PR_GLORIA {
	lvl 5
	onAction follow
	target_whenStatusInactive EFST_GLORIA
	isSelfSkill 1
	timeout 5
}
work
I want to putskillparty on master attack

**Comment by fadreus** [comment]
Assuming this was your slave, you need to use `attackAuto 2` / `attackAuto_followTarget 1` / `attackAuto_party 1` in your slave config.
It won't work if other player (master, following) is doing attack while slave just doing nothing.

**Comment by lututui** [comment]
onAction attack is only true if SELF is attacking, not a master or party member
