### ISSUE TITLE
cant seem to use heal bomb on mob.

### ISSUE THREAD

**Issue by gr4ndmasterz** [OpenKore/openkore#1243]
need help as i cant seem to ask my bot to ttack monster , i tried putting the mon id base on the table/mon.txt but it still wont use skill on it.

does anyone know how to fix it ? i tried every single way of writing the monster's name but all failed,

 96/ 97] You attack Monster Archer     Skeleton (0) (Dmg: 79) (Delay: 470ms)
[ 81/ 97] You attack Monster Archer     Skeleton (0) (Dmg: 77) (Delay: 470ms)
[ 81/ 97] You attack Monster Archer     Skeleton (0) (Dmg: Miss!) (Delay: 470ms)
[ 81/ 97] Monster Archer        Skeleton (0) attacks you (Dmg: 108) (Delay: 864ms)
[ 81/ 97] You attack Monster Archer     Skeleton (0) (Dmg: Miss!) (Delay: 470ms)
[ 67/ 97] You attack Monster Archer     Skeleton (0) (Dmg: 74) (Delay: 470ms)
[ 67/100] You attack Monster Archer     Skeleton (0) (Dmg: 78) (Delay: 470ms)
[ 68/100] You attack Monster Archer     Skeleton (0) (Dmg: Miss!) (Delay: 470ms)
[ 68/100] Monster Archer        Skeleton (0) attacks you (Dmg: 93) (Delay: 864ms)

**Comment by gr4ndmasterz** [comment]
attackSkillSlot heal {
	lvl 10
	dist 8, 7, 6, 5, 4, 3, 2, 1
	maxCastTime 0
	minCastTime 0
	hp
	sp > 10
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive EFST_POSTDELAY
	whenFollowing
	spirit
	amuletType
	aggressives
	previousDamage
	stopWhenHit 0
	inLockOnly 0
	notInTown 0
	timeout 1
	disabled 0
	monsters zombie, skeleton, Evil Druid, Wraith, Ghoul, Zombie Prisoner, Skel Prisoner, Munak, Bongun, Archer	Skeleton, Soldier Skeleton, Skeleton Archer, Archer Skeleton, ArcherSkeleton, Mummy, Verit, Archer     Skeleton

**Comment by sctnightcore** [comment]
```
attackSkillSlot heal {
lvl 10
dist 8, 7, 6, 5, 4, 3, 2, 1
sp > 10
timeout 1
monsters zombie, skeleton, Evil Druid, Wraith, Ghoul, Zombie Prisoner, Skel Prisoner, Munak, Bongun, Archer Skeleton, Soldier Skeleton, Skeleton Archer, Archer Skeleton, ArcherSkeleton, Mummy, Verit, Archer Skeleton
```
