### ISSUE TITLE
eventMacro condition substitution (iRO Chaos) - QuestHuntCompleted (Perl Exp Inquiry)

### ISSUE THREAD

**Issue by fadreus** [OpenKore/openkore#1245]
Referring to #914 condition `QuestHuntCompleted` doesn't work in iRO Chaos while it's working on other servers(?) since no issue from other servers.

In `macro.pl,` it support `perl expression` as condition

![untitled](https://user-images.githubusercontent.com/32188494/31314513-54e4d1b6-ac35-11e7-9c8c-dbd106466307.png)

# Do `eventMacro` have similar option for automacro as `condition`? using perl exp.
If it does, could anyone give me some example for quest complete?**

Or I just have to stick with triggering quest periodically?

_I've mine completed quests roughly 1 hour.
After eliminating some checks periodically, it can do around 50 minutes.
Manually play the game doing the quest took me around 30 minutes.
While I'm checking the quest manually without disturbing it's AI sequence, it can do around 40 minutes.
So, I'm expecting it to do that much._

## Additionally, any suggestion for how to do eval for party members's location (map)?
for example

```
automacro CheckAnyoneAtMap {
hook target_died
call {
if (any party member = map) goto end || any party member != map) goto bla)

: end
stop

: bla
do bla bla
}
}
```

**Comment by c4c1n6kr3m1** [comment]
this is part of my old macro, i never used it again
```
	$matis = 0
	do eval for (my $_i = 0; $_i < @partyUsersID; $_i++) {next if ($::partyUsersID[$_i] eq "");next if ($::partyUsersID[$_i] eq $::accountID);if ($::char->{'party'}{'users'}{$::partyUsersID[$_i]}{'name'} eq "sup3rb") {if (!$::char->{'party'}{'users'}{$::partyUsersID[$_i]}{'online'} || $::char->{'party'}{'users'}{$::partyUsersID[$_i]}{'map'} =~ /izlude/) {$::Macro::Data::varStack{matis} = 1;}}}
	if ($matis == 1) goto end
```

**Comment by fadreus** [comment]
Thx for the reference😁As long as I can get the value checked, I'll make it work around.
If only `eventMacro` support `perl exp` as condition _(if it available)_.😓

**Comment by Nipodemos** [comment]
unfortunaly it is not available on eventMacro =/

**Comment by fadreus** [comment]
Oo,. I thought I misunderstand something.
Thanks again !
