### ISSUE TITLE
1 Question please

### ISSUE THREAD

**Issue by Jeffgomz** [OpenKore/openkore#1246]
How many bot i can use in 1 laptop that will GM`s will catch it?
 thx for reply if someone ^_^

**Comment by Raguto** [comment]
It is your job to do the best you can to not get caught, the more bots you use the more you risk getting caught, simple as that.

**Comment by Jeffgomz** [comment]
just give me exact number that i can use im using 4 bots until now GM didnt caught it

**Comment by Jeffgomz** [comment]
thank you ^_^
