### ISSUE TITLE
fRO new ip ?

### ISSUE THREAD

**Issue by kumulo123** [OpenKore/openkore#1247]
Hi, fRO has changed his server location, so the ip also changed..
Does someone knows what is the new ip and what is there to change in the config please ??
Thanks you !

**Comment by fadreus** [comment]
[You can try this.](openkore.com/index.php/Connectivity_Guide)

**Comment by kumulo123** [comment]
404 page note foud, but i have opened the grf with grf tool and i douf the ip
`54.36.76.129`
:)

**Comment by Uldural** [comment]
I tried this but it dont works :( can you post the new ip, master server etc....? Please.

**Comment by lututui** [comment]
Open the .grf file with grftools, find the .xml file (most times it's called clientinfo.xml). The new address should be in there

**Comment by Uldural** [comment]
But i didnt find the master level and the other things :( WPE diesnt work...please post the complete new adress <3

**Comment by fadreus** [comment]
Oh yeah, I forgot the link for WPE is dead long time ago..
This is mine from long long time ago.
[wpepro09mod.zip](https://github.com/OpenKore/openkore/files/1369266/wpepro09mod.zip)

**Comment by Uldural** [comment]
if i press "Target Program" the Ragnarok-exe isnt there :/

**Comment by Uldural** [comment]
my ragnarok.exe is open and still runs in the background in the login screen

**Comment by Uldural** [comment]
The Ip is : 62.21.1.52
port: 6900
version: 1

Grftool works by me fine....the other doesnt,

**Comment by alisonrag** [comment]
@Uldural  
are the openkore working with new ip?

**Comment by Uldural** [comment]
no, the master lvl and the other things are wrong

**Comment by Uldural** [comment]
can anyone post the server config pleeeeasseee? :(

**Comment by fadreus** [comment]
Oh well, ignore mine. 😥I'm outdated.

**Comment by Uldural** [comment]
Nobody here that can find out the server configs?

**Comment by alisonrag** [comment]
The only dev that play in this server is @sctnightcore

**Comment by sctnightcore** [comment]
welll -*- wait

**Comment by alisonrag** [comment]
fixed in #1251
