### ISSUE TITLE
Need the new Server IP from fRO!!!

### ISSUE THREAD

**Issue by Uldural** [OpenKore/openkore#1248]
iam a computer noob and ive tried to find out the ip,master level etc. of fRO....ive tried WPE and wireshark but nothing happens :( 

Pleeeassse help me! Post this new IP etc. !

**Comment by fadreus** [comment]
#1247 
Same issue already existed, Shouldn't start new issue.

**Comment by alisonrag** [comment]
closed due to duplicated issue, please read and search before posting
