### ISSUE TITLE
Ragnarok PH 2017 - Openkore

### ISSUE THREAD

**Issue by boaterszxc** [OpenKore/openkore#1249]
I have a bot here but it is mac based and it has a timer. I am looking for someone who can decrypt the dll file to disable timer and mac-based. If you can help me I will give to you this openkore bot already configured its xkore1 btw. Thank you!

**Comment by boaterszxc** [comment]
Mac based means = I can only use it on my pc @_@ / And there's a timer that need to renew every week. DX

**Comment by alisonrag** [comment]
continue in #1225

**Comment by boaterszxc** [comment]
its already working dude but it has a timer

**Comment by jonelle1990** [comment]
share hahaha

**Comment by jonelle1990** [comment]
share hahaha
