### ISSUE TITLE
problem connecting to locally hosted rAthena

### ISSUE THREAD

**Issue by HoboSage** [OpenKore/openkore#125]
After following all relevant guides and forum posts I could find, openKore gets rejected at character selection for unknown packet version. It seems like the most obvious potential problem would be that the client is 2015-09-16a, and the versions in src/network seem to stop updating in 2013. Is openKore compatible with later client versions? Through posts on the forums I was able to use PEEK and an 
edited script to get recvpackets.txt, and WPE to get the info for servers.txt, but the serverType is still the last 2013ver. I already have all the servers packet info, but the network files seem to have much more than just the packets. If necessary, is there a way to use this to make updated networking files??

`//2015-09-16Ragexe
packet_ver: 53
packet_keys: 0x17F83A19,0x116944F4,0x1CC541E9 // [Napster]
0x0869,7,actionrequest,2:6
0x093E,10,useskilltoid,2:4:6
0x0877,5,walktoxy,2
0x08AC,6,ticksend,2
0x0936,5,changedir,2:4
0x089C,6,takeitem,2
0x092F,6,dropitem,2:4
0x0934,8,movetokafra,2:4
0x085E,8,movefromkafra,2:4
0x022D,10,useskilltopos,2:4:6:8
0x0873,90,useskilltoposinfo,2:4:6:8:10
0x095A,6,getcharnamerequest,2
0x0942,6,solvecharname,2
0x087F,12,searchstoreinfolistitemclick,2:6:10
0x0817,2,searchstoreinfonextpage,0
0x0920,-1,searchstoreinfo,2:4:5:9:13:14:15
0x0881,-1,reqtradebuyingstore,2:4:8:12
0x0835,6,reqclickbuyingstore,2
0x092E,2,reqclosebuyingstore,0
0x0948,-1,reqopenbuyingstore,2:4:8:9:89
0x089B,18,bookingregreq,2:4:6
// 0x094F,8 CZ_JOIN_BATTLE_FIELD
0x0961,-1,itemlistwindowselected,2:4:8:12
0x0969,19,wanttoconnection,2:6:10:14:18
0x0924,26,partyinvite2,2
// 0x0938,4 CZ_GANGSI_RANK
0x089E,26,friendslistadd,2
0x0960,5,hommenu,2:4
0x0941,36,storagepassword,2:4:20

// New Packet
0x097F,-1       // ZC_SELECTCART
0x0980,7,selectcart,2:6 // CZ_SELECTCART`

Any help would be greatly appreciated!!!

 Here is all other relevant info:
Servers.txt 
![servers txt](https://cloud.githubusercontent.com/assets/20084106/16259556/369f2ff4-3831-11e6-943f-9ff302332670.jpg)

server error: `[Info]: clif_parse: Disconnecting session #3 with unknown packet version (p:0x022d,l:10).`

![okerror](https://cloud.githubusercontent.com/assets/20084106/16258582/827546c0-382c-11e6-8385-d9fa7a3e5464.jpg)

[recvpackets.txt](https://github.com/OpenKore/openkore/files/327237/recvpackets.txt

**Comment by cydh** [comment]
I think, OpenKore doesn't test kRO's 2014+ clients yet. Even from 2013, there are some incompatibility for updated @rAthena emulator.
