### ISSUE TITLE
PHRO THOR SERVER IP anyone have?

### ISSUE THREAD

**Issue by chongtabs** [OpenKore/openkore#1250]
Still dont have SERVER IP to connect in THOR server...

Please Share working BOT PHRO thor server. 

But Still trying to fix how to connect in server. i really dont know how.. I get some IP for the server but ITS for loki,, I will try it later if any have a good server.txt for thor please share... Thanks we are one,,,

**Comment by chongtabs** [comment]
http://openkore.com/index.php/Connectivity_Guide

this will help i think.. i will try it later.

**Comment by alisonrag** [comment]
continue in #1225
