### ISSUE TITLE
Can anyone help me? I need your help.Chinese CRO

### ISSUE THREAD

**Issue by moran212** [OpenKore/openkore#1255]
Chinese CRO...
.Yes, what should I do? 
Can someone help me with my tutorials? 

[content removed]

**Comment by holymessenger** [comment]
There is no need to open the similar topic in a short time. I have seen several people have done it who are charge it for money or making profit by botting a lot theirselves.  Not everyone is warmhearted.  It depends on yourself. I'm also struggling in it.  you need learn openkore basic things , perl and even reverse.

**Comment by moran212** [comment]
@holymessenger Because the tutorial is too old for WPE. Wireshark.What software should I use

**Comment by moran212** [comment]
@alisonrag @sctnightcore  WPE. Wireshark You can't use   What software should I use NP
The tutorial is not available now
Is there a new tutorial? I need to study

**Comment by yon2kong** [comment]
I have forked openkore for cro.
https://github.com/yon2kong/openkore/tree/cro

**Comment by sctnightcore** [comment]
@yon2kong  wow ! i will test it !

**Comment by yon2kong** [comment]
I can't figure out the algorithm for encrypting the login password.
I have to use hex bytes password captured by wireshark directly.

Poseidon is too simple, but it works.

**Comment by sctnightcore** [comment]
@you2kong you can PR !

**Comment by holymessenger** [comment]
I just can't make my openkore connect to poseidon. my RO client works fine with poseidon.

**Comment by yon2kong** [comment]
@holymessenger @sctnightcore 

The ugly Poseidon that I've written can only handle connections from cro client.
https://github.com/yon2kong/Poseidon

1) run posesion
![poseidon2](https://user-images.githubusercontent.com/7730121/31609462-ef28daf2-b2a6-11e7-9a20-ade3e66ea1ac.png)

2) run ro-client to login poseidon

3) run openkore
<img width="604" alt="screen shot 2017-10-16 at 7 22 34 pm" src="https://user-images.githubusercontent.com/7730121/31609617-81552aac-b2a7-11e7-814d-e27a5cc8c803.png">

**Comment by holymessenger** [comment]
@yon2kong

Thank you for enlightening me.   Before you post your work on the github, I had been beset by why my bot doesn't connect and query to my poseidon. After trying your things, it seems some packet header I modified lead to my problem. 

And I think the password is encrypted by rijndael method. But I don't know much about the reverse things.  What you do to pass the master login is really the same as what I did.  haha, Great minds think alike.

**Comment by holymessenger** [comment]
@yon2kong

Thank you for enlightening me. Before you post your work on the github, I had been beset by why my bot doesn't connect and query to my poseidon. After trying your things, it seems some packet header I modified lead to my problem.(because your openkore works(connect and query) fine with my edited poseidon, and my edited openkore never try even once connect or query to my poseidon)

And I think the password is encrypted by rijndael method. But I don't know much about the reverse things to find the key. What you do to pass the master login is really the same as what I did. And I also use my character packet to construct the poseidon server. haha, Great minds think alike.

**Comment by vergil-lai** [comment]
@yon2kong Can not connect to cro,can you help me?

连接到帐号服务器...
连接 (118.89.42.108:6900)... 连接完成
Packet Tokenizer: Unknown switch: 0ACD
Timeout on Account Server, reconnecting. Wait 49 seconds...
连接到帐号服务器...
[reconnect] Login retry number 2, setting reconnect timeout to 72 seconds.
连接 (118.89.42.108:6900)... 连接完成
Packet Tokenizer: Unknown switch: 0ACD

**Comment by caryshen** [comment]
@yon2kong 
I used your poseidon and run ro-client to login poseidon,but it seems posesion didn't query and reply like your pic
![20171018](https://user-images.githubusercontent.com/17630500/31702735-8bf0d9ba-b40b-11e7-9d4d-80f41ce59f18.jpg)
What is the problem and what should i do to solve the problem?

**Comment by yon2kong** [comment]
@caryshen 
I have added README to illustrate how to use Poseidon.
https://github.com/yon2kong/Poseidon
Good luck.

**Comment by oleokoong** [comment]
@yon2kong  im not playing CRO, but i want to ask can i run poseidon on raspberrypi same result with vm?
