### ISSUE TITLE
[eventMacro] SimpleHookEvent parse hash

### ISSUE THREAD

**Issue by Naozumi2k** [OpenKore/openkore#1256]
Hi there.
How can I get the hash type variables in SimpleEventHook?
The following macro code does not work for me, it's printing empty string:
```
automacro vend {
	SimpleHookEvent vending_item_sold
	call {
		log $.SimpleHookEventLastVendArticle{name}
	}
}
```
Thanks in advice

**Comment by Nipodemos** [comment]
i am almost sure that you you dont need to make this a hash
you can just put directly `$.SimpleHookEventLastVendArticle`

did you tested like that to see if it works?

**Comment by Naozumi2k** [comment]
@Nipodemos Yes I do, it does not work for sure :D
Take a look - that hook calls in **src/Network/Receive/ServerType0.pm**:
```
	Plugins::callHook(
		'vending_item_sold',
		{
			#These first two entries are equivalent to $args' contents.
			'vendShopIndex' => $number,
			'amount' => $amount,
			'vendArticle' => $articles[$number], #This is a hash
		}
	);
```
As you can see there are two scalar args and one hash argument.
My questing is how do I get that hash keys inside my macros

**Comment by Nipodemos** [comment]
hey
when the macro triggers, you could use the console command `eventMacro var_get`
to see all the variables that exist and what values...

if you see the variable `$.SimpleHookEventLastVendArticle`, but with an empty value, so it means that for now that Condition doesn't have support for that specific variable

**Comment by Naozumi2k** [comment]
Thanks for advice
I've got the following result
```
[eventMacro] Printing values off all variables
-------- Scalars --------
1 - '$.caller' = 'vend'
2 - '$.SimpleHookEventLastAmount' = '1'
3 - '$.SimpleHookEventLast' = 'vending_item_sold'
4 - '$.SimpleHookEventLastVendShopIndex' = '44'
5 - '$.SimpleHookEventLastVendArticle' = 'HASH(0x3fcbff8)'
-------- Arrays ---------
-------- Hashes ---------
```
Looks like eventMacro does not recognize that $.SimpleHookEventLastVendArticle is a hash

**Comment by alisonrag** [comment]
Fixed at https://github.com/OpenKore/openkore/commit/8903494f97e21411c024c2ea170a29b7dd94737d
