### ISSUE TITLE
eventMacro NotInMap

### ISSUE THREAD

**Issue by Fvegini** [OpenKore/openkore#1260]
EventMacro -> automacro condition NotInMap breaking with multiple values.
Tested in Iro-Chaos Renewal

automacro test1 {
NotInMap aldebaran
call {}
}
Triggers in every map except aldebaran

automacro test2 {
NotInMap aldebaran, prontera
call {}
}
Triggers in every map (even aldebaran, the first one)

To work arround this, i'm using this ugly solution:

automacro test3 {
InMap not aldebaran, not prontera
call {}
}
Triggers in every map except aldebaran and prontera.

p.s: Looks like NotInMap is in the Portuguese Wiki of eventMacro, but not in the english one, curious thing!

**Comment by Henrybk** [comment]
It was never meant to be used that way, you should use use multiple lines of the condition

**Comment by Fvegini** [comment]
Got it!

With this config it worked:

automacro SaiudosMapas {
	exclusive 1
	timeout 600
	NotInMap aldebaran
	NotInMap prontera
	NotInMap moc_para01
	NotInMap c_tower1
	NotInMap aldeba_in
	call alertaSAIU
}

Thanks for the help!
