### ISSUE TITLE
 WPE. Wireshark

### ISSUE THREAD

**Issue by moran212** [OpenKore/openkore#1262]
WPE. Wireshark You can't use What software should I use NP
The tutorial is not available now
Is there a new tutorial? I need to stud

**Comment by holymessenger** [comment]
wpe pro is still useful even while the cRO is protected by nprotect gameguard. you should know how nprotect work and how to avoid nprotect. you have a very short  time to sniffer before nprotect shut down the cRo client. but it's enough I think.

**Comment by moran212** [comment]
@holymessenger 
![931908a8ea501fa1af62d25ad38442a7](https://user-images.githubusercontent.com/32576892/31538152-3c0d8ad8-b037-11e7-87f9-c326db75ce07.png)
I found him. What should I do

**Comment by moran212** [comment]
I found him. What should I do

**Comment by holymessenger** [comment]
English: Well done. go ahead!
Chinese:  你這基础也太薄弱了，找的什麼鬼我都看不懂，再自己学学吧

**Comment by moran212** [comment]
@holymessenger @joecabezas Because there are too few tutorials, I don't know where I should study so please

**Comment by sctnightcore** [comment]
#1255

**Comment by alisonrag** [comment]
use #1170
