### ISSUE TITLE
error "isCity" on an undefined value

### ISSUE THREAD

**Issue by alisonBR** [OpenKore/openkore#1266]
###### Summary: 
Error message:
Can't call method "isCity" on an undefined value at src/AI/CoreLogic.pm line 3270.

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
did you readed the bug template?

how we can reproduce this? what map?  version of openkore? are you using macro/eventmacro? why you didn't posted the errors.txt ?

no one here is soothsayer to supose what is going on with your openkore

**Comment by alisonBR** [comment]
Excuse me, but it's the first time I use the program. I think you should be more educated.

**Comment by alisonrag** [comment]
@alisonBR 
ok sir,
but we still cant help you, we dont have the necessary information

the only thing that i can think is: 
the openkore have not implemented the map that your char is in

post informations like:
-server that you are playng
-openkore version
-post  errors.txt file

**Comment by sctnightcore** [comment]
erRO ?

**Comment by alisonBR** [comment]
![sem titulo](https://user-images.githubusercontent.com/32744220/31578051-d5f32d70-b0ef-11e7-9ee5-7add2625c983.png)

**Comment by Nipodemos** [comment]
baixe o openkore todo denovo [seguindo esse tutorial (clique aqui)](http://openkorebrasil.org/index.php?/topic/3374-tortoisegit-baixar-atualizar-o-openkore/)

**Comment by alisonrag** [comment]
na verdade ele ta jogando em um private server e nao implementou o mapa no openkore

**Comment by alisonBR** [comment]
Thanks for the help, I was able to solve the problem.
