### ISSUE TITLE
Follow/HealBuff Nonparty,nonbot players [Help]

### ISSUE THREAD

**Issue by dersheys** [OpenKore/openkore#1269]
Hi guys, how can I get my support priest bot to Follow, Heal and Buff non-party, non-bot players? 

I only wish to bot the support, and have it follow me and/or my friend while we play and level. This way we get to share exp in a party while having a high level support bot to heal us. 

I've been searching for really long, and still I couldn't get find any solutions. Any examples of codes would be much appreciated, thank you so much!!

PS: Once not in party, my support priest bot stops following anyone. 
PS2: I also tried activating Bus 1 but it does nothing, Im new to plugins.

**Comment by fadreus** [comment]
Slave can still only follow non-party member while in `clientSight`.

Have you try something like this with macro?
- Example: Get healed when using HELP emotion
```
automacro Heal {
console /*Help*/
call {
do sp 28 @player ($.lastPlayerName)
do sp 28 @player ($.lastPlayerName)
}
}
```

Though you need to ask heal and stuff, no auto stuff.😆

**Comment by dersheys** [comment]
Hi fadreus, what is clientSight?
I'm quite new to this whole macro thing, would be really glad if you could tell me more on how to use it!  

Also, thank you for the above information, but in addition, how can my support priest bot follow my non-partied character?

**Comment by fadreus** [comment]
`clientSight` is in `config.txt`. [(Read Me - ClientSight)](http://openkore.com/index.php/ClientSight)

For starter, read macro wiki [here](http://openkore.com/index.php/Macro_plugin) or eventMacro [here](http://openkore.com/index.php/EventMacro). I'm more familiar with macro so I use macro.  Read [here](http://openkore.com/index.php/Category:Console_Command) too for what ever you want your slave to do. There are plenty of examples out there for any usage, so just keep searching.

Following non party is same, just don't leave your slave too far behind. It can't find your last track.
If you & your friend memorize all console command and `responses.txt` in `control` folder, set your name in `overallAuth.txt` so you can control your slave in-game (for example; `move <x> <y>` when ever your slave is lost, `town` to respawn, `relog <#>` if situation gets to mobby, etc etc)

_There's a way for non-party slave-master to follow each other using Bus as you mentioned but that is for bot & bot afaik, not sure about bot & game client._ 😆

<details>
<summary>Macro Example From The Forum - Click Here</summary>

```
// LOGINS

automacro sitting {
console /You are Sitting./i
call {
do look 6
}
}

// PUBLIC ACCESS
automacro basicBuff {
console /\[dist=(.*)\] (.*) \((\d+)\): (ab)$/
exclusive 1
call {
$i = $.lastMatch3
do stand
do sp 29 $i
do sp 34 $i
pause 1
stop
}
}

automacro basicKyrie {
console /\[dist=(.*)\] (.*) \((\d+)\): (ky)$/
exclusive 1
call {
$i = $.lastMatch3
do stand
do sp 73 $i
pause 2
do eval AI::clear;$::taskManager->stopAll();delete $::ai_v{temp};undef $::char->{dead};
stop
}
}

automacro buffing {
console /\[dist=(.*)\] (.*) \((\d+)\): (buff|buff pls|buff please|BUFF)$/
exclusive 1
call {
$i = $.lastMatch3
do stand
do sp 29 $i
do sp 34 $i
pause 1
do sp 73 $i
pause 2
do eval AI::clear;$::taskManager->stopAll();delete $::ai_v{temp};undef $::char->{dead};
stop
}
}

automacro emotions {
console /\[dist=(.*)\] (.*) \((\d+)\): \*(Help)\*$/i
exclusive 1
call {
$dist = $.lastMatch1
if ($dist > 8) goto away

$i = $.lastMatch3
do sp 29 $i
do sp 34 $i
pause 1
do sp 73 $i
pause 2
do eval AI::clear;$::taskManager->stopAll();delete $::ai_v{temp};undef $::char->{dead};
stop
:away
do stand
stop
}
}
```

</details>
