### ISSUE TITLE
Serve Privat

### ISSUE THREAD

**Issue by alisonBR** [OpenKore/openkore#1270]
Hello!
Good night, I'm new to this program, and I wanted the help of you, because I'm trying to use openkore on a privat server, and I managed to get it to run, but I get disconnected from the server every 30 seconds. And agr am using the "visual mode", but when I put the password on port 6901, I take Gravity error. PFV help me.

**Comment by sctnightcore** [comment]
well ! well ! well ! well ! well ! well 1 
visual mode is xkore 2 3 ?

**Comment by alisonBR** [comment]
I do not know anything about this, I just know that the error I made, if possible show me how I do to know the information you need, I try to pass to you.

**Comment by alisonrag** [comment]
if your server use cryptkey the only xkore that will work is the xkore 2

but to visual mode work the xkore 0 need to work perfect

**Comment by alisonBR** [comment]
What is xkore 2? where can i download

**Comment by sctnightcore** [comment]
WTF.  config.txt > xkore 1,2,3

**Comment by alisonBR** [comment]
http://narutorpgonline.com/ hey there

**Comment by alisonrag** [comment]
xkore is a way how openkore will connect to server, visual mode is xkore 1,2,3

http://openkore.com/index.php/XKore

**Comment by alisonBR** [comment]
And about Xkore, it's 2

**Comment by sctnightcore** [comment]
openkore.com ! 
MENU 

I want to bot on private servers 
 GlHF

**Comment by alisonBR** [comment]
Plus the openkore of privately served, is not outdated

**Comment by alisonBR** [comment]
Soon I'm using the private Kore, but when I open the visual mode, and I put the password I take gravite error. 

Openkore:
start NRO.exe 1rag1 /account:../data/openkore.xml
exit

Openkore.XML:
<?xml version="1.0" encoding="euc-kr" ?>
<clientinfo>
    <servicetype>brazil</servicetype><servertype>primary</servertype><extendedslot></extendedslot>
    <connection>
        <display>XK2 [6901]</display><address>127.0.0.1</address>
        <port>6901</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [6902]</display><address>127.0.0.1</address>
        <port>6902</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [6903]</display><address>127.0.0.1</address>
        <port>6903</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [6904]</display><address>127.0.0.1</address>
        <port>6904</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [6905]</display><address>127.0.0.1</address>
        <port>6905</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [6906]</display><address>127.0.0.1</address>
        <port>6906</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [6907]</display><address>127.0.0.1</address>
        <port>6907</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [6908]</display><address>127.0.0.1</address>
        <port>6908</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [6909]</display><address>127.0.0.1</address>
        <port>6909</port>
        <version>1</version>
    </connection>
    <connection>
        <display>XK2 [IPREMOTO:6901]</display>
        <address>IPREMOTO</address>
        <port>6901</port>
        <version>1</version>
    </connection>
    <connection>
        <display>Poseidon</display> <address>127.0.0.1</address>
        <port>6900</port>
        <version>1</version>
    </connection>
</clientinfo>

**Comment by sctnightcore** [comment]
visual mode is ? xkore 3 ? or 2 ?

**Comment by alisonBR** [comment]
2

**Comment by sctnightcore** [comment]
well ! ok ! Run!!!

**Comment by alisonBR** [comment]
But it does not work. When I open the visual mode and try to log in to port 6901 appears another served, and I take gravite error

**Comment by sctnightcore** [comment]
You try using xkore3, it should work.

**Comment by Youtouchmytralala** [comment]
He havent read TFM so he wont configure x3.

**Comment by alisonBR** [comment]
and so you suggest me some idea

**Comment by alisonBR** [comment]
Another thing that can improve, for you to help me is: if I leave the visual mode configured to open by ragexe.exe, it opens is the setup of the game.

**Comment by sctnightcore** [comment]
Follow
http://openkore.com/index.php/Main_Page 
![8888888888888](https://user-images.githubusercontent.com/23263315/32132397-30002fea-bbed-11e7-91d1-231c490c191b.PNG)
I do not have time to test it.

**Comment by windhamwong** [comment]
This is not an issue of OpenKore. Please discuss private server connection in other places.

@alisonBR I highly recommend you to read the wiki page first. If you still have further issues or questions, you can go to the forum and create a thread for discussing your findings and issues.

**Comment by alisonBR** [comment]
Thanks for the help, problem already solved!
