### ISSUE TITLE
autowarpn.pl

### ISSUE THREAD

**Issue by blakbord** [OpenKore/openkore#1274]
I need help about this

in my config.txt I put this line
lockMap_autoWarp_from <map list>
lockMap_autoWarp_to <target>

in plugin folder I put this
"autowarp" (folder) and inside this folder I put the autowarpn.pl

why is it not working?

**Comment by alisonrag** [comment]
add to openkore\control\sys.txt
before:
`loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder`

after:
`loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,autowarp`

**Comment by alisonrag** [comment]
Any update?

**Comment by blakbord** [comment]
hi alisonrag, sorry for getting this topic back and for my late response.. I've been busy this past few days so I need to open this topic back again.. about my problem, I already did what you say but still not working..
