### ISSUE TITLE
Last version bot not heal,increase agi, blessing on master

### ISSUE THREAD

**Issue by oENUNAo** [OpenKore/openkore#1279]
On my head issue

**Comment by oENUNAo** [comment]
This is my config

partySkill Heal {
	lvl 7
	dist 3
	maxCastTime 0
	minCastTime 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 5
	disabled 0
	manualAI 0
	target
	target_hp <= 70%
	target_isJob
	target_isNotJob
	target_whenStatusActive
	target_whenStatusInactive
	target_aggressives
	target_monsters
	target_timeout 0
	target_deltaHp
	target_dead 0
	inInventory
	isSelfSkill 0
}

partySkill Increase AGI {
	lvl 10
	dist 3
	maxCastTime 0
	minCastTime 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 5
	disabled 0
	manualAI 0
	target
	target_hp
	target_isJob
	target_isNotJob
	target_whenStatusActive
	target_whenStatusInactive Increase AGI
	target_aggressives
	target_monsters
	target_timeout 100
	target_deltaHp
	target_dead 0
	inInventory
	isSelfSkill 0
}

**Comment by oENUNAo** [comment]
Please, help me.

**Comment by alisonrag** [comment]
try to download again, we reverted this update yesterday

**Comment by sctnightcore** [comment]
target ?

**Comment by alisonrag** [comment]
any update?

**Comment by oENUNAo** [comment]
Now Increase AGI and Blessing are work, But Heal not work
