### ISSUE TITLE
openkore incoming data left in the buffer

### ISSUE THREAD

**Issue by bunnyy00** [OpenKore/openkore#1282]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary:I am trying to run in doram newbie land lasa_fild01, and i have got this message ( I downloaded the latest version of openkore just few minutes ago)
![18 10 2017](https://user-images.githubusercontent.com/25070736/31706089-59eedc64-b41a-11e7-8372-4ea6a50c07a8.png)

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
two possibilities:
1 - your servertype is wrog
2 - the kore have not implemented this map  yet

**Comment by bunnyy00** [comment]
Ok thank you
