### ISSUE TITLE
config double slow Help me

### ISSUE THREAD

**Issue by Junezavr** [OpenKore/openkore#1283]
config hunter
attackSkillSlot AC_DOUBLE {
	lvl 10
	sp > 20 %
	minCastTime 0.1
	inLockOnly 1
	maxUses 1
	monsters Miyabi Doll,Firelock Soldier,Shinobi
	target_whenStatusActive EFST_LEXAETERNA
Time out
ai_skill_use 0.50

config priest
monsterSkill PR_LEXAETERNA {
	target Miyabi Doll,Firelock Soldier,Shinobi
	maxUses 1

logs console
[100/100] You attack Monster Miyabi Doll (0) (Dmg: 445) (Delay: 190ms)
Player Priest name (0) is casting Lex Aeterna on Monster Miyabi Doll (0) (Delay: 0ms)
Player Priest name (0) uses Lex Aeterna on Monster Miyabi Doll (0) (Lv: 1)
[100/100] You attack Monster Miyabi Doll (0) (Dmg: 822) (Delay: 190ms)
You are no longer: EFST_POSTDELAY
You are casting Double Strafe on Monster Miyabi Doll (0) (Delay: 0ms)
[100/ 97] You use Double Strafe (Lv: 10) on Monster Miyabi Doll (0) (Dmg: 1676) (Delay: 190ms)
You are now: EFST_POSTDELAY (Duration: 0.1s)

skill Double slow in use
help me in config and timeout
i need kore
You attack  > Player Priest uses Lex Aeterna >  You use Skill Double

but mykore

You attack  > Player Priest uses Lex Aeterna >You attack >  You use Skill Double

kore Double Strafe not straight Lex Aeterna

**Comment by fadreus** [comment]
Try this;

- `mon_control.txt` set Miyabi Doll, Firelock Soldier & Shinobi to 3

- Hunter `config.txt`
```
monsterSkilll 46 {
target Miyabi Doll, Firelock Soldier, Shinobi
sp >= 12
target_whenStatusActive Lex Aeterna
}
```

If you want 100% usage of Lex Aeterna, can try set Priest as Master & Hunter as Slave.
Use `mon_control.txt` 3 for Priest.

**Comment by Junezavr** [comment]
@fadreus  This is the second time you have helped me.

**Comment by Junezavr** [comment]
I'll try again when I'm available.

**Comment by alisonrag** [comment]
@Junezavr 
this time will be the last time that we approve this type of topic here, this section is to report bug, it's not to ask for help.
for this use:
forums.openkore.com

**Comment by Junezavr** [comment]
@alisonrag I will not do it again.

**Comment by alisonrag** [comment]
thanks =]
if the solution of @fadreus  work, let us know or close this issue

**Comment by Junezavr** [comment]
I will close issuse when I try to succeed
Thanks

**Comment by Junezavr** [comment]
I do not know how it works thanks for help
