### ISSUE TITLE
hello im new here

### ISSUE THREAD

**Issue by franzhiro12345** [OpenKore/openkore#1284]
can you help me make a code that hunts gtb and when kills/or see a tomb log off and log in after 1hr/ or calclate that time when gtb ressurect again..is its posible first time post im new here.. hopr u guys can help me..

**Comment by joecabezas** [comment]
welcome, while community is always welcome to help, I suspect this is not
the right channel, since this works more like as an issue tracker rather
than a openkore forum, I suggest you to redirect your question to any
community driven forum if you don't get an answer here

**Comment by alisonrag** [comment]
this place is to report bugs

use this site to ask for help:
http://forums.openkore.com/
