### ISSUE TITLE
Im trying to add plugin hook into Corelogic.pm

### ISSUE THREAD

**Issue by oleokoong** [OpenKore/openkore#1295]
This is my first time to add modification into src file.
CoreLogic.pm
i wish to add hook after this line

message T("Auto-sell sequence completed.\n");
Plugins::callHook("sell_complete");
"success";

which i refer from Attack.pm 
message T("Target died\n"), "ai_attack";
Plugins::callHook("target_died", {monster => 

unfortunally i got this error, did i miss something on the CoreLogin Line?
 [eventMacro] Event of type 'hook', and of name 'sell_complete' activated automacro 'test111111', calling macro 'tempMacro60'
[eventMacro] Running macro 'tempMacro60' got orphaned, its orphan method is 'terminate'.

**Comment by alisonrag** [comment]
post your code here.

**Comment by oleokoong** [comment]
automacro clearout {
SimpleHookEvent sell_complete
timeout 30
call {
do respawn
log 123
relog
}
}

**Comment by alisonrag** [comment]
CoreLogic, Line 1540:

```
message T("Auto-sell sequence completed.\n"), "success";
Plugins::callHook("sell_complete");
```

```
automacro clearout {
SimpleHookEvent sell_complete
exclusive 1
call {
do respawn
log 123
do relog
}
}
```

**Comment by oleokoong** [comment]
it still produce same error.. i will get back to you later..quite busy recently

**Comment by Mortimal** [comment]
#1139 ? why not them?

**Comment by Nipodemos** [comment]
@Mortimal 
no, he is trying to put a hook on auto_sell, not on deal
i think its very good!!

**Comment by alisonrag** [comment]
try this
CoreLogic, Line 1540:
```
message T("Auto-sell sequence completed.\n"), "success";
Plugins::callHook("sell_complete");
```

eventMacros.txt:
```
automacro clearout {
    SimpleHookEvent sell_complete
    exclusive 1
    call clearoutM
}
macro clearoutM {
        do respawn
        log 123
        do relog
    }
}
```

**Comment by oleokoong** [comment]
@mortimal last time you did the target _died macro for me, now I’m trying to make macro after autosell , or autobuy

The original sequence is bot back to town autosell, then autobuy , then call hook for macro...

But I don’t which line is autobuy done, only found autosell complete

**Comment by sctnightcore** [comment]
@Mortimal  Do you have a discord.? I have something to talk to you.

**Comment by oleokoong** [comment]
#1306
