### ISSUE TITLE
Login to X-mode it's FREEZE......

### ISSUE THREAD

**Issue by oENUNAo** [OpenKore/openkore#1296]
I've try to use Xmode on iRO Re:start when client show game it "Freeze" can't do anything. But on normal bot it work.  How can i do to use X-mode

THX...

**Comment by fadreus** [comment]
#1227 
#1290 
#1287 
![image](https://user-images.githubusercontent.com/32188494/31853100-fb6d2774-b6b5-11e7-8b18-96b6741f3dc6.png)

**Comment by Youtouchmytralala** [comment]
>How can i do to use X-mode
RTFM
