### ISSUE TITLE
Cannot send encoded password : idRO

### ISSUE THREAD

**Issue by qorma8** [OpenKore/openkore#1298]
hi guys, after new patch on idRO, i got this issue,
anyone got the same issue ?

![asd](https://user-images.githubusercontent.com/20570223/31859092-b91dba7a-b730-11e7-80f6-9e5569b74145.png)

server.txt
[Indonesia - idRO: Midgard]
ip 202.93.25.81
port 6900
master_version 12
version 2
patchserver fpatch.ragnarok.co.id
patchpath /patch02
serverType idRO
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 144
charDeleteDateType 1

**Comment by qorma8** [comment]
This my server.txt.

[Indonesia - idRO: Thor - Legend - Fnc - Heroes]
ip 202.93.25.81
port 6900
master_version 12
version 2
patchserver fpatch.ragnarok.co.id
patchpath /patch02
serverType idRO
secureLogin 1
secureLogin_type 0
secureLogin_requestCode 
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 116

**Comment by sctnightcore** [comment]
`secureLogin_requestCode`

**Comment by XCBX** [comment]
different 0069 packet i believe

**Comment by qorma8** [comment]
@sctnightcore : so what should i do ?
@XCBX : where to change it ?

**Comment by sctnightcore** [comment]
I can not download idRO HAHAHA @qorma8

**Comment by sctnightcore** [comment]
0A75 new login packet!

**Comment by slianto** [comment]
@sctnightcore what to do?pls help!

i also encounter the same problem :(

**Comment by qorma8** [comment]
@sctnightcore  no luck bro.
anyone can help us  ?

**Comment by SoulDylan** [comment]
i have the same problem, need help

**Comment by alisonrag** [comment]
use #634
