### ISSUE TITLE
Equip Auto Error Bot Can Not Use Command Equip

### ISSUE THREAD

**Issue by Ax3l210817** [OpenKore/openkore#1299]
Why my bot always disconnect when i used macro command do eq @inventory(Item Name) and also in command console with command "eq" ? Pls help me i play in idRO Ragnarok Gravindo Thx

**Comment by Nipodemos** [comment]
@ inventory is not working on macro plugin anymore

you should use eventMacro plugin

**Comment by fadreus** [comment]
I didn't know it is not working anymore.
After reading this I try something with `@inventory` & it is not working but somehow this one is still working.
```
automacro FlyAway {
pubm /(.*?)/
call {
do is @inventory (Fly Wing)
}
}
```

**Comment by Kelberwitz** [comment]
i was try to use  " do eq Novice Main-Gauche " with macro its work for me .

**Comment by Glikadin** [comment]
Try just:

`do eq Novice Main-Gauche`

**Comment by oqhadev** [comment]
wrong packet send_equip

https://github.com/OpenKore/openkore/blob/master/src/Network/Send/idRO.pm
replace line 26  to be
`send_equip 0998
`

**Comment by sctnightcore** [comment]
@oqhadev  go PR XD .
