### ISSUE TITLE
Illegal Division By Zero when calculating target HP before using skill

### ISSUE THREAD

**Issue by gbudiman** [OpenKore/openkore#1300]
###### Affected configuration(s)/ file(s): Misc.pm :: sub checkMonsterCondition() (Line 4355)
```
	if ($config{$prefix . "_hp"}) {
		return 0 if (!$monster->{hp});
		if ($config{$prefix . "_hp"} =~ /^(.*)\%$/) {
			return 0 unless (inRange(($monster->{hp} * 100 / $monster->{hp_max}), $1)); 
		} else {
			return 0 unless (inRange($monster->{hp}, $config{$prefix . "_hp"})); 
		}
	}
```
###### Steps to Reproduce:
attackSkillSlot <skill_name> { target_hp >25% }

I used Sonic Blow with target_hp >25%
Occasionally, $monster->{hp_max} is zero for some reason, causing the crash. A simple fix would be to add zero-division check, where a failure will result to skill not used instead of crashing the bot.

**Comment by alisonrag** [comment]
monster_hp are implemented only in servers that send to the client the monster hp, in almost every official server, in private server the emulator send the hp in some packet else.

this should fix:
```
if ($config{$prefix . "_hp"}) {
		return 0 if (!$monster->{hp} || !$monster->{hp_max} );
		if ($config{$prefix . "_hp"} =~ /^(.*)\%$/) {
			return 0 unless (inRange(($monster->{hp} * 100 / $monster->{hp_max}), $1)); 
		} else {
			return 0 unless (inRange($monster->{hp}, $config{$prefix . "_hp"})); 
		}
	}
}
```

**Comment by gbudiman** [comment]
@alisonrag I don't get what you said. The interpreter crashed at the if- branch, which is this line
```return 0 unless (inRange(($monster->{hp} * 100 / $monster->{hp_max}), $1)); ```

This is iRO Restart server, which is an official server.

**Comment by alisonrag** [comment]
in openkore\src\Misc.pm

change this:
`return 0 if (!$monster->{hp});`

to this:
`return 0 if (!$monster->{hp} || !$monster->{hp_max} );`

and post the result

**Comment by c4c1n6kr3m1** [comment]
afaik, yes , a few months ago

damn more traffic

**Comment by alisonrag** [comment]
any update?
