### ISSUE TITLE
[eventMacro] PrivMsgName is not accepting variables

### ISSUE THREAD

**Issue by Nipodemos** [OpenKore/openkore#1301]
##### Summary: 
My problem here, is that the regex of name of the player of who you want to receive the message nevem works if i use a variable

Detail: if i us **PrivMsg** instead of **PrivMsgName** it works normally
##### Affected configuration(s)/ file(s):
```perl
#if there is any typo, it is because i translated for this issue, it is written in portuguesee
﻿automacro nameOfMerchant {
	priority -20 
	run-once 1
	BaseLevel > 0
	exclusive 1
	CheckOnAI auto,manual,off
	call {
		$nomeDoMercador = &nick(Nipodemos) 
                $messageThatActivesTheMacro = come here
        }
}

automacro startToGetTheItens {
	PrivMsg /$messageThatActivesTheMacro/  /$nomeOfMerchant/ 
	exclusive 1
	call {
		do conf -f passItens sim
		do pm $.PrivMsgLastName ok
		do autosell
	}
}
```
##### Impact:
i am not able to use this condition at full potential
##### Expected Behavior:
triggers when the privMsgIs sended
##### Actual Behavior:
nothing happens
##### Steps to Reproduce:

- log two bots, one to receive the item e other to send the item
- on the bot that send the item, put this piece of code
-  on other bot, send a pm with the phase **come here**
- see if it will trigger or not

**Comment by alisonrag** [comment]
this was fixed by: #2124

```
automacro nameOfMerchant {
	priority 0
	run-once 1
	BaseLevel > 0
	exclusive 1
	CheckOnAI auto,manual,off
	call {
		$nomeDoMercador = &nick(AngelTester) 
        $messageThatActivesTheMacro = HelloFromMe
    }
}

automacro startToGetTheItens {
	PrivMsgName /$messageThatActivesTheMacro/ /$nomeDoMercador/
	exclusive 1
	call {
		do pm $.PrivMsgNameLastName ok
	}
}
```

![image](https://user-images.githubusercontent.com/10372732/186680390-641c4ef1-f275-4e59-beb2-89510317a254.png)
