### ISSUE TITLE
MLRO BOT problem, please help

### ISSUE THREAD

**Issue by veeny** [OpenKore/openkore#1302]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary: 
please help, my MLRO setting

ip 106.106.167.36
port 6900
master_version 5
version 211
private 1
serverType kRO_RagexeRE_2015_05_13a
serverEncoding western
charBlockSize 147
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders twRO
captcha 0

when run, it stuck and can't connected. Here is the picture to show you.
![image](https://user-images.githubusercontent.com/13540203/31901318-b532334a-b853-11e7-92c9-b8dac2ccab54.png)

but if i put this setting as below, it will always come out this error
![image](https://user-images.githubusercontent.com/13540203/31901645-9bcff328-b854-11e7-96c9-50ba4c6629fa.png)

ip 106.106.167.36
port 6900
master_version 5
version 211
private 1
serverType twRO
serverEncoding western
charBlockSize 147
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders twRO
captcha 0

please help me. thx you

**Comment by sctnightcore** [comment]
wellllllllllllllllllllllllllllllll 

GG ? 
packet key ? 
privater server ?

**Comment by veeny** [comment]
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1410697/recvpackets.txt)

this is the recvpacket generated by peek, yup, twRO private server

**Comment by sctnightcore** [comment]
```
ip 106.106.167.36
port 6900
master_version 5
version 211
private 1
serverType twRO
serverEncoding western
charBlockSize 147
sendCryptKeys ? 
```

**Comment by veeny** [comment]
Hi, please look at the first setting that I set ServerType kRO_RagexeRE_2015_05_13a, this setting had no error packet key came out, but cannot connect to server...this is the link to download...but all in Chinese word
http://bbs.mlro.tw/thread-15-1-1.html

**Comment by sctnightcore** [comment]
@veeny ok sir

**Comment by veeny** [comment]
ID : help
pass : Rescue

thx you.

**Comment by veeny** [comment]
OMG, i just realize that your profile picture is REM, i'm super fan of her.

**Comment by sctnightcore** [comment]
@veeny  ok sir 
i will test it !

**Comment by veeny** [comment]
ok thx, wait for your good news.

**Comment by sctnightcore** [comment]
@veeny 
![image](https://user-images.githubusercontent.com/23263315/31956414-a533b622-b915-11e7-8f92-a945dbf22756.png)
ok ! 
I have something to say 
1.Finding a date client is not right.
2.Openkore.com has everything you need.


```
[MlRO]
ip 106.106.167.36
port 6900
master_version 5
version 211
private 1
serverType kRO_RagexeRE_2017_01_25a
serverEncoding western
charBlockSize 147
sendCryptKeys 0x066E04FE,0x04FF0458,0x3004224A
addTableFolders twRO
```
```
recvpacket get from tables > kRO > RagexeRE_2017_01_25a 
fix recvpacket > go to #1281
https://github.com/sctnightcore/openkore/blob/c4ec3fa09aea78c3c039b0eccca78098428b3fcb/tables/kRO/RagexeRE_2017_01_25a/recvpackets.txt
```

**If you do not edit the recvpacket // to #
openkore may not work**

**Comment by veeny** [comment]
![image](https://user-images.githubusercontent.com/13540203/31960946-ddd56be0-b92b-11e7-8725-9a46e2d1937c.png)

well, it working now, haha, thx you so much for your patient, but the packet parser :unknown switch error will effect the BOT?

**Comment by sctnightcore** [comment]
I think not
♥ @veeny

**Comment by veeny** [comment]
Okie, thx you so much 😘
