### ISSUE TITLE
can someone tech me how to setting the auto storage for iro

### ISSUE THREAD

**Issue by elviestan** [OpenKore/openkore#1303]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
Everything is on the openkore wiki.
```
storageAuto 0
http://openkore.com/index.php/StorageAuto
storageAuto_npc
http://openkore.com/index.php/StorageAuto_npc
storageAuto_distance 5
storageAuto_npc_type 1
storageAuto_npc_steps
http://openkore.com/index.php/StorageAuto_npc_steps
```
