### ISSUE TITLE
Latest commit on CoreLogic.pm broke plugin

### ISSUE THREAD

**Issue by Pachu1985** [OpenKore/openkore#1305]
###### Affected configuration(s)/ file(s): config.txt, planwalk.txt
```Include relevant code snippets and source code references```

**Comment by c4c1n6kr3m1** [comment]
read the instrucion again, afaik some plugin need you to edit your src to make it work

**Comment by lututui** [comment]
Not an officially supported plugin. Ask the developer to update, if that's the case.
