### ISSUE TITLE
Xcore 1 problem Can use skill, can hit monster, can't move

### ISSUE THREAD

**Issue by Gaizama** [OpenKore/openkore#1307]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by Youtouchmytralala** [comment]
Too bad.

**Comment by alisonrag** [comment]
Please use the issue template, please post infornations about the server and your configuration

**Comment by windhamwong** [comment]
Insufficient details for investigation. Closing.

@Youtouchmytralala , there is no point for leaving such comment.
