### ISSUE TITLE
[BUG] partySkill doesnt work instead it casts on itself

### ISSUE THREAD

**Issue by drunkenhammer** [OpenKore/openkore#1314]
My support bot is suppose to buff and heal the master but instead it heals itself instead

partySkill Heal {
	lvl 5
	target_hp < 70%
	target 5
	sp > 10%
	timeout 3
}

partySkill Blessing {
	lvl 10
	sp > 64
	notInTown 1
	target 4
	target_whenStatusInactive Blessing
	target_timeout 240
	timeout 3
}

partySkill Increase AGI {
	lvl 10
	sp > 45
	notInTown 1
	target 4
	target_whenStatusInactive Increase AGI
	target_timeout 240
	timeout 3
}

Here is the log on where the support is trying to use bless on my master but instead spammed this skills to itself

[Oct 25 10:06:56 2017.20] Found my master!
[Oct 25 10:06:56 2017.29] Packet Parser: Unknown switch: 0AB8
[Oct 25 10:06:56 2017.35] You are casting Blessing on yourself (Delay: 0ms)
[Oct 25 10:06:56 2017.41] You are again: Blessing (Duration: 220s)
[Oct 25 10:06:56 2017.45] You use Blessing on yourself (Lv: 9)
[Oct 25 10:06:56 2017.52] Packet Parser: Unknown switch: 0AB8
[Oct 25 10:06:57 2017.31] You are casting Blessing on yourself (Delay: 0ms)
[Oct 25 10:06:57 2017.40] You are again: Blessing (Duration: 220s)
[Oct 25 10:06:57 2017.44] You use Blessing on yourself (Lv: 9)
[Oct 25 10:06:57 2017.53] Packet Parser: Unknown switch: 0AB8
[Oct 25 10:06:58 2017.29] You are casting Increase AGI on yourself (Delay: 475ms)
[Oct 25 10:06:58 2017.83] You are again: Increase AGI (Duration: 240s)
[Oct 25 10:06:58 2017.88] You use Increase AGI on yourself (Lv: 10)
[Oct 25 10:06:58 2017.94] You are now: EFST_POSTDELAY (Duration: 1s)
[Oct 25 10:06:59 2017.10] Item Appeared: Bear's Footskin (0) x 1 (166, 265)
[Oct 25 10:06:59 2017.82] You are no longer: EFST_POSTDELAY
[Oct 25 10:07:00 2017.71] [dist=5] Monster Elder	Willow (0): *Sweat*
[Oct 25 10:07:00 2017.81] [dist=unknown] Unknown #50473: *$!@#*
[Oct 25 10:07:00 2017.86] Unknown #50473 uses Fireattack on Unknown #263170 (Dmg: Miss) (Delay: 672ms)

I tried disabling it and it works. I even set the target to the master name and still casts on itself.

**Comment by alisonrag** [comment]
enable bus in sys.txt and use this plugins:
Slave:
https://github.com/OpenKore/openkore/tree/master/plugins/needs-review/busFollow/trunk

Master:
https://github.com/OpenKore/openkore/tree/master/plugins/needs-review/wait4party/trunk

Both:
https://github.com/OpenKore/openkore/tree/master/plugins/needs-review/busParty/trunk

plus try:

partySkill Heal {
lvl 5
target_hp < 70%
sp > 10%
timeout 3
}

partySkill Blessing {
lvl 10
sp > 64
notInTown 1
timeout 240
}

partySkill Increase AGI {
lvl 10
sp > 45
notInTown 1
timeout 240
}

**Comment by c4c1n6kr3m1** [comment]
target _partyname1,partyname2,partyname3_

**Comment by fadreus** [comment]
Or he meant this bug from #1272 ?

**Comment by alisonrag** [comment]
@fadreus 
this bug was corrected, it doesn't exists anymore

**Comment by fadreus** [comment]
Some people just didn't update their openkore, just wondering if he using that version.

**Comment by windhamwong** [comment]
@drunkenhammer should try to remove `target` to see if it is working to all party members.

Looks like there is no more feedback from @drunkenhammer . We cannot tell whether he is using the latest version or not. I will close it until he is coming back to reopen it.
