### ISSUE TITLE
iRO:Restart - Xkore 3 fixes for encrypt do not work

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#1322]
This is on iRO:Restart, I manually patched that didn't work, so i downloaded the entire branch and it still doesn't work.  Gets to the point it shows the server and ip address then says Closing connection and then disconnecting, doesn't even load into the game at all.  I'm sure you know xkore 1 allows login but the character is just stuck and can't move cast or anything.

Really hope xkore get's fixed.  Botting with simply a command line interface isn't safe with how the GMs are out banning.

**Comment by sctnightcore** [comment]
#1227

**Comment by alisonrag** [comment]
Tested yesterday with my branch and was working flawless

**Comment by Zexeta** [comment]
There was another client update today, perhaps they changed the encrypt key again?

**Comment by sctnightcore** [comment]
Server Update> new packet key @Zexeta 
Update your openkore and test again.

**Comment by Zexeta** [comment]
I tried both versions on alisons branch and neither work properly for me.  I can load into the game, none of the spells appear on the bars and i cant move.  I check the console and its spamming that its reconnecting repeatedly.   The other version doesn't even load in at all.  I am not sure how this supposedly is working?  I literally did an entire download, simply enabled Xkore 3 in the config and opened it and it doesn't work.

**Comment by alisonrag** [comment]
use #1227
