### ISSUE TITLE
Timeout on map server IRO CHAOS

### ISSUE THREAD

**Issue by appapie** [OpenKore/openkore#1323]
After today's maintenance update the "timeout on map server" problem is back.  Probably the crypt key thing again?

**Comment by sctnightcore** [comment]
download new openkore and test again ! .

**Comment by Xregretor** [comment]
I did redownload but Same Problem occur, time out on account server........

**Comment by appapie** [comment]
Same here.  Downloaded latest, but still timeout on map server.

**Comment by appapie** [comment]
Fixed by allanon.  Thank you!
[https://github.com/OpenKore/openkore/pull/1321](url)

**Comment by batangmahaba** [comment]
HELP! time out on map server after iRO update last december 27, 2017
