### ISSUE TITLE
eventMacro error. (got orphaned, its orphan method is 'terminate'.)

### ISSUE THREAD

**Issue by oleokoong** [OpenKore/openkore#1325]
[eventMacro] Event of type 'hook', and of name 'AI_buy_auto_done' activated automacro 'autotrade', calling macro 'izc'
[eventMacro] Running macro 'izc' got orphaned, its orphan method is 'terminate'.

Im download fresh openkore from github..

automacro autotrade {
	SimpleHookEvent AI_buy_auto_done
	timeout 30
	call izc
}
macro izc {
	do ai manual
	do respawn
	do ai on
}

watever how i change the macro izc, its still show error above..
should i add something like ($.SimpleHookEventLast<capitalized variable name>) ?

**Comment by sctnightcore** [comment]
```
automacro autotrade {
	SimpleHookEvent AI_buy_auto_done
	timeout 30
	call {
		do ai manual
		do respawn
		do ai on
	}
}	
```
https://github.com/sctnightcore/eventmacro-by-me-/blob/master/resetaibuysell.txt

**Comment by oleokoong** [comment]
@sctnightcore 
still have the error, and the automacro must have timeout , if not will keep spamming same automacro

**Comment by sctnightcore** [comment]
@oleokoong  test it again ! 
timeout > pause

**Comment by oleokoong** [comment]
only timeout can use as condition,

automacro aibuyandsellreset {
	SimpleHookEvent AI_sell_auto_complete,AI_buy_auto_done
	timeout 10
	call {
	do ai clear
	pause 1
	log reset ai buy/sell
}
}

**Comment by sctnightcore** [comment]
ok sir @oleokoong  test it again ! . 
Not sure if it will work. XD

**Comment by oleokoong** [comment]
need someone can explaine what the error means.

Running macro 'izc' got orphaned, its orphan method is 'terminate'.

**Comment by sctnightcore** [comment]
```
automacro autotrade {
	SimpleHookEvent AI_buy_auto_done
	call izc
}
macro izc {
	do ai manual
	do respawn
	do ai on
}
```
@Nipodemos

**Comment by Nipodemos** [comment]
The problem is the hook , it is in the wrong place inside the source code of Openkore 

That's why it is happening this

**Comment by oleokoong** [comment]
@Nipodemos thanks for the information.
@lututui need your help here..

**Comment by oleokoong** [comment]
issue solve..
move hook down 2 line
		AI::dequeue;
		Plugins::callHook('AI_buy_auto_done');
		if ($ai_v{'temp'}{'var'} && $config{storageAuto}) {
