### ISSUE TITLE
IRO-Restart , Why is my bot not using any potion, I;m using new version of open kore

### ISSUE THREAD

**Issue by rexlim7** [OpenKore/openkore#1326]
useSelf_item Novice Potion, Red Potion, {
	hp < 60
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 1
	notWhileSitting 1
	notInTown 1
	timeout
	disabled 0
	inInventory
	manualAI 0

useSelf_item Novice Potion {
	hp < 60%                                or                 hp < 60 %
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 1
	notWhileSitting 1
	notInTown 1
	timeout
	disabled 0
	inInventory
	manualAI 0

All i had tried but could not work, please help .Thanks

**Comment by sctnightcore** [comment]
```
useSelf_item Meat,Apple,Banana,Sweet Potato,Potato,Carrot,Novice Potion,Red Potion,Orange Potion,Yellow Potion,White Potion {
    hp < 80%
}

```

test it !

**Comment by rexlim7** [comment]
I already test it, the bot still won't use the potion @sctnightcore

**Comment by sctnightcore** [comment]
![3333333333333333](https://user-images.githubusercontent.com/23263315/32131040-96aff898-bbce-11e7-8f2f-e089706317d2.PNG)

I tested it and it worked.

**Comment by oleokoong** [comment]
inLockOnly 1
notWhileSitting 1
notInTown 1

these 3 condition 
maybe your bot sit first before use pot

**Comment by fadreus** [comment]
Well, unless you edit your config for posting it here only

# Where the closing bracket?   =     }

**Comment by oleokoong** [comment]
useSelf_item Novice Potion {
	hp < 50%
	inInventory Novice Potion > 0
}

**Comment by windhamwong** [comment]
It is better to attach/upload your config (WITHOUT your username/password) to somewhere for us to review.

**Comment by alisonrag** [comment]
try to download the latest version and use the block posted by @oleokoong
