### ISSUE TITLE
how to auto update opencore

### ISSUE THREAD

**Issue by lalilulelo1** [OpenKore/openkore#1327]
hello guys, anyone can tell me how to auto update opencore?
since last patch 10/26/2017 my opencore always disconnecting after connected
this is the same like previously patch
and after updating the file like server.txt in tables folder or recvpacket.txt, shuflle.txt, sync.txt ind tables>iRo folder, the opencore can work again..
and i try to looking the issue about this matters, but cant find the issue

thanks before

![bot iro](https://user-images.githubusercontent.com/32214970/32131333-bf41fdc2-bbd5-11e7-8ef0-f81e7a1f85bd.png)

**Comment by sctnightcore** [comment]
The simplest way  download new openkore HAHAHAHAHAHAHAHAHAHAHAHAHA
use with github desktop and something.

**Comment by fadreus** [comment]
### I use TortoiseSVN to update (only works if fixes pulled to master branch).
![image](https://user-images.githubusercontent.com/32188494/32131403-db7b61e0-bbdf-11e7-806e-022821474161.png)

### At openkore wiki, the links given are from svn/sourceforge.
![image](https://user-images.githubusercontent.com/32188494/32131476-6fd8027a-bbe1-11e7-9852-c0cc0cc3be5e.png)

### Replace the link with github.
![image](https://user-images.githubusercontent.com/32188494/32131471-5329abc4-bbe1-11e7-862c-7fc0bb98133e.png)

### Do note that by doing this it will download everything from masterbranch (including those needs-review plugin; which is large-sized in total but you can exclude or remove it later).

*Unless someone have some program to check updates like windows update, this is the most easiest way for anyone who not familiar with editing codes (or lazy one like me xD).

**Comment by lalilulelo1** [comment]
@sctnightcore maybe i can try it for my pc at home,

@fadreus my opencore doesn't look like yours, and if i redownload opencore like yours, my old opencore will be replaced?

**Comment by fadreus** [comment]
If you download at the same directory, it will.
If you download at different directory, it won't.

**Comment by windhamwong** [comment]
@lalilulelo1 if you are not familiar with git, I recommend you to download a new copy from here and replace files EXCEPT config folder.
The tool @fadreus is using is called TortoiseGIT.

**Comment by windhamwong** [comment]
Please reopen if you still have issues with updating. I believe the solution @fadreus and I suggested can tackle the issue you mentioned.
