### ISSUE TITLE
Anywork in progress

### ISSUE THREAD

**Issue by ncplay91** [OpenKore/openkore#1329]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:

So I found out this "supposed to be" plugin to fix "any work in progress (NPC dialog, manufacturing...)quit and try again."

automacro cancelWarp {
        console "any work in progress (NPC dialog, manufacturing...)quit and try again."
        delay 0.3
        timeout 3
        call {
                do warp cancel
        }
}

and I created cancelwarp.pl in macro folder.. and it doesn't work...
The bot often stuck..
I also read on the other forum to put it in macros.txt... but when I searched for macros.txt there are like 4 exact same files with different content.. I don't know which macros.txt did that person mention.

Please kindly illuminate this puzzle for me..

**Comment by alisonrag** [comment]
in openkore\control create a macros.txt file and put this code inside, just save and start openkore

**Comment by lututui** [comment]
If tweak your timeouts
