### ISSUE TITLE
how to use of PEEK generate data 'PacketLengths.ini'  about Shuffle_Packets tag??

### ISSUE THREAD

**Issue by a115027a** [OpenKore/openkore#133]
hello,in TWRO  i got PacketLengths.ini from PEEK.
And this file have 3 tag.
[Packet_Lengths]
[Packet_Keys]
[Shuffle_Packets]
i know [Packet_Lengths]  tag data put in to recvpack.txt
[Packet_Keys] tag data put in to cryptKeys .
but  i don't really understand hot to use this.

i try do this,
change about /src/Network/Send/tRO.pm
'08AB'

```
my %packets = (
    '08AB' => ['map_login', 'a4 a4 a4 V C', [qw(accountID charID sessionID tick sex)]],
my %handlers = qw(
    map_login 08AB
```

is it change this? about  Shuffle_Packets?

thanks

**Comment by AlexandreBR3N** [comment]
Re-read the guide 👍 
http://forums.openkore.com/viewtopic.php?f=36&t=207278

script re-added. temporarily.
