### ISSUE TITLE
openkore not working restart iro

### ISSUE THREAD

**Issue by robt101** [OpenKore/openkore#1331]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by blakbord** [comment]
it is 100% working to me on Restart

**Comment by sctnightcore** [comment]
download new openkore ! and test again !

**Comment by robt101** [comment]
nothing happen

**Comment by sctnightcore** [comment]
@robt101 what?

**Comment by robt101** [comment]
timeout on map server
timeout on account server
i updated and redownload nothing happen :)

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/32139614-5f7b93d2-bc78-11e7-9023-a01f4b31c8b3.png)
@robt101 new openkore work !

**Comment by robt101** [comment]
really darn.... can you send a linked where to download the whole thing maybe im downloading the wrong thing

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/32139636-2cf15284-bc79-11e7-9390-ec1fb39e0809.png)


https://github.com/OpenKore/openkore/archive/master.zip

**Comment by oleokoong** [comment]
deng deng deng.. how come not working.. im the 1 tell allanon to update the shuffle..

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/pull/1313/commits/49b6e69bd030763ce2502994d5c6704171252737

@robt101  Now it's been updated.

**Comment by robt101** [comment]
lol all it needs was my old config. thanks for the help

**Comment by sctnightcore** [comment]
If your bot ok .
close issues.
♥
