### ISSUE TITLE
Help Please Autowarp Plugin

### ISSUE THREAD

**Issue by blakbord** [OpenKore/openkore#1332]
does autowarp plugin have a bug?

my bot says "Preparing to cast a warp" but it didn't cast a warp
after that my bot starts to walk and talk to kafra.

in my config.txt I put this line.
autoWarp_from payon <--- my save point
autoWarp_to glast_01 <--- my lockmap

PS: I have blue gemstones in my inventory

**Comment by sctnightcore** [comment]
lockmap glast_01

**Comment by blakbord** [comment]
thanks, I'm gonna try this macro..
