### ISSUE TITLE
iRO Chaos- Homunculus Dropping Target

### ISSUE THREAD

**Issue by igeloid** [OpenKore/openkore#1334]
I keep on getting the message that my homunculus will not kill steal others even if there is nobody nearby. This effectively stops it from killing anything. I tried looking for a solution but I can't find one. Is there any fix for this? I'm using the latest version of openkore.

**Comment by fadreus** [comment]
Kindly upload your config.txt

**Comment by igeloid** [comment]
[config.txt](https://github.com/OpenKore/openkore/files/1425319/config.txt)

**Comment by fadreus** [comment]
Try this [config.txt](https://github.com/OpenKore/openkore/files/1425343/config.txt)

**Comment by igeloid** [comment]
Fadreus, the config you provided seems to have solved the problem. Thank you so much. 👍
May I know what was wrong with my original config? This is to avoid the same mistake in the future.

**Comment by fadreus** [comment]
```
attackAuto -1 <----------------(This caused you to walk away without engaging in any monster)
attackUseWeapon 1<-------------(You won't land a hit on monster but still engaging in battle) 
attackNoGiveup 0<--------------(Give time for homun to kill without dropping target)
```

The rest are just for insurance.
