### ISSUE TITLE
Autostorage only opens storage but doesn't actually store anything

### ISSUE THREAD

**Issue by ncplay91** [OpenKore/openkore#1335]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

So for the sake of testing the function, I set all 0 1 0 at items control
and here's my config

storageAuto 1
storageAuto_npc aldebaran 143 119
storageAuto_distance 5
storageAuto_npc_type 1
storageAuto_npc_steps  c r1 n
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 0

Kore only opens storage.. and then close it without actually storing anything and it proceed to sell all the precious items... - _ -"

What went wrong?

**Comment by Junezavr** [comment]
You can open storage
Yes or no

**Comment by fadreus** [comment]
Try delete all content in `items_control.txt` and write only this:

`all 0 1 0`

**Comment by ncplay91** [comment]
That's exactly what I do.. and kore doesn't do anything... just open storage and close it.
The same with autosell.

**Comment by fadreus** [comment]
Someone probably would gladly assist you if you can just provide more information like what server you are playing, what openkore version you are using, console's log, print screen, etc etc etc.

What I can recommend is simply download new one and try again.

**Comment by oleokoong** [comment]
let me guess is IRO Restart..
for me, i just disable autostorage

**Comment by ncplay91** [comment]
@oleokoong totally right.. it's restart... and now both autosell and autostorage dont work.. this is getting weird day by day

**Comment by oleokoong** [comment]
you have to get lastest copy to run... dont copy and paste control folder...

**Comment by sctnightcore** [comment]
@ncplay91  Now ok ?

**Comment by ncplay91** [comment]
@oleokoong @sctnightcore I've downloaded the latest version of Openkore.. and the problem persists.. do you guys have any issue like this?

**Comment by fadreus** [comment]
Try using item's ID instead of item's name for items you want to sell and storage in items_control.txt.
I thought Re:Start server issue with items storage/sell/buy was solved.
#1006

**Comment by ncplay91** [comment]
@fadreus I have checked the link you provided, I dont think, they've got the solution yet?

**Comment by fadreus** [comment]
<details>
<summary>Hmm</summary>

> worked 2-3 days ago.. until yesterday

_Maybe if you put this & other details using issue template, dev team could assist this issue more quickly. Here I am, thinking it was issue from ages ago. But since you like to give detail 1 by 1, let's have it your way then._
</details>

According to my iRo logs, there is patch released less around 24 hours ago. Might be due that.

**Comment by ncplay91** [comment]
@fadreus so basically you can do autostorage and autosell perfectly?
Dude please be the man, the myth, and the legend.. by share your openkore (without config)..

**Comment by ncplay91** [comment]
Hey I have found out the error! It's basically my config settings that's messed up...
Thanks a lot for the support guys..!

**Comment by fadreus** [comment]
Close your issue when you done.
