### ISSUE TITLE
iRo Renewal - Homun AFK -> Stuck

### ISSUE THREAD

**Issue by shacalif** [OpenKore/openkore#1337]
**Summary:**

Hi champs, didn't find anything in the forum or internet related to this issue. Basically I'm trybing to AFK and my homun stuck after a while not moving or attacking. AFK works fine using official client btw..
I am using the latest openkore branch

Affected

 configuration(s)/ file(s):

My config.txt file looks like this,

_AutoAttack block:_

`
> attackAuto 0
attackAuto_party 0
attackAuto_onlyWhenSafe 0
attackAuto_followTarget 0
attackAuto_inLockOnly 1
attackAuto_notInTown 1
attackDistance 1
attackDistanceAuto 0
attackMaxDistance 1
attackMaxRouteDistance 100
attackMaxRouteTime 4
attackMinPlayerDistance 2
attackMinPortalDistance 4
attackUseWeapon 0
attackNoGiveup 0
attackCanSnipe 0
attackCheckLOS 0
attackLooters 0
attackChangeTarget 1
aggressiveAntiKS 0
`

_Take auto config:_

`

> itemsTakeAuto 0
itemsTakeAuto_party 0
itemsGatherAuto 0
itemsMaxWeight 89
itemsMaxWeight_sellOrStore 48
itemsMaxNum_sellOrStore 99
cartMaxWeight 9500
itemsTakeAuto_new 0
itemsTakeGreed 0
`

_lockMap:_

`

> lockMap
lockMap_x
lockMap_y
lockMap_randX
lockMap_randY
`

_To disallow route and movement:_  the idea is that my char look like and AFK player like others in the same map.

`

> route_escape_reachedNoPortal 1
route_escape_randomWalk 1
route_escape_shout
route_avoidWalls 0
route_randomWalk 0
route_randomWalk_inTown 0
route_randomWalk_maxRouteTime 75
route_maxWarpFee
route_maxNpcTries 5
route_teleport 0
route_teleport_minDistance 150
route_teleport_maxTries 5
route_teleport_notInMaps
route_step 0
route_tryToGuessMissingPortalByDistance 1
`

_This_ disable autoSit to avoid homun standby:_

`

> sitAuto_hp_lower 0
sitAuto_hp_upper 0
sitAuto_sp_lower 0
sitAuto_sp_upper 0
sitAuto_follow 0
sitAuto_over_50 0
sitAuto_idle 0
sitAuto_look
sitAuto_look_from_wall
sitTensionRelax 0
`

And my homunculus config:

`

> homunculus_attackAuto 2
homunculus_attackAuto_party 2
homunculus_attackAuto_notInTown 1
homunculus_attackAuto_onlyWhenSafe 0
homunculus_attackDistance 1
homunculus_attackMaxDistance 15
homunculus_attackMaxRouteTime 4
homunculus_attackCanSnipe 0
homunculus_attackCheckLOS 0
homunculus_attackNoGiveup 0
homunculus_attackChangeTarget 0
homunculus_followDistanceMax 15
homunculus_followDistanceMin 1
homunculus_route_step 15
homunculus_tankMode 0
homunculus_tankModeTarget
homunculus_runFromTarget 0
homunculus_runFromTarget_dist 6
homunculus_StandByAuto 0
homunculus_teleportAuto_hp 0
homunculus_teleportAuto_maxDmg 30000
homunculus_teleportAuto_maxDmgInLock 0
homunculus_teleportAuto_deadly 0
homunculus_teleportAuto_unstuck 0
homunculus_teleportAuto_dropTarget 0
homunculus_teleportAuto_dropTargetKS 0
homunculus_teleportAuto_totalDmg 0
homunculus_teleportAuto_totalDmgInLock 0
homunculus_teleportAuto_attackedWhenSitting 0
`

**Impact**: Homunculus Amistr stuck after a while not moving or attacking. Actual map is orcsdun02 in Chaos server.

**Expected Behavior**: Homunculus attack while I am AFK the same way as official client.

Actual Behavior: Not working as expected.

**Steps to Reproduce**: I'm using homunculus amistr which dont have any attack skills probably with other homuns problem will not happen. 

Attached is the console output with debug=1.

Thanks!!

[console_.txt](https://github.com/OpenKore/openkore/files/1425825/console_.txt)

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration

**Comment by fadreus** [comment]
Seems to me your homun moved too far and stuck, that's all.
Try some of these:
- Vaporize and Call Homunculus in macro each time homunculuse tried too long to move.
- Periodically vaporize & call with doCommand with timeout 300 or something
- Vaporize and call when homun HP > 80% or something when doing nothing.

Take advantage of bot, move around and kill instead of sitting at 1 spot.
Use this setting and kill any non-aggressives monster (metaling at higher level until 99 for example)

```

attackAuto 2
attackAuto_party 2
attackAuto_onlyWhenSafe 0
attackAuto_followTarget 1
attackAuto_inLockOnly 1
attackAuto_notInTown 0
attackDistance 1.5
attackDistanceAuto 1
attackMaxDistance 2.5
attackMaxRouteDistance 100
attackMaxRouteTime 4
attackMinPlayerDistance 2
attackMinPortalDistance 4
attackUseWeapon 0 <----- (Use this and you never have to attack)
attackNoGiveup 1 <-------(Prevent from running away while humun is killing too slow)
attackCanSnipe 0
attackCheckLOS 1
attackLooters 0
attackChangeTarget 1
aggressiveAntiKS 1


homunculus_attackAuto 2
homunculus_attackAuto_party 2
homunculus_attackAuto_notInTown 1
homunculus_attackAuto_onlyWhenSafe 0
homunculus_attackDistance 1.5
homunculus_attackMaxDistance 2.5
homunculus_attackMaxRouteTime 4
homunculus_attackCanSnipe 0
homunculus_attackCheckLOS 1
homunculus_attackNoGiveup 0
homunculus_attackChangeTarget 1
```

**Comment by shacalif** [comment]
Yes, I thought the same. At some point he moved very far and no chance to get back close by the amount of monsters nearby. I will try with your suggestions using some macros.

Regarding the modification of the configuration I understand that the bot was not designed for when the master is AFK, and this last is what I try to emulate. Many players leave their chars (with the official client) on the map and the homun is responsible for attack anything. The problem with this is that intimacy goes down and there is no auto feed.

Another thing that I notice is that the AI by default of the official client has a rescue option, that is, if the master is under attack the slave returns to give help. Is this feature or behavior available in openkore or not?, I did not see anything similar in the structure of the Slave.pm.

Thanks so much for the help!!

**Comment by fadreus** [comment]
> Regarding the modification of the configuration I understand that the bot was not designed for when the master is AFK

Not really. The thing is homun sometimes out of sight where it isn't too far enough to be respawn back to you. and while moving to kill monster and run back to you it stuck (position lag) like being attacked (screen/bot shows homun at x,y coordinate but it's 2 cell behind).

> AI by default of the official client has a rescue option, that is, if the master is under attack the slave returns to give help. Is this feature or behavior available in openkore or not?, I did not see anything similar in the structure of the Slave.pm.

Well, we can't have all the good things in the world, can we? 🤣

**Comment by shacalif** [comment]
Added the following changes to config:

**This one replace the rescue feature in some ways**
> doCommand
 conf attackUseWeapon 1 {
	hp < 50%
	timeout 120
	aggressives > 5
}

> doCommand
 conf attackUseWeapon 0 {
	timeout 120
	hp > 50%
}

##Move Homun nearby when HP drops##

> doCommand  homun move 40 44 {
	timeout 300
	inmap orcsdun02
	hp < 60%
}

#Vaporize homun after a while#

> doCommand  ss 244 {
	inmap orcsdun02
	timeout 300
}

#Call Homun back#

> doCommand ss 243 {
	timeout 5
	whenStatusInactive ESFT_POSTDELAY
	inmap orcsdun02
}

Also applied the changes to autoAttack block, the following make a lot of difference in the AI:

> attackAuto 2
attackAuto_party 2
attackUseWeapon 0
attackNoGiveup 1


With all these changes I think can survive more time..

Appreciate your help!!
