### ISSUE TITLE
Timeout ai_attack_giveup I think this it's not working

### ISSUE THREAD

**Issue by NewbieZz** [OpenKore/openkore#1338]
I tried shorten the time but i think it's not working. I shorten it because my bot will stand beside hill and try to attack the monster but it can't be reach. So it will always wait for 12 sec before dropping the target.

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration.

**Comment by NewbieZz** [comment]
Issue template? What's that?
I'm currently on iRO and the setting in timeout is

# Give up attacking a monster if it can't be reached within x seconds
ai_attack_giveup 2

**Comment by NewbieZz** [comment]
Yeap " Can't reach or damage target, dropping target "
This only trigger around 12 sec which is the default value in the timeout.txt even though i changed it to 6 or 2

**Comment by fadreus** [comment]
> Issue template? What's that?

# HAHAHAHAHAA...

## This is issue tamplete.
![image](https://user-images.githubusercontent.com/32188494/32154498-193aa846-bd6c-11e7-9ffd-bacfd29b0041.png)


You make it toooooooooooooooo fast, 2 seconds is too fast.
It's like you saw a chick across the street, try to walk to her and then 1 sec later ignore her.
You saw your grandma 3 meter infront of you, 2 seconds later you ignore her assuming your walking speed is 1m/s If you don't want to kill anything across the hill, set `attackCanSnipe 0`.

![image](https://user-images.githubusercontent.com/32188494/32154419-8c2a1a86-bd6b-11e7-85aa-938b9d36eef2.png)

Seriously bro, you ignore most of the text. Should have read more before starting an issue here.

**Comment by sctnightcore** [comment]
@fadreus  WTF . I LOVE YOU ! ♥

**Comment by NewbieZz** [comment]
Lol i set it 6 not 2 i just making an example that the setting isn't working.
And nop attackCanSnipe isn't working because it it can't be hit from top to bottom even i play it manually.
And you'r funny making those examples HAHAHAHAHAHA

**Comment by fadreus** [comment]
> Lol i set it 6 not 2 i just making an example that the setting isn't working.

Yeah, much easier to understand if you use the template.

> because my bot will stand beside hill and try to attack the monster but it can't be reach

Your bot do this stuff when `attackCanSnipe 1`

> And nop attackCanSnipe isn't working because it it can't be hit from top to bottom even i play it manually.

If `attackCanSnipe 0` isn't working and timeouts also not working, download new openkore maa. I at iRO use timeout dropping 5 sec working fine lor. Guess you mess up really bad one there.

Glad someone understand my joke. Some people take it too seriously 🤣🤣🤣🤣

**Comment by alisonrag** [comment]
any update? is it a bug?

**Comment by NewbieZz** [comment]
Hey, thanks for trying to help out, i found out where's the problem, I'm a hunter and i set the attackdistance = 1 and attackmaxdistance = 15 manually in config, the problem is fixed once i put attackdistanceauto = 1. Thanks all~
