### ISSUE TITLE
Visual Mode iRo Restart 

### ISSUE THREAD

**Issue by ShadowCold** [OpenKore/openkore#1339]
# ------------------ Bug Report Template ------------------
###### Summary: 
Good afternoon,

I'm trying to run a slave bot in Visual Mode but every time I start it the game just times out. I also get the MSG in the console "Timeout on Map Server, waiting actions for the Ragnarok Online Client" I'm also running the game and Openkore in admin mode with no luck.

My config has 
XKore 1

Regards

**Comment by sctnightcore** [comment]
xkore 0,2,3 work ! for iro restart

**Comment by ShadowCold** [comment]
@sctnightcore 
I'm not sure what that meas.. Do I just change it to Xkore 2?

**Comment by fadreus** [comment]
It means, xKore 1 is not working. Simple as that.
If you drive in highway, the lane sign show only motorcycle allowed. What does that mean?
It mean cars, bus, lorry, trailer, bicycle, aeroplane, jet fighter, helicopter & submarine are not allowed.

The issue 1227 is referenced for you to check.
In other word, your issues already exist but you didn't check before starting a new issues.

![image](https://user-images.githubusercontent.com/32188494/32172477-bcfaa3c4-bdb6-11e7-8934-917646811292.png)

**Comment by sctnightcore** [comment]
xkore 1 dont work for iRO ! @shadowclod

**Comment by ShadowCold** [comment]
Thank you for that, I'm new to github and still trying to work out how it all works. Sorry to west your time.

Regards

**Comment by alisonrag** [comment]
use #1227
