### ISSUE TITLE
Bad arg length for Socket::unpack_sockaddr_in, length is 4096, should be 16

### ISSUE THREAD

**Issue by NandoPrates** [OpenKore/openkore#1340]
on ubuntu 17.10
```
Connecting to Account Server...
Connecting (128.241.92.133:6800)... connected
---------- Account Info ----------

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Odin                  3961   128.241.92.138  4500
-----------------------------------------------------
Bad arg length for Socket::unpack_sockaddr_in, length is 4096, should be 16 at /usr/lib/x86_64-linux-gnu/perl/5.22/Socket.pm line 153.
Closing connection to Account Server
```

**Comment by NandoPrates** [comment]
is https://msdn.microsoft.com/en-us/commandline/wsl/install-win10?f=255&MSPPError=-2147217396
ubuntu on win 10 .-.

**Comment by asiphm** [comment]
Tested with the same environment WSL Ubuntu resulting the same :

---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  412    128.241.92.155  4500
1   Chaos                 1644   128.241.92.130  4500
-----------------------------------------------------
Closing connection to Account Server
Bad arg length for Socket::unpack_sockaddr_in, length is 4096, should be 16 at /usr/lib/x86_64-linux-gnu/perl/5.22/Socket.pm line 153.

**Comment by moneyisgod** [comment]
Maybe the problem is not with ubuntu, and with perl 5.22 ?!

**Comment by alisonrag** [comment]
there is a very long time since this issue started, but seems until today this issue is not fixed at WSL
https://github.com/microsoft/WSL/issues/134

**Comment by alisonrag** [comment]
Its not related to openkore
