### ISSUE TITLE
not attack

### ISSUE THREAD

**Issue by elviestan** [OpenKore/openkore#1341]
You are now attacking Monster Ambernite (3)
[ 92/100] You attack Monster Ambernite (3) (Dmg: 112) (Delay: 440ms)
[存在=unknown] Unknown #51758: *Sweat*
[存在=unknown] Unknown #51765: *Sweat*
[ 92/100] Monster Ambernite (3) attacks you (Dmg: 53) (Delay: 648ms)
Player *~Holy Bishop~* (0) is casting Increase AGI on you (Delay: 539ms)
You are now: Increase AGI (Duration: 140s)
Player *~Holy Bishop~* (0) uses Increase AGI on you (Lv: 5)
[ 74/100] Monster Ambernite (3) attacks you (Dmg: 50) (Delay: 648ms)
[ 57/100] Monster Ambernite (3) attacks you (Dmg: Miss!) (Delay: 648ms)
Player *~Holy Bishop~* (0) is casting Heal on you (Delay: 0ms)
Player *~Holy Bishop~* (0) uses Heal on you (Gained: 160 hp)
[dist=6.3] Monster Ambernite (1): *Sweat*
[100/100] Monster Ambernite (3) attacks you (Dmg: Miss!) (Delay: 648ms)
[100/100] Monster Ambernite (3) attacks you (Dmg: Miss!) (Delay: 648ms)
[100/100] Monster Ambernite (3) attacks you (Dmg: 48) (Delay: 648ms)
[ 83/100] Monster Ambernite (3) attacks you (Dmg: Miss!) (Delay: 648ms)
[ 84/100] Monster Ambernite (3) attacks you (Dmg: Miss!) (Delay: 648ms)
[ 84/100] Monster Ambernite (3) attacks you (Dmg: Miss!) (Delay: 648ms)
[ 84/100] Monster Ambernite (3) attacks you (Dmg: Miss!) (Delay: 648ms)
[ 84/100] Monster Ambernite (3) attacks you (Dmg: 49) (Delay: 648ms)
[ 67/100] Monster Ambernite (3) attacks you (Dmg: Miss!) (Delay: 648ms)
[ 67/100] Monster Ambernite (3) attacks you (Dmg: 40) (Delay: 648ms)

can some 1 tell me wat wrong on my openkore or setting pls , why my bot just attack 1 time then stuck there?im a archer

**Comment by Junezavr** [comment]
Check mon_control.txt
All 1 0 0
<attack>:
-1 means to leave the monster alone, even if it attacks you.
0 means to leave the monster alone, unless it attacks you.
1 means to always auto-attack this monster.
2 means always aggressive, auto-attack this monster when it appears, even if sitting.
3 means to attack the monster once (provoke) then leave it, useful for mobbing.

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration.

**Comment by windhamwong** [comment]
@elviestan This is not src issue. Please read the Wiki or Google when you encounter a problem for HOW TO USE THE PROGRAM PROPERLY.

**Comment by elviestan** [comment]
ready set in mon control 100 lasttime also same, try to set again also stuck

**Comment by Junezavr** [comment]
set mon_control.txt 
all 1 0 0
try agin

**Comment by fadreus** [comment]
@elviestan Download new, setup new, configure one by one using http://openkore.com as references.
Don't copy-paste your control folder from where ever you got it.

Help yourself. Do more reading. Visit forum for more example of settings.
Even if you ask, we give general answer because there is no faulty on openkore.
