### ISSUE TITLE
openkore cannot work now?

### ISSUE THREAD

**Issue by clarawong** [OpenKore/openkore#1348]
its keeping connecting to the server,when logged in ,then disconnected ,then try to relog,whats wrong?

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration

**Comment by clarawong** [comment]
yes?how to do ?
its on the new server re:start
please check the screenshot
![ro](https://user-images.githubusercontent.com/33313184/32318440-43160916-bff2-11e7-983f-995f56e69352.png)

**Comment by sctnightcore** [comment]
Download new openkore and Test Again . !!

**Comment by fadreus** [comment]
I'm reporting this account for botting GG.

**Comment by alisonrag** [comment]
please download the latest version and try again
