### ISSUE TITLE
Feature Request : Refine UI

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1349]
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details: 
```
https://github.com/rathena/rathena/pull/2494
https://github.com/rathena/rathena/pull/2499
https://github.com/rathena/rathena/tree/feature/refineui
```

**Comment by sctnightcore** [comment]
```
+ * 0a23 <packetLength>.W <ACHCount>.L <ACHPoint>.L
+ * 0a24 <ACHPoint>.L
+ * 0a25 <achievementID>.L
+ * 0a26 <result>.W <achievementID>.L
+ * 0aa2 <length>.W <index>.W <catalyst count>.B { <material>.W <chance>.B <price>.L }*
+ * 0aa1 <index>.W

+#if PACKETVER >= 20161012
 +	packet(0x0AA0,2);
 +	parseable_packet(0x0AA1,4,clif_parse_refineui_add,2);
 +	packet(0x0AA2,-1);
 +	parseable_packet(0x0AA3,7,clif_parse_refineui_refine,2,4,6);
 +	parseable_packet(0x0AA4,2,clif_parse_refineui_close,0);
 +#endif
 recv
 		'0AA0' => ['Opens_the_refine_UI', 'v', [qw(number)]],
 		'0AA2' => ['refineui_info', 'v', [qw(len item_id price)]],
		
 send 
		'0AA1' => ['Refineui_add', 'V v', [qw(item_id)]],
		'0AA3' => ['refineui_refine', 'V v', [qw()]],

```

**Comment by moneyisgod** [comment]
Can u please check if u sv is using 0980 and 098F?

**Comment by sctnightcore** [comment]
0980 098F ? what is it  ? @moneyisgod

**Comment by mjonrest** [comment]
can this work on rathena emu?

**Comment by sctnightcore** [comment]
@mjonrest  yep !

**Comment by mjonrest** [comment]
@sctnightcore if i want to install that features to my server. can you deal with it?

**Comment by sctnightcore** [comment]
https://github.com/rathena/rathena/tree/feature/refineui @mjonrest

**Comment by mjonrest** [comment]
but i cant open the window, can you help me? @sctnightcore

**Comment by alisonrag** [comment]
@mjonrest i
ts not impleme4nted yet, this issue is a feature request to implement this system in openkore

**Comment by moneyisgod** [comment]
Hi Sir. packet of cart customization

**Comment by sctnightcore** [comment]
LOL @moneyisgod 
@alisonrag  wait openkore update ♥

**Comment by c4c1n6kr3m1** [comment]
is it implemented? or kRO only?

**Comment by sctnightcore** [comment]
Now there's just kRO and privater server @c4c1n6kr3m1

**Comment by sctnightcore** [comment]
Test With marco Work ! 
Send Hex

**Comment by moneyisgod** [comment]
RefineUI in construction. 
I'll try to include some peoples to trigger this request. I'm very bad at perl OOP. ^^

**Comment by sctnightcore** [comment]
@moneyisgod  online discord bro

**Comment by cydh** [comment]
if OK support for basic 2016-10-12 (prefer 2017-09-20 xD) packets, I can help to init the Refine UI functions
(~2 months ago maybe, still unsupported and I too lazy to make changes even for walking)

**Comment by alisonrag** [comment]
@cydh 
openkore now support almost every severtype from 2015 to 2017

**Comment by cydh** [comment]
@alisonrag still fails on 2017-09-20
I thought I made some changes to fix char size block, but idk where. and decided to use 20161207, at least it's stable for me to stand in fornt Hollenghern and test Refine UI xD

**Comment by sctnightcore** [comment]
@cydh  cannot find recvpacket in client 201708+ hahahah 

I think add new packet in **sakexe_0** and **servertype0**
