### ISSUE TITLE
can't connect on the game openkore renewal ragnarok i think they change something on the tables again @allanon

### ISSUE THREAD

**Issue by jomarlorica** [OpenKore/openkore#1351]
@allanon can't connect on the game i think they change something on the tables again @allanon can you help us?

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration.

Download new openkore and test again. !

**Comment by sctnightcore** [comment]
#1350

**Comment by jomarlorica** [comment]
this maintenance change the renewal again. cant connect again @sctnightcore  @allanon  thanks for helping us. can you update the tables for the patch.pl thanks again in advance

**Comment by jomarlorica** [comment]
ill try to redownload again and check if its ok @sctnightcore  thanks but i think its not working. need new edit on the table or patch.pl

**Comment by jomarlorica** [comment]
owh now its working. thanks @sctnightcore

**Comment by fadreus** [comment]
Even monkey can learn.
This guy never learn.
Always need to start new issue after maintenance.
