### ISSUE TITLE
iro Chaos stuck at character server

### ISSUE THREAD

**Issue by icecreamkings** [OpenKore/openkore#1353]
Iro chaos still stuck at character server any help please?

**Comment by HayRoH** [comment]
I have the same problem :v

**Comment by blazasin** [comment]
Hi @allanon Openkore gets stuck while connecting to Map server / Account server after this latest server maintenance . Any update which should be made to Openkore files ? Help Please ....

**Comment by icecreamkings** [comment]
the latest file for iro chaos updated 7 hours ago but it's not working =(

**Comment by fadreus** [comment]
You guys seriously have eye problem.
Go download new one..

# READ THE ISSUE TEMPLATE AND USE IT

**Comment by fadreus** [comment]
# The fix was updated indeed 7 hours ago but it isn't on master branch.
# Master branch pulled request for fix 2 hours ago.
# Learn people. LEARN. Monkey can learn. Why can't you?

**Comment by blazasin** [comment]
@fadreus Didnot see the updated files , yeah its working now thanks !!
