### ISSUE TITLE
why not connected please help.. Nov 3, 2017

### ISSUE THREAD

**Issue by poooch707** [OpenKore/openkore#1354]
![screenshot 2017-11-03 19 38 18](https://user-images.githubusercontent.com/33144070/32372325-35a4fd8a-c049-11e7-97e1-c087230b3568.png)
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/32372563-616af992-c0d0-11e7-9255-423cd05a2056.png)

**Comment by Youtouchmytralala** [comment]
Who the hell read this? Most ppl just post somethink like "OMG IT DOESNT WORK. MAKE ME A WORKING BOT AGAIN!".

**Comment by poooch707** [comment]
okey, Thank you soo much...
