### ISSUE TITLE
iRo Chaos: Yellow Butterfly Wing not work

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#1356]
Server: iRo Chaos Renewal
version: 02.11.2017

Report:

![1349](https://user-images.githubusercontent.com/20753532/32390850-10e71f9e-c0e1-11e7-86d1-518d41655dc5.jpg)

**Comment by Glikadin** [comment]
Part oh this macros:
...
        do ai manual
	do is Yellow Butterfly Wing
	pause 5
	do talk resp 3
	pause 20
...

**Comment by alisonrag** [comment]
talk resp and the index of city

**Comment by Glikadin** [comment]
![1455](https://user-images.githubusercontent.com/20753532/32401564-253516a4-c122-11e7-96f9-837d34380735.jpg)

**Comment by fadreus** [comment]
It's same as creating potion; no selective option afaik.
Required to send packet as mentioned in that issue.

But since this thinggy not a big deal, why not just log in and use it manually instead 😁.
Or use it with xKore 1,2,3.

**Comment by Glikadin** [comment]
Oh. Thx , i forgot about the command "send ". This solution.

**Comment by fadreus** [comment]
Similar Issues #1357
