### ISSUE TITLE
Cant use Kafra Cards Iro Renewal

### ISSUE THREAD

**Issue by 43521** [OpenKore/openkore#1357]
###### Steps to Reproduce: Use a Kafra Card you will get a npc dialog with an npc named (Unknown #0)  any commands after come back with  an error in function you are not talking to an npc.
[](url)https://imgur.com/a/39XSa

**Comment by fadreus** [comment]
Need to use command `send` afaik.

![image](https://user-images.githubusercontent.com/32188494/32408681-5e02c12e-c1d7-11e7-9e64-819da2e587d8.png)

**Comment by 43521** [comment]
I've been using "talk resp #" for 4 years it stopped working with the anti cheat update on iro 2 months ago. Prior to that when you only had 1 storage I did use the send command and the default packet for closing a chat which never changed. Since there are multiple storage options with the kafra card it no longer works as the packet changes every time you use a card
