### ISSUE TITLE
MerchDB Webpage

### ISSUE THREAD

**Issue by RorroCarrasco** [OpenKore/openkore#1361]
Hello Comunity.

I want to ask if someone have tested some of the free source plugins of player database and merch database webpage. Similar as ropd.info and ragi.al

I have a little experience in webpages but i want to learn so i hired a cheap webhosting with cPanel, phpadmin, and Mysql for the DB. Already I run those webpages but they have several errors.
My intention is to oppen a merch page for a private server wich doesnt exist @autotrade but there is a lot of merchs vending (obviusly i can bot there hahaha)

If someone can share the source code to make this proyect i will apreciate this.
my e-mail: black.shale01@gmail.com

Already tested the plugin and the database and works fine.

**Comment by sctnightcore** [comment]
https://github.com/titu1994/Ragial-Searcher
https://github.com/Naozumi2k/openkore_ragial
https://github.com/ragnastats
XD

**Comment by alisonrag** [comment]
http://www.ragcomercio.com.br

**Comment by RorroCarrasco** [comment]
Thanks very much for all help!!
Yes, i undertand, but it is for a private proyect, non comertial.
Already tested the Ragial-Searcher but it is the page that i should see?

![sin titulo](https://user-images.githubusercontent.com/33394956/32416021-59027292-c221-11e7-8cc9-917c818d9518.jpg)

**Comment by RorroCarrasco** [comment]
@alisonrag Yes!! I tried it but it didnt worked :( too much several errors, on the index page and connections to the database (I put all tables manually but it was a waste of time) finally it doesnt worked :(

But not the plugin, openkore put all the information in the database, nothing bad ;) great job there
