### ISSUE TITLE
Bus Server Issue

### ISSUE THREAD

**Issue by oleokoong** [OpenKore/openkore#1362]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 
When i use openkore download from GitHuB connecting to my raspberry pi hosting Bus Server is no issue. 
But i use other method for multi exe  http://forums.openkore.com/viewtopic.php?f=6&t=13
Which is using shortcut to run start.exe , openkore cant connect to raspberry pi Bus server , and will automatic run bus server on the first openkore running and the rest able to connect to the local bus server not the raspberry pi.

###### Affected configuration(s)/ file(s):
sys.txt

###### Impact:
No Bus Server will DIE.

**Comment by Glikadin** [comment]
How i use the Bus server
**1. Add busCommands plugin to \plugins
2. Add settings to control\sys.txt**
```

bus 1

bus_server_host 127.0.0.0

bus_server_port 1350

bus_userAgent 1

```
**3. Make bath file for start bus server
_startBus.bat_**
```
@echo off

cd C:\openkore\

start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.0 --port=1350 --nodaemon

exit
```
If you did everything right, you will see a message about connecting a new client at startup Openkore:
![bus](https://user-images.githubusercontent.com/20753532/32430694-64b61510-c2e1-11e7-8cf7-504cac8241fd.jpg)

C:\openkore\ this is the path to any of your copies openkore

**Comment by oleokoong** [comment]
@Glikadin 
Thanks for sharing
look at your is different with my ...
Client identified as 1:1 , 1:2 because  you set bus_userAgent 1 ?
----------------------------------------------------------------------------------------------
my current setting is 
bus 1
bus_server_host
bus_server_port
bus_userAgent
work on 1 machine..
work very well at the moment...but issue is i already reach the limit for window OS, bus server run on Window limited to 60 connection.
----------------------------------------------------------------------------------------------
for 2 machine or more..
Raspberry pi = bus server, because on linux there is no limit connection..
but my issue happen when use multi exe folder tree..
if i duplicate whole openkore folder will be alright, but hard to maintaine
----------------------------------------------------------------------------------------------
![untitled](https://user-images.githubusercontent.com/8089017/32431418-84b17440-c327-11e7-941d-e27536c73b55.png)

ps: dont ask me why run so much, when i do something, my style is push to the limit and over

**Comment by Glikadin** [comment]
**First openkore group:**
 ...control\sys.txt :
```
bus 1
bus_server_host 127.0.0.1 
bus_server_port 1351
bus_userAgent 1
```
startBus1.bat :
```
@echo off
cd C:\openkore\
start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.1 --port=1351 --nodaemon
exit
```
**Second openkore group:**
 ...control\sys.txt :
```
bus 1
bus_server_host 127.0.0.2
bus_server_port 1352
bus_userAgent 2
```
startBus3.bat :
```
@echo off
cd C:\openkore\
start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.1 --port=1351 --nodaemon
exit
```
**Third openkore group:**
 ...control\sys.txt :
```
bus 1
bus_server_host 127.0.0.3 
bus_server_port 1353
bus_userAgent 3
```
startBus2.bat :
```
@echo off
cd C:\openkore\
start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.3 --port=1353 --nodaemon
exit
```

And so on...
![bus](https://user-images.githubusercontent.com/20753532/32432224-c6630cb8-c2e7-11e7-8687-8358107a041a.jpg)

**Comment by oleokoong** [comment]
@Glikadin 
i did like this 
`@echo off

cd C:\openkore\

start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.1 --port=45827 --nodaemon

start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.1 --port=45828 --nodaemon

start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.1 --port=45829 --nodaemon
`
and its work..i let the window stay with remove exit

**Comment by Zelecktor** [comment]
As i know on the command line, port is used first than bind. For me if i write it also on my raspberry pi bus server doesnt run.

start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --port=45829 --bind=127.0.0.1

For UNIX
Enter on directory of bus server /src/Bus/
perl ./bus-server.pl --port=45829 --bind=127.0.0.1

**Comment by roytanz** [comment]
> ## **First openkore group:**
> **...control\sys.txt :**
> 
> ```
> bus 1
> bus_server_host 127.0.0.1 
> bus_server_port 1351
> bus_userAgent 1
> ```
> 
> **startBus1.bat :**
> 
> ```
> @echo off
> cd C:\openkore\
> start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.1 --port=1351 --nodaemon
> exit
> ```
> 
> ## **Second openkore group:**
> **...control\sys.txt :**
> 
> ```
> bus 1
> bus_server_host 127.0.0.2
> bus_server_port 1352
> bus_userAgent 2
> ```
> 
> **startBus2.bat :**
> 
> ```
> @echo off
> cd C:\openkore\
> start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.2 --port=1352 --nodaemon
> exit
> ```
> 
> ## **Third openkore group:**
> **...control\sys.txt :**
> 
> ```
> bus 1
> bus_server_host 127.0.0.3 
> bus_server_port 1353
> bus_userAgent 3
> ```
> 
> **startBus3.bat :**
> 
> ```
> @echo off
> cd C:\openkore\
> start /low C:\openkore\start.exe ! src/Bus/bus-server.pl --bind=127.0.0.3 --port=1353 --nodaemon
> exit
> ```
> 
> And so on... ![bus](https://user-images.githubusercontent.com/20753532/32432224-c6630cb8-c2e7-11e7-8687-8358107a041a.jpg)

Hi @Glikadin how can i create  3 different group openkore like u?i follow all your step but i fail
do u have discord or messager?can u teach me
