### ISSUE TITLE
error.. what is that?

### ISSUE THREAD

**Issue by greatjr** [OpenKore/openkore#1363]
![1](https://user-images.githubusercontent.com/28333670/32437708-c2e8f6a0-c31a-11e7-9c48-015ce3e7d5dd.png)

whats the problem it is?

**Comment by sctnightcore** [comment]
**Please use the issue template, please post infornations about the server and your configuration.**

recvpackets is wrong .

**Comment by greatjr** [comment]
idk what must i do..
my server is idRO

1 question more..
how can search the server.txt
where can i download the tools for search server

**Comment by sctnightcore** [comment]
There are no developers now idRO. !
