### ISSUE TITLE
Autostorage and Autosell

### ISSUE THREAD

**Issue by ncplay91** [OpenKore/openkore#1365]
Hi,

I'm having problem with auto storage/sell at Re:start server..
It seems like Openkore can't figure out which items to be sold and which items to be stored in the storage despite what I believe with the correct configurations.

The following is my config:

storageAuto 1
storageAuto_npc comodo 195 150
storageAuto_distance 1
storageAuto_npc_type 1
storageAuto_npc_steps c c r1 n
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 0

sellAuto 1
sellAuto_npc comodo 225 164
sellAuto_standpoint
sellAuto_distance 2
sellAuto_npc_steps

and here's the items_control.txt

all 0 0 1 (sell everything)
Hydra Card 0 1 0 (except this one)..

What happened was Openkore sold everything, including the cards.. T.T

What is wrong with my Openkore?

**Comment by Glikadin** [comment]
sellAuto_npc_steps s e
storageAuto_npc_steps c r1 n

**Comment by sctnightcore** [comment]
# Please use the issue template, please post infornations about the server and your configuration.

**Comment by fadreus** [comment]
@ncplay91 
![image](https://user-images.githubusercontent.com/32188494/32497235-db99138c-c406-11e7-8501-3ce9472a20be.png)
![image](https://user-images.githubusercontent.com/32188494/32497294-0c333c5c-c407-11e7-9689-9c2bbaf50cb8.png)
![image](https://user-images.githubusercontent.com/32188494/32497413-6eee2672-c407-11e7-85af-8721653b7229.png)
![image](https://user-images.githubusercontent.com/32188494/32497470-9f0c8830-c407-11e7-96e8-4c514e3f0eb1.png)
![image](https://user-images.githubusercontent.com/32188494/32497521-c3eb23aa-c407-11e7-8ae2-82ee01a4a426.png)
![image](https://user-images.githubusercontent.com/32188494/32497631-210bd2e6-c408-11e7-93ed-376bb544836e.png)
![image](https://user-images.githubusercontent.com/32188494/32497689-51147ef2-c408-11e7-8562-a29bc3db9d7f.png)

**Comment by ncplay91** [comment]
Since I've made this mistake... I don't know what to do to undo my mistakes now..
