### ISSUE TITLE
Difference and Advantages of Xkore1 2 3

### ISSUE THREAD

**Issue by Bombahee** [OpenKore/openkore#1367]
Delete or close if this is not the right place to ask...

What is the difference and advantages of Xkores 1 2 3?
please enlighten those who are not so techie like us with the information's and tutorials or links.
currently i'm using or most of us are using xkores 0 and 1, but 2 and 3 is more complicated to run.

sorry for the newbie question...

thanks in advance.

**Comment by alisonrag** [comment]
http://openkore.com/index.php/XKore

**Comment by alisonrag** [comment]
xKore 0: 
Plain old Kore.	

xKore 1:
Sniffer: Kore hooks onto client's connection with the server using NetRedirect library.	

xKore 2: 
Server: Plain old Kore additionally acts as a custom server for the game client.

xKore 3: 
Proxy: Kore acts as a proxy between the client and the serve

**Comment by Bombahee** [comment]
thank you very much sir
