### ISSUE TITLE
Stuck on Linux

### ISSUE THREAD

**Issue by Zelecktor** [OpenKore/openkore#1369]
many bots on linux says a message like "cannot move to location A to location B" and fixed with reloging via quit and re-open.
I used all my methods to force moving and got disconect with this message

Only 47 bytes in the buffer, when 09DD's packet length is supposed to be 41988056 (wrong recvpackets?)
47 bytes   Nov 8 16:19:48 2017
 0>  DD 09 52 00 00 07 88 01    00 1C 3C 03 00 4B 00 00
16>  00 00 00 00 00 00 00 0A    00 08 00 00 00 00 00 69 
32>  04 11 02 00 00 03 00 00    00 00 00 01 00 EF 04

**Comment by sctnightcore** [comment]
private server ?

**Comment by oleokoong** [comment]
reload portals

**Comment by Zelecktor** [comment]
nope, iRO Re:Start

**Comment by hfingler** [comment]
I have the same issue. It can't calculate even a route to one tile away.
I have to keep quit/reopening until it works. I think I'm having more success when I log out and the bot is sitting.

**Comment by fadreus** [comment]
Not sure if it the same as iRo Renewal, similar issue I had solved by either one of these:

- reload portals & relog (reload both portals & LOS)
- ai clear <command>
- north / south / west / east <command>

**Comment by hfingler** [comment]
@fadreus Doesn't work, just had an instance stuck after about 8 restarts trying everything there and still didn't work.

**Comment by alisonrag** [comment]
Route system updated at #2871 
Ubuntu support updated at #2402
This kind of issue was never seen again
