### ISSUE TITLE
xkore 1&3 DC after 5-10 min running

### ISSUE THREAD

**Issue by puakayj** [OpenKore/openkore#1377]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
use #1374

**Comment by alisonrag** [comment]
miss click =p

**Comment by puakayj** [comment]
heh :p im gonna try to update all. wish me luck

**Comment by alisonrag** [comment]
download the latest version from here:
https://github.com/OpenKore/openkore/archive/master.zip

apply my patch:
#1374 

more xKore:
http://openkore.com/index.php/XKore

obs:
XKore is less tolerant to incorrect server settings. If everything works without XKore and there is some problem with XKore, it may still be a problem with server settings like serverType, charBlockSize etc.

**Comment by alisonrag** [comment]
any update?

**Comment by puakayj** [comment]
ok done , now everything running good after apply  #1374 thank alot.

**Comment by alisonrag** [comment]
Thanks <3
