### ISSUE TITLE
Openkore>Control>Config BEST FLYWİNG OPTİONS for blacksmith

### ISSUE THREAD

**Issue by Gulxx** [OpenKore/openkore#1378]
my flywing options please write best flywing options for BS 70 level İzlude Dungeon Marc Swordfish

teleportAuto_hp 500
teleportAuto_sp 0
teleportAuto_idle 0
teleportAuto_portal 0
teleportAuto_search 0
teleportAuto_minAggressives 7
teleportAuto_minAggressivesInLock 5
teleportAuto_onlyWhenSafe 0
teleportAuto_maxDmg 1000
teleportAuto_maxDmgInLock 0
teleportAuto_deadly 0
teleportAuto_useSkill 0
teleportAuto_useChatCommand
teleportAuto_allPlayers 0
teleportAuto_notPlayers
teleportAuto_atkCount 0
teleportAuto_atkMiss 0
teleportAuto_unstuck 0
teleportAuto_lostTarget 0
teleportAuto_dropTarget 0
teleportAuto_dropTargetKS 0
teleportAuto_attackedWhenSitting 1
teleportAuto_totalDmg 0
teleportAuto_totalDmgInLock 0
teleportAuto_equip_leftAccessory
teleportAuto_equip_rightAccessory
teleportAuto_lostHomunculus
teleportAuto_useItemForRespawn
teleportAuto_item1 fly wing
teleportAuto_item2 novice fly wing

**Comment by fadreus** [comment]
This section for reporting bugs in openkore.
Not for everyone personal issue.
Use forum instead.

**Comment by sctnightcore** [comment]
# Please use the issue template, please post infornations about the server and your configuration

**Comment by alisonrag** [comment]
i'm sorry bro, but this session is to report issue in openkore and not to ask for suport in configuration.
use:
http://forums.openkore.com
