### ISSUE TITLE
iro classic not connecting

### ISSUE THREAD

**Issue by creedsin** [OpenKore/openkore#1379]
timeout on map and account server.

old version working fine version ctime:2017_11_08 but not working with latest verison

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration
download new openkore - https://github.com/OpenKore/openkore/archive/master.zip

**Comment by creedsin** [comment]
![image](https://user-images.githubusercontent.com/17100479/32688846-9195d4d2-c6fe-11e7-9ac0-4c576cd0167a.png)
[servers.txt](https://github.com/OpenKore/openkore/files/1463681/servers.txt)
[config.txt](https://github.com/OpenKore/openkore/files/1463682/config.txt)

PFA

**Comment by sctnightcore** [comment]
download new openkore @creedsin  and test again

**Comment by fadreus** [comment]
Yo bro @creedsin ..
You forgot to remove your other name there (Ch**d*).
Want someone here reporting you with concrete evidence or what?

Sometimes I do tempted to do report; teaching people like you some lessons.
Since you guys never bother to read.

**Comment by alisonrag** [comment]
delete:
openkore\tables\iRO\sync.txt
and
openkore\tables\iRO\shuffle.txt

**Comment by creedsin** [comment]
@fadreus removed screenshot

**Comment by creedsin** [comment]
@alisonrag thanks for your help issue fixed
