### ISSUE TITLE
Stuck at Izlude town.

### ISSUE THREAD

**Issue by japerwaulk** [OpenKore/openkore#138]
I already downloaded the updated files here but the bot is unable to move away from the center like there's an invisible wall.

When asked to go to Byalaan it will walk 144, 144 and in out of the tool shop.
When using wxstart to manually walk its only able to walk around the center isle in Izlude town like theres an invisible wall. I cant even ask it to move to the kafra to teleport to other towns.

**Comment by cydh** [comment]
Server?
It must be related with 'new' izlude

**Comment by japerwaulk** [comment]
iRO loki

**Comment by c4c1n6kr3m1** [comment]
Iro loki use old izlude ?

**Comment by itsrachelfish** [comment]
Loki is the name for iRO's classic server, so yes they'd be using the old izlude map. @japerwaulk when you downloaded the updated version of openkore from github, did you re-use any of your old files?

This is *supposed* to be handled by the resnametable file, but it looks like we might need to add a resnametable for classic? https://github.com/OpenKore/openkore/tree/master/tables/iRO/Classic

**Comment by japerwaulk** [comment]
@itsrachelfish I'm a RO returnee so my only openkore files are the ones I recently downloaded here.

**Comment by c4c1n6kr3m1** [comment]
look inside folder fields\
1. make sure your izlude.fld is old izlude map,
   new izlude map has straight road to prontera fild 08 ( to the left ) , long time ago new izlude map is inside folder fields\EP14.1\
2. remove izlude.dist 
3. look inside folder map\
   remove izlude.xpm

**Comment by ksands99** [comment]
Is there any update on this? I had attempted to look through this, but the bot is still failing to path through Izlude correctly.

iRO server

**Comment by jeraffas** [comment]
hello, sorry if there's been a fix for this but i've recently tried to bot byalan dungeon and the bot seems to not recognize izlude, same problem as op pretty much, anyone have any suggestions?
