### ISSUE TITLE
The server has denied your connection.

### ISSUE THREAD

**Issue by fikriaulia13** [OpenKore/openkore#1381]
excuse me sir..
i want to test bot at private server Lets Play Ragnarok
but when i setting in error
The server has denied your connection

[LetsPlayRO]
ip 156.67.217.152
port 6900
version 55
master_version 0
serverType kRO_RagexeRE_2015_11_04a
serverEncoding western
charBlockSize 145
addTableFolders iRO

is there any mistake ? maybe in my recvpacket.txt ? because i cant get that file using any tools :(
thanks before

@sctnightcore 
1. how do i know the packet key
2. client date is Nov 2,2015
thx for reply sir

**Comment by sctnightcore** [comment]
get from peek ! 
herc.ws/board/topic/4912-peek-successor-to-yommys-packet-analyzer/

**Comment by alisonrag** [comment]
@sctnightcore 
we need to implement 082D in kRO servertype
![image](https://user-images.githubusercontent.com/10372732/32691560-98f68342-c6f0-11e7-8277-301c678bfcbd.png)

**Comment by alisonrag** [comment]
```
[Lets Play Ragnarok]
ip 156.67.217.152
port 6900
master_version 0
version 55
serverType iRO_Restart
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders translated;translated/kRO_english;kRO
charBlockSize 124
recvpackets recvpackets.txt
pinCode 0
private 1
gameGuard 0
```

[recvpackets.txt](https://github.com/OpenKore/openkore/files/1463916/recvpackets.txt)

stuck in char-server because of unknow packet

**Comment by sctnightcore** [comment]
charBlockSize 147
serverType kRO_RagexeRE_2015_11_04a
@alisonrag  
LOL

**Comment by fikriaulia13** [comment]
@sctnightcore @alisonrag thank you very much sir for helping me, wait, ill try it

**Comment by fikriaulia13** [comment]
@sctnightcore i try ur advice sir

[LetsPlayRO]
ip 156.67.217.152
port 6900
version 55
master_version 1
serverType kRO_RagexeRE_2015_11_04a
serverEncoding western
addTableFolders translated;translated/kRO_english;kRO
charBlockSize 147
recvpackets recvpackets.txt
private 1
sendCryptKeys  0x4C17382A,0x7ED174C9,0x29961E4F

but its show packet tokenizer
![capture](https://user-images.githubusercontent.com/26967975/32691912-9d1a22fc-c741-11e7-8b20-868cbec234f3.PNG)

**Comment by fikriaulia13** [comment]
@sctnightcore @alisonrag this is what i get from WPE for ip port version master_version
![wpe](https://user-images.githubusercontent.com/26967975/32692026-909a98a2-c743-11e7-8171-3980913ecec0.PNG)

**Comment by sctnightcore** [comment]
recvpacket : https://github.com/OpenKore/openkore/tree/master/tables/kRO/RagexeRE_2015_11_04a_b

Put away with tables.txt

**Comment by fikriaulia13** [comment]
@sctnightcore 
where should i place that recvpacket ?

i've try to place it in tables folder but same problem

**Comment by fikriaulia13** [comment]
@sctnightcore why its recvpacket : https://github.com/OpenKore/openkore/blob/master/tables/kRO/RagexeRE_2015_11_04a_b/recvpackets.txt
sir ?

i'm using kRO_RagexeRE_2015_11_04a isn't it ?
sorry if to much asking im still new about this

**Comment by fikriaulia13** [comment]
@sctnightcore i try to replace recvpacket.txt at openkore-master\openkore-master\tables\kRO with that recvpacket and the packet toke
![capture](https://user-images.githubusercontent.com/26967975/32692364-61fe2166-c749-11e7-8e82-5af4f2994671.PNG)
nizer has gone but it back to the first problem sir

**Comment by fikriaulia13** [comment]
where should i place the recvpackets.txt that u give me in github sir ?
i try to place it to tables folder
but its still "Packet Tokenizer: Unknown switch: 082D"
plss help me :(

2017-11-12 0:53 GMT+07:00 sctnightcore <notifications@github.com>:

**Comment by fikriaulia13** [comment]
@sctnightcore when i try to replace the recvpacket.txt at tables/kro folder it turn like this now sir
![capture](https://user-images.githubusercontent.com/26967975/32692846-0b87cf9a-c752-11e7-8324-e1469f98a550.PNG)

**Comment by alisonrag** [comment]
for now:

```
[International - iRO: Lets Play Ragnarok]
ip 156.67.217.152
port 6900
master_version 0
version 55
serverType iRO_Restart
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders iRO/Restart;iRO
charBlockSize 145
recvpackets recvpackets.txt
pauseCharLogin 1
pinCode 0
private 1
gameGuard 0
sendCryptKeys 0x4C17382A, 0x7ED174C9, 0x29961E4F
```
paste in openkore\tables
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1464206/recvpackets.txt)

**Comment by alisonrag** [comment]
please post feedback so i can close this issue. 
**## always remember that section is to report bugs, issue and etc, to personal support use:**
http://forums.openkore.com

**Comment by fikriaulia13** [comment]
@alisonrag wow thank you sir it works, but im still thinking about ur argument "Working but you will need to add portals and add fields"
it works right now, but is there any map or field i should add ?
because i've read that how to add portal and fld creation i still dont know how to do it

**Comment by alisonrag** [comment]
if your server does'nt use custom map you dont have to care about this.

**Comment by fikriaulia13** [comment]
@alisonrag owhh.. ok sir thank you so much, maybe i will ask again if i want know about that

**Comment by fikriaulia13** [comment]
excuse me sir, can u help me again ? i get error server has denied your
connection at the private server i want to test, i already post it at github
https://github.com/OpenKore/openkore/issues/1647 thx sir

2017-11-12 8:09 GMT+07:00 Alison Serafim <notifications@github.com>:

**Comment by fikriaulia13** [comment]
@alisonrag excuse me sir, can u help me again ? i get error server has denied your
connection at the private server i want to test, i already post it at github
#1648 thx sir
