### ISSUE TITLE
mercdb2 plugin not working

### ISSUE THREAD

**Issue by RorroCarrasco** [OpenKore/openkore#1382]
Doing my proyect of the merch page database some parts of the plugins works as put information on the shopOwnerID database (its the only part that works) but all the rest of all information is missing.

The bot doesnt print the information on the shopcont database. (and it is the most important)

Im using the mercdb2 and all the files on that folder.
Already i have installed all the requeriments to run the pluging (as DBI and many other stuff, and conecting to my DB) the plugin runs without problems, but it is not printing the info on the DB.

Someone could help me in fix this or upload an update plugin please.
Thanks in advance
Mail: black.shale01@gmail.com

**Comment by sctnightcore** [comment]
# Please use the issue template, please post infornations about the server and your configuration.

**Comment by alisonrag** [comment]
This plugin is outdated, openkore changed the structure of many variables

I will post a plugin that i have

**Comment by alisonrag** [comment]
plugin:
https://pastebin.com/FVPpNyzZ

sql:
https://pastebin.com/NtxxNGsq

**Comment by RorroCarrasco** [comment]
@alisonrag
Thanks you very much for you help!!! Yeah it worked perfectly!!!!
1000 thanks <3

**Comment by alisonrag** [comment]
you are welcome!

if u want u can contactme in discord:
alisonrag#6961

**Comment by Kuzyashin** [comment]
@alisonrag Hi! Pastebin link for plugin outdated. Can u update it ?

**Comment by alisonrag** [comment]
@Kuzyashin 
using the same mysql database:
https://pastebin.com/NtxxNGsq

Plugin:
https://pastebin.com/ztgJ5Pnj

if u want u can contact me in discord:
alisonrag#6961
