### ISSUE TITLE
Can someone make server info for CityRO? thanks

### ISSUE THREAD

**Issue by nate111590** [OpenKore/openkore#1385]
thanks!

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration.

**Comment by fadreus** [comment]
> thanks!

You're welcome.

**Comment by sctnightcore** [comment]
@fadreus  CityRO what is it ?  idk XDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by fadreus** [comment]
@sctnightcore Perhaps me meant [this](http://city.ro-game.net/)?

**Comment by sctnightcore** [comment]
@fadreus  I'm lazy for download it. XD wait bro 
```
Request information
Client date? 
```

**Comment by alisonrag** [comment]
same site:
http://city.ro-game.net/
and
http://156.67.217.152/cp/index.php

lol no one is caring about the exclusivity of ragnarok server

**Comment by nate111590** [comment]
sorry for bothering you guys. i never played ragnarok for years and im really noob on openkore.  just need to find out this server configuration so i can run it on openkore.

**Comment by sctnightcore** [comment]
http://openkore.com/index.php/Main_Page
![ssssssssssssssssss](https://user-images.githubusercontent.com/23263315/32741741-dd30aa98-c8d9-11e7-8f61-f30133902003.PNG)

@nate111590 
**If you do not try it. No one helped you.**

**Comment by nate111590** [comment]
well i tried it already, used wpe but wont detect my client. downloaded wireshark but the guide is different. i know how to config the bot. my problem is getting the server details.

**Comment by fadreus** [comment]
Tried with grftool yet?

**Comment by nate111590** [comment]
i tried it, i got some info. but i cant make it to run. im having
this Packet Parser: Unknown switch: 020D error. somethings missing?

**Comment by fadreus** [comment]
> this Packet Parser: Unknown switch: 020D error. somethings missing?

![image](https://user-images.githubusercontent.com/32188494/32766701-0d813110-c94b-11e7-9814-c27f1da07931.png)

**Comment by nate111590** [comment]
​well i got this, and i cant see any working links for JCV's Tool

**Comment by sctnightcore** [comment]
Client date ? @nate111590

**Comment by nate111590** [comment]
​this 1?

**Comment by sctnightcore** [comment]
@nate111590  1 ? 
WTF ? 
http://openkore.com/index.php/ServerType

**Comment by nate111590** [comment]
where to locate that step 5? im really confused

**Comment by sctnightcore** [comment]
What is step 5? @nate111590

**Comment by nate111590** [comment]
u asked me about the client date right. im trying to find out i just
followed the instruction in thr link given. but cannot locate whTs being
told in step 5

**Comment by fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/32770610-3ab636ca-c95b-11e7-8d1a-2d26858e5c36.png)
![image](https://user-images.githubusercontent.com/32188494/32770578-1f0d7230-c95b-11e7-89b5-c5daf053c94a.png)
![image](https://user-images.githubusercontent.com/32188494/32770581-21aa81c2-c95b-11e7-8e1e-9de681003419.png)
![image](https://user-images.githubusercontent.com/32188494/32770731-96a1ad52-c95b-11e7-8b25-79defd244e6e.png)

**Comment by sctnightcore** [comment]
omg ! download new openkore on github !

**Comment by nate111590** [comment]
haha, sorry for being such an headache. i made it running but everytime an
unknown item appeared it disconnects. what to do? :D

**Comment by nate111590** [comment]
like this.
​

**Comment by alisonrag** [comment]
this is not a official issue, to get help about connect in private server use:
http://forums.openkore.com/viewforum.php?f=9&sid=dd9cb3dc8b763f7423af9da1d78fe0b1

read the manual:
http://openkore.com/index.php/Main_Page
![image](https://user-images.githubusercontent.com/32188494/32766701-0d813110-c94b-11e7-9814-c27f1da07931.png)
