### ISSUE TITLE
Compilation failed in require at plugins/eventMacro/eventMacro/Condition.pm

### ISSUE THREAD

**Issue by NandoPrates** [OpenKore/openkore#1388]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details: scons: done building targets.
make: Leaving directory '/home/nando/openkore'
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

Carregando plugins selecionados...
Carregando plugin plugins/map/map.pl...
Carregando plugin plugins/eventMacro/eventMacro.pl...
Este plugin não pôde ser carregado devido a um problema no plugin. Por favor notifique o autor sobre o problema, ou remova o plugin para que o OpenKore possa inicializar.

A mensagem de erro é:
Plugin contém erros de sintaxe:
The encoding pragma is no longer supported at plugins/eventMacro/eventMacro/FileParser.pm line 4.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/FileParser.pm line 4.
Compilation failed in require at plugins/eventMacro/eventMacro/Utilities.pm line 23.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Utilities.pm line 23.
Compilation failed in require at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
Compilation failed in require at plugins/eventMacro/eventMacro/Condition.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Condition.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Automacro.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Automacro.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Core.pm line 12.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Core.pm line 12.
Compilation failed in require at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.
BEGIN failed--compilation aborted at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.

Benchmark results saved to benchmark-results.txt
map unloaded.
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***
[nando@nando-pc openkore]$ ./openkore.pl
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

Carregando plugins selecionados...
Carregando plugin plugins/map/map.pl...
Carregando plugin plugins/eventMacro/eventMacro.pl...
Este plugin não pôde ser carregado devido a um problema no plugin. Por favor notifique o autor sobre o problema, ou remova o plugin para que o OpenKore possa inicializar.

A mensagem de erro é:
Plugin contém erros de sintaxe:
The encoding pragma is no longer supported at plugins/eventMacro/eventMacro/FileParser.pm line 4.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/FileParser.pm line 4.
Compilation failed in require at plugins/eventMacro/eventMacro/Utilities.pm line 23.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Utilities.pm line 23.
Compilation failed in require at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
Compilation failed in require at plugins/eventMacro/eventMacro/Condition.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Condition.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Automacro.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Automacro.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Core.pm line 12.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Core.pm line 12.
Compilation failed in require at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.
BEGIN failed--compilation aborted at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.

map unloaded.
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***
[nando@nando-pc openkore]$ ./openkore.pl
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

Carregando plugins selecionados...
Carregando plugin plugins/map/map.pl...
Carregando plugin plugins/eventMacro/eventMacro.pl...
Este plugin não pôde ser carregado devido a um problema no plugin. Por favor notifique o autor sobre o problema, ou remova o plugin para que o OpenKore possa inicializar.

A mensagem de erro é:
Plugin contém erros de sintaxe:
The encoding pragma is no longer supported at plugins/eventMacro/eventMacro/FileParser.pm line 4.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/FileParser.pm line 4.
Compilation failed in require at plugins/eventMacro/eventMacro/Utilities.pm line 23.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Utilities.pm line 23.
Compilation failed in require at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
Compilation failed in require at plugins/eventMacro/eventMacro/Condition.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Condition.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Automacro.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Automacro.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Core.pm line 12.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Core.pm line 12.
Compilation failed in require at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.
BEGIN failed--compilation aborted at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.

map unloaded.
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

scons: done building targets.
make: Leaving directory '/home/nando/openkore'
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

Carregando plugins selecionados...
Carregando plugin plugins/map/map.pl...
Carregando plugin plugins/eventMacro/eventMacro.pl...
Este plugin não pôde ser carregado devido a um problema no plugin. Por favor notifique o autor sobre o problema, ou remova o plugin para que o OpenKore possa inicializar.

A mensagem de erro é:
Plugin contém erros de sintaxe:
The encoding pragma is no longer supported at plugins/eventMacro/eventMacro/FileParser.pm line 4.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/FileParser.pm line 4.
Compilation failed in require at plugins/eventMacro/eventMacro/Utilities.pm line 23.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Utilities.pm line 23.
Compilation failed in require at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
Compilation failed in require at plugins/eventMacro/eventMacro/Condition.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Condition.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Automacro.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Automacro.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Core.pm line 12.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Core.pm line 12.
Compilation failed in require at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.
BEGIN failed--compilation aborted at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.

Benchmark results saved to benchmark-results.txt
map unloaded.
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***
[nando@nando-pc openkore]$ ./openkore.pl
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

Carregando plugins selecionados...
Carregando plugin plugins/map/map.pl...
Carregando plugin plugins/eventMacro/eventMacro.pl...
Este plugin não pôde ser carregado devido a um problema no plugin. Por favor notifique o autor sobre o problema, ou remova o plugin para que o OpenKore possa inicializar.

A mensagem de erro é:
Plugin contém erros de sintaxe:
The encoding pragma is no longer supported at plugins/eventMacro/eventMacro/FileParser.pm line 4.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/FileParser.pm line 4.
Compilation failed in require at plugins/eventMacro/eventMacro/Utilities.pm line 23.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Utilities.pm line 23.
Compilation failed in require at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
Compilation failed in require at plugins/eventMacro/eventMacro/Condition.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Condition.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Automacro.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Automacro.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Core.pm line 12.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Core.pm line 12.
Compilation failed in require at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.
BEGIN failed--compilation aborted at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.

map unloaded.
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***
[nando@nando-pc openkore]$ ./openkore.pl
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

Carregando plugins selecionados...
Carregando plugin plugins/map/map.pl...
Carregando plugin plugins/eventMacro/eventMacro.pl...
Este plugin não pôde ser carregado devido a um problema no plugin. Por favor notifique o autor sobre o problema, ou remova o plugin para que o OpenKore possa inicializar.

A mensagem de erro é:
Plugin contém erros de sintaxe:
The encoding pragma is no longer supported at plugins/eventMacro/eventMacro/FileParser.pm line 4.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/FileParser.pm line 4.
Compilation failed in require at plugins/eventMacro/eventMacro/Utilities.pm line 23.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Utilities.pm line 23.
Compilation failed in require at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Validator/NumericComparison.pm line 6.
Compilation failed in require at plugins/eventMacro/eventMacro/Condition.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Condition.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Automacro.pm line 8.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Automacro.pm line 8.
Compilation failed in require at plugins/eventMacro/eventMacro/Core.pm line 12.
BEGIN failed--compilation aborted at plugins/eventMacro/eventMacro/Core.pm line 12.
Compilation failed in require at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.
BEGIN failed--compilation aborted at /home/nando/openkore/plugins/eventMacro/eventMacro.pl line 17.

map unloaded.
*** OpenKore what-will-become-2.1 ( version git:29c9cf8_2017-11-13 ctime:2017_11_13 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

 perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-thread-multi

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by alisonrag** [comment]
openkore is compatible only with 5.12 32bits version of perl

**Comment by NandoPrates** [comment]
o @lututui  disse no discord q ele é compativel com as novas versões do perl no linux pq o linux compila o xstools.sempre usei no linux e nunca tive erros até testar no manjaro q contem a ultima versao do perl, não sei quanto a versão do perl no ubuntu e centos q utilizei a semanas atrás

**Comment by Nipodemos** [comment]
@NandoPrates the error says, that eventMacro is using some pragma ( in this case, is `enconding`)

which is deprecated in this version you are using

eventMacro was made for version 5.12
and you are using version 5.26

you have to downgrade perl a little bit, or update eventMacro code

**Comment by NandoPrates** [comment]
agora estou usando 5.20.1 e está totalmente funcional
usei o comando sudo curl -L http://xrl.us/installperlnix | bash 
a minha duvida é, será q entrara em conflito algum programa? @Nipodemos

**Comment by Nipodemos** [comment]
não tem como saber porque depende dos programas que voce instala e como eles são feitos

mas acho bem dificil. os programas normalmente nao se atualizam tao rapido assim

**Comment by lututui** [comment]
@alisonrag that's not true

@NandoPrates 
1- open plugins/eventMacro/eventMacro/FileParser.pm
2- find use encoding 'utf8'; (line 4)
3- replace it by use utf8;
4- repeat this for plugins/macro/Macro/Parser.pm

**Comment by moneyisgod** [comment]
@NandoPrates @HenryBK
