### ISSUE TITLE
ocp XII cant sell in vending for iro

### ISSUE THREAD

**Issue by lalilulelo1** [OpenKore/openkore#1389]
Hello i try to modify the item and item description in folder Tables>Iro>official
for example the item is skin of gwiber, and the gwiber is listed in inventory or cart
But the problem is bot wont sell the item in vending..
Any1 know what else i should change so the bot can sell in vending for newcoming items?
Thanks before

**Comment by alisonrag** [comment]
Try to use id in items_control
Ex
3232 0 0 1 0 0

**Comment by alisonrag** [comment]
Sorry is in vending :0
Post your configuration

**Comment by lalilulelo1** [comment]
@alisonrag  here is the configuration
![gwiber](https://user-images.githubusercontent.com/32214970/32757591-d60e0380-c912-11e7-86c6-a0546b1cd332.png)
![gwiber 2](https://user-images.githubusercontent.com/32214970/32757592-d7259b70-c912-11e7-9e4f-9b978111fc44.png)
![vending](https://user-images.githubusercontent.com/32214970/32757607-df9ea4c2-c912-11e7-87ef-cb28b9a8a333.png)

**Comment by alisonrag** [comment]
shop.txt?

**Comment by lalilulelo1** [comment]
here is the shop.txt
my gwiber is +8
![shop](https://user-images.githubusercontent.com/32214970/32760312-5751e044-c920-11e7-83d1-6bf13f5e8ccc.png)

**Comment by alisonrag** [comment]
in your shops is write
+8 Skin of Gwiber **[1]**
but openkore only show:
+8 Skin of Gwiber

without slot

**Comment by lalilulelo1** [comment]
I following the previous description, and in previous didnt written slotted
[1]

**Comment by lalilulelo1** [comment]
OMG
thanks for ur suggestion @alisonrag 
it worked
never think about the item slotted or not
thanks dude

**Comment by alisonrag** [comment]
@lalilulelo1 
you are welcome
