### ISSUE TITLE
Private Server Connection Problem

### ISSUE THREAD

**Issue by shahraf** [OpenKore/openkore#1390]
i'm having trouble with server type on http://flaxro.ro-gaming.net/?module=main&action=info
i already try all the kRO_RagexeRE,
currently on latest version of openkore,
and i'm trying to make a status buff type bots like clown and dancer..
i already trying it for a week and follow the wiki guide on how to connect to private server but i'm still failed

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration.

1. Client date ?

**Comment by alisonrag** [comment]
this is not a official issue, to get help about connect in private server use:
http://forums.openkore.com/viewforum.php?f=9&sid=dd9cb3dc8b763f7423af9da1d78fe0b1

read the manual:
http://openkore.com/index.php/Main_Page
![image](https://user-images.githubusercontent.com/32188494/32766701-0d813110-c94b-11e7-9814-c27f1da07931.png)
