### ISSUE TITLE
Detecting Player as NPC  for server version 46

### ISSUE THREAD

**Issue by shahraf** [OpenKore/openkore#1394]
ip 45.77.45.251
port 6907
private 1
version 46
master_version 14
addTableFolders FlaxRO
serverType **kRO_RagexeRE_2015_10_01b**
serverEncoding Western
charBlockSize 144

if using **kRO_RagexeRE_2015_10_01b**
its detect player as NPC

[recvpackets.txt](https://github.com/OpenKore/openkore/files/1473177/recvpackets.txt)

![untitled](https://user-images.githubusercontent.com/33647911/32815370-bbc71c1e-c9ee-11e7-872e-c0dfa27eb7ba.jpg)

and my  **ragnarok .exe date is Dec 23 2013****

if i using the **RagexeRE_2013_08_07a** 
here's the problem:

![problem](https://user-images.githubusercontent.com/33647911/32815649-046b1492-c9f0-11e7-9c8d-39f55713ae08.jpg)

i cant find the correct one....

**Comment by shahraf** [comment]
this is on private server and when i post here they say go to private section and when i go there its say moved to github, so how do i get help!!!!

**Comment by fadreus** [comment]
You don't read & use the issue template; that's why you're confused.
I believe the appropriate issue to be discussed here is if there are any problems with openkore and any request to improve openkore (by create PR).

> so how do i get help!!!!

This section isn't Service Center.
This place is more to R&D department.
![image](https://user-images.githubusercontent.com/32188494/32817914-5433a5b0-c9fb-11e7-8a32-f1e6b73556d9.png)

> moved to github

If you read properly, indeed the project are moved to github (from SourceForge) not moving the entire discussion from forum to github.

If you spend more time reading, you won't be confused.

**Comment by sctnightcore** [comment]
RagexeRE_2013_08_07a

**Comment by shahraf** [comment]
http://flaxro.ro-gaming.net/?module=main&action=info
id : botapple
pass : 123456789
@sctnightcore  ty for help really appreciate it..

**Comment by shahraf** [comment]
@sctnightcore  so what do i do now? i really noob on this.. need guide..

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/pull/1395/files 

@shahraf  You just follow me fix .

**Comment by shahraf** [comment]
@sctnightcore  can u connect teamviewer ?

here the id 295 176 301 
pass 9442

**Comment by sctnightcore** [comment]
@shahraf  download new openkore and test it again ! .

**Comment by shahraf** [comment]
@sctnightcore  okay..!! thx bro let me try this 👍

**Comment by shahraf** [comment]
@sctnightcore  this is happen after i download new openkore add the server.txt and recvpacket


![fail](https://user-images.githubusercontent.com/33647911/32859024-3d72d3e0-ca88-11e7-9608-de3eb70a8822.jpg)

**Comment by shahraf** [comment]
i try to connect like 10 times...sometime it can sometime its stuck at connecting char select server

![sometimes](https://user-images.githubusercontent.com/33647911/32874251-00342d50-cacc-11e7-9fa6-223684b25fb4.jpg)

**Comment by sctnightcore** [comment]
@shahraf  i will fix sometime .. 
if i'm free .

**Comment by c4c1n6kr3m1** [comment]
compare the packet

**Comment by shahraf** [comment]
@sctnightcore  what is the problem??

**Comment by sctnightcore** [comment]
@shahraf  wait to char i think XD

**Comment by shahraf** [comment]
@sctnightcore i got old contol folder from my friend and it can login but this happen

[teleToDest] There are config keys not defined, plugin won't be activated.
[eventMacro] No control/eventMacros.txt file was found. Plugin disabled.
[eventMacro] Plugin unloading
Plugin eventMacro unloaded.

**Comment by sctnightcore** [comment]
**Dont use old Contol !**
