### ISSUE TITLE
İro ReStart maintenance

### ISSUE THREAD

**Issue by Gulxx** [OpenKore/openkore#1396]
iro re start maintenance after again not working

**Comment by Darksin88** [comment]
i logged in and only 200ppl connected.. you telling me that 4k are bots?

**Comment by Bombahee** [comment]
download the latest version, you can login but still having problem, stuck during route in town

**Comment by Gulxx** [comment]
stuck during route openkore i have

**Comment by oleokoong** [comment]
#1397
