### ISSUE TITLE
openkore does not move.

### ISSUE THREAD

**Issue by gr4ndmasterz** [OpenKore/openkore#1397]
apparently after downloading the latest openkore.

the bot wont move and just stays in 1 place.

**Comment by Bombahee** [comment]
mine, getting stuck in town, stuck during route

**Comment by Gulxx** [comment]
stuck during route openkore  i have

**Comment by Nipodemos** [comment]
Type a command when this happen:
**reload portals **

**Comment by Gulxx** [comment]
not works reload portals

**Comment by davinci1986** [comment]
Me too. Keep like this after re-download the new Openkopre

Server: iRO-Restart: Odin

> Calculating random route to: Mushroom Farm (job_thief1): 66, 178
> Stuck at job_thief1 (61,52), while walking from (61,52) to (66,178).
> Stuck during route.
 Any idea?

**Comment by oleokoong** [comment]
the packet for move is broke, and the devs who did the shuffler will look for it in next 9 hour..because he busy on real life things

**Comment by akositek** [comment]
Stuck at payon (258,241), while walking from (258,241) to (233,304).
Stuck during route.
Calculating lockMap route to: Payon Cave(pay_dun03)
Stuck at payon (258,241), while walking from (258,241) to (228,329).
Stuck during route.
Calculating lockMap route to: Payon Cave(pay_dun03)

I got this issue guys. please help ..

**Comment by c4c1n6kr3m1** [comment]
be patient

**Comment by null32sys** [comment]
Openkore Log

Sent sendMapLogin
Received packet: 0283 Handler: account_id

And can't load map login

I've been got this on map server tcp port 5000 through wireshark (C Array)

Send
0x72, 0x00, 0xa7, 0x28, 0x03, 0x00, 0xb7, 0xc5, 
0x07, 0x00, 0xa3, 0x2e, 0x00, 0x00, 0x54, 0x60, 
0x06, 0x00, 0x01 };

Recv
char peer1_1[] = { /* Packet 49 */
char peer1_2[] = { /* Packet 50 */
0x83, 0x02, 0xa7, 0x28, 0x03, 0x00 };
char peer1_3[] = { /* Packet 51 */
0xeb, 0x02, 0x4b, 0xb4, 0x07, 0x1f, 0x38, 0x4d, 
0x60, 0x05, 0x05, 0x00, 0x00 };
char peer1_4[] = { /* Packet 53 */
0xb0, 0x00, 0x31, 0x00, 0x2b, 0x01, 0x00, 0x00, 
0xb0, 0x00, 0x35, 0x00, 0xb8, 0x01, 0x00, 0x00, 
0xb0, 0x00, 0x31, 0x00, 0x35, 0x01, 0x00, 0x00,

**Comment by sctnightcore** [comment]
> '0072' => ['map_login', 'a4 a4 a4 V C', [qw(accountID charID sessionID tick sex)]],

**Comment by null32sys** [comment]
look after char peer1_4[] = { / Packet 53 */

that the character move packet

**Comment by sctnightcore** [comment]
packet move size 5  !

**Comment by null32sys** [comment]
00000000  72 00 a7 28 03 00 b7 c5  07 00 a3 2e 00 00 54 60   r..(.... ......T`
00000010  06 00 01                                           ...
    00000000  83 02 a7 28 03 00                                  ...(..
    00000006  eb 02 4b b4 07 1f 38 4d  60 05 05 00 00            ..K...8M `....
    00000013  b0 00 31 00 2b 01 00 00  b0 00 35 00 b8 01 00 00   ..1.+... ..5.....
    00000023  b0 00 31 00 35 01 00 00  3a 01 01 00 0f 01 7c 03   ..1.5... :.....|.
    00000033  01 00 00 00 00 00 09 00  00 00 01 00 4e 56 5f 42   ........ ....NV_B

I think the packet has been encrypted

**Comment by sctnightcore** [comment]
```
----[ send( 672, 0x07F27791, 5, 0x0 ) == 5
0000  3E 13 3A CB C0                                   >.:..
```
`133E 0437 ?`

test again

**Comment by null32sys** [comment]
I must go to go now sorry slow response

**Comment by null32sys** [comment]
1  :50050  128.241.92.133:6800  55  Send  
0000  64 00 12 00 00 00 

2  128.241.92.133:6800  :50050  79  Recv  
0000  69 00 4F 00 38 AA 3A FC B8 43 02 00 00 00 00 00    i.O.8.:..C......
0010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0020  00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 80    ................
0030  F1 5C 8A 94 11 4F 64 69 6E 00 00 00 00 00 00 00    .\...Odin.......
0040  00 00 00 00 00 00 00 00 00 7B 05 00 00 00 00       .........{.....

3  :50051  128.241.92.138:4500  17  Send  
0000  65 00 B8 43 02 00 38 AA 3A FC 00 00 00 00 00 00    e..C..8.:.......
0010  01                                                 .

4  128.241.92.138:4500  :50051  4  Recv  
0000  B8 43 02 00                                        .C..

5  128.241.92.138:4500  :50051  35  Recv  
0000  2D 08 1D 00 03 09 00 03 03 00 00 00 00 00 00 00    -...............
0010  00 00 00 00 00 00 00 00 00 00 00 00 00 A0 09 0C    ................
0020  00 00 00                                           ...

6  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

7  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

8  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

9  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

10  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

11  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

12  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

13  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

14  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

15  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

16  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

17  :50051  128.241.92.138:4500  2  Send  
0000  A1 09                                              ..

18  128.241.92.138:4500  :50051  149  Recv  
0000  9D 09 95 00 B0 A3 02 00 90 7A 07 00 C5 3D 00 00    .........z...=..
0010  54 68 03 00 1E 00 00 00 00 00 00 00 00 00 00 00    Th..............
0020  00 00 00 00 00 00 00 00 00 00 00 00 06 00 21 0A    ..............!.
0030  00 00 E6 0E 00 00 2C 01 2C 01 96 00 0C 00 17 00    ......,.,.......
0040  00 00 48 00 00 00 00 00 00 00 60 02 44 00 05 00    ..H.......`.D...
0050  00 00 4E 75 62 65 65 00 00 00 00 00 00 00 00 00    
0060  00 00 00 00 00 00 00 00 00 00 35 34 10 01 16 37    ..........54...7
0070  00 00 00 00 63 6D 64 5F 66 69 6C 64 30 34 2E 67    ....cmd_fild04.g
0080  61 74 00 00 00 00 00 00 00 00 00 00 00 00 00 00    at..............
0090  00 00 00 00 01                                     .....

19  :50051  128.241.92.138:4500  6  Send  
0000  87 01 B8 43 02 00                                  ...C..

20  128.241.92.138:4500  :50051  6  Recv  
0000  87 01 B8 43 02 00                                  ...C..

21  :50051  128.241.92.138:4500  3  Send  
0000  66 00 00                                           f..

22  128.241.92.138:4500  :50051  28  Recv  
0000  71 00 B0 A3 02 00 63 6D 64 5F 66 69 6C 64 30 34    q.....cmd_fild04
0010  2E 67 61 74 00 00 80 F1 5C 8B 98 11                .gat....\...

23  :50052  128.241.92.139:4504  19  Send  
0000  CF 32 B8 43 02 00 B0 A3 02 00 38 AA 3A FC 11 10    .2.C......8.:...
0010  16 00 01                                           ...

24  128.241.92.139:4504  :50052  2048  Recv  
0000  83 02 B8 43 02 00 EB 02 B1 1C 57 04 30 11 E0 05    ...C......W.0...
0010  05 00 00 B0 00 32 00 1D 01 00 00 B0 00 00 00 87    .....2..........
0020  00 00 00 0F 01 C3 02 01 00 00 00 00 00 09 00 00    ................
0030  00 01 00 4E 56 5F 42 41 53 49 43 00 00 00 00 00    ...NV_BASIC.....

**Comment by Gulxx** [comment]
please fixed Stuck at morocc (159,69), while walking from (159,69) to (160,17).
Stuck during route.
Calculating lockMap route to: Sograt Desert(moc_fild16)

**Comment by VModMango** [comment]
Any updates?

**Comment by alisonrag** [comment]
please wait for someone, the update dont come more faster if you post everytime

**Comment by Gokuref** [comment]
As far as I know, everyone here is waiting.
Asking a question doesn't hurt. mi mi mi

**Comment by olodummare** [comment]
vamos ter calma que os cara é bom ,, jaja sai essa att
