### ISSUE TITLE
vender command right-truncates newly allowed higher prices.

### ISSUE THREAD

**Issue by ChrstphrR** [OpenKore/openkore#14]
iRO, and I believe, kRO, and possibly other official servers now support a price limit of 9999*10^5 (999,900,000z), but the table for a vender's shop is only wide enough to support the old limit of 99,999,999z, which causes prices over 100 million to to truncate the last zero in the display.

E.g.  Vender Foo is vending Jellopy for 250,000,000z each (what a bargain!), the vender shop price in openkore will display as 250,000,00z

It's not a huge functional bug, but it is a bug

**Comment by allanon** [comment]
The new limit is actually `1,000,000,000z`, so the worst case truncation is three characters, and the result is `1,000,000,`, which is pretty confusing.

**Comment by itsrachelfish** [comment]
Gotta love that auto close on merge. :+1:
