### ISSUE TITLE
XKore 1, 2, and 3 DC on Map Server- iRO- Renewal Thor

### ISSUE THREAD

**Issue by vhonn** [OpenKore/openkore#1401]
I just came back to play after a year of hibernation, Just need to know if there is any way I can Run Xkore 1 on iRO Thor. As of the moment I can run on XKore 0 smoothly but when I go Xkore 1 or 3 it wont connect on Map server or being disconnected right after. Any Help. TYIA.

Plus NPC locations are messed up on iRO Renewal Thor.

**Comment by sctnightcore** [comment]
**Please use the issue template, please post infornations about the server and your configuration.**

Wait @allanon

**Comment by fadreus** [comment]
@vhonn Have you try #1374 ?
This PR hasn't been merged to master, yet.

**Comment by alisonrag** [comment]
use #1374 
and if the renewal update wait for the update.

one more thing:
XKore is less tolerant to incorrect server settings. If everything works without XKore and there is some problem with XKore, it may still be a problem with server settings like serverType, charBlockSize etc.

**Comment by vhonn** [comment]
so basically this is just copy/paste overwrite files I assume because there is 5 parts of this update [#1374](https://github.com/OpenKore/openkore/pull/1374) 
1. **_fix xkore 1 and 3_** - contains  .gitignore, reconnect.pl, Receive.pm ,ServerType0.pm, Xkore.pm and 
    XKoreProxy.pm
2. **_remove not used variable_** - contains update for reconnect.pl file
3.  **_missing import_** - update to XKore.pm file (overwrites XKore.pm file on the 1st part of the update).
4. **_remove portal LOS_**  - not applicable
5. **_xkore 1 reset key when chang mapserver_** - update to XKore.pm file (overwrites XKore.pm file on the 1st and 3rd part of the update).

**Comment by alisonrag** [comment]
@vhonn 
just access this link:
https://github.com/OpenKore/openkore/pull/1374/files
this files is the latest version in pull request

**Comment by vhonn** [comment]
XKore 1 works perfectly for iRO -Thor Server. One issue I bump in is being DC on map server while or after doing autostorage and so disabled autostorage for the time being.

**Comment by alisonrag** [comment]
so this is with servertype file =p
