### ISSUE TITLE
iRO: Restart - xkore 3 back to stuck after login

### ISSUE THREAD

**Issue by puakayj** [OpenKore/openkore#1406]
###### Summary: 
New update xkore 3 back to stuck after login and keep reconnecting to the server

###### Impact:
cant connect to iRO : RESTART

###### Steps to Reproduce:
try to connect using xkore 3

**Comment by sctnightcore** [comment]
what ?

**Comment by alisonrag** [comment]
please update your issue or we will close

**Comment by alisonrag** [comment]
server?

**Comment by puakayj** [comment]
idro : restart

**Comment by sctnightcore** [comment]
LOL 
idRO : RESTART XD

**Comment by alisonrag** [comment]
@sctnightcore 
can you confirm this?

@puakayj 
did you downloaded the last version of openkore?

**Comment by puakayj** [comment]
yup just DL new open  kore and everything back to stuck like before

**Comment by sctnightcore** [comment]
@alisonrag  Nooooooooo

**Comment by alisonrag** [comment]
is idRO or iRO?

**Comment by puakayj** [comment]
its iRO

**Comment by alisonrag** [comment]
in:
openkore\src\network\iRO.pm

change this:
```
	my %handlers = qw(
		sync 0360
		character_move 035F
		actor_info_request 0368
		actor_look_at 0361
		item_take 0362
		item_drop 0363
		storage_item_add 0364
		storage_item_remove 0365
		skill_use_location 0366
		party_setting 07D7
		buy_bulk_vender 0801
		char_delete2_accept 098f
		send_equip 0998
	);
```

to this:
```
	my %handlers = qw(
		sync 0360
		character_move 035F
		actor_info_request 0368
		actor_look_at 0361
		item_take 0362
		item_drop 0363
		storage_item_add 0364
		storage_item_remove 0365
		skill_use_location 0366
		party_setting 07D7
		buy_bulk_vender 0801
		char_delete2_accept 098f
		send_equip 0998
		**map_login 0DBD**
	);
```
and post result:

**Comment by lobocop** [comment]
still stuck, attacking but still stuck

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/32927818-6d8dec46-cb81-11e7-9832-0bc6108d7d29.png)
I have tested it. It works fine.

**Comment by puakayj** [comment]
openkore\src\network\iRO.pm ?

**Comment by alisonrag** [comment]
1 - download the latest version
https://github.com/OpenKore/openkore/archive/master.zip

2 - apply my pull
#1374 

3 - in src\network\send\iRO.pm add `map_login 0436` in handlers(edited)
`
my %handlers = qw(
        sync 0360
        character_move 035F
        actor_info_request 0368
        actor_look_at 0361
        item_take 0362
        item_drop 0363
        storage_item_add 0364
        storage_item_remove 0365
        skill_use_location 0366
        party_setting 07D7
        buy_bulk_vender 0801
        char_delete2_accept 098f
        send_equip 0998
        map_login 0436
    );
`

**Comment by c4c1n6kr3m1** [comment]
good

**Comment by rocket12406** [comment]
can you up load file to mediafire.com. I can't dowload new version from your link

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore.git @rocket12406  
XD GL

**Comment by Gulxx** [comment]
thank you

**Comment by alisonrag** [comment]
@puakayj 
please update us

**Comment by alisonrag** [comment]
Working with latest version

**Comment by puakayj** [comment]
ops sry for late reply, everything working now .
