### ISSUE TITLE
xKore1 DC after 10 Minutes - Timeout from Map Server (iRO Re:start)

### ISSUE THREAD

**Issue by xSorux** [OpenKore/openkore#1411]
------------------ Bug Report Template ------------------
###### Summary: 
TimeOut from Map Server after approx. 10 minutes. Verified on xKore1. Can't tell if 2 or 3 work, havent tested. No issues when not using xKore. 
**Tried a complete fresh installation.** 
Same issue as #1377 . Occured again after movement encryption and shuffle has been fixed.
Let me know if you need any debug info.

###### Steps to Reproduce:
run Xkore1.

**Comment by sctnightcore** [comment]
**Download openkore again and test again.**

**Comment by xSorux** [comment]
>  Tried a complete fresh installation.

**Comment by sctnightcore** [comment]
Download new openkore and test again ! .
It works fine @xSorux 
![x1](https://user-images.githubusercontent.com/23263315/32975157-069d3d8c-cc37-11e7-9fcf-73d833cbd540.png)

**Comment by xSorux** [comment]
![grafik](https://user-images.githubusercontent.com/30437356/32975801-9fe4c360-cc0b-11e7-8f5e-81f158f3f4c8.png)

**Comment by xSorux** [comment]
![grafik](https://user-images.githubusercontent.com/30437356/32975825-cef173e2-cc0b-11e7-8b6f-ed83d4f42c1f.png)

**Comment by sctnightcore** [comment]
@alisonrag  come here 
@xSorux  You try xkore3 XD

**Comment by alisonrag** [comment]
That i can see @xSorux tested and worked we can close

**Comment by xSorux** [comment]
no timeout on xKore3 in around 1h

**Comment by sctnightcore** [comment]
@xSorux  ♥
