### ISSUE TITLE
Party Setting (Spam)

### ISSUE THREAD

**Issue by FireflySkye** [OpenKore/openkore#1412]
Server: **iRO Chaos**
Lastest (new) Openkore

I set my config to **`partyAutoShare 1`**, if I have a party mate that out of my level range the kore will spam the msg below (right). It stops if I transfer the lead or kick low level character.

(Left) Party Share is Even
(Right) Party Share is Each

I set all my config `partyAutoShare` to `1` so that I don't need to change it every time party within my level range.

![party](https://user-images.githubusercontent.com/19757768/32979091-10ad24bc-cc92-11e7-8278-938f3c623983.png)

**Comment by fadreus** [comment]
Someone will probably asking this since you ignore the bug issue template;

- Which server?
- Openkore version?

**Comment by FireflySkye** [comment]
Sorry about that.

I set it to `partyAutoShare 1` so that I don't need to changed it if I party my other other within the same level range.

Anyways. Thanks.

**Comment by fadreus** [comment]
Is it solved?
Can simply change config setting using console without editing config.txt by using command
`conf partyAutoShare 0`

**Comment by FireflySkye** [comment]
Okay. Thanks.

**Comment by alisonrag** [comment]
Custom timeout?

**Comment by alisonrag** [comment]
the only way to this happen is delete or set  partyShareCheck to a lower value intimeouts.txt, can you confirm?

**Comment by FireflySkye** [comment]
@alisonrag Thank you. That fixed the spamming thing

**timeouts.txt**
set `partyShareCheck` value to below 60
I set mine to `partyShareCheck 10`
