### ISSUE TITLE
Bot gets disconnected after ~30s - CzechRO

### ISSUE THREAD

**Issue by JVilda** [OpenKore/openkore#1416]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:
http://forums.openkore.com/viewtopic.php?f=9&t=212463

**Comment by sctnightcore** [comment]
There is a problem at servertybe.
I'll come back to fix it.

**Comment by alisonrag** [comment]
POST YOUR CONFIGURATION

**Comment by alisonrag** [comment]
maybe sync packet is wrong

**Comment by sctnightcore** [comment]
@alisonrag  i think so

**Comment by JVilda** [comment]
[CzRo]
ip 82.142.93.36
port 6900
private 1
version 20
master_version 16
serverType kRO_RagexeRE_2010_07_14a
serverEncoding Western
charBlockSize 106
recvpackets ferda.txt
addTableFolders kRO/RagexeRE_2010_07_14a;translated/kRO_english;kRO


This is the most actual settings im using

**Comment by sctnightcore** [comment]
@JVilda  register id pw and Create char

**Comment by JVilda** [comment]
id Bump
pw JVilda10

char done

**Comment by sctnightcore** [comment]
@JVilda  ok ty

**Comment by JVilda** [comment]
@sctnightcore I thank you :+1:

**Comment by sctnightcore** [comment]
@JVilda 
serverType kRO_RagexeRE_2010_11_24a

With recvpacket from client

**Comment by JVilda** [comment]
@sctnightcore 
Still the same problem as before. Tried to get recvpackets again from the client. Doesnt help.
![newkore](https://user-images.githubusercontent.com/33792012/33028622-b4998568-ce16-11e7-831a-44ced87047c3.png)

**Comment by sctnightcore** [comment]
@JVilda  wait 

I want time T.T

**Comment by JVilda** [comment]
@sctnightcore Im waiting, you have all the time you want and need

**Comment by JVilda** [comment]
With this config i was able to log in with Xkore 1 [CzRo]
ip 82.142.93.36
port 6900
private 1
version 20
master_version 16
serverType kRO_RagexeRE_2012_04_10a
serverEncoding Western
charBlockSize 106
recvpackets recvpackets_czro.txt
addTableFolders pserver/KoreRO;eA;kRO/RagexeRE_2010_07_14a;translated/kRO_english;kRO


Problem is with Unknown switch: 0085 Packet Parser: Unknown switch: 0085 Packet Parser: Unknown switch: 0085 Packet Parser: Unknown switch: 0085 Packet Parser: Unknown switch: 0085

Game is not properly responding to bot, some commands i.e. movement, fighting does not work, some i.e. sorting items to cart and autoskill worked for a while. 

Problem looks like AntiWPE Sock hook + custom packets on client. 

I am open to any suggestions on what to try.

Thank you all for your time

**Comment by sctnightcore** [comment]
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1489427/recvpackets.txt)

test with recvpacket + x1

**Comment by JVilda** [comment]
With this recvpackets and Xkore 1 i am unable to connect to map server.

**Comment by sctnightcore** [comment]
@JVilda  idk why . XD

**Comment by JVilda** [comment]
@sctnightcore its weird af :D

**Comment by c4c1n6kr3m1** [comment]
on servertype0.pm
'0085' => ['character_move', 'a3', [qw(coords)]],

**Comment by alisonrag** [comment]
some packets:
0094 actor_info_request
0095 actor_info
0085 move
007F sync

**Comment by alisonrag** [comment]
its a 2010 servertype, we only have documented and implemented right 2012+ servers, fornow we can do a custom servertype based in RagexeRE_2010_xx_xx

**Comment by JVilda** [comment]
So, what should i do ?

**Comment by alisonrag** [comment]
should i stay or should i go?

**Comment by alisonrag** [comment]
you can do a servertype to your server by yourself or wait for someone help you with this.

**Comment by JVilda** [comment]
[CzRo]
ip 82.142.93.36
port 6900
private 1
version 20
master_version 16
serverType iRO_Classic
serverEncoding Western
charBlockSize 106
recvpackets recvpackets.txt
addTableFolders czRO 



Working config. Now bot works as usual.

Thanks to everyone for support.

#prayforopenkore

**Comment by sctnightcore** [comment]
I will not go back to fix sT2010.

**Comment by alisonrag** [comment]
I will be back

**Comment by simbi5784** [comment]
Hi JVilda, can you help me with setting for this server?
