### ISSUE TITLE
Rouge Autosteal not working

### ISSUE THREAD

**Issue by kentmel** [OpenKore/openkore#1419]
Skill Steal failed: requirement (error number 10)

what is wrong? i don't know how to fix because it a passive skill but is not working... Any idea would be appreciated. THanks

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration.

**Comment by alisonrag** [comment]
Its not a bug,
Its normal is the passive trying to work
If you pay attention in console will see that rogue is stealing sometimes
