### ISSUE TITLE
Received packet: 0088 Handler: actor_movement_interrupted [idRO : Renewal]

### ISSUE THREAD

**Issue by null32sys** [OpenKore/openkore#1422]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Actual Behavior:
My bot doesn't attack Disguise
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

attackAuto 2

###### Additional Details:

[Nov 20 16:40:20 2017.27] Received packet: 0088 Handler: actor_movement_interrupted
[Nov 20 16:40:20 2017.28] Received packet: 02E1 Handler: actor_action
[Nov 20 16:40:20 2017.29] [ 25/ 82] Monster Disguise (1) attacks you (Dmg: Miss!!) (Delay: 768ms)
[Nov 20 16:40:20 2017.46] Received packet: 0088 Handler: actor_movement_interrupted
[Nov 20 16:40:20 2017.51] Received packet: 02E1 Handler: actor_action
[Nov 20 16:40:20 2017.53] [ 25/ 82] Monster Disguise (0) attacks you (Dmg: Miss!) (Delay: 768ms)
[Nov 20 16:40:20 2017.93] Received packet: 0088 Handler: actor_movement_interrupted
[Nov 20 16:40:20 2017.95] Received packet: 02E1 Handler: actor_action
[Nov 20 16:40:20 2017.96] [ 25/ 82] Monster Disguise (2) attacks you (Dmg: 252) (Delay: 768ms)
[Nov 20 16:40:21 2017.28] Received packet: 0088 Handler: actor_movement_interrupted
[Nov 20 16:40:21 2017.42] Received packet: 02E1 Handler: actor_action
[Nov 20 16:40:21 2017.55] [ 25/ 82] Monster Disguise (1) attacks you (Dmg: Miss!) (Delay: 768ms)
[Nov 20 16:40:21 2017.13] Received packet: 0088 Handler: actor_movement_interrupted

**Comment by sctnightcore** [comment]
'0088' => ['actor_movement_interrupted', 'a4 v2', [qw(ID x y)]],
xkore 1,3 ?

**Comment by null32sys** [comment]
xkore 1

**Comment by null32sys** [comment]
Close this thread, I get the solution.

avoidSkill 0
avoidSkill_domain info

avoidSkill Warp Portal {
	source Player
	radius 0
	method 0
	step 10
}
avoidSkill Hammer Fall {
	source Monster
	method 2
	radius 1
	step 10
}
#incase u want to avoid angelings safetywall#
avoidSkill Safety Wall {
	source Monster
	method 1
	radius 2
	step 10
}
avoidSkill Ice Wall {
	source Player
	method 3
}
avoidSkill Heaven's Drive {
	source Monster
	method 2
	radius 2
	step 10
}
avoidSkill Brandish Spear {
	source Monster
	method 3
}
avoidSkill Fire Bolt, Fire Wall, Water Ball {
	source Monster
	method 4
	radius 15
	step 10
}
avoidSkill Fire Bolt, Fire Wall, Water Ball {
	source Monster
	method 5
	radius 15
	step 10
	skill Provoke
	lvl 1
}

AvoidSkill macro make me get this error.

**Comment by null32sys** [comment]
AvoidSkill is 0 now still get error Received packet: 0088 Handler: actor_movement_interrupted

**Comment by sctnightcore** [comment]
**ADD ALL AVOID TO CONFIG ! NOT MARCO FILE .**

**Comment by null32sys** [comment]
@sctnightcore restart pc and delete the macro from plugin folder
config same as the source

And still get that error 

Received packet: 0088 Handler: actor_movement_interrupted

**Comment by sctnightcore** [comment]
actor_action 02E1 is not 08C8 ?

**Comment by greatjr** [comment]
@null32sys 
null.. tau ngga server.txt buat ragnarok gravindo yg renewal..
share please

**Comment by null32sys** [comment]
xkore 1

**Comment by ilfan14** [comment]
why today can't login with openkore?

**Comment by sctnightcore** [comment]
@ilfan14  use with x1 and x3

**Comment by sctnightcore** [comment]
Any update? @null32sys

**Comment by null32sys** [comment]
I change my spot.

Sometime I get this error

[Nov 20 00:36:05 2017.58] Timeout on Map Server, [Nov 20 00:36:05 2017.72] waiting actions for the Ragnarok Online client

**Comment by sctnightcore** [comment]
@null32sys  xkore 3 !!!

**Comment by KimJongkok** [comment]
This is about idro renewal or idro classic guys?

**Comment by KimJongkok** [comment]
Can we use xkore1 for idro classic?

**Comment by sctnightcore** [comment]
@KimJongkok  only idRO renewal
