### ISSUE TITLE
iRO: Failed to teleport using NPC at prontera[Cutom warp with vip user]

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#1423]
Server: iRO Chaos Renewal
Version: last and pre last
All my bots stuck now in Prontera and get its messages :
![freshbug](https://user-images.githubusercontent.com/20753532/33020754-74731d24-ce10-11e7-8fa9-314ad9695746.jpg)

This happened unexpectedly, before the incident I did not update the Openkore and did not change the setting.

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration.

New openkore ?

**Comment by fadreus** [comment]
That's location is for old prontera map.
Renewal NPC need to be updated as the NPC location has slightly moved.
And also, apply this #1182

**Comment by Glikadin** [comment]
![freshbug](https://user-images.githubusercontent.com/20753532/33021317-7b6dbcea-ce12-11e7-8c15-7fb417c38a7c.jpg)

**Comment by fadreus** [comment]
Old one working fine
![image](https://user-images.githubusercontent.com/32188494/33021357-8da754c8-ce3c-11e7-80ab-540faf6f47f4.png)

**Comment by Glikadin** [comment]
config.txt
```
lockMap yuno_fild02
lockMap_x
lockMap_y
lockMap_randX
lockMap_randY

route_escape_reachedNoPortal 1
route_escape_randomWalk 1
route_escape_shout
route_avoidWalls 1
route_randomWalk 1
route_randomWalk_inTown 0
route_randomWalk_maxRouteTime 75
route_maxWarpFee
route_maxNpcTries 5
route_teleport 0
route_teleport_minDistance 150
route_teleport_maxTries 8
route_teleport_notInMaps
route_step 15
```
portals.txt:
`prontera 146 89 aldebaran 168 112 2000 c r2 c r~/al de baran/i`

1 minuts , i am trying Old Prontera

**Comment by Glikadin** [comment]
Nice. Dont work. I'm going to use routeweights.txt or macros

**Comment by fadreus** [comment]
This can be cont at #1417 it seems.

**Comment by Glikadin** [comment]
automacro RouteFix {
console /Failed to teleport using NPC at prontera/i
timeout 120
     call {
     do talknpc 146 89 c r2 c r~/al de baran/i
     pause 5
     }
}

It work!
Ahahaha xD xD

**Comment by fadreus** [comment]
@Glikadin I just downloaded a new one to test and everything is fine.
What the heck do you guys did?
:thinking::thinking::thinking::thinking:
![image](https://user-images.githubusercontent.com/32188494/33022347-d7aa3baa-ce3f-11e7-9afb-9ff4658386ae.png)

**Comment by Glikadin** [comment]
Oh sorry, i dont know

**Comment by sctnightcore** [comment]
GO #1417

**Comment by fadreus** [comment]
> plugins conflicts or specific settings

That's what I mean by "what did you do" since plain original one have no issue.

**Comment by Glikadin** [comment]
I found problem:
need to switch in portals.txt:
from
`prontera 146 89 aldebaran 168 112 2000 c r2 c r~/al de baran/i`
to
`prontera 146 89 aldebaran 168 112 2000 c r2 c r~/baran/i`

I don `t know why both options do not work.
Thanks for the help and sorry for the trouble.

**Comment by sctnightcore** [comment]
**Send a response to the NPC. The response is the first one which matches the given regular expression.**
`prontera 146 89 aldebaran 168 112 2000 c r2 c r~/al.de.baran/g`

**Comment by fadreus** [comment]
@Glikadin If you not sure, what you wanna change, just stick to the basic
![image](https://user-images.githubusercontent.com/32188494/33023975-bdcd88ae-ce44-11e7-9444-34d0a7f05eb1.png)

**Comment by Glikadin** [comment]
@fadreus Me need to use WIP and non-WIP accounts =\

**Comment by sctnightcore** [comment]
You should use the following @fadreus

**Comment by Glikadin** [comment]
Now i am using this portals:
```
# Non-VIP Warps
prontera 146 89 izlude 94 103 2000 c r2 c r~/izlude/i
prontera 146 89 geffen 120 39 2000 c r2 c r~/geffen/i
prontera 146 89 payon 161 58 2000 c r2 c r~/payon/i
prontera 146 89 morocc 156 47 2000 c r2 c r~/morroc/i
prontera 146 89 alberta 117 56 2000 c r2 c r~/alberta/i
prontera 146 89 aldebaran 168 112 2000 c r2 c r~/baran/i
prontera 146 89 comodo 209 143 3000 c r2 c r~/comodo/i
prontera 146 89 umbala 100 154 3000 c r2 c r~/umbala/i
prontera 151 29 izlude 94 103 2000 c r2 c r~/izlude/i
prontera 151 29 geffen 120 39 2000 c r2 c r~/geffen/i
prontera 151 29 payon 161 58 2000 c r2 c r~/payon/i
prontera 151 29 morocc 156 47 2000 c r2 c r~/morroc/i
prontera 151 29 alberta 117 56 2000 c r2 c r~/alberta/i
prontera 151 29 aldebaran 168 112 2000 c r2 c r~/baran/i
prontera 151 29 comodo 209 143 3000 c r2 c r~/comodo/i
prontera 151 29 umbala 100 154 3000 c r2 c r~/umbala/i
prontera 282 200 izlude 94 103 2000 c r2 c r~/izlude/i
prontera 282 200 geffen 120 39 2000 c r2 c r~/geffen/i
prontera 282 200 payon 161 58 2000 c r2 c r~/payon/i
prontera 282 200 morocc 156 47 2000 c r2 c r~/morroc/i
prontera 282 200 alberta 117 56 2000 c r2 c r~/alberta/i
prontera 282 200 aldebaran 168 112 2000 c r2 c r~/baran/i
prontera 282 200 comodo 209 143 3000 c r2 c r~/comodo/i
prontera 282 200 umbala 100 154 3000 c r2 c r~/umbala/i
prontera 29 207 izlude 94 103 2000 c r2 c r~/izlude/i
prontera 29 207 geffen 120 39 2000 c r2 c r~/geffen/i
prontera 29 207 payon 161 58 2000 c r2 c r~/payon/i
prontera 29 207 morocc 156 47 2000 c r2 c r~/morroc/i
prontera 29 207 alberta 117 56 2000 c r2 c r~/alberta/i
prontera 29 207 aldebaran 168 112 2000 c r2 c r~/baran/i
prontera 29 207 comodo 209 143 3000 c r2 c r~/comodo/i
prontera 29 207 umbala 100 154 3000 c r2 c r~/umbala/i
prontera 98 120 yuno 157 167 1800 c c r0 c r~/juno/i c
geffen 120 62 prontera 116 72 1200 c r2 c r~/prontera/i
geffen 203 123 prontera 116 72 1200 c r2 c r~/prontera/i
aldebaran 143 119 geffen 120 39 2000 c r2 c r~/geffen/i
izlude 128 148 prontera 116 72 2000 c r2 c r~/prontera/i
yuno 152 187 einbroch 67 195 2000 c r2 c r~/einbroch/i
yuno 152 187 lighthalzen 159 90 2000 c r2 c r~/lighthalzen/i
yuno 152 187 hugel 98 150 2000 c r2 c r~/hugel/i
yuno 152 187 rachel 119 135 2000 c r2 c r~/rachel/i
yuno 327 108 aldebaran 168 112 2000 c r2 c r~/baran/i
yuno 142 183 prontera 116 72 1800 c c r~/prontera/i c n
morocc 156 97 prontera 116 72 2000 c r2 c r~/prontera/i
comodo 195 150 morocc 156 47 2000 c c r2 c r~/morroc/i
alberta 113 60 payon 161 58 2000 c r2 c r~/payon/i
rachel 109 138 veins 205 101 2200 c r2 c r~/veins/i
rachel 109 138 yuno 158 125 3000 c r2 c r~/yuno/i
veins 208 128 rachel 115 125 2200 c r2 c r~/rachel/i
veins 208 128 yuno 158 125 3000 c r2 c r~/yuno/i
moc_para01 14 32 prontera 116 72 1800 c c c c r0 c r~/prontera/i c n
```

**Comment by sctnightcore** [comment]
Test with it . 
https://user-images.githubusercontent.com/32188494/33023975-bdcd88ae-ce44-11e7-9444-34d0a7f05eb1.png

**Comment by fadreus** [comment]
With VIP status, now this seems to be personal issue rather than openkore issue..

**Comment by Glikadin** [comment]
Vip warp:
![vip](https://user-images.githubusercontent.com/20753532/33028709-a090680a-ce27-11e7-9945-38bee1789716.jpg)
nonVip warp:
![nonvip](https://user-images.githubusercontent.com/20753532/33028721-af8a47a4-ce27-11e7-8edc-d91fa162765a.jpg)
As you can see, Aldebaran is in different positions.

My portals.txt work correctly (after correcting errors).

**Comment by fadreus** [comment]
Leggo sleep now..
=)

**Comment by sctnightcore** [comment]
`prontera 146 89 izlude 94 103 2000 c r2 c r0`

**Comment by fadreus** [comment]
Problem solved by using ` r~/baran/i `
