### ISSUE TITLE
Server Connection Issue on idRO Renewal Server

### ISSUE THREAD

**Issue by ChocoCreme** [OpenKore/openkore#1425]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 
**Cannot connect with xkore 0, but the xkore 1 works just fine. *I am not a programmer and my knowledge in coding or script may be very limited.**
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
**The WPE shows as follow...**
![werpwer](https://user-images.githubusercontent.com/33345290/33061216-d43dda6a-cecd-11e7-8fdd-5082e84e5ef4.png)

And my server.txt is as follow...

[Indonesia - idRO: Valhalla]
ip 202.93.25.131
port 6900
master_version 28
version 2
patchserver patchragnarok.gravindo.id
patchpath /patch02
serverType idRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 144
charDeleteDateType 1

**I believe that I got the server and port right, but I think the version/master_version/encoding is(are) not correct.**

**Config.txt looks like this...**

# Please Read the Users Manual
# The Manual is located at http://wiki.openkore.com/index.php?title=Manual

######## Login options and server-specific options ########

master Indonesia - idRO: CHAOS
server 0
username 
password 
loginPinCode
char 0

# Poseidon Settings (http://wiki.openkore.com/index.php/PoseidonServer)
# They must be the same as Query Server config in Poseidon.txt
poseidonServer 127.0.0.1
poseidonPort 24390

bindIp
forceMapIP

# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore
XKore 0
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe

# XKore 2 / Proxy configuration
XKore_listenIp 127.0.0.1
XKore_listenPort 6901
XKore_publicIp 127.0.0.1
XKore_ID

# It is not advised to set secureAdminPassword if you're using Xkore 2
secureAdminPassword 1
adminPassword beawrite
callSign
commandPrefix ;
callSignGM 0
inGameAuth 0

pauseCharServer 0
pauseMapServer 0
ignoreInvalidLogin 0
secureLogin_requestCode

# Opening cash shop when connected to map server (recv/ST0)
whenInGame_requestCashPoints 0

message_length_max 80

###### Actual Behavior:
**The error shows...**

![timeout error](https://user-images.githubusercontent.com/33345290/33061426-ac35e840-cece-11e7-9d98-2d28edeee0d8.png)

**Comment by c4c1n6kr3m1** [comment]
idRO is encrypted !!!!!!

**Comment by sctnightcore** [comment]
X 1 and x3 work
