### ISSUE TITLE
Timeout on Account Server, reconnecting. (idRO)

### ISSUE THREAD

**Issue by noobie90** [OpenKore/openkore#1429]
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:
Can anyone tell me why am I always getting timeout on Account Server?
I want to check the server information like how it was explained in Faqs but I couldn't get it work. 
I'm absolutely new to openkore but i'm trying to figure out how this work.
I downloaded the latest update so I assumed all the servers information is correct?

Please help..

**Comment by sctnightcore** [comment]
idRO: RE ?

**Comment by noobie90** [comment]
idRO Renewal,

By x1 and x3 you mean the xkore version because the one I downloaded only said openkore_master.zip.
Sorry ...

**Comment by noobie90** [comment]
Still the same..

Loading plugin plugins/breakTime/breakTime.pl...
Loading plugin plugins/eventMacro/eventMacro.pl...
Loading plugin plugins/item_weight_recorder/item_weight_recorder.pl...
Loading plugin plugins/macro/macro.pl...
Loading plugin plugins/map/map.pl...
Loading plugin plugins/profiles/profiles.pl...
Loading plugin plugins/raiseSkill/raiseSkill.pl...
Loading plugin plugins/raiseStat/raiseStat.pl...
Loading plugin plugins/reconnect/reconnect.pl...

No profiles found, using standard control folder
Loading tables\item_weights.txt...
Loading control\config.txt...
Loading control\consolecolors.txt...
Loading control\mon_control.txt...
Loading control\items_control.txt...
Loading control\shop.txt...
Loading control\overallAuth.txt...
Loading control\pickupitems.txt...
Loading control\responses.txt...
Loading control\timeouts.txt...
Loading control\chat_resp.txt...
Loading control\avoid.txt...
Loading control\priority.txt...
Loading control\routeweights.txt...
Loading control\arrowcraft.txt...
Loading tables\servers.txt...
Loading tables\idRO\recvpackets.txt...
Loading tables\idRO\cities.txt...
Loading tables\commanddescriptions.txt...
Loading tables\idRO\directions.txt...
Loading tables\elements.txt...
Loading tables\emotions.txt...
Loading tables\equiptypes.txt...
Loading tables\idRO\haircolors.txt...
Loading tables\headgears.txt...
Loading tables\idRO\items.txt...
Loading tables\idRO\itemsdescriptions.txt...
Loading tables\idRO\itemslots.txt...
Loading tables\idRO\itemslotcounttable.txt...
Loading tables\itemtypes.txt...
Loading tables\idRO\resnametable.txt...
Loading tables\idRO\maps.txt...
Loading tables\monsters.txt...
Loading tables\npcs.txt...
Loading tables\packetdescriptions.txt...
Loading tables\idRO\portals.txt...
Loading tables\portalsLOS.txt...
Loading tables\idRO\sex.txt...
Loading tables\SKILL_id_handle.txt...
Loading tables\idRO\skillnametable.txt...
Loading tables\spells.txt...
Loading tables\idRO\skillsdescriptions.txt...
Loading tables\idRO\skillssp.txt...
Loading tables\STATUS_id_handle.txt...
Loading tables\STATE_id_handle.txt...
Loading tables\LOOK_id_handle.txt...
Loading tables\AILMENT_id_handle.txt...
Loading tables\MAPTYPE_id_handle.txt...
Loading tables\MAPPROPERTY_TYPE_id_handle.txt...
Loading tables\MAPPROPERTY_INFO_id_handle.txt...
Loading tables\statusnametable.txt...
Loading tables\skillsarea.txt...
Loading tables\skillsencore.txt...
Loading tables\idRO\quests.txt...
Loading tables\idRO\msgstringtable.txt...
Loading tables\hateffect_id_handle.txt...
Loading tables\hateffect_name.txt...
[eventMacro] No control/eventMacros.txt file was found. Plugin disabled.
[eventMacro] Plugin unloading
Plugin eventMacro unloaded.

Generating session Admin Password...

Checking for new portals... none found


Connecting to Account Server...
Connecting (202.93.25.131:6900)... connected
Secure Login...
Sending encoded password...
Config 'XKore' set to 1 (was 0)
Timeout on Account Server, reconnecting. Wait 37 seconds...
Connecting to Account Server...
Connecting (202.93.25.131:6900)... connected
Secure Login...
Sending encoded password...
Timeout on Account Server, reconnecting. Wait 37 seconds...
Config 'XKore' set to 3 (was 1)
Connecting to Account Server...
Connecting (202.93.25.131:6900)... connected
Secure Login...
Sending encoded password...
Relogging in 5 seconds...
Connecting to Account Server...
Connecting (202.93.25.131:6900)... connected
Secure Login...
Sending encoded password...
Timeout on Account Server, reconnecting. Wait 37 seconds...

**Comment by noobie90** [comment]
It works now..thank you so much.. :)
I'll figure out other things by myself

**Comment by sctnightcore** [comment]
@noobie90  i will close issues

**Comment by greatjr** [comment]
@sctnightcore can i use that with xKore 0 ?

but thanks its works for xKore 1..

**Comment by sctnightcore** [comment]
@greatjr  No
