### ISSUE TITLE
character can't walk into ra_san01 ( International Ragnarok Online)

### ISSUE THREAD

**Issue by hendra814** [OpenKore/openkore#143]
here my config for lock map

> lockMap ra_san01
> lockMap_x
> lockMap_y
> lockMap_randX
> lockMap_randY

route_escape_reachedNoPortal 1
route_escape_randomWalk 1
route_escape_shout
route_avoidWalls 1
route_randomWalk 1
route_randomWalk_inTown 0
route_randomWalk_maxRouteTime 75
route_maxWarpFee
route_maxNpcTries 5
route_teleport 0
route_teleport_minDistance 150
route_teleport_maxTries 8
route_teleport_notInMaps
route_step 15

and here my ss problem
![image](https://cloud.githubusercontent.com/assets/9587609/16945837/fff693f6-4dd0-11e6-867c-bc9e8cc3046d.png)

![image](https://cloud.githubusercontent.com/assets/9587609/16946009/bb060c80-4dd1-11e6-983c-c828d702cde0.png)

![image](https://cloud.githubusercontent.com/assets/9587609/16946044/dcb9a238-4dd1-11e6-973a-e6679c599717.png)

**Comment by hendra814** [comment]
Solved by Me.

add this to tables\portal.txt

> ra_temple 119 180 ra_temin 169 23
ra_temin 28 319 ra_san01 139 139

![untitled1](https://cloud.githubusercontent.com/assets/9587609/17008555/718051d2-4f1c-11e6-8deb-afaee7b872db.JPG)

**Comment by cydh** [comment]
Thank you. I never set into ra_san yet

**Comment by hendra814** [comment]
Bump.
still not update into svn.

**Comment by hendra814** [comment]
Bump again.
need Moderator or support to update this into GIT.
thanks

**Comment by sctnightcore** [comment]
go  PR . #1805

**Comment by Nipodemos** [comment]
how did you find this VEEEEEEEEERY OOOOOOOOOOOOOOOOOLLLLLLDDDDDDDD issue? hahahahah

**Comment by sctnightcore** [comment]
@Nipodemos  xD
