### ISSUE TITLE
config play dead

### ISSUE THREAD

**Issue by greatjr** [OpenKore/openkore#1431]
did you know config play dead?
if there are monsters using play dead, if no monsters i wake up..

thanks and close thread if know

**Comment by fadreus** [comment]
Use Forum
http://forums.openkore.com/

**Comment by alisonrag** [comment]
use this: 

useSelf_skill NV_TRICKDEAD {
	lvl 1	
	sp > 10	
	whenStatusInactive EFST_POSTDELAY, EFST_TRICKDEAD
	monstersCount > 1
	monsters	
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0	
	manualAI 0
}

useSelf_skill NV_TRICKDEAD {
	lvl 1	
	sp > 10
	whenStatusActive EFST_TRICKDEAD
	whenStatusInactive EFST_POSTDELAY	
	monstersCount < 1	
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	manualAI 0
}

**Comment by windhamwong** [comment]
Looks like you are playing dead and I am putting this ticket into dead.
