### ISSUE TITLE
[iRO Chaos]

### ISSUE THREAD

**Issue by userix** [OpenKore/openkore#1433]
###### Affected configuration(s)/ file(s):  Not sure which file specifically, but guessing recpackets or server related table files

xkore 0
master International - iRO: Ymir/Yggdrasil/Valkyrie
server 1

[Nov 22 00:55:23 2017.20] Disconnecting (128.241.92.130:4502)...[Nov 22 00:55:23 2017.20] disconnected
[Nov 22 00:55:23 2017.20] Error: Out of sync with server
[Nov 22 00:56:53 2017.14] Connecting to Account Server...
[Nov 22 00:56:53 2017.40] Connecting (128.241.92.162:6800)... [Nov 22 00:56:53 2017.47] connected

###### Steps to Reproduce:  Just connect like normal.

**Comment by sctnightcore** [comment]
Please use the issue template, please post infornations about the server and your configuration.


Xkore 0 ?

**Comment by sctnightcore** [comment]
@userix  Are you ok ?

**Comment by userix** [comment]
Haven't had time to download a new copy. Are there files I can just update to make work again?

**Comment by sctnightcore** [comment]
@userix  download new openkore  XD

**Comment by userix** [comment]
![sync error](https://user-images.githubusercontent.com/20689010/33342317-8d4ff91c-d436-11e7-92d2-440c5f1192f2.png)

Downloaded new opnekore, still having random sync errors.
