### ISSUE TITLE
Help with xKore

### ISSUE THREAD

**Issue by con3ras** [OpenKore/openkore#1434]
---------------------------
Error - OpenKore
---------------------------
This program has encountered an unexpected problem. This is probably because
of a recent server update, a bug in this program, or in one of the plugins.
We apologize for this problem. You may get support from IRC or the forums.

A detailed error report has been saved to errors.txt. Before posting a bug
report, please try out the SVN version first. If you are already using the SVN
version, search the forums first to see if your problem had already been solved,
or has already been reported. If you truly believe you have encountered a bug in
the program, please include the contents of the errors.txt in your bug report,
or we may not be able to help you!

The error message is:
Unable to start the X-Kore proxy (127.0.0.1:6901): IO::Socket::INET: An attempt was made to access a socket in a way forbidden by its access permissions.
Make sure no other servers are running on port 6901. at src/Network/XKoreProxy.pm line 333.
---------------------------
OK   
---------------------------

I am getting this error while I am trying to make the bot work on xkore (visual)

on the table " Server.txt " I erased all the servers i am not playing and let only the server I am playing which is running on port 6900 

******* server info *******

ip 167.114.27.73
port 6900
private 1
version 55
master_version 1
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
charBlockSize 147
addTableFolders iRO
sendCryptKeys 0x4C17382A,0x29961E4F,0x7ED174C9

*******************

****config info****

# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore
XKore 3
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName LithiumRO.exe

# XKore 2 / Proxy configuration
XKore_listenIp 127.0.0.1
XKore_listenPort 6901
XKore_publicIp 127.0.0.1
XKore_ID
*****

![image](https://user-images.githubusercontent.com/33917416/33156791-794e1992-cfd3-11e7-98c9-7f6f371246bf.png)

**Comment by boyamiexcited** [comment]
xkore is probably running on a different port, other than 6901. if you can trace where exactly it runs, then you can update config

**Comment by c4c1n6kr3m1** [comment]
forbidden by its access permissions

your computer problem

**Comment by boyamiexcited** [comment]
I agree

**Comment by con3ras** [comment]
How do I fix it? as I can understand my computer is using the port 6901. should I change my pc port? if so, how can I do it ?

**Comment by con3ras** [comment]
Bump

**Comment by alisonrag** [comment]
Solved?

**Comment by con3ras** [comment]
Not really alisonrag, if someone could help, please

**Comment by noobie90** [comment]
Have you tried using xkore1 ? I get this error too when I used Xkore3

**Comment by masue** [comment]
my xkore 3 want connect map server

**Comment by sctnightcore** [comment]
Use with xkore 0 is ok !

**Comment by con3ras** [comment]
Can xkore bypass Gepard?

**Comment by sctnightcore** [comment]
@con3ras  idk

**Comment by Sabog29** [comment]
hi im not really got at this but can someone help me how to fix this.
 xkore 1
![shitttttttttt](https://user-images.githubusercontent.com/24473006/33536359-8c2cb7e2-d8ef-11e7-9ffe-d10f36fc1eed.png)

**Comment by fadreus** [comment]
@Sabog29  put timeout on ur macro

**Comment by casualmind** [comment]
@sabog29 trying use xkore 3 then. And don't forget to put timeout on ur marco like fadreus said before.
