### ISSUE TITLE
Does anybody has a good copy of hooktest.dll? It's not anywhere I can find in any openkore folders. Please send me a link. thank you!

### ISSUE THREAD

**Issue by boyamiexcited** [OpenKore/openkore#1436]
I'm trying to configure xkore for another server but I dont have hooktest.dll to bind in my audioses.dll. please send me a copy by posting the link here. thank you!

**Comment by fadreus** [comment]
[hooktest.zip](https://github.com/OpenKore/openkore/files/1499028/hooktest.zip)

**Comment by windhamwong** [comment]
they are both not part of our official repo. Are you referring to something else?

**Comment by fadreus** [comment]
Trying [this](https://github.com/mrpond/ROEXEOpenkore) for PhRO I guess..
