### ISSUE TITLE
how can add card alert Openkore

### ISSUE THREAD

**Issue by Gulxx** [OpenKore/openkore#1437]
how can add card alert Openkore??

Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by Glikadin** [comment]
Add **CardAlert.wav** in  **...\sounds\**
and try this macros:
```
automacro CardAlert {
console /Item added (.*) Card/i
timeout 120
	call {
		do eval Utils::Win32::playSound('sounds\CardAlert.wav');
		log =====
		log Bot Take a Card! Congrats!
		log =====
		stop
	}
}
```

if you need a specific card:
`console /Item added (.*) Poring Card/i`
If you need several specific cards:
`console /Item added (.*) (Poring|Lunatic|Pupa) Card/i`

Such questions should be asked at the forum: http://forums.openkore.com

**Comment by Gulxx** [comment]
thank you
