### ISSUE TITLE
wrong message from msgstringtable

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [OpenKore/openkore#144]
( i've downloaded from this site at 15th july , winrar shown 83ffc20bed0aaa85d9f6e4ea0103851005935447 )

i try double cast teleport using "ss 26 1"
the message shown wrong line

iro chaos shown "Security Level" (number 1928)
idro shown "Silahkan kamu keluarkan dari grup dan guild terlebih dulu untuk menghapus karakter ini" (number 1929)

it should show number 1924 ""any work in progress (NPC dialog, manufacturing...)quit and try again."
while my old 1.5 year openkore show correct message

i checked the array $msgTable[1924] , it is wrong recorded
problem with fileparsing ? textreader?
Can someone clarify this ? 

and weird delay before showing character list
after received the data, i feel more than 5 second pause before character list shown, why is that ?

**Comment by cydh** [comment]
I wonder if the fault is in OpenKore code.
I use same msgstringtable.txt file for my idRO bot (from idRO data.grf that I PR'd in #94), my old OK show message correctly.
My old OK
![screenshot_45](https://cloud.githubusercontent.com/assets/4016864/16971364/516353ec-4e4d-11e6-8bf9-1f62778d715f.png)
OK on a6ecb1c79fff2bac77c97925c2bae44b60d2cd2f
![screenshot_46](https://cloud.githubusercontent.com/assets/4016864/16971393/8b9aea70-4e4d-11e6-8760-226f6dbb2cab.png)

**Comment by c4c1n6kr3m1** [comment]
@cydh , so u choose to adjust msgstringtable.txt ? it's a partial solution

after read your solution, i checked Fileparsers.pm
but "sub parseArrayFile" is not changed
so the problem must be the new Utils::TextReader
after read TextReader i found 


> $self->{hide_comments} = defined $options->{hide_comments} ? $options->{hide_comments} : 1;



it will make all comment not record by default
i choose to edit this line, because TextReader is used Frequently 

and what about the delay before Received characters list ? i can't find the problem
i don't need this delay

**Comment by cydh** [comment]
> @cydh , so u choose to adjust msgstringtable.txt ? it's a partial solution

just for now, and yet I have a little work around to pass the `hide_comments` option for msgstringtable.txt since the issue may not only occurs for idRO.
