### ISSUE TITLE
Edit qw Sakexe_2004_07_05a to ServerType0

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1444]
###### Summary:
```
package Network::Receive::kRO::Sakexe_2004_07_05a;
use base qw(Network::Receive::ServerType0);
```
```
package Network::Send::kRO::Sakexe_2004_07_05a;
use base qw(Network::Send::ServerType0);
```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Benefits:
**You do not need to add in recv section, but sT you just add in servertybe0 it just works.**
###### Additional Details:
I think we should include sakexe_0 with servertybe0.
I do not have much time to edit the recv in sT.
PR : #1454

**Comment by c4c1n6kr3m1** [comment]
as far as i remember, similar suggestion was rejected before

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1 
I think it would be good for sT2015 +

**Comment by moneyisgod** [comment]
What it implies? do u noted that sakexe is diff from ragexe?

**Comment by sctnightcore** [comment]
It is not very different. But better than we would include sakexe_0 with servertybe0. @moneyisgod

**Comment by lututui** [comment]
I strongly oppose this

**Comment by sctnightcore** [comment]
Whyyy ? @lututui
