### ISSUE TITLE
 WireShark FAQ in openkore wiki

### ISSUE THREAD

**Issue by hougochia** [OpenKore/openkore#1446]
Summary: WireShark FAQ need to be updated follow the current version of wireshark or provide same version of wireshark following the picture FAQ

The 4 , 6 , 10 , 11 is not compatible to new version of wireshark , hex dump function is not available following picture and i cant find the hex dump anywhere in the wireshark , currently using stable version v 2.2.10

**Comment by rainsom** [comment]
Although is not same version but the function is there. The new version of Wireshark is still working fine, you can hook the server information that you want.

**Comment by hougochia** [comment]
yeah found it at bottom anyhow , automatic hex generate
