### ISSUE TITLE
Siege Teleport Scroll support

### ISSUE THREAD

**Issue by Al3xandrad3** [OpenKore/openkore#1447]
The openkore not supported Siege Teleport Scroll?
I use this item nothing happens any idea how I can fix this?

@PT-BR
O openkore não tem suporte para os pergaminhos de feudo?
Quando uso o item não consigo usar o teleporte, alguma ideia de como posso resolver esse problema?
![sem titulo](https://user-images.githubusercontent.com/34034450/33274529-77c456fc-d377-11e7-9b03-b389e7753b6f.png)

**Comment by alisonrag** [comment]
I dont know why but it was working before
Maybe in talknpc the kore remove the conversation because dont know from where this conversation is coming

**Comment by alisonrag** [comment]
fixed in #1604
