### ISSUE TITLE
Help with xkore PacketParse Build

### ISSUE THREAD

**Issue by stancesvince** [OpenKore/openkore#1450]
hello, i can connect xkore with editing packetparser.pm method

like this 
Closing connection to Account Server
Disconnecting (128.241.92.162:6800)...disconnected
Connecting to Character Server...
Selected server: CHAOS
Connecting (202.93.25.70:6000)... connected
char sex : 1fError logging into Character Server (invalid character specified)...
Disconnecting (202.93.25.70:6000)...disconnected
Connecting to Account Server...
Connecting (128.241.92.162:6800)... connected
rebuilding packet here ..
rebuilding packet here ..
---------- Account Info ----------
Account ID: 187124 F4 DA 02 00
Sex: Boy
Session ID: 17959 27 46 00 00
0 00 00 00 00

i'm put manualy season id when i got from WPE to folder src>network>packetparser.pm then i can connect, my question is how what i do to make session id auto generate if i got disconected or auto input session id?

**Comment by alisonrag** [comment]
server?

**Comment by hideman012** [comment]
Sorry dev alisonrag need you help for mro too

**Comment by stancesvince** [comment]
idRO Server, i'm already read thread about idRO but i got nothing..

thx for help!

**Comment by sctnightcore** [comment]
@hideman012  go to #1445

**Comment by stancesvince** [comment]
here my config:

>sub parse {
	my ($self, $msg, $handleContainer, @handleArguments) = @_;

	$lastSwitch = Network::MessageTokenizer::getMessageID($msg);
    if($config{x1}eq't1')
	{
		$lastSwitch = "01DC";
		$config{x1} = 't2';
	}
    if($lastSwitch eq "01DC")
    {
          warning "rebuilding packet here ..\n", "packetParser" ,0;
          $lastSwitch = "0069";
          $msg = "";
          $msg.=chr(hex("69"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("4F"));
          $msg.=chr(hex("00"));
		  
          $msg.=chr(hex("yy")); #session id
          $msg.=chr(hex("yy")); #session id
		  
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
		  
          $msg.=chr(hex("xx")); #id
          $msg.=chr(hex("xx")); #id
          $msg.=chr(hex("xx")); #id
		  
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
		  
          $msg.=chr(hex("32"));
          $msg.=chr(hex("fa"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("02"));
          $msg.=chr(hex("00"));
		  
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          
          
          $msg.=chr(hex("e8"));
          $msg.=chr(hex("1f"));
          $msg.=chr(hex("9f"));
          $msg.=chr(hex("0e"));
          $msg.=chr(hex("84"));
          $msg.=chr(hex("f8"));
          $msg.=chr(hex("b2"));
          $msg.=chr(hex("18"));
          
           $msg.=chr(hex("13"));
          $msg.=chr(hex("bd"));
          $msg.=chr(hex("2a"));
          $msg.=chr(hex("77"));
          $msg.=chr(hex("e8"));
          $msg.=chr(hex("1f"));
          $msg.=chr(hex("9f"));
          $msg.=chr(hex("0e"));
          
           $msg.=chr(hex("e0"));
          $msg.=chr(hex("1f"));
          $msg.=chr(hex("9f"));
          $msg.=chr(hex("0e"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00")); #sex 
          $msg.=chr(hex("CA"));
          
           $msg.=chr(hex("5D"));
          $msg.=chr(hex("19"));
          $msg.=chr(hex("46"));
          $msg.=chr(hex("70"));
          $msg.=chr(hex("17"));
          $msg.=chr(hex("54"));
          $msg.=chr(hex("68"));
          $msg.=chr(hex("6f"));
          
           $msg.=chr(hex("72"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          
           $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          
           $msg.=chr(hex("00"));
          $msg.=chr(hex("50"));
          $msg.=chr(hex("14"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
          $msg.=chr(hex("00"));
		  
    }   
    
	my $handler = $self->{packet_list}{$lastSwitch};

	unless ($handler) {
		warning "Packet Parser: Unknown switch: $lastSwitch\n";
		return undef;
	}

<

i'm manualy change session id "yy" after disconnected i got it from WPE then how to make session ID automatically then if i'm going to school and bot stuck or disconected openkore try auto generate session id.

sry for my rip grammar really i need your help i'm already stuck 4 month, when i saw nothing people ask about idRO again then i'm make this trhead thx asap

**Comment by sctnightcore** [comment]
idRO RE ? @stancesvince

**Comment by stancesvince** [comment]
idRO gravindo server thor

i dont know what you meant about "RE"

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/blob/6ddfaf6bede31c3116e062aba1a5a529e7625346/tables/servers.txt#L67-L83
This server is right?

**Comment by stancesvince** [comment]
@sctnightcore 

sriously i'm used xkore 0 but i'm moddified folder src>network>packetparser.pm

then i change sub parser at packetparser.pm like my code before finnaly i can login but i must do it mannualy find session id with WPE then put it on to packetparser.pm every time i got disconnected

**Comment by sctnightcore** [comment]
Idro classic ? 
Now openkore dont work on it . GG

**Comment by stancesvince** [comment]
here the website : https://ragnarok.gravindo.id/home

i'm plaaying classic server is a thor

**Comment by stancesvince** [comment]
i can make it work i'm disabled client security then use WPE for find my session id when i logged in client game then i put it on openkore

**Comment by sctnightcore** [comment]
Now openkore work only server idRO : Midgard,Asgard ,Valhalla with xkore1,xkore 3

**Comment by stancesvince** [comment]
can you trust me? i'm make it work on thor server but its manually input session id every times disconnected 

can you see my dekstop pc with remote dekstop or etc.. i will show you how its worked on thor server

**Comment by sctnightcore** [comment]
No, I'll update if I can.
I have tested it. In the same way you can not connect to map.

**Comment by stancesvince** [comment]
i can connect to map

but my prob if i got unstable connection on my ISP(internet Server Provider) openkore will be discconected and i'm must do mannualy find session id again with WPE to reconnected again...!!!

**Comment by sctnightcore** [comment]
test with xkore 3 ? @stancesvince

**Comment by stancesvince** [comment]
xkore3,2,1 cant working with my code

**Comment by stancesvince** [comment]
can you give your mail to me i will send myopenkore and video tutorial how its work!

**Comment by c4c1n6kr3m1** [comment]
@stancesvince
session ID is server side , create by server, not bot
there's nothing you can do
@sctnightcore , close this issue

**Comment by Youtouchmytralala** [comment]
c4c1n6kr3m1, why you want so much to close it? As it seems it doesnt resolved.

**Comment by ts196644** [comment]
any ip or port can use for sgmy server? plz
