### ISSUE TITLE
idRo Renewal, openkore multiple logins.

### ISSUE THREAD

**Issue by casualmind** [OpenKore/openkore#1455]
Hello there.

I was trying to login with multiple openkore but it didn't work in idRo Renewal. 

I want to ask to who can fixed this thing, I tried almost three days and yeah still get failed so any tips or guides for running multiple bots or multiple openkore on server idRo renewal?

Thank you.

**Comment by sctnightcore** [comment]
use with xkore3 !!!!!!

**Comment by casualmind** [comment]
@sctnightcore yeah i tried it using xkore3, but I see the notice connectiong failed didnt respond etc.

One thing, if I only using xkore 1 it's work but just for running one openkore.

**Comment by sctnightcore** [comment]
http://forums.openkore.com/viewtopic.php?f=28&t=7555 ? 

xkore 1 ? 

I think xkore3 is best for me.

**Comment by casualmind** [comment]
@sctnightcore I'll try that methods soon.

Here I tried again to using xkore3 and there's the problem...

`Waiting Ragnarok Client to connect on (localhost:6901)
Proxying to [Indonesia - idRO: Midgard,Asgard ,Valhalla]
Connecting (192.168.43.167:63263)... couldn't connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (error code 10060)
Invalid server specified or server does not exist...`

What's wrong with that? I also edited the config.txt to..

`# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore
XKore 3
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe

# XKore 2 / Proxy configuration
XKore_listenIp 127.0.0.1
XKore_listenPort 6901
XKore_publicIp 127.0.0.1
XKore_ID

# It is not advised to set secureAdminPassword if you're using Xkore 2
secureAdminPassword 0
adminPassword santonigitulho
callSign
commandPrefix ;
callSignGM 0
inGameAuth 1`

and I was put the client.xml to data.grf. I don't have any idea where's the problem, I didn't found it.

**Comment by sctnightcore** [comment]
data.grf > clientinfo.xml > ip > 127.0.0.1 port 6901

**Comment by casualmind** [comment]
@sctnightcore yeah I was edited that bro. Still the same

**Comment by sctnightcore** [comment]
LOL @casualmind  
dont add Openkore Proxy

edit in **Indonesia Server**

```
<connection>
	<display>Indonesia Server</display>
	<desc>None</desc>
	<address>127.0.0.1</address>
	<port>6901</port>
	<version>2</version>
	<langtype>6</langtype>
	<registrationweb>http://www.gravindo.id</registrationweb>
	<aid>
		<admin>100004</admin><admin>100005</admin><admin>100045</admin><admin>100046</admin><admin>100047</admin><admin>100048</admin><admin>100049</admin><admin>100050</admin><admin>100051</admin>
		<admin>100052</admin><admin>100053</admin><admin>100054</admin><admin>100055</admin><admin>100056</admin><admin>100057</admin><admin>100058</admin><admin>100059</admin><admin>100060</admin>
		<admin>100061</admin><admin>100062</admin>
	</aid>
</connection>

<loading>
	<image>loading00.jpg</image>
	<image>loading01.jpg</image>
	<image>loading02.jpg</image>
	<image>loading03.jpg</image>
	<image>loading04.jpg</image>
	<image>loading05.jpg</image>
</loading>
```

**Comment by casualmind** [comment]
@sctnightcore still didn't work it well.

**Comment by sctnightcore** [comment]
@casualmind  I just got a new os yesterday. I do not have a client idRO_RE.
T.T

**Comment by alisonrag** [comment]
use multiple port

**Comment by alisonrag** [comment]
<servicetype>indonesia</servicetype>
<servertype>primary</servertype>

<passwordencrypt></passwordencrypt>
<extendedslot></extendedslot>
<connection>
	<display>Openkore Proxy</display>
	<desc>AREUAN</desc>
	<address>127.0.0.1</address>
	<port>6901</port>
	<version>2</version>
	<language>6</language>
</connection>
<connection>
	<display>Openkore 1</display>
	<desc>AREUAN 2</desc>
	<address>127.0.0.1</address>
	<port>6902</port>
	<version>2</version>
	<language>6</language>
</connection>
<connection>
	<display>Openkore Proxy</display>
	<desc>AREUAN 3</desc>
	<address>127.0.0.1</address>
	<port>6903</port>
	<version>2</version>
	<language>6</language>
</connection>

<connection>
	<display>Indonesia Server</display>
	<desc>None</desc>
	<address>202.93.25.131</address>
	<port>6900</port>
	<version>2</version>
	<langtype>6</langtype>
	<registrationweb>http://www.gravindo.id</registrationweb>
	<aid>
		<admin>100004</admin><admin>100005</admin><admin>100045</admin><admin>100046</admin><admin>100047</admin><admin>100048</admin><admin>100049</admin><admin>100050</admin><admin>100051</admin>
		<admin>100052</admin><admin>100053</admin><admin>100054</admin><admin>100055</admin><admin>100056</admin><admin>100057</admin><admin>100058</admin><admin>100059</admin><admin>100060</admin>
		<admin>100061</admin><admin>100062</admin>
	</aid>
</connection>

<loading>
	<image>loading00.jpg</image>
	<image>loading01.jpg</image>
	<image>loading02.jpg</image>
	<image>loading03.jpg</image>
	<image>loading04.jpg</image>
	<image>loading05.jpg</image>
</loading>

**Comment by alisonrag** [comment]
config.txt
XKore 3

and
first bot
XKore_listenPort 6901

second
XKore_listenPort 6902

third
XKore_listenPort 6903

**Comment by casualmind** [comment]
@alisonrag yeah I know that. But the problem is I cant reach the server. 

> Waiting Ragnarok Client to connect on (localhost:6901)
Proxying to [Indonesia - idRO: Midgard,Asgard ,Valhalla]
Connecting (192.168.43.167:63263)... couldn't connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (error code 10060)
Invalid server specified or server does not exist...

**Comment by sctnightcore** [comment]
192.168.43.167  LOL

**Comment by casualmind** [comment]
@sctnightcore I got that IP from WPE, because in XKore1 it's work.

**Comment by sctnightcore** [comment]
192.168.43.167 is **you ip**
You do not have to edit server.txt.

**Comment by casualmind** [comment]
@sctnightcore here my servers.txt I didn't edit this

> [Indonesia - idRO: Midgard,Asgard ,Valhalla]
ip 192.168.43.167
port 63263
master_version 0
version 1
patchserver wpatch.ragnarok.co.id
patchpath /patch02
serverType idRO
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 144
charDeleteDateType 1

**Comment by sctnightcore** [comment]
**fix** 
https://github.com/OpenKore/openkore/blob/3743bb5a772b9a2d9fe4012588119f6433a15583/tables/servers.txt#L67-L83
**If you want to use xkore 3 you do not need to edit server.txt.
Edit just clientinfo.xml**

**Comment by casualmind** [comment]
@sctnightcore omg it's work! Thanks mate! Now, I wanna ask to run many bots with xkore3. Due idRO can't dual login client.

**Comment by sctnightcore** [comment]
@casualmind  ok i will close issues

**Comment by casualmind** [comment]
Wait @sctnightcore now about run many bots. How can I do? Since idRO can't dual login client ragnarok.exe anymore.

**Comment by sctnightcore** [comment]
idk XD @casualmind

**Comment by casualmind** [comment]
@sctnightcore aaaah, alright then xD thanks btw!

**Comment by fadreus** [comment]
Try with sandboxie or VM XD

**Comment by m0m0n** [comment]
@sctnightcore cant login

[https://ibb.co/fFpQ2R](url)

> Menunggu Ragnarok Client untuk connect ke (localhost:6901)
Melakukan Proxy ke [Indonesia - idRO: Midgard,Asgard ,Valhalla]
Koneksi terhubung (202.93.25.131:6900)... Telah connect
---------- Account Info ----------
Account ID: 247084     2C C5 03 00
Sex:        Laki-Laki
Session ID: 23679      7F 5C 00 00
            0          00 00 00 00

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Valhalla (New)        2144   202.93.25.228   6000
1   Asgard                54     202.93.25.196   6000
2   Midgard               252    202.93.25.133   6000
-----------------------------------------------------
Mengakhiri koneksi ke Account server
Mengakhiri koneksi (202.93.25.131:6900)...Telah disconnect

**Comment by saitamax1** [comment]
hello i wanna ask about my openkore for IdRo Renewal. I can't login. when i start and choose server and then my id and pass it goes like this : 
Connecting to Account Server...
Connecting (202.93.25.131:6900)... connected
Secure Login...
Sending encoded password...
Timeout on Account Server, reconnecting. Wait 42 seconds...
Connecting to Account Server...
[reconnect] Login retry number 2, setting reconnect timeout to 62 seconds.
Connecting (202.93.25.131:6900)... connected
Secure Login...
Sending encoded password...
Timeout on Account Server, reconnecting. Wait 62 seconds...
Connecting to Account Server...
always like this, do you know how to fix this ?
Thanks
