### ISSUE TITLE
Eventmacro BaseLevel and JobLevel not working on iRO:Restart

### ISSUE THREAD

**Issue by CaioVictor21** [OpenKore/openkore#1458]
## ------------------ Bug Report Template ------------------
**###### Summary:** 

eventMacro.txt
```
automacro BaseLevel {
	BaseLevel = 1
	BaseLevel > 1
	BaseLevel < 1
	call {
		do move 52 113
	}
}
```

Console response to the comand   **eventMacro auto BaseLevel**:

```
----  Conditions   ----
1 - BaseLevel: 'false'
2 - BaseLevel: 'false'
3 - BaseLevel: 'false'
```

Same to JobLevel ...

**###### Affected configuration(s)/ file(s):**
EventMacro plugin, BaseLevel.pm,JobLevel.pm

**###### Impact:**

automacro  with this conditions will never trigger

**###### Expected Behavior:**

automacro  conditions return TRUE after reach determined level

**###### Actual Behavior:**

The conditions always returns FALSE, regardless of the baselevel or joblevel of the char

**###### Steps to Reproduce:**
Create a automacro with this conditions on iRO:RE

**Comment by sctnightcore** [comment]
Do move mapname x y?

**Comment by Nipodemos** [comment]
@Henrybk 
check your son please, it is getting rebellious

**Comment by lututui** [comment]
Couldn't reproduce

![2018-01-27_12h52_04](https://user-images.githubusercontent.com/17522256/35473038-0369b60c-0361-11e8-9044-a90749146c27.png)
![2018-01-27_12h52_44](https://user-images.githubusercontent.com/17522256/35473039-04866f6c-0361-11e8-886e-2c4b01360f10.png)
