### ISSUE TITLE
RE:Start   Timeout on Map Server, connecting to Account Server...

### ISSUE THREAD

**Issue by KMR78977** [OpenKore/openkore#1460]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by KMR78977** [comment]
restaet 
Timeout on Map Server, connecting to Account Server...

**Comment by sctnightcore** [comment]
Server update ?

**Comment by Glikadin** [comment]
This happened after the maintenance and server update.

**Comment by sctnightcore** [comment]
@Glikadin  You can zip Ragexe.exe to me ?

**Comment by makana21** [comment]
[Ragexe.zip](https://github.com/OpenKore/openkore/files/1516298/Ragexe.zip)

**Comment by sctnightcore** [comment]
8924eb1
**download new openkore and test again .**

**Comment by 0Noro** [comment]
@sctnightcore 
Now It's working
