### ISSUE TITLE
iRoTimeout on map server

### ISSUE THREAD

**Issue by bunnyy00** [OpenKore/openkore#1464]
As title, couldn't coonect to iRo due to Timeout on Account Server, reconnecting. Wait 30 seconds...
iRo CHAOS server

MAP IP: 128.241.92.130
MAP 端口: 4505
-----------------------------
断开和人物服务器的连接
断开连接 (128.241.92.130:4500)...中断
连接到地图服务器...
连接 (128.241.92.130:4505)... 连接完成
连接地图服务器超时, 重新连接到人物服务器...
连接到帐号服务器...
连接 (128.241.92.162:6800)... 连接完成
Timeout on Account Server, reconnecting. Wait 30 seconds...

**Comment by fadreus** [comment]
Wait PR merge, then download new.

**Comment by ulysis05** [comment]
same issue, can u update me pls uly.adlao@gmail.com thank u very much

**Comment by jomarlorica** [comment]
hi @allanon  can you merge it to the openkore there in github? thanks.

**Comment by plokislokis** [comment]
my openkore was able to connect ingame but getting an error "Stuck during route" and bot doesn't move

**Comment by ulysis05** [comment]
it's working now, thanks to lututui! at to all :)

**Comment by jeffkewjk** [comment]
how did u make it work ulysis05?

**Comment by sctnightcore** [comment]
Download new openkore is work ! .

**Comment by ulysis05** [comment]
download new openkore, thanks to all awesome contributor! :D

**Comment by ulysis05** [comment]
i wish someone can do a bot for pRO (Philippines Ragnarok) https://www.ragnarokonline.com.ph/

**Comment by sctnightcore** [comment]
@ulysis05  No someone can do it . !!!!
