### ISSUE TITLE
Attackauto_party (master/Slave) issues

### ISSUE THREAD

**Issue by vhonn** [OpenKore/openkore#1465]
as the subject implies, the issue starts on master attacking mobs and right after ignores the slave being mobbed beside it, the master then continues to search mobs completely ignoring the slave being hit by another mobs. Reason? Tried running AI manual to test whats the reason for this, found out that it doesn't want to hit the mobs engage by party because it wasn't allowed to killsteal. I find it weird since master/slave is always a party thing hence shouldn't be kill stealing.

.Run on WXStart
config settings:
xkore 0

attackauto 1
attackauto_party 1

**Comment by supermankesasar** [comment]
this is a party bug ( maybe ) , i dont realy sure.
but i have the same problem like this,
simple answer, create a new party.

**Comment by lututui** [comment]
http://openkore.com/index.php/AttackAuto_party

If your slave doesn't attack the mob, a master with attackAuto_party 1 won't help the slave.

Use attackAuto_party 2

**Comment by vhonn** [comment]
same thing nether 1 or 2 works with master not helping the slave just like the master ignoring all the mobs on slave hitting it, reason console shows it wont kill steal even it is on the same party.

**Comment by alisonrag** [comment]
fixed in 
https://github.com/OpenKore/openkore/commit/996f78bdb66a7a843c256957ea52243da305a235
