### ISSUE TITLE
iRO Renewal disconnected cant connect. i need help how to fix tables folder can anyone help me 

### ISSUE THREAD

**Issue by jomarlorica** [OpenKore/openkore#1466]
Hello. i need help how to fix tables folder can anyone help me. i dont know how the patch_iro.pl put it in a tables folder where to put etc. @allanon can you help me pls? hehe thanks in advance.

**Comment by sctnightcore** [comment]
Download new openkore !!!!! ..

IT WORKKKK!!!!!

**Comment by jomarlorica** [comment]
ih @sctnightcore it didnt. on renewal. i downloaded thrice. but my bot cant connect

**Comment by jomarlorica** [comment]
![image](https://user-images.githubusercontent.com/32188407/33483484-0f577f9e-d6d9-11e7-8614-22b26896ba2f.png)

**Comment by jomarlorica** [comment]
i tried many times T_T

**Comment by jomarlorica** [comment]
its working now. thanks
