### ISSUE TITLE
PacketParser unknown switch for RagexeRE_2015_11_04a

### ISSUE THREAD

**Issue by smallvill3** [OpenKore/openkore#1469]
![capture](https://user-images.githubusercontent.com/26625329/33512288-3b7ded12-d768-11e7-9f8f-b634c153c9f6.JPG)

Openkore version ctime:2017_12_01
serverType kRO_RagexeRE_2015_11_04a
Server tested: GGamerzRO http://gombak-gamerz.com/

- [098A]  Clan System? (not yet support)
- [0988]  Clan System? (not yet support)
- [097A] quest_all_list2 (already have at ServerType0.pm)
- [0A24] achievement_update (already have at ServerType0.pm)
- [0A23] achievement_list (already have at ServerType0.pm)
- [09E7] unread_rodex (already have at ServerType0.pm)

As you can see, packet 097A, 0A24, 0A23, 09E7 already implemented at ServerType0.
I can manually add those line code to be able to fix this, but how can we implement this properly?

**Comment by sctnightcore** [comment]
Clan System 
```
[098A] Clan System? (not yet support)
[0988] Clan System? (not yet support)
```
openkore dont support clansystem.
if you can do it . you can PR .

**Comment by smallvill3** [comment]
Ill just wait for the PR than.
Hope that gets cleanup.

**Comment by sctnightcore** [comment]
I'm still lazy.
Wait XD

**Comment by jeffkewjk** [comment]
im having the same problem. unknown status 993 994

**Comment by sctnightcore** [comment]
@jeffkewjk  iRO restart ?

**Comment by smallvill3** [comment]
![capture](https://user-images.githubusercontent.com/26625329/33527162-c9ddd40e-d886-11e7-9f11-e127a9fa5a32.JPG)

And this one 0A27, already have at servertype0.pm

**Comment by sctnightcore** [comment]
`'0A27' => ['hp_sp_changed', 'vV', [qw(type amount)]],`

@smallvill3
