### ISSUE TITLE
How to setting autofeed pet ???

### ISSUE THREAD

**Issue by fikriaulia13** [OpenKore/openkore#1471]
Anyone knows how to config the bot to autofeed the pet ?
Thanks before

**Comment by lututui** [comment]
http://openkore.com/index.php/Pet_hunger
http://openkore.com/index.php/Pet_autoFeed

**Comment by fikriaulia13** [comment]
excuse me sir
ive already did that thing
but my bot did feed the pet
why

2017-12-03 2:46 GMT+07:00 lututui <notifications@github.com>:

**Comment by alisonrag** [comment]
@lututui 
maybe can be a problem.

this pull can fix this:
#1345

**Comment by fikriaulia13** [comment]
its work now sir, thank you very much

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-03 23:16 GMT+07:00 Alison Serafim <notifications@github.com>:

**Comment by Fadreus** [comment]
This is fixed, can be closed?

**Comment by Fadreus** [comment]
Fixed & Too old 2017..
Can close?

**Comment by fikriaulia13** [comment]
sure sir....

Pada tanggal Min, 29 Sep 2019 pukul 01.58 チビすけ <notifications@github.com>
menulis:

**Comment by Fadreus** [comment]
Fixed & Too old 2017..
Didn't see any problem anymore..
Can close?

**Comment by Nipodemos** [comment]
i agree
closing since it's already fixed
