### ISSUE TITLE
sending encoded password

### ISSUE THREAD

**Issue by pamungkas95** [OpenKore/openkore#1472]
can someone help?
idRO
![snapshot_2017-12-3_20-47-24](https://user-images.githubusercontent.com/34211741/33525937-3d6ddc6e-d86b-11e7-9b67-374fb381e5e5.jpg)

**Comment by sctnightcore** [comment]
idRO_Re ?

**Comment by pamungkas95** [comment]
renewal valhalla

**Comment by sctnightcore** [comment]
@pamungkas95  use with xkore 1 ,xkore 3 
work !

**Comment by pamungkas95** [comment]
how?
sorry, im newbie

**Comment by sctnightcore** [comment]
config.txt
Xkore 0 > 1

1.open client 
2.runadmin openkore 
3.login game

**Comment by pamungkas95** [comment]
thanks, it work!
