### ISSUE TITLE
How to find call pattern 1 , 2

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1477]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

## ------------------ My problem Template ------------------
How to find   call pattern 1 , 2 ? 

https://github.com/OpenKore/packetExtractor/blob/b63edc93856d7249b7493f2824546359b32426df/packet-extractor/Source.cpp#L142-L152

I'm trying to fix it to work for **kRO,Pserver**.

**client** : http://herc.ws/board/topic/15348-kro-unpacked-clients-releases/

**Comment by pandakidx** [comment]
the issue is , I'm playing the new ragnarok online MYSG , copy the server ip and stuff , can login , just stuck at the 
Timeout on Account Server
pls help

**Comment by moneyisgod** [comment]
Looks like the packet data is encrypted using rijndael. And then we can see a lot of thing that i dont understand.
