### ISSUE TITLE
party issues - IRO Renewal

### ISSUE THREAD

**Issue by masue** [OpenKore/openkore#1478]
![untitled](https://user-images.githubusercontent.com/26917660/33603155-348f9234-d9e4-11e7-9d0e-c897a3d216b7.png)

I use latest version, i tried to create party and share exp. but party function is not working.
Hope this issue will be fixed 
TY :D

**Comment by sctnightcore** [comment]
latest version ? 

Download new again . !

**Comment by masue** [comment]
solved
i download again, maybe something missing in may openkore
TY :D
