### ISSUE TITLE
Status_id_handle for Weapon Blocking

### ISSUE THREAD

**Issue by noobie90** [OpenKore/openkore#1480]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 
AI won't use Counter Slash after Weapon Blocking was activated
###### Affected configuration(s)/ file(s):
useSelf_skill GC_COUNTERSLASH {
	lvl
	maxCastTime 0
	minCastTime 0
	hp
	sp > 200
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	maxUses 1
	whenStatusActive EFST_WEAPONBLOCKING_POSTDELAY
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 1
	notWhileSitting 1
	notInTown 1
	timeout 0
	disabled 0
	inInventory
	manualAI 0
}
###### Expected Behavior:
AI use Counter Slash when Weapon Blocking Activated

**Comment by fadreus** [comment]
Tried with combo block?

**Comment by noobie90** [comment]
Tried with combo block too, nothing happened.
Can anyone help?

**Comment by alisonrag** [comment]
when skill is triggered server dont send any status you can try this:

http://openkorebrasil.org/index.php?/topic/4737-sic%C3%A1rio-trigar-retalia%C3%A7%C3%A3o-gc-counterslash/
```
attackComboSlot 2029 {
	lvl 5
	afterSkill Weapon_Blocking
	waitBeforeUse 0.5
	sp > 10%
	inLockOnly 1
	aggressives 1 
	disabled 0
}
```
