### ISSUE TITLE
xkore 1 keeps failing after sometimes.

### ISSUE THREAD

**Issue by balasubas13** [OpenKore/openkore#1483]
please help. 
done #1374  fixed but same result. disconnected after 5-15mins and failed to cast skills/use item buffs

**Comment by sctnightcore** [comment]
server ?

**Comment by balasubas13** [comment]
iro renewal.

**Comment by sctnightcore** [comment]
@balasubas13  xkore 3

**Comment by balasubas13** [comment]
same results. help please. thanks

**Comment by balasubas13** [comment]
please help still getting the same issues after maintenance.aathanks

**Comment by sctnightcore** [comment]
use with new openkore work with xkore  1 2 3

**Comment by balasubas13** [comment]
thanks. done downloading new kore. 
its working.. but after sometimes it show unable to move and get disconnected or failed to cast skill continuously and then get diaconnected..

**Comment by sctnightcore** [comment]
@balasubas13  use with xkore 3 XD
