### ISSUE TITLE
RE:Start - After server maintenance - Timeout on Map Server, connecting to Account Server...

### ISSUE THREAD

**Issue by 0Noro** [OpenKore/openkore#1484]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:
[Ragexe.zip](https://github.com/OpenKore/openkore/files/1537551/Ragexe.zip)

**Comment by Pachu1985** [comment]
you will have to wait for someone to update the packets after the maintenance.

is there any noob friendly guide to do this? i have free time and i want to try doing it

**Comment by xaerus88** [comment]
i am new to openkore, can someone please help me, i have the same problem as well/.

**Comment by gr4ndmasterz** [comment]
dev are aware, give them time, they are contributing without expecting anythin in return , so just wait, everytime after maintenance this will happen. so relax

**Comment by xaerus88** [comment]
thanks. =)

**Comment by johnleydelgado** [comment]
They will closed this issue if they fixed it

**Comment by EnzoMachiavelli** [comment]
Can someone link me allanon's packet generator?

**Comment by sctnightcore** [comment]
https://gist.github.com/allanon/d8181ceaf6380da6d8fa4fddf1885706

**Comment by Glikadin** [comment]
Okay . How get and install disassemble x86.pm ?  I am noob
![125125ssssss](https://user-images.githubusercontent.com/20753532/33706633-c2f91cb8-db45-11e7-9f5b-050b260f06e4.jpg)
xD

**Comment by xaerus88** [comment]
Is it fix now? thanks. =)

**Comment by EnzoMachiavelli** [comment]
@sctnightcore these are the crypt keys for restart. now I'm clueless how to get the rest

**Comment by sctnightcore** [comment]
@EnzoMachiavelli  key is true ! but problem is recvpacket and shuffle

**Comment by EnzoMachiavelli** [comment]
@sctnightcore isn't supposed to auto generate if you used the key?

**Comment by sctnightcore** [comment]
I think the recvpacket shuffle will be renewed every week. @EnzoMachiavelli

**Comment by sctnightcore** [comment]
@EnzoMachiavelli  up to you XD

**Comment by sctnightcore** [comment]
Fix :  0115068

**Comment by Glikadin** [comment]
God Bless

**Comment by xaerus88** [comment]
how do we change that. in what folder, I am really a newbie. thanks

**Comment by lututui** [comment]
Merged #1486 . Just update and it should be solved
