### ISSUE TITLE
iRO Chaos renewer Timeout on Account Server, reconnecting...

### ISSUE THREAD

**Issue by bunnyy00** [OpenKore/openkore#1489]
Seems like they doing this every week now..

**Comment by sctnightcore** [comment]
wait !!!

**Comment by bunnyy00** [comment]
@sctnightcore yes i will... please close this and delete this thread , i think i was a lil impatient here>_<

**Comment by fadreus** [comment]
@bunnyy00 Please don't open issue each time renewal can't connect after maintenance. Just wait at least 24 hours before opening an issue.

**Comment by Glikadin** [comment]
24 hours :(
