### ISSUE TITLE
automatic recording at logs folder

### ISSUE THREAD

**Issue by 530453506** [OpenKore/openkore#1491]
**Openkore always automatic records information in chat.txt like belows:**
[Dec 8 12:23:34 2017][K] You become MVP!
[Dec 8 12:23:34 2017][K] Congratulations, you are the MVP! Your reward is 11169225 exp!
[Dec 8 12:23:36 2017][K] Player wusheng75 (1) become MVP!
....
**config.txt  setting as belows:**
logChat 0
logPrivateChat 0
logPartyChat 0
logGuildChat 0
logSystemChat 0
logEmoticons 0
logConsole 0
logAppendUsername 0
logAppendServer 0
monsterLog 0
logDead 0

**I don't want the logs, how can I do? Pls help me.**

**Comment by fadreus** [comment]
Click log folder and press DEL on your keyboard.

**Comment by c4c1n6kr3m1** [comment]
servertypes0.pm and Sakexe_0.pm , find these lines and delete
```	message TF("%s become MVP!\n", $display);
	chatLog("k", TF("%s become MVP!\n", $display));```

**Comment by Nipodemos** [comment]
if i remember correctly, openkore create the folder if not exists

**Comment by c4c1n6kr3m1** [comment]
```
sub mvp_other {
	my ($self, $args) = @_;
	my $display = Actor::get($args->{ID});
	message TF("%s become MVP!\n", $display);
	chatLog("k", TF("%s become MVP!\n", $display));
}

sub mvp_you {
	my ($self, $args) = @_;
	my $msg = TF("Congratulations, you are the MVP! Your reward is %s exp!\n", $args->{expAmount});
	message $msg;
	chatLog("k", $msg);
}
```

**Comment by c4c1n6kr3m1** [comment]
did u see that "chatLog("k" ...... blablabla
delete if u want
it's on ServerType0.pm and Sakexe_0.pm

**Comment by 530453506** [comment]
@Nipodemos  you are right!
@c4c1n6kr3m thanks a lot!
