### ISSUE TITLE
busCommands

### ISSUE THREAD

**Issue by adraaawr** [OpenKore/openkore#1495]
_Please_ refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 
Kore do not identify other kores
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:
Do not send bus commands
###### Expected Behavior:
Should received new client from console and identify it.
###### Actual Behavior:
Kore starting a bus server and ignoring other kores.
###### Summary:
It is supposed to connect to a local host automatically, like default?
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:
I will attached some screenshot and my sys.txt
![eto](https://user-images.githubusercontent.com/32107546/33803984-dd33c2de-ddd6-11e7-9c12-fbdcff92b09c.png)
![bat](https://user-images.githubusercontent.com/32107546/33803995-00c0b806-ddd7-11e7-98b5-6ad105543c90.png)
[sys.txt](https://github.com/OpenKore/openkore/files/1545500/sys.txt)

**Comment by lututui** [comment]
Set the same port for bus in sys.txt across all clients (`bus_server_port`)

**Comment by adraaawr** [comment]
everytime I open kore, bus server port changes too, I need to set it again and again.
Is there any way to prevent this? since I'm only running multiple bots in the same operating system.

**Comment by lucasbradok** [comment]
Set this in all your bots control/sys.txt line 12~20

###### Bus system settings ######
# Whether to enable the bus system.
bus 1

# If you want to connect to an already running bus server on a different
# computer, specify the host and port here.
bus_server_host 127.0.0.1 # OR other external ip all need to be the same.
bus_server_port 1501 # Or other port all need to be the same
bus_userAgent

**Comment by adraaawr** [comment]
thank fixed now, i think its on my pc, i uninstalled all vpns .

**Comment by adraaawr** [comment]
this issue came back again, no broadcasting message like this

![32430694-64b61510-c2e1-11e7-8cf7-504cac8241fd](https://user-images.githubusercontent.com/32107546/34176079-a0cd02dc-e539-11e7-8b6b-c4b9fee3f7e7.jpg)

only this, 

![96-dyp5xtnkwky3gccr13w](https://user-images.githubusercontent.com/32107546/34176134-d1d0e9b6-e539-11e7-9d34-e72b8878121c.png)

**Comment by imthemenace** [comment]
hi adraaawr do you have extreme ro ph full config source or sample copy can you please send me a link or pics of sample here im a new bot user here tnx any help will so much appreciated

**Comment by alisonrag** [comment]
@adraaawr did you tried restart your pc, download a fresh openkore and reconfigure again?

**Comment by alisonrag** [comment]
Any update?
