### ISSUE TITLE
The issue of kRO: zero now.

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1496]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### My problem :
**Now** 
```
1. random ip login - -
2. 0ACF login from client  < I think new login packet 
3. 0875+token from web
4.OTP packet 0AE3
```
**This is what i have**
1.New recvpacket,sync,shuffle,CryptKeys

Client dont pack 

**Discord for kRO:zero** : https://discord.gg/n7knzdh
PR: #1500

**Comment by c4c1n6kr3m1** [comment]
token from web? so you need to open the web first?
although i am not going to try, 
but can you show the login packet ?
may be some one has extraordinary brain to breakthrough

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1  
0ACF OK > 0AE3+token > 0825+token from 0AE3 > server

0ACF i think connect to 112.175.128.135:6900 
0825+token connect to 112.175.128.137:6950
![image](https://user-images.githubusercontent.com/23263315/33827392-c903a6ac-de9a-11e7-992f-eb63d1f3e375.png)

Now 0ACF ok   miss 5 len 
`'0ACF' => ['master_login', 'V Z24 a32 C', [qw(version username password_rijndael master_version)]],`

```
sub reconstruct_master_login {
	my ($self, $args) = @_;
    
	if (exists $args->{password}) {
		my $key = pack('C32', (0x06, 0xA9, 0x21, 0x40, 0x36, 0xB8, 0xA1, 0x5B, 0x51, 0x2E, 0x03, 0xD5, 0x34, 0x12, 0x00, 0x06, 0x06, 0xA9, 0x21, 0x40, 0x36, 0xB8, 0xA1, 0x5B, 0x51, 0x2E, 0x03, 0xD5, 0x34, 0x12, 0x00, 0x06));	
		my $chain = pack('C32', (0x3D, 0xAF, 0xBA, 0x42, 0x9D, 0x9E, 0xB4, 0x30, 0xB4, 0x22, 0xDA, 0x80, 0x2C, 0x9F, 0xAC, 0x41, 0x3D, 0xAF, 0xBA, 0x42, 0x9D, 0x9E, 0xB4, 0x30, 0xB4, 0x22, 0xDA, 0x80, 0x2C, 0x9F, 0xAC, 0x41));
		my $in = pack('a32', $args->{password});
		my $rijndael = Utils::Rijndael->new;
		$rijndael->MakeKey($key, $chain, 32, 32);
		$args->{password_rijndael} = unpack("Z24", $rijndael->Encrypt($in, undef, 32, 0));
		Misc::visualDump($args->{password_rijndael});
	}
}
```

**Comment by alisonrag** [comment]
Size in Bytes

Send 0ACF [login packet] (Size: 68)
	struct {
		Header: 0ACF (Size: 2)
		Game Code: 0036 (Ragnarok game code) (Size: 4)
		Login Literal: Login (Size: 25)
		Password Encrypted: Password (Size: 32)
		Flag: idk Normally string: G000 (Size: 5)
	}

Recv 0AE3 [token packet] (Size: -1)
	struct {
		Header: 0AE3 (Size: 2)
		Length :  length ?? (Size: 2)
		Login Type:  always 0? (Size: 4)
		Flag: Normaly string: S1000 (Size: 20)
		Token: Literal Token (Size: not Fixed)
	}
	

Send 0825 [send token packet] (Size: -1)
	struct {	
		Header: 0825 (Size: 2)
		Length :  length ?? (Size: 2)
		Version:
		MasterVersion:
		Username: Username (Size: 24)
		PassWord: ???  (Size: 27)
		Macaddress: Mac Address from adapter (Size: 17)
		IP: Machine IP (Size: 15)
		Token: Literal Token (Size: not Fixed)
	}

Recv 0AC4
Recv 0F70

Send 0065 << Start from here everything seens fine

**Comment by sctnightcore** [comment]
```
The server has denied your connection for unknown reason (119).
You can not access an IP if it is not randomized by the client.
```

**Comment by c4c1n6kr3m1** [comment]
computer bound?
xkore 1 work ? 
is 0069 normal ?

**Comment by alisonrag** [comment]
its your turn.

Ragexe:
![ragexe](https://user-images.githubusercontent.com/10372732/33885446-7d6542ba-df2a-11e7-8d9c-b1adce8d9f1f.png)


Openkore:
![kore](https://user-images.githubusercontent.com/10372732/33885456-826eded8-df2a-11e7-8357-eef55492ad90.png)

missing some bytes in 0825

know struct:
`'0825' => ['token_login', 'v v x v Z24 a27 Z17 Z15 a*', [qw(len version master_version username password_rijndael mac ip token)]],`

my branch with modifications is here:
https://github.com/alisonrag/openkore/tree/kRO_Zero

my result is this:
![openkore test](https://user-images.githubusercontent.com/10372732/33885587-ef48dbd0-df2a-11e7-8379-1ffcf0b55782.png)

**Comment by sctnightcore** [comment]
Now can login 
Miss 
```
Packet Parser: Unknown switch: 0ADC
Packet Parser: Unknown switch: 0ADE
Actor is unknown or not ready for stat information (switch 0ACB, type 23, val 18)
Packet Parser: Unknown switch: 0ADF
Exp bar not load 
```
