### ISSUE TITLE
Unable to BOT in Lasagna fields/dungeon

### ISSUE THREAD

**Issue by plokislokis** [OpenKore/openkore#1499]
Hello Guys, I'm getting a "cannot load field" error every time I try to access Lasagna fields. It shows no corresponding field file found. I checked the fields folder and it shows the .fld file for the lasagna maps and maps.txt also shows the lasagna maps. Need help thanks.

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/33862629-46c6e40c-df16-11e7-8958-71f0d3d376fe.png)
Copy .fld to fields
![image](https://user-images.githubusercontent.com/23263315/33862641-5c4ddfa6-df16-11e7-8c9a-e8e6b5fc69a7.png)

**Comment by plokislokis** [comment]
I already tried that but still getting the same error.

**Comment by sctnightcore** [comment]
Error ?

**Comment by plokislokis** [comment]
![error](https://user-images.githubusercontent.com/29620340/33864121-1c7be0a2-df26-11e7-932c-8c3c49613203.jpg)

**Comment by sctnightcore** [comment]
@plokislokis server ?

**Comment by plokislokis** [comment]
thor

**Comment by sctnightcore** [comment]
thor ? @plokislokis

**Comment by plokislokis** [comment]
yes

**Comment by sctnightcore** [comment]
Thor ? iRO ? 
@plokislokis

**Comment by fadreus** [comment]
That IP seems from iRO renewal 128.241.92.xxx

**Comment by alisonrag** [comment]
add to maps.txt

**Comment by sctnightcore** [comment]
@alisonrag  Tonight I will check and fix them.

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/33916664-806e7352-dfdc-11e7-8980-fd476593f440.png)
idk why HAHAHA

**Comment by plokislokis** [comment]
That's the same error i'm getting @sctnightcore. Map.txt shows the lasagna fields as well.

**Comment by c4c1n6kr3m1** [comment]
my maps.txt
```
// Doram race - Lasagna town
lasagna.rsw#Port Town Lasagna#
lasa_fild01.rsw#Ravioli Plain, Border post#
lasa_fild02.rsw#Ravioli Forest#
lasa_dun01.rsw#Dragon Nest#
lasa_dun02.rsw#Dragon Nest#
lasa_dun03.rsw#Dragon Nest#
conch_in.rsw#Inside Conch#
lasa_in01.rsw#Inside Lasagna#
lasa_dun_q.rsw#Dragon Nest#
```

my resnametable.txt
```
lasagna.gat#lasagna.gat#
lasa_in01.gat#lasa_in01.gat#
conch_in.gat#conch_in.gat#
lasa_fild01.gat#lasa_fild01.gat#
lasa_fild02.gat#lasa_fild02.gat#
lasa_dun01.gat#lasa_dun01.gat#
lasa_dun02.gat#lasa_dun02.gat#
lasa_dun03.gat#lasa_dun03.gat#
lasa_dun_q.gat#lasa_dun_q.gat#
```

**Comment by plokislokis** [comment]
@c4c1n6kr3m1 , thanks it worked now God Bless
