### ISSUE TITLE
Character Selection Not Showing Properly - Kore, Official iRO (Chaos)

### ISSUE THREAD

**Issue by Palagi** [OpenKore/openkore#1505]
Hello,
I have downloaded and redownloaded kore and still running through the same issue.

I have followed the directions in this link (https://github.com/OpenKore/openkore/pull/1209) and got the latest crypt files (sync.txt, shuffle.txt, servers.txt, and recvpackets.txt). Doing so caused kore to time out. I have put these files in their corresponding locations and copied and pasted the txt files. And I still got errors. And so, I started from scratch again.

From my research, I found that the problem seems to be caused by charblocksize in the server.txt file. Right now, I have it as 144 and it shows me this error:
![pic 1](https://user-images.githubusercontent.com/34534160/33979863-1ea4b3fa-e05b-11e7-954b-9ecc5893bc35.JPG)

If I change charblocksize to 145, I get this error:
![pic2](https://user-images.githubusercontent.com/34534160/33979999-c44fa3be-e05b-11e7-9e2e-9055cefea3c5.JPG)

Please Help! I've been working on this for 2 days (about 10 hours) and can't seem to figure it out. I was able to run kore early this year with no major troubleshooting issue such as this.

Thanks in advance!

**Comment by fadreus** [comment]
Download new one.

> I have followed the directions in this link (#1209)

This one from September, now December.

> I was able to run kore early this year

IRo update weekly, thus we also need update weekly.

IRO so far have no major issue since allanon keep it up-to-date.

**Comment by Palagi** [comment]
Thanks for pointing it out. I thought the most recent update we have is Sep.

Do you mind pointing me to the proper link for December please? The most recent one I am able to find is Sep. I agree with you, I have to download the December updates; I just can't seem to find them.

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/archive/master.zip

**Comment by Palagi** [comment]
It works. Thanks!

**Comment by amby127** [comment]
Gud day master Alisonrag I've got problem can u help me plss it happend last night 5-9-2019 after server update cant connect -_-
![Untitled](https://user-images.githubusercontent.com/50486500/57524695-13328c80-7318-11e9-8da2-e3db16870e5b.png)

**Comment by nirca** [comment]
![Capture](https://user-images.githubusercontent.com/63701257/79305154-67c98900-7f25-11ea-8a9a-67b101439426.JPG)

It doesn't work anymore. It doesn't show the actual characters that I have. Please help!
