### ISSUE TITLE
cRo poseidon ask for help!

### ISSUE THREAD

**Issue by agfield** [OpenKore/openkore#1507]
today cro have this probroms:
when Run cro-client slaves to login Poseidon:
CHARACTER_INFO size error!!
CHARACTER_INFO size : 145
![default](https://user-images.githubusercontent.com/34531479/33999678-184a6808-e126-11e7-8000-2be20728f0ff.jpg)

and
after run start have this problems:
![default](https://user-images.githubusercontent.com/34531479/33999660-06a870b8-e126-11e7-883c-8f682690ff9a.png)

Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

**Comment by sctnightcore** [comment]
where you get openkore ?

**Comment by dcyxxt** [comment]
following~~~

**Comment by sctnightcore** [comment]
```
'09FD' => ['actor_moved', 'v C a4 a4 v3 V v5 a4 v6 a4 a2 v V C2 a6 C2 v2 a9 Z*', [qw(len object_type ID charID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tick tophead midhead hair_color clothes_color head_dir costume guildID emblemID manner opt3 stance sex coords xSize ySize lv font opt4 name)]],
'09FE' => ['actor_connected', 'v C a4 a4 v3 V v11 a4 a2 v V C2 a3 C2 v2 a9 Z*', [qw(len object_type ID charID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tophead midhead hair_color clothes_color head_dir costume guildID emblemID manner opt3 stance sex coords xSize ySize lv font opt4 name)]],
'09FF' => ['actor_exists', 'v C a4 a4 v3 V v11 a4 a2 v V C2 a3 C3 v2 a9 Z*', [qw(len object_type ID charID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tophead midhead hair_color clothes_color head_dir costume guildID emblemID manner opt3 stance sex coords xSize ySize act lv font opt4 name)]],
```

**Comment by agfield** [comment]
@yon2kong
Can you offer help？TKS

**Comment by vasa1983** [comment]
@agfield \src\Network\Receive\cRO.pm

**Comment by agfield** [comment]
Have you been able to connect to the server normally？@vasa1983

**Comment by vasa1983** [comment]
@agfield use the old client for poseidon

**Comment by agfield** [comment]
use the old client for poseidon
after login there have this probroms:
![11](https://user-images.githubusercontent.com/34531479/34034781-dbaacdd0-e1ba-11e7-9e02-bad4ef100dc3.png)

**Comment by hubertyang88** [comment]
@agfield use old version client ragexe.exe , the one before update

**Comment by vasa1983** [comment]
@sctnightcore which array or hash should I update 09FD,09FE,09FF,not familar with the packet.

**Comment by vasa1983** [comment]
@agfield OK connection is okay but with the unknow packet.

**Comment by wr2cna** [comment]
@sctnightcore how can i update \src\Network\Receive\cRO.pm  with '09FD' => ['actor_moved', 'v C a4 a4 v3 V v5 a4 v6 a4 a2 v V C2 a6 C2 v2 a9 Z*', [qw(len object_type ID charID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tick tophead midhead hair_color clothes_color head_dir costume guildID emblemID manner opt3 stance sex coords xSize ySize lv font opt4 name)]],
'09FE' => ['actor_connected', 'v C a4 a4 v3 V v11 a4 a2 v V C2 a3 C2 v2 a9 Z*', [qw(len object_type ID charID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tophead midhead hair_color clothes_color head_dir costume guildID emblemID manner opt3 stance sex coords xSize ySize lv font opt4 name)]],
'09FF' => ['actor_exists', 'v C a4 a4 v3 V v11 a4 a2 v V C2 a3 C3 v2 a9 Z*', [qw(len object_type ID charID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tophead midhead hair_color clothes_color head_dir costume guildID emblemID manner opt3 stance sex coords xSize ySize act lv font opt4 name)]],

**Comment by leilei007** [comment]
How to extract out of the study thank you!
