### ISSUE TITLE
Zero Server have several issues.

### ISSUE THREAD

**Issue by yonghagg** [OpenKore/openkore#1509]
i found several issues in zero server.

first.  yesterday(2017_12_14), added gameguard in zero server.
![image](https://user-images.githubusercontent.com/34561835/34025765-188ccfb2-e195-11e7-82f1-69af30763348.png)

second. displayed wrong job in console. my slot1 character job is merchant, and my other characters were not displayed(job is thief).
![image](https://user-images.githubusercontent.com/34561835/34025982-59d7aac2-e196-11e7-9410-16bc4386cdac.png)

third. i can't into map server. (The yellow part of the picture above)

last, "Packet Tokenizer: Unknown switch: " is displayed and not attack mobs.

**Comment by sctnightcore** [comment]
https://discord.gg/fwgHW3

**Comment by yonghagg** [comment]
I have to work, I will contact you later.

**Comment by sctnightcore** [comment]
find someone can unpack client

**Comment by genieker** [comment]
I have same problems..

**Comment by sctnightcore** [comment]
1. cannot unpack 2.cannot find packet key 3.cannot find recvpacket
4.cannot redirect connection to local host to use poseidon
