### ISSUE TITLE
Help to recvpackets tRO plzz

### ISSUE THREAD

**Issue by yordnakub** [OpenKore/openkore#151]
recvpackets.txt help tRO plz Roexe

Ragexe.exe ro.exe.in.th

**Comment by plubnakub** [comment]
++++

**Comment by nocoment01** [comment]
++++

**Comment by mackhahai** [comment]
help me

**Comment by Jasmineit** [comment]
it now data.grf has to edit by ro.exe.in.th and me edit file clientinfo.xml but can't working i have error CEasyAntiCheatMgr someone can fix this pls tell us for thai server  community

**Comment by Jasmineit** [comment]
i can make file recvpackets.txt

**Comment by AsakuraTK** [comment]
@Jasmineit How can I contact you?

**Comment by kittisk** [comment]
how to pass the sc login ?

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
