### ISSUE TITLE
eventMacros.txt file not found on iRO: Renewal

### ISSUE THREAD

**Issue by Palagi** [OpenKore/openkore#1511]
Before maintenance, I was able to log in using current version of Kore. After maintenance, I can't anymore and I encounter this error. I don't remember seeing eventMacros.txt file in control folder. I didn't change anything - I straight up downloaded current version of kore and this just happened after maintenance.

![pic1](https://user-images.githubusercontent.com/34534160/34026414-cdbafe76-e10a-11e7-8273-320dbe7fa7f1.JPG)

I'm not a skilled coder and so I'm asking for help. Thanks very much!

**Comment by fadreus** [comment]
### Unless it's a bug on openkore, I suggest you to use forum.

Just create eventMacros.txt in your control.
Its only saying no files found, not really an error & have nothing to do with connectivity.

**Comment by lututui** [comment]
This has nothing to to with the update. You're just not using eventMacros. There's no connection between iRO's maintenance and this
