### ISSUE TITLE
CRO  封包更新问题

### ISSUE THREAD

**Issue by leilei007** [OpenKore/openkore#1513]
<trans data-src="Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:
" data-dst="Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant coDE段和源代码参考` ` ` 
 ######影响：
 
 ######好处：
 
 ######弊端：">Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant coDE段和源代码参考` ` ` 
 ######影响：
 
 ######好处：
 
 ######弊端：</trans>
![f 1 db d 3w3ll hivm](https://user-images.githubusercontent.com/34589883/34066724-6268de1e-e24e-11e7-8c70-664cfe792be7.jpg)
![y vj iqj z730 d9s7 1w](https://user-images.githubusercontent.com/34589883/34066725-62ab521c-e24e-11e7-9c8f-df4c11e00484.png)

**Comment by kou90258** [comment]
Can you speak in English with the department?
And the detailed questions in English language to thank the narrative.

**Comment by agfield** [comment]
please speak in English

**Comment by sctnightcore** [comment]
if you can unpack > you can find recvpacket

**Comment by leilei007** [comment]
I see you send the packet But how to modify the ~

**Comment by agfield** [comment]
please refer to
http://openkore.com/index.php/Frequently_Asked_Questions#Packet_Tokenizer:_Unknown_switch:_xxxx

**Comment by agfield** [comment]
![default](https://user-images.githubusercontent.com/34531479/34102907-ba064d5e-e425-11e7-9be8-ad595ba17a9d.png)
for help

**Comment by sctnightcore** [comment]
```
alisonrag - Yesterday at 10:16 PM
updating cRO
now i can:
1 - unpack client
2 - extract recvpackets / shuffle / sync
working on connection files cRO.pm
and after all ok
i will work in poseidon.pl
3 - can login without hardcode password
now working in poseidon
```

**Comment by sctnightcore** [comment]
https://discord.gg/aWfnKX5

**Comment by sctnightcore** [comment]
go go go #1519
