### ISSUE TITLE
iRO dir table

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#1516]
###### Summary: 
i'm using current version: version git:f8071ed_2017-12-17

###### Affected configuration(s)/ file(s):
servers.txt and connection to iRO Classic

###### Impact:
Actually openkore still load sync and shuffle from another iRO server (Renewall) to connect to Classic

###### Actual Behavior:
with sync and shuffle files:
![iro cant connect](https://user-images.githubusercontent.com/10372732/34080288-9c464fa2-e322-11e7-942f-4b940dea4359.png)

###### Expected Behavior:
without sync and shuffle files:
![iro connect](https://user-images.githubusercontent.com/10372732/34080285-7a77a13c-e322-11e7-8595-b531ce757b23.png)

###### Steps to Reproduce:
to test just try to connect to iRO classic server with latest version of openkore and you will see that is not possible to login in map server

after this delete:
```
openkore\tables\iRO\shuffle.txt
openkore\tables\iRO\sync.txt
```
and you will see that is possible to login and play 

### Suggestion
i think we need to rework the iRO dir and move the files to the right place
#1380

**Comment by sctnightcore** [comment]
@allanon
