### ISSUE TITLE
PEEK recvpackets problem

### ISSUE THREAD

**Issue by 530453506** [OpenKore/openkore#1518]
Here's my main problem,the private server use it's own packet key and use kRO_RagexeRE_2017_06_14b client.
I tried PEEK to analyze,but it did not work(ExtractPacketLen: failed to find the packet_cz_enter).
Should I disassemble the EXE? How can I get the 3 keys?
Thank you so much in advance!

Heres my client:
[ro.exe.backup_by_PEEK.zip](https://github.com/OpenKore/openkore/files/1569023/ro.exe.backup_by_PEEK.zip)

**Comment by sctnightcore** [comment]
table > kRO > RagexeRE_2017_06_14b

**Comment by alisonrag** [comment]
> the private server use it's own packet key

**Comment by sctnightcore** [comment]
@alisonrag  Nemo cannot diff custom packet key!

**Comment by alisonrag** [comment]
@sctnightcore 
this nemo can
https://gitlab.com/4144/Nemo

**Comment by sctnightcore** [comment]
http://herc.ws/board/topic/4912-peek-successor-to-yommys-packet-analyzer/
use it . AAHAHAH

**Comment by 530453506** [comment]
@alisonrag no any anticheat or guard

**Comment by sctnightcore** [comment]
@530453506  link server ? i will test if have free time

**Comment by 530453506** [comment]
It's Chinese Server, heres the patch.
https://drive.google.com/open?id=1iP72gh--bRh0uxGhy2S6W0-S3d9Ky-Eb

**Comment by sctnightcore** [comment]
@530453506  link server !!!  i want link server !!!!!!!!!

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/34140126-2f2eb654-e4ab-11e7-8273-6f47375f00ec.png)
i cannot download patch . GG

**Comment by 530453506** [comment]
@sctnightcore 
er..could you open the client(18800KB) directly?

**Comment by sctnightcore** [comment]
https://pastebin.com/uTEkgp0m

**Comment by 530453506** [comment]
I had a mistake, i transformed 3 keys from HEX to OCT(due to 2013 clients), it is no need. the default keys were right.

**Comment by sctnightcore** [comment]
@530453506  use with **sendCryptKeys**
https://github.com/OpenKore/openkore/blob/4aab75cf4de3c9586ba4755059c1d2f0e31fc0b4/tables/servers.txt#L29

sendCryptKeys key1 key3 key2
