### ISSUE TITLE
cro~~!Unknown packet how to update

### ISSUE THREAD

**Issue by leilei007** [OpenKore/openkore#1523]
![Uploading Y}VJ))IQJ[]Z730@D9S7%1W.png…]()

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/34181940-ce178fac-e546-11e7-939b-940813ec1b9c.png)
 . .. .. . .

https://discord.gg/aWfnKX5

**Comment by leilei007** [comment]
https://discord.gg/aWfnKX5  Not registered

**Comment by sctnightcore** [comment]
@leilei007  go discord room or post packet unknow

**Comment by leilei007** [comment]
I sent you an email

**Comment by sctnightcore** [comment]
@leilei007 post in discord !!!

**Comment by sctnightcore** [comment]
go #1519

**Comment by leilei007** [comment]
Look, I still don't understand

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/34183352-014d5216-e54d-11e7-8e86-f94e3004ad5d.png)
@leilei007

**Comment by leilei007** [comment]
Thank you very much! But I still don't ~ ~
