### ISSUE TITLE
MySg Extreme Connection

### ISSUE THREAD

**Issue by shahraf** [OpenKore/openkore#1524]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 
latest openkore,
recvpacket generate by using  PeekMaster
ip and port by using wireshark.
trying to connect using pRO serverType, failed 

[servers.txt](https://github.com/OpenKore/openkore/files/1575118/servers.txt)
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1575120/recvpackets.txt)

Requesting for serverType, did anyone successful to connect?

**Comment by sctnightcore** [comment]
No dev of mRO 
sry , i want close it XD
