### ISSUE TITLE
Hi, add me! :)

### ISSUE THREAD

**Issue by technologyguild** [OpenKore/openkore#1527]

**Comment by sctnightcore** [comment]
add me discord :  sctnightcore24hour#1063 i will add you to openkoredevroom 

♥♥♥♥♥

**Comment by sctnightcore** [comment]
lol @alisonrag

**Comment by alisonrag** [comment]
this is not a issue

**Comment by alisonrag** [comment]
@technologyguild still receive notification, he need just click in notification tab
