### ISSUE TITLE
teleportAuto_notPlayers is not working

### ISSUE THREAD

**Issue by kittygrill** [OpenKore/openkore#153]
Used player name as string still teleports when said player is in range

**Comment by lututui** [comment]
I believe this is a logic issue in CoreLogic.pm, line 2954

`if (!existsInList($config{teleportAuto_notPlayers}, $player->{name}) **&&** !existsInList($config{teleportAuto_notPlayers}, $player->{nameID})) {`

This is only true if neither the player name nor their ID match with the configuration; meanwhile, the intended behavior is to match either one, not both.

**Comment by lututui** [comment]
I can't reproduce it.

**Comment by kaliwanagan** [comment]
Closing for now until repro steps are available
