### ISSUE TITLE
Timeout on Map Server, connecting to Account Server...

### ISSUE THREAD

**Issue by manojbabu31** [OpenKore/openkore#1532]
Hello All,

Need help in fixing the timeout issue.
Have downloaded the latest version of openkore-master multiple times and tried but of no use.
I am trying to configure bot for Valor RO.
I think I have all the required details i.e. server info, recvpackets.txt. But when I try running the bot I encounter the Timeout on Map Server, connecting to Account Server... issue and then get a message like
Timeout on Account Server, reconnecting. Wait 183 seconds...

Error image
![bot_error](https://user-images.githubusercontent.com/29751084/34262775-54158008-e693-11e7-9688-01bbb0672166.JPG)

details from servers.txt

[Valor RO]
ip 104.207.155.105
port 6900
master_version 1
version 56
serverType kRO_RagexeRE_2016_02_03a
addTableFolders vRO
charBlockSize 147
pinCode 1
clientHash 14cd82deca04abeedce9276e2e4b97c2
sendCryptKeys 0x3E1411AF, 0x6C744497, 0x7CFA1BDE

[recvpackets.txt](https://github.com/OpenKore/openkore/files/1579689/recvpackets.txt)

Please help in identifying and with steps to troubleshoot the issue.

I tried configuring the bot for another private server as well.. I face the same issue again.

Thanks in Advance...

Merry Christmas and a Happy New Year..

**Comment by alisonrag** [comment]
post your config

**Comment by manojbabu31** [comment]
Here it is..

[servers.txt](https://github.com/OpenKore/openkore/files/1580149/servers.txt)

**Comment by sctnightcore** [comment]
If it was me, I would close the issues because he did not tell the link server and other parts.

**Comment by manojbabu31** [comment]
@sctnightcore.. sorry sir.. please let me know what i need to share from the bot folder so that I can attach them here.. kindly help to fix the issue..

**Comment by sctnightcore** [comment]
1.Check client date ! 
2. packet key use with 1 3 2

**Comment by manojbabu31** [comment]
@alisonrag and @sctnightcore.. Thanks a lot for the help

Checked the client date - it was same as above mention in the initial comment.
Was able to connect and working fine when I changed the sendCryptKeys to 1 3 2.

Thanks again..
Merry Christmas and a Happy New Year..
