### ISSUE TITLE
hidden NPC kafra [Iro]

### ISSUE THREAD

**Issue by Junezavr** [OpenKore/openkore#1537]
pic.
![npc](https://user-images.githubusercontent.com/22251521/34283461-71ba25c6-e6fe-11e7-900c-16bb9d857eed.jpg)

npc  hidden

**Comment by sctnightcore** [comment]
Map ?

**Comment by Junezavr** [comment]
einbroch

**Comment by Junezavr** [comment]
error Talk with a hidden NPC prevented

**Comment by Junezavr** [comment]
![2](https://user-images.githubusercontent.com/22251521/34285659-c4179a4c-e70d-11e7-8a25-7ca49f8f2d47.jpg)

**Comment by fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/34289636-5a8a572e-e72e-11e7-8ff0-836826be19cf.png)

IRO fine with me..
Did you mess up something?
What version did you use?

**Comment by Junezavr** [comment]
iro restart

**Comment by imthemenace** [comment]
hi meron ba roph botter dto may tatanong sana ako bout bot config please help me
di ko alam panu iset up

**Comment by iamtonysoft** [comment]
If you login ingame you can't find the kafra on einbroch to save. Maybe they remove it temporarily or permanently. Also the `train guy` was not there.

**Comment by alisonrag** [comment]
as @iamtonysoft told the npc was not there
