### ISSUE TITLE
extreme ragnarok online philippines new booter

### ISSUE THREAD

**Issue by imthemenace** [OpenKore/openkore#1540]
guys is there any filipino running a bot here
can you please comment back the full log in config system for our server
or take a screenshot and post it here please any help may appreciated
tnx rak pinoys HAVE FUN BOTIING!

**Comment by imthemenace** [comment]
also please send a link of the latest openkore system if theres only a new one because i got a master zip file here i dont know if its the latest one tnx rok on

**Comment by alisonrag** [comment]
@imthemenace 
the zip is the 
https://github.com/OpenKore/openkore/archive/master.zip

also we already have a issue fo phRO

see #1225 
unfortunely we dont have devs working in this serving, no one here play in this server

**Comment by imthemenace** [comment]
tnx for this alison

**Comment by imthemenace** [comment]
sir alison any update? about ROPH config?

**Comment by alisonrag** [comment]
Maybe not, unfortunely no one dev play in this server

**Comment by imthemenace** [comment]
in ragnarok online here in philippines?
ouch sad... /sob

**Comment by C0reC0re** [comment]
any update as of Jan 
2020
