### ISSUE TITLE
Ragnarok Extreme MYSG

### ISSUE THREAD

**Issue by dankers881** [OpenKore/openkore#1544]
https://roextreme.com/mysg/main

[ROMYSG]

ip 139.99.7.212
port 6900
master_version 112

version 24

serverType kRO_RagexeRE_2017_11_01b
addTableFolders ROMYSG
charBlockSize 144

gameGuard 1
sendCryptKeys 0x3DBE2F85, 0x577565D3, 0x22754487

![capture](https://user-images.githubusercontent.com/34808035/34325448-d81d2b9a-e8cc-11e7-8ab3-4296964b9d91.PNG)

Stuck at timeout on acc server.
any idea?

**Comment by sctnightcore** [comment]
No dev of mRO

**Comment by johncena255** [comment]
help this Ragnarok Extreme MYSG i want can send bot me ?
