### ISSUE TITLE
useSelf_iTem and pickupitems

### ISSUE THREAD

**Issue by rehpej** [OpenKore/openkore#1548]
I have downloaded the openkore in this github and I'm having problem with my config

I tried this code so that my bot will use awakening potion 
> useSelf_item Awakening Potion {
> 	whenStatusInactive Awakening Potion
> 	inLockOnly 1
> 	notWhileSitting 1
> }

but my bot wont use it. my bot is already running around 2hrs 45mins. still all my awakening potions are unused.

also with the pickupitems, inside mt pickupitems.txt
> Potato -1
> Yellow Herb -1

as of now even i have set it to -1 or 0, the bot keeps on picking it up.

**Comment by alisonrag** [comment]
please check the names or try the id
