### ISSUE TITLE
Error running openkore.pl for Mac

### ISSUE THREAD

**Issue by alicoding** [OpenKore/openkore#155]
I did follow http://openkore.com/index.php/How_to_run_OpenKore

No error at all and I have change `hash_fun.h` as suggested in the troubleshooting section.

My mac version is `10.11.5 (15F34)`

```
$ ./openkore.pl
scons: Reading SConscript files ...
Checking Perl configuration ...(cached) yes
Checking for C library ncurses... (cached) yes
Checking for GNU readline 4.3 or higher...(cached) yes
Checking for C library readline.5... (cached) no
Checking whether Readline 5 is available... no
Checking for libcurl...(cached) libcurl 7.43.0
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/auto/XSTools/utils/perl/Benchmark.os -c -Wall -O3 -pipe -no-cpp-precomp -DPERL_DARWIN -fno-strict-aliasing -DVERSION=\"1.0\" -DXS_VERSION=\"1.0\" -Wall -O3 -pipe -no-cpp-precomp -DPERL_DARWIN -fno-strict-aliasing -DVERSION=\"1.0\" -DXS_VERSION=\"1.0\" -fPIC -I/usr/include -I/usr/local/include -I/sw/include -I/usr/local/opt/readline/include -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE src/auto/XSTools/utils/perl/Benchmark.cpp
In file included from src/auto/XSTools/utils/perl/Benchmark.xs:1:
src/auto/XSTools/utils/perl/../dense_hash_map.h:93:10: fatal error: 'ext/hash_fun.h' file not found
#include HASH_FUN_H                  // defined in sparseconfig.h
         ^
src/auto/XSTools/utils/perl/../sparseconfig.h:62:22: note: expanded from macro 'HASH_FUN_H'
                #define HASH_FUN_H <ext/hash_fun.h>
                                   ^
1 error generated.
scons: *** [src/auto/XSTools/utils/perl/Benchmark.os] Error 1
scons: building terminated because of errors.
-e \e[1;31mCompilation failed. Please read http://wiki.openkore.com/index.php/How_to_run_OpenKore for help.\e[0m
Can't locate loadable object for module XSTools in @INC (@INC contains: /Users/ali/projects/openkore/src/deps /Users/ali/projects/openkore/src /Users/ali/projects/openkore /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/ali/projects/openkore/src/Translation.pm line 30.
```

**Comment by itsrachelfish** [comment]
Hey, thanks for your interest in running OpenKore on OSX... I don't think I've heard of anyone doing that in a long time!

Personally I don't have a Mac, but I can do some testing on my boyfriend's computer this weekend. :smile:

**Comment by alicoding** [comment]
@itsrachelfish I'm happy to help debug if you need me to test anything :)

**Comment by lututui** [comment]
Isn't this because of Perl 5.18? Or is the need for Perl 5.12.3 only for windows users?

**Comment by alicoding** [comment]
@lututui good question... maybe I should try this out to see what happen if I switch to 5.12.3

**Comment by c0ke** [comment]
Hi

edit src/auto/XSTools/utils/sparseconfig.h line 62 from
`#define HASH_FUN_H <ext/hash_fun.h>`
to
`#define HASH_FUN_H <ext/hash_map>`

PS. I'm using OS X 10.11.6

**Comment by alicoding** [comment]
@c0ke สวัสดีครับ I actually have done that, but nothing change. It might have been PATH issue here too.

**Comment by c0ke** [comment]
@alicoding สวัสดีครับ could you share the error output ?

**Comment by alicoding** [comment]
@c0ke It's actually on the OP :)

**Comment by c0ke** [comment]
@alicoding could you try this [patch](https://gist.github.com/c0ke/5ccfb634600450c685e7dd276a781a7c)

then run

> $ make clean
> $ ./openkore.pl

**Comment by alicoding** [comment]
@c0ke so `make clean` did the trick here! I have changed that line before, but it never worked :P thanks!

**Comment by c0ke** [comment]
@alicoding welcome :) does it working now ? ps. i didn't check for bot is working correctly or not.

**Comment by alicoding** [comment]
@c0ke yep the script is running now, but I haven't got a chance to try the bot itself either.

**Comment by c0ke** [comment]
@alicoding so do i :) 
thanks

**Comment by itsrachelfish** [comment]
@alicoding There were some updates made by @farrainbow last month related to OSX: https://github.com/OpenKore/openkore/pull/343

Please try these updates and let us know if the issue is resolved for you :+1:

**Comment by kaliwanagan** [comment]
Looks like the fix linked to this issue works.
