### ISSUE TITLE
Timeout on map server

### ISSUE THREAD

**Issue by TechMachine** [OpenKore/openkore#1550]
hye guys need your help on this new server,i keep getting timeout on map server,hope any pro can help me out, thanks in advance!!

https://www.ragnaroksea.com/

ip 103.6.245.89
port 6900
master_version 1
version 55
serverType kRO_RagexeRE_2015_11_04a
addTableFolders SEARO
charBlockSize 145
recvpackets recvpackets.txt
charDeleteDateType 1
sendCryptKeys 0x2713CF0D, 0x24C19575, 0x44D86F97

**Comment by sctnightcore** [comment]
sendCryptKeys 1,3,2
charBlockSize 147

**Comment by TechMachine** [comment]
Thanks for replying sir, but it still disconnecting.. can u help please?


Timeout on Account Server, reconnecting. Wait 75 seconds...
Incoming data left in the buffer:
================================================
3 bytes   Dec 26 13:08:26 2017
  0>  81 00 08                                              ...
Disconnecting (103.6.245.89:6900)...disconnected

**Comment by TechMachine** [comment]
Thanks for replying sir, but it still disconnecting.. can u help please?


Timeout on Account Server, reconnecting. Wait 75 seconds...
Incoming data left in the buffer:

3 bytes Dec 26 13:08:26 2017
0> 81 00 08 ...
Disconnecting (103.6.245.89:6900)...disconnected

**Comment by sctnightcore** [comment]
`The server is temporarily blocking your connection until 2037-12-25 15:44:46`

```
sendCryptKeys 1,3,2
charBlockSize 147

```

**Comment by TechMachine** [comment]
ahhhhh thanksssss alot u so pro!!!

1 more question do u able to bot this server https://roextreme.com/mysg/main???

**Comment by sctnightcore** [comment]
No

**Comment by TechMachine** [comment]
anyway thanks alot sctnightcore!!! Appricate it alot!!
