### ISSUE TITLE
Renewal New Patch Can't Connect Openkore.

### ISSUE THREAD

**Issue by ramojskie** [OpenKore/openkore#1559]
need help update on openkore server change again thanks in advance @allanon  @sctnightcore

**Comment by jomarlorica** [comment]
Also Sir @alisonrag thanks

**Comment by leonado8** [comment]
me also after updated then issue as above also,please help sir

**Comment by bunnyy00** [comment]
just wait...

**Comment by plokislokis** [comment]
waiting for the updated scripts hehe

**Comment by masue** [comment]
just wait

**Comment by lobocop** [comment]
same issue in re:start

**Comment by fadreus** [comment]
@jomarlorica 
Do you always need to start new issue each time after maintenance?
Do you really don't know allanon will update it?
Do you need people to spell it for you?
Can't you learn to wait?
Can't you read the bug template?
Do you have some mental disease which block you learning capabilities?

**Comment by fadreus** [comment]
@jomarlorica 
You've been around for quite time. Why can't you learn to wait or follow the template?
Are you a kid with mental disability or something?

**Comment by jomarlorica** [comment]
@fadreus. im just asking if they can. im not asking you. mind your own business ok?

**Comment by sctnightcore** [comment]
go #1561

**Comment by masue** [comment]
@sctnightcore i tried it, still time out
renewal iro

**Comment by sctnightcore** [comment]
@masue  use with #1561  ?

**Comment by masue** [comment]
@sctnightcore sry my bad, miss some items :D 
AND WORK, thank you @sctnightcore

**Comment by Pachu1985** [comment]
thanks for updating brothers, i love ya all <3

**Comment by sctnightcore** [comment]
Wait update new PR Xd

**Comment by Pachu1985** [comment]
i modified the files myself from the PR and at least for re:start it worked

**Comment by sctnightcore** [comment]
go #1561 1562
