### ISSUE TITLE
Timeout in map server issue Chaos iRO 27 des 2017

### ISSUE THREAD

**Issue by cipoklu** [OpenKore/openkore#1560]
i got issue when i tried to login, always got "timeout in map server"

I already downloaded the new version of openkore

**Comment by fadreus** [comment]
First time here?
Please read & check before posting.

**Comment by cipoklu** [comment]
Yes im, sorry then @fadreus

**Comment by sctnightcore** [comment]
go #1561

**Comment by cipoklu** [comment]
@sctnightcore i'm so sorry sir, i tried to use [#1561](https://github.com/OpenKore/openkore/pull/1561)

but still not working on me, cause i just copied and pasted the codes. im sorry newbie here.
so helpful for me if u can give me new download link (new table folder)

**Comment by sctnightcore** [comment]
@cipoklu  It is not different. Just organized to look better.

**Comment by cipoklu** [comment]
@sctnightcore so i just copy that codes and paste to my folder right sir?

**Comment by sctnightcore** [comment]
wait merge PR XD @cipoklu

**Comment by cipoklu** [comment]
@sctnightcore yes sir sure. I tried to understand sorry :)
Anyway whats PR means?

**Comment by sctnightcore** [comment]
pull request

**Comment by cipoklu** [comment]
@sctnightcore oh i see, so is it fixed now? can i download new openkore?

**Comment by sctnightcore** [comment]
@cipoklu  yes .download new openkore XD

**Comment by cipoklu** [comment]
@sctnightcore thanks a lot sir!!! XD
