### ISSUE TITLE
idRO success connected but always DC after killing any monster

### ISSUE THREAD

**Issue by rastafara88** [OpenKore/openkore#1564]
hi guys,

i already checked every history of issues.. but there wasn't any clue for my problem..

here my logs

Received character ID and Map IP from Character Server
----------Game Info----------
MAP Name: gef_fild10.gat
MAP IP: 202.93.25.82
MAP Port: 5000
-----------------------------
Closing connection to Character Server
Disconnecting (202.93.25.70:6000)...disconnected
Connecting to Map Server...
Connecting (202.93.25.82:5000)... connected
You are now in the game
Your Coordinates: 64, 199
You are now: Speed Up
Allowed other player invite to Party
Other players are not allowed to view your Equipment.
=========================== Server Infos ===========================
EXP Rates: 100% (Base 0% + Premium 0% + Server 0% + Plus 0%) 
Drop Rates: 100% (Base 0% + Premium 0% + Server 0% + Plus 0%) 
Death Penalty: 100% (Base 0% + Premium 0% + Server 0% + Plus 0%) 
=====================================================================
Calculating random route to: Daratan Geffen (gef_fild10): 71, 297
You are now attacking Monster Orc Warrior (0)
[ 97/100] Monster Orc Warrior (0) attacks you (Dmg: Miss!) (Delay: 864ms)
[ 97/100] You attack Monster Orc Warrior (0) (Dmg: 456!) (Delay: 270ms)
[ 97/100] You attack Monster Orc Warrior (0) (Dmg: 456!) (Delay: 270ms)
[ 97/100] You attack Monster Orc Warrior (0) (Dmg: 316) (Delay: 270ms)
[ 97/100] Monster Orc Warrior (0) attacks you (Dmg: Miss!) (Delay: 864ms)
[ 97/100] You attack Monster Orc Warrior (0) (Dmg: 456!) (Delay: 270ms)
You have gained 408/160 (0.06%/0.03%) Exp
Target died
Calculating random route to: Daratan Geffen (gef_fild10): 216, 34
You are now attacking Monster Poporing (0)
[ 97/100] You attack Monster Poporing (0) (Dmg: 359) (Delay: 270ms)
Target died
You have gained 81/44 (0.01%/0.01%) Exp
Disconnected from Map Server, connecting to Account Server in 30 seconds...
Connecting to Account Server...
Connecting (202.93.25.81:6900)... connected
Secure Login...
rebuilding packet here ..
---------- Account Info ----------

could somebody to getting clue for above issue?

**Comment by sctnightcore** [comment]
idRO RE ?

**Comment by rastafara88** [comment]
Different sir... idRo offical...

**Comment by sctnightcore** [comment]
idRO_RE or idRO_PRE ?

**Comment by rastafara88** [comment]
idRo Classic official.. Grav*ndo publisher.

 here my server.txt:
[Indonesia - idRO: Midgard]
ip 202.93.25.81
port 6900
master_version 12
version 2
patchserver wpatch.ragnarok.co.id
patchpath /patch02
serverType idRO
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 144
charDeleteDateType 1

**Comment by sctnightcore** [comment]
idRO_classic have new login packet  
sry , no someone can do it.

**Comment by rastafara88** [comment]
i can do that sir but by manually for getting new login packet and successfully login..
bot will be fine if following master or just AFK..

but once i set to auto hitting.. thats problem happen...

difficult to me whats wrong with the auto hitting... is there any same cases for other server?

**Comment by sctnightcore** [comment]
No idea for rebuilding packet

**Comment by rastafara88** [comment]
hmmm.. ok.. just wanted for clue after hitting more than 2 or 3 mobs like was kicked from the server.. should waiting someone or just closed it?

because i saw other bots were working fine in this server.. hitting and continue without getting kicked from server...

**Comment by sctnightcore** [comment]
idk XD

**Comment by rastafara88** [comment]
which one packet is encrypt?

also checked alison has reference some threads.. but confuse while following the reference because the reference thread was lopping back to same threads.. lolz

**Comment by sctnightcore** [comment]
I just guess, idk XD

**Comment by rastafara88** [comment]
here sir..

https://ufile.io/m7gr0

already posted before.. :D

**Comment by sctnightcore** [comment]
[sync.txt](https://github.com/OpenKore/openkore/files/1593078/sync.txt)
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1593079/recvpackets.txt)

Not sure Work XD

**Comment by rastafara88** [comment]
thanks.. i will try it... btw where i should put file sync.txt ? table/idRo/ ?

**Comment by sctnightcore** [comment]
Put to tables/idRO

**Comment by rastafara88** [comment]
yes i did,,,  but still same.. >_<

**Comment by mfauziracing** [comment]
@rastafara88 i think wrong packet, i have same problem in Renewal when i take item, use equip, storage before. maybe you can turn on debugPacket (unparser/received/etc), so you can see what wrong with the packet before you dc.

hope can help you.

**Comment by sctnightcore** [comment]
IdRO_RE work with xkore1 and xkore3

**Comment by rastafara88** [comment]
@mfauziracing 
i was wondering, while i used bot for following master and/or supporting buff in every where place.. there was fine.. and also just stay AFK was fine using OK.. haha ~___~.

difficult to debugpacket caused RO will detect tools packet tracer after open 1 minutes arround and forcing quit the RO... :(

**Comment by mfauziracing** [comment]
@rastafara88 yap because your bot dont send 'attack' packet or receive 'attack' packet so everything ok haha

use OK to read the packet. i use this method to fix my dc problem last week.
![packet](https://user-images.githubusercontent.com/20220416/34475188-33c545ae-efbc-11e7-8e66-e4be70cdb838.png)

**Comment by sctnightcore** [comment]
**'00BF' => ['sync_request', 'a4', [qw(ID)]],**
Not sure .

**Comment by rastafara88** [comment]
@mfauziracing whats version ur XKore ? seems different with my xkore...

does xkore 3 working in idRO classic?

**Comment by mfauziracing** [comment]
no i cant, still stuck at login packet in IdRO classic >.< but @rastafara88 did with xkore 0 right?

xkore doesnt work in idRO classic. my pic just an exampe to detect wrong packet which cause dc. (i do it in renewal). i use the latest xkore gan @rastafara88.

**Comment by rastafara88** [comment]
how to know what type of Xkore? newbie here...haha

ok.. where i should tracing my problem?
very interesting to tracing.. but hate when got stuck the way to start tracking....lol

**Comment by mfauziracing** [comment]
in config.
> # 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
> XKore 3 <------------------------ type of xkore
> XKore_port 2350
> XKore_dll NetRedirect.dll
> XKore_autoAttachIfOneExe 1
> XKore_silent 1
> XKore_bypassBotDetection 1
> XKore_exeName ragexe.exe

edit config.txt, start your kore, wait until dc, and you will find the packet that make you dc.
> debug 1
> debugPacket_unparsed 1
> debugPacket_received 1
> debugPacket_ro_sent 1
> debugPacket_sent 1

**Comment by rastafara88** [comment]
ok thanks, so i just configure the Xcore type ya... i will try ya..

**Comment by rastafara88** [comment]
ok i have tried to debug using Xkore 0...

> You on route to: (): 273, 335
Route You Solution Ready!
Route You - next step moving to (273, 335), index 7, 8 steps left
Move You - (re)trying
Sent packet    : 035F    [ 5 bytes]  
<< Received packet:      0069 - Account Info [12 bytes]
You're moving from (270, 332) to (273, 335) - distance 4.2
<< Received packet:      0069 - Account Info [ 8 bytes]
Move You - (re)trying
Sent packet    : 035F    [ 5 bytes]  
<< Received packet:      0069 - Account Info [12 bytes]
You're moving from (270, 332) to (273, 335) - distance 4.2
<< Received packet:      0069 - Account Info [ 6 bytes]
Item Disappeared: Cyfar (0)
Target at (275,336) is now within 2.5 blocks; stop moving
Ready to attack target (which is 2 blocks away); we're at (273,335)
Sent packet    : 0089    [ 7 bytes]  [Attack / Sit / Stand]
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
<< Received packet:      0069 - Account Info [10 bytes]
<< Received packet:      0069 - Account Info [33 bytes]
[ 87/100] Monster Orc Archer (0) attacks you (Dmg: Miss!) (Delay: 620ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 293) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 328) (Delay: 160ms)
Sent packet    : 0360    [ 6 bytes]  
Sent packet    : 0089    [ 7 bytes]  [Attack / Sit / Stand]
<< Received packet:      0069 - Account Info [ 6 bytes]
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 295) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 312) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
Sent packet    : 0089    [ 7 bytes]  [Attack / Sit / Stand]
<< Received packet:      0069 - Account Info [10 bytes]
<< Received packet:      0069 - Account Info [33 bytes]
[ 87/100] Monster Orc Archer (0) attacks you (Dmg: Miss!) (Delay: 620ms)
<< Received packet:      0069 - Account Info [34 bytes]
Incremented missedFromYou count to 1
[ 87/100] You attack Monster Orc Archer (0) (Dmg: Miss!) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
<< Received packet:      0069 - Account Info [77 bytes]
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 318) (Delay: 160ms)
Sent packet    : 0089    [ 7 bytes]  [Attack / Sit / Stand]
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 327) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 292) (Delay: 160ms)
<< Received packet:      0069 - Account Info [10 bytes]
<< Received packet:      0069 - Account Info [33 bytes]
[ 87/100] Monster Orc Archer (0) attacks you (Dmg: Miss!) (Delay: 620ms)
Sent packet    : 0089    [ 7 bytes]  [Attack / Sit / Stand]
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 322) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 318) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
Incremented missedFromYou count to 2
[ 87/100] You attack Monster Orc Archer (0) (Dmg: Miss!) (Delay: 160ms)
Sent packet    : 0089    [ 7 bytes]  [Attack / Sit / Stand]
<< Received packet:      0069 - Account Info [34 bytes]
[ 87/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
<< Received packet:      0069 - Account Info [ 8 bytes]
<< Received packet:      0069 - Account Info [34 bytes]
[ 88/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
<< Received packet:      0069 - Account Info [10 bytes]
<< Received packet:      0069 - Account Info [33 bytes]
[ 88/100] Monster Orc Archer (0) attacks you (Dmg: Miss!) (Delay: 620ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 88/100] You attack Monster Orc Archer (0) (Dmg: 462!) (Delay: 160ms)
Sent packet    : 0089    [ 7 bytes]  [Attack / Sit / Stand]
<< Received packet:      0069 - Account Info [34 bytes]
[ 88/100] You attack Monster Orc Archer (0) (Dmg: 305) (Delay: 160ms)
<< Received packet:      0069 - Account Info [34 bytes]
[ 88/100] You attack Monster Orc Archer (0) (Dmg: 313) (Delay: 160ms)
<< Received packet:      0069 - Account Info [ 7 bytes]
Monster Died: Orc Archer (0)
<< Received packet:      0069 - Account Info [ 8 bytes]
<< Received packet:      0069 - Account Info [14 bytes]
<< Received packet:      0069 - Account Info [ 8 bytes]
You have gained 1729/1787 (0.12%/2.00%) Exp
<< Received packet:      0069 - Account Info [14 bytes]
<< Received packet:      0069 - Account Info [17 bytes]
<< Received packet:      0069 - Account Info [17 bytes]
<< Received packet:      0069 - Account Info [ 6 bytes]
Item Disappeared: Orcish Voucher (1)
Target died
You AI suspended by clientSuspend for 0.7 seconds
Disconnected from Map Server, connecting to Account Server in 30 seconds...

**Comment by sctnightcore** [comment]
0069?

**Comment by rastafara88** [comment]
whats wrong with 0069 ?

i suspect 2 codes

Sent packet : 035F [ 5 bytes] and Received packet: 0069 - Account Info [12 bytes] (the account info bytes looks different every occuring)


and where i should check in OK?

**Comment by sctnightcore** [comment]
sniff !!!! packet !!!

**Comment by rastafara88** [comment]
this is funny,, it's working now without kicked disconnecting... lol

already 10 minutes running... will update in here if OK running for 1 or 2 hours..

still observe..

**Comment by rastafara88** [comment]
ok it's working fine till now... 2 hours running...

i dont know what happen... but its working without DC.. i will closed it...

**Comment by mfauziracing** [comment]
wahaha good 👍🏻👍🏻. you are lucky boy.
