### ISSUE TITLE
kRO:Zero The server has denied your connection

### ISSUE THREAD

**Issue by kimssww** [OpenKore/openkore#1565]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 
계정 서버에 connecting...
연결 중 (112.175.128.137:6950)... 연결되었습니다. connect
연결 중 (112.175.128.135:6900)... 연결되었습니다. connect
종료 중 (112.175.128.135:6900)...종료되었습니다. exit

I entered ID and password. I don't know why not.
I guess there are 3 servers but I do not have one source to choose from.

**Comment by sctnightcore** [comment]
kRO:Zero | New Korea server | Need unpack,recvpacket,sync,key | 
1. cannot unpack 2.cannot find packet key 3.cannot find recvpacket
4.cannot redirect connection to local host to use poseidon.
