### ISSUE TITLE
Can't loot anything as of last update 24hr ago.

### ISSUE THREAD

**Issue by ninthkeys** [OpenKore/openkore#1568]
###### Affected configuration(s)/ file(s):
#pickupitems.txt
all 1
jellopy 0
sticky mucus 0
fluff 0

#config.txt
itemsTakeAuto 1
itemsTakeAuto_party 0
itemsGatherAuto 1
itemsMaxWeight 0
itemsMaxWeight_sellOrStore 48
itemsMaxNum_sellOrStore 0
cartMaxWeight 7900
itemsTakeAuto_new 1
itemsTakeGreed 1

###### Steps to Reproduce: No idea. Have not tampered with these lines in a long time.

**Comment by sctnightcore** [comment]
http://openkore.com/index.php/ItemsTakeAuto
http://openkore.com/index.php/Pickupitems.txt

**Comment by fadreus** [comment]
Try `@autoloot`

**Comment by sctnightcore** [comment]
@fadreus  lol

**Comment by alisonrag** [comment]
as i can see in the last 3 days we didn't changeg nothing about pick items
![image](https://user-images.githubusercontent.com/10372732/34438456-3b1473e2-ec8e-11e7-93e9-b5bd7bca5cd3.png)

**Comment by fadreus** [comment]
@sctnightcore 
No idea, Just fishing him (sarcasm) with his server information since there is no recent PR related to items or pickup. So I thought maybe his RO had an update or something since he deny any changes made on his openkore (so no update?) & he also being vague about his openkore version (until now, last update, long time ago).

If a math question sound like this;
```
This is 9th Keys.
He have an apple until now but without any changes since last winter, his apple gone.
He have been here from long time ago."

Determine the time 9th receive an apple.
```

**Comment by sctnightcore** [comment]
ROFL

**Comment by ninthkeys** [comment]
Playing on Restart server. Seasonal event items are dropping but OpenKore is not picking up anything, even non-event items. Also having a small issue where OpenKore is looping where bot places seasonal item "unknown" into cart, then immediately withdraws it back to inventory, then deposits into cart. Have to almost everything is related to seasonal items.

**Comment by Pachu1985** [comment]
itemsMaxWeight 0

From OpenKore wiki:
When your weight is greater than the one specified, Kore will not take or gather any items.

**Comment by alisonrag** [comment]
update:
itemsMaxWeight 0

to
itemsMaxWeight 49
