### ISSUE TITLE
Items control issues

### ISSUE THREAD

**Issue by TheDrakenZ** [OpenKore/openkore#1571]
Not sure if this has been addressed or not, but there are a lot of incorrectly labeled items in the items control file.

2406 0 0 1 # Boots
2104 0 0 1 # Buckler ---- both labeled as the unslotted versions, but they're using the slotted item id's.

2310 0 0 1 # Coat
2310 0 0 1 # Coat [1] ---- unslotted and slotted version, both have the same id, so its storing unslotteds.

2102 0 0 1 # Guard --- selling slotted guards to the npc.

2209 0 0 1 # Ribbon
2209 0 0 1 # Ribbon [1] -- same IDs for slotted vs unslotted

2402 0 0 1 # Sandals
2402 0 0 1 # Sandals [1] -- again same IDs so it stores the unslotted sandals.

2333 0 0 1 # Silver Robe
2333 0 0 1 # Silver Robe [1] - etc

2329 0 0 1 # Wooden Mail
2329 0 0 1 # Wooden Mail [1] - etc

2336 0 0 1 # Thief Clothes -- auto sell that junk slotted thief clothes hahahah. :sa: 

Just curious what everyone thought of this, definitely just threw me for a loop.

**Comment by fadreus** [comment]
Btw, Do people still using those stuff? Hahahaha...
That was like ancient stuff..
XD

**Comment by TheDrakenZ** [comment]
Apparently people think that slotted bucklers, slotted guards, slotted helms and slotted thief clothes are all examples of garbage drops, good thing the bot auto sells them....

**Comment by Nipodemos** [comment]
Ohhhhhhhh, that's interesting
yeah these equips are sold to npc by default, but the labels are incorrect, I'll check that today to see if I can fix this (although is just an visual issue, don't affect the openkore)

**Comment by TheDrakenZ** [comment]
O_O pretty sure its not just a visual issue, my bots have been on kobolds for 3 days, got many cards but its been npc'ing all the 3s glads and the 1s bucklers, while it stores unslotted guards because the slotted ones are set to auto sell in the items control. I checked the ID's with RMS too, 2336 is slotted thief clothes, and items control is npc'ing them.

**Comment by alisonrag** [comment]
Just set to store :)

**Comment by alisonrag** [comment]
We will work in this and try to change

**Comment by TheDrakenZ** [comment]
cool sounds good. just happy to contribute.

**Comment by Nipodemos** [comment]
Hey @TheDrakenZ
could you please send here, which ones you think that should've be changed? Like, what IDs are selling that should store, and those that are missing here and should have
Don't need to be all of them, but each one will make, is already a good thing 
You can post it here, or you can send a pull request with the changes :-)

**Comment by TheDrakenZ** [comment]
I'll definitely do that, tomorrow probably. New years party to be had tonight. hahah

**Comment by Nipodemos** [comment]
just remembering, openkore store the ones that are not wroted there.

so you just need to make the ones that will sell to npc


## happy new year!!!

**Comment by TheDrakenZ** [comment]
##### WORTHLESS GEARS #####
# Worthless gears which are sold by default

2306 0 0 1 # Adventurer's Suit
2211 0 0 1 # Bandana
2217 0 0 1 # Biretta
2405 0 0 1 # Boots
2103 0 0 1 # Buckler
2227 0 0 1 # Cap
2314 0 0 1 # Chain Mail
2233 0 0 1 # Circlet
2309 0 0 1 # Coat
2310 0 0 1 # Coat [1]
2302 0 0 1 # Cotton Shirt
Cotton Shirt [1] 0 0 1
#Crystal Pumps 0 0 1
2613 0 0 1 # Diamond Ring
2205 0 0 1 # Diver Goggles
2212 0 0 1 # Eye Patch
2612 0 0 1 # Flower Ring
2219 0 0 1 # Flu Mask
2316 0 0 1 # Full Plate
2231 0 0 1 # Gemmed Sallet
2204 0 0 1 # Glasses
2610 0 0 1 # Gold Ring
2101 0 0 1 # Guard
2210 0 0 1 # Hair Band
2221 0 0 1 # Hat
2228 0 0 1 # Helm
2409 0 0 1 # High Heels
2501 0 0 1 # Hood
2502 0 0 1 # Hood [1]
2303 0 0 1 # Jacket
2304 0 0 1 # Jacket [1]
2505 0 0 1 # Manteau
2307 0 0 1 # Mantle
2308 0 0 1 # Mantle [1]
2107 0 0 1 # Mirror Shield
2278 0 0 1 # Mr. Smile
2503 0 0 1 # Muffler
2313 0 0 1 # Padded Armor
2371 0 0 1 # Pantie
2208 0 0 1 # Ribbon
2209 0 0 1 # Ribbon [1]
2840 0 0 1 # Rosary
2325 0 0 1 # Saint's Robe
2401 0 0 1 # Sandals
2402 0 0 1 # Sandals [1]
2323 0 0 1 # Scapulare
2408 0 0 1 # Shackles
2105 0 0 1 # Shield
2403 0 0 1 # Shoes
2321 0 0 1 # Silk Robe
2611 0 0 1 # Silver Ring
2332 0 0 1 # Silver Robe
2333 0 0 1 # Silver Robe [1]
2715 0 0 1 # Skull Ring
2335 0 0 1 # Thief Clothes
2330 0 0 1 # Tights
2223 0 0 1 # Turban
2328 0 0 1 # Wooden Mail
2329 0 0 1 # Wooden Mail [1]


Those were my revised changes for myself:
slotted versions of thief Clothes, Tights, shoes, shield, boots, muffler, manteau, helm, buckler, chainmail and guard  were all being sold and the non slotted versions were being stored. I changed the item ID's accordingly.

**Comment by Nipodemos** [comment]
oh thank you for the changes!!
do you know how to make a pull request? with this your changes would be permanent added to the main repository

if you don't know how to do it, and don't want to learn, i can do it for you, and put your credits of coursee

**Comment by TheDrakenZ** [comment]
Sure, I'll give it a try. Thank you! :D

**Comment by TheDrakenZ** [comment]
Actually nevermind, i'd appreciate you doing it hahaha

**Comment by Nipodemos** [comment]
done 😄 thank you for this update!

**Comment by TheDrakenZ** [comment]
Happy to help! :D

**Comment by TheDrakenZ** [comment]
@Nipodemos  Sorry, I just realized I forgot one. -- Adventurer's Suit should be 2305 not 2306.

**Comment by Nipodemos** [comment]
no problem :smile:
