### ISSUE TITLE
After the update, the language of Openkore has changed.

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#1575]
Hello. After the update, the language of Openkore has changed.
sys.txt:

`
locale English
`

But i see:
![125151251251251lang](https://user-images.githubusercontent.com/20753532/34459530-563325da-ee03-11e7-8d24-0ff897fb1be7.jpg)

**Comment by alisonrag** [comment]
`locale en`

**Comment by Glikadin** [comment]
@alisonrag Thx you!

**Comment by Glikadin** [comment]
I trying:
```
locale en
locale En
locale EN
locale English
locale ENGLISH
```
Its not work. I still get Russian lanuage T__________T

**Comment by lututui** [comment]
Version, please

**Comment by Glikadin** [comment]
Last version. Download 10 hours ago from  GitHub

**Comment by fadreus** [comment]
`locale eng` tried that?

**Comment by Glikadin** [comment]
locale eng
locale Eng
locale ENG
Not work too.
My system Windows 7. local time UTC + 03

**Comment by fadreus** [comment]
I tested current version
Using `locale <blank>` = sys default.
Using `local ru` = appear as yours.
Using `local en` = appears in English.

All seems fine in Win 8.1 UTC+8.
Not sure if it kore or your comp.
But have you tried using previous version?
<details>
<summary>Especially from 3 days ago.</summary>

If it still persist, prolly your comp?
If it your comp, try run on different comp.
If other appear the same, your version prob.
Start clean from anew might help xD
Hahahaha..

</details>

**Comment by Glikadin** [comment]
I just delete the last update. Thx

**Comment by Glikadin** [comment]
I found solution:
openkore.pl:
`
40                   Translation::initDefault('en');
`

**Comment by lututui** [comment]
That makes absolutely no sense
