### ISSUE TITLE
cRO client disconnected

### ISSUE THREAD

**Issue by sonsonpan** [OpenKore/openkore#1577]
## hi,i just fellow the guide to set openkore and cRo client,but failed : ( 
 i close  firewall and use VM but nothing changed.Can any guys help me,THX :D
![qq 20171231192958](https://user-images.githubusercontent.com/34977289/34461344-c4e33d04-ee61-11e7-8b8c-26a5445391b4.png)

**Comment by alisonrag** [comment]
![image](https://user-images.githubusercontent.com/10372732/34462151-13b9bc7a-ee24-11e7-8a9b-80858209acd9.png)

working fine with latest version of openkore and cRO

**Comment by alisonrag** [comment]
download the latest version of openkore
you can use src\poseidon\poseidon.pl in the same machine of ragexe

**Comment by sonsonpan** [comment]
> you can use src\poseidon\poseidon.pl in the same machine of ragexe
Thank you@alisonrag i succeed in login Poseidon . 
But a few minutes later,bad things happend just like that. GameGurad finds an illegal program,and makes me offine. 
![qq 20171231230449](https://user-images.githubusercontent.com/34977289/34462493-3cc967f8-ee80-11e7-8f70-47e7cc1dc365.png)

**Comment by alisonrag** [comment]
Need to use openkore in vm

**Comment by alisonrag** [comment]
Or use Openkore.pl in PowerShell terminal

**Comment by sonsonpan** [comment]
@alisonrag > use Openkore.pl in PowerShell terminal

> 
First，thank you very much for helping me ,but,PowerShell can't help me.Should try VM? or other way?
![qq 20180101094517](https://user-images.githubusercontent.com/34977289/34465080-ebe98c42-eed8-11e7-98bc-1bc1c2882f22.png)

**Comment by sctnightcore** [comment]
Open Openkore in power shell too.

**Comment by sonsonpan** [comment]
> Open Openkore in power shell too.

WELLDONE，THX for you all and happy new year !@alisonrag @sctnightcore
