### ISSUE TITLE
RO:Restart error wont open new/old openkore files

### ISSUE THREAD

**Issue by rvd0998** [OpenKore/openkore#1579]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details: i was gone for a week and downloaded the new openkore but it wont open and when i used my old openkore files it will only connect to character select but will timeout on servermap please help me
![error 3](https://user-images.githubusercontent.com/30879696/34463582-dae0c20c-ee25-11e7-9ab8-b8c74cf5d442.png)
![openkore error](https://user-images.githubusercontent.com/30879696/34463583-dcfddc96-ee25-11e7-867b-2e330a73ed7c.png)
![openkore error](https://user-images.githubusercontent.com/30879696/34463584-df3efc10-ee25-11e7-9947-e98bdf78a2cd.png)

**Comment by rvd0998** [comment]
nobody wants to help

**Comment by lututui** [comment]
It looks like something got deleted or corrupted? Master branch is fine.

**Comment by rvd0998** [comment]
I’ve downloaded the new one a couple of times idk what’s wrong with it. Can u post a link file on where to download the master branch I’m not sure if im downloading it right please help

**Comment by fadreus** [comment]
@rvd0998 
![image](https://user-images.githubusercontent.com/32188494/34465502-9e33f17e-eeea-11e7-9b3d-fcc1bb4864bc.png)

**Comment by rvd0998** [comment]
there was something wrong with my winrar i fixed it using a different one
