### ISSUE TITLE
tRO connectivity, #221 duplicate

### ISSUE THREAD

**Issue by GioFen** [OpenKore/openkore#158]
[Thailand - tRO EXE]
ip 103.55.55.12
port 6900
master_version 7
version 24
serverType tRO
secureLogin 3
secureLogin_type 0
secureLogin_account 0
patchserver wpatch.ragnarok.in.th
patchpath /patch70
serverEncoding Thai
addTableFolders tRO
charBlockSize 112
gameguard 1

**Comment by tignoname** [comment]
it not work for me
how to fix

**Comment by tignoname** [comment]
how to by pass EAC.

**Comment by wizarady** [comment]
![image](https://cloud.githubusercontent.com/assets/20181940/17266054/65b051be-561e-11e6-9fe7-3f4490d69ccf.png)   ???

**Comment by bomteamza** [comment]
Hi, I need to start now. Ragnarok bot to understand now, I know I need to fix the IP, then I have to go up against it now. Thank you very much
![2](https://cloud.githubusercontent.com/assets/20739525/17270774/478bbe9a-5695-11e6-8df3-c1be52a29eae.jpg)

**Comment by totti100** [comment]
![rag2](https://cloud.githubusercontent.com/assets/22409601/18807956/e885e072-827e-11e6-8e48-98731a7244b0.png)
any expert pls suggest 
x0 win32

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
