### ISSUE TITLE
anyone can help? idro_renewal valhalla server. always timeout on account server

### ISSUE THREAD

**Issue by rucan** [OpenKore/openkore#1580]
halo anyone can help me fix this.
 idro_renewal valhalla server. always timeout on account server.
tell me where the problem
thank a lot

**Comment by sctnightcore** [comment]
Use with xkore1 and xkore3

**Comment by rucan** [comment]
where can i use that xkore 1 and xkore 3
because i am newbie with this program

**Comment by rucan** [comment]
![eror](https://user-images.githubusercontent.com/34993334/34465814-71f26a34-eef2-11e7-804b-faa42379a33e.jpg)

**Comment by sctnightcore** [comment]
http://openkore.com/index.php/XKore
