### ISSUE TITLE
HI i want ask anyone can help me to setup mysgro? my xkore cannot connect with client. im stuck

### ISSUE THREAD

**Issue by Fazliyusof89** [OpenKore/openkore#1584]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
No dev of mRO .

**Comment by Fazliyusof89** [comment]
owh like that.. if anyone can help to develop this issue i facing can tell me. im try to run xkore and try to inject mysg client sudennly disconnected. anyone?
