### ISSUE TITLE
Buying Yellow Potions make kore disconnect

### ISSUE THREAD

**Issue by iamtonysoft** [OpenKore/openkore#1587]
###### Summary: 
![yellow](https://user-images.githubusercontent.com/23303913/34524719-82e0ba26-f0d7-11e7-8c6d-286e14ff2be6.png)

###### Affected configuration(s)/ file(s):
Disconnect if it was like this
`
buyAuto Yellow Potion {
	maxAmount 100
	minAmount 0
	npc 
	distance 8
}
`

Works if it was like this
`
buyAuto Yellow potion {
	maxAmount 100
	minAmount 0
	npc 
	distance 8
}
`
###### Steps to Reproduce:
autobuy

**Comment by alisonrag** [comment]
what is the difference?

**Comment by sctnightcore** [comment]
p and P XD

**Comment by iamtonysoft** [comment]
uhhmm yes only the letter `p` and `P` dunno why my bot disconnect.

**Comment by fadreus** [comment]
Now that you mention it, Renewal also have small `p` for yellow potion.
But haven't try yet if it also disconnect,

**Comment by lututui** [comment]
The store is selling ```Yellow potion```, not ```Yellow Potion```

**Comment by iamtonysoft** [comment]
So it means the function buyAuto also accepts case sensitive ? 
and the data with a small case `Yellow potion` coming from or cause by game client ? 🤔

**Comment by lututui** [comment]
So, I found out buyAuto is case insensitve, so this should be working.

Can you set ```debugPacket_sent 2``` in config.txt and send a log or screenshot of the disconnection moment?

**Comment by iamtonysoft** [comment]
@lututui 
![dc](https://user-images.githubusercontent.com/23303913/34776150-c7446338-f650-11e7-8199-1a62bd692c65.png)

**Comment by lututui** [comment]
Which server is this?

**Comment by iamtonysoft** [comment]
@lututui iRO:Restart

**Comment by lututui** [comment]
`BB 5C 08 00 00 00 F7 01`
which breaks down to
5C BB -> 00C8 -> Buy packet
00 08 -> Which is the amount of different items we're trying to buy, in the format 4+4*amountOfDifferent items -- in this case 4+4*1 => 8
00 00 -> Which should be the amount. **For some reason, we're trying to buy zero items -- this must be the disconnect source.**
01 F7 -> 503, which is the item id - Yellow Potion

**Comment by lututui** [comment]
Does #1622 have any effect on this?

**Comment by iamtonysoft** [comment]
i was trying to buy the amount of 100 `Yellow Potion`

**Comment by lututui** [comment]
Does #1622 have any effect on this?

**Comment by lututui** [comment]
So #1622 fixes this?
