### ISSUE TITLE
iro restart timeout on map server

### ISSUE THREAD

**Issue by nunops** [OpenKore/openkore#1588]
After today's update my bots cannot connect to iro restart server. I already tried to download the lastest updated client but somehow i got timeout on map server. Someone else having this same issue and how to solve it?

**Comment by nunops** [comment]
![korefail](https://user-images.githubusercontent.com/13694416/34544140-a228d1c2-f0cb-11e7-9d74-927d226b1dda.jpg)

**Comment by sctnightcore** [comment]
wait

**Comment by alisonrag** [comment]
why some peoples can wait for @allanon update? '-'

**Comment by nunops** [comment]
it's not a matter of patience, i just wanna learn how to fix that issue.

**Comment by sctnightcore** [comment]
ez fix = wait allanon .

**Comment by alisonrag** [comment]
@nunops 
you can do it by yourself if you know how to use this script:
https://gist.github.com/allanon/d8181ceaf6380da6d8fa4fddf1885706

**Comment by sctnightcore** [comment]
PR #1587
