### ISSUE TITLE
Problem with tRO

### ISSUE THREAD

**Issue by sailomsaengdaed** [OpenKore/openkore#159]
1. Openkore send packet 01 DB (secure_login_key_request) to  Server But Server not respond.
    But ragexe.exe don't send this packet 
2. I don't have $salt and $type to encrypt password
3. in src/Network/Send/ServerType0.pm to fixed length for user and password

(I by pass secure_login_key_request and i use function sendMasterSecureLogin)

    '0A76' => ['master_login', 'V Z24 Z48 C', [qw(version username password master_version)]],
    example
00000000  76 0a 18 00 00 00 74 65  73 74 69 6e 67 00 00 00   v.....te sting...
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 ae 2b   ........ .......+
00000020  1f ca 51 59 49 e5 d5 4f  b2 2b 8e d9 55 75 00 00   ..QYI..O .+..Uu..
00000030  00 00 00 00 00 00 00 07  00 00 00 00 00 00 00 00   ........ ........
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........

Connect failed, something is wrong with the login settings:\n
version: 24
master_version: 7
serverType: tRo

I think because master isn't last 2 byte

and master verion is behind password 1 byte 
format is 76 01 18 00 00 00  (username 23 byte) 00 (password 23 byte ) 00 mastervertion 00

if i set 
    '0A76' => ['master_login', 'V Z24 Z48 C', [qw(version username password master_version)]],
00000000  76 0a 18 00 00 00 74 65  73 74 69 6e 67 00 00 00   v.....te sting...
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 ae 2b   ........ .......+
00000020  1f ca 51 59 49 e5 d5 4f  b2 2b 8e d9 55 75 00 00   ..QYI..O .+..Uu..
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 07 00   ........ ........
Openkore ask new userid id
format is 76 01 18 00 00 00  (username 23 byte) 00 (password 47 byte ) 00 mastervertion 00

But ragexe is 
00000000  76 0a 18 00 00 00 74 65  73 74 69 6e 67 00 77 00   v.....te sting.w.
00000010  00 00 17 01 00 00 0b 01  00 00 16 01 00 00 7a 00   ........ ......z.
00000020  00 00 7a 00 00 00 7b 00  00 00 0b 01 00 00 a4 50   ..z...{. .......P
00000030  af 15 e2 44 72 03 5d 5c  79 be 13 26 17 3e d2 fc   ...Dr.]\ y..&.>..
00000040  e8 d7 5a 36 02 4a 76 16  43 06 87 21 ce bb 07 00   ..Z6.Jv. C..!....

usernamd and password far is 1 byte

and master verion is stay last 2 byte 

If I copy packet from ragexe.exe to send by Openkore it login success
in function reconstruct
	$packet=chr(0x76).chr(0x0a).chr(0x18).chr(0x0).chr(0x0).chr(0x0).chr(0x77)....

    '0A76' => ['master_login', 'V n/a n/a C', [qw(version username password master_version)]],

**Comment by sailomsaengdaed** [comment]
password had been evey day??????
This day.
00000000  76 0a 18 00 00 00 74 65  73 74 69 6e 67 31 32 33   v.....te sting123
00000010  00 a9 a9 a9 a9 a9 a9 a9  a9 a9 a9 a9 a9 a9 a9 a9   ........ ........
00000020  a9 a9 a9 a9 a9 a9 a9 a9  a9 a9 a9 a9 a9 a9 67 28   ........ ......g(
00000030  3a 61 18 a7 d5 da 26 48  16 cd 3e 70 20 5d dc fe   :a....&H ..>p ]..
00000040  e9 ea 65 e4 7b 51 37 36  0f 8d b2 36 37 dd 07 00   ..e.{Q76 ...67...

**Comment by sailomsaengdaed** [comment]
Character have problem.
I force to send packet login.
I can connect to server and character.
Server send charater info to me but Operkore dosen't recive charater info this picture
![character](https://cloud.githubusercontent.com/assets/20695708/17269096/97fd28cc-5669-11e6-9013-108fb20a9a4d.jpg)
But The packet is
00000000  75 02 20 f5 3b 00 78 54  00 00 01 00 00 00 00 00 u. .;.xT ........
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 ........ ........
00000020  00 0c 00 00 00                                   .....
    00000000  20 f5 3b 00                                       .;.
    00000004  2d 08 1d 00 06 00 00 06  06 00 00 00 00 00 00 00 -....... ........
    00000014  00 00 00 00 00 00 00 00  00 00 00 00 00 a0 09 02 ........ ........
    00000024  00 00 00                                         ...
00000025  a1 09                                            ..
00000027  a1 09                                            ..
    00000027  9d 09 94 00 aa 4a 05 00  63 04 00 00 0e 03 00 00 .....J.. c.......
    00000037  d4 05 00 00 09 00 00 00  00 00 00 00 00 00 00 00 ........ ........
    00000047  00 00 00 00 00 00 00 00  00 00 00 00 01 00 51 00 ........ ......Q.
    00000057  00 00 39 01 00 00 3a 00  3a 00 96 00 06 00 01 00 ..9...:. :.......
    00000067  00 00 18 00 00 00 00 00  00 00 00 00 00 00 00 00 ........ ........
    00000077  00 00 cb c7 d2 b9 a4 d0  00 00 00 00 00 00 00 00 ........ ........
    00000087  00 00 00 00 00 00 00 00  00 00 14 1b 01 01 12 01 ........ ........
    00000097  00 00 00 00 6d 6f 63 5f  66 69 6c 64 30 39 2e 67 ....moc_ fild09.g
    000000A7  61 74 00 00 00 00 00 00  00 00 00 00 00 00 00 00 at...... ........
    000000B7  00 00 00 00                                      ....
    000000BB  b9 08 0c 61 4a 0b 20 f5  3b 00 01 00             ...aJ. . ;...

**Comment by solomnotao** [comment]
You Set table/server.txt

>> charBlockSize 144 

then look at character again!

**Comment by GioFen** [comment]
How to bypass the secure_login_key_request function?
When i commend this command, i get to error message " Can't reconstruct unknown packet: secure_login_key_request at src/network/Packerparser.pm line 179

**Comment by sailomsaengdaed** [comment]
in src/network/Packerparser.pm line 378
				if ($code ne '') {
					$messageSender->sendToServer($messageSender->reconstruct({
						switch => 'client_hash',
						code => $code,
					}));
				} elsif ($master->{secureLogin_type}) {
					$messageSender->sendToServer($messageSender->reconstruct({
						switch => 'client_hash',
						type => $master->{secureLogin_type},
					}));
				}
				$messageSender->sendToServer($messageSender->reconstruct({
					switch => 'secure_login_key_request',
				}));

			}
change to
			if($config{'serverType'} == 'tRO'){
				my $master = $masterServer;
					message T("Sending encoded password...\n"), "connection";
					$messageSender->sendMasterSecureLogin1($config{'username'}, $config{'password'}, $secureLoginKey,
							$master->{version}, $master->{master_version},
							$master->{secureLogin}, $master->{secureLogin_account});
					undef $secureLoginKey;
			}else{
				if ($code ne '') {
					$messageSender->sendToServer($messageSender->reconstruct({
						switch => 'client_hash',
						code => $code,
					}));
				} elsif ($master->{secureLogin_type}) {
					$messageSender->sendToServer($messageSender->reconstruct({
						switch => 'client_hash',
						type => $master->{secureLogin_type},
					}));
				}
				$messageSender->sendToServer($messageSender->reconstruct({
					switch => 'secure_login_key_request',
				}));

			}

**Comment by sailomsaengdaed** [comment]
tables/server.txt
add pinCode 1 to 

[Thailand - tRO Main server (EXE)]
ip 103.55.55.12
port 6900
master_version 7
version 24
serverType tRO
secureLogin 3
secureLogin_type 0secureLogin_account 0
patchserver wpatch.ragnarok.in.th
patchpath /patch70
serverEncoding Thai
addTableFolders tRO
charBlockSize 144
gameguard 1
pinCode 1

**Comment by codepushr** [comment]
Please use proper markdown syntax so the code gets more readable! 😎

**Comment by Cozzie** [comment]
Duplicate #221.
