### ISSUE TITLE
(RO MYSG) Ragnarok Online Client not connecting to XKore

### ISSUE THREAD

**Issue by LangrB** [OpenKore/openkore#1591]
Hey guys,

I've been trying to figure out how to get OpenKore to work for the newly launched RO MYSG server. I've gotten quite far but am encountering a problem whereby when I start wxstart.exe and then launch Ragnarok, I get this message:

"Please start the Ragnarok Online client (ragexe.exe)
Ragnarok Online client found, pid = 2350
Waiting for the Ragnarok Online client to connect to X-Kore..."

And it just stops there. After that, OpenKore just freezes and says Not Responding. 

If I run 'Start' instead of 'wxstart', it'll show the same message and ragexe.exe still doesn't connect to X-Kore for some reason.

Anyone got a solution for this? 

Thanks in advanced.

**Comment by sctnightcore** [comment]
No dev of mRO

**Comment by Youtouchmytralala** [comment]
There is no working OK here for MYSG.

**Comment by premier91** [comment]
Do u guys have guidelines that I can follow to "atleast" develop this server?
