### ISSUE TITLE
antibot

### ISSUE THREAD

**Issue by TIKIJNE** [OpenKore/openkore#1592]
anyone can help me with this antibot

![a](https://user-images.githubusercontent.com/35103635/34575607-ee02cf70-f1ad-11e7-80a0-8cdbd31d42b0.png)
![b](https://user-images.githubusercontent.com/35103635/34575612-efeef084-f1ad-11e7-884d-b4b736e593cd.png)
![c](https://user-images.githubusercontent.com/35103635/34575616-f284fc44-f1ad-11e7-9a80-c5788dd4755e.png)

im using this
```
reactOnNPC talk num @eval (my $color = '#1~1'@;my @@array = ('#4~1', '#4~3', '#4~5'@);my $answer;for ($a = 0;$a < 3;$a+1@) { if (@@array[$a] eq $color2) {$answer =  @@array[$a]} else {$a += 1;} return $answer);
type number
useColors 1
delay 2
msg_0 /\^[0-9a-z]{6}RO Guard\^[0-9a-z]{6}/i	
msg_1 /\"?Please enter the (\^[0-9a-z]{6})(.\w+)RED COLOUR NUMBER\^[0-9a-z]{6}\"?\./i
msg_2 /\^[0-9a-z]{6}RO Guard\^[0-9a-z]{6}/i
msg_3 /Number \:/i
msg_4 /\d+\^([0-9a-fA-F]{6})(\d+)\^[0-9a-fA-F]{6}\d+/


```

but cant enter the number

**Comment by Nipodemos** [comment]
can you please show us a print of this message inside openkore? to see how it shows there

**Comment by alisonrag** [comment]
3 days without a response of owner, and this is not a issue.
