### ISSUE TITLE
tRo How to by pass EAC

### ISSUE THREAD

**Issue by tignoname** [OpenKore/openkore#160]
![image](https://cloud.githubusercontent.com/assets/10294281/17260872/fed9326a-55fc-11e6-9196-170a5d338547.png)

How to by pass EAC
who passed this step plz answer me plzzzzzzz.

**Comment by bomteamza** [comment]
Hi, I need to start now. Ragnarok bot to understand now, I know I need to fix the IP, then I have to go up against it now. Thank you very much

**Comment by AmenoMissaki** [comment]
Server.txt

## www.ragnarok.in.th/

[Thailand - tRO Main server (EXE)]
ip 103.55.55.12
port 6900
master_version 7
version 24
serverType tRO
secureLogin 3
secureLogin_type 0
secureLogin_account 0
secureLogin_requestCode
pauseCharServer 1
patchserver wpatch.ragnarok.in.th
patchpath /patch70
serverEncoding Thai
addTableFolders tRO
charBlockSize 144
gameguard 1

You do Try

**Comment by AmenoMissaki** [comment]
Confix.txt

master Thailand - tRO Main server (EXE)
server
username
password
loginPinCode
char 1

# Poseidon Settings (http://wiki.openkore.com/index.php/PoseidonServer)
# They must be the same as Query Server config in Poseidon.txt
poseidonServer 127.0.0.1
poseidonPort 24390

bindIp
forceMapIP

# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore

XKore 3
XKore_3_gameServer 0 <<<Here Number You want At Server Bot (Iris = 0 chaos = 1  Odin = 2 Loki = 3 Thor = 4)
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe


# XKore 2 / Proxy configuration
XKore_listenIp 127.0.0.1
XKore_listenPort 6901
XKore_publicIp 127.0.0.1
XKore_ID

**Comment by AmenoMissaki** [comment]
And the you don't forget Hide Process Program Chales & Openkore

**Comment by AmenoMissaki** [comment]
Hide Process Use Sure and Os Windows XP SP3 32 Bit & Windows 7 32Bit

**Comment by itsrachelfish** [comment]
@AmenoMissaki Could you please submit these changes in a pull request? We'd love to have tRO working again by default. :smiley:
