### ISSUE TITLE
kRO Zero support

### ISSUE THREAD

**Issue by inorang** [OpenKore/openkore#1600]
Your Ragnarok Online server uses GameGuard. In order to support GameGuard, you must use the Poseidon server. Please read http://wiki.openkore.com/index.php?title=Poseidon for more information.
종료 중 (112.175.130.32:10008)...종료되었습니다.

![image](https://user-images.githubusercontent.com/35145083/34617936-62e5c8ce-f280-11e7-88e4-66bbaf04642b.png)

**Comment by sctnightcore** [comment]
https://discord.gg/aWfnKX5

come here

**Comment by alisonrag** [comment]
you must use poseidon '-'
