### ISSUE TITLE
kRo:zero filed08b error

### ISSUE THREAD

**Issue by fromsantorini** [OpenKore/openkore#1607]
![2018-01-07 23 36 48](https://user-images.githubusercontent.com/1477253/34650435-ae2b50d0-f404-11e7-969c-0d2bc14cff5f.png)
![111](https://user-images.githubusercontent.com/1477253/34650438-b05b93d8-f404-11e7-9c84-835b04b85424.png)

**Comment by comwhat** [comment]
한국분인가..접속해결하셧나요?  poseidon 으로 안되서리 --;;

**Comment by tedrun** [comment]
have the same problem

**Comment by alisonrag** [comment]
use this branch
https://github.com/alisonrag/openkore/tree/kRO-Zero-update

**Comment by fromsantorini** [comment]
Thanks. I'll test it.

**Comment by sctnightcore** [comment]
https://discord.gg/aWfnKX5
come here .

**Comment by alisonrag** [comment]
fixed in #1603
