### ISSUE TITLE
My bot didnt want store the loot

### ISSUE THREAD

**Issue by lalilulelo1** [OpenKore/openkore#1611]
Hello good day,
i have a problem with my bot didnt want to store the loot i got
i used stalker to farm zeny n the loot (c.mace and r.ori)
and when my stalker go back to kafra, the bot alrd talked to kafra and open the storage (pay 500zeny)
but the problem is the bot didnt want to store the loot, and keep repeating talk to kafra and open storage lol
here is my configuration
[config.txt](https://github.com/OpenKore/openkore/files/1610829/config.txt)
[items_control.txt](https://github.com/OpenKore/openkore/files/1610830/items_control.txt)
[pickupitems.txt](https://github.com/OpenKore/openkore/files/1610831/pickupitems.txt)
![storage](https://user-images.githubusercontent.com/32214970/34662068-8111ead8-f480-11e7-8b46-10447d2a01b2.png)

thanks before

**Comment by sctnightcore** [comment]
```
Crimson Mace [2] 1 1 0
Crimson Mace [Holy] [2] 1 1 0
Crimson Mace [Fire] [2] 1 1 0
Crimson Mace [Ice] [2] 1 1 0
Crimson Mace [Earth] [2] 1 1 0
Crimson Mace [Darkness] [2] 1 1 0
```

PS. rem is best

**Comment by lalilulelo1** [comment]
@sctnightcore trying it, but the bot still didnt want to open the storage
still stuck at choose main storage
and when i manually choose the main storage option, the bot automatically trying to store all the item in inventory (like items from eden group),
and didnt want to store all of c.mace, only r.ori could be stored..
@.@

**Comment by sctnightcore** [comment]
**storageAuto_npc_steps p r1 n**
c r1 r0 n ?

**Comment by lalilulelo1** [comment]
Ok i try it again later at home
Oh yes, where should i put that crimson mace [2] 1 1 0 setting?
In items.txt or pickup items.txt?
Im afraid if i put it in the wrong place, the bot wont pickup the mace,
only put the mace in storage

**Comment by Nipodemos** [comment]
maybe if you insert inside quotes
```perl
"Crimson Mace [2]" 1 1 0
"Crimson Mace [Holy] [2]" 1 1 0
"Crimson Mace [Fire] [2]" 1 1 0
"Crimson Mace [Ice] [2]" 1 1 0
"Crimson Mace [Earth] [2]" 1 1 0
"Crimson Mace [Darkness] [2]" 1 1 0
```

if i do remember correctly, openkore has problems to detect it when the name of item contains numbers

### or

you could use the id of item

**Comment by lalilulelo1** [comment]
the real problem is the bot wont open the storage
![storage](https://user-images.githubusercontent.com/32214970/34676026-ef92c59e-f4bd-11e7-8507-c1c55d8257ae.png)
as u guys see, always stuck at choose main storage
i tried nightcore solution, but still wont open the storage..

**Comment by sctnightcore** [comment]
c r1 r0 n ?
**storageAuto_npc_steps p r1 n**


p what is it ?

**Comment by fadreus** [comment]
@lalilulelo1 

`storageAuto_npc_steps c r1 c r0 n`

http://openkore.com/index.php/StorageAuto_npc_steps
http://openkore.com/index.php/NPC_conversation_codes

Read the manual please.

**Comment by fadreus** [comment]
@sctnightcore 
Missing `c` in between `r1` & `r0` -> stuck, wait, conversation auto close >- loop.

**Comment by lalilulelo1** [comment]
@fadreus idk, its the default from the opencore
im just filling the location of kafra

**Comment by sctnightcore** [comment]
lol sry

**Comment by fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/34676910-62f4bd8e-f4c9-11e7-9c33-9ba0e4b8318d.png)

@lalilulelo1 The default is empty.
Where this opencore do you speak off?
www.myfriendgaveme.com?

**Comment by lalilulelo1** [comment]
uhm @fadreus well i dont really know or how i fill that config in the past time..
honestly i dont know any of the manual said about autostorage

and a moment ago i change the config like this
storageAuto_npc_type 3
storageAuto_npc_steps c r1 c r0 n 
and its work

now i will try to config the mace,
sometimes the bot didnt store the mace

anyway thanks for all of ur help guys @fadreus , @sctnightcore , @Nipodemos 

#### case closed ####
