### ISSUE TITLE
I am having issues with autostore/sell and using potions.. can someone help?

### ISSUE THREAD

**Issue by babypixels** [OpenKore/openkore#1616]
useSelf_item Novice Red Potion, Red Potion, {
	hp < 40%
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 1
	notWhileSitting 1
	notInTown 1
	timeout
	disabled 0
	inInventory
	manualAI 0
}

######## Autostorage/autosell ########

buyAuto {
	npc
	standpoint
	distance 5
	price
	minAmount 2
	maxAmount 3
	batchSize
	disabled 0
}

sellAuto 1
sellAuto_npc Payon Town 159 96
sellAuto_standpoint
sellAuto_distance 5
sellAuto_npc_steps s

storageAuto 1
storageAuto_npc Payton181 104
storageAuto_standpoint
storageAuto_distance 3
storageAuto_npc_type 1
storageAuto_npc_steps
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 50

npcTimeResponse
npcWrongStepsMethod 0

getAuto {
	minAmount
	maxAmount
	passive
}

**Comment by fadreus** [comment]
Fill the bug report template when reporting bug
If this isn't a bug, you shouldn't come here.
# Read the fucking manual.

Don't setup your config like you messaging your mother.
Use the correct format.

> useSelf_item Novice Red Potion, Red Potion, {

`useSelf_items Novice Red Potion, Red Potion {

> inLockOnly 1
> notWhileSitting 1
> notInTown 1

Don't use this fucking block.
Why? Read the manual.

> sellAuto_npc Payon Town 159 96

WTF? Payon Town? Fucking wrong. It's payon.
# Read the manual

> storageAuto_npc Payton181 104

What the fuck payton? where the space between town name and coordinate?

# Seriously bro, master the manual at wiki before posting anything.

**Comment by fadreus** [comment]
Fill the bug report template when reporting bug
If this isn't a bug, you shouldn't come here.
# Read the fucking manual!

Don't setup your config like you messaging your mother.
Use the correct format.

> inLockOnly 1
> notWhileSitting 1
> notInTown 1

Don't use these.
Why? Read the manual.

> sellAuto_npc Payon Town 159 96

WTF? Payon Town? Did you just put your pet name there? never use /where in game?
It's payon.
# Read the manual

> storageAuto_npc Payton181 104

What the fuck payton? where the space between town name and coordinate?

# Seriously bro, master the manual at wiki before posting anything.

**Comment by fadreus** [comment]
Fill the bug report template when reporting bug
If this isn't a bug, you shouldn't come here.
# Read the fucking manual!

Don't setup your config like you messaging your mother.
Use the correct format.

> inLockOnly 1
> notWhileSitting 1
> notInTown 1

Don't use these.
Why? Read the manual.

> sellAuto_npc Payon Town 159 96

WTF? Payon Town? Did you just put your pet name there? never use /where in game?
It's payon.
# Read the manual

> storageAuto_npc Payton181 104

What the fuck payton? where the space between town name and coordinate?

# Seriously bro, master the manual at wiki before posting anything.
## You are so wrong at so many level. If you need help, go to forum. Not here.

**Comment by Youtouchmytralala** [comment]
storageAuto_npc Payton181 104
lul
