### ISSUE TITLE
Where do I begin

### ISSUE THREAD

**Issue by bomteamza** [OpenKore/openkore#162]
![2](https://cloud.githubusercontent.com/assets/20739525/17270766/1d5af10e-5695-11e6-8a14-68acb77da795.jpg)
Hi, I need to start now. Ragnarok bot to understand now, I know I need to fix the IP, then I have to go up against it now. Thank you very much

**Comment by bomteamza** [comment]
![111](https://cloud.githubusercontent.com/assets/20739525/17271665/ed7560ac-56ab-11e6-890f-411b3447ca78.jpg)
I recommend sticking straight Thread

**Comment by ballstp1234** [comment]
ส่ง บอทมาจะแก้ให้

**Comment by 6ixthz** [comment]
@ballstp1234 พอจะช่วยแนะนำได้ไหมครับ  6ixthz@gmail.com

**Comment by ballstp1234** [comment]
............ส่ง บอท มา ทางนี้เลย ครับ ต้องมี ตัว แกะรหัสก่อน ปกกันการตัด
 ลบรหัส id pass มา   เล่น เชิฟไร ครับ ผมชาออค

2016-07-31 16:11 GMT+07:00 6ixthz <notifications@github.com>:

**Comment by kinkungzz** [comment]
สวัสดีครับคือผมเคยเซทมาก่อนแต่10ปีที่แล้วอยากกลับมาทำอีกรอบ ขอคำแนะนำหน่อยครับผม

**Comment by bomteamza** [comment]
ไห้ผมส่งบอทไปไห้ ที่เมลไหนครัช คุณballstp1234

**Comment by kinkungzz** [comment]
สวัสดีครับขอแจ้งก่อนผมไม่ใช่คุณballstp1234นะครับ
จากuser kinkungz ครับผมก็เล่นchaos เช่นกันถ้าเป็นไปได้รบกวนแนะนำหน่อยนะครับ
ทางเมล์ก็ได้ครับ

**Comment by ballstp1234** [comment]
izeeseo@gmail.com

2016-07-31 21:02 GMT+07:00 bomteamza <notifications@github.com>:

**Comment by itsrachelfish** [comment]
Hi there. Does anyone know a bilingual Thai / English speaker who would be willing to join the openkore team or help translate?

Thank you! :sunglasses: :sparkling_heart: 

my email: rachel@openkore.com

**Comment by kokzarag** [comment]
ขอด้วยนะ จะเป็นพระคุณอย่างสูงเลยครับ

vasin_@hotmail.com

**Comment by bomteamza** [comment]
ballstp1234 ส่งแล้วครับเล่นเซฟเวอร์ thor

**Comment by Middayz** [comment]
bomteamza ballstp1234 ท่านทั้งสองช่วยสอนผมด้วยนะคับ

**Comment by kUltraBoy** [comment]
I want bots, you set bots to send the email. I can help you fix it.

> k_ultra@hotmail.co.kr

**Comment by ballstp1234** [comment]
Time  Thai 19.00   i will send bot to you

2016-08-01 4:03 GMT+07:00 kUltraBoy <notifications@github.com>:

**Comment by ballstp1234** [comment]
https://www.facebook.com/groups/315444625465275/315482528794818/?notif_t=group_activity&notif_id=1470023348690963

2016-08-01 13:03 GMT+07:00 izeeseo marketing <izeeseo@gmail.com>:

**Comment by sarantojr** [comment]
![image](https://cloud.githubusercontent.com/assets/20738441/17306528/b099f02a-585a-11e6-99a7-c6c2704a72d4.png)
i stuck at this point when i just set only  servers.txt and config.txt are

servers.txt
[Thailand - tRO Main server (Revo)]
ip 103.55.55.12
port 6900
master_version 7
version 24
serverType tRO
secureLogin 3
secureLogin_type 0secureLogin_account 0
patchserver wpatch.ragnarok.in.th
patchpath /patch70
serverEncoding Thai
addTableFolders tRO
charBlockSize 112
gameguard 1

config.txt
XKore 1
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName Ragnarok.exe

how should i do

**Comment by ballstp1234** [comment]
Hey. Guy.  Send   facebook to me



ส่งจาก iPhone ของฉัน

เมื่อ 2 ส.ค. 2559 เวลา 02:45 sarantojr <notifications@github.com> เขียน:

**Comment by tkitty28** [comment]
plz me.. disconnect !!  naksen1985@live.com

**Comment by sarantojr** [comment]
@ballstp1234 Thanks for your helping :), my fb is https://www.facebook.com/saran.saikrasoon

**Comment by lungbest** [comment]
@ballstp1234 sorry i don't know set bot

**Comment by lungbest** [comment]
รบกวนด้วยครับ คือผมมือใหม่ setค่าอะไรยังไม่เป็นเลย
pim5453100346@gmail.com

**Comment by baka2016** [comment]
Hey Could you send me to an e-mail and how to set it? 
wootthiphatboy44@gmail.com
