### ISSUE TITLE
IRO:Restart Timeout on map Server

### ISSUE THREAD

**Issue by weebnoobi** [OpenKore/openkore#1624]
i guess because of the new patch?

**Comment by rvd0998** [comment]
we have to wait sadly..

**Comment by sctnightcore** [comment]
wait #1625

**Comment by iamtonysoft** [comment]
learn to wait. people nowadays are impatient.

**Comment by gprevedello** [comment]
Sorry to bother, but what should I do with that topic? (#1625)
There will be a file to download, something like that? Kinda new to git hub

**Comment by lututui** [comment]
#1624

**Comment by weebnoobi** [comment]
Thank you Devs!

**Comment by iamtonysoft** [comment]
@gprevedello check again the new commit #1625
