### ISSUE TITLE
idRO Classic - Session ID changed every change to another Map

### ISSUE THREAD

**Issue by rastafara88** [OpenKore/openkore#1643]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
Probably the file affected is SessionStore.Pm
because i couldn't get file contain creator session

sub generateSessionID {
	my ($self) = @_;
	my $ID = $self->{sessionCount};
	$self->{sessionCount} = ($self->{sessionCount} + 1) % 0xFFFFFFFF;
	return $ID;
}

###### Impact:
Disconnect every change to another map and every Session Expired
###### Expected Behavior:
able to change to another map
###### Actual Behavior:
69 00 4f 00 **# 3e 64** 00 00  09 38 05 00 00 00 00 00

that which i bold was changing every time if we change to another map.
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
Now openkore work only RE server with xkore1 and xkore 3

**Comment by rastafara88** [comment]
sorry sir... idRO classic also work... i can identified the problem.. but need clue for fixing...
currently my bot working with manual handle at first login... and work only in 1 current map.. if we change to another it will disconnected.

that's why i want to fix it...

**Comment by sctnightcore** [comment]
if you can do it . go pull request

**Comment by rastafara88** [comment]
no i mean i need clue for this issue...

i can handle manually for login.. is that acceptable for pull request?

**Comment by mfauziracing** [comment]
@rastafara88 can you show your send.pm and packetparser.pm gan?
i am still cannot login with manual method like you >.<
