### ISSUE TITLE
sub checkRodexID isn't working.

### ISSUE THREAD

**Issue by burnowned** [OpenKore/openkore#1646]
I try everything.
Was working, i got my mail's id but isnt working any more.
I'm reciving a message "You have no mails", but i have.
What can i do ?

automacro getrodex {
inventory "White Potion" <= 70
timeout 30
call getdex
}

macro getdex {
pause 1
checkRodexID()
$hardtolearn = @eval (checkRodexID($id))
pause 5
do rodex read $hardtolearn
pause 5
do rodex getitems
pause 5
do rodex close
}
sub checkRodexID {
	my $id;
	foreach my $mail_id (keys %{$rodexList->{mails}}) { my $mail = $rodexList->{mails}{$mail_id}; next if ($mail->{page} != 0 || $mail->{page_index} != 0); $id = $mail_id; last; }
	if (defined $id) {
		message "Your wanted mail id is $id.\n";
		return $id;
	} else {
		message "You have no mails.\n";
		return 0;
	}
}

**Comment by c4c1n6kr3m1** [comment]
do we still need to use **$::**
and not **$**
in macro ?

**Comment by lututui** [comment]
Try `$::Globals::rodexList` instad of `$rodexList`

**Comment by burnowned** [comment]
like this?
sub checkRodexID {
	my $id;
	foreach my $mail_id (keys %{$::Globals::rodexList->{mails}}) { my $mail = $::Globals::rodexList->{mails}{$mail_id}; next if ($mail->{page} != 0 || $mail->{page_index} != 0); $id = $mail_id; last; }
	if (defined $id) {
		message "Your wanted mail id is $id.\n";
		return $id;
	} else {
		message "You have no mails.\n";
		return 0;
	}
}

**Comment by burnowned** [comment]
![sem titulo](https://user-images.githubusercontent.com/25069600/34962887-d21b6556-fa2c-11e7-8006-45d5ef2cdbcd.png)

**Comment by ReedemBR** [comment]
```
**sub checkRodexID {
my $id;
foreach my $mail_id (keys %{$rodexList->{mails}}) { my $mail = $rodexList->{mails}{$mail_id}; next if ($mail->{page} != 0 || $mail->{page_index} != 0); $id = $mail_id; last; }
if (defined $id) {
    message "Your wanted mail id is $id.\n";
    return $id;
} else {
    message "You have no mails.\n";
    return 0;
}
}**
```

**Comment by burnowned** [comment]
Reedem, tem como deixar um contato?

**Comment by burnowned** [comment]
It's not even working
macro checkid {
checkRodexID()
}
sub checkRodexID {
	my $id;
	foreach my $mail_id (keys %{$rodexList->{mails}}) { my $mail = $rodexList->{mails}{$mail_id}; next if ($mail->{page} != 0 || $mail->{page_index} != 0); $id = $mail_id; last; }
	if (defined $id) {
		message "Your wanted mail id is $id.\n";
		return $id;
	} else {
		message "You have no mails.\n";
		return 0;
	}
}

**Comment by Nipodemos** [comment]
inside macro, you have to pass the sub value to a variable, like this:
```
macro checkid {
    $check = checkRodexID()
}
```
Reedem made this and you did not notice

**Comment by ReedemBR** [comment]
Um exemplo aqui da sua macro:

```
macro getdex {
pause 1
$hardtolearn = checkRodexID()
pause 5
do rodex read $hardtolearn
pause 5
do rodex getitems
pause 5
do rodex close
}
```

**Comment by iamtonysoft** [comment]
This might help you using eventMacro.
https://github.com/PoringUniverse/iro-restart-repo/blob/master/add-ons/rodex/auto-receive.txt
just change the `JobID` from automacro block... what it does was to receive all rodex items including zennies
