### ISSUE TITLE
After select server it gets error "the server has denied your connection"

### ISSUE THREAD

**Issue by fikriaulia13** [OpenKore/openkore#1648]
excuse me sir
why did i got this error "The server has denied your connection"
after select server it gets error

here's my server.txt

[International - iRO: Nostradamus Ragnarok]
ip 45.64.98.125
port 6900
master_version 2
version 54
serverType kRO_RagexeRE_2015_11_04a
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders iRO;iRO/Restart
charBlockSize 145
recvpackets recvpackets.txt
pauseCharLogin 1
pinCode 0
private 1
gameGuard 0
#sendCryptKeys 0x4C17382A, 0x7ED174C9, 0x29961E4F

maybe its recvpackets but i cant get it

thanks for helping me

**Comment by sctnightcore** [comment]
Link server

**Comment by fikriaulia13** [comment]
@sctnightcore here it is sir http://www.ronostradamus.com/

**Comment by sctnightcore** [comment]
client date ? 
get recvpacket and key from peek !

**Comment by fikriaulia13** [comment]
@sctnightcore  client date Oct 29, 2015
i dont understand how to use peek
because i dont have that program :(

**Comment by sctnightcore** [comment]
i will try if have freetime

**Comment by fikriaulia13** [comment]
@sctnightcore im trying using jcv ro tools but its get error "Sorry I cant find the offset of the packet length function.
The executable file might be compressed/protected"

**Comment by sctnightcore** [comment]
test charBlockSize 147

**Comment by fikriaulia13** [comment]
@sctnightcore its still get same error :(

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/34955114-996b34a6-fa55-11e7-839e-1c9e159e202b.png)
Now ok XD

**Comment by fikriaulia13** [comment]
@sctnightcore its get error packet tokenizer sir 
![aha](https://user-images.githubusercontent.com/26967975/34955828-c8d9cc86-fa58-11e7-9249-925ab54ae9b7.PNG)

can i copy your server.txt ?
and recvpackets.txt i should place it openkore\tables\iRO ??

**Comment by sctnightcore** [comment]
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1632603/recvpackets.txt)
recvpacket .
```
[Nostradamus Ragnarok]
ip 45.64.98.125
port 6900
master_version 2
version 54
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders tRO
charBlockSize 147
pauseCharLogin 1
private 1
sendCryptKeys 0x45B945B9, 0x45B945B9, 0x45B945B9
```

**Comment by fikriaulia13** [comment]
@sctnightcore  its still server has denied your connection sir
btw which one recvpackets i should use
the above one or the pastebin ?
and what folder should i copy that recvpackets.txt ?

**Comment by sctnightcore** [comment]
copy recvpackets.txt to `you addTableFolders in server.txt`

**Comment by fikriaulia13** [comment]
[Nostradamus Ragnarok]
ip 45.64.98.125
port 6900
master_version 2
version 54
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders 
charBlockSize 147
pauseCharLogin 1
private 1
sendCryptKeys 0x45B945B9, 0x45B945B9, 0x45B945B9

but ur server.txt addTableFolders .........
ive try many times and still same :(
i try to addTableFolders iRO/Renewal:iRO
i try addTableFolders tRO like before u edited
place all over there that recvpacket but still same error

**Comment by fikriaulia13** [comment]
@sctnightcore its still same "the server has denied your connection"

[International - iRO: Nostradamus Ragnarok]
ip 45.64.98.125
port 6900
master_version 2
version 54
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders iRO
charBlockSize 147
pauseCharLogin 1
private 1
sendCryptKeys 0x45B945B9, 0x45B945B9, 0x45B945B9

ive already use that for server.txt
use ur recvpackets.txt and place it at tables/iRO

but the error still coming up
im feel crazy right now

**Comment by sctnightcore** [comment]
I'm lazy for update new sT for clientdate : 20151029

**Comment by fikriaulia13** [comment]
@sctnightcore ok then sir thx for the time maybe ill try asking some help from mr @alisonrag

**Comment by sctnightcore** [comment]
@fikriaulia13  GO #1650 

Main support pServer is me .  XD
