### ISSUE TITLE
MRO MYSG(looking for a dev)

### ISSUE THREAD

**Issue by hougochia** [OpenKore/openkore#1658]
well i know theres no dev working on the MRO , but simply close the thread and said no dev working on MRO isnt solving it , people are going to create and create again, why not leave the thread here and leave it to someone that are interested. im gonna bump it overtime see if theres any dev can help

**Comment by alisonrag** [comment]
you can use phRO issue, the gameshield and client is the same

**Comment by alisonrag** [comment]
#1225
