### ISSUE TITLE
KRO:zero map server connetion timeout error

### ISSUE THREAD

**Issue by jasmine69** [OpenKore/openkore#1665]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

## ------------------ Bug Report Template ------------------

KRO:Zero 

map server connection timeout error

yesterday KRO:Zero  client updated!!

This error occurred since yesterday's update.

![kro_zero](https://user-images.githubusercontent.com/35547535/35081061-0984a668-fc55-11e7-882c-3aaf51dc1d95.png)

**Comment by sctnightcore** [comment]
https://discord.gg/a2bd5M8

if kRO:zero come hereeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
