### ISSUE TITLE
kro zero has Gameguard error.. disconnection core T_T

### ISSUE THREAD

**Issue by KroZeroUser** [OpenKore/openkore#1667]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

I downloaded the patched file, but I get an error.
![image](https://user-images.githubusercontent.com/35427658/35082602-2df4bc28-fc5e-11e7-8fb3-6e6212787ece.png)

+ Item name does not appear normally.
![image](https://user-images.githubusercontent.com/35427658/35082656-62907260-fc5e-11e7-8137-33d9df42e127.png)

Help us. Thank you..

**Comment by sctnightcore** [comment]
use poseidon.

tonight i will fix itemname .
