### ISSUE TITLE
Unable to load the file recvpackets.txt. 

### ISSUE THREAD

**Issue by megafailed** [OpenKore/openkore#1669]
Unable to load the file recvpackets.txt.
i putted m server (ragnarok restart )
and it says this Unable to load the file recvpackets.txt.
im new here pls help

**Comment by sctnightcore** [comment]
download new openkore .

**Comment by megafailed** [comment]
im using the newest i downloaded it some hours ago
any way ill try Thank you

**Comment by megafailed** [comment]
ok does it need perl i dont think i downloaded it ?

**Comment by sctnightcore** [comment]
google > perl download

**Comment by megafailed** [comment]
thanks it actully works !

**Comment by megafailed** [comment]
ok sorry if i annoy you
but how to see what my charcher doing ? when its bot?

**Comment by alisonrag** [comment]
console say everithing that you bot is doing, attacking moving, etc
