### ISSUE TITLE
Xkore=1 : Unable to inject... what should i do, thanks :)

### ISSUE THREAD

**Issue by sarantojr** [OpenKore/openkore#167]
![image](https://cloud.githubusercontent.com/assets/20738441/17306105/6deb51a8-5858-11e6-851e-a8c4e3018b80.png)

i can not start bot in xmode as picture above, please help me, thanks :)

**Comment by sarantojr** [comment]
i stuck at this point when i just set only servers.txt and config.txt are

servers.txt
[Thailand - tRO Main server (Revo)]
ip 103.55.55.12
port 6900
master_version 7
version 24
serverType tRO
secureLogin 3
secureLogin_type 0secureLogin_account 0
patchserver wpatch.ragnarok.in.th
patchpath /patch70
serverEncoding Thai
addTableFolders tRO
charBlockSize 112
gameguard 1

config.txt
XKore 1
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName Ragnarok.exe

how should i do

**Comment by eichtodev** [comment]
Hi All,

I new in openkore development, so basically i just self-study the openkore.
and now i got the same error on NetworkRedirect.dll injection.
Anyone can help me with this.

Thanks for helping me in Advanced.

**Comment by fadreus** [comment]
Run openkore as administrator (Win 7 & later) for that error.

**Comment by fadreus** [comment]
@eichtodev  Run openkore as administrator (Win 7 & later) for that error.

**Comment by eichtodev** [comment]
@fadreus i tried to run as admin both start.exe, and before i open the ro client the error message already displayed.

**Comment by eichtodev** [comment]
@fadreus  i think i already figure out about your feedback "Run openkore as administrator (Win 7 & later) for that error.",
i set the compatibility for openkore (start.exe), and same config for Ragexe.exe and Ragnarok.exe
![image](https://user-images.githubusercontent.com/8839011/32700843-cc300560-c805-11e7-9ccf-41adaadacc58.png)

but the error still the same and this time the error display once i open the ragnarok.exe (*as admin).
any idea how to fix that?

Thanks for helping me in Advanced.

**Comment by fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/32700976-a3885038-c808-11e7-9a43-a413f4619895.png)

Did you use latest version?
Did you apply fix from #1374 ?
Generally it's working.

> BTW, i trying to config a bot for phRO.

Ah, I forgot about this.
For phRO continue at #1225

**Comment by eichtodev** [comment]
I clone from this repo https://github.com/OpenKore/openkore.git
The error still the same.
![image](https://user-images.githubusercontent.com/8839011/32705465-bd90581c-c84f-11e7-9e28-0a6f79a44c62.png)

Question do i need to set the ragexe.exe or Ragnarok.exe (which is the patcher)?

**Comment by alisonrag** [comment]
The pRO client is protected, you need to find another way, if xkore 0 doesnt work xkore 1, 2 and 3 will not work to

**Comment by KimJongkok** [comment]
any update for idro classic guys?

**Comment by imthemenace** [comment]
why this issue in pRo cannot solve
but in the game there is a lot of botter in all servers
those who already have the right config they selling it for excash
and black market
and a lot of players who dont want to get behind are buying it

please if someone have the config already please post it and inform those who are looking for it
so that we can stop those abusers who have it to abuse the kores... specially the creator who implementing a free openkore distribution....

tnx more power admins and creator of kore

**Comment by qimux99** [comment]
i cant login here.
![1](https://user-images.githubusercontent.com/35319615/34810910-e98539da-f6d8-11e7-99d5-658314887ef0.png)
if i change xkore port.the bot freeze

**Comment by sctnightcore** [comment]
@qimux99  server ?
