### ISSUE TITLE
[Private server] not connect to map server

### ISSUE THREAD

**Issue by Frostig1992** [OpenKore/openkore#1672]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: I download the latest version of openkore, today 18-01-2018.
And don't connect to map server.

Packet Parser: Unhandled Packet: 08B9 Handler: login_pin_code_request2
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: B4 4B 02 00 (150452)
MAP Name: aldebaran.gat
MAP IP: 142.4.217.163
MAP Port: 5121
-----------------------------
Closing connection to Character Server
Disconnecting (142.4.217.163:6121)...disconnected
Connecting to Map Server...
Connecting (142.4.217.163:5121)... connected
Disconnecting (142.4.217.163:5121)...disconnected
The server has denied your connection.
Timeout on Map Server, connecting to Account Server...
Connecting to Account Server...
[reconnect] Login retry number 2, setting reconnect timeout to 73 seconds.
Connecting (supremacy.ws:5222)... connected
Disconnecting (142.4.217.163:5222)...disconnected
Error: The server still recognizes your last connection
###### Affected configuration(s)/ file(s):
my servers.txt

[servers.txt](https://github.com/OpenKore/openkore/files/1643569/servers.txt)

my config.txt

[config.txt](https://github.com/OpenKore/openkore/files/1643573/config.txt)

my  recvpackets.txt

[recvpackets.txt](https://github.com/OpenKore/openkore/files/1643575/recvpackets.txt)

###### Expected Behavior:
connect to map server

###### Actual Behavior:
not connect to map server
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
your servertype or keys is wrong.
follow the guide in wiki:
http://openkore.com/index.php/Connectivity_Guide
http://openkore.com/index.php/ServerType

**Comment by Frostig1992** [comment]
i use the grftool to get servertype


<?xml version="1.0" encoding="EUC-KR"?>

-<clientinfo>

<servicetype>korea</servicetype>

<servertype>sakray</servertype>


-<connection>

<display>Pow Supremacy Online</display>

<balloon>Tu otro mundo.</balloon>

<desc>Servidor Principal</desc>

<address>supremacy.ws</address>

<port>5222</port>

<version>30</version>

<langtype>1</langtype>

<registrationweb>http://www.supremacy.ws</registrationweb>


-<loading>

<image>loadingscreen00.jpg</image>

<image>loadingscreen01.jpg</image>

<image>loadingscreen02.jpg</image>

<image>loadingscreen03.jpg</image>

<image>loadingscreen04.jpg</image>

<image>loadingscreen05.jpg</image>

<image>loadingscreen06.jpg</image>

</loading>

</connection>

</clientinfo>


Previously I had used the guides that you just gave me, but I did not even connect to the server.

With PE viewer, the delivered date is Apr 9, 2012, and try with kRO_RagexeRE_2012_03_07f  and kRO_RagexeRE_2012_04_10a, but does'nt work :(.

And the keys take them out from PEEK.


[Packet_Keys]
1 = 0x01581359
2 = 0x452D6FFA
3 = 0x6AFB6E2E


Please help me, I've been trying for 8 days, with the guides and the openkore forum

**Comment by alisonrag** [comment]
openkore use in order 1, 3, 2
try
kRO_RagexeRE_2012_04_10a,

**Comment by Frostig1992** [comment]
Closing connection to Account Server
Disconnecting (142.4.217.163:5222)...disconnected
Connecting to Character Server...
Selected server: Supremacy
Connecting (142.4.217.163:6121)... connected
Received characters from Character Server
------------- Character List -------------
Slot 0: Openkore (High Priest, Boy, level 99/70, aldebaran)
------------------------------------------
PIN code is correct.
------------- Character List -------------
Slot 0: Openkore (High Priest, Boy, level 99/70, aldebaran)
------------------------------------------
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: B4 4B 02 00 (150452)
MAP Name: aldebaran.gat
MAP IP: 142.4.217.163
MAP Port: 5121
-----------------------------
Closing connection to Character Server
Disconnecting (142.4.217.163:6121)...disconnected
Connecting to Map Server...
Connecting (142.4.217.163:5121)... connected
Disconnecting (142.4.217.163:5121)...disconnected
The server has denied your connection.

i use 1,3,2 and kRO_RagexeRE_2012_04_10a. (sorry for my bad english)

**Comment by sctnightcore** [comment]
link server ?

**Comment by Frostig1992** [comment]
https://supremacy.ws/

**Comment by sctnightcore** [comment]
link download . ID PW .

**Comment by Frostig1992** [comment]
Maybe you mean this, I try my best to speak English 🐙 , 


http://www.mediafire.com/file/t8aobr284tisgym/kRO+2015.rar

 and ID and Password of login account? or forum account of server D:

**Comment by sctnightcore** [comment]
login account in game ! 
Dont have mini download ?

**Comment by Frostig1992** [comment]
okey okey, https://drive.google.com/file/d/0BxXhJkmD8eDLTkstYWEyME9rT1U/view  light version

and login account is 
login: gypsy
Pass: gypsy12

**Comment by sctnightcore** [comment]
```
[https://supremacy.ws/]
ip 142.4.217.163
port 5222
master_version 14
version 30
serverType kRO_RagexeRE_2012_04_10a
serverEncoding Western
addTableFolders   #you tables 
charBlockSize 144
pinCode 1
charDeleteDateType 1
#sendCryptKeys 0x01581359, 0x6AFB6E2E, 0x452D6FFA
```
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1644793/recvpackets.txt)
![image](https://user-images.githubusercontent.com/23263315/35126599-bdc5bca8-fce0-11e7-99be-6ae2b63b4458.png)

**Comment by Frostig1992** [comment]
thx u a lot 🗡
