### ISSUE TITLE
Where to post to ask for help with a new server? Sorry newbie

### ISSUE THREAD

**Issue by cte793** [OpenKore/openkore#1681]
Hi! I know how to extract grf's and this is the file, but i cant seem to make the server.txt of this server. Please help!!!!! thank you!

?xml version="1.0" encoding="euc-kr" ?
clientinfo
	desc>NewG Ragnarok Online</desc
	servicetype>korea</servicetype
	servertype>primary</servertype
        connection
		display>NewG Ragnarok Online</display
      		address>139.99.101.116</address
      		port>6900</port
      		version>55</version
      		langtype>8</langtype

**Comment by sctnightcore** [comment]
.....
![image](https://user-images.githubusercontent.com/23263315/35193442-f44b6142-fed4-11e7-8fcd-440b6974c997.png)
link server ? 

xD

**Comment by cte793** [comment]
http://newg-ro.com/

**Comment by cte793** [comment]
wow that was fast... XD

**Comment by sctnightcore** [comment]
http://openkore.com/index.php/ServerType
http://openkore.com/index.php/Connectivity_Guide

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/35193470-57e70b98-fed5-11e7-8328-092439b09488.png)
# openkore dont support GEPARD

**Comment by cte793** [comment]
I've tried everything within my knowledge, sometimes it connects until map server and gets disconnected afterwards

**Comment by cte793** [comment]
That was just a display XD because the server doesnt have any shield :D

**Comment by sctnightcore** [comment]
@cte793  wait me check

**Comment by cte793** [comment]
okay thank you!!

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/35193718-7f93bf48-fed9-11e7-9ac2-0e93622af5d6.png)
how to download ?

**Comment by cte793** [comment]
https://m.facebook.com/NewGRagnarokOnline/posts/1968619653460038

**Comment by sctnightcore** [comment]
how to extract grf ? 
grf is lock !

**Comment by cte793** [comment]
I just used grf tool XD

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/35193936-2e36e8ba-fedd-11e7-88b4-a3eb8b23cbd4.png)

If you do not try it yourself, I'm lazy to help you.

**Comment by cte793** [comment]
ohhh

**Comment by cte793** [comment]
I've tried everything. Lol. Spent 4 hours on this

**Comment by cte793** [comment]
I'm just a newbie, I tried everything, I used openkore before, but it was years ago. And even then, I only knew the basics.

**Comment by cte793** [comment]
Here was my server.txt

[NewG RO - Pro]
ip 139.99.101.116
port 6900
master_version 1
version 22
serverType kRO_RagexeRE_2015_11_04a
secureLogin 0
secureLogin_type
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
private 1
addTableFolders iRO/Classic;iRO
charBlockSize 145
recvpackets recvpackets.txt
pauseCharLogin 1

**Comment by sctnightcore** [comment]
```
[NewG RO - Pro]
ip 139.99.101.116
port 6900
master_version 1 > check in wpe 
version 22 > check in wpe 
serverType kRO_RagexeRE_2015_11_04a
private 1
addTableFolders  # you tables 
charBlockSize 145 > 147
pauseCharLogin 1
sendCryptKeys 1,3,2 > get from peek .
```
http://openkore.com/index.php/Connectivity_Guide
http://forums.openkore.com/viewtopic.php?f=6&t=207278

**Comment by cte793** [comment]
I've already tried peek, and it says it cannot run, and cannot fin DLL

**Comment by cte793** [comment]
![untitled](https://user-images.githubusercontent.com/35653328/35194120-d805565a-fee8-11e7-8f04-b796d575fd5a.png)

**Comment by sctnightcore** [comment]
run admin is work for me . 
```

[Packet_Keys]
1 = 0x4C17382A
2 = 0x7ED174C9
3 = 0x29961E4F
```

**Comment by cte793** [comment]
Told you I was a newbie, I've never used other apps before, I ran openkore before by just trying things,

**Comment by cte793** [comment]
![untitled](https://user-images.githubusercontent.com/35653328/35194197-7b2970ae-feea-11e7-9d45-0b1da36c31d7.png)

**Comment by cte793** [comment]
[NewG RO - Pro]
ip 139.99.101.116
port 6900
master_version 16
version 55
serverType kRO_RagexeRE_2015_11_04a
secureLogin 0
secureLogin_type
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
private 1
addTableFolders iRO/Classic;iRO
charBlockSize 147
recvpackets recvpackets.txt
pauseCharLogin 1

**Comment by cte793** [comment]
still cant seem to use peek

**Comment by cte793** [comment]
[NewG RO - Pro]
ip 139.99.101.116
port 6900
master_version 16
version 55
serverType kRO_RagexeRE_2015_11_04a
secureLogin 0
secureLogin_type
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
private 1
addTableFolders NewgRO
charBlockSize 147
recvpackets recvpackets.txt
pauseCharLogin 1

**Comment by cte793** [comment]
![untitled](https://user-images.githubusercontent.com/35653328/35195876-d6d06a42-ff04-11e7-9c7b-7b11f32bc29e.png)

**Comment by cte793** [comment]
[NewG RO - Pro]
ip 139.99.101.116
port 6900
master_version 16
version 55
serverType kRO_RagexeRE_2015_11_04a
private 1
addTableFolders NewgRO
charBlockSize 147
pauseCharLogin 1
sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9
