### ISSUE TITLE
Cannot buy item in pServer

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1682]
###### Summary: 
test with old openkore is work .  **s e**
but new openkore get
` There are still steps to be done but the conversation has already ended (current step: s)`
https://media.discordapp.net/attachments/383073124708515841/404597468957900800/unknown.png?width=712&height=445
test with b `There are still steps to be done but the conversation has already ended (current step: b).`

Now test with RMS server is work . 
Maybe dont work in custom npc sell in rA , Herc

**Comment by Mortimal** [comment]
More info required... servertype... log from console with debug on...

**Comment by moneyisgod** [comment]
How about custom npc sell ? I guess It's too 'cause in some servers i can send sell command when buying items ?!
