### ISSUE TITLE
Cannot extract recvpackets - Newbie

### ISSUE THREAD

**Issue by cte793** [OpenKore/openkore#1683]
Hi! I'm having a problem with the PEEK extractor and I need help, because I ran the PEEK and extract, no issues came out, but when I look at the output folder, there is no "run1" file there, aside from the PacketLength, structs; only a PacketRecord shows up after i extract length. I had a other issue before and someone did fix it; however he wants me to figure it on my own, but after another two hours still can't find a way. Can someone help me? thank you! 
Here's my not so perfect server.txt
[NewG RO]
ip 139.99.101.116
port 6900
master_version 16
version 55
serverType kRO_RagexeRE_2015_09_16
secureLogin 0
secureLogin_type
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
private 1
addTableFolders NewgRO
charBlockSize 147
recvpackets recvpackets.txt
pauseCharLogin 1

**Comment by cte793** [comment]
![untitled](https://user-images.githubusercontent.com/35653328/35195872-c8809d7c-ff04-11e7-83a6-ba22c0815cc0.png)

**Comment by sctnightcore** [comment]
http://forums.openkore.com/viewtopic.php?f=6&t=207278

**Comment by cte793** [comment]
Still having errors..

**Comment by cte793** [comment]
Please dont close issues that you don't even know if you've already helped someone.

**Comment by cte793** [comment]
Stop being a douche.

**Comment by cte793** [comment]
Stop being a douche. Not everyone is like you. LOL. If you have beefs with someone don't take it to other people

**Comment by sctnightcore** [comment]
¯\_(ツ)_/¯

**Comment by cte793** [comment]
You can but not me. Maybe that's why im asking for help? LoL douche.

**Comment by cte793** [comment]
Closing issues you havent even asked if they've already resolved it.

**Comment by sctnightcore** [comment]
Script to get the clean recvpackets : 
![image](https://user-images.githubusercontent.com/23263315/35202398-18bc3062-ff55-11e7-9a89-fa3f3a643a8d.png)

**Comment by cte793** [comment]
Already did that and i still error when opening that LOL

**Comment by sctnightcore** [comment]
.pl ?

**Comment by cte793** [comment]
Yeah. And also downloaded active perl. But when i open the .pl an error pops up.

**Comment by sctnightcore** [comment]
error ?

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/tree/master/tables/kRO/RagexeRE_2015_11_04a

ez step use it .

**Comment by cte793** [comment]
should've started helping, not closing issues, douche

**Comment by sctnightcore** [comment]
Pserver go forums not  issues ! .

**Comment by fadreus** [comment]
@cte793 
For your information, github isn't a place to ask for help. It's main purpose for reporting bug and feature request.

If you read properly before starting an issue, there is a bug report template.
If you read the forum, openkore moved source code from svn to git for easier management purpose & not for everyone personal problem.
Plus everyone doing on their free time. Should have be grateful someone spend their precious time responding to your question.

Your attitude asking for help isn't appropriate.
You are being lazy. Only tried for 4 hours? 4 hours for newbie is barely even trying.

Use the forum next time.
Use the proper channel.
