### ISSUE TITLE
We still use scons 2.0.1

### ISSUE THREAD

**Issue by Henrybk** [OpenKore/openkore#1688]
###### Impact:
Compiling XStools and binaries in windows is horribly hard

###### Expected Behavior:
It should not be that hard

###### Actual Behavior:
but it is

###### Steps to Reproduce:
Try to compile XSTools in windows

**Comment by lututui** [comment]
Or ditch scons

**Comment by Henrybk** [comment]
What do you suggest we use @lututui ?

**Comment by NandoPrates** [comment]
eu estava esperando tanto tempo por isso

**Comment by Nipodemos** [comment]
hey @NandoPrates try commenting in english here on github please

**Comment by sctnightcore** [comment]
wait
