### ISSUE TITLE
cannot connect to poseidon server (kRO:Zero)

### ISSUE THREAD

**Issue by laputii** [OpenKore/openkore#1689]
i modified some files to use openkore in kRO Zero server, but i think i did it wrong.

i cannot connect to poseidon server. TT

-------------------------------------------------------------------------------------------------------

First, i modified poseidon.xml file (in ragnarokzero data folder)
(i omitted "<", ">")

xml version="1.0" encoding="euc-kr"
clientinfo
	servicetype korea /servicetype
	servertype primary /servertype

	connection
		display Poseidon /display
		desc None /desc
		address 127.0.0.1 /address
		port 6900 /port
		version 1 /version
	/connection
/clientinfo

-------------------------------------------------------------------------------------------------------

and poseidon.txt file (in openkore control folder)

ragnarokserver_ip=127.0.0.1
ragnarokserver_port=6900

queryserver_ip=127.0.0.1
queryserver_port=24390

server_type=kRO_2018-01-03a

CharBlockSize=155

debug=0

-------------------------------------------------------------------------------------------------------

last, i checked the part of my config.txt file (in openkore control folder)

poseidonServer 127.0.0.1
poseidonPort 24390

-------------------------------------------------------------------------------------------------------

should i modify any files more?

need help, plz.

**Comment by sctnightcore** [comment]
https://discord.gg/a2bd5M8 
come here .
