### ISSUE TITLE
Freezing 20sec after map change. kRO ZERO

### ISSUE THREAD

**Issue by iropis123** [OpenKore/openkore#1693]
Hi guys

my bot freezes '20sec' after map changes( after using teleport, after relog, after going to another map..)

So I changed 'AI' in timeouts.txt. AI applied well but still freezing.

I think AI is not a reason because after teleport my bot immediately become a 'route state' or 'attack state' but only freeze.

My bot character never response in 'the freezing time'.
In the freezing time, kore is working but only my character is fixed

I asked this issue on Openkore Forum and someone helped me.

I changed timeouts.txt that someone suggested but it doesn't work.

I think it's not a timeouts.txt problems.

After map changing(relog, teleport, move next map) , I can see my bot is there(through real RO client screen) but actually it seems that bot doesn't exist.
I cannot deal with my bot( game message says "that character already deal with another character") and aggressive monsters don't recognize bot until bot unfreeze.

what should I do?

I don't know other kRO zero server openkore users experience this situation.

--

**Comment by sctnightcore** [comment]
https://discord.gg/f5svzJ8
go xD
