### ISSUE TITLE
[eventMacro] macro keyword &split not working correctly

### ISSUE THREAD

**Issue by Nipodemos** [OpenKore/openkore#1695]
###### Summary: 
inside a while, `&split` set value on array just once, on the following loops doesn't update the values
###### Impact:
&split becomes useless if inside a while loop
###### Expected Behavior:
on each loop, it updates the values of an array
###### Actual Behavior:
do only once, then it is like it doesnt event trying
###### Steps to Reproduce:
use this eventMacro: 
```perl
automacro test {
	exclusive 1
	run-once 1
	BaseLevel > 0
	macro_delay .5
	call {
		@array = (a:b:c, 1:2:3, ma:me:mi:mo, sim:griim:fin)
		$i = 0
		while ($i < @array) {
			@group = &split(':',$array[$i])
			if ( $i = 0) log \$i is $i, then \@group should be a:b:c
			if ( $i = 1) log \$i is $i, then \@group should be 1:2:3
			if ( $i = 2) log \$i is $i, then \@group should be ma:me:mi:mo
			if ( $i = 3) log \$i is $i, then \@group should be sim:griim:fin
			$j = 0
			while ($j < @group) {
				log \$group[$j] is $group[$j]
				$j++ 
			}
			$i++
		}
		log done loop
	}
}
```

Aditional Details:
Here is what shows when runs the macro:

```
[eventMacro] Conditions met for automacro 'test', calling macro 'tempMacro11'
[eventmacro log] $i is 0, then @group should be a:b:c
[eventmacro log] $group[0] is a
[eventmacro log] $group[1] is b
[eventmacro log] $group[2] is c
[eventmacro log] $i is 1, then @group should be 1:2:3
[eventmacro log] $group[0] is a
[eventmacro log] $group[1] is b
[eventmacro log] $group[2] is c
[eventmacro log] $i is 2, then @group should be ma:me:mi:mo
[eventmacro log] $group[0] is a
[eventmacro log] $group[1] is b
[eventmacro log] $group[2] is c
[eventmacro log] $i is 3, then @group should be sim:griim:fin
[eventmacro log] $group[0] is a
[eventmacro log] $group[1] is b
[eventmacro log] $group[2] is c
[eventmacro log] done loop
```

here's print:
![image](https://user-images.githubusercontent.com/11494727/35351031-d72e030e-0126-11e8-8fea-e278e7835d2c.png)

**Comment by lututui** [comment]
$eventMacro->get_split_var is being called with undef complement, so perl type conversion magic kicks in and undef becomes zero.

**Comment by Nipodemos** [comment]
oh, that makes sense, i'll look this now

**Comment by lututui** [comment]
Actually, I was wrong. Here's a fix for this case

https://github.com/OpenKore/openkore/commit/2dc0c1aa1ccaa1e8eae804fe6e749c4d3b2ccd94

I don't know what happens when nesting stuff.
Splitting a hash value is still broken
