### ISSUE TITLE
bot freezes 20sec when map is changed (include teleport)

### ISSUE THREAD

**Issue by iropis123** [OpenKore/openkore#1698]
###### Affected configuration(s)/ file(s):
I don't know what file is affected. However I'm sure it's  not a config.txt or timeouts.txt problem
###### Impact:
bot cannot farm using teleport because every teleport spend 20sec
###### Expected Behavior:
Bot is acting immediately(or specificated time on timeouts.txt 'ai' 'tele') after using teleport
###### Actual Behavior:
Bot spend 20sec every mapchanges
###### Steps to Reproduce:

here's my timeouts.txt but it's not a problem
# Server connection timeouts
master 12
gamelogin 12
charlogin 12
maplogin 12
play 20
# When disconnected, wait x seconds before reconnecting again
reconnect 10

# After repeated disconnects, wait longer before reconnecting, to reduce load on the server.
# The first value in this list overrides the "reconnect" timeout above.
reconnect_backoff 30,60,120,180,300,600,600,900,900,1800

# Add a random amount of seconds to reconnect time, up to a maximum of reconnect_random seconds.
reconnect_random 10

# Wait x seconds for a poseidon reply before disconnecting
# Ignore this if you don't use Poseidon Server
poseidon_wait_reply 15

# Activate AI after x seconds after the map's loaded
ai 0

ai_teleport 0.1
ai_teleport_away 0.1
ai_teleport_idle 0.1
ai_teleport_portal 0.1
ai_teleport_hp 0.1
ai_teleport_safe_force 120

**Comment by sctnightcore** [comment]
server ?

**Comment by fadreus** [comment]
Kro:Zero
Same guy -> #1693 & [here](http://forums.openkore.com/viewtopic.php?f=10&t=212549)
If you close issue, he will spam again until his demands are met.
He need reply in 24 hours or riot.

**Comment by fadreus** [comment]
@sctnightcore 
Kro:Zero
Same guy -> #1693 & [here](http://forums.openkore.com/viewtopic.php?f=10&t=212549)
If you close issue, he will spam again until his demands are met.
He need reply in 24 hours or riot.

**Comment by iropis123** [comment]
@fadreus 
yesterday I upload issue with wrong template. So sctnightcore invite me at discord and he close my issue but nobody know about the issue in korean room and I asked english room.
Then someone told me "you can ask but you have to upload issue with template."
So I upload issue with template.

What's my fault?
I

**Comment by alisonrag** [comment]
this is not openkore stuck,we have to discovery why, but i think we miss send some packet, so the server freeze the bot for 20 seconds until server unfreeze the character.
if you enable debug you will see that openkore try to move but the server dont allow for 20 seconds

**Comment by iropis123** [comment]
@alisonrag 
Thank you so much. I have to learning further.

**Comment by iropis123** [comment]
This problem is solved. After applying kRO plugin(about new login process), openkore receives packet(?) immediately so bot acts in less than a  1 sec. thank you!

**Comment by alisonrag** [comment]
Fixed here #1764

**Comment by alisonrag** [comment]
Fixed in #1735

**Comment by andraaza** [comment]
can you help me my openkore problem same like this server idRO

**Comment by alisonrag** [comment]
@andraaza 
the only dev that work in idRO is @sctnightcore

**Comment by sctnightcore** [comment]
@alisonrag   i cannot connect to idRO . GG
