### ISSUE TITLE
iRO Loki, izlude -> byalan issue

### ISSUE THREAD

**Issue by jeraffas** [OpenKore/openkore#1706]
###### Summary: 
iRO Classic Loki, trying to setup a byalan bot, but kore doesn't seem to recognize izlude. It demonstrates some strange behaviors like routing but extremely slowly. It eventually ends up in the izlude tool shop and goes in and out forever.

I've checked portals (which should be correct) and have tried to write a macro that walks kore through console commands to byalan, but that doesn't work either.

This issue was brought up in #138 , but did not seem to be resolved afaik. That post suggested an old izlude, new izlude issue, but I don't have a clue how to navigate that. Any help would be much appreciated, thanks!

**Comment by fadreus** [comment]
Check this #1182

**Comment by jeraffas** [comment]
I have tried replacing fields/izlude.fld with the one in fields/EP14.1 and deleting the .dist, nothing.
I also tried the izlude.fld in 15.1 but no luck either. Am I doing this correctly? and is fields/EP14.1/izlude.fld the one iRO classic loki uses?

**Comment by c4c1n6kr3m1** [comment]
no,
fields/EP14.1/izlude.fld.gz and fields/EP15.1/izlude.fld.gz are new izlude

fields/izlude.fld.gz is old izlude

it's the resnametable problem

try extract again if you still have the original old izlude or 
get this https://raw.githubusercontent.com/OpenKore/openkore/master/fields/izlude.fld.gz

than put inside \field
delete \field\izlude.dist and \map\izlude.xpm if files exist

go to tables\iRO\Classic\official
do you see all txt files ? move all txt files to tables\iRO\Classic\
i don't know why those files inside offical folder, my bot years behind, but in my oppinion it should not be there

that's it, try use wxstart.exe to see if the map is correct

**Comment by jeraffas** [comment]
thank you. it works now
