### ISSUE TITLE
how to remove loot mapping?

### ISSUE THREAD

**Issue by chuvachok101** [OpenKore/openkore#1710]
Hello. Tell me how to remove the display of the dropping loot in the console?

**Comment by fadreus** [comment]
@chuvachok101 
http://wiki.openkore.com/index.php/SquelchDomains

Use forum if it's not openkore issue.
Git isn't place for Q&A

**Comment by fadreus** [comment]
@chuvachok101 
http://openkore.com/index.php/ShowDomain
http://wiki.openkore.com/index.php/SquelchDomains

Use forum if it's not openkore issue.
Git isn't place for Q&A

**Comment by fadreus** [comment]
@chuvachok101 
http://openkore.com/index.php/Domain
http://openkore.com/index.php/ShowDomain
http://wiki.openkore.com/index.php/SquelchDomains

Use forum if it's not openkore issue.
Git isn't place for Q&A
