### ISSUE TITLE
The Server has denied your connection

### ISSUE THREAD

**Issue by clouds015** [OpenKore/openkore#1713]
The Server has denied your connection.

i already follow all the procedure can anyone help me.

thanks.

**Comment by sctnightcore** [comment]
Server ?

**Comment by clouds015** [comment]
vanro sir

**Comment by sctnightcore** [comment]
@clouds015  

packet key . try with youself.

**Comment by clouds015** [comment]
how? i just used peek,!PEviewer and WPE for the server info.

**Comment by sctnightcore** [comment]
@clouds015  openkore.com

**Comment by clouds015** [comment]
@sctnightcore 
thanks i already resolved the issue ;)
