### ISSUE TITLE
twro restart server

### ISSUE THREAD

**Issue by u811312** [OpenKore/openkore#1718]
who can refresh twro restart server
218.32.4.152
ob on 1/30/2018

**Comment by sctnightcore** [comment]
link server ?

**Comment by u811312** [comment]
i know the server ip is 218.32.4.152
but i dont know how to set on tables/servers

**Comment by sctnightcore** [comment]
@u811312  give me link server ! now !!!!!

**Comment by u811312** [comment]
i dont know what you mean

**Comment by u811312** [comment]
link server is

**Comment by u811312** [comment]
<?xml version="1.0" encoding="euc-kr" ?>

<clientinfo>

	<desc>Taiwan Restart Server</desc>
	<servicetype>taiwan</servicetype>
	<servertype>primary</servertype>
	<hideaccountlist></hideaccountlist>
	<extendedslot></extendedslot>
	
	<connection>
		<display>Taiwan Restart Main</display>
		<desc>None</desc>
		<address>218.32.4.152</address>
		<port>6900</port>
		<version>1</version>
		<langtype>4</langtype>
		<registrationweb>https://member.gnjoy.com.tw/signin.aspx</registrationweb>
		<aid>
			<admin>10000001</admin>
		</aid>
	</connection>
</clientinfo>


</clientinfo>

**Comment by sctnightcore** [comment]
server use cheat defender GG

**Comment by u811312** [comment]
WoW
