### ISSUE TITLE
OpenKore stucks When there is no item drop from Monsters.

### ISSUE THREAD

**Issue by topkung1** [OpenKore/openkore#172]
If there is no item drops from monster, It will stuck for awhile (7-8secs)

If item drops from monsters OpenKore will continue searching for monsters after that

any helps?

**Comment by m3kgin3er** [comment]
Hello. The problem is when the loot is not yours.
There's a problem when we receive KS or give KS.

Anyway, i've suffered with this, 'case the client-side say for you : This item is not yours, but Kore is trying to pickup the item .
