### ISSUE TITLE
Command - Doridori

### ISSUE THREAD

**Issue by Fadreus** [OpenKore/openkore#1725]
###### Summary:
Using doridori command in-game instead of look head to trigger Happy Break Status for Taekwon Class

###### Affected configuration(s)/ file(s):
src/Commands.pm
```
sub cmdDoriDori {
	if (!$net || $net->getState() != Network::IN_GAME) {
		error TF("You must be logged in the game to use this command '%s'\n", shift);
		return;
	}
	my $headdir;
	if ($char->{look}{head} == 2) {
		$headdir = 1;
	} else {
		$headdir = 2;
	}
	$messageSender->sendLook($char->{look}{body}, $headdir);
}
```
###### Impact:
Won't trigger Happy Break 

###### Expected Behavior:
Using doridori and trigger Happy Break Status every 10 seconds
![image](https://user-images.githubusercontent.com/32188494/35665229-225669a4-0760-11e8-9fa1-30e043242352.png)
![image](https://user-images.githubusercontent.com/32188494/35665694-4ab24916-0762-11e8-85da-3d151a3d183d.png)

###### Actual Behavior:
Head look only like mouse clicking.

###### Steps to Reproduce:
- 2 Taekwon class sitting besides each other
- Spam doridori command around 0.5~1 secs interval suppose to trigger Happy Break

```
doCommand doridori {
	whenStatusActive Sitting
	timeout 0.6
}
```
###### Summary:
Using doridori as it should

###### Affected configuration(s)/ file(s):
src/Commands.pm

###### Benefits:
Star Gladiator / Taekwon Master can reset Solar, Lunar & Stellar Maps without going to hospital for Tunnel Carpel.

###### Additional Details:

<details>
<summary>Not a bug but it suppose to work as it should.</summary

_Yeah, this is ancient stuff since no love for taekwon, guess no one tried this.
But since the Star Emperor/Soul Reaper class is coming, this might not be useful anymore (Guess I'm 13 years late?)_

</details>

**Comment by c4c1n6kr3m1** [comment]
can u sniff the packet both using client and bot ? , during Happy Break will better

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1 
iRO use packet 3 key . 
I think Decode send packet .

**Comment by fadreus** [comment]
I tried with XKore 0 = The head turn but not /doridori as in game. (No buff)
I tried with XKore 1 = Head didn't turn & manually using /doridori from hotkeys client disconnect.
_(Spam to many or just wrong packets?)_

As far as I'm concern, this doesn't work on any RO _(From what I've read)_
（ノ♯｀△´）ノ~’┻━┻

**Comment by fadreus** [comment]
I tried with XKore 0 = The head turn but not /doridori as in game. (No buff)
I tried with XKore 1 = Head didn't turn & manually using /doridori from hotkeys client disconnect.
_(Spam to many or just wrong packets?)_

As far as I'm concern, this doesn't work on any RO _(From what I've read)_
Can anyone confirm this?
（ノ♯｀△´）ノ~’┻━┻

**Comment by c4c1n6kr3m1** [comment]
i don't know about taekwoon

but i test dori2 using xkore 0 on iro odin
it is slow, u need to spam it right? while using client is faster
may be because my connection
or may be, because the code need to receive the packet, before send different head direction ?

**Comment by fadreus** [comment]
The rumor has it to spam doridori 6 times in 10 seconds.
I test with client for 0.5 sec; 2 doridori/sec and it triggers.
But then I figured only the last 5 seconds that matters. _(Before the recovery number shows)_

_(I test & spam using [Mario Underground BGM rhythm](https://www.youtube.com/watch?v=c0SuIMUoShI). It has 6 tones & 1 sec pause for 10 sec for this "myth")_

I'm no good playing with packets but I figured openkore didn't use doridori, instead just turn the head after checking this;

```
sub sendLook {
	my ($self, $body, $head) = @_;
	my $msg;
		$msg = pack("C*", 0x9B, 0x00, 0xF2, 0x04, 0xC0, 0xBD, $head,
					0x00, 0xA0, 0x71, 0x75, 0x12, 0x88, 0xC1, $body);	
	$self->sendToServer($msg);
	debug "Sent look: $body $head\n", "sendPacket", 2;
	$char->{look}{head} = $head;
	$char->{look}{body} = $body;
}
```
I guess to trigger happy mode, one does not simply shake their head.
Σ（￣□￣；）

**Comment by fadreus** [comment]
Some insight I could use?
Or I'll have to use macro to send packets?
Or I just use keybot?
<details>
<summary>ヽ(●ﾟ´Д｀ﾟ●)ﾉﾟ</summary>

_I want to abuse SG really bad. SG have some potential to be excellent farmer.
The only problem is I need more test & need to reset maps (rather than making new class over and over again.)_
</details>

**Comment by lututui** [comment]
I just sniffed RMS renewal. The doridori command just turns the character head. There's no such thing as a "doridori" packet, at least in RMS

**Comment by lututui** [comment]
If this is an official server, please disclose

**Comment by fadreus** [comment]
Does it trigger happy break in RMS?
I've yet to get any feedback from my acquaintance on their server _(maybe they forgot?)_ ( ≧Д≦)
I only test this on iRO Renewal. Don't have any access to other servers. (๑´╹‸╹`๑)

If there is no such thing as "doridori" packet, now I really have no idea why it won't trigger happy break.

<details>
<summary>Guess I stick to keybot for now.</summary>

_I only found legal discussion (non-bot) at Warpportal, TalonRO & NovaRO forum.
Since there is nothing on google, no one talk about this, I assume no one ever bother with it.
Most private servers offer different alternative. The struggle only lies in official servers._

</details>

**Comment by alisonrag** [comment]
someone can sniff a packet in official client?
like lututui said: doridori command just turns the character head. There's no such thing as a "doridori" packet

**Comment by lututui** [comment]
"There's no such thing as a "doridori" packet"

On rAthena. I claimed that's true for RMS, which runs on rAthena. I do not know about Herc.ws or Aegis

**Comment by fadreus** [comment]
## Details update:
XKore 1 doridori through iRO Renewal client :
![image](https://user-images.githubusercontent.com/32188494/35904809-7d890994-0c1f-11e8-8e9a-579c6adf4e3c.png)

- Spam doridori more than 0.5 sec happy break won't trigger, this switch won't appear.
- Spam 0.5 sec, happy break trigger, this switch appear.
- Spam less than 0.5, happy break won't trigger, this switch appear and disconnect occasionally.
- ### **This error appear when using doridori using any class besides Taekwon class.**

**Comment by fadreus** [comment]
## Details update:

<details>
<summary>XKore 1 doridori through iRO Renewal client : (Click here)</summary>

![image](https://user-images.githubusercontent.com/32188494/35904809-7d890994-0c1f-11e8-8e9a-579c6adf4e3c.png)

</details>

- Spam doridori more than 0.5 sec happy break won't trigger, this switch won't appear.
- Spam 0.5 sec, happy break trigger, this switch appear.
- Spam less than 0.5, happy break won't trigger, this switch appear and disconnect occasionally.
- ### **This error appear when using doridori using any class besides Taekwon class.**

**Comment by c4c1n6kr3m1** [comment]
that's sendSuperNoviceDoriDori
do we receive some an unique packet before send this , or it's automatically send by client ?

**Comment by fadreus** [comment]
The issue still persist but my intention for bringing up this issue is because of [resetting SLS Perception (Hate & Feel)](https://forum.talonro.com/topic/18568-star-gladiator-feelinghatred-reset-guide-doridori/). So now I got it to reset somehow, I'll drop this issue here for future reference until someone have a clue.

_I actually been trying for the last 2 weeks with my limited capabilities & now I'm blank._ （；￣д￣）
_Need expert to take a look or this can be ignored when Star Emperor released._ ヾ（〃＾∇＾）ﾉ♪

<details>
<summary> I ran them overnight to see what else coming up & here is the console log.</summary>

```
# The real content was too long, I removed few unrelated & repetitive entries.
# Most likely every 10 seconds after I start sitting.
# This test ran in xKore 1 mode since I can't get it work in Xkore 0.

[Feb 7 22:06:08 2018.12] Packet Parser: Unknown switch: 0925
[Feb 7 22:16:07 2018.67] Packet Parser: Unknown switch: 0925
[Feb 7 22:26:08 2018.79] Packet Parser: Unknown switch: 0925
[Feb 7 23:22:48 2018.48] Packet Parser: Unknown switch: 0925
[Feb 7 23:32:48 2018.33] Packet Parser: Unknown switch: 0925
[Feb 7 23:44:02 2018.38] Packet Parser: Unknown switch: 0925
[Feb 7 23:54:01 2018.65] Packet Parser: Unknown switch: 0925
[Feb 8 00:04:01 2018.91] Packet Parser: Unknown switch: 0953
[Feb 8 00:14:02 2018.54] Packet Parser: Unknown switch: 0953
[Feb 8 00:24:01 2018.33] Packet Parser: Unknown switch: 0953
[Feb 8 00:34:01 2018.35] Packet Parser: Unknown switch: 0953
[Feb 8 00:44:01 2018.42] Packet Parser: Unknown switch: 0953
[Feb 8 00:54:01 2018.60] Packet Parser: Unknown switch: 0953
[Feb 8 01:04:02 2018.49] Packet Parser: Unknown switch: 0953
[Feb 8 01:14:02 2018.10] Packet Parser: Unknown switch: 0953
[Feb 8 01:24:01 2018.95] Packet Parser: Unknown switch: 0953
[Feb 8 01:34:01 2018.88] Packet Parser: Unknown switch: 0953
[Feb 8 01:44:02 2018.11] Packet Parser: Unknown switch: 0953
[Feb 8 02:04:01 2018.42] Packet Parser: Unknown switch: 092B
[Feb 8 02:14:01 2018.64] Packet Parser: Unknown switch: 092B
[Feb 8 02:24:02 2018.58] Packet Parser: Unknown switch: 092B
[Feb 8 02:34:02 2018.15] Packet Parser: Unknown switch: 092B
[Feb 8 03:19:23 2018.45] Packet Parser: Unknown switch: 092B
[Feb 8 03:29:22 2018.93] Packet Parser: Unknown switch: 092B
[Feb 8 03:39:23 2018.40] Packet Parser: Unknown switch: 092B
[Feb 8 03:49:22 2018.94] Packet Parser: Unknown switch: 092B
[Feb 8 03:59:23 2018.26] Packet Parser: Unknown switch: 092B
[Feb 8 04:09:25 2018.22] Packet Parser: Unknown switch: 0882
[Feb 8 04:19:23 2018.10] Packet Parser: Unknown switch: 0882
[Feb 8 04:29:23 2018.73] Packet Parser: Unknown switch: 0882
[Feb 8 04:39:23 2018.17] Packet Parser: Unknown switch: 0882
[Feb 8 05:12:56 2018.45] Packet Parser: Unknown switch: 0882
[Feb 8 05:22:56 2018.44] Packet Parser: Unknown switch: 0882
[Feb 8 05:32:57 2018.24] Packet Parser: Unknown switch: 0882
[Feb 8 05:42:56 2018.17] Packet Parser: Unknown switch: 0882
[Feb 8 05:52:56 2018.48] Packet Parser: Unknown switch: 0882
[Feb 8 05:57:01 2018.74] Your Hate and Feel targets have been resetted.
[Feb 8 06:02:56 2018.58] Packet Parser: Unknown switch: 086F
[Feb 8 06:12:56 2018.23] Packet Parser: Unknown switch: 086F
[Feb 8 06:22:56 2018.65] Packet Parser: Unknown switch: 086F
[Feb 8 06:32:56 2018.49] Packet Parser: Unknown switch: 086F
[Feb 8 06:42:56 2018.58] Packet Parser: Unknown switch: 086F
[Feb 8 06:48:52 2018.52] Your Hate and Feel targets have been resetted.
[Feb 8 06:52:58 2018.24] Packet Parser: Unknown switch: 086F
[Feb 8 07:02:56 2018.56] Packet Parser: Unknown switch: 086F
[Feb 8 07:12:56 2018.48] Packet Parser: Unknown switch: 086F
[Feb 8 07:22:56 2018.19] Packet Parser: Unknown switch: 086F
[Feb 8 07:32:56 2018.35] Packet Parser: Unknown switch: 086F
[Feb 8 07:42:57 2018.30] Packet Parser: Unknown switch: 086F
[Feb 8 07:52:56 2018.81] Packet Parser: Unknown switch: 086F
[Feb 8 08:02:56 2018.50] Packet Parser: Unknown switch: 0920
[Feb 8 08:12:56 2018.53] Packet Parser: Unknown switch: 0920
[Feb 8 08:22:56 2018.38] Packet Parser: Unknown switch: 0920
[Feb 8 08:32:56 2018.87] Packet Parser: Unknown switch: 0920
[Feb 8 08:42:56 2018.61] Packet Parser: Unknown switch: 0920
[Feb 8 08:52:56 2018.53] Packet Parser: Unknown switch: 0920
[Feb 8 09:12:56 2018.73] Packet Parser: Unknown switch: 0920
[Feb 8 09:22:56 2018.16] Packet Parser: Unknown switch: 0920
[Feb 8 09:32:56 2018.62] Packet Parser: Unknown switch: 0920
[Feb 8 09:42:56 2018.59] Packet Parser: Unknown switch: 0920
[Feb 8 09:52:56 2018.42] Packet Parser: Unknown switch: 0920
[Feb 8 10:02:56 2018.18] Packet Parser: Unknown switch: 0A69
[Feb 8 10:12:56 2018.23] Packet Parser: Unknown switch: 0A69
[Feb 8 10:22:56 2018.16] Packet Parser: Unknown switch: 0A69
[Feb 8 10:32:56 2018.56] Packet Parser: Unknown switch: 0A69
[Feb 8 10:42:56 2018.13] Packet Parser: Unknown switch: 0A69
[Feb 8 10:52:56 2018.17] Packet Parser: Unknown switch: 0A69
[Feb 8 11:02:57 2018.17] Packet Parser: Unknown switch: 0A69
[Feb 8 11:58:14 2018.48] Packet Parser: Unknown switch: 0253
```

</details>

**Comment by fadreus** [comment]
If there's in need ID with Taekwon Class to test, I can make dummy account for iRO Renewal in couple of days.

**Comment by fadreus** [comment]
I give up.
(ノಠ益ಠ)ノ彡┻━┻

**Comment by moneyisgod** [comment]
"There's no such thing as a "doridori" packet"

I refuse it.
Because it's a client packet sent. If you send the doridori in bRO using XKore2, but instead of using the command in Kore, use in the RO window, type in the chat window the '/doridori' and will see a packet message error. Regularly i receive warns using XKore2.

**Comment by lututui** [comment]
Stop misquoting me

**Comment by c4c1n6kr3m1** [comment]
use wxstart
XKore 2
debugPacket_received 2
debugPacket_ro_sent 2
debugPacket_sent 2

record your char ID hex, you will get this char ID on relog
---------- Account Info ----------
Account ID: YYYYYY     AA BB CC DD
Sex:        Boy

that "AA BB CC DD" is your ID on hexa

then show the console report ,becareful for the ID, change it to something

**Comment by Fadreus** [comment]
Actually I was planning on making SN, TKK, TKM & SL _(dummy accounts)_ for anyone to test but I don't have spare PC & time to test lately. I'll get back to this later.

**Comment by Fadreus** [comment]
Erm, about that. I'll make the char later to test.

**Comment by Fadreus** [comment]
Erm, about that. I'll make the char later to test. Already deleted those since I give up already >w<.
