### ISSUE TITLE
Openkore is blocked at kRo:Zero

### ISSUE THREAD

**Issue by tartaryaho** [OpenKore/openkore#1726]
###### Summary: 
Hi there, I'm playing zero, and there was newest update on 1/31/2018 ! It changed the login system on client, need otp to login on client. If you don't have otp, then have to get access through the web site. This is very annoying :( This is a big problem at zero sverver ! Openkore is dead after the patch...so sad.. I tried xkore 1/2/3 with poseidon, but all fail.. Before I used xkore 0 without poseidon, and it worked well except auto sell/buy operation.

briefly, first, does xkore 1/2/3 work on the zero? second, can we add one more stop to insert otp?

###### Affected configuration(s)/ file(s):
poseidion/config

###### Impact:
openkore doesn't work anymore for zero

###### Expected Behavior:
openkore will rework well

###### Summary:
second, can we add one more stop to insert otp on the zero client?

###### Benefits:
openkore will rework well

###### Drawbacks:
it won't be easy task

###### Additional Details:

![image](https://user-images.githubusercontent.com/36030218/35669590-f2c50948-0778-11e8-8668-069edc042f40.png)
![image](https://user-images.githubusercontent.com/36030218/35669602-00d535bc-0779-11e8-8aef-110a16fe8f4f.png)
these are my set up for poseidon

![image](https://user-images.githubusercontent.com/36030218/35669905-0a7812be-077a-11e8-909f-e665d281a1a4.png)
poseidon initialized,

![image](https://user-images.githubusercontent.com/36030218/35669935-243cfba6-077a-11e8-9a4c-2bc88e708abf.png)
I got it with no error,

![image](https://user-images.githubusercontent.com/36030218/35670003-631a93a6-077a-11e8-88d9-a301d229eddd.png)
but it says, 'currently the access is delayed, try it again.' maybe it's timeout..?

and these are steps to login on official client
![image](https://user-images.githubusercontent.com/36030218/35669648-2e1c807a-0779-11e8-8cb3-75b91c32dfe7.png)
first
![image](https://user-images.githubusercontent.com/36030218/35669658-3c655f3a-0779-11e8-94b9-30a242aed13c.png)
and second. I got an error and be banned cuz I don't set otp for this account. It says, 'go to web site to play ro, bacause u don't have otp.'

this is ip, I'm adding this, maybe it will help you
![image](https://user-images.githubusercontent.com/36030218/35669811-aea6e096-0779-11e8-8400-d362ccbec9c7.png)

I'm studying openkore, but it's still hard for me. can someone help me..!?

**Comment by sctnightcore** [comment]
https://discord.gg/f5svzJ8
come here
