### ISSUE TITLE
Open kore Is no longer working with Warpportal Re-Start Server

### ISSUE THREAD

**Issue by DinaHarris** [OpenKore/openkore#1731]
Open kore Is no longer working with Warpportal Re-Start Server

**Comment by DinaHarris** [comment]
It telling me that there is an error with MAP

**Comment by masue** [comment]
we need ss bro

**Comment by ayie6285** [comment]
its okay nothing problem.. >.<

**Comment by DinaHarris** [comment]
Please can you tell me those information or tell me about how to get those things? @ayie6285

**Comment by sctnightcore** [comment]
download new again
