### ISSUE TITLE
xKore1 is not working on kRo:zero (freeze)

### ISSUE THREAD

**Issue by tkwk6428** [OpenKore/openkore#1738]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 
xKore1 is not working on kRo:zero
###### Affected configuration(s)/ file(s):
control/config.txt
###### Impact:
when I start client, wxstart is freezed.
###### Summary:
kRo:zero can't use poseidon now. and we can't use in kRo:zero (Because of MOTP)
###### Affected configuration(s)/ file(s):
연결 중 (112.175.128.135:6900)... 연결되었습니다.
<< Received packet:      006A - Connection Failed [23 bytes]
종료 중 (112.175.128.135:6900)...종료되었습니다.
The server has denied your connection for unknown reason (119).

**Comment by sctnightcore** [comment]
Work only xkore0 xD

**Comment by tkwk6428** [comment]
Now its working???
