### ISSUE TITLE
No access due to updates Zero

### ISSUE THREAD

**Issue by claydoll1** [OpenKore/openkore#1739]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

## ------------------ Bug Report Template ------------------
Summary: No access due to updates
Affected configuration(s)/ file(s):openkore-b800c121f5d375e98572b4d96c5413429060f031
Include relevant code snippets and source code references

Impact: OTP is a prerequisite
![1](https://user-images.githubusercontent.com/36101450/35766293-dda0be4e-0918-11e8-915d-b6433478a114.png)
plz help

**Comment by sctnightcore** [comment]
go IRC openkore
