### ISSUE TITLE
How can we use openkore in zero?

### ISSUE THREAD

**Issue by tkwk6428** [OpenKore/openkore#1740]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 
How can we use openkore in zero
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:
Our korean players want to know bypass MOTP
Someone say its already solve in discord
Plz invite code
Thankyou.
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
@tkwk6428
https://discord.gg/XYpJXA

**Comment by pss757** [comment]
@alisonrag  The invitation to Discode Code is said to be incorrect or expired Please send me a new discode invitation.

**Comment by tkwk6428** [comment]
@alisonrag me too plz new invitation address

**Comment by cassandra209** [comment]
come on!

**Comment by 1e34** [comment]
@alisonrag Hello, plz new invitation address.. Thk

**Comment by jiandan7927** [comment]
@alisonrag me too plz new invitation address ty

**Comment by computernala** [comment]
hello. Help me plz. new invitation address. Thx

**Comment by computernala** [comment]
@alisonrag hello. Help me plz. new invitation address. Thx

**Comment by sctnightcore** [comment]
https://discord.gg/aJ5tu  
30 min xD

**Comment by openkorezero** [comment]
@sctnightcore The invitation to Discode Code is said to be incorrect

**Comment by sctnightcore** [comment]
@openkorezero  
wait next time . 

now have many user join . but fake offline . i want to ban him xD

**Comment by openkorezero** [comment]
@openkorezero yep
I want to know how to avoid motpt.
I can code.

**Comment by cassandra209** [comment]
plz let me know

**Comment by openkorezero** [comment]
I am not sure how to check the login from the server.......
i intend to use motpt
can I use it when I modify the sendTokenToServer function?

**Comment by myjae** [comment]
please let me know too..

**Comment by sctnightcore** [comment]
wait .

**Comment by cassandra209** [comment]
it is expirated...

**Comment by sctnightcore** [comment]
You're too late
 @cassandra209  hahahahah

**Comment by cassandra209** [comment]
what are you want

**Comment by cassandra209** [comment]
come on guys

**Comment by computernala** [comment]
@sctnightcore reply discord plz

**Comment by sctnightcore** [comment]
@computernala  wait next time .hahahahahaha

**Comment by computernala** [comment]
@sctnightcore Well..What time is it next?

**Comment by sctnightcore** [comment]
next year , i think .

**Comment by cassandra209** [comment]
copy that

**Comment by cassandra209** [comment]
the time is coming

**Comment by sctnightcore** [comment]
https://discord.gg/69B8aT 1 day / 25 user .
