### ISSUE TITLE
sctnightcore, alisong someone give us the discord invite code.

### ISSUE THREAD

**Issue by tkwk6428** [OpenKore/openkore#1742]
You don't have to worry about spy.
first, If there was a spy, the file would have already been filed.

Second,The OpenKore program has already been detected.
Evidence is that the program is detected when you turn start.exe on with Ragnarok.
They are detecting the program by checking the hash value of the file.

Third, No plug-ins have been detected so far.

So, Give us discord invite code, or just upload the plugin on web
I think it's the act of monopolizing the program.

**Comment by sctnightcore** [comment]
https://discord.gg/aJ5tu 

30 min xD

**Comment by cassandra209** [comment]
plz update

**Comment by sctnightcore** [comment]
wait xD

**Comment by han9090** [comment]
discord Invitation code plz 
how to Bypass motp?
