### ISSUE TITLE
How to new a office server in openkore

### ISSUE THREAD

**Issue by s951010sam** [OpenKore/openkore#1753]
###### Summary:
Taiwan's restart server officially operated in the end of January.
I try to new office server in the openkore, but it don't work.

###### Affected configuration(s)/ file(s):
server.txt
```
[twRO - Restsrt]
ip 218.32.4.152
port 6900
master_version 5
version 1
serverType twRO
serverEncoding Big5
charBlockSize 147
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
recvpackets recvpackets.txt
addTableFolders twRO
captcha 0
shuffle 1
crypt 1
sync 1
```
###### Additional Details:
I have tried to retrieve the package and get the version number.
but when I login the map server will be disconnected
but the account server is successfully
I also have tried to extractor this new server exe file,
but I get the following error message
![image](https://user-images.githubusercontent.com/13153677/35900509-47211f02-0c0d-11e8-8eff-09d497e21ff7.png)
Please help solve or teach me how to do it

**Comment by sctnightcore** [comment]
server use with cdclient

**Comment by s951010sam** [comment]
I move packet_extract to the ro dir
and run the cmd
got following
![image](https://user-images.githubusercontent.com/13153677/35917144-f56f6f5c-0c47-11e8-9d4c-a19984f5b62c.png)

**Comment by sctnightcore** [comment]
@s951010sam  problem is cdclient not packet_extract .

**Comment by s951010sam** [comment]
problem is cdclient?
Sorry for not understanding
Can you explain more details?thx.

**Comment by fadreus** [comment]
@s951010sam Check RO directory, there should be 1 file name `cdclient.dll`
