### ISSUE TITLE
Bug with maps: in_sphinx3 and in_sphinx5

### ISSUE THREAD

**Issue by ragdroll** [OpenKore/openkore#1757]
###### Summary: 
Server: Ragnarok Restart
![in_sphinx_problem](https://user-images.githubusercontent.com/35811197/35972148-c7dd8ac2-0cb7-11e8-82c1-168daf2c0e90.jpg)

**in_sphinx5**
The bot AI does not know what to do when he enters those _two yellow areas_ in the image above. It keeps spaming that he could not find the path to some random route in in_sphinx5 till he finds one in the same yellow area, like he is traped there.

**in_shpinx3**
If you choose to walk to in_sphinx4 or in_sphinx5 without teleport, everything is fine. If you choose to use the teleport option till he is close to the portal, the AI "thinks" that the _yellow circle_ in the image is the portal to the next map level. When he is close to that portal, he starts walking, once he enters the portal, he keeps teleporting again, even if he is close to the real portal to sphinx4, he will teleport.

**Comment by fadreus** [comment]
http://openkore.com/index.php/PortalRecord
http://openkore.com/index.php/Portals.txt
http://openkore.com/index.php/Route_teleport_minDistance

in_sphinx5 not a bug. Just need to add portals or enable portal record.
in_sphinx3 you can set minDistance before start to walk.
