### ISSUE TITLE
recvpackets Private Serve

### ISSUE THREAD

**Issue by domingosliraneto** [OpenKore/openkore#1761]
Hello, I am having difficulty extracting the recvpackets from the following .exe:
[RagnaSnow.zip](https://github.com/OpenKore/openkore/files/1709586/RagnaSnow.zip)
can anybody help me?

**Comment by sctnightcore** [comment]
@domingosliraneto  use PEEK

**Comment by domingosliraneto** [comment]
Packet: Tokenizer: Switch desconhecido: 0069

**Comment by sctnightcore** [comment]
use recvpacket from tables/kRO/servertype

**Comment by domingosliraneto** [comment]
Dados recebidos deixados no buffer:
================================================
3 bytes   Feb 09 09:59:16 2018
  0>  81 00 08

**Comment by domingosliraneto** [comment]
# http://www.ragnasnow.com.br/
ip 54.233.170.72
port 6900
version 51
master_version 2
serverType kRO_RagexeRE_2017_11_01b
recvpackets recvpackets.txt
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2014_10_22b;translated;translated/kRO_english;kRO
sendCryptKeys 0x3E1411AF, 0x6C744497, 0x7CFA1BDE
pinCode 0

**Comment by sctnightcore** [comment]
- - check clientdate 
openkorebrasil.org

**Comment by domingosliraneto** [comment]
@sctnightcore 
Hello, I'm trying to all of them as forms, but it says that the client is protected, but it is not because I am using wpe pro for good. I can not in any way configure openkore for this server, could you help me try?
![image](https://user-images.githubusercontent.com/11670306/36028179-36e6e59e-0d85-11e8-83f2-4a09bbc80ada.png)

**Comment by sctnightcore** [comment]
go discord room . openkore bRO . i will help you .

**Comment by domingosliraneto** [comment]
Do you have the chat link?

**Comment by domingosliraneto** [comment]
My user is no discord is #6315.

**Comment by sctnightcore** [comment]
post in http://openkorebrasil.org/ 

i will help you if have freetime

**Comment by domingosliraneto** [comment]
I tried there, but still I still do not answer.

**Comment by sctnightcore** [comment]
give me link you post in forum !

**Comment by domingosliraneto** [comment]
They have not yet approved my registration.

**Comment by sctnightcore** [comment]
@domingosliraneto  check email .

**Comment by domingosliraneto** [comment]
http://openkorebrasil.org/index.php?/topic/4526-tempo-esgotado-no-servidor-de-mapas-conectando-se-ao-servidor-de-contas/

**Comment by domingosliraneto** [comment]
@sctnightcore Thank you very much, everything went well!
If you are in need of C / C ++ Developer I am at your disposal.
