### ISSUE TITLE
Hunting MVP location / tomb location

### ISSUE THREAD

**Issue by plokislokis** [OpenKore/openkore#1764]
Hi Team, I'm trying to  create a macro for hunting MVP location / Mvp tomb location. I created a macro but doesn't work properly. I wanted my bot to use teleport when "idle" and whenever an MVP or MVP tomb is spotted it will send message to my other character that it found the MVP/Tomb. My current macro does work whenever an MVP is spotted but doesn't work on tombs. Can someone enlighten me whats wrong. Here are my scripts.

**Config.txt**
teleportAuto_idle 1

**Macros.txt**
automacro search {
console /Map Change/i
exclusive 1
call {
pause 1
do nl
release search
}
}

automacro tomb {
console /Tomb/i
exclusive 1
call {
pause 1
do pm "character1" tomb
pause 1
release tomb
}
}

automacro boss {
console /Orc Lord/i
exclusive 1
call {
pause 1
do pm "character1" MVP
pause 1
release boss
}
}

**Comment by fadreus** [comment]
Use forum.
Git for fix stuff, not help stuff.

**Comment by alisonrag** [comment]
this section is to report bug, not to help with personal stuff
