### ISSUE TITLE
Error use flywing/buterflywing/para team mark

### ISSUE THREAD

**Issue by banirizal** [OpenKore/openkore#1766]
Try to use Para Tim Mark, Flywing, Buterflywing, and something happen being error like this

![eror](https://user-images.githubusercontent.com/34872048/36069473-3db4c730-0f1d-11e8-9862-db80a7e28b6c.png)

**Comment by sctnightcore** [comment]
Server?

**Comment by banirizal** [comment]
idRO renewal @sctnightcore

**Comment by sctnightcore** [comment]
@banirizal  not sure in idRO_RE . Maybe use xkore 3

**Comment by oqhadev** [comment]
i know the problem
but since im not botting on idRO anymore and busy IRL, i didnt try to solve it
the problem is idRO has added new Packet after map_load
and it should be easy to fix

**Comment by banirizal** [comment]
@oqhadev it's mean we must generate new recvpackets from ragexe idro renewal?

**Comment by sctnightcore** [comment]
@banirizal  give me last client . i will use allanon tool .

**Comment by banirizal** [comment]
@sctnightcore  here the ragexe
[Ragexe.zip](https://github.com/OpenKore/openkore/files/1722197/Ragexe.zip)

**Comment by VeteranIdro** [comment]
@sctnightcore how do you use allanon tool? there's tutorial for it?

**Comment by sctnightcore** [comment]
@VeteranIdro  perl 1.pl Ragexe.exe

**Comment by alisonrag** [comment]
as i can see in console you bot is trying to use teleportation and use fky wing at same time

**Comment by VeteranIdro** [comment]
@sctnightcore where's the allanon tool app? i didnt found on google or github

**Comment by banirizal** [comment]
@alisonrag i didnt try to use teleport at the same time, it's mean if i try do that, how to solve it? the logic explanation is idRO has added new Packet after map_load so we need new recvpackets, i put last client on this thread, still waiting @sctnightcore to update new recvpackets from allaon tool

**Comment by oqhadev** [comment]
first u must find the `new packet` u can easily find it with sniff tcp raw packet app like smartsniff
if u familiar with the packet . u can easily find the new packet 
if not, just compare all packet to servertypeXX.pm / idro.pm 

sorry if not give it all,u know lah indonesian people,
