### ISSUE TITLE
IRO [RE:START] Time out on map issue after recent maintainance

### ISSUE THREAD

**Issue by btleo** [OpenKore/openkore#1774]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary:  Character time out on map server every time when log in, and get into indefinitely loop: connected server account => time out map server => reconnect server account => time out map server.
It happens after 14th Feb maintenance, which I think they implied some antibot features.

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
Download new openkore and test it again
