### ISSUE TITLE
.Gat to plain text

### ISSUE THREAD

**Issue by Shizuke** [OpenKore/openkore#1777]
Hello i saw (and also use) the tool that comes with openkore called: "gat_to_fld2"
What i need is to do something like a gat to txt to have a matrix of cell info like: 
0,1,0,0,0,2,2,4,0,0,8,4
0,1,1,1,0,0,4,4,4,0,8,8
and so on

Is there a way to edit the gat_to_fld2 to make it output a file that writes it in plain text?
Tried myself but i know nothing about perl. Also i still don't know how it starts to read, i mean in what order if south west first and then moves in x axis until the final is reached then goes does something like y+1 and reads the entire x and again.
I'm asking here because i didn't see something like that anywhere, tried searching everywhere.
Also using GRF Editor past month i was making a flatmap grf and idk how i saw a matrix like that one i shown but idk how to reproduce this again because at that time i didn't pay attention.
Hope you can help me, please been the entire week with this

Thank you for your time.

Sorry if this is not supposed to be here, but understand idk where i can ask because i get no answer on other places and the only  .gat to something else file i found is openkore's one.

Again thank you for your time

**Comment by lututui** [comment]
You could edit gat_to_fld.pl and remove the conversion part. Just whenever there's

```print $out pack(SOMETHING_A, SOMETHING_B);```

replace with

```print $out SOMETHING_B;```

This should take the packing out of the equation
