### ISSUE TITLE
Range Attack Delay

### ISSUE THREAD

**Issue by michael7978** [OpenKore/openkore#178]
My ranger seems to delay after hitting a monster. Seems like the program is relocating my character location. From my observation, the cursor in the mini map is still moving when my character starts using range skill (Double Strafe), when its done killing the monster, it will delay for 3-4 sec, then the cursor will roll back to my character current position before it start moving. Any solution to this tiny problem, cuz its delaying my character from killing faster. Any advise would be appreciated. thank you

**Comment by tarkungZ** [comment]
I have this issue too

**Comment by Jozoko** [comment]
Cursor? A u serious ?)))))))

Just edit delays in timeouts.txt for attack delay and after skill delay

**Comment by Cozzie** [comment]
@Jozoko attack delay and after skill delay does not cause 3-4 sec in delays.
@michael7978  Please post a log.

**Comment by fawkbr** [comment]
Bump, it's 2018 and i having quite the same problem in Chaos/iRO. I'm a Hunter and the bot always stop in a random time after it kills a monster. I checked everything in config and timeouts, without success.

**Comment by fawkbr** [comment]
And yes, i'm using Xkore, when i click to move after the kill, it resumes it's activity.

**Comment by fawkbr** [comment]
I made a macro (working on 02.2018 on updated openkore) to unstuck when the bot stop moving. Didn't realized a better way (even working hard to find) to fix the stop for random seconds before leaving. It's simple as hell but works fine every 5 seconds, nice timing for maps full of mobs. 

#################################
## Unstuck macro, Archer/Evos problem ##
#################################

automacro STUCKAFTERKILL {
InMap MAPSYOUFIGHTMONSTERS <-- Ex: pay_fild08
timeout 5
run-once 1
exclusive 1
disabled 0
call UNSTUCKMOVE
}

macro UNSTUCKMOVE {
do south
release STUCKAFTERKILL
}
