### ISSUE TITLE
Autosell doesn't sell items

### ISSUE THREAD

**Issue by userix** [OpenKore/openkore#1780]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

**Comment by Nipodemos** [comment]
which server?
do you have a print of the moment the openkore tries to sell?

**Comment by userix** [comment]
My mistake, gravity did change up the name of some of the items, such as "Skel-bone" to "skeleton bone" and "powder of butterfly" to "butterfly powder".  Didn't notice it at first glance :)
