### ISSUE TITLE
disconnected issue to renewal. can't connect. dont bother. we will wait. thanks dev team. 👍 

### ISSUE THREAD

**Issue by ramojskie** [OpenKore/openkore#1801]
disconnected issue to renewal. can't connect. dont bother. we will wait. thanks dev team. 👍

**Comment by sctnightcore** [comment]
server ?

**Comment by ramojskie** [comment]
@sctnightcore  renewal iRO

**Comment by ramojskie** [comment]
thor iRO renewal. can't connect.  thanks dev team. 👍   thanks @sctnightcore
