### ISSUE TITLE
IRO ISSUE 02/23/18

### ISSUE THREAD

**Issue by ariechecoii** [OpenKore/openkore#1806]
Slot 0: LORD MOMONGA (Thief, Boy, level 45/39, pay_fild01)
------------------------------------------
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 32 F0 44 02 (38072370)
MAP Name: pay_fild01.gat
MAP IP: 128.241.92.130
MAP Port: 4506
-----------------------------
Closing connection to Character Server
Disconnecting (128.241.92.130:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.130:4506)... connected
Timeout on Map Server, connecting to Account Server...
Connecting to Account Server...
[reconnect] Login retry number 2, setting reconnect timeout to 74 seconds.
Connecting (128.241.92.162:6800)... connected
Timeout on Account Server, reconnecting. Wait 74 seconds...

**Comment by sctnightcore** [comment]
download new openkore and test it again .

**Comment by ariechecoii** [comment]
I will thank you

**Comment by ariechecoii** [comment]
Thank you so much sir its all working now i Downloaded the openkore on your profile its working

**Comment by sctnightcore** [comment]
my profile ? 
download from : https://github.com/OpenKore/openkore

**Comment by ariechecoii** [comment]
yeah I clicked your profile and there's an openkore link there hehehe thank you so much btw sir with regards on the banning system do you have any idea on how to avoid that like using macro but i don't know how do you have any guide?

**Comment by sctnightcore** [comment]
@ariechecoii  if you get ban . i feel good .

**Comment by ariechecoii** [comment]
my apology sir
