### ISSUE TITLE
Bot phRO valkyrie

### ISSUE THREAD

**Issue by ariechecoii** [OpenKore/openkore#1808]
Summary:Help openkore phRO valkyrie server
Agroup in one issue the attempts to connect to phRO server

Affected configuration(s)/ file(s): I'm a newbie dont have any bot with PH i just want to know if you can give me some link or working openkore bot for that server
pro connection files

Benefits: connect to phRO server

**Comment by fadreus** [comment]
> i just want to know if you can give me some link or working openkore bot for that server

# NO
