### ISSUE TITLE
alertsound

### ISSUE THREAD

**Issue by PrincessLei** [OpenKore/openkore#1823]
Hey guys,
Sorry totally new to programming. It seems that the plugin alertsound is not working... I just want sound alert to work when I get a private message 1:1 from someone... is there a macro I could use since the plug in is not working? Thanks...

Princess~

**Comment by sctnightcore** [comment]
if you use eventmarco 
`SimpleHookEvent packet_selfChat` 
I think . @Nipodemos

**Comment by PrincessLei** [comment]
ohhh thanks for giving me the hook idea!
This is what I came up with and it worked :dancer: 

#####ALERTSOUNDONPM#####

automacro privatemesg {
hook packet_privMsg
save MsgUser
save Msg
	call {
		do eval Utils::Win32::playSound('C:\sounds\msgpm.wav');
		log =====
		log Player $.hooksave0 said $.hooksave1
		log =====
		stop
	}
}

Thanks!!
