### ISSUE TITLE
failed to connect to server new patch iro update.

### ISSUE THREAD

**Issue by ramojskie** [OpenKore/openkore#1824]
hi i just want to update. but not to bother anyone. failed to connect to server new patch iro update march 1-2. thanks. iro renewal

**Comment by sctnightcore** [comment]
download new openkore :p

**Comment by ramojskie** [comment]
oh sorry. done download now heheh sorry to bother you @sctnightcore sctnightcore

**Comment by ramojskie** [comment]
sorry if i bother you or disturb you. thanks sir
