### ISSUE TITLE
the openkore for new vervion(CRO)

### ISSUE THREAD

**Issue by tanjunjie1988** [OpenKore/openkore#1826]
I can use the old version,it works fine...but I use the new version...The console tell me that server is blocking anytime...  How should I do?  @alisonrag @sctnightcore   thank you~~
![111](https://user-images.githubusercontent.com/36705566/36936418-2e9213d8-1f40-11e8-885d-853ae2e7665e.png)

**Comment by sctnightcore** [comment]
you ID get ban :p

discord : https://discord.gg/qvWK77w

**Comment by tanjunjie1988** [comment]
I am suer that my ID is no problem...
because in other version,i can run the poseidon and OP fine...
![111](https://user-images.githubusercontent.com/36705566/36936612-979a001e-1f42-11e8-9822-4084612859d9.png)
@sctnightcore

**Comment by sctnightcore** [comment]
Can you id to my discord ? @tanjunjie1988

**Comment by tanjunjie1988** [comment]
the previous problem has been solved...
casuse I used the encode in the new OP....but new op can encode password....xD
thx @sctnightcore 

and then,another problem appears....
I had tried change the servertype,not work....
What should I do next....

@sctnightcore @alisonrag 
thank you,sir~~
![111](https://user-images.githubusercontent.com/36705566/36937860-6f054dfe-1f54-11e8-97de-c583e3f376de.png)

**Comment by tanjunjie1988** [comment]
the previous problem has been solved...
casuse I used the encode in the new OP....but new op can encode password....xD
thx @sctnightcore
