### ISSUE TITLE
kRo Zero poseidon Server Character select server disconnected

### ISSUE THREAD

**Issue by KORLAB** [OpenKore/openkore#1828]
###### Summary: 
I want to  Openkore use to kRo Zero Server.
kRo Zero Server use GameGuard 
So I set the Poseidon server according to the guide.

###### Affected configuration(s)/ file(s):
Poseidon.txt 
ragnarokserver_ip=127.0.0.1
ragnarokserver_port=6950
queryserver_ip=127.0.0.1
queryserver_port=24390
server_type=kRO_2018-02-07a

CharBlockSize=155

debug=1

poseidon.xml (Gravity\RagnarokZero\data)

<?xml version="1.0" encoding="euc-kr" ?>
<clientinfo>
	<servicetype>korea</servicetype>
	<servertype>primary</servertype>
	<extendedslot></extendedslot>

	<connection>
		<display>Poseidon</display>
		<desc>None</desc>
		<address>127.0.0.1</address>
		<port>6950</port>
		<version>1</version>
	</connection>
</clientinfo>

**Comment by sctnightcore** [comment]
Discord : https://discord.gg/qvWK77w
