### ISSUE TITLE
Readme Proposal

### ISSUE THREAD

**Issue by codepushr** [OpenKore/openkore#183]
As OpenKore has been pushed to GitHub and is now versioned, I don't see any reason to have the readme file contain a change log.
It would make more sense to introduce the project and write a guide on how to setup Perl or build the project.
I'm thinking of contributing but have no clue where to start, as I've never written code in Perl before. Also is it possible to build OpenKore into a binary for Mac OS or Linux?

Oh and btw. check out Gitter.im - it's a chat for open source projects and let's you integrate GitHub projects and handle issues in real time.

**Comment by itsrachelfish** [comment]
Hi @codepushr !

You're right, the readme is in a serious state of neglect. It would be great if you had the time to update it and provide more information about the project. Currently all of that information is available on the OpenKore wiki:
 - How to install / run openkore:  http://wiki.openkore.com/index.php/How_to_run_OpenKore 
 - Post-install introduction: http://wiki.openkore.com/index.php/Quick_Start_Guide
 - More advanced dev information: http://wiki.openkore.com/index.php/Network_subsystem

If you'd like to chat with us, you can join #openkore on FreeNode IRC. I've seen Gitter before but unfortunately I don't think it's a good fit for this project. We're already relying on GitHub which itself is closed source, and I don't want to move all of our correspondence into yet another closed source system. 

Thanks for your interest in helping out :sparkling_heart:

**Comment by codepushr** [comment]
Will look into the resources sometime next week and propose a readme via PR. ✌🏻

**Comment by kaliwanagan** [comment]
@codepushr waiting for the PR :)
