### ISSUE TITLE
Sending Encoded Password idRO Thor Server

### ISSUE THREAD

**Issue by ayong0022** [OpenKore/openkore#1832]
Hi everyone

is anyone could help me to solve this??
![xkore didnt work](https://user-images.githubusercontent.com/37106671/37081379-38ca0d9c-2224-11e8-9506-6f8621954425.jpg)

![sending encoded password](https://user-images.githubusercontent.com/37106671/37081515-a50e4270-2224-11e8-87df-d8cda6d82105.jpg)

i've tried many time changing all those file and still stuck at here,

Thank You

Sorry that i can't write a good english.

**Comment by sctnightcore** [comment]
New packet login :p

**Comment by ayong0022** [comment]
@sctnightcore how can i find the new package login??

cause i'm trying using WPE but it didn't work. It crash when i'm starting up my Ragnarok.exe

**Comment by sctnightcore** [comment]
@ayong0022  wpe or something .

**Comment by ayong0022** [comment]
@sctnightcore i've tried to use WPE but my ragnarok got crash.

should i use another App that could hide my WPE or what?
