### ISSUE TITLE
portal.txt Kafra teleport IRO/renewal-Chaos

### ISSUE THREAD

**Issue by aozito** [OpenKore/openkore#1833]
Hello, I'm having trouble with the teleports of Kafra on the server IRO-CHAOS.
I wonder if you have an updated portal.txt with the Kafra for the Chaos server.
Thanks

**Comment by Fadreus** [comment]
You can update yourself.
So simple..

**Comment by Fadreus** [comment]
You can update it yourself.
So simple, the format is include in the file.

**Comment by sctnightcore** [comment]
You should try yourself. I'm not a slave.
