### ISSUE TITLE
Not connection

### ISSUE THREAD

**Issue by ojuniorbezerra** [OpenKore/openkore#1835]
I upgraded openkore but it did not connect to the map server.
Alguém pode me ajuda?

**Comment by sctnightcore** [comment]
server ?

**Comment by ojuniorbezerra** [comment]
bro - Thor

**Comment by enricoluigi** [comment]
http://openkorebrasil.org/index.php?/topic/3374-tortoisegit-baixar-atualizar-o-openkore/

**Comment by Nipodemos** [comment]
EN: no update for now man, lututui is without pc
PT: sem atualização por enquanto amigo, lututui está sem pc
