### ISSUE TITLE
TroExE mage Eac new Sv. Jellopy

### ISSUE THREAD

**Issue by pomza123** [OpenKore/openkore#1836]
Hi everyone

**Comment by sctnightcore** [comment]
ทำตามกฎหน่อยครับ

**Comment by Fadreus** [comment]
Da fuck sell bot? Here?
LOLOLOLOL.

**Comment by sctnightcore** [comment]
@Fadreus  tRO use EAC . 

it hard for bypass it .

**Comment by Fadreus** [comment]
So, it's oke to advertise & doing marketing here?
0,o Welp, this gonna get ugly soon.
