### ISSUE TITLE
New Server in tRO [Jellopy][revo-classic][EAC]

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1837]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
recvpacket & sync  /08/03/2561  get with something . 
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1792749/recvpackets.txt)
[sync.txt](https://github.com/OpenKore/openkore/files/1792750/sync.txt)
###### Additional Details:

@unknown-item Do you want update it ?

**Comment by pomza123** [comment]
noob

**Comment by RobotTZ** [comment]
cool :D

**Comment by Tokyo35123** [comment]
I was able to run it on novice battle ground with X3, but it would just walk back and fourth toward a wall.

Got bunch of unknown errors.

**Comment by sctnightcore** [comment]
i dont have bot . i cannot test it :p

**Comment by RobotTZ** [comment]
PLEASE HELP @unknown-item

**Comment by yunasad** [comment]
มีช่องทางการติดต่อเจ้าของโพสไหมครับ

**Comment by mrchakkit** [comment]
coming soon!
