### ISSUE TITLE
iRO classic moc_fild10

### ISSUE THREAD

**Issue by kittygrill** [OpenKore/openkore#184]
iRO classic uses an old version of morroc maps, when on lockMap moc_fild10 ai can't route to lockMap whenever it's outside the map.

**Comment by sctnightcore** [comment]
```
moc_fild10 19 207 morocc 302 207
moc_fild10 189 23 moc_fild11 189 363
moc_fild10 208 298 moc_fild06 207 18
moc_fild10 384 258 moc_fild09 30 162
```
I'm not sure it will work. @kittygrill
