### ISSUE TITLE
fRO; PM/Whisper does not work properly (console + log)

### ISSUE THREAD

**Issue by visionlol** [OpenKore/openkore#1840]
###### Affected configuration(s)/ file(s):
n/a

###### Impact: 
PM's / Whispers do not show up properly (console + log)

###### Expected Behavior:
Working PM/Whispers 

###### Actual Behavior: 
PM's / Whispers do not show up properly (console + log)
on a PM the console and log just show's up the Name of sender of the message.

###### Steps to Reproduce:
do a PM

**Comment by sctnightcore** [comment]
sniff packet from client .

**Comment by sctnightcore** [comment]
public_chat is ok

**Comment by sctnightcore** [comment]
fix PR : #1877
