### ISSUE TITLE
Map init problem

### ISSUE THREAD

**Issue by RaynV** [OpenKore/openkore#1842]
###### Summary: 
lack of packet sent after changing map / teleport IdRO

###### Affected configuration(s)/ file(s):
Network
###### Impact:
Bot stuck
###### Expected Behavior:
Change map / teleport normally
after sending 7D 00 packet, send 47 04 immediately
###### Actual Behavior:
Can't move or do anything after teleport or change map
only sending 7D 00 packet.
###### Steps to Reproduce:
Teleport or move to portal using openkore

**Comment by RaynV** [comment]
?

**Comment by sctnightcore** [comment]
@RaynV  openkore support only RE server with xkore1 xkore 3

**Comment by RaynV** [comment]
yes, i've sniffed and the client send 007D and then sent 0447. While openkore only send 007D, not sending the 0447 packet.
FYI, packet move in idro is 035F
this issue occur in both server (RE and Classic)

**Comment by sctnightcore** [comment]
@RaynV  Do you have data 0447 ? idRO ?

**Comment by RaynV** [comment]
![image](https://user-images.githubusercontent.com/25734089/37254446-e50c43ca-2578-11e8-89c3-6ae8f23aaef4.png)

**Comment by sctnightcore** [comment]
0447 is sync ? I think .

**Comment by RaynV** [comment]
Nope. It appear after portal bug fix patch. My character can't do anything unless i sent the packet manually from bot after map loaded.

**Comment by RaynV** [comment]
Now we can't do something like this in idRO
https://www.youtube.com/watch?v=qHqUOk2VQrM

**Comment by sctnightcore** [comment]
```
// packet 0x447
struct PACKET_CZ_BLOCKING_PLAY_CANCEL {
  /* this+0x0 */ short PacketType
}

```
it like kRO:zero . i will add if have freetime

**Comment by alisonrag** [comment]
^^

**Comment by banirizal** [comment]
Where file to put (add 0447 to idRO_RE) 

and this 

```
// packet 0x447
struct PACKET_CZ_BLOCKING_PLAY_CANCEL {
  /* this+0x0 */ short PacketType
}
```

from two from this [https://github.com/OpenKore/openkore/commit/69d45282ef781c0cb90c49ddd3e9c2c77b08f8ea#diff-27bcd83aae5e5fef3706cc3a14115cdcL2147](1845)

src/Network/Receive.pm & src/Network/Receive/ServerType0.pm

**Comment by sctnightcore** [comment]
Don't add 0437

**Comment by banirizal** [comment]
Add actor_action 0437 update ServerType0.pm, bot still freeze 20 second until change map

**Comment by sctnightcore** [comment]
@banirizal ! 
update you bot !

**Comment by banirizal** [comment]
New openkore you mean?

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/archive/master.zip

**Comment by RaynV** [comment]
Hi, sorry to reopen this issue. the fix working perfectly for map changing. but it didn't send 47 04 first time after login (after map loaded).

**Comment by Fadreus** [comment]
#2554

**Comment by Fadreus** [comment]
#2524
