### ISSUE TITLE
Timeout on Map Server, connecting to Account Server...

### ISSUE THREAD

**Issue by 11suppakit** [OpenKore/openkore#1858]
fixed by myself thx 👍

**Comment by Fadreus** [comment]
# * Before submitting an issue, ensure you are on the latest release
![image](https://user-images.githubusercontent.com/32188494/37507102-fe2a4d40-2927-11e8-84b8-a127ec9a6e40.png)

![image](https://user-images.githubusercontent.com/32188494/37507011-8eaf4f6a-2927-11e8-83e6-0179a6ccbc1f.png)

![image](https://user-images.githubusercontent.com/32188494/37507043-b2b65b9c-2927-11e8-8b48-e6e810c6c8db.png)

http://forums.openkore.com/viewtopic.php?f=0&t=11287
![image](https://user-images.githubusercontent.com/32188494/37507061-cf30c410-2927-11e8-8d4f-62d71392052c.png)

**Comment by 11suppakit** [comment]
sorry nerd, i'm just new here

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=0&t=129
![image](https://user-images.githubusercontent.com/32188494/37507304-c3d41ef4-2928-11e8-858e-91abd5879b1d.png)

**Comment by 11suppakit** [comment]
pickachuuu LMAO

**Comment by alisonrag** [comment]
you post a issue without give us more information. 
you dont fixed anything you just configured your openkore right in this time.

if your openkore can work in your server you have to say thanks to us openkore developers =]
