### ISSUE TITLE
Timeout on Account Server, reconnecting, Wait 64 seconds...

### ISSUE THREAD

**Issue by Jangsunsuk** [OpenKore/openkore#1860]
Help me

server : Korea Zero server

Timeout on Account Server, reconnecting, Wait 64 seconds...

![zero](https://user-images.githubusercontent.com/35761643/37509415-a2e810bc-293a-11e8-8ae9-50d357e6484c.jpg)

**Comment by gotletter** [comment]
kRO:Zero | Korea Zero server | Cdclient | Not Working
kRO:Zero server No longer supported

**Comment by Jangsunsuk** [comment]
Is there no possibility of support anymore?

**Comment by gotletter** [comment]
Maybe......

**Comment by Fadreus** [comment]
Cdclient.dll has been around since last year & no breakthrough is shared so far. (Those who can ain't sharing). So don't expect anytime soon.

**Comment by Fadreus** [comment]
Cdclient.dll has been around since last year & no breakthrough is shared so far. (Those who can ain't sharing). So don't expect solution anytime soon.
