### ISSUE TITLE
Bout Gepard

### ISSUE THREAD

**Issue by Aobchoey** [OpenKore/openkore#1864]
1. my kore see monster look like unknown , some can attack some cant attack
2. my kore dont see npc,
3. my kore see player look like monster and run follow and try to attack
4. my kore cant use all skill but can use any items

p.s. so sorry my english so bad

**Comment by sctnightcore** [comment]
Openkore don't support gepard

**Comment by hnomkeng** [comment]
@Aobchoey You can speak thai ?

**Comment by Aobchoey** [comment]
@hnomkeng Yes
