### ISSUE TITLE
Cannot login char > map [Pserver]

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#1866]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s): 
log1 : https://pastebin.com/24hgcb5h
log2 : https://pastebin.com/Q92BN6hX
sniff from client by WPE  : https://pastebin.com/uYmkXsXx
```Include relevant code snippets and source code references```
######
[pServer 2015+]
[Sometimes I can login but sometimes I can not login.]

**Comment by c4c1n6kr3m1** [comment]
looks like too much Sent sendCharLogin
char_login_pause activated ?

**Comment by sctnightcore** [comment]
maybe add timeout ? 

login > wait 1 > char > wait 1 > map > wait >   
my idea

**Comment by alisonrag** [comment]
we already have this in selectchar in servertype0

**Comment by sctnightcore** [comment]
:thinking:

**Comment by c4c1n6kr3m1** [comment]
and your last commit, sendBanCheck
it will make send many sendBanCheck too, i guess
need a delay too

**Comment by sctnightcore** [comment]
:thinking: sendbancheck after recv 099D . 

but recv many 099D

**Comment by HorrendousVon** [comment]
is the chaos server updated already?the rev packets, servers,sync,shuffle .. thanks guys

**Comment by nizdi** [comment]
@HorrendousVon not yet!

**Comment by moneyisgod** [comment]
Your capture was awesome.

But looks this : 


```
23.3  127.0.0.1:51052  127.0.0.1:6121  17  Send  


24.0000  65 00 80 84 1E 00 A2 B6 7F 44 69 B3 4B 31 00 00    e........Di.K1..


25.0010  01                                                 .


26. 


27.4  127.0.0.1:6121  127.0.0.1:51052  4  Recv  


28.0000  80 84 1E 00        

```

**Comment by moneyisgod** [comment]
```

23.3  127.0.0.1:51052  127.0.0.1:6121  17  Send  


24.0000  65 00 80 84 1E 00 A2 B6 7F 44 69 B3 4B 31 00 00    e........Di.K1..


25.0010  01                                                 .


26. 


27.4  127.0.0.1:6121  127.0.0.1:51052  4  Recv  


28.0000  80 84 1E 00  

```

**Comment by moneyisgod** [comment]
Uh, strange.
In your rAthena log 👍 
44 09 is map_login packet. sent after 0071.
After map_login, sync is sent.

And we received 099D only once, but in kore you see it a lot.
Probably because it keep trying to parse it ^^.
It keeps trying to parse, and because he didn't parsed, he can't send.

I'll check the syntax.

**Comment by c4c1n6kr3m1** [comment]
how is the progress
take a look at this pull to make char_login_pause https://github.com/OpenKore/openkore/pull/976

**Comment by moneyisgod** [comment]
```
Scheme {
	sent sendMasterLogin 0064 {
		received 0AC4
	}

	sent game_login 0065 {
		received 80 84 1E 00 ? 
			merged {
				received characters_info 082D
				received received_characters 006B
				received sync_received_characters 09A0
			}
	}

	Sent 09A1 (sync_received_characters) after 3 times {
		receive received_characters 099D 
	}
	
	Sent 0187 {
		send ban check containing ID		
	}

	Sent 08BA {
		send new pin password
	}

	Received {
		08B9 => login_pin_code_request2 {
			send char_login 0066 {
				received 0071 received_character_ID_and_Map
			}
		}
	}

	Send {
		map_login 0x944
	}

	Received {
		account_id 0x283
	}

	Received Chat {

	}
	
	Received Sync {

	}
}
	
```

Your log {

```
master_login 0064
game_login 0065
received_characters_info 082D
received_characters 006b
->Sent sendCharLogin ? Too early
sync_received_characters 09A0
->Sent 0x9A1 three times ONLY in LOG2
character_block_info 020D
Received login_pin_code_request 08B9
->Sent Login pinCode 08B8 ?
Received received_character_ID_and_Map 0071
Received 099D ?
```
It's clearly is Reading sometimes the buffer as 151 bytes and later as 161 bytes.

**Comment by sctnightcore** [comment]
fix with pauseCharLogin
