### ISSUE TITLE
Someone crack Password RO.EXE JELLOPY 2018

### ISSUE THREAD

**Issue by RobotTZ** [OpenKore/openkore#1868]
del by sctnightcore
Crack Password

**Comment by sctnightcore** [comment]
คืออิหยังหว๊า

**Comment by RobotTZ** [comment]
https://www.facebook.com/botrosupport/posts/716155492107886

**Comment by sctnightcore** [comment]
มันโกงโว้ยยย ไอ้ชิบหาย
