### ISSUE TITLE
Can't connect to iro chaos sad

### ISSUE THREAD

**Issue by ariechecoii** [OpenKore/openkore#1873]
LORD AINZ SAMA (Lord Knight, Boy, level 72/31, aldebaran)
------------------------------------------
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 65 0C 45 02 (38079589)
MAP Name: aldebaran.gat
MAP IP: 128.241.92.130
MAP Port: 4505
-----------------------------
Closing connection to Character Server
Disconnecting (128.241.92.130:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.130:4505)... connected
Timeout on Map Server, connecting to Account Server...
Connecting to Account Server...

**Comment by sctnightcore** [comment]
go IRc and wait

**Comment by ariechecoii** [comment]
what IRc?
