### ISSUE TITLE
I can't connect iRO

### ISSUE THREAD

**Issue by baskedue** [OpenKore/openkore#1875]
I uppdated my files fron github but I can't connect my bot at iRO. The error is:

"Tempo esgotado no Servidor de Mapas, conectando-se ao Servidor de Contas..."

**Comment by drewm1983** [comment]
me too iro chaos :(

**Comment by Fadreus** [comment]
Check PR before start new issue.
Wait PR Merge ffs.

**Comment by baskedue** [comment]
iRO Chaos too... what is PR?

**Comment by sctnightcore** [comment]
update you bot

**Comment by AugustaY** [comment]
iRo don't work again ? ( If need  update my bot, how I can do that?

**Comment by Nipodemos** [comment]
yes, again.
Every single week, on every single maintence of iRO, allanon goes and discover how to fix files to make openkore work again on iRO (every maintence openkore stop work)
so be patient, wait few more hours
