### ISSUE TITLE
time out on map server

### ISSUE THREAD

**Issue by jokenchatz** [OpenKore/openkore#1876]
Hi, Im just new here.. can anyone knows how to fix this? please..

[Mar 23 04:51:58 2018.31] Closing connection to Character Server
[Mar 23 04:51:58 2018.32] Disconnecting (128.241.92.130:4500)...[Mar 23 04:51:58 2018.33] disconnected
[Mar 23 04:51:58 2018.35] Connecting to Map Server...
[Mar 23 04:51:58 2018.36] Connecting (128.241.92.130:4506)... [Mar 23 04:51:58 2018.63] connected
[Mar 23 04:52:03 2018.65] Timeout on Map Server, connecting to Account Server...
[Mar 23 04:52:28 2018.65] Connecting to Account Server...
[Mar 23 04:52:28 2018.70] [reconnect] Login retry number 12, setting reconnect timeout to 30 seconds.

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/37818342-6906e108-2eac-11e8-8860-043a4b2e39aa.png)
