### ISSUE TITLE
phRO Valhalla start of a new journey

### ISSUE THREAD

**Issue by exelion99** [OpenKore/openkore#1878]
is there a bot on this server?
thanks
here is the website

http://www.playvalhalla.ph/

thanks

**Comment by sctnightcore** [comment]
official server ?

**Comment by exelion99** [comment]
yes official server

**Comment by sctnightcore** [comment]
Pserver . I think .

**Comment by exelion99** [comment]
well here in the philippines it says official but if its a priv server is there any bot that can use there?

**Comment by sctnightcore** [comment]
anticheat ?

**Comment by exelion99** [comment]
i think its GEPARD SHIELD its the one that is loading

**Comment by sctnightcore** [comment]
openkore dont support gepard . :p

**Comment by exelion99** [comment]
uhh too bad
