### ISSUE TITLE
Failed to retrieve recvpackets.txt for 2015-11-04aRagexe

### ISSUE THREAD

**Issue by PedroLuz89** [OpenKore/openkore#1879]
Hello guys,

Been trying to connect to my own private server, here's the server table:

[nbsRO2]
ip nbsro.eastus.cloudapp.azure.com
port 6900
private 1
master_version 1
version 55
serverType kRO_RagexeRE_2012_04_10a
serverEncoding Western
addTableFolders translated/kRO_english;kRO

I'm pretty sure it's the right version since I've built rAthena myself for using RagexeRE_2012_04_10a

Packet obfuscation and also packet encryption keys are DISABLED

I get an error on PEEK when trying to login into the map server

Find attached the hexed client
[nbsRO.zip](https://github.com/OpenKore/openkore/files/1852629/nbsRO.zip)

PS. Server is online atm, so I don't mind if you use that for testing it :)

**Comment by sctnightcore** [comment]
tables / kRO / RagexeRE_2015_11_04

**Comment by PedroLuz89** [comment]
This one won't work, no reason as for why

**Comment by sctnightcore** [comment]
@PedroLuz89  you client is 2012 ! 

check packet.h

**Comment by PedroLuz89** [comment]
I'm currently using this:

[nbsRO]
ip 185.144.156.131
port 6900
private 1
master_version 1
version 55
serverType kRO_RagexeRE_2012_04_10a
serverEncoding Western
addTableFolders translated/kRO_english;kRO;nbsRO
recvpackets recvpackets_nbsRO.txt

It's a custom recvpackets and public chat won't work :(

2018-03-31 14:38 GMT+01:00 Maytichai Saowa <notifications@github.com>:

**Comment by sctnightcore** [comment]
https://github.com/rathena/rathena/blob/master/src/config/packets.h#L15

check it

**Comment by moneyisgod** [comment]
http://openkore.com/index.php/Frequently_Asked_Questions

**Comment by alisonrag** [comment]
Check other servertypes, openkore can also support 2017 clienta
