### ISSUE TITLE
"any work in progress " solution WITHOUT using /console/ condition

### ISSUE THREAD

**Issue by PrincessLei** [OpenKore/openkore#1881]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: Bot gets stuck on a loop with "any work in progress" error for HOURS... I saw a macro solution with console condition but I want to know if I can use something else because I already use another automacro /console/ condition for something else..

_error code: "any work in progress (NPC dialog, manufacturing...)quit and try again"_ when warping

**Comment by sctnightcore** [comment]
server ?

**Comment by PrincessLei** [comment]
Sorry forgot to mention... iRO

**Comment by lututui** [comment]
You can in fact use multiple macros/eventMacros. Just put them in the same file

**Comment by PrincessLei** [comment]
@lututui I can? I was under the impression that once I use a specific condition e.g. /console/ I can only use it once and that only time or it won’t work properly... since event-based condition triggers for automacro works that way.
I’ll try and see.. thank you!

**Comment by Fadreus** [comment]
Event-based condition can only be used **once** per **automacro** & not once per macro file.
1 automacro start with open brace `{` and end with closure `}`

At first the wiki might seems confusing for those who not familiar with the terms but if you check some other macro example _(at the forum perhaps)_ it might enlighten you.

**Comment by PrincessLei** [comment]
ahh thank you! I've been limiting myself all this time... lol.
