### ISSUE TITLE
Timeout on map server. IRO Chaos!

### ISSUE THREAD

**Issue by Kostalios** [OpenKore/openkore#1882]
Every 5-7 minutes, freez the Ro client and bot (timeout on map server). Using the latest version openkore.
Please, help.
![trouble](https://user-images.githubusercontent.com/11650096/38009469-26bffb5e-325d-11e8-8a2a-2441eccf9c57.jpg)

**Comment by sctnightcore** [comment]
xkore ?

**Comment by Kostelio** [comment]
xkore 1

**Comment by Kostiks** [comment]
Xkore 1

**Comment by sctnightcore** [comment]
try with xkore0

**Comment by Kostiks** [comment]
Ok

**Comment by Kostiks** [comment]
I dont see this error, but can be done this on xkore 1?

**Comment by alisonrag** [comment]
you can re write xkore1, iupdated this file sometime, but just to work with 2017 clients

**Comment by Kostalios** [comment]
What i can do?

**Comment by alisonrag** [comment]
yo can use my pull as base to try fix
#1374

**Comment by Kostalios** [comment]
Played 30 min with ur fix, thought all right, but still the error(

**Comment by alisonrag** [comment]
update your openkore

**Comment by Kostalios** [comment]
Update today openkore, and again have tame out, wtf?

**Comment by Kostalios** [comment]
16 days work good with 1 xkore, after update openkore have time out..

**Comment by Fadreus** [comment]
Hmm, Tried too with latest version. DC after few minutes (iRO - Chaos)
The old version working fine (Nov 2017) even today.

But I didn't update anything except those weekly 4 files; ever since Nov 2017.
4 days ago running more than an hour also no problem.

**Comment by Kostalios** [comment]
How downgrade openkore?

**Comment by Fadreus** [comment]
Wait feedback from them first.
Unless you know what you are doing, search through commit history.

![image](https://user-images.githubusercontent.com/32188494/38769497-ada170e4-4036-11e8-8224-81a01b91cf4d.png)

**Comment by Kostalios** [comment]
Thank u, but another version not working for me(
