### ISSUE TITLE
account blocked

### ISSUE THREAD

**Issue by jokenchatz** [OpenKore/openkore#1883]
Hi, Is there anyway I can recover my account? both playing or botting gives the same message to me.. please help.. thanks in advance..

[Mar 28 22:49:48 2018.98] 
[Mar 28 22:49:48 2018.99] Connecting to Account Server...
[Mar 28 22:49:49 2018.12] Connecting (128.241.92.162:6800)... [Mar 28 22:49:49 2018.41] connected
[Mar 28 22:49:49 2018.76] Disconnecting (128.241.92.162:6800)...[Mar 28 22:49:49 2018.77] disconnected
[Mar 28 22:49:49 2018.77] The server is temporarily blocking your connection until 2067-12-31 00:00

**Comment by alisonrag** [comment]
that i know thats not possible, ban because of bot is permmanent

**Comment by jokenchatz** [comment]
thank you.

**Comment by Jazzmeen** [comment]
Is that for RO ph? jokenchatz
