### ISSUE TITLE
Disconnect on map (IRO:REstart), even after most recent update

### ISSUE THREAD

**Issue by btleo** [OpenKore/openkore#1888]
Still cannot log in map server, after latest pull request commitment. Is the update not working or the update didn't imply on the zip files? When download the zip files, the problem is unsolved.

**Comment by Pachu1985** [comment]
the required files werent updated. if you check carefully some quests files were updated. still gotta wait.

**Comment by sctnightcore** [comment]
```
Things to know
Before submitting an issue, ensure you are running the latest commit on branch.
Check if an issue already exists for your request.
Please post in English if possible.
Please use the issue template, please post information about the server and your configuration.
Remember, developers are doing this on free time.
```
