### ISSUE TITLE
problem with storage somehow it does not store anything

### ISSUE THREAD

**Issue by solbiee** [OpenKore/openkore#189]
storageAuto 1
storageAuto_npc geffen 120 62
storageAuto_distance 5
storageAuto_npc_type 1
storageAuto_npc_steps c w5 c r0 w5
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 5
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 50

**Comment by itsrachelfish** [comment]
What server do you play on?

**Comment by solbiee** [comment]
chaos, nvm fixed it thanks
