### ISSUE TITLE
Slow potion use?

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#1895]
I want to run the bot in xkore mode and use it as sort of an auto potter/auto pet feeder but it uses potions very slowly, i checked timeouts but didn't really want to mess the bot up.  Is there an option to change this and make it do it quickly?  I also obviously have timout set to 0 in the potion use block.

**Comment by Fadreus** [comment]
http://forums.openkore.com/

**Comment by alisonrag** [comment]
Using the following configuration openkore was using more faster then players haha:
config.txt:
```
sleepTime 1000

useSelf_item Yellow Potion {
	hp < 95%
	sp
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	manualAI 0
}
```

timeouts.txt:
```
ai_item_use_auto 0.1
```

video:
https://youtu.be/APFxpYbRhsg
