### ISSUE TITLE
Bot does not TP using skill

### ISSUE THREAD

**Issue by allnamesareunavailable** [OpenKore/openkore#1897]
Hi,

My bot has TP skill but doesnt use it to avoid any monster, instead keeps giving the following error

Skill Teleport failed: Mid-Delay (error number 4)
Skill Heal failed: Mid-Delay (error number 4)
Skill Teleport failed: Mid-Delay (error number 4)

Please help.

**Comment by Fadreus** [comment]
http://forums.openkore.com/

Github for report, not help.
That's not bug, that's setting faulty.

Same thread exist in google dated back 2010+.
You say you are noob/newbie, I say you are lazy.
