### ISSUE TITLE
Improve item and pickupitem 

### ISSUE THREAD

**Issue by Jozoko** [OpenKore/openkore#190]
I would like to propose an addition to the config files - items_control.txt and  pickupitems.txt

It is this - to add the possibility of using regexp in this files and maybe add group of items like Cards,Armors and etc
Pickupitems.txt
/.\* Card/ 2 0 0 - all card will be pickuped as fast as kore can
Items_control.txt
Cards 0 1 0
Loot -1 0 0

**Comment by itsrachelfish** [comment]
Cool idea, could be very useful!

**Comment by t3quila** [comment]
You can change (items.txt) all Cards name with #Card#
for example
`4001#Card#
4002#Card#
4003#Card#
4004#Card#
4005#Card#
4006#Card#
4007#Card#`

so simple right? =P

**Comment by Jozoko** [comment]
It's simple, but very stupid, u need to reread my feature

**Comment by c4c1n6kr3m1** [comment]
use different format, or you will be in trouble like i was 

all_Card  0 0 0

**Comment by itsrachelfish** [comment]
@t3quila And then you can't tell what card it is. :stuck_out_tongue:

**Comment by AlexandreBR3N** [comment]
Really, it is an amazing feature, instead of re-edit your items_control with Cards.
But this of 'loot' for me it's not good 'cause I only earn money with Loot. Hahaha. 
But some feature such as 'gef_fild10 0 0 0' , take all loots of that lockMap, and if i don't want for example, an axe battle, i just set the line : 'Axe Battle'. I think that we just need of one more txt files. 

Or i'm talking shit ?!

**Comment by alisonrag** [comment]
grf file have one file to define card images, maybe we start with this file. 
I'm worried just about the performance.

**Comment by Arkelsa** [comment]
I found this and it seems to have worked so far ??

http://forums.openkore.com/viewtopic.php?f=27&t=144711&p=200125&hilit=wildcard#p200125

**Comment by ChrstphrR** [comment]
Looking on the thread Arkelsa linked up, this was a solved issue 3 years prior to this issue/feature request's creation.

Arkelsa popped into the IRC channel asking questions about pickupitems.txt under a different nickname, and had used and tested the code from the 2013 era thread, and said that regex support for the item name field seems to work.

**Comment by alisonrag** [comment]
continue in #2110
