### ISSUE TITLE
Party Skills Not Working - iRO Restart

### ISSUE THREAD

**Issue by allnamesareunavailable** [OpenKore/openkore#1913]
Kindly refer to my previous issue #1896 

It has improved, but not completely resolved hence i request you to reopen the issue.

Now, the priest does use support skills in party, but there is an immense random delay in doing so.

For sometime it works perfectly, but then again it goes back to its old self where it just refuses to use the party support skills.

Request the team to please look into it.

Thanks

**Comment by Fadreus** [comment]
> For sometime it works perfectly, but then again it goes back to its old self where it just refuses to use the party support skills.

DId you try move around?
Does it back to buff and heal?

**Comment by alisonrag** [comment]
i cant reproduce your error.

have you downloaded the latest openkore version and make a new configuration?

in bRO no one seems to have the same problem

**Comment by plsdontkilme** [comment]
1st: bot is in the same party...
2nd: used this config...
partySkill Increase AGI {
	lvl 10
	target NAME
        whenStatusInactive Increase AGI
	target_timeout 100
	target_hp < 80%
	sp > 10%
        timeout 5
}

**Comment by allnamesareunavailable** [comment]
sorry for the late reply.

I download the latest version after every maintenance the server has. So, yes i have done that.

The config is nothing different than what plsdontkilme has posted above. I think he is also facing the same problem.

iRO Restart is the server we are referring to here.

Ill share my config file.

[config.txt](https://github.com/OpenKore/openkore/files/1902358/config.txt)

**Comment by Fadreus** [comment]
Try this.
[config.txt](https://github.com/OpenKore/openkore/files/1902530/config.txt)

**Comment by Fadreus** [comment]
[Try this.](https://github.com/OpenKore/openkore/files/1902555/config.txt)

**Comment by allnamesareunavailable** [comment]
Ok will try it. Waiting for the recvpackets to be updated for iRO Restart.

**Comment by sctnightcore** [comment]
@allnamesareunavailable  Update new bot : p

**Comment by allnamesareunavailable** [comment]
@Fadreus thanks a ton for taking the initiative and fixing the config for me. 👍 

It works perfect now. You may close this issue.

You guys rock!

@sctnightcore thank you for that. 👍
