### ISSUE TITLE
automacro pm trigger suddenly stopped working 

### ISSUE THREAD

**Issue by PrincessLei** [OpenKore/openkore#1918]
###### Summary: 
My automacro for pm was working perfectly today until I came home and saw that wxstart for my priest bot has stopped working (frozen). No problem, I force closed the program and restarted. And then I found out that few of my macros stopped working... specifically anything that had "pm" as the trigger. /console/ and pubm etc. are still working fine but pm triggers no longer works. I tested it on my other bots using the code below for testing purposes:

###test
automacro tesa {
	pm /diamond/
	call {
	pause 2
	log pm trigger is working!
	do e ok
}
}

The test code above  _works for my other_ bots but **not** for my priest bot. I tried reinstalling and left my control folder untouched but its still not working properly.

###### Affected configuration(s)/ file(s):
 When I list my macros on the console for my priest bot, it still shows up. It just doesn't trigger or run...
There are also no error codes... it's as if the automacro doesn't exist.

--------automacros-------
privatemesg
followtele
passwordwarp1
respondGreet
**tesa**
SupportOthers
---------Perl Sub--------

###### Impact:
I had to change or delete all my automacros with pm / as trigger for my priest bot.

###### Expected Behavior:
pm trigger to start working again...

Any ideas on how to fix this? I found a work around for the moment but I have no idea what went wrong aside from the priest bot freezing and having to do a force restart..

**Comment by Fadreus** [comment]
Try use eventMacro.pl instead of macro.pl.
I had this behavior like 4~6 years ago when using PM stuff.
You either need more condition (like run-once then release) or simply reload macro, ai clear.
Macro no longer being updated.🤕

Dun remember back then, but sometimes when u PM too much or triggering auto macro to much, yer bot just said "YER NOT MA MOM" and sulking.😕
Too much automacro and stuff make yer priest crazy too yo (Sometimes)~
Ain't gonna make mess with yer slave.
Have mercy on it.🤣

Btw, I tested with latest version with these on AB (Sry, dun have Priest)
```
automacro NiggaTestWorking {
	pm /nigga/
	call {
		pause 2
		log This nigga work fine, ma nigga.
		do e ok
	}
}

```

![image](https://user-images.githubusercontent.com/32188494/38467437-2fe89d6e-3b6b-11e8-879a-f66d9a87d02e.png)

If yer concern in some automacro condition ain't available at eventMacro, simply use macro to call eventMacro. Kek.

**Comment by PrincessLei** [comment]
I tried eventmacro but I ended up with a fatal error :sob:
![bug](https://user-images.githubusercontent.com/36978390/38479615-bfcce488-3c03-11e8-83a9-54775f1ebe1d.JPG)

**Comment by PrincessLei** [comment]
I tried eventmacro but ended up with a fatal error :sob:
Im not too adept with using eventmacro but I assume it's about the same as using a macro.pl? I could be wrong...

![bug](https://user-images.githubusercontent.com/36978390/38479697-32d07512-3c04-11e8-955d-7a055cba9f3c.JPG)

Idk what to do with my priest at this point but avoid `pm/` for now

**Comment by Fadreus** [comment]
@PrincessLei eventMacro.pl & macro.pl is not the same. The condition syntax are totally different (but similar) Read here http://openkore.com/index.php/EventMacro



<details>
<summary>I'm guessing it's the server as mention by @c4c1n6kr3m1 If the issue still persist using eventMacro,</summary>

I only noticed this recently. Trying to pm too fast **_(or sending same messages)_**, the frist 3 will appear while the rest is gone **_(just like in game, 3 messages can be send when try to send another message a warning appear 'cant send too fast' or getting muted)_**. But after few seconds later, when try to send another PM, the message appear chronologically.

I guess this is related to this matter? _(Theoretically speaking)_
</details>

**Comment by PrincessLei** [comment]
> eventMacro? i never use it, but i think wiki said PrivMsg , not pm

@c4c1n6kr3m1 @Fadreus EVENTMACRO worked!!! ^^He's right on the mark on that one, i put pm/ lmao!!! More to study :cry: .. 
THANK YOUUUU! I could kiss you both :kissing_heart: :kiss: 

![working again](https://user-images.githubusercontent.com/36978390/38486719-2f747f72-3c21-11e8-970f-b1c122e870d5.JPG)
