### ISSUE TITLE
AutoSpell isn't working

### ISSUE THREAD

**Issue by PedroPrellwitz** [OpenKore/openkore#192]
I followed the directions on how to set the auto spell so that I could set my crusader to cast Spear Quicken but it is not working. Here is my setup:

useSelf_skill Spear Quicken {
	lvl 10
	maxCastTime 0
	minCastTime 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	monsters
	notMonsters
	monstersCount
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 1
	notInTown 0
	timeout 10
	disabled 0
	inInventory
	manualAI 0
	
}

**Comment by Jozoko** [comment]
useSelf_skill Spear Quicken {
   lvl 10
   whenStatusInactive Spear Quicken
   sp > 10%
   notWhileSitting 1
   timeout 10
}

**Comment by PedroPrellwitz** [comment]
Thank you very much sir!!
