### ISSUE TITLE
Visual Bot constantly Getting disconnected

### ISSUE THREAD

**Issue by Sixte44** [OpenKore/openkore#1923]
Hello, i have some trouble with my visual bot ( xkore 1 , 2 & xkore 3 ) ; Everytime that i use a spell ( like call spirit for exemple , my game freeze ( it freeze only when i use the spell, not when someone else does ), but not my openkore, wich is realy strange here is a screen : 
https://image.noelshack.com/fichiers/2018/15/1/1523230435-erroropenkore.png

- xkore 3 and xkore 1 : so basicaly, on the screen, just after i tried to use body relocation, i use the spell 'call spirit' and Boom, game freeze, kore searching for the client to connect... 

- xkore 2 : i can't select my character , because i see him ready to get deleted, and ofc , i cant cancel it ^^.

https://image.noelshack.com/fichiers/2018/15/1/1523268816-xkore2.png

EDIT : Alright , i have been testing all this morning on different servers, and i have experienced the same Issue, SO ! :+1: 

- 1 : it comes from MY openkore files
- 2 : its Global, and we all have this issue

If someone could try and play visual kore mode 1 , 2 or 3 , and cast a 'call spirit' , it'll help me to know if its global, or if its just me. 

tested on 

- 1 : Client RagexeRE_2015_11_04a
- 2 : Client : RagexeRE_2010_08_03a

server ( Private ) :  https://www.ro-play.fr/

I have the latest version of openkore.

EDIT : i have tested on differents jobs , and here's some others errors with : 

 - Professor(_M / _F) : Double-Casting / Dispell / ( Box of gloom only for Professor_F )
 - Monk(_M) / champion(_M) : Critical explosion / call spirit / blade stop
 - High-priest(_F) : Assumptio

didnt try all the spells and effect of the game on every and each jobs, but i can do it if its neccesary lol

Thanks !

**Comment by Sixte44** [comment]
Hello, thanks for reply, here the console ;

 - Error using Box of gloom : https://image.noelshack.com/fichiers/2018/15/1/1523280808-bog-bug.png ( with a professor_F)

- Error using call spirit : https://image.noelshack.com/fichiers/2018/15/1/1523280816-callspiritbug.png
( with a champ_M)

- Error using Critical Explosion : https://image.noelshack.com/fichiers/2018/15/1/1523280824-critical-bug.png

**Comment by alisonrag** [comment]
have you downloaded the latest version?

**Comment by Sixte44** [comment]
yes i have downloaded the latest version , and i did it again like 5 hours ago

**Comment by c4c1n6kr3m1** [comment]
i only use xkore2 now
but that "Outgoing unknown packet" is suspicious, 

is the server using sendCryptKeys ?

actually these will be better
debug 2
debugPacket_unparsed 2
debugPacket_received 2
debugPacket_ro_sent 2
debugPacket_sent 2

but it will show your hex ID !!!!! so it's dangerous
do u know how to identify your ID ? you need to change it to something like "xx xx xx xx" or "AA BB CC DD" so no one can identify your ID

**Comment by c4c1n6kr3m1** [comment]
are you sure your recvpacket is correct?

packet 0089 [attack/sit/stand] as far as i know , normally, 7 bytes . your ss show 11 bytes

**Comment by Sixte44** [comment]
hello @c4c1n6kr3m1 , and thanks for your reply

Well for the recvpackets, i dont know, i used peek V3 ( for the Ragexe 2015 ) and JVCro tools i think for the packets Ragexe 2010, i dont have any other packet extractor. so i cant tell if my packets are good or not, i would say yes, but i'm not an expert

nah its fine if you see my Hex ID, i just want to solve this problem on P-server ^^

here is a screen that i toke from xkore 2 on the 2015 ragexe server ( Ro-play )  : 

https://image.noelshack.com/fichiers/2018/15/1/1523305022-gitopenkorehelp.png

and i cant use xkore 2 since, i see my character siting , ready to delete lol ^^' like this : 

https://image.noelshack.com/fichiers/2018/15/1/1523268816-xkore2.png

**Comment by c4c1n6kr3m1** [comment]
hi, try download this
https://raw.githubusercontent.com/c4c1n6kr3m1/openkore/slicePacket/src/Network/MessageTokenizer.pm

and replace your src/Network/MessageTokenizer.pm with that

**Comment by Sixte44** [comment]
Nice its working ! Thanks @c4c1n6kr3m1 

Do you have any idea for the Xkore 2 ? i still have this issue tho  : 

 - https://image.noelshack.com/fichiers/2018/15/1/1523268816-xkore2.png

But you solved the problem "freeze screen with skills" good job :+1:

**Comment by c4c1n6kr3m1** [comment]
nope
need to compare alot of packets for that since private server has their own packet

**Comment by Sixte44** [comment]
alright, thanks anyway :+1:

**Comment by c4c1n6kr3m1** [comment]
my last commit is not perfect @sctnightcore

**Comment by Sixte44** [comment]
well i putted 'Solved' because its working, not for Xkore 2 tho, but its still good to me :+1:
