### ISSUE TITLE
Timeout on map server,connecting to account server

### ISSUE THREAD

**Issue by MaGi66** [OpenKore/openkore#1924]
Hi,
I am new to open kore, whenever I try to run the openkore I get an error as Timeout on map server, connecting to account server. 

Pls help 
Thank You 
![untitled](https://user-images.githubusercontent.com/38223982/38513221-26c68706-3c4b-11e8-92bf-934e972c390f.png)

**Comment by sctnightcore** [comment]
server ?

**Comment by MaGi66** [comment]
iRo restart

**Comment by sctnightcore** [comment]
@MaGi66  download new openkore and test it again

**Comment by MaGi66** [comment]
I downloaded the latest one form the below link
https://github.com/OpenKore/openkore

**Comment by alisonrag** [comment]
![image](https://user-images.githubusercontent.com/10372732/38513422-99391cb4-3c04-11e8-8a29-b2ebe27fba28.png)
tested just now

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/archive/master.zip

**Comment by MaGi66** [comment]
after downloading from the above link i am getting this error
![untitled](https://user-images.githubusercontent.com/38223982/38513689-9b2b1f98-3c4c-11e8-8750-def776842cfa.png)

**Comment by alisonrag** [comment]
this account is banned or server still recognize your last connection

**Comment by alisonrag** [comment]
try relog

**Comment by MaGi66** [comment]
The account is not banned as i can log in using the client.. and i also tried relog but it shows the same error

**Comment by sctnightcore** [comment]
try to use xkore 1

**Comment by Minabe** [comment]
Instead of making a new thread just gonna use this one. New update broke map server connection again, if someone knows why and how to fix it i'd be glad. I'm asking for that bc while i'd like the fix, i'd prefer to fix it myself although i currently have no way to know exactly what is the problem (other than asking here).

**Comment by Fadreus** [comment]
@Minabe Never ever open new thread for iRO _(xKore 0)_  connectivity issue after maintenance. It's a Sin. You can kill 1000 people, but never open new thread. If you asking why, you can see what files is updated every week; the encrypt key & packets.
