### ISSUE TITLE
BUG on Customs Maps ( Private servers )

### ISSUE THREAD

**Issue by Sixte44** [OpenKore/openkore#1931]
Hello, i have experienced a Bug with the customs maps on private servers : 

When i enter to a custom map i have this Error message from openkore 

 - https://image.noelshack.com/fichiers/2018/15/3/1523439053-xpmincorrect.png

And on all customs maps of this server, here's what happens : i cant see any of the NPC, Monsters or players in it , like the screen below : 

 - https://image.noelshack.com/fichiers/2018/15/3/1523439112-bugcustommap2.png

my kore doesnt recognize them on Customs Map , but i have 0 problem on regulars maps.

EDIT : the bug only appears on 1 P-server, not on the other i tested, so idk what to think about that

Any idea ? ^^ 
Thanks !

**Comment by alisonrag** [comment]
your custom map is not implemented in openkore, so every actor is out of screen, so openkore delete, but re add to list and enter in a looping, add and remove actor

**Comment by Sixte44** [comment]
Hi,
alright, is there a way to fix it by myself ? @alisonrag

**Comment by Sixte44** [comment]
it doesnt work, it may be coming from for the server so i guess i wont try to figure out whats going on ^^
thanks anyway !
