### ISSUE TITLE
Cant Talk to NPC

### ISSUE THREAD

**Issue by Sixte44** [OpenKore/openkore#1938]
Hello, i cant talk to NPC , idk why, i see them etc but look at the screen : 

 -  - https://image.noelshack.com/fichiers/2018/15/5/1523608696-npcerror.png

When i enter the command talknpc , the console says "talking to npc", but nothing happen on the game screen...
When i try to direcly click on the NPC trough the console NPC names, it says error in functon talk to npc
"you are already talking with an NPC"

Any ideas ? Thank you

**Comment by sctnightcore** [comment]
xkore 0 ?

**Comment by Fadreus** [comment]
@Sixte44 When reporting, please be specific. Give extra details. No one know what you do, what xKore version u use, what server you are playing, what mod you've done. Bla bla bla..

The bug report template is a good start. (If only you use it instead of deleting it without even reading).

**Comment by c4c1n6kr3m1** [comment]
do you see any npc with coordinate 76 85
/swt

**Comment by Sixte44** [comment]
yeah i fucked up the screen lol, but it did the same while i typed to correct location.

But i think i figured out the 'bug' : i was switching from console to game screen to open and close NPC, kore didnt know i closed the NPC dial, so he thought i was still in NPC conversation.

Anyway sorry for trouble !
