### ISSUE TITLE
Can't reach or damage target problem

### ISSUE THREAD

**Issue by TajemnyPanHulak** [OpenKore/openkore#1939]
###### Affected configuration(s)/ file(s):
default configuration from newest GIT

###### Impact:
character is not able to attack any mob with any weapon (melee or range)

###### Expected Behavior:
character is able to attack mob

###### Actual Behavior:
"Can't reach or damage target, dropping target" for all mobs. I tried to play with options like Attack Distance, Attack max distance etc. but no luck. I tried same configuration on other official server (International - iRO) and its working there perfectly => only fRO is affected. 

Character is able to move, etc. so it is just following mob, trying to attack it, but thats all.

###### Steps to Reproduce:
Download newest OpenKore -> connect to server -> try to attack something

del config by sctnightcore 
it have id pw (it was just test account with random credentials)

**Comment by sctnightcore** [comment]
Nani ? :thinking:

**Comment by TajemnyPanHulak** [comment]
Here is log from console:

You are now attacking Monster Pupa (0)
[dist=2] Monster Pupa (0): *Sweat*
Can't reach or damage target, dropping target
You are now attacking Monster Willow (0)
Can't reach or damage target, dropping target
You are now attacking Monster Willow (1)
Can't reach or damage target, dropping target
You are now attacking Monster Willow (2)
Can't reach or damage target, dropping target

**Comment by sctnightcore** [comment]
http://forums.openkore.com/viewtopic.php?f=55&t=12089
try it .

**Comment by sctnightcore** [comment]
@TajemnyPanHulak  Tonight, I can check it .

**Comment by sctnightcore** [comment]
@TajemnyPanHulak  something like it.

**Comment by c4c1n6kr3m1** [comment]
executable file is Ragnarok.exe ? 
/heh
