### ISSUE TITLE
AI stuck

### ISSUE THREAD

**Issue by kittygrill** [OpenKore/openkore#194]
For whatever reason my kore sometimes becomes idle and there's no way to tell why or how it gets stuck so I went to enable debug and it just prints this out repeatedly until a monster starts attacking it until it goes to a certain HP to teleport then it goes back to normal,

<img width="273" alt="openkore" src="https://cloud.githubusercontent.com/assets/11700758/17789083/307d5a18-6556-11e6-9edb-63c0a77c56ae.png">

**Comment by Jozoko** [comment]
Post u skill use block

**Comment by kittygrill** [comment]
My skill use block is fine 
{
lvl 1 
whenStatusInactive Preserve
timeout 10
}

I also have the same bug on my other character 
<img width="634" alt="aaaaaaaaaaaaaa" src="https://cloud.githubusercontent.com/assets/11700758/18014433/814f3e1a-6b88-11e6-8730-61555f0dfb8e.png">

**Comment by Jozoko** [comment]
Preserve? Look at ur console log. Bot trying to cast Quicken on self.

**Comment by kittygrill** [comment]
Preserve for the first pic, second and third one has Twohand Quicken and Spear Quicken respectively

**Comment by Jozoko** [comment]
i think problem in Self status. Try to check it

**Comment by kittygrill** [comment]
It works everytime, but there's just an instance AI goes stuck then it never moves nor uses skills

**Comment by Cozzie** [comment]
Closing issue and making assumption that #213 is the cause for now.
