### ISSUE TITLE
Lucky escape?

### ISSUE THREAD

**Issue by PrincessLei** [OpenKore/openkore#1944]
Good Evening,
Just wanted to let you guys know that the forum is locked from registration because the captcha is not working... I was going to post my question there because this isn't bug related (i hope)
![captcha](https://user-images.githubusercontent.com/36978390/38807605-824a31c0-41c0-11e8-8230-8e302b388e34.JPG)

thank you...
------------
My question is I had an alertsound and action for the following

`console /perfectly hidden|uses Sandman on you|You are now: state: Sleep|Goodnight, Sweety|Goodnight|iRO GM|iRO_GM|iRO GM (.*)/
`
After a few hours, automacro above triggered for the first time in my lockmap today... thankfully it worked as I was not banned when I checked lol (my heart was pounding XD). But I can't figure out if its a troll or an actual GM that I avoided!! I'm not sure if I should bot in the same area or if it was a false alarm... I scouted the location with my main account but I didn't see anything... like I teleported around looking for what triggered the scary automacro but nothing.

I am sure that its not one of the _"uses sandman or state: sleep_ because it didn't show on the console... I figured maybe it was the perfectly hidden or the iRO tags... ???
**Chat log had NO information** also so I'm stumped...
This is what was on the console (I deleted monster name and etc. so not to reveal my location or my personalized call macro for botting lol)

> [Apr 16 15:39:53 2018.11] [100/ 98] You attack Monster ----- (1) (Dmg: 495) (Delay: 310ms)
> [Apr 16 15:39:53 2018.38] [macro] automacro SOUNDGMALERT triggered.
> [Apr 16 15:39:53 2018.74] [ 98/ 98] Monster -------- (3) attacks you (Dmg: 132) (Delay: 672ms)
> [Apr 16 15:39:54 2018.63] [macro log] GM SIGHTED! QUICK ESCAPE ACTIVATED!!
> [Apr 16 15:39:54 2018.53] [ 97/ 98] Monster ----- (1) attacks you (Dmg: Miss!) (Delay: 672ms)
> [Apr 16 15:39:55 2018.48] [ 97/ 98] Monster ----- (3) attacks you (Dmg: Miss!) (Delay: 672ms)
> **[BLOCKED------------------------N/A N/A PERSONAL CALL COMMANDS ETC SECRET ]**
> [Apr 16 15:42:58 2018.54] Disconnecting ---- disconnected

--My bot followed its escape GM macro successfully (phew)

Did I actually "escape" a GM ? Or maybe it was a troll? How do you troll anyway? I tried making a character name with iRO in it to try to test but its not letting me.
Thanks in advance..

**Comment by Fadreus** [comment]
@itsrachelfish

**Comment by itsrachelfish** [comment]
@PrincessLei Thank you for reporting this. I'll look into upgrading the forums

**Comment by Nipodemos** [comment]
a good way of know what caused the macro to activate is:
on your **config.txt**, search for **logConsole** key e put value 1 in front of it

this way all lines that apeear on openkore will be saved on a file called NAMEOFCHAR_console.txt
Insite logs folder

Then you can simply read what line caused the macro to trigger

**Comment by PrincessLei** [comment]
@Nipodemos thank you! I’m not home right now to test it but I know my logconsole is set to 1. Can you explain how to key e?
Like 
logconsole e 1 ? A bit confused

**Comment by itsrachelfish** [comment]
Hey there, I changed the forum to use a different captcha. You should be able to post on the forums now :+1:
