### ISSUE TITLE
Longer Time to Calculate Master Position.

### ISSUE THREAD

**Issue by Fadreus** [OpenKore/openkore#1953]
###### Summary: 
Slave following master took longer time to start following master once lost _(approximately more than 10 seconds to start following back to normal.)_ Early version of Openkore 2.1 doesn't have this behavior _(as long as I remember)_

###### Impact:
Slave always left behind; going back and forth trying to get to master.

###### Expected Behavior:
Immediately move to master's last position.
Start following master when found.

###### Actual Behavior:
Once master lost, it just standing for few seconds (usually 3) trying to calculate master coordinates.
When master is found, it still moving to the calculated coordinates rather than start following.

###### Steps to Reproduce:
-Master moving without any concern of slave.
-Set slave to follow moving master (Especially Arch Bishop, but normal priest also can )

###### Additional info:
My current solution is to clear AI when ever master is found. This immediately follow master once found instead of passing through master. I hand-play with Slave AB.

**Comment by Fadreus** [comment]
Or should I use #1684 ?

**Comment by Fadreus** [comment]
Or #1684 would fix this?

**Comment by Nipodemos** [comment]
#1684 will not fix this

**Comment by Fadreus** [comment]
###### Additional-related info:

When slave being attacked while moving _(position lag)_, openkore still think it near master _(if master didn't move from last position)_ compared to older version where openkore know when it's not near even with position lag _(server depended?)_.

Slave didn't check LOS whether it can cast skill or not _(partySkill)_; resulting standing there until master pick it up or out of sight _(then this problem occur when it will take another more time to get to master)_.

About 8/10 this will happen, almost always.
While I can ensure this often always at mobby area _(Test at Juperos / Magma Dungeon / Manuk Field)_.

Most of my solution is
- Clearing AI.
- Move random direction to update current position.

**Comment by Fadreus** [comment]
So, it's not a bug?
- Lost master
- Calculate
- Found master
- Ignore master while moving to coordinate
- Lost master again.
- Move to master.

Is it suppose to do this?
Hmm.. I guess I'll 'fix' this on my own again then.
Sorry for bringing this up. 😱
Thanks for your time.

**Comment by lututui** [comment]
Closed accidentally, sorry :3

**Comment by Fadreus** [comment]
I thought closed because irrelevant. >w<

And yes, it's an old bug.
I brought this up coz I've no better way getting around it now.

**Comment by Nipodemos** [comment]
> AI::clear(qw/move route/)

so, it's just someone put this line of code in the correct place to solve part of the problem?

**Comment by Fadreus** [comment]
Just want to mention something related stopping/slowing slave from following _(closing the distance to master)_

- when `stopWhenHit 1` is used, slave will standing still, tying to cast until not hit which eventually losing master.

My solution is to replace it with `aggressives < 1`. This way it wont cast when hit and using this also keep the master & slave close to each other.

`stopWhenHit` compared to `aggressives` do the same thing but `aggressives` have better performance when following master.

<details>
<summary>Here is my config if you guys need to test what exactly happen.</summary>

```

###Self Skill###

useSelf_skill 28 {
	hp < 80%
	sp > 40
}

useSelf_skill 34 {
	whenStatusActive Curse, Cursed
	sp > 60
	timeout 1
}

useSelf_skill 2041 {
	sp > 100
	whenStatusInactive Blessing
	notInTown 1
	notWhileSitting 1
	stopWhenHit 0
	aggressives < 1
}

useSelf_skill 2042 {
	sp > 100
	whenStatusInactive Increase AGI
	notWhileSitting 1
	stopWhenHit 0
	aggressives < 1
	disabled 0
}

useSelf_skill 74 {
	sp > 50
	whenStatusInactive Magnificat
	stopWhenHit 0
	aggressives < 1
}

useSelf_skill 75 {
	hp > 80%
	sp > 50%
	whenStatusInactive Gloria
	notWhileSitting 1
	notInTown 1
	disabled 0
}

useSelf_skill 361 {
	sp > 40
	whenStatusInactive Assumptio
	timeout 10
	notInTown 1
	stopWhenHit 0
	aggressives < 1
	notWhileSitting 1
	disabled 0
}

useSelf_skill 2045 {
	sp > 90
	whenStatusInactive Kyrie Eleison
	timeout 30
	notInTown 1
	stopWhenHit 0
	aggressives < 1
	notWhileSitting 1
	disabled 1
}

useSelf_skill 2515 {
	stopWhenHit 0
	aggressives < 1
	notWhileSitting 1
	notInTown 1
	sp > 100
	timeout 5
	disabled 1
	whenStatusInactive EFST_AB_SECRAMENT
}

useSelf_skill 33 {
	stopWhenHit 0
	aggressives < 1
	sp > 100
	timeout 10
	notInTown 1
	notWhileSitting 1
	whenStatusInactive Angelus
	disabled 1
}

useSelf_skill 25 {
	defendMonsters Blue Dimik, Green Dimik, Red Dimik, Orange Dimik, Dimik
	whenNotGround Pneuma
	sp >= 10
}

useSelf_skill 2050 {
	stopWhenHit 0
	aggressives < 1
	notWhileSitting 1
	notInTown 1
	timeout 10
	sp > 100
	whenStatusInactive EFST_RENOVATIO
	disabled 0
}

###Party Skill###

partySkill 54 {
	sp > 100
	target_dead 1
}

partySkill 28 {
	sp > 60
	target_hp < 80%
}

partySkill 34 {
	target_whenStatusActive Curse, Cursed
	sp > 60
	timeout 1
}

partySkill 34 {
	sp > 40
	target_whenStatusInactive Blessing
	target_timeout 180
	notInTown 1
	notWhileSitting 1
	disabled 1
}

partySkill 29 {
	sp > 40
	target_whenStatusInactive Increase AGI
	target_timeout 10
	notWhileSitting 1
	stopWhenHit 0
	aggressives < 1
	disabled 1
}

partySkill 29 {
	target_whenStatusActive Decrease AGI
	sp > 60
	timeout 1
}

partySkill 66 {
	sp > 40
	target_timeout 60
	target_whenStatusInactive Impositio Manus
	notWhileSitting 1
	notInTown 1
	disabled 0
}

partySkill 361 {
	sp > 40
	target_whenStatusInactive Assumptio
	target_timeout 100
	notInTown 1
	stopWhenHit 0
	aggressives < 1
	notWhileSitting 1
	disabled 0
}

partySkill 35 {
	sp > 50
	target_whenStatusActive Silance, Silanced, Silence
}

partySkill 2515 {
	stopWhenHit 0
	aggressives < 1
	notWhileSitting 1
	notInTown 1
	timeout 5
	sp > 100
	target_timeout 90
	target_whenStatusInactive EFST_AB_SECRAMENT
	disabled 1
}

partySkill 2050 {
	stopWhenHit 0
	aggressives < 1
	notWhileSitting 1
	notInTown 1
	timeout 10
	sp > 100
	target_timeout 90
	target_whenStatusInactive EFST_RENOVATIO
	disabled 0
}

partySkill 2537 {
	sp > 100
	target_whenStatusInactive EFST_ODINS_POWER
	target_timeout 60
	notInTown 1
	notWhileSitting 1
	disabled 0
}

partySkill 35 {
	target_whenStatusActive Blind
	sp >= 15
}

partySkill 72 {
	target_whenStatusActive Stun, Stunned
	sp >= 5
}

partySkill 25 {
	target_defendMonsters Blue Dimik, Green Dimik, Red Dimik, Orange Dimik, Dimik
	target_whenNotGround Pneuma
	sp >= 10
}

```

</details>

**Comment by moneyisgod** [comment]
https://github.com/OpenKore/openkore/blob/04f115473fd91ecd19b34aa60d6a72f16ce7044c/plugins/needs-review/busFollow/trunk/doc/README.txt

**Comment by Fadreus** [comment]
Still, have no idea where to put this `AI::clear(qw/move route/)`

**Comment by Nipodemos** [comment]
@Fadreus in the piece of code that writes the message
"Found my master!"
at least i think so

**Comment by Fadreus** [comment]
@Nipodemos I thought it was something like this;
```
# if we are not following now but master is in the screen...
	if (!defined $args->{'ID'}) {
		for my Actor::Player $player (@$playersList) {
			if (($player->name eq $config{followTarget}) && !$player->{'dead'}) {
				$args->{'ID'} = $player->{ID};
				$args->{'following'} = 1;
				$args->{'name'} = $player->name;
 				message TF("Found my master - %s\n", $player->name), "follow";
				AI::clear(qw/move route/);
				last;
			}			
		}
	} elsif (!$args->{'following'} && $players{$args->{'ID'}} && %{$players{$args->{'ID'}}} && !${$players{$args->{'ID'}}}{'dead'} && ($players{$args->{'ID'}}->name eq $config{followTarget})) {
		$args->{'following'} = 1;
		delete $args->{'ai_follow_lost'};
 		message TF("Found my master!\n"), "follow";
		AI::clear(qw/move route/)
	}
```
... but not sure if it right. _(iRO server still down for another approximately 8 hours before test)_
😥😥😥😥😥

**Comment by Nipodemos** [comment]
@Fadreus that seems ok to me! but i'm not very good on openkore, at least the syntax is correct, i can't give you sure this will work :confused:

**Comment by c4c1n6kr3m1** [comment]
put the code before the message , so logically , a line faster
i use low ai_follow_lost_end , i don't care what people say, i made my slave bot walk like client does , bump the master every time master made a single tiny step

**Comment by Fadreus** [comment]
- `ai_follow_lost_end 1`
- `AI::clear(qw/move route/)`

These seems to fix the time taken to find master & start following master once found.
It just that now looking more weird 😆 when things getting mobby with **Position Bug** and **Skill didn't check LOS**. More or less, this increase support efficiency greatly _(at least to me, that is)_

Thanks. Now, leveling to 175 does't seems hard with quick-witted slaves 😁.

**Comment by Nipodemos** [comment]
you coud do a pull request with this line you inserted :smile:

**Comment by Fadreus** [comment]
Okies.. 😸
