### ISSUE TITLE
Openkore can't load config.txt on Mac

### ISSUE THREAD

**Issue by icecoldweather** [OpenKore/openkore#1963]
It's my first time using openkore on a Mac and I'm pretty inexperienced on it..On executing the openkore.pl file in terminal, an error comes up saying that the config.txt file can't be loaded. I've installed command line tools, homebrew and readline but can't figure out what's the problem.. Would appreciate any help.
Thanks!!

Affected configuration(s)/ file(s):
Benchmarking was not compiled on this system
*** OpenKore what-will-become-2.1 ( version ctime:2018_04_25 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

Loading all plugins (by default)...

Unable to load the file config.txt.
Benchmark results saved to benchmark-results.txt
*** OpenKore what-will-become-2.1 ( version ctime:2018_04_25 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

**Comment by sctnightcore** [comment]
it ok ?
