### ISSUE TITLE
Help : problem > Packet Parser: Unknown switch: 0A84 and 0AA5 !

### ISSUE THREAD

**Issue by sikama10** [OpenKore/openkore#1966]
hello, it's me again. I managed to connect to the server. thanks to the help of @sctnightcore he was a big help to me. thank you for spending again!

once launch the openkore. it connects to the map, but in the table I still encounter error codes.
`You are now: UNKNOWN_STATUS_824`
`Packet Parser: Unknown switch: 0A84`
`Packet Parser: Unknown switch: 0AA5`

is it from recvpacket.txt?

I took the file provided from openkore in the openkore \ tables \ kRO \ RagexeRE_2017_06_14b \ recvpacket.txt folder, I do not know if it was a good idea.

if you had an idea how to settle get error code, you save my life.
ah yes i tested the recvpacket.txt thanks to the extraction of the software peek master. it does not work.
so I did some research before posting. I did not find the same error code on google.
thank very much for your help. really !!!

![faefaefaf](https://user-images.githubusercontent.com/38733584/39303949-48baa79c-4958-11e8-9dae-5d2c48a63880.png)

**Comment by alisonrag** [comment]
this packets is not implemented in openkore, but it should not stop your bot

**Comment by alisonrag** [comment]
you have to undertand prel and this:
http://openkore.com/index.php/Network_subsystem

after that you can try implement and add to openkore in src/network/receive/kRO/Sakexe_0.pm

the struct to this packet is:
` '0a84': 
    [
        (
            ("guild basic info", (parseAllFields,), (0, 100000000)),
            [
                ('guild id', generic, 4, 1),
                ('guild level', generic, 4, 1),
                ('online members', generic, 4, 1),
                ('max members', generic, 4, 1),
                ('avg players level', generic, 4, 1),
                ('guild exp', generic, 4, 1),
                ('guild next level exp', generic, 4, 1),
                ('tax points', generic, 4, 1),
                ('guild honor', generic, 4, 1),
                ('guild virtue', generic, 4, 1),
                ('guild emblem id', generic, 4, 1),
                ('guild name', string, 24, 1),
                ('guild castles', string, 16, 1),
                ('guild money', generic, 4, 1),
                ('guild leader char id', generic, 4, 1),
            ]
        ),
    ],

`
and

`   '0aa5': 
    [
        (
            ("guild members list", (parseAllFields,), (0, 100000000)),
            [
                ('num', counter, 0, 1),
                ('account id', generic, 4, 1),
                ('char id', generic, 4, 1),
                ('hair style', generic, 2, 1),
                ('hair color', generic, 2, 1),
                ('sex', generic, 2, 1, getUInt, printSex),
                ('class', generic, 2, 1, getUInt, printClass),
                ('level', generic, 2, 1),
                ('basic exp', generic, 4, 1),
                ('online', generic, 4, 1, getUInt, printGuildMemberOnline),
                ('position id', generic, 4, 1),
                ('last login time', generic, 4, -11),
            ]
        ),
    ],
`

this packets is already implemented in old packets in official servers you can use old packets as base to implement in openkore
base to 0aa5:
https://github.com/OpenKore/openkore/search?utf8=%E2%9C%93&q=guild_members_list&type=

base to 0a84:
https://github.com/OpenKore/openkore/search?utf8=%E2%9C%93&q=guild_info&type=

**Comment by sikama10** [comment]
Oh shit, I'll try to understand all that. my brain is going strong.
x_x thank very much
