### ISSUE TITLE
Bugs: Stuck route after selling and open storage loop.

### ISSUE THREAD

**Issue by N3evin** [OpenKore/openkore#197]
There seems to be a bug where the route will be stuck after autosell and storage open kept on loop without stopping.

I had set lockMap and auto sit, so it use to be sell > storage > sit till hp 100% > go to lockMap.

However it is no longer working.

**Comment by itsrachelfish** [comment]
Solved this issue on IRC. :+1:

**Comment by Suchat777** [comment]
how to solve this?
I got this loop too when not enough zeny for auto buy

**Comment by itsrachelfish** [comment]
@Suchat777 Download the most recent version of openkore
