### ISSUE TITLE
IdRo Renewal cant login

### ISSUE THREAD

**Issue by saitamax1** [OpenKore/openkore#1971]
@sctnightcore 
hello i wanna ask about my openkore for IdRo Renewal. I can't login. when i start and choose server and then my id and pass it goes like this :
Connecting to Account Server...
Connecting (202.93.25.131:6900)... connected
Secure Login...
Sending encoded password...
Timeout on Account Server, reconnecting. Wait 42 seconds...
Connecting to Account Server...
[reconnect] Login retry number 2, setting reconnect timeout to 62 seconds.
Connecting (202.93.25.131:6900)... connected
Secure Login...
Sending encoded password...
Timeout on Account Server, reconnecting. Wait 62 seconds...
Connecting to Account Server...
always like this, do you know how to fix this ?
Thanks

**Comment by sctnightcore** [comment]
use xkore 1 and xkore3
