### ISSUE TITLE
Timeout on Map Server IRO Chaos

### ISSUE THREAD

**Issue by Avngl** [OpenKore/openkore#1981]
Hi. I noticed that iro:restart is updated. I assumed IRO Chaos was updated too but currently timeout on map server.

**Comment by Fadreus** [comment]
@Avngl 
You don't **NOTICED,** you **READ.**
You don't **ASSUME,** you **CHECK.**

As dev spend their time to update openkore FREELY, you should do you part too in this community; spend your time learning how to use github.
