### ISSUE TITLE
XKORE 3 Not working for iRO Chaos but works on Thor

### ISSUE THREAD

**Issue by Avngl** [OpenKore/openkore#1983]
Tried to run OpenKore in Xkore 3 mode but the console shows disconnected upon clicking 'Chaos' Server. I am able to login to the game and move around fine without DCing but Openkore console shows that it is still "connecting" in the background. 

![image](https://user-images.githubusercontent.com/36796461/39659214-488903c2-5056-11e8-80f7-184872b7b5e1.png)

I tried the same steps and selected Thor instead of Chaos and OpenKore connected successfully in XKore 3 mode.

![image](https://user-images.githubusercontent.com/36796461/39659223-7004d4e4-5056-11e8-8133-29c0614056e0.png)

**Comment by alisonrag** [comment]
Send infos with debug packet sent and received actived

**Comment by Avngl** [comment]
It says:

Waiting Ragnarok Client to connect on (localhost:6901)
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected

Sent packet    : 0064    [55 bytes]  [Account Server Login]
<< Received packet:      0069 - Account Info [111 bytes]

---------- Account Info ----------

---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  492    128.241.92.155  4500
1   Chaos                 1765   128.241.92.130  4500
-----------------------------------------------------


---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  492    128.241.92.155  4500
1   Chaos                 1765   128.241.92.130  4500
-----------------------------------------------------
Closing connection to Account Server

**Comment by alisonrag** [comment]
its not complete we need infos with:
```
debugPacket_unparsed 1
debugPacket_received 2
debugPacket_ro_sent 2
debugPacket_sent 2
```

**Comment by Avngl** [comment]
Done. :)

```
Waiting Ragnarok Client to connect on (localhost:6901)
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
================================================
<< Sent by RO client:    0064 [55 bytes]   May 08 00:48:36 2018
  0>  64 00 12 00 00 00 74 65    73 74 65 72 6D 65 73 74    d.....testermest
 16>  65 72 00 00 31 00 26 00    52 00 45 00 56 00 68 61    er..1.&.R.E.V.ha
 32>  68 61 6C 6F 6F 6B 00 00    31 00 26 00 56 00 45 00    halook..1.&.V.E.
 48>  4E 00 5F 00 31 00 01                                  N._.1..
================================================
>> Sent packet: 0064  [Account Server Login] [55 bytes]   May 08 00:48:36 2018
  0>  64 00 12 00 00 00 74 65    73 74 65 72 6D 65 73 74    d.....testermest
 16>  65 72 00 00 31 00 26 00    52 00 45 00 56 00 68 61    er..1.&.R.E.V.ha
 32>  68 61 6C 6F 6F 6B 00 00    31 00 26 00 56 00 45 00    halook..1.&.V.E.
 48>  4E 00 5F 00 31 00 01                                  N._.1..
================================================
<< Received packet:      0069 - Account Info [111 bytes]   May 08 00:48:37 2018
  0>  69 00 6F 00 BF 59 91 80    7A 9D 53 00 00 00 00 00    i.o..Y..z.S.....
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 80    ................
 48>  F1 5C 9B 94 11 54 68 6F    72 00 00 00 00 00 00 00    .\...Thor.......
 64>  00 00 00 00 00 00 00 00    00 74 01 00 00 00 00 80    .........t......
 80>  F1 5C 82 94 11 43 68 61    6F 73 00 00 00 00 00 00    .\...Chaos......
 96>  00 00 00 00 00 00 00 00    00 68 07 00 00 00 00       .........h.....
---------- Account Info ----------
Account ID: 5479802    7A 9D 53 00
Sex:        Girl
Session ID: 2157009343 BF 59 91 80
            0          00 00 00 00

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  372    128.241.92.155  4500
1   Chaos                 1896   128.241.92.130  4500
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (128.241.92.162:6800)...disconnected

```

**Comment by Avngl** [comment]
This can be closed as XKore 3 is functioning on Chaos with the latest version of OpenKore

**Comment by Avngl** [comment]
@alisonrag This issue is present once again with the current version of OpenKore
@sctnightcore

**Comment by sctnightcore** [comment]
?

**Comment by Avngl** [comment]
@sctnightcore  Pls re-open. Same problem now after the latest update of openkore. Can't login using Xkore 3

**Comment by c4c1n6kr3m1** [comment]
just tested several minutes on chaos
works fine
may be you forgot to change something on config.txt 
server 1 #<<< you put 0 , and it won't work
XKore_listenPort 6901 #<<< 1 bot for 1 port

**Comment by Avngl** [comment]
@c4c1n6kr3m1 It works now that I downloaded the newest version of OpenKore. That issue was present last week when openkore was updated for iro after the weekly maint. My config is correct as it was working previously, and then stopped working and so on.

**Comment by Avngl** [comment]
It's not working again with the latest openkore. Haha

**Comment by c4c1n6kr3m1** [comment]
openkore hates you
that's it
