### ISSUE TITLE
eventMacro waypoints + wait4party pl

### ISSUE THREAD

**Issue by gprevedello** [OpenKore/openkore#1985]
Hi! I was trying to figure out a waypoint macro to improve my route during my hunting. In addition the code should cope with wait4party plugin. So I came out to this:

Explaining - 13 Wp, it should trigger when reached the lockmap and them when reached the pre-determined coordinate. While not there, it should spam the console command move lockmap X Y.
When reached the determined location, call the next automacro and so on. 
However, it seems that the automacro won't break the while loop. (Actually I did not find anything that would break it, whithout stopping the whole macro itself). 
```
automacro move0{
	InMap alde_dun02
	run-once 1
	priority 14
	call movem0
	
}
macro movem0 {
        release move13
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 137) && ($py != 171)) {
	do move alde_dun02 137 171
		}
}
automacro move1{
	IsInCoordinate 137 171
	InMap alde_dun02
	run-once 1
	priority 13
	call movem1
}
macro movem1 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 175) && ($py != 192)) {
	do move alde_dun02 175 192
	}
}
automacro move2{
	run-once 1
	InMap alde_dun02
	IsInCoordinate 175 192
	priority 12
	call movem2
}
macro movem2 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 78) && ($py != 245)) {
	do move alde_dun02 78 245
		}
	}
}
automacro move3{
	run-once 1
	InMap alde_dun02
	priority 11
	IsInCoordinate 78 245
	call movem3
}
macro movem3{
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 61) && ($py != 227)) {
	do move alde_dun02 61 227
		}
	}
automacro move4{
	run-once 1
	InMap alde_dun02
	priority 10
	IsInCoordinate 61 227
	call movem4 
}
macro movem4 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 38) && ($py != 181)) {
	do move alde_dun02 38 181
		}
}
automacro move5{
	run-once 1
	InMap alde_dun02
	priority 9
	IsInCoordinate 38 181
	call movem5 
}
macro movem5 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 45) && ($py != 49)) {
	do move alde_dun02 45 49
		}
}
automacro move6{
	run-once 1
	InMap alde_dun02
	priority 8
	IsInCoordinate 45 49
	call movem6
}
macro movem6 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 114) && ($py != 72)) {
	do move alde_dun02 114 72
		}
	}
automacro move7{
	run-once 1
	InMap alde_dun02
	priority 7
	IsInCoordinate 114 72
	call movem7
}
macro movem7 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 174) && ($py != 53)) {
	do move alde_dun02 174 53
		}
}
automacro move8{
	run-once 1
	InMap alde_dun02
	priority 6
	IsInCoordinate 174 53
	call movem8 
}
macro movem8 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 257) && ($py != 44)) {
	do move alde_dun02 257 44
		}
	}
automacro move9{
	run-once 1
	InMap alde_dun02
	priority 5
	IsInCoordinate 257 44
	call movem9 
}
macro movem9 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 263) && ($py != 250)) {
	do move alde_dun02 263 250
		}
}
automacro move10{
	run-once 1
	InMap alde_dun02
	priority 4
	IsInCoordinate 263 250
	call movem10
}

macro movem10 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 194) && ($py != 253)) {
	do move alde_dun02 194 253
		}
}
automacro move11{
	run-once 1
	InMap alde_dun02
	priority 3
	IsInCoordinate 194 253
	call movem11
}
macro movem11 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 233) && ($py != 122)) {
	do move alde_dun02 233 122
		}
}
automacro move12{
	run-once 1
	InMap alde_dun02
	priority 2
	IsInCoordinate 233 122
	call movem12
}

macro movem12 {
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 176) && ($py != 116)) {
	do move alde_dun02 176 116
	}
}

automacro move13{
	run-once 1
	InMap alde_dun02
	priority 1
	IsInCoordinate 176 116
	call movem13
}

macro movem13 { 
	release move0
	release move1
	release move2
	release move3
	release move4
	release move5
	release move6
	release move7
	release move8
	release move9
	release move10
	release move11
	release move12
}
```

Results 1 - Openkore triggers the first macro, move to the first coordinate and them it becomes stuck in this command "do move alde_dun02 137 171" spamming all the way. 

Result 2 - A curious fact is that when I inserted the line "do macro moveX stop" - refering to the last macro activated, it returned an error "there is no macro moveX on the queue". 

ex:
```
automacro move1{
	IsInCoordinate 137 171
	InMap alde_dun02
	run-once 1
	priority 13
	call movem1
}
macro movem1 {
        **do macro movem0 stop**
	$px = &arg ("$.pos", 1)
  	$py = &arg ("$.pos", 2)
	while (($px != 175) && ($py != 192)) {
	do move alde_dun02 175 192
	}
}
```
Despite the error mentioned, somehow the bot was running through all the waypoints as expected. On the other hand, after the first complete loop (walking through the 13 wps) it became stuck in the same problem described on the result 1 above. 

Does anyone would have a clue about this? How is it possible to break a while loop with another macro.

Thank you!

**Comment by Nipodemos** [comment]
hello :smile: 
## first
first of all, you are using the **priority** parameter incorrectly
here on eventMacro, the value is different. The LOWER the number, more priority it will have
so:
**automacro move0** should be priority 1
**automacro move1** should be priority 2
an so on

or you can set the value as negative
**automacro move0** as -14 (minus fourteen)
**automacro move1** as -13
and so on

## second

you didnt need to use &arg() to get the pos
you can simply put that way:
```perl
automacro move10{
	run-once 1
	InMap alde_dun02
	priority 4
	IsInCoordinate 263 250
	call movem10
}

macro movem10 {
        #HERE IS THE DIFFERENCE
	while ($.pos != 194 253) {
	        do move alde_dun02 194 253
	}
}
```

### be careful, if something or someone is in the exact cell you want to be, you will not be able to stay on this cell, so the next eventMacro will not trigger

i hope that helped you out

**Comment by gprevedello** [comment]
Hi Nipodemos,
thank you for your reply! I am testing this new code and asap I`ll post the results here.
=)

**Comment by Nipodemos** [comment]
:smile: 
if it is working then nothing else matters :laughing: :laughing: :laughing:

**Comment by Pachu1985** [comment]
just use the planwalk plugin, im using it and its magical but im not sure if it works with latest version of openkore (i have a pretty old version, i just update the connection files)
