### ISSUE TITLE
the leatest vison of openkore use party chat will Garbled

### ISSUE THREAD

**Issue by dcyxxt** [OpenKore/openkore#1996]
the leatest vison of openkore use party chat will Garbled

###### Steps to Reproduce:
![_20180514003252](https://user-images.githubusercontent.com/29876819/39969458-6fce433e-570e-11e8-8efb-d452c90f71ee.png)

**Comment by dcyxxt** [comment]
i am CRO and chinese simple system

**Comment by forbbs** [comment]
In src\network\receive.pm,sub party_chat add bytesToString

sub party_chat {
	my ($self, $args) = @_;
	my $msg = bytesToString($args->{message});

**Comment by alisonrag** [comment]
Is working? If yes i can make a pull

**Comment by forbbs** [comment]
It's working.I can confirm.
