### ISSUE TITLE
bot can not move to in_sphinx4 from in_sphinx3

### ISSUE THREAD

**Issue by june1112** [OpenKore/openkore#2002]
What I see is.... bot is trying to go on top portal which are not the right portal to enter in_sphinx4 .

The reason i know this problem is because when ever bot tele near the top portal.... bot will walk but after enter portal.. it instantly tele.
But when ever the bot tele near down portal... it auto teleport and not go inside to go in_sphinx4 .
![cucu](https://user-images.githubusercontent.com/22233405/40177196-0c51c91e-5a08-11e8-8857-59654e79dde0.PNG)   Please help thank you.
I try to update portal but it not work... may be i did something wrong.

**Comment by Nipodemos** [comment]
which server ?

**Comment by june1112** [comment]
in_sphinx3 12 69 in_sphinx4 10 224
in_sphinx3 35 227 in_sphinx3 60 227
in_sphinx3 60 227 in_sphinx3 35 227
in_sphinx3 70 83 in_sphinx3 70 111
in_sphinx3 70 111 in_sphinx3 70 83

I don t know it correct or wrong or not thank

**Comment by Minabe** [comment]
That map does tend to mess with route tele, mine sometimes detects the route and stops but other times it just tps again, when in that map i just clear the ai when it lands near the portal and it resumes correctly.

**Comment by Fadreus** [comment]
Try change `route_teleport_minDistance` to 300~500 when in this map _(macro)?_

OR

Delete all portals in this map, enable `portalRecord 1` then walk through all portals in this map manually when using XKore 1 _(ai manual, play like usual)_ if you don't know check the portals.

**Comment by Minabe** [comment]
I don't know if that'd help since i've got mine to 180 and even when it lands near the portal (just out of sight), it still tps. Might be a timing thing, bc of lag maybe.

**Comment by june1112** [comment]
thank you for your  answer... you mean i need to type ai to let the bot stop? but befefore that delete all portal first....    and I need to play manually take him to the map right. Also, use portalRecord 1in config?

**Comment by june1112** [comment]
already try to walk in all the portal in 3 floor but when open bot again... it not walk to anywhere. Yeah am using x1

**Comment by Fadreus** [comment]
Deleting portals and recording it is just simple way to get correct coordinates _(coz u said u dont know how)_ not really to fix this.

The idea is to walk when u reach the last area there on the left.
Try use macro when u reach 35 227 disabling `route_teleport`
If u have better macro check coordinate when `x = 0~50 & y = 50~230` would be good to.

**Comment by june1112** [comment]
thank you for your kind answer, I have test everything and found that if use route tele 0 for bot to walk... it will go to top portal and walk down to enter down portal. It is as you just said ... need macro to put route_teleport 0    32  227 after enter portal on top to be in that location.
Any example of this would be nice for me.
But thank you so much man

**Comment by rkone23** [comment]
@june1112 Hi there, since I just started playing mysg too, mind if you share the bot?

**Comment by june1112** [comment]
am just rent from some guy per month bro, he lock the ip of the computer.

**Comment by rkone23** [comment]
@june1112 If possible, can I get the contact of the guy?

**Comment by june1112** [comment]
i will close it now since i found other way to do it by let it walk in that map instead thank for help.
