### ISSUE TITLE
Bot disconnect when using sl (skill on ground location)

### ISSUE THREAD

**Issue by Zeddzorr** [OpenKore/openkore#2004]
Hello, i have a problem with my bot, everything work exept skill on ground location (sl)
here are the confs:
http://imagizer.imageshack.us/a/img923/378/GtXi1p.png
https://imageshack.com/a/img921/9431/2Zop0O.png

that gave me server.txt : 
[Natural RO]
ip 66.150.188.126
port 6900
master_version 1
version 30
serverType 8_1
serverEncoding Western
charBlockSize 144
recvpackets recvpackets.txt
addTableFolders iRO

I've tried all serverType but ONLY 8_1 work.

Once in game i can use sm (skill on monster):
https://imageshack.com/a/img924/3813/bX7LSq.png

But when i use sl (skill on location) is disconnect me ! : 
https://imageshack.com/a/img921/1125/DLAr5v.png

server: http://natural.ro-game.net/
recvpackets.txt : https://pastebin.com/NJZDeC5v

I really hope you guys can help me out, i think it might be serverType but no other type worked.

New problem, i get disconnected as soon as my bot is set to AI on, but work normal with Ai manual.

**Comment by sctnightcore** [comment]
clientdate ?

**Comment by Zeddzorr** [comment]
I've tried RagexeRE_2012_04_10a as serverType but i can't get online, it disconnect me.
where should i add clienthash ? do you think that's what causing trouble ?

**Comment by sctnightcore** [comment]
https://kiwiirc.com/client/irc.freenode.net/?nick=IRC-Source_?#openkore

**Comment by sctnightcore** [comment]
join iRC again

**Comment by sctnightcore** [comment]
```
[Natural RO]
ip 66.150.188.126
port 6900
master_version 1
version 30
serverType kRO_RagexeRE_2012_04_10a
serverEncoding Western
charBlockSize 144
addTableFolders kRO/RagexeRE_2012_04_10a;translated;translated/kRO_english;kRO
clientHash 365e0ac78598abb316e6a98f67fb0bcb
```

**Comment by Zeddzorr** [comment]
@sctnightcore I just tried the server conf you got me and its working ! You're awesome thank you :)
