### ISSUE TITLE
can not calculate route after die 2 or 3 times

### ISSUE THREAD

**Issue by june1112** [OpenKore/openkore#2013]
After my bot die for 3 to 5 times and res pawn in the town... it turn out that it can not goes back to the map and said can not calculate route portal (name of the map) and stay afk like that for ever with the message can not calculate route portal in loop. Need to re open only to make it walk back. My question is...  is it normal for openkore to have problem like this? I need which kind of macro to fix this? or I will just use reconnect function to relog every 5min? 
Thank

**Comment by june1112** [comment]
found one solution which are reload portals macro

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore
![image](https://user-images.githubusercontent.com/32188494/40391560-46ac3c9c-5e4b-11e8-84c8-3ce326047806.png)

Continue at #1069.
