### ISSUE TITLE
The server has denied your connection.

### ISSUE THREAD

**Issue by awaw99** [OpenKore/openkore#2014]
Please help 
I could not connect to my private server 
it says "The server has denied your connection"
I am really new to this.

Here's my server txt code:
[sRO]
ip 162.248.93.73
port 6900
master_version 1
version 45
serverType kRO_RagexeRE_2013_08_07a
addTableFolders sRO
charBlockSize 145
recvpackets recvpackets.txt
#sendCryptKeys 0x7E241DE0, 0x5E805580, 0x3D807D80

Heres the .exe date info:
https://imgur.com/a/cTFnnFf

Here's my openkore execution code result:
Connecting to Account Server...
Connecting (162.248.93.73:6900)... connected
---------- Account Info ----------
Account ID: 2000057    B9 84 1E 00
Sex:        Boy
Session ID: 552877361  31 3D F4 20
            2094814038 56 53 DC 7C

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Saint                 21     162.248.93.73   6121
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (162.248.93.73:6900)...disconnected
Connecting to Character Server...
Selected server: Saint
Connecting (162.248.93.73:6121)... connected
Received characters from Character Server
------------- Character List -------------
Slot 1:  (, Boy, level 1/65536, )
Slot 100:  (, Boy, level 1/858240164)
Slot 121:  (, Boy, level 34304/25640)
Slot 255:  (, Boy, level 0/1682949100)
------------------------------------------
PIN code is correct.
------------- Character List -------------
Slot 1:  (, Boy, level 1/65536, )
Slot 100:  (, Boy, level 1/858240164)
Slot 121:  (, Boy, level 34304/25640)
Slot 255:  (, Boy, level 0/1682949100)
------------------------------------------
Received characters from Character Server
------------- Character List -------------
Slot 1:  (, Boy, level 1/65536, )
Slot 100:  (, Boy, level 1/858240164)
Slot 121:  (, Boy, level 34304/25640)
Slot 255:  (, Boy, level 0/1682949100)
------------------------------------------
Received characters from Character Server
------------- Character List -------------
Slot 1:  (, Boy, level 1/65536, )
Slot 100:  (, Boy, level 1/858240164)
Slot 121:  (, Boy, level 34304/25640)
Slot 255:  (, Boy, level 0/1682949100)
------------------------------------------
Received characters from Character Server
------------- Character List -------------
Slot 1:  (, Boy, level 1/65536, )
Slot 100:  (, Boy, level 1/858240164)
Slot 121:  (, Boy, level 34304/25640)
Slot 255:  (, Boy, level 0/1682949100)
------------------------------------------
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 2F 00 00 00 (47)
MAP Name: prontera.gat
MAP IP: 162.248.93.73
MAP Port: 5121
-----------------------------
Closing connection to Character Server
Disconnecting (162.248.93.73:6121)...disconnected
Connecting to Map Server...
Connecting (162.248.93.73:5121)... connected
Disconnecting (162.248.93.73:5121)...disconnected
The server has denied your connection.

**Comment by sctnightcore** [comment]
if pServer . GO IRC . You can ask me

**Comment by awaw99** [comment]
@sctnightcore how can i do that sorry im really new in this stuff

**Comment by sctnightcore** [comment]
https://kiwiirc.com/client/irc.freenode.net/?nick=IRC-Source_?#openkore @awaw99
