### ISSUE TITLE
i canot generate packet

### ISSUE THREAD

**Issue by deojet** [OpenKore/openkore#202]
Who can help mee????
i use win10 <<< is beacuase this or ...
**1...RO Tools v1.0.3**

==================[ ERROR ]==================
Sorry I cant find the offset of the packet length function.
The executable file might be compressed/protected.
=============================================

**2.....OpenKore Packet Length Extractor v1.1.0**
error.?????????
**3....Packet Extractor v3**
error.?????????

**Comment by Jozoko** [comment]
executable file might be compressed/protected

**Comment by deojet** [comment]
thank ,i edit new Receive & Sand *.pm it work but warnning massage ,than i can run my bot too.

**Comment by popololopo** [comment]
Hi, deojet, could you explain a bit more how you did that ? i facing the same problem "The executable file might be compressed/protected." for my exe. =x
Thanks

**Comment by Cozzie** [comment]
I am assuming this is related to tRO. If so, please refer to #221.
