### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by RobotTZ** [OpenKore/openkore#203]
<<Received packet:   006C - Error logging into Game Login Server(invalid character specified)...[3 bytes]
0> 6C 00 000
Error logging into Character Server(invalid character specified)
Disconnecting(103.55.55.31:4500).....disconnected

please help me

**Comment by roxaslock** [comment]
check your in network folder.
or post your code,, let me see

**Comment by scream1ng** [comment]
Rox? leopardo?

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
