### ISSUE TITLE
[bRO] bug : command 'uneq' does not work

### ISSUE THREAD

**Issue by Guiim** [OpenKore/openkore#2031]
###### Summary: 

command 'uneq'

###### Expected Behavior:

should unequip the specified equipment

###### Actual Behavior:

informs that the equipment has been unbalanced, but does not

###### Steps to Reproduce:

'uneq #'

version:

![image](https://user-images.githubusercontent.com/19537284/40921959-45abce20-67e7-11e8-819a-eb564b0d4523.png)

server : bRO Thor

uneq
![image](https://user-images.githubusercontent.com/19537284/40921839-fd266b92-67e6-11e8-802a-191af0fd3469.png)

command i for verification

![image](https://user-images.githubusercontent.com/19537284/40921879-14320760-67e7-11e8-9001-ca9891eb2027.png)

reported user 'josedafeira'.

http://openkorebrasil.org/index.php?/topic/4793-comando-uneq-bugado/#entry37199

**Comment by lututui** [comment]
Happens on all servers

**Comment by alisonrag** [comment]
Openkore was sending the right packet but filled with 0
When i tested other packets if you send the correct size, but filled with 0 the server dont disconnect you
