### ISSUE TITLE
openkore disconnect after run 1 minute

### ISSUE THREAD

**Issue by andraaza** [OpenKore/openkore#2033]
please help me, why openkore disconnect after run 1 minute thks
Server IdRO
![ro](https://user-images.githubusercontent.com/36213055/40966218-1aafa31a-68da-11e8-9ea3-2bf147d20cac.PNG)

**Comment by sctnightcore** [comment]
idRO RE?

**Comment by cikdinz** [comment]
idRO classic... me too....

**Comment by sctnightcore** [comment]
Openkore dont work in idRO classic !

**Comment by sctnightcore** [comment]
idk :p

**Comment by Dorizo1** [comment]
@sctnightcore we could still use an Openkore in iDRo Classic with some few changes... 

@andraaza @cikdinz u guys sure it's diconnected ?? can u guys sending ur Openkore in Zip Files to my Emails ?
