### ISSUE TITLE
Cook command not working properly

### ISSUE THREAD

**Issue by Nipodemos** [OpenKore/openkore#2035]
###### Summary: 
When it is used the genecist skill `Mixed Cooking` , and right after that use the command `cook 0`, nothing happens.
###### Affected configuration(s)/ file(s):
```
[Jun 04 02:13:16 2018.22] Você está conjurando Mixed Cooking em si (Atraso: 0ms)
[Jun 04 02:13:16 2018.25] UseSkill - Casting started, waiting for cast to finish...
[Jun 04 02:13:16 2018.95] Received packet: 00B0 Handler: stat_info
[Jun 04 02:13:16 2018.97] Stat: 7 => 4768
[Jun 04 02:13:16 2018.10] Received packet: 025A Handler: cooking_list
[Jun 04 02:13:16 2018.10] ----------------------------- Cook List ------------------------------
  0 Chá Gelado de Siroma
-------------------------------------------------------------------------------
[Jun 04 02:13:16 2018.10] Now you can use the 'cook' command.
[Jun 04 02:13:16 2018.10] Received packet: 09CB Handler: skill_used_no_damage
[Jun 04 02:13:16 2018.11] Você usou Mixed Cooking em si (Nível: 2)
[Jun 04 02:13:16 2018.11] UseSkill - Done.
[Jun 04 02:13:17 2018.77] Encrypted MID : [035F]->[332F] / KEY : [0x0070]->[0x3070]
[Jun 04 02:13:17 2018.77] ================================================
>> Sent packet: 035F   [6 bytes]   Jun 04 02:13:17 2018
  0>  2F 33 CA 0C 51 05                                     /3..Q.
[Jun 04 02:13:17 2018.77] Sent Sync
[Jun 04 02:13:17 2018.81] Received packet: 007F Handler: received_sync
[Jun 04 02:13:19 2018.61] Received packet: 035F Handler: sync
[Jun 04 02:13:21 2018.59] Input: cook 0
[Jun 04 02:13:21 2018.60] Encrypted MID : [025B]->[722B] / KEY : [0x3070]->[0x7070]
[Jun 04 02:13:21 2018.60] ================================================
>> Sent packet: 025B   [6 bytes]   Jun 04 02:13:21 2018
  0>  2B 72 01 00 90 30                                     +r...0
[Jun 04 02:13:21 2018.60] Sent Cooking.
```

and nothing happens after that...
###### Impact:
I am not able to cook +20 foods!
###### Expected Behavior:
as soon as i type `cook 0` it should remove the ingredients of the food, and make the food (or fail and make another thing)
###### Actual Behavior:
nothing happens!
###### Steps to Reproduce:
* Have a geneticist with skill Mixed Cooking at any level
* have the items required for at least one type of food (list here: https://irowiki.org/wiki/Mixed_Cooking)
* have in inventory 1 [Cooking Book: Mix Cooking](http://db.irowiki.org/db/item-info/11022/)
* try to make a food.

###### Aditional Details:
talked with @sctnightcore , and he showed me this:
```
/// Present a list of producable items (ZC_MAKINGITEM_LIST). 
/// 025a <packet len>.W <mk type>.W { <name id>.W }* 
/// mk type: 
/// 1 = cooking 
/// 2 = arrow 
/// 3 = elemental 
/// 4 = GN_MIX_COOKING 
/// 5 = GN_MAKEBOMB 
/// 6 = GN_S_PHARMACY
```

so i checked the sub of cooking, and it is sending only type 1 !!!
```perl
sub cmdCooking {
	if (!$net || $net->getState() != Network::IN_GAME) {
		error TF("You must be logged in the game to use this command '%s'\n", shift);
		return;
	}
	my ($cmd, $arg) = @_;
	if ($arg =~ /^\d+/ && defined $cookingList->[$arg]) { # viewID/nameID can be 0
                #here on sendCooking, it only has type 1
		$messageSender->sendCooking(1, $cookingList->[$arg]); # type 1 is for cooking
	} else {
		message TF("Item with 'Cooking List' index: %s not found.\n", $arg), "info";
	}
}
```

i talked with @alisonrag and showed him the list above
and he said: "just change type to 4 and it may work"

i tested and it worked!!!

so the correct way to fix this is to store which skill were used before (since the cook command can only be used after a specific skill cast, listed on the packet description) and change type based on this

**Comment by c4c1n6kr3m1** [comment]
it's cooking
not mix cooking
so nothing wrong with the command ....:)

**Comment by Nipodemos** [comment]
So
it have to make another sub for mix cooking, and another command? So the sub that receives the list of itens do cook must me changed too

**Comment by c4c1n6kr3m1** [comment]
for what? all you need is to remember the type.

**Comment by Nipodemos** [comment]
i'm sorry, i did not understand what that means
right now, the cook command does not support mix cooking and there is no other way to use the skill properly.

so, what do you suggest? modify the cook command, or create another command? (like `mixcooking` for example)

**Comment by c4c1n6kr3m1** [comment]
i was saying that cmdCooking purpose is for cooking, intentionally may be, because the comment "# type 1 is for cooking" in the code
so if you said "Cook command not working properly" , than i said "it's working"

but if you want to make it work with mix cooking, you don't need to create new command
you just need to remember the "type" that you received from server

**Comment by Nipodemos** [comment]
oh i understand :smile: 
if the cooking list sends type , then it will be great!!!
