### ISSUE TITLE
ช่วยทีคับ อันนี้มันติดบัคตรงไหนหรอ

### ISSUE THREAD

**Issue by thegenk1** [OpenKore/openkore#204]
OpenKore version what-will-become-2.1
Network state = 5
Network handler = Network::XKoreProxy
SVN revision: unknown
Loaded plugins:
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = {};

Stack trace:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = {};
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x56602b4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

**Comment by muzazhi** [comment]
ไปแก้ไรมัน ไว้บ้างละครับ

**Comment by somewere** [comment]
Ha Ha

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
