### ISSUE TITLE
Timeout on map server - iRO Chaos

### ISSUE THREAD

**Issue by PoringJuice9** [OpenKore/openkore#2040]
Downloaded latest Openkore after today's maintenance, still can't connect. I guess WP updated packets or IP again. Anyone know when this will be fixed?

**Comment by Nipodemos** [comment]
wait allanon merge pull request please, he already made

**Comment by PoringJuice9** [comment]
hope it gets approved soon

**Comment by alisonrag** [comment]
Thanks for report
