### ISSUE TITLE
Connecting to OriginsRO

### ISSUE THREAD

**Issue by Luc1993** [OpenKore/openkore#2041]
server website : https://originsro.org/

Hello, since the forum isnt that much active nowadays, i allowed myself to post here for a little help on a private server : OriginsRO

This server has no Gepard Shield / Harmony or whatsoever

The problem is that, they have 2 launchers, not 1, you have to open the 1st Launcher first, he will ask you to connect your master login, master login which allow you to create and manage game login : 

http://oi63.tinypic.com/2u5e6tk.jpg

One your logged with your master login, you can switch between all of your characters / or game logins 

http://oi64.tinypic.com/sq311l.jpg

then you click on the "play" button and it will open the second Launcher, wich will connect you directly into the server / with the game login that you chose on the previous screen ( you dont enter your login / password once you'r diriged on the second launcher )

its all i can say for now, if you have other questions i'll be glad to answer, if someone has enough time to spare on this project, it will be realy helpfull, thanks !

**Comment by alisonrag** [comment]
I was checking this server last week and i have the following information about this server
1 - use custom login based in token, so you have to get access key
2 - all autentication is made over http/ssl
3 - you can use some software to strip, but request data is encrypted
4 - xkore 3 can work, but you have to update

**Comment by Luc1993** [comment]
Thanks for the informations Alison, infortunaly, i'm not a developper, i won't be abble to do much with that i think lol, i was just wondering if someone has already checked for this server and already made an update.
Will you be able to tell me how to update the Xkore 3 for origin ? thank you !

**Comment by alisonrag** [comment]
unfotunely i dont know how you can do it, you need to update some parsers, modify some packets, but you have to learn by yourself.

by the way the owner of this server is hercules emulator developer he can easy stop openkore a few minutes after you can login
