### ISSUE TITLE
[bRO] bug : call spirit - skill sorcerer's 

### ISSUE THREAD

**Issue by Guiim** [OpenKore/openkore#2042]
###### Summary: 
erro in skill 'call elementary'
https://irowiki.org/wiki/Call_Ventus

###### Expected Behavior:
**invoke an elemental spirit**
**class active skill available as Sorcerer and part of the Elemental Spirit System.**

###### Actual Behavior:

**Actor is unknown or not ready for stat information(switch 081E, type7, val 979)**

after using the command openkore hangs, and accepts no further actions

###### Steps to Reproduce:

command 'ss skillID"

server bRO - Thor

Version-

![image](https://user-images.githubusercontent.com/19537284/41163399-ed9cf8c8-6b0e-11e8-8ec2-12b9d7bca22a.png)

error-

![image](https://user-images.githubusercontent.com/19537284/41163552-5ced8ac6-6b0f-11e8-8700-e58858f740f6.png)

![image](https://user-images.githubusercontent.com/19537284/41163548-572db2aa-6b0f-11e8-8300-d52ab6db9469.png)

###### Additional Details:
report user : swordman

http://openkorebrasil.org/index.php?/topic/4800-feiticeiro-elemental-actor-is-unknown-or-not/#entry37263

**Comment by sctnightcore** [comment]
Elemental System
```
void clif_elemental_info(struct map_session_data *sd) {
	int fd;
	struct elemental_data *ed;
	struct status_data *status;

	if( !clif_session_isValid(sd) || (ed = sd->ed) == NULL )
		return;

	fd = sd->fd;
	status = &ed->battle_status;

	WFIFOHEAD(fd,22);
	WFIFOW(fd, 0) = 0x81d;
	WFIFOL(fd, 2) = ed->bl.id;
	WFIFOL(fd, 6) = status->hp;
	WFIFOL(fd,10) = status->max_hp;
	WFIFOL(fd,14) = status->sp;
	WFIFOL(fd,18) = status->max_sp;
	WFIFOSET(fd,22);
}
```
```
void clif_elemental_updatestatus(struct map_session_data *sd, int type) {
	struct elemental_data *ed;
	struct status_data *status;
	int fd;

	if( !clif_session_isValid(sd) || (ed = sd->ed) == NULL )
		return;

	fd = sd->fd;
	status = &ed->battle_status;
	WFIFOHEAD(fd,8);
	WFIFOW(fd,0) = 0x81e;
	WFIFOW(fd,2) = type;
	switch( type ) {
		case SP_HP:
			WFIFOL(fd,4) = status->hp;
			break;
		case SP_MAXHP:
			WFIFOL(fd,4) = status->max_hp;
			break;
		case SP_SP:
			WFIFOL(fd,4) = status->sp;
			break;
		case SP_MAXSP:
			WFIFOL(fd,4) = status->max_sp;
			break;
	}
	WFIFOSET(fd,8);
}
```
