### ISSUE TITLE
CPU Usage Increase

### ISSUE THREAD

**Issue by Dorizo1** [OpenKore/openkore#2044]
can someone help me ... i had issue about CPU Usage ... at 5 May i regulary had like 00-02 CPU Usage for 1 Bots.. but now .. suddenly it increase from 02-07 ... 
already did Sleeptime and i set it 150000... i did to set it prioritize to low .. but none of them taking effect to decrease CPU Usage like before ... 
4 days i didn't realize when i open 20 Bots usually only takes like 10-20% of CPU Usage but what happen is it suddenly increasing to 100% CPU Usage ...

**Comment by sctnightcore** [comment]
20 bot  :thought_balloon:

**Comment by Dorizo1** [comment]
yup... i usually run like 40 bots in my PC but still had like 40-50% CPU Usage .. but now... 20 Bots only could freak me out heheee

**Comment by siefer214** [comment]
Reformat your pc maybe its time to clean all your data usage you have a lot
for your ram memory and dont watch porn nhyahahah

**Comment by picolojunior** [comment]
x 1 or x 0? I use to have same problem before.
Example 1 client eat 20 to 30 percent processor...
After my friend modify some setting of my graphic card... each client eat less than 10 percent. (x1)

**Comment by Dorizo1** [comment]
@siefer214 hahaaaa.. xD and btw i already uninstall the win7 thou before running it ... 

@picolojunior it's X 0 ... tried everything ...

**Comment by cikdinz** [comment]
@Dorizo1 stilll dc in on idro classic... help plz... can u sent zip master? plz....

**Comment by c4c1n6kr3m1** [comment]
try redownload bot
start from zero, don't use plugin
i have one bot, that will suck memory up, slowly but sure until more than 1 GB after several hours and keep climb up . and looks like because unusual config/plugin .

**Comment by Fadreus** [comment]
@Dorizo1 You might wanna check every changes prior to last usage especially windows update in WIn10. You can always download Openkore previous version. If Openkore older version still causing high CPU usage, I suggest you give that PC to me and you go buy new one. 😂😂😂
