### ISSUE TITLE
poseidon illegal detection 

### ISSUE THREAD

**Issue by laintime01** [OpenKore/openkore#2046]
Hi guys i got this problem when i start poseidon using power shell ，after abt 1 mintue ，illegal detection come out and ro client shut down，any advice？thx a lot

Btw server is CRO，openkore also runing in powershell

Thank you very much

**Comment by sctnightcore** [comment]
server? information ?

**Comment by sctnightcore** [comment]
cRO : https://discord.gg/XK6b59

**Comment by alisonrag** [comment]
![image](https://user-images.githubusercontent.com/10372732/41202888-49c42d7c-6ca6-11e8-969f-c354061b456a.png)

**Comment by alisonrag** [comment]
ameguard is catching proxy to local host or lan ip(edited)
if you change ip to 127.0.0.1/localhost/192.168.xxx.xxx gameguard will prompt a error and close the ragnarok client

**Comment by alisonrag** [comment]
![image](https://user-images.githubusercontent.com/10372732/41202925-bab31e12-6ca6-11e8-9c77-c2c9bad70a38.png)

**Comment by alisonrag** [comment]
this 3 people followed the instructions and is working
