### ISSUE TITLE
XKore 0 : Packet Parser: Unknown switch: 0A7B [tRO] 

### ISSUE THREAD

**Issue by jesthaiza** [OpenKore/openkore#206]
XKore 0 : Packet Parser: Unknown switch: 0A7B [tRO] 

<< Received packet:      0A7B [44 bytes]   Aug 25 03:06:43 2016
  0>  7B 0A 2C 00 28 00 00 00    01 00 00 00 02 B4 B4 E3    {.,.(...........
 16>  01 00 00 00 01 00 00 00    00 00 00 00 02 00 00 00    ................
 32>  C8 FD 69 04 FB 7A 4F 73    84 80 F4 62                ..i..zOs...b

Access maps out all but 30 seconds.

**Comment by KwangGan** [comment]
Sync package

**Comment by ninenite** [comment]
how to sync package ? please tech me

**Comment by Selifity** [comment]
Hello jesthaiza 
You use it Wireshark  look for  saw  [80 bytes]  already click right at number packet 76axxxxxxxxxxxxxx
 select coppy Vale Mabe  Ok .. Byeeee

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
