### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by Avngl** [OpenKore/openkore#2063]
Deleted

**Comment by Nipodemos** [comment]
it is impossible, you would have to make a sub that returns the mail ID, which is quite hard

**Comment by Avngl** [comment]
@Nipodemos 

I found this code from : https://github.com/OpenKore/openkore/issues/1258

`sub checkRodexID {
	my $id;
	foreach my $mail_id (keys %{$rodexList->{mails}}) { my $mail = $rodexList->{mails}{$mail_id}; next if ($mail->{page} != 0 || $mail->{page_index} != 0); $id = $mail_id; last; }
	if (defined $id) {
		message "Your wanted mail id is $id.\n";
		return $id;
	} else {
		message "You have no mails.\n";
		return 0;
	}
}`

But I am not sure how to incorporate that into the macro..
