### ISSUE TITLE
Issue with item names (private server)

### ISSUE THREAD

**Issue by mariohugo96** [OpenKore/openkore#2077]
Hi guys so recently the names of the items and quest names shows only as boxes, and the bot is not picking up any item that I configured to pick up (I had to use autoloot for the account) any clue?

thanks!
![image](https://user-images.githubusercontent.com/40477043/41749677-12d105c4-7575-11e8-8c4d-bba905d942dd.png)

**Comment by Nipodemos** [comment]
what is the language of that private server?

**Comment by mariohugo96** [comment]
Server is located in spain, but everything is on english.

**Comment by sctnightcore** [comment]
You need update item.txt !
