### ISSUE TITLE
Timeout on map server,connecting to account server

### ISSUE THREAD

**Issue by igormadeo2** [OpenKore/openkore#2079]
Timeout on map server,connecting to account server. after update today ( IRO SERVER )

**Comment by Holybeatrix** [comment]
same any luck anybody?

**Comment by Nipodemos** [comment]
iRO?

**Comment by igormadeo2** [comment]
Yes IRO

**Comment by Nipodemos** [comment]
let me explain one thing
every wekk iRO update, and when update, openkore stops working on iRO
so some developer has to fix that, to make work again
in iRO case, is @allanon who do this, so thank him
he already sent a code to fix, but need to be approved
so just wait :smile:

**Comment by Fadreus** [comment]
@igormadeo2 
@Holybeatrix 

You need to wait until celestial stars aligned in straight line then only it will start working.
iRO is working by magic. No one know how to make it work.
But every week, around Thursday (Western time) or Friday (Eastern time) the gate to new universe opened. You need to wait until the celestial door closed before you can use openkore again.
Openkore is a Gift by God. It's beyond any mortal understand.

Freaking amazing.

**Comment by Fadreus** [comment]
@igormadeo2 
@Holybeatrix 

You need to wait until celestial stars aligned in straight line then only it will start working.
iRO is working by magic. No one know how to make it work.
But every week, around Thursday (Western time) or Friday (Eastern time) the gate to new universe opened. You need to wait until the celestial door closed before you can use openkore again.
Openkore is a Gift by God. It's beyond any mortal understanding.

Freaking amazing.

**Comment by sctnightcore** [comment]
Download New openkore !

**Comment by alisonrag** [comment]
kRO Zero is not working, they use cdclient and web authentication
