### ISSUE TITLE
Problem! character select.

### ISSUE THREAD

**Issue by expertly01** [OpenKore/openkore#209]
i success with x0 and i found new a problem ....

my account id have 4 character, but x0 display just 3 character

anyone can fix this problem.... 

thank a lot!!
![2](https://cloud.githubusercontent.com/assets/16747081/18027022/4e8025f8-6c82-11e6-94ac-98ce6d57e7f6.jpg)

**Comment by itsrachelfish** [comment]
@expertly01 Can you please upload your copy of openkore?

**Comment by Jimmylamz** [comment]
https://drive.google.com/open?id=0BxqcpQY7UQq3Y2loeS1iOXFKb0U

we put raw id packets using wireshark into line 442 /src/network/send.pm

like this http://www.mx7.com/i/dd8/AGClJe.jpg

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
