### ISSUE TITLE
[pserver] The server has denied your connection

### ISSUE THREAD

**Issue by a1234594590** [OpenKore/openkore#2097]
excuse me sir
I used  bot at private server success before
but some day private server update version then bot cant use
bot show me this:
![aq1](https://user-images.githubusercontent.com/40664468/42036303-a91f4c28-7b17-11e8-9c66-3725cca8715e.jpg)
I dont' know what to do 
----------------------------------------------
server.txt:
[Aqua Marine]
ip aquamarinesf.no-ip.org
port 31742
master_version 5
version 26
serverType kRO_RagexeRE_2014_01_12
serverEncoding Big5
charBlockSize 144
recvpackets recvpackets_aquamarine.txt
addTableFolders twRO
captcha 0
clientHash
--------------------------------------------------
here is private server download: http://aquamarineserver.com/data_web/DownLoads.html
download 2.84GB - 2018/01/28 this file ,then download file done
Use system administrator to execute 1.  AquaMarineThor.exe and 2. opensetup.exe and 3. setup.exe

is there any mistake? maybe in my recvpacket.txt ? because i cant get that file using any tools
please help me
thank you

**Comment by sctnightcore** [comment]
ask in iRC!

**Comment by a1234594590** [comment]
sorry ,do you know IRC openkore URL???
I cant find it

**Comment by alisonrag** [comment]
https://webchat.freenode.net/?channels=openkore

**Comment by a1234594590** [comment]
thank you ,bro, 
hope some one can tell me or teach me what to do can let bot work in private server
