### ISSUE TITLE
Timeout on Account Server

### ISSUE THREAD

**Issue by fikriaulia13** [OpenKore/openkore#2098]
Excuse me sir, im trying this server but i got this error

Connecting to Account Server...
Connecting (45.76.176.61:6900)... connected
Packet Tokenizer: Unknown switch: 4753
Timeout on Account Server, reconnecting. Wait 31 seconds...

this is server.txt that i get from clienfinfo using grftool
ip 45.76.176.61
port 6900
master_version 12
version 45
serverType kRO_RagexeRE_2013_08_07a
charBlockSize 147
serverEncoding Western
addTableFolders kRO/RagexeRE_2017_08_07a;translated;translated/kRO_english;kRO
pauseCharLogin 1

but i cant get the recvpacket because i dont know how to do it, im using peek and always fail
im using packet extractor v3 too but its said search for packet len map failed
this the exe file
https://drive.google.com/open?id=1B5Pglui_tBz374-2CkmtaGOvKqphzu9x
thx before

**Comment by sctnightcore** [comment]
ask in iRC pls
