### ISSUE TITLE
Plugins missing

### ISSUE THREAD

**Issue by windhamwong** [OpenKore/openkore#21]
Some of the plugins are optional for installation however we should think about where can we put them.

**Comment by itsrachelfish** [comment]
What do you mean?

Currently all of the plugins have been moved into the "[needs-review](https://github.com/OpenKore/openkore/tree/master/plugins)" folder except for the macro plugin, which is now enabled by default. When we made the migration to GitHub, we changed the default behavior of the plugins folder to only load a [whitelist of default plugins](https://github.com/OpenKore/openkore/blob/master/control/sys.txt#L40-L52). This lets us have many "official" plugins directly in the repo without needing a subproject.

If there are any plugins you want enabled by default, please review them and move the "trunk" files into their own folder, exactly the same way as the macro plugin is set up.

Let me know if you have any questions, and I'm always on IRC if you wanna chat there too. :)

**Comment by ya4ept** [comment]
I propose to move workers plugins from "../plugins/needs-review/" folder in "../plugins" folder, like macro plugin. For example, I always use the plugin "alert sound". I can not use it by default.
