### ISSUE TITLE
Update code location on OpenHub

### ISSUE THREAD

**Issue by lututui** [OpenKore/openkore#210]
[Openkore's page](https://www.openhub.net/p/openkore) on OpenHub.net (formerly Ohloh) still lists 'Code Location' as being on sourceforge

**Comment by itsrachelfish** [comment]
Does this need to be updated by a specific person (an admin who has access) or can anyone with an OpenHub account fix this?

**Comment by lututui** [comment]
isieo and kLabMouse are listed as managers.

**Comment by isieo** [comment]
I'll fix it

**Comment by isieo** [comment]
done

**Comment by isieo** [comment]
@itsrachelfish i can set you as manager if you apply to be one via openhub
