### ISSUE TITLE
[pserver]how to build new servertype and PEEK on 2018server question.

### ISSUE THREAD

**Issue by blackroseyun** [OpenKore/openkore#2101]
i have 2 question , i can use PEEK and OPENKORE on most private server.
but when i use PEViewer , then i know this server's exe is about 2018.05.21.
so i want to learn how to build a servertype for this server , and i can't also use PEEK(i have run as administrator) on this Server , i dont know why , hope who can help me to solve this.
 
![qq20180629203857](https://user-images.githubusercontent.com/40693417/42092744-9649a2ea-7bdc-11e8-83bf-5efdfceedc50.png)
![qq20180629204404](https://user-images.githubusercontent.com/40693417/42092916-302c0dee-7bdd-11e8-92e5-9b585de64cd1.jpg)

this is the private server's file and exe 
[https://drive.google.com/uc?id=1gL3ydVREp-26W4-WdYq5Q7HoRw4HWzY2&export=download](url)

thanks you for watch , My English is not very good, but I'm working on it :(

**Comment by blackroseyun** [comment]
so u mean is wait for 2018's servertype?

**Comment by sctnightcore** [comment]
Yep , I'll update it . 1- 2 year .

**Comment by blackroseyun** [comment]
thank you , ill waiting , but i still want to know , why cant use PEEK on 2018's server

**Comment by sctnightcore** [comment]
U need use New PEEK from 4144.

**Comment by blackroseyun** [comment]
thank you , i try it , new PEEK can work on 2018server

**Comment by blackroseyun** [comment]
i think got recvpackets.txt is not enough , so i will waitiing for your Servertype update .
or anywhere i can find Servertype build guide , thank you

**Comment by sctnightcore** [comment]
u can get packet send in rAthena / Herc
https://github.com/HerculesWS/Hercules/blob/stable/src/map/packets_shuffle_main.h
https://github.com/sctnightcore/rathena/blob/master/src/map/clif_shuffle.hpp

**Comment by blackroseyun** [comment]
!!!!
i will go to try this , maybe i can create a servertype , so i can update file if i successful create

**Comment by blackroseyun** [comment]
I try this , but I still cant login on map server. I try kore0 and kore3.
can you watch my Servertype to check this file , I think I have something wrong . or you can try this server I provide my ID and Password

test is my servertype file , servers.txt is my setting
[test.txt](https://github.com/OpenKore/openkore/files/2150434/test.txt)
[servers.txt](https://github.com/OpenKore/openkore/files/2150437/servers.txt)

and 2018server's character interface is different , i can also setting char like before?
![testt](https://user-images.githubusercontent.com/40693417/42108750-fccdbd9a-7c0d-11e8-962e-bd7eac0a768f.jpg)

ID: test
Password: 456654

**Comment by alisonrag** [comment]
This is kRO zero interface, you need to get zero shuffle packets.
Have a many things that you have to do, i think this client use encrypted password and use token to login like kRO Zero, many time ago i implemeted both system, but still only supporting kRO Zero, you need to move and create your own servertype based in KRO Zero.

**Comment by blackroseyun** [comment]
thank you sir, i solve thie problem , and i did a 2018servertype
