### ISSUE TITLE
Timeout on Map Server (After July 5, 2018 Update)

### ISSUE THREAD

**Issue by ejsantos89** [OpenKore/openkore#2120]
Openkore not working anymore after the update.
error is Timeout on Map server, Connecting to Account Server

I hope you could help me on this

<img width="320" alt="error" src="https://user-images.githubusercontent.com/40907093/42406829-4c7a14d6-81e2-11e8-8f63-4401b313e860.PNG">

Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by Nipodemos** [comment]
i truly hope you are not speaking of iro restart

**Comment by kkampanat** [comment]
@Nipodemos I not connecting server map iro. Msg Time out Server Map.    :(

**Comment by ejsantos89** [comment]
This is IRO-Chaos server..

**Comment by Rovejoe** [comment]
play manual please .. haha

**Comment by Nipodemos** [comment]
https://github.com/OpenKore/openkore/issues/2118
dont have upadte yet, click on this link and wait there
questios are there too
