### ISSUE TITLE
Openkore doesn`t find autostorage npc

### ISSUE THREAD

**Issue by rksasuke** [OpenKore/openkore#2132]
Hello. I'm having a hard time trying to solve a problem in iRO. Whenever the autostorage triggers the bot tries to talk to the autostorage NPC but the error "Could not find an NPC at location:" comes up every time. I've tried to use the command talknpc whenever the bot is close to the npc and it works. Also the most strage part is if I swap the storageAuto_npc_type to 1 it suddenly finds the npc, but it will not proceed with the custom dialogue I need. I tested it like a dozen times and if the type is 1 openkore can find the NPC, if I use the command talknpc on console it also works, only if I set the storageAuto_npc_type to 3 I get this error. Unfortunately the Kafras are customized in iRO so I need to set the type to 3.

My console:
```
> autostorage
> Initiating auto-storage.
> Calculating auto-storage route to: Payon Town(payon): 181, 104
> NPC Exists: Kafra Employee (181, 104) (ID 50893) - (2)
> Using storage steps defined in config.
> Could not find an NPC at location (181,104).
> talknpc 181 104
> Talking to NPC at (181, 104) using sequence:
> NPC image: kafra_05.bmp
> Kafra Employee: [Kafra Employee]
> Kafra Employee: The Kafra Corporation
> Kafra Employee: is always working to provide
> Kafra Employee: you with convenient services.
> Kafra Employee: How may I be of assistance?
> NPC Kafra Employee (2): Type 'talk cont' to continue talking
> ------ Responses (Kafra Employee) ------
> #  Response
> 0  Save
> 1  Use Storage
> 2  Use Teleport Service
> 3  Rent a Pushcart
> 4  Check Other Information
> 5  Cancel
> 6  Cancel Chat
> ----------------------------------------
> NPC Kafra Employee (2): Type 'talk resp #' to choose a response.
> 
```
And my config.txt:

> storageAuto 1
> storageAuto_npc payon 181 104
> storageAuto_standpoint
> storageAuto_distance 5
> storageAuto_npc_type 3
> storageAuto_npc_steps r1 r0 n
> storageAuto_password
> storageEncryptKey
> storageAuto_keepOpen 0
> storageAuto_useChatCommand
> storageAuto_useItem 0
> storageAuto_useItem_item
> storageAuto_notAfterDeath 1
> relogAfterStorage 0
> minStorageZeny 500

Please help, I've so far read half of the wiki and searched each site of the first 25 google pages. I've tried a bunch of solutions but none seemmed to work and the bot keep stuck at autostorage function and every attempt to find the npc is failed.
Thanks.

**Comment by sctnightcore** [comment]
storageAuto_npc_steps r1 r0 n is wrong .

**Comment by rksasuke** [comment]
As far I know c isn't mandatory. I've tried, same results yet.

**Comment by Fadreus** [comment]
Hmmm,.. This happen earlier yesterday.
Same thing when talking to NPC to warp, doesn't proceed with NPC sequence `talk response`. Lazy to test, so I use macro instead xD.

**Comment by alisonrag** [comment]
config.txt
`autoTalkCont 0`

**Comment by c4c1n6kr3m1** [comment]
his problem is 
```
Could not find an NPC at location (181,104).
```
it's better stay focuse on this , i doubt change storageAuto_npc_steps to 1 really solve the problem
any one can reproduce this ?

**Comment by c4c1n6kr3m1** [comment]
did you change npcTimeResponse ?
try make it 45

**Comment by Fadreus** [comment]
> Update: for some reason it **sometimes** works, sometimes doesn't, apart of the steps synthax.

This "sometimes" is bothering me.
But based on recent changes, I think he need to apply #2134 ?
His bot prolly dead (change map) > suck & unable to move, find or what ever it is.

Not like he's telling everything _(If only he use the bug report template.)._

**Comment by Fadreus** [comment]
> Update: for some reason it **sometimes** works, sometimes doesn't, apart of the steps synthax.

This "sometimes" is bothering me.
But based on recent changes, I think he need to apply #2134 ?
His bot prolly dead (change map) > stuck & unable to move or find npc or what ever it is.

Not like he's telling everything _(If only he use the bug report template.)._

Note: I can't reproduce this **sometimes** xD, everything looks normal.

**Comment by c4c1n6kr3m1** [comment]
yes, his console report is weird
normally lots of npcs arround kafra , but his report only show one npc, the kafra
so, he edited the report ?

**Comment by rksasuke** [comment]
After a few days I solved the issue by setting the bot to relog if npc not found. It sometimes relogs 2 or 3 times but problem solved. Just to clarify, "sometimes" means sometimes in complete random times. And yes I edited the log just to remove useless data. I found a turnaround but not a solution. iRO Renewal btw.

**Comment by Fadreus** [comment]
No one should tamper with report.
It only hinder the investigation.

<details>
<summary>But 1 thing I could say; this sometimes is lag, not bug (unless you got more information).</summary>
I had this behavior long time ago & it turn out to be position lag.
</details>

**Comment by rksasuke** [comment]
Just believe me, I'm not that dumb. The problem is crystal clear: talknpc works fine, autostorage when npc type is 1 works fine, autostorage when npc type is 3 doesn't work, the npc is the same, the configuration is the same, the only thing that changes is the f...king the npc type. I already found a "solution" by myself, don't bother, just close the topic. Since it works after a few relogs I might be just some laag or packet loss.

**Comment by Fadreus** [comment]
Upload your config file here.

**Comment by Rangtasitc** [comment]
i have to say i have had a similar Problem with the npc to ama_dun the last week . 

Kore fails to continue the conversation to enter the dungeon and then reports: can not calculate route to ama_dun01 .. 

this only seems to hapen when i am using X-Kore 1 So Fadreus may be on the right track with possible lag issue.. 

Also is this hapening After you teleport or use butterfly wings to get to storage? 

You may find it is server lag from opening a new map. i get it sometimes with the sell npc's because my standpoint is where you end up once you enter the room. Kore see's it is in the map and looks for the npc but in my game client window the npc has not appeared yet and Kore gives up trying to sell or buy.

if you think this may be why it is happening add a storageAuto_standpoint [x] [y] to your config, this way kore will not look for the npc until it has moved to that location and by then the npc has spawned in.

let me know if this helped and good luck.

**Comment by Fadreus** [comment]
So the problem might be from 0447.
Download new openkore and test again.

**Comment by alisonrag** [comment]
#2760 
should handle this
