### ISSUE TITLE
TH-RO Mega Thread - All issues here only EXE bypass for EAC

### ISSUE THREAD

**Issue by luffyza123** [OpenKore/openkore#2143]
how can i fix this problem??

today my server has update new EAC, my openkore can login to map server but after 1-3 second my openkore has disconnect from map server, please help me or notice me about this problem.

ps. i'm newbie for programmer :D
ps2. i'm from Free bot page....

**Comment by Fluke7744** [comment]
tRO need some one to be Supporter no one help us Thaibot to beat that EAC and fix the problem.
Need some one who have kinds to help us plz.

**Comment by Fluke7744** [comment]
#221         @luffyza123

**Comment by oleokoong** [comment]
There is bypass bot for new EAC.. but have to paid.. just let u know..
