### ISSUE TITLE
Timeout on Map Server

### ISSUE THREAD

**Issue by ComeOnAndGitMe** [OpenKore/openkore#2147]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:
-------------------------------------------------------------------

Hey guys, after the 2018-07-12 update for iRO renewal, the timeout on map server is happening again.
Thanks in advance for the fix.

**Comment by Fadreus** [comment]
For fuck sake dude, check the Pull Request.
Check existing issue.
Do some reading.
By reading at least read bug report template before posting.

Grow some brain.
Don't give "I'm new, nub" excuse.
Everything in plain sight, unless you blind.
