### ISSUE TITLE
You can only choose a character from the first 3 character slots

### ISSUE THREAD

**Issue by lehotf** [OpenKore/openkore#2152]
###### Summary: 
Server: IRO

Hi :)

Is this happening to anyone else?

You can only choose one character from the first 3 character slots.

The server is sending a list of the first 3 character slots. Then, in the sequence, the server sends the complete list. But openkore allows only the choice of the first 3 characters (first received list).

[connection] ------------- Character List -------------
Slot 0: Char name (Class, Level, Map)
Slot 1: Char name (Class, Level, Map)
Slot 2: Char name (Class, Level, Map)

------------------------------------------
[connection] Received characters from Character Server
[connection] Received characters from Character Server
[connection] ------------- Character List -------------
Slot 0: Char name (Class, Level, Map)
Slot 1: Char name (Class, Level, Map)
Slot 2: Char name (Class, Level, Map)
Slot 3: Char name (Class, Level, Map)
Slot 4: Char name (Class, Level, Map)
Slot 5: Char name (Class, Level, Map)
Slot 6: Char name (Class, Level, Map)
Slot 7: Char name (Class, Level, Map)

###### Impact:
You can not choose characters from the other slots

**Comment by sctnightcore** [comment]
**Please use the issue template, please post information about the server and your configuration.**

**Comment by Fadreus** [comment]
This one caused by #2134 
Commit `3594d58` don't have this problem.

**Comment by Fadreus** [comment]
This one caused by #2134 
sT iRO > iRO_Renewal

**Comment by Fadreus** [comment]
This one caused by #2134 
sT iRO > iRO_Renewal

@lehotf If you need fast solution,change iRO sT back to iRO (currently iRO_Renewal) or wait.

**Comment by Fadreus** [comment]
This one caused by #2134 
sT iRO > iRO_Renewal

@lehotf If you need quick fix, change sT back to iRO or wait.

**Comment by sctnightcore** [comment]
try **openkore\src\Network\Receive\ServerType0.pm**
Line 2304: iRO => iRO_Renewal
Line 2325: iRO => iRO_Renewal


Maybe , I can try fix. back to use sT iRO

**Comment by Fadreus** [comment]
That fix the problem. :+1:

**Comment by lehotf** [comment]
\o/
Perfect! 
I love you!!!

**Comment by lututui** [comment]
#2154
