### ISSUE TITLE
Timeout on Map Server iRO Chaos

### ISSUE THREAD

**Issue by CrispyChickenFilletRice** [OpenKore/openkore#2153]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions
 (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Additional Details:

I just came back from RO after 5 years.

I've downloaded the latest Openkore now why it's always "Timeout on Map Server"?

Server: iRO Chaos

**Comment by sctnightcore** [comment]
Check : https://github.com/OpenKore/openkore/pull/2145
