### ISSUE TITLE
Unable to load the file buyer_shop.txt

### ISSUE THREAD

**Issue by jeffridelacruz** [OpenKore/openkore#2156]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Actual Behavior:

No profiles found, using standard control folder
Loading tables/item_weights.txt...
Loading control/config.txt...
Loading control/consolecolors.txt...
Loading control/mon_control.txt...
Loading control/items_control.txt...
**Unable to load the file buyer_shop.txt.**
Benchmark results saved to benchmark-results.txt
map unloaded.
macro plugin unloading, cleaning up
[raiseSkill] Plugin unloading or reloading
[raiseStat] Plugin unloading or reloading
[eventMacro] Plugin unloading
*** OpenKore what-will-become-2.1 ( version ctime:2018_07_15 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***
Bye!

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by jeffridelacruz** [comment]
I resolved the issue, I created buyer_shop.txt on control folder

**Comment by sctnightcore** [comment]
:thinking:

**Comment by Fadreus** [comment]
Be careful when you copy-paste your control folder when downloading new openkore.
