### ISSUE TITLE
XKore 3 & XKore 1 Not Working on iRO Chaos ( windows 7 64bit ) 

### ISSUE THREAD

**Issue by Rangtasitc** [OpenKore/openkore#2159]
###### Summary: 

**Unable to use XKORE 1 or Xkore 3 with latest version of openkore . 
once you have loged into the map server the RO client Freezes and kore cannot communicate with the RO client**

###### Affected configuration(s)/ file(s):
``` XKore 1 XKore 3 ```
###### Impact:
Frozen RO client Once map loads, nothing spawns no mobs no Npc's ect..
###### Expected Behavior:
A smooth running Awsum supper botting period...
###### Actual Behavior:
Stuck at Server Map with a frozen RO client.
###### Steps to Reproduce:
Use Xkore 1 or Xkore 3 to connect to iRO Chaos, with the newest download available. 
###### Summary:
When useing xkore 1 : 

Please start the Ragnarok Online client (ragexe.exe)
Ragnarok Online client found, pid = 6912
Waiting for the Ragnarok Online client to connect to X-Kore... ready
You can login with the Ragnarok Online client now.
---------- Account Info ----------
Account ID: 5495541    F5 DA 53 00
Sex:        Girl
Session ID: 1427492767 9F CF 15 55
            0          00 00 00 00

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  353    128.241.92.155  4500
1   Chaos                 2184   128.241.92.130  4500
-----------------------------------------------------
Config 'char' is already 1
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 0B 03 46 02 (38142731)
MAP Name: lou_fild01.gat
MAP IP: 128.241.92.131
MAP Port: 4505
-----------------------------
Waiting for map to load...
Your Coordinates: 245, 344
Autodetected attackDistance = 1
You are now: Job Manual (Duration: 3600s)
Calculating random route to: Louyang Field (lou_fild01): 194, 151
Autodetected attackDistance = 15
You are now: Awakening Potion (Duration: 1349.099s)
You are no longer: Job Manual
You are now: Job Manual (Duration: 2606.621s)
You are now: UNKNOWN_STATUS_993 (Duration: 474.692s)
You are now: UNKNOWN_STATUS_994 (Duration: 1674.692s)
Allowed other player invite to Party
Other players are not allowed to view your Equipment.
You joined party 'mafiaosa'
Party EXP set to Individual Take
Achievement 129004 added or updated.
Achievement 120031 added.
Achievement 120139 added.
Achievement 129004 added.
Achievement 200003 added.
Achievement 200005 added.
Achievement 200007 added.
Achievement 200020 added.
Achievement 220000 added.
Achievement 220001 added.
Achievement 220009 added.
Achievement 220010 added.
Achievement 220011 added.
Achievement 220012 added.
Achievement 220013 added.
Achievement 220023 added.
Achievement 220024 added.
Achievement 220025 added.
Achievement 220026 added.
Achievement 220027 added.
Achievement 220030 added.
Achievement 220031 added.
Achievement 220032 added.
Achievement 230100 added.
Achievement 230104 added.
Achievement 230201 added.
Achievement 230203 added.
Achievement 240000 added.
Achievement 240001 added.
Achievement 240002 added.
Achievement 240003 added.
Achievement 240004 added.
Achievement 240005 added.
Achievement 230100 added or updated.
Stuck at lou_fild01 (245,344), while walking from (245,344) to (194,151).
Stuck during route.
Calculating random route to: Louyang Field (lou_fild01): 283, 277
Timeout on Map Server, waiting actions for the Ragnarok Online client

When uiseing XKore 3 : 

Waiting Ragnarok Client to connect on (localhost:6901)
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
---------- Account Info ----------
Account ID: 5495541    F5 DA 53 00
Sex:        Girl
Session ID: 2226637295 EF C9 B7 84
            0          00 00 00 00

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  377    128.241.92.155  4500
1   Chaos                 2148   128.241.92.130  4500
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (128.241.92.162:6800)...disconnected
Connecting (128.241.92.130:4500)... connected
Config 'char' is already 1
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 0B 03 46 02 (38142731)
MAP Name: lou_fild01.gat
MAP IP: 128.241.92.131
MAP Port: 4505
-----------------------------
Disconnecting (128.241.92.130:4500)...disconnected
Closing connection to Character Server
Connecting (128.241.92.131:4505)... connected
Waiting for map to load...
Your Coordinates: 245, 344
Autodetected attackDistance = 1
You are now: Job Manual (Duration: 3600s)
Autodetected attackDistance = 15
You are now: Awakening Potion (Duration: 1344.817s)
You are no longer: Job Manual
You are now: Job Manual (Duration: 2602.339s)
You are now: UNKNOWN_STATUS_993 (Duration: 470.41s)
You are now: UNKNOWN_STATUS_994 (Duration: 1670.41s)
Allowed other player invite to Party
Other players are not allowed to view your Equipment.
You joined party 'mafiaosa'
Party EXP set to Individual Take
Achievement 129004 added or updated.
Achievement 120031 added.
Achievement 120139 added.
Achievement 129004 added.
Achievement 200003 added.
Achievement 200005 added.
Achievement 200007 added.
Achievement 200020 added.
Achievement 220000 added.
Achievement 220001 added.
Achievement 220009 added.
Achievement 220010 added.
Achievement 220011 added.
Achievement 220012 added.
Achievement 220013 added.
Achievement 220023 added.
Achievement 220024 added.
Achievement 220025 added.
Achievement 220026 added.
Achievement 220027 added.
Achievement 220030 added.
Achievement 220031 added.
Achievement 220032 added.
Achievement 230100 added.
Achievement 230104 added.
Achievement 230201 added.
Achievement 230203 added.
Achievement 240000 added.
Achievement 240001 added.
Achievement 240002 added.
Achievement 240003 added.
Achievement 240004 added.
Achievement 240005 added.
Achievement 230100 added or updated.
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Calculating random route to: Louyang Field (lou_fild01): 267, 339
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected
Proxying to [International - iRO: Ymir/Yggdrasil/Valkyrie]
Connecting (128.241.92.162:6800)... connected

###### Additional Details:

As i stated i am using a Fresh Current Version Of Kore , this Issue Began after the New iRO Packets From Pull Request [Updating packet tables and keys for iRO (Chaos and Restart) #2145](https://github.com/OpenKore/openkore/pull/2145) were added. I did mention it there but was ignored for what ever reason, so i thought maybe i would report it here if any one Cares.. Xkoe 2 works perfectly fine But i am being stalked by GM so i would like to use Xkore 1 or 3 .

Thanks for your time and i appreciate any and all feed back regarding this matter.

**Comment by Fadreus** [comment]
> I did mention it there but was ignored for what ever reason

Different issue different thread bro.
It's something we call "Management".
Github is not Forum.

Incase you miss github front page.
![image](https://user-images.githubusercontent.com/32188494/42742684-632b6b30-88ef-11e8-83db-f8f681a6109b.png)

**Comment by sctnightcore** [comment]
Go #2160
