### ISSUE TITLE
How to find send  Packet Parser when my openkore received Packet Parser: Unknown switch?

### ISSUE THREAD

**Issue by expertly01** [OpenKore/openkore#216]
i'm received  Packet Parser: Unknown switch:  0923

but i don't know how to find send packet 0923

i think that receive 0923 and in my opinion, send packet will be  0923+2A = 094C

Receive: 0923
Send: 094C

anyone can tech me how to find the send packet, thank you. :D

**Comment by itsrachelfish** [comment]
Hi @expertly01

What server are you playing on? What version of OpenKore are you using?
