### ISSUE TITLE
thRO Mega Thread - All issues here only EXE bypass for EAC

### ISSUE THREAD

**Issue by Jordanford** [OpenKore/openkore#2161]
how can i fix this problem??

today my server has update new EAC, my openkore can login to map server but after 1-3 second my openkore has disconnect from map server, please help me or notice me about this problem.

ps. i'm newbie for programmer :D
ps2. i'm from Free bot page....

**Comment by sctnightcore** [comment]
Please use the issue template, please post information about the server and your configuration.

**Comment by luffyza123** [comment]
นายบอทได้ยังอะครับ  Jordanford   เราก็เล่นเซฟไทยอยู่ พยายามขุดกระทู้เดิมขึ้นมา แต่บินไปละ

**Comment by Thanakit1987** [comment]
เห็นมีบอทตัวใหม่ ชื่อ BOTFAM นะครับ ตัวนี้ไม่ได้เกี่ยวไรกับ openkore นะครับ 
ซื้อขายกันในเว็บบอร์ดไทย กันใหญ่เลยครับ

**Comment by sctnightcore** [comment]
@Thanakit1987  กระจอก

**Comment by Thanakit1987** [comment]
@sctnightcore มันเป็นบอทมาโคร สีใช่ปะครับ  เดาเล่นๆนะครับ

**Comment by Fadreus** [comment]
Ckp omputeh la brader..
Kcik2 xnk mmpus, da bsar nyusahkn org..
