### ISSUE TITLE
Update iRO restart please. bot not working after patch 7/18/2018

### ISSUE THREAD

**Issue by icemanwafu** [OpenKore/openkore#2172]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Summary: 

Connecting to Account Server...
Connecting (128.241.92.133:6800)... connected
---------- Account Info ----------
Account ID: 
Sex:       
Session ID: 
            0          00 00 00 00

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Odin                  120    128.241.92.138  4500
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (128.241.92.133:6800)...disconnected
Pausing for 1 second(s)...
Connecting to Character Server...
Selected server: Odin
Connecting (128.241.92.138:4500)... connected
Received characters from Character Server
------------- Character List -------------
Slot 1: 
------------------------------------------
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: C
MAP Name: 
MAP IP: 
MAP Port: 
-----------------------------
Closing connection to Character Server
Disconnecting (128.241.92.138:4500)...disconnected
Pausing for 1 second(s)...
Connecting to Map Server...
Connecting (128.241.92.135:4505)... connected
Timeout on Map Server, connecting to Account Server...

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
Can u upload Ragexe.exe to me ?

**Comment by icemanwafu** [comment]
this https://we.tl/Wlo8sUe0Py ?

**Comment by icemanwafu** [comment]
@delawr0190 help please. Thank you!

**Comment by sctnightcore** [comment]
Go https://github.com/OpenKore/openkore/pull/2173
