### ISSUE TITLE
idro encrypted grf file?

### ISSUE THREAD

**Issue by frizki88** [OpenKore/openkore#2175]
Hey i just tried to use openkore for the first time and encounter an account server timeout.
and they suggested to use xcore 1 or 3.

to do that i need to edit clientinfo.xml located on data.grf (CMIIW)
but when i tried to extract, it said the grf file is encrypted and need a key

how can i find this key? or i did it wrong?? 

Thank you

**Comment by Nipodemos** [comment]
that is not the way of doing it

you create a file called `clientinfo.xml` on a folder called `data` (if the folder does not exist, you create one)
then you do that script that opens ragexe with the info of clientinfo.xml you've just created

**Comment by frizki88** [comment]
@Nipodemos Thanks for the reply!
