### ISSUE TITLE
Xcore 1 have problem after updated?

### ISSUE THREAD

**Issue by unicornbaby** [OpenKore/openkore#2179]
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
XKore 1
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 1
XKore_exeName ragexe.exe

**Comment by Fadreus** [comment]
Download new la..
Don't need to be told every week liao..
Got brain ro not?

**Comment by Fadreus** [comment]
Download new la..
Don't need to be told every week liao..

**Comment by unicornbaby** [comment]
I already updated to lastest opk version. Anyway  Xcore 0 is running smoothly. but Xcore 1 i founded some this porblem

**Comment by Fadreus** [comment]
I tested XKore 1, no **some this problem**.

**Comment by Fadreus** [comment]
I tested XKore 1, no **some this problem** found.

**Comment by unicornbaby** [comment]
@Fadreus Thank guy. This refer to me for try to solve by myself.
