### ISSUE TITLE
help me pls  It try to walk but can't

### ISSUE THREAD

**Issue by BlueAngelz** [OpenKore/openkore#218]
It try to walk but can't
[console.txt](https://github.com/OpenKore/openkore/files/456277/console.txt)

src\Network\Send
[
https://mega.nz/#!q8NA2YAT!p5XwXT6g2klZep0ZxNtsVZSzAr4uu19V1r2mjmIos7M
](url)

src\Network\Receive
[
https://mega.nz/#!Gw9wGKJb!oV0VnlHrZUXH6UAOHe6_WdYRgExyWD0bPsvI0QWn0fw
](url)

**Comment by itsrachelfish** [comment]
What server are you trying to play on? The IP address ```103.7.59.175``` isn't found in the current ```servers.txt``` table. I'm guessing you are trying to modify kore to work on a private server?

**Comment by BlueAngelz** [comment]
`[Classic]
ip 103.7.59.175
port 6551
master_version 10
version 255
serverType tRO
secureLogin 0
secureLogin_type 0
secureLogin_account 0
serverEncoding Thai
addTableFolders tRO
charBlockSize 144
gameguard 0
clientHash d7f4bc2c80f29a29aee763c8c8264918
pauseCharServer 1`

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
