### ISSUE TITLE
Ai stuck while attacking 

### ISSUE THREAD

**Issue by Jozoko** [OpenKore/openkore#219]
While bot attacking monster what spawned behiend textur - ai stuck
http://image.prntscr.com/image/8c304c4dd4f240b9b6458e6fa0078401.png

0: route

1: attack
```
{
monsterPos=>{ y=>'282', x=>'146'},
ID=>'io?.',
missedFromYou_last=>'',
dmgFromYou_last=>'',
move_start=>'1473166839.02608',
pos_to=>{y=>'282',x=>'146'},
unstuck=>{time=>'',timeout=>'2.75'},
lastSkillTime=>'1473166196.76263',
dmgToYou_last=>'0',
attackMethod=>{maxDistance=>'2',distance=>'1',type=>'weapon'},
pos=>{y=>'282',x=>'146'},
missedYou_last=>'2',
ai_attack_giveup=>{timeout=>'12',time=>'1473166839.02463'},
attackMainTimeout=>'1473166839.02599'
}
```
2: route

where
Prontera Field (prt_fild02) : (baseName: prt_fild02) : 146, 279

**Comment by itsrachelfish** [comment]
What value are you using for ```attackDistance``` in your control.txt?

**Comment by Jozoko** [comment]
am? i send log from ai print > maxDistance=>'2',distance=>'1', . Also trying some different. I think it will work good if i make distance - 0 - 0.9 But it's very bad solution.

Have not any attackskillslots, just weapon attack

**Comment by Cozzie** [comment]
Is this a fld problem cause openkore thinks that slot is a walkable one?

**Comment by c4c1n6kr3m1** [comment]
it's classic openkore problem , attacking Immovable monster

**Comment by deezar** [comment]
Can confirm this is a common problem. 
Try setting `attackCheckLOS 1` (likely not help though).
Or make a simple macro checking position every X seconds if it stays the same then teleport.

**Comment by itsrachelfish** [comment]
I reviewed [the source code](https://github.com/OpenKore/openkore/blob/cda86a7a20f73455dae37ef9f8e223d85a640435/src/AI/Attack.pm#L394) for ```attackCheckLOS``` and it seems like whoever wrote it was under the assumption that any attacks 2 or less cells away will always succeed.

It might be possible to fix this bug by simply removing the distance check on that line. I'd recommend trying that and letting us know if it works.

**Comment by Jozoko** [comment]
I'll try, thx

**Comment by Jozoko** [comment]
i check source here is one more condition **OR**
(!$config{attackCanSnipe} && $realMonsterDist <= $args->{attackMethod}{maxDistance} && !checkLineWalkable($realMyPos, $realMonsterPos, 1)))
so i dont think what we need to delete attack distance

**Comment by Jozoko** [comment]
```
[Sep 15 05:00:10 2016.73] Target distance 2.0 is >1; moving to target: from (108,112) to (108,111)
[Sep 15 05:00:10 2016.74] You on route to: (): 108, 111
[Sep 15 05:00:10 2016.74] Route You Solution Ready!
[Sep 15 05:00:10 2016.74] Route You - next step moving to (108, 112), index 1, 2 steps left
[Sep 15 05:00:10 2016.74] Move You - (re)trying
[Sep 15 05:00:10 2016.74] Sent move to: 108, 112
[Sep 15 05:00:10 2016.76] Received packet: 01F3 Handler: misc_effect
[Sep 15 05:00:10 2016.77] Received packet: 01F3 Handler: misc_effect
[Sep 15 05:00:10 2016.91] Received packet: 01F3 Handler: misc_effect
[Sep 15 05:00:10 2016.96] Received packet: 0087 Handler: character_moves
[Sep 15 05:00:10 2016.96] You're moving from (108, 112) to (108, 112) - distance 0.0
[Sep 15 05:00:10 2016.96] Move You - done
[Sep 15 05:00:10 2016.97] Route You - trimming down solution (2) by 2 steps
[Sep 15 05:00:10 2016.97] You reached the destination.
[Sep 15 05:00:10 2016.97] Target distance 2.0 is >1; moving to target: from (108,112) to (108,111)
[Sep 15 05:00:10 2016.97] You on route to: (): 108, 111
[Sep 15 05:00:10 2016.98] Route You Solution Ready!
```
Bot trying to step in unwalkable cell and looping

**Comment by denucles** [comment]
up

**Comment by alisonrag** [comment]
dplicated issue:
#1687
