### ISSUE TITLE
packet DC

### ISSUE THREAD

**Issue by AncientEgyptSoul** [OpenKore/openkore#2193]
###### Affected configuration(s)/ file(s): 
server : 76 61 6c 68 61 6c 6c 61 20 2d 20 69 6e 64 6f 6e 65 73 69 61
```Include relevant code snippets and source code references```
packet before dc
![capture](https://user-images.githubusercontent.com/21959952/43251765-012cdd52-90eb-11e8-9b6e-0f33d23c3096.PNG)
packet that make it dc
![capture2](https://user-images.githubusercontent.com/21959952/43251810-1dcd0cb6-90eb-11e8-98d2-0931a3e9de59.PNG)

###### Steps to Reproduce:
fixing receive or send packet (maybe)??

**Comment by alisonrag** [comment]
server?

**Comment by AncientEgyptSoul** [comment]
server : i already mention it above
plugin : no
packet captured with wireshark

**Comment by alisonrag** [comment]
can you set this in config and send the openkore console text?
```
debug 0
debugPacket_unparsed 1
debugPacket_received 2
debugPacket_ro_sent 0
debugPacket_sent 2
```

**Comment by AncientEgyptSoul** [comment]
<< Received packet:      009A - Special Message [111 bytes]   Jul 26 19:57:13 2018
  0>  9A 00 6F 00 4E 6F 2E 33    20 4C 61 70 6F 72 61 6E    ..o.No.3 Laporan
 16>  20 6A 75 6D 6C 61 68 20    69 6E 76 65 73 74 61 73     jumlah investas
 32>  69 20 74 65 6C 61 68 20    6B 65 6C 75 61 72 2E 20    i telah keluar. 
 48>  4B 61 6D 75 20 64 61 70    61 74 20 6D 65 6C 69 68    Kamu dapat melih
 64>  61 74 6E 79 61 20 64 69    20 49 6E 76 65 73 74 6D    atnya di Investm
 80>  65 6E 74 20 53 74 61 74    75 73 20 42 6F 61 72 64    ent Status Board
 96>  20 70 61 64 61 20 6D 61    70 20 57 4F 45 2E 00        pada map WOE..
[Jul 26 19:57:13 2018.83] [S] No.3 Laporan jumlah investasi telah keluar. Kamu dapat melihatnya di Investment Status Board pada map WOE.
[Jul 26 19:57:13 2018.96] ================================================
>> Sent packet: 0885   [2 bytes]   Jul 26 19:57:13 2018
  0>  85 08                                                 ..
[Jul 26 19:57:14 2018.68] ================================================
>> Sent packet: 0367   [90 bytes]   Jul 26 19:57:14 2018
  0>  67 03 CE F3 00 00 00 00    00 00 00 00 00 00 00 00    g...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00 00 00 00 00 00    00 00                      ..........
[Jul 26 19:57:16 2018.69] ================================================
>> Sent packet: 0367   [90 bytes]   Jul 26 19:57:16 2018
  0>  67 03 CB F3 00 00 00 00    00 00 00 00 00 00 00 00    g...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00 00 00 00 00 00    00 00                      ..........
[Jul 26 19:57:18 2018.70] ================================================
>> Sent packet: 0367   [90 bytes]   Jul 26 19:57:18 2018
  0>  67 03 CD F3 00 00 00 00    00 00 00 00 00 00 00 00    g...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00 00 00 00 00 00    00 00                      ..........
[Jul 26 19:57:20 2018.71] ================================================
>> Sent packet: 0367   [90 bytes]   Jul 26 19:57:20 2018
  0>  67 03 CE F3 00 00 00 00    00 00 00 00 00 00 00 00    g...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00 00 00 00 00 00    00 00                      ..........
[Jul 26 19:57:22 2018.71] ================================================
>> Sent packet: 0367   [90 bytes]   Jul 26 19:57:22 2018
  0>  67 03 CB F3 00 00 00 00    00 00 00 00 00 00 00 00    g...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00 00 00 00 00 00    00 00                      ..........
[Jul 26 19:57:23 2018.84] ================================================
<< Received packet:      0187 - Request Sync Packet [6 bytes]   Jul 26 19:57:23 2018
  0>  87 01 84 26 05 00                                     ...&..
[Jul 26 19:57:24 2018.72] ================================================
>> Sent packet: 0367   [90 bytes]   Jul 26 19:57:24 2018
  0>  67 03 CD F3 00 00 00 00    00 00 00 00 00 00 00 00    g...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00 00 00 00 00 00    00 00                      ..........
[Jul 26 19:57:25 2018.97] ================================================
>> Sent packet: 0885   [2 bytes]   Jul 26 19:57:25 2018
  0>  85 08                                                 ..
[Jul 26 19:57:26 2018.74] ================================================
>> Sent packet: 0367   [90 bytes]   Jul 26 19:57:26 2018
  0>  67 03 CE F3 00 00 00 00    00 00 00 00 00 00 00 00    g...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00 00 00 00 00 00    00 00                      ..........
[Jul 26 19:57:28 2018.75] ================================================
>> Sent packet: 0367   [90 bytes]   Jul 26 19:57:28 2018
  0>  67 03 CB F3 00 00 00 00    00 00 00 00 00 00 00 00    g...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 80>  00 00 00 00 00 00 00 00    00 00                      ..........
[Jul 26 19:57:29 2018.95] Terputus dari Map Server,[Jul 26 19:57:29 2018.95] Melakukan koneksi ke Account Server dalam 41 detik...
[Jul 26 19:57:29 2018.95] ================================================
>> Sent packet: 018A  [Exit] [4 bytes]   Jul 26 19:57:29 2018
  0>  8A 01 00 00                                           ....
[Jul 26 19:57:29 2018.96] Mengakhiri koneksi (202.93.25.231:5000)...[Jul 26 19:57:29 2018.96] Telah disconnect
[Jul 26 19:57:33 2018.52] Keluar...
[Jul 26 19:57:33 2018.53] macro plugin unloading, [Jul 26 19:57:33 2018.53] cleaning up
[Jul 26 19:57:33 2018.53] map unloaded.
[Jul 26 19:57:33 2018.54] [raiseSkill] Plugin unloading or reloading
[Jul 26 19:57:33 2018.54] [raiseStat] Plugin unloading or reloading
[Jul 26 19:57:33 2018.55] xConf plugin reloading or unloading
[Jul 26 19:57:33 2018.55] *** OpenKore what-will-become-2.1 ( version ctime:2018_07_25 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

**Comment by alisonrag** [comment]
@AncientEgyptSoul 
please try delete the following file:
openkore\tables\yourserver\shuffle.txt

**Comment by sctnightcore** [comment]
@AncientEgyptSoul  You should tell your server.
Do not tell me to use hex to text for your server name.

**Comment by alisonrag** [comment]
@sctnightcore 
he is afraid because the company that host this server is watching this repository

**Comment by AncientEgyptSoul** [comment]
it's working good. case closed then :+1:  :laughing:
