### ISSUE TITLE
Connecting map server 

### ISSUE THREAD

**Issue by Bleu01** [OpenKore/openkore#2199]
good some solution? download the openkore of the github and follow the problem here an image that could be

https://ibb.co/kQfW8o link direct

i am noob

**Comment by sctnightcore** [comment]
packet key / servertype is wrong .

**Comment by Bleu01** [comment]
ip 167.114.155.103
port 6900
private 1
master_version 1
version 55
serverType kRO_RagexeRE_2017_06_14b
serverEncoding Western
addTableFolders translated/kRO_english;kRO
charBlockSize 155
any more?

**Comment by sctnightcore** [comment]
clientdate ? ?

**Comment by Bleu01** [comment]
2017-06-13

**Comment by Bleu01** [comment]
Slot 1: Judith (Novice, Girl, level 1/1, izludeTimeout on Map Server, connecting to Account Server...

now this

**Comment by sctnightcore** [comment]
upload only .exe to me .

**Comment by Bleu01** [comment]
[NewPatcher.zip](https://github.com/OpenKore/openkore/files/2237584/NewPatcher.zip)

**Comment by sctnightcore** [comment]
client.exe not patche :p

**Comment by Bleu01** [comment]
SORRY my error
[Server.zip](https://github.com/OpenKore/openkore/files/2237624/Server.zip)

**Comment by sctnightcore** [comment]
```
[fuckyou]
ip 167.114.155.103
port 6900
version 55
master_version 1
serverType kRO_RagexeRE_2017_06_14b
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2017_06_14b;translated;translated/kRO_english;kRO
pauseCharLogin 1
sendCryptKeys 0x5ED10A48,0x2E5D761F,0x667F4301
```

**Comment by Bleu01** [comment]
work tnx very very very tnx
