### ISSUE TITLE
please help me how to skip this antibot

### ISSUE THREAD

**Issue by cacad125** [OpenKore/openkore#2200]
![screenzoke ragnarok000](https://user-images.githubusercontent.com/41810909/43352304-e6d46db4-924b-11e8-9ca6-63ab73c92134.jpg)

first time i use opencore ✌️ 
please help me master

**Comment by Fadreus** [comment]
To skip this anti-bot just write the number you see.

**Comment by alisonrag** [comment]
sorry guy this is a place to report a openkore issue you can try forum.

by default the regular antibots have a limited number of answer you can try to save every option and make bot quit when dont have the answer
