### ISSUE TITLE
 slow hunter

### ISSUE THREAD

**Issue by Bleu01** [OpenKore/openkore#2202]
Some solution my bot is slow to attack the mob there are many but it does not attack fast the gold peco!

Is there something to attack the mob faster?

**Comment by Fadreus** [comment]
Use forum.
Github for reporting bugs.
Do some reading before posting.

**Comment by Bleu01** [comment]
Never respond in the forum

**Comment by Fadreus** [comment]
So, you post 2 times, around 3 days ago and someone replied to you and you said "Never"? That's exaggerate. You should work on news industry. They like people making a huge fuss over a small thing and call it "News".
