### ISSUE TITLE
Sever type for 2018_05_30b

### ISSUE THREAD

**Issue by AzarthMZintos** [OpenKore/openkore#2213]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page
 download new openkore - https://github.com/OpenKore/openkore/archive/master.zip
* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible
* Please use the issue template, please post infornations about the server and your configuration

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
Wait :p 

or u can make servertype for uself .

**Comment by AzarthMZintos** [comment]
if i know how i will

**Comment by sctnightcore** [comment]
It ez . check packet send from rA/Herc and add it to openkore .

**Comment by AzarthMZintos** [comment]
why the issue was close if still not there?
