### ISSUE TITLE
About different autospell on different monsters

### ISSUE THREAD

**Issue by easywolf** [OpenKore/openkore#2215]
Hi everyone, does anyone know how to set autospell on different monsters?
Here's my config:

autoSpell Lightening Bolt {
	monsters Siroma,Gazeti
}

autoSpell Fire Bolt {
	monsters Muscipular,Roween,Galion
}

useSelf_skill Hindsight {
	lvl 10
	whenStatusInactive Hindsight
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	timeout 10
}

I guess when you attack new monsters, bc status will still have Hindsight, so it didn't really work. 
Anyone know how to fix it?

**Comment by Fadreus** [comment]
Some retard are unable to cure.
You are the living proof.

Read the fucking wiki gaddammit..
And drill in your fucking head, **github only for bug report and feature request**.
If you need help with config, go forum or elswhere, not here.

**Comment by alisonrag** [comment]
openkore dont give support to autospell blocks, you can use only one

**Comment by Fadreus** [comment]
This isn't an issue to stay open.
More like asking rather than reporting.

**Comment by Nipodemos** [comment]
great work finding those unclosed issues 👏
