### ISSUE TITLE
can some help/teach me to PEEK this exe?

### ISSUE THREAD

**Issue by MingFaiYau** [OpenKore/openkore#2216]
Hi all,

I tried PEEK , Packet Extractor v3 and OpenKore Packet Length Extractor v1.1.0
All fail to get the recvpackets.txt
Can some one teach/help me? thanks a lot

Here are the client.exe

[Ragnarokf.exe.zip](https://github.com/OpenKore/openkore/files/2250080/Ragnarokf.exe.zip)

**Comment by sctnightcore** [comment]
clientdate?

**Comment by MingFaiYau** [comment]
I am using this setting now, but cant connect into map server.
testaccoun:

id: testman
pw: 1234qwer

[FRo]
ip 47.101.20.127
port 9001
private 1
master_version 4
version 1828841237
charBlockSize 144
serverType kRO_RagexeRE_2013_08_07a
serverEncoding Big5
addTableFolders translated/kRO_english;kRO
recvpackets recvpackets130806.txt

[recvpackets130806.txt](https://github.com/OpenKore/openkore/files/2250105/recvpackets130806.txt)

**Comment by AlexandreVitorino** [comment]
huuu use scylla hide to unpack it  (made by ntquery ... v0.97c)

**Comment by MingFaiYau** [comment]
@sctnightcore 
Thanks a lot, i will try to unpack it.

**Comment by sctnightcore** [comment]
test in winxp 32bit

**Comment by MingFaiYau** [comment]
@sctnightcore 
Dear sir,

Thank a lot , final i unpack it and got the recvpackets..

In 2013_08_07a.pm i add base no the recvpackets.txt
	$self->cryptKeys(0x370B8BE0, 0x0594FA7E, 0x05A3AA37);

it seems can connect to the map server..but ..have new problem..
is it mean..the server type is wrong?..
the client.exe is 20130806 but i dont find 0806 client in rathena.org.

Could you mind help again? thank a lot
![image](https://user-images.githubusercontent.com/28052105/43673866-7d82cffc-97fc-11e8-9eab-0a0c3f956326.png)



[recvpackets.txt](https://github.com/OpenKore/openkore/files/2259293/recvpackets.txt)
