### ISSUE TITLE
Mild Wind TK_SEVENWIND Usage base on current Target Element?

### ISSUE THREAD

**Issue by leeandreic** [OpenKore/openkore#2218]
I'm not sure if this feature has been implemented yet or not but currently I have to selectively add
monsters in Self Conditions -> Monsters based on the opposite element to achieve full Mild Wind automation.

Would there be a chance to have a logic where Kore takes current target property/element to consideration before casting Mild Wind?

This indirectly could affect different weapon switching as well but that's another topic.

**Comment by Nipodemos** [comment]
the only problem on this logic is to have a trustable database of all monsters of official servers

unfortunaly we don't have, and we can't trust on databases of rathena, hercules and others

but, if you want, already exist a plugin that let's you use the skill based on element of target, search for **enhancedCasting** on *needs-review* folder

**Comment by alisonrag** [comment]
we cant trust in any database, and add this logic to openkore will cause a several changes and a slow execution, so you have to add monster to useselfskill condition by yourself
