### ISSUE TITLE
Hunting board eventMacro

### ISSUE THREAD

**Issue by easywolf** [OpenKore/openkore#2221]
Hi everyone, I tried to put the eventMacros.txt with the hunting board code and somehow it didn't work.
Please let me know if there's any problems in code?

control/eventMacros.txt

automacro BoardQuest1 {
exclusive 1
priority 1
timeout 120
BaseLevel > 75
QuestActive [b]QuestID1[/b], [b]QuestID2[/b]
macro_delay 3
call {
    if (&questCompleteCount([b]QuestID1[/b]) == 1 && &questCompleteCount([b]QuestID2[/b]) == 1) call Quest1

    log Quest not Completed yet
    }
}

macro [b]Quest1[/b] {
log completed quest of [b]Quest1[/b]
do conf lockMap [b]mapID[/b]
lock BoardQuest1
}

###################################################################################################################

automacro BoardQuest2 {
exclusive 1
priority 2
timeout 120
BaseLevel > 75
QuestHuntCompleted [b]QuestID1 MobID1[/b], [b]QuestID2 MobID2[/b]
QuestActive [b]QuestID3[/b], [b]QuestID4[/b]
macro_delay 3
call {
    if (&questCompleteCount([b]QuestID3[/b]) == 1 && &questCompleteCount([b]QuestID4[/b]) == 1) call Quest2

    log Quest not Completed yet
    }
}

macro Quest2 {
log completed quest of [b]Quest2[/b]
do conf lockMap [b]mapID[/b]
lock BoardQuests2
}

###################################################################################################################

automacro BoardQuest3 {
exclusive 1
priority 3
timeout 120
BaseLevel > 75
QuestHuntCompleted [b]QuestID1[/b] MobID1, [b]QuestID2 MobID2[/b], [b]QuestID3[/b] MobID3, [b]QuestID4 MobID4[/b]
QuestActive [b]QuestID5[/b], [b]QuestID6[/b], [b]QuestID7[/b]
macro_delay 3
call {
    if (&questCompleteCount([b]QuestID5[/b]) == 1 && &questCompleteCount([b]QuestID6[/b]) == 1 && &questCompleteCount([b]QuestID7[/b]) == 1) call Quest3

    log Quest not Completed yet
    }
}

macro Quest3 {
log All quests completed!
do respawn
do move [b]mapID[/b] #(map where the hunting board is)
do talknpc [b]X Y[/b] [b]NPCResponseSequence[/b] #for example c c r1 c r17 n
do talknpc [b]X Y[/b] [b]NPCResponseSequence[/b]
... #and so on until you turned in all quests
do talknpc [b]X Y[/b] [b]NPCResponseSequence[/b] #this last line is to take all the quests again once turned in
do conf lockMap [b]mapID[/b] #should be the map the whole macro chain started in.
release all
do relog 3
}

----------------------------------------------------------------------------------------------------------
And here's the false report

[eventMacro] Ignoring automacro 'BoardQuest3'
[eventMacro] Error in condition 'QuestHuntCompleted'
[eventMacro] Error type: Wrong condition syntax ('[b]QuestID1[/b] MobID1, [b]QuestID2 MobID2[/b], [b]QuestID3[/b] MobID3, [b]QuestID4 MobID4[/b]')
[eventMacro] Error code: 'List member '[b]QuestID1[/b] MobID1' has an invalid quest ID '[b]QuestID1[/b]''.
[eventMacro] Ignoring automacro 'BoardQuest1'
[eventMacro] Error in condition 'QuestActive'
[eventMacro] Error type: Wrong condition syntax ('[b]QuestID1[/b], [b]QuestID2[/b]')
[eventMacro] Error code: 'List member '[b]QuestID1[/b]' must be a quest ID or a variable name'.
[eventMacro] Ignoring automacro 'BoardQuest2'
[eventMacro] Error in condition 'QuestHuntCompleted'
[eventMacro] Error type: Wrong condition syntax ('[b]QuestID1 MobID1[/b], [b]QuestID2 MobID2[/b]')
[eventMacro] Error code: 'List member '[b]QuestID1 MobID1[/b]' has an invalid quest ID '[b]QuestID1''.

**Comment by c4c1n6kr3m1** [comment]
http://openkore.com/index.php/EventMacro

read!!!!!!!!!!!!

**Comment by alisonrag** [comment]
you are just copying and pasting the eventmacro.

did you read what you are pasting?

you have to rewrite all QuestID with the Quest ID that you are wanting to do
