### ISSUE TITLE
xKore3 question

### ISSUE THREAD

**Issue by blackroseyun** [OpenKore/openkore#2225]
i have a question , when i play RO with xKore3 
sometimes my character would auto sit , even though i close config's auto sit setting
so i have create a marco , auto stand when I sit , but its not good , so how can i solve thie problem

**Comment by c4c1n6kr3m1** [comment]
sitAuto_idle
???

**Comment by blackroseyun** [comment]
this setting is 0
i have close all about sit's setting.

**Comment by Fadreus** [comment]
Delete all sitAuto, problem solved.
LOL

**Comment by Nipodemos** [comment]
first you need to know why he is sitting, maybe you can check AI sequence,  or some other config

**Comment by blackroseyun** [comment]
i have solve this problem , is other txt cause this question
most cause auto sit is about vs sura , when sura kick you , sometimes openkore would auto sit even though i stand and close sit setting

**Comment by AlexandreVitorino** [comment]
race condition ?

**Comment by blackroseyun** [comment]
i think so , so i modify timeouts.txt's  sit setting. then i solve this problem
