### ISSUE TITLE
Timeout on account server

### ISSUE THREAD

**Issue by yahj112** [OpenKore/openkore#2227]
pls help me . how to fix this ??

![1](https://user-images.githubusercontent.com/42144468/43718919-cc38f630-99be-11e8-9751-c61710ed7e1c.png)

ip 168.235.75.193
port 6900
master_version 14
version 45
serverType Zero
serverEncoding Korea
charBlockSize 140
addTableFolders kRO/Zero;kRO

server name is RageRO
Website http://playrage-ro.com/

**Comment by yahj112** [comment]
server name is RageRO
Website http://playrage-ro.com/

**Comment by sctnightcore** [comment]
go irc .

**Comment by yahj112** [comment]
what IRC ???

**Comment by alisonrag** [comment]
check the link in openkore description page

**Comment by alisonrag** [comment]
![image](https://user-images.githubusercontent.com/10372732/43724777-379137c4-9971-11e8-93ae-4e154a512b6e.png)
