### ISSUE TITLE
[tRO]now we've some problems to fix 

### ISSUE THREAD

**Issue by lianstohim** [OpenKore/openkore#223]
I want to know " how can we do or what ways we should do ; the charactor move 035F send, disconnect suddenly.  www.ro.exe.in.th 

https://mega.nz/#!8112XDJQ!x3P8Rz_lwWUlVRUr62qfUDXpM0RBUfT8HMzxzVPOrew

               help me plz If u want to see file u can tell me Thanks

**Comment by SuperBotTz** [comment]
i have x-0   thnksyou D:

**Comment by windhamwong** [comment]
Merge to #221 
Please use single thread.
