### ISSUE TITLE
【help】Unable to get the correct map server IP on cRO

### ISSUE THREAD

**Issue by waltermai** [OpenKore/openkore#2232]
thank you very much.

![1](https://user-images.githubusercontent.com/42194005/43830909-0bcc01da-9b35-11e8-86aa-ae3700ffefc1.png)

[XKore 2]
ip 118.89.42.108
port 6900
master_version 4
version 1
serverType cRO
serverEncoding GBK
charBlockSize 147
addTableFolders cRO
gameGuard 1
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
pinCode 1
charDeleteDateType 1
pauseCharLogin 1

**This is my op server.txt data.
Is it because my settings are wrong?I guess because... op is didn't get the IP of the MAP server？
at config.txt is set xkore type "3"****

**Comment by waltermai** [comment]
if(!$masterServer->{'private'}) {
 line 555			$mapInfo->{mapIP} = _inet_ntoa($mapInfo->{mapIP});
	       	} else {
			$mapInfo->{mapIP} = $masterServer->{ip};
		}

XKoreProxy.pm line 555

**Comment by sctnightcore** [comment]
download new openkore and test again .

**Comment by waltermai** [comment]
I try again.
but the problem still....
my step is here ...have wrong?
step1: download cRO Official client dump and modify clientinfo.xml of data.grf
step2: download OP and set master server kore 2 in config，set kore mode type "3"（is this xkore3?)
ste
step3:  edit server.txt copy cro server information to xkore2 server information.
step4: run op
step5: run game~~

I am not sure where the problem is...
Can you please guide me?

**Comment by waltermai** [comment]
if(!$masterServer->{'private'}) {
line 555	$mapInfo->{mapIP} = _inet_ntoa($mapInfo->{mapIP});
} else {
$mapInfo->{mapIP} = $masterServer->{ip};
}
XKoreProxy.pm

if I del this code..Can login the game. xkore looks like everything is ok..but,if I go to other maps Will drop the line..

**Comment by waltermai** [comment]
![12](https://user-images.githubusercontent.com/42194005/43842823-c0b0e91c-9b58-11e8-99db-e8797d666c85.png)
![13](https://user-images.githubusercontent.com/42194005/43842831-c4d854e4-9b58-11e8-9e5d-290248fb37f7.png)

**Comment by waltermai** [comment]
OpenKore version what-will-become-2.1
Network state = 4
Network handler = Network::XKoreProxy
Revision: ctime:2018_08_08
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Bad arg length for Socket::inet_ntoa, length is 20, should be 4 at src/Network/XKoreProxy.pm line 555.

Stack trace:
Bad arg length for Socket::inet_ntoa, length is 20, should be 4 at src/Network/XKoreProxy.pm line 555.
 at src/Network/XKoreProxy.pm line 554
	Network::XKoreProxy::modifyPacketIn('Network::XKoreProxy=HASH(0x4d63cac)', '\x{c5}\x{a}\x{cb}_\x{3}\x{0}pay_dun00.gat\x{0}\x{0}\x{0}\x{a}\x{87}>\x{a3}\x{1d}\'zone13.ro.zhaouc.com:10013\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}...') called at src/Network/XKoreProxy.pm line 210
	Network::XKoreProxy::clientSend('Network::XKoreProxy=HASH(0x4d63cac)', '\x{c5}\x{a}\x{cb}_\x{3}\x{0}pay_dun00.gat\x{0}\x{0}\x{0}\x{a}\x{87}>\x{a3}\x{1d}\'zone13.ro.zhaouc.com:10013\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}...') called at src/functions.pl line 752
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x3221ec4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136


  		if(!$masterServer->{'private'}) {
* 			$mapInfo->{mapIP} = inet_ntoa($mapInfo->{mapIP});
  		} else {

**Comment by alisonrag** [comment]
i will try t fix it this soon, the problem is because cRO use alias name address and not ip address.

**Comment by waltermai** [comment]
Thank you for your reply Alison Serafim..
I saw error log，also think that inet_aton returns the problem caused by the length of the domain name.
I sincerely hope help fix this，but because I don't know how to write code,QAQ~orz~~~
