### ISSUE TITLE
questions about poseidon servertype cRO1213a

### ISSUE THREAD

**Issue by waltermai** [OpenKore/openkore#2234]
login poseidon the npc say.
As you can see, I can't find a matching serverType for your server.
Please make a trial-and-error using all available serverTypes, one of them might be able to work.
Like I said, your server is not yet fully supported by Openkore.
You can login to the server and do most basic tasks, but you cannot attack, sit or stand, or use skills.

and the nProtect shutdown my game.

servertype is cRO1213a Is this expired？

**Comment by alisonrag** [comment]
you can try talk with some chinese people they can hel you i made wxactly that what i told to you and worked:
https://discord.gg/NbQsXf

**Comment by waltermai** [comment]
Thank you~
