### ISSUE TITLE
【report】xkore1 absolutely not work in cro.

### ISSUE THREAD

**Issue by waltermai** [OpenKore/openkore#2235]
![123](https://user-images.githubusercontent.com/42194005/43899468-9a7cc5b0-9c14-11e8-968e-3b5a87952dae.png)

and the xkore3 login the game，also will be shutdown in few min..

**Comment by alisonrag** [comment]
Xkore 1 inject dll, ganeguard block

**Comment by waltermai** [comment]
hello alisonrag.thanks Reply
but if I use xkore3 login the game，ganeguard also will be shutdown the Client in few min ..
Is there a way for CRO to use OP?
@alisonrag

**Comment by alisonrag** [comment]
a lot of peoples run cRO with poseidon.
need to use real ip in poseidon, gameguard can detect proxy to localhost

**Comment by alisonrag** [comment]
PC 1 = 
```
poseidon.pl
openkore.pl
```

PC 2 =
`Ragnarok Client`

--
PC 1 = 
```
poseidon.txt
ragnarokserver_ip=127.0.0.1
ragnarokserver_port=6900
queryserver_ip=127.0.0.1
queryserver_port=24390
server_type=cRO_2017-12-13a
CharBlockSize=147
debug=0
```


config.txt
```
poseidonServer 127.0.0.1
poseidonPort 24390
```


PC 2 =
clientinfo.xml inside data.grf
```
<port>6900</port>
<domain>REAL.IP.FROM.PC1:6900</domain>
```


C:\WINDOWS\System32\drivers\etc\hosts
`REAL.IP.FROM.PC1 poseidon.yiend.com`


start client by ragnarok.exe

**Comment by waltermai** [comment]
I try it~~~Thank you alisonrag.

**Comment by waltermai** [comment]
In PC2（VM） client  can't login poseidonRO.
like this ![111](https://user-images.githubusercontent.com/42194005/43918424-9f85c5d0-9c45-11e8-9b7d-b0e2cd1ffa0a.png)

but if run client in PC 1 login is ok. run client in pc 1 and set 127.0.0.1 can login poseidon but...gameguard will be shutdown it......

i don,t know what wrong~
orz....

**Comment by waltermai** [comment]
@alisonrag

**Comment by waltermai** [comment]
![123321321](https://user-images.githubusercontent.com/42194005/43921166-8f5de202-9c4d-11e8-8d34-ac0b77b74f9b.png)
![321321](https://user-images.githubusercontent.com/42194005/43921187-9c4221fe-9c4d-11e8-9d12-3edb90181d88.png)

**Comment by waltermai** [comment]
I have added real IP125.xx.xx.xx to the client's file modifications.
But the strange thing is that when I log in to Poseidon, I use the network software to detect the remote data direction of Ragexe. Is 192.168.1.59 (lan IP).
I even used another network line to connect. Still like this.
It can be connected.

**Comment by waltermai** [comment]
I think if queryserver_ip=192.168.1.59 ragexe will connection this ip..
even if the real ip inset clientinfo.xml.

**Comment by waltermai** [comment]
@alisonrag .......Could you please advise me, where the problem is?

**Comment by hubertyang88** [comment]
@waltermai are your op working? I have same problem , npguard allways shutdown client,any adivce？

**Comment by waltermai** [comment]
@alisonrag 
@hubertyang88 
I am very sure poseidon Unable to cheat cro...
