### ISSUE TITLE
timeout to map sever

### ISSUE THREAD

**Issue by babyfatz41** [OpenKore/openkore#2237]
Hi i need help

after iRO maintenance earlier i couldnt connect to openkore please help!!..

![image](https://user-images.githubusercontent.com/42262326/43941124-2a4c7fee-9c30-11e8-9df2-a34122b151be.png)

**Comment by Fadreus** [comment]
![10314591_806478259365240_4759021608493571750_n](https://user-images.githubusercontent.com/32188494/43942435-98de5976-9caa-11e8-8226-b0a6d652b093.jpg)
