### ISSUE TITLE
Unable to load non-default config file, conflict at macro.pl

### ISSUE THREAD

**Issue by Cozzie** [OpenKore/openkore#224]
```
root@ubuntu-512mb-sgp1-01:~/openkore# perl ./openkore.pl --config=control\config_c2.txt
*** OpenKore what-will-become-2.1 ( version ? ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

Loading all plugins...
Loading plugin plugins/macro/macro.pl...
Use of the encoding pragma is deprecated at plugins/macro/Macro/Parser.pm line 5.
Loading plugin plugins/profiles/profiles.pl...

```

**Comment by allanon** [comment]
I don't see any error here. Are you saying that openkore dies after the last line in your snippet? Is there an error?

**Comment by Cozzie** [comment]
@allanon Oh sorry, did not realize i did not paste the whole thing and yes it did fail. For some reason when I tried it today it did not. Think it is a edge case bug. I will close this and reopen again if there are issues.
