### ISSUE TITLE
macros stuck while using SL Skill on ground ( body relocation )

### ISSUE THREAD

**Issue by Vitale44** [OpenKore/openkore#2245]
https://zupimages.net/up/18/32/3bef.png
Hello , i had this problem for like 5 years now,  using the SL command in console / macros to Body relocation on the ground, makes the others macros unable to do anything while the red error message isnt showing up, wich is realy anoying, i have to wait 4 seconds before the message shows up, and be able to do something else. I got an error message saying "Nothing happened, but the bot succesfuly body relocate to the position, it must have something do to with the scripts, idk, maybe because its an instant cast ? idk
 any way to fix this ? Thanks ( i have the latest version of Openkore )

**Comment by Fadreus** [comment]
That 4 secs, maybe try this? Cut the time, not really fix. Default is 3. So, IDK..

src/Task/UseSkill.pm

```
use constant {
	DEFAULT_MAX_CAST_TRIES => 1,
	DEFAULT_CAST_TIMEOUT   => 1
```

**Comment by Vitale44** [comment]
Thanks , that solved the problem kinda :D

**Comment by Fadreus** [comment]
> Thanks , that solved the problem kinda :D

No more feedback from user and he claimed it to be solved (kindda).
Request closing. :no_mouth:
