### ISSUE TITLE
client crash when using xkore 1 (iRO)

### ISSUE THREAD

**Issue by newkore** [OpenKore/openkore#2246]
##Client Crashed on XKore 1

iRO Chaos

Client crashed

is xkore 1 still supported on iRO ? client crashed when i tried to open it when using xkore1
im currently using the latest openkore from repository

**Comment by Zexeta** [comment]
Xkore 1 and 2 are both causing client crashes on restart. I cant sort out what's causing it. I know for a fact bards using frost joke causes a crash. Otherwise it just randomly crashes.

**Comment by Fadreus** [comment]
Latest version working fine with XKore 1 in iRO Chaos.
Tested.
