### ISSUE TITLE
Need some help with Packet Extraction TRO.exe

### ISSUE THREAD

**Issue by omaka50** [OpenKore/openkore#226]
Can someone Help me to extract  recvpackets for this exe

http://www.mediafire.com/download/v3cwfslkv40jzk6/Ragexe.rar

I try many ways such as Ro Tool, Peek, Packet Extractor but still didn't work. my guess is I need to unpack exe or need to do something with protect exe but after I tried to download so many program it still didn't work so I come here looking for some help it can be some advice or if it complete recvpackets I'm going to thank you so much.

PS. Sorry for bad English.

**Comment by windhamwong** [comment]
Merge to #221 
The current packet extractor is not working, however, we have a new one. Please chat in one single thread please.
