### ISSUE TITLE
Kore got Dc when talk resp to npc ( gramps, teleporter, kafra etc..)

### ISSUE THREAD

**Issue by bunnyy00** [OpenKore/openkore#2265]
Hi all, do you guys know why my kore will auto dc when talking to npc? It can talk for the first time but when I try to type 'talk resp 0' , it will go dc.. And even got dc when I try to feed my homun
Thanks.

I did try to update the most recent src--task--talknpc.pm

**Comment by pointzero2** [comment]
have the same issue

**Comment by Fadreus** [comment]
Download new and test again.

**Comment by bunnyy00** [comment]
I have got this message then dc

We have waited for too long after we sent a response to the npc.
断开与地图服务器的连接, 重新连接帐号服务器在 37 秒后...

**Comment by Fadreus** [comment]
It's server, not openkore; if you talk about iRo that is.
Not like you give out the details, do you?

**Comment by bunnyy00** [comment]
![npcccc](https://user-images.githubusercontent.com/25070736/44250414-cdccad00-a226-11e8-8174-18997f46f29e.jpg)

**Comment by bunnyy00** [comment]
![npppc](https://user-images.githubusercontent.com/25070736/44250453-f81e6a80-a226-11e8-8008-e456bc06dba9.jpg)

**Comment by bunnyy00** [comment]
yes it's iRO renewal chaos

**Comment by bunnyy00** [comment]
@Fadreus yes sorry i have forgotten all about the details.
Server: Iro renewal chaos
can's even feed homun

**Comment by bunnyy00** [comment]
ok I will try again now

**Comment by bunnyy00** [comment]
@Fadreus  ermmm...just downloaded the latest again and update the latest again, seemed no problem at all, please close this topic, my bad >.<
