### ISSUE TITLE
Timeout on Map Server, connecting to Account Server

### ISSUE THREAD

**Issue by jeffridelacruz** [OpenKore/openkore#2266]
After last maintenance patch, cannot connect to map Server.

MAP IP: 128.241.92.130
MAP Port: 4506
-----------------------------
Closing connection to Character Server
Disconnecting (128.241.92.130:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.130:4506)... connected
Timeout on Map Server, connecting to Account Server...
Connecting to Account Server...
[reconnect] Login retry number 3, setting reconnect timeout to 139 seconds.
Connecting (128.241.92.162:6800)... connected
Timeout on Account Server, reconnecting. Wait 139 seconds...

**Comment by Fadreus** [comment]
For fuck sake, check exist thread dammit.

**Comment by jeffridelacruz** [comment]
What for fuck sake? This is happening almost every time iRo patches after maintenance. And what exist thread? Would you mind sharing the "EXIST THREAD"?

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/44273044-f37ea400-a270-11e8-89fe-84d456b9b10d.png)
