### ISSUE TITLE
Openkore Wiki down?

### ISSUE THREAD

**Issue by Zelecktor** [OpenKore/openkore#2279]
As the title, the oficial page is offline.

http://openkore.com/

**Comment by Nipodemos** [comment]
now is working :smile:

**Comment by Zelecktor** [comment]
![captura](https://user-images.githubusercontent.com/19712343/44319688-c6b6c200-a413-11e8-8b14-7e249956934c.PNG)

and my cellphone 
![whatsapp image 2018-08-20 at 00 56 40](https://user-images.githubusercontent.com/19712343/44319728-02ea2280-a414-11e8-98ec-8fdfd1703d3c.jpeg)

**Comment by Fadreus** [comment]
@Nipodemos Brazil online, English nope.

**Comment by Fadreus** [comment]
@Nipodemos Brazil online, English nope.
Tag @isieo

**Comment by Fadreus** [comment]
Both Forum & Wiki is now online..

**Comment by alisonrag** [comment]
![image](https://user-images.githubusercontent.com/10372732/44472721-1c05f580-a605-11e8-9aa5-865e9a30f7ea.png)
