### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by AsakuraTK** [OpenKore/openkore#228]
Hello, I have problem.
My client [tRo] is connected to poseidon server (show in poseidon) but cannot login server.
I think ServerType.txt and RagnarokServer.pm not match with current client. How to find it?

Packet for tRo
'0A76' => ['master_login', 'V Z24 Z24 C', [qw(version username password master_version)]],
'0276' => ['account_server_info', 'x2 a4 a4 a4 x30 C1 x4 a*', [qw(sessionID accountID sessionID2 accountSex serverInfo)]],
'0275' => ['game_login', 'a4 a4 a4 v C x16 v', [qw(accountID sessionID sessionID2 userLevel accountSex iAccountSID)]],
'0436' => ['map_login', 'a4 a4 a4 V C', [qw(accountID charID sessionID tick sex)]],
$self->cryptKeys(0x4d8e77b2, 0x6e7b6757, 0x46ae0414);

Old ServerType.txt
[tRO_2013-07-09a]
decrypt_mid 1
decrypt_mid_keys 0x6441767a 0x71020102 0x48c21f02 # K A M
charBlockSize 144
![poseidon](https://cloud.githubusercontent.com/assets/20513397/18508048/d3aed788-7a9c-11e6-9469-f01eef758f28.jpg)

Sorry I'm bad English.

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
