### ISSUE TITLE
Skill delay time problem

### ISSUE THREAD

**Issue by ikkk5000** [OpenKore/openkore#2280]
This server have not skill delay time, So player can use skill quickly by manual operation.
But OpenKore have skill delay time about 1s~2s.
I try to modify control\timeouts.txt, but it's not work.

ai_attack 0.1
ai_attack_waitAfterKill 0.1
ai_skill_use 0.1

I think that modifying the code at src/ XX.pm is an effective method.
Can someone help me?
Thank you.

**Comment by AlexandreIV** [comment]
https://github.com/OpenKore/openkore/issues/2245

**Comment by ikkk5000** [comment]
Thank you for your answer.
I try it, but its not work.
I upload the video. Please help me. Thank you.

Video:

OpenKore
https://youtu.be/dD93JY_eMWc

Manual operation
https://youtu.be/C_T-7JWSQUI

**Comment by AlexandreIV** [comment]
You can try use the block monsterSkill with the timeout set on 0.1 ! ^^ ??

**Comment by ikkk5000** [comment]
Where is monsterSkill condition??

**Comment by AlexandreIV** [comment]
I dunno if it will work but you can set something such as : 

```
monsterSkill Aspersio {
timeout 0.1
monsters Petite
}
```

**Comment by ikkk5000** [comment]
Where add this code?
macros.txt?

**Comment by Nipodemos** [comment]
@ikkk5000 config.txt

**Comment by lututui** [comment]
sleepTime is definitely involved

**Comment by alisonrag** [comment]
using the following configuration i was able to use the skill more faster then using the manual:

config.txt:
```
attackUseWeapon 0
sleepTime 1000

attackSkillSlot Adoramus {
	lvl 10
	dist 1.5
	maxCastTime 0.1
	minCastTime 0.1
	hp
	sp > 10
	onAction
	whenStatusActive
	whenStatusInactive EFST_POSTDELAY
	stopWhenHit 0
	inLockOnly 0
	notInTown 0
	timeout 0
	disabled 0
	maxAttempts 0
	maxUses 0
	inInventory
	isSelfSkill 0
	manualAI 0
}
```

timeouts.txt:
```
ai_skill_use 0.1
```

video:
https://youtu.be/Fw0hgDn4HFw
