### ISSUE TITLE
Stucked at connecting to map server.

### ISSUE THREAD

**Issue by xqwerty1** [OpenKore/openkore#2283]
Hello!
i just want to ask for help, im stucked on connecting to map server then dc.

https://imgur.com/a/8NQeej4

server info i got using wpe

[HERO]
ip 66.150.188.145
port 6907
master_version 14
version 55
serverType kRO_RagexeRE_2016_03_02b
serverEncoding Western
addTableFolders bRO
charBlockSize 147
sendCryptKeys 0x4C17382A, 0x7ED174C9, 0x29961E4F

link for the server~ http://heroes.ro-game.net/

**Comment by lututui** [comment]
You really shouldn't be using bRO's recvpackets

**Comment by xqwerty1** [comment]
actually, i got recvpackets using PEEK, idk why i pasted it on bro folder, my bad.

**Comment by xqwerty1** [comment]
still cant connect, also tried to make and use a different folder w/o those and not working either

**Comment by AlexandreIV** [comment]
0x4C17382A, 0x29961E4F, 0x7ED174C9

Try on this order.

**Comment by alisonrag** [comment]
```
[HERO]
ip 66.150.188.145
port 6907
master_version 14
version 55
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO
charBlockSize 147
private 1
gameGuard 0
```
working with this, but openkore dont have suport to custom maps if you can extract from grf you can use this guide 
http://openkore.com/index.php/FLD_Creation_Guide

**Comment by xqwerty1** [comment]
The bot is working now, thanks to you!. My problem now is whenever i extract and add the fields like you said, npcs and players cant detect by the bot aka if i type pl (player list) it says "There are no players near you" even if there is, same as nl (npc list).
