### ISSUE TITLE
Re:start, Xkore 2 = wrong gender/sprite errors

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#2296]
Title says it all, when loading into a female character on restart with xkore 2 it shows as a male. I would like to fix this if a GM were to ask me to take a screenshot.

The other problem is sprite errors with xkore 2.  I think they are pulling something with invisible NPCs to crash bots.  When my bot goes into certain maps the client crashes saying a novice or thief sprite is missing and this is in biolabs where obviously neither of these things are around.  I confirmed with a normal client that there aren't people of these classes there when it occurs either.  

I think it's a way to screw with bots because when i was watching one of my bots in another area there was a weird NPC in the middle of the field that had a 99 aura around it and it's not normally there.  Anyone else encounter this?

**Comment by sctnightcore** [comment]
**Please use the issue template, please post information about the server and your configuration.**

**Comment by Zexeta** [comment]
There is nothing to put in the template.  I said the server and the issue.  I am using the newest bot, i didn't mess with any files aside from putting my login information.  It works fine with male chars but shows females(aside from dancers) as males.  I assume its a server type or char block size issue?

**Comment by Zexeta** [comment]
I updated the original post with a 2nd problem.

**Comment by Fadreus** [comment]
@Zexeta Template can go like this:

## ------------------ Openkore Issues Template ------------------








* **Openkore version git**: -Openkore date-

* **Server**: iRO Re:Start

* **Bug Report / Feature Request**: Sprite Error in XKore 2

* **Summary**: Female sprite show as male


People here don't have much time to read long love letter.
Keep it short, compact & detailed.

**Comment by alisonrag** [comment]
Try #2291

**Comment by Zexeta** [comment]
I tested and it works alisonrag, thank you :)
