### ISSUE TITLE
Xkore 2 = Urgent Recall not usable?

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#2297]
------------------ Openkore Issues Template ------------------
Openkore version git: Newest
Server: iRO Re:Start
Bug Report / Feature Request: Urgent Recall can't be used in xkore2
Summary: The guild abilities do not show at all while in xkore2 and since you can't put the spell on your bars you're unable to use it.  It doesn't show up skills list either so i am at a loss as how to use it short of directly sending the packet which would stop working each week :(

**Comment by Fadreus** [comment]
> The guild abilities do not show at all while in xkore2 and since you can't put the spell on your bars you're unable to use it. It doesn't show up skills list either

![image](https://user-images.githubusercontent.com/32188494/44624312-3994d100-a91d-11e8-9057-9316485e0596.png)

![image](https://user-images.githubusercontent.com/32188494/44624321-7c56a900-a91d-11e8-8f6f-7bfe4acd651e.png)

**Comment by alisonrag** [comment]
is not usable in client, unfortunely xkore 2 is outdated and not send everything,

you can use xkore 3

**Comment by Zexeta** [comment]
Ahh I see. I'm kind of weary about using 3 because of these weird sprite traps the gms seem to be setting. If it crashes your client with 3 you disconnect and it's obvious you're a bot.

**Comment by c4c1n6kr3m1** [comment]
xKore 2 bound to xKore 0
if u can not see the skill on xKore 0 than you would not see it on xKore 2
about the weird char with aura and ruwach, r u sure it happen on xKore 3 too ?
i don't know what cause it

**Comment by Zexeta** [comment]
I'm not sure what causes it either. I don't feel like getting banned if it disconnects every single time it loads into certain maps though. I definitely think it's some sort of bot trap though. For days it happened everytime the bots took the warp to biolabs 1. Then it switched to biolabs 2 for days and now it hasn't been happening at all. I'm tempted to just paste those sprite files where it's saying they are missing from n see what happens.

**Comment by Zexeta** [comment]
Well i tried to use xkore 3 and it isn't able to connect?  Anyone able to use it on re:Start?

**Comment by c4c1n6kr3m1** [comment]
https://github.com/OpenKore/openkore/pull/2304 
quick test , works fine with xkore3 on odin

**Comment by c4c1n6kr3m1** [comment]
about the weird aura and ruwach novice char
my prediction is, if it only happen on xkore2, may be xkore 2 make wrong data
when first login , bot try to mimic the condition around, including player, npc ,monster ,item
so, try login with xkore 2, while you are lonely
i wonder if this is only happen on iRO

**Comment by Fadreus** [comment]
iRO Restart is dead.
Closing? :thinking:
