### ISSUE TITLE
Time out on map server, connecting to account server. Please Help !

### ISSUE THREAD

**Issue by lonto08** [OpenKore/openkore#2300]
# http://fury-ro.com/
[Fury Ragnarok Online]
ip 66.150.188.171
port 6900
private 1
master_version 1
version 55
recvpackets recvpackets_20151104.txt
serverType kRO_RagexeRE_2015_11_04a
serverEncoding euc-kr
charBlockSize 147
pinCode 1
addTableFolders pserver/ggRO
clientHash DA4E4A35A46BF326C9C45C653979972A
sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9

please help ! thanks !

**Comment by alisonrag** [comment]
tested and working:
```
[FuryRO]
ip 66.150.188.171
port 6900
master_version 0
version 55
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO
charBlockSize 147
sendCryptKeys 0x79B4CCA3, 0x4FF250D1, 0x2EBB5705
private 1
gameGuard 0
```

here is a place to post issues, you can ask for help in forum

**Comment by lonto08** [comment]
Wow thanks ! it worked ! thanks alisonrag !

**Comment by lonto08** [comment]
@alisonrag 
Please Help ! Not detecting my characters XD

**Comment by sctnightcore** [comment]
check clientdate :p

**Comment by lonto08** [comment]
![image](https://user-images.githubusercontent.com/42707814/44795855-8caa9600-ab60-11e8-9a6a-03bed2faedf1.png)

I tried the neares 2015 but still cant detect character heheh, Am my missing something?

[FuryRO]
ip 66.150.188.171
port 6900
master_version 0
version 55
serverType kRO_RagexeRE_2015_12_30a
serverEncoding Western
addTableFolders kRO/RagexeRE_2015_12_30a;translated;translated/kRO_english;kRO
charBlockSize 147
sendCryptKeys 0x79B4CCA3, 0x4FF250D1, 0x2EBB5705
private 1
gameGuard 0

**Comment by lonto08** [comment]
https://github.com/OpenKore/openkore/issues/2300#issuecomment-416012177

Not working on new openkore :(

**Comment by lonto08** [comment]
<clientinfo>
	<desc>Modified High Rate Server</desc>
	<servicetype>korea</servicetype>
	<servertype>primary</servertype>
	<connection>
		<display>Fury Ragnarok Online</display>
      		<address>66.150.188.171</address>
      		<port>6900</port>
      		<version>55</version>
      		<langtype>0</langtype>
      		<aid>
      		<admin>2000000</admin>
			<admin>2000001</admin>
			<admin>2000002</admin>
			<admin>2000004</admin>
			<admin>2000005</admin>
			<admin>2000009</admin>
      		</aid>
		<loading>
			<image>loading00.jpg</image>
			<image>loading01.jpg</image>
			<image>loading02.jpg</image>
			<image>loading03.jpg</image>
			<image>loading04.jpg</image>
			<image>loading05.jpg</image>
			<image>loading06.jpg</image>
		</loading>
   	</connection>
</clientinfo>
?F

**Comment by alisonrag** [comment]
@lonto08 
use #2312
