### ISSUE TITLE
IdRO server

### ISSUE THREAD

**Issue by RaynV** [OpenKore/openkore#2306]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

First, After new update. sometimes bot can't recognize entity packet such as buff, status, and etc.
![image](https://user-images.githubusercontent.com/25734089/44642514-20fce780-a9ff-11e8-9f02-af00efdbfc16.png)
for example walking character packet.
before update 0914 changed to 09DB and the size of packet is different from older version

Second, can you make thor server botable just like renewal? Most people already know how to bot there but they didn't want to share.

**Comment by sctnightcore** [comment]
src\Network\Receive\idRO.pm

del

```
		actor_exists 0915
		actor_connected 090F
		actor_moved 0914
```
not sure work :p
