### ISSUE TITLE
Chat Room title appear incorrectly.

### ISSUE THREAD

**Issue by Fadreus** [OpenKore/openkore#2313]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: https://github.com/OpenKore/openkore/commit/3bce1df373e7b6be4d2b0e2bceea4c2d49d906f2

* **Server**: iRO Chaos - Renewal

* **Bug Report / Feature Request**: Bug Report

* **Summary**: Chat room title missing 2 characters when the title using more than 2 while title using less than 2 characters will result to disconnect; as reported [here](http://forums.openkore.com/viewtopic.php?f=16&t=212765) by @gooey

**Comment by alisonrag** [comment]
missing len here:
https://github.com/OpenKore/openkore/blob/3bce1df373e7b6be4d2b0e2bceea4c2d49d906f2/src/Network/Send/ServerType0.pm#L77

**Comment by lututui** [comment]
Oops

**Comment by Fadreus** [comment]
In addition to this, command `chat modify` now not working.

**Comment by Fadreus** [comment]
Poke @alisonrag @lututui

**Comment by lututui** [comment]
@Fadreus does #2329 work?

**Comment by Fadreus** [comment]
Now that working just fine :grin:
