### ISSUE TITLE
kame_house waypoint error

### ISSUE THREAD

**Issue by kamirie** [OpenKore/openkore#2316]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
 Latest download from github
* **Server**: 
 Private server vanRO
* **Bug Report / Feature Request**: Assistance for map waypoint

* **Summary**:

I would like to request some help regarding map waypoint. Is kame_house already part of the existing fld filed? Because I cannot extract the field to make a new field file, grftool is haveing an error getting the .gat file grom grf. Whenever I tried to go to the map , it's always cannot calculate route and if i move manually I have this errors.
`Removed actor with off map coordinates : (113,83)->(113,83), field max :(0,0)

Removed actor with off map coordinates : (94,82)->(94,82), field max :(0,0)

Removed actor with off map coordinates : (96,82)->(96,82), field max `:(0,0)`
`

**Comment by sctnightcore** [comment]
xkore 0 ?

**Comment by alisonrag** [comment]
this is a custom map FuryRO and HeroeRO seems to have the same owner.

data.grf have password

**Comment by kamirie** [comment]
both xkore 0 and 3, I tried both . Probably the grf is encrypted as when I try to extract the fields I cannot get the exact .gat file. So there's no solution for this?

**Comment by sctnightcore** [comment]
No way to fix for encrypted grf.
