### ISSUE TITLE
Undetectable npc/players after extracting and creating custom maps fld

### ISSUE THREAD

**Issue by xqwerty1** [OpenKore/openkore#2317]
server config

www.heroes.ro-game.net

[HERO]
ip 66.150.188.145
port 6907
master_version 14
version 55
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO
charBlockSize 147
private 1
gameGuard 0

So i got a working bot that can see npc and players, but whenever i extract and create an fld file after following instructions from http://openkore.com/index.php/FLD_Creation_Guide the bot cant detect both npc/players with nl and pl console command.

**Comment by c4c1n6kr3m1** [comment]
you need to list the map name on maps.txt
or may the fld is broken?

**Comment by sctnightcore** [comment]
Please use the issue template, please post information about the server and your configuration.

**Comment by xqwerty1** [comment]
@sctnightcore updated post.

Altho i dont think there's something wrong about the servers.txt but the way i get files from extracting. 

This is the result i get whenever i open the grf
![image](https://user-images.githubusercontent.com/42544172/44856323-b28a8480-ac9f-11e8-8072-c4d10fb0d7c9.png)

And this is when i try to extract all; you can see that i get 0kb files
![image](https://user-images.githubusercontent.com/42544172/44856353-c6ce8180-ac9f-11e8-8d37-0518811b1651.png)

When i try to extract just 1 file
![image](https://user-images.githubusercontent.com/42544172/44856375-d221ad00-ac9f-11e8-8b84-d9d42ecabba9.png)

i think the files are somehow protected or idk

**Comment by sctnightcore** [comment]
try it 
https://rathena.org/board/files/file/2766-grf-editor/

**Comment by sctnightcore** [comment]
yep . 
GG
