### ISSUE TITLE
Help Timeout on map server (private server)

### ISSUE THREAD

**Issue by eraniichan** [OpenKore/openkore#2318]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: Latest

* **Bug Report / Feature Request**:

* **Summary**:

I am trying to bot in a private server named Fury RO
http://fury-ro.com

[Fury RO]
ip 66.150.188.171
private 1
port 6900
version 0
master_version 55
serverType kRO_RagexeRE_2015_10_29a
serverEncoding Western
charBlockSize 147
addTableFolders eA;translated/kRO_english;kRO
recvpackets recvpackets.txt
sendCryptKeys 0x79B4CCA3,0x2EBB5705,0x4FF250D1

I've managed to connect until character server, but on the map server it timeouts.
How am I sure for the cryptkeys? I tried using those into diffing a new client and it works, I got to play my diffed client.
Please help, as I've tried numerous solutions and still I can't make a workaround :(

**Comment by sctnightcore** [comment]
try
```
[Fury RO]
ip 66.150.188.171
private 1
port 6900
version 0
master_version 55
serverType kRO_RagexeRE_2015_10_29a
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2015_10_29a;translated;translated/kRO_english;kRO
#sendCryptKeys 0x79B4CCA3,0x2EBB5705,0x4FF250D1
```

**Comment by sctnightcore** [comment]
#sendCryptKeys 0x79B4CCA3,0x2EBB5705,0x4FF250D1
to
sendCryptKeys 0x79B4CCA3,0x4FF250D1,0x2EBB5705

**Comment by alisonrag** [comment]
[HERO]
ip 66.150.188.145
port 6907
master_version 14
version 55
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO
charBlockSize 147
private 1
gameGuard 0

**Comment by alisonrag** [comment]
[FuryRO]
ip 66.150.188.171
port 6900
master_version 0
version 55
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO
charBlockSize 147
sendCryptKeys 0x79B4CCA3, 0x4FF250D1, 0x2EBB5705
private 1
gameGuard 0

**Comment by alisonrag** [comment]
This server was already in issues and the custom maps is not supported
