### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Manoft** [OpenKore/openkore#232]
From we improved openkore by use Digest::HMAC_MD5 qw(hmac_md5) on yesterday.
Today 15/09/2016 my server update somthing that openkore can login in to map but not action anything and just second was disconnected.

we many thank for who support on yesterday and we hope to help us again in today for Big Thread.

**Comment by Poonjaroen** [comment]
Same issues like me.

**Comment by mastersood** [comment]
Were removed from the server. Like Tuesday

**Comment by johnshaorai** [comment]
exe always has a plan

**Comment by moononza112** [comment]
Same issues like me  removed from server update 15/9/2016

**Comment by odysseypeemai** [comment]
same issues

**Comment by tarkungZ** [comment]
We are all having the same issues brother

**Comment by RobotTZ** [comment]
Same issues

**Comment by kenjiza** [comment]
Same issues

**Comment by Manoft** [comment]
55555555 love your guy. we will walk together

**Comment by topgamemun** [comment]
Same issues

**Comment by TanasanJJ7** [comment]
hmac code missing from send.pm

The newly added Then open openkore will close automatically.

**Comment by rabbitgreen** [comment]
sameee issues.. please help :)

**Comment by tonblur** [comment]
Same issues please help

**Comment by iinfernoz** [comment]
I want to know how to get the key. Please Help Thank you.

**Comment by blackstep** [comment]
Same issues please help

**Comment by ballzas** [comment]
Can u teach me,Pls. I want to know solution to find KEY , Please

**Comment by Gamingzeen** [comment]
if you use any xkore mode, you can simply trim packets from client (excluding map_login) like this:
substr($msg, 2, length($msg) - 2 - 24)
then modify as above before sending to server.

**Comment by patjung555** [comment]
@Gamingzeen  thx for this guide

**Comment by ballzas** [comment]
@patjung555 Pls, Can u teach me. Thank

**Comment by lauksanaza** [comment]
sorry teach me more plz @Gamingzeen

**Comment by rabbitgreen** [comment]
@Gamingzeen  Thank for the advice but can u teach us .. ? please ...

**Comment by minimax1** [comment]
@patjung555 can u teach me for gen the key plz? thank

**Comment by odysseypeemai** [comment]
@patjung555 can u teach me for gen the key plz? thank

**Comment by Manoft** [comment]
Pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee :)

**Comment by modimo31** [comment]
@patjung555  Please teach me plz plz

**Comment by Dalk2ness** [comment]
new packet format, after hmac is:
length(2 bytes) + original packet(whole old format packet) + flag(always 1, 4 bytes) + sequence(increase by one starting from 0, 4 bytes) + hmac(16 bytes).
my code generate new format packets from old ones. for xkore, you need to extract the original packet from client to server and recalculate other things(because sequence is changed, which is also included in hmac calculation).

Credit by unknown-item

**Comment by tequiliewqzz699** [comment]
new packet format, after hmac is:
length(2 bytes) + original packet(whole old format packet) + flag(always 1, 4 bytes) + sequence(increase by one starting from 0, 4 bytes) + hmac(16 bytes).
my code generate new format packets from old ones. for xkore, you need to extract the original packet from client to server and recalculate other things(because sequence is changed, which is also included in hmac calculation).

Credit by unknown-item  ?????????????????????????????

**Comment by lordslegolas** [comment]
@Dalk2ness It for today problem?

**Comment by jnuujnuu** [comment]
@Dalk2ness Please, What is tools for extract a client? 
sorry I'm noob.

**Comment by bird5523** [comment]
need to debug a running game client with EAC code injected to find this key

**Comment by ninenite** [comment]
@bird5523  with program ?

**Comment by returnerza** [comment]
@bird5523 you have programs to debug and find this key ?
what is programs ? and how to unpack the client ?

**Comment by tobmusicroom** [comment]
original packet + flag + sequence + hmac

**Comment by returnerza** [comment]
@tobmusicroom  how to ??

**Comment by danmadoon** [comment]
packet: 001C 

How to fix it plss.....

**Comment by windhamwong** [comment]
Guys, it is pointless to just say, "Same Issue" in here. I am here to fix it but I do need time to work on it. In the meanwhile, please response to a single issue thread please.

**Comment by cansupermuay** [comment]
ok w8

**Comment by nitat1175** [comment]
@cansupermuay 
Can you tech me how to find hmac_md5's pack ?

**Comment by scream1ng** [comment]
@nitat1175 do you know any assembly language?

**Comment by nitat1175** [comment]
@scream1ng Bat C# 
is it can help for this ?

**Comment by minimax1** [comment]
@windhamwong  we waiting you sir! :D

**Comment by cansupermuay** [comment]
@scream1ng  i can't find it.

**Comment by Manoft** [comment]
Can you tell about edit?

I'm newbie for kore.

**Comment by vidkung** [comment]
Hey guy hashcat program can crack Key form HMAC 
Please help me 
How to find Plaintext and HMAC Packet 


https://hashcat.net/hashcat/

**Comment by returnerza** [comment]
@vidkung It not work i'm test it.

**Comment by returnerza** [comment]
@vidkung  i'm see msg by unknown-item

"new packet format, after hmac is:
length(2 bytes) + original packet(whole old format packet) + flag(always 1, 4 bytes) + sequence(increase by one starting from 0, 4 bytes) + hmac(16 bytes).
my code generate new format packets from old ones. for xkore, you need to extract the original packet from client to server and recalculate other things(because sequence is changed, which is also included in hmac calculation)."

and re test for find hmac_md5 = now how to find packet ?

**Comment by thitiboy** [comment]
@tobmusicroom 
original packet(whole old format packet) + flag(always 1, 4 bytes) + sequence(increase by one starting from 0, 4 bytes) + hmac(16 bytes).

How to find  hmac(16 bytes).
What is packet(plain text) for hmac_md5?

**Comment by returnerza** [comment]
@thitiboy

use (original packet + flag + seq) = hmac_md5 
by unknown-item

**Comment by vidkung** [comment]
@returnerza

You can test following command example "hashcat64.exe -m 150 -a 3 Hash_Codes.txt"
Hash_Codes.txt  "580cd618407c0b22106905cfeaa66f8214c53205:ABCDEF"
Output hashcat.pot "580cd618407c0b22106905cfeaa66f8214c53205:ABCDEF:Cisco"

I think you must convert Binary to String

**Comment by tequiliewqzz699** [comment]
580cd618407c0b22106905cfeaa66f8214c53205    Binary ?

**Comment by Manoft** [comment]
what file i will edit ?
send.pm?

**Comment by tequiliewqzz699** [comment]
Manoft   No

**Comment by vidkung** [comment]
@tequiliewqzz699 

correct    
this example HMAC = Plaintext + Key

**Comment by tequiliewqzz699** [comment]
@vidkung thank you

**Comment by reeza555** [comment]
@tequiliewqzz699 If not, then I will come again to teach it.

**Comment by vidkung** [comment]
Hi guy 
I can find HMAC packet 
Please guide me find original packet

0000   20 00 68 03 8e 2f 45 00 01 00 00 00 0b 00 00 00
0010   fb dc d0 04 44 34 e5 cf a5 3a 39 c3 19 f5 d0 dd  << HMAC 


fbdcd0044434e5cfa53a39c319f5d0dd=HMAC Packet

**Comment by thitiboy** [comment]
@returnerza 
Now I do this,
my $msgHmac = hmac_md5($msgOrginal.$msgFlag.$msgSeq , pack('H*', 'EDB9D10AB84C9A2E05E38997C2F64A29'));
my $msgFinal = $msgOrginal.$msgFlag.$msgSeq.$msgHmac;
$msg = pack('v', length($msgFinal) + 2) .$msgFinal;

It doesn't work.

**Comment by vidkung** [comment]
@thitiboy

I think EAC change key for HMAC
you must to find out new key 
old key not invalid

**Comment by tequiliewqzz699** [comment]
@vidkung EDB9D10AB84C9A2E05E38997C2F64A29

**Comment by tarkungZ** [comment]
Old key doesn't work anymore we need to find new key. And I'm working on it with my 0% knowledge.

**Comment by blackstep** [comment]
How to decode 9166e0d672c03214ebd1fb9866bdebcc pls.

**Comment by returnerza** [comment]
@thitiboy old key is don't work just make new key

**Comment by thitiboy** [comment]
@returnerza Can u teach me for find key ?

**Comment by eieirelaxz4** [comment]
pls teach me

**Comment by returnerza** [comment]
@thitiboy sorry i'm not work for key :(

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
