### ISSUE TITLE
Disconnecting problem

### ISSUE THREAD

**Issue by nightmor** [OpenKore/openkore#2320]
Hello, Openkore worked just fine for me yesterday but today when i tried to open my character it didn't connect. how can i fix it please? it's my first time using openkore

I also redownloaded the zip again just in case
![capturesssssssssssssss](https://user-images.githubusercontent.com/42865644/44908908-3b8fd300-ad15-11e8-8012-88dc83c630dd.PNG)

**Comment by Fadreus** [comment]
#2315 
Use report template when reporting.
Read [things to know](https://github.com/OpenKore/openkore#things-to-know) before posting.

Don't ignore the text.
Ignorant can only be cured by reading.

**Comment by Fadreus** [comment]
#2315 
Use report template when reporting.
Read [things to know](https://github.com/OpenKore/openkore#things-to-know) before posting.

Don't ignore the text.
Ignorance can only be cured by reading.

**Comment by nightmor** [comment]
Sorry, i fixed it. thank you for the hard work 👍

**Comment by nightmor** [comment]
how can i delete the post?
