### ISSUE TITLE
Cant connect to fRO

### ISSUE THREAD

**Issue by Plasmabug** [OpenKore/openkore#2321]
## ------------------ Openkore Issues Template ------------------

* **Version ctime 2018_08_31**: 
* fRO
* Bug Report:
Cant connect to fRo. It Connects to the loginserver and as soon as it should switch to char selection it gets stuck. See picture. 
![problem](https://user-images.githubusercontent.com/42871055/44919428-d0a6c200-ad3d-11e8-98a2-f154359ef8b3.jpg)

I tried xcore 1 also but then i get 

Error message:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = undef;

Stack trace:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = undef;
 at src/Utils/BlessedRefTie.pm line 10
	Tie::BlessedRef::STORE('Tie::BlessedRef=SCALAR(0x650d37c)', undef) called at src/Network/Receive/ServerType0.pm line 930
	Network::Receive::ServerType0::map_loaded('Network::Receive::fRO=HASH(0x620becc)', 'HASH(0x668da44)') called at src/Network/PacketParser.pm line 276
	Network::PacketParser::parse('Network::Receive::fRO=HASH(0x620becc)', '\x{eb}\x{2}\x{80}\x{ed}\x{12}K&\x{83}\x{90}\x{5}\x{5}\x{0}\x{0}', 'Network::Receive::fRO=HASH(0x620becc)') called at src/Network/Receive.pm line 471
	Network::Receive::parse('Network::Receive::fRO=HASH(0x620becc)', '\x{eb}\x{2}\x{80}\x{ed}\x{12}K&\x{83}\x{90}\x{5}\x{5}\x{0}\x{0}', 'Network::Receive::fRO=HASH(0x620becc)') called at src/Network/PacketParser.pm line 410
	Network::PacketParser::process('Network::Receive::fRO=HASH(0x620becc)', 'Network::MessageTokenizer=HASH(0x640b38c)', 'Network::Receive::fRO=HASH(0x620becc)') called at src/functions.pl line 752
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4a59414)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

**Comment by alisonrag** [comment]
can you use in config.txt
debugPacket_received 2

and send here the console data?

**Comment by Plasmabug** [comment]
Schließe Verbindung zum Account Server
Unterbrechen der Verbindung (54.36.76.129:6900)...Verbindung unterbrochen
Verbinde zum Character Server...
Selected server: Chaos
Verbinde (54.36.76.130:6000)... verbunden
<< Received packet:      082D [493 bytes]

**Comment by alisonrag** [comment]
can you enter in 
openkore\src\Network\Receive\fRO.pm

and change this:

```
my %packets = (
		'0097' => ['private_message', 'v Z24 V Z*', [qw(len privMsgUser flag privMsg)]],
	);
```

to this:
```
my %packets = (
		'0097' => ['private_message', 'v Z24 V Z*', [qw(len privMsgUser flag privMsg)]],
		'082D' => ['received_characters_info', 'v C x2 C2 x20 a*', [qw(len total_slot premium_start_slot premium_end_slot charInfo)]],
	);
```

and in servers.txt
update:
```
# http://www.ragnarokeurope.com/
[France - fRO]
title France - fRO (ragnarokeurope.com): Chaos
ip 54.36.76.129
port 6900
master_version 31
version 1
patchpath /patch01
patchserver ftp.ragnarokonline.fr
serverType fRO
serverEncoding Western
addTableFolders fRO
charBlockSize 116
pauseCharLogin 1
```

**Comment by Plasmabug** [comment]
seems to work. thank you
