### ISSUE TITLE
Can't connect after game update

### ISSUE THREAD

**Issue by SallySyrup** [OpenKore/openkore#2322]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: Latest

* **Server**: iRO

* **Bug Report / Feature Request**: Can't enter the game.

* **Summary**: Refer to the image attached. It happened after the update. It can't enter the game.

![capture](https://user-images.githubusercontent.com/42872302/44922248-7e987900-ad0a-11e8-837c-0286270e85cc.JPG)

**Comment by alisonrag** [comment]
waint merge #2315
