### ISSUE TITLE
Timeout on Account Server

### ISSUE THREAD

**Issue by isirlok** [OpenKore/openkore#2325]
* **Openkore version git**: 
Up to Date
* **Server**: 
iRo Chaos/Thor
* **Bug Report / Feature Request**:
Bug Report
* **Summary**:
Closing connection to Character Server
Disconnecting (128.241.92.130:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.131:4504)... connected
Timeout on Map Server, connecting to Account Server...
Disconnecting (128.241.92.131:4504)...disconnected

Hello, looking for answers on here, is this a daily routine to wait on an update everytime the server patches? Is there a way we could update manually, It's not letting me in since the patch update.

**Comment by isirlok** [comment]
I wou7ld like to learn why this happens and how I could help it improve for future updates.

**Comment by alisonrag** [comment]
wait for #2315 
this happen because after every week update the warpportal change a lot of things in client, like packets and cryptkeys

**Comment by isirlok** [comment]
Thanks for letting me know! it is awesome how you guys work on all this!
