### ISSUE TITLE
[pserver]'X' outside of string in unpack at src/Network/Receive.pm line 3216.

### ISSUE THREAD

**Issue by blackroseyun** [OpenKore/openkore#2339]
this pserver is use kRO_RagexeRE_2013_08_07a. 
when i play with kore3 , sometime i use skills. i would get this error message.
can anyone help me to solve this problem. thank you.

OpenKore version what-will-become-2.1
@ai_seq = skill_use attack
Network state = 5
Network handler = Network::XKoreProxy
Revision: ctime:2018_09_03
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
'X' outside of string in unpack at src/Network/Receive.pm line 3216.

Stack trace:
'X' outside of string in unpack at src/Network/Receive.pm line 3216.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x5c54cfc)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		$msg = substr($spellInfo, $i, 18);
* 		($ID, $sourceID, $x, $y, $type, $range, $fail) = unpack('a4 a4 v3 X2 C2', $msg);

**Comment by blackroseyun** [comment]
solved. i try to use old openkore . and would not get error message https://github.com/OpenKore/openkore/tree/bf3eca1b8a446ff9b06c8f71a325663acf1b45b0

**Comment by alisonrag** [comment]
meybe openkore is slicing packts wrong
can you send the server info?

**Comment by blackroseyun** [comment]
[beauRO]
ip 220.128.175.75
port 7011
master_version 5
version 45
serverType kRO_RagexeRE_2013_08_07a
serverEncoding Big5
charBlockSize 144
addTableFolders twRO
sendCryptKeys 0x7E241DE0, 0x3D807D80, 0x5E805580,


[Packet_Keys]
1 = 0x7E241DE0
2 = 0x5E805580
3 = 0x3D807D80

**Comment by lututui** [comment]
Does #2340 fix this?

**Comment by blackroseyun** [comment]
sorry i was sleep. i try this. wait me to test

**Comment by blackroseyun** [comment]
fix this. but line 3247 have some problem like this photo. 
so i try to delete line 3247. now i wuold not get error with latest  openkore
![527](https://user-images.githubusercontent.com/40693417/45015347-03113180-b054-11e8-95c5-12b688576a7c.jpg)

**Comment by lututui** [comment]
Fixed that.
So #2340 fixes this?

**Comment by blackroseyun** [comment]
yes fix this. this problem is solved
