### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Dreamro7** [OpenKore/openkore#234]
Hello all Friend xkore

  Sorry to say i'm need help for fix Openkore x3 13/09/2016-15/09-2016 Thai server have update make x0 or x3 can't work it when have someone to help to fix it please share for me

Thanks

**Comment by topgamemun** [comment]
Same issues

**Comment by Cozzie** [comment]
@Dreamro7 Please do not post an issue without contributing productive information.
