### ISSUE TITLE
Recent cleanup produce mass error

### ISSUE THREAD

**Issue by smallvill3** [OpenKore/openkore#2343]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  version ctime:2018_09_04

* **Server**: Private server / GGamerz RO

* **Bug Report / Feature Request**: Bot cant start due to many error

* **Summary**: 
![capture](https://user-images.githubusercontent.com/26625329/45040081-b64f4a00-b097-11e8-9c19-9bf293bb08f7.JPG)

**Comment by sctnightcore** [comment]
I'll fix it . ...

**Comment by lututui** [comment]
Why can't alisonrag do anything right and why can't people actually review stuff before merging?

**Comment by smallvill3** [comment]
its ok, i have fix it.
