### ISSUE TITLE
hmac key bypass

### ISSUE THREAD

**Issue by icezZz** [OpenKore/openkore#235]
http://www.synacktiv.fr/ressources/owasp_esapi_hmac_bypass_poc.tgz

**Comment by icezZz** [comment]
goodluck

**Comment by minimax1** [comment]
@icezZz how to use sir?

**Comment by cydiath** [comment]
@icezZz Thec me sir

**Comment by firstsozaa** [comment]
can u explain more ?

**Comment by tonblur** [comment]
HOW TO USE SIR ???

**Comment by icezZz** [comment]
Now the RO  bot protection by preventing editing of the game.
But there is a solution to the Man in the middle (MitM) to redirect packet, go to openkore x3 proxy mode.

Expect more to be done HMAC with nonce (Hash based message authentication code) with some packet.
To prevent editing by openkore x3 proxy and packet hash algorithm used is very low SHA2-256.

What you have just MD5, SHA1, but not SHA2-256.
Added SHA2-256

**Comment by firstsozaa** [comment]
still dont understand how to add SHA2-256 can u guide us more ?

**Comment by dogsmile** [comment]
dont know what you mean anyway thanks

**Comment by i3irdy** [comment]
How to add file SHA2-256 ?
guild line please.

thank you.

**Comment by tosspons** [comment]
http://www.synacktiv.com/ressources/synacktiv_owasp_esapi_hmac_bypass.pdf

Manual.

**Comment by GAMENOVASZ** [comment]
How to use Program EsapiVictim ? 
Write of JAVA Language 
I can not find it GUI of Program

**Comment by dekaze** [comment]
@GAMENOVASZ  you can yun by install JVM and use command "java EsapiVictim g ...." to run it

**Comment by marshazz** [comment]
@icezZz why are you so sure that tRO is using ESAPI currently?

**Comment by topgamemun** [comment]
https://github.com/icezZz i want have take it program ?

**Comment by phisanu** [comment]
Wait

**Comment by Cozzie** [comment]
All discussion related to tRO refer to #221 .
