### ISSUE TITLE
IRO Now!!

### ISSUE THREAD

**Issue by eAthenaService** [OpenKore/openkore#2354]
Iro I don't Login

**Comment by haltamimi** [comment]
we're just going to wait for the update. How I wish I can update the tables and all lol

**Comment by Fadreus** [comment]
Don't open new issue.
Read past issues.
Read things to know.
Read front page.
Read read read.
Newbie is not an excuse.
Newbie have tons of homework to do.

**Comment by Fadreus** [comment]
#2349 
Don't open new issue.
Read past issues.
Read things to know.
Read front page.
Read read read.
Newbie is not an excuse.
Newbie have tons of homework to do.
