### ISSUE TITLE
IRO Table Update

### ISSUE THREAD

**Issue by haltamimi** [OpenKore/openkore#2355]
Hi Good Sir's. Can somebody help me get an update for IRO renewal today? Thank you so much. Just a new Openkore user here.

**Comment by Fadreus** [comment]
Don't open new issue.
Read past issues.
Read things to know.
Read front page.
Read read read.
Newbie is not an excuse.
Newbie have tons of homework to do.

**Comment by Fadreus** [comment]
#2349 
Don't open new issue.
Read past issues.
Read things to know.
Read front page.
Read read read.
Newbie is not an excuse.
Newbie have tons of homework to do.
