### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by reeza555** [OpenKore/openkore#236]
Someone has already solved HMAC Help me here. TRo

**Comment by ltdedigos** [comment]
T^T

**Comment by dcoffset** [comment]
Yeah , Waiting for Love

**Comment by tarkungZ** [comment]
Hmm , are you sure about this. 

Have you seen any bot in game already?

**Comment by reeza555** [comment]
@tarkungZ Yes, I just want to add a new key.

**Comment by Cozzie** [comment]
@reeza555 This is not the place to post an issue without contributing productive information.
