### ISSUE TITLE
Problem after windows update?

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#2360]
I just updated windows 10 to a new insider version.  Now when i open the bot up and it loads all the config files it is going very slowly.  What normally takes a few seconds to go through now takes 30+ seconds to load all the files and the bot is very laggy/slow.  Works fine in wxstart mode but normal mode it is really bad.  Any ideas on what could cause this?  I tried disabling anti virus, adding it to exceptions n everything.

**Comment by Fadreus** [comment]
> Any ideas on what could cause this?

Windows update is the cause.

**Comment by alisonrag** [comment]
This ia not a openkore issue, its related to perl, something in perl is slow in Windows 10
You can try to run with powershell
