### ISSUE TITLE
error message "start.exe>Encode.pm line 174" 

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#2370]
## ------------------ Openkore Issues Template ------------------

I'm using newest version , everytime use "relog" , the bot will shut down ,below is error message

```
This program has encountered an unexpected problem. This is probably because
of a recent server update, a bug in this program, or in one of the plugins.
We apologize for this problem. You may get support from IRC or the forums.

A detailed error report has been saved to errors.txt. Before posting a bug
report, please try out the SVN version first. If you are already using the SVN
version, search the forums first to see if your problem had already been
solved,
or has already been reported. If you truly believe you have encountered a bug
in
the program, please include the contents of the errors.txt in your bug report,
or we may not be able to help you!

The error message is:
Wide character in subroutine entry at
/<C:\Users\Administrator\Desktop\BotOrganizer\start.exe>Encode.pm line 174.
```

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by Nipodemos** [comment]
Solution: Don't use BotOrganizer

**Comment by hubertyang88** [comment]
no , I try start.exe  , error remains

**Comment by Nipodemos** [comment]
post your errors.txt

**Comment by hubertyang88** [comment]
The error message is:
Wide character in subroutine entry at
/<C:\Users\Administrator\Desktop\openkore-last\openkore-master\start.exe>Encode
.pm line 174.

**Comment by hubertyang88** [comment]
btw, if BotOrganizer is not recommended , is there good way to organize profiles instead of use many copies of openkore?

**Comment by hubertyang88** [comment]
@Fadreus thank you very much!!  it really helps

**Comment by hubertyang88** [comment]
@lututui Sorry  , I didn't notice there is an error file . below is the errors.txt , it seems something worng with chinese name of char , I try an english name , it's ok

Error message:
Wide character in subroutine entry at /<C:\Users\Administrator\Desktop\openkore-last\openkore-master\start.exe>Encode.pm line 174.

Stack trace:
Wide character in subroutine entry at /<C:\Users\Administrator\Desktop\openkore-last\openkore-master\start.exe>Encode.pm line 174.
 at /<C:\Users\Administrator\Desktop\openkore-last\openkore-master\start.exe>Encode.pm line 174
	Encode::decode('GBK', '按错错') called at C:/Users/Administrator/Desktop/openkore-last/openkore-master/src/I18N.pm line 61
	I18N::bytesToString('按错错') called at src/Network/Receive.pm line 710
	Network::Receive::received_characters('Network::Receive::cRO=HASH(0x5bd1db4)', 'HASH(0x5924614)') called at src/Network/PacketParser.pm line 276
	Network::PacketParser::parse('Network::Receive::cRO=HASH(0x5bd1db4)', '\x{9d}\x{9}\x{97}\x{0}0%\x{2}\x{0}\x{a4}\x{e}\x{0}\x{0}~\\x{1}\x{0}.\x{b4}\x{0}\x{0})\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{c}\x{0}\x{a6}\x{4}\x{0}\x{0}\x{a6}\x{4}\x{0}\x{0}o\x{0}o\x{0}\x{96}\x{0}\x{ce}...', 'Network::Receive::cRO=HASH(0x5bd1db4)') called at src/Network/Receive.pm line 472
	Network::Receive::parse('Network::Receive::cRO=HASH(0x5bd1db4)', '\x{9d}\x{9}\x{97}\x{0}0%\x{2}\x{0}\x{a4}\x{e}\x{0}\x{0}~\\x{1}\x{0}.\x{b4}\x{0}\x{0})\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{c}\x{0}\x{a6}\x{4}\x{0}\x{0}\x{a6}\x{4}\x{0}\x{0}o\x{0}o\x{0}\x{96}\x{0}\x{ce}...', 'Network::Receive::cRO=HASH(0x5bd1db4)') called at src/Network/PacketParser.pm line 410
	Network::PacketParser::process('Network::Receive::cRO=HASH(0x5bd1db4)', 'Network::MessageTokenizer=HASH(0x2e22044)', 'Network::Receive::cRO=HASH(0x5bd1db4)') called at src/functions.pl line 752
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x3c091bc)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

**Comment by alisonrag** [comment]
related to a call in bytestostring in received_characters
```
I18N::bytesToString('修飞飞') called at src/Network/Receive.pm line 710
	Network::Receive::received_characters('Network::Receive::cRO=HASH(0x5b99efc)', 'HASH(0x58b833c)') called at src/Network/PacketParser.pm line 276
```

**Comment by c4c1n6kr3m1** [comment]
wait till 2067.........
:)

**Comment by ronderev** [comment]
Geez. Lol. 2 weeks straight (except maintenance) with botting. Wasted energy. Hahaha

**Comment by alisonrag** [comment]
fixed in:
https://github.com/OpenKore/openkore/commit/996f78bdb66a7a843c256957ea52243da305a235
