### ISSUE TITLE
Custom server login

### ISSUE THREAD

**Issue by Vitale44** [OpenKore/openkore#2375]
Hello, it has been like 2-3 years that this server is still open, and has no real protection in IT, just custom login with custom master account. i was wondering if someone has already worked on IT, if not , i'm willing to remunerate anyone who will work on this ( 50$ )

i'll also pay 10$ for a way to force custom grf  on this server ( like flatmap )

server : https://originsro.org/

thank you

**Comment by Fadreus** [comment]
Use forum/IRC.
Github not place for such a thing.
