### ISSUE TITLE
tRO(Thailand RO) It doesn't work.

### ISSUE THREAD

**Issue by 3TRIRAT** [OpenKore/openkore#2378]
Protection -> Easy Anti Cheat (EAC) 

 Can anyone solve this problem?

**Comment by alisonrag** [comment]
no one developer play in this server, and for now no one was able to bypass the easy ant cheat

**Comment by Darkultima** [comment]
thx ^_^

**Comment by sctnightcore** [comment]
It hard to do it .

tRO use private key and public key . 
and encode head packet .
