### ISSUE TITLE
iRO won't let me run bot after patch

### ISSUE THREAD

**Issue by ronderev** [OpenKore/openkore#2379]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by ZaskarAlpha** [comment]
of course because its after maintenance. U need to update packets. :)

**Comment by ronderev** [comment]
Oh. Thanks. I'm just gonna wait. I'm new to this. Lol
