### ISSUE TITLE
Packet Parser: Unknown switch: 0864

### ISSUE THREAD

**Issue by suradetch** [OpenKore/openkore#238]
![image](https://cloud.githubusercontent.com/assets/22225876/18566792/83e9c586-7bbf-11e6-93e0-c15ba52a29f3.png)

**Comment by lututui** [comment]
This is not an error, it's just a warning. If it doesn't affect your experience with openkore, it can be safely ignored

**Comment by suradetch** [comment]
Thx you

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
