### ISSUE TITLE
Map Timeout since Sept 19th update

### ISSUE THREAD

**Issue by BabyFaceJ** [OpenKore/openkore#2384]
So... I have downloaded the new openkore multiple times throughout the day. Anytime I connect I get a map timeout error. I have googled for a couple hours, and downloaded the github client. Made sure to clone it a couple times. Checked my config. Cant seem to connect since the most recent IRO update. Issue is on the Chaos server. Really just want to see if this is an issue people are aware of, or, others are having the same issue. I have not used openkore in like 15+ years back when I was a kid messing around and still relearning everything. Any suggestions or opinion are appreciated. Thanks for what you guys do.

**Comment by Fadreus** [comment]
> Any suggestions or opinion are appreciated

Read more.

**Comment by Nipodemos** [comment]
Resuming:
When ragnarok have maintence, openkore needs to have maintence too. When openkore don't have the maintence, the map timeout error shows

solution : wait for some developer to do the maintence on openkore

**Comment by BabyFaceJ** [comment]
Alright, thanks for the quick response. I was positive I was just waiting for the update after maintenance, just wasn't sure if I was doing something wrong. Again, Thanks.

**Comment by BabyFaceJ** [comment]
> > Any suggestions or opinion are appreciated
> 
> Read more.

Gee thanks. You're so helpful. If arrogance was a skill you sir, have mastered it.

**Comment by Fadreus** [comment]
Call me arrogant, you are ignorant.
Everything in front page, and you didn't even read any single one of them.

**Comment by BabyFaceJ** [comment]
> Call me arrogant, you are ignorant.
> Everything in front page, and you didn't even read any single one of them.

Please link the page you are reading that has info about this because as I stated before I read the whole main page ran through the issues list, browsed forums, checked google. I had seen it was a known issue just wasnt sure where to locate the information I needed on what was to be updated. Again, No reason for you to act like such a prick. I am sure these guys get this question ALL THE TIME and I didnt want to be "That guy" but was having issues getting a finalized answer, again I knew it was the update but wasnt sure I myself had done something wrong. SO again, thanks for your rude comment, and again stating obvious answers with no real information provided whatsoever your awesome.

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#things-to-know
![image](https://user-images.githubusercontent.com/32188494/45876554-80b39c00-bdcd-11e8-933c-3fab2bca0171.png)

### HERE I ENLARGED IT FOR YOU INCASE YOU CAN'T SEE CLEARLY.
![image](https://user-images.githubusercontent.com/32188494/45876603-ac368680-bdcd-11e8-90f7-653c0665669e.png)

**Comment by BabyFaceJ** [comment]
OMFG LuLz. 

I love how you just copy and pasted useless information and try to claim this shit as obvious info. Again, I read this whole front page went browsing through forums googled the issue, again I KNEW IT WAS THE UPDATE BRO, I WAITED UNTIL THE OPENKORE MASTER FILES STATED "Updated 3 hours ago". I then followed the directions on the website cloned it even downloaded the github app, made sure my config and shit matched. I was unaware the guy running this show has to do each fuckin server one at a time so when I saw an update and tried to clone it the only patch he had done was for fuckin renewal. What you just linked in no way whatsoever says ya even after Kore has been updated after an iRO patch you have to wait for your specific server to be updated. That was the answer I was looking for BROSEPH I knew there was a weekly update and if you READ my fucking post you would have known I DID READ THAT SHIT. 

If your only ever going to be a condecending asshole and put useless information out here, please dont bother writing shit. Honestly. I needed to wait for the recv packets for that specific server to be updated. Even the response you gave me was un-informattive your a fucking idiot and an asshole. *Clap Clap*

If you cant say anything nice at all and none of these last 3 things you wrote has ANY fucking useful information whatsoever you shouldnt be on forums bro. Period. If you cant treat other people asking a simple question with kindness or some sort of direction just keep your fucking mouth shut dude its that simple. Just because you cant get your ass kicked by hiding behind a computer doesnt mean its a reason to go around sniping rude, sarcastic comments with an I know it all AIR. Again maybe you should have read my fucking post. I said I KNEW IT WAS THE UPDATE. Dont even bother responding to this your a waste of fucking air bro. I wont read shit you post after this. 

Troll on bro.

**Comment by Fadreus** [comment]
The only one useless is you.
A piece of information about biology only useful for scientist, not for artist.
You found my reply not useful because you are hopeless

Well, I like to reply with short words since long text people like  you prolly didn't read.
So, I guess your head is too thick so let me clarify it for you.

### By "more reading" I mean:
### - You report without using the bug report template.
### - You didn't check existed issue before posting (There are 2 issue just few hours before yours, you should use that thread rather then starting new issue).
### - You don't know who maintaining iRO server, his schedule, when he usually update and yet you claim you've read everything.

Well, ignorant people are always like this.
They think they always right.

You said you knew, but keep doing what shouldn't.
If you know fire will burn, will you put your hand on it?
A wise man act with their knowledge but you are just a fool.
You don't even use any of information you have.

So, should I tell you what's more you are wrong since you are too idiot?

> I WAITED UNTIL THE OPENKORE MASTER FILES STATED "Updated 3 hours ago"

You should check what is updated LOL.
Why would KRO update affect IRO? Are you retard?
Do you even English bro?
Even baby know how to click on their touch screen.
Why don't you use your mouse to click the link?

**Comment by Fadreus** [comment]
Ignorant, lazy & a fool.
Call people rude, you don't even read rule which to respect others.
Too many you didn't read.
You don't read FAQ and also READ me in forum.

I can debate with 100 wise men but not to a fool.

**Comment by alisonrag** [comment]
Sorry guys, but this place is not to discuss
