### ISSUE TITLE
I can not change thief class macros [ iro Renewal]

### ISSUE THREAD

**Issue by kasemsan** [OpenKore/openkore#2389]
I can not change thief class macros !!!!!
macros not use skill steal/Envenom poring

**Comment by sctnightcore** [comment]
problem in marco not openkore :p

**Comment by alisonrag** [comment]
you are configuring wrong please try http://openkore.com/index.php/AttackSkillSlot

**Comment by Fadreus** [comment]
Use forum.

**Comment by c4c1n6kr3m1** [comment]
... and use brain
