### ISSUE TITLE
Mailbox doesn't work

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#2396]
## ------------------ Openkore Issues Template ------------------

I try to use mailbox in openkore , it doesn't work , when I use cmd "mi" or "mo"  , openkore will disconnect . I use wireshark to get the packet
open mailbox: E8 09 00 00 00 00 00 00 00 00 00
read a mail: EA 09 00 14 CC 06 00 00 00 00 00
get attachment :  F3 09 14 CC 06 00 00 00 00 00 00
in the packet "14" seems to be ID of the mail , this value will change
I can use "send E8 09 00 00 00 00 00 00 00 00 00" to open mailbox , but the mailbox shows empty when it's not , and I can't read or get attachment because I can't get the ID of the mail
by add something to openkore\src\Network\Send\cRO.pm
add to %handler
       + mailbox_open 09E8
       + mail_read 09EA
"mi" works , a mail list can show , but "mo" "ma" still show the mailbox is empty or not opened 

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by alisonrag** [comment]
this issue is about to update send handlers in cRO

**Comment by sctnightcore** [comment]
09E8 / 09EA / 09F3

Rodex Packet !
