### ISSUE TITLE
Nova ro server.

### ISSUE THREAD

**Issue by pussbacon** [OpenKore/openkore#2398]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: Nova RO
* **Bug Report / Feature Request**: server and is being detected.

* **Summary**:server and is being detected.

**Comment by alisonrag** [comment]
the server has custom encryption, is located in cps.dll, but i was not able to reverse, if you know something please open a topic in forum, this place is to report issues in openkore
