### ISSUE TITLE
recvpackets

### ISSUE THREAD

**Issue by KelvinDesenvolvedor** [OpenKore/openkore#2403]
Boa tarde, quero perguntar para vocês colaboradores principais qual método vocês utilização para extrair as informações do arquivo recvpackets do openkore, hoje estou fazendo uma conexão com outro servidor, porem meu personagem esta configurado com um recvpackets diferente do servidor onde estou alocado, quero saber qual metodo ou ferramenta a equipe usa para conseguir extrair esses pacote do ragnarok, é extraído de um .exe mas qual método vocês estão usando ficarei muito grato se minha duvida for sanada.

**Comment by alisonrag** [comment]
Boa Tarde, apenas informando que usar softwares prontos é muito fácil.

De nada adianta você ter ferramentas prontas se na hora que precisar usar você não entende o que está fazendo. 

Exitem algumas dezenas de servidores não oficiais pelo mundo, falando em termos de client, todos eles usam o RagexeRE (client do kRO) como base.  O que acontece é que alguns servidores podem e/ou utilizam alguns softwares de proteção que dificultam o acesso ou bloqueiam a extração de dados do executavel.

O método atual é baseado em disassemble do executavel do jogo, onde com base no que já foi estudado do mesmo ao longo dos anos, através de ferramentas nós procuramos padrões dentro do arquivo que nos indicam os pacotes e os respectivos tamanhos, além das chaves de criptografia, chave de storage e pacotes shuffle.

não vou ficar me estendendo por aqui, mas se esta atras de ferramentas prontas pra extração do recvpackets segue uma lista:

1 - allanon tool (usada no iRO e compativel com a maioria dos clientes 2014 ~ 2017)
https://gist.github.com/allanon/d8181ceaf6380da6d8fa4fddf1885706

2 - Peek (compativel com todos os clientes 2011+)
https://gitlab.com/4144/peek

3 - drKNA toll (compativel com tRO)
https://github.com/OpenKore/packetExtractor

4 - packet extractor v3 (clients 2013-)
https://github.com/OpenKore/packet-extractor/

5 - JCV RO tool (usado em clientes super antigos talvez funcione em 2011-)
https://github.com/Fadreus/JCV-s-RO-Tools-1.0.3

6 - BPE (usado para debug e extração de dados de clients [ funciona com todos ])
https://gitlab.com/4144/bpe/

Além desses muitas pessoas principalmente no brasil tem suas próprias ferramentas de extração, mas não são diferentes dessas citadas.

perceba que a maioria deles ainda é funcional, mas muitos delas se você não souber o que esta fazendo não vai adiantar nada.

você pode descobrir a data do seu cliente e escolher a melhor ferramenta usando este tutorial:
http://openkore.com/index.php/ServerType#Compilation_Date

**Comment by KelvinDesenvolvedor** [comment]
Boa Tarde Alison, cara muito obrigado pelas informações, hoje sou
programador assim como você acredite você me deu um norte muito bom por
onde partir, sou grato pelo seutempo e pela sua atenção.

Em seg, 8 de out de 2018 às 15:59, Alison Serafim <notifications@github.com>
escreveu:
