### ISSUE TITLE
RE:Start update

### ISSUE THREAD

**Issue by kurah00** [OpenKore/openkore#2407]
Allanon, wouldn't you like to teach us how to use your tool?
(so you do not have the effort to update the information of a dead server)

**Comment by kurah00** [comment]
> ppm install Disassemble-X86

I was stucked exactly here, thank you.

**Comment by Skye168** [comment]
How do you get new "shuffle.txt" file, it'll only generate other files but not shuffle.txt.
Thanks.

**Comment by siefer214** [comment]
im lose in this section>where can i see this one thanks
 put in same paste:
Ragexe.exe
recvpackets.txt
shuffle.txt
sync.txt
servers.txt
extract_recvpackets.pl

open cmd move to paste and type:
extract_recvpackets.pl Ragexe.exe

**Comment by kurah00** [comment]
Use of uninitialized value $file in open at C:\Users\Name\extract_recvpackets.pl line 352
read<> on closed filehandle FP at C:\Users\Name\extract_recvpackets.pl line 354
Use of uninitialized value $file in open at C:\Users\Name\extract_recvpackets.pl (line 327)
read<> on closed filehandle FP at C:\Users\Name\extract_recvpackets.pl line 330
Unable to determine start of recvpackets definition function. 0 possible locations found

**Comment by kurah00** [comment]
@Skye168 How did you generate the other files? I get this /\

**Comment by Skye168** [comment]
It's much more simple than that, here are the steps:
- copy these files from openkore bot folder then put them all in same folder, easiest place to be is in c:\Gravity\Ragnarok Restart\

Ragexe.exe - it's in c:\Gravity\Ragnarok Restart\
recvpackets.txt - C:\openkore-master\tables\iRO\Restart
shuffle.txt - C:\openkore-master\tables\iRO\Restart
sync.txt - C:\openkore-master\tables\iRO\Restart
servers.txt - C:\openkore-master\tables
extract_recvpackets.pl - you get this file from the link above from allanon script

Now open cmd or command prompt on windows, then go to that folder where you want to generate new files. Ex. c:\Gravity]Ragnarok Restart>extract_recvpackets.pl ragexe.exe        
You will see that a few files has been re-generated usually are recvpackets.txt, servers.txt, sync.txt.
The only file left unsolved is usually "shuffle.txt", I stuck here and can't go any further till someone can tell us how to go on from there. GL.

**Comment by kurah00** [comment]
It just load without a "complete message"?

**Comment by Skye168** [comment]
Yes. You won't see complete message but you can see that the file has been updated by looking at the time stamp on the file itself.

**Comment by kurah00** [comment]
when I open cmd, there is a pre-written path that I can not change: C: \ Users \ Name>

To skip this, I put the files in the path instead of matching the path to my files

I opened the cmd
C: \ Users \ Name> extract_recvpackets.pl ragexe.exe
loading a second ...
jumped a line and nothing happened

I closed all, replace the four files in openkore
It did not work, did I do something wrong?

**Comment by kurah00** [comment]
oh! you're right!
shuffle is the only file that has not changed the date

**Comment by alisonrag** [comment]
if not changed, shuffle not changed also in client

**Comment by kurah00** [comment]
I tested it and it did not work,
Trying again...

**Comment by alisonrag** [comment]
the correct shuffle have 29 packets.

this script dont get only the correct as you can see here:
List:
https://gitlab.com/4144/peek/blob/master/Input/packet_names.ini#L1

examples:
with packet name:
https://github.com/alisonrag/openkore/blob/aceeeaddbc32d930d9f988598e5892326eb8ef3f/tables/kRO/Sakray/shuffle.txt

without:
https://github.com/OpenKore/openkore/blob/master/tables/bRO/shuffle.txt

a lot of packets in iRO shuffle is related to sync packets

you can use peek, but you will need to know how to convert to openkore files format:
https://gitlab.com/4144/peek/

old tutorial:
http://forums.openkore.com/viewtopic.php?f=36&t=207278&start=0

**Comment by Zexeta** [comment]
Peek doesn't seem to work at all for me.  I try to extract packets or start analyzer and it says Reference Location not found.  I moved copies of the client/launcher into the folder with peek, selected them and when i press either button it says that error message.  Are you sure peek is compatible with this client?
