### ISSUE TITLE
iRO Restart packets not updated? 

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#2409]
Title says it all.

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=16&t=212775

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=16&t=212775

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#weekly-maintence-on-official-servers
http://forums.openkore.com/viewtopic.php?f=16&t=212775

**Comment by Zelecktor** [comment]
@Fadreus 
@sctnightcore 
I have some issues extracting packets. (for iRO Re:Start to be clear)

Comparing with the old recvpackets, there are 13 new packets. Adding them manually the result is wrong shuffle. (about 1400-700 lines where the correct is arround 60-70 lines)

New packets:

```
0197 4 4 0

0B01 56 56 0
0B02 56 56 0

0B04 80 80 0
0B05 59 59 1
0B06 53 53 0
0B07 -1 47 0
0B08 27 27 1
0B09 -1 5 1
0B0A -1 5 1
0B0B 4 4 1
0B0C 155 155 1
0B0D 10 10 1
0B0E -1 4 1
```

**Comment by c4c1n6kr3m1** [comment]
usually, new packets not shuffled
