### ISSUE TITLE
็How to find packet (recvpacket.txt) in Wireshark.  I'm newbie 

### ISSUE THREAD

**Issue by DestinyJame** [OpenKore/openkore#241]
I don't know how to find packet in Wireshark.
How i do. Thank.

**Comment by Phunsin** [comment]
for tRO data 80 when you login you can copy from that

**Comment by DestinyJame** [comment]
Example   0x07   how to convert to    xxxx  10  20     in recvpacket.txt      10 and  20 how to mean.
 Thank you so much, but i'dont need for tRO.
I want to find packet in server private. 

Thank you.

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
