### ISSUE TITLE
iRO Renewal not updated yet?

### ISSUE THREAD

**Issue by Ace071418** [OpenKore/openkore#2410]
Allanon didnt update it yet?

Thanks for the Replies :)

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=16&t=212775

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#weekly-maintence-on-official-servers
http://forums.openkore.com/viewtopic.php?f=16&t=212775

**Comment by Ace071418** [comment]
well I'm sorry I didn't clarify my question.. he updated/changed items.text and itemsdescriptions.txt I thought this is the update of the week.. not the recvpackets.txt, shuffle.txt, sync.txt and server.txt.. so Im just wondering if thats it?


![allanon](https://user-images.githubusercontent.com/42865587/46856487-28eeda80-ce39-11e8-9fc3-7e32783a1847.png)

**Comment by Fadreus** [comment]
Use that PR to ask, not open new issue.
You should read before posting.
Especially the one you've deleted.
