### ISSUE TITLE
Error - OpenKore - help

### ISSUE THREAD

**Issue by KelvinDesenvolvedor** [OpenKore/openkore#2412]
Good afternoon guys, I'm having trouble making the connection on a private server, I was able to extract all the necessary information but my character does not remain logged in, follow data from the server, please help me.

http://openkorebrasil.org/index.php?/topic/5129-openkore-private-server-help/
```
Error - OpenKore
---------------------------
This program encountered an unexpected problem. Probably because of
some update on the server, a bug in the program or one of the plugins.
We apologize for this problem. You can request support from IRC or the forum.

An account was saved in errors.txt. Before reporting a bug, try using the
SVN first. If you are already using the SVN version, look in the forum if your problem
has not been resolved or if it has not already been reported. If you really believe that you found
a bug in the program, please include the bug.txt report in your report or we do not
we will be able to help you!

The error message is:
Can't reconstruct unknown packet: sync_received_characters at src/Network/PacketParser.pm line 180.
---------------------------

# [Packet_Keys]
# 1 = 0x09366971
# 2 = 0x005672F1
# 3 = 0x6F3712AE
```

[www.worldrag.com/re]
ip 192.99.119.147
port 9810
version 57
master_version 2

#PE VIEW "Dec 21, 2006 11:33:37 AM"
serverType kRO_Sakexe_2007_01_02a
charBlockSize 147
serverEncoding Western

#PEEK MASTER package and files kRO
addTableFolders kRO2 /Sakexe_2007_01_02a; translated / kRO_english; kRO2

clientHash 3900000072616661656C303035343838
#PEEK MASTER
sendCryptKeys 0x09366971, 0x6F3712AE, 0x005672F1

**Comment by sctnightcore** [comment]
I wonder why you do not use English.

**Comment by NoahXIII** [comment]
![capture](https://user-images.githubusercontent.com/44184439/46991327-ba24b200-d0c2-11e8-8411-249af2cba4db.PNG)

Help PLS.

**Comment by alisonrag** [comment]
@KelvinDesenvolvedor 
please post all errors.txt here

**Comment by KelvinDesenvolvedor** [comment]
I still can not solve the server error, can anyone help me?

**Comment by alisonrag** [comment]
inside of openkore folder have a errors.txt file, send the content here

**Comment by sctnightcore** [comment]
btw, server has gepard ?

**Comment by alisonrag** [comment]
have gepard dll but is not implemented.

correct server info is:
```
# http://www.worldrag.com/re/
[WorldRAG - RE]
ip 192.99.119.147
port 9810
master_version 2
version 57
serverType kRO_RagexeRE_2016_12_28a
secureLogin 0
secureLogin_type 0
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders kRO/RagexeRE_2016_12_28a;iRO/official;iRO
charBlockSize 144
sendCryptKeys 0x09366971, 0x6F3712AE, 0x005672F1
pinCode 0
private 1
gameGuard 0
```
but i checked with network sniffer and login seems encrypted

![image](https://user-images.githubusercontent.com/10372732/47230172-e3359300-d39f-11e8-9f38-c54282d9d27c.png)
