### ISSUE TITLE
some one can use bot  origins ro

### ISSUE THREAD

**Issue by TomEnder** [OpenKore/openkore#2413]
some one can use bot  originsro
https://originsro.org/

**Comment by alisonrag** [comment]
just to make it clear, this is a place to post issues

**Comment by Drowcan2** [comment]
Dude i tried everyting for botting there. Can u please help me how u did?

**Comment by Wouchou** [comment]
Hi @alisonrag,

Any chance to help me out finding why i can't use it on OriginsRO? Is it still possible ?

Thank you mate
