### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by suradetch** [OpenKore/openkore#242]
Npc name : Utan Shaman 
Map: um_in 44 71
![image](https://cloud.githubusercontent.com/assets/22225876/18617714/604e22f0-7e00-11e6-9e80-259aa60fd9d6.png)
![image](https://cloud.githubusercontent.com/assets/22225876/18617716/6a9fc588-7e00-11e6-8ab5-221fef19ae94.png)

**Comment by Jozoko** [comment]
It's not macro request topics. Use openkore forum for it

**Comment by suradetch** [comment]
I'm sorry

**Comment by Phunsin** [comment]
This problem it not good to post in here. It better to ask in openkore thai group first...
