### ISSUE TITLE
IdRO - cant select character on 4th slot or more

### ISSUE THREAD

**Issue by S31389** [OpenKore/openkore#2431]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: IdRO Midgard

* **Bug Report / Feature Request**:

* **Summary**:

![image](https://user-images.githubusercontent.com/44332321/47263037-1eac9a80-d523-11e8-8892-1548f67dfea3.png)
Please help for this condition, i cant select any char on 4th slot or more.

**Comment by S31389** [comment]
[console_debug_.txt](https://github.com/OpenKore/openkore/files/2499084/console_debug_.txt)

**Comment by ya4ept** [comment]
what charBlockSize do you use?
