### ISSUE TITLE
Correct field file for this map ( kame_house )

### ISSUE THREAD

**Issue by kamirie** [OpenKore/openkore#2432]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

* **Openkore version git**: 
Latest Git download
* **Server**:  
Private Server
* **Bug Report / Feature Request**:
Question/Request
* **Summary**:
Does any one have a correct field file for this map? Unfortunately , the grf of the server i'm playing at is encrypted and I cannot extract the map files to make a field out of.

TIA
https://imgur.com/wMeYOwx

**Comment by alisonrag** [comment]
this is not a issue, you can try to search in 
http://herc.ws/board/
https://rathena.org/board/
http://cronus-emulator.com/
https://forum.brathena.org/
https://github.com/idathena/trunk
