### ISSUE TITLE
time out on map server ,connect to account server on idRO:Thor

### ISSUE THREAD

**Issue by Yusrisal** [OpenKore/openkore#2435]
![testtt](https://user-images.githubusercontent.com/44333633/47281392-0c0a9200-d605-11e8-8712-0b54071689ed.png)
some one ,help me....!?
what's wrong with the error above? tell me plz thanks

**Comment by alisonrag** [comment]
classic server is not official supported by openkore.

no one dev play in this server and no one that know how to connect share information with us.

continue in #2392
