### ISSUE TITLE
Webmonitor plugin issues

### ISSUE THREAD

**Issue by aecute** [OpenKore/openkore#244]
i put JSON, Protocol and ReadBackwards into openkore/src  (https://drive.google.com/file/d/0B14zWOVzgsgRR05pS05DdHVoV2s/view?usp=sharing)

and i ran wxstart in the console i got this http://pastebin.com/4JaRHNRZ

and i try to install a SHA.dll in windows/system32 or Windows\SysWOW64 but it's not working. 

SHA.dll from : http://dllyes.com/sha-dll/

my os: windows10 edu 64 bit.

**Comment by itsrachelfish** [comment]
@aecute Why did you close this issue? Did you find a solution?
