### ISSUE TITLE
We need to bot on RSS Restart iRO

### ISSUE THREAD

**Issue by caomongthuong** [OpenKore/openkore#2440]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by alisonrag** [comment]
we is a lot of people '-'
only you is asking for bot in this server ^^

**Comment by alisonrag** [comment]
Custom Drops
Hunting Mission
**Gepard 3.0
No Bots**
No Autotrade
No MultiClients
Proxy Servers to Cater players around the world

i'm sorry but no one is able to bypass gepard, use forums to ask for help
