### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by nicoismyname** [OpenKore/openkore#2443]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

I’m using an app that can track the Packets made by attack and spawn of mobs. Can I use this to have a working PHRO bot? Thanks. 
P.S. if this is not the correct sub, please move. Thanks.

**Comment by alisonrag** [comment]
unfortunately maybe not.
maybe you can resend the packet with another software and will work, but in openkore this is not enough

**Comment by alisonrag** [comment]
you can use #1225 to share infos you you have any idea how we can reconstruct the packets
