### ISSUE TITLE
не могу зайти

### ISSUE THREAD

**Issue by fil9039** [OpenKore/openkore#2450]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 25.10.2018

* **Server**: rRo

* **Bug Report / Feature Request**:Timeout on Account Serve

* **Summary**: пжалуйсто подскажите что и как нужно делать

**Comment by alisonrag** [comment]
use #2272

**Comment by fil9039** [comment]
прошу прощения я от и до прокрутил #2273 но так и не нашел нужной информации не могли быт вы мне изложить чт и как нужно делать

**Comment by Fadreus** [comment]
جاڠنله ڬونا بهاس يڠ اورڠ لاين تق ڤاهم. بودوه ك اڤي كاو ني؟

**Comment by Fadreus** [comment]
جاڠنله ڬونا بهاس يڠ اورڠ لاين تق ڤاهم. بودوه ك اڤي كاو ني؟

**Comment by fil9039** [comment]
мне просто нужна информация как законектить бота, он тайм аут пишет и все, если есть возможность фото ну или фаил с конектом буду благодареню.

**Comment by Fadreus** [comment]
. تو مان بوليه بوت بيڠاي. كالاو بوليه ده اڤدات سبلوم كاو تاڽ. بهلول ruRO سرۏر

**Comment by Fadreus** [comment]
. تو مان بوليه بوت بيڠاي. كالاو بوليه ده اڤدات سبلوم كاو تاڽ. بهلول ruRO سرۏر
おまえさんにわよみませんか？
Klu xphm gak sah bngong la ko ni.

**Comment by Kuzyashin** [comment]
Cool, όλοι θα επικοινωνήσουμε σε διαφορετικές γλώσσες. Βλέπε ότι δεν
καταλαβαίνει τι να κάνει.

сб, 27 окт. 2018 г., 19:01 司 <notifications@github.com>:

**Comment by fil9039** [comment]
μπορείς να βοηθήσεις??;

**Comment by fil9039** [comment]
I'm asking for help, not bullying...

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/47607918-11c70400-da59-11e8-876e-a3691d9427a6.png)

![image](https://user-images.githubusercontent.com/32188494/47607940-49ce4700-da59-11e8-9cc3-1aeb65e0c0b9.png)
