### ISSUE TITLE
Can someone teach me about sync,recvpackets in peek file

### ISSUE THREAD

**Issue by chaiisrn** [OpenKore/openkore#2453]
how to convert output file to use in openkore 
i see **[Packet_Lengths],[Packet_Keys],** 
**[Shuffle_Packets]**

**[Packet_Keys]** I put it in servers.txt
**[Shuffle_Packets]** in shuffle.txt follow @alisonrag in #2425 

but i don't know where is sync and recvpackets in **[Packet_Lengths]**

**Comment by nizdi** [comment]
Packets_lengths are basic revpackets, just use this http://forums.openkore.com/viewtopic.php?f=6&t=207278

But about sync I don't really know how to get it if not by using allanon script (find in his gist). Did you find out?
