### ISSUE TITLE
iro not connecting to map and iro updates but not updates? fml. 

### ISSUE THREAD

**Issue by pelthor** [OpenKore/openkore#2457]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by pelthor** [comment]
referring to the commits but evidently I am trying to figure out if i can just modify and what exactly they are doing on these updates.  I care not for luxury updates, but the actual weekly maintenance days updates.    that gets the bots back streaming

**Comment by Fadreus** [comment]
[iRO FAQ.](http://forums.openkore.com/viewtopic.php?f=16&t=212775)

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=16&t=212775

**Comment by pelthor** [comment]
why is it closed if iro is down?


________________________________

**Comment by alisonrag** [comment]
because we know that openkore is not working in iRO as you should know that you have to wait for update 
https://github.com/OpenKore/openkore#weekly-maintence-on-official-servers

**Comment by pelthor** [comment]
then post the update,  i fixed it internally it seems,  have a nice day.

________________________________
