### ISSUE TITLE
Carp::Assert::assert(' ') Failed InventoryList.pm Assert.pm

### ISSUE THREAD

**Issue by Razalka** [OpenKore/openkore#2458]
kRO_RagexeRE_2015_11_25d

The bot run normally in 5 minutes and this happened.
Happened repeatedly after the bot run in 5 minutes.

![image](https://user-images.githubusercontent.com/25100730/47603943-34d3c280-da1d-11e8-9f08-d8dee775c34a.png)

**Comment by AlexandreVitorino** [comment]
Could u upload the log file ?

**Comment by Razalka** [comment]
`OpenKore version what-will-become-2.1
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2018_10_08
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Assertion failed!
 at C:/BOT/BOT/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('') called at src/InventoryList.pm line 273
	InventoryList::remove('InventoryList::Inventory=HASH(0x717b454)', 'HASH(0x602d0b4)') called at src/Misc.pm line 1905
	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 2849
	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', 'HASH(0x60394a4)') called at src/Network/PacketParser.pm line 276
	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', '\x{fa}\x{7}\x{1}\x{0}\x{b}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/Network/Receive.pm line 472
	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', '\x{fa}\x{7}\x{1}\x{0}\x{b}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/Network/PacketParser.pm line 410
	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', 'Network::MessageTokenizer=HASH(0x3c5188c)', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/functions.pl line 752
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4a9a954)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Stack trace:
Assertion failed!
 at C:/BOT/BOT/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('') called at src/InventoryList.pm line 273
	InventoryList::remove('InventoryList::Inventory=HASH(0x717b454)', 'HASH(0x602d0b4)') called at src/Misc.pm line 1905
	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 2849
	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', 'HASH(0x60394a4)') called at src/Network/PacketParser.pm line 276
	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', '\x{fa}\x{7}\x{1}\x{0}\x{b}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/Network/Receive.pm line 472
	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', '\x{fa}\x{7}\x{1}\x{0}\x{b}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/Network/PacketParser.pm line 410
	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', 'Network::MessageTokenizer=HASH(0x3c5188c)', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/functions.pl line 752
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4a9a954)') called at openkore.pl line 97
	main::__start() called at start.pl line 136
 at C:/BOT/BOT/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('') called at src/InventoryList.pm line 273
	InventoryList::remove('InventoryList::Inventory=HASH(0x717b454)', 'HASH(0x602d0b4)') called at src/Misc.pm line 1905
	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 2849
	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', 'HASH(0x60394a4)') called at src/Network/PacketParser.pm line 276
	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', '\x{fa}\x{7}\x{1}\x{0}\x{b}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/Network/Receive.pm line 472
	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', '\x{fa}\x{7}\x{1}\x{0}\x{b}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/Network/PacketParser.pm line 410
	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)', 'Network::MessageTokenizer=HASH(0x3c5188c)', 'Network::Receive::kRO::RagexeRE_2015_11_25d=HASH(0x6d7f90c)') called at src/functions.pl line 752
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4a9a954)') called at openkore.pl line 97
	main::__start() called at start.pl line 136`

**Comment by Razalka** [comment]
[errors.txt](https://github.com/OpenKore/openkore/files/2527670/errors.txt)

**Comment by alisonrag** [comment]
related to #469
