### ISSUE TITLE
Talknpc when many NPCs standing on the same cell

### ISSUE THREAD

**Issue by deezar** [OpenKore/openkore#247]
When there are more than one NPC standing on a cell, `talknpc` command will only talk to the first npc in the NPC list (`nl`). This is a problem if you want to talk the other NPC than the first one.

`talk` command cannot fully substitute because it doesn't support NPC conversation codes.

Possible solution is adding NPC number (from `nl`) support to the `talknpc` command.
Example: `talknpc <NPC#> <NPC conversation codes>`

**Comment by itsrachelfish** [comment]
Cool idea, but I'm curious what server you're playing on that has multiple NPCs stacked on top of each other?

**Comment by deezar** [comment]
I've seen several times in iRO servers.
A visible NPC stacked under an invisible NPC making bot unable to initiate `talknpc` sequences.

**Comment by itsrachelfish** [comment]
@deezar Good to know. I play on iRO as well, can you give some examples so we can test?

Exact maps / coordinates would be very helpful. Thanks! :+1:

**Comment by cydh** [comment]
idRO has some after the server merger, some Kafras are stacked.

**Comment by farrainbow** [comment]
It's not the best idea to use the number from `nl` to specify NPC since it's not permanent. What about using NPC's name?

Also if some NPCs are invisible then maybe we can give priority to the one which is visible. Which NPCs exacly have this problem?

**Comment by flacrasec** [comment]
@farrainbow I often use the nl command then the number of npc when I manually using openkore so this is a no fail situation, but when you write a macro often the location is needed then this situation is kind of troublesome.

**Comment by farrainbow** [comment]
So can we have some examples?

**Comment by flacrasec** [comment]
sorry I personally never experienced the issue I was just wondering if happened, but I dont Understando why the examples did not show up.

**Comment by c4c1n6kr3m1** [comment]
i remember the   orc lady valentine event years ago

**Comment by Henrybk** [comment]
Now you can add many npc steps into talk command and it will not talk to invisible npcs

**Comment by deezar** [comment]
@Henrybk 
Can you clarify?
From wiki the talknpc command still looks the same.
http://openkore.com/index.php/Talknpc

There's a situation where multiple NPCs stack over a single cell (intentionally or not). And sometimes there're visible and invisible NPCs.
I cannot remember exactly where is the example of such spot in official server but I could confirm there's. For private servers, they could intentionally do this to render talknpc command unusable.

**Comment by deezar** [comment]
@farrainbow 
Good suggestion. Using full or part of NPC name would be more favourable since `nl` doesn't guarantee npc order.
Example: `talknpc <NPC name> <NPC conversation codes>`

**Comment by Nipodemos** [comment]
use **talk** instead of talknpc
with talk you give the index of npc (which you can find using **nl** command
thus it has 0 chances of choosing the wrong npc

**Comment by deezar** [comment]
@Nipodemos 
In my opinion, `talk` cannot replace the convenience of `talknpc`. The first command is more suitable for manual play (XKore) rather than the latter command. Imagine an NPC which has 10 response dialogs, `talknpc` can usually complete it in one go while `talk` command requires 10 automacros to effectively complete dialogs.

**Comment by Nipodemos** [comment]
no, you do'nt need 10 automacros, you will just nedd 10 lines
you can use:
(assuming that you have **autoTalkCont 1**)
&talk(Kafra Employee)
talk resp 1
talk resp 3
talk resp 2
talk resp 0

on eventMacro it works perfectly.

**Comment by deezar** [comment]
@Nipodemos I have never tried eventMacro. I'll give it a try.
Just a question though, wouldn't it cause disconnection if macro sends `talk resp` too fast or just faster than your response dialog actually appears?

**Comment by Nipodemos** [comment]
This is not a problem, Openkore answer's on each 1.5 second , so no DC 
It will look for an answer only when it needs

And it will continue the conversation normally (the 'c' step) it is automatic when autoTalkCont is 1
