### ISSUE TITLE
cRO  poseidon notworking  It will be detected.

### ISSUE THREAD

**Issue by zzwyrmslayer** [OpenKore/openkore#2470]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

I follow all the instructions on http://openkore.com/index.php/Poseidon. But the Np will soon detect illegal procedures.What can i do？

**Comment by alisonrag** [comment]
poseidon is catching if you redirect the connection to a local ip
for example:
```
127.0.0.1
localhost
192.168.0.1
10.0.0.1
```

you need to use wan ip
like `177.434.344.123`

you can join and ask for help maybe other chinese people can help you:
https://discord.gg/X23aDu

**Comment by royluo1984** [comment]
hi sir can u please give me another invite to the discord?

**Comment by alisonrag** [comment]
@royluo1984 
https://discord.gg/55Hj73K

**Comment by polme32** [comment]
@alisonrag  Sir, I'm sorry. I'd like to visit the web page you provided, but I can't open it. Is there any other way?
