### ISSUE TITLE
Blank Quest List 

### ISSUE THREAD

**Issue by kamirie** [OpenKore/openkore#2472]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  Latest Git Download

* **Server**:  Private Server

* **Bug Report / Feature Request**: Support
 
* **Summary**: 
Good Day,
background : Im using kore to do some repeatable quests and it was working fine before. But the server I'm playing at updated server/client version. And now when I try to do the quests again, my quest lisrt is blank, I know I have quests because I was doing some manual quests earlier and left it for the kore to finish.

https://ibb.co/dkgC50

The old client is RagexeRE 2013 08 07

New Details : 
version 54
master_version 5
serverType kRO_RagexeRE_2015_10_29a <<- used PE viewer
charBlockSize 147
serverEncoding Western

http://forums.openkore.com/viewtopic.php?f=9&t=212806

**Comment by cydh** [comment]
exactly, openkore doesn't add `08fe` and `09f9` yet

**Comment by cydh** [comment]
sorry, just need to add this (assumed if you set it correctly by using kRO/RagexeRE\* server based
```diff
diff --git a/src/Network/Receive/kRO/RagexeRE_2015_05_13a.pm b/src/Network/Receive/kRO/RagexeRE_2015_05_13a.pm
index 1ef06f5b7..a00cb70f1 100644
--- a/src/Network/Receive/kRO/RagexeRE_2015_05_13a.pm
+++ b/src/Network/Receive/kRO/RagexeRE_2015_05_13a.pm
@@ -26,4 +26,7 @@ sub new {
 	return $self;
 }
 
+*parse_quest_update_mission_hunt = *Network::Receive::parse_quest_update_mission_hunt_v2;
+*reconstruct_quest_update_mission_hunt = *Network::Receive::reconstruct_quest_update_mission_hunt_v2;
+
 1;
```

**Comment by Fadreus** [comment]
@cydh I'm not sure if he would understand what you just wrote. He don't even quite understand what I'm referring to. :neutral_face:

**Comment by Fadreus** [comment]
@cydh I'm not sure if he would understand what you just wrote. He don't even quite understand what I'm referring to. :neutral_face: 

Well, I'm not good with words too.

**Comment by Fadreus** [comment]
[Seems solved. ](http://forums.openkore.com/viewtopic.php?f=9&t=212806&start=20):neutral_face:

**Comment by Fadreus** [comment]
[Solved. ](http://forums.openkore.com/viewtopic.php?f=9&t=212806&start=20):neutral_face:

**Comment by Fadreus** [comment]
[Solved. ](http://forums.openkore.com/viewtopic.php?f=9&t=212806&start=20)

**Comment by Fadreus** [comment]
[Solved. ](http://forums.openkore.com/viewtopic.php?f=9&t=212806&start=20):neutral_face: 
Can close this.

**Comment by Fadreus** [comment]
[Solved. ](http://forums.openkore.com/viewtopic.php?f=9&t=212806&start=20)
Can close this.

**Comment by cydh** [comment]
should make a fix commit before closing this xD

**Comment by Fadreus** [comment]
The fix I recommended to him is adding this on his sT.
```
'09F8' => ['quest_all_list3', 'v3 a*', [qw(len count unknown message)]],
```
```
sub quest_all_list3 {
	my ( $self, $args ) = @_;

	# Long quest lists are split up over multiple packets. Only reset the quest list if we've switched maps.
	our $quest_generation      ||= 0;
	our $last_quest_generation ||= 0;
	if ( $last_quest_generation != $quest_generation ) {
		$last_quest_generation = $quest_generation;
		$questList             = {};
	}

	my $i = 0;
	while ( $i < $args->{RAW_MSG_SIZE} - 8 ) {
		my ( $questID, $active, $time_start, $time, $mission_amount ) = unpack( 'V C V2 v', substr( $args->{message}, $i, 15 ) );
		$i += 15;

		$questList->{$questID}->{active} = $active;
		debug "$questID $active\n", "info";

		my $quest = \%{ $questList->{$questID} };
		$quest->{time_start}     = $time_start;
		$quest->{time}           = $time;
		$quest->{mission_amount} = $mission_amount;
		debug "$questID $time_start $time $mission_amount\n", "info";

		if ( $mission_amount > 0 ) {
			for ( my $j = 0 ; $j < $mission_amount ; $j++ ) {
				my ( $conditionID, $mobID, $count, $goal, $mobName ) = unpack( 'V x4 V x4 v2 Z24', substr( $args->{message}, $i, 44 ) );
				$i += 44;
				my $mission = \%{ $quest->{missions}->{$conditionID} };
				$mission->{conditionID} = $conditionID;
				$mission->{mobID}       = $mobID;
				$mission->{count}       = $count;
				$mission->{goal}        = $goal;
				$mission->{mobName_org} = $mobName;
				$mission->{mobName}     = bytesToString( $mobName );
				debug "- $mobID $count / $goal $mobName\n", "info";
			}
		}
	}
}
```
IDK much about sT but I thought it should be properly added on Sakexe so I just suggest him to put that on which ever server he's playing. He claimed to be solved but not sure which fix he's applying that is working.

I thought sctnightcore who like to update for p. server. :stuck_out_tongue:

**Comment by Fadreus** [comment]
The fix I recommended to him is adding 09F8 on his sT.
IDK much about sT but I thought it should be properly added on Sakexe so I just suggest him to put that on which ever server he's playing. He claimed to be solved but not sure which fix he's applying that is working.

I thought sctnightcore who like to update for p. server. :stuck_out_tongue:

**Comment by Fadreus** [comment]
The fix I recommended to him is adding 09F8 on his sT.
IDK much about sT but I thought it should be properly added on Sakexe so I just suggest him to put that on which ever server he's playing. He claimed to be solved but not sure which fix he's applying that is working.

I thought sctnightcore who like to update for p. server. stuck_out_tongue
