### ISSUE TITLE
4 game RusRo openkore

### ISSUE THREAD

**Issue by AugustaY** [OpenKore/openkore#2478]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by AugustaY** [comment]
hi all. Sorry I try make config OpenKore for Rus Server 4Game, but cant, it's don't work. Maybe someting can help me?

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/47950744-8fc36780-df91-11e8-9efc-e6aaad06be77.png)

**Comment by alisonrag** [comment]
Use #2272
