### ISSUE TITLE
tRO connectivity, #221 duplicate

### ISSUE THREAD

**Issue by lianstohim** [OpenKore/openkore#248]
![hmac](https://cloud.githubusercontent.com/assets/22186736/18741091/78a700a4-80d7-11e6-80a7-3bec96d32113.png)
 
help me plz bro!

regard, bro  
thxs  a lot

**Comment by ExynosA10** [comment]
help me plz.......

**Comment by soasdty** [comment]
me tooo 
plz Help me!!!!!!

**Comment by nutanuta1** [comment]
please help  T^T

**Comment by soasdty** [comment]
99 เปอรเซน เป็นคนไทยชัวๆ 555

**Comment by nutanuta1** [comment]
@soasdtry   ไม่สนใจอะไรเลยก็ รอต่อไปนะ

**Comment by rabbitgreen** [comment]
To all Thai..

เขาบอกให้ไปโพสไว้ในกระทู้เดียวว .. มาโพสกันอย่างนี้ เด๋วเขาก็รำคาญกันอีก .. 

เขาให้ไปโพสไว้ในกระทู้ #221

รู้ว่าบอทกันไม่ได้ ผมก็ไม่ได้ แต่อยากให้ช่วยเคารพกฎที่เขามีกันหน่อยครับ


โปรดเข้าใจด้วย ผมกลัวว่าพวกคนที่พัฒนาเขาจะรำคาญแล้วจะไม่ช่วยนะครับ  เว็ปนี้ของ ตปท นะ ไม่ใช่ของคนไทยอย่างเดียว  =.=

**Comment by nuaofzaa** [comment]
@rabbitgreen i think so. Haha

**Comment by deava** [comment]
Can you close or delete post?

**Comment by carisbero** [comment]
hmac map server chang again

**Comment by snimbusser** [comment]
Fu*k u!! Hurry tell me!!! 
I what bot!! Fu*k

**Comment by game1332612** [comment]
tackup

**Comment by Cozzie** [comment]
All tRO discussion refer to #221.
