### ISSUE TITLE
EventMacro Timeout Random

### ISSUE THREAD

**Issue by eprabotmesmo** [OpenKore/openkore#2485]
hello have some way to use eventMacro with random timeout?
example

$timeout = int rand(21)
automacro start {
BaseLevel > 0 
priority -1
 exclusive 1
 timeout $timeout
 call {
log is running
 }
}

**Comment by sctnightcore** [comment]
http://openkore.com/index.php/EventMacro
![image](https://user-images.githubusercontent.com/23263315/48091216-9c6ae880-e23b-11e8-856c-8472bba453df.png)

$timeout = int rand(21) // wrong

**Comment by Nipodemos** [comment]
i'll test this now

**Comment by Nipodemos** [comment]
you can't. eventMacro doesnt support this

you can use a workaround, but it is not good...

```perl
automacro start {
    BaseLevel > 0
    priority -1
    exclusive 1
    call {
        $var = &rand(1,10)
        pause $var
        log is running
    }
}
```

**Comment by c4c1n6kr3m1** [comment]
i don't use eventMacro yet
but, for old macro plugin , let say you have automacro gotostore
you can change the timeout because it is stored on $::Macro::Data::automacro{gotostore}{timeout}

for this event macro plugin, i don't know
looks like variable $eventMacro inside eventMacro::Data

**Comment by c4c1n6kr3m1** [comment]
$eventMacro inside package eventMacro::Data ????

**Comment by c4c1n6kr3m1** [comment]
in old macro plugin you have access to the parameters
but in eventMacro ....:confused:

**Comment by eprabotmesmo** [comment]
> you can't. eventMacro doesnt support this
> 
> you can use a workaround, but it is not good...
> 
> ```perl
> automacro start {
>     BaseLevel > 0
>     priority -1
>     exclusive 1
>     call {
>         $var = &rand(1,10)
>         pause $var
>         log is running
>     }
> }
> ```

openkore pauses all actions

**Comment by Fadreus** [comment]
I wonder why not using the forum.
I see this thread has no benefits here for openkore. :thinking:
Anyway, the solution is just to overrideAI

```perl
automacro start {
    BaseLevel > 0
    priority -1
    run-once 1
    overrideAI 1 <---put here
    call {
        set overrideAI 1 <---or put here, any
        $var = &rand(1,10)
        pause $var
        log is running
        release all
    }
}
