### ISSUE TITLE
multi xkore

### ISSUE THREAD

**Issue by claudio17** [OpenKore/openkore#2505]
hello ....... my server is Iro chaos

I have this problem
Critical Error: Dual login prohibited - Someone trying to login because I want to connect several bots
I read and say that with the xkore 3 but I could not find any well-explained guide or some theme of this, and the one I saw is to duplicate the openkore folder

someone could help me out

**Comment by ya4ept** [comment]
http://openkore.com/index.php/Run_multiple_bots_from_the_same_.exe

**Comment by claudio17** [comment]
I do not know, I already did that but the problem is that it does not let connect more than one bots I bounced the error mentioned above

**Comment by alisonrag** [comment]
You are using the same config txt in your profiles folder make sure that you have changed login and password in every profile folder

**Comment by claudio17** [comment]
look at this is what happens when the second xkore works, the first work perfect but hardly
![captura](https://user-images.githubusercontent.com/30068733/48666778-3893bb80-ea96-11e8-98f9-d46c9afcb261.JPG)

**Comment by claudio17** [comment]
finally I'm like this - control = "supernovice" --logs = "supernovice" / logs thanks
