### ISSUE TITLE
Incoming data left in the buffer

### ISSUE THREAD

**Issue by kumulo123** [OpenKore/openkore#2514]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
i have the last version of openkore i downloaded it today
* **Server**: 
private server
* **Bug Report / Feature Request**:

* **Summary**:
Hi everyone i am trying to bot on a new server dans i am still getting this issue : 

<img width="488" alt="capture d ecran 2018-11-22 a 17 17 26" src="https://user-images.githubusercontent.com/31310913/48913550-648db300-ee81-11e8-8a81-b139fed02fa7.png">
<img width="670" alt="capture d ecran 2018-11-22 a 17 17 37" src="https://user-images.githubusercontent.com/31310913/48913551-648db300-ee81-11e8-9a66-127a11cb23da.png">

please telle me all of the files that you need to understand the problem i'll send them

Thank you very much

**Comment by sctnightcore** [comment]
server.txt?

**Comment by kumulo123** [comment]
hi here is my [servers.txt](https://github.com/OpenKore/openkore/files/2608924/servers.txt)

but how can i give you my clientdate ? i dont know what it is..

thanks for your help

**Comment by kumulo123** [comment]
i don't know if it will help, but while opening the Ragnarok.exe with text editor, I found this..
<img width="670" alt="capture d ecran 2018-11-22 a 19 37 58" src="https://user-images.githubusercontent.com/31310913/48917219-51cdab00-ee8e-11e8-8e71-93205a86b85e.png">

**Comment by Fadreus** [comment]
http://openkore.com/index.php/ServerType

If you do your research properly, opening ragexe.exe with text editor is really unthinkable.

**Comment by c4c1n6kr3m1** [comment]
put pauseCharLogin 1 on your servers.txt

**Comment by c4c1n6kr3m1** [comment]
try put pauseCharLogin 1 on your servers.txt , may be it will work

**Comment by kumulo123** [comment]
> http://openkore.com/index.php/ServerType
> 
> If you do your research properly, opening ragexe.exe with text editor is really unthinkable.

i've tried to get the PE Viewer but the link is dead...

**Comment by kumulo123** [comment]
> try put pauseCharLogin 1 on your servers.txt , may be it will work

now i am getting this : 

<img width="594" alt="capture d ecran 2018-11-23 a 10 00 00" src="https://user-images.githubusercontent.com/31310913/48932959-0f948000-ef07-11e8-9161-b1a4ddb93dc4.png">

**Comment by sctnightcore** [comment]
> PE

find pe view in google .

**Comment by kumulo123** [comment]
> > PE
> 
> find pe view in google .

Hi, so i found it then I got this : 
<img width="412" alt="capture d ecran 2018-11-24 a 18 12 53" src="https://user-images.githubusercontent.com/31310913/48970427-b6b30d80-f014-11e8-8684-967494a80473.png">

so i tried : 
`serverType kRO_RagexeRE_2016_04_14b`
and also
`serverType kRO_RagexeRE_2016_03_02b`

And I am getting the same exact error..

**Comment by c4c1n6kr3m1** [comment]
try change inside control\timeouts.txt
char_login_pause 5

**Comment by c4c1n6kr3m1** [comment]
you connect to map server
but still receive chars list, it's not normal

try change this on control\timeouts.txt
char_login_pause 7

than if still failed to connect to map server , may be it has protection
may be your serverType, the sendCryptKeys problem

last, use sniffer, try to compare the datas sent by client versus openkore
that's all i can say, because i don't play PS

**Comment by kumulo123** [comment]
> try change this on control\timeouts.txt
> char_login_pause 7

Still the same problem :/

> than if still failed to connect to map server , may be it has protection

what can is do if there is a protection ?

> may be your serverType

maybe what peek told me was wrong because there is not exactly a launcher, if you want to run the game you need to use the patcher, if you run the Ragnarok.exe directly you are getting an error..

>the sendCryptKeys problem

Ok, how can i found them please ?

> last, use sniffer, try to compare the datas sent by client versus openkore

Is there a tutorial for this please ?

> that's all i can say, because i don't play PS

What is PS

Thank you very much for your help

**Comment by sctnightcore** [comment]
Can u upload .exe ? 
i can help u but i'm lazy

**Comment by kumulo123** [comment]
> You might wanna try google search result related to `0> 81 00 08`
> I found the key but I don't know the lock coz I stopped playing PS long time ago.
> Some said it worked, the rest don't come back to give feedback.
> 
> So, good luck with the hint.

Yes that's what i am doing.. but I did not found anything beside this : https://github.com/OpenKore/openkore/issues/1761

So if you guys understand what happend there or **sctnightcore** if you remember what i need to do..

Thank you

**Comment by kumulo123** [comment]
> Can u upload .exe ?
> i can help u but i'm lazy

Haha i'm lazy too but pleaaaase help me 
here is the launcher and the patcher :
[Archive.zip](https://github.com/OpenKore/openkore/files/2612977/Archive.zip)

**Comment by sctnightcore** [comment]
clientdate is 20180620 ?

**Comment by Fadreus** [comment]
![picard](https://user-images.githubusercontent.com/32188494/48979546-9c9e2b80-f0f7-11e8-8b50-ad6f44e4d6a2.jpg)

**Comment by kumulo123** [comment]
![tenor](https://user-images.githubusercontent.com/31310913/48979822-f63b3180-f0c8-11e8-8d41-ba669ac9fcad.gif)

**Comment by sctnightcore** [comment]
Can u check .exe from process ? 
ex. 

![image](https://user-images.githubusercontent.com/23263315/48980140-b17abf00-f0f7-11e8-9e9c-45d6b28e4ab2.png)
![image](https://user-images.githubusercontent.com/23263315/48980143-b770a000-f0f7-11e8-8fdc-6604613109c0.png)

**Comment by kumulo123** [comment]
![capture d ecran 2018-11-25 a 16 41 40 copie](https://user-images.githubusercontent.com/31310913/48980412-32729000-f0d1-11e8-9c70-a971057c59fd.jpg)

wich gives me the .exe that is not openable by itself...


> if clientdate is 2018 .
> made servertype with uself .


what is uself ? i did not understand sorry

**Comment by sctnightcore** [comment]
lolll 

Clientdate is 2018 
#2101

peek from 4144
https://gitlab.com/4144/peek

**Comment by kumulo123** [comment]
Thank you for your answers

> Clientdate is 2018
> #2101

Ok, i've read it but I dont know what to do with the **clif_shuffle.hpp** and the **packets_shuffle_main.h** that you gave to the guy on this page...

> peek from 4144
> https://gitlab.com/4144/peek

<img width="374" alt="capture d ecran 2018-11-25 a 17 48 30" src="https://user-images.githubusercontent.com/31310913/48981174-e7f61100-f0da-11e8-83b2-6a66113ad8f6.png">

**Comment by sctnightcore** [comment]
https://pastebin.com/eVyS5c06

**Comment by kumulo123** [comment]
Ok don't ask me why but now PEEK worked from my mac...

[PacketLengths_20180620.txt](https://github.com/OpenKore/openkore/files/2613243/PacketLengths_20180620.txt)

What do i need to do now

**Comment by kumulo123** [comment]
ah lol...

**Comment by kumulo123** [comment]
so what do i need to do with your file please ?

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/blob/master/src/Network/Receive/kRO/RagexeRE_2017_12_27a.pm
https://github.com/OpenKore/openkore/blob/master/src/Network/Send/kRO/RagexeRE_2017_12_27a.pm
1.**Need to change head packet in send**
2.**You can see head packet in peek and herc / rA.**

PEEK 
![image](https://user-images.githubusercontent.com/23263315/48981736-0aece900-f10c-11e8-9e55-7966aafa8111.png)
https://gist.github.com/sctnightcore/da3d5b0b6dc7f1e950d66789cb97451d

**Comment by kumulo123** [comment]
I did change all the shuffle packets but i get the same error...
is that what you told me to do ?
[RagexeRE_2017_12_27a.txt](https://github.com/OpenKore/openkore/files/2613544/RagexeRE_2017_12_27a.txt)

**Comment by kumulo123** [comment]
By the way this is my server in the server.txt

`[PixelRo]
ip 91.121.168.83
port 6900
master_version 31
version 55
recvpackets recvpackets.txt
pauseCharLogin 1
serverType kRO_RagexeRE_2017_12_27a
serverEncoding Western
charBlockSize 155
addTableFolders pserver/ggRO`

**Comment by sctnightcore** [comment]
> By the way this is my server in the server.txt
> 
> <img alt="capture d ecran 2018-11-25 a 23 56 52" width="283" src="https://user-images.githubusercontent.com/31310913/48985198-cfebb500-f10d-11e8-9335-c1ee8893fd1a.png">

try del recvpacket.txt in tables/pServer/ggRO 
and copy recvpacket[client2018] to tables/pServer/ggRO

**Comment by sctnightcore** [comment]
> where do i find recvpacket[client2018] please ?
read . How to use PEEK to openkore ! 
http://forums.openkore.com/viewtopic.php?f=6&t=207278

**Comment by kumulo123** [comment]
I'm trying very hard from this morning to launch the perl program that is on this page but it doesnt work is there an other way to convert the file that PEEK gives to a recvpacket.txt ?

**Comment by sctnightcore** [comment]
> I'm trying very hard from this morning to launch the perl program that is on this page but it doesnt work is there an other way to convert the file that PEEK gives to a recvpacket.txt ?


try it 
[recvpackets.txt](https://github.com/OpenKore/openkore/files/2616457/recvpackets.txt)

**Comment by kumulo123** [comment]
thanks you so much finally it works !!!
thank you sctnightcore, thank you everyone

there is juste one last thing, all the monsters are unknown etc.. maybe you have a fix ??
<img width="438" alt="capture d ecran 2018-11-26 a 18 49 10" src="https://user-images.githubusercontent.com/31310913/49028856-07a93a00-f1ac-11e8-938d-739880080e8a.png">

**Comment by nizdi** [comment]
IDK if it's solve, but this might help: https://blog.highker-service.web.id/2016/06/27/openkore-packet-parser-unknown-switch-0915/

Got it from here: http://openkorebrasil.org/index.php?/topic/3007-tutorial-erro-0-81-00-08/

**Comment by alisonrag** [comment]
#2569
