### ISSUE TITLE
mon_control.txt file is not correctly parsed

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#2518]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: ctime:2018_11_24
* **Server**: localhost
* **Bug Report / Feature Request**: Bug Report
* **Summary**: see actual mon_control.txt it contains the following lines (with comments):
> 1511 -1 1 0 #Amon Ra

our current parser (parseMonControl) does not work properly. At the output we get:
```
$key = 1511 
{$key}{attack_auto} = -1 
{$key}{teleport_auto} = 1 
{$key}{teleport_search} = 0 
{$key}{skillcancel_auto} = #amon 
{$key}{attack_lvl} = ra
```
need to fix parser

**Comment by alisonrag** [comment]
this is a problem in every single control file, if you do this:
config.txt:
```
username myaccount # account here
```
and try to get the value:
$config{'username'} will be equal to:  `myaccount # account here`

**Comment by Nipodemos** [comment]
on mon_control.txt, items_control and shop.txt we could simply put some code to ignore what come after `#`
but on config.txt this is not possible

**Comment by lututui** [comment]
Why not? @Nipodemos

**Comment by c4c1n6kr3m1** [comment]
remember, reactOnNPC plugin use the "#"

**Comment by c4c1n6kr3m1** [comment]
as a reminder , reactOnNPC plugin use the "#"

**Comment by Nipodemos** [comment]
@lututui sorry i read the code wrongly, it is possible

**Comment by lututui** [comment]
reactOnNPC makes this very annoying to fix. Just adding #(\d+)~(\d+) as a valid syntax to the config parser is a workaround. Do we know of any other plugins that use '#' as part of their syntax? Mainly those ones inside [plugins](https://github.com/OpenKore/openkore/tree/master/plugins) and [plugins/needs-review](https://github.com/OpenKore/openkore/tree/master/plugins/needs-review)
