### ISSUE TITLE
Gepard Shield

### ISSUE THREAD

**Issue by puiuii** [OpenKore/openkore#252]
Server Gepard Shield
Hello Can you help or advice about Bot see monter/player are NPC Bot x3 mode
Bots walk, but do not attack monsters.

![gepard222](https://cloud.githubusercontent.com/assets/20508548/18820044/0a360f4e-83c4-11e6-98bd-570f974004cb.png)

**Comment by AsakuraTK** [comment]
![capture](https://cloud.githubusercontent.com/assets/20513397/18821436/4674e870-83d0-11e6-8e70-01e4789edff8.JPG)

Refer from #251

**Comment by k1nt4r0** [comment]
@puiuii hey sir, how u do that?
u even can login with gepard protection?

**Comment by eduardomoroni** [comment]
I know you don't support private servers, But what's wrong with sharing knowledge over this subject?
