### ISSUE TITLE
what is "47 04"?

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#2524]
## ------------------ Openkore Issues Template ------------------

#1735  I try this ,and worked!

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by Fadreus** [comment]
#1842

**Comment by Fadreus** [comment]
#1842 

What version are you using? :thinking:

**Comment by sctnightcore** [comment]
Openkore version git: ?

**Comment by lututui** [comment]
Which server?

**Comment by hubertyang88** [comment]
how to check the version ? newest version and the version of 2017.12 have same problem

**Comment by hubertyang88** [comment]
if send 7D 00 , server will disconnect

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#things-to-know

> Before submitting an issue, ensure you are running the latest commit on branch.

:point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: 

>how to check the version ? newest version and the version of 2017.12 have same problem, server is cRo

ATM almost December 2018, entering 2019.
If last time you download is at 2017, download new one & try again.
Always use latest version before reporting.

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#things-to-know

> Before submitting an issue, ensure you are running the latest commit on branch.

:point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2: :point_up_2:

**Comment by sctnightcore** [comment]
@hubertyang88  download new openkore . 

@lututui has already fixed it.
![image](https://user-images.githubusercontent.com/23263315/49226681-e3529500-f419-11e8-9cc5-09ebb37e2858.png)
