### ISSUE TITLE
my openkore startexe run very slow can anyone help?

### ISSUE THREAD

**Issue by picolojunior** [OpenKore/openkore#2529]
I have same issue with this one #1634

where my start.exe load very slow while wxstart have normal speed.

I did not understand how to fix it from #1634

this happen when I re install the window

Can someone explain to me please thank

**Comment by alisonrag** [comment]
this is a perl issue with windows, you can run openkore in powershell window and make the perl a little bit faster

**Comment by picolojunior** [comment]
Could you teach me how to  run openkore in powershell window, i try to search in google but I don t find the way to do it at all thank man.

**Comment by hubertyang88** [comment]
1. install 
http://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0.msi
2. run perl cmd , and type
ppm install Win32::Console
3.  and type "your openkoredir"\openkore.pl 
or create a bat file 
"C:\Windows\SysWOW64\cmd.exe /k perl "your openkoredir"\openkore.pl "

**Comment by Fadreus** [comment]
> "your openkoredir"\openkore.pl " it said the directory name is invalid. So sad haha

![image](https://user-images.githubusercontent.com/32188494/49335659-92ff5100-f62c-11e8-94de-24a9e6b4fe31.png)

**Comment by c4c1n6kr3m1** [comment]
https://media.tenor.com/images/5ba04a413127ad765f9650aa915528aa/tenor.gif
>when type "your openkoredir"\openkore.pl it said thesystem can not find the path specific.

https://media.tenor.com/images/46ce8de5a62f6484f7dbf52934b6fcd5/tenor.gif

**Comment by c4c1n6kr3m1** [comment]
<img src="https://media.tenor.com/images/5ba04a413127ad765f9650aa915528aa/tenor.gif"/>

>when type "your openkoredir"\openkore.pl it said thesystem can not find the path specific.

<img src="https://media.tenor.com/images/46ce8de5a62f6484f7dbf52934b6fcd5/tenor.gif"/>

**Comment by c4c1n6kr3m1** [comment]
<img src="https://media.tenor.com/images/5ba04a413127ad765f9650aa915528aa/tenor.gif"/><img src="https://media.tenor.com/images/46ce8de5a62f6484f7dbf52934b6fcd5/tenor.gif"/>

**Comment by c4c1n6kr3m1** [comment]
<img src="https://media.tenor.com/images/5ba04a413127ad765f9650aa915528aa/tenor.gif"/><img src="https://media.tenor.com/images/46ce8de5a62f6484f7dbf52934b6fcd5/tenor.gif"/><img src="https://media.tenor.com/images/1c64a112f215793cda98d726a9f06507/tenor.gif"/>

**Comment by alisonrag** [comment]
1 -  go to openkore folder
![image](https://user-images.githubusercontent.com/10372732/49339303-d3ec6b00-f616-11e8-9720-e1e9baab42a8.png)

2 - press shift + mouse right buttom
![image](https://user-images.githubusercontent.com/10372732/49339311-e666a480-f616-11e8-9f31-ac1be7901366.png)

3 - select "open PowerShell here"
![image](https://user-images.githubusercontent.com/10372732/49339319-01d1af80-f617-11e8-9db1-716767229fdb.png)

4 - type in powershell window: "perl .\openkore.pl" and press enter
![image](https://user-images.githubusercontent.com/10372732/49339326-23329b80-f617-11e8-9d1f-a5fd8625b905.png)

5 - see the magic:
![image](https://user-images.githubusercontent.com/10372732/49339343-49583b80-f617-11e8-939c-098f607e116c.png)

you can try to find for powershell in start menu
![image](https://user-images.githubusercontent.com/10372732/49339352-67be3700-f617-11e8-959d-c09251222d74.png)

**Comment by picolojunior** [comment]
@alisonrag   thank for taking your time to help bro but it still not run just wonder what is wrong with my window. Here is the result after I follow your method
![11](https://user-images.githubusercontent.com/22233405/49339945-e3e26a00-f66b-11e8-9a5b-bde4b33344ec.PNG)

**Comment by picolojunior** [comment]
Thank for helping. I just re install window to 8.1 instead of 10.
Now it run smoothly.

**Comment by bigspender143** [comment]
Hi, how can I run multiple bot clients using powershell? lets say that my exe name is vendor01 and so on? Thanks!

**Comment by Fadreus** [comment]
@bigspender143 
http://www.openkore.com/index.php/Run_multiple_bots_from_the_same_.exe?hc_location=ufi
http://openkore.com/index.php/Profiles
https://www.youtube.com/watch?v=ixTO5d-tn54

Did you know? You can just use google. :no_mouth: 
![image](https://user-images.githubusercontent.com/32188494/54617621-8fd58700-4a9c-11e9-82e0-d6a85c7aeaca.png)

Plus, ask at IRC or Forum.
Not github.

**Comment by bigspender143** [comment]
You read my comment out of the context, what i mean running this(see photo)
using the command in powershell.

**Comment by Xropsha** [comment]
Any fix around? Got exact same issue after reinstalled my windows.

**Comment by hubertyang88** [comment]
@bigspender143 Try this 
C:\Users\Administrator\Desktop\openkore\wxstart.exe --control=openkore\Profiles\vendor1\Config
in this example , openkore is in desktop , you should change the path
you also can create shortcut use this

**Comment by ya4ept** [comment]
1) just run start.exe
2) Right-click the Title bar and select Properties:
![Properties](https://www.isunshare.com/images/article/windows-10/enable-use-legacy-console-for-command-prompt-in-windows-10/open-cmd-properties.png)
3)  In Options, choose Use legacy console (requires relaunch) and tap OK:
![Use legacy console](https://www.isunshare.com/images/article/windows-10/enable-use-legacy-console-for-command-prompt-in-windows-10/select-use-legacy-console-in-options.png)

**Comment by ya4ept** [comment]
[FAQ: OpenKore_start.exe_run_very_slow](http://openkore.com/index.php/Frequently_Asked_Questions#OpenKore_start.exe_run_very_slow_.28windows_10.29)
