### ISSUE TITLE
botting the rathena offline project

### ISSUE THREAD

**Issue by royluo1984** [OpenKore/openkore#2533]
## ------------------ Openkore Issues Template ------------------

Hi ppl,
There is a very interesting RO offline project launched in rathena

Link:
https://rathena.org/board/topic/109823-ragnarok-online-complete-offline-server-client-pack-2018-make-your-ro-server-in-less-then-5-minutes/

which allows you play RO offline.
It is very funny but it gets bored very quickly as solo can be very boring
I want to add some AI teammates which controlled by openkore.

However, I get this error --->There are no characters on this account.

The time stamp for the game client is May 29, 2018

here are the servers info
#####################
[iRO]
ip 127.0.0.1
port 6900
master_version 4 #(I can't peek the game client this number is just a guess)
version 51 #(I can't peek the game client this number is just a guess)
serverType iRO_Renewal #(I can't peek the game client this number is just a guess)
serverEncoding Western
addTableFolders iRO/Renewal;iRO
charBlockSize 148 #(I can't peek the game client this number is just a guess)
charDeleteDateType 1 #(I can't peek the game client this number is just a guess)
sendCryptKeys 0x79983A07, 0x11F01662, 0x03BD32BA #(I can't peek the game client this number is just a guess)
####################

and this is the console debug log， I have created two chars which name are "test" and "testchar"
I can see these two chars are in the debug log, but still I get that error.
please assist

```
[Dec 04 22:42:04 2018.62] [eventMacro] No control/eventMacros.txt file was found. Plugin disabled.
[Dec 04 22:42:04 2018.64] [eventMacro] Plugin unloading
[Dec 04 22:42:04 2018.67] Plugin eventMacro unloaded.
[Dec 04 22:42:04 2018.69] 
Generating session Admin Password...
[Dec 04 22:42:04 2018.73] 
[Dec 04 22:42:04 2018.78] Checking for new portals... [Dec 04 22:42:04 2018.89] none found

[Dec 04 22:42:04 2018.94] 
[Dec 04 22:42:05 2018.24] Connecting to Account Server...
[Dec 04 22:42:05 2018.57] Connecting (127.0.0.1:6900)... [Dec 04 22:42:05 2018.88] connected
[Dec 04 22:42:05 2018.11] ================================================
>> Sent packet: 0064  [Account Server Login] [55 bytes]   Dec 04 22:42:05 2018
  0>  64 00 33 00 00 00 6C 75    6F 63 6F 6E 67 6F 00 00    d.3...luocongo..
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 31 32    ..............12
 32>  33 34 35 36 00 00 00 00    00 00 00 00 00 00 00 00    3456............
 48>  00 00 00 00 00 00 04                                  .......
[Dec 04 22:42:05 2018.14] ================================================
<< Received packet:      0AC4 [224 bytes]   Dec 04 22:42:05 2018
  0>  C4 0A E0 00 1B 49 2B 73    83 84 1E 00 50 B0 F1 50    .....I+s....P..P
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 01 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  7F 00 00 01 E9 17 72 41    74 68 65 6E 61 5F 52 45    ......rAthena_RE
 80>  4E 45 57 41 4C 5F 32 30    31 00 00 00 00 00 00 00    NEWAL_201.......
 96>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
112>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
128>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
144>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
160>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
176>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
192>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
208>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
[Dec 04 22:42:05 2018.16] ---------- Account Info ----------
Account ID: 2000003    83 84 1E 00
Sex:        Boy
Session ID: 1932216603 1B 49 2B 73
            1358016592 50 B0 F1 50

----------------------------------
[Dec 04 22:42:05 2018.19] ---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   rAthena_RENEWAL_201   0      127.0.0.1       6121
-----------------------------------------------------
[Dec 04 22:42:05 2018.22] Closing connection to Account Server
[Dec 04 22:42:05 2018.25] Disconnecting (127.0.0.1:6900)...[Dec 04 22:42:05 2018.27] disconnected
[Dec 04 22:42:05 2018.31] Connecting to Character Server...
[Dec 04 22:42:05 2018.34] Selected server: rAthena_RENEWAL_201
[Dec 04 22:42:05 2018.37] Connecting (127.0.0.1:6121)... [Dec 04 22:42:05 2018.39] connected
[Dec 04 22:42:05 2018.42] ================================================
>> Sent packet: 0065  [Character Server Login] [17 bytes]   Dec 04 22:42:05 2018
  0>  65 00 83 84 1E 00 1B 49    2B 73 50 B0 F1 50 00 00    e......I+sP..P..
 16>  01                                                    .
[Dec 04 22:42:05 2018.45] ================================================
<< Received packet:      082D [29 bytes]   Dec 04 22:42:05 2018
  0>  2D 08 1D 00 09 03 03 09    0F 00 00 00 00 00 00 00    -...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00             .............
[Dec 04 22:42:05 2018.48] ================================================
<< Received packet:      006B - Received characters from Game Login Server [337 bytes]   Dec 04 22:42:05 2018
  0>  6B 00 51 01 0F 09 0C 00    00 00 00 00 00 00 00 00    k.Q.............
 16>  00 00 00 00 00 00 00 00    00 00 00 F4 49 02 00 96    ............I...
 32>  00 00 00 00 00 00 00 00    00 00 00 11 00 00 00 00    ................
 48>  00 00 00 03 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 01 00 2D 00 00    .............-..
 80>  00 2D 00 00 00 0D 00 0C    00 96 00 00 00 01 00 00    .-..............
 96>  00 01 00 02 00 00 00 00    00 00 00 00 00 00 00 00    ................
112>  00 00 00 74 65 73 74 00    00 00 00 00 00 00 00 00    ...test.........
128>  00 00 00 00 00 00 00 00    00 00 00 01 01 01 01 15    ................
144>  01 00 00 01 00 69 7A 6C    75 64 65 5F 62 2E 67 61    .....izlude_b.ga
160>  74 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    t...............
176>  00 00 00 00 00 01 F5 49    02 00 00 00 00 00 00 00    .......I........
192>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 01 00    ................
208>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
224>  00 00 00 00 00 00 30 00    28 00 00 00 28 00 00 00    ......0.(...(...
240>  0B 00 0B 00 96 00 00 00    01 00 00 00 01 00 01 00    ................
256>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 74 65    ..............te
272>  73 74 76 68 61 72 00 00    00 00 00 00 00 00 00 00    stvhar..........
288>  00 00 00 00 00 00 01 01    01 01 01 01 01 00 01 00    ................
304>  69 7A 5F 69 6E 74 30 33    2E 67 61 74 00 00 00 00    iz_int03.gat....
320>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
336>  01                                                    .
[Dec 04 22:42:05 2018.50] ================================================
<< Received packet:      09A0 [6 bytes]   Dec 04 22:42:05 2018
  0>  A0 09 03 00 00 00                                     ......
[Dec 04 22:42:05 2018.53] ================================================
>> Sent packet: 09A1   [2 bytes]   Dec 04 22:42:05 2018
  0>  A1 09                                                 ..
[Dec 04 22:42:05 2018.56] ================================================
>> Sent packet: 09A1   [2 bytes]   Dec 04 22:42:05 2018
  0>  A1 09                                                 ..
[Dec 04 22:42:05 2018.58] ================================================
>> Sent packet: 09A1   [2 bytes]   Dec 04 22:42:05 2018
  0>  A1 09                                                 ..
[Dec 04 22:42:05 2018.61] ================================================
<< Received packet:      020D [4 bytes]   Dec 04 22:42:05 2018
  0>  0D 02 04 00                                           ....
[Dec 04 22:42:05 2018.64] ================================================
<< Received packet:      08B9 [12 bytes]   Dec 04 22:42:05 2018
  0>  B9 08 3C 75 00 00 83 84    1E 00 00 00                ..<u........
[Dec 04 22:42:05 2018.67] PIN code is correct.
[Dec 04 22:42:05 2018.69] There are no characters on this account.

```

**Comment by royluo1984** [comment]
> charBlockSize 155?

sorry still not working, here is the debug log for 155 blocksize

`Connecting to Account Server...
Connecting (127.0.0.1:6900)... connected
================================================
>> Sent packet: 0064  [Account Server Login] [55 bytes]   Dec 05 14:57:29 2018
  0>  64 00 2E 00 00 00 6C 75    6F 63 6F 6E 67 6F 00 00    d.....luocongo..
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 31 32    ..............12
 32>  33 34 35 36 00 00 00 00    00 00 00 00 00 00 00 00    3456............
 48>  00 00 00 00 00 00 04                                  .......
================================================
<< Received packet:      0AC4 [224 bytes]   Dec 05 14:57:29 2018
  0>  C4 0A E0 00 B7 23 D6 44    83 84 1E 00 42 18 16 3E    .....#.D....B..>
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 01 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  7F 00 00 01 E9 17 72 41    74 68 65 6E 61 5F 52 45    ......rAthena_RE
 80>  4E 45 57 41 4C 5F 32 30    31 00 00 00 00 00 00 00    NEWAL_201.......
 96>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
112>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
128>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
144>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
160>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
176>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
192>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
208>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
---------- Account Info ----------
Account ID: 2000003    83 84 1E 00
Sex:        Boy
Session ID: 1154884535 B7 23 D6 44
            1041635394 42 18 16 3E

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   rAthena_RENEWAL_201   0      127.0.0.1       6121
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (127.0.0.1:6900)...disconnected
Connecting to Character Server...
Selected server: rAthena_RENEWAL_201
Connecting (127.0.0.1:6121)... connected
================================================
>> Sent packet: 0065  [Character Server Login] [17 bytes]   Dec 05 14:57:30 2018
  0>  65 00 83 84 1E 00 B7 23    D6 44 42 18 16 3E 00 00    e......#.DB..>..
 16>  01                                                    .
================================================
<< Received packet:      082D [29 bytes]   Dec 05 14:57:30 2018
  0>  2D 08 1D 00 09 03 03 09    0F 00 00 00 00 00 00 00    -...............
 16>  00 00 00 00 00 00 00 00    00 00 00 00 00             .............
================================================
<< Received packet:      006B - Received characters from Game Login Server [337 bytes]   Dec 05 14:57:30 2018
  0>  6B 00 51 01 0F 09 0C 00    00 00 00 00 00 00 00 00    k.Q.............
 16>  00 00 00 00 00 00 00 00    00 00 00 F4 49 02 00 96    ............I...
 32>  00 00 00 00 00 00 00 00    00 00 00 11 00 00 00 00    ................
 48>  00 00 00 03 00 00 00 00    00 00 00 00 00 00 00 00    ................
 64>  00 00 00 00 00 00 00 00    00 00 00 01 00 2D 00 00    .............-..
 80>  00 2D 00 00 00 0D 00 0C    00 96 00 00 00 01 00 00    .-..............
 96>  00 01 00 02 00 00 00 00    00 00 00 00 00 00 00 00    ................
112>  00 00 00 74 65 73 74 00    00 00 00 00 00 00 00 00    ...test.........
128>  00 00 00 00 00 00 00 00    00 00 00 01 01 01 01 15    ................
144>  01 00 00 01 00 69 7A 6C    75 64 65 5F 62 2E 67 61    .....izlude_b.ga
160>  74 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    t...............
176>  00 00 00 00 00 01 F5 49    02 00 00 00 00 00 00 00    .......I........
192>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 01 00    ................
208>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
224>  00 00 00 00 00 00 30 00    28 00 00 00 28 00 00 00    ......0.(...(...
240>  0B 00 0B 00 96 00 00 00    01 00 00 00 01 00 01 00    ................
256>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 74 65    ..............te
272>  73 74 76 68 61 72 00 00    00 00 00 00 00 00 00 00    stvhar..........
288>  00 00 00 00 00 00 01 01    01 01 01 01 01 00 01 00    ................
304>  69 7A 5F 69 6E 74 30 33    2E 67 61 74 00 00 00 00    iz_int03.gat....
320>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
336>  01                                                    .
================================================
<< Received packet:      09A0 [6 bytes]   Dec 05 14:57:30 2018
  0>  A0 09 03 00 00 00                                     ......
================================================
>> Sent packet: 09A1   [2 bytes]   Dec 05 14:57:30 2018
  0>  A1 09                                                 ..
================================================
>> Sent packet: 09A1   [2 bytes]   Dec 05 14:57:30 2018
  0>  A1 09                                                 ..
================================================
>> Sent packet: 09A1   [2 bytes]   Dec 05 14:57:30 2018
  0>  A1 09                                                 ..
================================================
<< Received packet:      020D [4 bytes]   Dec 05 14:57:30 2018
  0>  0D 02 04 00                                           ....
================================================
<< Received packet:      08B9 [12 bytes]   Dec 05 14:57:30 2018
  0>  B9 08 A4 C1 00 00 83 84    1E 00 00 00                ............
PIN code is correct.
There are no characters on this account.
------------ Character selection ------------
#   Choice
0   Create a new character
------------------------
Please choose a character or an action.
---------------------------------------------
Enter your answer:`

**Comment by sctnightcore** [comment]
http://openkore.com/index.php/Connectivity_Guide
http://openkore.com/index.php/ServerType#Compilation_Date

**Comment by royluo1984** [comment]
> http://openkore.com/index.php/Connectivity_Guide
> http://openkore.com/index.php/ServerType#Compilation_Date
> 
> **FOR 2018 CLIENT**
> Now openkore still does not support it because I'm lazy.

T_T

the openkore managed connect to server, now just stuck at selecting char,
I tried blocksize from 144 - 200
not working at all.

is that because of the latest RO version using the different char selection layout?

screenshot
[![Screenshot from Gyazo](https://gyazo.com/b1144514ecf60f186fd662a5e698ab4d/raw)](https://gyazo.com/b1144514ecf60f186fd662a5e698ab4d)

**Comment by c4c1n6kr3m1** [comment]
the blocksize is 155
but your other servers info is questionable

http://openkore.com/index.php/Connectivity_Guide
http://openkore.com/index.php/ServerType

**Comment by royluo1984** [comment]
> the blocksize is 155
> but your other servers info is questionable
> 
> http://openkore.com/index.php/Connectivity_Guide
> http://openkore.com/index.php/ServerType

I tried to use kRO servertype, but it will result unknown switch error.

my current servers.txt is 

```
[offline iro]
ip 127.0.0.1
port 6900
master_version 4
version 55
serverType iRO_Renewal
serverEncoding Western
addTableFolders iRO/Renewal;iRO
charBlockSize 155
```

**Comment by Fadreus** [comment]
Simple answer:
- sT not updated.
- Need use correct sT.

I'm might be wrong but do we even once getting p. server working without using kRO sT in history? Hmm? Unless the issue is about makine right sT #2101 

Now, lets move along.
Exit this way --> :door: :running_man: :dash:

**Comment by Fadreus** [comment]
Simple answer:
- sT not updated.
- Need use correct sT.

I'm might be wrong but do we even once getting p. server working without using kRO sT in history? Hmm? Unless the issue is about making right sT #2101 

Now, lets move along.
Exit this way --> :door: :running_man: :dash:

**Comment by Fadreus** [comment]
- sT not updated.
- Incorrect sT.
- sT iRO? Wut?!

I'm might be wrong but do we even once getting p. server working without using kRO sT in history? Hmm? Unless the issue is about making right sT #2101 

Now, lets move along.
Exit this way --> :door: :running_man: :dash:

**Comment by royluo1984** [comment]
> > serverType iRO_Renewal
> 
> ![image](https://user-images.githubusercontent.com/32188494/49578242-3ed5d300-f984-11e8-8fba-1a90a8cd744c.png)

I know it doesn't make senses, but this is the only servertype works as far.

**Comment by royluo1984** [comment]
> this client is kRO Zero based, openkore dont support Zero client for a while, and dont suport 2018 clients

Thank you sir. I will try to learn to use lower version as server side.
