### ISSUE TITLE
Bot stucks

### ISSUE THREAD

**Issue by Norfolkk** [OpenKore/openkore#2546]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
 
* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

Hi everybody! 
I cant solve my problem, need your help. 
Sometimes bot is trying to catch occupied by monster/player cell and doind strange fast back-forward movements close to that cell. I dont know the reason why.
Do you have any advices how to explain him to check the cell before he wants to go there. And recalculate his route if it needs.

**Comment by Glikadin** [comment]
I create plugin for fix this problem.
Write me in discord: Лютый Дед#5309
