### ISSUE TITLE
NPC triggered when close

### ISSUE THREAD

**Issue by kumulo123** [OpenKore/openkore#2548]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

last version
* **Server**: 

private server
* **Bug Report / Feature Request**:

* **Summary**:

Hi to go from nyd_dun01 to spl_fild01 my bot need to be close to a NPC and then a window pops up and it ask if you want to climb if you say yes you are warped to spl_fild01 **but** if you are talk to the NPC without being close to him then nothing happends

Is there a way to tell the bot to go close to the NPC ans then when the window pops up to say yes ?
thanks a lot :)

**Comment by Fadreus** [comment]
Macro

**Comment by Nipodemos** [comment]
https://github.com/Henrybk/Plugins/tree/master/autoTalkDatabase

**Comment by kumulo123** [comment]
> Macro
Ok thanks



> https://github.com/Henrybk/Plugins/tree/master/autoTalkDatabase
Hi how do i use this please ?

**Comment by Nipodemos** [comment]
inside of file autoTalkDatabase.pl is a mini-guide to teach how to use it

**Comment by Fadreus** [comment]
This should continue at #38 I assume?

**Comment by alisonrag** [comment]
continue in #38
