### ISSUE TITLE
(IRO) error in xkore3 when changing maps

### ISSUE THREAD

**Issue by opn-1** [OpenKore/openkore#2556]
Hi.

http://forums.openkore.com/viewtopic.php?f=16&t=212845
Bot crashes when changing city (e.g. pront-> payon, payon->alberta)
Seems no problem if map change within city (yuno->yuno_fild08, payon->pay_fild08)
Error is for Xkore3. Xkore2 seems to be working fine. Can't test Xkore1 since I'm having errors which I do not understand how to fix
Issue for both wxstart.exe and start.exe
Here's the error.txt
```
OpenKore version what-will-become-2.1
Network state = 4
Network handler = Network::XKoreProxy
Revision: git:c3d3d28_2018-12-14 ctime:2018_09_08
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Bad arg length for Socket::inet_ntoa, length is 0, should be 4 at src/Network/XKoreProxy.pm line 624.

Stack trace:
Bad arg length for Socket::inet_ntoa, length is 0, should be 4 at src/Network/XKoreProxy.pm line 624.
at src/Interface/Wx.pm line 163
   Interface::Wx::mainLoop('Interface::Wx=HASH(0x5c79a84)') called at openkore.pl line 97
   main::__start() called at start.pl line 136

Died at this line:
        } else {
*          $mapInfo->{ip} = inet_ntoa($mapInfo->{ip});
        }
```

**Comment by nizdi** [comment]
Someone claimed in your link to forum that: "_I use xkore 3 daily on iro, never had this problem. You either didn't fully update or messed with the timeouts in some very odd way._"
Have you tried a fresh installation?

Also, what's your problem with  Xkore1? Try opening start.exe (not openkore.pl) with admin rights to be able to inject NetRedirect.dll.

**Comment by Fadreus** [comment]
fRO reported for having the same issue:

**Comment by Fadreus** [comment]
Someone reported fRO having same issue.

**Comment by alisonrag** [comment]
@opn-1 
go to openkore\src\network\XkoreProxy.pm line 624 and change this:
```
$mapInfo->{ip} = inet_ntoa($mapInfo->{ip});
```

to this:
```
$mapInfo->{ip} = inet_ntoa($mapInfo->{'IP'});
```

post result here please
