### ISSUE TITLE
Route Random Walk to New Destinations

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [OpenKore/openkore#2565]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
596dbaf_2018-12-21 ctime:2018_12_17
* **Server**: 
iRO
* **Bug Report / Feature Request**:
Feature Request
* **Summary**:
OpenKore now route using walk to a randomly chosen destination, but does not remember the destinations it has gone before, often walk to same place.
I request that OpenKore route only to destinations that has not gone before.
OpenKore now has A* path finding algorithm. We can have this feature by improve OpenKore to keep the destinations that have gone before in memory and randomly choose a destination that have not gone before. Then use A* path finding algorithm to go to the destination.

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=34&t=13558&sid=b1e0672e73d9ed491dac5d0dc83c1dcb

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=34&t=13558

**Comment by c4c1n6kr3m1** [comment]
I have never tried this new random route since it delete after "attack"
but i guess computer will hotter

**Comment by alisonrag** [comment]
partially fixed in #3145

to more support search for planwalk
https://forums.openkore.com/viewtopic.php?f=34&t=13558

or wayPoint
https://github.com/OpenKore/openkore/blob/master/plugins/needs-review/WayPoint/trunk/wayPoint.pl
