### ISSUE TITLE
squelchDomains can't supress [console] messages

### ISSUE THREAD

**Issue by nizdi** [OpenKore/openkore#2567]
![image](https://user-images.githubusercontent.com/29477616/50524467-fc07a680-0abc-11e9-8c28-d121266da66c.png)

Server: iRO.

[squelchDomains](http://openkore.com/index.php/SquelchDomains ) for some reason isn't supressing console messages on kore. Trying to do this to cause less lag.

It's this supossed to be happening? Like some infos can't be supressed, or it's actually a bug?

Sorry for many hiding in the print screen and if it's some problem with config i'm sorry again.

@EDIT: Not it's not only "attacked itself" that it's being shown, but "used teleport lvl1" too. None of them was supressed.

**Comment by Nipodemos** [comment]
hey, you opened with openkore.pl?

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=10&t=212811&p=281818&hilit=squelchDomains#p281818

**Comment by lututui** [comment]
"console" is the default domain, assigned to Logs which don't have a specific domain assigned.
As it is indeed a domain, it should be squelch-able, therefore this is a bug.
#2570 should fix it

**Comment by nizdi** [comment]
Thank you so much for this fix.

While there're some important information, what my bot is doing is some kinda labor-job which messages would only lagging it, since he doesn't need those. But thanks for the advice too!
