### ISSUE TITLE
EventMacro: @.param not found

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#2576]
eventMacro code:
```
macro Test {
 log Parameter 1 is $.param[0]
 log Parameter 2 is $.param[1]
}
```
I write in console: eventMacro Test --testparam
and get:
```
 Parameter 1 is
 Parameter 1 is
```
$.param[0] and $.param[1] is empty T__T

**Comment by Fadreus** [comment]
Space after `--`

![image](https://user-images.githubusercontent.com/32188494/50725163-5abfc680-1134-11e9-9624-0008570a13ab.png)

**Comment by Glikadin** [comment]
ooops
Not Working: eventMacro Test --testparam
Working: eventMacro Test -- testparam
Oh, sorry for spam, good luck!
