### ISSUE TITLE
Add Option to Continue Walk to Destination

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [OpenKore/openkore#2584]
* **Openkore version git**: 

* **Server**: 
iRO
* **Bug Report / Feature Request**:
Feature Request
* **Summary**:
OpenKore now does random walk to a destination. It walks to new destination after encounter a monster. We need an option to set OpenKore to continue to walk to current destination even after encounter a monster.

**Comment by Fadreus** [comment]
Assuming it is in `lockMap`, openkore do walk to random coordinate after encounter any monster.
What is it that you are talking about?

**Comment by Fadreus** [comment]
Assuming it is in `lockMap`, openkore do walk to random coordinate after encounter any monster. It didn't change until it reach it.
What is it that you are talking about?

**Comment by aaabbbcccddd00001111** [comment]
I mean, add a option so that openkore does not calcalute random route after encounter any monster, but continue the route it calculated before.

**Comment by Fadreus** [comment]
Okay. I run a test and this is not feature request.
This is a bug.

Openkore wasn't suppose to calculate new destination after engaging with monsters.

**Comment by alisonrag** [comment]
this is not a bug, openkore was moving away from monsters then backing to kill.
then this was necessary to avoid this.
see #841

**Comment by alisonrag** [comment]
you can revert this pull by yourself

**Comment by c4c1n6kr3m1** [comment]
never tried that fix, but aren't your computer working harder because calculating route more often?

**Comment by Fadreus** [comment]
Oh.. I understand it wrongly about `dequeue`.

Now this explain why those bot roaming in midgard is going back and forth along the route where it just it came from due to changing destination often. :thinking:
