### ISSUE TITLE
Wiki pages that need to be removed

### ISSUE THREAD

**Issue by lututui** [OpenKore/openkore#259]
http://wiki.openkore.com/index.php/TeleportAuto_emptyName
Blank page, unknown function.

http://wiki.openkore.com/index.php/Item_settings
Blank page, was once a Brazilian Portuguese version of items_control.txt.

http://wiki.openkore.com/index.php/Enabled
Blank page, moved to References. 

http://wiki.openkore.com/index.php/Nostalgia-RO.ru
Blank page, was once server settings for Nostalgia-RO.ru, which no longer exists

**Comment by Cozzie** [comment]
You can register and edit them yourself.

**Comment by lututui** [comment]
I'm not allowed to delete them.

**Comment by itsrachelfish** [comment]
@lututui I deleted these pages and went ahead and added you as an administrator on the wiki. :+1:
