### ISSUE TITLE
New Project "OpenAuto"

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [OpenKore/openkore#2591]
I have an idea, a new project called "OpenAuto". OpenAuto is an general automation program. It can be used for any automation that needs action for network.
OpenAuto has an application that is a GUI application that do Ragnarok Online client automation.
OpenAuto is written in .NET C#, and use WPF.

I invite OpenKore developers to join this project.

**Comment by sctnightcore** [comment]
:thinking:

**Comment by Fadreus** [comment]
Is it just me or all your posts are like: 

`Hey, I need this. You there. Do this for me.`

**Comment by Fadreus** [comment]
Is it just me or all your posts are like: 

`Hey, I need this. You there. Do this for me.`

![thinking](https://user-images.githubusercontent.com/32188494/51428592-7c46a500-1c40-11e9-9563-bc35bd862339.gif)
