### ISSUE TITLE
"Unable to use portal" problem

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#2592]
## ------------------ Openkore Issues Template ------------------

sometimes , openkore can't use a existing portal because of some reason , When "Unable to use portal at XXX"  happened , openkore will stop use that portal , is there a switch to turn this function off ,let openkore keep trying to use the portal?

* **Openkore version git**: 

* **Server**: 
cRO

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by Fadreus** [comment]
For now, temporary solution is using macro

Example:
```
automacro Portal {
	console /Unable to use portal/
	timeout 1
	call ReloadPortal
}

automacro Route {
	console /Cannot calculate a route/
	timeout 1
	call ReloadPortal
}

macro ReloadPortal {
	do reload portal
	# Add relog if necessary
	# do relog 10
}
```

**Comment by lututui** [comment]
Be more specific, please.

**Comment by hubertyang88** [comment]
@Fadreus @lututui Thanks for your time . I guess these problems is caused by network delay , when kore try to use a portal , after sometime ,if nothing happened , kore will think the portal is unusable, and "Cannot calculate a route"will keep comming , in this case , I need to shut kore and reopen it . If "do reload portal" can fix it , I think it good enough for me ! THX!
Example message:
[Jan 18 09:12:54 2019.23] Unable to use portal at 1@mist (285,225).
[Jan 18 09:12:54 2019.40] Cannot calculate a route from 1@mist (285,225) to

**Comment by lututui** [comment]
In config.txt, what are these keys set to?

```
route_removeMissingPortals_NPC
route_removeMissingPortals
```

In timeouts.txt, what is this key set to?

```
ai_portal_give_up
```

**Comment by Fadreus** [comment]
Oh, that fix implemented already. Didn't notice. I thought that PR didn't get implemented.
Never tried that. :thinking:
