### ISSUE TITLE
Opencore how to tele out prt_maze01

### ISSUE THREAD

**Issue by HengHeng92** [OpenKore/openkore#2596]
I try record all the portals at the prt_maze01,
but still unable to tele out and find the correct portals.
Please help.

**Comment by sctnightcore** [comment]
How to use openkore work in mRO ?

**Comment by Fadreus** [comment]
If you have problem using openkore, use forum for discussion or ask in IRC.
I'd gladly assist you there but not here.

I don't want to encourage anyone posting their every personal problem at github because this is not a place for that as stated in forum announcement.

**Comment by alisonrag** [comment]
hmm.. as I know a lot of portals in prt_maze random teleport you, so the best way is use butterfly wings, openkore offer support to use item to return to savemap
