### ISSUE TITLE
Can't call method "baseName" on an undefined value at src/Network/Receive.pm line 1812.

### ISSUE THREAD

**Issue by ftkwang** [OpenKore/openkore#2603]
OpenKore version what-will-become-2.1
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2019_01_27
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Can't call method "baseName" on an undefined value at src/Network/Receive.pm line 1812.

Stack trace:
Can't call method "baseName" on an undefined value at src/Network/Receive.pm line 1812.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x70609dc)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

这行有错误:
  			my $ID = $args->{ID};
* 			my $location = $field->baseName . " $actor->{pos}{x} $actor->{pos}{y}";
  			if ($npcs_lut{$location}) {

**Comment by ya4ept** [comment]
On which map does this error appear? See your maps.txt file - is this map there?

**Comment by ftkwang** [comment]
Thank you. According to your prompt. The problem has been solved.
