### ISSUE TITLE
Disconnect from Map Server and Reconnect Account Server

### ISSUE THREAD

**Issue by ftkwang** [OpenKore/openkore#2605]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

![1548634837 1](https://user-images.githubusercontent.com/47087053/51808935-d673e580-2292-11e9-8405-d5748114363b.png)
![1548634890 1](https://user-images.githubusercontent.com/47087053/51808936-d673e580-2292-11e9-9087-7550cc0475df.png)
![1548634848 1](https://user-images.githubusercontent.com/47087053/51808937-d70c7c00-2292-11e9-8d39-b1b8b3287036.png)

**Comment by alisonrag** [comment]
Server?

**Comment by ftkwang** [comment]
sorry。    cro

**Comment by alisonrag** [comment]
cRO need to use Poseidon

**Comment by alisonrag** [comment]
Chinese community is not active here, this is why dont have any tutorial for cRO
You can try talk with someone here
https://discord.gg/jYPFZTq
