### ISSUE TITLE
poseidon.xml

### ISSUE THREAD

**Issue by ftkwang** [OpenKore/openkore#2606]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git none: 

* **Server**: 

* **Bug Report / Feature Request**:Following the steps did not yield the corresponding

* **Summary**:

open start-poseidon.exe=>open Ragnarok.exe=>done
![1](https://user-images.githubusercontent.com/47087053/51814740-a6d5d500-22b4-11e9-9301-ae65ad3f0822.png)
![2](https://user-images.githubusercontent.com/47087053/51814743-aa695c00-22b4-11e9-91db-b9a2d2da86a0.png)
![3](https://user-images.githubusercontent.com/47087053/51814747-accbb600-22b4-11e9-9397-57b8f68dc0df.jpg)
![4](https://user-images.githubusercontent.com/47087053/51814749-af2e1000-22b4-11e9-9956-694e5be6fc84.jpg)

**Comment by alisonrag** [comment]
https://cdn.discordapp.com/attachments/411486483019595786/415978614459203585/cRO_batclient.7z

**Comment by alisonrag** [comment]
cRO use `<domain>` to define the connection

so you dont need to change `<ip>` and `<port>`

use:
`<domain>my.real.ip.address:poseidonport</domain>`

**Comment by alisonrag** [comment]
as i know gameguard can detect if you redirect connection to 127.0.0.1 or to pcs in the same lan

**Comment by alisonrag** [comment]
PC 1 = 
```
poseidon.txt
ragnarokserver_ip=127.0.0.1
ragnarokserver_port=6900
queryserver_ip=127.0.0.1
queryserver_port=24390
server_type=cRO_2017-12-13a
CharBlockSize=147
debug=0

```

config.txt
```
poseidonServer REAL.IP.FROM.PC1
poseidonPort 24390
```


PC 2 =
clientinfo.xml inside data.grf
```
<port>6900</port>
<domain>REAL.IP.FROM.PC1:6900</domain>
```
