### ISSUE TITLE
OpenKore for TalonRO is possible?

### ISSUE THREAD

**Issue by Dekard86** [OpenKore/openkore#2609]
I can`t find some settings for TalonRO. OpenKore work on this server?

**Comment by Fadreus** [comment]
If you search using  ![image](https://user-images.githubusercontent.com/32188494/52175482-9905df80-27df-11e9-9678-3a0baeb72a8d.png) or  ![image](https://user-images.githubusercontent.com/32188494/52175489-b0dd6380-27df-11e9-8a89-12e517b82e73.png) , you will get the answer.
But you search in ![image](https://user-images.githubusercontent.com/32188494/52175459-4a584580-27df-11e9-9b72-cf18f8e0a9ac.png), of course you can't find anything.

**Comment by Fadreus** [comment]
TalonRO have Gepard.
I simply go to openkore forum, enter keyword in search box `TalonRO` and find answer.
If you search using  ![image](https://user-images.githubusercontent.com/32188494/52175482-9905df80-27df-11e9-9678-3a0baeb72a8d.png) or ![image](https://user-images.githubusercontent.com/32188494/52175489-b0dd6380-27df-11e9-8a89-12e517b82e73.png) , you will find your answer or some leads.
But you search in ![image](https://user-images.githubusercontent.com/32188494/52175459-4a584580-27df-11e9-9b72-cf18f8e0a9ac.png), of course you can't find anything.

**Comment by Fadreus** [comment]
Do you even read what I just wrote?
![image](https://user-images.githubusercontent.com/32188494/52175845-023c2180-27e5-11e9-9ab7-8bac2fd2b7e4.png)

http://forums.openkore.com/search.php?keywords=talonRO&terms=all&author=&sc=1&sf=all&sk=t&sd=d&sr=posts&st=0&ch=300&t=0&submit=Search
![image](https://user-images.githubusercontent.com/32188494/52175923-4d0a6900-27e6-11e9-9883-906248dc8328.png)

![image](https://user-images.githubusercontent.com/32188494/52175859-2d267580-27e5-11e9-9a36-cdd3afd8ea47.png)
![image](https://user-images.githubusercontent.com/32188494/52175889-a8882700-27e5-11e9-9540-ecc27dff21a2.png)
![image](https://user-images.githubusercontent.com/32188494/52175902-e6854b00-27e5-11e9-88cb-b54e3d801ed0.png)

There are around 7,460 results on google and 46 results on forum to be read but you just read 2?
![thinking](https://user-images.githubusercontent.com/32188494/52175957-e0439e80-27e6-11e9-8442-639eb041134a.gif) 

You don't read what I wrote.
You just read 2 threads.
You don't do research.

Man, how lazy can you be?
There, I've made this picture-book for you so it's easy for you to understand.
I used to read picture book too when i was around 4 years old.
I thought it suit you.
