### ISSUE TITLE
Crash when bot is target of any skill

### ISSUE THREAD

**Issue by ArcLarien** [OpenKore/openkore#2612]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: what-will-become-2.1

* **Server**: kRO-Based private server [Wing-RO]

* **Bug Report / Feature Request**: Crash when bot is target of any skill

* **Summary**: The bot worked fine until 2 days ago, but now, every time it is target of a skill it crashes.
I have no macros nor automacros, config.txt mods is only the server I play.

What I find weird is that this very same folder was working 2 days ago, I have downloaded again, and with no mods I get the same error.

Screenshot:
![error](https://user-images.githubusercontent.com/6582562/52436043-d799e380-2ad8-11e9-91af-7314936bede8.PNG)

This is the error log summary on error.txt:
OpenKore version what-will-become-2.1

@ai_seq = route attack
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2019_02_06
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
No valid skill identifier specified.

Stack trace:
Trace begun at src\Skill.pm line 142
Skill::new('Skill', 'idn', undef) called at src\Network\Receive.pm line 6978
Network::Receive::skill_delete('Network::Receive::kRO::RagexeRE_2010_08_03a=HASH(0xaae5a3c)', 'HASH(0xb0828e4)') called at src\Network\PacketParser.pm line 276
Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2010_08_03a=HASH(0xaae5a3c)', 'A^D[^@', 'Network::Receive::kRO::RagexeRE_2010_08_03a=HASH(0xaae5a3c)') called at src\Network\Receive.pm line 492
Network::Receive::parse('Network::Receive::kRO::RagexeRE_2010_08_03a=HASH(0xaae5a3c)', 'A^D[^@', 'Network::Receive::kRO::RagexeRE_2010_08_03a=HASH(0xaae5a3c)') called at src\Network\PacketParser.pm line 410
Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2010_08_03a=HASH(0xaae5a3c)', 'Network::MessageTokenizer=HASH(0x49ceb14)', 'Network::Receive::kRO::RagexeRE_2010_08_03a=HASH(0xaae5a3c)') called at src\functions.pl line 757
main::mainLoop_initialized at src\functions.pl line 75
main::mainLoop at src\Interface\Wx.pm line 190
Interface::Wx::__ANON__('Interface::Wx=HASH(0x5d764f4)', 'Wx::TimerEvent=SCALAR(0xae0366c)') called at src\Interface\Wx.pm line 163
eval {...} at src\Interface\Wx.pm line 163
Interface::Wx::mainLoop('Interface::Wx=HASH(0x5d764f4)') called at openkore.pl line 97
main::__start at start.pl line 136

Died at this line:
  	} else {
* 		ArgumentException->throw("No valid skill identifier specified.");
  	}

Please help, I've tried updating the skill names in tables/SKILL_id_handle with no luck.

My knowledge doesn't go over that.

Thanks in advance.

EDIT: verified the skill ID in ratemyserver and in the file SKILL_id_handle, both have the same identifier (91 for WZ_HEAVENDRIVE) so I don't understand why it shows problem with the skill identifier.

**Comment by ya4ept** [comment]
attach the servers.txt settings

**Comment by Fadreus** [comment]
Same problem reported here:
http://forums.openkore.com/viewtopic.php?f=10&t=212873&start=0
http://forums.openkore.com/viewtopic.php?f=9&t=212823&start=0

None of them return to give feedback.
Not sure either solved or persistent.

**Comment by Fadreus** [comment]
Same problem reported here:
http://forums.openkore.com/viewtopic.php?f=10&t=212873&start=0
http://forums.openkore.com/viewtopic.php?f=9&t=212823&start=0

None of them return to give feedback.
Not sure either solved or persistent.

Seems to me all three cases happen when being attacked with skills and then attempt to teleport _(avoid)_.

**Comment by ArcLarien** [comment]
Thank you for following up!

Here's my servers.txt for this particular server entry:

# http://wing-ro.com/
[WingRO]
ip 192.95.15.148
port 6900
private 1
master_version 49
version 199
recvpackets recvpackets.txt
serverType kRO_RagexeRE_2010_08_03a
serverEncoding Western
charBlockSize 132
addTableFolders translated/kRO_english;kRO

Also find attached the full file.

Kind regards
[servers.txt](https://github.com/OpenKore/openkore/files/2847209/servers.txt)

**Comment by ArcLarien** [comment]
> Same problem reported here:
> http://forums.openkore.com/viewtopic.php?f=10&t=212873&start=0
> http://forums.openkore.com/viewtopic.php?f=9&t=212823&start=0
> 
> None of them return to give feedback.
> Not sure either solved or persistent.
> 
> Seems to me all three cases happen when being attacked with skills and then attempt to teleport _(avoid)_.

I checked both topics before coming here, but they don't provide any glimmer of hope on what could it be, I don't know exactly on how to read the error log, however, my autoteleport is at 10% (teleport when hp is 10% or less) and deactivated for aggros. So I know that is not because of tele.

**Comment by Fadreus** [comment]
Ain't your screenshot just showed you are teleporting due to damage over 500 from skill Heaven Drive? :thinking: 

If you disable all `teleportAuto`, I'm pretty much sure this problem won't happen;
_(Unless this error pop out even after disabling `teleportAuto`.)_ :no_mouth:

**Comment by ya4ept** [comment]
maybe you use the wrong recvpackets? try to use these settings:
```# http://wing-ro.com/
[WingRO]
ip 192.95.15.148
port 6900
version 22
master_version 13
serverType kRO_RagexeRE_2010_08_03a
serverEncoding Western
charBlockSize 112
addTableFolders kRO/RagexeRE_2010_07_14a;translated/kRO_english;kRO
clientHash C70A94C27ACC389A47F554397CA4D039
```

**Comment by ArcLarien** [comment]
> Ain't your screenshot just showed you are teleporting due to damage over 500 from skill Heaven Drive? 🤔
> 
> If you disable all `teleportAuto`, I'm pretty much sure this problem won't happen;
> _(Unless this error pop out even after disabling `teleportAuto`.)_ 😶

Indeed, I changed those settings to minimum damage 50k and same happened, then disabled all the 'teleportAuto' settings, but same happened.

Weird thing is that there were fly wings in inventory, so I thought that it was because Maya could kill my bot with one hit, but then I changed map to Brasilis dungeon 2 and a cold bolt from a piranha (My bot's equip being swordfish card and marse card) with a damage of 100 overall, still crashed it...

**Comment by ArcLarien** [comment]
> maybe you use the wrong recvpackets? try to use these settings:
> 
> ```
> [WingRO]
> ip 192.95.15.148
> port 6900
> version 22
> master_version 13
> serverType kRO_RagexeRE_2010_08_03a
> serverEncoding Western
> charBlockSize 112
> addTableFolders kRO/RagexeRE_2010_07_14a;translated/kRO_english;kRO
> clientHash C70A94C27ACC389A47F554397CA4D039
> ```

Hi! Thanks for the new settings, however, same error happened, I'm really cracking my head open with this issue and can't find an answer :/

Here's another Screenie with the new server settings:
![image](https://user-images.githubusercontent.com/6582562/52528684-f69b9f80-2ca9-11e9-9ff2-66129f8ae899.png)

On this one it applies that it doesn't autotele because of damage (autoTeleport is disabled) and the new server settings are applied in servers.txt.

Thank you for sticking with me on this, I really appreciate it. Could it be any OS setting? I'm using win10.

Kind regards

**Comment by ArcLarien** [comment]
Update:
Noticed something weird: It crashes only in active skills (damage done), with passive skills (like Lex Divina from Obeaunes) doesn't happen.

**Comment by lututui** [comment]
Is this a Rogue/Stalker/ShadowChaser that knows [Intimidate/Plagiarism](https://irowiki.org/wiki/Intimidate) without [Preserve](https://irowiki.org/wiki/Preserve)?

**Comment by lututui** [comment]
@ArcLarien please test #2615

**Comment by ArcLarien** [comment]
> @ArcLarien please test #2615

Hi! That did it!!!

Indeed apparently the bot could not maintain the copied skill and because of that crashed.

Issue fixed. THANK YOU Iututui, ya4ept and Fadreus.
