### ISSUE TITLE
Xkore stuck after char server

### ISSUE THREAD

**Issue by opn-1** [OpenKore/openkore#2620]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: ctime:2019_02_11

* **Server**: iRO

* **Bug Report / Feature Request**: Xkore stuck at char server. Disconnects afterwards.

* **Summary**: I think its similar to these: 
http://forums.openkore.com/viewtopic.php?f=10&t=212618&start=0
https://github.com/OpenKore/openkore/issues/1406
Basically disconnects after char server.
I already downloaded the latest version, but no avail.

**Comment by Fadreus** [comment]
http://forums.openkore.com/viewtopic.php?f=16&t=212775

**Comment by Fadreus** [comment]
#2613 
About time people read [this](http://forums.openkore.com/viewtopic.php?f=16&t=212775), don't you think?
