### ISSUE TITLE
Can't create character in char select interface

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#2622]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
latest version

* **Server**: 
cRo

* **Bug Report / Feature Request**:
I fail to create a character in char select interface, and I try wireshark client and openkore , 
when create a character; 
client will send 39:0a:6e:6e:6e:6d:6d:6d:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:00:00:00:00:00:01
but openkore will send 70:09:6b:6b:6a:6a:6c:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:05:00:05:00
it's different , what should I do to make this work? 

* **Summary**:

**Comment by hubertyang88** [comment]
By replace "char_create 0A39" in \src\Network\Send\cro.pm , it works ! Well , someone can modify this in the src file.

**Comment by alisonrag** [comment]
i will update src,

about selectscreen

http://openkorebrasil.org/index.php?/topic/5007-plugin-createchar/
http://openkorebrasil.org/index.php?/topic/5208-reincarnatepl/

**Comment by hubertyang88** [comment]
thank you! @alisonrag , I will try the plugin
