### ISSUE TITLE
error when whisper is hiding - "Invalid arguments."

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#2627]
* **Openkore version git**: 
Version git : ctime:2019_02_11
* **Server**:  RagnaRevival (pirate)
* **Bug Report**:

> Received packet: 0195 Handler: actor_info
> Received object info: Whisper
> Monster Info: Whisper (0)
> Received packet: 09FD Handler: actor_moved
> **Monster Moved: Whisper (0) - (84, 63) -> (0, 0)**
> Move You - (re)trying
> Sent move to: 84, 63
> Received packet: 0983 Handler: actor_status_active
> You are again: UNKNOWN_STATUS_2014
> Received packet: 08C8 Handler: actor_action
> **[100/100] You attack Monster Whisper (0) (Dmg: 61!) (Delay: 292ms)**
> Received packet: 009C Handler: actor_look_at
> You looks at 3, 0
> Sent get player info: ID - B1 83 C2 06
> AI: route attack | 3
> Received packet: 0195 Handler: actor_info
> Received object info: Whisper
> Monster Info: Whisper (0)
> Received packet: 09FD Handler: actor_moved
> **Monster Moved: Whisper (0) - (84, 63) -> (0, 0)**
> Received packet: 0087 Handler: character_moves
> You're moving from (85, 64) to (84, 63) - distance 1.4
> Move You - done
> Route You - trimming down solution (4) by 4 steps
> You reached the destination.
> Received packet: 0087 Handler: character_moves
> You're moving from (84, 63) to (85, 63) - distance 1.0
> Received packet: 0195 Handler: actor_info
> Received object info: Whisper
> Monster Info: Whisper (1)
> Update attack giveup time
> **Target distance 106.0 is >2.5; moving to target: from (85,63) to (2,0)**
> You on route to: (): 2, 0
> Sent Quit
> Disconnecting (139.99.117.6:5121)...disconnected

```
This program has encountered an unexpected problem. This is probably because of a recent server update, a bug in this program, or in one of the plugins. We apologize for this problem. You may get support from IRC or the forums.
A detailed error report has been saved to errors.txt. Before posting a bug report, please try 
out the latest release GIT version first. If you are already using the latest release GIT 
version, search the forums first to see if your problem had already been solved, or has 
already been reported. If you truly believe you have encountered a bug in the program, 
please include the contents of the errors.txt in your bug report
 (https://github.com/openkore/openkore/issues), or we may not be able to help you!

The error message is:
Invalid arguments.
```
Errors.txt:
```OpenKore version what-will-become-2.1
@ai_seq = attack
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2019_02_11
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/eventMacro/eventMacro.pl (eventMacro; description: allows usage of eventMacros)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Invalid arguments.

Stack trace:
Trace begun at src\Task\Route.pm line 81
Task::Route::new('Task::Route', 'actor', 'Actor::You=HASH(0x42edeac)', 'x', 2, 'y', 0, 'maxDistance', undef, 'maxTime', 4, 'avoidWalls', '', 'distFromGoal', undef, 'pyDistFromGoal', undef, 'notifyUponArrival', undef) called at src\Actor.pm line 786
Actor::route('Actor::You=HASH(0x42edeac)', undef, 2, 0, 'maxRouteTime', 4, 'attackID', 'M-2M-^CM-B^F', 'noMapRoute', 1, 'noAvoidWalls', 1) called at src\AI\Attack.pm line 531
AI::Attack::main at src\AI\Attack.pm line 97
AI::Attack::process at src\AI\CoreLogic.pm line 82
AI::CoreLogic::iterate at src\functions.pl line 787
main::mainLoop_initialized at src\functions.pl line 75
main::mainLoop at src\Interface.pm line 75
Interface::mainLoop('Interface::Console::Win32=HASH(0x1caab14)') called at openkore.pl line 97
main::__start at start.pl line 136

Died at this line:
  
* 	unless ($args{actor}->isa('Actor') and $args{x} != 0 and $args{y} != 0) {
  		ArgumentException->throw(error => "Invalid arguments.");
```

**Comment by c4c1n6kr3m1** [comment]
hiding by move to (0, 0) ?

**Comment by ya4ept** [comment]
I think yes. This happens only with Whisper. but he doesn't seem to use skill

**Comment by lututui** [comment]
Were it cloaked?

**Comment by c4c1n6kr3m1** [comment]
server bug?
remove actor with pos 0,0 ?
remove actor outside 2xclientsight ?
reject actor moving pos_to 0,0 ?

**Comment by ya4ept** [comment]
probably features  of private server
