### ISSUE TITLE
Ragnarok Re Start time out on map server, connecting to account server

### ISSUE THREAD

**Issue by mikeekim2019** [OpenKore/openkore#2629]
can anyone fix the issue ..

**Comment by sctnightcore** [comment]
#2628  ?

**Comment by mikeekim2019** [comment]
thank you sir but.. not working for me sir... same error sir .. time out on map server ,,

**Comment by mikeekim2019** [comment]
> #2628 ?



> #2628 ?

thank you sir but.. not working for me sir... same error sir .. time out on map server ,,

**Comment by ya4ept** [comment]
Why do we answer such issue? what server is meant? Where is the build version?
The rules for creating a issue say:

> Use this template or your issue will be closed.

**Comment by jourlez** [comment]
@ya4ept https://github.com/OpenKore/openkore/issues/2630

**Comment by jourlez** [comment]
@ya4ept Please check my issue instead, I made it according to the template.

**Comment by Fadreus** [comment]
@jourlez Don't go around making new thread.
Just edit your last one.

Do read before posting.

**Comment by Fadreus** [comment]
@jourlez This thread is the same. Why making new one?
Just give the info here.
Don't come here and make a mess.

**Comment by ya4ept** [comment]
close as a duplicate
