### ISSUE TITLE
Statuses on mercenary not working (iRO)

### ISSUE THREAD

**Issue by dorwardv** [OpenKore/openkore#263]
I tried using mercenary concentration/awakening/berserk potion, Increase AGI, Blessing, Kyrie Eleison  nothing seems to register as a mercenary status

[Screenshot of merc s](https://s3-ap-southeast-2.amazonaws.com/dorward/2016/10/wxstart_2016-10-13_02-11-53.png)

The effect of this is not being able to check using mercenary_whenStatusInactive or mercenary_whenStatusActive flags when using items such as potions or using partySkills

**Comment by lututui** [comment]
They might be getting registered as player statuses. Check your player status through **s** command.

**Comment by Cozzie** [comment]
I think mercenaries' aspd is fixed?

**Comment by dorwardv** [comment]
No it does not register as a player status.

I can replicate it using iRO Oct 13 patch
Oct 13 cloned openkore repo

- bowman6/bowman9
- use of mercenary concentration/awake/berserk potions

It's also interesting to note that in payon, the the same mercenaries, I believe, have all the statuses even poisoned.  I can't really verify if it is indeed all as 'merc s' is not exhaustive

- I am using windows 10 enterprise

**Comment by dorwardv** [comment]
Another info

It looks like I can see the status after doing a teleport or a change map.
[merc s after teleport/change map](https://s3-ap-southeast-2.amazonaws.com/dorward/2016/10/wxstart_2016-10-17_06-01-17.png)

**Comment by alisonrag** [comment]
testing in private server seems like u only receive the stat update, and not the potion status
![image](https://user-images.githubusercontent.com/10372732/86493030-4e76f280-bd46-11ea-905a-f0e36654719b.png)

**Comment by alisonrag** [comment]
in bRO u only receive marcenary stat update:
![image](https://user-images.githubusercontent.com/10372732/86493316-829ee300-bd47-11ea-849e-02d2c34b1af2.png)

**Comment by ya4ept** [comment]
i think we can already close this issue
