### ISSUE TITLE
Stuck getting "Timeout on Map Server, connecting to Account Server... "

### ISSUE THREAD

**Issue by jourlez** [OpenKore/openkore#2630]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: #2628 

* **Server**: International - iRO: Re:Start

* **Bug Report / Feature Request**: OpenKore gets stuck in "Timeout on Map Server, connecting to Account Server..."

* **Summary**: Despite having the most recent version of OpenKore I can´t get the program to work, console shows "OpenKore gets stuck in "Timeout on Map Server, connecting to Account Server...".
Thanks in advance.

**Comment by Fadreus** [comment]
Just edit you last issue, why create new one?
If your car broken, you buy new one of fix it?
If your house damaged, you buy new one?

Please use common sense.
Don't come here and make a mess.
Read before posting.

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#things-to-know
It says there:
- Check if an issue already exists for your request.

And issue thread already exist in #2629 
Don't make a mess here.

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#things-to-know
It says there:
- Check if an issue already exists for your request.

And issue thread already exist in #2629 
Don't make a mess here.
Just replied on that thread.

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#things-to-know
It says there:
- Check if an issue already exists for your request.

And issue thread already exist in #2629 
Don't make a mess here.
Use that thread and reply there.

**Comment by jourlez** [comment]
I think I should mention, I still have the same problem even after the pull request was merged into master, I tried the other commits done in the same pull request hours after I first opened this issue but I keep getting "Timeout on Map Server, connecting to Account Server... ".
The master branch that it was merged into is also not working for me.
Thanks again.
