### ISSUE TITLE
[Request] Re-write character creation logic

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#2635]
* **Openkore version git**: 
latest.
* **Server**: 
all
* **Feature Request**:
Update character creation logic
* **Summary**:
#2625 was just a workaround is necessary re-write character creation logic to use %args, this way we can merge functions, this way the maintenance will be easier

**Comment by Loserack** [comment]
Strategy and Observer pattern on openkore.
CRUD

**Comment by alisonrag** [comment]
#fixed at #3517
