### ISSUE TITLE
Settings in items_control.txt ignored.

### ISSUE THREAD

**Issue by Fadreus** [OpenKore/openkore#2656]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 53692e9  

* **Server**: iRO

* **Bug Report / Feature Request**: Bug Report

* **Summary**:

![image](https://user-images.githubusercontent.com/32188494/53853129-37fc4200-3fff-11e9-855a-871a2ef41024.png)

Openkore ignoring _(not recognizing ?)_ items control settings for any equipment with enchant / option _(?)_ .
I just happen to saw it during auto storage, not sure with sell auto / get & put in cart.
_(Too lazy to check other things :mask:)_

**Comment by lututui** [comment]
@alisonrag I think this might be cause by your item options

**Comment by alisonrag** [comment]
type in console:
`eval use Data::Dumper; message Dumper(%items_control);`

**Comment by alisonrag** [comment]
@lututui tested here this is a parse problem

```
eval use Data::Dumper; print Dumper(%items_control);
$VAR1 = 'eden group dager iii [bradium golem:matk';
$VAR2 = {
          'cart_get' => '0',
          'cart_add' => '0',
          'keep' => '3]',
          'storage' => '99',
          'sell' => '0'
        };
$VAR3 = 'giant faceworm snake skin [agi +';
$VAR4 = {
          'cart_get' => '99',
          'cart_add' => '[1]',
          'keep' => '2:vit',
          'storage' => '+',
          'sell' => '2]'
        };
$VAR5 = 'eden group manteau ii [def +';
$VAR6 = {
          'cart_get' => '0',
          'cart_add' => '99',
          'keep' => '9:mdef',
          'storage' => '+',
          'sell' => '4]'
        };
$VAR7 = 'all';
$VAR8 = {
          'cart_get' => undef,
          'cart_add' => undef,
          'keep' => '0',
          'storage' => '1',
          'sell' => '0'
        };
```
