### ISSUE TITLE
Ragnarok Thailand

### ISSUE THREAD

**Issue by ykzmop** [OpenKore/openkore#2661]
Hello guys is there new version for openkore in ragnarok thailand? We use the old but yesterday since the update we can't use it anymore. Cannot detect monster,npc,players the openkore says Unknown#123123 something like that.

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#status-of-botting-on-official-servers
![image](https://user-images.githubusercontent.com/32188494/54019729-dbe41a00-41c6-11e9-9359-ba5079582ec7.png)

AFAIK official release never even working for any Extreme Electronics RO since 2017.
I think you confused official openkore with uKoreTeam ?

**Comment by ykzmop** [comment]
Yes I do have bot, but the openkore canot detect monster. Can you tell me which file I must fix in the latest openkore that github/oepnkore has.

**Comment by ykzmop** [comment]
Cannot detect npc,monster,players & when hitting monster it shows unknown.
![b2](https://user-images.githubusercontent.com/34195631/54020693-56159e00-41c9-11e9-86bb-e3264322d296.PNG)
![b1](https://user-images.githubusercontent.com/34195631/54020695-56159e00-41c9-11e9-93c8-fa6da14c2fef.PNG)

**Comment by Fadreus** [comment]
> Yes I do have bot

![image](https://user-images.githubusercontent.com/32188494/54023259-79dbe280-41cf-11e9-8189-ecf45a8ffb16.png)

![yare yare](https://user-images.githubusercontent.com/32188494/54023050-eb676100-41ce-11e9-9a49-78cce69c1e8a.gif)

**Comment by ykzmop** [comment]
Fixed already now the problem is charblocksize ;)

**Comment by alisonrag** [comment]
i'm sorry, we already have a issue for this. and we dot support buyed openkore. we cant connect, so we cant test ^^

**Comment by TaylorAvila** [comment]
@alisonrag cara consigo falar com você de alguma forma? to a algum tempo procurando algo e não consigo, acho que você pode ter a resposta, não quero tomar seu tempo!

**Comment by alisonrag** [comment]
> @alisonrag cara consigo falar com você de alguma forma? to a algum tempo procurando algo e não consigo, acho que você pode ter a resposta, não quero tomar seu tempo!

discord: alisonserafim
