### ISSUE TITLE
Error after update: "4c0caa5705974481b851125bfeee6fc72f51de31" Packet of inventory expansion feature. (#2593)

### ISSUE THREAD

**Issue by AzarthMZintos** [OpenKore/openkore#2672]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: last update today

* **Server**: Private

* **Bug Report / Feature Request**:i got the error of the print after that update, before it will work perfect
![ERROR](https://user-images.githubusercontent.com/35034692/54470775-97d7b300-478c-11e9-8cb3-714cb7580795.png)

* **Summary**:

**Comment by cydh** [comment]
on that line
```perl
use constant {
	EXPAND_INVENTORY_RESULT_SUCCESS = 0x0,
	EXPAND_INVENTORY_RESULT_FAILED = 0x1,
	EXPAND_INVENTORY_RESULT_OTHER_WORK = 0x2,
	EXPAND_INVENTORY_RESULT_MISSING_ITEM = 0x3,
	EXPAND_INVENTORY_RESULT_MAX_SIZE = 0x4	
};
```

to 
```perl
use constant {
	EXPAND_INVENTORY_RESULT_SUCCESS => 0x0,
	EXPAND_INVENTORY_RESULT_FAILED => 0x1,
	EXPAND_INVENTORY_RESULT_OTHER_WORK => 0x2,
	EXPAND_INVENTORY_RESULT_MISSING_ITEM => 0x3,
	EXPAND_INVENTORY_RESULT_MAX_SIZE => 0x4	
};
```
