### ISSUE TITLE
New error relate to #2672 issue

### ISSUE THREAD

**Issue by AzarthMZintos** [OpenKore/openkore#2674]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: after update the last commit i now got a new error on the print
![error2](https://user-images.githubusercontent.com/35034692/54475394-967baa00-47cf-11e9-8643-136850de934a.png)

* **Server**: renewal private

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by sctnightcore** [comment]
#2675
