### ISSUE TITLE
iRO Unknown switch: 0A95,0A9B,0A97,0A98,0A9C,0A9D,0A9A,

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [OpenKore/openkore#2676]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 
iRO
* **Bug Report / Feature Request**:

you get 0A95 when login,change map server
```
<< Received packet:      0A95 [4 bytes]   Mar 99 99:99:99 2019
  0>  95 0A 01 00                                           ....
[Mar 99 99:99:99 2019.86] Packet Parser: Unknown switch: 0A95
```
it's equip publicity, 
(need clarification, before was 02DA 3 bytes, now 4 bytes )

you get 0A9B when login,change map server
```
<< Received packet:      0A9B [10 bytes]   Mar 99 99:99:99 2019
  0>  9B 0A 0A 00 1C 00 02 00    00 00                      ..........
[Mar 99 99:99:99 2019.55] Packet Parser: Unknown switch: 0A9B
[Mar 99 99:99:99 2019.56] 
```
0A9B is new equip switch system and 0A97,0A98,0A9C,0A9D,0A9A,0A99 too
 , you get equip switch list 0A9B every change map including teleport

1C 00 is inventory id/index
2 is righthand
1 hat
4 robe

**Comment by sctnightcore** [comment]
```
4144Last Saturday at 11:28 PM
@sctnightcore24hour 0a95 is one of packets for set config value, exists many types of it
in 0a95 present two fields, flag for equipment and flag for call function
0a95, 0aa8, 0adc. same packet but in each newer version added new flag
```

https://github.com/rathena/rathena/pull/3548

**Comment by Fadreus** [comment]
So.. 0A95 XX YY
XX = Equipment.
YY = Call function.

:thinking:

**Comment by Fadreus** [comment]
Oh, that's 01 00 mean. Show equipment. :open_mouth: 
00 01 flag for call off.

**Comment by Fadreus** [comment]
So, 95 0A
01 00 = Show Equip.
00 01 = Call Off.

:thinking:

**Comment by Fadreus** [comment]
So, 95 0A XX YY
XX = Show Equip (01 ON / 00 OFF)
YY = Call function (01 OFF/ 01 ON)

00 00 Default _(Off show equip and can be call by skill guild / parent / partner / child)_

Not 02DA I guess..? :thinking:

**Comment by Fadreus** [comment]
So, 95 0A XX YY
XX = Show Equip (01 ON / 00 OFF)
YY = Call function (01 OFF/ 00 ON)

00 00 Default _(Off show equip and can be call by skill guild / parent / partner / child)_

Not 02DA I guess..? :thinking:

**Comment by c4c1n6kr3m1** [comment]
what is "call function" ? exall ?

**Comment by Fadreus** [comment]
Some notes for 0A95:

`95 0A 00 00` -> Default Setting _( Show Equip Disabled / Call Function Enabled )_
`95 0A 01 00` -> Show Equip **Enabled** / Call Function Enabled
`95 0A 00 01` -> Show Equip Disabled / Call Function **Disabled**
`95 0A 01 01` -> Show Equip **Enabled** / Call Function **Disabled**

Changing **Call Function** by using in-game command `/call`
- Giving player option to allow / refuse being summoned by skills:
`Urgent Call`, `Romantic Rendezvous`, `Come to me, honey~` & `Let's Go, Family!`

**Comment by Fadreus** [comment]
#2681

**Comment by hideman012** [comment]
need new update iro sir

**Comment by alisonrag** [comment]
#3095 fix the following packets:
0A98 0A9A 0A9B 0A9D - Recv
0A97 0A99 0A9C 0ACE - Send

after this pull will only miss:
0A95 and related versions (0AA8, 0ADC)
