### ISSUE TITLE
The server has denied your connection

### ISSUE THREAD

**Issue by Keeynt** [OpenKore/openkore#2691]
Dear Sirs, here is my server config
[RumbleRO]
ip 162.248.93.197
port 6900
master_version 1
version 55
serverType kRO_RagexeRE_2015_09_23d
addTableFolders RumbleRO
charBlockSize 147
sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9
blockingPlayerCancel 1
rankingSystemType 1
1,I used UE Explorer , the time date stamp is 29/10/2015.
2,I used PEEK to find the "recvpackets.txt" and put it in twRO.

[recvpackets.txt](https://github.com/OpenKore/openkore/files/3000582/recvpackets.txt)

and then it says display The server has denied your connection.

After that i set $self->cryptKeys(0x4C17382A, 0x29961E4F, 0x7ED174C9); in RagexeRE_2015_11_18a
Info's was received with PEEK and it says Timeout on Map Server.

Closing connection to Character Server
Disconnecting (162.248.93.197:6121)...disconnected
Connecting to Map Server...
Connecting (162.248.93.197:5121)... connected
Timeout on Map Server, connecting to Account Server...
Connecting to Account Server...
[reconnect] Login retry number 2, setting reconnect timeout to 77 seconds.
Connecting (162.248.93.197:6900)... connected
Timeout on Account Server, reconnecting. Wait 77 seconds...
Incoming data left in the buffer:
================================================
3 bytes   Mar 24 19:53:58 2019
  0>  81 00 08                                              ...
Disconnecting (162.248.93.197:6900)...disconnected...

Can anyone help me with my issue. Thank you!

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by sctnightcore** [comment]
**### I'm not a god to know your problems. Please enter the problem details.**

**Comment by Keeynt** [comment]
@sctnightcore i just updated it. sorry.

**Comment by sctnightcore** [comment]
*2,I used PEEK to find the "recvpackets.txt" and put it in twRO.
addTableFolders RumbleRO
why u put to twRO not RumbleRO ? 

* if u use sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9
u dont need to use $self->cryptKeys

1,I used UE Explorer , the time date stamp is 29/10/2015.
use RagexeRE_2015_10_29a

**Comment by Keeynt** [comment]
> *2,I used PEEK to find the "recvpackets.txt" and put it in twRO.
> addTableFolders RumbleRO
> why u put to twRO not RumbleRO ?
> 
> * if u use sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9
>   u dont need to use $self->cryptKeys
> 
> 1,I used UE Explorer , the time date stamp is 29/10/2015.
> use RagexeRE_2015_10_29a

Mybad, i used RumbleRO.

1,I used UE Explorer , the time date stamp is 29/10/2015.
use RagexeRE_2015_10_29a
The same openkore response.

Incoming data left in the buffer:
================================================
3 bytes   Mar 24 20:09:41 2019
  0>  81 00 08                                              ...
Disconnecting (162.248.93.197:6900)...disconnected

**Comment by sctnightcore** [comment]
sendCryptKeys 1, 3, 2 ?

**Comment by Keeynt** [comment]
> sendCryptKeys 1, 3, 2 ?

Yes sir, and I also tried to 1, 2, 3

**Comment by sctnightcore** [comment]
try sendCryptKeys 1, 3, 2 ?

**Comment by alisonrag** [comment]
```
[RumbleRO]
ip 162.248.93.197
port 6900
master_version 1
version 55
serverType kRO_RagexeRE_2015_09_23d
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
private 1
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders kRO/RagexeRE_2015_09_23d;iRO/official;iRO
charBlockSize 147
rankingSystemType 1
pinCode 0
charDeleteDateType 1
```

try this, without cryptkeys

**Comment by Keeynt** [comment]
> ```
> [RumbleRO]
> ip 162.248.93.197
> port 6900
> master_version 1
> version 55
> serverType kRO_RagexeRE_2015_09_23d
> secureLogin 0
> secureLogin_type 0
> secureLogin_requestCode
> secureLogin_account 0
> serverEncoding Western
> gameGuard 0
> private 1
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> addTableFolders kRO/RagexeRE_2015_09_23d;iRO/official;iRO
> charBlockSize 147
> rankingSystemType 1
> pinCode 0
> charDeleteDateType 1
> ```
> try this, without cryptkeys

![Capture](https://user-images.githubusercontent.com/48887916/54883077-6f2d7880-4e72-11e9-9e5b-9ffb61638695.JPG)

Same response

**Comment by Keeynt** [comment]
> try sendCryptKeys 1, 3, 2 ?

Yes sir, it didn't work

**Comment by sctnightcore** [comment]
> ```
> [RumbleRO]
> ip 162.248.93.197
> port 6900
> master_version 1
> version 55
> serverType kRO_RagexeRE_2015_09_23d
> secureLogin 0
> secureLogin_type 0
> secureLogin_requestCode
> secureLogin_account 0
> serverEncoding Western
> gameGuard 0
> private 1
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> addTableFolders kRO/RagexeRE_2015_09_23d;iRO/official;iRO
> charBlockSize 147
> rankingSystemType 1
> pinCode 0
> charDeleteDateType 1
> ```
> try this, without cryptkeys

client is 29/10/2015.



> > ```
> > [RumbleRO]
> > ip 162.248.93.197
> > port 6900
> > master_version 1
> > version 55
> > serverType kRO_RagexeRE_2015_09_23d
> > secureLogin 0
> > secureLogin_type 0
> > secureLogin_requestCode
> > secureLogin_account 0
> > serverEncoding Western
> > gameGuard 0
> > private 1
> > storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> > addTableFolders kRO/RagexeRE_2015_09_23d;iRO/official;iRO
> > charBlockSize 147
> > rankingSystemType 1
> > pinCode 0
> > charDeleteDateType 1
> > ```
> > try this, without cryptkeys
> 
> ![Capture](https://user-images.githubusercontent.com/48887916/54883077-6f2d7880-4e72-11e9-9e5b-9ffb61638695.JPG)
> 
> Same response

Do u have test ID PW ?

**Comment by Keeynt** [comment]
> > ```
> > [RumbleRO]
> > ip 162.248.93.197
> > port 6900
> > master_version 1
> > version 55
> > serverType kRO_RagexeRE_2015_09_23d
> > secureLogin 0
> > secureLogin_type 0
> > secureLogin_requestCode
> > secureLogin_account 0
> > serverEncoding Western
> > gameGuard 0
> > private 1
> > storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> > addTableFolders kRO/RagexeRE_2015_09_23d;iRO/official;iRO
> > charBlockSize 147
> > rankingSystemType 1
> > pinCode 0
> > charDeleteDateType 1
> > ```
> > try this, without cryptkeys
> 
> client is 29/10/2015.
> 
> > > ```
> > > [RumbleRO]
> > > ip 162.248.93.197
> > > port 6900
> > > master_version 1
> > > version 55
> > > serverType kRO_RagexeRE_2015_09_23d
> > > secureLogin 0
> > > secureLogin_type 0
> > > secureLogin_requestCode
> > > secureLogin_account 0
> > > serverEncoding Western
> > > gameGuard 0
> > > private 1
> > > storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> > > addTableFolders kRO/RagexeRE_2015_09_23d;iRO/official;iRO
> > > charBlockSize 147
> > > rankingSystemType 1
> > > pinCode 0
> > > charDeleteDateType 1
> > > ```
> > > try this, without cryptkeys
> > 
> > 
> > ![Capture](https://user-images.githubusercontent.com/48887916/54883077-6f2d7880-4e72-11e9-9e5b-9ffb61638695.JPG)
> > Same response
> 
> Do u have test ID PW ?

ID: teest1
PW: Test12345

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/54883223-30a9b500-4e96-11e9-9c93-977ac98c720e.png)
```
[RumbleRO]
ip 162.248.93.197
port 6900
master_version 1
version 55
serverType kRO_RagexeRE_2015_10_29a
serverEncoding Western
private 1
addTableFolders kRO/RagexeRE_2015_10_29a;translated;translated/kRO_english;kRO
charBlockSize 147

```

**Comment by Keeynt** [comment]
> ![image](https://user-images.githubusercontent.com/23263315/54883223-30a9b500-4e96-11e9-9c93-977ac98c720e.png)
> 
> ```
> [RumbleRO]
> ip 162.248.93.197
> port 6900
> master_version 1
> version 55
> serverType kRO_RagexeRE_2015_10_29a
> serverEncoding Western
> private 1
> addTableFolders kRO/RagexeRE_2015_10_29a;translated;translated/kRO_english;kRO
> charBlockSize 147
> ```

Thank you so much sir! now it's working!
