### ISSUE TITLE
Disconnected from Map Server, refuse to walk & attack

### ISSUE THREAD

**Issue by Keeynt** [OpenKore/openkore#2693]
Dears, 

Can someone help me with my problem, below issue for your information.

Server Info:

# rumble.ro-game.net
[RumbleRO]
ip 162.248.93.197
port 6900
master_version 1
version 55
serverType kRO_RagexeRE_2015_10_29a
serverEncoding Western
private 1
addTableFolders kRO/RagexeRE_2015_10_29a;translated;translated/kRO_english;kRO
charBlockSize 147

[recvpackets.txt](https://github.com/OpenKore/openkore/files/3003233/recvpackets.txt)

**After logging-in for 2-3 mins, he'll disconnect automatically.** (Attached Screenshot for reference)
![Disconnected from Map Server](https://user-images.githubusercontent.com/48887916/54920087-5aed8800-4f13-11e9-9a29-d4203ab51bd5.JPG)

mon_control.txt is empty so he will attack all monsters
Attached config.txt for reference.
[config.txt](https://github.com/OpenKore/openkore/files/3003247/config.txt)

Please, thank you!

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by sctnightcore** [comment]
```
// 2015-10-29aRagexe
#elif PACKETVER == 20151029
	parseable_packet(0x0202,5,clif_parse_ChangeDir,2,4);
	parseable_packet(0x022D,19,clif_parse_WantToConnection,2,6,10,14,18);
	parseable_packet(0x023B,26,clif_parse_FriendsListAdd,2);
	parseable_packet(0x0281,-1,clif_parse_ItemListWindowSelected,2,4,8,12);
	parseable_packet(0x035F,6,clif_parse_TickSend,2);
	parseable_packet(0x0360,6,clif_parse_ReqClickBuyingStore,2);
	parseable_packet(0x0361,5,clif_parse_HomMenu,2,4);
	parseable_packet(0x0362,6,clif_parse_DropItem,2,4);
	//parseable_packet(0x0363,8,NULL,0); // CZ_JOIN_BATTLE_FIELD
	parseable_packet(0x0364,8,clif_parse_MoveFromKafra,2,4);
	parseable_packet(0x0365,18,clif_parse_PartyBookingRegisterReq,2,4);
	parseable_packet(0x0366,90,clif_parse_UseSkillToPosMoreInfo,2,4,6,8,10);
	parseable_packet(0x0368,6,clif_parse_SolveCharName,2);
	parseable_packet(0x0369,7,clif_parse_ActionRequest,2,6);
	//parseable_packet(0x0436,4,NULL,0); // CZ_GANGSI_RANK
	parseable_packet(0x0437,5,clif_parse_WalkToXY,2);
	parseable_packet(0x0438,10,clif_parse_UseSkillToPos,2,4,6,8);
	parseable_packet(0x07E4,6,clif_parse_TakeItem,2);
	parseable_packet(0x07EC,8,clif_parse_MoveToKafra,2,4);
	parseable_packet(0x0802,26,clif_parse_PartyInvite2,2);
	parseable_packet(0x0811,-1,clif_parse_ReqTradeBuyingStore,2,4,8,12);
	parseable_packet(0x0815,-1,clif_parse_ReqOpenBuyingStore,2,4,8,9,89);
	parseable_packet(0x0817,2,clif_parse_ReqCloseBuyingStore,0);
	parseable_packet(0x0819,-1,clif_parse_SearchStoreInfo,2,4,5,9,13,14,15);
	parseable_packet(0x0835,2,clif_parse_SearchStoreInfoNextPage,0);
	parseable_packet(0x0838,12,clif_parse_SearchStoreInfoListItemClick,2,6,10);
	parseable_packet(0x083C,10,clif_parse_UseSkillToId,2,4,6);
	parseable_packet(0x0860,36,clif_parse_StoragePassword,0);
	parseable_packet(0x096A,6,clif_parse_GetCharNameRequest,2);
```
checked is true ...

**Comment by Keeynt** [comment]
> ```
> // 2015-10-29aRagexe
> #elif PACKETVER == 20151029
> 	parseable_packet(0x0202,5,clif_parse_ChangeDir,2,4);
> 	parseable_packet(0x022D,19,clif_parse_WantToConnection,2,6,10,14,18);
> 	parseable_packet(0x023B,26,clif_parse_FriendsListAdd,2);
> 	parseable_packet(0x0281,-1,clif_parse_ItemListWindowSelected,2,4,8,12);
> 	parseable_packet(0x035F,6,clif_parse_TickSend,2);
> 	parseable_packet(0x0360,6,clif_parse_ReqClickBuyingStore,2);
> 	parseable_packet(0x0361,5,clif_parse_HomMenu,2,4);
> 	parseable_packet(0x0362,6,clif_parse_DropItem,2,4);
> 	//parseable_packet(0x0363,8,NULL,0); // CZ_JOIN_BATTLE_FIELD
> 	parseable_packet(0x0364,8,clif_parse_MoveFromKafra,2,4);
> 	parseable_packet(0x0365,18,clif_parse_PartyBookingRegisterReq,2,4);
> 	parseable_packet(0x0366,90,clif_parse_UseSkillToPosMoreInfo,2,4,6,8,10);
> 	parseable_packet(0x0368,6,clif_parse_SolveCharName,2);
> 	parseable_packet(0x0369,7,clif_parse_ActionRequest,2,6);
> 	//parseable_packet(0x0436,4,NULL,0); // CZ_GANGSI_RANK
> 	parseable_packet(0x0437,5,clif_parse_WalkToXY,2);
> 	parseable_packet(0x0438,10,clif_parse_UseSkillToPos,2,4,6,8);
> 	parseable_packet(0x07E4,6,clif_parse_TakeItem,2);
> 	parseable_packet(0x07EC,8,clif_parse_MoveToKafra,2,4);
> 	parseable_packet(0x0802,26,clif_parse_PartyInvite2,2);
> 	parseable_packet(0x0811,-1,clif_parse_ReqTradeBuyingStore,2,4,8,12);
> 	parseable_packet(0x0815,-1,clif_parse_ReqOpenBuyingStore,2,4,8,9,89);
> 	parseable_packet(0x0817,2,clif_parse_ReqCloseBuyingStore,0);
> 	parseable_packet(0x0819,-1,clif_parse_SearchStoreInfo,2,4,5,9,13,14,15);
> 	parseable_packet(0x0835,2,clif_parse_SearchStoreInfoNextPage,0);
> 	parseable_packet(0x0838,12,clif_parse_SearchStoreInfoListItemClick,2,6,10);
> 	parseable_packet(0x083C,10,clif_parse_UseSkillToId,2,4,6);
> 	parseable_packet(0x0860,36,clif_parse_StoragePassword,0);
> 	parseable_packet(0x096A,6,clif_parse_GetCharNameRequest,2);
> ```
> checked is true ...

Any suggestion sir?

**Comment by sctnightcore** [comment]
client date is 20151102  -*-
why u say `1,I used UE Explorer , the time date stamp is 29/10/2015.` ? 

lol

**Comment by sctnightcore** [comment]
```
[RumbleRO]
ip 162.248.93.197
port 6900
master_version 1
version 55
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
private 1
addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO
charBlockSize 147
```
![image](https://user-images.githubusercontent.com/23263315/54946919-b8152800-4f6b-11e9-8134-38d93e7702f4.png)
