### ISSUE TITLE
Private server Erro map

### ISSUE THREAD

**Issue by crashburne** [OpenKore/openkore#2695]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2019_03_27

* **Server**: Private server 

* **Bug Report / Feature Request**:Failed to connect with map server

* **Summary**:
ip 177.54.156.133
port 6900
master_version 16
version 115
serverType kRO_RagexeRE_2012_04_10a
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders bRO
charBlockSize 144
pinCode 1

server site http://www.onepieceonline.com.br/

![Sem título](https://user-images.githubusercontent.com/49005592/55114938-0b998a00-50c2-11e9-91f1-85494ace6c2d.png)

**Comment by sctnightcore** [comment]
Clientdate  ? 
id pw for test ?

**Comment by crashburne** [comment]
this? :http://www.mediafire.com/file/zsid8tygsyl3rp3/One_Piece_Online.exe/file


![image](https://user-images.githubusercontent.com/49005592/55115997-a98e5400-50c4-11e9-90a1-ec60669f6e56.png)
![image](https://user-images.githubusercontent.com/49005592/55116016-bc088d80-50c4-11e9-8706-1e8f4715e43b.png)

**Comment by crashburne** [comment]
id alanzinho
pw alanzinho44

**Comment by sctnightcore** [comment]
try
`addTableFolders kRO/RagexeRE_2012_04_10a;translated;translated/kRO_english;kRO`

**Comment by crashburne** [comment]
thx bro
it worked
but now i have the erro 
![image](https://user-images.githubusercontent.com/49005592/55203095-fba8a580-51a8-11e9-81ee-2338053faf26.png)

**Comment by devilsir** [comment]
ow, c conseguiu rodar o bot no fim?
