### ISSUE TITLE
Macro Storage get & autosell

### ISSUE THREAD

**Issue by Keeynt** [OpenKore/openkore#2696]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

Can anyone help me with my macro issue? I just want to get the item from the storage and sell the gold directly to the npc, below is my macro sample. Thank you!

automacro storage {
console /You are now sitting./
call storage
}

macro storage {
do c @storage
pause .5
do storage get 1 627
pause .5
do storage close
release storage
}

automacro sell
console /You are now: Owg 50%/
run-once 1
call sell
}

macro sell {
do talknpc 161 181 c r0
pause .5
do sell
pause .5
do sell 2 627
pause .5
do sell done
release sell
}

**Comment by Nipodemos** [comment]
to get the index of the item correctly, you use: 
`@storage(Name of Item)`

and to get from inventory, you must use:
`@inventory(Name of Item)`


in the storage macro:
`do storage get @storage(NameOfItem) 627`

in the sell macro:
`do sell @inventory(NameOfItem) 627


i believe this will fix
if not fix, show us the error

**Comment by lututui** [comment]
Kore can open storage through chat commands, no need for macro

**Comment by Keeynt** [comment]
> Kore can open storage through chat commands, no need for macro

Precisely Sir, however, I would like the bot to do it.

**Comment by alisonrag** [comment]
http://openkore.com/index.php/Category:Storage

**Comment by alisonrag** [comment]
http://openkore.com/index.php/StorageAuto_useChatCommand
