### ISSUE TITLE
iRO packet unknown switch: 0886 and got dc

### ISSUE THREAD

**Issue by kharlessha** [OpenKore/openkore#2704]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: the newest client

* **Server**: iRO renewal

* **Bug Report / Feature Request**: bug report

* **Summary**: used openkore and update the tables iro renewal. used to vending. when the shop is open, later it will show unknown packet switch 0886 3 times. and suddenly vendor bot got disconnect.

![Untitled](https://user-images.githubusercontent.com/49101068/55278873-e66c7c00-534c-11e9-99db-dea12922f64e.png)

**Comment by sctnightcore** [comment]
``` 0A28 It has in openkore . update u bot 
0A28
// 0 - open vending success
// 1 - message MSG_MERCHANTSHOP_MAKING_FAIL
// 2 - silent ignore
// 3 - message MSG_ID_C9D (You can not open a stall at the current location)
```

**Comment by Fadreus** [comment]
@kharlessha 
You surely not using latest version.

**Comment by kharlessha** [comment]
Ahhhh alright. Even i dont too understand what it is mean, really appreciate!
Thanks for helping sir, it is solved now :)
