### ISSUE TITLE
header incorrect

### ISSUE THREAD

**Issue by crashburne** [OpenKore/openkore#2707]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2019_03_27

* **Server**: private server kro

* **Bug Report / Feature Request**:after login in the server i recive this 
![55203095-fba8a580-51a8-11e9-81ee-2338053faf26](https://user-images.githubusercontent.com/49005592/55372176-2eb7a580-54d7-11e9-9469-faf1313b53ee.png)

* **Summary**:actor removido cujas coordenadas estavam fora do limite do mapa:

**Comment by alisonrag** [comment]
this is clearly a error in custom map, about actor removed out of the range, this can be a wrong clientdate in servers.txt
