### ISSUE TITLE
Can't we use AI on this thing already?

### ISSUE THREAD

**Issue by kevinreyes9566** [OpenKore/openkore#2708]
I'm suggesting that instead typing everything manually like editing the way openkore calculating routes to a map we should use ML DL and AI to do that for us. And also we need CI CD

**Comment by sctnightcore** [comment]
ML DL ? CI CD ?

**Comment by Fadreus** [comment]
Are you drunk?

**Comment by Fadreus** [comment]
Are you drunk?
My 4 years old niece can wrote better than this. :thinking:

**Comment by Fadreus** [comment]
@kevinreyes9566 Are you drunk?
If you want to report, use template.
If you want to request feature, use template.
If you want to suggest changes, make PR.
If you want to ask, use IRC.

If you want to talk nonsense, go Twitter.

**Comment by c4c1n6kr3m1** [comment]
he is too smart, and the result is no one understand what he said . . . . .

**Comment by Fadreus** [comment]
![11074439_628591427242862_3970254854802538360_n](https://user-images.githubusercontent.com/32188494/55404219-02a92c80-558a-11e9-8a3d-5f4b17f2aa83.jpg)

**Comment by lututui** [comment]
Feel free to do it

I'm not getting paid to do it and there's too much effort involved
