### ISSUE TITLE
Iro-renewal bot not working new patch

### ISSUE THREAD

**Issue by nicolejakereyes** [OpenKore/openkore#2711]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by nicolejakereyes** [comment]
Sorry i'm kinda new to this stuffs. if only someone would show me how to properly fix this issue i would appreciate it. thank you.

**Comment by Fadreus** [comment]
@nicolejakereyes 
Every newbie need to do lot of reading.
But the most important is to reading the basics.
And the basic things to know is on the front page here:
https://github.com/OpenKore/openkore#weekly-maintence-on-official-servers

**Comment by nicolejakereyes** [comment]
Hi guys. iknow its on my end, but every master was once a beginner. Like i said just show or guide what to do and i'll do the rest. You Devs are awesome. Thank you.

**Comment by Fadreus** [comment]
@nicolejakereyes 
![image](https://user-images.githubusercontent.com/32188494/55666138-bb1deb80-587c-11e9-9fa4-14aec20dd731.png)
