### ISSUE TITLE
Update IRO renewal

### ISSUE THREAD

**Issue by OPKTH** [OpenKore/openkore#2712]
**IRO Renewal Update**

![8888](https://user-images.githubusercontent.com/49314693/55636296-c3c6e100-57ec-11e9-9dff-1cf03da0d828.jpg)

**Comment by alisonrag** [comment]
#2711

**Comment by Fadreus** [comment]
@OPKTH Calm your tits.
Read here:
https://github.com/OpenKore/openkore#weekly-maintence-on-official-servers
