### ISSUE TITLE
Vending issue

### ISSUE THREAD

**Issue by Flanged** [OpenKore/openkore#2716]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
 Just downloaded fresh as of this writing
* **Server**: 
iRO Renewal
* **Bug Report / Feature Request**:
When attempting to vend the bot will do the below continually in the console never actually vending:
[Apr 08 22:01:07 2019.54] You are casting Vending on yourself (Delay: 0ms)
[Apr 08 22:01:07 2019.67] You are now: EFST_STOP
[Apr 08 22:01:07 2019.70] You can sell 12 items!
[Apr 08 22:01:12 2019.78] You need this with a cart in order to create a shop!
[Apr 08 22:01:12 2019.93] "any work in progress (NPC dialog, manufacturing...)quit and try again.#"
[Apr 08 22:01:13 2019.54] You are now: Sitting
[Apr 08 22:01:13 2019.67] You are sitting.
[Apr 08 22:01:13 2019.81] "any work in progress (NPC dialog, manufacturing...)quit and try again.#"
[Apr 08 22:01:13 2019.91] You are no longer: Sitting
[Apr 08 22:01:13 2019.95] You are standing.
[Apr 08 22:01:14 2019.89] "any work in progress (NPC dialog, manufacturing...)quit and try again.#"
* **Summary**:

The merchant has a cart and the items are in the cart. This problem started maybe ~2 weeks ago and have been trying different settings including getting the most up-to-date version and following the Wiki's instructions and doing nothing else. At one point I added the shop_useSkill_delay option which actually worked  but only once and then the problem resurfaced. I've tested this out with a simple shop.txt using just a short title and a single item to no avail. Any insight would be greatly appreciated!

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/55791060-494dd800-5af0-11e9-9a9b-b3e9dc431046.png)

I have no problem with latest version.
Setup new again, don't copy-paste from your old config and give feedback.

**Comment by Flanged** [comment]
It works, took the advice and didn't copy any files. I also as a habit always extract the revpackets and didn't do that either so thank you!
