### ISSUE TITLE
dllgen:reference location not found ERROR

### ISSUE THREAD

**Issue by dcyxxt** [OpenKore/openkore#2717]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: private Sever

* **Bug Report / Feature Request**:

* **Summary**:

when i use peek1.1 to open the client,ant then click the extract lengths,it will appeart the error
 
and i have on idea to PacketLengths file

here is the client ant luancher

https://drive.google.com/drive/folders/1wDpp7GiEk0Q6AlY9HXdayOU0uBQ1fnIi

**Comment by sctnightcore** [comment]
try https://gitlab.com/4144/peek

**Comment by dcyxxt** [comment]
> try https://gitlab.com/4144/peek

yes, i used this vision

**Comment by sctnightcore** [comment]
> > try https://gitlab.com/4144/peek
> 
> yes, i used this vision

try rename client name .

**Comment by sctnightcore** [comment]
:thinking: click START RECORDER .

**Comment by dcyxxt** [comment]
> 🤔 click START RECORDER .
> see output
still "dllgen:reference location not found"
structs.qs in the output folder

[structs.zip](https://github.com/OpenKore/openkore/files/3059075/structs.zip)

**Comment by sctnightcore** [comment]
@dcyxxt  I think if u cannot get it . I think server use patch NEMO for AntiPEEK.

**Comment by dcyxxt** [comment]
> @dcyxxt I think if u cannot get it . I think server use patch NEMO for AntiPEEK.

so....what can i do?can you give me a direction？？T.T

**Comment by sctnightcore** [comment]
I cannot do it too .T.T
