### ISSUE TITLE
Timeout map

### ISSUE THREAD

**Issue by duanekurt** [OpenKore/openkore#2727]
[PVP RO]
ip 66.150.155.171
port 6900
master_version 1
version 46
serverType kRO_RagexeRE_2015_11_04a
addTableFolders pvpRO
pinCode 0
charBlockSize 147
sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9

![Capture](https://user-images.githubusercontent.com/30798050/56076588-d7ce9c00-5e05-11e9-9aff-49212f9816f2.PNG)

**Comment by sctnightcore** [comment]
try ```addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO```
without sendCryptKeys

**Comment by duanekurt** [comment]
> try `addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO`
> without sendCryptKeys

still getting the same error

**Comment by sctnightcore** [comment]
> > try `addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO`
> > without sendCryptKeys
> 
> still getting the same error

Are u sure clientdate is 20151104 ?

**Comment by duanekurt** [comment]
> 20151104

![Capture](https://user-images.githubusercontent.com/30798050/56076799-963ef080-5e07-11e9-95f9-59f1c3f2ba4e.PNG)

Thats the closest am i wrong?

**Comment by sctnightcore** [comment]
try sendCryptKeys 1,3,2 ?

**Comment by duanekurt** [comment]
> try sendCryptKeys 1,3,2 ?

sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9

My first config is with the 1,3,2 setup still doesnt work :(

**Comment by duanekurt** [comment]
Incoming data left in the buffer:
================================================
3 bytes   Apr 13 16:21:20 2019
  0>  81 00 08                                              ...
Disconnecting (66.150.155.171:6900)...disconnected

and i occasionally getting this error

**Comment by sctnightcore** [comment]
try add #sendCryptKeys

**Comment by duanekurt** [comment]
> try add #sendCryptKeys

[PVP RO]
ip 66.150.155.171
port 6900
master_version 1
version 46
serverType kRO_RagexeRE_2015_11_04a
addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO
pinCode 0
#clientHash 2E0000006475616E656B7572743100A3 
charBlockSize 147
#sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9

Like this?

**Comment by duanekurt** [comment]
wow it works thanks alot sir!

**Comment by sctnightcore** [comment]
yes
