### ISSUE TITLE
Assertion ('Actor::Item' must be blessed) failed!

### ISSUE THREAD

**Issue by igormdiniz** [OpenKore/openkore#2731]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

i use it on bRO, since last weeks release, started with an error when starting, in the process it crashes and send me the error, according to openkore.com, it says that its not updated, but i checked 3 times by now, its sync with git
[errors.txt](https://github.com/OpenKore/openkore/files/3081384/errors.txt)

**Comment by alisonrag** [comment]
patched 22 hours ago.

#2729
