### ISSUE TITLE
[eventMacro] Validator::NumericComparison doesn't work properly with vars

### ISSUE THREAD

**Issue by Nipodemos** [OpenKore/openkore#2736]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: version git:d4c4286_2019-04-18 ctime:2019_04_18

* **Server**:  any

* **Bug Report / Feature Request**: Bug Report

* **Summary**: In condition **MobNearCount**, which uses as base the NumericComparison, does not work when you use variables
looking a little deeper into the code, i noticed that `$self->{min}` and `$self->{max}` are set as undef when use variables, but it never gets updated when variable value updates.
Unfortunaly i don't know how to solve this problem, it only works if you don't use variables

**Comment by lututui** [comment]
$self->{min} and $self->{max} are supposed to be undef when using vars. Parsing is correct.

Values aren't being retrieved during validation, resulting in false response whenever using vars

**Comment by Nipodemos** [comment]
solved on #2740
