### ISSUE TITLE
fRO login error

### ISSUE THREAD

**Issue by analfabetagamma** [OpenKore/openkore#2744]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by analfabetagamma** [comment]
OpenKore what-will-become-2.1 ( version ctime:2019_03_13 )
fRO
The error message is:
Can't call method "baseName" on an undefined value at src/Network/Receive.pm line 1814.

**Comment by sctnightcore** [comment]
Download new openkore again !

**Comment by analfabetagamma** [comment]
Thank you.

**Comment by analfabetagamma** [comment]
The problem remained,

Unknown #50001 shown unknown effect 9999 at location 135, 64 with the color [R:255, G:255, B:0, A:0]

**Comment by analfabetagamma** [comment]
It was a trying to grant me to GM...
