### ISSUE TITLE
Reopen

### ISSUE THREAD

**Issue by analfabetagamma** [OpenKore/openkore#2745]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

Please reopen #2744

**Comment by sctnightcore** [comment]
go IRC

**Comment by analfabetagamma** [comment]
I have no IRC.

**Comment by sctnightcore** [comment]
https://kiwiirc.com/client/irc.freenode.net/?nick=IRC-Source_?#openkore

**Comment by analfabetagamma** [comment]
are you here?
