### ISSUE TITLE
fRO update failed

### ISSUE THREAD

**Issue by analfabetagamma** [OpenKore/openkore#2747]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by analfabetagamma** [comment]
#2744, #2745 
Today's result: Timeout on Character Select Server, reconnecting...

**Comment by analfabetagamma** [comment]
fixing failed

**Comment by Fadreus** [comment]
Stick to 1 thread, you can do that much, could you?
Why you need to make 3 thread?

**Comment by Fadreus** [comment]
Stick to 1 thread. 
You can do that much, could you?
Why you need to make 3 threads?

**Comment by analfabetagamma** [comment]
Because 2 of them is closed... but the error is remained.

**Comment by Fadreus** [comment]
Tested in fRO
No problem.
![image](https://user-images.githubusercontent.com/32188494/56755438-1e3ad800-67c2-11e9-87f8-6e4438885b9a.png)

Download new on again.

**Comment by analfabetagamma** [comment]
Working. Thank you.
