### ISSUE TITLE
Timeout on Account Server, 

### ISSUE THREAD

**Issue by sar3of** [OpenKore/openkore#2753]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
openkore_master version
![‏‏لقطة الشاشة (121)](https://user-images.githubusercontent.com/50479838/57511308-a74d2580-7311-11e9-9359-fac25bbdc58f.png)

* **Server**: 
kRO Private server
* **Bug Report / Feature Request**:
Times out
* **Summary**:
hello, im noob at openkore , i have an issue when I tried for 3 days to make openkore work , but it doesn't join, and it shows times out. btw, I'm using 2018.04.16 client  

here is my server.txt
```
# This file contains information about master servers.

#####################
# Official RO Servers

[Old Arabic Ragnarok Online]
ip 172.104.139.212
port 6900
private 1
master_version 23
version 55
serverType kRO_RagexeRE_2018_03_07b
serverEncoding Korean
charBlockSize 155
chatLangCode 0
addTableFolders kRO/Zero;pserver;translated;translated/kRO_english;kRO;iRO

```

**Comment by sar3of** [comment]
any help, please!

**Comment by alisonrag** [comment]
link?

**Comment by alisonrag** [comment]
server offline, can be a mistake in missing sendcryptkeys or in add wrong table folder.

if server back online reopen the issue

**Comment by sar3of** [comment]
nuh, I have done it by myself thx mate
