### ISSUE TITLE
fRO cards ere missing

### ISSUE THREAD

**Issue by analfabetagamma** [OpenKore/openkore#2754]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by analfabetagamma** [comment]
newest git
fRO
Brasilis cards are missing from the items table
please fix it

**Comment by analfabetagamma** [comment]
Closing was a mistake.

**Comment by analfabetagamma** [comment]
Plus the "Nightmare" cards in the Pyramid.

**Comment by analfabetagamma** [comment]
sctnightcore please give me a short answer...

**Comment by analfabetagamma** [comment]
... I am not an expert in the git developing...

**Comment by sctnightcore** [comment]
@analfabetagamma  read http://openkore.com/index.php/Category:Tables
u can update tables with u self . 
I'm lazy for update fRO :p

**Comment by analfabetagamma** [comment]
where can I find the full tables?

**Comment by sctnightcore** [comment]
@analfabetagamma  data.grf
if u read  http://openkore.com/index.php/Category:Tables 
you can know how to do it ..
