### ISSUE TITLE
INIFINITUS-RO

### ISSUE THREAD

**Issue by slashgg2019** [OpenKore/openkore#2777]
KINDLY HELP ME getting RECVPACKETS, the server has no GEPARD or BOT SHIELD.

This is the site :

http://infinitus-ro.com/

i've got only SERVER INFO:

[Infinitus-RO]]
ip 23.227.163.122
port 6900
version 32
master_version 1
serverType RMS
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2014_10_22b;translated;translated/kRO_english;kR

**Comment by sctnightcore** [comment]
I'm lazy for help .

**Comment by slashgg2019** [comment]
Please sir sctnightcore

**Comment by slashgg2019** [comment]
anybody help me?

**Comment by sctnightcore** [comment]
I'm not God. To know what you are looking for. Please enter more information.

**Comment by slashgg2019** [comment]
i'd like to know the recvpackets of this server, so hard to get the recvpakcets using PACKET EXTRACTOR v3 & PEEK, the information is on the topic

**Comment by slashgg2019** [comment]
[https://imagizer.imageshack.com/img921/8203/EfXvOy.png](url)


i got this error

**Comment by sctnightcore** [comment]
https://gitlab.com/4144/peek
try it . 
if u cannot get it . It patch with anti peek from nemo tool .

**Comment by slashgg2019** [comment]
Same problem, not solved, so no solutions for this?

**Comment by hikashin** [comment]
Hahahaha Extracting it will resulting like a noob :3

**Comment by slashgg2019** [comment]
fuck that nightcore

**Comment by slashgg2019** [comment]
fuck you !

**Comment by slashgg2019** [comment]
deleted my comment? fuckin` scnightcore, f0ck malaysia, thailand, singapore !
