### ISSUE TITLE
How to find a Ragexe 2015 11 05 version for ServerType and made it ? 

### ISSUE THREAD

**Issue by reguszii** [OpenKore/openkore#280]
My ragexe is version 2015 11 05 how to made this file in .pm ? and 

i just learned from http://www.openkore.com/index.php/ServerType

but i don't know how 

what should i do first or advice about tools ?

for test with a private servers.

thx.....

**Comment by AlexandreBR3N** [comment]
The unique information about this date 👍 

https://github.com/rathena/rathena/commit/71c68965412cea75e48e256df6e287d2de276bbe

You should have knowledgment about serverType structure. No automatic tools. If you want i can provide for u a new serverType for you to test.

**Comment by reguszii** [comment]
@AlexandreBR3N  thank you so much i will try :)

**Comment by Nyxvanthcal** [comment]
For while : 

http://forums.openkore.com/viewtopic.php?f=9&t=211704

**Comment by sctnightcore** [comment]
Now openkore updates ST2017.
♥
