### ISSUE TITLE
ROPH  BOT

### ISSUE THREAD

**Issue by akumaishere** [OpenKore/openkore#2800]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

Hi everyone im reaching out for help coz im desprate to work the bot on my server
i changed everything according to the resources that i read about the error that im facing 
1. control.txt change to xcore 1 or xcore 2
2. check the revpackets
3. connections IP add and port. i used the wire shark to double check and its 100% accurate from the latest file that im downloaded
![Screenshot (61)](https://user-images.githubusercontent.com/51767399/59395490-3656be80-8d52-11e9-934a-91a1f9dd2707.png)

and im 100 % sure that the Openkore is working because based on my observation and experience  from botting to other server like iRO. i know its Openkore 

Thank you so much Devs i hope u can help me to this problem :(

**Comment by sctnightcore** [comment]
OpenKore dont work in pRO .
if u want . u need buy bot from someone .
