### ISSUE TITLE
Help!! MYYSG BOT !!

### ISSUE THREAD

**Issue by rickng89** [OpenKore/openkore#2802]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by Nipodemos** [comment]
WTF?

tell what you want, follow the issue template

**Comment by rickng89** [comment]
Fuck u

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 13, 2019 at 1:08 PM, Nipodemos<notifications@github.com> wrote:   
WTF?

tell what you want, follow the issue template

**Comment by sctnightcore** [comment]
.... ?

**Comment by Fadreus** [comment]
This is why I'm on Thanos side.
