### ISSUE TITLE
This way, please, [xkore3] landing problem

### ISSUE THREAD

**Issue by Xubenw** [OpenKore/openkore#2808]
The private server works in XKORE 3 and downloads the latest openkore. Nothing else was done except to imitate this page, https://wiki.wetfish.net/xkore, and everything was set up to start with an administrator. That's what happened.

When I logged in, I could see my role and he was online on the map, **but XKore tried to connect like crazy** (#520 this problem is the same as mine, please God solve it. Trouble for several days)

Is this setting correct?

![微信截图_20190620104558](https://user-images.githubusercontent.com/34146691/59816110-694e1300-934d-11e9-8b5d-01bb1735e82c.png)
![1111](https://user-images.githubusercontent.com/34146691/59851655-c1156a00-939f-11e9-85c4-6b6894b7d9e4.png)
![微信截图_20190620110437](https://user-images.githubusercontent.com/34146691/59816135-884ca500-934d-11e9-897d-c12497cc88f4.png)

**Comment by Xubenw** [comment]
The private server line:  [https://share.weiyun.com/5aaSfXY](url)

**Comment by ya4ept** [comment]
I need a test account

**Comment by Xubenw** [comment]
> 我需要一个测试帐户

benyuty.benyuty

**Comment by ya4ept** [comment]
@Xubenw, you have wrong settings charBlockSize
correct `sendCryptKeys` must also be defined

**Comment by Xubenw** [comment]
> @Xubenw，你有错误的设置，还必须定义charBlockSize 
> 正确`sendCryptKeys`

Thanks.what should I do to run it?

**Comment by ya4ept** [comment]
use search
http://forums.openkore.com/viewtopic.php?f=10&t=212535&hilit=sendCryptKeys

**Comment by Xubenw** [comment]
> 使用搜索
> http://forums.openkore.com/viewtopic.php?f=10&t=212535&hilit=sendCryptKeys

Thanks bro. Is done...NO problem.How exciting when I saw the character on line!!! For nice day bro//
