### ISSUE TITLE
build openkore in termux without install ubuntu! 

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#2813]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**: Feature Request

* **Summary**: I think we need build in termux without install ubuntu .

https://jejakatutorial-official.blogspot.com/2019/02/ubuntu-is-one-of-linux-distributions.html
![image](https://user-images.githubusercontent.com/23263315/60126565-7e48fd00-97b8-11e9-8c22-76ecb9ed29f8.png)

**Comment by alisonrag** [comment]
ubuntu is a necessary dependence, termux as itself can't run, even if u install the regular dependences
