### ISSUE TITLE
how to encrypte servers.txt without change any code?

### ISSUE THREAD

**Issue by royluo1984** [OpenKore/openkore#2821]
Is there a way to encrypt or hide the server information in the /tables/servers.txt without change any code?

eg master_version, sendCryptKeys and etc...

**Comment by Fadreus** [comment]
Elaborate

**Comment by alisonrag** [comment]
Elaborate:
Im trying to sell openkore for a individual server and i dont want my customer copying my config and reselling

**Comment by sctnightcore** [comment]
xD

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/60953020-f1ad4b80-a32e-11e9-89de-482fe9544736.png)

This should answer him.
"Encrypt" and "Hide".
LOL
:laughing:

**Comment by royluo1984** [comment]
@Fadreus @alisonrag @sctnightcore
yes and no. I am trying to host a PVP focused RO server (equipment will drop on death), and I want to provide players a limited edition openkore so they can bringer a priest when them all the time and go afk for a bit when they needed.

**Comment by Fadreus** [comment]
No offense brother but this Github Repositories is mainly for:

- Reporting bugs
- Implement kRO updates
- Improving openkore

Other things should go to forums.

**Comment by sctnightcore** [comment]
@royluo1984
i think u can check server 
npc script =https://www.google.co.th/url?sa=t&source=web&rct=j&url=https://rathena.org/board/topic/84890-universal-script-freebies-1-per-ip/&ved=2ahUKEwiMjdLG5q_jAhUbi3AKHTLoA7QQFjAAegQICBAB&usg=AOvVaw06U1mf9h4uPY_eGpzm1JlF


something like it.
