### ISSUE TITLE
Error on Unknown charBlockSize:  at src/Network/Receive.pm line 672.

### ISSUE THREAD

**Issue by sennincito** [OpenKore/openkore#2827]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

```
Hello I am using the latest updated (updated using TortoiseSVN) and I am receiving this error: 
Unknown charBlockSize:  at src/Network/Receive.pm line 672.
 at src/Network/Receive.pm line 672
	Network::Receive::received_characters_unpackString('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)') called at src/Network/Receive.pm line 709
	Network::Receive::received_characters('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)', 'HASH(0x6abbe6c)') called at src/Network/Receive.pm line 703
	Network::Receive::received_characters_slots_info('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)', 'HASH(0x6abbe6c)') called at src/Network/Receive.pm line 856
	Network::Receive::received_characters_info('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)', 'HASH(0x6abbe6c)') called at src/Network/PacketParser.pm line 276
	Network::PacketParser::parse('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)', 'k\x{0}\x{84}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{f6}K\x{2}\x{0}\x{ac}\x{0}\x{0}\x{0}2\x{2}\x{0}\x{0}\x{82}\x{1}\x{0}\x{0}\x{a}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}...', 'Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)') called at src/Network/Receive.pm line 493
	Network::Receive::parse('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)', 'k\x{0}\x{84}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{f6}K\x{2}\x{0}\x{ac}\x{0}\x{0}\x{0}2\x{2}\x{0}\x{0}\x{82}\x{1}\x{0}\x{0}\x{a}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}...', 'Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)') called at src/Network/PacketParser.pm line 410
	Network::PacketParser::process('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)', 'Network::MessageTokenizer=HASH(0x3a4eb44)', 'Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x666a344)') called at src/functions.pl line 757
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x327557c)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
          } else {
* 		    die "Unknown charBlockSize: $_";
  		}
```
this is the server I am using: 
```
[midgar]
ip 104.248.237.34
port 6900
version 20
master_version 1
serverType kRO_Sakexe_2008_03_25b
addTableFolders 
serverEncoding Western
charblocksize 106
recvpackets recvpackets.txt
```
I have noted that if I change serverType to 8_1 I dont receive any error, however it never connects to char map, this is the error: 
```
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   MidgarKingdom!        35     104.248.237.34  6121
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (104.248.237.34:6900)...disconnected
Connecting to Character Server...
Selected server: MidgarKingdom!
Connecting (104.248.237.34:6121)... connected
Timeout on Character Select Server, reconnecting...
Disconnecting (104.248.237.34:6121)...disconnected
```
I've tried updating serverType and charblocksize to many different ones, but I never get to connect. 

I have extracted recvpackets.txt as well but I dont think that could be the problem. 
what could be the issue on this case? 
I have around a week trying to make this work and I am getting frustrated now.

**Comment by sctnightcore** [comment]
client 2008 lollll

**Comment by sennincito** [comment]
https://github.com/OpenKore/openkore/issues/2827#issuecomment-511250624

I know right!!! But thats the info I got with PE viewer

**Comment by sctnightcore** [comment]
@senincito 

can u check in game?

are sure client is 2008?

**Comment by sennincito** [comment]
look at this: 
![image](https://user-images.githubusercontent.com/52898321/61192127-4a525080-a66f-11e9-9539-987fcde02f49.png)

**Comment by sennincito** [comment]
> @senincito
> 
> can u check in game?
> 
> are sure client is 2008?

**Comment by ya4ept** [comment]
@sennincito send a link to the server

**Comment by sennincito** [comment]
@ya4ept this is the link to the server:
http://www.midgarkingdom.tk/?fbclid=IwAR26LvyeFbcABzUUvA2IAerBXuFjShmvKfSznsWlJdq6A6GANtrVJ_nJQ9Q

**Comment by sennincito** [comment]
Im reopening the case since a solution has not being provided to my request or there is no reason added of why the issue was closed, if there is a reason could you please let me know to understand why this was closed?

**Comment by alisonrag** [comment]
![image](https://user-images.githubusercontent.com/10372732/61224535-20dc0800-a6f5-11e9-89ba-8eaa25cf1c5d.png)

**Comment by alisonrag** [comment]
must be `charBlockSize` not `charblocksize`.

`B` and `S` must be capital letter

**Comment by sennincito** [comment]
OMG I must be crazy, anyhow, issue still open so I am open to your suggestions. I am very frustrated at this point.

**Comment by alisonrag** [comment]
> must be `charBlockSize` not `charblocksize`.
> 
> `B` and `S` must be capital letter

**Comment by sennincito** [comment]
> servers.txt:
> 
> > must be `charBlockSize` not `charblocksize`.
> > `B` and `S` must be capital letter

I've updated to `charBlockSize` and issue looks fixed, however I get wrong char information, I've tried all from the list but are not working (list: http://openkore.com/index.php/CharBlockSize).
Any other suggestion?

![image](https://user-images.githubusercontent.com/52898321/61227041-c638b100-a6e0-11e9-890a-021c2e9acc1b.png)

**Comment by alisonrag** [comment]
control/config.txt
debugPacket_received 1

before charselection you gonna see 006B or 082D or 099D with length/size in bytes.
to know the right charblocksize
`(size -4) / total chars in account`

**Comment by sennincito** [comment]
this is the result: 
![image](https://user-images.githubusercontent.com/52898321/61228694-04839f80-a6e4-11e9-82f8-06c2f7bcfde9.png)

Where do I translate this to the right charBlocksize?

**Comment by sctnightcore** [comment]
118 ? 
![image](https://user-images.githubusercontent.com/23263315/61232779-48fd5280-a759-11e9-9f12-7db346fcb358.png)

**Comment by sennincito** [comment]
I have added 118 and this is the result: 
![image](https://user-images.githubusercontent.com/52898321/61233428-c2f7f200-a6ed-11e9-8bf5-947fd5f4c259.png)

checking errors.txt this is the information: 
Error message:
Unknown charBlockSize: 118 at src/Network/Receive.pm line 672.

Stack trace:
Unknown charBlockSize: 118 at src/Network/Receive.pm line 672.
 at src/Network/Receive.pm line 672
	Network::Receive::received_characters_unpackString('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)') called at src/Network/Receive.pm line 709
	Network::Receive::received_characters('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)', 'HASH(0x6a10dcc)') called at src/Network/Receive.pm line 703
	Network::Receive::received_characters_slots_info('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)', 'HASH(0x6a10dcc)') called at src/Network/Receive.pm line 856
	Network::Receive::received_characters_info('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)', 'HASH(0x6a10dcc)') called at src/Network/PacketParser.pm line 276
	Network::PacketParser::parse('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)', 'k\x{0}\x{f0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{98}L\x{2}\x{0}\x{a7}\x{1}\x{0}\x{0}H\x{3}\x{0}\x{0}\x{c}\x{0}\x{0}\x{0}\x{9}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}...', 'Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)') called at src/Network/Receive.pm line 493
	Network::Receive::parse('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)', 'k\x{0}\x{f0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{98}L\x{2}\x{0}\x{a7}\x{1}\x{0}\x{0}H\x{3}\x{0}\x{0}\x{c}\x{0}\x{0}\x{0}\x{9}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}...', 'Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)') called at src/Network/PacketParser.pm line 410
	Network::PacketParser::process('Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)', 'Network::MessageTokenizer=HASH(0x3af6c84)', 'Network::Receive::kRO::Sakexe_2008_03_25b=HASH(0x6663434)') called at src/functions.pl line 757
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x32359c4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
          } else {
* 		    die "Unknown charBlockSize: $_";
  		}

**Comment by sennincito** [comment]
Hello Any feedback on this you can provide?

**Comment by Fadreus** [comment]
Just to make sure, you did try any of [this](http://openkore.com/index.php/CharBlockSize), do you?

**Comment by sennincito** [comment]
> Just to make sure, you did try any of [this](http://openkore.com/index.php/CharBlockSize), do you?

yes, all of 'em

**Comment by sennincito** [comment]
Any idea what could be causing this issue?

**Comment by c4c1n6kr3m1** [comment]
here's easy way to find the correct charblocksize
create 2 chars
sniff the packet , packet you receive the chars name
the spaces between 1st name to 2nd char name, is your charblocksize 
let say your first char is "abcde" than 2nd char name is "xyz"
start from "a" and stop before "x" , that's your charblocksize

**Comment by Fadreus** [comment]
If 118 is the right one, then it ain't supported, right?

https://github.com/OpenKore/openkore/blob/ac26cde50521b1a9700207029b01c05988bfc677/src/Network/Receive.pm#L641
https://github.com/OpenKore/openkore/blob/ac26cde50521b1a9700207029b01c05988bfc677/src/Network/Receive.pm#L647

**Comment by alisonrag** [comment]
Old servers use old and maybe unsurpoted char block size

**Comment by alisonrag** [comment]
You can create a new char and sub the difference in size
006b is different from.others parse character

**Comment by sennincito** [comment]
i've created another char, then the new result is 524-4/5 = 104... but this is not supported. 

I've used openkore on this server like 10 years ago, obviously I dont have the files I've used in the past and it worked perfectly. 
I dont think they have changed anything, the owner is very lazy. But I cannot make it work, saddly.

**Comment by sennincito** [comment]
this is the last result using charBlockSize 106 as default. 

![image](https://user-images.githubusercontent.com/52898321/61502852-c3fd7d80-a992-11e9-806a-80805ce4c36b.png)

**Comment by alisonrag** [comment]
Seems 108, test it and send screenshot

**Comment by sennincito** [comment]
I've tried 108 but names are not correct, it manages to connect... but only works with one char, when I try to change char, char doesnt change. 

![image](https://user-images.githubusercontent.com/52898321/61505017-ab916100-a99a-11e9-85e3-b02860d7d48d.png)
![image](https://user-images.githubusercontent.com/52898321/61505035-ba781380-a99a-11e9-9016-9fc56052e0d7.png)

**Comment by ZaskarAlpha** [comment]
that leaves a right amount of guesswork to your charblocksize. understand first what char block size is. you can easily find the right number by a lot of testing though.

**Comment by sennincito** [comment]
> that leaves a right amount of guesswork to your charblocksize. understand first what char block size is. you can easily find the right number by a lot of testing though.

i've tried each one from the openkore list

**Comment by alisonrag** [comment]
Other sizes not listed will only crash openkore

**Comment by alisonrag** [comment]
006b need update

**Comment by sennincito** [comment]
Where I can get that update?

**Comment by sctnightcore** [comment]
I think wait @alisonrag  update it ...

**Comment by alisonrag** [comment]
give me server link

**Comment by sennincito** [comment]
Midgarkingdom.tk is the server link.

**Comment by alisonrag** [comment]
src\Network\Receive\kRO\Sakexe_0.pm

change from:
`'006B' => ['received_characters_info', 'v C3 x20 a*', [qw(len total_slot premium_start_slot premium_end_slot charInfo)]], # last known struct`

to:
`'006B' => ['received_characters_info', 'v x20 a*', [qw(len charInfo)]], # last known struct`

and use 
`charBlockSize 108`

**Comment by sennincito** [comment]
It is working now at 100%!!!!!!!!
thank you all for your time and helping me to fix this.

**Comment by Nipodemos** [comment]
@alisonrag pull request please

**Comment by alisonrag** [comment]
this server uses to old version of 006B, maybe the only one in earth hahah
it will mess with all other servers that use this 006B updated
