### ISSUE TITLE
Map Server Connection Problem

### ISSUE THREAD

**Issue by Nathan2017** [OpenKore/openkore#2829]
Unable to connect to Map Server after downloading the lastest github file. Server: IRO Chaos

del img by sctnightcore

**Comment by alisonrag** [comment]
Server?

**Comment by Nathan2017** [comment]
> Server?

IRO Chaos

**Comment by sctnightcore** [comment]
u need wait.

**Comment by ZaskarAlpha** [comment]
u need to wait for devs to update. iRO just finished the maintenance jeez.

**Comment by Fadreus** [comment]
@Nathan2017 
IDK if you are a person or a cat behind that computer neither do I know if you speak English or using google translate.
IDK if you are from this planet but let me tell you how common sense work here on earth.

1st
- The file "ReadMe" **literally** mean **read** me. This is not some bitch girl said one thing and mean another. Computer translate code literally. They don't print "Error" and meant _**"It's not like I don't wanna connect, BAKA!"**_.
So go and read that.

2nd
- We put everything most people need to know at the front page;either for noobs, idiots, pro or god. We don't hide it in Area 51. So don't skip the (Code) and jump straight to (Issue). It's like skipping breakfast and go for dinner. It's idiot, right? If not, you are.

3rd
- I know people usually skip "Tutorial" when playing new games and then cry for not knowing thing.
Don't be like that kid. The "tutorial" to report bug already given in the bug report template. Its is given to be used, same as condom. Wise people put in on their dick, dumb people put on their head and thus DickHead was born.

Feel free to call me asshole, rude or what ever you like.
I don't mind being the bad guy.
If that what it takes for people to be less idiot, then I'm more than willing to take the "asshole" role.
