### ISSUE TITLE
Improve xor scheme

### ISSUE THREAD

**Issue by AlexandreBR3N** [OpenKore/openkore#283]
Since **2013**, some players think that the xor on header of packets were a characteristic only of bRO. But i only want propose a change on Receives.pm to read the servers.txt, some line that talk about 'mid keys'. and one line to confirm the crypt.
Like poseidon. **Poseidon** has your own servertypes file. 

I've talked some time ago with **_iMikeLance_**, then he told me that he has have already posted this function. I can't find this function, and since 2015, i've seen 30% of international topics talking about 'denied server connection'. I really searched for this function but don't found. Is it too late to add this ?! 
Players have to edit the sT. Since we have **PEEK** doing all for us 

1)It should be part of tables folders since keys are related with recvpackets. !? 

2)Or add it on recvpackets, as comment line, since Kore ignore all # . Then downloading the '4ept version' of PEEK, we can get a full recvpackets/crypt scheme with one step. And with this the user should have select the correct serverType to make work for all private server (unless that serverType really is bigger than > 2014. I've seen private servers using 2015 PE header but using 2013sT worked successfully (tip).

3)Edit WIKI (FAQ) adding or create a international fix topic : 

Server has dennied your connection: The client send an incorrect information to the server. 

I hate topics like this 👍 
http://forums.openkore.com/viewtopic.php?f=9&t=211602&p=274554#p274554

4) Instead of edit servers.txt, could be on config.txt. But really it's better work with $servers instead of $config :P
It'll help a little bit. 

If someone approves, i really promise to do a FULL GUIDE for private servers.

**Comment by lututui** [comment]
The error "the server has denied your connection" upon connecting to map server is also caused by an incorrect 'map_login' packet. If the KMA keys are incorrect, most of the times, the player will be timed out.

Also, I think it's problematic to add them to the servers.txt, because keeping servers where keys change regularly up to date would potentially cause conflicts with user configuration for private servers. The same could be said for the storage keys, although most of them haven't changed in years.

**Comment by AlexandreBR3N** [comment]
Where is the better place to set this?! poseidon.txt (create code on receive to read this)? 

Interesting ;) 

"The same could be said for the storage keys, although most of them haven't changed in years."

So the recvpackets is the best idea ?! Such defining a line as 'custom_keys' in recvpackets 👍
 
#custom_keys: 0x123456, 0x123456, 0x699669
0123 -1 0 1

**Comment by Henrybk** [comment]
Most of the servertype code on Send could be automatized using the last lines from a recvpackets, only the Receive counterpart needs real manual work, 

I don't see a problem in having this function and adding the keys directly to recvpackets.

**Comment by AlexandreBR3N** [comment]
Little hard uh ? :/ i tried to export the keys using fileparsers but doesnt worked.
