### ISSUE TITLE
guys I would like to IP Sv. RoThai Help me.

### ISSUE THREAD

**Issue by gangzaboss** [OpenKore/openkore#2834]
as blow is wrong. can plz help me to correct.

 
# https://ro.exe.in.th/
[Thailand - tRO Main server (Norse)]
ip 122.155.11.240
port 6900
master_version 7
version 24
serverType tRO
secureLogin 3
secureLogin_type 0
secureLogin_account 0
patchserver wpatch.ragnarok.in.th
patchpath /patch70
serverEncoding Thai
addTableFolders tRO
charBlockSize 112
gameguard 1

**Comment by alisonrag** [comment]
Thro have eac, no one bypassed and also we already have a issue for this server
