### ISSUE TITLE
Plugins autowarp doest work anymore?

### ISSUE THREAD

**Issue by oleokoong** [OpenKore/openkore#2835]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

plugins\needs-review\autowarp
can anyone update this?

**Comment by sctnightcore** [comment]
Bug Report / Feature Request:?
Openkore version git:?

**Comment by Fadreus** [comment]
That was very useful information.

"This doesn't work. Fix it. End of story."
![image](https://user-images.githubusercontent.com/32188494/62063196-02c9e800-b25d-11e9-822d-e2bf8fedc778.png)
