### ISSUE TITLE
Can't Connect Openkore to iRO  map server account

### ISSUE THREAD

**Issue by TanasanJJ7** [OpenKore/openkore#2839]
help me pls..
![Untitled](https://user-images.githubusercontent.com/16222517/62349616-7d7b5780-b52a-11e9-8a51-400bf5b03865.jpg)

Thank you    for fix

**Comment by sctnightcore** [comment]
I'm u want bot . u need wait

**Comment by Fadreus** [comment]
Censoring char name but not ID number is like:
- Guess what pokemon is this?
![image](https://user-images.githubusercontent.com/32188494/62366421-6ef86480-b559-11e9-84e7-1aa657e7f140.png)
![image](https://user-images.githubusercontent.com/32188494/62366496-a23af380-b559-11e9-91de-ae066437d0ff.png)

**Comment by sctnightcore** [comment]
@Fadreus  Gamemaster can find Acc ID xD 

let's send repot him id xD

**Comment by Fadreus** [comment]
Go on. :+1: 
Make him an example to others. :laughing:
