### ISSUE TITLE
ChargeBlockSize error (AGAIN) due update on server

### ISSUE THREAD

**Issue by sennincito** [OpenKore/openkore#2840]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

Server: Midgarkingdom, from midgarkingdom.tk
kRO
Error on charBlockSize due an update on server

Summary, 

In the past I had an error on this server due that server was not using a regular charBlockSize, this was fixed here: https://github.com/OpenKore/openkore/issues/2827

However, server has been updated from sakray 2008 to Ragexe 2010.
I have updated all packages again and server information, however I am having an issue with charBlockSize again, looks like the number should be 115 as per debug information: 
Chars in account = 6
![image](https://user-images.githubusercontent.com/52898321/62491029-19ee6580-b788-11e9-9740-3879de6383d2.png)

the result is 699 - 4 / 6 = 115.83.

I've tried 115 and 116 and openkore crashes

Using 116 I receive this error: 
Error message:
'x' outside of string in unpack at src/Network/Receive.pm line 717.
	(in cleanup) Can't locate object method "DESTROY" via package "InventoryList::SUPER" at src/InventoryList.pm line 86.

Stack trace:
'x' outside of string in unpack at src/Network/Receive.pm line 717.
	(in cleanup) Can't locate object method "DESTROY" via package "InventoryList::SUPER" at src/InventoryList.pm line 86.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x617650c)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	$self->clear();
* 	$self->SUPER::DESTROY();
  }

what could be the solution to this problem?

**Comment by ya4ept** [comment]
try [this](https://github.com/OpenKore/openkore/issues/2827#issuecomment-512678379)
115 does not exist. See [possible values](http://openkore.com/index.php/CharBlockSize)

**Comment by sennincito** [comment]
> try [this](https://github.com/OpenKore/openkore/issues/2827#issuecomment-512678379)
> 115 does not exist. See [possible values](http://openkore.com/index.php/CharBlockSize)

I've tried all charblocksize from the list, last issue was that 006B needed an update, maybe this is the same case again. 
@alisonrag Could you please help me on this again? you fixed my issue last time. 

thanks

**Comment by robotrono** [comment]
@sennincito can you give the server info? thx

**Comment by sctnightcore** [comment]
1. he don't show about server info , client date , recvpacket blabalb
2. i'm not god to know u problem
3. I think I want close issues xD

**Comment by sennincito** [comment]
> received_characters_info', 'v C3 x20 a*',

thank you, 

the solution was to revert the change done before as you advised. 

Appreciate. 

@sctnightcore you can close this case now. Thanks,

**Comment by robotrono** [comment]
@sennincito can you give me the recvpackets.txt data pls?

**Comment by sennincito** [comment]
@robotrono 
claro

0064 55
0065 17
0066 3
0067 37
0068 46
0069 0
006A 23
006B 0
006C 3
006D 114
006E 3
006F 2
0070 3
0071 28
0072 22
0073 11
0074 3
0075 0
0076 9
0077 5
0078 55
0079 53
007A 58
007B 60
007C 44
007D 2
007E 105
007F 6
0080 7
0081 3
0082 2
0083 2
0084 2
0085 10
0086 16
0087 12
0088 10
0089 11
008A 29
008B 23
008C 14
008D 0
008E 0
0090 7
0091 22
0092 28
0093 2
0094 19
0095 30
0096 0
0097 0
0098 3
0099 0
009A 0
009B 34
009C 9
009D 17
009E 17
009F 20
00A0 23
00A1 6
00A2 14
00A3 0
00A4 0
00A5 0
00A6 0
00A7 9
00A8 7
00A9 6
00AA 7
00AB 4
00AC 7
00AE 0
00AF 6
00B0 8
00B1 8
00B2 3
00B3 3
00B4 0
00B5 6
00B6 6
00B7 0
00B8 7
00B9 6
00BA 2
00BB 5
00BC 6
00BD 44
00BE 5
00BF 3
00C0 7
00C1 2
00C2 6
00C3 8
00C4 6
00C5 7
00C6 0
00C7 0
00C8 0
00C9 0
00CA 3
00CB 3
00CC 6
00CD 3
00CE 2
00CF 27
00D0 3
00D1 4
00D2 4
00D3 2
00D4 0
00D5 0
00D6 3
00D7 0
00D8 6
00D9 14
00DA 3
00DB 0
00DC 28
00DD 29
00DE 0
00DF 0
00E0 30
00E1 30
00E2 26
00E3 2
00E4 6
00E5 26
00E6 3
00E7 3
00E8 8
00E9 19
00EA 5
00EB 2
00EC 3
00ED 2
00EE 2
00EF 2
00F0 3
00F1 2
00F2 6
00F3 0
00F4 21
00F5 11
00F6 8
00F7 17
00F8 2
00F9 26
00FA 3
00FB 0
00FC 6
00FD 27
00FE 30
00FF 10
0100 2
0101 6
0102 6
0103 30
0104 79
0105 31
0106 10
0107 10
0108 0
0109 0
010A 4
010B 6
010C 6
010D 2
010E 11
010F 0
0110 10
0111 39
0112 4
0113 25
0114 31
0115 35
0116 17
0117 18
0118 2
0119 13
011A 15
011B 20
011C 68
011D 2
011E 3
011F 16
0120 6
0121 14
0122 0
0123 0
0124 21
0125 8
0126 8
0127 8
0128 8
0129 8
012A 2
012B 2
012C 3
012D 4
012E 2
012F 0
0130 6
0131 86
0132 6
0133 0
0134 0
0135 7
0136 0
0137 6
0138 3
0139 16
013A 4
013B 4
013C 4
013D 6
013E 24
013F 26
0140 22
0141 14
0142 6
0143 10
0144 23
0145 19
0146 6
0147 39
0148 8
0149 9
014A 6
014B 27
014C 0
014D 2
014E 6
014F 6
0150 110
0151 6
0152 0
0153 0
0154 0
0155 0
0156 0
0157 6
0158 0
0159 54
015A 66
015B 54
015C 90
015D 42
015E 6
015F 42
0160 0
0161 0
0162 0
0163 0
0164 0
0165 30
0166 0
0167 3
0168 14
0169 3
016A 43
016D 14
016E 186
016F 182
0170 14
0171 30
0172 10
0173 3
0174 0
0175 6
0176 106
0177 0
0178 4
0179 5
017A 4
017B 0
017C 6
017D 7
017E 0
017F 0
0180 6
0181 3
0182 106
0183 10
0184 10
0185 34
0187 6
0188 8
0189 4
018A 4
018B 4
018C 29
018D 0
018E 10
018F 6
0190 23
0191 86
0192 24
0193 2
0194 30
0195 102
0196 9
0197 4
0198 8
0199 4
019A 14
019B 10
019C 0
019D 6
019E 2
019F 6
01A0 3
01A1 3
01A2 37
01A3 5
01A4 11
01A5 26
01A6 0
01A7 4
01A8 4
01A9 6
01AA 10
01AB 12
01AC 6
01AD 0
01AE 4
01AF 4
01B0 11
01B1 7
01B2 0
01B3 67
01B4 12
01B5 18
01B6 114
01B7 6
01B8 3
01B9 6
01BA 26
01BB 26
01BC 26
01BD 26
01BE 2
01BF 3
01C0 2
01C1 14
01C2 10
01C3 0
01C4 22
01C5 22
01C6 4
01C7 2
01C8 13
01C9 97
01CA 3
01CB 9
01CC 9
01CD 30
01CE 6
01CF 28
01D0 8
01D1 14
01D2 10
01D3 35
01D4 6
01D5 0
01D6 4
01D7 11
01D8 54
01D9 53
01DA 60
01DB 2
01DC 0
01DD 47
01DE 33
01DF 6
01E0 30
01E1 8
01E2 34
01E3 14
01E4 2
01E5 6
01E6 26
01E7 2
01E8 28
01E9 81
01EA 6
01EB 10
01EC 26
01ED 2
01EE 0
01EF 0
01F0 0
01F1 0
01F2 20
01F3 10
01F4 32
01F5 9
01F6 34
01F7 14
01F8 2
01F9 6
01FA 48
01FB 56
01FC 0
01FD 15
01FE 5
01FF 10
0200 26
0201 0
0202 26
0203 10
0204 18
0205 26
0206 11
0207 34
0208 14
0209 36
020A 10
020D 0
020E 32
020F 10
0210 22
0212 26
0213 26
0214 42
0215 6
0216 6
0217 2
0218 2
0219 282
021A 282
021B 10
021C 10
021D 6
021E 6
021F 66
0220 10
0221 0
0222 6
0223 8
0224 10
0225 2
0226 282
0227 18
0228 18
0229 15
022A 58
022B 57
022C 65
022D 5
022E 71
022F 5
0230 12
0231 26
0232 9
0233 11
0234 6
0235 0
0236 10
0237 2
0238 282
0239 11
023A 4
023B 36
023C 6
023D 6
023E 8
023F 2
0240 0
0241 6
0242 0
0243 6
0244 6
0245 3
0246 4
0247 8
0248 0
0249 3
024A 70
024B 4
024C 8
024D 12
024E 6
024F 10
0250 3
0251 34
0252 0
0253 3
0254 3
0255 5
0256 5
0257 8
0258 2
0259 3
025A 0
025B 6
025C 4
025D 6
025E 4
025F 6
0260 6
0261 11
0262 11
0263 11
0264 20
0265 20
0266 30
0267 4
0268 4
0269 4
026A 4
026B 4
026C 4
026D 4
026F 2
0270 2
0271 40
0272 44
0273 30
0274 8
0275 37
0276 0
0277 84
0278 2
0279 2
027A 0
027B 14
027C 60
027D 62
027E 0
027F 8
0280 12
0281 4
0282 284
0283 6
0284 14
0285 6
0286 4
0287 0
0288 10
0289 12
028A 18
028B 0
028C 46
028D 34
028E 4
028F 6
0290 4
0291 4
0292 2
0293 70
0294 10
0295 0
0296 0
0297 0
0298 8
0299 6
029A 27
029B 80
029C 66
029D 0
029E 11
029F 3
02A2 8
02A5 8
02AA 4
02AB 36
02AC 6
02AD 8
02B0 85
02B1 0
02B2 0
02B3 107
02B4 6
02B5 0
02B6 7
02B7 7
02B8 22
02B9 191
02BA 11
02BB 8
02BC 6
02C1 0
02C2 0
02C4 26
02C5 30
02C6 30
02C7 7
02C8 3
02C9 3
02CA 3
02CB 65
02CC 4
02CD 71
02CE 10
02CF 6
02D0 0
02D1 0
02D2 0
02D3 4
02D4 29
02D5 2
02D6 6
02D7 0
02D8 10
02D9 10
02DA 3
02DB 0
02DC 0
02DD 32
02DE 6
02DF 36
02E0 34
02E1 33
02E2 20
02E3 22
02E4 11
02E5 9
02E6 6
02E7 0
02E8 0
02E9 0
02EA 0
02EB 13
02EC 67
02ED 59
02EE 60
02EF 8
02F0 10
02F1 2
02F2 2
02F3 0
02F4 0
02F5 0
02F6 0
02F7 0
02F8 0
02F9 0
02FA 0
02FB 0
02FC 0
02FD 0
02FE 0
02FF 0
0300 0
0301 0
0302 0
0303 0
0304 0
0305 0
0306 0
0307 0
0308 0
0309 0
030A 0
030B 0
030C 0
030D 0
030E 0
030F 0
0310 0
0311 0
0312 0
0313 0
0314 0
0315 0
0316 0
0317 0
0318 0
0319 0
031A 0
031B 0
031C 0
031D 0
031E 0
031F 0
0320 0
0321 0
0322 0
0323 0
0324 0
0325 0
0326 0
0327 0
0328 0
0329 0
032A 0
032B 0
032C 0
032D 0
032E 0
032F 0
0330 0
0331 0
0332 0
0333 0
0334 0
0335 0
0336 0
0337 0
0338 0
0339 0
033A 0
033B 0
033C 0
033D 0
033E 0
033F 0
0340 0
0341 0
0342 0
0343 0
0344 0
0345 0
0346 0
0347 0
0348 0
0349 0
034A 0
034B 0
034C 0
034D 0
034E 0
034F 0
0350 0
0351 0
0352 0
0353 0
0354 0
0355 0
0356 0
0357 0
0358 0
0359 0
035A 0
035B 0
035C 2
035D 0
035E 2
035F 0
0360 0
0361 0
0362 0
0363 0
0364 0
0365 0
0366 0
0367 0
0368 0
0369 0
036A 0
036B 0
036C 0
036D 0
036E 0
036F 0
0370 0
0371 0
0372 0
0373 0
0374 0
0375 0
0376 0
0377 0
0378 0
0379 0
037A 0
037B 0
037C 0
037D 0
037E 0
037F 0
0380 0
0381 0
0382 0
0383 0
0384 0
0385 0
0386 0
0387 0
0388 0
0389 0
038A 0
038B 0
038C 0
038D 0
038E 0
038F 0
0390 0
0391 0
0392 0
0393 0
0394 0
0395 0
0396 0
0397 0
0398 0
0399 0
039A 0
039B 0
039C 0
039D 0
039E 0
039F 0
03A0 0
03A1 0
03A2 0
03A3 0
03A4 0
03A5 0
03A6 0
03A7 0
03A8 0
03A9 0
03AA 0
03AB 0
03AC 0
03AD 0
03AE 0
03AF 0
03B0 0
03B1 0
03B2 0
03B3 0
03B4 0
03B5 0
03B6 0
03B7 0
03B8 0
03B9 0
03BA 0
03BB 0
03BC 0
03BD 0
03BE 0
03BF 0
03C0 0
03C1 0
03C2 0
03C3 0
03C4 0
03C5 0
03C6 0
03C7 0
03C8 0
03C9 0
03CA 0
03CB 0
03CC 0
03CD 0
03CE 0
03CF 0
03D0 0
03D1 0
03D2 0
03D3 0
03D4 0
03D5 0
03D6 0
03D7 0
03D8 0
03D9 0
03DA 0
03DB 0
03DC 0
03DD 18
03DE 18
03E2 0
03E3 0
03E4 0
03E5 0
03E6 0
03E7 0
03E8 0
03E9 0
03EA 0
03EB 0
03EC 0
03ED 0
03EE 0
03EF 0
03F0 0
03F1 0
03F2 0
03F3 0
03F4 0
03F5 0
03F6 0
03F7 0
03F8 0
03F9 0
03FA 0
03FB 0
03FC 0
03FD 0
03FE 0
03FF 0
0400 0
0401 0
0402 0
0403 0
0404 0
0405 0
0406 0
0407 0
0408 0
0409 0
040A 0
040B 0
040C 0
040D 0
040E 0
040F 0
0410 0
0411 0
0412 0
0413 0
0414 0
0415 0
0416 0
0417 0
0418 0
0419 0
041A 0
041B 0
041C 0
041D 0
041E 0
041F 0
0420 0
0421 0
0422 0
0423 0
0424 0
0425 0
0426 0
0427 0
0428 0
0429 0
042A 0
042B 0
042C 0
042D 0
042E 0
042F 0
0430 0
0431 0
0432 0
0433 0
0434 0
0435 0
0436 19
0437 7
0438 10
0439 8
043D 8
043E 0
043F 25
0440 10
0441 4
0442 0
0443 8
0444 0
0445 10
0446 14
0447 2
0448 0
044A 6
044B 2
07D0 6
07D1 2
07D2 0
07D3 4
07D4 4
07D5 4
07D6 4
07D7 8
07D8 8
07D9 268
07DA 6
07DB 8
07DC 6
07DD 54
07DE 30
07DF 54
07E0 58
07E1 15
07E2 8
07E3 6
07E4 0
07E5 8
07E6 8
07E7 32
07E8 0
07E9 5
07EA 2
07EB 0
07EC 8
07ED 10
07EE 6
07EF 8
07F0 6
07F1 15
07F2 6
07F3 4
07F4 3
07F5 6
07F6 14
07F7 0
07F8 0
07F9 0
07FA 8
07FB 25
07FC 10
07FD 0
07FE 26
07FF 0
0800 0
0801 0
0802 18
0803 4
0804 14
0805 0
0806 2
0807 4
0808 14
0809 50
080A 18
080B 6
080C 2
080D 3
080E 14
080F 20
0810 3
0811 0
0812 8
0813 0
0814 86
0815 2
0816 6
0817 6
0818 0
0819 0
081A 4
081B 10
081C 10
081D 22
081E 8
081F 0
0820 11
0821 2
0822 9
0823 0
0824 6
0825 0
0826 4
0835 0
0836 0
0837 3
0838 2
0839 66
083A 4
083B 2
083C 12
083D 6
083E 26
