### ISSUE TITLE
eval error.

### ISSUE THREAD

**Issue by sianromantic** [OpenKore/openkore#2844]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2019_08_01

* **Server**: private server

* **Bug Report / Feature Request**: none.

* **Summary**:

i want to ask. why my macro doesn't work ?

<details><summary>question (.gif)</summary>

![cca1](https://user-images.githubusercontent.com/37154438/62759744-cbf19e80-bab4-11e9-9101-a95772aca8b7.gif)
</details>
<details><summary>macros.txt (img)</summary>

[Code](https://pastebin.com/JKgcfM3h)
The id `110635998` is correct .
![eqeq111](https://user-images.githubusercontent.com/37154438/62760085-b5981280-bab5-11e9-9535-487a45fec3c2.JPG)
</details>

<details><summary>My process</summary>

````
first i type eval $messageSender->sendTalkText(pack("V", 110635998 ),1544545)
deliberately answer the wrong answer to trigger automacro
the new verification code is "1p2l7f0k"
but why my automacro doesn't answer it ?
````

![cca2](https://user-images.githubusercontent.com/37154438/62760260-22aba800-bab6-11e9-8259-13611e369b79.gif)
</details>

**Comment by Nipodemos** [comment]
surround $.lastMatch2 on double quotes:
$messageSender->sendTalkText(pack("V", 110635998 ),"$.lastMatch2")

**Comment by sianromantic** [comment]
@Nipodemos 
it work. thank!!!!
