### ISSUE TITLE
Unable to display exp output in guild chat or pm

### ISSUE THREAD

**Issue by class777** [OpenKore/openkore#2851]
I used to have script for displaying exp output(exp.txt) in guild chat but lost due to ransomeware
hence,lost all so can anyone help me with this?

this is just for an certain item using pm:

automacro test {
pm "item"
exclusive 1
priority 1
timeout 30
call qwer
}

macro qwer {
	$item1 = @invamount (Iron) Iron
	while (@invamount (Iron) > 0) as loop
        do pm "$.lastpm" $item1
        $item1 -= 1;
        end loop
	stop
}

**Comment by ya4ept** [comment]
Use forum.

**Comment by Fadreus** [comment]
Learn some English @class777

**Comment by class777** [comment]
> Learn some English @class777

is this relavent to the question? or u just here to bully?

**Comment by Fadreus** [comment]
Just close this.
It's not even an issue to stay open.
