### ISSUE TITLE
Packet Parser: Unknown switch: 0840

### ISSUE THREAD

**Issue by KKillleer** [OpenKore/openkore#2852]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
 2019_08_23
* **Server**: 
 bRO
* **Bug Report / Feature Request**: Packet Parser: Unknown switch: 0840
 Feature Request
* **Summary**:

After selecting my character, this appears (Packet Parser: Unknown switch: 0840) and it gets stucked there. Trying to recconect.
Was it supposed to work, or is there really nobody else programming for bRO?
Downloaded it in 22/08/2019.

![Openkore Ver](https://user-images.githubusercontent.com/54377597/63560605-046d8f80-c52d-11e9-9789-a0fb0b1cd29e.png)
![Openkore error](https://user-images.githubusercontent.com/54377597/63560621-0b949d80-c52d-11e9-8ffa-8c1b5094851d.png)

**Comment by sctnightcore** [comment]
```
// packet 0x841
struct PACKET_CH_SELECT_ACCESSIBLE_MAPNAME {
  /* this+0x0 */ short PacketID;
  /* this+0x2 */ unsigned char CharNum;
  /* this+0x3 */ unsigned char mapListNum;
};
```
if no one update it . u can try it with u self .

**Comment by KKillleer** [comment]
@sctnightcore Thank You for the help, but i havent used Opk. for like... a year?
So i'm kinda lost, where should i place/type, that "command".
And i'm not that good at programming, but just tell me where, and i'll figure it out!
Once again, thank you!

**Comment by KKillleer** [comment]
Help. Should i be typing it there, or should i be placing in some of the text files?
How am i supposed to fit that command, in the examples the "wiki" (print1), provides me?

Thats what i tried, and what i got (print2). Unknown command, mostly.

> my $commands_handle = Commands::register(
> // packet 0x841
> struct PACKET_CH_SELECT_ACCESSIBLE_MAPNAME {
>   /* this+0x0 */ short PacketID;
>   /* this+0x2 */ unsigned char CharNum;
>   /* this+0x3 */ unsigned char mapListNum;
> };)

![OPK Adding C-Commands](https://user-images.githubusercontent.com/54377597/63615824-9a043000-c5bc-11e9-8161-609f16ddb5c4.png)

![Totally lost](https://user-images.githubusercontent.com/54377597/63615862-b2744a80-c5bc-11e9-953c-4b7865d0525a.png)

**Comment by sctnightcore** [comment]
@KKillleer  it need update packet 0840 to src not command

**Comment by Fadreus** [comment]
Telling someone to build a house, don't even know what hammer is.
The future is grim. Unworthy.

**Comment by KKillleer** [comment]
Thanks @sctnightcore, i'll try to find something, but this goes beyond my knowledge, thank you for the help.

![recvpackets bRO](https://user-images.githubusercontent.com/54377597/63626080-15bfa600-c5d8-11e9-9734-b7423118d9bd.png)

@Fadreus If you won't help, don't bother trying to demotivate us.

**Comment by Fadreus** [comment]
I'm actually helping you realize if you wanna update packet, you need to be able to read them first.

![image](https://user-images.githubusercontent.com/32188494/63632454-cd03fd80-c668-11e9-8874-04856b3c5aa6.png)

Not to demotivate you tho but sometimes the truth in life hurts more than K-Drama. :laughing:

**Comment by KKillleer** [comment]
And why didn't you told me how, instead of criticizing? Or at least give me a "hammer".
Cause, in case you didn't realize, my server is bRO.
So english, is NOT my main language, which makes it all harder. 
You could have just said it: "Read this, so you can understand this or at least make it a little easier."
But you didn't.

> Unworthy.

**Comment by Fadreus** [comment]
Which part of my word is criticizing?
**Unworthy** = means not worth explaining coz at the end you will never get it.
**Unworthy** = also replying to your statement:
> You could have just said it: "Read this, so you can understand this or at least make it a little easier."

(I can see the future tho..)
![image](https://user-images.githubusercontent.com/32188494/63634722-e9b22c80-c68c-11e9-91d7-a917775d35fa.png)

If you still insist, then hit the bookstore and buy book about Perl & know what it means about:

- Array.
- Serialization.
- String length.
- Packet structure.

Then prolly someone could guide or at least you know what they are talking.
Imagine someone talking about packets and the other think it's command.
Ops, it already happen LOL :laughing:

**Comment by KKillleer** [comment]
@Fadreus It wasn't that hard, was it?

Credits to @sctnightcore, for helping and @lututui, for fixing it.

**Comment by Fadreus** [comment]
> It wasn't that hard, was it?

![image](https://user-images.githubusercontent.com/32188494/63712833-12931700-c871-11e9-9ac6-d77470159561.png) ![image](https://user-images.githubusercontent.com/32188494/63712170-b67bc300-c86f-11e9-8ce0-c1fac31954b8.png) ![image](https://user-images.githubusercontent.com/32188494/63713155-acf35a80-c871-11e9-8d11-32e8da5ae70f.png) ![image](https://user-images.githubusercontent.com/32188494/63713033-6f8ecd00-c871-11e9-8ad7-ce68fde43362.png)

**Comment by jcbjacob** [comment]
Haha.. he just say bla bla bla..give meme .. no solution for any question we ask..
