### ISSUE TITLE
Timeout on selection character server

### ISSUE THREAD

**Issue by KKillleer** [OpenKore/openkore#2856]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
2019_08_25
* **Server**: 
 bRO
* **Bug Report / Feature Request**: Feature Request

* **Summary**:

Downloaded ActivePearl 5.28.1, Git 2.23.0(64bit), openkore-master(25/08), extracted it, executed it, configured my account details, through the commands and got this error(print 1), am i missing something?

![Timeout on Selection Character Server](https://user-images.githubusercontent.com/54377597/63655126-5b0be100-c75a-11e9-9fc1-407eea1dbf8d.png)

![Screenshot_2](https://user-images.githubusercontent.com/54377597/63655129-5e9f6800-c75a-11e9-8b45-6374ea1a5e71.png)

@sctnightcore 
@lututui

**Comment by sctnightcore** [comment]
**I think u need read https://github.com/OpenKore/openkore#status-of-botting-on-official-servers**

**Comment by alisonrag** [comment]
saiu novo char blocksize (146 no bRO)
