### ISSUE TITLE
New servers IP for iRO - Chaos/Thor

### ISSUE THREAD

**Issue by aynamaster** [OpenKore/openkore#2860]
## ------------------ Openkore Issues Template ------------------
Yesterday maintence the IP servers changed, soo i'm waiting for update in servers lists and new IP. Thank you!

* **Openkore version git**: 
* **Server**:  iRO
* **Bug Report / Feature Request**: Feature Request
* **Summary**: New Servers

**Comment by sctnightcore** [comment]
I think u can get ip of iRO in clientinfo.xml xD

**Comment by sctnightcore** [comment]
Fixed :https://github.com/OpenKore/openkore/pull/2859
