### ISSUE TITLE
Disconnect to map server and got incoming data left in the buffer

### ISSUE THREAD

**Issue by yakessu** [OpenKore/openkore#2862]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: i have the last version of openkore i downloaded it today 

* **Server**: private server

* **Bug Report / Feature Request**: 

* **Summary**: 
Hi everyone I was trying to bot on a new server and got 0> 81 00 08 issue.
I was trying to use PEEK to create recvpackets.txt but failed that unblae to extract packet lengths.
Could anyone kindly help me with this?

![openKoreError](https://user-images.githubusercontent.com/54759422/64071672-7ffbd900-ccb1-11e9-82ee-c1f972e6dd82.png)

Here is the Time Data Stamp: Jun 13, 2017 3:44:43
[Rag.exe](https://drive.google.com/open?id=1fwziHiYXFII1bdV2x3ApIKtM-_c2cCXq)

**Comment by yakessu** [comment]
The servers what I used.
[LunaRO]
ip 114.32.37.225
port 7021
private 1
master_version 1
version 55
recvpackets recvpackets_20151104.txt
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
charBlockSize 147
pinCode 1
addTableFolders pserver/ggRO
clientHash DA4E4A35A46BF326C9C45C653979972A
sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9
pauseCharLogin 1

**Comment by c4c1n6kr3m1** [comment]
read the red warning dude

**Comment by yakessu** [comment]
Hi @c4c1n6kr3m1 ,
Sorry for my bad snapshot case, this problem I will solve it later.
For workaround I move my character to another map field.
The problem is I can't access map server... Could you help on this? Thank you.
![openKoreError1](https://user-images.githubusercontent.com/54759422/64074161-86eb1180-ccda-11e9-86b3-379cc7477f20.png)

**Comment by Fadreus** [comment]
> Time Data Stamp: Jun 13, 2017

> kRO_RagexeRE_2015_11_04a

![image](https://user-images.githubusercontent.com/32188494/64074560-71c4b180-ccdf-11e9-9d64-12d8c3d1b8f4.png)

**Comment by yakessu** [comment]
Hi @Fadreus ,
I know that is weird, however in my testing I can't access account server even if I use latest one.
If I use kRO_RagexeRE_2015_11_04a, I can access account server. I not sure what can I do for debugging.

**Comment by ya4ept** [comment]
read http://openkore.com/index.php/FLD_Creation_Guide
