### ISSUE TITLE
Openkore for euRO 4game

### ISSUE THREAD

**Issue by jacopo-lupi** [OpenKore/openkore#2864]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
everyone
* **Server**: 
euRO
* **Bug Report / Feature Request**:
<!-- Your problem is Bug Report / Feature Request . ex = **Bug Report / Feature Request**: Feature Request 
* **Summary**:
Hi dear developers. There will be the possibility to use openkore in euRO 4game server? Is unaccettable that actually someone is vending (high cost) a plugin for openkore in order to bot there.

Thank you very much for the attention,

Cheers

**Comment by Fadreus** [comment]
> * **Openkore version git**:
>   everyone

![image](https://user-images.githubusercontent.com/32188494/64345383-d60aac80-d022-11e9-80d0-e531c7190035.png)

**Comment by jacopo-lupi** [comment]
Since it's not implemented, is valid for every git version, right?

Il giorno gio 5 set 2019 alle ore 15:20 チビすけ <notifications@github.com> ha
scritto:
