### ISSUE TITLE
Task::Move won't end right after move packet is sent

### ISSUE THREAD

**Issue by Henrybk** [OpenKore/openkore#2867]
* **Openkore version git**: Latest
* **Server**:  All
* **Bug Report / Feature Request**: Bug Report
* **Summary**: As the title says Task::Move should should end after it is confirmed that the server has received a move command from the char.
`This task will keep sending the 'move' message to the server until the character has moved, or until a specific amount of time has passed.`

At the moment this is done by saving the time the task was created (and activated):
```
sub activate {
	my ($self) = @_;
	$self->SUPER::activate();
	$self->{giveup}{time} = time;
	$self->{start_time} = time;
}
```
And comparing it with `$char->{time_move}` which is set on `sub character_moves` when kore receives a confirmation from the server that the character is moving.

The problem is that `Task::Move` uses `Time::HiRes qw(time)`, while `Network::Receive` doesn't, so if openkore received the move confirmation in the same second that the Task was created this check ( `$self->{actor}{time_move} > $self->{start_time}` ) will fail, and openkore will try to send another move packet even though the server has already received one and confirmed it.

This causes openkore to not be able to finish Task::Move before the second finishes, making the character stop during walk.

Possible solution: Also use `Time::HiRes` on Receive.pm

Logs:
**### Kore sending 3 move packets, 2 of them after having received the server confirmation:**
![image](https://i.gyazo.com/3341328c9c80ddf3ddc8dfd115049985.png)

**### Same as above but adding the code `debug "Move $self->{actor} - debug: self->{actor}{time_move}:** ".$self->{actor}{time_move}." - self->{start_time}: ".$self->{start_time}."\n", "move";` on `Task:Move itare`, showing that the problem is indeed `time` vs `Time::HiRes`:
![image](https://i.gyazo.com/6d331a5c41440630d3065bcfdbe4bebc.png)

**### Same, but after adding `Time::HiRes` to `receive.pm`, kore stops sending additional packets:**
![image](https://i.gyazo.com/2709e253d7595fd3243723664e9ee6e8.png)

**Comment by ya4ept** [comment]
Interestingly, is this the same problem?
![move](https://user-images.githubusercontent.com/7117363/64631254-653b0a00-d3ff-11e9-8400-2718350e24c5.gif)

**Comment by Nipodemos** [comment]
I guess the problem on that gif is another one
Openkore should check if there is a npc/player/object on that coordinate and change the coordinate...

**Comment by Henrybk** [comment]
@ya4ept No, that is another problem with the way openkore checks if the route is complete, I have been working on a fix for it on my pathfinding branch, I will probably finish it today if you want to test.
