### ISSUE TITLE
XSTools won't even compile (Debian)

### ISSUE THREAD

**Issue by lowermouse** [OpenKore/openkore#288]
Basically, not even a clean compile will fix the XSTools issue.
5.24 is a hard link to 5.24.1
suggestions?

`user@pc:~/openkore$ perl openkore.pl
make: Entering directory '/home/user/openkore'
scons: Reading SConscript files ...
Checking Perl configuration ...(cached) yes
Checking for C library ncurses... (cached) yes
Checking for GNU readline 4.3 or higher...(cached) yes
Checking for libcurl...(cached) libcurl 7.50.1
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/auto/XSTools/unix/consoleui.os -c -Wall -O3 -pipe -fPIC -D_REENTRANT -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DVERSION=\"1.0\" -DXS_VERSION=\"1.0\" -Wall -O3 -pipe -fPIC -D_REENTRANT -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DVERSION=\"1.0\" -DXS_VERSION=\"1.0\" -fPIC -I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE src/auto/XSTools/unix/consoleui.cpp
src/auto/XSTools/unix/consoleui.cpp:10:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
scons: *** [src/auto/XSTools/unix/consoleui.os] Error 1
scons: building terminated because of errors.
-e \e[1;31mCompilation failed. Please read http://wiki.openkore.com/index.php/How_to_run_OpenKore for help.\e[0m
make: Leaving directory '/home/user/openkore'
Can't locate loadable object for module XSTools in @INC (@INC contains: /home/user/openkore/src/deps /home/user/openkore/src /home/user/openkore /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/user/openkore/src/Translation.pm line 30.`

**Comment by lututui** [comment]
You're missing  gnu readline

http://wiki.openkore.com/index.php/How_to_run_OpenKore#GNU_readline
