### ISSUE TITLE
Unknown Switch 0A7B , IdRO Server

### ISSUE THREAD

**Issue by musisician** [OpenKore/openkore#2880]
![Screenshot (15)](https://user-images.githubusercontent.com/11483587/64807676-ed680d80-d5bf-11e9-8cbf-afa542adc826.png)

Hi i want ask about receive packet on xkore 0 , i have unknown packet 07AB, is my idRO.pm not handle it ? 

thanks.

note : server idRO
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by asokakeisha** [comment]
[https://i.postimg.cc/QCXJyWC7/71681717-3304530999564764-273090332965470208-n.jpg](url)
[https://i.postimg.cc/jj0N1Jkj/69903816-484907889020520-4531984568013553664-n.jpg](url)

BOT WORK FROM Ragnarok ro.gnjoy.id

**Comment by sulabesi** [comment]
> 
> 
> ![](https://camo.githubusercontent.com/e664b95f950ec7c899495c9faa067d943f2b2aff/68747470733a2f2f692e706f7374696d672e63632f5143584a795743372f37313638313731372d333330343533303939393536343736342d3237333039303333323936353437303230382d6e2e6a7067)
> ![](https://camo.githubusercontent.com/3836976dabbde5384e225d317162e1301dbedde4/68747470733a2f2f692e706f7374696d672e63632f6a6a304e314a6b6a2f36393930333831362d3438343930373838393032303532302d343533313938343536383031333535333636342d6e2e6a7067)
> 
> BOT WORK FROM Ragnarok ro.gnjoy.id
> Happy Botters

beli apa nemu solusi sendiri bro di share aja
or kasih pencerahan ahahha

**Comment by realtoxic** [comment]
> OpenKore dont work with EAC .
> if u want bot .
> u need buy from ukore.

hello.. sorry i want to ask what is ukore?

**Comment by jcbjacob** [comment]
Same question, what is ukore ?
And can i learning from him with compensation ?

**Comment by Nipodemos** [comment]
i don't know for sure, but seems like a paid openkore
and looks like they sell EAC bypass

i don't know anything else about this, i don't have link and i don't recommend you use this

**Comment by Fadreus** [comment]
@Nipodemos 
uKore / uKoreTeam / UltiKore.
They can search it on [google](https://www.google.com/search?q=ukore+openkore&oq=ukore+openkore&aqs=chrome..69i57.2279j0j1&sourceid=chrome&ie=UTF-8) & [forum](http://forums.openkore.com/search.php?keywords=ukoreteam&terms=all&author=&sc=1&sf=all&sk=t&sd=d&sr=posts&st=0&ch=300&t=0&submit=Search) but choose not to.
![image](https://user-images.githubusercontent.com/32188494/66733287-a0fb4080-ee91-11e9-80f1-ad55521e74eb.png)

**Comment by jcbjacob** [comment]
i need openkore work on ragnarok server idr, for learning any script and
etc about that

Pada tanggal Sen, 14 Okt 2019 pukul 13.50 チビすけ <notifications@github.com>
menulis:

**Comment by jcbjacob** [comment]
dude, i find " packet parser : Unknown switch: 0A7B " on openkore your
build.. can you tell me what can i do for solving this problem
[image: bot.jpg]

Pada tanggal Sen, 14 Okt 2019 pukul 05.18 Nipodemos <
notifications@github.com> menulis:
