### ISSUE TITLE
How to fix error "unknown switch" 0A7B 010C server: IDRO Forever Love

### ISSUE THREAD

**Issue by sulabesi** [OpenKore/openkore#2886]
im try to run openkore on IDRO forever love can enter but i got ERROR 0A7B 010C
my char cant move or do config file like move to lockmap or attack monster just stay on his place after login?? n im give a command chat but not work too

please help me thanks

nb : sorry for bad english n im new on openkore too 
![Capture](https://user-images.githubusercontent.com/26086820/64909767-6d19e780-d73a-11e9-8549-49ca78c8fc6e.JPG)

**Comment by Fadreus** [comment]
You are new? Great !
You can start being "not new" by reading this
https://github.com/OpenKore/openkore#status-of-botting-on-official-servers

**Comment by sctnightcore** [comment]
I want close issues .

**Comment by Nipodemos** [comment]
plase do not use all capital letters on title or on post, it's not cool

i'm almost sure that idRO have EAC protection. If it have, then give up

**Comment by sulabesi** [comment]
> 
> 
> plase do not use all capital letters on title or on post, it's not cool
> 
> i'm almost sure that idRO have EAC protection. If it have, then give up

oow sorry im using caiptal on tittle 
btw im think it have EAC..

thanks for information i will close this issues

**Comment by asokakeisha** [comment]
sini bro mau bot gratis buat Forever Love
tinggal lo download aja ada disana keterangannya..
jangan dengarkan bacot bacot yang sok sok an dislike..
https://black.leakedin.net/threads/bot-ragnarok-forever-love.5/

BOT WORK FOR IDRO FOREVER LOVE
U Pelajari disini. nanti diarahkan sama Master / Admin disana.
OPENCORE WORK BOT IDRO FOREVER LOVE PREMIUM
