### ISSUE TITLE
Please help : Sample Client

### ISSUE THREAD

**Issue by NatakranPim** [OpenKore/openkore#2894]
Dear All,

Please help me.

Now, I already connect the openkore to my rAthena server in normal state.

Server : 
- (rAthena PACKETVER = 20151104) as bypass PACKET_OBFUSCATION

openkore : table/server 
- ip localhost
- port 6900
- master_version 1
- version 55
- recvpackets recvpackets_20151104.txt
- serverType kRO_RagexeRE_2015_11_04a
-  charBlockSize 147
- pinCode 1
- addTableFolders pserver/ggRO

kRO_Client : 
- 2015-11-04aRagexe_patched

(Login, Char, Map, Play, Move, Attack Whatever,  anything is ok)

::::::: I need to do a simple thing on client-side. ::::::::::::

I try to understand concept of sending packet datas.
I tried to chase all the code, but I got nothing. It so difficult and very huge.

I try to debug bus-client, but it not work.
s <ID> <Key> <Value> I have no idea what are ID, Key, Value
s <2000000> <0x0064> <d7admin123456> I don't know. It's not working.

Can some one make a code or explain likes:

- One page coding to do a simple task of packet sending:
   : Login <admin,123456>
   : Select char <slot 1>
   : Move to <x, y>
   : Chat <public chat, "hello world">
   : logout 
         * (any platforms c, c++, perl, python, c#, java)

- Or it should have receive side:
   : receive all env in the game in sample string.

If it already have please give me link to go there....

Thank you.

**Comment by Fadreus** [comment]
This is not problem with openkore..
Asking for help should go through forum / IRC.

**Comment by Fadreus** [comment]
This is not problem with openkore..
Asking for help should go through forum / IRC.

Or go to rArthena?

**Comment by Nipodemos** [comment]
as he said, this is not the correct area to ask for tips ou tutorials
closing
