### ISSUE TITLE
Add priority to labels

### ISSUE THREAD

**Issue by Cozzie** [OpenKore/openkore#29]
Issues should have a priority label so they can be sorted based on importance. At the very least they should be: **URGENT, HIGH, MEDIUM, LOW**.

 Pretty standard stuff.Thoughts?

**Comment by itsrachelfish** [comment]
You mean in addition to the labels we have now, we'd just have something like "priority: urgent" / "priority: high", etc. as labels?

**Comment by Cozzie** [comment]
Yes. So we can sort by bugs that are urgent for example.

**Comment by itsrachelfish** [comment]
Good idea! The labels have been added
