### ISSUE TITLE
Undefined subroutine &Network::Receive::ai_setMapChanged

### ISSUE THREAD

**Issue by dadunkst** [OpenKore/openkore#290]
Every my bot change map location always open pop up error.
Can some one help me?..

here the error text:
------------------------------------------
OpenKore version what-will-become-2.1
@ai_seq = route
Network state = 5
Network handler = Network::DirectConnection
SVN revision: unknown
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: config.autoBreakTime)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Undefined subroutine &Network::Receive::ai_setMapChanged called at src/Network/Receive.pm line 3667.

Stack trace:
Undefined subroutine &Network::Receive::ai_setMapChanged called at src/Network/Receive.pm line 3667.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x42e6ac4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Berakhir pada baris ini:
  	for (my $i = 0; $i < @ai_seq; $i++) {
* 		ai_setMapChanged($i);
  	}

**Comment by itsrachelfish** [comment]
What server are you playing on? What version of openkore are you using? Did you download it from this website?

**Comment by JunyuT** [comment]
I'm experiencing a similar issue. 
`OpenKore version what-will-become-2.1
@ai_seq = route
Network state = 5
Network handler = Network::DirectConnection
SVN revision: unknown
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: config.autoBreakTime)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Undefined subroutine &Network::Receive::ai_setMapChanged called at src/Network/Receive.pm line 3666.

Stack trace:
Undefined subroutine &Network::Receive::ai_setMapChanged called at src/Network/Receive.pm line 3666.
 at src/Network/Receive.pm line 3666.
	Network::Receive::map_change('Network::Receive::iRO=HASH(0x7fd0fed3ad08)', 'HASH(0x7fd0fc777c40)') called at src/Network/PacketParser.pm line 267
	Network::PacketParser::parse('Network::Receive::iRO=HASH(0x7fd0fed3ad08)', '\x{91}\x{0}gef_dun00.gat\x{0}\x{0}\x{0}h\x{0}c\x{0}', 'Network::Receive::iRO=HASH(0x7fd0fed3ad08)') called at src/Network/Receive.pm line 137
	Network::Receive::parse('Network::Receive::iRO=HASH(0x7fd0fed3ad08)', '\x{91}\x{0}gef_dun00.gat\x{0}\x{0}\x{0}h\x{0}c\x{0}', 'Network::Receive::iRO=HASH(0x7fd0fed3ad08)') called at src/Network/PacketParser.pm line 401
	Network::PacketParser::process('Network::Receive::iRO=HASH(0x7fd0fed3ad08)', 'Network::MessageTokenizer=HASH(0x7fd0fbe32cc0)', 'Network::Receive::iRO=HASH(0x7fd0fed3ad08)') called at src/functions.pl line 738
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Unix=HASH(0x7fd0fde696f0)') called at ./openkore.pl line 97
	main::__start() called at ./openkore.pl line 212

Died at this line:
  	main::initMapChangeVars();
* 	for (my $i = 0; $i < @ai_seq; $i++) {
  		ai_setMapChanged($i);

`

Playing on iRO Chaos, mac OS X El Capitan. No additional plugins/macro. It crashes when I change maps or when I set party share to even. Currently running the latest build cloned from this repository.

**Comment by paco676** [comment]
Same error message for me :(!

**Comment by lututui** [comment]
In Network/Receive.pm, we're only importing ai_items_take. That's the source of the problem.

use AI qw(ai_items_take);

**Comment by dadunkst** [comment]
so, have a solution please?

**Comment by paco676** [comment]
I downloaded the last version that lututui uploaded 7 minutes ago... but error still happening.

**Comment by lututui** [comment]
@paco676 did you download my fork? or the main repo? bc it's only fixed in my fork

**Comment by JunyuT** [comment]
Thanks, it's fixed now. It's not on the master tree but on the acb.... tree on lututui's fork just incase anyone has trouble finding. I did a `make clean` just to be safe before running openkore again.

**Comment by paco676** [comment]
I had downloaded the main repo... Its working now (L) Thank u !!!
