### ISSUE TITLE
Map timing out iRO xKore 0 xKore 1

### ISSUE THREAD

**Issue by thirstyrivers** [OpenKore/openkore#2906]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: Current 09_20

* **Server**: iRO

* **Bug Report / Feature Request**: xKore 1 mode time out in map within few minute, xKore 0 does same but can recover, longer time

* **Summary**: Trying to level Homunculus both with xKore 0 and 1. Map times out, orcdun02.

**Comment by Fadreus** [comment]
I tested and found no problem.
I suggest you download new version and don't copy-paste your old stuff into new openkore.

**Comment by something990** [comment]
hi what server of ragnarok is this? thank you
