### ISSUE TITLE
Timeout when connecting to map server iRo

### ISSUE THREAD

**Issue by Brijeshcr** [OpenKore/openkore#2914]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by ronaldstaana** [comment]
I’m encountering this issue as well

**Comment by Nipodemos** [comment]
closing since it is not following the issue template

wait for someone to update openkore to work on iRO
