### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by gilchan** [OpenKore/openkore#2920]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
OpenKore what-will-become-2.1 ( version ctime:2019_09_28 )
* **Server**: 
iRO Chaos
* **Bug Report / Feature Request**:
Bug Report 
* **Summary**:
Bug  #1: "View Inventory" showed wrong amounts for arrows while other items remain correct.
![Screenshot (16)_LI](https://user-images.githubusercontent.com/32204733/65813816-9479b580-e20c-11e9-809c-b9cde8502cf2.jpg)
Bug #2: After a map change, all items disappear from the inventory list.
![Screenshot (15)](https://user-images.githubusercontent.com/32204733/65813841-d276d980-e20c-11e9-852b-4be9261e1e53.png)

**Comment by sctnightcore** [comment]
My PR?

**Comment by gilchan** [comment]
I applied the changes that you made about 2 hours ago but the bugs still persist.

**Comment by Fadreus** [comment]
It's good when you using the bug template properly but when you are testing **_unimplemented PR_,** please use that PR thread instead to give feedback so discussion can be done under 1 thread.

**Comment by gilchan** [comment]
Closed.
Refer to Pull Request: IRO: RE Update ! #2916
