### ISSUE TITLE
Last update on iRO Timeout on Account Server, reconnecting.

### ISSUE THREAD

**Issue by AzmodanGod** [OpenKore/openkore#2921]
## ------------------ Openkore Issues Template ------------------

I did read some stuff of people that had similar problem but i was not able to understand how to fix it. It was working fine until this last update... i guess i have to change the version or something but i don't know how to know to witch one i switch. Thank you
# Renewal
# http://playragnarok.com
[International - iRO: Ymir/Yggdrasil/Valkyrie]
title International - iRO: Thor|Chaos (Renewal-compatible)
ip 128.241.92.36
port 6800
master_version 1
version 18
serverType iRO_Renewal
serverEncoding Western
patchserver ropatch1.gravityus.com
patchpath /patch02
addTableFolders iRO/Renewal;iRO
charBlockSize 147
charDeleteDateType 1
sendCryptKeys 0x639573FD, 0x30007ABA, 0x18EC45FF
blockingPlayerCancel 1
rankingSystemType 1

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by Fadreus** [comment]
> I did read some stuff

Stop with the lies, then what is this?

![image](https://user-images.githubusercontent.com/32188494/65826925-470a5080-e2bf-11e9-8494-049611afa7ec.png)

![image](https://user-images.githubusercontent.com/32188494/65826952-981a4480-e2bf-11e9-91cf-d528025fb82a.png)

**Comment by AzmodanGod** [comment]
yeah just you guys talking about kafra not working and the only 1 guys that asked the same thing that i am you guys just gave tumb down and didn't say anything... great help

**Comment by Fadreus** [comment]
Then explain to me what is "Draft" & what is "Pull Request" O smart ancient one.
