### ISSUE TITLE
answer me, don't just close the issues- Timeout on Map Server Ragnarok - iRO: 

### ISSUE THREAD

**Issue by avantilandscape** [OpenKore/openkore#2923]
[Sep 29 18:09:32 2019.66] [eventMacro] No control/eventMacros.txt file was found. Plugin disabled.
[Sep 29 18:09:32 2019.66] [eventMacro] Plugin unloading
[Sep 29 18:09:32 2019.67] Plugin eventMacro unloaded.
[Sep 29 18:09:32 2019.67] 
Generating session Admin Password...
[Sep 29 18:09:32 2019.69] 
[Sep 29 18:09:32 2019.72] Checking for new portals... [Sep 29 18:09:32 2019.81] none found

[Sep 29 18:09:32 2019.84] 
[Sep 29 18:09:32 2019.86] Connecting to Account Server...
[Sep 29 18:09:32 2019.89] Connecting (128.241.92.36:6800)... [Sep 29 18:09:32 2019.90] connected
[Sep 29 18:09:33 2019.82] ---------- Account Info ----------
Account ID: 5915435    2B 43 5A 00
Sex:        Boy
Session ID: 1261463873 41 69 30 4B
SessionID2: 0          00 00 00 00

----------------------------------
[Sep 29 18:09:33 2019.82] ---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Chaos                 1405   128.241.92.42   4500
1   Thor                  127    128.241.92.50   4500
-----------------------------------------------------
[Sep 29 18:09:33 2019.82] Closing connection to Account Server
[Sep 29 18:09:33 2019.83] Disconnecting (128.241.92.36:6800)...[Sep 29 18:09:33 2019.83] disconnected
[Sep 29 18:09:33 2019.84] Connecting to Character Server...
[Sep 29 18:09:33 2019.85] Selected server: Chaos
[Sep 29 18:09:33 2019.85] Connecting (128.241.92.42:4500)... [Sep 29 18:09:33 2019.86] connected
[Sep 29 18:09:35 2019.40] Received characters from Character Server
[Sep 29 18:09:37 2019.42] ------------------------------- Character List --------------------------------
Slot 1: Xitao (Assassin, Boy, level 64/20, geffen.gat  )
-------------------------------------------------------------------------------
[Sep 29 18:09:38 2019.90] Received character ID and Map IP from Character Server
[Sep 29 18:09:38 2019.99] ----------Game Info----------
Char ID: 22 18 50 02 (38803490)
MAP Name: geffen.gat
MAP IP: 128.241.92.42
MAP Port: 4503
-----------------------------
[Sep 29 18:09:38 2019.10] Closing connection to Character Server
[Sep 29 18:09:38 2019.10] Disconnecting (128.241.92.42:4500)...[Sep 29 18:09:38 2019.11] disconnected
[Sep 29 18:09:38 2019.12] Connecting to Map Server...
[Sep 29 18:09:38 2019.12] Connecting (128.241.92.42:4503)... [Sep 29 18:09:38 2019.13] connected

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/pulls

**Comment by Fadreus** [comment]
What use of answer if you can't read and lazy to search for it?
We are not your parent to spoon feed you.
This happened for 2 years. 2 FUCKING YEARS !!
Enough material to read for everyone.
Yet you so lazy fuck and want people to send a convoy to your doorstep letting you know?

Who the fuck you think you are?
If you wanna ask, use IRC.
This is not forum or social media.
Github is a work place.
WORK-FUCKING-PLACE !

Ignorance is not a license to do as you please.
Go get some brain or pair of eyes if you lost them.

I'm not gonna be polite with lazy ignorant fools.

**Comment by avantilandscape** [comment]
Fadreus fuck you ass, stupid. if u not will help whit u post this shit..

**Comment by Fadreus** [comment]
Why must I help you?



> Who the fuck you think you are?

**Comment by avantilandscape** [comment]
fuck you stupid come here talk to me personally

**Comment by Fadreus** [comment]
> come here talk to me personally



> Who the fuck you think you are?

**Comment by avantilandscape** [comment]
I'm guy fucking your mother...

**Comment by avantilandscape** [comment]
@Fadreus  you shit, I'm waiting for you here or the day you want, you stupid

**Comment by sctnightcore** [comment]
i can ban u in github. 
I think u stupid for read everything.

**Comment by avantilandscape** [comment]
@sctnightcore go ahead, this guys and post shit. i dont care. you are defending him

**Comment by sctnightcore** [comment]
Why not ? 
Without him he wouldn't be able to use bots.

**Comment by avantilandscape** [comment]
and? You don't have to be stupid and respond like that, by the way I don't even know why a shit of those answers won't help!

**Comment by sctnightcore** [comment]
I will update again next month.
ty

**Comment by avantilandscape** [comment]
I have here by email all but your friend's!

**Comment by sctnightcore** [comment]
**¯\_(ツ)_/¯**

**Comment by Nipodemos** [comment]
@avantilandscape  you want answers but you don't even know how to make a question
we closed your last issue because you didn't follow the issue template, which is required.

you also problably didn't even google the error, because you would find A LOT of awnsers to your problem

@Fadreus is right

**Comment by avantilandscape** [comment]
@Nipodemos of course I searched and no answer just the same problem but if you and his girlfriend, what can do! don't do like stupid. you can do it better
