### ISSUE TITLE
packet tokenizer unknown switch 4753

### ISSUE THREAD

**Issue by yahj112** [OpenKore/openkore#2924]
![1](https://user-images.githubusercontent.com/42144468/66097949-066a4a00-e5d3-11e9-8c33-15ea195d3f01.png)

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: latest

* **Server**: URDR private server 

* **Bug Report / Feature Request**:  packet tokenizer unknown switch 4753

* **Summary**:

**Comment by sctnightcore** [comment]
server link ?

**Comment by Nipodemos** [comment]
please elaborate a little more you issue
besides tell name of the server, tell what you already tried to make openkore works on this server,
Tell us link
Show what you changed in servers.txt
show what else did you have changed

tell us everything that you've tried.

And if you didn't tried anything, you should. We might help but we certainly will not do all the work for you and hand on a silver platter

**Comment by jcbjacob** [comment]
> please elaborate a little more you issue
> besides tell name of the server, tell what you already tried to make openkore works on this server,
> Tell us link
> Show what you changed in servers.txt
> show what else did you have changed
> 
> tell us everything that you've tried.
> 
> And if you didn't tried anything, you should. We might help but we certainly will not do all the work for you and hand on a silver platter

Hii brother, how i can fix " packet parser 0A7B on openkore for idro gnjoy ?
I'm have read any issue but i cant find the solution..

I need your help

**Comment by tykez28** [comment]
http://www.playro.ph/ same as mine can you help me sir??

**Comment by jwrublak** [comment]
Hi, I have the same problem. The server has gepard shield, I was unable to use WPE, I suffered a little with wireshark.
The server link is: http://ragnagoldtimes.com/

The information I got is as follows (I don't know if they are correct):
# https://ragnagoldtimes.com/
[Ragnagoldtimes]
ip 18.229.75.37
port 6900
master_version 2
version 55
patchserver 0
patchpath 0
serverType bRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 145
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1


If you can help me, I'd appreciate it!

**Comment by jedlionel19** [comment]
Up for this issue, Anyone can resolve this?


Thanks!

**Comment by delacruzmikko** [comment]
Please help or atleast give us clue about this if it can be solved or what. Thank you sir.

**Comment by alisonrag** [comment]
this is gepard shield and nope this wasn't bypassed, so openkore cant connect

**Comment by jedlionel19** [comment]
Hi Sir,

You mean even gepard shield can bypass by openkore? 

will light up this topic  if can bypass:D haha

Thanks! 
    On Sunday, April 26, 2020, 08:32:52 AM GMT+8, delacruzmikko <notifications@github.com> wrote:  
 
 


Please help or atleast give us clue about this if it can be solved or what. Thank you sir.

**Comment by baratie11** [comment]
![recv](https://user-images.githubusercontent.com/67263099/85268263-ddfbe600-b4a8-11ea-99d4-6361dc4b6158.png)

Server: Heroes of Valhalla
ip singapore proxy: 51.79.144.3
ip LA proxy:149.248.20.33

server dl link: https://playvalhalla.net/?module=main&action=downloads
