### ISSUE TITLE
Need bot for euro (4game)

### ISSUE THREAD

**Issue by MayDayMay** [OpenKore/openkore#2926]
Hello openkore team.

As i wrote on title we all need an openkore bot for 4game euro server with frost security bypass.

Someone already made a bypass solution but they are selling their method too expensive for avarage ragnarok user.

We need your help.

Regards.

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/66250113-af01e080-e770-11e9-8c95-411d7637cbd0.png)

![image](https://user-images.githubusercontent.com/32188494/66250153-e7a1ba00-e770-11e9-8e49-a03b08b0fe49.png)

![image](https://user-images.githubusercontent.com/32188494/66250157-04d68880-e771-11e9-8174-930a701ebb4e.png)

![image](https://user-images.githubusercontent.com/32188494/66250170-49622400-e771-11e9-95f6-74274f3699b0.png)

## Do you have trouble reading?
If yes, you don't need help from openkore.
You need help from Doctors.
Call 911 for help.

![image](https://user-images.githubusercontent.com/32188494/66250213-271cd600-e772-11e9-8917-1f6a88898247.png)

![image](https://user-images.githubusercontent.com/32188494/66250230-7531d980-e772-11e9-88d9-dfc65fc04176.png)

P/S: This is not my words so don't targeting me.

**Comment by MayDayMay** [comment]
Why should I target you. Its funny reply and its ok :) 
I can see that I explained my problem simplest and fastest way.

**Comment by mk-pmb** [comment]
Hi! I'm trying to make a market watch bot. Before I try and start a new bot from scratch: What's the issue with frost security? What is their detection mechanism? When they detect it, do they actively interfere with openkore, or does the game just refuse to start?
