### ISSUE TITLE
inventory not available after entering a map

### ISSUE THREAD

**Issue by williamrtiu** [OpenKore/openkore#2928]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: OpenKore what-will-become-2.1 ( version ctime:2019_05_27 )
from the last update of iRO the openkore table is not updated when downloaded, so I manually downloaded table files like recvpacket from "pull request"

* **Server**: iRO

* **Bug Report / Feature Request**:

* **Summary**: inventory is unavailable after entering a map, always need to relog to make inventory available

**Comment by Fadreus** [comment]
![Angry2](https://user-images.githubusercontent.com/32188494/66258243-5284dc80-e7d5-11e9-96c9-bb052c87b31d.png)

**Comment by williamrtiu** [comment]
sorry for the noob post... I had actually did the update, downloading the latest openkore from https://github.com/OpenKore/openkore, but it did not connect so I manually downloaded RE update from PR, I was able to connect but the issue about inventory in map switching appear. One thing I did not notice is the icon beside the PR, it is still green... Thank you for the info and sorry for the bother....

**Comment by Igotlostagain** [comment]
I want to be able to help and downloaded python and active perl. I understand basic algorithms, concepts, etc. I just need to know how to setup shop so that I can help. :(

**Comment by Nipodemos** [comment]
@Igotlostagain unfortunaly is harder than it looks...
you understand Perl is not enough (python you don't need much)

you have to read the files of openkore and understand them, going bit by bit
you don't need to understand all of it, but the in my opinion the harder part to understand is packets part. And that what you need to understand to deal with problems such as this.

**Comment by alisonrag** [comment]
continue in #2983
