### ISSUE TITLE
Ask About Macros

### ISSUE THREAD

**Issue by sulabesi** [OpenKore/openkore#2933]
hi all

im write a macro for bounty board but when it trigger its error this is my macros can someone help me to fix it??
Thanks Before

`
automacro questharpy {
	SimpleHookEvent target_died
	timeout 15
	exclusive 1 # this let other macros dont interrupt
	call {
	$temp1 = @eval($::questList->{29208}->{missions}->{1376}->{count})
	if ($temp1 == 150) call finharpy
	:end
	}
}

macro finharpy {
	do ai manual
	do tele 2
	pause 5
	do move &rand(177,186) &rand(173, 151) yuno
	do move &rand(177,186) &rand(139,143) yuno
	pause 3
	do talknpc 180 145 c c r1 c r1 c r2 c n #Ambil Hadiah
	pause 2
	do talknpc 180 145 c c c r0 c r1 n #Ambil Quest
	pause 10
	do conf lockMap yuno_fild04     #Lock Map Harpy/Goat
	do ai auto
	do autostorage
	do release questharpy
	stop
}

`

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**:  IDRO

* **Bug Report / Feature Request**: Macros Config

* **Summary**:

![macros](https://user-images.githubusercontent.com/26086820/66463200-cc9fb480-eaa6-11e9-9261-491c4547c254.png)

**Comment by ya4ept** [comment]
github is no place for such questions!
go to the forum or IRC chat

**Comment by Nipodemos** [comment]
i'm surprised that fadreus didn't triggered in this issue lol
love you rages man

**Comment by Fadreus** [comment]
I was making the meme but ya4ept closing it before the art piece is done.
And the fun disappeared :unamused:「ダサい。」
