### ISSUE TITLE
Learn for openkore

### ISSUE THREAD

**Issue by jcbjacob** [OpenKore/openkore#2940]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**:  idro gnjoy

* **Bug Report / Feature Request**: a channel for learning the openkore

* **Summary**: my old openkore out of date and not working

Good night..
Hello anyone, a long time ago i played ragnarok online indonesia and use openkore for support my activity on game.
But now, so more have changed on that game. I wanna learn about openkore, can you give a channel discord or someone will teach me about openkore.. god bless you..

Sorry for my bad english..

**Comment by Fadreus** [comment]
To start learning, you can start from [here.](https://www.ui.ac.id/en/bachelor/computer-science.html)
Use something like [these](https://www.google.com/search?q=learning+perl&source=lnms&tbm=bks&sa=X&ved=0ahUKEwiR3bSLtZnlAhVFwI8KHXKGBuUQ_AUIGCgB&biw=1300&bih=665) if you can't use the first link.
If that still didn't help, try read [this](https://github.com/OpenKore/openkore#faq-frequently-asked-questions) and [this](https://github.com/OpenKore/openkore#status-of-botting-on-official-servers).
This [video tutorial](https://www.youtube.com/watch?v=w3jLJU7DT5E) might be easier to understand.
If have any more question, use [this](https://github.com/OpenKore/openkore#contacts).
![image](https://user-images.githubusercontent.com/32188494/66717296-04419000-ee0a-11e9-9c8b-80936ef699fb.png)
![image](https://user-images.githubusercontent.com/32188494/66717404-3bfd0780-ee0b-11e9-82e3-0f92568586ae.png)

**Comment by jcbjacob** [comment]
God bless you alison, god bless you *blessingsfx*
