### ISSUE TITLE
Wrong item appears in inventory.

### ISSUE THREAD

**Issue by hexhexd** [OpenKore/openkore#2943]
Using the newest openkore from the master branch.

![unknown](https://user-images.githubusercontent.com/6869543/66845478-13295f00-ef3e-11e9-93c2-c951cc0d1c28.png)

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/66846998-40f5be80-efa5-11e9-98ac-c59c63558d02.png)

http://forums.openkore.com/viewtopic.php?f=0&t=11287
![image](https://user-images.githubusercontent.com/32188494/66846774-e0668180-efa4-11e9-8ae8-c2fc062afde3.png)

**Comment by Fadreus** [comment]
@hexhexd Edit, don't make new.

**Comment by Nipodemos** [comment]
i had the same issue, so as my friend
and it is when you receive some item from an npc

**Comment by Fadreus** [comment]
Bot dead in iRO in 6 weeks..
Enjoy while it last..

**Comment by tpysz5n** [comment]
> 
> 
> Bot dead in iRO in 6 weeks..
> Enjoy while it last..

Wait what do you mean by that? lol

**Comment by alisonrag** [comment]
> > Bot dead in iRO in 6 weeks..
> > Enjoy while it last..
> 
> Wait what do you mean by that? lol

iRO will close and reopen with new features and new Shield (anti-hack)

**Comment by tpysz5n** [comment]
> iRO will close and reopen with new features and new Shield (anti-hack)

Ah I see. And that'll be the doom of iRO bots?

**Comment by Nipodemos** [comment]
@tpysz5n we can't make sure of that, but recently there is way less servers that openkore works... bRO don't work, iRO is buggy, cRO i think it doesn't work, tRO it doesn't work

as someone said, openkore might be slowly dying

**Comment by tpysz5n** [comment]
Aww that's sad. I find botting even more interesting that the game itself

**Comment by jimbit76** [comment]
simple hacks, clear storage before autostorage.
In src/command.pm
sub cmdAutoStorage {
	message T("Initiating auto-storage.\n");
	$char->storage->clear();

When bot going for autostorage it will clear old storage log. Maybe someone can put a better code.

Thank you.

**Comment by jimbit76** [comment]
to clear inventory, there are 2 parts in src/network/receive/servertype0.pm
`message(swrite(
		"---------Map  Info----------", [],
		"MAP Name: @<<<<<<<<<<<<<<<<<<",
		[$args->{map}],
		"MAP IP: @<<<<<<<<<<<<<<<<<<",
		[$map_ip],
		"MAP Port: @<<<<<<<<<<<<<<<<<<",
		[$map_port],
		"-------------------------------", []),
		"connection");

	message T("Closing connection to Map Server\n"), "connection";
	$char->inventory->clear();
	$net->serverDisconnect unless ($net->version == 1);
`

`# Replies 0166 (Guild Member Titles List) and 0154 (Guild Members List)
		$messageSender->sendGuildRequestInfo(1);
		message(T("You are now in the game\n"), "connection");
		$char->inventory->clear();
		Plugins::callHook('in_game');
		$timeout{'ai'}{'time'} = time;
		our $quest_generation++;
`
tested myself there is no more buggy inventory

**Comment by bookbk** [comment]
> to clear inventory, there are 2 parts in src/network/receive/servertype0.pm
> 
> ```perl
> message(swrite(
> 		"---------Map  Info----------", [],
> 		"MAP Name: @<<<<<<<<<<<<<<<<<<",
> 		[$args->{map}],
> 		"MAP IP: @<<<<<<<<<<<<<<<<<<",
> 		[$map_ip],
> 		"MAP Port: @<<<<<<<<<<<<<<<<<<",
> 		[$map_port],
> 		"-------------------------------", []),
> 		"connection");
> 
> 	message T("Closing connection to Map Server\n"), "connection";
> 	$char->inventory->clear();
> 	$net->serverDisconnect unless ($net->version == 1);
> ```
> 
> and
> 
> ```
> # Replies 0166 (Guild Member Titles List) and 0154 (Guild Members List)
> 		$messageSender->sendGuildRequestInfo(1);
> 		message(T("You are now in the game\n"), "connection");
> 		$char->inventory->clear();
> 		Plugins::callHook('in_game');
> 		$timeout{'ai'}{'time'} = time;
> 		our $quest_generation++; 
> ```
> 
> Tested for a week and no more issue for buggy inventory

I'm testing. Thank you for helping

**Comment by bookbk** [comment]
> to clear inventory, there are 2 parts in src/network/receive/servertype0.pm
> 
> ```perl
> message(swrite(
> 		"---------Map  Info----------", [],
> 		"MAP Name: @<<<<<<<<<<<<<<<<<<",
> 		[$args->{map}],
> 		"MAP IP: @<<<<<<<<<<<<<<<<<<",
> 		[$map_ip],
> 		"MAP Port: @<<<<<<<<<<<<<<<<<<",
> 		[$map_port],
> 		"-------------------------------", []),
> 		"connection");
> 
> 	message T("Closing connection to Map Server\n"), "connection";
> 	$char->inventory->clear();
> 	$net->serverDisconnect unless ($net->version == 1);
> ```
> 
> and
> 
> ```
> # Replies 0166 (Guild Member Titles List) and 0154 (Guild Members List)
> 		$messageSender->sendGuildRequestInfo(1);
> 		message(T("You are now in the game\n"), "connection");
> 		$char->inventory->clear();
> 		Plugins::callHook('in_game');
> 		$timeout{'ai'}{'time'} = time;
> 		our $quest_generation++; 
> ```
> 
> Tested for a week and no more issue for buggy inventory

after test it
Inventory is Ok.
Storage still have some bug but it's better when bot restorage.

**Comment by tpysz5n** [comment]
I've tested it too and it totally works (didn't notice the storage bug @bookbk mentioned).
Shout out to @jimbit76 for the brilliant hack!

**Comment by alisonrag** [comment]
continue in #2983 2983
