### ISSUE TITLE
packet parser : Unknown switch: 0A7B (need solve )

### ISSUE THREAD

**Issue by jcbjacob** [OpenKore/openkore#2952]
## ------------------ Openkore Issues Template ------------------

i have read any issue and pull request about this openkore, im trying to start that,
im find this " packet parser : Unknown switch: 0A7B "
can someone give me a guide for solve any problem about this issue
like something i have to download or im using for solving about that

God bless you all and all your sharing knowledge
 
* **Openkore version git**: henryBK openkore

* **Server**: idro : yggdrasil

* **Bug Report / Feature Request**: packet parser : Unknown switch: 0A7B

* **Summary**:

**Comment by asokakeisha** [comment]
sini bro mau bot gratis buat Forever Love
tinggal lo download aja ada disana keterangannya..
jangan dengarkan bacot bacot yang sok sok an dislike..
https://black.leakedin.net/threads/bot-ragnarok-forever-love.5/

BOT WORK FOR IDRO FOREVER LOVE
U Pelajari disini. nanti diarahkan sama Master / Admin disana.
OPENCORE WORK BOT IDRO FOREVER LOVE PREMIUM
