### ISSUE TITLE
Wanna bring twRO bot back online

### ISSUE THREAD

**Issue by tpysz5n** [OpenKore/openkore#2957]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: `c84fa6e`

* **Server**: twRO

* **Feature Request**: Make twRO botable again

* **Summary**: Hi guys, I know this sounds a little unrealistic and very likely to end up as a failure, but I wish to help make OpenKore botable again on twRO. I was a heavy OpenKore user around 2014-2016 but this is the first time I dive into source code. Naturally I find the scope pretty wide and I **need some guidance on where to start**.
  E.g., if there exists any branch that was working on similar issue that I can pick up, or suggestions on which server is closest to twRO so I can somehow transplant from. Any help would be much appreciated :)

**Comment by tpysz5n** [comment]
Could someone in the admin group help assign this issue to me?

**Comment by Fadreus** [comment]
Use this thread https://github.com/OpenKore/openkore/issues/1861
Don't need many thread on same issue.

**Comment by AllenPeng0209** [comment]
Hey, I'm trying to do this. If you are interested in doing this, let's contact.

**Comment by tpysz5n** [comment]
Yo man,
由於沒人有空提供足夠的前後文，我不久後就放棄tw然後去寫iRO了XD
然後去年底iRO大維修之後我也沒再玩過，不知道新的抓掛功能表現如何
我來這之前在OPTW的discord頻道觀察了一下
有人claim說他會，但問問題要收錢，不知真偽
有興趣可以去瞧瞧：https://discord.gg/VEyYqD (連結一天後失效)
祝 日安
