### ISSUE TITLE
Private Server | The executable file might be compressed/protected.

### ISSUE THREAD

**Issue by marowizz** [OpenKore/openkore#2960]
Hello guys
I tell you that I have tried to configure a private server ([AtlantisRO](https://www.atlantis-ro.net/portal/)) but I have problems generating the recvpackets.txt.
I am using JCV-RO-Tools-1.0.3-master
He read the milestones but found no solution to the problem.

![image](https://user-images.githubusercontent.com/32345913/67686405-67d4cd00-f975-11e9-8971-055cdd5f4411.png)

This is the exe
https://drive.google.com/file/d/13Rhk4rNv1IXmc24q7IliQOlTmyD-B-XC/view?usp=sharing

The file weighs 14.6 KB

If you can help me, you can be grateful.

Regards !!

**Comment by marowizz** [comment]
@sctnightcore you can help me?

**Comment by marowizz** [comment]
guys please can help me?
I am new to this world and I have read a lot of documentation but no solution to the problem.

**Comment by Nipodemos** [comment]
if i remember well, you can't get to encrypted GRF to get recvpackets
if it is encrypted, then unfortunaly you have to give up

**Comment by marowizz** [comment]
If so, I have nothing else to do
thx. @Nipodemos
