### ISSUE TITLE
merc fire/delete doesn't work

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#2967]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
latest

* **Server**: 
cRO

* **Bug Report / Feature Request**:
cmd: "merc fire/delete" doesn't work , however "send 9f 02 02" works

* **Summary**:

**Comment by ya4ept** [comment]
1. enter the command: `debug 2`
2. enter the command: `merc fire`
3. send log`logs\console.txt`

**Comment by Henrybk** [comment]
This should have been fixed in #2911, please provide the logs so we can see what the problem might be.

**Comment by hubertyang88** [comment]
#2911  tried , It works ! thx
