### ISSUE TITLE
Can someone help me? The server has denied your connection

### ISSUE THREAD

**Issue by polme32** [OpenKore/openkore#2974]
得知exe日期为2013.08.07，packet key为默认，但是还是被服务器拒绝链接，
以下是exe下载路径
http://mx-ro.com/down.htm
贴上我的servers.txt
[梦想仙境]
ip 103.219.36.94
port 6666
private 1
master_version 4
version 107
serverType kRO_RagexeRE_2013_08_07a
serverEncoding GBK
charBlockSize 144
recvpackets recvpackets.txt
captcha 0
clientHash

[console.txt](https://github.com/OpenKore/openkore/files/3861345/console.txt)
这是console记录，求帮帮我！

**Comment by polme32** [comment]
Knowing that the exe date is 2013.08.07, packet key is the default, but the link is still rejected by the server. 
The following is the exe download path. 
Http://mx-ro.com/down.htm. 
Post my servers.txt. 
[dream Wonderland]. 
Ip 103.219.36.94. 
Port 6666. 
Private 1. 
Master_version 4. 
Version 107. 
ServerType kRO_RagexeRE_2013_08_07a. 
ServerEncoding GBK. 
CharBlockSize 144. 
Recvpackets recvpackets.txt. 
Captcha 0. 
ClientHash. 

Console.txt. 
This is a console record. Please help me!

**Comment by 530453506** [comment]
you can try sendCryptKeys, use peek to find these keys

**Comment by alisonrag** [comment]
issue owner disappeared
