### ISSUE TITLE
condition timeout is not working in block partySkill.

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#2976]
* **Openkore version git**: last
* **Server**: RMS Renewal Test Server
* **Bug Report**:
condition `timeout`  is not working in block `partySkill`. This block will use castes constantly
```
partySkill Blessing {
    lvl 10
    timeout 10
#    target_whenStatusInactive Blessing
    sp > 64
    disabled 0
}
```
SelfCondition check `partySkill_0_time` but we have `partySkill_0_target_time`

**Comment by Mortimal** [comment]
https://github.com/OpenKore/openkore/pull/2978

**Comment by c4c1n6kr3m1** [comment]
this one doesn't work ? http://openkore.com/index.php/Target_timeout

**Comment by c4c1n6kr3m1** [comment]
i've been in this situation, need to use timeout + target_timeout, but i cannot remember what condition made me
any example? why do u need timeout when you have target_timeout

**Comment by ya4ept** [comment]
@c4c1n6kr3m1 `timeout` - its standard selfConditions

**Comment by alisonrag** [comment]
fixe in #2982
