### ISSUE TITLE
 Unknown switch : 09D5 09D6 09D7 09D8

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [OpenKore/openkore#2981]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: iRO

* **Bug Report / Feature Request**: Unknown switch : 09D5 09D6 09D7 09D8

* **Summary**:

npc special market, you can buy but no discount
when selling, only get 10z although it's buying prize is 700K

cann't figure out complete packet meaning
this is part of the 09D5  packet (list of items)
```
CF 13 	04 	60 AE 0A 00 	0A 00 00 00 C8 00
```
nameID , itemtype? , price700K , ??????

edit : ah , i got it, 
```
 C8 00 is item's wight x 10
```
weird
what is last 0A ???
edit:

looks like 0A 00 00 00 is item's quantity left

:D

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1  Do u have img in game ?

**Comment by c4c1n6kr3m1** [comment]
i don't have. i'm lazy worst than you
u can try for yourself ,  npc inside har_in01 sell some old cowboy headgears
and prontera rebellion machine sell Probation gun
guns sell for 4M each
and headgears >700K
ask @Fadreus , may be he will give you free zeny if you need it haha:D

**Comment by Fadreus** [comment]
I think at Eden 2nd Floor NPC selling arrow might having similar thing.
Testing it there is cheaper..

**Comment by c4c1n6kr3m1** [comment]
ah , always forget this quiver merchant location, it's near entrance
moc_paraup 41 162 Quivering Merchant	50576
