### ISSUE TITLE
Missing Swordsman's Passive Skill

### ISSUE THREAD

**Issue by filipeqm** [OpenKore/openkore#299]
The HP Regen Passive skill is missing on the recvpackets.txt
I fixed it by adding 0A27 8 8 1 to the file
openkore folder > tables/iRO/recvpackets.txt

**Comment by Doomr** [comment]
There may also be an issue with SP Regen Passive.
Packet Tokenizer: Unknown switch: 09DB

**Comment by alisonrag** [comment]
the packet are in recvpacket in the latest version of openkore
