### ISSUE TITLE
Help with private server recvpackets and CryptKeys

### ISSUE THREAD

**Issue by soliduusnake** [OpenKore/openkore#2990]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  2.1

* **Server**:  kRO_RagexeRE_2018_05_02b

* **Bug Report / Feature Request**: help with recvpackets and CryptKeys

* **Summary**: I have 3 days triying to configure the new settings of the private server however I can't unpack the Ragexe.exe so I can't have access to recvpackets and the needed CryptKeys.
Server.txt config is as fllow:

ip 104.248.237.34
port 6900
master_version 1
version 55
serverType kRO_RagexeRE_2018_05_02b
addTableFolders RO
charBlockSize 155
pinCode 1
serverEncoding Western
recvpackets recvpackets.txt
clientHash AE318C5D1FB0A19C400E0377D47A418C
sendCryptKeys ???????

Attached the Ragexe.exe

Already try with PEEK, Extractor V3, RO Tools, etc with no luck (Couldn't run Stripper I ignore if it still works)

[Ragexe.zip](https://github.com/OpenKore/openkore/files/3906940/Ragexe.zip)

**Comment by ya4ept** [comment]
go to the forum!
