### ISSUE TITLE
Unknown switch: 0B08,0B09,0B1B,0AE2 , Inventory doesn't work

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#2998]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
lastest

* **Server**: 
cRO

* **Bug Report / Feature Request**:
Server newly updated , and some Unknown switches showed ,  
Packet Tokenizer: Unknown switch: 0B08,0B09,0B1B 0AE2
And , inventory shows empty , cmd "i" and "is" don't work ,  fail to use storage, fail to swich equipment  .
New column of inventory is functional , in this column item can be protected to avoid selled to npc.
![image](https://user-images.githubusercontent.com/34257256/70975233-783b3580-20e4-11ea-983a-c7c5a0b486b7.png)

* **Summary**:

**Comment by alisonrag** [comment]
item_list: 0B08, 0B09, 0B0A was implemented to all servers.
try latest version and add
`itemListType 1`
in servers.txt

**Comment by alisonrag** [comment]
0AE2 is just a server asking for open a UI window

**Comment by alisonrag** [comment]
0AE2 added in #3001

**Comment by hubertyang88** [comment]
Tried latest version,  0AE2 is ok , 
but,
itemListType 1  added 
Unknown switch: 0B08 remains.

**Comment by alisonrag** [comment]
TODO:
update recvpackets (this is why we got Unknown switch)
update item unpack struct to cRO

**Comment by hubertyang88** [comment]
after update recvpackets
in src\Network\Receive\ServerType0.pm
items_nonstackable => {
type8 => {
len => 57,
types => 'a2 v C V2 C a8 l v2 C a25 C',
keys => [qw(ID nameID type type_equip equipped upgrade cards expire bindOnEquipType sprite_id num_options options identified)],
},
},

items_stackable => {
type7 => {
len => 24,
types => 'a2 v C v V a8 l C',
keys => [qw(ID nameID type amount type_equip cards expire identified)],
},
},

it should work

**Comment by c4c1n6kr3m1** [comment]
@hubertyang88
did u see this line
```
if (grep { $masterServer->{serverType} eq $_ } qw(iRO_Renewal)) {
```
put cRO inside the qw,  so u don't need to edit the items type

**Comment by hubertyang88** [comment]
It works  @c4c1n6kr3m1 
I actually tried this before , but I don't have updated recvpackets back then . 
Thanks to @alisonrag , give me new recvpackets. 
Can anyone make a proper update and merge it?

**Comment by sctnightcore** [comment]
it better @hubertyang88 
```
} elsif ($args->{switch} eq '0B0A') { # item_list
	if (grep { $masterServer->{serverType} eq $_ } qw(cRO iRO_Renewal)) {
		return $items->{type7};
	} else {
		return $items->{type8};
	}

 elsif ($args->{switch} eq '0B09') { # item_list
	if (grep { $masterServer->{serverType} eq $_ } qw(cRO iRO_Renewal)) {
		return $items->{type6};
	} else {
		return $items->{type7};
	}
```

**Comment by lasep** [comment]
sir @hubertyang88
how do u login to this server? i always get something "wide character" error when type chinese username?

**Comment by hubertyang88** [comment]
inventory shows empty after use tele or change maps
new Unknown switch found . 
Unknown switch: 0B1B , 08E2
[console.txt](https://github.com/OpenKore/openkore/files/3992644/console.txt)
0B1B is long packet.

Anyone has new recvpackets ?

**Comment by alisonrag** [comment]
> inventory shows empty after use tele or change maps
> new Unknown switch found .
> Unknown switch: 0B1B , 08E2
> [console.txt](https://github.com/OpenKore/openkore/files/3992644/console.txt)
> 0B1B is long packet.
> 
> Anyone has new recvpackets ?

both are not implemented in openkore
08E2 = navigation system, server asking for client show navigation to a determined location
0B1B = seems like hotkeys

**Comment by hubertyang88** [comment]
0B1B and  08E2 , these two are irrelevant to inventory bug ,  where should I look to fix empty inventory problem after change maps? 
after change map , do openkore try to read item info again?

**Comment by hubertyang88** [comment]
see #3003
