### ISSUE TITLE
0AF4

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [OpenKore/openkore#2999]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 
 PS
* **Bug Report / Feature Request**:

* **Summary**:

send skill_use_location , 11 bytes
F4 0A 01 00 12 00 3E 00 6F 00 00 
what is the latest 00 ???

**Comment by alisonrag** [comment]
```/// Request to use a ground skill.
/// 0116 <skill lv>.W <skill id>.W <x>.W <y>.W (CZ_USE_SKILL_TOGROUND)
/// 0366 <skill lv>.W <skill id>.W <x>.W <y>.W (CZ_USE_SKILL_TOGROUND2)
/// 0AF4 <skill lv>.W <skill id>.W <x>.W <y>.W <unknown>.B (CZ_USE_SKILL_TOGROUND3)
/// There are various variants of this packet, some of them have padding between fields.```
```
void clif_parse_UseSkillToPos(int fd, struct map_session_data *sd)
{
	struct s_packet_db* info = &packet_db[RFIFOW(fd,0)];
	if (pc_cant_act(sd))
		return;
	if (pc_issit(sd))
		return;

	clif_parse_UseSkillToPosSub(fd, sd,
		RFIFOW(fd,info->pos[0]), //skill lv
		RFIFOW(fd,info->pos[1]), //skill num
		RFIFOW(fd,info->pos[2]), //pos x
		RFIFOW(fd,info->pos[3]), //pos y
		// TODO: find out what this is intended to do
		//RFIFOB(fd, info->pos[4])
		-1	//Skill more info.
	);
}```

**Comment by alisonrag** [comment]
seems like no one was able to find out what this last byte is supposed to do.

do you have more examples of this packet?

sometime it can be just a unnused field

**Comment by c4c1n6kr3m1** [comment]
nah, i only have fire wall from novice Mage Manual, and it's the same, always 00
```
'0AF4' => ['skill_use_location', 'v4 Z1', [qw(lv skillID x y)]],
```
this ps fucked up , always sent npc_talk_close every 2 seconds , it made NPC's ai broken

**Comment by alisonrag** [comment]
Ps? Can u explain about npc close spam?

**Comment by alisonrag** [comment]
seems like a unused byte, i will close this issue until client start to send another info in this last byte
