### ISSUE TITLE
Incoming data left in the buffer: 0>  81 00 08      

### ISSUE THREAD

**Issue by lloydq15** [OpenKore/openkore#3006]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Summary**:
Hi everyone i am trying to bot on a new server classic high-rate
![Untitled](https://user-images.githubusercontent.com/59231642/71449037-4d5f6b80-26fa-11ea-8e01-33782e3be778.png)
 i am still getting this issue :
Hope Someone will help me this..so much appreciated... Merry Christmas <3

**Comment by lloydq15** [comment]
Hope Someone will help me so much appreciated`

**Comment by sctnightcore** [comment]
I'm lazy for help u.
back to read openkore wiki

**Comment by lloydq15** [comment]
@sctnightcore  hope u help me..can i contact you on other software?.,i configure it whole day but i did not success :(

**Comment by lloydq15** [comment]
@sctnightcore  or some guide how to..thanks a lot sir
