### ISSUE TITLE
Map Timeout Van Ro

### ISSUE THREAD

**Issue by KaiJein** [OpenKore/openkore#3007]
[VanRO:Renewal]
ip classic.vanserver.com
port 8500
private 1
master_version 50
version 35
serverType kRO_RagexeRE_2015_10_29a
serverEncoding Western
charBlockSize 147
recvpackets vanrorecv.txt
addTableFolders vanro;kRO/RagexeRE_2015_10_29a;translated;translated/kRO_english;kRO
clientHash f3317ec20a442d9d8014d67ea4158254
#sendCryptKeys 0x1CA773E0, 0x64D666C9, 0x0D6CDA0F
#chatLangCode 3
#masterLogin_packet 0825

I already got recvpackets from PEEK, already got cryptkeys, versions, charblocksize.
I already played with master_version and other commented configs.
I also tried poseidon, I'm getting uknown packets in debug.
I also tried xkore 1 and 3, for xkore 1 i'm getting unable to inject, for xkore 3 I can login to map but freezes and it spams proxying and connecting.
I don't know if I'm doing xkore 3 right, I just did it like how poseidon is setup like new xml file.
for xkore 0, after I character select, I get Map timeout.

Thanks in advance for the help!
![VanRo](https://user-images.githubusercontent.com/59220464/71451825-53b41d00-27b8-11ea-9045-123bd1b8f42a.jpg)

**Comment by sctnightcore** [comment]
I'm lazy for help u . back to read openkore wiki .
