### ISSUE TITLE
Can't Detect NPC/Players names and coordinates [Custom Packet Length]

### ISSUE THREAD

**Issue by TehKurangManis** [OpenKore/openkore#3008]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
Happy New Year 2019 Guys
* **Server**: 
ValValRO
* **Summary**:
NPC name and coordinate ERROR. Monsters coordinate is fine
Can't Detect NPC/Players names and coordinates. When I try to use WPEpro to recv server length packet. It was custom packet started with FF FF FF FF FF. 

https://imgur.com/R98Qsju
![YY](https://user-images.githubusercontent.com/59425679/71649308-7a3dff00-2d48-11ea-9f7b-fe8eed6f5bd9.png)

**Comment by sctnightcore** [comment]
client date? servertype?

**Comment by Fadreus** [comment]
@sctnightcore 
http://forums.openkore.com/viewtopic.php?f=9&t=215313&sid=8637cd4890fe266571b615bad3d5f3f4

He posted there before.

**Comment by TehKurangManis** [comment]
> client date? servertype?

client date : Jan 16 , 2019

**Comment by sctnightcore** [comment]
@TehKurangManis  openkore support only 2018 not 2019 !

**Comment by TehKurangManis** [comment]
> @TehKurangManis openkore support only 2018 not 2019 !

Can you give me a clue how to fix this problem? packer_parser maybe?

**Comment by alisonrag** [comment]
#3023 same issue
