### ISSUE TITLE
equip cards unpack ... length from a hash ?

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [OpenKore/openkore#3011]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**: BUG ?

* **Summary**:

```
sub itemName {
	my $item = shift;

	my $name = itemNameSimple($item->{nameID});

	# Resolve item prefix/suffix (carded or forged)
	my $prefix = "";
	my $suffix = "";
	my @cards;
	my %cards;
	
	my $item_len = length($item);
	my $card_unpack;
	
	# FIXME WORKAROUND TO ITEMID 4BYTES
	if ($item_len == 67 || $item_len == 34) {
		$card_unpack = "V";
	} else {
		$card_unpack = "v";
	}
	
	my $card_len = length pack $card_unpack;
	for (my $i = 0; $i < 4; $i++) {
		my $card = unpack($card_unpack, substr($item->{cards}, $i*$card_len, $card_len));
		next unless $card;
		push(@cards, $card);
		($cards{$card} ||= 0) += 1;
	}
.
.
.
```

this part
```
my $item_len = length($item);
```
but $item is hash ref , this is weird
to unpack cards, we need it from $item->{cards}

**Comment by alisonrag** [comment]
Updated in https://github.com/OpenKore/openkore/pull/3003

This issue is not valid, about 4 bytes card, only item_list packet use thia size

**Comment by c4c1n6kr3m1** [comment]
ups sorry, didn't read latest version
delete the useless line - 2179
