### ISSUE TITLE
Elements of weapon don't show

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3015]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
Latest

* **Server**: 
cRO

* **Bug Report / Feature Request**:
Normally Elements of weapon showed [Wind] [Fire]
But now, it shows [1 Option] , where should I look to fix this?

* **Summary**:

**Comment by alisonrag** [comment]
This is not a bug, this was made this way cause weapon can have more then 1 option.
I updated this so ppl can read
If u want to change by yourself go to Misc.pm, sub itemName
