### ISSUE TITLE
stat exp/job bug

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [OpenKore/openkore#3017]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**:  Private Server

* **Bug Report / Feature Request**: BUG

* **Summary**:

```
[Jan 11 12:52:02 2020.42] ================================================
<< Received packet:      0ACB [12 bytes]   Jan 11 12:52:02 2020
  0>  CB 0A 01 00 64 F9 2E 00    00 00 00 00                ....d.......
[Jan 11 12:52:02 2020.45] Received packet: 0ACB Handler: stat_info
[Jan 11 12:52:02 2020.49] Stat: 1 => 3078500
[Jan 11 12:52:02 2020.52] ================================================
<< Received packet:      0ACB [12 bytes]   Jan 11 12:52:02 2020
  0>  CB 0A 16 00 00 09 3D 00    00 00 00 00                ......=.....
[Jan 11 12:52:02 2020.55] Received packet: 0ACB Handler: stat_info
[Jan 11 12:52:02 2020.58] Stat: 22 => 0
[Jan 11 12:52:02 2020.62] ================================================
<< Received packet:      0ACB [12 bytes]   Jan 11 12:52:02 2020
  0>  CB 0A 02 00 7C 3E 21 01    00 00 00 00                ....|>!.....
[Jan 11 12:52:02 2020.66] Received packet: 0ACB Handler: stat_info
[Jan 11 12:52:02 2020.69] Stat: 2 => 18955900
[Jan 11 12:52:02 2020.72] You have gained 0/0 (0.00%/0.00%) Exp
[Jan 11 12:52:02 2020.76] ================================================
<< Received packet:      0ACB [12 bytes]   Jan 11 12:52:02 2020
  0>  CB 0A 17 00 FF C9 9A 3B    00 00 00 00                .......;....
[Jan 11 12:52:02 2020.79] Received packet: 0ACB Handler: stat_info
[Jan 11 12:52:02 2020.83] Stat: 23 => 999999999
[Jan 11 12:52:02 2020.86] ================================================
<< Received packet:      00B0 - Your Status Info [8 bytes]   Jan 11 12:52:02 2020
  0>  B0 00 0C 00 10 00 00 00                               ........
[Jan 11 12:52:02 2020.90] Received packet: 00B0 Handler: stat_info
[Jan 11 12:52:02 2020.94] Stat: 12 => 16
[Jan 11 12:52:02 2020.97] ================================================
```

take a look at 2nd data, it said basemax exp Stat: 22 => 0
**0** while real value is 4,000,000

client showed base exp 76.9%
bot don't show any number while hovering mouse on base exp

why use Z8 to unpack 64 bits number????

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1  

we cannot use Q for unpack 64 bit packet .
https://github.com/OpenKore/openkore/blob/e346fdd370bd81ffad8e6d5c51877b99d1d991ed/src/Network/Receive.pm#L6074-L6090

**Comment by c4c1n6kr3m1** [comment]
i use the same tactic with you @sctnightcore 
```
$args->{val} = hex (unpack("H*",scalar reverse(unpack("a8", substr($args->{'RAW_MSG'}, 4, 8)))))
```

**Comment by alisonrag** [comment]
> i use the same tactic like yours @sctnightcore 
> 
> ```
> $args->{val} = hex (unpack("H*",scalar reverse(unpack("a8", substr($args->{'RAW_MSG'}, 4, 8)))))
> ```

this works?

**Comment by c4c1n6kr3m1** [comment]
yes, it's working, i'm sure the only difference is me using "a8" not "Z8"
but i need to test this on sub received_characters_unpackString , because 155 charBlockSize use "Z8" too

**Comment by alisonrag** [comment]
> yes, it's working, i'm sure the only difference is me using "a8" not "Z8"
> but i need to test this on sub received_characters_unpackString , because 155 charBlockSize use "Z8" too

it was a fail workaround, just a pull request to "support" 155 charblocksize, if u test with your model/code it can works

**Comment by alisonrag** [comment]
can u create a pull request?

**Comment by c4c1n6kr3m1** [comment]
no, i got another problem on this 155 charblocksize
i test this on lvl 175 rebel

first login working fine
second login ( after relog ), [console] show 2 weird report ,: "integer overflow in hexadecimal number at ......receive.pm line ..." 
these report show line number owned by hex function
i tried revert to original code, same report
( weird, working on stat_info,  working on sub received_characters  first login, but fail on sub received_characters after relog )
tried to google this and i'm not good enough too find the solution
i leave it to you guys

**Comment by c4c1n6kr3m1** [comment]
i'll test with bigint

**Comment by c4c1n6kr3m1** [comment]
after struggle , looks like i understand why relog make a disaster
if you have multiple 099D , this line
```
$character = $char if $char && $char->{ID} eq $accountID && $char->{charID} eq $character->{charID};
```
and key like $character->{last_map} ( which has further proc·ess with substr ) will corrupted
thus for 155 charBlockSize, after relog ,  exp and exp_job will corrupted to , will made exp become veryveryveryvvvvvv.... hugh number,
