### ISSUE TITLE
Unknown name for player connected/exists/moved packet

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [OpenKore/openkore#3023]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**: bug?

* **Summary**:

09FE,09FF,09FD , but probably previous switch too
example :
```
<< Received packet:      09FF [88 bytes]   Jan 08 10:54:47 2020
  0>  FF 09 58 00 00 89 84 1E    00 3E 4D 02 00 96 00 00    ..X......>M.....
 16>  00 00 00 00 00 00 00 8F    10 12 00 00 00 00 00 00    ................
 32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 00    00 00 00 35 4C 84 05 05    ...........5L...
 64>  00 AF 00 00 00 FF FF FF    FF FF FF FF FF 00 00 00    ................
 80>  52 61 66 74 61 61 61 61                               Raftaaaaa
[Jan 08 10:54:47 2020.22] Received packet: 09FF Handler: actor_exists
[Jan 08 10:54:47 2020.23] Player Exists: Unknown #2000009 (4) Level 175 Girl Star Emperor (213, 200)
```
sakexe : 09FF' => ['actor_exists', 'v C a4 a4 v3 V v11 a4 a2 v V C2 a3 C3 v2 a9 Z*', [qw(len object_type ID charID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tophead midhead hair_color clothes_color head_dir costume guildID emblemID manner opt3 stance sex coords xSize ySize act lv font opt4 name)]],

with sakexe formula 
for $arg->{name} , raw data = 00 00 52 61 66 74 61 61 61 61
bytesToString failed on this
wonder where this formula came from
it's annoying to see "unknown " on wx right pane

**Comment by sctnightcore** [comment]
> ## ------------------ Openkore Issues Template ------------------
> * **Openkore version git**:
> 
> * **Server**:
> 
> * **Bug Report / Feature Request**: bug?
> 
> * **Summary**:
> 
> 09FE,09FF,09FD , but probably previous switch too
> example :
> 
> ```
> << Received packet:      09FF [88 bytes]   Jan 08 10:54:47 2020
>   0>  FF 09 58 00 00 89 84 1E    00 3E 4D 02 00 96 00 00    ..X......>M.....
>  16>  00 00 00 00 00 00 00 8F    10 12 00 00 00 00 00 00    ................
>  32>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00    ................
>  48>  00 00 00 00 00 00 00 00    00 00 00 35 4C 84 05 05    ...........5L...
>  64>  00 AF 00 00 00 FF FF FF    FF FF FF FF FF 00 00 00    ................
>  80>  52 61 66 74 61 61 61 61                               Raftaaaaa
> [Jan 08 10:54:47 2020.22] Received packet: 09FF Handler: actor_exists
> [Jan 08 10:54:47 2020.23] Player Exists: Unknown #2000009 (4) Level 175 Girl Star Emperor (213, 200)
> ```
> 
> sakexe : 09FF' => ['actor_exists', 'v C a4 a4 v3 V v11 a4 a2 v V C2 a3 C3 v2 a9 Z*', [qw(len object_type ID charID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tophead midhead hair_color clothes_color head_dir costume guildID emblemID manner opt3 stance sex coords xSize ySize act lv font opt4 name)]],
> 
> with sakexe formula
> for $arg->{name} , raw data = 00 00 52 61 66 74 61 61 61 61
> bytesToString failed on this
> wonder where this formula came from
> it's annoying to see "unknown " on wx right pane

https://github.com/OpenKore/openkore/blob/master/src/Network/Receive/bRO.pm#L27-L29

**Comment by c4c1n6kr3m1** [comment]
so, if i follow bRO
maxHP = FF FF FF FF
HP = FF FF FF FF
isBoss = 00
opt4 = 00 00
name = 52 61 66 74 61 61 61 61

what is opt4 ? because i ever saw it once with value  "01 00"

**Comment by sctnightcore** [comment]
@c4c1n6kr3m1  What server do you play?
client info ?

**Comment by alisonrag** [comment]
> so, if i follow bRO
> maxHP = FF FF FF FF
> HP = FF FF FF FF
> isBoss = 00
> opt4 = 00 00
> name = 52 61 66 74 61 61 61 61
> 
> what is opt4 ? because i ever saw it once with value "01 00"

Its right, maxHP and HP will always have "FF FF FF FF" value, tested in tRO, bRO and now iRO-RT
isBoss is to identify MVP
I dont know much about opt4 need to chech packet struct in HérculesWS

**Comment by moneyisgod** [comment]
Well just check all actors and will understand. I tried to guess this opt4 and have no success.

**Comment by moneyisgod** [comment]
I was trying to resolve all unknowns and opt on packet structs and i didnt found anything related. I guess need to use black box method.
