### ISSUE TITLE
Anti Bot

### ISSUE THREAD

**Issue by KaiJein** [OpenKore/openkore#3024]
Anyone can help me regarding of this please...

here is my block config i dont know how to make it work please..
```perl
reactOnNPC talk num @eval(my $color = '#1~1';my $color2 = '#1~2';my $number1 = #2~2;my $number2 = #2~4;my $number3 = #2~6;my $number4 = #2~8;my $number5 = #2~10;my $number6 = #2~12;my $numberout1 = 0;my $numberout2 = 0;if ($color1 == '#2~1'@) {$numberout1 = $number1;} if ($color1 == '#2~4'@) {$numberout1 = $number2;} if ($color1 == '#2~7'@) {$numberout1 = $number3;} if ($color1 == '#2~10'@) {$numberout1 = $number4;} if ($color2 == '#2~1'@) {$numberout2 = $number1;} if ($color2 == '#2~4'@) {$numberout2 = $number2;} if ($color2 == '#2~7'@) {$numberout2 = $number3;} if ($color2 == '#2~10'@) {$numberout2 = $number4;} return ($numberout1 + $numberout2@);)
type number
useColors 1
msg_0 /---- Bot verification ----/
msg_1 /^What is the result of:/
msg_2 /\^([0-9a-fA-F]{6})\^[0-9a-zA-Z]\w+\^([0-9a-fA-F]{6})\s+plus\s+\^([0-9a-fA-F]{6})\w+\^[0-9a-zA-Z]/i
msg_3 /\[\s*\^([0-9a-fA-F]{6})(\d)\^[0-9a-fA-F]{6}\s*\] \s*\[\s*\^([0-9a-fA-F]{6})(\d)\^[0-9a-fA-F]{6}\s*\] \s*\[\s*\^([0-9a-fA-F]{6})(\d)\^[0-9a-fA-F]{6}\s*\] \s*\[\s*\^([0-9a-fA-F]{6})(\d)\^[0-9a-fA-F]{6}\s*\] \s*\[\s*\^([0-9a-fA-F]{6})(\d)\^[0-9a-fA-F]{6}\s*\] \s*\[\s*\^([0-9a-fA-F]{6})(\d)\^[0-9a-fA-F]{6}\s*\]/i
}

reactOnNPC talk num @eval(my $color1 = '#3~1';my $color4 = '#4~1';my $color5 = '#5~1';my $color6 = '#6~1';my $number3 = #3~2;my $number4 = #4~2;my $number5 = #5~2;my $number6 = #6~2;my $anwser = 0;if ($color3 eq '#0~1'@) {$anwser = $number1;}if ($color4 eq '#0~1'@) {$anwser = $number2;}if ($color5 eq '#0~1'@) {$anwser = $number3;}if ($color6 eq '#0~1'@) {$anwser = $number4;} return $anwser) {
type number
useColors 1
delay 5
msg_0 /---- Bot verification ----/
msg_1 /Choice the one you see!/
msg_2 /Reply saying you are not a bot./
msg_3 /\^([0-9a-fA-F]{6})I am not a bot/
msg_4 /\^([0-9a-fA-F]{6})I am not a bot/
msg_5 /\^([0-9a-fA-F]{6})I am not a bot/
msg_6 /\^([0-9a-fA-F]{6})I am not a bot/
}
```
![111](https://user-images.githubusercontent.com/59220464/73182082-57d6b000-4153-11ea-95a7-3e967f40c311.jpg)
![222](https://user-images.githubusercontent.com/59220464/73182089-5b6a3700-4153-11ea-83d4-9213ef612b04.jpg)

Please Help me regarding of this thank you in advance.

**Comment by KaiJein** [comment]
i Just want to update.please...
![bot num1](https://user-images.githubusercontent.com/59220464/73251257-8dcb7100-41f3-11ea-8636-3086f8d3cd21.gif)

**Comment by cliffordx3** [comment]
` reactOnNPC talk resp @resp (@eval(
my @@color = ('#3~1';'#4~1';'#5~1';'#6~1'@;)
my @@resp ('#3~2';'#4~2';'#5~2';'#6~2'@;)
my $anwser = 'error';

if (@@color eq '#3~1'@) {
$anwser == @@resp[0];}
if ($@@color eq '#4~1'@) {
$anwser == @@resp[1];}
if (@@color eq '#5~1'@) {
$anwser == @@resp[2];}
if (@@color eq '#6~1'@) {
$anwser == @@resp[3];}
return $anwser;)) { 
type responses
useColors 1 
delay 5 
msg_0 /---- Bot verification ----/ 
msg_1 /Choice the one you see!/ 
msg_2 /Reply saying you are not a bot./
msg_3 /\^([0-9a-fA-F]{6})I am not a bot\^000000/ 
msg_4 /\^([0-9a-fA-F]{6})I am not a bot\^000000/ 
msg_5 /\^([0-9a-fA-F]{6})I am not a bot\^000000/ 
msg_6 /\^([0-9a-fA-F]{6})I am not a bot\^000000/ 
}
   `

**Comment by Nipodemos** [comment]
didn't have a plugin that checks color of letters too? Almost sure that is inside `openkore/plugins/needs-review` folder

you will first have to know what colors are possible
then correct that typo on `reactOnNPC` line (there is a #1~1 that is not quoted)

that's all i can say to help now

**Comment by KaiJein** [comment]
they don't generate

 NPC message saved (1): "What is the result of: ".
[Feb 01 11:24:20 2020.86] Unknown #110011142: 403333+0222405
[Feb 01 11:24:20 2020.88] [reactOnNPC] NPC message saved (2):
"^FEFAFF4^000000^F2FFFB0^000000^F7FBFF3^000000^B780FF3^000000^F5F6FF3^000000^FFF8F53^000000^148774+^000000^F2FFFB0^000000^FFF8F52^000000^1487742^000000^F7FBFF2^000000^FDF5FF4^000000^F7FFF20^000000^F5F6FF5^000000".
[Feb 01 11:24:20 2020.90] [reactOnNPC] onNPCAction type is: number.
[Feb 01 11:24:20 2020.92] [reactOnNPC] Conditions for reactOnNPC_0
(npc:number , rect:number) is met.
[Feb 01 11:24:20 2020.93] [reactOnNPC] Matching [msg (0)] "Attempt:
^ff00000^000000/3" to
"/\^[0-9a-fA-F]{6}\d+\^000000\^([0-9a-fA-F]{6})(\d+)\^000000\^([0-9a-fA-F]{6})(\d+)\^000000/"
... doesn't match.
[Feb 01 11:24:20 2020.94] [reactOnNPC] One or more lines doesn't match for
"reactOnNPC_0" (0).
[Feb 01 11:24:20 2020.95] [reactOnNPC] Conditions for reactOnNPC_1
(npc:number, rect:responses) 'type' not met.
[Feb 01 11:24:20 2020.96] [reactOnNPC] Conditions for reactOnNPC_2
(npc:number, rect:responses) 'type' not met.
[Feb 01 11:24:20 2020.97] itself: Type 'talk num <number #>' to input a
number.
[Feb 01 11:24:21 2020.50] AI set to manual mode
[Feb 01 11:24:22 2020.51] [macro log] «««««««« Bot Hunt Number Danger
»»»»»»»»»»
[Feb 01 11:24:33 2020.26] [reactOnNPC] onNPCAction type is: continue.
[Feb 01 11:24:33 2020.30] [reactOnNPC] Conditions for reactOnNPC_0
(npc:continue, rect:number) 'type' not met.
[Feb 01 11:24:33 2020.34] [reactOnNPC] Conditions for reactOnNPC_1
(npc:continue, rect:responses) 'type' not met.
[Feb 01 11:24:33 2020.36] [reactOnNPC] Conditions for reactOnNPC_2
(npc:continue, rect:responses) 'type' not met.
[Feb 01 11:24:33 2020.37] itself: Type 'talk cont' to continue talking
[Feb 01 11:24:34 2020.74] Unknown #110011142: Attempt: 1/3
[Feb 01 11:24:34 2020.78] [reactOnNPC] NPC message saved (0): "Attempt:
^ff00001^000000/3".
[Feb 01 11:24:34 2020.82] Unknown #110011142: Choice the one you see!
[Feb 01 11:24:34 2020.84] [reactOnNPC] NPC message saved (1): "Choice the
one you see!".
[Feb 01 11:24:34 2020.86] ---- Responses (Unknown #110011142) ----
#  Response
0  I am not a bot
1  I am not a bot
2  I am not a bot
3  I am not a bot
4  Cancel Chat

number they are random from 1-9 digit + random 1-9 digit to something like
123214+5215 or 2412+521512 something like that.. and this one I am not a
bot they dont have any color display

**Comment by moneyisgod** [comment]
I have no idea how to bypass this neither based in a visible spectre.

**Comment by cliffordx3** [comment]
﻿reactOnNPC talk resp @resp ( 
my $color5 = '5~1';
my $color6 = '6~1';
my $color7 = '7~1';
my $color8 = '8~1';

my $resp5 = '5~2';
my $resp5 = '6~2';
my $resp5 = '7~2';
my $resp5 = '8~2';

my $answer = 'error';

if ( $color5 eq $resp5 ){
return $answer = $resp5;
}
if ( $color6 eq $resp6 ){
return $answer = $resp6;
}
if ( $color7 eq $resp7 ){
return $answer = $resp7;
}
if ( $color8 eq $resp8 ){
return $answer = $resp8;
}
) {
useColors 1
delay 1
type responses

msg_1 /--- Bot verification ---/
msg_2 /Reply saying you are not a bot./
msg_3 /Attempt\s\^([0-9a-fA-F]{6})(\d):(\d)/
msg_4 /Choice the one you see!/
msg_5 /\^([0-9a-fA-F]{6})(.*)/
msg_6 /\^([0-9a-fA-F]{6})(.*)/
msg_7 /\^([0-9a-fA-F]{6})(.*)/
msg_8 /\^([0-9a-fA-F]{6})(.*)/



}
Try this reactOnNPC of it will triggered I am not a bot feedback ok. Thanks.

**Comment by cliffordx3** [comment]
> ﻿reactOnNPC talk resp @resp ( 
my $color5 = '5~1';
my $color6 = '6~1';
my $color7 = '7~1';
my $color8 = '8~1';

my $resp5 = '5~2';
my $resp5 = '6~2';
my $resp5 = '7~2';
my $resp5 = '8~2';

my $answer = 'error';

if ( $color5 eq $resp5 ){
return $answer = $resp5;
}
if ( $color6 eq $resp6 ){
return $answer = $resp6;
}
if ( $color7 eq $resp7 ){
return $answer = $resp7;
}
if ( $color8 eq $resp8 ){
return $answer = $resp8;
}
) {
useColors 1
delay 1
type responses

msg_1 /--- Bot verification ---/
msg_2 /Reply saying you are not a bot./
msg_3 /Attempt\s\^([0-9a-fA-F]{6})(\d):(\d)/
msg_4 /Choice the one you see!/
msg_5 /\^([0-9a-fA-F]{6})(.*)/
msg_6 /\^([0-9a-fA-F]{6})(.*)/
msg_7 /\^([0-9a-fA-F]{6})(.*)/
msg_8 /\^([0-9a-fA-F]{6})(.*)/



}

>

**Comment by xcoutinho** [comment]
Managed to solve?

**Comment by KaiJein** [comment]
> Managed to solve?

No it won't.

**Comment by xcoutinho** [comment]
There's no way?

send me e-mail xcoutinho@gmail.com

**Comment by xcoutinho** [comment]
I have a few ways

**Comment by cliffordx3** [comment]
How to solved?
