### ISSUE TITLE
Please help update the cRO

### ISSUE THREAD

**Issue by mcpchen** [OpenKore/openkore#3031]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: cRO

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by sctnightcore** [comment]
I think u need wait .

**Comment by alisonrag** [comment]
what kinda of update?!

**Comment by mcpchen** [comment]
Cro &nbsp;i command is not work and 0B08



发自我的iPhone


------------------ Original ------------------

**Comment by hubertyang88** [comment]
@mcpchen 最新的openkore应该可以用了，我看你在 # 3005 里面的问过了，物品栏应该可以用,
Packet Parser: Unknown switch: 0B1B 这种不影响使用的
Latest version should work as long as you update as  #3005 ,  openkore can work with some unknown switches .

**Comment by mcpchen** [comment]
非常感谢，最新测试也不行，昨天给了我一份cRO的封包文件添加进去才可以，请问一下波塞冬这个在cRO有办法吗？
我波塞冬试过2台物理机不能连接。虚拟机也一样不行。现在只能是挂几分钟断线在上线使用openkore.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hubertyang88"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月4日(星期二) 上午9:25
收件人:&nbsp;"OpenKore/openkore"<openkore@noreply.github.com&gt;;
抄送:&nbsp;"阿仙奴-Arsenal"<2356507@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenKore/openkore] Please help update the cRO (#3031)




@mcpchen 最新的openkore应该可以用了，我看你在 # 3005 里面的问过了，物品栏应该可以用,
 Packet Parser: Unknown switch: 0B1B 这种不影响使用的
 Latest version should work as long as you update as  #3005 ,  openkore can work with some unknown switches .

**Comment by sctnightcore** [comment]
@hubertyang88  @mcpchen 
Me and @alisonrag  not chinese.
Please use english.

**Comment by mcpchen** [comment]
Tanks!&nbsp;
sorry my en is very very bad


USER translation SOFT：
Thank you very much, the latest test also not line, yesterday gave me a packet of cRO files added to, excuse me Poseidon this in cRO can?
I Poseidon tried 2 physical machine can't connect. The virtual machine as well. Now, a few minutes break can only be used in online openkore.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月4日(星期二) 上午10:17
收件人:&nbsp;"OpenKore/openkore"<openkore@noreply.github.com&gt;;
抄送:&nbsp;"阿仙奴-Arsenal"<2356507@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenKore/openkore] Please help update the cRO (#3031)




@hubertyang88  @mcpchen
 Me and @alisonrag  not chinese.
 Please use english.

**Comment by moneyisgod** [comment]
cRO have nProtect. You can emulate it.

**Comment by mcpchen** [comment]
THANKS ALL!
