### ISSUE TITLE
Need Bot for iRO 

### ISSUE THREAD

**Issue by kanekihaise777** [OpenKore/openkore#3033]
------------------ Openkore Issues Template ------------------
Server 
iRO
Feature Request
Request --> How to bypass the anti cheat system and allow botting again. Can you guys help?
It actualy chooses a Boy character Level 1 instead of my character.

![image](https://user-images.githubusercontent.com/54960545/73768477-0746fe80-47b4-11ea-961c-66ee0b27a4d9.png)

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/73772341-edf58080-47ba-11ea-97e5-45fcc8ee94e3.png)

**Comment by Nipodemos** [comment]
closing because it is being treated in other issue

https://github.com/OpenKore/openkore/issues/2963#issuecomment-582164654
