### ISSUE TITLE
Yggdrasill Server

### ISSUE THREAD

**Issue by Inabaglefra** [OpenKore/openkore#3034]
Hi Sir, 

Can I ask question if the yggrasil server by electronics extreme work on your openkore, since i download the whole openkore i see the server ygg. When im creating account i found out that the bot can connect but unfortunately did not moving.. 

Ygg server is is on process? Or is Not.

Sorry for may bad english. 

Thank you

**Comment by Fadreus** [comment]
https://github.com/OpenKore/openkore#faq-frequently-asked-questions
https://github.com/OpenKore/openkore#status-of-botting-on-official-servers

Your English is not that bad but your eyes is definitely  rotten.

**Comment by Inabaglefra** [comment]
What do you mean Sir? Im asking if it work thr yggdrasil server in openkore?

**Comment by alisonrag** [comment]
nope, openkore dont wirk by itself, need a bypass to eac, and to ask help for eac there is a another issue opened
