### ISSUE TITLE
Parameter "name_given" issue

### ISSUE THREAD

**Issue by sianromantic** [OpenKore/openkore#3035]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2020_02_03

* **Server**: private server

* **Bug Report / Feature Request**: getting (name_given) value too slow.

* **Summary**:
Situation:
10 monster in one map.
The names are different, I need to find the right name and kill it to get the reward
ex. the correct name is blade but there are other look similar names like bald or bold.
i tried use plugin hook to packet/actor_info ,

<details><summary>snippet code</summary>
<p>

#### 
```
my $name;
my ($self, $args) = @_;
$name = bytesToString($args->{name});
message "Fake name : $name\n";
```
</p>
</details>

The code is work,only problem is packet speed too slow.
speed : 3s or more per packet(name_given).

**Comment by alisonrag** [comment]
this is not a issue, this was a decision take to reduce lag in: #959

if u want to do it faster, just go to control/timeouts.txt and change 
ai_getInfo from `2` to `.3`
