### ISSUE TITLE
plugins killcountFix Error

### ISSUE THREAD

**Issue by oleokoong** [OpenKore/openkore#3036]
Im using latest openkore from github

[killcountFix] New mission added without goal. Quest id: '65536' | Mob id: ''
[killcountFix] Data file has no information on questID '65536' and MobID ''.
[killcountFix] Data file will be updated once you kill the first mob.
[killcountFix] New mission added without goal. Quest id: '65536' | Mob id: ''
[killcountFix] Data file has no information on questID '65536' and MobID ''.
[killcountFix] Data file will be updated once you kill the first mob.
[killcountFix] New mission added without goal. Quest id: '65536' | Mob id: ''
[killcountFix] Data file has no information on questID '65536' and MobID ''.
[killcountFix] Data file will be updated once you kill the first mob.
[killcountFix] New mission added without goal. Quest id: '65536' | Mob id: ''

Some id will had this ERROR spam in console non stop
and The server never give this quest
can someone help me fix this by ignore this quest in plugins killcountfix?

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: latest from github

* **Server**: pRO 

* **Bug Report / Feature Request**: plugins killcountFix Error

* **Summary**:

**Comment by moneyisgod** [comment]
You just talking shit

**Comment by boom19** [comment]
what server in pRO exactly?

**Comment by alisonrag** [comment]
talking with @oleokoong using latest version this dont happens anymore
