### ISSUE TITLE
plss help me unknown status

### ISSUE THREAD

**Issue by allanpinca** [OpenKore/openkore#3037]
unknown status  824
unknown status 993
unknown status 994

**Comment by sctnightcore** [comment]
it's problem ?

**Comment by ya4ept** [comment]
Show your servers.txt

**Comment by allanpinca** [comment]
# Official RO Servers

# http://ragnarok.uol.com.br
[Brazil - bRO: Valhalla]
ip 200.229.50.36
port 6900
master_version 22
version 1
serverType bRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders bRO
charBlockSize 147
pinCode 1
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1

# http://ragnarok.uol.com.br
[Brazil - bRO: Thor]
ip 200.229.50.3
port 6900
master_version 22
version 1
serverType bRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders bRO
charBlockSize 147
pinCode 1
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1

# http://ro.zhaouc.com/
[cRO - China: Taren]
ip 118.89.42.108
port 6900
master_version 4
version 1
serverType cRO
serverEncoding GBK
charBlockSize 147
addTableFolders cRO
gameGuard 1
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
pinCode 1
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType

# https://ro.gnjoy.id/
[Indonesia - idRO: Yggdrasil]
ip 202.93.26.198
port 6900
master_version 12
version 2
patchserver wpatch.ragnarok.co.id
patchpath /patch02
serverType idRO_Renewal
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 145
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1

# Renewal
# http://playragnarok.com
[International - iRO: Ymir/Yggdrasil/Valkyrie]
title International - iRO: Thor|Chaos (Renewal-compatible)
ip 128.241.92.36
port 6800
master_version 1
version 18
serverType iRO_Renewal
serverEncoding Western
patchserver ropatch1.gravityus.com
patchpath /patch02
addTableFolders iRO/Renewal;iRO
charBlockSize 147
charDeleteDateType 1
sendCryptKeys 0x38012567, 0x078F087E, 0x71BD2BEA
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1

# http://playragnarok.com
[International - iRO: Sakray]
ip 128.241.92.36
port 6800
master_version 14
version 18
serverType iRO_Sakray
serverEncoding Western
addTableFolders iRO/Sakray;iRO
charBlockSize 147
#sendCryptKeys 0x00000000, 0x00000000, 0x00000000
rankingSystemType 1
blockingPlayerCancel 1
charDeleteDateType 1

# TODO: needs a servertype & table folder
# https://ragnarokonline.gungho.jp/
[Japan - jRO: Verdandi]
ip 61.215.212.13
port 6900
master_version 3
version 10
serverType 7
secureLogin 1
serverEncoding Japanese
addTableFolders Old

# http://roz.gnjoy.com/
[Korea - kRO:Zero]
ip 112.175.128.137
port 6950
master_version 0
version 19
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverType Zero
serverEncoding Korean
charBlockSize 155
gameGuard 1
addTableFolders kRO/Zero;kRO
pinCode 1
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
OTT_ip 112.175.128.135
OTT_port 6900
sendCryptKeys 0x2FC330DD, 0x4D914DE2, 0x01C04E1F
blockingPlayerCancel 1

# http://ro.gnjoy.com/
[Korea - kRO: Sara/Rangidis/Thanatos]
ip 112.175.128.137
port 6900
master_version 0
version 19
serverType kRO_RagexeRE_0
serverEncoding Korean
charBlockSize 112
storageEncryptKey 0x050B6F79,0x0202C179,0x00E20120,0x04FA43E3,0x0179B6C8,0x05973DF2,0x007D8D6B,0x08CB9ED9
gameGuard 1
addTableFolders kRO

# http://ro.gnjoy.com/
[Korea - kRO: Sakray]
ip 112.175.128.138
port 6900
master_version 2
version 29
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverType Sakray
serverEncoding Korean
charBlockSize 155
addTableFolders kRO/Sakray;kRO
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
pinCode 1
gameGuard 0

# https://roextreme.com/msp/main
[Philippines - pRO: Valhalla]
ip 139.99.113.156
port 6900
master_version 15
version 24
serverType pRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
addTableFolders pRO
charBlockSize 144
pinCode 1
charDeleteDateType 1
rankingSystemType 1

# https://roextreme.com/msp/main
[Philippines - pRO: Yggdrasil]
ip 139.99.7.212
port 6900
master_version 15
version 24
serverType pRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
addTableFolders pRO
charBlockSize 144
pinCode 1
charDeleteDateType 1
rankingSystemType 1

# https://ru.4game.com/ro/play/
[Russia - rRO-Renewal]
ip 109.105.140.145
port 6800
master_version 25
version 1
serverType rRO
serverEncoding Russian
addTableFolders rRO
charBlockSize 145
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
blockingPlayerCancel 1
gameGuard 0

# https://ro.gnjoy.com.tw/
[Taiwan - twRO: OldFriend (ChaosFree, IrisFree, LokiFree)]
ip 220.130.113.235
port 6900
master_version 5
version 211
serverType twRO
serverEncoding Big5
charBlockSize 144
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
recvpackets recvpackets.txt
addTableFolders twRO
captcha 0

# https://ro.exe.in.th/
[Thailand - tRO Main server (Norse)]
ip 122.155.11.240
port 6900
master_version 7
version 24
serverType tRO
secureLogin 3
secureLogin_type 0
secureLogin_account 0
patchserver wpatch.ragnarok.in.th
patchpath /patch70
serverEncoding Thai
addTableFolders tRO
charBlockSize 112
gameguard 1

[Localhost]
ip localhost
port 6900
private 1
master_version 1
version 20
serverType kRO_RagexeRE_2009_11_04a
serverEncoding Western
addTableFolders translated/kRO_english;kRO

# this is for XKore 2 client only, it won't affect XKore 2 server
# configure serverType, serverEncoding, charBlockSize according to your server
[XKore 2]
ip localhost
port 6901
serverType
serverEncoding Western
addTableFolders translated/kRO_english;kRO
charBlockSize
clientHash 0123456789abcdef0123456789abcdef

# http://play.ratemyserver.net
[RMS Renewal Test Server]
ip 69.197.167.236
port 6900
version 51
master_version 2
serverType RMS
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2014_10_22b;translated;translated/kRO_english;kRO
#clientHash 6e1d7aae3838cd7aec434cd10ef861e9
clientHash 82d12c914f5ad48fd96fcf7ef4cc492d
pinCode 1

# http://play.ratemyserver.net
[RMS Pre-Re Test Server]
ip 69.197.167.236
port 6901
version 51
master_version 2
serverType RMS
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2014_10_22b;translated;translated/kRO_english;kRO
clientHash 82d12c914f5ad48fd96fcf7ef4cc492d
pinCode 1

####################
# Dead

# http://euro-ro.net/
[Europe - euRO]
dead 1
dead_message euRO was closed on September 30, 2010. There used to be transfers to fRO, check out their website.

# Re:Start
# http://playragnarokrestart.com/
[International - iRO: Re:Start]
dead 1
dead_message iRO Re:Start was merged into iRO Renewal on 11th July 2019. Visit official website for more details.

# Pre-renewal
# http://playragnarok.com
[International - iRO: Loki Classic]
title International - iRO: Classic.Loki
dead 1
dead_message iRO Classic was closed on July 11, 2019. Visit official website for more details.

# http://www.ragnarokeurope.com/
[France - fRO]
title France - fRO (ragnarokeurope.com): Chaos
dead 1
dead_message fRO was closed on 12 of August, 2019. Visit official website for more details.

# https://roextreme.com/mysg/main
[Malaysia - mRO]
dead 1
dead_message mRO was merged into phRO on July, 2019. Visit official website for more details.

# http://ggamerz-ro.com/
[GGamerzRO]
dead 1
dead_message GGamer

**Comment by allanpinca** [comment]
# http://ragnarok.uol.com.br
[Brazil - bRO: Valhalla]
ip 200.229.50.36
port 6900
master_version 22
version 1
serverType bRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders bRO
charBlockSize 147
pinCode 1
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1

# http://ragnarok.uol.com.br
[Brazil - bRO: Thor]
ip 200.229.50.3
port 6900
master_version 22
version 1
serverType bRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders bRO
charBlockSize 147
pinCode 1
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1

# http://ro.zhaouc.com/
[cRO - China: Taren]
ip 118.89.42.108
port 6900
master_version 4
version 1
serverType cRO
serverEncoding GBK
charBlockSize 147
addTableFolders cRO
gameGuard 1
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
pinCode 1
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType

# https://ro.gnjoy.id/
[Indonesia - idRO: Yggdrasil]
ip 202.93.26.198
port 6900
master_version 12
version 2
patchserver wpatch.ragnarok.co.id
patchpath /patch02
serverType idRO_Renewal
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 145
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1

# Renewal
# http://playragnarok.com
[International - iRO: Ymir/Yggdrasil/Valkyrie]
title International - iRO: Thor|Chaos (Renewal-compatible)
ip 128.241.92.36
port 6800
master_version 1
version 18
serverType iRO_Renewal
serverEncoding Western
patchserver ropatch1.gravityus.com
patchpath /patch02
addTableFolders iRO/Renewal;iRO
charBlockSize 147
charDeleteDateType 1
sendCryptKeys 0x38012567, 0x078F087E, 0x71BD2BEA
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1

# http://playragnarok.com
[International - iRO: Sakray]
ip 128.241.92.36
port 6800
master_version 14
version 18
serverType iRO_Sakray
serverEncoding Western
addTableFolders iRO/Sakray;iRO
charBlockSize 147
#sendCryptKeys 0x00000000, 0x00000000, 0x00000000
rankingSystemType 1
blockingPlayerCancel 1
charDeleteDateType 1

# TODO: needs a servertype & table folder
# https://ragnarokonline.gungho.jp/
[Japan - jRO: Verdandi]
ip 61.215.212.13
port 6900
master_version 3
version 10
serverType 7
secureLogin 1
serverEncoding Japanese
addTableFolders Old

# http://roz.gnjoy.com/
[Korea - kRO:Zero]
ip 112.175.128.137
port 6950
master_version 0
version 19
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverType Zero
serverEncoding Korean
charBlockSize 155
gameGuard 1
addTableFolders kRO/Zero;kRO
pinCode 1
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
OTT_ip 112.175.128.135
OTT_port 6900
sendCryptKeys 0x2FC330DD, 0x4D914DE2, 0x01C04E1F
blockingPlayerCancel 1

# http://ro.gnjoy.com/
[Korea - kRO: Sara/Rangidis/Thanatos]
ip 112.175.128.137
port 6900
master_version 0
version 19
serverType kRO_RagexeRE_0
serverEncoding Korean
charBlockSize 112
storageEncryptKey 0x050B6F79,0x0202C179,0x00E20120,0x04FA43E3,0x0179B6C8,0x05973DF2,0x007D8D6B,0x08CB9ED9
gameGuard 1
addTableFolders kRO

# http://ro.gnjoy.com/
[Korea - kRO: Sakray]
ip 112.175.128.138
port 6900
master_version 2
version 29
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverType Sakray
serverEncoding Korean
charBlockSize 155
addTableFolders kRO/Sakray;kRO
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
pinCode 1
gameGuard 0

# https://roextreme.com/msp/main
[Philippines - pRO: Valhalla]
ip 139.99.113.156
port 6900
master_version 15
version 24
serverType pRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
addTableFolders pRO
charBlockSize 144
pinCode 1
charDeleteDateType 1
rankingSystemType 1

# https://roextreme.com/msp/main
[Philippines - pRO: Yggdrasil]
ip 139.99.7.212
port 6900
master_version 15
version 24
serverType pRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
addTableFolders pRO
charBlockSize 144
pinCode 1
charDeleteDateType 1
rankingSystemType 1

# https://ru.4game.com/ro/play/
[Russia - rRO-Renewal]
ip 109.105.140.145
port 6800
master_version 25
version 1
serverType rRO
serverEncoding Russian
addTableFolders rRO
charBlockSize 145
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
blockingPlayerCancel 1
gameGuard 0

# https://ro.gnjoy.com.tw/
[Taiwan - twRO: OldFriend (ChaosFree, IrisFree, LokiFree)]
ip 220.130.113.235
port 6900
master_version 5
version 211
serverType twRO
serverEncoding Big5
charBlockSize 144
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
recvpackets recvpackets.txt
addTableFolders twRO
captcha 0

# https://ro.exe.in.th/
[Thailand - tRO Main server (Norse)]
ip 122.155.11.240
port 6900
master_version 7
version 24
serverType tRO
secureLogin 3
secureLogin_type 0
secureLogin_account 0
patchserver wpatch.ragnarok.in.th
patchpath /patch70
serverEncoding Thai
addTableFolders tRO
charBlockSize 112
gameguard 1

[Localhost]
ip localhost
port 6900
private 1
master_version 1
version 20
serverType kRO_RagexeRE_2009_11_04a
serverEncoding Western
addTableFolders translated/kRO_english;kRO

# this is for XKore 2 client only, it won't affect XKore 2 server
# configure serverType, serverEncoding, charBlockSize according to your server
[XKore 2]
ip localhost
port 6901
serverType
serverEncoding Western
addTableFolders translated/kRO_english;kRO
charBlockSize
clientHash 0123456789abcdef0123456789abcdef

# http://play.ratemyserver.net
[RMS Renewal Test Server]
ip 69.197.167.236
port 6900
version 51
master_version 2
serverType RMS
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2014_10_22b;translated;translated/kRO_english;kRO
#clientHash 6e1d7aae3838cd7aec434cd10ef861e9
clientHash 82d12c914f5ad48fd96fcf7ef4cc492d
pinCode 1

# http://play.ratemyserver.net
[RMS Pre-Re Test Server]
ip 69.197.167.236
port 6901
version 51
master_version 2
serverType RMS
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2014_10_22b;translated;translated/kRO_english;kRO
clientHash 82d12c914f5ad48fd96fcf7ef4cc492d
pinCode 1

####################
# Dead

# http://euro-ro.net/
[Europe - euRO]
dead 1
dead_message euRO was closed on September 30, 2010. There used to be transfers to fRO, check out their website.

# Re:Start
# http://playragnarokrestart.com/
[International - iRO: Re:Start]
dead 1
dead_message iRO Re:Start was merged into iRO Renewal on 11th July 2019. Visit official website for more details.

# Pre-renewal
# http://playragnarok.com
[International - iRO: Loki Classic]
title International - iRO: Classic.Loki
dead 1
dead_message iRO Classic was closed on July 11, 2019. Visit official website for more details.

# http://www.ragnarokeurope.com/
[France - fRO]
title France - fRO (ragnarokeurope.com): Chaos
dead 1
dead_message fRO was closed on 12 of August, 2019. Visit official website for more details.

# https://roextreme.com/mysg/main
[Malaysia - mRO]
dead 1
dead_message mRO was merged into phRO on July, 2019. Visit official website for more details.

# http://ggamerz-ro.com/
[GGamerzRO]
dead 1
dead_message GGamerzRO was closed on sometime in 2019.
###

**Comment by allanpinca** [comment]
can you help me plsss

**Comment by allanpinca** [comment]
[servers.txt](https://github.com/OpenKore/openkore/files/4190138/servers.txt)

**Comment by allanpinca** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/60665740/74309331-4c70b080-4d1f-11ea-8334-6e5cc4582846.jpg)

**Comment by hubertyang88** [comment]
this won't affect botting , I guess it is CD time of use some items ，such as Para Team Mark

**Comment by allanpinca** [comment]
this is for phro server yggdrasil

**Comment by sctnightcore** [comment]
for me.

it's not problem
