### ISSUE TITLE
unknown status

### ISSUE THREAD

**Issue by allanpinca** [OpenKore/openkore#3038]
![Screenshot (3)](https://user-images.githubusercontent.com/60665740/74399654-54d4f400-4dd0-11ea-8eab-67d7c1b48d6b.jpg)

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/74409286-67533a00-4e71-11ea-9cb9-55648c6e4242.png)

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/74409521-d6c92980-4e71-11ea-89b4-12df1a899979.png)

Your post be like

![image](https://user-images.githubusercontent.com/32188494/74409748-5820bc00-4e72-11ea-82e4-6bc33c7e1d9b.png)

The fuck?
- Did you read the FAQ?
- Did you read how to write an issue?
- Care to write some explanation?
- Or did your keyboard went missing?
- Or your brain that is missing?
