### ISSUE TITLE
Packet Parser: Unknown switch: 0A7B

### ISSUE THREAD

**Issue by k3ldon** [OpenKore/openkore#3045]
* **Openkore version git**: 

* **Server**: 
iRO/RT
* **Bug Report **:

Always when i connect 
Packet Parser: Unknown switch: 0A7B

[Feb 16 19:43:47 2020.88] Connecting (128.241.92.197:4501)... [Feb 16 19:43:48 2020.81] connected
[Feb 16 19:43:48 2020.63] You are now in the game
[Feb 16 19:43:48 2020.64] Your Coordinates: 207, 321
[Feb 16 19:43:48 2020.64] You are now: UNKNOWN_STATUS_824
[Feb 16 19:43:48 2020.65] You are now: UNKNOWN_STATUS_993 (Duration: 533.624s)
[Feb 16 19:43:48 2020.65] You are now: UNKNOWN_STATUS_994 (Duration: 1733.624s)
[Feb 16 19:43:48 2020.66] Allowed other player invite to Party
[Feb 16 19:43:48 2020.82] Packet Parser: Unknown switch: 0A7B
[Feb 16 19:43:48 2020.82] Achievement 200005 added.
[Feb 16 19:43:48 2020.84] Achievement 220023 added.
[Feb 16 19:43:48 2020.85] Achievement 230201 added.
[Feb 16 19:43:48 2020.85] Achievement 240000 added.
[Feb 16 19:43:48 2020.86] Achievement 240001 added.
[Feb 16 19:43:48 2020.87] Achievement 500006 added.
[Feb 16 19:43:48 2020.87] Achievement 500008 added.
[Feb 16 19:43:48 2020.88] Achievement 500014 added.
[Feb 16 19:43:48 2020.88] Achievement 500030 added.
[Feb 16 19:43:48 2020.89] Achievement 500043 added.
[Feb 16 19:43:48 2020.90] Achievement 500058 added.
[Feb 16 19:43:48 2020.90] Achievement 500062 added.
[Feb 16 19:43:48 2020.91] Achievement 500063 added.
[Feb 16 19:43:48 2020.92] Achievement 500068 added.
[Feb 16 19:43:48 2020.93] Achievement 500069 added.
[Feb 16 19:43:48 2020.94] Achievement 500086 added.
[Feb 16 19:43:50 2020.65] Calculating random route to: Prontera Field (prt_fild08): 322, 242
[Feb 16 19:43:51 2020.13] Packet Parser: Unknown switch: 0A7B
[Feb 16 19:43:53 2020.13] Packet Parser: Unknown switch: 0A7B
[Feb 16 19:43:55 2020.12] Packet Parser: Unknown switch: 0A7B
[Feb 16 19:43:57 2020.13] Packet Parser: Unknown switch: 0A7B
[Feb 16 19:43:59 2020.10] Packet Parser: Unknown switch: 0A7B
[Feb 16 19:44:01 2020.11] Packet Parser: Unknown switch: 0A7B
[Feb 16 19:44:03 2020.13] Packet Parser: Unknown switch: 0A7B
[Feb 16 19:44:04 2020.22] Disconnected from Map Server, connecting to Account Server in 43 seconds...

* **Summary**:

**Comment by alisonrag** [comment]
#2963 is same issue

**Comment by philamasz** [comment]
iRo RT server experience also this one
