### ISSUE TITLE
auto disconnect

### ISSUE THREAD

**Issue by mugemuge001** [OpenKore/openkore#3048]
why my characters not move always auto disconnect .

Server PRO YGGDRASIL

[Feb 19 09:19:06 2020.38] Received character ID and Map IP from Character Server
[Feb 19 09:19:06 2020.39] ----------Game Info----------
Char ID: DD 21 03 00 (205277)
MAP Name: umbala.gat
MAP IP: 139.99.113.51
MAP Port: 10038
-----------------------------
[Feb 19 09:19:06 2020.40] Closing connection to Character Server
[Feb 19 09:19:06 2020.40] Disconnecting (139.99.120.129:4500)...[Feb 19 09:19:06 2020.40] disconnected
[Feb 19 09:19:06 2020.42] Connecting to Map Server...
[Feb 19 09:19:06 2020.42] Connecting (139.99.113.51:10038)... [Feb 19 09:19:07 2020.16] connected
[Feb 19 09:19:08 2020.39] You are now in the game
[Feb 19 09:19:08 2020.42] Your Coordinates: 99, 153
[Feb 19 09:19:09 2020.46] You are now: Increase amount of EXP acquired (Duration: 377.33s)
[Feb 19 09:19:09 2020.46] You are now: Increase item drop rate two times higher (Duration: 377.33s)
[Feb 19 09:19:09 2020.46] You are now: Get 1.5x Job EXP when hunting monsters (Duration: 980.381s)
[Feb 19 09:19:09 2020.46] You are now: ASPD Reinforce Potion (Duration: 764.083s)
[Feb 19 09:19:09 2020.47] You are now: UNKNOWN_STATUS_824
[Feb 19 09:19:09 2020.47] You are now: UNKNOWN_STATUS_993 (Duration: 477.956s)
[Feb 19 09:19:09 2020.47] You are now: UNKNOWN_STATUS_994 (Duration: 1677.977s)
[Feb 19 09:19:09 2020.48] Allowed other player invite to Party
[Feb 19 09:19:09 2020.48] Other players are not allowed to view your Equipment.
[Feb 19 09:19:26 2020.52] Disconnected from Map Server, connecting to Account Server in 34 seconds...

**Comment by alisonrag** [comment]
because of EAC check #2963 #3045
