### ISSUE TITLE
how can i get server info like ip address new here thanks

### ISSUE THREAD

**Issue by xxchuckzxc** [OpenKore/openkore#3050]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by alisonrag** [comment]
http://openkore.com/index.php/Connectivity_Guide

http://openkore.com/index.php/ServerType

http://openkore.com/index.php/Packet_Length_Extractor
