### ISSUE TITLE
pRO Valkyrie Server Settings

### ISSUE THREAD

**Issue by jem578** [OpenKore/openkore#306]
Well good day btw!

Valkyrie Server Ph is not working at the moment 
Extracted this from the data.grf
I get connection timeout
Fixed my server.txt and changed the IP already I have around 5-10% Knowledge about this and still learning at the moment. Would be great help if you can make it work ? Thanks heaps

<?xml version="1.0" encoding="euc-kr" ?>
<clientinfo>
    <servicetype>philippine</servicetype>
    <servertype>primary</servertype>
	<passwordencrypt />
	<passwordencrypt2 />
    <connection>
        <display>Philippine Ragnarok Online</display>
        <desc>The comeback is real!</desc>
        <address>66.150.188.189</address>
        <port>6900</port>
        <version>20</version>
        <langtype>7</langtype>
        <balloon>Maligayang Pagbabalik!!!</balloon>
	<registrationweb>http://www.playragnarok.ph</registrationweb>
        <aid>
			<admin>20000001</admin>
			<admin>2000001</admin>
			<admin>2000002</admin>
			<admin>2000003</admin>
			<admin>2000004</admin>
			<admin>2000005</admin>
		<loading>
			<image>loading00.jpg</image>
			<image>loading01.jpg</image>
			<image>loading02.jpg</image>
			<image>loading03.jpg</image>
			<image>loading04.jpg</image>
			<image>loading05.jpg</image>
			<image>loading06.jpg</image>
			<image>loading07.jpg</image>
			<image>loading08.jpg</image>
			<image>loading09.jpg</image>
			<image>loading10.jpg</image>
			<image>loading11.jpg</image>
			<image>loading12.jpg</image>
			<image>loading13.jpg</image>
			<image>loading14.jpg</image>
		</loading>
        </aid>
    </connection>
</clientinfo>?

It seems it is quite outdated already or i am doing something wrong and incomplete :(
Also the server is under Gepard Gameguard.
Server Link is Playragnarok.ph (pRO Valkyrie Server)

[Philippines - pRO: Valkyrie]
ip 66.150.188.189
port 6900
master_version 15
version 20
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverType mRO
patchserver wpatch.ragnarok.com.ph
patchpath /patch50
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
serverEncoding Tagalog
charBlockSize 116
gameGuard 1
recvpackets recvpackets.txt
addTableFolders pRO

**Comment by jaybeewat** [comment]
i have the same problem...

**Comment by jaybeewat** [comment]
hahaha no one can help?

**Comment by yvesgeolingo** [comment]
Still no luck. Effin annoying

**Comment by floydfernandez** [comment]
Is there a openkore bot for playragnarok.ph?
