### ISSUE TITLE
roextreme EAC..

### ISSUE THREAD

**Issue by rolfnufable** [OpenKore/openkore#3061]
Hi I have read the faqs..

is it possible to bypass the eac? do you have steps? I wanted to use openkore for yggdrasil server of roextreme but I need to bypass the eac. 

anyone knows how ?

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/75131488-42cb4d80-570e-11ea-8cc4-04bf21163f81.png)
