### ISSUE TITLE
Add New Servers for BOTS

### ISSUE THREAD

**Issue by boom19** [OpenKore/openkore#3065]
Hi there, I think we need new servers to bot on aside from cRO. So I've check some old REstart RO servers and their community is just about to grow. So here they are

<blockquote class="imgur-embed-pub" lang="en" data-id="t2saIa5"><a href="https://imgur.com/t2saIa5">View post on imgur.com</a></blockquote>

<blockquote class="imgur-embed-pub" lang="en" data-id="Uj3ou8W"><a href="https://imgur.com/Uj3ou8W">View post on imgur.com</a></blockquote>

<blockquote class="imgur-embed-pub" lang="en" data-id="gfbiq8f"><a href="https://imgur.com/gfbiq8f">View post on imgur.com</a></blockquote>

Looking forward to your reply guys. I hope one can make a bot for any of it.
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by alisonrag** [comment]
can u download and confirm if one of these server dont use gepard shield?

if dont use gepard there is a chance to use openkore there.

i will leave this issue open for some days before closing

**Comment by boom19** [comment]
downloading the three post as of now. Will check asap hold on!

**Comment by boom19** [comment]
Found one!

The name of the server is 

Asgard Legend  and here it is. No Gepard shield

<blockquote class="imgur-embed-pub" lang="en" data-id="N0zkJCb"><a href="https://imgur.com/N0zkJCb">View post on imgur.com</a></blockquote>

**Comment by sctnightcore** [comment]
it's private server.
u can make bot working .

read openkore wiki

**Comment by boom19** [comment]
> can u download and confirm if one of these server dont use gepard shield?
> 
> if dont use gepard there is a chance to use openkore there.
> 
> i will leave this issue open for some days before closing

this is the only private of all the private servers i see

**Comment by boom19** [comment]
> it's private server.
> u can make bot working .
> 
> read openkore wiki

can you send me a bot for this? they told me its not a private server.  I'm just finding some servers to bot on anyway. hopefully you can share one?
