### ISSUE TITLE
ADD NEW BOTTABLE SERVER and Help for Asgard Legend RO $$

### ISSUE THREAD

**Issue by boom19** [OpenKore/openkore#3069]
Can anyone here make a working bot in this server, it ain't private and players are buying zeny from other players so I think we can make money on this server. It has no GEPARD or FROST SECURITY

Also can you share some of your bottable servers here on this comment?

Hope you could give us a functioning bot for this one guys.

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**:  Asgard Legend

* **Bug Report / Feature Request**: Can you make a working BOT for this?

* **Summary**: I Cannot load mine it says  cannot load server type, because I am not good at making one lol.

**Comment by sctnightcore** [comment]
go forums not github issues.
