### ISSUE TITLE
Please help me how to fix this

### ISSUE THREAD

**Issue by xNoywellx** [OpenKore/openkore#3079]
![Untitled2](https://user-images.githubusercontent.com/18489189/75606285-18bac680-5b26-11ea-9b00-6f054747ee85.jpg)

**Comment by sctnightcore** [comment]
what the fix?

**Comment by Nipodemos** [comment]
just to let some more info:

* The Issue report is not a place to ask for help in configuration and errors
* The right place to do it is in forums, [here is the link](http://forums.openkore.com/)
* before make a topic, you must first try to solve this problem by yourself
* In case you coudn't solve it and decide to make a topic there, please include more information, say what you already tried, say the most details possible

that's all
