### ISSUE TITLE
iRO RT server

### ISSUE THREAD

**Issue by philamasz** [OpenKore/openkore#3080]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Packet Parser: Unknown switch: 0A7B
![zzzzzz](https://user-images.githubusercontent.com/61679132/75659628-411cff00-5ca5-11ea-858c-966c60fe1fa1.PNG)
**:

* **Summary**:

**Comment by sctnightcore** [comment]
packet of EAC 

it hard for do it .

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/75675278-d1693d00-5cc1-11ea-9409-61240657278a.png)
