### ISSUE TITLE
Crash while Botting PLs Help..

### ISSUE THREAD

**Issue by xNoywellx** [OpenKore/openkore#3081]
Pls Help me How To fix This!!.

![Untitled2](https://user-images.githubusercontent.com/18489189/75677657-f318f300-5cc6-11ea-97fe-1ba9bf4bab1d.jpg)

**Comment by Fadreus** [comment]
Troubleshooting method:

- Learn to read.
- Read that error.
- Understand that error.
- Read how to post.
- Dont delete that template.
- Go to church/temple or what ever and repent for your sin as for you have sinned.

Suggestive solution:
- Did you try turn it off and on again?
- Make sure your pc is connected to the internet.
- Try format your computer.
- Buy new computer.
- Dont forget to feed your cat.

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/search?q=%22invalid+arguments%22&unscoped_q=%22invalid+arguments%22

you used  one of the following tasks with wrong arguments:
Sit
Move
Route
Follow

you need to attach your errors.txt

**Comment by xNoywellx** [comment]
thank you sir. For the reply.

**Comment by xNoywellx** [comment]
this the error.txt sir how to Fix this error?. thank you..

OpenKore version what-will-become-2.1
@ai_seq = attack
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2020_03_02
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Invalid arguments.

Stack trace:
Trace begun at src\Task\Route.pm line 82
Task::Route::new('Task::Route', 'actor', 'Actor::You=HASH(0xb92fccc)', 'x', 0, 'y', 25, 'maxDistance', undef, 'maxTime', 4, 'avoidWalls', '', 'distFromGoal', undef, 'pyDistFromGoal', undef, 'notifyUponArrival', undef) called at src\Actor.pm line 779
Actor::route('Actor::You=HASH(0xb92fccc)', undef, 0, 25, 'maxRouteTime', 4, 'attackID', 'M-_^CM-8^F', 'noMapRoute', 1, 'noAvoidWalls', 1) called at src\AI\Attack.pm line 484
AI::Attack::main at src\AI\Attack.pm line 97
AI::Attack::process at src\AI\CoreLogic.pm line 82
AI::CoreLogic::iterate at src\functions.pl line 791
main::mainLoop_initialized at src\functions.pl line 75
main::mainLoop at src\Interface\Wx.pm line 191
Interface::Wx::__ANON__('Interface::Wx=HASH(0x60c2e3c)', 'Wx::TimerEvent=SCALAR(0xbef83f4)') called at src\Interface\Wx.pm line 164
eval {...} at src\Interface\Wx.pm line 164
Interface::Wx::mainLoop('Interface::Wx=HASH(0x60c2e3c)') called at openkore.pl line 97
main::__start at start.pl line 136

Died at this line:
  
* 	unless ($args{actor}->isa('Actor') and $args{x} != 0 and $args{y} != 0) {
  		ArgumentException->throw(error => "Invalid arguments.");
