### ISSUE TITLE
packet tokenizer unknown switch 4753

### ISSUE THREAD

**Issue by yahj112** [OpenKore/openkore#3083]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  latest

* **Server**: Chicken Ragnarok Online https://chicken.playdf.org/?module=main

* **Bug Report / Feature Request**: packet tokenizer unknown switch 4753

* **Summary**: Server Settings
Episode: 13.3+ - El Dicastes
Server Mode: ### Pre-Renewal

![66097949-066a4a00-e5d3-11e9-8c33-15ea195d3f01](https://user-images.githubusercontent.com/42144468/75879533-82a0dc00-5e56-11ea-8707-b102af60c5b1.png)

**Comment by yahj112** [comment]
please help me ..

**Comment by sctnightcore** [comment]
gepard

**Comment by yahj112** [comment]
y

> gepard

what should i do??

**Comment by yahj112** [comment]
> gepard

this cannot be fix??

**Comment by sctnightcore** [comment]
> y
> 
> > gepard
> 
> what should i do??

pray
