### ISSUE TITLE
HELP ME PLS HOW TO FIX THIS ERROR

### ISSUE THREAD

**Issue by xNoywellx** [OpenKore/openkore#3084]
![Untitled2](https://user-images.githubusercontent.com/18489189/75882943-23929580-5e5d-11ea-9221-4fd1f8bf4b39.jpg)

error.txt

OpenKore version what-will-become-2.1
@ai_seq = attack
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2020_03_04
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Invalid arguments.

Stack trace:
Trace begun at src\Task\Route.pm line 82
Task::Route::new('Task::Route', 'actor', 'Actor::You=HASH(0xb2dbc44)', 'x', 0, 'y', 10, 'maxDistance', undef, 'maxTime', 4, 'avoidWalls', '', 'distFromGoal', undef, 'pyDistFromGoal', undef, 'notifyUponArrival', undef) called at src\Actor.pm line 779
Actor::route('Actor::You=HASH(0xb2dbc44)', undef, 0, 10, 'maxRouteTime', 4, 'attackID', 'M-CM-4M-^T^F', 'noMapRoute', 1, 'noAvoidWalls', 1) called at src\AI\Attack.pm line 484
AI::Attack::main at src\AI\Attack.pm line 97
AI::Attack::process at src\AI\CoreLogic.pm line 82
AI::CoreLogic::iterate at src\functions.pl line 793
main::mainLoop_initialized at src\functions.pl line 75
main::mainLoop at src\Interface\Wx.pm line 191
Interface::Wx::__ANON__('Interface::Wx=HASH(0x61eea4c)', 'Wx::TimerEvent=SCALAR(0xb1275d4)') called at src\Interface\Wx.pm line 164
eval {...} at src\Interface\Wx.pm line 164
Interface::Wx::mainLoop('Interface::Wx=HASH(0x61eea4c)') called at openkore.pl line 97
main::__start at start.pl line 136

Died at this line:
  
* 	unless ($args{actor}->isa('Actor') and $args{x} != 0 and $args{y} != 0) {
  		ArgumentException->throw(error => "Invalid arguments.");

**Comment by Fadreus** [comment]
Make more threads...
Im sure you gonna get the fix faster if you post 100 issues a day..

**Comment by sctnightcore** [comment]
I'm not god for know your issues.
