### ISSUE TITLE
Client date is hidding

### ISSUE THREAD

**Issue by robotrono** [OpenKore/openkore#3085]
* **Openkore version git**:  -----
* **Server**:  midgarkingdom.com.mx
* **Summary**:

The client date is hidding so Idk how get that info for try to make a bot with Openkore.

Headers from ragexe:
https://i.imgur.com/reUfyLn.png

Anyone know how to get the client date info from a Ragexe?

WPE is not working for this client, I cant see the process.

Sorry for my bad english is not my first language.

**Comment by Nipodemos** [comment]
hey

this is not the place to ask for help in these kind of things. It is a place to report issues or ask for a new feature.

If you want help with that you can go to openkore forum
