### ISSUE TITLE
About poseidon server

### ISSUE THREAD

**Issue by abudasi2020** [OpenKore/openkore#3092]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: Latest commit cb39bcd

* **Server**: cRO

* **Bug Report / Feature Request**: 

* **Summary**:

I try to use the ragnarok client to connect the poseidon server by Hamachi LAN.
Then the ragnarok client crash as the picture. But my openkore can connect. (Its lan is the same as client )
Can somebody help me to identify the issue? Thanks.
![2020-03-14_113907](https://user-images.githubusercontent.com/62161906/76674414-486bd300-65ea-11ea-8465-ffcacdee3811.png)

**Comment by alisonrag** [comment]
can some of you help this guy?
@mcpchen @hubertyang88

**Comment by mcpchen** [comment]
you network must router（cisco1821，pix-505，huawei2821）client routeing poseidon-server。
config your router two network mask
X.X.X.X（client）routeing y.y.y.y（poseidon-server）



发自我的iPhone


------------------ Original ------------------

**Comment by abudasi2020** [comment]
After I change the port setting of poseidon, the connection is normal.
For a while, the nProtect GamGuard still detect the illegal program.
How to prevent it happen? Thanks.

**Comment by mcpchen** [comment]
use different subnets。



发自我的iPhone


------------------ Original ------------------

**Comment by abudasi2020** [comment]
My setting is as following:
Poseidon ip : 26.198.230.12.
Client ip :  26.190.222.211
Is it right?

**Comment by mcpchen** [comment]
no problem with configuration ip address。
Take a screenshot of your environment。



发自我的iPhone


------------------ Original ------------------

**Comment by abudasi2020** [comment]
![image](https://user-images.githubusercontent.com/62161906/77179535-9198b700-6b03-11ea-8409-e53dcb5e5cb9.png)

**Comment by abudasi2020** [comment]
![image](https://user-images.githubusercontent.com/62161906/77179701-c7d63680-6b03-11ea-9f23-63c33b441fbd.png)

**Comment by mcpchen** [comment]
正在使用发音


Which way does the client link xml？







发自我的iPhone


------------------ Original ------------------

**Comment by mcpchen** [comment]
if using XML links，try changing the host file of the client pc



发自我的iPhone


------------------ Original ------------------

**Comment by abudasi2020** [comment]
This is my setting
![image](https://user-images.githubusercontent.com/62161906/77210153-371b4d00-6b3b-11ea-9747-9f3bc1570857.png)

**Comment by mcpchen** [comment]
save host Run official client。



发自我的iPhone


------------------ Original ------------------

**Comment by mcpchen** [comment]
正在使用发音


Use default port




发自我的iPhone


------------------ Original ------------------

**Comment by abudasi2020** [comment]
I just erased some information from host file. --> so the txt shows *
it is no matter.

**Comment by abudasi2020** [comment]
When I use 6900, the first problem will occur.
There is no restriction on Firewall of both OS.
I don't know why the rag client can't connect to the poseidon server.

**Comment by abudasi2020** [comment]
![image](https://user-images.githubusercontent.com/62161906/77214525-8ae16280-6b4a-11ea-8864-e9b9a354de35.png
Port 6900 seems to be occupied.

**Comment by abudasi2020** [comment]
Port 6900 seems to be occupied.
![image](https://user-images.githubusercontent.com/62161906/77214586-e1e73780-6b4a-11ea-860b-fe2d000eebdd.png)

**Comment by abudasi2020** [comment]
When the port of the query server is 6900, the openkore works very well.
It seems there is some mechanism inside the rag client program or nProtect.
![image](https://user-images.githubusercontent.com/62161906/77224041-d58bca80-6b9c-11ea-885d-e582fc170a42.png)
