### ISSUE TITLE
can't extract recvpackets

### ISSUE THREAD

**Issue by Sensuii** [OpenKore/openkore#3093]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: fb56fd5

* **Server**: private server

* **Bug Report / Feature Request**: 

* **Summary**:I can't extract the recvpackets from a private server

by peek i got this error https://uploaddeimagens.com.br/imagens/screenshot_1-png-79263148-e0a2-4238-9094-1c0f3afa333b
by openkore-packet-length-extractor https://uploaddeimagens.com.br/imagens/screenshot_2-png-2cb1d50c-e9cc-4656-bfe2-f492eb988248
and ro tools https://uploaddeimagens.com.br/imagens/screenshot_3-png-bbd7b227-1012-40ce-8fb5-a5d8ac86fef6
and by another peek(by yommy and neo) https://uploaddeimagens.com.br/imagens/screenshot_1-png-9e7d8d9f-5012-4728-9e2a-cc040410b405

**Comment by Sensuii** [comment]
worked,thx

**Comment by Cazeiga** [comment]
> worked,thx

Hi bro, could you tell me how did u to solve this error... i am in the same condition, trying to extract the recvpackets, till now i already tryed(Peek, openkore-packet-length-extractor and by another peek(by yommy and neo)...

**Comment by Sensuii** [comment]
> > worked,thx
> 
> Hi bro, could you tell me how did u to solve this error... i am in the same condition, trying to extract the recvpackets, till now i already tryed(Peek, openkore-packet-length-extractor and by another peek(by yommy and neo)...

sorry for delay,if you still need help,go to folder table/kRO , open the folder corresponding to your server date(find it with peviewer,targeting server exe) and use recvpackets inside the folder as the recvpackets of the server
