### ISSUE TITLE
BOT bRO - How to buy?

### ISSUE THREAD

**Issue by bobledgamer** [OpenKore/openkore#3094]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: bRO

* **Bug Report / Feature Request**: Didn't find how to make work or how to buy bot.

* **Summary**: Hello guys, I was searching how to buy the bot, but I didn't found it.
I saw that @lututui @Henrybk and @alisonrag  are the supporter, so can you help me please?
I tried to use the bot but it didn't work.

**Comment by Fadreus** [comment]
> I saw that

Too bad you didn't see that asking question should go through IRC/Forum, not github issue.
