### ISSUE TITLE
CDClient.dll

### ISSUE THREAD

**Issue by robotrono** [OpenKore/openkore#3101]
Server: http://104.248.237.34/
Ragexe: 20180620
Version: 55
Master version: 1
Last version openkore.
Windows 10.

Is there a bypass to be able to inject the client with CDClient.dll protect?

**Comment by sctnightcore** [comment]
if client > 2013.

xkore1 dont work . ty

**Comment by alisonrag** [comment]
#1861 is already opened

**Comment by robotrono** [comment]
@alisonrag thx I will see
