### ISSUE TITLE
iRo not detecting char ID on server

### ISSUE THREAD

**Issue by uplight** [OpenKore/openkore#3102]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**:  iRO

* **Bug Report / Feature Request**:
openkore connects to account but not detecting existing chars

Slot: 0 char:0

* **Summary**:
If some one working on iRO fixes?

**Comment by alisonrag** [comment]
charBlockSize changed to 155, but iRO have EAC shield
#2963
