### ISSUE TITLE
 charBlockSize 155 stops kore, cannot login to IRO

### ISSUE THREAD

**Issue by jojo801** [OpenKore/openkore#3103]
This is what I get and then kore doesn't do anything more

-----------------------------
Closing connection to Character Server
Disconnecting (128.241.92.43:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.43:4503)... connected
Timeout on Map Server, connecting to Account Server...

The only change I have made is in servers.txt
 charBlockSize 155

I have the latest updated kore. Please help.

**Comment by sctnightcore** [comment]
iRO use EAC.

openkore dont work with it.
