### ISSUE TITLE
Error when try to use peek viewer

### ISSUE THREAD

**Issue by Cryptologism** [OpenKore/openkore#3107]
Hello everyone, recently ive encountered an error while trying to view the exe of xXxRagnarok. It show error like in the picture. Anyone can help me about this and its been a long time did not try to bot tou, might be im missing something.

*Edit*
Someone said that this was because of the encryption exe. Are those true? And is there any way to do the decryption?

https://ibb.co/9VfknWp

**Comment by alisonrag** [comment]
this is a peek issue, not related to openkore.
if peek cant get the packet means some of the folowing options:
1 - client is packet/encrypted
2 - the server owner patched the peek detection
http://nemo.herc.ws/patches/HidePacketsFromPeek/
3 - peek dont support the client
