### ISSUE TITLE
Packet tokenizer: Unknown switch 4753

### ISSUE THREAD

**Issue by ferrariako** [OpenKore/openkore#3108]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

![image](https://user-images.githubusercontent.com/63333409/78746771-523ee700-799a-11ea-9f44-aa9dd5e47152.png)

server config below
![image](https://user-images.githubusercontent.com/63333409/78746861-85817600-799a-11ea-9d7d-63fc34dd2ecc.png)

URL
https://dark-ro.com/

Game is running gepard 3.0

Any help is welcome

**Comment by sctnightcore** [comment]
openkore dont work with gepard :)

**Comment by baratie11** [comment]
Server: Heroes of Valhalla
ip singapore proxy: 51.79.144.3
ip LA proxy:149.248.20.33

server dl link: https://playvalhalla.net/?module=main&action=downloads
![recv](https://user-images.githubusercontent.com/67263099/85268853-a93c5e80-b4a9-11ea-9f67-dd0a0d570759.png)
