### ISSUE TITLE
Monster Search in Town.

### ISSUE THREAD

**Issue by rlsbautista** [OpenKore/openkore#3109]
Hi Team,

I would just like to ask if it's possible for bot to do random walk or teleport in searching for monster in town? I've tried my best my bot is still idle on towns. Please help me.

Thank you.

I look forward to hear from you.

Regards,

Rlsb

**Comment by alisonrag** [comment]
http://openkore.com/index.php/Route_randomWalk_inTown

or remove city from cities.txt
