### ISSUE TITLE
[Philippines - pRO: Yggdrasil]

### ISSUE THREAD

**Issue by b0y3t** [OpenKore/openkore#3110]
Hi, alisonrag,

Would like to seek your assistance on the uploaded openkore "alisonrag committed 8 days ago" 
It already connect in the game but it will disconnected after 15 seconds or when i used commands like "eq" or move moc_fild01.

# https://roextreme.com/msp/main
[Philippines - pRO: Yggdrasil]

I guess the revcpacket is the problem why it is disconnecting.
Can you help me at this one

**Comment by sctnightcore** [comment]
it just update only packet not bypass.

**Comment by b0y3t** [comment]
So how can i resolved the issue by disconnecting on the map. 

Thanks for the usual support

**Comment by b0y3t** [comment]
@alisonrag  Hi Sir, Seeking your assistance on this please. Thanks for the usual support and cooperation
