### ISSUE TITLE
Try to fix randome walk after kill

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3111]
## ------------------ Openkore Issues Template ------------------
 if there are multi monsters in sight , after each kill , bot will randomly walk for 1 or 2 grid ,it looks not like a human at all.
add `AI::clear("route");`  to
 src\AI\Attack.pm
```
sub finishAttacking {
        ....
	+AI::clear("route");
	Plugins::callHook('attack_end', {ID => $ID})
}
```
the move looks better , but this will cancel current destination of walk , it is bad for planLockMapWalk .
do you guys have better idea?

* **Openkore version git**: 
Latest

* **Server**: 
All server
* **Bug Report / Feature Request**:
Bug Report
* **Summary**:
Help needed!

**Comment by hubertyang88** [comment]
Well , it seems there is no fix ,  if don't use planLockMapWalk , AI::clear("route"); is good enough

**Comment by c4c1n6kr3m1** [comment]
years and years ago, i said : after target died, don't fall back to "route".

**Comment by hubertyang88** [comment]
I have thought no one care about this bug 
can I add a new key to AI ?
like below
AI.pm
```
block_route

sub block_route {
    return 1;
}
```


in corelogic.pm

```
sub processAutoAttack {
    .......
    AI::clear('block_route');
    Benchmark::end("ai_autoAttack") if DEBUG;
}
```

in attack.pm
```
sub process {
    ......
    if (AI::action eq "attack") {
        my $ID = $args->{ID};
        if (targetGone()) {
            finishAttacking();
            AI::queue('block_route');
        } elsif (shouldGiveUp()) {
            giveUp();
            AI::queue('block_route');
        } else {
            if (timeOut($args->{attackMainTimeout}, 0.1)) {
                $args->{attackMainTimeout} = time;
                main();
            }
        }
    }
    .........
}
```
block_route is set by attack done , and reset by processAutoAttack
force processAutoAttack run once after a kil

**Comment by hubertyang88** [comment]
Actually ， there are something more need to check after a kill before route to new positon
1, CD for skill , bot should not route if pre_set skill is in cooling down.
2, Hp , for some class like mage ,  should heal self before route.
3, follower(if exist) missing , should wait for pre_set time if follower not in sight.
it just some thought , AI might need a new key

**Comment by c4c1n6kr3m1** [comment]
if u don't know what your doing, try change config take/gather auto to 1, and mon_control auto attack 2

**Comment by hubertyang88** [comment]
```
in corelogic.pm

sub processAutoAttack {
    .......
    if ((AI::isIdle || AI::is(qw/route follow sitAuto take items_gather items_take block_route/) || (AI::action eq "mapRoute" && AI::args->{stage} eq 'Getting Map Solution'))
    ........
            } else {
            AI::clear("block_route");
            $timeout{'ai_attack_auto'}{'time'} = time;
            
        }
    }
    
    Benchmark::end("ai_autoAttack") if DEBUG;
    
}

in AI.pm

sub ai_items_take {
    my ($x1, $y1, $x2, $y2) = @_;
    my %args;
    $args{pos}{x} = $x1;
    $args{pos}{y} = $y1;
    $args{pos_to}{x} = $x2;
    $args{pos_to}{y} = $y2;
    $args{ai_items_take_end}{time} = time;
    $args{ai_items_take_end}{timeout} = $timeout{ai_items_take_end}{timeout};
    $args{ai_items_take_start}{time} = time;
    $args{ai_items_take_start}{timeout} = $timeout{ai_items_take_start}{timeout};
    $args{ai_items_take_delay}{timeout} = $timeout{ai_items_take_delay}{timeout};
    AI::queue('block_route');
    AI::queue("items_take", \%args);
}
```
add 'block_route'  like this , it seems fix the random walk after kill
Well , if anyone is interested.
