### ISSUE TITLE
Concern about openkore group.

### ISSUE THREAD

**Issue by youmarky** [OpenKore/openkore#3122]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

I know it is something to ask for all hardworking coders and developer here because you've done so many things on this application, kudos to our developer and contributors. I want to raise an issue regarding openkore since its only running now on cRO, and the rest is has a lot to do, for example like me i want to create an account on cRO, creating an account needs mobile no. So its hard to get an account for us who lives in US or some part of the world, we really want to play and bot when we are away. But unfortunately we cant, i tried the tutorial for getting connected to a private servers but a lot of them had anti cheat programs and as for me who dont know how to code or configure im only relying and hoping that someone provides here a working server even if its private. I hope all contributors and developers try to consider making alternative to bot like on private servers or some other Ragnarok Online. I know somebody will reply to me that make your own or some thing like that, well i must say not all of us born techy please try to be nice to me. :) if you have working server pls provide the details and client to download. :) thank you very much guys. And thank you all contributors and developers who are ceaselessly working on openkore. Thanks!

**Comment by alisonrag** [comment]
https://forums.openkore.com/viewtopic.php?f=9&t=211785
http://ggamerz-ro.com/?module=account&action=create
