### ISSUE TITLE
Timeout on Map Server (Private server)

### ISSUE THREAD

**Issue by dawnvillain** [OpenKore/openkore#3124]
Openkore version git: 2020_04_29
Server: Miro (private server)
site: http://www.miragnarokonline.ml/

Bug Report / Feature Request: "Timeout on Map Server"

Summary: bot able to login to account server and character server but then gets disconnected in map server. I'm also experiencing the same issues with non-protected private servers. Is there a general guide on fixing this error?

server:
ip 51.79.159.200
port 6900
master_version 55
version 1
serverType kRO_RagexeRE_2017_06_14b
serverEncoding Western
addTableFolders kRO/RagexeRE_2017_06_14b;translated/kRO_english;kRO
charBlockSize 155
private 1
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
gameGuard 0

recvpackets:
https://pastebin.com/zcVMfJDr

![screenshot](https://i.imgur.com/KKEIyRL.png)

I am able to connect but it keeps freezing on Map Server and then it disconnects, how to fix this issue?

**Comment by alisonrag** [comment]
have u checked the cryptkeys?

**Comment by dawnvillain** [comment]
> have u checked the cryptkeys?

Can you give me a program that can get it? PEEK not working for me.

**Comment by sumnayak** [comment]
I'm having this issue too, now #3129 
Has anyone found out how to fix this yet?

**Comment by dawnvillain** [comment]
I feel like there's no new software that can get the cryptkeys for renewal clients.
sadly, its what we need -_-

**Comment by alisonrag** [comment]
website changed?

**Comment by centrix5** [comment]
Received characters from Character Server
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: B0 E5 0E 00 (976304)
MAP Name: prontera.gat
MAP IP: 23.250.112.34
MAP Port: 8122
-----------------------------
Closing connection to Character Server
Disconnecting (23.250.112.34:7124)...disconnected
Connecting to Map Server...
Connecting (23.250.112.34:8122)... connected
------------------------------- Character List --------------------------------
Slot 7: TCG Hunter1012266 (Swordsman, Boy, level 260/43, einbroch)
Slot 8: ShoeMart976304 (Creator, Boy, level 260/104, prontera)
-------------------------------------------------------------------------------
Timeout on Map Server, connecting to Account Server...



**SAME ERROR HERE**

**Comment by dawnvillain** [comment]
> website changed?

Yes!
New website is: http://shot-ro.ga/
new IP is 51.79.159.200

any chance we can bot on this server?

**Comment by alisonrag** [comment]
> > website changed?
> 
> Yes!
> New website is: http://shot-ro.ga/
> new IP is 51.79.159.200
> 
> any chance we can bot on this server?

the ragexe is edited e maybe protected with some kind of packer, i will try to find the function, but i dont have so much hope

**Comment by centrix5** [comment]
im trying this server....
# https://www.vanserver.com

ip 23.250.112.34
port 7101
version 35
master_version 1
serverType kRO_RagexeRE_2015_10_29a
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2015_10_29a;translated;translated/kRO_english;kRO
clientHash C6102514058D96473A2D16CC535E082A250863002300000009

**Comment by alisonrag** [comment]
> im trying this server....
> 
> ```
> # https://www.vanserver.com
> 
> ip 23.250.112.34
> port 7101
> version 35
> master_version 1
> serverType kRO_RagexeRE_2015_10_29a
> serverEncoding Western
> charBlockSize 147
> addTableFolders kRO/RagexeRE_2015_10_29a;translated;translated/kRO_english;kRO
> clientHash C6102514058D96473A2D16CC535E082A250863002300000009
> ```

I already answered your question when you asked elsewhere

please pay attention to your notifications and do not pollute topics not related to your topic

https://github.com/OpenKore/openkore/issues/3151#issuecomment-638886598

**Comment by alisonrag** [comment]
Info:
```
[Shot-RO]
ip 51.79.159.200
port 6900
version 55
master_version 2
serverType kRO_RagexeRE_2018_06_20e
serverEncoding Western
charBlockSize 155
addTableFolders kRO/RagexeRE_2018_06_21a;iRO;iRO/Renewal;
private 1
gameGuard 0
pinCode 1
```
