### ISSUE TITLE
identify object error (old client about 2013)

### ISSUE THREAD

**Issue by sianromantic** [OpenKore/openkore#3128]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2020_05_09

* **Server**: private (server like SeAr)

* **serverType**: kRO_RagexeRE_2013_08_07a

* **Bug Report / Feature Request**: Can't correct identify object

* **Summary**: Openkore will recognize monsters(player) as NPC,  and can't correct remove NPC object

![monster NPC](https://user-images.githubusercontent.com/37154438/81471850-a0a80580-9226-11ea-8cc9-c8fba26bfa6b.png)
i think is packet(0857) issue..but i don't know how to fix it

**Comment by c4c1n6kr3m1** [comment]
so , you do believe someone has psychic power, can read your mind or understand what happened on your computer without doing nothing, don't you?
