### ISSUE TITLE
Unreachable map server，help~

### ISSUE THREAD

**Issue by polme32** [OpenKore/openkore#3134]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
OpenKore what-will-become-2.1 ( version ctime:2020_05_18 )
* **Server**: 
serverType kRO_RagexeRE_2018_06_21a
* **Bug Report / Feature Request**:
Unreachable map server
* **Summary**:

[初心RO]
ip 49.234.203.241
private 1
port 6917
master_version 4
version 56
serverType kRO_RagexeRE_2018_06_21a
serverEncoding GBK
charBlockSize 155
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, x04FA43E3, 0x0179B6C8, 0x05973DF2, 
0x07D8D6B, 0x08CB9ED9
PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 
0x07D8D6B, 0x08CB9ED9
recvpackets recvpackets.txt
sendCryptKeys 0x347D68D0, 0x7B4A199D, 0x2C705320

Key obtained from peek
How do I change to log in to the server normally
Post the test account testt    123123

**Comment by alisonrag** [comment]
no update from the owner
