### ISSUE TITLE
Position lag bug

### ISSUE THREAD

**Issue by Henrybk** [OpenKore/openkore#3142]
* **Openkore version git**: latest
* **Server**:  RMS Renewal
* **Bug Report / Feature Request**: Bug Report

* **Summary**:
In all rAthena servers at least (I don't know if this is the official behaviour or hercules's) when a monster takes damage while moving its movement will stop completely, but the server (at least rAthena) won't send any information about it, only that the mob took damage.
This has been reported a few times in rAthena's forum and github (https://rathena.org/board/tracker/issue-7460-hitlocking-and-position-lag/, https://github.com/rathena/rathena/issues/1402).

This causes a position lag on openkore.

Example: Magmaring starts moving from 100:100 to 110:100, half a second after it started moving you hit it, the mob was hit while it was at cell 103:100 (midway movement), in the client and server-side the Magmaring just stops moving and stays at cell 103:100 where it was hit, but "actor_movement_interrupted" is never sent by the server, so openkore still thinks the mob is walking to 110:100.

Video showing the movement stop and no packet received: https://www.youtube.com/watch?v=TLQYBLw-vYs&feature=youtu.be

Proposed solution: Add a config.txt of servers.txt key to set if "damage taken""packets should reset the actor movement.

What do you guys think? This is a server-side bug but it impacts openkore.

**Comment by c4c1n6kr3m1** [comment]
so,on server side, monster pos 100,100 or 103,100?
if we reset actor movement, than bot recognize monster at 100,100 ?

**Comment by alisonrag** [comment]
fixed at #2871
