### ISSUE TITLE
tRO New Project

### ISSUE THREAD

**Issue by RobotTZ** [OpenKore/openkore#3143]
tRO New Project Anyone interested in exchanging experience

**Comment by spiritxyz** [comment]
![จับภาพ](https://user-images.githubusercontent.com/66155787/83321219-3eb44c00-a278-11ea-89f4-fe38f31e1edc.PNG)

**Comment by isardryu** [comment]
NICE

**Comment by autkub101** [comment]
ใครเป็นบ้าง บอท ยกเลิกการติดต่อกับ Map Server แล้ว, ทำการเชื่อมต่อกับ Account Server ใน 30 วินาที...
หรือมันใช้ได้แล้ว

**Comment by prasert1011** [comment]
> ใครเป็นบ้าง บอท ยกเลิกการติดต่อกับ Map Server แล้ว, ทำการเชื่อมต่อกับ Account Server ใน 30 วินาที...
> หรือมันใช้ได้แล้ว

Find bypass eac.

**Comment by ksuebkaew** [comment]
is there anyone can explain how the EAC works?, maybe we can figure it out how to bypass it

**Comment by xyanide-fedx0** [comment]
> ใครเป็นบ้าง บอท ยกเลิกการติดต่อกับ Map Server แล้ว, ทำการเชื่อมต่อกับ Account Server ใน 30 วินาที...
> หรือมันใช้ได้แล้ว

[Read this](https://github.com/OpenKore/openkore/issues/2963#issuecomment-547957947)

**Comment by autkub101** [comment]
> > ใครเป็นบ้าง บอท ยกเลิกการติดต่อกับ Map Server แล้ว, ทำการเชื่อมต่อกับ Account Server ใน 30 วินาที...
> > หรือมันใช้ได้แล้ว
> 
> [Read this](https://github.com/OpenKore/openkore/issues/2963#issuecomment-547957947)
> OpenKore don't suport encrypt packet from EAC
> If you bypass EAC . . . you can send real packet to server
> but server will say what the fuck this packet and kick your ass

thx you

**Comment by jaturapat1** [comment]
ขอรายละเอียดเพิ่มเติมหน่อยคับ

**Comment by vuxmoe** [comment]
have discord ??

**Comment by alisonrag** [comment]
use https://www.github.com/tRO-update
EAC discussion:
#2963
