### ISSUE TITLE
xkore 3 issue(not work)

### ISSUE THREAD

**Issue by sianromantic** [OpenKore/openkore#3148]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2020_05_31

* **Server**: private server

* **Bug Report / Feature Request**: xkore 3 not work

* **Summary**:

![aaaadd](https://user-images.githubusercontent.com/37154438/83349570-726e9f00-a368-11ea-8203-cee574eed80c.PNG)

if i change XKore mode to 0, then it work perfect.
but if i change XKore mode to 3, then control panel show that message(image)

red line means Client crash time.
(client crash without error report, just disappeared in an instant)

(i only type my account password, and press enter..)
(i even can't enter to choose character)

**Comment by alisonrag** [comment]
server info?

also we need a debug:

go to config and set:
debugPacket_received 2

**Comment by ThememoriesIII** [comment]
thank you very much alisonrag for tro update . but i have problem to. i use remote proxy send game packet to openkore i have 3 ip gamelogin character and map. remote all ip to openkore or gamelogin only?

**Comment by alisonrag** [comment]
@sianromantic can u provide more info?

**Comment by sianromantic** [comment]
@alisonrag 
<details>
  <summary>image for debugPacket_received 2</summary>

![11111](https://user-images.githubusercontent.com/37154438/84001779-e842be00-a999-11ea-8651-7764b7184838.PNG)

</details>
<details>
<summary>private server info(full game)</summary>

[https://drive.google.com/file/d/1Blv2_wBWSpXaHBRYJIqK7TUy94TltPNA/view](url)

</details>

**Comment by sianromantic** [comment]
@alisonrag 
<details>
  <summary>image for debugPacket_received 2</summary>

![aaq](https://user-images.githubusercontent.com/37154438/84002277-c0078f00-a99a-11ea-8306-9b06ea84eb16.PNG)


</details>
<details>
<summary>private server info(full game)</summary>

[download link (google drive)](https://drive.google.com/file/d/1Blv2_wBWSpXaHBRYJIqK7TUy94TltPNA/view)

</details>

**Comment by alisonrag** [comment]
there is another mirror? google is dropping my connection after 1gb

about dbi:

use perl 5.12 32 bits, use cpan or ppm and install the module, then in plugin header:

```
use lib 'C:/strawberry/perl/lib';
use lib 'C:/strawberry/perl/site/lib';
use lib 'C:/strawberry/perl/vendor/lib';
```

change the path to your perl folder

**Comment by sianromantic** [comment]
> there is another mirror? google is dropping my connection after 1gb
> 
> about dbi:
> 
> use perl 5.12 32 bits, use cpan or ppm and install the module, then in plugin header:
> 
> ```
> use lib 'C:/strawberry/perl/lib';
> use lib 'C:/strawberry/perl/site/lib';
> use lib 'C:/strawberry/perl/vendor/lib';
> ```
> 
> change the path to your perl folder

<details>
<summary>private server info(full game) add new download link</summary>

account:mirror
password:2222
[download link (google drive)](https://drive.google.com/file/d/1Blv2_wBWSpXaHBRYJIqK7TUy94TltPNA/view)
[download link (mega)](https://mega.nz/file/J64QxQqC#Bxc3ySKG_Org0tVoOo02LLq7KHM3JzTsfJy9tQNPRDc)

</details>
<details>
<summary>about off-topic</summary>

`thank for your tip, now it work.`

</details>

**Comment by alisonrag** [comment]
how do you are redirercting the client connection to openkore, tryied to use/account command and client dont start

**Comment by sianromantic** [comment]
> how do you are redirercting the client connection to openkore, tryied to use/account command and client dont start
@alisonrag 

<details>
<summary>method</summary>

1. create a.xml(langtype 4) file at Ragnarok folder path ( /data/a.xml )
2. jump to path ( / ) , and create .cmd files then type in

`start Glimmer.exe /account:a.xml`

that method can open client and redirect to openkore

</details>

**Comment by alisonrag** [comment]
using #3189 and:
```
[Glimmer]
ip 193.42.42.18
port 9002
version 55
master_version 5
serverType kRO_RagexeRE_2018_06_20e
serverEncoding Western
charBlockSize 155
addTableFolders kRO/RagexeRE_2018_06_21a;iRO;iRO/Renewal;
private 1
gameGuard 0
pinCode 0
clientHash 27481136367432032F951F0BED86DFF9
```

**Comment by sianromantic** [comment]
> 使用[＃3189](https://github.com/OpenKore/openkore/pull/3189)和：
> 
> ```
> [Glimmer]
> ip 193.42.42.18
> port 9002
> version 55
> master_version 5
> serverType kRO_RagexeRE_2018_06_20e
> serverEncoding Western
> charBlockSize 155
> addTableFolders kRO/RagexeRE_2018_06_21a;iRO;iRO/Renewal;
> private 1
> gameGuard 0
> pinCode 0
> clientHash 27481136367432032F951F0BED86DFF9
> ```

commit #3189 already fix my issue.
thank for your hard work
