### ISSUE TITLE
UKNOWN PACKET

### ISSUE THREAD

**Issue by centrix5** [OpenKore/openkore#3151]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 
+RO
* **Bug Report / Feature Request**:

* **Summary**:
Screenshot Below
![error](https://user-images.githubusercontent.com/66415142/83740913-7f6be680-a625-11ea-9673-bbae515a93de.png)
[errors.txt](https://github.com/OpenKore/openkore/files/4729095/errors.txt)

[errors.txt](https://github.com/OpenKore/openkore/files/4729092/errors.txt)

**Comment by ya4ept** [comment]
see https://openkore.com/index.php/Packet_Length_Extractor

**Comment by alisonrag** [comment]
```# http://vanserver.com
[VanRO: VanRO Classic]
ip 23.250.112.34
port 8500
version 51
master_version 2
serverType kRO_RagexeRE_2015_10_29a
serverEncoding Western
charBlockSize 147
addTableFolders vanRO;iRO/official;iRO
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
clientHash F3317EC20A442D9D8014D67EA4158254
sendCryptKeys 0x1CA773E0, 0x0D6CDA0F, 0x64D666C9
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1
secureLogin 0
secureLogin_type 0
secureLogin_account 0
gameGuard 0```
