### ISSUE TITLE
tRo amounts of items not update

### ISSUE THREAD

**Issue by oDestroyeRo** [OpenKore/openkore#3153]
* **Openkore version git**: 
"tRo-update"

* **Server**: 
tRo

* **Bug Report / Feature Request**:
When use item, item not reduce but if I pick up the item, it still increases with not update the amount.

![Capture](https://user-images.githubusercontent.com/13649162/83877155-9ff28880-a76c-11ea-8d93-8a2c52f85087.PNG)
![Capture2](https://user-images.githubusercontent.com/13649162/83877162-a123b580-a76c-11ea-97a2-6af0ab4085b1.PNG)

**Comment by Numodify** [comment]
oDestroyeRo   ,  Can you share how to use bot in tRO GGT? The server alway map disconnected 45 secound? Could you help me?

**Comment by ThememoriesIII** [comment]
alisonrag update tRO bot 2 day ago. 
 you can find source in branch tag name "[tRO-update](https://github.com/OpenKore/openkore/tree/tRO-update)"
openkore working to login. but i don't know why openkore stuck in server select page and ip connect not change to character page if i select a sever in select page.

**Comment by oDestroyeRo** [comment]
> branch

I used this branch but I got this problem

**Comment by oDestroyeRo** [comment]
> alisonrag update tRO bot 2 day ago.
> you can find source in branch tag name "[tRO-update](https://github.com/OpenKore/openkore/tree/tRO-update)"
> openkore working to login. but i don't know why openkore stuck in server select page and ip connect not change to character page if i select a sever in select page.

I got a problem with this branch.

**Comment by roxaslock** [comment]
Same Issue Still stuck on this problem

**Comment by ThememoriesIII** [comment]
yes me to ,openkroe in proxymode game stuck in server select page.
but openkore is working if me change xkore 3 to 1 and open roclient without eac if you make step form me you stuck in mapserver and not move. 
i open debug in config.txt and click mouse in game very long time to see roclient send packet to server and i see character_move and packet lenght is change, character_move 035F change  to 000D and lenght 5 change to 13.
in picture you can see mouse click in game and send 000D to server and receive charactor move.
i want to change it in network/tro.pm but i dont understand a3 in  ['character_move', 'a3', [qw(coords)]] a is flag? and 3 is leght?.
![image](https://user-images.githubusercontent.com/20499517/83933951-3eb3cf00-a7d7-11ea-914a-7fc8680a4812.png)

**Comment by i3ankboy** [comment]
> yes me to ,openkroe in proxymode game stuck in server select page.
> but openkore is working if me change xkore 3 to 1 and open roclient without eac if you make step form me you stuck in mapserver and not move.
> i open debug in config.txt and click mouse in game very long time to see roclient send packet to server and i see character_move and packet lenght is change, character_move 035F change to 000D and lenght 5 change to 13.
> in picture you can see mouse click in game and send 000D to server and receive charactor move.
> i want to change it in network/tro.pm but i dont understand a3 in ['character_move', 'a3', [qw(coords)]] a is flag? and 3 is lenght?.
> ![image](https://user-images.githubusercontent.com/20499517/83933951-3eb3cf00-a7d7-11ea-914a-7fc8680a4812.png)
> 
> normal game and wireshark
> ![image](https://user-images.githubusercontent.com/20499517/83934955-c7823900-a7de-11ea-977c-aa0c8833484e.png)

Any send package in map server is encrypted by EAC. That why you got 000D and difference package length.

**Comment by sctnightcore** [comment]
@i3ankboy  @ThememoriesIII  let's open new issues about it .
