### ISSUE TITLE
Timeout on mapserver and character don't move 

### ISSUE THREAD

**Issue by ThememoriesIII** [OpenKore/openkore#3158]
1.Openkroe in proxymode game stuck in server select page.
2.I change xkore 3 to 1 and open ro client without eac openkore is working but stuck in mapserver and character dont move and after sec mapserver timeout disconnect.
3.I open debug in config.txt and first step i open ro client and login to game second step i open openkore 
4.I click mouse in game very long time to see roclient send packet to server and i see character_move and packet lenght is change, character_move 035F change to 000D and lenght 5 change to 13.
![image](https://user-images.githubusercontent.com/20499517/83936499-82fe9980-a7ee-11ea-86d3-8edc29d22ede.png)
4.I want to change it in network/send/tro.pm but i dont understand a3 in ['character_move', 'a3', [qw(coords)]] a is flag? and 3 is leght?.

**Comment by sctnightcore** [comment]
if eac. 

it need enc packet .

**Comment by ThememoriesIII** [comment]
thank you for explain me, a eac enc all packet and send to mapserver yes right i understand it now, but i dont understand why i play a game without eac a few hour why game not disconnect?,

**Comment by alisonrag** [comment]
updated account server parse, xkore 3 should work until map server, 
about this issue is related to #2963
