### ISSUE TITLE
ask about perl type

### ISSUE THREAD

**Issue by topkung1** [OpenKore/openkore#3160]
## ------------------ Openkore Issues Template ------------------
* **Openkore version git**: 
lastest
* **Server**: 
-
* **Bug Report / Feature Request**:
curiousity
* **Summary**:

Why openkore usually uses "a4" unpack type for uint32 type? Why not "I" or more specific type?
just curious

thank you

**Comment by sctnightcore** [comment]
what packet id?

**Comment by topkung1** [comment]
> what packet id?

most of openkore structures for unpacked their incoming packets

**Comment by topkung1** [comment]
as I saw here https://perldoc.perl.org/functions/pack.html

UInt32 should be "I" but openkore uses "a4" instead of "I"

**Comment by sctnightcore** [comment]
sometime we dont need to paser all data .

a is best way for skip

**Comment by alisonrag** [comment]
old design pattern used to save resources.

now that computers have processing power nobody has updated
