### ISSUE TITLE
how to fix Tro?

### ISSUE THREAD

**Issue by jaturapat1** [OpenKore/openkore#3163]
![Untitled](https://user-images.githubusercontent.com/20749732/84100421-0bbb4680-aa36-11ea-9de7-f15acbd9599a.png)

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/tree/tRO-update

#2963

**Comment by jaturapat1** [comment]
![Untitled](https://user-images.githubusercontent.com/20749732/84104498-ffd48200-aa3f-11ea-9368-c50a4967aa76.png)
not try.
