### ISSUE TITLE
InInventory does not trigger

### ISSUE THREAD

**Issue by oDestroyeRo** [OpenKore/openkore#3164]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  master

* **Server**:  tRo

* **Bug Report / Feature Request**: Bug Report

* **Summary**: "Ininventory" in eventMacro does not trigger when run opk for a longtime. If I reload eventMacros it will work again. "InInventoryID" also have the same problem

automacro getYellowPotion {
	BaseLevel > 100
	InInventory "Yellow Potion" <= 10
	overrideAI 1
        exclusive 1
	call {
		do is Kafra Bell
		pause 1
		do storage get Yellow Potion 40
		do storage close
	}
}

**Comment by alisonrag** [comment]
#1215
Check before of open a new issue
