### ISSUE TITLE
how to bot on VPS

### ISSUE THREAD

**Issue by toffiizz** [OpenKore/openkore#3165]
![1](https://user-images.githubusercontent.com/66774403/84365926-5ab2d880-abfc-11ea-80ce-3102c5cbf96c.jpg)

**Comment by sctnightcore** [comment]
yes no ok ty

**Comment by toffiizz** [comment]
@sctnightcore what do you mean?
I can connect server with my own PC, but VPS not?
how to fix this? could you help me?

**Comment by sctnightcore** [comment]
> how to fix this? could you help me?

it has many problem. 
1. xver block ip
2.wrong ip port ? 
3.u try connect bot with same vps ?

**Comment by toffiizz** [comment]
> how to fix this? could you help me?
> 
> [TH]
> เกิดได้หลายกรณี
> 1. ตัว xver แบนไอพี ซึ่งผมเคยใช้มา มีปัญหาสุดๆ 
> 2. ไอพี พอร์ต ที่เชื่อมผิด
> 3. ถ้าเชื่อมในเครื่องเดียวกัน เปลี่ยนไปใช้ localhost ไม่ใช่ public ip
> 
> 
> it has many problem.
> 1. xver block ip
> 2. wrong ip port ? 
> 3. u try connect bot with same vps ? if yes  u need connect to localhost not public ip

TH
1. มีแนะนำเจ้าไหนที่สามารถเปิดได้โดยที่ไม่ต้องเซ็ตอัพเยอะไหม
2. ไม่ผิดแน่ครับ เพราะผมใช้เครื่องตัวเองเปิดได้ปกติ
3. ลองใช้ 2 เจ้า เป็นแบบเดียวกันทั้ง 2 เจ้า ผมจะหา โลเคิลโฮตจากไหนครับ

1. do you have any suggestion the VPS to easy set up?
2. right IP/Port, I use it with my own PC
3. try for 2 VPS, it's same problem, how to find localhost IP

**Comment by sctnightcore** [comment]
> * ลองใช้ 2 เจ้า เป็นแบบเดียวกันทั้ง 2 เจ้า ผมจะหา โลเคิลโฮตจากไหนครับ
> *

localhost เป็นไอพี 127.0.0.1 
ตอนนี้คือเชื่อมตัวเกมปกติ แต่บอทไม่ได้ 
มันขึ้น 10600 คือเชื่อมไม่ได้ลอง

เชื่อมผ่านเครื่อง pc ตัวเองดู ถ้าได้ แสดงว่า vps อาจบล็อกไอพี อะไรพวกนี้

**Comment by toffiizz** [comment]
> ลองใช้ 2 เจ้า เป็นแบบเดียวกันทั้ง 2 เจ้า ผมจะหา โลเคิลโฮตจากไหนครับ
> 
> 
> 
> localhost เป็นไอพี 127.0.0.1
> ตอนนี้คือเชื่อมตัวเกมปกติ แต่บอทไม่ได้
> มันขึ้น 10600 คือเชื่อมไม่ได้ลอง
> เชื่อมผ่านเครื่อง pc ตัวเองดู ถ้าได้ แสดงว่า vps อาจบล็อกไอพี อะไรพวกนี้

เครื่องตัวเอง ลองแล้วเปิดได้ปกติครับ แต่มาลองบน VPS ไม่ได้ เป็น win server 2012 กำลังหาเจ้าที่เปิดได้อยู่หาเจ้าที่เป็น win10

**Comment by sctnightcore** [comment]
> เครื่องตัวเอง ลองแล้วเปิดได้ปกติครับ แต่มาลองบน VPS ไม่ได้ เป็น win server 2012 กำลังหาเจ้าที่เปิดได้อยู่หาเจ้าที่เป็น win10

ผมว่าอาจเกี่ยวเรื่องบล็อกครับ ลอง cmd -> ping ip ดู

**Comment by toffiizz** [comment]
> เครื่องตัวเอง ลองแล้วเปิดได้ปกติครับ แต่มาลองบน VPS ไม่ได้ เป็น win server 2012 กำลังหาเจ้าที่เปิดได้อยู่หาเจ้าที่เป็น win10
> 
> ผมว่าอาจเกี่ยวเรื่องบล็อกครับ ลอง cmd -> ping ip ดู

![2](https://user-images.githubusercontent.com/66774403/84453770-e3745780-ac82-11ea-95e9-d346722354f8.jpg)
Ping request could not find host ip

**Comment by toffiizz** [comment]
![3](https://user-images.githubusercontent.com/66774403/84457251-5df5a500-ac8c-11ea-8e1b-4771317774b2.jpg)

**Comment by toffiizz** [comment]
ไปเปิดเจ้าที่ใช้ WIN 10 เปิดได้ปกติครับ 1 core ram 1g เปิดแทบไม่ได้เลย

**Comment by alisonrag** [comment]
all Official servers have ip block, check if your vps has the allowed ip

blocked ip = foreign ip

**Comment by alisonrag** [comment]
try to use some kind of vpn/proxy to test, this is not a openkore issue

i will keep this open for a week, just to confirm if it is a ip issue

**Comment by mimzmimz** [comment]
i got it fixed by deploying Windows 2008 Server edition. it seems higher versions have strict blocks on outbound connections even if you turn off the firewall
