### ISSUE TITLE
cannot access to tRO

### ISSUE THREAD

**Issue by patrickradulescu** [OpenKore/openkore#3168]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  Latest commit [4108947](https://github.com/OpenKore/openkore/commit/4108947edbe2bca17884f01d67496724c7ee4a41)

* **Server**: Thailand - tRO: Choas

* **Bug Report / Feature Request**:

* **Summary**:  when i try to log in this error showing up 'Packet Parser: Unknown switch: 0B60'. by the way, i try to merge branch tRO-update to master and test again it's still show the same error
![opk](https://user-images.githubusercontent.com/43396463/84407778-79819100-ac35-11ea-9d2c-39dbba4f1b4f.PNG)

**Comment by sctnightcore** [comment]
it's new packet . 
u need paser packet with uself.

we dont have bot for test it .
