### ISSUE TITLE
have question please expland me

### ISSUE THREAD

**Issue by ThememoriesIII** [OpenKore/openkore#3169]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2020_06_05

* **Server**: all server my qustion is diagram xkore1

* **Bug Report / Feature Reques /Questiont**:

> have question, how xkore1 working in diagram?, and what is prompt "<< >>" in front of message send receive?. please explain me.  
> 1. xkore mode 1 is packet sniffer to monitor packet receiv from ROserver and simulate play style packet for send to ROserver right?, if it true what a ROclient do it in diagram bait a packet from server?.
> 2. a arrow key in diagram point a ROclient to ROserver, is possible to switch ROclient  to answer a packet if openkore detect unkown packet?. 
> 3. "<< Sent by RO client" is packet from ROclient to server?
> 4. ">> Sent packet: " packet message under prompt is sendpacket modify by openkore send to server or openkore monitor client send packet to server?
> 5. "<< Received packet:" a message under prompt is packet receiv from server sniff by openkore get it only and not pass to client or openkore and client is both received packet?
> 6.  a packet from server go to openkore first or ROclient first?

* **Summary**:

sorry for bad english

**Comment by alisonrag** [comment]
> > have question, how xkore1 working in diagram?, and what is prompt "<< >>" in front of message send receive?. please explain me.
> > 
`<<` and  `>>` are just visual representation of received and sended packet

> > 1. xkore mode 1 is packet sniffer to monitor packet receiv from ROserver and simulate play style packet for send to ROserver right?, if it true what a ROclient do it in diagram bait a packet from server?

> > 2. a arrow key in diagram point a ROclient to ROserver, is possible to switch ROclient  to answer a packet if openkore detect unkown packet?
both openkore and client receive the same packet, so if openkore can't handle client will reply as the default behavior

> > 3. "<< Sent by RO client" is packet from ROclient to server?
Packet fom Ragnarok Client to Ragnarok Server, but xkore 1 always send this packet to openkore too, so server and openkore will receive the same packet
 
> > 4. ">> Sent packet: " packet message under prompt is sendpacket modify by openkore send to server or openkore monitor client send packet to server?
Sent Packet is a packet generated by openkore and sended to Server

> > 5. "<< Received packet:" a message under prompt is packet receiv from server sniff by openkore get it only and not pass to client or openkore and client is both received packet?
Both Client and Openkore receive all packets

> > 6. a packet from server go to openkore first or ROclient first?
first is openkore, then openkore parse, decide if will change the packet or send to client as received
