### ISSUE TITLE
Unable to find correct servertype and recvpackets

### ISSUE THREAD

**Issue by acepartacus** [OpenKore/openkore#3170]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2.0.7

* **Server**:  http://zetaro.net/

* **Bug Report / Feature Request**:

* **Summary**:

unable to find correct servertype, 

Packet Tokenizer Unknown switch 082D

ip 51.79.150.17
port 6900
version 55
master_version 1
serverType bRO
serverEncoding Western
charBlockSize 144
addTableFolders translated/kRO_english;kRO
recvpackets recvpackets.txt
[_zeta.zip](https://github.com/OpenKore/openkore/files/4771306/_zeta.zip)

**Comment by sctnightcore** [comment]
if u want private server .
u need servertype kRO_clientdate not bRO

**Comment by acepartacus** [comment]
Hi @sctnightcore , apologies, typo on bRO,

I used PE Viewer but client date is Jan 1 1970
