### ISSUE TITLE
Date on PEViewer is Jan 1 1970, unable to find correct servertype

### ISSUE THREAD

**Issue by acepartacus** [OpenKore/openkore#3171]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

Already able to get master version and version
ip 51.79.150.17
port 6900
version 55
master_version 1

unable to find the correct server type, followed the guides and tried to get recvpackets via PEEK.

not working.

[Ragexe.zip](https://github.com/OpenKore/openkore/files/4771336/Ragexe.zip)

**Comment by sctnightcore** [comment]
it hide with antipeek.


u need guess client with Game ui or packet map login .
