### ISSUE TITLE
how to fix code TRO

### ISSUE THREAD

**Issue by jaturapat1** [OpenKore/openkore#3173]
[Jun 14 02:22:07 2020.59] Packet Parser: Unknown switch: 0B60
[Jun 14 02:22:19 2020.34] Timeout on Account Server, reconnecting. Wait 63 seconds...
[Jun 14 02:23:06 2020.90] กำลังจะล๊อกอินใหม่ภายใน 5 วินาที...
[Jun 14 02:23:11 2020.90] ทำการเชื่อมต่อกับ Account Server...
[Jun 14 02:23:11 2020.98] [reconnect] Login retry number 3, setting reconnect timeout to 133 seconds.
[Jun 14 02:23:12 2020.71] กำลังเชื่อมต่อ (49.229.28.77:50001)... [Jun 14 02:23:12 2020.11] เชื่อมต่อสำเร็จ
[Jun 14 02:23:12 2020.17] ============= รายละเอียดการชำระเงิน =============
[Jun 14 02:23:12 2020.23] แบบรายวัน : 2982616 วัน 4 ชั่วโมง 14 นาที
[Jun 14 02:23:12 2020.26] แบบรายชั่วโมง : 2982616 วัน 4 ชั่วโมง 14 นาที
[Jun 14 02:23:12 2020.28] -------------------------------------------------------
[Jun 14 02:23:12 2020.31] Packet Parser: **Unknown switch: 0B60**
[Jun 14 02:23:24 2020.14] Timeout on Account Server, reconnecting. Wait 133 seconds...
[Jun 14 02:23:33 2020.56] กำลังออกจากโปรแกรม...

**Comment by sctnightcore** [comment]
u need paser packet.
