### ISSUE TITLE
Tro

### ISSUE THREAD

**Issue by jaturapat1** [OpenKore/openkore#3175]
คนไทยคนไหนทำได้ก็ช่วยๆแบ่งกันหน่อยเถอะค๊าบบอย้ากะ๊กไว้เลย

**Comment by sctnightcore** [comment]
มีแต่ ukore ครับ.

ถึงถ้าคนอื่นมี การเก็บไว้ก็ไม่ใช่ปัญหาอะไร

**Comment by chirawit23** [comment]
เจริญพรโยม
