### ISSUE TITLE
Tro

### ISSUE THREAD

**Issue by ninetybone** [OpenKore/openkore#3176]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by jaturapat1** [comment]
ไม่มีใครบอกหรอคับ เขาต่างคนต่างกั๊กกัน

**Comment by ninetybone** [comment]
ใจเย็นๆครับx0มันแก้ยากไม่มีใครกั๊กหรอกครับ ตนเป็นที่พึ่งแห่งตนก่อนครับ555
