### ISSUE TITLE
openkore on Windows Server 2012 and 2019

### ISSUE THREAD

**Issue by mimzmimz** [OpenKore/openkore#3177]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

anyone here able to run openkore on windows server in a VPS? it says it cant connect
I tried disabling blocks on outbound connections but i still cant connect

**Comment by alisonrag** [comment]
all Official servers have ip block, check if your vps has the allowed ip

blocked ip = foreign ip

continue in:
#3165
