### ISSUE TITLE
mosk_dun01 to mosk_dun02

### ISSUE THREAD

**Issue by notekubs** [OpenKore/openkore#3187]
i have a problem with mosk_dun01 to mosk_dun02 the bot cannot find npc milestone1-2 207 276 i don't know why any one can help me please
![Untitled](https://user-images.githubusercontent.com/66195892/85151979-a3166a00-b27e-11ea-84ab-02ffd2d6fc93.png)

**Comment by sctnightcore** [comment]
go forum not issues

**Comment by alisonrag** [comment]
You are far away from npc, npc at 207 276 you are at 220 192
This is at least 80 blocks away
