### ISSUE TITLE
bot dont use storageAuto_useItem if route

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#3188]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**: Bug Report

* **Summary**: bot dont use storageAuto_useItem if route.

bot don't use storageAuto_useItem if route.

it work if we try autostorage command.
https://github.com/OpenKore/openkore/pull/1613

**Comment by alisonrag** [comment]
what u mean when u say "router"?

openkore don't use item if still in route? can u send the config here to replicate?

**Comment by sctnightcore** [comment]
> what u mean when u say "router"?
> 
> openkore don't use item if still in route? can u send the config here to replicate?


set some item_control for test  
```storageAuto_useItem 1
storageAuto_useItem_item Kafra Card
```
set lockMap 

if item is low. bot go route not back to storage.

**Comment by alisonrag** [comment]
after login:
![image](https://user-images.githubusercontent.com/10372732/85230681-30b1a100-b3c8-11ea-8642-d368d992deb7.png)

i will test in lockMap

**Comment by alisonrag** [comment]
getAuto in lockMap
![image](https://user-images.githubusercontent.com/10372732/85230855-54291b80-b3c9-11ea-8e2f-d9c494e5973b.png)

**Comment by alisonrag** [comment]
storage in lockmap due to overweight:
![image](https://user-images.githubusercontent.com/10372732/85230913-876baa80-b3c9-11ea-9e8a-488d6b8f9cb0.png)

**Comment by alisonrag** [comment]
can't reproduce

**Comment by alisonrag** [comment]
config.txt:
```
storageAuto 1
storageAuto_npc prontera 151 29

storageAuto_useItem 1
storageAuto_useItem_item Kafra Card

getAuto Blue Gemstone {
	minAmount 1
	maxAmount 100
	batchSize
	passive
	disabled 0
}
```

items_control:
```
# All items not mentioned in this file will be automatically stored in storage.
all 0 1 0

Kafra Card 0 0 0
```

**Comment by alisonrag** [comment]
i need more info, maybe map, item to get, overweight?

also Kafra Card is auto moved to storage if u dont set `Kafra Card 0 0 0` in items_control

maybe he use first time then add to storage and dont have kafra card in inventory, so bot will walk to the kafra

**Comment by sctnightcore** [comment]
@alisonrag  it need add storageAuto  1 ?
