### ISSUE TITLE
help me,please Brother

### ISSUE THREAD

**Issue by chirawit23** [OpenKore/openkore#3195]
https://user-images.githubusercontent.com/44430730/85282545-1f46c280-b4b6-11ea-94bc-b493abfd7f70.png

**Comment by ya4ept** [comment]
### github is not intended for such assistance!
read: https://openkore.com/index.php/Main_Page

![изображение](https://user-images.githubusercontent.com/7117363/85287770-6d9b9780-b49d-11ea-848f-c6c3f566f913.png)

**Comment by chirawit23** [comment]
If you use Windows 7 you must setup a Virtual Machine

**Comment by alisonrag** [comment]
#2963
