### ISSUE TITLE
OpenKore does not check the skill level before sending it to the server

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3197]
* **Openkore version git**: last
* **Server**: any
* **Bug Report / Feature Request**:

Use the config:
```
useSelf_skill First Aid {
	lvl 100
	hp < 100%
	sp > 3
	timeout 30
	disabled 0
	manualAI
}
```
100 (0x0064) skill level is sent to the server:
```
>> Sent packet: 0438   [10 bytes]   Jun 22 17:52:31 2020
  0>  38 04 64 00 8E 00 02 AC    02 00                      8.d.......
```
* **Summary**:
the server accepts such packets without problems, but we should not send them, some security systems can take advantage of this

**Comment by alisonrag** [comment]
i doubt that u dont have lvl 100 hahahahah

must add a check in useskill

**Comment by ya4ept** [comment]
Task UseSkill?

**Comment by alisonrag** [comment]
task useskill is used only in commands

**Comment by ya4ept** [comment]
- [ ] add a check in `commands.pm`

- [ ] add a check in `CoreLogic.pm`

**Comment by alisonrag** [comment]
don't forget to add getOwner in check, cause skills can be casted by player or slaves (homun, merc)

**Comment by oleokoong** [comment]
> https://github.com/OpenKore/openkore/pull/3199
useSelf_skill Summon Spirit Sphere {
    lvl 5
    maxCastTime 0
    minCastTime 0
    hp
    sp > 50
    homunculus_hp
    homunculus_sp
    homunculus_dead
    onAction
    whenStatusActive
    whenStatusInactive
    whenFollowing
    spirit < 5
    amuletType
    aggressives
    monsters
    notMonsters
    monstersCount
    stopWhenHit 0
    inLockOnly 1
    notWhileSitting 1
    notInTown 1
    timeout 0
    disabled 0
    inInventory
    manualAI 0
    label ss11
}

My monk keep spam Summon Spirit Sphere while my Summon Spirit Sphere only lvl1
i think opk ignore the lvl>5 check
and keep spam to fullfill spirit < 5

**Comment by ya4ept** [comment]
@oleokoong, i do not see a problem when using your config
![изображение](https://user-images.githubusercontent.com/7117363/86161395-dd50f880-bb15-11ea-911a-27cfa3675cdc.png)

**Comment by oleokoong** [comment]
> @oleokoong, i do not see a problem when using your config
> ![изображение](https://user-images.githubusercontent.com/7117363/86161395-dd50f880-bb15-11ea-911a-27cfa3675cdc.png)
When my character just turn into monk, i preset auto add skill, its happen when my skill point just enough for lvl1 spirit sphere summon.. and my config is set lvl5.. openkore will keep spam the skill with fail msg
