### ISSUE TITLE
Exp doubled after relog

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3198]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 
cRO

* **Bug Report / Feature Request**:
Bug Report
After relog , bot will get a very high exp , I don't know if it's send by server or a bug of openkore .
after relog bot shows:
[Jun 22 22:51:43 2020.66] You have gained 38930192/-74401562 (51.68%/-56.51%) Exp
this is the total exp bot get before relog, so after relog exp is wrong.

* **Summary**:

**Comment by c4c1n6kr3m1** [comment]
always broken or recently update? (i don't play official coz i can't penetrate the security heh, not programer here)

**Comment by hubertyang88** [comment]
It is recently update , I don't update frequently , but I update openkore in April for cRO update Dorum, before this unpate , exp works fine.

**Comment by c4c1n6kr3m1** [comment]
than test with your old openkore first, because it could be server's update

**Comment by c4c1n6kr3m1** [comment]
may be relevant, months ago i got 64 bits exp problem https://github.com/OpenKore/openkore/issues/3017 than another problem is exp counting. Latest private server i tested, claimed latest version, using different mechanism
old server send level first than exp ( may be reverse, i don't remember well )
but this server send the opposite, that's how i got another exp problem  ( or reverse, as i said i don't remember well )

but it's depend on server
if any one want to take a look .... not me
