### ISSUE TITLE
Deal command use item name

### ISSUE THREAD

**Issue by FFW5056** [OpenKore/openkore#3204]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

tRO
* **Bug Report / Feature Request**:
Error message:
Not an ARRAY reference at src/Commands.pm line 2154.

Stack trace:
Not an ARRAY reference at src/Commands.pm line 2154.
 at src/Commands.pm line 2154
	Commands::cmdDeal('deal', 'add Grit') called at src/Commands.pm line 802
	Commands::run('deal add Grit') called at src/functions.pl line 1021
	main::parseInput('deal add Grit') called at src/functions.pl line 63
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4fceb34)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		}
* 		my $items = [ grep { $_ && lc( $_->{name} ) eq lc( $arg[1] ) && !$_->{equipped} } @$char->inventory ];
  		my $n = $currentDeal{you_items};

* **Summary**:

**Comment by sctnightcore** [comment]
it need item index not item id
