### ISSUE TITLE
Bug buyAuto & sellAuto not working.

### ISSUE THREAD

**Issue by Seaweez** [OpenKore/openkore#3208]
lastest version - master branch

![image](https://user-images.githubusercontent.com/67535394/85946120-4c8ae900-b96c-11ea-8a4d-eb0b642d910c.png)

My Openkore (x1) stuck at this point after "buy / sell Auto".
 
## My code : 

buyAuto Orange Potion {
	minAmount 3
	maxAmount 70
	npc mosk_in 21 254
	batchSize
	distance 6
	price 50
	label BuyOrange
	passive
	disabled 0
}

Macro command is still working ex. "talknpc 21 254 b b3,100 e"

**Comment by ya4ept** [comment]
[disabled 1](https://openkore.com/wiki/Disabled) ???

**Comment by sanfun089** [comment]
without disabled 1 I'm stuck in this issue too.

**Comment by Seaweez** [comment]
> [disabled 1](https://openkore.com/wiki/Disabled) ???

@ya4ept edited ! thanks sir, btw i just disabled it for now actually it still does not work in case of 0 as @sanfun089 said

**Comment by sanfun089** [comment]
I'm just try to add npc_steps like
buyAuto Awakening Potion {
minAmount 1
maxAmount 20
npc prt_in 126 76
distance 1
npc_steps b b8,20
}
it's work and I'm sure that might be have another better choice if any idea please guide me.

**Comment by alisonrag** [comment]
did u tryied only with?
```distance 3
npc_steps b
```

**Comment by Seaweez** [comment]
> did u tryied only with?
> 
> ```
> distance 3
> npc_steps b
> ```

I have tried it

with"npc_steps b & distance 3"
![image](https://user-images.githubusercontent.com/67535394/85964180-d8d7f300-b9e2-11ea-8c78-4857c3a31a07.png)


with "npc_steps b e"
![image](https://user-images.githubusercontent.com/67535394/85964132-ad550880-b9e2-11ea-8754-54c477cb41b1.png)

Both result in the same making my OPK:
![image](https://user-images.githubusercontent.com/67535394/85964205-f311d100-b9e2-11ea-85fc-c7be145be1c4.png)
and also not success in autoBuy/Sell

@alisonrag

**Comment by oleokoong** [comment]
The trick is increasing buy sell npc time in timeout

**Comment by sanfun089** [comment]
> The trick is increasing buy sell npc time in timeout

I'm tried to inscrease npc conversation time and buyAuto wait,wait_before , after_restart for two times of default it's doesn't work for me anyway.
Can you share your npc_talk and buyAuto time out please?
Thank you

**Comment by oleokoong** [comment]
ai_buyAuto 5
ai_buyAuto_wait 2
ai_buyAuto_wait_giveup_npc 20
ai_buyAuto_wait_before_buy 2
ai_buyAuto_wait_after_packet_giveup 15
ai_buyAuto_wait_after_restart 2

ai_sellAuto 2
ai_sellAuto_wait_giveup_npc 20
ai_sellAuto_wait_before_sell 2
ai_sellAuto_wait_after_packet_giveup 15

ai_storageAuto 2
ai_storageAuto_giveup 20
ai_storageAuto_useItem 2
ai_storageAuto_wait_before_action 2

im using lastest version

**Comment by alisonrag** [comment]
> ai_buyAuto 5
> ai_buyAuto_wait 2
> ai_buyAuto_wait_giveup_npc 20
> ai_buyAuto_wait_before_buy 2
> ai_buyAuto_wait_after_packet_giveup 15
> ai_buyAuto_wait_after_restart 2
> 
> ai_sellAuto 2
> ai_sellAuto_wait_giveup_npc 20
> ai_sellAuto_wait_before_sell 2
> ai_sellAuto_wait_after_packet_giveup 15
> 
> ai_storageAuto 2
> ai_storageAuto_giveup 20
> ai_storageAuto_useItem 2
> ai_storageAuto_wait_before_action 2
> 
> im using lastest version

@sanfun089 @Seaweez 

try the code above in timeouts.txt and the code below in config.txt:

```
buyAuto Orange Potion {
	npc mosk_in 21 254
	npc_steps b
	isMarket 0
	standpoint
	distance 5
	price 50
	minAmount 3
	maxAmount 70
	batchSize
	disabled 0
	maxBase
	minBase
}
```
