### ISSUE TITLE
help me please,Bro

### ISSUE THREAD

**Issue by chirawit23** [OpenKore/openkore#3218]
![image](https://user-images.githubusercontent.com/44430730/86435000-1d3bf980-bd29-11ea-89c6-0a0e76f870f9.png)

**Comment by ya4ept** [comment]
@sctnightcore please leave some comment

**Comment by alisonrag** [comment]
Seems like a source edition, we can't help without know what is edited

**Comment by sctnightcore** [comment]
@ya4ept 
Help me please, bro.

i need money

**Comment by alisonrag** [comment]
Who don't need it?
