### ISSUE TITLE
Need help how to run X1 for TRO 2020 

### ISSUE THREAD

**Issue by Chibipond** [OpenKore/openkore#3220]
First of all, I'm very new to OpenKore and don't want to pay money to commercial bot provider.
Just downloaded a few mins ago.

I've run wxstart in x1 mode and already bypass EAC. However, the character is not moving and return "stuck during route" (see pic below). I see the others and monsters moving. 
![image](https://user-images.githubusercontent.com/1866606/86526394-e5b28600-bebd-11ea-810d-b9dfde2ccfe8.png)

Could someone guide me how to resolve this?

**Comment by ninjavinka** [comment]
ผมก็ตอดตรงนี้เหือนกันครับ

**Comment by tonandnutza** [comment]
> First of all, I'm very new to OpenKore and don't want to pay money to commercial bot provider.
> Just downloaded a few mins ago.
> 
> I've run wxstart in x1 mode and already bypass EAC. However, the character is not moving and return "stuck during route" (see pic below). I see the others and monsters moving.
> ![image](https://user-images.githubusercontent.com/1866606/86526394-e5b28600-bebd-11ea-810d-b9dfde2ccfe8.png)
> 
> Could someone guide me how to resolve this?

I too 
Can you help me?
