### ISSUE TITLE
help me timeout on map server

### ISSUE THREAD

**Issue by ninjavinka** [OpenKore/openkore#3221]
help me timeout on map server ,waiting actions for the ragnarok online client 
to x1 Tro 

![Untitled](https://user-images.githubusercontent.com/21142403/86534541-6051c480-bf03-11ea-875b-6bf0cdcf86ab.png)

**Comment by sctnightcore** [comment]
help for what ?

**Comment by ninjavinka** [comment]
> help for what ?
RUN to x1 Tro timeout on map server ,waiting actions for the ragnarok online client
