### ISSUE TITLE
 (tro)​ขอคำแนะนำแนวทางและวิธีแก้ eac หน่อยครับ

### ISSUE THREAD

**Issue by PowerArm** [OpenKore/openkore#3225]
Openkore master new update 8/7/20
ไม่ขอให้เฉลยหรือช่วยเหลือ ขอเพียงแค่คำใบ้เพื่อที่จะศึกษาและไปต่อได้ด้วยตนเองหน่อยครับ รบกวนด้วย

**Comment by ya4ept** [comment]
in English please
