### ISSUE TITLE
Can't sent thai language with commands.

### ISSUE THREAD

**Issue by hnomkeng** [OpenKore/openkore#3228]
* **Openkore version git**: https://github.com/OpenKore/openkore/commit/a1e4673e16bba41b2723b3fe52347b8d3299db71
* **Server**: Private Server
* **Bug Report / Feature Request**: I testing command "do c ฉันนนนนน...." , Show on game "????????....."
![unknown](https://user-images.githubusercontent.com/9112684/87003056-1a3b8000-c1e5-11ea-81ea-868f0ebf4ef8.png)

**Comment by alisonrag** [comment]
use wxstart,exe, or if windows 10 disable console legacy, this is not a openkore issue, this is related to system, windows console can't display thai language

**Comment by ya4ept** [comment]
https://github.com/OpenKore/openkore/issues/2529#issuecomment-502442301
