### ISSUE TITLE
Anyone have Izlude Academy F2 map fix

### ISSUE THREAD

**Issue by mrbuchido** [OpenKore/openkore#3230]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: Lastest in Github

* **Server**: ThRO

* **Bug Report / Feature Request**:

* **Summary**:

I have a problem with Izlude Academy F2 map (iz_ac2), this map in Opk is not up to date. 
Problem is only in Hall Way, all room is fine.

If you have an updated please share
GAT RSW is ok but if it .fld it will be better ;-)

Many Thank,

![Annotation_2020-07-12_190305~2](https://user-images.githubusercontent.com/15907146/87246570-7ff36a80-c478-11ea-8815-6265ff6b5965.png)
![Annotation_2020-07-12_190305](https://user-images.githubusercontent.com/15907146/87246573-81bd2e00-c478-11ea-9cbc-271f90d85ef8.png)
![12367](https://user-images.githubusercontent.com/15907146/87246574-8255c480-c478-11ea-8384-91214a62d137.jpg)

**Comment by sctnightcore** [comment]
if u read openkore wiki.
u can update with uself.

**Comment by ya4ept** [comment]
https://openkore.com/wiki/FLD_Creation_Guide

**Comment by mrbuchido** [comment]
Solved this problem.

I get GAT and RSW in DATA.GRF in ragnarok original data game, extract it with GRF editor and make it to FLD with tools in OPK.
I create this topic because I cannot find GAT and RSW, I don't know where can I get it or anyway to download it. 
but now I know.

Thanks.
