### ISSUE TITLE
How to Modify & Recompile NetRedirect.dll ?

### ISSUE THREAD

**Issue by Tullaphat** [OpenKore/openkore#3231]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**:  tRO

* **Bug Report / Feature Request**:

* **Summary**:

How to Modify & Recompile NetRedirect.dll ?

**Comment by sctnightcore** [comment]
idk too

**Comment by ya4ept** [comment]
https://openkore.com/wiki/How_to_run_OpenKore#C.2FC.2B.2B_compiler
