### ISSUE TITLE
Cannot locate automacro module eventMacro::Condition::status

### ISSUE THREAD

**Issue by mimzmimz** [OpenKore/openkore#3234]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: OpenKore version what-will-become-2.1 Revision: ctime:2020_07_17

* **Server**:  GGamerzRO

* **Bug Report / Feature Request**:

* **Summary**:
I get this error when I start OpenKore even on a blank eventMacros.txt file

OpenKore version what-will-become-2.1 
Network state = 5
Revision: ctime:2020_07_17
Network handler = Network::DirectConnection

Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/eventMacro/eventMacro.pl (eventMacro; description: allows usage of eventMacros)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Cannot locate automacro module eventMacro::Condition::status.

Stack trace:
Trace begun at plugins\eventMacro\eventMacro\Core.pm line 369
eventMacro::Core::load_condition_module('eventMacro::Core=HASH(0x66db3f4)', 'eventMacro::Condition::status') called at plugins\eventMacro\eventMacro\Core.pm line 318
eventMacro::Core::create_automacro_list('eventMacro::Core=HASH(0x66db3f4)', 'HASH(0x5215614)') called at plugins\eventMacro\eventMacro\Core.pm line 56
eventMacro::Core::new('eventMacro::Core', 'control\eventMacros.txt') called at D:\Downloads\Compressed\openkore-master\openkore-master\plugins\eventMacro\eventMacro.pl line 94
eventMacro::parseAndHook('control\eventMacros.txt') called at D:\Downloads\Compressed\openkore-master\openkore-master\src\Settings.pm line 547
Settings::loadByHandle(63, 'CODE(0x438152c)') called at D:\Downloads\Compressed\openkore-master\openkore-master\src\Settings.pm line 603
Settings::loadFiles('ARRAY(0x784b79c)', 'CODE(0x438152c)') called at D:\Downloads\Compressed\openkore-master\openkore-master\src\Settings.pm line 575
Settings::loadByRegexp('Regexp=REGEXP(0x784ae1c)', 'CODE(0x438152c)') called at src\Misc.pm line 5335
eval {...} at src\Misc.pm line 5327
Misc::parseReload('eve') called at src\Commands.pm line 4931
Commands::cmdReload('reload', 'eve') called at src\Commands.pm line 851
Commands::run('reload eve') called at src\functions.pl line 1021
main::parseInput('reload eve') called at src\functions.pl line 63
main::mainLoop at src\Interface.pm line 75
Interface::mainLoop('Interface::Console::Win32=HASH(0x4d62904)') called at openkore.pl line 97
main::__start at start.pl line 136

Died at this line:
  	eval "use $condition_module";
* 	if ($@ =~ /^Can't locate /s) {
  		FileNotFoundException->throw("Cannot locate automacro module ".$condition_module.".");

**Comment by alisonrag** [comment]
status is not a eventmacro condition is a macro plugin, save your file as macros.txt
