### ISSUE TITLE
unable to cast skill prepare potion in 3 tries.

### ISSUE THREAD

**Issue by Zackkypro** [OpenKore/openkore#3237]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: lasted release

* **Server**: tRO

* **Bug Report / Feature Request**:

* **Summary**:

![asd123asd](https://user-images.githubusercontent.com/68665245/88226717-b27e3e00-cc96-11ea-8643-3aa3067f595b.png)

> automacro potzMaker {
sp > 20
inventory "Medicine Bowl" > 0
timeout 1.5
run-once 1
call {
do ss 228 10
do send 8E 01 F9 01 00 00 00 00 00 00
pause 0.5
release potzMaker
}
}

Bot stuck and close.exe after creating 1 potion

**Comment by alisonrag** [comment]
dont use send, this raw is used in old packets 201906-
use command 
`ss 228 10 `
then 
`create <index>`

**Comment by Zackkypro** [comment]
> dont use send, this raw is used in old packets 201906-
> use command
> `ss 228 10 `
> then
> `create <index>`

it's work 

`do ss 228 10
pause 0.5
do create *number*`
