### ISSUE TITLE
Compiling issue on debian jessie

### ISSUE THREAD

**Issue by kittygrill** [OpenKore/openkore#324]
Freshly installed debian jessie. Followed instructions for linux. Compiling won't output anything 

> 
> $ perl ./openkore.pl
> $

No output, nothing happens.

I tried start.pl

> $ perl ./start.pl
> 
> This file is meant to be compiled by PerlApp.
> To run kore, execute openkore.pl instead.
> 
> $

**Comment by kittygrill** [comment]
Nevermind, wiki seems to be wrong.

> apt-get install g++
for debian

I tried the ubuntu counterpart
>apt-get install build-essential g++

and got it working. It's a base install debian so it didn't have the complete gcc for it. Wiki seems  to be misleading.

**Comment by itsrachelfish** [comment]
Thanks for letting us know @kittygrill. I updated the instructions on the wiki
