### ISSUE TITLE
stuck at give up attack

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3240]
## ------------------ Openkore Issues Template ------------------

 if bot can't reach a monster , it shows the message of 'giving up attack' , but Bot will go back to attack this monster again , especially When  the monster is a plant which can't move  , bot will stuck .
I think this is a very old bug , did anyone try to fix it? 

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:
Bug Report 

* **Summary**:

**Comment by alisonrag** [comment]
same as #1687 
#2871 should fix this
