### ISSUE TITLE
Cro cant connect to Poseidon

### ISSUE THREAD

**Issue by feimao12** [OpenKore/openkore#3249]
Openkore version git:
Server: CRO
Bug Report / Feature Request:
Summary:
I tried to connect to Poseidon, but failed.
I set the Poseidon, as shown in the figure. 
![1](https://user-images.githubusercontent.com/69028347/89090815-e1ec2380-d3d7-11ea-8653-d4d73ab8f108.png)

Tt has been bothering me for several days. Can any guys help me,THX :D

**Comment by dongzhuming** [comment]
Change charBlockSize to 155 will work. you can find the property in  in poseidon.txt
