### ISSUE TITLE
[eventMacro] undocumented keyword `&venderamount`

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3252]
1) what arguments does this function take as input? Very likely it should be the index of the item, instead of its ID or name.
this syntax is not friendly: `&venderamount(&venderitem(Alcohol))`
I suggest making changes so that we can enter the name of the item or its ID

2) This does not work for non-stackable items (testing on the RMS server):
**Bot 1:**
shop.txt:
```
test shop
Knife [3]	100	1
Alcohol		50	10
Knife [3]	200	1
```
eventMacros.txt:
```
macro merch {
	do c \@go 1
	do c \@job 5
	do c \@str 99
	do c \@blvl 50
	do c \@statsall
	do c \@skillsall
	do c \@zeny 1000
	do talknpc 156 97 r3 r0 r5 if ($.statushandle != "EFST_ON_PUSH_CART")
	do c \@item knife 3
	do c \@item alcohol 100
	do cart add &Inventory(1201)
	do cart add &Inventory(970)
	do charselect
	pause 5
	do c \@go 1
	do openshop
}
```
**Bot 2:**
eventMacros.txt:
```
macro check {
	do c \@go 1
	do vender 0
	log venderitem Alcohol: &venderitem(970)
	log venderItem Knife: &venderItem(Knife [3])
	log venderamount Alcohol: &venderamount(&venderitem(970))
	$a = &venderItem(Knife [3])
	log venderamount Knife: &venderamount($a)
}
```
**Console:**
```
----------------------------- Vender: merchhh (0) -----------------------------
#   Name                                      Type        Amount          Price
0   Knife [3]                                 Weapon           1           100z
1   Alcohol                                   Event           10            50z
2   Knife [3]                                 Weapon           1           200z
-------------------------------------------------------------------------------
[eventmacro message] venderitem Alcohol: 1
[eventmacro message] venderItem Knife: 0,2
[eventmacro message] venderamount Alcohol: 10
[eventmacro message] venderamount Knife: 1
```
should be: `[eventmacro message] venderamount Knife: 2`

**Comment by Nipodemos** [comment]
the only thing i can think of for this error is the space in the name of the knife
depending of the place, eventMacro does not handle well spaces

**Comment by Nipodemos** [comment]
> 1. this syntax is not friendly: `&venderamount(&venderitem(Alcohol))`

i agree that is not friendly, but venderamount does not support you to pass the item name or ID directly? that's sad

**Comment by ya4ept** [comment]
we can do this operation inside the `getVendAmount` function

**Comment by ya4ept** [comment]
> the only thing i can think of for this error is the space in the name of the knife
> depending of the place, eventMacro does not handle well spaces

What does the space have to do with it? The fucttion `&venderItem (Knife [3])` works well, we see two items. But, `&venderamount` does not summarize them.

**Comment by ya4ept** [comment]
fixed, new syntax: 
```
&venderamount (<item|ID>)
```
