### ISSUE TITLE
Ragnarok iRO Transcended "0A7B Handler: EAC_key"

### ISSUE THREAD

**Issue by jokinvipo** [OpenKore/openkore#3253]
Hello guys,

Im running openkore xkore 1 in iRO Transcended server and im getting this error (sometimes i got alot spam mesage of it).
How i can fix this?

Im having other problem, after 30min running openkore i recieve the error **"timeout on map server. waiting action for the ragnarok online client".**

How can i solve this?

Thank you very much ;)

**Comment by ya4ept** [comment]
this server is not supported due to encryption

**Comment by bigspender143** [comment]
> this server is not supported due to encryption
> 
> ```
> '0A7B' => ['EAC_key'],
> 
> sub EAC_key {
>     chatLog("k", T("*** Easy Anti-Cheat Detected ***\n"));
>     error T("OpenKore don't have support to servers with Easy Anti-Cheat Shield, please read the FAQ (github).\n");
>     quit();
> }
> ```

where can I find this line of code? Is it in openkore file itself?
