### ISSUE TITLE
[eventMacro] undocumented keyword `&listitem`

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3254]
"returns given argument from a comma separated list"
Why do we need keyword  `&listitem`?
We can accomplish the same with the keyword `&arg`
**Example:**
```
 macro listitem {
   [
    $list = a,b,c
    log listitem: &listitem (2, $list)
    log arg: &arg ("$list", 3)
   ]
 }
```
Console:
```
em listitem
[eventmacro message] listitem: c
[eventmacro message] arg: c
```
i suggest to remove the keyword `&listitem`

**Comment by Nipodemos** [comment]
just read the code, &listitem seems better to be honest with you

&arg looks like @Henrybk grabbed from old macro plugin, but it works...
also &arg is more used because of that fact

&listitem i think almost no one even know that exists, so it is safer to remove, i agree with you

**Comment by ya4ept** [comment]
@Henrybk, let's remove the `&listitem` keyword?

**Comment by ya4ept** [comment]
@Henrybk ?
