### ISSUE TITLE
Xkore 1 Timeout on Map Server Waiting actions for Ragnarok Client

### ISSUE THREAD

**Issue by jokinvipo** [OpenKore/openkore#3259]
Hello,

Im using Xkore 1 i need to adjust anything in timeouts?

![bot](https://user-images.githubusercontent.com/35331883/89139753-9d779980-d537-11ea-8b7b-ee74a973f682.png)

**Comment by alisonrag** [comment]
Server?
Config?

**Comment by jokinvipo** [comment]
Its iRO Transcended, what config you need specific ?

**Comment by ya4ept** [comment]
https://github.com/OpenKore/openkore
![изображение](https://user-images.githubusercontent.com/7117363/89156700-c87fde80-d573-11ea-9755-cbaff0a877ce.png)
