### ISSUE TITLE
Packet Parser: Unknown switch: 0ADA

### ISSUE THREAD

**Issue by aididdev** [OpenKore/openkore#3261]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**:  tRO

* **Bug Report / Feature Request**:

* **Summary**: Packet Parser: Unknown switch: 0ADA

Packet Parser: Unknown switch: 0ADA
tRO Latest update

**Comment by scream1ng** [comment]
also 0A96 -> deal_add_other packet

Look like structure changed
