### ISSUE TITLE
 something wrong about special_item_obtain 

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3263]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:
Error msg
OpenKore version what-will-become-2.1
@ai_seq = route
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2020_03_06
Loaded plugins:
  plugins/alertSound/alertSound.pl (alertsound; description: plays sounds on certain events)
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/planLockMapWalk/planLockMapWalk.pl (planLockMapWalk; description: Auto Plan to walk.)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)

Error message:
Negative '/' count in unpack at src/Network/Receive.pm line 9355.

Stack trace:
Negative '/' count in unpack at src/Network/Receive.pm line 9355.
 at src/Interface/Wx.pm line 164
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x4c24a64)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

This line has error:
  	if ($args->{type} == TYPE_BOXITEM) {
* 		@{$args}{qw(box_nameID)} = unpack 'c/v', $args->{etc};

* **Summary**:
This happened when someone use a new egg , and system message about someone gets special item , then bot will shut down.

**Comment by ya4ept** [comment]
'c/v' ?

**Comment by hubertyang88** [comment]
I changed it from 'c/v' to 'v' , it seems to be ok
