### ISSUE TITLE
npc,item,monster,player Unable to recognize

### ISSUE THREAD

**Issue by polme32** [OpenKore/openkore#3264]
[ysys]
ip 45.248.8.55
port 6906
private 1
version 107
master_version 4
serverType kRO_RagexeRE_2018_06_21a
serverEncoding Simplified Chinese
addTableFolders ysys-RO
recvpackets recvpackets.txt
charBlockSize 155

this is server.txt

username test
password 123123

openkore I feel helpless because I can't recognize all kinds of information.
please help me~
and How do I change it?

**Comment by ya4ept** [comment]
most likely you are using the wrong serverType

**Comment by alisonrag** [comment]
27 days without a user feedback
