### ISSUE TITLE
Packet Tokenizer: Unknown switch: 91A9 after use charselect command

### ISSUE THREAD

**Issue by l3luel3ird** [OpenKore/openkore#3267]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: version ctime:2020_08_29 ) 

* **Server**: tRo

* **Bug Report / Feature Request**: recvpacket

* **Summary**: How to update recvpacket with new ragexe.exe

**Comment by ya4ept** [comment]
we do not support this server, because encrypted traffic
