### ISSUE TITLE
the "itemsTakeGreed" parameter does not work optimally

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3268]
i am using the following parameters:
```
itemsTakeAuto 1
itemsTakeAuto_new 0
itemsTakeGreed 1
```
at the same time, the bot always comes close to the item ([distance 1 cell](https://github.com/OpenKore/openkore/blob/master/src/AI/CoreLogic.pm#L795))

The Greed skill allows you to collect items at a distance of 2 cells.

See [r6386](https://sourceforge.net/p/openkore/code/6386/)

**Comment by alisonrag** [comment]
also i propose to remove `itemsTakeAuto_new ` flag and use only `ai_route` instead of `moveAlongVector`
