### ISSUE TITLE
OpenKore don't have support to servers with Easy Anti-Cheat Shield, please read the FAQ (github). *EXITING...*

### ISSUE THREAD

**Issue by bigspender143** [OpenKore/openkore#3271]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  Latest

* **Server**: iRO

* **Bug Report / Feature Request**: How can I disable the clientSuspend

* **Summary**: xkore 1 exits upon entering the game, i think this is a custom setup made on openkore but I can't find where. Ii clientSuspend will be removed I will be able to use xkore 1 to iRO. Once someone helped me out on this I will share my work. Thanks!

![Capture](https://user-images.githubusercontent.com/48724408/93725672-912cc600-fbe3-11ea-9112-d79560f30081.JPG)

**Comment by bigspender143** [comment]
I'm able to login in game but xkore keeps exiting even I bypassed EAC. I just want to have this

sub EAC_key {
    chatLog("k", T("*** Easy Anti-Cheat Detected ***\n"));
    error T("OpenKore don't have support to servers with Easy Anti-Cheat Shield, please read the FAQ (github).\n");
    quit();
}

removed, I don't know where can I find this script.Thanks

**Comment by bigspender143** [comment]
@alisonrag if you have an idea please let me know. thanks!

**Comment by ya4ept** [comment]
@bigspender143 just remove:
~~error T("OpenKore don't have support to servers with Easy Anti-Cheat Shield, please read the FAQ (github).\n");
quit();~~

**Comment by alisonrag** [comment]
openkore/src/network/receive.pm

**Comment by khelpogi** [comment]
sir how to bypass the openkore dont have support to servers with Easy Anti-Chear shield?? im logging in but exiting in the end

**Comment by masteronizuka** [comment]
i not use 
![image](https://user-images.githubusercontent.com/83839941/117499318-42327600-afa5-11eb-83f8-73ff121fe8c4.png)

**Comment by masteronizuka** [comment]
What did I do wrong? Server RO GGT (TH)
![Uploading image.png…]()
