### ISSUE TITLE
error cloned map iro transcendence

### ISSUE THREAD

**Issue by basilisco1994** [OpenKore/openkore#3272]
Hello, I'm wrong when trying to get my bots to run on the cloned map of iro Transcendence.

he doesn't find the map, even though I added it to the custom maps :(

**Comment by ya4ept** [comment]
any logs?

**Comment by alisonrag** [comment]
added to maps.txt? cloned the portals in portals.txt? added the field to fields folder?

**Comment by basilisco1994** [comment]
@alisonrag 
I did not do this.
could you tell me how to do please?

**Comment by alisonrag** [comment]
fld creation:
https://openkore.com/wiki/FLD_Creation_Guide

portal creation:
https://openkore.com/wiki/Portals.txt

maps creation:
https://openkore.com/wiki/Maps.txt

after all in console type:
```portal recompile```

**Comment by ya4ept** [comment]
@basilisco1994  do you still need help?
