### ISSUE TITLE
error with x y itemappeared

### ISSUE THREAD

**Issue by notekubpom** [OpenKore/openkore#3273]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

my bot not pickup the item
it a private server
no gepard 
the item show wrong x y in console
![Untitled (1)](https://user-images.githubusercontent.com/71810988/94107806-643d1500-fe68-11ea-9bf1-57ac70c09ef3.png)

the client date: 20200302 form bpe-master
my server.txt
[rofi-ro]
ip 103.91.207.20
port 6900
private 1
version 47
master_version 103
serverType kRO_RagexeRE_2018_11_21
recvpackets recvpackets.txt
serverEncoding Western
charBlockSize 155
addTableFolders translated/kRO_english;kRO

this is my recvpackets.txt 
[recvpackets.txt](https://github.com/OpenKore/openkore/files/5273860/recvpackets.txt)

**Comment by ya4ept** [comment]
received a link to the client and test account

**Comment by notekubpom** [comment]
full data
https://drive.google.com/file/d/1vfNy5vvUoJ_QT6We9qqVTpIVInGF799K/view?usp=sharing
only exe
https://drive.google.com/file/d/17srGTlGrIXGJIJEBjHSArJTNskUXNrap/view?usp=sharing
username : testacc
password : note1234

**Comment by notekubpom** [comment]
> received a link to the client and test account

full data
https://drive.google.com/file/d/1vfNy5vvUoJ_QT6We9qqVTpIVInGF799K/view?usp=sharing
only exe
https://drive.google.com/file/d/17srGTlGrIXGJIJEBjHSArJTNskUXNrap/view?usp=sharing
username : testacc
password : note1234

**Comment by alisonrag** [comment]
if using 2018+ servertype, there is no support to new item system yet
all items changed the nameID length in packets

**Comment by notekubpom** [comment]
anyway to fix it bro.

**Comment by alisonrag** [comment]
Always have a way to fix it :)
Just need to update src and update item lenght
Maybe ya4ept will do this

**Comment by notekubpom** [comment]
ok need to update

**Comment by ya4ept** [comment]
![изображение](https://user-images.githubusercontent.com/7117363/94350902-d1fd6280-005b-11eb-841b-58fb88bee313.png)

**Comment by sctnightcore** [comment]
@ya4ept  I will only update this packet when hacktoberfest activity. Starting next month

**Comment by ya4ept** [comment]
@note the server died?

**Comment by notekubpom** [comment]
@ya4ept yes server already died

**Comment by sctnightcore** [comment]
![image](https://user-images.githubusercontent.com/23263315/94775507-269d3680-03ea-11eb-8e48-dcce75251664.png)
@notekubpom 

just update only 0ADD . :)
