### ISSUE TITLE
Inventory Bug  Help Pls

### ISSUE THREAD

**Issue by TanasanJJ7** [OpenKore/openkore#3274]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  Openkore Last Version  >>>  X1

* **Server**:  IRO

* **Bug Report / Feature Request**:   Inventory Bug

* **Summary**:  How to fix item name in Inventory

![iro 25-9-20](https://user-images.githubusercontent.com/16222517/94251756-3251ae80-ff4d-11ea-9968-a15aa7ba66aa.PNG)

Thank for Support

**Comment by sctnightcore** [comment]
if u can make xkore1 work.
I think u can update it by u self.

**Comment by TanasanJJ7** [comment]
> if u can make xkore1 work.
> I think u can update it by u self. 🤔

I tried  >> [ProcessAutoBuy] bulkBuying #2948
But not working
Can you tell me the guidelines ?
