### ISSUE TITLE
Unknown Monster

### ISSUE THREAD

**Issue by 0dr4ud** [OpenKore/openkore#3277]
* **Openkore version git**: 
latest version downloaded from github

* **Server**: 
[Private]
ip 200.98.205.184
port 8682
private 1
master_version 1
version 30
serverType kRO_RagexeRE_2014_03_05
serverEncoding Western
charBlockSize 144
addTableFolders bRO

* **Bug Report / Feature Request**: 
The monsters are being shown as unknown

* **Summary**: 

Hello, I am trying to use Kore on a private server, in principle it is working 99%, it detects all npcs, players, items. However, the monsters are being shown as unknown.
All server data was obtained according to the Wiki connection guide. _IP, port, version, master_version, etc_. were obtained through WPE.
_Servertype_ obtained through PEViewer, as shown in the image below.
![PEViewer](https://user-images.githubusercontent.com/71929564/94341258-3e398100-ffde-11ea-8116-d37ac63a9ab2.jpg)
![ServerType](https://user-images.githubusercontent.com/71929564/94341267-45f92580-ffde-11ea-99b2-0d54201f1b31.jpg)
_Recvpackets_ obtained through PEEK.
[recvpackets.txt](https://github.com/OpenKore/openkore/files/5286695/recvpackets.txt)

According to my research, to solve this problem, I read that this would probably be an incorrect serverType problem, but this was obtained through PEViewer as stated earlier. Anyway, I tested all possible serverType's, and even so I was not successful. Researching further, I discovered that it may be that the client uses a fake data. However, I don't know any way on how to find out the actual date of the executable.

Something I found interesting, is that monsters are rarely recognized, and are generated in monsters.txt. Another detail is that when using the _ml_ command on the console, the monster that is unknown, part of his real name, is shown where the monster's ID would be, as in the image below:
![Desconhecido](https://user-images.githubusercontent.com/71929564/94341209-f6b2f500-ffdd-11ea-9a44-a6463bba4890.jpg)
In this case, I was attacking the monster Raydric, and as you can see in the image, part of his name (Ray) is shown in the space where the ID would be.

Anyway, as I already said, I tried several different serverType's, which would be the problem according to the wiki, but I was not successful. I no longer know which way to go to solve the problem, if anyone has any idea what may be causing this, I will be very grateful.

I'm leaving attached, the server executable, and also an account if someone can test
https://drive.google.com/drive/folders/1h1wWMVZbGj3e6gWlzTezkLvNX8PvwI4x?usp=sharing
u: testuser
p: test123456
map: prt_fild00

Thanks again

**Comment by 0dr4ud** [comment]
Hello, I apologize for posting again, but I would like to know if anyone has any idea how I can proceed to resolve this issue. I also apologize if I am posting in the wrong place, if so, I ask you to inform me of the correct location so that I can ask for support for this problem. Thank you again.

**Comment by sctnightcore** [comment]
i need freetime to test it.

**Comment by 0dr4ud** [comment]
> i need freetime to test it.

Oh yes, That is OK. I just asked because I didn't know if this was the right place for this problem. Anyway, I look forward to when you can test this. I am available if you need any more information. Thank you again! :)

**Comment by c4c1n6kr3m1** [comment]
interesting, the server doesn't send actor's name

my bot is very old, but working fine with this server
may be because https://github.com/OpenKore/openkore/pull/3179 ?
try previous version before this pull ?

**Comment by 0dr4ud** [comment]
> interesting, the server doesn't send actor's name
> 
> try make your own monsters.txt ???

Yes, i have already tested importing the complete list of monsters into monsters.txt, and even then without success. Strange, is that some monsters were generated in monsters.txt, but on the console they remain unidentified. 

I saw in your edited comment, that you tested and worked normally in an older version of Openkore. You can tell me where I could find an older version to download. Or would you be able to upload your Openkore for me? Grateful for the help.

**Comment by 0dr4ud** [comment]
Problem solved, I managed to solve it by removing the updates made in Receive.pm
https://github.com/OpenKore/openkore/pull/3179/commits/f1ddb7b09e45b93f3642df339b4b397c7448080f#

Thanks a lot c4c1n6kr3m1 👍

**Comment by c4c1n6kr3m1** [comment]
yes ,i edited link to https://github.com/OpenKore/openkore/pull/3179
because i'm too lazy to test and read, and i'm not sure if this pull is the trigger
lucky you i ever read this pull
i'm too lazy
let ask @alisonrag if any permanent solution for this

what about npcs name?

**Comment by 0dr4ud** [comment]
NPCs name, Items, Player working fine too. Thanks again :D

**Comment by alisonrag** [comment]
> yes ,i removed link to #3179
> because i'm too lazy to test and read, and i'm not sure if this pull is the trigger
> lucky you i ever read this pull
> i'm too lazy
> let ask @alisonrag if any permanent solution for this
> 
> what about npcs name?

Fix the packet is the correct way
He has lucky, because the initial data from packet is parsed correct, but the final is wrong, so info about name, hair style and others is wrong

**Comment by alisonrag** [comment]
The correct names get in her openkore is because of request info packet

**Comment by griffinxs** [comment]
I have a different problem, my openkore is showing the monsters as players and makes it impossible to attack, can someone help me?

**Comment by pakpao52** [comment]
For this version Do you have recvpackets.txt ?
![image](https://user-images.githubusercontent.com/132443816/235882766-16fd87b1-6e90-4e0b-8d86-29c39c076ad5.png)
