### ISSUE TITLE
Rodex dont working

### ISSUE THREAD

**Issue by jokinvipo** [OpenKore/openkore#3278]
Hello guys,

I found a problem when i try to use RODEX in Openkore.

When i call command "rodex open" he says "sending request to open rodex" but nothing happend.

What i can do ?

![dddd](https://user-images.githubusercontent.com/35331883/94486505-6cce7c00-01d7-11eb-9f15-fd07a868d83d.png)

**Comment by ya4ept** [comment]
we are not telepathic
use:
```
------------------ Openkore Issues Template ------------------
    Openkore version git:
    Server:
    Bug Report / Feature Request:
    Summary:
```

**Comment by jokinvipo** [comment]
Hey ya4ept,

Thank you for the reply,

------------------ Openkore Issues Template ------------------
    Openkore version git: lastest
    Server: iRO Transcendence
    Bug Report / Feature Request: Fix Rodex
    Summary: Kore can't open RODEX function

**Comment by jokinvipo** [comment]
Using debug 2 i got that packet:

![debug](https://user-images.githubusercontent.com/35331883/94566758-a13b4a00-0262-11eb-941b-33816a36888a.png)

**Comment by jokinvipo** [comment]
i did what you asked and i get this info:

![rrr](https://user-images.githubusercontent.com/35331883/94569765-fc227080-0265-11eb-821c-bc27670516c2.png)

**Comment by ya4ept** [comment]
can you send information in text form?

**Comment by jokinvipo** [comment]
================================================
<< Received packet:      0AC2 - Rodex Mail List [5 bytes]   Sep 29 16:35:45 2020
  0>  C2 0A 05 00 01                                        .....
Received packet: 0AC2 Handler: rodex_mail_list
------------------------------ Rodex Mail Page  -------------------------------
-------------------------------------------------------------------------------

**Comment by ya4ept** [comment]
oh my god .. i need the full text of the package

**Comment by jokinvipo** [comment]
updated

**Comment by ya4ept** [comment]
we fixed it:
`rodex_open_mailbox 0AC0`

**Comment by jokinvipo** [comment]
Hello ya4ept,

That fix only works when i digit manually in console, if i use macro with "do rodex open" he cant open RODEX.
Maybe the packet code change?

**Comment by ya4ept** [comment]
```css
do rodex open
pause 2
...
```
