### ISSUE TITLE
"Packet Parser: Unknown switch" for sent packages, when using "XKore 1" + sync.txt

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3291]
* **Openkore version git**: last
* **Server**: rRO / euRO
* **Bug Report**:

my **sync.txt**:
```
...
0934 095E
...
```
console log:
```
================================================
<< Sent by RO client:    095E [2 bytes]   Oct 14 02:12:33 2020
  0>  5E 09                                                 ^.
Packet Parser: Unknown switch: 095E
================================================
<< Received packet:      0934 [2 bytes]   Oct 14 02:12:33 2020
  0>  34 09                                                 4.
```
We should automatically add **sync.txt** packages to the appropriate **send serverType** ($self->{packet_list})

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/blob/cea96de5d4b4961981c5e8b42c299e729f44bcae/src/Network/Receive.pm#L4205

**Comment by alisonrag** [comment]
Xkore 1 is a little confuse
It send the packet to openkore, openkore handle and can edit the packet, then send again to xkore and xkore send to server

**Comment by ya4ept** [comment]
> 
> 
> https://github.com/OpenKore/openkore/blob/cea96de5d4b4961981c5e8b42c299e729f44bcae/src/Network/Receive.pm#L4205
> 
> 🤔 🤔 🤔 🤔

these are incoming packets. My bot swears at packets outgoing from the client
