### ISSUE TITLE
Openkore xKore3 Origins RO  ?

### ISSUE THREAD

**Issue by jokinvipo** [OpenKore/openkore#3295]
Hello guys,

Im trying to use Openkore in this private Origins RO (https://originsro.org/).

When i try to connect Openkore to client he can't detect, what can be ?

![unknown](https://user-images.githubusercontent.com/35331883/96505002-7171d780-124d-11eb-8e30-4f386688d634.png)

**recvpackets**
https://pastebin.com/1MTRCYYv

Server Info:
# https://originsro.org/
[France - OriginsRO: Main Server]
ip 94.23.193.170
port 6121
master_version 0
version 28
serverType kRO_RagexeRE_2013_08_07a
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders originsro;iRO/official;iRO
charBlockSize 144
pinCode 0
charDeleteDateType 1
sendCryptKeys 0x434115DE, 0x6791428E, 0x34A10FE9
rankingSystemType 1
private 1
clientHash 8c9031a8437f1188c77d0fd3a12e2ec5

**Comment by Wouchou** [comment]
Hey @jokinvipo,

How did you fix the issue please ? i'm currently at the same point and wondering how i can fix my issue...

(used the same configuration than you)

Thanks for your help !
