### ISSUE TITLE
Openkore recognize myself as normal player? Ghost Players ?

### ISSUE THREAD

**Issue by jokinvipo** [OpenKore/openkore#3296]
Hello,

Yesterday i found a very strange problem in my Openkore when i activate the function Teleport to avoid all players.

The Openkore spams every teleport "Avoid players" and the map is empty.

The server is Origin RO and all server info good only this feature is dont work.

What i can do ?

Example:

![1](https://user-images.githubusercontent.com/35331883/96724239-85315100-13a7-11eb-9ca1-5530c7c188ab.png)

**Comment by ya4ept** [comment]
is this behavior repeated on different maps?

**Comment by jokinvipo** [comment]
Yes, i tested in other 5 diferent maps i got the same behavior.

**Comment by jokinvipo** [comment]
> is this behavior repeated on different maps?

Yes, i tested in other 5 diferent maps i got the same behavior.

**Comment by ya4ept** [comment]
The following happens:
when you connecting on the map, a Player with ID 150000 appears  at your coordinates,  the profession is different every time, then after 2 seconds it disappears:
```css
[Oct 22 01:42:06 2020.39] ================================================
<< Received packet:      0915 - actor_display (actor exists) [74 bytes]   Oct 22 01:42:06 2020
  0>  15 09 4A 00 00 F0 49 02    00 96 00 00 00 00 00 04    ..J...I.........
 16>  00 00 00 07 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 01 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 19    00 90 05 05 00 3E 00 00    .............>..
 64>  00 FF FF FF FF FF FF FF    FF 00                      ..........
[Oct 22 01:42:06 2020.40] Received packet: 0915 Handler: actor_exists
[Oct 22 01:42:06 2020.41] [!!!] object_class=Actor::Player
[Oct 22 01:42:06 2020.41] [!!!] mustAdd = 1
[Oct 22 01:42:06 2020.42] Player Exists: Неизвестный #150000 (0) Level 62 Girl Knight (100, 9)
...
[Oct 22 01:42:08 2020.20] Sent get player info: ID - F0 49 02 00
...
[Oct 22 01:42:08 2020.96] ================================================
<< Received packet:      0080 - Actor Lost (Died, Disappeared, Disconnected) [7 bytes]   Oct 22 01:42:08 2020
  0>  80 00 F0 49 02 00 00                                  ...I...
[Oct 22 01:42:08 2020.10] Received packet: 0080 Handler: actor_died_or_disappeared
[Oct 22 01:42:08 2020.11] Player Disappeared: Неизвестный #150000 (0) Girl Knight (100, 9)
```
by the way, openKore is used in proxy mode .. maybe it really sees itself o_O

**Comment by ya4ept** [comment]
The following happens:
when you connecting on the map, a Player with ID 150000 appears  at your coordinates,  the profession is different every time, then after 2 seconds it disappears:
```css
[Oct 22 01:42:06 2020.39] ================================================
<< Received packet:      0915 - actor_display (actor exists) [74 bytes]   Oct 22 01:42:06 2020
  0>  15 09 4A 00 00 F0 49 02    00 96 00 00 00 00 00 04    ..J...I.........
 16>  00 00 00 07 00 00 00 00    00 00 00 00 00 00 00 00    ................
 32>  00 00 00 01 00 00 00 00    00 00 00 00 00 00 00 00    ................
 48>  00 00 00 00 00 00 00 19    00 90 05 05 00 3E 00 00    .............>..
 64>  00 FF FF FF FF FF FF FF    FF 00                      ..........
[Oct 22 01:42:06 2020.40] Received packet: 0915 Handler: actor_exists
[Oct 22 01:42:06 2020.41] [!!!] object_class=Actor::Player
[Oct 22 01:42:06 2020.41] [!!!] mustAdd = 1
[Oct 22 01:42:06 2020.42] Player Exists: Неизвестный #150000 (0) Level 62 Girl Knight (100, 9)
...
[Oct 22 01:42:08 2020.20] Sent get player info: ID - F0 49 02 00
...
[Oct 22 01:42:08 2020.96] ================================================
<< Received packet:      0080 - Actor Lost (Died, Disappeared, Disconnected) [7 bytes]   Oct 22 01:42:08 2020
  0>  80 00 F0 49 02 00 00                                  ...I...
[Oct 22 01:42:08 2020.10] Received packet: 0080 Handler: actor_died_or_disappeared
[Oct 22 01:42:08 2020.11] Player Disappeared: Неизвестный #150000 (0) Girl Knight (100, 9)
```

**Comment by jokinvipo** [comment]
Hello @ya4ept,

Yes im running at xKore 3 mode to bypass the client login,
To solve this problem can i simply use the function **teleportAuto_notPlayers** and add the **Player with ID 150000** or you recommend something else ?

**Comment by alisonrag** [comment]
hmmm, this should be a anti bot feature =p
this char dont exist and openkore is requesting info about

**Comment by jokinvipo** [comment]
Opa @alisonrag 

What should i do to bypass it ?

**Comment by sctnightcore** [comment]
@jokinvipo  Just ignore it

**Comment by alisonrag** [comment]
need to check issafequery or something like that in openkore, to avoid information query of undesirable units

**Comment by KagunyaIchito** [comment]
Try to use a GM command in your server

**Comment by dt1536** [comment]
> Opa @alisonrag
> 
> What should i do to bypass it ?

Hi are you still using openkore for OriginsRO?

**Comment by alisonrag** [comment]
specific server issue, openkore parse the info sent from server. if someone else want to ignore actor like this, just add the ID in the avoids.txt https://openkore.com/wiki/avoid.txt
