### ISSUE TITLE
the error message is: Attempt to STORE non blessed reference (or not a reference) Value: $VAR1 = undef;

### ISSUE THREAD

**Issue by ddd1155** [OpenKore/openkore#3297]
This program has encountered an unexpected problem. This is probably because of a recent server update, a bug in this
program, or in one of the plugins. We apologize for this problem. You may get support from IRC or the forums.
A detailed error report has been saved to errors.txt. Before posting a bug report, please try out the latest release
GIT version first. If you are already using the latest release GIT version, search the forums first to see if your
problem had already been solved, or has already been reported. If you truly believe you have encountered a bug in the
program, please include the contents of the errors.txt in your bug report
(https://github.com/openkore/openkore/issues), or we may not be able to help you!
The error message is:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = undef;
Press ENTER to exit this program.

**Comment by ddd1155** [comment]
Open with Start.exe

**Comment by ya4ept** [comment]
Need a little more information than just a mistake.
Use the template for creating a request

**Comment by ya4ept** [comment]
@sctnightcore why?

**Comment by alisonrag** [comment]
i guess this is related to charblocksize, and sct closed becaus this is related to new 175 charblocksize '-'
