### ISSUE TITLE
XSTool.dll  does not match  strawberryPerl

### ISSUE THREAD

**Issue by zzwyrmslayer** [OpenKore/openkore#3300]
I am using Windows 10. 
cRO server.
Due to the nprotect program,I only can run poseidon through perl.

I installed 64-bit ActivePerl  and When  I run poseidon.pl it shows as below.
![image](https://user-images.githubusercontent.com/20119492/97763562-ee068f00-1b46-11eb-8c85-ce3c5a20517b.png)
It says XSTool.dll is not valid win32 program. So I found that I should use a 32-bit version perl to run poseidon.pl.
But ActivePerl no more provide free 32-bit version, So I turn to 32bit strawberryPerl.
After all enviroment setup，I run poseidon.pl through 32bit strawberryPerl,it shows as below as can't find specified module.
![image](https://user-images.githubusercontent.com/20119492/97763806-b9470780-1b47-11eb-92bd-484f7fad174e.png)

I guess I need compile XSTools.dll for my own environment.How can I do that through 32bit strawberryperl?

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by ya4ept** [comment]
try just run `start-poseidon.exe`

**Comment by zzwyrmslayer** [comment]
> try just run `start-poseidon.exe`

Obviously can‘t.
nProtect will dectect start-poseidon.exe and shutdown ragexe

**Comment by ya4ept** [comment]
you should be using [perl version 5.12.3](http://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0.msi)

![изображение](https://user-images.githubusercontent.com/7117363/100809056-5d251b00-3446-11eb-841b-5065a97d6156.png)

**Comment by alisonrag** [comment]
or use this pull: #3138 and compile XSTools using any other perl version + any other python version.
recommended is:
perl 5.30 32bits + python 3.8
steps to recompile:
1 - open cmd as administrator
2 - go to openkore root folder
3 - type `gmake` then enter
new dlls will be generated at:
openkore\src\auto\XSTools

then u can run with the current perl version (5.30) 

dont forget that need to be 32 bits

**Comment by alisonrag** [comment]
issue "fixed" at #3138, just download some strawberry perl x86 + any python x86 and compile the dlls again as reported here:
https://github.com/OpenKore/openkore/issues/3300#issuecomment-736959726

this way only .pl will work
