### ISSUE TITLE
headgear.txt is not utf-8 encoded

### ISSUE THREAD

**Issue by ucodelukas** [OpenKore/openkore#3303]
you corrupted the headgear.txt by the last "fix"

i try to fix it

**Comment by ucodelukas** [comment]
���۽�Ÿ���   is not utf8

**Comment by ucodelukas** [comment]
i will delete every corrupted text now

**Comment by ya4ept** [comment]
@ucodelukas already fixed: #3276

**Comment by ucodelukas** [comment]
nope still iso

**Comment by ya4ept** [comment]
try this #3304

**Comment by ucodelukas** [comment]
confirmed working! :+1: 
headgears.txt: UTF-8 Unicode text
pls merge, will close after that

**Comment by alisonrag** [comment]
fixed at #3304
