### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ucodelukas** [OpenKore/openkore#3305]
I am about to port the buildscripts to python 3

i already manually rewrote them, any infos i need?

**Comment by sctnightcore** [comment]
https://www.scons.org/

**Comment by ucodelukas** [comment]
yeah? what about it? i know that are scons scripts...

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/pull/3138

already did this at this pull:
https://github.com/OpenKore/openkore/pull/3138

can use python 2.7 and 3+
also perl 5.12 until 5.30

**Comment by alisonrag** [comment]
fixed at #3138
