### ISSUE TITLE
Is there a Command to deal guild storage?

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3307]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 
all

* **Bug Report / Feature Request**:
By using cmd talknpc,  bot can open guild storage , but can't add item to it .Is there a Command to deal guild storage? I Searched commands.pm , but can't find any . 

* **Summary**:

**Comment by alisonrag** [comment]
nope, guild storage was never implemented in openkore.
if i'm not wrong only storage log is supported

**Comment by hubertyang88** [comment]
I see

**Comment by ya4ept** [comment]
don't these commands work?
https://openkore.com/wiki/Storage

**Comment by ya4ept** [comment]
RMS test:
```
c @gstorage
Guild storage opened.
storage

-------------------- Storage ---------------------
-- Usable --
1    Зеленое зелье x 90
2    Крылья мухи x 44
3    Корм питомцев x 50

-- Equipment --

-- Non-Usable --
0    Империум x 1

Capacity: 4/600
--------------------------------------------------
storage add 0 1
Storage Item Added: Unknown #321 (4) x 1 - Usable Special
Inventory Item Removed: Unknown #321 (0) x 1
storage get 1 10
Item added to inventory: Зеленое зелье (16) x 10 - Usable Heal
Storage Item Removed: Зеленое зелье (1) x 10
storage

-------------------- Storage ---------------------
-- Usable --
1    Зеленое зелье x 80
2    Крылья мухи x 44
3    Корм питомцев x 50
4    Unknown #321 x 1

-- Equipment --

-- Non-Usable --
0    Империум x 1

Capacity: 5/600
--------------------------------------------------
storage close
Storage closed.
Storage logged

```

**Comment by alisonrag** [comment]
they use a workaround in emulator to make this work, guild storage have exclusive packets

**Comment by ya4ept** [comment]
@hubertyang88 we need a test account

**Comment by hubertyang88** [comment]
sorry for the slow relay , I am quite busy lately ,  I will send an email to ya4ept@ya.ru about test account

**Comment by ya4ept** [comment]
@hubertyang88 its
http://ro.qiquanwl.com/download/game/default.html
???

**Comment by ya4ept** [comment]
`E1 09 04 00 01 00 00 00`
```perl
'09E1' => ['storage_item_add', 'a2 V', [qw(ID amount)]],
```

**Comment by hubertyang88** [comment]
I need to add this to ServerType0.pm?

**Comment by ya4ept** [comment]
no, there are many packages to check

**Comment by oa0405ao** [comment]
Does this feature work now?
