### ISSUE TITLE
timeout on mapserver

### ISSUE THREAD

**Issue by notekubs** [OpenKore/openkore#3312]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: private server

* **Bug Report / Feature Request**: timeout on map server

* **Summary**: can't connect to mapserver when i try to connect

picture : 
![image](https://user-images.githubusercontent.com/66195892/101272423-9353f900-37be-11eb-8926-c6d19fb9e7dd.png)
my exe : https://drive.google.com/file/d/1iQxiDvYUqL2zy52PdBNYirCiV4NfQiLF/view?usp=sharing
my server.txt : https://drive.google.com/file/d/1hwwEXkyf4uS1l5fMU21HQZubv2erQiyh/view?usp=sharing
website : https://discord.gg/hfR9nexCG4
register : http://www.noah-ro.com/register.php

**Comment by ya4ept** [comment]
https://openkore.com/wiki/Connectivity_Guide
