### ISSUE TITLE
packet error 

### ISSUE THREAD

**Issue by legokidd** [OpenKore/openkore#3313]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

![image](https://user-images.githubusercontent.com/29646314/101678465-f1236200-3a98-11eb-9c8d-473140900779.png)

**Comment by alisonrag** [comment]
0A18 is already implemented at official and kRO based servertypes
https://github.com/OpenKore/openkore/blob/574cd02b57f58c50afa00ab010e769702b227a89/src/Network/Receive/kRO/Sakexe_0.pm#L622
https://github.com/OpenKore/openkore/blob/afce5ff079cc0e131b6f9d10b15f094407f40323/src/Network/Receive/ServerType0.pm#L636

my guess is wrong recvpackets or wrong servertype (1 ~ 22)

and use template to open a issue

**Comment by Sarcasm11** [comment]
@legokidd hey man!. What type of WPE pro did you use to get the required info?

@alisonrag can you help me which wpe pro i need to use to get these? I tried my wpe pro and other wpe pro's that are modded but it seems it won't record the packets esp when i try to do the login thing in ragna then stop the time in wpe. nothng happens
master_version 22
version 1
serverType bRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders bRO
charBlockSize 147
pinCode 1
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1

**Comment by alisonrag** [comment]
7 days no reply
