### ISSUE TITLE
I need help alternative for WPE pro or any working WPE PRO ?

### ISSUE THREAD

**Issue by Sarcasm11** [OpenKore/openkore#3314]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:
 i used this https://github.com/OpenKore/openkore
* **Server**: 
 Private server Illusion of Loki
* **Bug Report / Feature Request**: 
 need help with WPE
* **Summary**:

Any one of you guys has a working WPE PRO ? I'm so confused why WPE PRO won't record packets anymore. I need the WPE PRO for me to get these desired infos:master_version 22
version 1
serverType bRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders bRO
charBlockSize 147
pinCode 1
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1

if possible can help me get server list? if not any tutorial aside from WPE or how to make WPE work.

website : https://illusionofloki.com/
server name : Illusion of Loki
IP : 51.79.164.136
port : 5300

**Comment by Sarcasm11** [comment]
the status when i run openkore.

Loading tables\MAPPROPERTY_INFO_id_handle.txt...
Loading tables\RO\statusnametable.txt...
Loading tables\skillsarea.txt...
Loading tables\skillsencore.txt...
Loading tables\RO\quests.txt...
Loading tables\effects.txt...
Loading tables\RO\msgstringtable.txt...
Loading tables\hateffect_id_handle.txt...
Loading tables\hateffect_name.txt...
Loading tables\item_stack_limit.txt...
Loading tables\ITEMOPTION_id_handle.txt...
Loading tables\item_options.txt...
Loading tables\title_name.txt...
Loading tables\achievement_list.txt...
[eventMacro] No control/eventMacros.txt file was found. Plugin disabled.
[eventMacro] Plugin unloading
Plugin eventMacro unloaded.

Generating session Admin Password...

Checking for new portals... none found


Connecting to Account Server...
Connecting (51.79.164.136:5300)... connected
Timeout on Account Server, reconnecting. Wait 48 seconds...
Disconnecting (51.79.164.136:5300)...disconnected

**Comment by alisonrag** [comment]
https://openkore.com/wiki/Main_Page
Take a look at private server secrion

**Comment by Sarcasm11** [comment]
thank you.! Will update you on this thread still. And ohh by the way. The client Illusion of Loki uses Gepard 3.0. So I doubt. But i will give it a try. Thank you.

**Comment by alisonrag** [comment]
gepard has strong encryption system, you will only can connect to this server if you have a solid knowleadge in reverse engineering

**Comment by Sarcasm11** [comment]
@alisonrag will this help in bypassing gepard ? 
![image](https://user-images.githubusercontent.com/58530202/101845817-936f4280-3b8a-11eb-934b-8f1405ff3fbd.png)

**Comment by alisonrag** [comment]
nope, this xRag is a tool to auto click and have some other features

**Comment by Sarcasm11** [comment]
Okay thanks. I had this since 2017. LOL

**Comment by Sarcasm11** [comment]
@alisonrag i tried for 2 days. I can't seem to know how to use the Microsoft network monitor? can u give me tips on how to record the packet for me to get the info for server version storage encrypt key and other stuff? :(

**Comment by Sarcasm11** [comment]
@alisonrag I'll be back soon. I'm currently self studying these : beginner guide to game hacking
Beginners guide to reverse engineering
Anti-debug anticheat and Kernel Mode
also will learn C++.

I will be back 2 years from now and will definitely help the community.

**Comment by alisonrag** [comment]
> @alisonrag I'll be back soon. I'm currently self studying these : beginner guide to game hacking
> Beginners guide to reverse engineering
> Anti-debug anticheat and Kernel Mode
> also will learn C++.
> 
> I will be back 2 years from now and will definitely help the community.

i hope u can study and work in it, this days there is no one able to bypass gepard

**Comment by alisonrag** [comment]
issue not related to openkore

**Comment by ryosz** [comment]
Its been 2 years.. Where is he?

**Comment by Cryptologism** [comment]
LoL
