### ISSUE TITLE
openkore does not recognize characters

### ISSUE THREAD

**Issue by Sensuii** [OpenKore/openkore#3325]
![Screenshot_1](https://user-images.githubusercontent.com/62197420/102381302-cd37b300-3fa7-11eb-9bd4-5c0cc3617f39.png)
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:
my openkore doesn't recognize the account characters, the name appears as 0, and the rest is all wrong,

**Comment by alisonrag** [comment]
its seem like wrong charblocksize 
take a look at:
https://openkore.com/wiki/CharBlockSize


also will be good take a look at private server section
https://openkore.com/wiki/Main_Page

**Comment by Sensuii** [comment]
i tried all from 106 to 128 and none works,but the 116 show this error instead of show character list
![Screenshot_3](https://user-images.githubusercontent.com/62197420/102397671-f4e54600-3fbc-11eb-8a9e-bc2df2f2204a.png)

**Comment by Sensuii** [comment]
the client date is Jan/22/2008

**Comment by alisonrag** [comment]
also will be better if u add a console log using this in config.txt:
debugPacket_received 2

**Comment by Sensuii** [comment]
searching in google i found a solution here https://github.com/OpenKore/openkore/issues/2827 ,the issue is exactly the same as mine,and it was you who found the solution kkkk,thanks
