### ISSUE TITLE
character dont attack

### ISSUE THREAD

**Issue by Sensuii** [OpenKore/openkore#3326]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:
 openkore dont attack any monsters,only walk,and when i click on monster nick the openkore show this on print

**Comment by Sensuii** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/62197420/102666185-18e38b80-4165-11eb-918f-db43e329a4f4.png)

**Comment by griffinxs** [comment]
I also have the same problem, I've done several searches and I can't find anything. Openkore is displaying monsters as players and this makes it impossible for him to attack.

**Comment by KagunyaIchito** [comment]
Which serverType is u using?
Maybe need add on receive 'attack' packet but the monstet must disappear from the monster list

**Comment by alisonrag** [comment]
this seems a wrong servertype setup
