### ISSUE TITLE
The latest betterRA terminal cannot be accessed offline. Do you have a solution?

### ISSUE THREAD

**Issue by polme32** [OpenKore/openkore#3328]
Here is a link to the server for you to test. 
Https://pan.baidu.com/s/1SxzxQ1ZWPT4QhKvgGoWbNw extraction code: fak4

**Comment by alisonrag** [comment]
Can you elaborate better?

**Comment by polme32** [comment]
ff

**Comment by polme32** [comment]
@alisonrag Unknown encryption method, unable to log in to the server through servers.txt，
It is controlled by the file BetterRA.dll. If you delete it, the client will not be able to start it.

**Comment by polme32** [comment]
Maybe this is a new encryption method. Can anyone try to solve this problem?

**Comment by alisonrag** [comment]
duplicated of #3352
