### ISSUE TITLE
Private Server: does not recognize monsters

### ISSUE THREAD

**Issue by griffinxs** [OpenKore/openkore#3332]
Openkore recognizes monsters as players. What do I do?

https://imgur.com/a/Ej6t52y

`[Ragnaruto]
ip 45.61.143.117
port 6900
master_version 15
version 23
serverType kRO_Sakexe_2008_03_18a
charBlockSize 108
serverEncoding Western
recvpackets recvpackets.txt
addTableFolders iRO`

**Comment by alisonrag** [comment]
duplicated of #3326

**Comment by griffinxs** [comment]
Não acho que o erro dele seja o mesmo que o meu, mas enfim.. Consegue nos ajudar de algum jeito?

**Comment by griffinxs** [comment]
I don't think his mistake is the same as mine, but anyway ... Can you help us in any way?
