### ISSUE TITLE
globals.pm not found

### ISSUE THREAD

**Issue by allanwiki2** [OpenKore/openkore#3334]
Openkore version git: NEWEST (on github)
Server: BRO
Bug Report / Feature Request:
Summary:

i lost my pin code and now i am trying to brute it, i found 2 brute scripts in perl for openkore, but when i try to run them i receive this error (both of them)

Can't locate Globals.pm in @INC (@INC contains: C:\Users\Pichau\AppData\Local\Temp\pdk-Pichau-18200\ .) at pin.pl line 20.
BEGIN failed--compilation aborted at pin.pl line 20.

Press ENTER to exit.

**Comment by alisonrag** [comment]
you are doing this wrong as i can see you are executing the script instead of download it and load in openkore

**Comment by allanwiki2** [comment]
this script is made to brute the pin, how could i load it in openkore if idk the pin?

**Comment by alisonrag** [comment]
seems like u did not understant what the process behind of openkore/plugin
so i will make a step by step to you
1 - download and extract openkore https://github.com/OpenKore/openkore/archive/master.zip
2 - save this plugin as pinBreaker at openkore/plugins folder (https://raw.githubusercontent.com/andyfoss/plugins-openkore/master/by_me/pinBreaker/pinBreaker.pl)
3 - go to sys.txt at openkore/control folder and add pinBreaker to `loadPlugins_list`
`loadPlugins_list pinBreaker`
4 - go to config.txt at openkore/control folder and set loginPinCode 0000
5 - then execute openkore using start.exe or wxstart.exe
6 - select bRO server, and fill your login/password when console ask for it
7 - wait in loginscreen until script stop
8 - when u are able to select the char your pin will be at config.txt in `loginPinCode`
