### ISSUE TITLE
Packet Tokenizer: Unknown switch: 0B1D

### ISSUE THREAD

**Issue by Alkaster** [OpenKore/openkore#3337]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
 find Version git :[GitHub hash](https://github.com/OpenKore/openkore/wiki/How-to-check-version-git-you-bot.)-->
* **Server**: 

* **Bug Report / Feature Request**:
buenas compañeros tengo problema con Packet Tokenizer: Unknown switch: 0B1D en un servertype iRO_Renewal
good fellows I have problem with Packet Tokenizer: Unknown switch: 0B1D in an iRO_Renewal servertype
What can be?
* **Summary**:

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore/pull/3284

ya

**Comment by KagunyaIchito** [comment]
You can close issue now

**Comment by Alkaster** [comment]
se puede borrar , no lo solucione pero vi que el problema era otro
