### ISSUE TITLE
Can't reconstruct unknown packet

### ISSUE THREAD

**Issue by noobie90** [OpenKore/openkore#3339]
[errors.txt](https://github.com/OpenKore/openkore/files/5855670/errors.txt)

* **Openkore version git**: 

* **Server**: kRO

* **Bug Report / Feature Request**: Can't reconstruct unknown packet

* **Summary**: Can anyone help me? I got this error message Can't reconstruct unknown packet: client_hash at src/Network/PacketParser.pm line 180. Any idea what went wrong?

**Comment by alisonrag** [comment]
can you post your servers.txt?

you can hide ip, port, server name
