### ISSUE TITLE
Character stop attack because of a infinity looping in teleport task

### ISSUE THREAD

**Issue by vegger93** [OpenKore/openkore#3341]
Server: bRO
Apparently with no obvious reason my bot "freezes" and stay there until the dead. Even when I use console commands like "ai clear", "ai off", "ai on" nothing happens. But sometimes when I force his attack with xkore 1 back to normal and get disconnect then.

**Comment by alisonrag** [comment]
when this happens type in console:
`conf debug 2`

and send the log here

**Comment by vegger93** [comment]
> when this happens type in console:
> `conf debug 2`
> 
> and send the log here

[Feb 06 22:30:01 2021.40] Received packet: 0095 Handler: actor_info
[Feb 06 22:30:01 2021.41] Received object info: Louva-a-Deus
[Feb 06 22:30:01 2021.41] Monster Info: Louva-a-Deus (1)
[Feb 06 22:30:01 2021.41] Sent Teleport
[Feb 06 22:30:01 2021.44] Sent Teleport
[Feb 06 22:30:01 2021.47] Sent Teleport
[Feb 06 22:30:01 2021.50] Sent Teleport
[Feb 06 22:30:01 2021.54] Sent Teleport
[Feb 06 22:30:01 2021.57] Received packet: 0196 Handler: actor_status_active
[Feb 06 22:30:01 2021.57] Received packet: 0196 Handler: actor_status_active
[Feb 06 22:30:01 2021.57] Sent Teleport
[Feb 06 22:30:01 2021.60] Sent Teleport
[Feb 06 22:30:01 2021.63] Sent Teleport
[Feb 06 22:30:01 2021.66] Received packet: 0088 Handler: actor_movement_interrupted
[Feb 06 22:30:01 2021.67] Sent Teleport
[Feb 06 22:30:01 2021.70] Sent Teleport
[Feb 06 22:30:01 2021.74] Sent Teleport
[Feb 06 22:30:01 2021.77] Sent Teleport
[Feb 06 22:30:01 2021.80] Received packet: 02E1 Handler: actor_action
[Feb 06 22:30:01 2021.80] [ 99/100] Monster Louva-a-Deus (0) attacks you (Dmg: Miss!) (Delay: 660ms)
[Feb 06 22:30:01 2021.80] Sent Teleport
[Feb 06 22:30:01 2021.83] Sent Teleport
[Feb 06 22:30:01 2021.86] Sent Teleport
[Feb 06 22:30:01 2021.90] Sent Teleport
[Feb 06 22:30:01 2021.93] Sent Teleport
[Feb 06 22:30:01 2021.96] Received packet: 0196 Handler: actor_status_active
[Feb 06 22:30:01 2021.96] Received packet: 0983 Handler: actor_status_active
[Feb 06 22:30:01 2021.96] Received packet: 0983 Handler: actor_status_active
[Feb 06 22:30:01 2021.97] Sent Teleport
[Feb 06 22:30:02 2021.67] Sent Teleport
[Feb 06 22:30:02 2021.32] Sent Teleport
[Feb 06 22:30:02 2021.62] Sent Teleport
[Feb 06 22:30:02 2021.10] Received packet: 0983 Handler: actor_status_active
[Feb 06 22:30:02 2021.11] Sent Teleport

Isso acontece mesmo estando com equipamento com teleporte equipado e em mapa com monstros agressivos, mapa de bicho passivo raramente isso ocorre
