### ISSUE TITLE
Remove everything related to defunct servers

### ISSUE THREAD

**Issue by farrainbow** [OpenKore/openkore#335]
- [ ] rRO is closed.
- [ ] is aRO closed?
- [ ] is pRO closed?
- [ ] is mRO closed?

But we should keep human-readable strings like item and map names, maybe.

**Comment by Cozzie** [comment]
You can make a PR for this. Nothing major that needs to be discussed outside a PR.

**Comment by kaliwanagan** [comment]
I think this is still a valid issue :P

**Comment by alisonrag** [comment]
fixed in #2993
