### ISSUE TITLE
NovaRo Server Selection

### ISSUE THREAD

**Issue by PrensCin** [OpenKore/openkore#3350]
Hi!
im newbie i need openkore server selection need Novaro please help me how can i do
![Novaroyokaq](https://user-images.githubusercontent.com/79111877/107987830-c812d680-6fdf-11eb-8812-c240ee1f84a7.jpg)

**Comment by alisonrag** [comment]
novaRO use ragnashield as anticheat, custom login packet and custom packet encrypt

**Comment by rennosoares** [comment]
And what can i do to bypass this?
