### ISSUE TITLE
A problem with being unable to access the server

### ISSUE THREAD

**Issue by polme32** [OpenKore/openkore#3352]
I try to use a different account to access the server, but the length of 0064 becomes 75, and the position after 55 bits changes every time. How can I get into this server?

![111](https://user-images.githubusercontent.com/48077963/108226929-4f934d80-7178-11eb-8bf2-2aa4de5f3fae.png)

**Comment by polme32** [comment]
![JZ2EHS%EM %2V9YXP@IV)WY](https://user-images.githubusercontent.com/48077963/108226428-deec3100-7177-11eb-88ed-e7508c5d2404.png)

**Comment by sctnightcore** [comment]
server url ?

**Comment by polme32** [comment]
> 服务器网址？
is this?

[RO-xiang]
ip 47.99.177.245
port 6909
master_version 4
version 20
serverType kRO_RagexeRE_2018_06_21a
serverEncoding Simplified Chinese
charBlockSize 155

**Comment by sctnightcore** [comment]
> > 服务器网址？
> > is this?
> 
> [RO-xiang]
> ip 47.99.177.245
> port 6909
> master_version 4
> version 20
> serverType kRO_RagexeRE_2018_06_21a
> serverEncoding Simplified Chinese
> charBlockSize 155


I think i need full client .
for test.

**Comment by polme32** [comment]
OK,please wait

**Comment by polme32** [comment]
https://drive.google.com/file/d/1NOj_N4Ki2J50AxqiBFvx5__on4SKzeNH/view?usp=sharing

**Comment by alisonrag** [comment]
what is the dll that if u remove u cant login?

**Comment by polme32** [comment]
The dll does not exist on this client.

**Comment by polme32** [comment]
> 如果你删除你不能登录的DLL是什么？



[BetterRA.zip](https://github.com/OpenKore/openkore/files/6006847/BetterRA.zip)
This is from another server.

**Comment by alisonrag** [comment]
> > 如果你删除你不能登录的DLL是什么？
> 
> [BetterRA.zip](https://github.com/OpenKore/openkore/files/6006847/BetterRA.zip)
> This is from another server.

this dll is packed with somekind of safeguard software, the code that i can see get some info from adapters and calc md5 before send it

**Comment by polme32** [comment]
At present, most GM in China use this to set up private servers. It is very difficult for openkore to get in. I feel very troubled. Is there anything you can do about it?

**Comment by polme32** [comment]
> > > 服务器网址？ is this?
> > 
> > 
> > [RO-xiang] ip 47.99.177.245 port 6909 master_version 4 version 20 serverType kRO_RagexeRE_2018_06_21a serverEncoding Simplified Chinese charBlockSize 155
> 
> I think i need full client .
> for test.
> 
> Can u upload to google driver ? or something better ?
> not baidu ?
Excuse me？

**Comment by chrislong93** [comment]
I have similar problem

![image](https://user-images.githubusercontent.com/26244945/121004453-e97b1680-c7b8-11eb-82fd-bb05ad993740.png)

This server, presumably official - run by a Vietnamese game distributor, is run through a **custom client** where you login ID & Password using a Patcher window, then the original client will showup and you just need to choose server and character.

Nevertheless, I applied the same technique where I find "eth contains xxx" and found this **IP & Port** 

![image](https://user-images.githubusercontent.com/26244945/121004794-4b3b8080-c7b9-11eb-84b4-a8de9a4903a8.png)

but with the version **and** **master_version**, its kinda odd:

![image](https://user-images.githubusercontent.com/26244945/121004893-673f2200-c7b9-11eb-9bdd-32b590d39f15.png)

Please kindly help me

**Comment by alisonrag** [comment]
last request of this topic is related to vRO, the login was implemented at: #3453
