### ISSUE TITLE
How to use any sub found in src?

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3359]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:
I can use some function by eval , such as eval ai_route(0, 100, 85, attackOnRoute => 2),where can I find all subs can be used like this?
For those can't  , such as sub in src\network\Send.pm::sendMove() , how can I make it useable for eval?
* **Summary**:

**Comment by alisonrag** [comment]
it depends a lot, some functios i just necessary to call, like ai / task function.
to use network related functions u will need to use `$messageSender` for send functions and `$packetParser` to receive messages
example:
```eval $messageSender->sendMove(100, 85)```

**Comment by hubertyang88** [comment]
Thanks ! it's really helpful ! 
Now I don't have to use  "do send 5f 03 19 44 90" when I need op to move some point straight , sometimes, ai_route like to take Detour .
