### ISSUE TITLE
monsters name problem of lastest version

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3361]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
Latest 
* **Server**: 
cro
* **Bug Report / Feature Request**:
something wrong with mon name
when set in mon_control
1081 0 0 0
kore will leave Yellow Plant alone
but when set
黄草 0 0 0 #“Yellow Plant 0 0 0”
kore will attck Yellow Plant , monsters name don't work

this also affect attackSkillSlot when use monsters name ,  only monster ID works

attackSkillSlot skills {
	lvl 2
	dist 1
	maxDist 3
	whenStatusInactive status
	monsters 1113,1009,1049
	timeout 2
}

Strangely , name of some new event monster works , kore didn't read monsters.txt only read new monsters ?
#3299  is this same problem?
* **Summary**:

**Comment by alisonrag** [comment]
just to have sure, can u delete the monsters.txt?

**Comment by alisonrag** [comment]
can u add this line at CoreLogic line 3074
```message "we are trying to check : " . $monster->{name} . " \tlc: ".lc($monster->{name})." \tID: ".$monster->{nameID}."\n";```

![image](https://user-images.githubusercontent.com/10372732/109331097-2db25e80-783b-11eb-9b16-47e5ce293e43.png)

and send log here?

**Comment by alisonrag** [comment]
you will see messages like this:
![image](https://user-images.githubusercontent.com/10372732/109331427-9699d680-783b-11eb-828d-6dd402d0931b.png)

**Comment by alisonrag** [comment]
also send your mon_control here

**Comment by hubertyang88** [comment]
As your request , I remove monsters.txt , and run kore , this file is generated again , see zip file , console and mon_control included.
[mon.zip](https://github.com/OpenKore/openkore/files/6053340/mon.zip)
In console , same monster first check -1 and then check 1.  As I set in mon_control, non of those mons should be killed twice.
For 2218 event monser , always check -1, kore seems ok with this one...
