### ISSUE TITLE
Openkore dont recognize new character after creation

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#3362]
* **Openkore version git**: 
https://github.com/OpenKore/openkore/commit/0655655fd3d07165057f86f6e605ea9ed5741c0b
* **Server**: 
tested in tRO but should be the same to all the other servers
* **Bug Report / Feature Request**:
Bug Report:
* **Summary**:
Openkore dont recognize new character after creation and if u select this character will lead to a error after map_login

error at:
https://github.com/OpenKore/openkore/blob/0655655fd3d07165057f86f6e605ea9ed5741c0b/src/Network/Receive.pm#L1178

**Comment by ya4ept** [comment]
I have seen this behavior on other servers (xKore 1)
