### ISSUE TITLE
I can't buy an arrow from a new NPC in prontera city, npc prt_in 162 135 clip is not correct, can anyone know, can you tell me? 

### ISSUE THREAD

**Issue by pdtong** [OpenKore/openkore#3370]
buyAuto Arrow {
	npc prt_in 162 135
	npc_steps c r0 
	isMarket 0
	standpoint
	distance 9
	price
	minAmount 50
	maxAmount 3000
	batchSize
	disabled 0
	maxBase
	minBase
}

**Comment by ya4ept** [comment]
similar questions should be asked on the forum

**Comment by alisonrag** [comment]
can u take a screenshot of npc seel list and send here?
