### ISSUE TITLE
Cannot Load Server message for server type "RagexeRE"

### ISSUE THREAD

**Issue by noobie90** [OpenKore/openkore#3378]
* **Private Server**
* **Bug Report / Feature Request**:
Cannot Load Server message for server type "RagexeRE"

* **Summary**:
Using PEViewer the date stamp is July 21, 2010. As advice If there is no file with exact compilation date, try the ones near to that date, or the latest available, and I did that, however the error of Cannot Load Server message for server type "RagexeRE" showed up.

Any way I can fix this?

**Comment by alisonrag** [comment]
paste your servers.txt here

**Comment by alisonrag** [comment]
maybe your servertype is wrong, try this:
`serverType kRO_RagexeRE_2010_11_24a`

**Comment by noobie90** [comment]
> maybe your servertype is wrong, try this:
> `serverType kRO_RagexeRE_2010_11_24a`

Tried it, and this shows up "Packet Tokenizer: Unknown switch: ABCD"

**Comment by alisonrag** [comment]
try:
`addTableFolders kRO/RagexeRE_2010_11_24a;kRO`

**Comment by sctnightcore** [comment]
> > maybe your servertype is wrong, try this:
> > `serverType kRO_RagexeRE_2010_11_24a`
> 
> Tried it, and this shows up "Packet Tokenizer: Unknown switch: ABCD"


ABCD = gepard
