### ISSUE TITLE
poseidon problem on CRO: Illegal program detected

### ISSUE THREAD

**Issue by dongzhuming** [OpenKore/openkore#3383]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2ef3b6d

* **Server**:  cRO

* **Bug Report / Feature Request**: Illegal program detected by gameguard

* **Summary**:
Firstly, I feel appreciate to all of the developers' sharing. You did great job!
I tried deploying the Poseiden and OpenKore on a cloud server, and open RO client to communicate with it. the sad news is "Illegal program detected" will be prompted and meanwhile the connection to poseiden server breaks.  
Not sure if this is a known issue since I'm new here. Search the discussion topic in Issues but most of them may be out-of-date.  
BTW, for cRO servertype, the charBlockSize should be assigned as 155 instead of 147. It seems working, but is in a short while.
If any discussion available, I hope to join that and provide my network packets. Thank you all!

**Comment by dongzhuming** [comment]
After 2 times of game guard sync, illegal program detected. So I guess GG is able to analysis the packet.
![image](https://user-images.githubusercontent.com/11461984/113171026-b298f980-9279-11eb-99fd-b9ffadca9f78.png)

**Comment by alisonrag** [comment]
some thing before to start:
1 - openkore/poseidon cant be run in the same ragexe/nprotect enviroment
2 - nprotect detect if u change the ip in clientinfo.xml to a local network (192.168.x.x. 10.0.x.x)
3 - cRO server info/tables is outdated

about illegal program:
https://github.com/OpenKore/openkore/issues/3092

**Comment by dongzhuming** [comment]
> some thing before to start:
> 1 - openkore/poseidon cant be run in the same ragexe/nprotect enviroment
> 2 - nprotect detect if u change the ip in clientinfo.xml to a local network (192.168.x.x. 10.0.x.x)
> 3 - cRO server info/tables is outdated
> 
> about illegal program:
> #3092

for the 3rd condition, how to check if it is outdated? I have alread updated the code from GitHub, and change charBlockSize from 147 to 155.  Appreciate to your kindly response.

**Comment by alisonrag** [comment]
> for the 3rd condition, how to check if it is outdated? I have alread updated the code from GitHub, and change charBlockSize from 147 to 155. Appreciate to your kindly response.

3rd option means that no one developer updated the cRO files u can check the git blame on cRO files or search for cRO in "pull request" tab
https://github.com/OpenKore/openkore/pulls?q=is%3Apr+is%3Aclosed+cRO

**Comment by dongzhuming** [comment]
> > for the 3rd condition, how to check if it is outdated? I have alread updated the code from GitHub, and change charBlockSize from 147 to 155. Appreciate to your kindly response.
> 
> 3rd option means that no one developer updated the cRO files. (last update 2020-02-27)
> You can check the git blame on cRO files or search for cRO in "pull request" tab
> https://github.com/OpenKore/openkore/pulls?q=is%3Apr+is%3Aclosed+cRO

in servertypes.txt, I could find cRO_2017-12-13a, so is it the only way for me to start Poseidon by the following way:  

`
cd src/Poseidon/`   
`perl ./poseidon.pl --server_type=cRO_2017-12-13a --ragnarokserver_ip=xxx.xxx.xxx.xxx --debug=on
`
Not sure if the server_type is already outdated.

**Comment by dongzhuming** [comment]
![image](https://user-images.githubusercontent.com/11461984/113323528-a3cd4800-9348-11eb-88a5-f9e19988d50e.png)
here is the XML file, I modified etc/hosts mapping roserver.com to my Poseiden server. But still illegel program detected in two minutes.
