### ISSUE TITLE
Unknown Status 993 and 994 please help

### ISSUE THREAD

**Issue by khelpogi** [OpenKore/openkore#3384]
Hi Sirs

Please help on the UNKNOWN_STATUS_993 and 994 its keeps  my openkore  disconnected

thanks for the help

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by alisonrag** [comment]
UNKNOWN_STATUS_993 and 994 there is no relation to DC as u can see here in this screenshot the bot is running even receiving this status:
![image](https://user-images.githubusercontent.com/10372732/113300367-3a135680-92d4-11eb-90c1-1a0f0aae6ea7.png)

looking at your last comment you are trying to run openkore in a server that use EAC as anticheat, as u can see openkore dont have official support this kind of server

**Comment by ya4ept** [comment]
these statuses appear every time the player changes maps:
```
UNKNOWN_993 Invulnerability
UNKNOWN_994 Stop
```

**Comment by khelpogi** [comment]
ithink i  have a problem with my poseidon
![image](https://user-images.githubusercontent.com/81727016/113381312-399cbd80-93b1-11eb-8d50-e8240eda757c.png)

**Comment by khelpogi** [comment]
what is the servers that the openkore is allowed?? thanks
