### ISSUE TITLE
[Anti-bot] Help get disguised monster ID

### ISSUE THREAD

**Issue by polme32** [OpenKore/openkore#3385]
Recently ran into a verification, will change the role of the model, and then choose an answer to choose, please help me

**Comment by alisonrag** [comment]
your issues dont make sense.
can you use the issue template? this is there for a reason.
1 day to close if you don't rewrite this.

**Comment by polme32** [comment]
> 你的问题没有道理。
> 您能使用问题模板吗？这是有原因的。
> 如果你不重写这个，一天就结束了。
i'm sorry,
I can only rely on translation, and I can't understand what the specific format is, and then the problem I ask for is that the ID, that gets the model of its own character now only finds char- > {name}.

**Comment by alisonrag** [comment]
own char ID is at:
`$char->{charID}`

own account ID is at:
`$accountID`

would be better if you try to explain or give us some examples that what you are trying to do

**Comment by polme32** [comment]
$accountIDI don't think it's what I want.，but charID I don't think it's what I want.。
During verification, the character will become a monster model, and I need to obtain the ID before I can make a choice.

**Comment by polme32** [comment]
![111](https://user-images.githubusercontent.com/48077963/113483904-3f40f300-94d8-11eb-8614-48e165b53e39.png)

**Comment by alisonrag** [comment]
try in config.txt:
debugPacket_received 2

but if i'm not wrong it is `$char->{jobID}`, but a packet log will help

**Comment by polme32** [comment]
jobID Tested, not，
I'll test config again.

**Comment by polme32** [comment]
[ku.txt](https://github.com/OpenKore/openkore/files/6253022/ku.txt)

It was triggered once, but I couldn't find any useful information.

**Comment by ya4ept** [comment]
```
[ 验证系统 ] 请在2分钟内验证
* 请不要点击取消或强行关闭游戏
* 否则判定验证失败并记录次数
> 2次机会选择 您变成了什么魔物：
```
```
#  Response
0  库克雷
1  溜溜猴
2  摩卡
3  盗虫
4  蛋壳小鸡
5  红草
6  [审判者]索菲娅
7  无颅武士
8  白素贞
9  鸟人哈比
10 Cancel Chat
```

**Comment by polme32** [comment]
yes,There is no hint on openkore, only the transformation of characters can be seen in the game screen.

**Comment by alisonrag** [comment]
i think it is before of freeze, client dont do the things if server dont ask for it

**Comment by polme32** [comment]
After testing and triggering, the character will be identified as a monster. And write it to monsters.txt. Is there any other way to get the name of the strange object it becomes?

**Comment by ya4ept** [comment]
I think that this issue needs to be resolved not here, but on the forum

**Comment by hubertyang88** [comment]
When char disguised , use cmd s check status , there might be unknow status number , figure out all monster listed , and then use macro to deal with it.
in chinese， 出现伪装状态时，用 S 命令在openkore中看人物状态，也许会有一个对应的装扮状态 ， 未知的状态xxx号，找到所有的装扮号，用macro来选择对话

**Comment by hubertyang88** [comment]
about issue template 
关于问题模板，你发问题的时候，问题窗口默认会有很预制的英文在里面，你大概都直接删除了，那些就是模板，写在哪行，你可以用 Preview 看看预览效果 ， 问题应该包括 版本 哪个服务器 等等信息

**Comment by alisonrag** [comment]
this is not a openkore issue, @hubertyang88  already gave you some hint

if you have some other question use:
forums.openkore.com
