### ISSUE TITLE
Bot for arcane ro? ph

### ISSUE THREAD

**Issue by emzky08** [OpenKore/openkore#3388]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by emzky08** [comment]
Can someone config for arcane ro ph server

**Comment by alisonrag** [comment]
if is this server:
https://www.facebook.com/ArcaneRagnarokOnline/

this use gepard and openkore dont have support to servers that use gepard shield
