### ISSUE TITLE
ShieldRO (RagexeRE_2018_04_18a) - Disconnect after public chat (c <chat>)

### ISSUE THREAD

**Issue by Razalka** [OpenKore/openkore#3389]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: Latest

* **Server**: **iRO**

* **Bug Report / Feature Request**: 

* **Summary**: disconnected after trying to chat in public.
*   [
![image](https://user-images.githubusercontent.com/25100730/114265880-74d86580-9a1d-11eb-984c-7a1e6eeb17ff.png)
](url)

**Comment by ya4ept** [comment]
Renewal, Transcendence or Sakray?

**Comment by Razalka** [comment]
> Renewal, Transcendence or Sakray?

Sakray.
Maybe the recvpackets ?
Is there any updated way to extract the recvpackets from unpacked client ? Because PEEK is outdated.

**Comment by alisonrag** [comment]
this is not iRO, this is some private server configured using iRO as servertype.

iRO is the worst servertype to try in a private server, their have a lot of random shuffled packets.

try to setup using kRO_RagexeRE_XXXX_XX_XX

**Comment by Razalka** [comment]
> this is not iRO, this is some private server configured using iRO as servertype.
> 
> iRO is the worst servertype to try in a private server, have a lot of random shuffled packets.
> 
> try to setup using kRO_RagexeRE_XXXX_XX_XX

Yup, you're right.
This is private server using iRO as servertype, I also tried used the latest kRO_RagexeRE_XXX as listed on OP,it's worked, but the only problem here is the recvpackets, after used the public chat, got dc same as picture above.

The PSRO used the newest client, maybe 2019/2020, they fake the exe header (1970/01/01).
The client also unpacked & uncrypted, no eac, gg, gepard either on this server.

Any suggestion to extract the recvpackets from newest client like 2019/2020?

**Comment by Razalka** [comment]
> this is not iRO, this is some private server configured using iRO as servertype.
> 
> iRO is the worst servertype to try in a private server, have a lot of random shuffled packets.
> 
> try to setup using kRO_RagexeRE_XXXX_XX_XX

Using kRO_RagexeRE_X (2018-2020) with RagexeRE_2018_06_21a recvpackets/tables.

![image](https://user-images.githubusercontent.com/25100730/114289987-3fc42580-9aa6-11eb-8501-c1a252906eac.png)

**Comment by alisonrag** [comment]
can u give the server information?
i can delete after test if you want

**Comment by Razalka** [comment]
> can u give the server information?
> i can delete after test if you want

**shieldragnarok.com**

# SHIELD
[ShieldRO]
ip 103.140.55.103
port 6900
master_version 12
version 55
serverType XXXXXXXXXX
serverEncoding Western
charBlockSize 155
addTableFolders kRO/RagexeRE_2018_06_21a;translated/kRO_english;kRO

**Comment by alisonrag** [comment]
```
[ShieldRO]
ip 103.140.55.103
port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2018_04_18a
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders kRO/RagexeRE_2018_04_04b;iRO/official;iRO
charBlockSize 155
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1
```


![image](https://user-images.githubusercontent.com/10372732/114293666-6a928780-9a6e-11eb-91d0-01fcce8d108b.png)

**Comment by Razalka** [comment]
> use this pull request:
> #3390
> 
> use this info in servers.txt:
> 
> ```
> [ShieldRO]
> ip 103.140.55.103
> port 6900
> master_version 12
> version 55
> serverType kRO_RagexeRE_2018_04_18a
> serverEncoding Western
> gameGuard 0
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> addTableFolders kRO/RagexeRE_2018_04_04b;iRO/official;iRO
> charBlockSize 155
> pinCode 0
> charDeleteDateType 1
> rankingSystemType 1
> private 1
> ```
> 
> result:
> ![image](https://user-images.githubusercontent.com/10372732/114293666-6a928780-9a6e-11eb-91d0-01fcce8d108b.png)

is there any explanation how to get the detail info as you mentioned ?

**Comment by Razalka** [comment]
> use this pull request:
> #3390
> 
> use this info in servers.txt:
> 
> ```
> [ShieldRO]
> ip 103.140.55.103
> port 6900
> master_version 12
> version 55
> serverType kRO_RagexeRE_2018_04_18a
> serverEncoding Western
> gameGuard 0
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> addTableFolders kRO/RagexeRE_2018_04_04b;iRO/official;iRO
> charBlockSize 155
> pinCode 0
> charDeleteDateType 1
> rankingSystemType 1
> private 1
> ```
> 
> result:
> ![image](https://user-images.githubusercontent.com/10372732/114293666-6a928780-9a6e-11eb-91d0-01fcce8d108b.png)





Thanks, it worked after used the pull request #3390.

But here's the same problem with another server.

**Server : kRO/Renewal**
**Client Stamp : 26/03/2020**
I tried used #3390 to another server **[http://circleragnarok.net/]**

[CircleRagnarok]
ip 103.52.146.53
port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2018_04_18a
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2018_04_04b;iRO/official;iRO
charBlockSize 155
pinCode 1
charDeleteDateType 1
rankingSystemType 1
private 1

Logged-in and many unknown packets shown.
and also the npc name y,y , like it's undefined.

![image](https://user-images.githubusercontent.com/25100730/114295318-bd9c2700-9ace-11eb-990d-7ca636d169b3.png)

But,
I tried to used iRO servertype again and there's no unknown packets, but the public chat back to error, disconnected after using public chat.
![image](https://user-images.githubusercontent.com/25100730/114295246-32229600-9ace-11eb-9582-b1d2ceb930f3.png)

**Comment by alisonrag** [comment]
paste this recvpackets at `tables/kRO/RagexeRE_2020_07_09a`:
https://github.com/OpenKore/openkore/blob/f68a09546cff7f654847e0013d49fd5565b297e0/tables/kRO/RagexeRE_2020_07_09a/recvpackets.txt

and try:
```
[CircleRagnarok]
ip 103.52.146.53
port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2020_03_04a
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2020_07_09a;iRO/official;iRO
charBlockSize 155
pinCode 1
charDeleteDateType 1
rankingSystemType 1
private 1
```

**Comment by alisonrag** [comment]
final version:
```
[CircleRagnarok]
ip 103.52.146.53
port 6900
OTT_ip 103.52.146.53
OTT_port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2020_03_04a
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2020_07_09a;iRO/official;iRO
charBlockSize 155
pinCode 1
charDeleteDateType 1
rankingSystemType 1
private 1
```
