### ISSUE TITLE
Error Code 10060, Unable to Connect

### ISSUE THREAD

**Issue by faiyazsayyed** [OpenKore/openkore#3408]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

![image](https://user-images.githubusercontent.com/82838526/115286470-b929db00-a16c-11eb-9da7-27841cdf0fff.png)

kRO Based Private Server
[Equate Ragnarok]
ip 51.79.240.138
port 6900
version 55
master_version 01
serverType kRO_RagexeRE_2018_04_18a
serverEncoding Western
addTableFolders translated/kRO_english;kRO

I am not sure about the ServerType so i used kRO_RagexeRE_2018_04_18a

Please assist, i am completely noob.

**Comment by faiyazsayyed** [comment]
Also if i change the Port from 6900 to 9443 then i get the below error.

![image](https://user-images.githubusercontent.com/82838526/115287416-e034dc80-a16d-11eb-9970-a6caebd5ad93.png)

Kindly Help Please.

**Comment by alisonrag** [comment]
> ## ------------------ Openkore Issues Template ------------------
> * **Openkore version git**:
> 
> * **Server**:
> 
> * **Bug Report / Feature Request**:
> 
> * **Summary**:
> 
> ![image](https://user-images.githubusercontent.com/82838526/115286470-b929db00-a16c-11eb-9da7-27841cdf0fff.png)
> 
> kRO Based Private Server
> [Equate Ragnarok]
> ip 51.79.240.138
> port 6900
> version 55
> master_version 01
> serverType kRO_RagexeRE_2018_04_18a
> serverEncoding Western
> addTableFolders translated/kRO_english;kRO
> 
> I am not sure about the ServerType so i used kRO_RagexeRE_2018_04_18a
> 
> Please assist, i am completely noob.

add `private 1` to servers.txt

**Comment by faiyazsayyed** [comment]
Hi,
I have added Private 1 and changed the Port to 6900 now i am getting the below error.

![image](https://user-images.githubusercontent.com/82838526/115290983-d2815600-a171-11eb-9c73-c8409b2d8520.png)

**Comment by faiyazsayyed** [comment]
@sctnightcore could you help me please...

**Comment by faiyazsayyed** [comment]
@sctnightcore

**Comment by faiyazsayyed** [comment]
@sctnightcore I was able to get the char logged in, then i am getting Timeout on Map Server error...

![image](https://user-images.githubusercontent.com/82838526/115309290-aeca0a00-a189-11eb-85b1-575d3b28d3b2.png)

**Comment by faiyazsayyed** [comment]
also below is the server information...

[Equate Ragnarok]
ip 51.79.240.138
port 6900
private 1
version 55
master_version 01
serverType kRO_RagexeRE_2018_06_20e
serverEncoding Western
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
gameGuard 0
addTableFolders kRO/RagexeRE_2018_06_21a;iRO;iRO/Renewal;
sendCryptKeys 0x1C4B6693, 0x125288C8, 0x1CAB9AF7
charBlockSize 147
pinCode 0

**Comment by faiyazsayyed** [comment]
@alisonrag could you check please ?

**Comment by alisonrag** [comment]
> @alisonrag could you check please ?

```
[Equate Ragnarok]
ip 51.79.240.138
port 6900
private 1
version 55
master_version 01
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
gameGuard 0
addTableFolders kRO/RagexeRE_2015_11_04a;iRO;iRO/Renewal;
charBlockSize 147
pinCode 0
```
![image](https://user-images.githubusercontent.com/10372732/116128661-8bc6bb00-a69f-11eb-9055-bcf0b10fdf99.png)
