### ISSUE TITLE
Connection issue on private server

### ISSUE THREAD

**Issue by Wouchou** [OpenKore/openkore#3409]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: Latest version available on github

* **Server**: OriginsRO

* **Bug Report / Feature Request**: Bug Report - connection issue
* Hi to the community,
i'm looking for help to connect on a private server (OriginsRO), to be honest i don't know if it's feasible but i'm pretty sure many people are already using Openkore on OriginsRO.
I've collected server informations (can be posted) and trying to connect with Xkore3 method (as i saw it was the method to follow).
Currently i'm receiving a message saying : 
Connecting to Account Server...
Connecting (94.23.193.170:6121)... connected
Disconnecting (94.23.193.170:6121)...disconnected

I'm trying to solve it by my self for hours now but without success...

If anyone can help me, will be appreciated :)

Sorry for my english.

* **Summary**: Connection issue on private server

**Comment by ya4ept** [comment]
this issue can be discussed on the forum

**Comment by alisonrag** [comment]
originsRO use a custom grf at  OriginsRO\OrigRO\main.orp
rename it to .grf, edit it, then rename back to .orp
