### ISSUE TITLE
Packet problem

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3417]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
Latest

* **Server**: 

cro
* **Bug Report / Feature Request**:
Latest version op can't move , I replace \src\Network\Send\cro.pm and ServerType0.pm with some older version , OP seems to be fine. useable file attached here
[useable.zip](https://github.com/OpenKore/openkore/files/6401975/useable.zip)

* **Summary**:

**Comment by zzwyrmslayer** [comment]
大佬能不能给个联系方式 有很多问题想请教

**Comment by ya4ept** [comment]
@zzwyrmslayer we use only English for communication!
