### ISSUE TITLE
[Ro X Generation] - The server has denied your connection for unknown reason (2)

### ISSUE THREAD

**Issue by paparagnarok1** [OpenKore/openkore#3422]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: version ctime:2021_05_07

* **Server**: kRO

* **Bug Report / Feature Request**:

* **Summary**: I am stuck at "The server has denied your connection for unknown reason (2)." I tried to follow your guideline #3390 but the issue is still persists. kindly please advise me on this matter, i am clueless after tried so many times.
* http://roxgen.ragnarok-online.net/
[Malaysia - Ro X Generation]
ip 194.233.69.30
port 6900
master_version 0
version 55
serverType kRO_RagexeRE_2020_03_04a
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2020_07_09a;iRO/official;iRO
charBlockSize 155
pinCode 1
charDeleteDateType 1
rankingSystemType 1
private 1
![Error](https://user-images.githubusercontent.com/81979557/117515071-de6d7480-afc7-11eb-8e0d-272c8883e064.PNG)

**Comment by paparagnarok1** [comment]
> try this:
> 
> ```
> #http://roxgen.ragnarok-online.net/
> [Malaysia - Ro X Generation]
> ip 194.233.69.30
> port 6900
> master_version 1
> version 55
> serverType kRO_RagexeRE_2018_11_21
> serverEncoding Western
> addTableFolders kRO/RagexeRE_2020_07_09a;iRO/official;iRO
> charBlockSize 155
> ```

thanks for your speedy reply. i tried but still getting same error :(

**Comment by paparagnarok1** [comment]
i tried servertype kRO_RagexeRE_XXX from 2018-2020 with kRO/RagexeRE_2020_07_09a but still no luck

**Comment by paparagnarok1** [comment]
i tried addTableFolders from 2018 till 2020 still getting same error

**Comment by alisonrag** [comment]
latest version:
https://github.com/OpenKore/openkore/archive/refs/heads/master.zip

servers.txt
```
[Malaysia - Ro X Generation]
ip 194.233.69.30
OTP_ip 194.233.69.30
OTP_port 6900
port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2020_03_04a
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2020_07_09a;iRO/official;iRO
charBlockSize 155
charDeleteDateType 1
rankingSystemType 1
private 1
```

working fine:
![image](https://user-images.githubusercontent.com/10372732/117692753-b599da80-b193-11eb-8d11-cebdc316fb6c.png)

**Comment by paparagnarok1** [comment]
@alisonrag thanks for your support and it is working now. Thank you very much.
kindly please delete/hide my post ya due to have server information
