### ISSUE TITLE
Please!!! Who can send a invite code to join china openkore discord，help me Pls.

### ISSUE THREAD

**Issue by zzwyrmslayer** [OpenKore/openkore#3436]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by ya4ept** [comment]
me too

**Comment by alisonrag** [comment]
seems like this server dont exists, maybe @hubertyang88 can help you
