### ISSUE TITLE
kRO and twRO support (nProtect gameguard)

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#3438]
* **Openkore version git**: 
https://github.com/OpenKore/openkore/commit/c871bdb1d973ca71e1fefb6bb248538b77cad3b5

* **Server**: 
kRO and twRO 

* **Feature Request**:
Add support to kRO and twRO

**Comment by chrislong93** [comment]
Hi I extracted client.xml from data.grf (using GRF Editor) but it doesnt show any info similar to the template clientinfo.xml 

```
<clientinfo>
	<servicetype>vietnam</servicetype>
	<servertype>primary</servertype>
	<passwordencrypt></passwordencrypt>
	<hideaccountlist></hideaccountlist>
	<extendedslot></extendedslot>
	
	<connection>
		<display>Vietnam Live</display>
		<desc>None</desc>
		<domain>roacc1.vtcgame.vn:6900</domain>
		<port>6900</port>
		<version>1</version>
		<registrationweb>http://www.ragnarok.co.kr</registrationweb>
		<aid>
			<admin>100001</admin><admin>100002</admin><admin>100003</admin><admin>100004</admin><admin>100005</admin><admin>100006</admin><admin>100007</admin><admin>100008</admin>
			<admin>100009</admin><admin>100010</admin><admin>100011</admin><admin>100012</admin><admin>100013</admin><admin>100014</admin><admin>100015</admin><admin>100016</admin>
			<admin>100017</admin><admin>100018</admin><admin>100019</admin><admin>100020</admin>
			
		</aid>
	</connection>

</clientinfo>
```

This server has nProtect Gameguard. Please kindly guide me how to extract useful clientinfo.xml for Poseidon server. Thank you.

**Comment by kou90258** [comment]
@chrislong93 This is the clientinfo.xml of the Vietnam server.
IP address roacc1.vtcgame.vn:6900
port 6900
version 1
You should use Wireshark to obtain the correct IP address and create server.txt
Read more https://openkore.com/wiki/Connectivity_Guide
server example:
[<server name>]
ip <number/host>
port <number>
version <number>
master_version <number>
serverType <serverType name>
serverEncoding <encoding>
charBlockSize <number>
addTableFolders <folder path>

# following options are optional
private <boolean>
recvpackets <file name>
chatLangCode <boolean>
storageEncryptKey <encrypt key>
field_<location> <filename>
clientHash <hex string>
captcha <boolean>

gameGuard <number>

secureLogin <boolean>
secureLogin_type <type>
secureLogin_requestCode <hex string>
secureLogin_account <boolean>

paddedPackets <boolean>
paddedPackets_attackID <packet switches>
paddedPackets_skillUseID <packet switches>

masterLogin_packet <packet switch>

OTP_ip <IP_or_hosthame>
OTP_port <number>

dead <boolean>
dead_message <any text>
title <any text>

pinCode <boolean>
charDeleteDateType <boolean>
blockingPlayerCancel <boolean>
rankingSystemType <boolean>
itemListType <boolean>
ignoreAntiCheatWarning <boolean>

**Comment by kou90258** [comment]
Attached Taiwan RO server.txt 
[Taiwan RO - GNJoy]
ip 219.84.200.54
port 6900
master_version 5
version 1
serverType twRO
serverEncoding Big5
charBlockSize  ???
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
recvpackets recvpackets.txt
addTableFolders twRO
pinCode 1
gameGuard 1

At present, there are some problems in charBlockSize, and you need to seek professional expert support. 

082D 099D The unpacking is incorrect, causing the character list to not be displayed correctly .

**Comment by chrislong93** [comment]
> Attached Taiwan RO server.txt
> [Taiwan RO - GNJoy]
> ip 219.84.200.54
> port 6900
> master_version 5
> version 1
> serverType twRO
> serverEncoding Big5
> charBlockSize ???
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> recvpackets recvpackets.txt
> addTableFolders twRO
> pinCode 1
> gameGuard 1
> 
> At present, there are some problems in charBlockSize, and you need to seek professional expert support.
> 
> [console.txt](https://github.com/OpenKore/openkore/files/6609069/console.txt)
> ![charBlockSize](https://user-images.githubusercontent.com/84857638/121022709-2bb25100-c7d5-11eb-90db-1991737081f5.png)
> 
> The previous packet extractor used by windhamwong. Ver. 4cdb79con 12 Aug 2018 Git stats
> 
> https://github.com/OpenKore/packetExtractor

Hey there, thanks a lot for your reply. 

I posted my issue on a separate topic but long-story short, I've managed to acquire IP & Port & version & master_version but not recvpackets by any means available. 

Please refer to this link for a detail post: https://github.com/OpenKore/openkore/issues/3440#issue-913430792

Thank you very much !

**Comment by alisonrag** [comment]
> Attached Taiwan RO server.txt
> [Taiwan RO - GNJoy]
> ip 219.84.200.54
> port 6900
> master_version 5
> version 1
> serverType twRO
> serverEncoding Big5
> charBlockSize ???
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> PINEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> recvpackets recvpackets.txt
> addTableFolders twRO
> pinCode 1
> gameGuard 1
> 
> At present, there are some problems in charBlockSize, and you need to seek professional expert support.
> 
> [console.txt](https://github.com/OpenKore/openkore/files/6609069/console.txt)
> ![charBlockSize](https://user-images.githubusercontent.com/84857638/121022709-2bb25100-c7d5-11eb-90db-1991737081f5.png)
> 
> The previous packet extractor used by windhamwong. Ver. 4cdb79con 12 Aug 2018 Git stats
> 
> https://github.com/OpenKore/packetExtractor

There is already a branch with Twro info:
https://github.com/OpenKore/openkore/tree/twRO-support

**Comment by kou90258** [comment]
We tried to block NP with a firewall
WINDOWS software is unable to run
if
Set up fortigate firewall virtual
Then connect to open RO through virtual windows10 IP ortigate, if open RO comes with NP open
That IP will open NP= =
As for the original breakthrough NP revision file, Aegis, this one has been greatly modified. 
[pass NP.zip](https://github.com/OpenKore/openkore/files/6639785/pass.NP.zip)

![passNP](https://user-images.githubusercontent.com/84857638/121717395-b49df500-cb13-11eb-8979-a71ff5caf484.png)

**Comment by sctnightcore** [comment]
client 

> We tried to block NP with a firewall
> WINDOWS software is unable to run
> if
> Set up fortigate firewall virtual
> Then connect to open RO through virtual windows10 IP ortigate, if open RO comes with NP open
> That IP will open NP= =
> As for the original breakthrough NP revision file, Aegis, this one has been greatly modified.
> [pass NP.zip](https://github.com/OpenKore/openkore/files/6639785/pass.NP.zip)
> 
> ![passNP](https://user-images.githubusercontent.com/84857638/121717395-b49df500-cb13-11eb-8979-a71ff5caf484.png)

client can connect to localhost ?

**Comment by kou90258** [comment]
In the previous version of nProtect gameguard, using xkore 0 will disconnect the connection because the special data packet of nProtect gameguard is not connected.
Our previous method was to use the main system to modify the clientinfo.xml in data.grf to connect to the local IP and open the client nProtect gameguard, nProtect gameguard will detect openkore as an illegal program under the same system, so we use a virtual machine to open Openkore xkore 2 connects to the IP of the same domain to avoid detection by nProtect gameguard, but the current situation seems that Gravity has used the new nProtect gameguard system to prevent the modification of files in data.grf, so this method cannot be used. I am currently looking for a way to see if I can connect to the same domain and use xkore2 /3 without modifying data.grf/clientinfo.xml

**Comment by sctnightcore** [comment]
> In the previous version of nProtect gameguard, using xkore 0 will disconnect the connection because the special data packet of nProtect gameguard is not connected.
> Our previous method was to use the main system to modify the clientinfo.xml in data.grf to connect to the local IP and open the client nProtect gameguard, nProtect gameguard will detect openkore as an illegal program under the same system, so we use a virtual machine to open Openkore xkore 2 connects to the IP of the same domain to avoid detection by nProtect gameguard, but the current situation seems that Gravity has used the new nProtect gameguard system to prevent the modification of files in data.grf, so this method cannot be used. I am currently looking for a way to see if I can connect to the same domain and use xkore2 /3 without modifying data.grf/clientinfo.xml

Do u have discord ?

**Comment by kou90258** [comment]
@sctnightcore  We are analyzing CheatDefender. If you have any discussion, please go to our Discord channel to discuss
OpenKoreTW Discord group: https://discord.gg/kQX5b5u

**Comment by sctnightcore** [comment]
> @sctnightcore We are analyzing CheatDefender. If you have any discussion, please go to our Discord channel to discuss
> OpenKoreTW Discord group: https://discord.gg/kQX5b5u

joined :)

**Comment by ya4ept** [comment]
we can already connect to the map. Next we need to look at poseidon.

![image](https://user-images.githubusercontent.com/7117363/124605615-c6ee2300-de74-11eb-9ae3-c7ae4b409881.png)

**Comment by ya4ept** [comment]
Done #3467

**Comment by AriesCrack** [comment]
> > @sctnightcore We are analyzing CheatDefender. If you have any discussion, please go to our Discord channel to discuss
> > OpenKoreTW Discord group: https://discord.gg/kQX5b5u
> 
> joined :)

I have the same question:  Gravity has used the new nProtect gameguard system to prevent the modification of files in data.grf
Could it can connect to the same domain and use xkore2 /3 without modifying data.grf/clientinfo.xml?

Current I modify Ragexe.exe to load my xml file, and it can enter poseidon server.
But it also detection by nProtect gameguard for a period of time.

**Comment by ya4ept** [comment]
use hosts:
```
127.0.0.1			twro-acc.gnjoy.com.tw
```

**Comment by AriesCrack** [comment]
> use hosts:
> 
> ```
> 127.0.0.1			twro-acc.gnjoy.com.tw
> ```

Thanks! Workable.
