### ISSUE TITLE
Can't connect between openkore and Ragexe

### ISSUE THREAD

**Issue by TanasanJJ7** [OpenKore/openkore#3445]
------------------ Openkore Issues Template ------------------
Openkore version git:
Server:  iRO-Renew
Bug Report / Feature Request:   X-Kore 1
Summary:

![Capture](https://user-images.githubusercontent.com/16222517/121834217-6564e980-ccf8-11eb-9bd4-9957f2276138.PNG)

![Capture](https://user-images.githubusercontent.com/16222517/121834788-d48f0d80-ccf9-11eb-8f53-2459e5eb234b.PNG)

How to Fix  Packet unknow

Thank You   For  Reply

**Comment by ya4ept** [comment]
```
	MSG_FAILED_RECV_ITEM_OVERCOUNT = 0xa4d,
/*20140625 to latest
무게가 초과하였습니다. 소지창의 여유공간을 확보해주세요.
The weight has been exceeded. Please free up the possesion window.
*/
```

**Comment by TanasanJJ7** [comment]
> ```
> 	MSG_FAILED_RECV_ITEM_OVERCOUNT = 0xa4d,
> /*20140625 to latest
> 무게가 초과하였습니다. 소지창의 여유공간을 확보해주세요.
> The weight has been exceeded. Please free up the possesion window.
> */
> ```
> 
> ```c++
> #if PACKETVER_MAIN_NUM >= 20181219 || PACKETVER_RE_NUM >= 20181219 || PACKETVER_ZERO_NUM >= 20181212
> struct PACKET_ZC_INVENTORY_EXPANSION_INFO {
> 	int16 packetType;
> 	int16 expansionSize;
> } __attribute__((packed));
> DEFINE_PACKET_HEADER(ZC_INVENTORY_EXPANSION_INFO, 0x0b18);
> #endif
> ```
> 
> `0B18` we did here: #2593

Don't working   
Openkore don't connect to ragexe   and  can't run

**Comment by TanasanJJ7** [comment]
> ```
> 	MSG_FAILED_RECV_ITEM_OVERCOUNT = 0xa4d,
> /*20140625 to latest
> 무게가 초과하였습니다. 소지창의 여유공간을 확보해주세요.
> The weight has been exceeded. Please free up the possesion window.
> */
> ```
> 
> ```c++
> #if PACKETVER_MAIN_NUM >= 20181219 || PACKETVER_RE_NUM >= 20181219 || PACKETVER_ZERO_NUM >= 20181212
> struct PACKET_ZC_INVENTORY_EXPANSION_INFO {
> 	int16 packetType;
> 	int16 expansionSize;
> } __attribute__((packed));
> DEFINE_PACKET_HEADER(ZC_INVENTORY_EXPANSION_INFO, 0x0b18);
> #endif
> ```
> 
> `0B18` we did here: #2593

![Capture](https://user-images.githubusercontent.com/16222517/121978100-ac62e580-cdb1-11eb-9a82-2cd528f3609a.PNG)
Don't Move

**Comment by chrislong93** [comment]
> ```
> 	MSG_FAILED_RECV_ITEM_OVERCOUNT = 0xa4d,
> /*20140625 to latest
> 무게가 초과하였습니다. 소지창의 여유공간을 확보해주세요.
> The weight has been exceeded. Please free up the possesion window.
> */
> ```
> 
> ```c++
> #if PACKETVER_MAIN_NUM >= 20181219 || PACKETVER_RE_NUM >= 20181219 || PACKETVER_ZERO_NUM >= 20181212
> struct PACKET_ZC_INVENTORY_EXPANSION_INFO {
> 	int16 packetType;
> 	int16 expansionSize;
> } __attribute__((packed));
> DEFINE_PACKET_HEADER(ZC_INVENTORY_EXPANSION_INFO, 0x0b18);
> #endif
> ```
> 
> `0B18` we did here: #2593

Hi Ya4ept, I emailed you on your email address: ya4ept@ya.ru. Could you please kindly check? большое спасибо

**Comment by TanasanJJ7** [comment]
> what should i check?

disconnect to map

**Comment by ya4ept** [comment]
I'm sorry, I'm the main file ServerType0, we added the `0B18` package only in #3467 (29.08.2021)

**Comment by alisonrag** [comment]
i think the issue here was disconnect after map load, unfortunately seem he was using a flag to disable eac and this flag also disable the packet encypt in map-server so in first send packet client is disconnected.
use #2963 for eac
