### ISSUE TITLE
Disconnected right after char

### ISSUE THREAD

**Issue by percent-90** [OpenKore/openkore#3447]
Hi:
      I have download the lartest openkore file and try to login in. But the character was  disconnected after choose the char. I had tried three accounts but all the same. Is there something I should to do? 

Server: Twro

## ------------------ Openkore Issues Template ------------------

![image](https://user-images.githubusercontent.com/86037454/122356477-6c545c00-cf85-11eb-8dbc-1d680873d479.png)

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by ya4ept** [comment]
see #3438
