### ISSUE TITLE
tRO Mega Thread - All tRO issues here only #2

### ISSUE THREAD

**Issue by aecute** [OpenKore/openkore#345]
Chapter 2

talking about bug, hmac, etc for openkore here!!

Come back is real!!

**Comment by tosspons** [comment]
hmac decoded or disable eac? do you know it? Working bot now that i see is autoscript click by pixel complie frome vb. But this way bot are very stupid.

**Comment by Cozzie** [comment]
OK, I am going to be strict as we received a lot of complaints even from github last time.

1. English only
2. Technical discussions only
3. If you want to have non technical discussion please use the forum. 

This will be the only notice.

**Comment by itsrachelfish** [comment]
@Cozzie We received complaints from github? Can you explain?

**Comment by farrainbow** [comment]
The politically better alternative, gitlab, already exists, just in case anything happens to this one.
