### ISSUE TITLE
OpenKore cannot teleport through an NPC if it is behind a wall

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3451]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: last

* **Server**: RMS Renewal Test Server

* **Bug Report / Feature Request**: OpenKore cannot teleport through an NPC if it is behind a wall

* **Summary**: we have the following portal-NPC:
```new_1-4 100 29 moc_ruins 155 44 0 c c c c c r0 c c c c r1 r0 r0 r0 r1 r1 c c r0 c r0 c r0 c r1 c c r0 c r1 c r1 c r1 c c r2 c r2 c r2 c r0 c r2 c r2 c r0 c r1 c c c c c c c c c c r0 c c c c c c c c```
OpenKore cannot calculate the path from **new_1-4** to **moc_ruins** openkore cannot calculate the path from location 1 to location 2 because the NPC is hiding behind the table:
![image](https://user-images.githubusercontent.com/7117363/124047448-e6242500-da1c-11eb-81bb-e5c5cf39e47b.png)

Use this macro to check for defect:
```css
macro test {
	do c @warp new_1-4 100 19
	pause 3
	do debug 2
	do move moc_ruins 155 44
	do debug 0
}
```

console logs:
```css
macro test
Map Change: new_1-4.gat (100, 19)
Warped.
NPC Exists: Final Tester#nv1 (100, 29) (ID 110014979) - (0)
Config 'debug' set to 2 (was 0)
Saving control\config.txt...
AI: macro sitAuto sitting | 3
Calculating route to: Morocc Ruins(moc_ruins): 155, 44
You on route to: Morocc Ruins(moc_ruins): 155, 44
CalcMapRoute - initialized.
CalcMapRoute failed.
Cannot calculate a route from new_1-4 (100,19) to moc_ruins (155,44)
Config 'debug' set to 0 (was 2)
```

**Comment by alisonrag** [comment]
It is a old issue, it also can't teleport in modo fields

**Comment by alisonrag** [comment]
https://forums.openkore.com/viewtopic.php?p=54026#p54026

**Comment by ya4ept** [comment]
One more problematic place.
```
macro test {
	do c @warp monk_test 260  125
	pause 3
	do debug 2
	do move monk_test 314 134
	do debug 0
}
```
The portal is outside the map border

![image](https://user-images.githubusercontent.com/7117363/124389487-ffb0bf80-dcef-11eb-937e-1f61231d7acf.png)

**Comment by alisonrag** [comment]
maybe add a flag in portals.txt and in config keys related to npc ?

**Comment by toy9371** [comment]
請問TWRO可以使用嗎?
目前似乎卡在地圖KEYS

**Comment by ya4ept** [comment]
This behavior should be automatic for all NPCs.
OpenKore should build a route to the NPC if there is a free cell within "clientSight 15"

**Comment by alisonrag** [comment]
> This behavior should be automatic for all NPCs.
> OpenKore should build a route to the NPC if there is a free cell within "clientSight 15"

so auto walk to the npc closest cell in range of clientSight

**Comment by c4c1n6kr3m1** [comment]
me, long time ago :
- if npc exist on the screen, why move closer?
- why 10 blocks?

**Comment by alisonrag** [comment]
> me, long time ago :
> 
> * if npc exist on the screen, why move closer?
> * why 10 blocks?

Portals are also npcs, so need to move closer

**Comment by c4c1n6kr3m1** [comment]
portals ; npcs , they use different code inside MapRoute.pm
my old openkore change this line
```} elsif (distance($self->{actor}{pos_to}, $self->{mapSolution}[0]{pos}) <= $dist) {```
to something like this
```} elsif ((distance($self->{actor}{pos_to}, $self->{mapSolution}[0]{pos}) <= $dist) || (List::MoreUtils::any { $_->{pos}{x} == $self->{mapSolution}[0]{pos}{x} && $_->{pos}{y} == $self->{mapSolution}[0]{pos}{y} } @{$::npcsList->getItems})) {```

than change the 10 blocks spot to random spots

**Comment by c4c1n6kr3m1** [comment]
for portal outside map ... editing the field is easier?

**Comment by alisonrag** [comment]
add to portals:
`mosk_fild02 198 53 moscovia 140 54 c r0`

macro:
```
macro test {
	do c @warp mosk_fild02 202 58
	pause 3
	do debug 2
	do move moscovia
	do debug 0
}
```

**Comment by alisonrag** [comment]
Change this in src/Task/Route.pm:
from:
`
my $closest_dest = $field->closestWalkableSpot(\%dest, 1);
`
to:
`
my $closest_dest = $field->closestWalkableSpot(\%dest, 10);
`

results:
Novice Grounds:
![image](https://user-images.githubusercontent.com/10372732/127065213-cbac6457-fdd4-4f8b-a283-3bca83a99ab0.png)

Monk Test:
![image](https://user-images.githubusercontent.com/10372732/127065335-cc92ba82-6b3a-4104-a935-8a6a90c9771b.png)

Moscovia:
![image](https://user-images.githubusercontent.com/10372732/127065358-b7062ced-4944-47f2-b30b-a7e61ab40258.png)
