### ISSUE TITLE
Issues in twRO

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#3474]
List of issues in twRO

- [x] Skills Lists related packets (0B32, 0B33 and possibly others)
- [x] 0B31 'skill_add'
- [x] 0B73
- [x] If the bot is a member of a guild, then it disconnects from the server immediately after connecting to the location. 
      We have to check "sendGuildRequestInfo"
- [x] 0B7B 'guild_info'
- [x] 0B7D 'guild_members_list'
- [ ] Izlude and new academy training grounds
- [x] item_exists and item_appear packet
- [x] Disconnect when use a item
- [x] Inventory not updated after use a item
- [x] check `skill_use_location 0366` << I think it's wrong
Poseidon Shows New Package `0AF4`
- [x] [Soul Reaper skills support](https://github.com/OpenKore/openkore/issues/3474#issuecomment-884175311)
- [x] `rodex open` does not show the list of letters
- [x] `Rolling Cutter` (0B10 and 0B11 packet)
- [ ] The protection has changed. Cheat Defender is now used.

**Comment by ya4ept** [comment]
> Disconnect when use a item

i checked, no errors

**Comment by ya4ept** [comment]
[fix item_exists ](https://github.com/OpenKore/openkore/pull/3467/commits/7e095afb2d80ce9d0257a3a2e31290db9d32d089)

**Comment by ya4ept** [comment]
- [ ] check `skill_use_location 0366`
[fixed](https://github.com/OpenKore/openkore/pull/3467/commits/fe2a43a8424c6e3ddbe4fbee9d527d1cb2d6d514)

**Comment by alisonrag** [comment]
> * [x]  0B73

fixed at:
https://github.com/OpenKore/openkore/pull/3467/commits/6b5ea52b55ec68d48741b372cef2a75ae7a924b7

**Comment by kou90258** [comment]
unkown switch : 0B7D
![unknown](https://user-images.githubusercontent.com/84857638/126187383-453c1d96-3e62-4394-99fd-0180492b06d3.png)

**Comment by alisonrag** [comment]
seems related to guild...
can u set in config:
`debugPacket_received 2`

**Comment by ya4ept** [comment]
> * [x] 0B31

fixed at: https://github.com/OpenKore/openkore/pull/3467/commits/ea95fa2c396fe33115dd25b5aed32ad42233c648

**Comment by kou90258** [comment]
for DEV.
Soul Reaper class skill list is not supported
Unable to test related Soul Reaper career issues.
Soul Reaper Career Related Information
https://www.novaragnarok.com/wiki/Soul_Reaper

OpenKore version what-will-become-2.1
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2021_07_17
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
No valid skill identifier specified.

Stack trace:
Trace begun at src\Skill.pm line 142
Skill::new('Skill', 'handle', undef) called at src\Commands.pm line 5210
Commands::cmdSkills('skills', undef) called at src\Commands.pm line 858
Commands::run('skills') called at src\functions.pl line 1108
main::parseInput('skills') called at src\functions.pl line 63
main::mainLoop at src\Interface.pm line 75
Interface::mainLoop('Interface::Console::Win32=HASH(0x5229c54)') called at openkore.pl line 97
main::__start at start.pl line 136

Died at this line:
  	} else {
* 		ArgumentException->throw("No valid skill identifier specified.");
  	}

**Comment by ya4ept** [comment]
- [x] 0B7B 'guild_info'
- [x] 0B7D 'guild_members_list'
[fixed](https://github.com/OpenKore/openkore/pull/3467/commits/c4a8b40afa477d491dbd20846a3874dc2e41a70f)

**Comment by alisonrag** [comment]
> * [x]  [Soul Reaper skills support](https://github.com/OpenKore/openkore/issues/3474#issuecomment-884175311)
fixed at: https://github.com/OpenKore/openkore/pull/3467/commits/471e71a5e59d634952ef98baa44f2ba901954044

**Comment by ya4ept** [comment]
> 0B32, 0B33
[fixed](https://github.com/OpenKore/openkore/pull/3467/commits/8ac8b2d5d32e8351accbe6d68b1c64701718c9f2)

**Comment by alisonrag** [comment]
> * [x]  `rodex open` does not show the list of letters
[fixed](https://github.com/OpenKore/openkore/pull/3467/commits/208b08eaa691036edf7ced059c1af6a86436a2da)

**Comment by ya4ept** [comment]
> > * [x]   `rodex open` does not show the list of letters
> >   [fixed](https://github.com/OpenKore/openkore/pull/3467/commits/208b08eaa691036edf7ced059c1af6a86436a2da)

you're wrong it didn't work

**Comment by kisk76278** [comment]
Excuse me  
I don’t know if it’s right to leave a message here. Please forgive me.
I would like to ask what is the reason for the disconnection in about 20 seconds?

**Comment by ya4ept** [comment]
> - [x] `rodex open` does not show the list of letters
fixed: #3491

**Comment by kou90258** [comment]
It has been found that the robot will get stuck at a location where the altitude cannot be determined (mountains, cliffs), and lock down monsters in low ground. Has been targeting the attack.
Is the height parameter in the map data unable to exist?
Robot movement information only has x, y but no z-direction parameter data, and obstacles on the map can’t be determined.
![未命名4](https://user-images.githubusercontent.com/84857638/127321147-0c7955fd-2382-4b52-9c15-834f5ac67d23.png)
![未命名3](https://user-images.githubusercontent.com/84857638/127321153-619fecb5-a780-4c74-ab02-64028d6cacc9.png)
[2021.07.28 19:21:06.75] [ai_attack] Unable to calculate a route to target, dropping target
[2021.07.28 19:21:06.75] [console] You are now attacking Monster 綠變色龍 (0)
[2021.07.28 19:21:06.81] [ai_attack] Unable to calculate a route to target, dropping target
[2021.07.28 19:21:06.81] [console] You are now attacking Monster 綠變色龍 (0)
[2021.07.28 19:21:06.87] [ai_attack] Unable to calculate a route to target, dropping target
[2021.07.28 19:21:06.88] [console] You are now attacking Monster 綠變色龍 (0)
[2021.07.28 19:21:06.93] [ai_attack] Unable to calculate a route to target, dropping target
[2021.07.28 19:21:06.94] [console] You are now attacking Monster 綠變色龍 (0)
[2021.07.28 19:21:07.33] [ai_attack] Unable to calculate a route to target, dropping target
[2021.07.28 19:21:07.91] [console] You are now attacking Monster 綠變色龍 (0)

**Comment by royalgarter** [comment]
> > Disconnect when use a item
> > Inventory not updated after use a item
> 
> i checked, no errors
> ![image](https://user-images.githubusercontent.com/7117363/126052076-bdd09505-139a-4ab5-b0b6-50a71406e29d.png)

This problem is exists in vRO. Used item is not update without relog or change map using portals.

**Comment by momo525566** [comment]
Packet Parser: Unknown switch: 0A73

**Comment by alisonrag** [comment]
We need a log/how to reproduce

**Comment by kou90258** [comment]
@momo525566 
When Packet Parser: Unknown switch:
Or other serious unsolvable problems
Please use the Debugging optionsru function first to record the problem clearly with logConsole
  Debugging optionsru is a very important function, please don’t ignore it

**Comment by kou90258** [comment]
Packet Parser: Unknown switch: 
These issues are not of high importance.
0B7C   Command guild
0A83   Command guild kick 
0B47   guild kick and request autoSpell skill 
0B7E   Command guild request
[guild.txt](https://github.com/OpenKore/openkore/files/6949280/guild.txt)

**Comment by love08006310** [comment]
config.txt
shopAuto_open 1
shopAuto 1 

[SHOP.txt](https://github.com/OpenKore/openkore/files/7077976/SHOP.txt)

**Comment by love08006310** [comment]
openShop is not available
shopAuto_open 1
openshop



OFF SHOP has records
![unknown](https://user-images.githubusercontent.com/45393082/131367975-058ffee7-8c59-4916-9592-efff636c464f.png)

![unknown](https://user-images.githubusercontent.com/45393082/131368126-1a1376ff-daa0-4d14-b5da-56c7e62697fb.png)


![unknown](https://user-images.githubusercontent.com/45393082/131368095-a83c4c23-07f9-4ade-846c-3feb21271c62.png)

[SHOP.txt](https://github.com/OpenKore/openkore/files/7077982/SHOP.txt)

**Comment by lgyaxx** [comment]
Is twRo bottable right now? I'm getting 
`
Packet Tokenizer: Unknown switch: 0007
Packet Tokenizer: Unknown switch: 0009
Packet Tokenizer: Unknown switch: 000B
Packet Tokenizer: Unknown switch: 0008
Packet Parser: Unknown switch: 017E
Packet Tokenizer: Unknown switch: 797A
Packet Tokenizer: Unknown switch: 0797
Packet Tokenizer: Unknown switch: 05C3
Packet Tokenizer: Unknown switch: 0014
`
I've tried xkore0-3, no luck, anyone can enlighten me a bit?

**Comment by rMengLien** [comment]
@alisonrag 請問 Packet Tokenizer: Unknown switch: 000F 
這是哪裡出了問題?

**Comment by Sameq13242** [comment]
Can twRO server enter by updating the above files?

**Comment by ya4ept** [comment]
openkore can't work with "Cheat Defender" protection
