### ISSUE TITLE
Issues in vRO

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#3475]
- [ ] Party Follow issue (sometimes OpenKore [Crash](https://cdn.discordapp.com/attachments/863751966743724052/865532085606547476/unknown.png) when master lost), followTarget issue
- [x] Party commands disconnecting
- [x] Skill Name issues? (Need Confirmation)
- [x] Begginer Fly wing should be added to fly wing check?
- [x] skill use failed wrong unpack
- [ ] New Maps: Izlude, Academy, Alberta
- [x] check freeCast plugin (route issue?)
- [x] error openkore cant drop target
- [ ] Remake vRO_auth plugin: use https and use new user-agent:
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
- [ ] add "XkoreProxy" support
- [x] check autostorage. It looks like items are not being parsed correctly
- [x] check "Warp Portal" skill

**Comment by TheSunShower** [comment]
Getting hit by an unreachable monster (ranged stationary) cause AI to get stuck trying to attack it and dropping it.

**Comment by ya4ept** [comment]
> Party commands disconnecting

[this problem has long been solved](https://github.com/OpenKore/openkore/pull/3460/commits/a564627e22026bc923fc93365eb54c0a6c4834d9)

> Skill Name issues? (Need Confirmation)

[this problem has long been solved](https://github.com/OpenKore/openkore/pull/3460/commits/9ce3da931dbc1148fcd33b3ea0e63aff17d31ab3)

**Comment by playboyvntgn** [comment]
![image](https://user-images.githubusercontent.com/10356162/126063724-14a0bf1d-acf5-4e2b-b04b-61cb94436f01.png)
The bot does not recognize the Butterfly Wing or Fly Wing in inventory.

**Comment by talkervn** [comment]
@playboyvntgn  ông share tôi bản bot ông đang sử dụng có được không?

**Comment by talkervn** [comment]
@ya4ept  i have an error? can you help me to fix it? Thank you so much
![image](https://user-images.githubusercontent.com/87598844/126069044-dd770663-2392-47fd-bf28-4981fbf684ae.png)
[openkore-master.zip](https://github.com/OpenKore/openkore/files/6836331/openkore-master.zip)

**Comment by talkervn** [comment]
@ya4ept  can you share me the lastest of vro bot tool? i am a newbie :(

**Comment by alisonrag** [comment]
> * [x]  Begginer Fly wing should be added to fly wing check?

fixed at:
https://github.com/OpenKore/openkore/pull/3460/commits/be8b641b6c7cf6c4226ea1cd22f70cb495393e5a

**Comment by kynguyen96** [comment]
I config poseidon server for vro but step Start 'ragexe 1rag1 /account:poseidon.xml' i can't do it. Please help me

**Comment by alisonrag** [comment]
> * [x]  error [openkore](https://cdn.discordapp.com/attachments/863751966743724052/866357526613721108/unknown.png) cant drop target

will be fix at https://github.com/OpenKore/openkore/pull/3480

**Comment by hailua28** [comment]
Hi @alisonrag 
I don't know what to do with this error, can you help me?
![abc 1](https://user-images.githubusercontent.com/87394162/126189435-cfa7c515-7a74-4cd6-8283-4607d7d9416c.jpg)
![abc](https://user-images.githubusercontent.com/87394162/126189443-b1dbcaeb-4b91-4e0e-b840-e5f9d4dbb779.jpg)

**Comment by KnowNothing123** [comment]
> ![abc](https://user-images.githubusercontent.com/87394162/126189443-b1dbcaeb-4b91-4e0e-b840-e5f9d4dbb779.jpg)

Same problems, please give us some solutions, thx.

**Comment by datxu0410** [comment]
Please help me use poseidon, i can't run the rag.exe throw the client of vRO.
Thanks.

**Comment by datxu0410** [comment]
Dear,
Please check this errors, thanks.
[errors.txt](https://github.com/OpenKore/openkore/files/6846208/errors.txt)

**Comment by datxu0410** [comment]
Dear,
Please check this errors, can't connect to server vRO went open star_poseidon.exe
Thanks
[errors.txt](https://github.com/OpenKore/openkore/files/6846256/errors.txt)

**Comment by datxu0410** [comment]
Dear,
Please check this errors, can't connect to server vRO went open star_poseidon.exe
Thanks
[errors.txt](https://github.com/OpenKore/openkore/files/6846462/errors.txt)

**Comment by ya4ept** [comment]
@datxu0410 you're setting up your poseidon wrong. No need to write about it here! 
1) [Read the manual](https://openkore.com/wiki/Poseidon)
2) [read neighboring topics](https://github.com/OpenKore/openkore/issues/3440)
3) [read the forum](https://forums.openkore.com/)
4) [read the discord](https://discord.gg/kmvfgYAfhC)

**Comment by nguyenquang2302** [comment]
hello i'm newbie.

After some research i tried using poseidon. But it doesn't seem to work
It seems I can't connect between openkore and poseidon server yet
Can you guide me?
![image](https://user-images.githubusercontent.com/13691088/126864876-635d55b6-001a-44d5-a326-aa3cebee734f.png)

**Comment by alisonrag** [comment]
> * [x]  check autostorage. It looks like items are not being parsed correctly
[fixed](https://github.com/OpenKore/openkore/pull/3460/commits/503749d2b7fec85119a8ab30209af62ade0ca14c)

**Comment by alisonrag** [comment]
> * [x]  check freeCast plugin (route issue?)
freeCast was made only to run, there is no support to attack while cast

**Comment by TheSunShower** [comment]
There isn't anything to support attack while casting right? Somehow Actor always locked itself to casting and wouldn't attempt to attack while casting. Giving it a melee distance and attack command doesn't help either.

**Comment by vutung2311** [comment]
- [ ]  Remake vRO_auth plugin: use https and use new user-agent:
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
 This is done in https://github.com/vutung2311/openkore/commit/c8378801b18a91849f586a7b6e7eebe65d5a2acf

**Comment by ya4ept** [comment]
> > * [x]   check freeCast plugin (route issue?)
> 
> freeCast was made only to run from target, there is no support to attack while cast

here they write that the plugin works:
https://ro-fan.ru/viewtopic.php?p=56846#p56846

**Comment by alisonrag** [comment]
> > > * [x]    check freeCast plugin (route issue?)
> > 
> > 
> > freeCast was made only to run from target, there is no support to attack while cast
> 
> here they write that the plugin works:
> https://ro-fan.ru/viewtopic.php?p=56846#p56846

Is almost the same compared to the one in plugin folder, still has no support to melee attack while casting

**Comment by chumlacklx** [comment]
Is xkore 2 support in vRO ? I have tried many but it does not work :(

**Comment by alisonrag** [comment]
> Is xkore 2 support in vRO ? I have tried many but it does not work :(

nope, xkore 2 should not work in any official server

**Comment by todangtan** [comment]
Today, i see Botter don't disconnect. How to i can?

**Comment by alisonrag** [comment]
> Today, i see Botter don't disconnect. How to i can?

https://discord.gg/kmvfgYAfhC

**Comment by timelinebk9x** [comment]
There is an issue with my client and poseidon server. The client connected to the poseidon server but could not load character list, it stucked at waiting dialogue and disconnected after 1 minute. Is there any guide to solve this issue?

**Comment by kiemthan** [comment]
Bots priest does not buff increase agi. What should I do. My config:
useSelf_skill Increase AGI {
	lvl 10
	whenStatusInactive Increase AGI
	sp > 10%
	timeout 5
}
partySkill Increase AGI {
	lvl 10
	sp > 45
	notInTown 0
	timeout 3
	target_whenStatusInactive Increase AGI
	target_timeout 240
}

Bots just buff Blessing. I try another but all not work. PLZ help. sever vRo

**Comment by Tus299** [comment]
My bot doesnt standup after reach the sitAuto_hp_upper xx value, even when it fully regen HP/SP.
It will remain sitting until there's some random mob appear around

I asked some friend and they're got the same problem.
Thank you.

![image](https://user-images.githubusercontent.com/88768393/128994080-e97c366c-062a-4c4d-8408-e62e0d95c6d8.png)

**Comment by kiemthan** [comment]
> My bot doesnt standup after reach the sitAuto_hp_upper xx value, even when it fully regen HP/SP.
> It will remain sitting until there's some random mob appear around
> 
> I asked some friend and they're got the same problem.
> Thank you.
> 
> ![image](https://user-images.githubusercontent.com/88768393/128994080-e97c366c-062a-4c4d-8408-e62e0d95c6d8.png)

Hi Tus299 

Please contact me on zalo 0902930489 to help me get openkore working on my pc. Currently my computer cannot pass gameguard. I live in Vietnam

**Comment by DuongBien2204** [comment]
> Bots priest does not buff increase agi. What should I do. My config:
> useSelf_skill Increase AGI {
> lvl 10
> whenStatusInactive Increase AGI
> sp > 10%
> timeout 5
> }
> partySkill Increase AGI {
> lvl 10
> sp > 45
> notInTown 0
> timeout 3
> target_whenStatusInactive Increase AGI
> target_timeout 240
> }
> 
> Bots just buff Blessing. I try another but all not work. PLZ help. sever vRo

You are using the wrong skill name

**Comment by royalgarter** [comment]
> * [ ]  New Maps: Izlude, Academy, Alberta

New [Raw FLD2](https://1drv.ms/u/s!AshOi9yrIQq_hLMhIaDbq9VCG5aUXA?e=n9tAc5) extracted from vRO data.grf.

**Comment by ya4ept** [comment]
> [+]  check "Warp Portal" skill

this works by default

**Comment by ya4ept** [comment]
@alisonrag How about a KANBAN board instead of this issue?
https://github.com/OpenKore/openkore/projects/10

**Comment by Kiienn149** [comment]
@alisonrag An illegal software was detected.
I run start-poseidon then run ragexe and wxstart.Bot run smoothly but  after over 5 minutes a window appear with the text ''An illegal software was detected" . And after that, bot just run over 1 minutes and then "Disconnecting from map server"
How can i solve this problem.
Thanks for reading and sorry for my not good english =))

**Comment by ya4ept** [comment]
run "wxstart" on another computer

**Comment by royalgarter** [comment]
> * [ ]  add "XkoreProxy" support

I created a [pull request](https://github.com/OpenKore/openkore/pull/3529) for this.

**Comment by ya4ept** [comment]
vRO server no longer exists
