### ISSUE TITLE
change logic "teleportAuto_item"

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3479]
Now it works like this:
if you specify an `teleportAuto_item`, then the bot will only use it, while it will ignore the presence of Wings in the inventory.

New logic:
if an `teleportAuto_item` is specified, then the bot first tries to use this item, if the `teleportAuto_item` is not found, then the bot tries to use the Wings

PS:
Now these messages is not always correct and may mislead the user:
> You don't have the Teleport skill or a Fly Wing
> You don't have the Teleport skill or a Butterfly Wing

**Comment by alisonrag** [comment]
fixed at: https://github.com/OpenKore/openkore/pull/3460/commits/14b3ae12107a53cd2ff329c698d301cb3e83bfdc
