### ISSUE TITLE
help me poseiden

### ISSUE THREAD

**Issue by leaf8831** [OpenKore/openkore#3482]
![Screenshot (9)](https://user-images.githubusercontent.com/87678131/126247885-c60c1a4f-ddef-4f83-a56a-92fb4e2a492e.png)
help me fix it

**Comment by ya4ept** [comment]
you're setting up your poseidon wrong. No need to write about it here! 
1) [Read the manual](https://openkore.com/wiki/Poseidon)
2) [read neighboring topics](https://github.com/OpenKore/openkore/issues/3440)
3) [read the forum](https://forums.openkore.com/)
4) [read the discord](https://discord.gg/kmvfgYAfhC)

**Comment by nnduylc** [comment]
chạy được không ông, server poseiden  thì tôi chạy được rồi vào được game rồi nhưng k biết làm thế nào để bot

**Comment by talkervn** [comment]
Please use english!!!
