### ISSUE TITLE
About Poseidon remote

### ISSUE THREAD

**Issue by chumlacklx** [OpenKore/openkore#3485]
I have successed botting with poseidon client. But i wonder what is poseidon remote ? Is that i can run open kore via using LAN or WAN without need to open poseidon client ? Wish to heard your answer, thank you very much !

![image](https://user-images.githubusercontent.com/87187797/126865438-68edc016-a6d9-4d1c-a790-4a50d00daa98.png)

**Comment by AxeNick00** [comment]
@chumlacklx ông có thể giúp tui cài poseidon đc không ông tui bế tắc bửa h ko thể nào cài đc zalo của tui 0908114069 liên lạc qua zalo nha xin dc hậu tạ cảm ơn ông

**Comment by ya4ept** [comment]
@AxeNick00 use english please

**Comment by ya4ept** [comment]
@chumlacklx you can run poseidon anywhere. This is a network service
