### ISSUE TITLE
Is Xkore support in vRO ?

### ISSUE THREAD

**Issue by chumlacklx** [OpenKore/openkore#3498]
Many thank for Contributor alisonrag and ya4ept for supporting in vRO. 

I have an issued to ask, can vRO have xkore support ? I have tried xkore 1 but GG make disconnect a few seconds.

With xkore 3 i have config clientinfo.xml change to port 6901 and make shortcut 1rag1 User=anyusername Token=Foo BToken=Bar /account:xkore3.xml but it show expired token. 

Is there any solutions ? Thank for answer :)

![image](https://user-images.githubusercontent.com/87187797/127668975-d8165c93-3ff5-4460-88c0-c667f1f7b5ed.png)

![image](https://user-images.githubusercontent.com/87187797/127669376-39a2f502-d40d-4210-821b-8b0cd64b903f.png)

**Comment by alisonrag** [comment]
use #3475 to ask stuffs about vRO, also if u can check there, there is no official support to xkore 3
