### ISSUE TITLE
Item-related code renames

### ISSUE THREAD

**Issue by farrainbow** [OpenKore/openkore#350]
In order to bring Item::Actor (inventory, cart and storage) stuff to the same track as other Actor classes:

First step:
- [x] rename `index` to `ID`. Make it bytes (`a2`) instead of number (`v`) since we have nothing useful to do with it?
- [x] rename `invIndex` to `binID`;
- [x] rename `getByServerIndex()` to `getByID()`;
- [ ] ensure everything works, since it would touch many places.

Second step:
- [x] use `ActorList` as a base for `InventoryList` (instead of `ObjectList`), as at that point they would do many things exactly the same way. Remove a bunch of code.

Next:
- [ ] discuss if we need inventory item be entirely new class;
- [x] possibly clean up related Wx code;
- [ ] possibly clean up related Commands code;
- [ ] possibly clean up related Network code.

That would allow to further merge the code for ActorList and InventoryList and all the related stuff later.

Assuming this is to do after https://github.com/OpenKore/openkore/pull/119

**Comment by Henrybk** [comment]
rename index to ID && rename invIndex to binID: I find that to be okay.

rename getByServerIndex() to getByID() && use ActorList as a base for InventoryList : Well these two conflict a little, ActorList already has a method called getByID which in the case of the Actor being an item on the ground gets it by 'server ground index' ($actor->{ID}), while this new getByID in InventoryList would get an Actor which is an item in inventory by it's 'server inventory index'  ($actor->{index}).

Also I think we should have separate Actor classes for items on the ground and on the inventory (Actor::GroundItem and Actor::InvItem ?) or even a new class just for inventory items (src/Item.pm).

**Comment by Henrybk** [comment]
Also ActorList::add uses $self->{IDmap} to map items by ID, and inventory items have no $item->{ID}, they only hold $item->{index}  and $item->{InvIndex}.

**Comment by farrainbow** [comment]
>ActorList already has a method called getByID which in the case of the Actor being an item on the ground gets it by 'server ground index' ($actor->{ID}), while this new getByID in InventoryList would get an Actor which is an item in inventory by it's 'server inventory index' ($actor->{index}).

Yes, and it looks like item only has one single ID - would it be on-ground server ID (if it's on ground), or inventory server ID (when in inventory) or cart/storage ID etc. Everywhere it means just the current and only ID which is used for operations with the item. For other things it's not even unpacked for the most time, since we don't have anything to do with it other than send it back to the server. Somebody correct me if that's wrong.

>Also I think we should have separate Actor classes for items on the ground and on the inventory (Actor::GroundItem and Actor::InvItem ?)

Yes, we probably should, at least for placing methods like `->use` which are only applicable to some of them.

>or even a new class just for inventory items (src/Item.pm).

Maybe as the next thing if we'll the that it's what we really want? We can change this later.

**Comment by farrainbow** [comment]
>Also ActorList::add uses $self->{IDmap} to map items by ID, and inventory items have no $item->{ID}, they only hold $item->{index} and $item->{InvIndex}.

>But in the end $ground_item->{ID} is the same as $inv_item->{index} and $ground_item->{binID} is the same as $inv_item->{InvIndex} so we could just change the class method GetByID in InventoryList to use $inv_item->{index} or just make all these 4 changes at the same time and be okay :P

Yes, if we rename those simultaneously, existing `ActorList` functions should handle everything just fine. That's the point of it, to reduce different code which does almost the same thing.

**Comment by Henrybk** [comment]
Yeah, all these changes seem to good and will certainly make the code cleaner, safer and faster, we just have to finish and merger #119
