### ISSUE TITLE
Condition "var" of Macro plugin does not work.

### ISSUE THREAD

**Issue by jim83803** [OpenKore/openkore#3501]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  The latest version of branch twro-recvpacket 

* **Server**:  twRO

* **Bug Report / Feature Request**:

I want to use the condition "var" in automacro, and I test it.
The code is as follows:
```
automacro test1 {
    run-once 1
    call {
        $test = 1
    }
}

automacro test2 {
    var $test unset
    call {
        log $test = $test
    }
}
```
This is my thought:
1st, automacro test1 assigns 1 to $test.
2nd, automacro test2 should not be triggered because "$test == 1" instead of "$test == unset".
So the call body will not run.

But the result is:
```
[macro] automacro test2 triggered.
[macro log] $test = 1
[macro] automacro test2 triggered.
[macro log] $test = 1
[macro] automacro test2 triggered.
[macro log] $test = 1
```
It can be seen from the above:
Although $test is 1, it is regarded as unset at the line "var $test unset" because it is triggered.
* **Summary**:  The condition "var" of automacro is something wrong if I understand correctly.
I referred the Openkore Wiki: [https://openkore.com/wiki/macro_plugin](https://openkore.com/wiki/macro_plugin )
```
var <variable> (unset | <condition> <value>)
Triggers when <variable> is either unset or matches <condition> <value>.
Multiple lines are treated as AND conditions.
```

**Comment by ya4ept** [comment]
The condition is incorrectly specified in the second auto-macro. In the `var` condition you need to use "test", instead of "$test"
Here is the correct macro:
```
automacro test1 {
    run-once 1
    exclusive 1
    call {
        $test = 1
        log test = $test
    }
}

automacro test2 {
    var test unset
    call {
        log test = $test
    }
}
```

**Comment by ya4ept** [comment]
added an example to the [documentation](https://openkore.com/wiki/macro_plugin#Events)
