### ISSUE TITLE
how can i handle clientinfo.xml

### ISSUE THREAD

**Issue by mookseven** [OpenKore/openkore#3511]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
 d291ab5
* **Server**:  twRO

* **Bug Report / Feature Request**: how can i handle clientinfo.xml ? don't work on your manual

* **Summary**:
* i'm trying to roclient to poseidon server , but after extract clientinfo.xml ,changed poseidon.xml ,after that client show no msg ,failed
* so didn't connect to poseidon server 
* what can i do setting xml file ???
* refer site https://openkore.com/wiki/Poseidon
* i save to data.grf for modifed clientinfo.xml (data/poseidon.xml no effect now)
![image](https://user-images.githubusercontent.com/50956625/130942507-ed487332-6179-4df7-af92-7928faf6b75b.png)

**Comment by ya4ept** [comment]
GitHub is not intended for such questions, I use forum or discord
