### ISSUE TITLE
iRO packet parser !

### ISSUE THREAD

**Issue by Vortrexx** [OpenKore/openkore#3513]
Does anyone know the reason for this error?

![image](https://user-images.githubusercontent.com/89709387/131231024-0df6e0b6-2a24-4077-b493-87febdabaa98.png)

**Comment by arm321689** [comment]
i have same problem And Status Coneecting..........

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore#status-of-botting-on-official-servers

**Comment by ya4ept** [comment]
iRO - not botable

**Comment by haKKulamatata** [comment]
> iRO - not botable

why and how can we make it botable

**Comment by alisonrag** [comment]
Easy Anti Cheat, encrypt all data traffic
