### ISSUE TITLE
BUG of 07FD

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3520]
## ------------------ Openkore Issues Template ------------------

original packet 
'07FD' => ['special_item_obtain', 'v C v c/Z a*', [qw(len type nameID holder etc)]], 

But in some server nameID is a V instead of v  ,  tested in cro , below works
'07FD' => ['special_item_obtain', 'v C V c/Z a*', [qw(len type nameID holder etc)]], 

* **Openkore version git**: 

* **Server**:  cRO

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by ya4ept** [comment]
done
