### ISSUE TITLE
bug of dropping target

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3522]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: Latest.

* **Server**: all

* **Bug Report / Feature Request**:

op can't drop a target , keep showing msg "Unable to calculate a route to target, dropping target"
attack_failed don't work.
in CoreLogic.pm , should we add one line like blow?

`next if (!timeOut($monster->{attack_failedLOS}, $timeout{ai_attack_failedLOS}{timeout}));`
`+ next if (!timeOut($monster->{attack_failed}, $timeout{ai_attack_unfail}{timeout}));`

* **Summary**:

**Comment by ya4ept** [comment]
try to close the bot and reopen it
maybe it's a double #3508

**Comment by hubertyang88** [comment]
After editing CoreLogic.pm , I checked console file, don't see continuing msg "Unable to calculate a route to target, dropping target"  to same target for 7 hours .
I guess something is wrong about calculate a meetingPosition to target , but editing CoreLogic.pm might bypass this glitch

**Comment by hubertyang88** [comment]
it turned out this bug still happen ,  wait for proper fix

**Comment by hubertyang88** [comment]
If OP begin game in a small size map  , then move to a bigger map , this bug will happen , but  the reverse will not  .

**Comment by ya4ept** [comment]
this is a duplicate: #3508
