### ISSUE TITLE
[twRO] cannot connect poseidon server

### ISSUE THREAD

**Issue by beaune1117** [OpenKore/openkore#3523]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: master

* **Server**: twRO

* **Bug Report / Feature Request**:Feature Request

* **Summary**:
* I am use latest openkore version and follow "https://openkore.com/wiki/Poseidon" step ,
* i am sure all needs change parameter was changed ,
* but when I execute "Ragexe.exe 1rag1 /account:poseidon.xml" via cmd will boot into formal server not poseidon server. Is there anything else I need to pay attention to?
* Thanks

**Comment by huaaann** [comment]
I have the same question , need somebody for help!!xst
And I found that I can just run "start-poseidon" then use "wxstart" it become useful.
But "wxstart" will disconnect in almost 30 seconds then try reconnect , disconnect ....

**Comment by ya4ept** [comment]
have you run openkore on twRO before?

**Comment by kou57112** [comment]
@huaaann 
[Ask questions  SOP.txt](https://github.com/OpenKore/openkore/files/7315191/Ask.questions.SOP.txt)

**Comment by huaaann** [comment]
> @huaaann [Ask questions SOP.txt](https://github.com/OpenKore/openkore/files/7315191/Ask.questions.SOP.txt) 1.Search for answers
> 
> Have a problem? Update your openkore or download a new one. Still having problems? Search in Wiki. Search in Forum. Search in Github issues. Search in discord Cant find what you need? / Do not understand? Is it a problem in Openkore? Read things to know before reporting.
> 
> 2.Learn to try to solve the problem https://openkore.com/wiki/Poseidon
> 
> 3.Ask questions Get help from other users from the international forum or discord
> 
> https://forums.openkore.com/
> 
> https://github.com/OpenKore/openkore/issues
> 
> discord https://discord.gg/kmvfgYAfhC

Thanks for your reply!
1.I've try to solve this problem in wiki, search andGithub issues.
2.Learn to try to solve the problem
https://openkore.com/wiki/Poseidon  <<<< same as title , I follow the tips and it still can't work.
3.Ask questions Get help from other users from the international forum or discord
yeah,  I'm try to get some help here now....

**Comment by huaaann** [comment]
> @huaaann In the end I think you will need https://www.gnjoy.com.tw/Question
> 
> OR https://www.gnjoy.com.tw/Cs

oh, sounds a great idea.
But it still can't solve my problem.
Thanks for your help.  Have a nice day!!

**Comment by love08006310** [comment]
只有上帝能解決你的問題

> > @huaaann最後我想你需要https://www.gnjoy.com.tw/Question
> > 或https://www.gnjoy.com.tw/Cs
> 
> 哦，聽起來是個好主意。 但是還是不能解決我的問題。 謝謝你的幫助。祝你今天過得愉快！！

只有上帝能解決你的問題

**Comment by gnjoy** [comment]
@beaune1117
![未命名](https://user-images.githubusercontent.com/90633582/136657150-5d6630a0-1788-48fc-b879-15cd6e357cb5.png)

**Comment by clayman101** [comment]
> @ya4ept謝謝！！！有用！它可以關閉這個問題。

Hello, I also have this problem...Want to ask you how to solve it?
I don't quite understand...
Can @ya4ept's method be explained in more detail?

**Comment by jye90505** [comment]
Hi.. I had follow enery step above, it success connect to the Poseidon server, but everytime it runs to the "Waiting for PIN code request", it has no reponse... is anyone know how to fix it?

---------------------- Servers ----------------------
#   Name                  Users  IP              Port  SID   State
0   Poseidon server       0      127.0.0.1       6900   0      Idle
-----------------------------------------------------
對帳號伺服器關閉連線
斷線中 (127.0.0.1:6900)...已斷線
正在連線至角色伺服器...
Selected server: Poseidon server
連線中 (127.0.0.1:6900)... 已連線
從角色伺服器接受角色
Waiting for PIN code request
角色選擇伺服器逾時, 重新連線中...
斷線中 (127.0.0.1:6900)...已斷線

**Comment by jye90505** [comment]
Hi.. I had follow enery step above, it success connect to the Poseidon server, but everytime it runs to the "Waiting for PIN code request", it has no reponse... is anyone know how to fix it?

![image](https://user-images.githubusercontent.com/92679290/137630851-52b0957c-ce02-416b-9cb5-32450a5c6a74.png)

**Comment by jye90505** [comment]
Hi.. I have follow every steps above, it has success to connect Poseidon server, but everytime it runs to "Waiting for PIN code request", it has no response, is anyone know how to fix it?

![image](https://user-images.githubusercontent.com/92679290/137630877-1298a642-f5c0-4081-a9e8-820269f5d718.png

**Comment by jye90505** [comment]
Hi.. I have follow every steps above, it has success to connect Poseidon server, but everytime it runs to "Waiting for PIN code request", it has no response, is anyone know how to fix it?
![image](https://user-images.githubusercontent.com/92679290/137630959-e4b147f1-037c-4c0e-b265-4aadeb13bdb5.png)
