### ISSUE TITLE
[twRO]How to solve the problem of continuous disconnection and reconnection...

### ISSUE THREAD

**Issue by ghost** [OpenKore/openkore#3527]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  master

* **Server**:  twRO

* **Bug Report / Feature Request**: Feature Request

* **Summary**: 

Hello, I would like to ask a question. This is the first time I have asked a question here.
I also followed the teaching steps of the website (https://openkore.com/wiki/Poseidon), and I successfully used start.exe to log in to the twRO game.

But after I enter the game, after almost 20~30 seconds, I will display "Disconnected from the map"...
Then it keeps disconnecting, reconnecting, disconnecting again...continuously looping.

start.exe：
![q1](https://user-images.githubusercontent.com/92602359/137548177-83151252-fd2d-4165-8156-3864cf4f5556.png)

start-poseidon.exe：
![q2](https://user-images.githubusercontent.com/92602359/137548210-0232e57c-e683-4d2d-9570-fc3f67c73648.png)

On average, as long as one or two monsters are killed (that is, 20~30 seconds), Will be disconnected and reconnected. I really can’t figure out the reason, I need someone’s help...

How can I solve this problem...?

**Comment by clayman101** [comment]
Fuck you mother

:)

Clarence ***@***.***> 於 2021年10月16日 週六 上午10:28寫道：

**Comment by love08006310** [comment]
So you are like this, greeting people

**Comment by ya4ept** [comment]
duplicate #3530
