### ISSUE TITLE
The problem has been resolved, request deletion.

### ISSUE THREAD

**Issue by eyb794613** [OpenKore/openkore#3528]
The problem has been resolved, request deletion.

**Comment by eyb794613** [comment]
@hubertyang88
Hey
I followed your instructions to use different IP addresses to run two Poseidon servers, but still "disconnected from the map server"

![help](https://user-images.githubusercontent.com/92778436/137982896-0ca27e16-ea46-4125-819a-572265146644.jpg)
Running one bot is very stable, but running more than two bots will definitely disconnect from the map server.
(And both disconnected almost at the same time)

I still can't solve this problem... :(

**Comment by eyb794613** [comment]
> twRO dont allow open more then 1 ragexe client, so this is not a openkore issue, this is related to nprotect/ragexe. i will let this open for some days to see if someone has a tool for help you

Yes, I also thought about this.

The best answer I can think of now is to open VirtualBox and run a second Poseidon server in it.

But first assume that this method is feasible
When running one more Bot, one more VirtualBox needs to be opened, worrying that the CPU load on the computer is a bit huge.

I still hope to find a way to run multiple Bots without using VirtualBox...

**Comment by LKKK01234** [comment]
Then don't use it, there will be no cpu problem

**Comment by eyb794613** [comment]
> 問題已解決，請求刪除。
