### ISSUE TITLE
[vRO]How to solve the problem of continuous disconnection and reconnection...

### ISSUE THREAD

**Issue by talkervn** [OpenKore/openkore#3533]
Openkore version git: master
Server: vRO
Bug Report / Feature Request: Feature Request
Summary:
Hello, I would like to ask a question. This is the first time I have asked a question here.
I also followed the teaching steps of the website (https://openkore.com/wiki/Configuring_Poseidon_for_twRO), and I successfully used start.exe to log in to the vRO game.

![image](https://user-images.githubusercontent.com/87598844/139911558-8e7953d2-7fa6-460a-8a6a-c54ea7fb0071.png)
![image](https://user-images.githubusercontent.com/87598844/139911696-d5834717-0955-4c91-9208-cbd66e4c7ea8.png)

But after I enter the game, after almost 20~30 seconds, I will display "Disconnected from the map"...
Then it keeps disconnecting, reconnecting, disconnecting again...continuously looping.

**Comment by talkervn** [comment]
@ya4ept please help me.

**Comment by talkervn** [comment]
Nobody can fix :(

**Comment by ya4ept** [comment]
let's use this query: #3530

**Comment by talkervn** [comment]
Reopen please!
