### ISSUE TITLE
After 5min Poseidon connot receive Query from bot client?

### ISSUE THREAD

**Issue by EdwardZerG** [OpenKore/openkore#3538]
## ------------------ Openkore Issues Template ------------------

RoClient can connects to Poseidon, and I used some method to make RoClient donot report NP error.
KORE connect server well.
BUT! After Poseidon receive 2time bot Query, Poseidon connot receive Query from bot client, than KORE disconnect the Map sever...
KORE can successful run about 6mins.
SO how can I solve this problem? 
![png1](https://user-images.githubusercontent.com/32728157/141766228-186dba7c-e401-4ed9-9982-8e7cafb0d39a.png)

**Comment by ya4ept** [comment]
duplicate #3530
