### ISSUE TITLE
Use $char->cart->isReady instead of $char->cartActive

### ISSUE THREAD

**Issue by farrainbow** [OpenKore/openkore#354]
Since we don't usually care about which statuses $char has, but whether we can manipulate items in the cart.

**Comment by AlexandreBR3N** [comment]
Well. great. I don't know if this already exists ('isReady'), but how to check properly when we can manipulate ?

**Comment by alisonrag** [comment]
now we use $char->cart->isReady
https://github.com/OpenKore/openkore/search?p=2&q=cart-%3EisReady&type=&utf8=%E2%9C%93
