### ISSUE TITLE
Private server, need help 

### ISSUE THREAD

**Issue by SCM44** [OpenKore/openkore#3540]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: last version of openkore

* **Server**:  private server ( https://ro-inception.com/ )

* **Bug Report / Feature Request**: not able to get recvpackets , and  the server type isnt in openkore folders
https://zupimages.net/up/21/46/qr0n.png

can connect with another servertype, but got disconnected when i enter the map

* **Summary**:
 i'd pay 10 euros for your work, if it works !

**Comment by ya4ept** [comment]
you need to find encryption keys, no instructions
