### ISSUE TITLE
skill name bug

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3542]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
latest

* **Server**: 
all
* **Bug Report / Feature Request**:
In file  SKILL_id_handle.txt , there are several skills named xx_STARTMARK , I think "STARTMARK" should be some other name ?
* **Summary**:

**Comment by alisonrag** [comment]
it is auto extracted from skill skillid.lub
![image](https://user-images.githubusercontent.com/10372732/146030520-a60d958f-3a56-44e5-a8e3-a959ccdf2891.png)

there is also a XX_ENDMARK

what do you suggest, have you seen any skill related to this with different name?

**Comment by hubertyang88** [comment]
it works as long as a proper name is give to this startmark or endmark skill . but just for an example , SC_STARTMARK should be SC_FATALMENACE  .
 Leave it this way if it dosen't cause problems.

**Comment by ya4ept** [comment]
i don't know what is true

https://divine-pride.net/database/skill/2284/fatal-menace
![image](https://user-images.githubusercontent.com/7117363/146655163-2be193f6-5052-4bb4-95d7-61067968d94c.png)
