### ISSUE TITLE
Bot of vRO is working

### ISSUE THREAD

**Issue by talkervn** [OpenKore/openkore#3543]
After the monthly update of yesterday, the bot of vRO is working. Please check.

**Comment by hieunmG1** [comment]
Still the same issue, are you sure?

**Comment by ya4ept** [comment]
i think it is not true
![image](https://user-images.githubusercontent.com/7117363/146676028-ffb34f90-dd44-4676-8f9a-d628508c03b9.png)

**Comment by ya4ept** [comment]
@talkervn  Why did we open this issue?
