### ISSUE TITLE
[idRO] XKore 1 mode not connecting to Ragnarok Client

### ISSUE THREAD

**Issue by Abyzzmal** [OpenKore/openkore#3545]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  655a335

* **Server**: IdRO (all)

* **Bug Report / Feature Request**: Bug Report - Question

* **Summary**: Trying to run XKore 1 on a new server (IdRO); it detects & hooks into the Ragnarok Client but it won't detect me trying to login. When I try to login, OpenKore still keeps waiting for the Ragnarok Client to connect to X-Kore. I assume that XKore 1 does not rely on the server settings in servers.txt, so maybe the XKore_port has to be the correct value?

**Comment by ya4ept** [comment]
idRO server uses EAC protection like here #2963
idRO - is not a botable server

**Comment by Abyzzmal** [comment]
> idRO server uses EAC protection like here #2963 idRO - is not a botable server

So even if I use XKore 0, and somehow luckily get the Version/Master Version right, it'll still not connect due to EAC?
Sorry if that's a stupid question, I last botted back in 2005.

**Comment by ya4ept** [comment]
yes it won't help you

**Comment by Abyzzmal** [comment]
> yes it won't help you

Ah okay, so the only way would probably to create a new NetRedirect.dll that could somehow bypass the EAC (in this case Delphine for IdRO) and use XKore 1.

I'll try and see if I can somehow figure this out. Thanks for the help bud.

**Comment by coldmuffin** [comment]
I also faced the same problem, I was using XKore 1 and it keeps waiting for the Ragnarok Client to connect to X-Kore.

**Comment by coldmuffin** [comment]
When I run the RO Client first then run the openkore, it produces an error:

> Unable to inject E:\Openkore\openkore-master-test\NetRedirect.dll

But, when I run the open core first then RO Client, it stuck after this message:

> Waiting for the Ragnarok Online client to connect to X-Kore...

**Comment by HeLLioNeS** [comment]
can someone teach me or give clue how dual login or multi client in id ro server. thanks.

**Comment by ya4ept** [comment]
idRO - is not a botable server

**Comment by faisalakmal** [comment]
> idRO - is not a botable server



> When I run the RO Client first then run the openkore, it produces an error:
> 
> > Unable to inject NetRedirect.dll
> 
> But, when I run the open core first then RO Client, it stuck after this message:
> 
> > Waiting for the Ragnarok Online client to connect to X-Kore...

i got same problem like you, something error with  NetRedirect.dll
**sigh**

**Comment by faisalakmal** [comment]
> idRO - is not a botable server

yeah but i see unnormal movement hahaha
