### ISSUE TITLE
TWRo not working

### ISSUE THREAD

**Issue by sashiiiii** [OpenKore/openkore#3550]
## ------------------ Openkore Issues Template ------------------
When open the bot, it show
This program has encountered an unexpected problem. This is probably because of
a recent server update, a bug in this program, or in one of the plugins. We
apologize for this problem. You may get support from IRC or the forums.

A detailed error report has been saved to errors.txt. Before posting a bug
report, please try out the latest release GIT version first. If you are already
using the latest release GIT version, search the forums first to see if your
problem had already been solved, or has already been reported. If you truly
believe you have encountered a bug in the program, please include the contents
of the errors.txt in your bug report
(https://github.com/openkore/openkore/issues), or we may not be able to help
you!

The error message is:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = {};

**Comment by s936511** [comment]
> ## ------------------ Openkore Issues Template ------------------
> When open the bot, it show This program has encountered an unexpected problem. This is probably because of a recent server update, a bug in this program, or in one of the plugins. We apologize for this problem. You may get support from IRC or the forums.
> 
> A detailed error report has been saved to errors.txt. Before posting a bug report, please try out the latest release GIT version first. If you are already using the latest release GIT version, search the forums first to see if your problem had already been solved, or has already been reported. If you truly believe you have encountered a bug in the program, please include the contents of the errors.txt in your bug report (https://github.com/openkore/openkore/issues), or we may not be able to help you!
> 
> The error message is: Attempt to STORE non blessed reference (or not a reference) Value: $VAR1 = {};
> 
> OpenKore version what-will-become-2.1 Network state = 4 Network handler = Network::DirectConnection Revision: ctime:2021_12_31 Loaded plugins: plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day) plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin) plugins/macro/macro.pl (macro; description: allows usage of macros) plugins/map/map.pl (map; description: map) plugins/profiles/profiles.pl (profiles; description: Profiles Selector) plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills) plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats) plugins/reconnect/reconnect.pl (reconnect; description: v1.0) plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)
> 
> Error message: Attempt to STORE non blessed reference (or not a reference) Value: $VAR1 = {};
> 
> Stack trace: Attempt to STORE non blessed reference (or not a reference) Value: $VAR1 = {}; at src/Utils/BlessedRefTie.pm line 10 Tie::BlessedRef::STORE('Tie::BlessedRef=SCALAR(0x724fb74)', 'HASH(0x720b85c)') called at src/Network/Receive.pm line 1787 Network::Receive::actor_display called at src/Network/Receive.pm line 1736 Network::Receive::actor_display_compatibility('Network::Receive::twRO=HASH(0x725c6a4)', 'HASH(0x7250824)') called at src/Network/PacketParser.pm line 279 Network::PacketParser::parse('Network::Receive::twRO=HASH(0x725c6a4)', '\x{dd}\x{9}\x{0}#\x{a}\x{da}\x{9}2\x{0}\x{0}\x{0}\x{2}\x{3}\x{0}\x{0}\x{8}\x{0}_\x{0}\x{0}\x{0}\x{d6}\x{0}\x{0}\x{0}\x{b1}\x{ad}\x{1}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}...', 'Network::Receive::twRO=HASH(0x725c6a4)') called at src/Network/Receive.pm line 564 Network::Receive::parse('Network::Receive::twRO=HASH(0x725c6a4)', '\x{dd}\x{9}\x{0}#\x{a}\x{da}\x{9}2\x{0}\x{0}\x{0}\x{2}\x{3}\x{0}\x{0}\x{8}\x{0}_\x{0}\x{0}\x{0}\x{d6}\x{0}\x{0}\x{0}\x{b1}\x{ad}\x{1}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}...', 'Network::Receive::twRO=HASH(0x725c6a4)') called at src/Network/PacketParser.pm line 413 Network::PacketParser::process('Network::Receive::twRO=HASH(0x725c6a4)', 'Network::MessageTokenizer=HASH(0x3a52b14)', 'Network::Receive::twRO=HASH(0x725c6a4)') called at src/functions.pl line 832 main::mainLoop_initialized() called at src/functions.pl line 75 main::mainLoop() called at src/Interface.pm line 75 Interface::mainLoop('Interface::Console::Win32=HASH(0x4b44584)') called at openkore.pl line 97 main::__start() called at start.pl line 136
> 
> * **Openkore version git**:
> 
> * **Server**:
> 
> * **Bug Report / Feature Request**:
> 
> * **Summary**:

@sashiiiii There is no problem, it can't work in the first place.
![000](https://user-images.githubusercontent.com/25875385/148248061-7e7a80df-8a28-4b8d-bcb9-54ae4eb0c9f5.png)

**Comment by sashiiiii** [comment]
> ###

I have tried to open again, the error still exist.
what do you mean 'can't work in the first place'?
thank you!

![image](https://user-images.githubusercontent.com/97030347/148259047-890b5523-0e99-4d77-8013-a9ec787bedcc.png)

**Comment by talkervn** [comment]
Send me your tool. I can fix it.

**Comment by sashiiiii** [comment]
> Send me your tool. I can fix it. @sashiiiii

Do you have any idea?
i just downloaded from this website.
No any change is applied.
