### ISSUE TITLE
monster stucked  in screen

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3551]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

latest
* **Server**: 
all
* **Bug Report / Feature Request**:

When bot using some skill, such as RG_BACKSTAP , which will cause position changing ,  sometimes , some monster looks stucked in screen ,  player's pos is 350 350 ,  when use comand ml , bot will show some monster pos at 90 70 , how to clear this?
* **Summary**:

**Comment by alisonrag** [comment]
this is because of server it also happens in clean client when u use backstab too fast

server dont send the actor dissapear packet

**Comment by hubertyang88** [comment]
is there a comand to refresh screen ? Or some mothed in macro to refresh screen?
