### ISSUE TITLE
recvpackets tool outdated no longer works for private server?

### ISSUE THREAD

**Issue by kyloren23** [OpenKore/openkore#3554]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
 latest 
* **Server**:  private server
 
* **Bug Report / Feature Request**: Bug Report

* **Summary**:  i have successfully connected to a private server, my character was able to random walk, emote, sit, but unable to attack. because monsters are shown as npc .. it won't show monster in ml command, the culprit is wrong servertype because im not able to extract recvpacket for privateserver ragexe.exe, the server has no protection, no gepard and only like 20-30 players.. i hope you can help me. i have tried packet extracter v3, peek, etc and other shown in openkore connectivity guide wiki, but gave me bunch of errors my guess is.. the tool is outdated last update was 2014(?) i will attach my ragexe.exe i hope someone can help me to find recvpackets
[ragexe.zip](https://github.com/OpenKore/openkore/files/7844243/ragexe.zip)

servers.txt
[RO private5]
ip 103.102.46.87
port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2020_04_01b
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2020_04_01b;iRO/official;iRO
charBlockSize 155
charDeleteDateType 1
rankingSystemType 1
private 1

![image](https://user-images.githubusercontent.com/97502057/148894826-36a2184a-a555-4640-b304-ca2050e545f0.png)

**Comment by ya4ept** [comment]
@sctnightcore

**Comment by bllamy** [comment]
> the ro server is [www.m@gnusro.com](http://www.m@gnusro.com) replace @ with a

use this:
ip 103.102.46.87
port 6900
private 1
master_version 1
version 55
recvpackets recvpackets_20180620.txt
serverType kRO_RagexeRE_2018_06_20e
serverEncoding Western
charBlockSize 155
pinCode 1
addTableFolders pserver/GGamerzRO
clientHash 6BB2AFD0D3F780730809E3BD0407AF7C
sendCryptKeys 0x00000000, 0x00000000, 0x00000000

**Comment by alisonrag** [comment]
other tools:
1. https://gitlab.com/4144/peek?sid=D3OWX0
2. https://gist.github.com/gudoh/75015d93d9b08a0fa2172dba61588f50

Also some recvpackets are already extracted u can check the list here:
https://github.com/OpenKore/openkore/tree/master/tables/kRO

just load it using addTableFolders:
`addTableFolders kRO/RagexeRE_2020_04_01b`

also reading the reply above seems more like a wrong servertype so im closing this
