### ISSUE TITLE
TW RO Login Issue

### ISSUE THREAD

**Issue by alvin349069** [OpenKore/openkore#3559]
Hi:
my openkore version is the latest
when I try to login , It shows the message below.
How should I solve this problem?

Error message:
Can't call method "inventory" on an undefined value at src/Network/Receive.pm line 3549.

Stack trace:
Can't call method "inventory" on an undefined value at src/Network/Receive.pm line 3549.
 at src/Network/Receive.pm line 3549
	Network::Receive::inventory_item_removed('Network::Receive::twRO=HASH(0x7216c1c)', 'HASH(0x7294a0c)') called at src/Network/PacketParser.pm line 279
	Network::PacketParser::parse('Network::Receive::twRO=HASH(0x7216c1c)', '\x{af}\x{0}\x{0}#\x{a}\x{ac}', 'Network::Receive::twRO=HASH(0x7216c1c)') called at src/Network/Receive.pm line 564
	Network::Receive::parse('Network::Receive::twRO=HASH(0x7216c1c)', '\x{af}\x{0}\x{0}#\x{a}\x{ac}', 'Network::Receive::twRO=HASH(0x7216c1c)') called at src/Network/PacketParser.pm line 413
	Network::PacketParser::process('Network::Receive::twRO=HASH(0x7216c1c)', 'Network::MessageTokenizer=HASH(0x3b5625c)', 'Network::Receive::twRO=HASH(0x7216c1c)') called at src/functions.pl line 832
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4e75b9c)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

在這一行當掉:
  	return unless changeToInGameState();
* 	my $item = $char->inventory->getByID($args->{ID});
  	my $reason = $args->{reason};

**Comment by s936511** [comment]
![36D85655-A4C1-4792-95A0-A384A472182A](https://user-images.githubusercontent.com/25875385/153640404-e97c1391-a9e9-4491-a316-bd2102e154ac.jpeg)

TWRO has replaced the protection system CheatDefender, Openkore no longer supports TWRO, please don't keep asking the same question. Please close this issue.
