### ISSUE TITLE
RAGNAROK GGH BOT PLEASE LET US KNOW. 

### ISSUE THREAD

**Issue by jcarlo52** [OpenKore/openkore#3567]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by alisonrag** [comment]
use #3561

**Comment by jcarlo52** [comment]
> use #3561

I don't know how

**Comment by alisonrag** [comment]
> > use #3561
> 
> I don't know how

me too, but split the info in a lot of "issues" won't help

**Comment by jcarlo52** [comment]
> > > use #3561
> > 
> > 
> > I don't know how
> 
> me too, but split the info in a lot of "issues" won't help

Sorry bro, do u know how to use bots?

**Comment by BurdenEX** [comment]
> > > > use #3561
> > > 
> > > 
> > > I don't know how
> > 
> > me too, but split the info in a lot of "issues" won't help
> 
> Sorry bro, do u know how to use bots? 

Why you questioining the developer of openkore? Loll
