### ISSUE TITLE
How to extract recvpackets

### ISSUE THREAD

**Issue by royluo1984** [OpenKore/openkore#3568]
I am hosting a rathena server
openkore is allowed to use in my server, but after the server-side upgrade, the client repacket is upgrade to 20211117
the lastest repackets I can find in openkore is [RagexeRE_2020_07_09a].
Could anyone tell me how to extract recvpackets on my own?

I tried all the extractors and PEEKs I can find in the internet

**Comment by jmando01** [comment]
I'm having the same issue. Were you able to figure it out?

**Comment by alisonrag** [comment]
use this project to ask about extraction:
https://github.com/OpenKore/packetExtractor
