### ISSUE TITLE
openkore stuck on map specifix cordinate

### ISSUE THREAD

**Issue by oleokoong** [OpenKore/openkore#3569]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

When my bot in izlude going to prontera will pass prt_fild08

the bot will auto calculate route and stuck in fix cordinate at prt_fild08

debug log
Route You Solution Ready! Found path on prt_fild08 from 139 139 to 170 378. Size: 0 steps.
You reached the destination.

139 139 is the stuck cordinate
170 378 is portal entry prontera

i try find portals.txt but nothing in the file

anyone know who to remove this stuck cell?

**Comment by Photonzx** [comment]
update your portal.txt you should found something the same coordinate or go to ratemyserver check the renewal izlude map you will see different portals there go login in the server and just check which portal is which.

**Comment by oleokoong** [comment]
> update your portal.txt you should found something the same coordinate or go to ratemyserver check the renewal izlude map you will see different portals there go login in the server and just check which portal is which.

the issue is prt_fild08 not izlude, in this map have few spot that openkore think it is "portals"  and i already check in portals that loaded, dont have such cordinate.. 

i also delete portalLOS and let it recompile..

is there any file that i can check?

stuck point as below i found
moc_fild02 66 299
prt_fild08 139 139
prt_fild08 169 299
