### ISSUE TITLE
How to launch Poseidon server?(Already follow all instruction)

### ISSUE THREAD

**Issue by hating1014** [OpenKore/openkore#3572]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: *** OpenKore what-will-become-2.1 ( version ctime:2022_03_27 ) - Custom Ragnarok Online client ***

* **Server**: twRO

* **Bug Report / Feature Request**:Feature Request

* **Summary**:HI, it's my first issue here, so if any clue is needed just don't hesitate to let me know and I'll fix it; as the title, I already do every step with https://openkore.com/wiki/Configuring_Poseidon_for_twRO before this issue, and somehow, I am stuck in the step of launching the Poseidon server, I can see Poseidon server after I start the twRO client, but can't see the Poseidon player and disconnect. Is it's me to miss any parameters here? Did anyone get the same issue as me?
* ![image](https://user-images.githubusercontent.com/31810626/160638585-04533c07-a9f8-4e15-9e19-5ebf5cbcea09.png)

**Comment by s936511** [comment]
TwRo will replace the protected system from nProtect to CheatDefender soon.
Poseidon server does not support CheatDefender.
Please close this issue#3572.
