### ISSUE TITLE
how does openkore tell if server alive?

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3575]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

I found 
\src\Network\DirectConnection.pm
```
sub serverAlive {
	return $_[0]->{remote_socket} && $_[0]->{remote_socket}->connected();
}
```
and then I am lost , where is the further function?

I also found shorter value '1.8' in RagnarokServer.pm line 911 `if (timeOut($clientdata{$index}{emoticonTime}, 1.8))` can help ROclient stay connected to poseidon , if anyone need this.
* **Summary**:

**Comment by alisonrag** [comment]
$_[0]->{remote_socket} is a instance of `IO::Socket::INET` that use `IO::Socket` as base
https://github.com/OpenKore/openkore/blob/8795c03bcb22113a3b1f70ab3ecabbba2298ce90/src/Network/DirectConnection.pm#L70

so your function can be found here:
https://perldoc.perl.org/IO::Socket#connected

**Comment by NNagatoYuki** [comment]
你好，私个联系方式？1095581313@qq.com
