### ISSUE TITLE
bot is stucked, keeps attacking dead monsters/desync monster

### ISSUE THREAD

**Issue by kyloren23** [OpenKore/openkore#3578]
[](https://i.imgur.com/fFLkciU.png)
https://i.imgur.com/fFLkciU.png
i really have issue with dead monsters/desync monsters.. bot stucked forver keeps hugging and attacking it ..failing to teleport even with teleportAuto_unstuck 1
teleportAuto_lostTarget 1
teleportAuto_dropTarget 1 

 if you type "ml" console says there is a monster detected beside your character (literally 1 cell beside you) even there is no monster present on my screen (xkore1) it only get fixed. if i char select or teleported away.

im thinking of temporary solution how do i check my character in same position for like 15-20seconds then teleport? i hope you guys can help me

```
automacro unstucked {
    location gef_fild04
    status not Sitting
    timeout 60
    call {
        :Start
        $old = $.pos
        log Before $old

        do teleport

        $new = $.pos
        log After $new

        if ($old == $new) goto Start
        if ($old != $new) goto End

        :End
        log Moved
        stop
}
}
```

**Comment by alisonrag** [comment]
use this branch:
https://github.com/OpenKore/openkore/tree/fin-unreachable-npc

**Comment by kyloren23** [comment]
> use this branch: https://github.com/OpenKore/openkore/tree/fin-unreachable-npc

hello again, there are too much edited branches to your repository, i dont know which one of folder exactly? can you please tell which of your folder should i merge?? misc folder?? 

also my openkore is heavily modded to work with my server ro ggh, im not sure if this might mess up some packets

**Comment by alisonrag** [comment]
i saw this dll and it is not parsing all the data, because some packets are encrypted. so i'm closing this because this is not a openkore issue, its related to your "bypass"/"client mod"
