### ISSUE TITLE
Can't Connect to kRO

### ISSUE THREAD

**Issue by rodriigm** [OpenKore/openkore#3580]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  2022_04_18

* **Server**:  kRO

* **Bug Report / Feature Request**: Bug Report

* **Summary**:  I'm not able to log with the open kore in kRO, after having Poseidon opened nothing happens with the open kore. Message is:
 Connecting to Account Server...
Connecting (112.175.128.137:6900)... connected
Timeout on Account Server, reconnecting. Wait 44 seconds...)

Can it be related to the server selection within kRO (Baphomet, Yggdrasil, etc.)?

**Comment by alisonrag** [comment]
use this pull request:
https://github.com/OpenKore/openkore/pull/3430

is necessary strawberry perl 5.32 and run openkore.pl using new dlls, u can get here:
https://github.com/OpenKore/openkore/suites/7684660984/artifacts/320811325

**Comment by inguKang9074** [comment]
> use this pull request: #3430
> 
> is necessary strawberry perl 5.32 and run openkore.pl using new dlls, u can get here: https://github.com/OpenKore/openkore/suites/7684660984/artifacts/320811325

hello sir. 
Plz Configuring Poseidon for kRo Guide

https://openkore.com/wiki/Configuring_Poseidon_for_twRO < i'm following
but i don't know KroDomain

`<?xml version="1.0" encoding="euc-kr" ?>

<no_free_server></no_free_server>
`

plz let me know KroDomain

**Comment by alisonrag** [comment]
Use #3514

**Comment by Cai7777** [comment]
> 使用此拉取請求： #3430
> 
> 是必需的 strawberry perl 5.32 並使用新的 dll 運行 openkore.pl，你可以在這裡： https: [//github.com/OpenKore/openkore/suites/7684660984/artifacts/320811325](https://github.com/OpenKore/openkore/suites/7684660984/artifacts/320811325)


How to log in to "TWRO" smoothly?

**Comment by kirby278** [comment]
> > use this pull request: #3430
> > is necessary strawberry perl 5.32 and run openkore.pl using new dlls, u can get here: https://github.com/OpenKore/openkore/suites/7684660984/artifacts/320811325
> 
> hello sir. Plz Configuring Poseidon for kRO Guide
> 
> https://openkore.com/wiki/Configuring_Poseidon_for_twRO < i'm following but i don't know kRO Domain..
> 
> <no_free_server></no_free_server>
> 
> plz let me know KroDomain

Same problem. Used #3514 , #3430 and other files as well to try and solve the problem but cannot.
Plz create a configuation guide for Poseidon kRO.
Tried using twRO and vRO and followed sample but does not work.
