### ISSUE TITLE
Hi need help i plan to reverse engineer a ragexe 

### ISSUE THREAD

**Issue by leonardNoobs** [OpenKore/openkore#3581]
can someone help me

what tools i need to know the source file

since i have a working bot but i pay a monthly subscription for it. so i plan if i can reverse engineer the ragexe so that i dont need to pay monthly subscription anymorer

thank you

**Comment by Melcons08** [comment]
Share your Bot files here and they will Customize it for you.. Remove first your user name and password in your config .before you share

**Comment by kyloren23** [comment]
even you bypass the ragexe ...you still gonna need to update the packets everytime there is maintenance/patch lol without the knowledge of how to unpack and read packets structure with programming knowledge. so its useless, unless you pay some developer to that for you every maintenance update

**Comment by alisonrag** [comment]
use this project to ask about packet extraction:
https://github.com/OpenKore/packetExtractor
