### ISSUE TITLE
Exchange shop '0B56'

### ISSUE THREAD

**Issue by polme32** [OpenKore/openkore#3582]
I searched NPC stores and found that they were all fixed packet lengths,

However, the amount of materials required for each item exchanged in this exchange shop is not fixed, which affects the length of the package. What should I do

**Comment by polme32** [comment]
[npc_store_info_new.txt](https://github.com/OpenKore/openkore/files/8536326/npc_store_info_new.txt)
![QQ图片20220422100351](https://user-images.githubusercontent.com/48077963/164582726-68050d84-d70b-4753-81f8-a381544e815d.png)
![QQ图片20220422100404](https://user-images.githubusercontent.com/48077963/164582732-1329c0ab-724b-4d1f-9494-2698fdacaab8.png)
![QQ图片20220422100617](https://user-images.githubusercontent.com/48077963/164582738-df1aecdf-07dd-4410-b8d3-5a8c049a4dcd.png)

**Comment by polme32** [comment]
[npc_store_info_new.txt](https://github.com/OpenKore/openkore/files/8536332/npc_store_info_new.txt)
[新建文本文档 (2).txt](https://github.com/OpenKore/openkore/files/8536333/2.txt)
[新建文本文档 (3).txt](https://github.com/OpenKore/openkore/files/8536334/3.txt)

**Comment by s936511** [comment]
![E22386B0-71A8-4510-BCE9-47EA3CCE3F76](https://user-images.githubusercontent.com/25875385/164873278-b2783c01-a9ed-4e30-8503-beb7d8ac0b70.jpeg) 

You can try to fix the receiver, make changes in your specific receiver or fix it, it can be changed in a simple way.

**Comment by polme32** [comment]
> npc_store_info_new.txt [新建文本文档 （2）.txt](https://github.com/OpenKore/openkore/files/8536333/2.txt) [新建文本文档 （3）.txt](https://github.com/OpenKore/openkore/files/8536334/3.txt)

but The length of the package will vary according to the amount of material required

**Comment by polme32** [comment]
> ![E22386B0-71A8-4510-BCE9-47EA3CCE3F76](https://user-images.githubusercontent.com/25875385/164873278-b2783c01-a9ed-4e30-8503-beb7d8ac0b70.jpeg)
> 
> 您可以尝试修复接收器，在特定接收器中进行更改或修复它，可以通过简单的方式进行更改。

but The length of the package will vary according to the amount of material required

**Comment by polme32** [comment]
npc_macket_info_pack  

I don't have this package name here. Do I need to update it myself

**Comment by alisonrag** [comment]
this kind of shop is not implemented at openkore

**Comment by polme32** [comment]
> 这种商店在openkore没有实现

Expect someone to improve him

**Comment by alisonrag** [comment]
related to #2586
