### ISSUE TITLE
openkore not reading custom monster name from monster.txt

### ISSUE THREAD

**Issue by oleokoong** [OpenKore/openkore#3583]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

openkore version March 2022

Server GGH Asia

Im try to farming at Novus monster..
in my Server there is 2 monster id sharing same monster Name
this is the default monster receive from server..
1715 Novus
1718 Novus

im try change the monster name, because i want to avoid 1718
openkore\tables\monster.txt , there is no monster.txt in sub directories
1715 Novus Baby
1718 Novus Adult

after restart kore, console still showing Novus

and i check with ml

its print

`-------------------------------- Monster List ---------------------------------
#   Name                        ID      DmgTo DmgFrom  Distance    Coordinates
0   Novus                       1718    0     0        5.1         (177, 208)
1   Novus[Unknown]              1718    0     0        5.1         (177, 208)
-------------------------------------------------------------------------------`

**Comment by alisonrag** [comment]
openkore only get name from monsters.txt if cant get name, today the packets send the name, so openkore just save it and not read

**Comment by alisonrag** [comment]
You can use ID in mon_control
