### ISSUE TITLE
How to install DBI with mysql in deps

### ISSUE THREAD

**Issue by nikkoxgonzales** [OpenKore/openkore#3585]
* **Openkore version git**: 78fe22c_2022-04-09 ctime:2022_04_10

* **Server**: Not server related

* **Bug Report / Feature Request**: DBI in deps

* **Summary**: How to install DBI w/ mysql in openkore deps so it will be using exe? Is it possible? I used ActivePerl 5.12 but no mysql.pm there. Trying to install using ppm results into HTTP 500 SSL negotiation Failed. Any work around? Probably because PPM is using outdated certificates due to the age of our version.

**Comment by alisonrag** [comment]
you can download direct from https://metacpan.org/pod/DBD::mysql
there is a link on left side, the issue could be the dependences, you will need to download and install all ant deps folder

also the 500 ssl is because of ssl version in this outdated version

**Comment by alisonrag** [comment]
you can download the dlls from newer version in actions, latest is here:
https://github.com/OpenKore/openkore/actions/runs/2112845325#artifacts

so u can use strawberry perl 5.12 and use the openkore.pl file

**Comment by nikkoxgonzales** [comment]
Thanks alison, what I did is I downloaded XSTools for perl 5.32, openkore.pl worked.
Now I use cpan to install MySQL, but when I ran it, I encountered this:
![image](https://user-images.githubusercontent.com/74746556/165387262-794dcd7f-a970-4633-a04e-fd1faa9b1639.png)

I know this is outside of openkore, but have you encountered the same error before? 

I tried downgrading my BDI but it won't install even with --force.
`cpanm https://cpan.metacpan.org/authors/id/T/TI/TIMB/DBI-1.613.tar.gz --force`

**Comment by alisonrag** [comment]
did u installed using this command `cpan install DBD::mysql` ?

**Comment by alisonrag** [comment]
be careful about deps folder, did u put something there?

**Comment by nikkoxgonzales** [comment]
I did put DBI.pm in deps which messed up the library. It's a dumb issue I had.
It's actually better now because I can use the latest strawberry perl in openkore.

Also for future reference, if you are trying to access MySQL DB on a hosted server or maybe even local if you run into issues like "caching_sha2_password" you can refer to this [link](https://stackoverflow.com/questions/50169576/mysql-8-0-11-error-connect-to-caching-sha2-password-the-specified-module-could-n/50333079#50333079).

Closing this ticket now, thanks, Alison.
