### ISSUE TITLE
Equipment in inventory disappears after mapchange

### ISSUE THREAD

**Issue by 10odnamj** [OpenKore/openkore#3586]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: version ctime:2022_04_23 

* **Server**:  kRO

* **Bug Report / Feature Request**: Bug Report

* **Summary**: When starting Kore and loading into the map or changing maps Kore does not load the equipment gear in the inventory. Other items (non-equipment gear) will show up as normal. I also noticed that while picking up items they show the wrong item type (usable heal or event item). I get (Packet Parser Unknown Switch 0B39) every time Kore loads into a map or map changes. Might be related.

![Packet Parser Unknown Switch 0B39](https://user-images.githubusercontent.com/11077174/169605914-6bdf2bdf-dc4a-465a-9354-22cce2b18341.PNG)

![Wrong Item Type](https://user-images.githubusercontent.com/11077174/169714808-e777a50f-9bc2-44b4-8073-7176b5b70222.PNG)

**Comment by NNagatoYuki** [comment]
new items_nonstackable
added one secondary armor field
4th armor

**Comment by 10odnamj** [comment]
> new items_nonstackable added one secondary armor field 4th armor

Thanks for you reply NNagatoYuki,

Where and what changes did you add?

**Comment by alisonrag** [comment]
use https://github.com/OpenKore/openkore/pull/3598 and add `itemListType 1` to your servers.txt
