### ISSUE TITLE
[twRO] XKore1 can't connect with RO client

### ISSUE THREAD

**Issue by Jack3606** [OpenKore/openkore#3592]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  openkore-master

* **Server**:  twRO

* **Bug Report / Feature Request**:  XKore1 can't connect with RO client

* **Summary**: Hi everyone,I'm come from twRO servers.

I use XKore1 mode before,but it doesn't work now.

It always stuck when connect with RO client.(as shown)

(somebody says need to modify ragexe.exe,but I don't know if it's correct or not)

Does anyone can teach me how to deal with it?

Appreciate it.

![00](https://user-images.githubusercontent.com/108250393/175860292-c2bc6687-7475-475c-aacd-2dc2ac552832.jpg)

**Comment by s936511** [comment]
https://openkore.com/wiki/XKore
https://openkore.com/wiki/netRedirect
NetRedirect it is DLL is "injected" into the RO client's address space. Once injected, we intercept all network traffic and redirect some of it to Kore.
https://github.com/OpenKore/openkore/blob/master/src/auto/XSTools/win32/netredirect.cpp
https://github.com/OpenKore/openkore/issues/3231
https://openkore.com/wiki/How_to_run_OpenKore#C.2FC.2B.2B_compiler
https://github.com/OpenKore/openkore/issues/837
https://www.youtube.com/watch?v=0Y20x4a60Tw

**Comment by st820210** [comment]
i have same question , i can't search solution for this QQ

**Comment by alisonrag** [comment]
same as #2183
