### ISSUE TITLE
Quest List Problem

### ISSUE THREAD

**Issue by gospelkiru** [OpenKore/openkore#360]
Suddenly the "quest list" only show 2 - 5 quest.

**Comment by c4c1n6kr3m1** [comment]
iRO ? mine is fine , just tested
how much do you have? more than 52?

**Comment by Henrybk** [comment]
Would you please explain more? Maybe post a picture of your problem.

**Comment by gospelkiru** [comment]
when i type "quest list" command only 2 - 3 quest list will show up.
![delete me](https://cloud.githubusercontent.com/assets/24469417/21149264/ebd05dc4-c195-11e6-962f-4d6af76a3c6a.jpg) I should have 10 - 15 quest active.

**Comment by farrainbow** [comment]
Can you repeat with the following in your config:
```
debugPacket_include 02B1, 02B2, 02B3, 02B4, 02B5, 02B7
debugPacket_include_dumpMethod 2
```

**Comment by gospelkiru** [comment]
finish.

**Comment by Henrybk** [comment]
@farrainbow would you please try out kill count plugin? Its in the pull requests here, it may solve some of your problems while we investigate the others.

**Comment by c4c1n6kr3m1** [comment]
just found another problem with quest_update_mission_hunt
i have 2 mission killing fabre
[code]
  2 11339 The most delicious on earth     active      
 -  Poring                          0/10
  3 11340 Carrots are delicious!          active      
 -  Lunatic                         0/10
  4 11341 Rolling Fabre's clothing        active      
 -  Fabre                           0/10
  5 11344 Barrier!!                       active      
 -  Pupa                            0/5
  6 60401 Drops Hunt                      active      
 -  Drops                           0/10
  7 60402 Lunatic and Fabre Hunt          active      
 -  Fabre                           0/10
 -  Lunatic                         0/10
[/code]
when i kill fabre, this is the packet
[code]
B5 02 1E 00 02 00 4D 2C 00 00 EF 03 00 00 0A 00 01 00 F2 EB 00 00 EF 03 00 00 0A 00 01 00
[/code]
when i kill poring, this is the packet
[code]
B5 02 12 00 01 00 4B 2C 00 00 EA 03 00 00 0A 00 01 00
[/code]
and as i said before , if you have 52 quests or more , iRO split and send double '097A' or more
so this line will make problem in quest_all_list2
[code]
$questList = {};
[/code]

**Comment by c4c1n6kr3m1** [comment]
another setback, if i have 2 quests hunt to killing the same monster , everytime i killed the target , i only get 1 mission updated , should both.

**Comment by alisonrag** [comment]
Someone can confirm this?
In last months we updated some quest subs

**Comment by c4c1n6kr3m1** [comment]
you can close it @alisonrag
