### ISSUE TITLE
[Help](twRO)connection to the fake Poseidon server failed

### ISSUE THREAD

**Issue by Bruce21404** [OpenKore/openkore#3618]
I followed this website to connect to the fake Poseidon server
(Website：https://openkore.com/wiki/Configuring_Poseidon_for_twRO)
But the connection failed
Server： twRO
![1](https://user-images.githubusercontent.com/112742145/188256016-f17502b9-f3a1-49cf-8de1-5f5aee0343d9.png)
![2](https://user-images.githubusercontent.com/112742145/188256017-7b500ff9-7f9d-4b30-a25a-8e3420dbdb82.png)
Please help me.

**Comment by alisonrag** [comment]
twRO is now using CheatDefender, poseidon is not needed. Will be necessary to figure out how to make openkore connect to the client
