### ISSUE TITLE
Rethink talk and talknpc

### ISSUE THREAD

**Issue by Henrybk** [OpenKore/openkore#362]
Right now we have many bugs with npc conversarions, such as auto talk continuation having no timeout, no way to talk to npcs which need to be approached, no way to use talknpc without coordinates, no way to use talk command without npc binID.

I think talknpc task should be initialized everytime a npc conversation is started, be it by command or by approaching it, and all npc management should be done by it, including all talk commands.

**Comment by AlexandreBR3N** [comment]
Everything should be done until he get this objective. Close the chat...
