### ISSUE TITLE
[bug] itemsTakeGreed ignore few items and use skill far away in some cases

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#3647]
* **Bug Report

* **Openkore version git**: 
https://github.com/OpenKore/openkore/commit/51332642d8eba92890819eb9cc339c9c2f3829f0

* **Server**: 
jRO

* **Summary**:
1. bot ignore few loot dropped by the monster if GatherAuto is off
https://www.youtube.com/watch?v=vP9HOJDm-Y4

2.  bot try to use greed too far (bug position?)
https://www.youtube.com/watch?v=Z1s15BFC5hE

3. Need to remember to add timeout to Greed

**Comment by FrozenCube** [comment]
These are games rules and cannot be implemented at free source code, you can compile solutions onto wxstart.
