### ISSUE TITLE
remove monster beyond clientSight from monster list

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3652]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

all
* **Bug Report / Feature Request**:

in misc.pm , there is a sub 
`sub processNameRequestQueue`
it says ,  Remove actors with a distance greater than clientSight. Some private servers (notably Freya) use a technique where they send actor_exists packets with ridiculous distances in order to automatically ban bots. By removingthose actors, we eliminate that possibility and emulate the client more closely. 
but it seems this sub only works for npcs or players  , how to make it work for monsters and items ? 
for some reason , monsters or items can stuck at screen even when they don't exist , but bot will try to lock them

* **Summary**:

Feature Request

**Comment by hubertyang88** [comment]
Is it ok  if I do this ?
add 
`next if (blockDistance($monster->{pos}, calcPosition($char)) >= ($config{clientSight} || 16));`
to corelogic.pm
`sub processAutoAttack `

			foreach (@monstersID) {
				next if (!$_ || !checkMonsterCleanness($_));
				my $monster = $monsters{$_};
				next if (!timeOut($monster->{attack_failed}, $timeout{ai_attack_unfail}{timeout}));
				# Never attack monsters that we failed to get LOS with
				next if (!timeOut($monster->{attack_failedLOS}, $timeout{ai_attack_failedLOS}{timeout}));
				next if (blockDistance($monster->{pos}, calcPosition($char)) >= ($config{clientSight} || 16));
`

**Comment by alisonrag** [comment]
i had some issues with items and monster too, should we ignore add it to actor list when it is too far?
also should we add or fix some function that remove actor that has distance more then clientSight?

**Comment by hubertyang88** [comment]
Please do both , ignore and not add it to actor list when it is too far  and remove actor that has distance more then clientSight.
you can add a boolean in config to switch this on/off.
when bot tele , the list seems to be refreshed , what trigger this refresh , some function or some packets send by sever?

**Comment by hubertyang88** [comment]
I saw you guys already fix it , #3667 ,THX
