### ISSUE TITLE
private server connect problem

### ISSUE THREAD

**Issue by lym0811** [OpenKore/openkore#3654]
could someone help me to check the server information correct or not,

it's a private server, when i connect to the server and select charater, it would have an error like this....

![image](https://user-images.githubusercontent.com/114160844/191755317-8080e124-3397-4e75-983d-2df49cba61e1.png)

![image](https://user-images.githubusercontent.com/114160844/191755625-c802ed17-bbe9-49d2-91c9-589f19c014fd.png)

**Comment by alisonrag** [comment]
dont use official server table folder to private, also serverType is not valid use adding date, to a private server the servers.txt should look like this:

```
[icarRO]
ip 61.220.80.223
port 2006
master_version 5
version 1
serverType kRO_RagexeRE_2020_04_01b
serverEncoding Big5
addTableFolders kRO/Ragexe_2020_04_01b;translated/kRO_english
charBlockSize 155
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
pinCode 0
charDeleteDateType 1
rankingSystemType 1
gameGuard 0
private 1
itemListType 1
```

**Comment by lym0811** [comment]
thanks 
so my master version and version correct? 
because i follow the step didn't know how to calculate the numbers

**Comment by lym0811** [comment]
if i use the official server table folder could be enter the sever like this

![image](https://user-images.githubusercontent.com/114160844/191770162-fe677f87-659d-478b-ab8f-8c48e8179156.png)


if i use the other table folder, can't enter the server

**Comment by alisonrag** [comment]
2 things:
1 - `charBlockSize` is wrong, you should be able to see the character info at character select screen. try other from the list of availabe charblocksize: https://openkore.com/wiki/charBlockSize

2 - you are getting disconnected because you are connecting the openkore in a map that dont exists, you will need to add it in fields folder:
https://openkore.com/wiki/FLD_Creation_Guide

**Comment by lym0811** [comment]
great! it worked

 but i still can't understand the second thing,

where can i find the  map (gat & rsw)

**Comment by alisonrag** [comment]
from server grf file
