### ISSUE TITLE
about BetterWalkPlan v2 

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3668]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
all

* **Server**: 

all
* **Bug Report / Feature Request**:

@Henrybk 
#3653 , To turn on BetterWalkPlan ,  is `betterWalkPlan 1`  needed in config.txt?
 could you pls add more options for this "betterWalkPlan", for example, 1 means walks forward of the walking list , 2 means backward , 3 means randomward but reach one point only once in one sequence , because it's very likely more than one bot are placed in same map , they will all walk in same route .....
* **Summary**:

 Feature Request

**Comment by Henrybk** [comment]
Last update added the 'random' key
