### ISSUE TITLE
twRo  Packet Parser: Unknown switch: 

### ISSUE THREAD

**Issue by sny12130** [OpenKore/openkore#3671]
- **Bug Report

- Openkore version git:
https://github.com/OpenKore/openkore/commit/51332642d8eba92890819eb9cc339c9c2f3829f0

- Server:
twRO

- Summary:
openkore open and then i see this problem ,how can i solve it thx ?!

console.txt
Packet Tokenizer: Unknown switch: 0007
Packet Tokenizer: Unknown switch: 0009
Packet Tokenizer: Unknown switch: 0009
Packet Tokenizer: Unknown switch: 000B
Packet Tokenizer: Unknown switch: 0028
Packet Tokenizer: Unknown switch: 001F
Packet Tokenizer: Unknown switch: 0008
Packet Tokenizer: Unknown switch: 002A
Packet Tokenizer: Unknown switch: 0038
Packet Parser: Unknown switch: 0065
Packet Tokenizer: Unknown switch: 0000

**Comment by alisonrag** [comment]
this is because of cdclient the shield of twro. continue in #3474
