### ISSUE TITLE
avoid ground skill

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3673]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
latest
* **Server**: 
all
* **Bug Report / Feature Request**:

how to avoid ground skill , such as fire pillar or trap ?
can new path finding deal with this issue?
* **Summary**:

Feature Request

**Comment by Henrybk** [comment]
Currently there is no official way of avoiding those, I have a plugin for this purpose but it is still in development if you want to try.

https://github.com/Henrybk/Plugins/blob/master/NewAStarAvoid/NewAStarAvoid.pl

Just gotta add the spellID to
%area_spell_type_obstacles, with like dist 12 and weight 1500

**Comment by hubertyang88** [comment]
thank you

**Comment by hubertyang88** [comment]
my %area_spell_type_obstacles = (
	'80' => {
		weight => 1500,
		dist => 4
	}

it seems not working , is there anything need to do in src file?
