### ISSUE TITLE
sendcryptkeys VanRO Classic

### ISSUE THREAD

**Issue by krispaul27** [OpenKore/openkore#3680]
# http://vanserver.com
[Classic - Vanro]
ip classic-asia.vanserver.com
port 8500
master_version 50
version 35
secureLogin 0
sendCryptKeys
clientHash F3317EC20A442D9D8014D67EA4158254
#sendCryptKeys 0x0, 0x0, 0x0
![image](https://user-images.githubusercontent.com/8620097/198886280-50e04dba-7d33-4b85-a26a-bb140ff27748.png)

**Comment by alisonrag** [comment]
gepard shield, there is no support to custom packet encryption

**Comment by krispaul27** [comment]
How to get rid of this ? atleast you drop some hint. :)
