### ISSUE TITLE
help twro

### ISSUE THREAD

**Issue by philip15142** [OpenKore/openkore#3684]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

[connection] 對角色伺服器關閉連線
[connection] 斷線中 (219.84.200.98:10029)...[connection] 已斷線
[connection] 正在連線至地圖伺服器...
[connection] 連線中 (twro-zone-3d.gnjoy.com.tw:10013)... [connection] 已連線
[connection] Packet Tokenizer: Unknown switch: 0007
[connection] Packet Tokenizer: Unknown switch: 0009
[connection] Packet Tokenizer: Unknown switch: 0009
[connection] Packet Tokenizer: Unknown switch: 0028
[console] Packet Parser: Unknown switch: 0112
[connection] Packet Tokenizer: Unknown switch: 000B
[connection] Packet Tokenizer: Unknown switch: 0008
[connection] Packet Tokenizer: Unknown switch: 000B
[connection] Packet Tokenizer: Unknown switch: 0014
[connection] 地圖伺服器逾時, 連線至帳號伺服器中...
[connection] 斷線中 (219.84.200.103:10013)...[connection] 已斷線

**Comment by pomahuang** [comment]
I have same problem as you, looking forward programmer help check how we can fix it.

**Comment by LycorisRecoil-NishikigiChisato** [comment]
Issues in twRO
[Issues in twRO #3474](https://github.com/OpenKore/openkore/issues/3474)
commented on Nov 18, 2021
vRO and twRO are no longer supported.
Cause:
nProtect now detects Poseidon and closes the game client
[updating server information #3544](https://github.com/OpenKore/openkore/pull/3544)
commented on Dec 19, 2021.
The protection has changed on twRO. Cheat Defender is now used.
[readme update #3539](https://github.com/OpenKore/openkore/pull/3539)
https://www.youtube.com/watch?v=_pzS4w5rVeU
