### ISSUE TITLE
In cRo use poseidon eject nProtect GameGuard The program is closed

### ISSUE THREAD

**Issue by taxaser** [OpenKore/openkore#3694]
## ------------------ Openkore Issues Template ------------------

![QQ图片20230125231713](https://user-images.githubusercontent.com/1031857/214601571-d966f4c9-4bdd-410c-b616-cb3ea1746801.png)

* **Openkore version git**: 

* **Server**:  Cro

* **Bug Report / Feature Request**: 

* **Summary**:  Refer to the configuration of vro

**Comment by alisonrag** [comment]
will be necessary 2 pcs, 
1 with openkore and poseidon and other with client, 
also is necessary in ragnarok pc change host from windows to redirect ragnarok connection to other pc, 
also cant use local ips lik:e 127.0.0.1, 192.168.x.x and 10.0.x.x
