### ISSUE TITLE
[bug] [attack] openkore stuck when monster use Hiding skill

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#3695]
**Bug Report**
* **Openkore version git**: 
https://github.com/OpenKore/openkore/commit/1417e68ac69649f58bf991eb0bf455549deedd1a
* **Server**: 
all
* **Summary**:
when attack some monster and monster use Hiding, openkore just stuck at same position until the monster appear again or droptarget time is reeached.
I'm suggesting to add a config key to drop monster or avoid hiding monsters

**Comment by hubertyang88** [comment]
if bot want to farm monsters have hide skill , Sight skill need to be prepared 
HORONG card has sight skill

attackSkillSlot Sight {
	lvl 1
	dist 2
	whenStatusInactive Sight
	monsters xxx
	target_whenStatusActive hide
	timeout 10
}
it's tested
