### ISSUE TITLE
Can't call method "inventory" on an undefined value at src/Network/Receive.pm line 6963.

### ISSUE THREAD

**Issue by cat00107** [OpenKore/openkore#3697]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

OpenKore version what-will-become-2.1

* **Server**: 

twRO

* **Bug Report / Feature Request**:

OpenKore version what-will-become-2.1
Network state = 4
Network handler = Network::DirectConnection
Revision: ctime:2023_01_29
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Can't call method "inventory" on an undefined value at src/Network/Receive.pm line 6963.

Stack trace:
Can't call method "inventory" on an undefined value at src/Network/Receive.pm line 6963.
 at src/Network/Receive.pm line 6963
	Network::Receive::item_upgrade('Network::Receive::twRO=HASH(0x79a8df4)', 'HASH(0x7b9817c)') called at src/Network/PacketParser.pm line 279
	Network::PacketParser::parse('Network::Receive::twRO=HASH(0x79a8df4)', '\x{88}\x{1}\x{0}\x{ff}\x{a}\x{85}\x{1}\x{13}', 'Network::Receive::twRO=HASH(0x79a8df4)') called at src/Network/Receive.pm line 579
	Network::Receive::parse('Network::Receive::twRO=HASH(0x79a8df4)', '\x{88}\x{1}\x{0}\x{ff}\x{a}\x{85}\x{1}\x{13}', 'Network::Receive::twRO=HASH(0x79a8df4)') called at src/Network/PacketParser.pm line 413
	Network::PacketParser::process('Network::Receive::twRO=HASH(0x79a8df4)', 'Network::MessageTokenizer=HASH(0x3c28914)', 'Network::Receive::twRO=HASH(0x79a8df4)') called at src/functions.pl line 834
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4e6f8f4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

在這一行當掉:
  
* 	my $item = $char->inventory->getByID($index);
  	if ($item) {

* **Summary**:

Sorry to bother everyone, I just started to learn to use "Openkore", and encountered the above problems during execution, can you seniors have any solutions to solve this problem?
Thank you everyone.

**Comment by alisonrag** [comment]
your `$char` is not defined, means that your charBlockSizeis wrong
https://openkore.com/wiki/charBlockSize
