### ISSUE TITLE
why there is teleport function in sub updateDamageTables?

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3704]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
latest
* **Server**: all

* **Bug Report / Feature Request**:

in misc.pm
sub updateDamageTables
there are quite a few lines function about teleport , the problem is when bot is hit by many monsters , and it seems this sub
has no timeout , it will send many times teleport request in short time to cause bot freeze and fail to teleport . 
I searched in src , only found this sub is called in \Network\Receive by skill_use , I am lost there.  

When is this sub updateDamageTables  called? It's need a timeout!
at least teleportAuto_hp part should be removed from this sub
Am I looking at right sub?
* **Summary**:

Can anyone help?
@alisonrag @ya4ept

**Comment by hubertyang88** [comment]
it will help a bit , but when there are too many monsters (over 20) on same spot , specially ranger monster , there always is possibility for bot be killed on sight.

**Comment by alisonrag** [comment]
suggest to move all direct calls to teleport skill in useTeleport to corelogic or create a task to do this

**Comment by hubertyang88** [comment]
That is too hard for me 😵‍💫

**Comment by alisonrag** [comment]
continue in #3711
