### ISSUE TITLE
Unable to BOT. Cannot load field prt_mz03_i: No corresponding field file found for field 'prt_mz03_i'

### ISSUE THREAD

**Issue by R1990s** [OpenKore/openkore#3707]
Hello Guys, I'm getting a "cannot load field prt_mz03_i" error every time I try to access prt_mz03_i / (Illusion of Labyrinth). It shows no corresponding field file found. Need help thanks.

**Comment by alisonrag** [comment]
https://openkore.com/wiki/FLD_Creation_Guide
