### ISSUE TITLE
[eventMacro] EventMacro Not Working Auto , after manual reload and running

### ISSUE THREAD

**Issue by Topongoro** [OpenKore/openkore#3708]
------------------ Openkore Issues Template ------------------
Openkore version git:
Server:
Bug Report / Feature Request: 
I have tried several things about eventMacro bugs, but I am having problems with eventMacro in openkore Files
1. eventMacro is not trigged auto when I run openkore
2. EventMacro can run after I type the manual console command in the /reload all screen
3. I've searched various forums and tried several things but until now I haven't found a solution

i hope i get some help here
Summary:

**Comment by alisonrag** [comment]
Try this branch:
https://github.com/OpenKore/openkore/tree/bugfix/hotfix-revert-callhooks-update

or download it direct
https://github.com/OpenKore/openkore/archive/refs/heads/bugfix/hotfix-revert-callhooks-update.zip

since the following commit the hooks are not working as it should:
https://github.com/OpenKore/openkore/commit/1417e68ac69649f58bf991eb0bf455549deedd1a

**Comment by Topongoro** [comment]
Thanks i will try

**Comment by Topongoro** [comment]
@alisonrag its work , my event macro , but i feel freze 20 second after login and change map , i try this  #1698 , ##1693  not working ,  im feel bad

**Comment by alisonrag** [comment]
just go to timeouts and change:
`ai_clientSuspend 10` to `ai_clientSuspend 1`

**Comment by Topongoro** [comment]
@alisonrag im try , but same , freze after change map , y macro every time stuck any solution ? but thanks before my server Idro

**Comment by alisonrag** [comment]
i'm not sure what is heppening, are u connected using xkore 0 or 1?

**Comment by Topongoro** [comment]
im using xkore 0 

Received packet: 0095 Handler: actor_info
Received object info: Sprakki#newbe05
NPC Info: Sprakki#newbe05 (0)
AI:  | 1
AI:  | 1
AI:  | 1
AI:  | 1
Moving to 103, 15
You on route to: Tempat Pelatihan(new_1-2): 103, 15
Route You Solution Ready! Found path on new_1-2 from 101 17 to 103 15. Size: 2 steps.
Route You - movement vector confirmed.
Route You - not trimming down solution (3) because best_pos_step is 0.
Route You - next step moving to (103, 15), index 2, 3 steps left
Move You (to 103 15) - trying (1)
Sent move to: 103, 15
Move You (to 103 15) - trying (2)
Sent move to: 103, 15
Received packet: 0187 Handler: sync_request
AI: route | 2
Move You (to 103 15) - trying (3)
Sent move to: 103, 15
Move You (to 103 15) - trying (4)
Sent move to: 103, 15
Move You (to 103 15) - timeout
Route You - not trimming down solution (3) because best_pos_step is 0.
Route You - next step moving to (103, 15), index 2, 3 steps left
Move You (to 103 15) - trying (1)
Sent move to: 103, 15
Sent Sync
Move You (to 103 15) - trying (2)
Sent move to: 103, 15
Received packet: 007F Handler: received_sync
Received Sync
Move You (to 103 15) - trying (3)
Sent move to: 103, 15
Move You (to 103 15) - trying (4)
Sent move to: 103, 15
Move You (to 103 15) - timeout
Route You - not trimming down solution (3) because best_pos_step is 0.
Route You - not moving, decreasing step size to 1
Move You (to 102 16) - trying (1)
Sent move to: 102, 16

**Comment by Topongoro** [comment]
@alisonrag 

I get this Code  and player can move 

Sent move to: 143, 111
Move You (to 143 111) - trying (3)
Sent move to: 143, 111
AI: route macro | 3
**Sent get player info: ID - C5 ED 00 00**
