### ISSUE TITLE
Not detect statuses EFST_SPELLBOOK7

### ISSUE THREAD

**Issue by R1990s** [OpenKore/openkore#3714]
sorry to ask, why in openkore is now undetecable statusinactive EFST_SPELLBOOK7 ? does anyone know ? thx

**Comment by alisonrag** [comment]
EFST_SPELLBOOK7 is already at statusnametable, what openkore version are u using? how to reproduce your issue?
![image](https://user-images.githubusercontent.com/10372732/216981703-06e90673-58d3-498e-9964-df548b3627ac.png)
