### ISSUE TITLE
[Feature Request] Rodex use openType

### ISSUE THREAD

**Issue by hubertyang88** [OpenKore/openkore#3715]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: latest

* **Server**: all

* **Bug Report / Feature Request**:

when a rodex mail is sent by system , the type of mail is 1
but in Commands.pm
read mail packet is 
`$messageSender->rodex_read_mail(0,$arg2,0);`
it need to be
`$messageSender->rodex_read_mail(1,$arg2,0);`

it is same for delete and getitems

this is tested , wait for a fix 
And it seems the type of mail  is not processed in Receive.pm . Can bot get type of mail and use it in $messageSender? 
* **Summary**:

**Comment by hubertyang88** [comment]
We can add  rodextype 0||1 in config.txt
and add $type anywhere needed. it works
```
sub cmdRodex {
	my (undef, $args) = @_;
	my ($arg1) = $args =~ /^(\w+)/;
	my ($arg2) = $args =~ /^\w+\s+(\S.*)/;
	my $type = ($config{rodextype} || 0);
......
$messageSender->rodex_delete_mail($type,$arg2,0);
```

**Comment by alisonrag** [comment]
@hubertyang88 can u test #3716 ?
`rodex open 0|1|2`

```
0 = normal
1 = account
2 = returned
```

can u test all other commands: read, delete, getitem, getzeny

**Comment by hubertyang88** [comment]
rodex open 1: read, delete, getitem, are tested , works fine

**Comment by ya4ept** [comment]
@hubertyang88 can you test #3716 again?

**Comment by hubertyang88** [comment]
tested below ;
rodex open , read with mail_# , it is much better than using mail_ID
I don't have any admin mails for now , so admin mail is not tested.

I use wireshark to see “receive all” and “delete all” button ， they just send many receive or delete packets at same time
so I guess bot don't need to read a mail to getitems.
I tried below ，rodex getitems xxxxx without reading a mail works

```
	} elsif ($arg1 eq 'getitems') {
		if (!defined $rodexList) {
			error T("Your rodex mail box is closed.\n");
			return;

		} elsif (defined $rodexWrite) {
			error T("You are writing a rodex mail.\n");
			return;

		#} elsif (!exists $rodexList->{current_read}) {
			error T("You are not reading a rodex mail.\n");
		#	return;

		#} elsif (scalar @{$rodexList->{mails}{$rodexList->{current_read}}{items}} == 0) {
			error T("The current rodex mail has no items.\n");
		#	return;
		}

		my $openType = $rodexList->{mails}{$rodexList->{current_read}}{openType};
		message T("Requesting items of current rodex mail.\n");
		$messageSender->rodex_request_items($arg2, 0, $openType);
```
Could you please make  "rodex getitems mail_#" with no requirement of reading mail ,  and also "rodex delete mail_#"

**Comment by hubertyang88** [comment]
I did below in macro , it works .
but this macro can only read one page ,  how to read mails in multi in one sub ?

```
sub dealmail {
	my $count = 0 ;
	foreach my $mail_id (keys %{$rodexList->{mails}}) {
	$messageSender->rodex_request_items($mail_id, 0, 0);
	$messageSender->rodex_delete_mail(0,$mail_id,0);
	$count++;
	last if ($count >= 16);
	next;
	}
	return 1;
}

macro dmail {
do rodex open
pause 5
$kk = dealmail()
pause 7
do rodex close
}
```

**Comment by ya4ept** [comment]
> Could you please make "rodex getitems mail_#" with no requirement of reading mail , and also "rodex delete mail_#"

done: [c0300c8](https://github.com/OpenKore/openkore/pull/3716/commits/c0300c88e85f63011d30375a37fb55401042e9da)

**Comment by hubertyang88** [comment]
Tested , Excellent work ! From now on , we can deal mails with mail_# 👍
