### ISSUE TITLE
How to prevent Poseidon server from being detected by nprotect gameguard

### ISSUE THREAD

**Issue by CloudMake** [OpenKore/openkore#3718]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

latest 
* **Server**: 

cRO
* **Bug Report / Feature Request**:

Feature Request
* **Summary**:

After the update on February 7, 23, the gameguard program of the cRO client was upgraded from version 2675 to version 2690. Now the client detects an illegal program after connecting to the poseidon server. Please help me to update the settings of cRO. Thank you very much!

**Comment by sOm2y** [comment]
yep i got the same issue with cRO, posidon was working fine even running in the same OS with Ragexe client. After this new patch, posidon server has been detected by nProtect no matter it's in vm or different os. Would love to help and figure it out what's going on if core devs can give us a direction, cheers.

**Comment by sOm2y** [comment]
Did some investigation and tried couple way to setup poseidon but all failed:
1. setup local poseidon(default port 6900) with ragexe client in same OS (managed to get way working before) - Failed
2. local vm(including vmware workstation, hyper v, default port 6900) using vpn like logmein, radmin, being detected by nprotect gameguard straightway - Failed
3. remote vm(azure vm, setup networking with default port 6900 open) no vpn connection - Failed
It seems nprotect gameguard can detect poseidon no matter what OS you are on, it has to be from the network packages.
Further investation: need to analysis the network packages between ragexer client and nprotect

**Comment by TorresVan** [comment]
The same problem occurred in XKORE3 mode.

![console](https://user-images.githubusercontent.com/125642080/219589215-d841c8e2-df09-423d-a632-2781565bad04.png)

![error](https://user-images.githubusercontent.com/125642080/219589230-b281297c-ac6d-41a2-b8c7-563cf308a394.jpg)

**Comment by Fruitard** [comment]
> The same problem occurred in XKORE3 mode.
> 
> ![console](https://user-images.githubusercontent.com/125642080/219589215-d841c8e2-df09-423d-a632-2781565bad04.png)
> 
> ![error](https://user-images.githubusercontent.com/125642080/219589230-b281297c-ac6d-41a2-b8c7-563cf308a394.jpg)

where did you guys download cRO? i cant seem to get the link to work

**Comment by TorresVan** [comment]
> where did you guys download cRO? i cant seem to get the link to work

http://ro.qiquanwl.com/download/game/default.html

**Comment by Fruitard** [comment]
> > where did you guys download cRO? i cant seem to get the link to work
> 
> http://ro.qiquanwl.com/download/game/default.html

thank you, but i cant register as i verify my ID

**Comment by Nanotechboy** [comment]
Hiding bypass detection

**Comment by taxaser** [comment]
> Hiding bypass detection

How to do it specifically?

**Comment by CroJJJ** [comment]
> 做了一些调查，并尝试了几种方法来设置波塞冬，但都失败了：
> 
> 1. 安装本地波塞冬(默认端口6900)与同一个操作系统中的regexe客户端交互(在此之前设法工作)-失败
> 2. 本地VM(包括vmware工作站、hyper v、默认端口6900)使用vpn(如LogMeIn、Radmin)，由nProtection游戏守卫直接检测到-失败
> 3. 远程VM(Azure VM，设置默认端口6900打开的网络)没有VPN连接失败
> 
> 看来，无论你在什么操作系统上，都可以检测到Poseidon，这必须是游戏保护，改变了验证机制，或者是网络包改变了。
> 
> 进一步的投资：需要分析拉格瑟客户端和nsecurity之间的网络包。
> 
> 我仍然是这个领域的新手，如果仍然有积极的开发人员/专业人士可以帮助我们，我会非常谨慎。将提供资金：)



> 是的，我在CRO上遇到了同样的问题，Posidon在Ragexe客户端运行在同一个操作系统上也很好。在这个新的补丁程序之后，nProtect已经检测到了posidon服务器，不管它是在VM中还是在不同的操作系统中。如果核心开发人员能给我们一个方向，干杯，我很乐意帮你弄清楚到底发生了什么。



> yep i got the same issue with cRO, posidon was working fine even running in the same OS with Ragexe client. After this new patch, posidon server has been detected by nProtect no matter it's in vm or different os. Would love to help and figure it out what's going on if core devs can give us a direction, cheers.



> yep i got the same issue with cRO, posidon was working fine even running in the same OS with Ragexe client. After this new patch, posidon server has been detected by nProtect no matter it's in vm or different os. Would love to help and figure it out what's going on if core devs can give us a direction, cheers.

Is now the problem solved?

**Comment by CroJJJ** [comment]
> yep i got the same issue with cRO, posidon was working fine even running in the same OS with Ragexe client. After this new patch, posidon server has been detected by nProtect no matter it's in vm or different os. Would love to help and figure it out what's going on if core devs can give us a direction, cheers.

Is now the problem solved?

**Comment by sOm2y** [comment]
> > yep i got the same issue with cRO, posidon was working fine even running in the same OS with Ragexe client. After this new patch, posidon server has been detected by nProtect no matter it's in vm or different os. Would love to help and figure it out what's going on if core devs can give us a direction, cheers.
> 
> Is now the problem solved?

you could try this: https://github.com/zhaodice/qemu-anti-detection

**Comment by alisonrag** [comment]
its not related to openkore, but related to methods to avoid nprotect detect changes, nothing in openkore code will change this
