### ISSUE TITLE
Packet Parser: Unknown switch: 0AC4

### ISSUE THREAD

**Issue by Sensuii** [OpenKore/openkore#3726]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: idk,the "find version git" site has not working

* **Server**: NunRO
 bRO
* **Bug Report / Feature Request**:

* **Summary**:
 i receive this error https://uploaddeimagens.com.br/imagens/WzJy1r4

**Comment by alisonrag** [comment]
please provide more information: like your servers,txt setup, seems like wrong servertype, 0AC4 is already implemented at openkore source

**Comment by Sensuii** [comment]
[NunRO]
ip 167.114.189.192
port 6900
version 56
master_version 16
serverType 22
serverEncoding Western
addTableFolders bRO
charBlockSize 124
recvpackets recvpackets.txt

**Comment by alisonrag** [comment]
`serverType 22` is wrong, these numericals are not used anymore.
try https://openkore.com/wiki/serverType

to antecipate your attempts, the most commom servertypes are:
20180620:
```
serverType kRO_RagexeRE_2018_06_20e
addTableFolders kRO/RagexeRE_2018_06_21a;translated/kRO_english
```

20200401:
```
serverType kRO_RagexeRE_2020_04_01b
addTableFolders kRO/RagexeRE_2020_04_01b;translated/kRO_english
```

20211103:
```
serverType kRO_RagexeRE_2021_11_03
addTableFolders kRO/Ragexe_2021_11_03;translated/kRO_english
```

**Comment by Sensuii** [comment]
i tryed the three and receive this error in all tries https://uploaddeimagens.com.br/imagens/OZejjCU

**Comment by ya4ept** [comment]
what is written there?

**Comment by ya4ept** [comment]
try adding the `kRO` folder to the `addTableFolders` parameter

**Comment by Sensuii** [comment]
when i tried i tried servertype along with addtablefolders from alisonrag's post

**Comment by ya4ept** [comment]
do you understand the text of the error?

**Comment by alisonrag** [comment]
`failed to load itemsslots.txt`
you are doing something wrong at servers.txt, because this file is at the kRO_english folder:
![image](https://user-images.githubusercontent.com/10372732/220660694-4de2b86e-2b33-4239-8ed4-98319d08b820.png)

**Comment by Sensuii** [comment]
i downloaded openkore from your link and copy/paste your servers.txt info,and receive this https://uploaddeimagens.com.br/imagens/8Ak2bVw

servers.txt info
[NunRO]
ip 167.114.189.192
port 6900
version 56
master_version 16
serverType kRO_RagexeRE_2020_04_01b
addTableFolders kRO/RagexeRE_2020_04_01b;translated/kRO_english
serverEncoding Western
charBlockSize 124
recvpackets recvpackets.txt
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9

**Comment by alisonrag** [comment]
wrong charblocksize, list:
https://openkore.com/wiki/charBlockSize

**Comment by Sensuii** [comment]
i used charblocksize 175 and receive this https://uploaddeimagens.com.br/imagens/T1cKrTI

**Comment by alisonrag** [comment]
```
# http://167.114.189.192/
[NunRO]
ip 167.114.189.192
port 6900
version 56
master_version 16
serverEncoding Western
serverType kRO_RagexeRE_2017_05_17a
addTableFolders kRO/RagexeRE_2017_05_17a;translated/kRO_english
charBlockSize 147
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
```

this server has custom maps and the grf is encrypted try to find the maps somewhere in the internet and use this tutorial to convert to fld https://openkore.com/wiki/FLD_Creation_Guide

**Comment by carry4not** [comment]
sir alisonrag pls help i have a problem i got error unknown witch 8ec4

**Comment by alisonrag** [comment]
> sir alisonrag pls help i have a problem i got error unknown witch 8ec4 and when i try this serverType kRO_RagexeRE_2021_11_03 addTableFolders kRO/Ragexe_2021_11_03;translated/kRO_english the error was unknown switch A90B

this id is not valid, it means that ur recvpackets/servertype is wrong
