### ISSUE TITLE
cant find RagexeRE_2022_02_21 in src/Network/Receive/kRO

### ISSUE THREAD

**Issue by fildabert** [OpenKore/openkore#3735]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
* latest, cloned master branch

* **Server**: 
* private server

* **Bug Report / Feature Request**:
* Feature Request

* **Summary**:
* I'm following the connectivity guide from the manual and i'm stuck in serverType section since my ragnarok.exe compilation date is at 2022-02-21 and the RagexeRE files in `src/Network/Receive/kRO` are only until `RagexeRE_2020-04_01_b`

**Comment by alisonrag** [comment]
latest rathena support is 20211103
https://github.com/rathena/rathena/blob/3f45df102501908843cea81a0655fce210984f2d/src/config/packets.hpp#L16

there is a pull request to this:
https://github.com/OpenKore/openkore/pull/3701


clients after this date are not supported by openkore

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/issues/2702
