### ISSUE TITLE
Timeout on map server

### ISSUE THREAD

**Issue by Fruitard** [OpenKore/openkore#3737]
**------------------ Openkore Issues Template ------------------**

- Openkore version git:
  Using latest version

- Server:
  Private server

- Bug Report / Feature Request:
  after selecting character, openkore just timeout on map server. this server doesn't have gepard or gameguard

```
------------------------------- Character List --------------------------------
Slot 0: forsaken (Thief, Girl, level 11/1, Payon Town)
-------------------------------------------------------------------------------
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 42 25 02 00 (152114)
MAP Name: payon.gat
MAP IP: 54.39.21.155
MAP Port: 5121
-----------------------------
Closing connection to Character Server
Disconnecting (54.39.21.155:6121)...disconnected
Connecting to Map Server...
Connecting (54.39.21.155:5121)... connected
Timeout on Map Server, connecting to Account Server...
```

**Comment by alisonrag** [comment]
By default it is related to wrong servertype and recvpacket.
If you dont provide more info about client and servers.txt we cant help you.

**Comment by Fruitard** [comment]
> By default it is related to wrong servertype and recvpacket. If you dont provide more info about client and servers.txt we cant help you.

```
[Devi]
ip 54.39.21.155
port 6900
private 1
master_version 1
version 55
charBlockSize 146
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
addTableFolders kRO/RagexeRE_2020_04_01b;translated/kRO_english;kRO
```

this is the server info that i used

**Comment by JohtoNoob** [comment]
ip 54.39.21.155
port 6900
master_version 1
version 55
charBlockSize 147
serverType kRO_RagexeRE_2015_11_04a
addTableFolders kRO/RagexeRE_2015_11_04a;translated;translated/kRO_english;kRO
pinCode 1
private 1
pauseCharLogin 1
sendCryptKeys 0x4C17382A, 0x29961E4F, 0x7ED174C9
