### ISSUE TITLE
Packet Tokenizer: Unknown Switch: 4753

### ISSUE THREAD

**Issue by paparagnarok1** [OpenKore/openkore#3741]
* **Openkore version git**: openkore-master

* **Server**: kRO

* **Bug Report / Feature Request**:

* **Summary**: I am stuck at "Packet Tokenizer: Unknown Switch: 4753" and i believe this is an issue with revpacket, however i tried to follow https://openkore.com/wiki/Packet_Length_Extractor and its failed. Kindly assist me on this issue. attached below are the details of the server and error message.

https://osro.gg/
[Malaysia - Old School Ragnarok]
ip 143.244.40.195
port 6900
private1
master_version 0
version 46
serverType kRO_RagexeRE_2018_06_21a
serverEncoding Western
charBlockSize 155
charDeleteDateType 1
rankingSystemType 1
addTableFolders kRO/RagexeRE_2018_06_21a;translated;translated/kRO_english;kRO
![error](https://user-images.githubusercontent.com/81979557/229313423-c104d4dd-cf11-4c45-be03-c961c7e73d2b.PNG)

![erro1](https://user-images.githubusercontent.com/81979557/229313428-3f735adc-1d1a-4410-a3c8-9b9ce82dd5a2.PNG)

[recvpackets.txt](https://github.com/OpenKore/openkore/files/11130565/recvpackets.txt)

**Comment by alisonrag** [comment]
4753 means gepard and openkore cant run o server that use it as shield
