### ISSUE TITLE
Error on Unknown charBlockSize: at src/Network/Receive.pm

### ISSUE THREAD

**Issue by johnrego** [OpenKore/openkore#3745]
```
OpenKore version what-will-become-2.1
Network state = 3
Network handler = Network::DirectConnection
Revision: ctime:2023_04_16
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: adiciona pontos de habilidade automaticamente)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: adiciona pontos de atributo automaticamente)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Unknown charBlockSize:  at src/Network/Receive.pm line 771.

Stack trace:
Unknown charBlockSize:  at src/Network/Receive.pm line 771.
 at src/Interface/Wx.pm line 164
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x6445b34)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Interrompido nestá linha:
  		} else {
* 			die "Unknown charBlockSize: $_";
  		}


```

# http://ragnaplay.com.br
[Brazil - ragnaplay]
ip 177.54.147.188
port 6900
master_version 30
version 30
serverType iRO_Sakray
serverEncoding Western
addTableFolders iRO/Sakray;iRO
charBlockSize 108

![Captura de tela 2023-04-17 182934](https://user-images.githubusercontent.com/29126348/232615049-7651f29a-f017-4291-8ca3-75f3617cc19c.png)

I only have 1 character on this account

**Comment by VVTBONIN** [comment]
Opa jhon, tranquilo, infelizmente não sei como resolver o seu problema, mas queria te perguntar uma coisa e não sei como te chamar no privado, como eu consigo as informações de um servidor privado para usar o OpenKore?

**Comment by johnrego** [comment]
> Opa jhon, tranquilo, infelizmente não sei como resolver o seu problema, mas queria te perguntar uma coisa e não sei como te chamar no privado, como eu consigo as informações de um servidor privado para usar o OpenKore?

Snifando as conexões da sua maquina assim q abrir o cliente do jogo. Ao ligar o sniffer, ele vai exibir todas as conexões criadas por sua maquina. Se vc estiver logado, uma das conexões será a do jogo. Como sniffer pode usar o Wireshark.

**Comment by VVTBONIN** [comment]
> 

Então, não to sabendo fazer isso, pelo WPE ele não encontra meu rag, ai tento pelo wireshark mas o tutorial do openkore é do wireshark antigo, ai não tem as mesmas funções e o comando que pedem para usar para encontrar o Processo do Rag não existe mais, que seria o '' eth contains ''meunick'', o contains não existe mais, vc sabe se tem algum tutorial ou vc poderia me ajudar com isso por favor, se não for pedir muito.

teria como eu deixar meu contato de whatsapp para fazer isso mais rapidamente?  por conta da facul n consigo mais jogar direito e n to afim de ficar pra tras kkk

**Comment by alisonrag** [comment]
keep other infos and try the following:
```
serverType kRO_RagexeRE_2020_04_01b
serverEncoding Western
gameGuard 0
addTableFolders kRO/Ragexe_2020_04_01b;iRO/official;iRO
charBlockSize 155
pinCode 0
private 1
```

or
```
serverType kRO_RagexeRE_2018_04_18a
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2018_04_04b;translated/kRO_english
charBlockSize 155
pinCode 0
private 1
```

**Comment by alisonrag** [comment]
```
[Brazil - RagnaPLAY]
ip 177.54.147.188
port 6900
master_version 30
version 30
serverType kRO_RagexeRE_2018_04_18a
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2018_04_04b;translated/kRO_english
charBlockSize 155
pinCode 0
private 1
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
```
