### ISSUE TITLE
Help on a Private Server Historyreborn

### ISSUE THREAD

**Issue by VVTBONIN** [OpenKore/openkore#3746]
iam new on Ragnarok and i have no time to play, i see the OpenKore working on a private servers and i want to know how i can do a Bot work on: **historyreborn.net** , i want do a Bot to autowalk on a especifc map and autoskill to farm, if is possivel i need learn or any expert to help me do this simple bot, and if is possivel when my bag is full send a RODEX for my account and continue farming

**Comment by VVTBONIN** [comment]
i Need to know how i can get the info of server too, i try WPE Pro but the Ragnarok.exe is vanish

**Comment by JohtoNoob** [comment]
https://openkore.com/wiki/Connectivity_Guide

**Comment by VVTBONIN** [comment]
> https://openkore.com/wiki/Connectivity_Guide

i aleardy try use the WPE, but the historyreborn rag is vanish on WPE

**Comment by VVTBONIN** [comment]
i try with wireshark now, but the command on filter eth contains ''my nick'' dosent work. when i type contains the command dosent exist.

Somebody can record a short video and send the link to i see how i can do this? the Wireshark is different of the GUide on open kore

or send me a tutorial please

**Comment by LycorisRecoil-NishikigiChisato** [comment]
@VVTBONIN  Please use the keyword "wireshark technology" in google, you will find the information you want to know. Instead of directly asking questions that do not belong to "Openkore". 

https://www.comptia.org/content/articles/what-is-wireshark-and-how-to-use-it

**Comment by VVTBONIN** [comment]
> @VVTBONIN Please use the keyword "wireshark technology" in google, you will find the information you want to know. Instead of directly asking questions that do not belong to "Openkore".
> 
> https://www.comptia.org/content/articles/what-is-wireshark-and-how-to-use-it
> 
> Rome was not created in a day, I think what you need is "Learn how to find the knowledge you want?" Learn how to fish, catch fish, and not wait until the fisherman.

This belong to OpenKore... have a tutorial on OpenKore Wiki to how do this, but is the OLD Wireshark... i just ask one thing because i have no idea how to do, i aleardy see tutorials and still cant do this.

**Comment by LycorisRecoil-NishikigiChisato** [comment]
I don't think there will be any problems with the old and new tutorials. The important and key methods have been written out in the tutorial. Is your problem not using tools to find the information you need? Then search engines will be your best choice. It's our fault that the internet generation doesn't use search engines, not the people who write the tutorials. Sorry, I wrote something not related to "openkore" here.

**Comment by VVTBONIN** [comment]
> I don't think there will be any problems with the old and new tutorials. The important and key methods have been written out in the tutorial. Is your problem not using tools to find the information you need? Then search engines will be your best choice. It's our fault that the internet generation doesn't use search engines, not the people who write the tutorials. Sorry, I wrote something not related to "openkore" here.

my generation? i have 29 years old, i see the internet born my friend... i aleardy use the search engines to try find and i cant do this... your problem is, maybe u know how to do and dosent help, or u dont know and u awnser me wih a bad words to explain this.

**Comment by LycorisRecoil-NishikigiChisato** [comment]
@VVTBONIN 
https://openkore.com/wiki/Connectivity_Guide

Before 8th, you only need to install Wireshark and reboot, open Wireshark on a clean system, and select the option corresponding to your network card (there is an option for network fluctuations in the program), and then Wireshark will capture Record all network packets. Before that, you only need to prepare your private server window and wait for the login screen, then switch to Wireshark to start capturing, switch to the private server window to log in to the account, and you can get what you want information.

8.The above description is to obtain IP and port,
9.Follow TCP Stream. Wireshark selected specific function options.
10.data type displayed  "Hex Dump."
11.64 00 is the packet of the login account server address. The length of 0064 is 55. 
You can find version and master version in the packet content.

But as alisonrag said this server historyreborn has gepard, so unfortunately openkore will not work.

**Comment by VVTBONIN** [comment]
> In fact u just need to use any wireshark version to get infos from login packet and use peviewer to get the client version, but this server historyreborn has gepard, so unfortunately openkore will not work

Thanks

**Comment by VVTBONIN** [comment]
> @VVTBONIN https://openkore.com/wiki/Connectivity_Guide
> 
> Before 8th, you only need to install Wireshark and reboot, open Wireshark on a clean system, and select the option corresponding to your network card (there is an option for network fluctuations in the program), and then Wireshark will capture Record all network packets. Before that, you only need to prepare your private server window and wait for the login screen, then switch to Wireshark to start capturing, switch to the private server window to log in to the account, and you can get what you want information.
> 
> 8.The above description is to obtain IP and port, 9.Follow TCP Stream. Wireshark selected specific function options. 10.data type displayed "Hex Dump." 11.64 00 is the packet of the login account server address. The length of 0064 is 55. You can find version and master version in the packet content.
> 
> But as alisonrag said this server historyreborn has gepard, so unfortunately openkore will not work.

Oh, really thanks, i really dosent cant see this on the blog, i will try now
