### ISSUE TITLE
[request] Asia RO (aRO) - support 

### ISSUE THREAD

**Issue by Fruitard** [OpenKore/openkore#3748]
**Openkore version git**: Latest
**Server**: aRO 
**Bug Report / Feature Request:**
Successfully connected but timeout and disconnected from server
![Capture](https://user-images.githubusercontent.com/31286810/233936525-618ddd68-92fa-4a29-bbb9-ab598c9919ff.JPG)

**Comment by caru89** [comment]
same problems

**Comment by alisonrag** [comment]
https://www.gnjoy.asia/

**Comment by ya4ept** [comment]
The server is not botable, because CDC protection is used!
