### ISSUE TITLE
recvpackets.txt

### ISSUE THREAD

**Issue by pakpao52** [OpenKore/openkore#3751]
**Is there a giveaway? recvpackets.txt for this version.**

![235882766-16fd87b1-6e90-4e0b-8d86-29c39c076ad5](https://user-images.githubusercontent.com/132443816/235885089-eecec915-f3a7-4b8c-99e7-13b9b9a13e4a.png)

**Comment by pakpao52** [comment]
Verry Nice

**Comment by alisonrag** [comment]
this date was changed using nemo/warp 
you can try to use peek to get recvpacket, if not work, you can try to compare the functions in client using their launch date:
https://www.novaragnarok.com/wiki/List_of_Episodes

for example if alq has Gear Swap System so it should be at least late 2016 client

**Comment by alisonrag** [comment]
this is in pt br, but for example if you can use `ctrl + end` to make other players transparent the client is at least 2021
