### ISSUE TITLE
Unable to calculate a meeting position to target, dropping target" and dont attack the monsters.

### ISSUE THREAD

**Issue by jokinvipo** [OpenKore/openkore#3775]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  Openkore 2.1

* **Server**:  Private

* **Bug Report / Feature Request**:  Error Fix

* **Summary**: 
 My bot is showing this error "unable to calculate a meeting position to target, dropping target" and dont attack the monsters.

**Comment by LycorisRecoil-NishikigiChisato** [comment]
Look at #3676.
May be helpful for you.

**Comment by alisonrag** [comment]
https://openkore.com/wiki/attackRouteMaxPathDistance
