### ISSUE TITLE
packet parser : unknow switch 0A4D

### ISSUE THREAD

**Issue by BlazingBR** [OpenKore/openkore#3790]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by BlazingBR** [comment]
I chan't connect bot to server getting this error {packet parser :unknow switch 0A4D}

**Comment by LycorisRecoil-NishikigiChisato** [comment]
@BlazingBR 
version used ？
which server ？
Have you looked for other issues and pull requests ?

Have you seen Frequently Asked Questions？
https://github.com/OpenKore/openkore#faq-frequently-asked-questions

**Comment by BlazingBR** [comment]
ctime : ctime:2023_09_15 i'm trying to connect to IRO

**Comment by BlazingBR** [comment]
Issue is Subject ;
Been off RO for a good few years and OpenKore for the same.
I already downloaded the newest OpenKore 3 times off of GitHub.
Has there been an update recently?
I am not a pure noob, but most definitely not an elite when it comes to this stuff.
If its something to do with packets can I get the specifics?
Or did I return right after an update and just have to wait?
Thanks to everyone, I appreciate you.

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/issues/3770

**Comment by BlazingBR** [comment]
Thanks for the reply. I will try it out . Thank you

    On Saturday, December 14, 2024 at 09:35:01 PM CST, Alison ***@***.***> wrote:  
 
 


Closed #3790 as completed.
