### ISSUE TITLE
20220406 recvpackets and 0A4D packet

### ISSUE THREAD

**Issue by lyy289065406** [OpenKore/openkore#3792]
My server is rAthena, PACKETVER 20220406, set up locally.
The client is using 2022-04-06_Ragexe_1648707856.exe

When connecting with openkore, I select Localhost, but I receive the error "packet parser: unknown switch 0A4D". 
I checked 'tables/servers.txt' and found the serverType is incorrect:

```
[Localhost]
ip localhost
port 6900
private 1
master_version 1
version 20
serverType kRO_RagexeRE_2009_11_04a
serverEncoding Western
addTableFolders translated/kRO_english;kRO
```

I couldn't find kRO_RagexeRE_2022_04_06 in the 'tables/kRO' directory.
How should I go about creating a recvpackets.txt file on my own?"

**Comment by alisonrag** [comment]
0a4d is not implemented on openkore

**Comment by lyy289065406** [comment]
> ![IMG_4704](https://user-images.githubusercontent.com/25875385/269698878-d8868c52-74fc-4a4f-b0bd-b979c0517949.jpeg) 0A4D is server list? #3757 The same question keeps asking. Has the questioner not searched for the previous question?

Is this my original question? Has the responder see what my original question was?

**Comment by lyy289065406** [comment]
> 0a4d is not implemented on openkore


I wrote it wrong, not 0A4d, , it was this:
```
Packet Tokenizer: Unknown switch: 0AC4
```

**Comment by alisonrag** [comment]
0Ac4 is already implemented try one of the following server configuration:

```[localHost - rA/Herc 2020]
ip 127.0.0.1
port 6900
master_version 1
version 28
serverType kRO_RagexeRE_2020_04_01b
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders kRO/RagexeRE_2020_04_01b;iRO
charBlockSize 155
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1

[localHost - rA/Herc 2021]
ip 127.0.0.1
port 6900
master_version 1
version 28
serverType kRO_RagexeRE_2021_11_03
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders kRO/Ragexe_2021_11_03;iRO
charBlockSize 175
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1

[localHost - rA/Herc 2018]
ip 127.0.0.1
port 6900
master_version 1
version 28
serverType kRO_RagexeRE_2018_04_18a
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders kRO/RagexeRE_2018_04_04b;iRO
charBlockSize 155
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1
```

**Comment by lyy289065406** [comment]
> 0Ac4 is already implemented try one of the following server configuration:
> 
> ```
> [localHost - rA/Herc 2020]
> ip 127.0.0.1
> port 6900
> master_version 1
> version 28
> serverType kRO_RagexeRE_2020_04_01b
> serverEncoding Western
> gameGuard 0
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> addTableFolders kRO/RagexeRE_2020_04_01b;iRO
> charBlockSize 155
> pinCode 0
> charDeleteDateType 1
> rankingSystemType 1
> private 1
> 
> [localHost - rA/Herc 2021]
> ip 127.0.0.1
> port 6900
> master_version 1
> version 28
> serverType kRO_RagexeRE_2021_11_03
> serverEncoding Western
> gameGuard 0
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> addTableFolders kRO/Ragexe_2021_11_03;iRO
> charBlockSize 175
> pinCode 0
> charDeleteDateType 1
> rankingSystemType 1
> private 1
> 
> [localHost - rA/Herc 2018]
> ip 127.0.0.1
> port 6900
> master_version 1
> version 28
> serverType kRO_RagexeRE_2018_04_18a
> serverEncoding Western
> gameGuard 0
> storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
> addTableFolders kRO/RagexeRE_2018_04_04b;iRO
> charBlockSize 155
> pinCode 0
> charDeleteDateType 1
> rankingSystemType 1
> private 1
> ```

`[localHost - rA/Herc 2021]`  is work ! thx
