### ISSUE TITLE
useSelf_Item not working at all

### ISSUE THREAD

**Issue by betlogboi** [OpenKore/openkore#3795]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

Hi.

Maybe you have other setup on making the healing and speed potion working.

My config

useSelf_item Awakening Potion {
whenStatusInactive EFST_ATTHASTE_POTION2
inLockOnly 1
notWhileSitting 1
timeout 10
}

useSelf_item Green Herb {
whenStatusActive Poisoned
}

useSelf_item Red Potion,Orange Potion,White Potion {
hp < 80%
}

useSelf_item Blue Potion {
sp < 15%
}

useSelf_item Grape Juice {
sp < 75%
}

Not sure where i went wrong but none of this work. tried searching other ways tried on different settings etc but no avail.

receivepackets from 2021_11_03

TIA

**Comment by Bradzinho** [comment]
I have the same problem on the Lanverse server, it must be that receivepackets is out of date
