### ISSUE TITLE
[ai] openkore stuck some seconds after kill a monster (timeouts.txt)

### ISSUE THREAD

**Issue by kyloren23** [OpenKore/openkore#3797]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

heres video: https://www.youtube.com/watch?v=XDm8t8QEtJg

is there way to reduce or remove delay after killing monster? there is noticeable delay for like 2-3sec pause after monster died, even i already have this in my timeouts 

ai_attack_wait_afterKill 0.1 

i kinda can't catch up by others with autoplayer from ro maxion gravity (this is built in-game autoattack subscription from server since its expensive i cant buy one, i decided to use openkore instead) but they're superior and more faster reaction than openkore (example: they can kill 3 thara frogs vs i can only kill 1 thara frog because bot is pausing 2-3 sec every after killed) i feels like there is hardcoded delay in openkore is there way to remove the delay? can the attack logic be edited inside tables folder or src/XXX.pm files? i hope you guys help me to find it thank you

**Comment by iikob** [comment]
Can I have  bots you use?

**Comment by marcgaming** [comment]
do you have server and config txt file for landverse.maxion.gg openkore? Thanks

**Comment by iikob** [comment]
I can't find it. Please send it to us.


ในวันที่ ส. 30 ก.ย. 2023 เวลา 17:45 marcgaming ***@***.***>
เขียนว่า:

**Comment by marcgaming** [comment]
Any update on this issue? I'm having also this issue.

**Comment by marcgaming** [comment]
@alisonrag please help us

**Comment by pwr43nd37** [comment]
can you share your server.txt config?

**Comment by marcgaming** [comment]
@kyloren23 hi how do you use xkore1 cannot use it only xcore0?

**Comment by marcgaming** [comment]
@alisonrag thank you boss in Ragnarok Landverse Auto when kill immitiedly attack another but in our openkore updated it waits for 2-3 secs before attack like in the video(default settings)

**Comment by alisonrag** [comment]
check #3802 

https://www.youtube.com/watch?v=7wGb7ju28Vw

**Comment by HudsonFranco** [comment]
Can anyone send the updated Openkore link?

**Comment by rbizaare** [comment]
@kyloren23 can you still bot RO maxion?

**Comment by kyloren23** [comment]
my bot is from private community using custom .exe to bypass the sard gameguard. i think its not allowed to post advertisement here so sorry i cant help you guys.. 
or search xRays-cheat from facebook/youtube

**Comment by kyloren23** [comment]
> check #3802
> 
> https://www.youtube.com/watch?v=7wGb7ju28Vw

thank you for the hard work, the bot is FAST as autoplay now, it goes fast brrrrt brrrtt zoom zoom （＾ω＾）

**Comment by marcgaming** [comment]
What server are you using openkore?
