### ISSUE TITLE
can't reconstruct unkown packet - ragnarok landverse

### ISSUE THREAD

**Issue by rbizaare** [OpenKore/openkore#3799]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

Latest. I just git cloned now.
* **Server**: 

Ragnarok Landverse. Website: https://landverse.maxion.gg/Login
* **Bug Report / Feature Request**:

* **Summary**: can't reconstruct unkown packet: sync_received_characters at src/Network/PacketParser.pm line 180
 I can get pass to the user and password section but I'm having the error above after selecting the server.

**Comment by rbizaare** [comment]
full error.

Error message:
Can't reconstruct unknown packet: sync_received_characters at src/Network/PacketParser.pm line 180.

Stack trace:
Can't reconstruct unknown packet: sync_received_characters at src/Network/PacketParser.pm line 180.
 at src/Network/PacketParser.pm line 180
	Network::PacketParser::reconstruct('Network::Send::kRO::RagexeRE_0=HASH(0x78312b4)', 'HASH(0x7831bb4)') called at src/Network/Receive.pm line 921
	Network::Receive::sync_received_characters('Network::Receive::kRO::RagexeRE_0=HASH(0x728973c)', 'HASH(0x7835224)') called at src/Network/PacketParser.pm line 279
	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_0=HASH(0x728973c)', '\x{a0}\x{9}\x{1}\x{0}\x{0}\x{0}', 'Network::Receive::kRO::RagexeRE_0=HASH(0x728973c)') called at src/Network/Receive.pm line 603
	Network::Receive::parse('Network::Receive::kRO::RagexeRE_0=HASH(0x728973c)', '\x{a0}\x{9}\x{1}\x{0}\x{0}\x{0}', 'Network::Receive::kRO::RagexeRE_0=HASH(0x728973c)') called at src/Network/PacketParser.pm line 413
	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_0=HASH(0x728973c)', 'Network::MessageTokenizer=HASH(0x3a9c2b4)', 'Network::Receive::kRO::RagexeRE_0=HASH(0x728973c)') called at src/functions.pl line 834
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x44d3194)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	unless ($self->{packet_list}{$switch}) {
* 		die "Can't reconstruct unknown packet: $switch";
  	}

**Comment by rbizaare** [comment]
I resolved it myself. Fixed my wrong server.txt. Closing this one

**Comment by pwr43nd37** [comment]
can you share your server.txt?

**Comment by vhinz2145** [comment]
> I resolved it myself. Fixed my wrong server.txt. Closing this one

hi sir, can you help me to setup the Xkore1, i'm having problem in connecting always saying that waiting for xkore. i'm a newbie. please help. :(

**Comment by vhinz2145** [comment]
> > I resolved it myself. Fixed my wrong server.txt. Closing this one
> 
> hi sir, can you help me to setup the Xkore1, i'm having problem in connecting always saying that waiting for xkore. i'm a newbie. please help. :(

This is my 
[config.txt](https://github.com/OpenKore/openkore/files/12908772/config.txt)
and
[servers.txt](https://github.com/OpenKore/openkore/files/12908774/servers.txt)
