### ISSUE TITLE
[request] How to use or run bpe-master

### ISSUE THREAD

**Issue by NegrongPNKMLupeT** [OpenKore/openkore#3805]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

any guide how to use or run bpe-master using wsl and python ?

**Comment by sctnightcore** [comment]
https://gitlab.com/4144/bpe/-/blob/master/README.md?ref_type=heads
