### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by LatnSimon** [OpenKore/openkore#3808]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: twRo

* **Bug Report / Feature Request**:

* **Summary**:

正在載入選擇的 plugins...
正在載入 plugin plugins/breakTime/breakTime.pl...
正在載入 plugin plugins/eventMacro/eventMacro.pl...
正在載入 plugin plugins/item_weight_recorder/item_weight_recorder.pl...
正在載入 plugin plugins/macro/macro.pl...
正在載入 plugin plugins/map/map.pl...
正在載入 plugin plugins/profiles/profiles.pl...
正在載入 plugin plugins/raiseSkill/raiseSkill.pl...
正在載入 plugin plugins/raiseStat/raiseStat.pl...
正在載入 plugin plugins/reconnect/reconnect.pl...
正在載入 plugin plugins/xConf/xConf.pl...

No profiles found, using standard control folder
正在載入 tables\item_weights.txt...
正在載入 control\config.txt...
正在載入 control\consolecolors.txt...
正在載入 control\mon_control.txt...
正在載入 control\items_control.txt...
正在載入 control\buyer_shop.txt...
正在載入 control\shop.txt...
正在載入 control\overallAuth.txt...
正在載入 control\pickupitems.txt...
正在載入 control\responses.txt...
正在載入 control\timeouts.txt...
正在載入 control\chat_resp.txt...
正在載入 control\avoid.txt...
正在載入 control\priority.txt...
正在載入 control\routeweights.txt...
正在載入 control\arrowcraft.txt...
正在載入 tables\servers.txt...
正在載入 tables\twRO\recvpackets.txt...
正在載入 tables\cities.txt...
正在載入 tables\twRO\directions.txt...
正在載入 tables\twRO\elements.txt...
正在載入 tables\twRO\emotions.txt...
正在載入 tables\twRO\equiptypes.txt...
正在載入 tables\twRO\haircolors.txt...
正在載入 tables\headgears.txt...
正在載入 tables\twRO\items.txt...
正在載入 tables\twRO\itemsdescriptions.txt...
正在載入 tables\twRO\itemslots.txt...
正在載入 tables\twRO\itemslotcounttable.txt...
正在載入 tables\twRO\itemtypes.txt...
正在載入 tables\twRO\resnametable.txt...
正在載入 tables\twRO\maps.txt...
正在載入 tables\twRO\monsters.txt...
正在載入 tables\npcs.txt...
正在載入 tables\packetdescriptions.txt...
正在載入 tables\portals.txt...
正在載入 tables\portalsLOS.txt...
正在載入 tables\twRO\sex.txt...
正在載入 tables\SKILL_id_handle.txt...
正在載入 tables\twRO\skillnametable.txt...
正在載入 tables\twRO\spells.txt...
正在載入 tables\twRO\skillsdescriptions.txt...
正在載入 tables\twRO\skillssp.txt...
正在載入 tables\twRO\STATUS_id_handle.txt...
正在載入 tables\STATE_id_handle.txt...
正在載入 tables\LOOK_id_handle.txt...
正在載入 tables\AILMENT_id_handle.txt...
正在載入 tables\MAPTYPE_id_handle.txt...
正在載入 tables\MAPPROPERTY_TYPE_id_handle.txt...
正在載入 tables\MAPPROPERTY_INFO_id_handle.txt...
正在載入 tables\twRO\statusnametable.txt...
正在載入 tables\skillsarea.txt...
正在載入 tables\skillsencore.txt...
正在載入 tables\twRO\quests.txt...
正在載入 tables\effects.txt...
正在載入 tables\twRO\msgstringtable.txt...
正在載入 tables\twRO\hateffect_id_handle.txt...
正在載入 tables\twRO\hateffect_name.txt...
正在載入 tables\item_stack_limit.txt...
正在載入 tables\ITEMOPTION_id_handle.txt...
正在載入 tables\twRO\item_options.txt...
正在載入 tables\twRO\title_name.txt...
正在載入 tables\twRO\attendance_rewards.txt...
正在載入 tables\twRO\achievement_list.txt...
[eventMacro] No control/eventMacros.txt file was found. Plugin disabled.
[eventMacro] Plugin unloading
Plugin eventMacro 已卸載.

正在產生 session Admin Password...
檢查有無新的傳點...沒有發現

正在連線至帳號伺服器...
連線中 (twro-acc.gnjoy.com.tw:6900)... 已連線
---------- Account Info ----------
Account ID: 24864055   37 65 7B 01
Sex:        男孩
Session ID: 8809       69 22 00 00
SessionID2: 824193075  33 30 20 31

----------------------------------
------------------------------ Servers -------------------------------
#   Name                  Users  IP              Port   SID    State
0   羅札納                   0      twro-char4.gnjo 10029  0      
1   巴基利                   0      twro-char1.gnjo 10029  0      
2   查爾斯                   0      twro-char2.gnjo 10029  0      
3   波利                    0      twro-char3.gnjo 10029  0      
----------------------------------------------------------------------
對帳號伺服器關閉連線
斷線中 (219.84.200.54:6900)...已斷線
正在連線至角色伺服器...
Selected server: 波利
連線中 (twro-char3.gnjoy.com.tw:10029)... 已連線
從角色伺服器接受角色
Waiting for PIN code request
Server requested PIN password in order to select your character.
PIN code is correct.
------------------------------- Character List --------------------------------
Slot 0: LatnSimon (Crusader, 男孩, level 89/50, prontera)
-------------------------------------------------------------------------------
從角色伺服器接受角色ID與地圖IP
----------遊戲資訊-----------
角色 ID: 5B 0E C9 42 (1120472667)
地圖名稱: prontera.gat
地圖 IP: twro-zone-3c.gnjoy.com.tw
地圖 Port: 10010
-----------------------------
對角色伺服器關閉連線
斷線中 (219.84.200.98:10029)...已斷線
正在連線至地圖伺服器...
連線中 (twro-zone-3c.gnjoy.com.tw:10010)... 已連線
Packet Tokenizer: Unknown switch: 0007
Packet Tokenizer: Unknown switch: 0009
Packet Tokenizer: Unknown switch: 0009
Packet Tokenizer: Unknown switch: 0012
Packet Tokenizer: Unknown switch: 0058
Packet Tokenizer: Unknown switch: 000B
Packet Parser: Unknown switch: 0112
Packet Tokenizer: Unknown switch: 000B
Packet Tokenizer: Unknown switch: 0008
Packet Tokenizer: Unknown switch: 000B
Packet Tokenizer: Unknown switch: 000B
Packet Parser: Unknown switch: 0365
Packet Tokenizer: Unknown switch: 0000
Packet Tokenizer: Unknown switch: 0591
Packet Tokenizer: Unknown switch: 0014
地圖伺服器逾時, 連線至帳號伺服器中...
斷線中 (219.84.200.102:10010)...已斷線

**Comment by LycorisRecoil-NishikigiChisato** [comment]
see it.
[CheatDefenderPackageRole.txt](https://github.com/OpenKore/openkore/files/12854225/CheatDefenderPackageRole.txt)
