### ISSUE TITLE
Having trouble using OpenKore on Landverse

### ISSUE THREAD

**Issue by nashzin** [OpenKore/openkore#3810]
Im trying to loggin in the OpenKore - Landverse server but im getting this message :
![273739952-795b9aca-f84f-4936-bf3b-1dfdb581d3c5](https://github.com/OpenKore/openkore/assets/147570553/4a3d4023-215d-4cbf-991b-cab99e40a8d2)

**Comment by Tlcardoso** [comment]
> Im trying to loggin in the OpenKore - Landverse server but im getting this message : ![273739952-795b9aca-f84f-4936-bf3b-1dfdb581d3c5](https://user-images.githubusercontent.com/147570553/274160262-4a3d4023-215d-4cbf-991b-cab99e40a8d2.png)

this message happen when you are reject from server

**Comment by alisonrag** [comment]
also this should mean ur ip is blacklisted

**Comment by nashzin** [comment]
> > Im trying to loggin in the OpenKore - Landverse server but im getting this message : ![273739952-795b9aca-f84f-4936-bf3b-1dfdb581d3c5](https://user-images.githubusercontent.com/147570553/274160262-4a3d4023-215d-4cbf-991b-cab99e40a8d2.png)
> 
> this message happen when you are reject from server.
> 
> they have a limit for players logged in the server



> > Im trying to loggin in the OpenKore - Landverse server but im getting this message : ![273739952-795b9aca-f84f-4936-bf3b-1dfdb581d3c5](https://user-images.githubusercontent.com/147570553/274160262-4a3d4023-215d-4cbf-991b-cab99e40a8d2.png)
> 
> this message happen when you are reject from server.
> 
> they have a limit for players logged in the server

Exactly, i just kept trying login and it worked, thx alot guys

**Comment by nashzin** [comment]
i just got send to the jail, i accepted a PT to help a friend to level and just after i got send there, i was botting like 12h already withou a problem, someone had the same problem?

**Comment by Tlcardoso** [comment]
> i just got send to the jail, i accepted a PT to help a friend to level and just after i was send there, i was botting like 12h already withou a problem, someone had the same problem?

which map were you on?

**Comment by nashzin** [comment]
> > i just got send to the jail, i accepted a PT to help a friend to level and just after i was send there, i was botting like 12h already withou a problem, someone had the same problem?
> 
> which map were you on?

pay_fild 09 , i put the autoparty 2 to accept all calls and when i accepted i got TPed to the prision, maybe its because of that... and i found some sacers/priest there too, so im creating another char to test it.

**Comment by nashzin** [comment]
Just updating, i created another char on the same acc that i got catch, worked for hours but after the update on the SARD i got catch again, but i had another one running and that didnt got caught, i dont really know the logic behind it but botting isnt safe
