### ISSUE TITLE
Want to know this server.

### ISSUE THREAD

**Issue by Oniark** [OpenKore/openkore#3816]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  I'm using the last update.

* **Server**:  Payon Stories

* **Bug Report / Feature Request**: just want to know if is possible to use Openkore on this serve.

* **Summary**: I'm about to buy from a guy that sent me some proof that he is using Openkore on this server, so I want to make sure that I will not get scam. My knowledge with Openkore is very basic, only what the site tutorials shows. I try to setup by myself but all I get using xkore3 is some messages ”ou off memory", my computer is Good enough so I guess is some protection by the server.

Thank you.

**Comment by Kotak666** [comment]
> ## ------------------ Openkore Issues Template ------------------
> 
>     * **Openkore version git**:  I'm using the last update.
> 
> 
>     * **Server**:  Payon Stories
> 
> 
>     * **Bug Report / Feature Request**: just want to know if is possible to use Openkore on this serve.
> 
> 
>     * **Summary**: I'm about to buy from a guy that sent me some proof that he is using Openkore on this server, so I want to make sure that I will not get scam. My knowledge with Openkore is very basic, only what the site tutorials shows. I try to setup by myself but all I get using xkore3 is some messages ”ou off memory", my computer is Good enough so I guess is some protection by the server.
> 
> 
> Thank you.

bought it? is it working?

**Comment by Oniark** [comment]
I didn't, the guy want me to pay in a strange way.
