### ISSUE TITLE
ROlandverse Unknown 5448 Xkore 1

### ISSUE THREAD

**Issue by xsosid1993** [OpenKore/openkore#3817]
Guys the servers.txt and correct recvpackets was posted if u have any issue related to openkore just open a new one. if is related to config go to forum and read the wiki, i'm closing this to mainteners only

_Originally posted by @alisonrag in https://github.com/OpenKore/openkore/issues/3791#issuecomment-1755810347_
  
  help me pls   
![image](https://user-images.githubusercontent.com/148610090/277098804-4cadf80e-5ef1-43a9-af6e-078428b6f326.png)

**Comment by xsosid1993** [comment]
New Server Freya
Version : 55
Master_version 5

![image](https://github.com/OpenKore/openkore/assets/148610090/719a4243-06de-4849-8f9a-95603c41e500)

**Comment by Kotak666** [comment]
![error openkore](https://github.com/OpenKore/openkore/assets/148692983/f1d9c898-3655-48e6-8311-361a1341e414)

Can help connecting to freya? always got this error. I copied recv and server info from 3791 but still not working.

**Comment by xsosid1993** [comment]
> ![error openkore](https://user-images.githubusercontent.com/148692983/277165453-f1d9c898-3655-48e6-8311-361a1341e414.jpg)
> 
> Can help connecting to freya? always got this error. I copied recv and server info from 3791 but still not working.

![image](https://github.com/OpenKore/openkore/assets/148610090/4bd0969d-496c-4ef9-91d5-48a4879403b3)

**Comment by alisonrag** [comment]
use #3791

**Comment by Tutoytheblack** [comment]
> > ![error openkore](https://user-images.githubusercontent.com/148692983/277165453-f1d9c898-3655-48e6-8311-361a1341e414.jpg)
> > Can help connecting to freya? always got this error. I copied recv and server info from 3791 but still not working.
> 
> ![image](https://user-images.githubusercontent.com/148610090/277166534-4bd0969d-496c-4ef9-91d5-48a4879403b3.png)

Did you resolved this?

**Comment by makuvexx** [comment]
Having the same problem. I used the recv and server

**Comment by mrclo3** [comment]
Hey guys, can someone help me, I'm having the same problem

"Connect failed, something is wrong with the login settings"
