### ISSUE TITLE
In ragnarok  landverse I can not connect or login  error 

### ISSUE THREAD

**Issue by doneline001** [OpenKore/openkore#3827]
Connecting to Account Server...
Connecting (103.169.66.142:51000)... connected
Timeout on Account Server, reconnecting. Wait 44 seconds...

Please Help and explain to me.

![image](https://github.com/OpenKore/openkore/assets/150236868/2db510d2-8d7e-4cd6-809e-aee3aa5b0eff)

**Comment by ricpumanes** [comment]
same issue here

**Comment by doneline001** [comment]
> same issue here

Waiting for someone to explain  U-U

**Comment by doneline001** [comment]
[sagunkho](https://github.com/sagunkho)
Can I still bot the Landverse server now?

**Comment by 4shinr** [comment]
I have a different issue, trying to solve too:

Connecting to Account Server...
Connecting (103.169.66.141:51000)... connected
Disconnecting (103.169.66.141:51000)...disconnected
Connect failed, something is wrong with the login settings:
version: 55
master_version: 1
serverType: kRO_RagexeRE_2021_11_03
Relogging in 30 seconds...

This is what I setup in server.txt:
# https://landverse.maxion.gg/
[R Landverse]
ip 103.169.66.141
port 51000
master_version 1
version 55
serverType kRO_RagexeRE_2021_11_03
serverEncoding Western
addTableFolders kRO/Ragexe_2021_11_03;iRO
charBlockSize 175
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1
pinCode 0

**Comment by 4shinr** [comment]
> Connecting to Account Server... Connecting (103.169.66.142:51000)... connected Timeout on Account Server, reconnecting. Wait 44 seconds...
> 
> Please Help and explain to me.
> 
> ![image](https://user-images.githubusercontent.com/150236868/281359672-2db510d2-8d7e-4cd6-809e-aee3aa5b0eff.png)

try the same ip I'm using so you can check if message changes. If that works please post your server.txt config

**Comment by ricpumanes** [comment]
have any of you tried the solutions mentioned here #3791 ?

**Comment by 4shinr** [comment]
> have any of you tried the solutions mentioned here #3791 ?

Yes, I've tried the configs on this topic, but it's out of date... I've got the new ip yesterday but something else may be changed from that time to now, does anyone has update info working?

**Comment by 4shinr** [comment]
@alisonrag , could you please give some hand here?

**Comment by unknowpk** [comment]
![image](https://github.com/OpenKore/openkore/assets/147792012/e464d1a0-869b-478c-af6b-d7d4ed03d459)
😎😎

**Comment by unknowpk** [comment]
‼️ It work!!! 😎

![ezgif com-crop](https://github.com/OpenKore/openkore/assets/147792012/cf799826-64bc-4a3f-85e2-a6c1741d58a0)

**Comment by ludwigpogi** [comment]
> ‼️ It work!!! 😎
> 
> ![ezgif com-crop](https://user-images.githubusercontent.com/147792012/282220226-cf799826-64bc-4a3f-85e2-a6c1741d58a0.gif) [ ![ezgif com-crop](https://user-images.githubusercontent.com/147792012/282220226-cf799826-64bc-4a3f-85e2-a6c1741d58a0.gif) ](https://user-images.githubusercontent.com/147792012/282220226-cf799826-64bc-4a3f-85e2-a6c1741d58a0.gif) [ ](https://user-images.githubusercontent.com/147792012/282220226-cf799826-64bc-4a3f-85e2-a6c1741d58a0.gif)

how?
can u send the server settings?

**Comment by ricpumanes** [comment]
@unknowpk would you mind sharing sharing the steps to fix this?

**Comment by ludwigpogi** [comment]
Stuck Here!
![image](https://github.com/OpenKore/openkore/assets/150534076/b4c325ee-5fcf-4ce8-9f7a-605e85617c39)

**Comment by ludwigpogi** [comment]
![image](https://github.com/OpenKore/openkore/assets/150534076/834f9334-812c-41da-bb61-5fcb7228820a)

**Comment by unknowpk** [comment]
Some packet is changed
Try to log with other program with manual play.
And full debug mode with openkore.

You can see what is difference.

**Comment by 4shinr** [comment]
> Some packet is changed Try to log with other program with manual play. And full debug mode with openkore.
> 
> You can see what is difference.

Could you please paste here your server.txt details for landverse server? I don't think people know how reproduce the steps you mentioned

**Comment by unknowpk** [comment]
[R Landverse]
ip 103.169.66.141
port 51000
master_version 1
version 55
serverType kRO_RagexeRE_2021_11_03
serverEncoding Western
addTableFolders kRO/Ragexe_2021_11_03;iRO
charBlockSize 175
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1
pinCode 0

**Comment by 4shinr** [comment]
> [R Landverse] ip 103.169.66.141 port 51000 master_version 1 version 55 serverType kRO_RagexeRE_2021_11_03 serverEncoding Western addTableFolders kRO/Ragexe_2021_11_03;iRO charBlockSize 175 storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9 charDeleteDateType 1 blockingPlayerCancel 1 rankingSystemType 1 itemListType 1 pinCode 0

I've used your config but got the same error as before through wxstart.exe :

Connecting to Account Server...
Connecting (103.169.66.141:51000)... connected
Disconnecting (103.169.66.141:51000)...disconnected
Connect failed, something is wrong with the login settings:
version: 55
master_version: 1
serverType: kRO_RagexeRE_2021_11_03
Relogging in 30 seconds...

**Comment by Thiaguinh0xX** [comment]
> [R Landverse] ip 103.169.66.141 port 51000 master_version 1 version 55 serverType kRO_RagexeRE_2021_11_03 serverEncoding Western addTableFolders kRO/Ragexe_2021_11_03;iRO charBlockSize 175 storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9 charDeleteDateType 1 blockingPlayerCancel 1 rankingSystemType 1 itemListType 1 pinCode 0

Could you post your recvpacket?

**Comment by unknowpk** [comment]
![image](https://github.com/OpenKore/openkore/assets/147792012/2acb430a-3aaa-431c-85f7-8966a42e2d50)

**Comment by 4shinr** [comment]
> ![image](https://user-images.githubusercontent.com/147792012/282275175-2acb430a-3aaa-431c-85f7-8966a42e2d50.png)

He means a file recvpacket.txt. It shouldn't be the issue on login phase. Can you erase your login/pass from the bot and attach here a zip of your entire openkore folder? That'd be easier because we're not progressing on the root cause

**Comment by unknowpk** [comment]
please  use x1 
x0 Fix many points

**Comment by mazeltov13** [comment]
> ![image](https://user-images.githubusercontent.com/150534076/282250122-834f9334-812c-41da-bb61-5fcb7228820a.png)

please help, also stuck on this. many thanks!

**Comment by doneline001** [comment]
> try the same ip I'm using so you can check if message changes, 103.169.66.141. If that works please post your server.txt config

![image](https://github.com/OpenKore/openkore/assets/150236868/aa4f0ba4-0963-4f2e-a36a-f31b41e3bf46)
I Try your IP connected But system will show same error

**Comment by alisonrag** [comment]
https://discord.gg/B6H23bVF
look for topic landverse

**Comment by doneline001** [comment]
> landverse

![image](https://github.com/OpenKore/openkore/assets/150236868/d0781f58-eb28-4e39-aff0-df47b8806cad)

Is this Discord? No Landverse topics found.

**Comment by doneline001** [comment]
> please use x1 x0 Fix many points i don't share any file.

May I please have a way to contact you?

**Comment by beautifulelona** [comment]
Can I have a new discord link for landverse? Thanks

**Comment by RugvedATA** [comment]
Do we have any latest UPDATE here I am still facing same issue 
Connecting (103.169.66.141:51000)... connected
Disconnecting (103.169.66.141:51000)...disconnected
Connect failed, something is wrong with the login settings:
version: 55
master_version: 1
serverType: kRO_RagexeRE_2021_11_03
Relogging in 30 seconds...

**Comment by WeirdGuismo** [comment]
Hi,

Can anybody to connect Openkore in Ragnarok Landverse and play automated?

And which is the updated Discord link?

Sorry for my bad english...

**Comment by ricardoj1** [comment]
> https://discord.gg/B6H23bVF look for topic landverse

please post new link

**Comment by WeirdGuismo** [comment]
> > https://discord.gg/B6H23bVF look for topic landverse
> 
> please post new link

Please, could you post a valid link again? This expired.

**Comment by danialrosli** [comment]
> https://discord.gg/B6H23bVF look for topic landverse

Hi could you send a new invite link pls.

**Comment by danialrosli** [comment]
> please use x1 x0 Fix many points i don't share any file.

How to donate you mr@unknowpk .

**Comment by alisonrag** [comment]
https://discord.gg/TEE93T8Hvm

**Comment by sjhonanthan** [comment]
@alisonrag Pode me ajudar a configurar o openkore?, teve uma atualização no jogo onde meu personagem foi deletado :( não tinha muita coisa, mas estou jogando na mão, então isso pelo menos me ajudaria a iniciar de forma confortavel, eu ficaria bastante agradecido
