### ISSUE TITLE
[Need help] Still stuck on RO Landverse

### ISSUE THREAD

**Issue by itzchoutime** [OpenKore/openkore#3829]
According to #3791 i did the same thing in there but it's not working

got this messages
> Connecting to Account Server...
> Connecting (103.169.66.142:51000)... connected
> Timeout on Account Server, reconnecting. Wait 41 seconds...

Any solution ?

**Comment by alisonrag** [comment]
use the same issue dont spam the same topi here

**Comment by itzchoutime** [comment]
> use the same issue dont spam the same topic here

Which same issue you mean i did already it’s not working
