### ISSUE TITLE
OpenKore Server config not working sending same error Tried everything mentioned.

### ISSUE THREAD

**Issue by RugvedATA** [OpenKore/openkore#3833]
Connecting (103.169.66.141:51000)... connected
Disconnecting (103.169.66.141:51000)...disconnected
Connect failed, something is wrong with the login settings:
version: 55
master_version: 1
serverType: kRO_RagexeRE_2021_11_03
Relogging in 30 seconds...

This Issume please help me out fed up of using brain now.

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by tojoe88791** [comment]
<img width="554" alt="123" src="https://github.com/OpenKore/openkore/assets/153115775/5c4271b2-3483-41ba-8708-37e223caaaeb">

**Comment by cliffordx3** [comment]
i think this is ROL?

**Comment by cliffordx3** [comment]
I think no one wanted to help you.

**Comment by RugvedATA** [comment]
I gues thats true No one is helping me here any idea guys ??

@alisonrag please share discord link for landverse

**Comment by alisonrag** [comment]
https://discord.gg/zpemnM7e

**Comment by danialrosli** [comment]
give new link for discord please. @alisonrag

**Comment by alisonrag** [comment]
https://discord.gg/Q5xGp3QNa3

**Comment by alisonrag** [comment]
#3791

**Comment by alisonrag** [comment]
https://discord.gg/TEE93T8Hvm
