### ISSUE TITLE
Landverse help! - password problem

### ISSUE THREAD

**Issue by nullkalahar** [OpenKore/openkore#3834]
Using the following serevr information:

```
# https://landverse.maxion.gg/
[Landverse]
ip 103.169.66.141
port 51000
master_version 1
version 15
serverType twRO
serverEncoding Western
addTableFolders twRO
charBlockSize 175
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1
pinCode 1
```

![image](https://github.com/OpenKore/openkore/assets/37444831/578acad1-e6a9-401a-a3b6-00212ac20196)

I keep getting wrong password error.
I'm sure the password is written correctly, but I still get this error.

I already read the other topic:
https://github.com/OpenKore/openkore/issues/3791

But nothing there could help me.
Can anyone help?

**Comment by nullkalahar** [comment]
@alisonrag Tu poderias me ajudar nisso ? 
Se possível, me manda teu discord :)

**Comment by RugvedATA** [comment]
What is Discord Link for same ?

**Comment by whatasi** [comment]
@nullkalahar 
![image](https://github.com/OpenKore/openkore/assets/140739856/197fa027-e540-42ca-9100-32b20e1ca61c)

**Comment by whatasi** [comment]
@nullkalahar same

**Comment by alisonrag** [comment]
https://discord.gg/zpemnM7e

**Comment by ricardoj1** [comment]
@nullkalahar Did you manage to solve it? I have the same error

**Comment by nullkalahar** [comment]
> @nullkalahar Did you manage to solve it? I have the same error

Join the discord that was made available there

**Comment by ricardoj1** [comment]
> > @nullkalahar Did you manage to solve it? I have the same error
> 
> Join the discord that was made available there

Convite invalido

**Comment by ricardoj1** [comment]
@alisonrag do you can sed new link of discord?

**Comment by katsuragi2012** [comment]
> @alisonrag do you can sed new link of discord?

Also waiting for an updated invite link to discord

**Comment by danialrosli** [comment]
Waiting a new discord link

**Comment by alisonrag** [comment]
#3791 
https://discord.gg/Q5xGp3QNa3

**Comment by alisonrag** [comment]
https://discord.gg/TEE93T8Hvm

**Comment by ricardoj1** [comment]
> https://discord.gg/TEE93T8Hvm

thanks man.
