### ISSUE TITLE
Landverse help! - password problem

### ISSUE THREAD

**Issue by quickbasic1111** [OpenKore/openkore#3835]
landverse.maxion.gg
Solution Until SARD Turn On:

# https://landverse.maxion.gg/
[Landverse]
ip 103.169.66.142
port 51000
master_version 5
version 55
serverType kRO_RagexeRE_2021_11_03
serverEncoding Western
addTableFolders kRO/Ragexe_2021_11_03;iRO
charBlockSize 175
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
itemListType 1
pinCode 0

**Comment by alisonrag** [comment]
#3791 
https://discord.gg/Q5xGp3QNa3

**Comment by SweetPeem** [comment]
> #3791 https://discord.gg/Q5xGp3QNa3

Sir could you please give me the fresh discord link ? thank you
