### ISSUE TITLE
reactOnNPC Antibot ( A + B + C )

### ISSUE THREAD

**Issue by dt1536** [OpenKore/openkore#3839]
> [2023.12.15 19:50:54.25] Unknown #110024469: [Kafra]
> [2023.12.15 19:50:54.25] [reactOnNPC] NPC message saved (0): "[^ff0000Kafra^000000]".
> [2023.12.15 19:50:54.26] Unknown #110024469: Solve the following problem:
> [2023.12.15 19:50:54.26] [reactOnNPC] NPC message saved (1): "Solve the following problem:".
> [2023.12.15 19:50:54.26] Unknown #110024469:  
> [2023.12.15 19:50:54.27] [reactOnNPC] NPC message saved (2): " ".
> [2023.12.15 19:50:54.27] Unknown #110024469: > If: B=1 A=1 ...
> [2023.12.15 19:50:54.27] [reactOnNPC] NPC message saved (3): "> If: ^0000ffB^000000=^ff00001 ^0000ffA^000000=^ff00001 ...".
> [2023.12.15 19:50:54.28] Unknown #110024469: How many is A + B ?
> [2023.12.15 19:50:54.28] [reactOnNPC] NPC message saved (4): "How many is ^0000ffA ^000000+ ^0000ffB ^000000?^000000".
> [2023.12.15 19:50:54.29] Unknown #110024469:  
> [2023.12.15 19:50:54.29] [reactOnNPC] NPC message saved (5): " ".
> [2023.12.15 19:50:54.29] Unknown #110024469: * Attempt 1 of 5 *
> [2023.12.15 19:50:54.29] [reactOnNPC] NPC message saved (6): "* Attempt 1 of 5 *".
> [2023.12.15 19:50:54.30] [reactOnNPC] onNPCAction type is: continue.
> [2023.12.15 19:50:54.30] [reactOnNPC] Conditions for reactOnNPC_0 (npc:continue, rect:text) 'type' not met.
> [2023.12.15 19:50:54.31] [reactOnNPC] Conditions for reactOnNPC_1 (npc:continue, rect:text) 'type' not met.
> [2023.12.15 19:50:54.31] : Type 'talk cont' to continue talking
> [2023.12.15 19:50:55.10] Kafra: You have 89 second(s) to respond.
> [2023.12.15 19:50:55.24] [reactOnNPC] onNPCAction type is: text.
> [2023.12.15 19:50:55.25] [reactOnNPC] Conditions for reactOnNPC_0 (npc:text , rect:text) is met.
> [2023.12.15 19:50:55.25] [reactOnNPC] Matching [msg (0)] "[Kafra]" to "/> If: C=(\d+) B=(\d+) A=(\d+) .../" ... doesn't match.
> [2023.12.15 19:50:55.25] [reactOnNPC] One or more lines doesn't match for "reactOnNPC_0" (0).
> [2023.12.15 19:50:55.26] [reactOnNPC] Conditions for reactOnNPC_1 (npc:text , rect:text) is met.
> [2023.12.15 19:50:55.26] [reactOnNPC] Matching [msg (0)] "[^ff0000Kafra^000000]" to "/[Kafra]/" ... regexp ok.
> [2023.12.15 19:50:55.26] [reactOnNPC] Matching [msg (1)] "Solve the following problem:" to "/Solve the following problem:/" ... regexp ok.
> [2023.12.15 19:50:55.27] [reactOnNPC] Matching [msg (2)] " " to "//" ... doesn't match.
> [2023.12.15 19:50:55.27] [reactOnNPC] One or more lines doesn't match for "reactOnNPC_1" (2).

> [2023.12.15 11:16:48.24] Unknown #110024469: [Kafra]
> [2023.12.15 11:16:48.25] Unknown #110024469: Solve the following problem:
> [2023.12.15 11:16:48.25] Unknown #110024469:  
> [2023.12.15 11:16:48.25] Unknown #110024469: > If: C=2 B=1 A=2 ...
> [2023.12.15 11:16:48.26] Unknown #110024469: How many is A + B - C ?
> [2023.12.15 11:16:48.26] Unknown #110024469:  
> [2023.12.15 11:16:48.26] Unknown #110024469: * Attempt 1 of 5 *
> [2023.12.15 11:16:48.27] : Type 'talk cont' to continue talking
> [2023.12.15 11:16:49.79] Kafra: You have 89 second(s) to respond.
> [2023.12.15 11:16:49.22] itself: Type 'talk text' (Respond to NPC)
> [2023.12.15 11:16:50.89] Kafra: You have 88 second(s) to respond.

> reactOnNPC_debug 0
> reactOnNPC c talk text @eval(#3~1 #4~1 #3~2) {
>     type text
>     useColors 1
>     delay 2
>     msg_0 /[Kafra]/
>     msg_1 /Solve the following problem:/
>     msg_2 //
>     msg_3 /> If: B=(\d+) A=(\d+) .../
>     msg_4 /How many is A (.) B ?/
> msg_5 / * Attempt . of . */
> }

Hi, I have been trying to resolve this antibot issue by using the antibot [[bypass Antibot] - How many is A + B](https://forums.openkore.com/viewtopic.php?f=34&t=209735) by 4epT, but it's not working. I am not sure what i did wrong, if anyone knows please assist

**Comment by cliffordx3** [comment]
try this one 
reactOnNPC c talk text @eval(#31 #41 #3~2) {
    type text
    useColors 1
    delay 2
    msg_0 /[Kafra]/
    msg_1 /Solve the following problem:/
    msg_2 //
    msg_3 /> If: B=(\d+) A=(\d+) C=(\d+) .../
    msg_4 /How many is A \+ B \+ C ?/
    msg_5 / * Attempt . of . */
}

**Comment by dt1536** [comment]
> try this one reactOnNPC c talk text @eval(#31 #41 #3~2) { type text useColors 1 delay 2 msg_0 /[Kafra]/ msg_1 /Solve the following problem:/ msg_2 // msg_3 /> If: B=(\d+) A=(\d+) C=(\d+) .../ msg_4 /How many is A + B + C ?/ msg_5 / * Attempt . of . */ }

> [2023.12.26 20:55:00.78] Unknown #110420366: Solve the following problem:
> [2023.12.26 20:55:00.79] [reactOnNPC] NPC message saved (1): "Solve the following problem:".
> [2023.12.26 20:55:00.79] Unknown #110420366:  
> [2023.12.26 20:55:00.79] [reactOnNPC] NPC message saved (2): " ".
> [2023.12.26 20:55:00.80] Unknown #110420366: > If: A=1 B=2 C=2 ...
> [2023.12.26 20:55:00.81] [reactOnNPC] NPC message saved (3): "> If: ^0000ffA^000000=^ff00001 ^0000ffB^000000=^ff00002 ^0000ffC^000000=^ff00002 ...".
> [2023.12.26 20:55:00.81] Unknown #110420366: How many is A + B + C ?
> [2023.12.26 20:55:00.81] [reactOnNPC] NPC message saved (4): "How many is ^0000ffA ^000000+ ^0000ffB ^000000+ ^0000ffC ^000000?^000000".
> [2023.12.26 20:55:00.82] Unknown #110420366:  
> [2023.12.26 20:55:00.82] [reactOnNPC] NPC message saved (5): " ".
> [2023.12.26 20:55:00.82] Unknown #110420366: * Attempt 1 of 5 *
> [2023.12.26 20:55:00.83] [reactOnNPC] NPC message saved (6): "* Attempt 1 of 5 *".
> [2023.12.26 20:55:00.83] [reactOnNPC] onNPCAction type is: continue.
> [2023.12.26 20:55:00.83] [reactOnNPC] Conditions for reactOnNPC_0 (npc:continue, rect:text) 'type' not met.
> [2023.12.26 20:55:00.84] : Type 'talk cont' to continue talking
> [2023.12.26 20:55:01.60] Kafra: You have 89 second(s) to respond.
> [2023.12.26 20:55:01.74] [reactOnNPC] onNPCAction type is: text.
> [2023.12.26 20:55:01.75] [reactOnNPC] Conditions for reactOnNPC_0 (npc:text , rect:text) is met.
> [2023.12.26 20:55:01.75] [reactOnNPC] Matching [msg (0)] "[^ff0000Kafra^000000]" to "/[Kafra]/" ... regexp ok.
> [2023.12.26 20:55:01.76] [reactOnNPC] Matching [msg (1)] "Solve the following problem:" to "/Solve the following problem:/" ... regexp ok.
> [2023.12.26 20:55:01.76] [reactOnNPC] Matching [msg (2)] " " to "//" ... doesn't match.
> [2023.12.26 20:55:01.77] [reactOnNPC] One or more lines doesn't match for "reactOnNPC_0" (2).
> [2023.12.26 20:55:01.78] itself: Type 'talk text' (Respond to NPC)
> [2023.12.26 20:55:02.40] Packet Parser: Unknown switch: 0A41
> [2023.12.26 20:55:02.62] Kafra: You have 88 second(s) to respond.

it didnt work

**Comment by cliffordx3** [comment]
what RO are you playing?

**Comment by alisonrag** [comment]
please continue this discussion on forum, its not related to the plugin but to your regex
