### ISSUE TITLE
Rodex error after items added

### ISSUE THREAD

**Issue by dt1536** [OpenKore/openkore#3840]
> [2023.12.25 13:14:45.16] You have already set the mail target.
> [2023.12.25 13:14:46.22] Changed the rodex mail message title to 'takeititsforbeginner'.
> [2023.12.25 13:14:47.58] Set the rodex mail message body to 'youarewelcomemyfriend'.
> [2023.12.25 13:14:48.11] Set the rodex mail message zeny to '0'.
> [2023.12.25 13:14:50.34] Adding amount 1 of item 'Creamy Card (11)' to rodex mail.
> [2023.12.25 13:14:50.51] Item added to rodex mail message: Creamy Card (0) x 1 - Card
> [2023.12.25 13:14:51.83] Sending rodex mail.
> [2023.12.25 13:14:51.55] You lost 2,500 zeny.
> [2023.12.25 13:14:51.62] Inventory Item Removed: Creamy Card (11) x 1
> [2023.12.25 13:14:51.68] Item added to inventory: Creamy Card (11) x 1 - Card
> [2023.12.25 13:14:51.74] You failed to send the rodex mail.
> [2023.12.25 13:14:53.11] Your rodex mail box has been closed.

everything in macro works fine until rodex send, items it added back to inventory instead of inside the rodex mail

**Comment by alisonrag** [comment]
servertype?

**Comment by ya4ept** [comment]
A whole year has already passed.. We are closing it as no longer relevant
