### ISSUE TITLE
Please help deal with map server issue.thanks.

### ISSUE THREAD

**Issue by a129570500** [OpenKore/openkore#3842]
![image](https://github.com/OpenKore/openkore/assets/155905393/a16aad4d-4be5-4f95-9f03-33145269a33a)
I don't know what will cause this problem, please help me to deal with, thanks!

**Comment by dt1536** [comment]
from what i know, twro cant use openkore now

**Comment by a129570500** [comment]
> from what i know, twro cant use openkore now

Very thank for your answer, and from you know, this situation is already how many days? one week, one month or more long time? Because I want to know that I need still wait for it or change other program, thanks.

**Comment by LycorisRecoil-NishikigiChisato** [comment]
Openkore Discord
https://discord.gg/kmvfgYAfhC

I try to understand your behavior. But people keep posting the same questions over and over again. Because you never look at other people's previous questions. So I decided to pin the question and never close it!

**Comment by alisonrag** [comment]
#3843
