### ISSUE TITLE
Unable Bot to Turn In Map IDRO Server , Can help me ?

### ISSUE THREAD

**Issue by Topongoro** [OpenKore/openkore#3845]
i have a problem with map ti_wait in IDRO server , i dont know what happen i try to fix with map.txt but it not working thanks for you attention 

![Screenshot 2024-01-13 115401](https://github.com/OpenKore/openkore/assets/123613200/ec1e1a0a-4f94-46b1-8bad-e33dc57ab587)

**Comment by ya4ept** [comment]
obsolete
