### ISSUE TITLE
Help to connect on Mythos of Midgard

### ISSUE THREAD

**Issue by Garapim** [OpenKore/openkore#3846]
Hello, I'm trying to connect to a server and OpenKore can't even though I've gotten all the data correctly.

ip 15.235.112.76
port 6121
version 97
master_version 1 
serverType kRO_RagexeRE_2014_10_22b
serverEncoding Western
charBlockSize 155
addTableFolders translated/kRO_english;kRO

![image](https://github.com/OpenKore/openkore/assets/122859025/af8b49bc-349c-4bd7-9836-290aefa2a45c)

**Comment by fenzerloureiro** [comment]
I need help with this too, someone can help?

**Comment by Garapim** [comment]
fenzer add me discord _fbraga

**Comment by fantomevision** [comment]
Anyone got the solution?

**Comment by ragexe** [comment]
@Garapim hey
was it successful? please contact me _ragexe#2978_

**Comment by jhernaez73** [comment]
i also need some help on connecting to another server im a newbie

**Comment by alisonrag** [comment]
server closed
