### ISSUE TITLE
RO Landverse 2024 won't connect! Does anyone know how to solve it?

### ISSUE THREAD

**Issue by Gugatrem** [OpenKore/openkore#3851]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
![landverse](https://github.com/OpenKore/openkore/assets/158843145/0b1aab01-776f-4832-bc71-2c92e4b8c9b9)

* **Server**: Landverse

* **Bug Report / Feature Request**: não conecta

* **Summary**: baixei o openkore pelo site oficial, mudei o serve, dei o start, apareceu esse erro, alguem pode me ajudar?

**Comment by sjhonanthan** [comment]
eu consegui passar desse erro, mas ele conecta, mas depois fica desconectando, conseguiu algo?

**Comment by Gugatrem** [comment]
Mesma coisa.. conecta, e desconecta

Em ter., 2 de abr. de 2024 às 13:06, sjhonanthan ***@***.***>
escreveu:

**Comment by sjhonanthan** [comment]
@Gugatrem ainda estou tentando, mas tem poucas informações a respeito, tem um cara chamado alissonrag que acho que possui a informação, mas ele não respondeu ainda :( qualquer coisa me informa, pois queria jogar o landverse, mas sem auto é complicado
forma que eu entendi, acredito que o ip e a porta do server mudou, então tem que usar o wpe conection guide para pegar novamente essas informações, porém o meu não reconhece o landverse para pegar essa informação e verificar, ai depois de configurar essa informação tem que verificar o proximo erro, enfim é o caminho por onde estou indo, se tu conseguir um ip e porta me informa ai

**Comment by alisonrag** [comment]
#3791
