### ISSUE TITLE
Newbie Question "How to set up openkore to Private Server ChaosClassic PH"

### ISSUE THREAD

**Issue by jhernaez73** [OpenKore/openkore#3853]
Very old ragnarok player 2002 but "Newbie on trying to understand the program" 

Issue : First time downloading the program but i'm not sure if im doing the right thing, it would be much appreciated if someone can point me to the right configuration and would also let me understand where to locate such file.

How would i be able to connect to this server https://chaos-classic.net/

**Comment by alisonrag** [comment]
server closed
