### ISSUE TITLE
kRO poseidon, gameguard ploblem

### ISSUE THREAD

**Issue by ragmania1** [OpenKore/openkore#3854]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
master
* **Server**: 
kRo
* **Bug Report / Feature Request**:
gameguard
* **Summary**:

Hello. I'm trying to use kRo, but even when I turn on Poseidon server and try to connect, 
it disconnects within 1-2 minutes. It seems like GameGuard is causing conflicts. Is there a solution to this issue?
I use a translator because I am not good at English. Sorry

![스크린샷 2024-03-13 043210](https://github.com/OpenKore/openkore/assets/163191582/5f9463b2-d6de-40d3-91fd-1435fb9fa6cb)

**Comment by comwhat** [comment]
해결하셧나요

**Comment by alisonrag** [comment]
#3514
