### ISSUE TITLE
Does OpenKore handle multiple IPs servers?

### ISSUE THREAD

**Issue by SapitoSucio** [OpenKore/openkore#3857]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
https://github.com/OpenKore/openkore/commit/1edc50f32460846e3a9d9ea58a523fb631b1ab6d

* **Server**: 
Landverse

* **Bug Report / Feature Request**:
Can't connect

* **Summary**:
Apparently, Landverse's login IP is `103.169.66.141::51000`, then passes to the char server, which is `103.169.66.142::52000`, then finally reaches map-server, which is `103.169.66.142::53000`

openkore tries to connect only to the first IP and doesn't try to reach the other IP.

**Comment by alisonrag** [comment]
yep, openkore can handle connections between servers, even if they use different ip/port
