### ISSUE TITLE
Bot  Skill error / No valid skill identifier specified.

### ISSUE THREAD

**Issue by danputaporn** [OpenKore/openkore#3858]
## ------------------ Openkore Issues Template ------------------

My bot dragonknight  use skill  Dragonica [6001] / crash .

![image](https://github.com/OpenKore/openkore/assets/166638895/11c9dc88-7788-41b8-8f9e-675bce98ca40)

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by dcyxxt** [comment]
i got the same problem

**Comment by BigPaps** [comment]
had same problem. 
i think it's related to this [2491232534](https://github.com/OpenKore/openkore/issues/3818#issuecomment-2491232534)

**Comment by ya4ept** [comment]
close as a double: https://github.com/OpenKore/openkore/issues/3818
