### ISSUE TITLE
adminPassword issue

### ISSUE THREAD

**Issue by Genuinegithub** [OpenKore/openkore#386]
Is the adminPassword is disabled now in openkore? because my bot wont respond when I pm'ed with my adminpassword.. I just wanted confirmation.. Thanks

**Comment by lututui** [comment]
To avoid players abusing the chat commands, inGameAuth was implemented. To auth a player through a PM, just toggle inGameAuth in the config.txt (inGameAuth 1)

**Comment by itsrachelfish** [comment]
@Genuinegithub Closing this issue now. Feel free to re-open it if you run into any other issues.
