### ISSUE TITLE
cRO Timeout on Account Server

### ISSUE THREAD

**Issue by skyzhishui** [OpenKore/openkore#3860]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 1edc50f

* **Server**: cRO

* **Bug Report / Feature Request**:After the recent change in authentication methods, openkore has been unable to log into cRO. Currently, the account uses a mobile verification code login mode similar to SSO authentication.

* **Summary**:
Connecting to Account Server...
Connecting (acc.ro.zhaouc.com:6900)... connected
Timeout on Account Server, reconnecting. Wait 34 seconds...

Before the change in authentication method,cRO's charBlockSize has been changed from 155 to 175.

**Comment by skyzhishui** [comment]
After the first successful verification,I can use the cookies to maintain login status. Here is the cookie format I obtained:
userData60={"appId":60,"accountId":"17****************0","token":"8******************************0","userName":"{your_phonenum}","avatar":"default.jpg","firstLogin":0,"realNameState":1}
**appId** :may be a fixed value.
**accountId** :the ID of the primary account.
**token**:a 32-character string.

the API can be used to further obtain the information of the bound sub-accounts:
**childAccountId** :the ID of the child account.
**childAccountToken** :the ID of the primary account.

other parameters that may be fixed include:
**unionAppId**=102020086
**unionChannelId**=102024001
**gameServerId**=9999

the result of capturing packets for login:
![20240511](https://github.com/OpenKore/openkore/assets/25737313/17a8b9c4-3301-471a-b706-1d3bac0b9952)

**Comment by hubertyang88** [comment]
same problem here , can you leave an email address?

**Comment by cola111222** [comment]
Hello, can you help me with the verification and Poseidon issues? I have configured Poseidon, and the address I obtained is exactly the same as the one you provided. However, I am not sure how to start the RO client with Poseidon to implement the fake server functionality. Can you teach me how to do this? QQ: 414275974. Payment is possible, big brother.

**Comment by kahineasin** [comment]
Hello can you help me to config for cRO? My QQ number is 251561897

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/issues/3837
