### ISSUE TITLE
私人服务器更新版本后，连接地图超时。

### ISSUE THREAD

**Issue by genemiaki** [OpenKore/openkore#3861]
Hi everyone, I'm playing on a private Chinese server, and before the game update it was working fine with openkore, but after the update yesterday, it prompted a connection timeout with the map server.

Here is the server.txt before the update
ip xxxxx
port 6900
master_version 128
version 4
serverType kRO_RagexeRE_2021_11_03
serverEncoding GBK
charBlockSize 175
addTableFolders kRO/Ragexe_2021_11_03;iRO
private 1
gameGuard 0

I tried to modify serverType and addTableFolders, and I can't solve the problem. I hope someone can help me out, I'm willing to pay.

**Comment by hubertyang88** [comment]
Please write in english or your issue might be ignored.
try to capture packets from ragexe and compare with openkore
用抓包工具抓一下客户端的地图服务器登录包，和openkore的比较一下

**Comment by genemiaki** [comment]
> 请用英文填写，否则您的问题可能会被忽略。 尝试从ragexe抓包并与openkore进行比较用 抓包工具抓一下客户端的地图服务器登录包，和openkore的比较一下

Ok, I have changed the description to English. deepl translator, hopefully it will translate accurately.

**Comment by akimzord** [comment]
Do you still need help? Check if the IP or port has changed. Another possible solution is to verify the hexed date to confirm if the date remains the same.
