### ISSUE TITLE
Issues with cRo Authentication and Usage

### ISSUE THREAD

**Issue by cola111222** [OpenKore/openkore#3862]
Openkore version git: https://github.com/OpenKore/openkore/commit/1edc50f32460846e3a9d9ea58a523fb631b1ab6d
Server: cRO
Bug Report / Feature Request:Change Cro login authentication to mobile authentication and WeGame platform login authentication. How can I pass the authentication and use it? Payment is possible.
Summary:
Connecting to Account Server...
Connecting (acc.ro.zhaouc.com:6900)... connected
Timeout on Account Server, reconnecting. Wait 34 seconds...

**Comment by alisonrag** [comment]
#3862

**Comment by alisonrag** [comment]
https://github.com/OpenKore/openkore/issues/3837
