### ISSUE TITLE
Can't call method "inventory" on unblessed reference at src/functions.pl line 437.

### ISSUE THREAD

**Issue by Maped12** [OpenKore/openkore#3867]
Hello, i have this problem when i try run my open kore.

OpenKore version 2.0.6.1
@ai_seq = clientSuspend
Network state = 4
Network handler = Network::XKore
SVN revision: 6803
Loaded plugins:
  plugins/macro.pl (macro)

Error message:
Can't call method "inventory" on unblessed reference at src/functions.pl line 437.

Stack trace:
Can't call method "inventory" on unblessed reference at src/functions.pl line 437.
 at src/Interface/Wx.pm line 113
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x43d4b40)') called at openkore.pl line 96
	main::__start() called at start.pl line 125

Died at this line:
  		delete $char->{homunculus}{appear_time};
* 		$char->inventory->clear();
  	}

**Comment by alisonrag** [comment]
in some way openkore is not setting char, could be:
wrong servertype
wrong charblocksize
you are trying to connect on xkore 1 after character select screen
