### ISSUE TITLE
Failed to connect to client, assistance needed

### ISSUE THREAD

**Issue by damiao-czh** [OpenKore/openkore#3873]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
OpenKore what-will-become-2.1 ( version ctime:2024_08_06 ) - Custom Ragnarok Online client
[servers.txt](https://github.com/user-attachments/files/16505521/servers.txt)
[config.txt](https://github.com/user-attachments/files/16505523/config.txt)
![QQ截图20240806130858](https://github.com/user-attachments/assets/caf310dc-558e-4bdb-9f87-bcf2a4b200d2)

* **Server**: 
kRO
* **Bug Report / Feature Request**:
When i use XKore 0,I received a message：Packet Tokenizer: Unknown switch: 4753；When i use XKore 3,I received a message：error
message
can't call method inventory on an undefined value at src/Network/Receive,pm line 5195

**Comment by damiao-czh** [comment]
[Uploading console_qwer_0.txt…]()

**Comment by damiao-czh** [comment]
help

**Comment by alisonrag** [comment]
packet 4753 means gepard, there is no official support to gepard
