### ISSUE TITLE
Kro Zero Support?

### ISSUE THREAD

**Issue by comwhat** [OpenKore/openkore#3875]
Kro Zero Support? Don't work Poseidon

## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
(https://github.com/OpenKore/openkore/tree/kRO-support)
kro

[RagnarokServer]-> Ragnarok Online client (5) disconnected.
[RagnarokServer]-> Ragnarok Online client (5) connected.
[RagnarokServer]-> Ragnarok Online client (5) disconnected.
[RagnarokServer]-> Ragnarok Online client (5) connected.
Requested Char List (Standard)
Wanted CharBlockSize : 155
Packstring size: 155
Built CharBlockSize : 155
[RagnarokServer]-> Ragnarok Online client (5) disconnected.

**Comment by alisonrag** [comment]
#3514
