### ISSUE TITLE
About cRO Server 

### ISSUE THREAD

**Issue by kahineasin** [OpenKore/openkore#3878]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: master

* **Server**: cRO

* **Bug Report / Feature Request**:Feature Request

* **Summary**:Can openKore use on cRO now? cRO use mobile phone message validate code to login by laucher.exe，how to set config for this way?

**Comment by ya4ept** [comment]
We do not have ready-made plugins for such authorization.
