### ISSUE TITLE
Arcadia RO reconnects to login server

### ISSUE THREAD

**Issue by alexey-khabulyak** [OpenKore/openkore#3879]
* **Openkore version git**:  the latest master version from git

* **Server**: Arcadia https://arcadia-online.org/

* **Bug Report / Feature Request**: Bug Report

* **Summary**:
I am trying to set up a bot for the server via xkore 3.
I can connect to login, char and map server.
But
1. there are 2 unkonwn switch errors Packet Tokenizer: Unknown switch: 0021 and Packet Parser: Unknown switch: 0840 
2. right after map server is connected, i get a lot of messages:

![image](https://github.com/user-attachments/assets/d0d0f340-faa6-47da-8508-3e0b3b889a00)

Server config:
[Arcadia]
ip 145.239.70.40
port 6121
serverType kRO_RagexeRE_2020_04_01b
master_version 1
version 20
serverEncoding Western
gameGuard 1
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders kRO/Ragexe_2020_04_01b;iRO/official;iRO
charBlockSize 175
pinCode 0
charDeleteDateType 1
rankingSystemType 1
private 1

**Comment by sohje** [comment]
@alexey-khabulyak did you get it sorted?

**Comment by skyleo** [comment]
Any updates?
