### ISSUE TITLE
Task::Teleport to replace Misc::useTeleport internals and current AI logic

### ISSUE THREAD

**Issue by farrainbow** [OpenKore/openkore#388]
`Task::Teleport` and maybe separate `Task::Respawn` interface.

It should wait for map change to occur, possibly retry and fail otherwise.

Needed for other AI tasks.

**Comment by c4c1n6kr3m1** [comment]
is teleportAuto_useSkill 2 or 3 still exists today ?

**Comment by itsrachelfish** [comment]
@c4c1n6kr3m1 I don't believe 2 or 3 works anymore on most servers. It definitely doesn't work on iRO chaos. It might work on old servers like iRO classic, but I haven't tested that.

**Comment by lututui** [comment]
I'm pretty sure it's been patched in most, if not all, emulators, Aegis included.

**Comment by itsrachelfish** [comment]
It's really sad too, using the teleport glitch was one of my favorite things :cry:
