### ISSUE TITLE
On Payon Stories

### ISSUE THREAD

**Issue by RagnaOldLORD** [OpenKore/openkore#3883]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 
The latest update
* **Server**: 
Private Payon Stories
* **Bug Report / Feature Request**:
General question/help, Is it possible to run openkore on this server?
* **Summary**:
I have used openkore on bRO like more than a decade ago and then went off. As I was studying to re-learn stuff again I got trapped in a few spots and didn't find solutions on wiki or forums since it's pretty much empty when checked the last updates by people.
I was wondering, has anyone got it to work on this server? Is it possible? 
I'm having dificulties on configuring and out of memory error.

**Comment by ya4ept** [comment]
we don't support this server, please use the [guide](https://openkore.com/wiki/Main_Page) and [form](https://forums.openkore.com/)
