### ISSUE TITLE
can't logging to 

### ISSUE THREAD

**Issue by sopik** [OpenKore/openkore#3884]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: newest

* **Server**: private servers 

* **Bug Report / Feature Request**: char server error

* **Summary**: how to edit char server ip?

![image](https://github.com/user-attachments/assets/4072fdc3-835f-4ad8-a5fe-cba1a2728f6f)

I try openkore to logging to a private servers

I received the following data:

64 00 14 00 00 00 73 6F 70 69 30 30 30 31 00 24 
00 00 00 00 00 00 66 CF 00 00 78 36 00 00 31 32 
31 33 31 32 00 00 2C 36 00 00 14 24 00 00 00 00 
00 00 5A CF 00 00 05

According to the wiki, the last 05 (hex) is the master version, which equals 5 (decimal).

The part 14 00 00 00 is supposed to represent the version, displayed as a 4-byte unsigned number in little-endian format (in hex). But I don’t understand—it seems to be 20?

Here are my settings:

ip 35.229.157.25
port 3011
master_version 5
version 20
patchserver wpatch.ragnarok.co.id
patchpath /patch02
serverType 0
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 155
charDeleteDateType 1
blockingPlayerCancel 1
rankingSystemType 1
ignoreAntiCheatWarning 0

this setting let me to the image

However, this setup fails to log in char server, it try to login to "192.168.x.x".

Could someone please help me figure out what’s wrong?

where can I edit the char server ip?

thanks

**Comment by alisonrag** [comment]
try `private 1`

**Comment by ya4ept** [comment]
https://openkore.com/wiki/private
