### ISSUE TITLE
Add new server

### ISSUE THREAD

**Issue by wandersonlt** [OpenKore/openkore#3889]
* **Server**: 

Would it be possible to add the Ragnatales server among the available servers?

**Comment by ya4ept** [comment]
Hi. We are not trying to add all pirate servers to the distribution. There is a guide on the wiki on how you can do it yourself. If the server has bot protection, you should bypass it yourself before using openkore.

**Comment by M3nestrel** [comment]
como eu posso configurar e extrair infomações de um servidor, para colar bot?
