### ISSUE TITLE
tRO Received packet: 09CF - GameGuard Request

### ISSUE THREAD

**Issue by TheLegionZ-B** [OpenKore/openkore#3891]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 2.1 ( version ctime:2024_08_17 )

* **Server**:  tRO

* **Bug Report / Feature Request**: Received packet: 09CF - GameGuard Request

* **Summary**: 
tRO change gameguard EAC to nProtect
x0 disconnect every 25sec
<< Received packet:      09CF - GameGuard Request [72 bytes]
<< Received packet:      09CF - GameGuard Request

**Comment by alisonrag** [comment]
Use wiki search for poseidon
