### ISSUE TITLE
Can't call method "inventory" on an undefined value at src/Network/Receive.pm line 5195.

### ISSUE THREAD

**Issue by Kadal6594asd** [OpenKore/openkore#3893]
help me

OpenKore version what-will-become-2.1
Network state = -1
Network handler = Network::XKoreProxy
Revision: ctime:2024_10_26
Loaded plugins:
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/SendDC.pl (Oqha Bot Helper RoRETRO; description: fb.com/oqhadev)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Can't call method "inventory" on an undefined value at src/Network/Receive.pm line 5195.

Stack trace:
Can't call method "inventory" on an undefined value at src/Network/Receive.pm line 5195.
 at src/Network/Receive.pm line 5195
	Network::Receive::item_list_start('Network::Receive::kRO::RagexeRE_2020_03_04a=HASH(0x900ad54)', 'HASH(0x9743e24)') called at src/Network/PacketParser.pm line 279
	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2020_03_04a=HASH(0x900ad54)', '\x{8}\x{b}\x{6}\x{0}\x{0}\x{0}', 'Network::Receive::kRO::RagexeRE_2020_03_04a=HASH(0x900ad54)') called at src/Network/Receive.pm line 603
	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2020_03_04a=HASH(0x900ad54)', '\x{8}\x{b}\x{6}\x{0}\x{0}\x{0}', 'Network::Receive::kRO::RagexeRE_2020_03_04a=HASH(0x900ad54)') called at src/Network/PacketParser.pm line 413
	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2020_03_04a=HASH(0x900ad54)', 'Network::MessageTokenizer=HASH(0x863300c)', 'Network::Receive::kRO::RagexeRE_2020_03_04a=HASH(0x900ad54)') called at src/functions.pl line 834
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4978884)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	if ( $args->{type} == INVTYPE_INVENTORY ) {
* 		$char->inventory->onitemListStart();
  	} elsif ( $args->{type} == INVTYPE_CART ) {

**Comment by alisonrag** [comment]
this means that ur $char is not defined, most part of time is a result of wrong character list or in some cases the lack of it.
if you are using xkore 1 make sure that openkore receives the character list and display it correct.
if you are using xkore 0 make sure to define the correct characterblocksize
