### ISSUE TITLE
Xcore Stuck after server selection

### ISSUE THREAD

**Issue by d3ndyyy** [OpenKore/openkore#3898]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

Latest Update Version Git
* **Server**: 

idRO [gnjoycl](https://roclassic.gnjoy.id/)
* **Bug Report / Feature Request**:

Stuck After Choose server
* **Summary**:
* hello need help how to solve this im using Xcore 1
after i choose server then nothing happened just failed to connect to server after i choose server 
thankyou for your help guys

**Comment by ya4ept** [comment]
you can join the discussion:
https://forums.openkore.com/viewtopic.php?f=13&t=334458
