### ISSUE TITLE
Quest killcount

### ISSUE THREAD

**Issue by Henrybk** [OpenKore/openkore#39]
Some server never send 'quest_all_mission' or 'quest_all_list2' packets or never update the 'goal' key in kill count quests until we kill at least one of whatever the quest wants us to kill, and even so when me change map or teleport (?) we lose that info. On some quests like eden equipment quest on payon cave that becomes a problem since when we leave pay_dun00 to go to pay_arche we lose the 'goal' key and as soon as we pass the portal kore doesn't know if the quest is complete anymore.

There could be a quest_killcount_db.txt in tables with all the killcount quests. It could be generated from a emulator file like this one from brAthena:
https://github.com/brAthena/brAthena/blob/master/db/quest_db.conf

And when the server finally gives us information of the 'goal' key we could check if it exists in quest_killcount_db.txt (and if not, add it) and if it matches the info we have from the file (and if not, change it).

**Comment by Henrybk** [comment]
This has been fixed in #43

**Comment by flacrasec** [comment]
I have got this error message
![error](https://cloud.githubusercontent.com/assets/17572686/19708233/69116e0a-9af3-11e6-9b88-5567a86b4c88.jpg)
