### ISSUE TITLE
appear You changed unknown sprite type (13)

### ISSUE THREAD

**Issue by dcyxxt** [OpenKore/openkore#3905]
when i use the latest vision ,my  kore appear this
You changed unknown sprite type (13)
You changed unknown sprite type (7)

This may be related to the change
https://github.com/OpenKore/openkore/pull/3899

[console_20241217.txt](https://github.com/user-attachments/files/18158838/console_20241217.txt)

**Comment by ya4ept** [comment]
show me `i eq`

**Comment by dcyxxt** [comment]
> show me `i eq`

i eq
------------------- Inventory --------------------
-- Equipment (Equipped) --
28   眼镜 [约旦教团主教卡] [1] -- 头部(中) (512)                      
30   初心者影之铠甲 -- 时装盔甲 (65536)                              
31   初心者影之盾牌 -- 时装盾牌 (262144)                             
32   初心者影之靴子 -- 时装鞋子 (524288)                             
33   初心者影之武器 -- 时装单手武器 (131072)                           
34   初心者影之耳环 -- 时装装饰品(左) (1048576)                        
35   初心者影之吊坠 -- 时装装饰品(右) (2097152)                        
36   暴徒的围巾 -- 头部(下) (1)                                   
37   +9 善恶王冠(龙骑士) [尧乐图斯主教卡片] -- 头部(上) (256)               
38   凯渥宝乐格手套 [森林魔法球(Expert Archer):森林魔法球(Master Archer):森林魔法球(Physical Power):雪兔鼻涕虫卡片] -- 装饰品(右) (8) 
39   +11 阿斯加德单手矛[强化] [乌龟将军卡片:雪花魔力(天龙气息)*2:雪花魔力(物理)5Lv] [4 Option] -- 单手武器 (2) 
40   尼德霍格的毒刺[普通] [故障的警卫型机器人β卡片] [5 Option] -- 装饰品(左) (128) 
41   +10 阿斯加德战士之盾[普通] [约旦圣地守护者卡片] [3 Option] -- 盾牌 (32)   
42   +10 尼德霍格的鳞甲[强化] [朱希娅卡片] [3 Option] -- 盔甲 (16)        
43   +10 尼德霍格的斗篷[强化] [尧斯特交涉师卡片] [3 Option] -- 披风 (4)      
44   +10 尼德霍格的胫甲[强化] [森林魔法球(Firing Shot):森林魔法球(HP):森林魔法球(Size Attack):郊狼卡片] [3 Option] -- 鞋子 (64) 
45   审判之翼 -- 时装头部(中) (2048)                               
46   迪奥娜の帽子 -- 时装头部(上) (1024)                             
47   迪奥娜の光环 [环球宝石[绿色]] -- 时装头部(下) (4096)

**Comment by ya4ept** [comment]
Can you unequip all the items, then equip them one by one and determine which item is causing the error?
And show a screenshot of the RO client

**Comment by dcyxxt** [comment]
> Can you unequip all the items, then equip them one by one and determine which item is causing the error? And show a screenshot of the RO client

I have already uneq all items, but still have this error

![01](https://github.com/user-attachments/assets/ae01d3dd-4521-472a-9a30-cf39df5a98cf)
![02](https://github.com/user-attachments/assets/9e17ac78-50fd-452c-95a2-ef8407276114)

**Comment by dcyxxt** [comment]
<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:56
  0>  D7 01 EA 92 1E 00 02 47    06 51 00 00 00 00 00       .......G.Q.....
[2024.12.17 09:12:56.95] ================================================
<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:56
  0>  D7 01 EA 92 1E 00 0D A7    10 00 00 00 00 00 00       ...............
[2024.12.17 09:12:56.95] You changed unknown sprite type (13), write about it to OpenKore developer


[2024.12.17 09:12:57.20] Player Exists: 打猎人 (0) Level 275 男孩 Windhawk (160, 106)
[2024.12.17 09:12:57.21] ================================================
<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:57
  0>  D7 01 32 86 1E 00 0D A1    10 00 00 00 00 00 00       ..2............
[2024.12.17 09:12:57.21] Player 打猎人 (0) changed unknown sprite type (13), write about it to OpenKore developer

<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:59
  0>  D7 01 02 90 1E 00 07 03    00 00 00 00 00 00 00       ...............
[2024.12.17 09:12:59.73] Player 哔哔哔哔哔哔哔哔哔哔揪 (1) changed unknown sprite type (7), write about it to OpenKore developer
[2024.12.17 09:12:59.73] ================================================
<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:59
  0>  D7 01 02 90 1E 00 0D F6    10 00 00 00 00 00 00       ...............
[2024.12.17 09:12:59.74] Player 哔哔哔哔哔哔哔哔哔哔揪 (1) changed unknown sprite type (13), write about it to OpenKore developer


I think 01D7 is the key point

**Comment by dcyxxt** [comment]
<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:56
  0>  D7 01 EA 92 1E 00 02 47    06 51 00 00 00 00 00       .......G.Q.....
[2024.12.17 09:12:56.95] ================================================
<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:56
  0>  D7 01 EA 92 1E 00 0D A7    10 00 00 00 00 00 00       ...............
[2024.12.17 09:12:56.95] You changed unknown sprite type (13), write about it to OpenKore developer


[2024.12.17 09:12:57.20] Player Exists: 打猎人 (0) Level 275 男孩 Windhawk (160, 106)
[2024.12.17 09:12:57.21] ================================================
<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:57
  0>  D7 01 32 86 1E 00 0D A1    10 00 00 00 00 00 00       ..2............
[2024.12.17 09:12:57.21] Player 打猎人 (0) changed unknown sprite type (13), write about it to OpenKore developer

<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:59
  0>  D7 01 02 90 1E 00 07 03    00 00 00 00 00 00 00       ...............
[2024.12.17 09:12:59.73] Player 哔哔哔哔哔哔哔哔哔哔揪 (1) changed unknown sprite type (7), write about it to OpenKore developer
[2024.12.17 09:12:59.73] ================================================
<< Received packet:      01D7 - Weapon / Shield Display [15 bytes]   2024.12.17 09:12:59
  0>  D7 01 02 90 1E 00 0D F6    10 00 00 00 00 00 00       ...............
[2024.12.17 09:12:59.74] Player 哔哔哔哔哔哔哔哔哔哔揪 (1) changed unknown sprite type (13), write about it to OpenKore developer


I think 01D7 is the key point

**Comment by dt1536** [comment]
> > Can you unequip all the items, then equip them one by one and determine which item is causing the error? And show a screenshot of the RO client
> 
> I have already uneq all items, but still have this error
> 
> ![01](https://private-user-images.githubusercontent.com/29876819/396384554-ae01d3dd-4521-472a-9a30-cf39df5a98cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MTk1NjcsIm5iZiI6MTczNDQxOTI2NywicGF0aCI6Ii8yOTg3NjgxOS8zOTYzODQ1NTQtYWUwMWQzZGQtNDUyMS00NzJhLTlhMzAtY2YzOWRmNWE5OGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MDc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNDM1OWM2NWE2NTM4MDgzODEzODg1ZWY5ZmZlNDJkMDg0ZmFjODIzNWQwY2FkZTg4YzJkNDMwODk1OGQ1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.baOq0igVXh6EbknTy054-L0B0_SH_cD_JwoiC0V5Gjw) ![02](https://private-user-images.githubusercontent.com/29876819/396384589-9e17ac78-50fd-452c-95a2-ef8407276114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MTk1NjcsIm5iZiI6MTczNDQxOTI2NywicGF0aCI6Ii8yOTg3NjgxOS8zOTYzODQ1ODktOWUxN2FjNzgtNTBmZC00NTJjLTk1YTItZWY4NDA3Mjc2MTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MDc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZTZjYjRlM2RiNDNmNjdmZjljOTgyMGI3ZTE4MzMwZGU0N2ExZmE4MDFmNTUxNDBiZjU3Zjc3Y2JkMTdiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HtM4OS1JB_iPX4yqw3ZN_tjJUdJ4vB1OYv9nfud8UEA)

which server is it?

**Comment by ya4ept** [comment]
Is there a choice of body color on the server?

**Comment by dcyxxt** [comment]
> Is there a choice of body color on the server?

nope。🥲
