### ISSUE TITLE
Unknown switch: 0A15

### ISSUE THREAD

**Issue by ya4ept** [OpenKore/openkore#3907]
Add package support:
```
<< Received packet:      0A15 [12 bytes]   2024.12.17 09:12:57
  0>  15 0A 01 01 35 00 00 00    AF 00 00 00                ....5.......
[2024.12.17 09:12:57.41] Packet Parser: Unknown switch: 0A15
```

```
#if PACKETVER >= 20140611
struct PACKET_ZC_GOLDPCCAFE_POINT {
	// Note: 2014-04-30 has 1 byte less, but those packets are only functional after 2014-06-11Ragexe
	uint16 PacketType;
	int8 isActive; //< 1 = yes, 0 = no
	int8 mode;
	int32 point;
	int32 playedTime;
} __attribute__((packed));
DEFINE_PACKET_HEADER(ZC_GOLDPCCAFE_POINT , 0x0a15);
#endif // PACKETVER >= 20140611
```

**Comment by kidultwoo** [comment]
> Add package support:
> 
> ```
> << Received packet:      0A15 [12 bytes]   2024.12.17 09:12:57
>   0>  15 0A 01 01 35 00 00 00    AF 00 00 00                ....5.......
> [2024.12.17 09:12:57.41] Packet Parser: Unknown switch: 0A15
> ```
> 
> ```
> #if PACKETVER >= 20140611
> struct PACKET_ZC_GOLDPCCAFE_POINT {
> 	// Note: 2014-04-30 has 1 byte less, but those packets are only functional after 2014-06-11Ragexe
> 	uint16 PacketType;
> 	int8 isActive; //< 1 = yes, 0 = no
> 	int8 mode;
> 	int32 point;
> 	int32 playedTime;
> } __attribute__((packed));
> DEFINE_PACKET_HEADER(ZC_GOLDPCCAFE_POINT , 0x0a15);
> #endif // PACKETVER >= 20140611
> ```

The code "0A15 12" already exists in my RECVPACKETS.txt document. Do I need to perform any other operations? And which TXT document should I copy the above - mentioned code into?

**Comment by ya4ept** [comment]
Try applying this patch: https://github.com/OpenKore/openkore/pull/3916
