### ISSUE TITLE
Can openkore display the damage as K,M,B

### ISSUE THREAD

**Issue by dcyxxt** [OpenKore/openkore#3909]
Now that damage is to high
so,can openkore dispaly the damage as K,M,B

1000=1K
1000000=1M
1000000000=1B

**Comment by dcyxxt** [comment]
> please send a log where you can see billions of damage

not billions yet，just for example。 😶😶😶

**Comment by ya4ept** [comment]
If there is no problem, then why did you create it?

**Comment by dcyxxt** [comment]
> If there is no problem, then why did you create it?

sorry，just an advice。。

**Comment by ya4ept** [comment]
We don't plan to do this at the moment.

**Comment by dcyxxt** [comment]
> We don't plan to do this at the moment.

okk
