### ISSUE TITLE
asgard_vil map (iRO Classic)

### ISSUE THREAD

**Issue by farrainbow** [OpenKore/openkore#391]
Needs a field file and portals. Field file is probably the same as old payon.

Some portals by mib from IRC:
```
# Geffen to Izlude via Asgard Teleporter
geffen 132 66 asgard_vil 89 129 0 c c r0 c
asgard_vil 31 137 izlude_in 74 165 0 c c r1 c
```

http://forums.openkore.com/viewtopic.php?f=16&t=211125
https://forums.warpportal.com/index.php?/topic/170179-asgard-training-village-mk-i/

- [ ] add a field file if needed (maybe just resnametable would be enough)
- [ ] add portals
- [ ] assign higher route weight for map if needed to prevent navigation to this map unless really wanted to

**Comment by zackdreaver** [comment]
From resnametable:
asgard_vil.gnd#payon_mem.gnd#
asgard_vil.gat#payon_mem.gat#
asgard_vil.rsw#payon_mem.rsw#
À¯ÀúÀÎÅÍÆäÀÌ½º\map\asgard_vil.bmp#À¯ÀúÀÎÅÍÆäÀÌ½º\map\payon_mem.bmp#

Map:
[payon_mem.zip](https://github.com/OpenKore/openkore/files/755064/payon_mem.zip)

I'm not playing iRO classic so no idea about the warps

**Comment by alisonrag** [comment]
@ devs this can be easy fixed

**Comment by alisonrag** [comment]
Classic Server was closed, this information can't be applied to any server.
