### ISSUE TITLE
iRO - recvpackets out of date

### ISSUE THREAD

**Issue by urameshibr** [OpenKore/openkore#392]
Hello, the recvpackets for iRO is out of date, many troubles with packets.

Actually its not possible to do disasm, that packaget-extractor does not work.
The bot make login normally, but cant heal with items and many maps show unknow packets...

How to proceed in this case?

**Comment by lututui** [comment]
If you mean the 09DB 09DD packet issue, they've been addressed  (#351). Try updating your working copy.

**Comment by urameshibr** [comment]
Working now, thanks friend
