### ISSUE TITLE
Crash latest update

### ISSUE THREAD

**Issue by tricell17** [OpenKore/openkore#3922]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  Latest

* **Server**:

* **Bug Report / Feature Request**: Bug Report

* **Summary**: Latest Update Crashing

```
OpenKore version what-will-become-2.1
@ai_seq = sitAuto
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2024_12_26
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/item_weight_recorder/item_weight_recorder.pl (item_weight_recorder; description: item_weight_recorder plugin)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/map/map.pl (map; description: map)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/reconnect/reconnect.pl (reconnect; description: v1.0)
  plugins/xConf/xConf.pl (xConf; description: commands for change items_control, mon_control, pickupitems, priority)

Error message:
Operation "+": no method found,
	left argument has no overloaded magic,
	right argument in overloaded package Actor::You at src/Utils.pm line 200.

Stack trace:
Operation "+": no method found,
	left argument has no overloaded magic,
	right argument in overloaded package Actor::You at src/Utils.pm line 200.
 at src/Interface/Wx.pm line 164
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x673eef4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	my $time_needed = $object->{time_move_calc};
* 	my $elasped = time - $object->{time_move} + $extra_time;

```

**Comment by ya4ept** [comment]
I don't see such an error, are you downloading the openkore distribution or modifying the files yourself?

**Comment by tricell17** [comment]
openkore distribution from here, and never modifying anything. i run wxstart with normal config.txt

**Comment by ya4ept** [comment]
I downloaded openkore, ran wxstart.exe, no error:
![image](https://github.com/user-attachments/assets/4934e5d9-926f-449a-a2f9-cf27863aa76d)

I chose the idRO server, there is no error either

**Comment by tricell17** [comment]
![image](https://github.com/user-attachments/assets/82081c29-a715-49fc-b581-622cea6f9f29)

**Comment by alisonrag** [comment]
add to src/Utils.pm between line 198 and 199:
```
my ($package, $filename, $line) = caller;
Log::message("$package, $filename, $line\n");
```

and send to us the console log

**Comment by dcyxxt** [comment]
i got this error too..

**Comment by dcyxxt** [comment]
> add to src/Utils.pm between line 198 and 199:
> 
> ```
> my ($package, $filename, $line) = caller;
> Log::message("$package, $filename, $line\n");
> ```
> 
> and send to us the console log

after i add this

![123](https://github.com/user-attachments/assets/68a66810-cd63-4a58-8d68-7d6f8ef5e3e3)
 my openkore can't connect

**Comment by dcyxxt** [comment]
i can't log..

**Comment by dcyxxt** [comment]
the error will appear after storage

**Comment by editorberkelas5588** [comment]
I have same issue too

`
Error message:
Operation "+": no method found,
	left argument has no overloaded magic,
	right argument in overloaded package Actor::You at src/Utils.pm line 202.

Stack trace:
Operation "+": no method found,
	left argument has no overloaded magic,
	right argument in overloaded package Actor::You at src/Utils.pm line 202.
 at src/Utils.pm line 202
	Utils::calcPosition('Field=HASH(0x9e9100c)', 'Actor::You=HASH(0x424c114)') called at src/AI/CoreLogic.pm line 2892
	AI::CoreLogic::processPartySkillUse() called at src/AI/CoreLogic.pm line 171
	AI::CoreLogic::iterate() called at src/functions.pl line 869
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x469fcd4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	my $time_needed = $object->{time_move_calc};
* 	my $elasped = time - $object->{time_move} + $extra_time;
`

**Comment by dcyxxt** [comment]
> add to src/Utils.pm between line 198 and 199:
> 
> ```
> my ($package, $filename, $line) = caller;
> Log::message("$package, $filename, $line\n");
> ```
> 
> and send to us the console log

![123123](https://github.com/user-attachments/assets/221ca85c-08ec-4a9f-a316-8717f1020330)
i deleted macro, still can't log console

**Comment by alisonrag** [comment]
@dcyxxt @editorberkelas5588 
can u try https://github.com/OpenKore/openkore/pull/3923?

**Comment by editorberkelas5588** [comment]
> @dcyxxt @editorberkelas5588 can u try #3923?

Solved !! Thank you

**Comment by dcyxxt** [comment]
> @dcyxxt @editorberkelas5588 can u try #3923?

fixed.thx

**Comment by tricell17** [comment]
tested all good now thank you @ya4ept @alisonrag for fixed it

**Comment by Shinrey91** [comment]
> > @dcyxxt @editorberkelas5588 can u try #3923?
> 
> fixed.thx

teach me please, i have same problem

**Comment by alisonrag** [comment]
> > > @dcyxxt @editorberkelas5588 can u try #3923?
> > 
> > 
> > fixed.thx
> 
> teach me please, i have same problem

just download openkore again, this fix was implemented
