### ISSUE TITLE
DISCONNECT MAP , AGAIN, AGAIN , AND AGAIN 5 SECOND AGAIN DISCONECT

### ISSUE THREAD

**Issue by ilhamapurnama** [OpenKore/openkore#3929]
![SSS](https://github.com/user-attachments/assets/875403bc-a21d-40c1-944c-8d61adf0948b)
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

**Comment by alisonrag** [comment]
server?

**Comment by alisonrag** [comment]
saw ur comment on other issue, its idRO and need poseidon check wiki for poseidon
https://openkore.com/wiki/Poseidon
https://openkore.com/wiki/Configuring_Poseidon_for_twRO

**Comment by ya4ept** [comment]
https://forums.openkore.com/viewtopic.php?f=13&t=334458
