### ISSUE TITLE
[Discussion] Automacro "map" and "location" syntax

### ISSUE THREAD

**Issue by lututui** [OpenKore/openkore#396]
The automacro conditions "map" and "location" are very similar, and, in very few cases, interchangeable. Basically, **map** is a very basic version of **location**, that can only accept a single mapname and can't be inverted by using a "not".

```
map <mapname>
location [not] <mapname [<x1> <y1> [<x2> <y2>]] [, ...]
```

What do you think of merging their syntaxes, both using the "location" syntax? Since **location** can do anything **map** can, this change wouldn't break any macros that use any of these conditions.

**Comment by Nipodemos** [comment]
i agree with this, but on eventMacro
