### ISSUE TITLE
autotalkcont bug

### ISSUE THREAD

**Issue by Henrybk** [OpenKore/openkore#40]
On some servers the lag sometimes makes openkore disconnect when talking to npcs if the config key autotalkcont is set to '1'

**Comment by itsrachelfish** [comment]
Do you know what the underlying cause for this is? As far as I know, RO servers will disconnect players for sending "unexpected" packets at any point. Like if you send a talk response when there is no response menu, you will be disconnected. Is kore trying to continue the conversation before the conversation has technically started?

**Comment by Henrybk** [comment]
As you can see here: https://i.gyazo.com/4aaa7306e3e99a544db0801496f61f92.png

and in this code from servertype0:
`sub npc_talk_continue {
	my ($self, $args) = @_;
	my $ID = substr($args->{RAW_MSG}, 2, 4);
	my $name = getNPCName($ID);

	$ai_v{npc_talk}{talk} = 'next';
	$ai_v{npc_talk}{time} = time;

	if ($config{autoTalkCont}) {
		message TF("%s: Auto-continuing talking\n", $name), "npc";
		$messageSender->sendTalkContinue($ID);
		# This time will be reset once the NPC responds
		$ai_v{npc_talk}{time} = time + $timeout{'ai_npcTalk'}{'timeout'} + 5;
	} else {
		message TF("%s: Type 'talk cont' to continue talking\n", $name), "npc";
	}
}`

There's no waiting time before sending the talk continuation packet. I suggest we move this to AI like proposed here: http://forums.openkore.com/viewtopic.php?f=36&t=10125&hilit=autoTalkCont

**Comment by as70873463** [comment]
tRO Bug !! 18/09/59

**Comment by Henrybk** [comment]
This is still a big problem, in brazilian community we have at least 1 post each week about this bug.
