### ISSUE TITLE
Can anyone answer this. (Private Server KRO)

### ISSUE THREAD

**Issue by crowndevilz** [OpenKore/openkore#400]
![error bot](https://cloud.githubusercontent.com/assets/25115445/21953078/17f4469a-da69-11e6-88a5-9e788232b7cb.png)

OpenKore version what-will-become-2.1
Network state = 4
Network handler = Network::DirectConnection
SVN revision: unknown
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = {};

Stack trace:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = {};
 at src/Utils/BlessedRefTie.pm line 10
	Tie::BlessedRef::STORE('Tie::BlessedRef=SCALAR(0x5a699fc)', 'HASH(0x6578fcc)') called at src/Network/Receive/kRO/Sakexe_0.pm line 3536
	Network::Receive::kRO::Sakexe_0::stat_info('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x6117964)', 'HASH(0x6578ffc)') called at src/Network/PacketParser.pm line 267
	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x6117964)', '\x{b0}\x{0}\x{7}\x{0}\x{88}\x{5}\x{0}\x{0}', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x6117964)') called at src/Network/Receive.pm line 137
	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x6117964)', '\x{b0}\x{0}\x{7}\x{0}\x{88}\x{5}\x{0}\x{0}', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x6117964)') called at src/Network/PacketParser.pm line 401
	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x6117964)', 'Network::MessageTokenizer=HASH(0x38c69f4)', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x6117964)') called at src/functions.pl line 736
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x46d045c)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

**Comment by itsrachelfish** [comment]
@crowndevilz Why did you close this? Did you find a solution?

**Comment by crowndevilz** [comment]
@itsrachelfish  i posted a new one which is more better to understand, but with the same problem.
