### ISSUE TITLE
combospam help

### ISSUE THREAD

**Issue by oquantico** [OpenKore/openkore#404]
is it normal that plugin combospam keep giving me the warning "Skill Raging Quadruple Blow failed: Requirement (error number 10)"??
it's like every second. the plugin is working but I had to use "squelchDomains skill" to see my console.

i'm doing something wrong?

**Comment by oquantico** [comment]
some one?

**Comment by alisonrag** [comment]
its normal, but maybe kore are sending the packet to use skill multiple times
