### ISSUE TITLE
Servertype not yet supported? KRO private server.

### ISSUE THREAD

**Issue by crowndevilz** [OpenKore/openkore#407]
i have done extracting revs and crypt keys. for this client [http://www.mediafire.com/file/6850zvhra7tfhln](url)
i Followed the Tut. [http://forums.openkore.com/viewtopic.php?f=6&t=211637](url)
seems like that i need to add a new server type in src/send.pm and receive.pm and tables/kro folder for RagexeRE_2015_05_13 client cause its not yet supported? @_@
![error](https://cloud.githubusercontent.com/assets/25115445/22051540/effe1dfa-dd7e-11e6-822c-33e03fae2026.png)

What do i need to do to create this new servertype? been trying for weeks now and this server has no gameguard or protection @_@

this is the official site   [http://www.valhalla.ro-gaming.net/](url)
PS. Not really sure if i got the revpackets correctly. 
[recvpackets.txt](https://github.com/OpenKore/openkore/files/713071/recvpackets.txt) my recvpacket.

**Comment by c4c1n6kr3m1** [comment]
Gepard Protection ?

**Comment by crowndevilz** [comment]
@c4c1n6kr3m1  nope there is no gameguard to this server. im thinking maybe this server type is not yet supported by openkore because it is 2015_05_13 client..

**Comment by itsrachelfish** [comment]
@crowndevilz Please test the code provided in pull request #414

**Comment by crowndevilz** [comment]
@itsrachelfish  hi ive tried using the new Server type that @Nyxvanthcal provided it didnt work but new error appears 
![errorrrs](https://cloud.githubusercontent.com/assets/25115445/22321774/597755cc-e3d2-11e6-8341-e24cf8b44c6b.png)

im trying to figure out what is that error.

**Comment by itsrachelfish** [comment]
Thanks for testing @crowndevilz !

**Comment by itsrachelfish** [comment]
@crowndevilz The code has been updated. Please reply directly to @Nyxvanthcal in pull request #414 if you have any other issues. :+1:

**Comment by Novishivsmoke** [comment]
Everything was updated ! 2015_05_13a created and 2015_11_04a too ! 
Thanks @itsrachelfish !

**Comment by LoseracK** [comment]
Hey if have looked in my repository, some 2015 clients are working good.
Can u close your thread @crowndevilz

**Comment by crowndevilz** [comment]
@LoseracK  yeah sure im just trying to find new servers where i could use it. anyway thank you so much for all of the effort. hope it could help others. BIG THANKS!!!
