### ISSUE TITLE
Changing font from Wx menu doesn't take effect.

### ISSUE THREAD

**Issue by onepointfivem** [OpenKore/openkore#409]
When changing the console font in the menu View > Font it doesn't take effect and the font dont change.
Using wxstart.exe and running from perl.

**Comment by ya4ept** [comment]
https://ro-fan.ru/viewtopic.php?p=87301#p87301
kLabMouse wrote:

> there has long been a bug related to the BX interface, or rather, the display of the interface.
I fixed it. But turned off the ability to change the font, color, etc. This is disabled until the BX components themselves are fixed.
