### ISSUE TITLE
Teleport using Fly Wing vs Novice Fly Wing

### ISSUE THREAD

**Issue by onepointfivem** [OpenKore/openkore#410]
Wouldn't be better if kore try to use Novice Fly Wing/Novice Butterfly Wings first, then if there's none, check for Fly Wing and Buttlerfly Wing? Makes more sense to me, because if one set to autobuy Fly Wings, Novice Fly Wings will never be used(?)

From Misc.pm
```
my $item;
	if ($use_lvl == 1) { #Fly Wing
		if (!$c	onfig{teleportAuto_item1}) {
			$item = $char->inventory->getByNameID(601);
			unless ($item) { $item = $char->inventory->getByNameID(12323); } # only if we don't have any fly wing
		} else {
			$item = $char->inventory->getByName($config{teleportAuto_item1});
		}
	} elsif ($use_lvl == 2) { #Butterfly Wing
		if (!$config{teleportAuto_item2}) {
			$item = $char->inventory->getByNameID(602);
			unless ($item) { $item = $char->inventory->getByNameID(12324); } # only if we don't have any butterfly wing
		} else {
			$item = $char->inventory->getByName($config{teleportAuto_item2});
		}
	}
```

**Comment by itsrachelfish** [comment]
I agree, novice wings should be used by default :+1:

**Comment by lututui** [comment]
Maybe the user should be able to choose the default behavior?

**Comment by onepointfivem** [comment]
Well, we can set `teleportAuto_item1` too I guess. Sometimes configs really makes me confusing lol

**Comment by c4c1n6kr3m1** [comment]
i choose fly wing first :)
so when i play using client, i don't need to buy FW, because i still have NFW , too lazy to buy ...

**Comment by alisonrag** [comment]
whats now? Novice Fly Wing or Fly Wing?

**Comment by alisonrag** [comment]
already implemented in openkore
