### ISSUE TITLE
Unknown Packet ABCD

### ISSUE THREAD

**Issue by masterplayer00000** [OpenKore/openkore#411]
Stuck on this Error.

How can this one be resolved?
Open to all suggestions.

**Comment by itsrachelfish** [comment]
What server are you playing on? Are you using the most recent version of openkore? We need more information! :stuck_out_tongue:

**Comment by masterplayer00000** [comment]
Lol sorry... haha! 

I'm currently Playing Philippine Ragnarok: Valkyrie
OpenKore Version: 2.0.7
DL Link: https://ncu.dl.sourceforge.net/project/openkore/OpenKore/2.0.7/openkore-2.0.7.zip

I'm not sure what i did but got this error afterwards...

Connecting to Character Server...
Connecting (127.0.0.1:6121)... couldn't connect: Unknown error (error code 10061)
Timeout on Character Server, reconnecting...
