### ISSUE TITLE
openkore for gepard shield protected

### ISSUE THREAD

**Issue by batobatoh** [OpenKore/openkore#412]
Good day all! 

i am new to open kore but i have once made my own connection to a private server like several years ago.
now, most servers are gepard protected, does anyone know how/where to start. i only have the IP and port as of now. i used the ro tools to get packets but it's protected. i'm talking about ragnarok PH URDR. http://urdr-ph.com

**Comment by Nyxvanthcal** [comment]
Openkore doesn't supports protected servers.

**Comment by batobatoh** [comment]
how sure are you? the last one i connected to had gepard shield too but i still managed to bot in their server's goldroom

**Comment by batobatoh** [comment]
help pls. no one?

**Comment by koodpzok** [comment]
how to fix seeing monsters as npcs ?

**Comment by hideman012** [comment]
@koodpzok can you shared for bot gepard

**Comment by xiaokeexiao** [comment]
> Openkore doesn't supports protected servers.
May i know what else bot program can be used on private server for RO?

**Comment by xiaokeexiao** [comment]
> Openkore doesn't supports protected servers.

May i know what else bot program can be used on private server for RO?
