### ISSUE TITLE
Error for offline boting kRO episode 15.2 server eAthena

### ISSUE THREAD

**Issue by Tepanyakigo** [OpenKore/openkore#413]
I do not understand why I cannot login using the latest version of OpenKore 2.0.7

OpenKore version what-will-become-2.1
Network state = 4
Network handler = Network::DirectConnection
SVN revision: unknown
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = {};

Stack trace:
Attempt to STORE non blessed reference (or not a reference)
Value:
$VAR1 = {};
 at src/Utils/BlessedRefTie.pm line 10
	Tie::BlessedRef::STORE('Tie::BlessedRef=SCALAR(0x5acd10c)', 'HASH(0x63ecb9c)') called at src/Network/Receive/kRO/Sakexe_0.pm line 3564
	Network::Receive::kRO::Sakexe_0::stat_info('Network::Receive::kRO::RagexeRE_2009_11_04a=HASH(0x60d555c)', 'HASH(0x63ecbcc)') called at src/Network/PacketParser.pm line 267
	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2009_11_04a=HASH(0x60d555c)', '\x{b0}\x{0}\x{19}\x{0}\x{f4}~\x{0}\x{0}', 'Network::Receive::kRO::RagexeRE_2009_11_04a=HASH(0x60d555c)') called at src/Network/Receive.pm line 137
	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2009_11_04a=HASH(0x60d555c)', '\x{b0}\x{0}\x{19}\x{0}\x{f4}~\x{0}\x{0}', 'Network::Receive::kRO::RagexeRE_2009_11_04a=HASH(0x60d555c)') called at src/Network/PacketParser.pm line 401
	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2009_11_04a=HASH(0x60d555c)', 'Network::MessageTokenizer=HASH(0x3852c7c)', 'Network::Receive::kRO::RagexeRE_2009_11_04a=HASH(0x60d555c)') called at src/functions.pl line 736
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x47598f4)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Any help is appreciated! Thanks!

**Comment by Razalka** [comment]
Whats your server config ?

**Comment by Tepanyakigo** [comment]
Uhm.... what do you mean by server config? I am sorry for my late reply.
