### ISSUE TITLE
Need help about Bypass-Antibot [PrivateServer]

### ISSUE THREAD

**Issue by wunsen747** [OpenKore/openkore#415]
at first i'm apologize for my language and my Eng is so bad i use translate.google (i'm from Thailand)

This is server i play : extra-ro.com and this server have antibot in game (Not Protection Program)

_Description_
when i atk 500 monster. Server sent a dialogue and want to offer the purchase a thing (Ex.Buy Apple 5 ea)
and random every time.

_This is some Console_ 
**Unknown #111918037: [ ตรวจจับมาโคร ]   <== is say Detect Macro
Unknown #111918037: เราขอตรวจสอบว่าท่านใช่บอทหรือไม่ <= is say want to know you a human?
Unknown #111918037: คุณมีเวลาซื้อ 60 วินาที. <== is say you have 60sec to buy it
Unknown #111918037: รบกวนซื้อ Carrot 9 ea <== is say please buy Carrot 9 ea
Unknown #111918037: คำเตือน :: ห้ามซื้อผิดและหลบหนี <== is say CAUTION don't buy wrong thing and Escape
Unknown #111918037: เมื่อคุณซื้อผิดเราจะเตะคุณออกจากเซิฟเวอร์ <== is say If you buy wrong thing You will be Disconnect
[กิล] === ซื้อ Carrot 9 ชิ้น ===  <== is say [Guild] === Buy Carrot 9 ea===
---------- Store List (Unknown #111918037) -----------
#  Name                    Type                  Price
0  Apple                   Usable Heal     4294967295z
1  Banana                  Usable Heal     4294967295z
2  Grape                   Usable Heal     4294967295z
3  Carrot                  Usable Heal     4294967295z
4  Ice Cream               Usable Heal     4294967295z
------------------------------------------------------
Unknown #111918037: สิ้นสุดการสนธนา <== is say End the conversation**

and than my Openkore is Disconnect and Re-login after that because openkore could not buy Carrot 
mean while GM is appear next by me and i got banned

_Question_
How can i fix it with Macro? please teach me or guide

**Comment by onepointfivem** [comment]
Is this an NPC talk, chat log,? Can you buy things with buy cmd?

**Comment by wunsen747** [comment]
@onepointfivem is a chat log and Buying pop-up 

and yes i can buy things with cmd but when i'm away i can't do that *sad*

**Comment by onepointfivem** [comment]
There you have it then. You can make an automacro trigger on hook, public msg ou even console msg, and make the appropriate buy.

**Comment by wunsen747** [comment]
@onepointfivem please send me a sample Command Macro i have no idea to make it

**Comment by wunsen747** [comment]
@onepointfivem this is some pic 
![image](https://cloud.githubusercontent.com/assets/25315846/22278226/46edf66a-e2f4-11e6-8a60-d68ba3cc7be8.png)

**Comment by sctnightcore** [comment]
> automacro antibot {
   console  /รบกวนซื้อ $item1\s[0-9]\sea/
   delay 2
   exclusive 1
   call {
      do buy $item1   
   }
}
is dont work

**Comment by sctnightcore** [comment]
https://pastebin.com/aUacrSJD

@needhelp some one

**Comment by moneyisgod** [comment]
console /\[.*\] (.*) (\d+)(\s+)?ea/i


do buy $.lastMatch2 $.lastMatch3

**Comment by koreguy** [comment]
anyone have gotten to fix this?
