### ISSUE TITLE
Weapon upgraded: Unknown

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [OpenKore/openkore#416]
i just refined using upgrade skill on iRO. Success or fail show the same message

> '0223' => ['upgrade_message', 'a4 v', [qw(type itemID)]],

handler use "itemID" while the Subroutines use "$args->{nameID}" 
we can use itemNameSimple rather than itemName for all type , and 'V' rather than 'a4'

**Comment by alisonrag** [comment]
is related to what?

**Comment by sctnightcore** [comment]
Maybe : #2105
