### ISSUE TITLE
Connecting to Character Server... [Unknown error (error code 10061)

### ISSUE THREAD

**Issue by masterplayer00000** [OpenKore/openkore#419]
Hi Guys!
I need your help in checking whats wrong with my configuration.
Connecting on **_Character Server_** is not pushing though....

Open to all suggestions.

RO Server: Valkyrie PH
GameGuard: Gepard

**_Here's the Logs:_**

Connecting to Account Server...
Connecting (###.###.##.###:####)... connected
Secure Login...
Sending encoded password...
Account Info:
Account ID: ########   ## ## ## ##
Sex:        Boy
Session ID: #########  ## ## ## ##
            #########  ## ## ## ##

Servers:
'#   Name                  Users  IP              Port
0   Valkyrie              990    127.0.0.1       6121

Closing connection to Account Server
Disconnecting (###.###.##.###:####)...disconnected
Server 0 selected
Connecting to Character Server...
Connecting (127.0.0.1:6121)... couldn't connect: Unknown error (error code 10061)

**Comment by alisonrag** [comment]
servers with gepard are not supported
