### ISSUE TITLE
Invalid map specified for lockmap

### ISSUE THREAD

**Issue by gospelkiru** [OpenKore/openkore#422]
![dewata](https://cloud.githubusercontent.com/assets/24469417/22438367/a86c7bac-e766-11e6-8bc4-99cdd2616369.jpg)
please help

**Comment by itsrachelfish** [comment]
What server are you playing on? If you're playing on a server with custom maps you need to generate field files: http://wiki.openkore.com/index.php/FLD_Creation_Guide

**Comment by alisonrag** [comment]
too many time without a asnwer of owner
