### ISSUE TITLE
All assertions should have explanations

### ISSUE THREAD

**Issue by farrainbow** [OpenKore/openkore#426]
Every call to `assert` should have the second argument with the string explaining what is asserted, in reasonable detail.

Example:
```diff
-assert(defined $actor->{ID}) if DEBUG;
+assert(defined $actor->{ID}, "Actor's ID must be defined when adding to ActorList") if DEBUG;
```

This way it's easier to understand what exactly went wrong, without digging in the code.

**Comment by moneyisgod** [comment]
Looks very good sir.
If possible the packet.Can it show it?
