### ISSUE TITLE
Cannot extract recvpackets for this server, can anyone help me?

### ISSUE THREAD

**Issue by raelemagy** [OpenKore/openkore#428]
So, it's a small server, a private, I tried PEEK and Packet Extractor V3, couldn't get anyting, also I would be thankfull if you could get the servertype, since the one that I get isn't listed on the openkore connectivity guide page, here is the [EXE FILE](http://www.mediafire.com/file/5u6mcegxrncyss0/private.exe).
Here's the complete [Patch for download](https://www.strumpro.com.br/download/patch.rar) for the server if you need. Thank's for you time.

**Comment by Nyxvanthcal** [comment]
Really ? 

Follow this guide 👍 
http://forums.openkore.com/viewtopic.php?f=36&t=207278

or this

http://forums.openkore.com/viewtopic.php?f=6&t=211637

And i have sure that you can extract it ! I've tried with PEEK and i've got successfully!
