### ISSUE TITLE
recvpackets extract problem..

### ISSUE THREAD

**Issue by dimvi** [OpenKore/openkore#429]
I tried to get recvpackets.txt from this client [Ragexe.exe](http://www.mediafire.com/file/zcpxr8o3tvl5usi/RagExe.exe) using PEEK

but its show error
ExtractPacketLen : Failed to find PACKET_CZ ENTER

tried another packet extractor ie (Packet Extractor v3), but no luck.

What should I do to generate recvpackets.txt from that client?

PS: That client from new official kRO [Frozen](http://frozensv.na.to/)

**Comment by Cozzie** [comment]
@OpenKore/project-leads Might want to help out someone that is playing on kRO

**Comment by chrislong93** [comment]
@Cozzie i cannot extract packet too can you please help check with the client ?  Its under 6mb but I have tried 3 different ways still no work.

Here is the link https://www.dropbox.com/s/cwio23g2mih269s/RokVNLauncher.exe?dl=0 

Thank you very much. THe server homepage is www.rokvn.com

**Comment by Razalka** [comment]
SkylorD guide.
http://forums.openkore.com/viewtopic.php?f=6&t=211637
