### ISSUE TITLE
New to bot program, confused, and hoping to find one that works for gravindo

### ISSUE THREAD

**Issue by namethatisnottaken** [OpenKore/openkore#432]
Hi,

First of all sorry for the obvious newbie question but i am not really sure that i understand how everything works on this forum.

Anyway, if you can help me i am looking for a ragnarok bot that works for the new Gravindo RO Indonesia, please help to give a clue or link on how to do it, how it works, or if it is even possible to do it.

Many Thanks for the help.

**Comment by rmfrmf** [comment]
![bot1](https://cloud.githubusercontent.com/assets/25648156/22758894/74c7c9b0-ee8b-11e6-812a-691570ddb97d.png)
![bot2](https://cloud.githubusercontent.com/assets/25648156/22758904/7c436f00-ee8b-11e6-9c1c-67f160860bfd.png)
i just download new OK, but it cant works on new server Gravindo IdRO.
I tried JCV RO TOOLs but it says "The executable file might be compressed/protected".
we need help here.

**Comment by 528custom** [comment]
you can't use JCV RO Tools since the exe is more than 6MB. It looks like the exe is packed using UPX.

and it's "Packet Tokenizer: Unknown Switch 16CF". help?

**Comment by TwinerCRIME** [comment]
same problem.
any help?

**Comment by RaynV** [comment]
Anyone know server setting for idro?

![](http://i.imgur.com/KhrLuhI.png)

**Comment by BigGolem** [comment]
im no different, here's some SS
[URL=http://www.imagebam.com/image/f81dd4533054155][IMG]http://thumbnails117.imagebam.com/53306/f81dd4533054155.jpg[/IMG][/URL]

**Comment by joegubrak** [comment]
same to me.. i got 6B94

**Comment by joegubrak** [comment]
but in the other forum some one alredy solve all problen and run his bot. do anyone  know?

**Comment by drone123** [comment]
please add me drone123 i need that program...

**Comment by chrislong93** [comment]
Please help.
I have tried using different methods of packet extraction like **_JVC , Packet Extractor v3 , PEEK_**... but all in vain.

JVC and Packet Extractor v3 both said "**_search for packet len map failed"_** , and when I tried using PEEK as instruction (Browse raglauncher.exe , click Generate) it does not show anything. The Output folder does not show anything related as in instruction.

I would like to ask for your help extracting the recvpackets.txt for this client. Its under 6mb, and when I used PE view , its timedate is around 2014

Here is the link https://www.dropbox.com/s/cwio23g2mih269s/RokVNLauncher.exe?dl=0

Thank you very much. The server homepage is www.rokvn.com.

**Comment by drone123** [comment]
Are u indonesian?
Pada 8 Mar 2017 16.37, "chrislong93" <notifications@github.com> menulis:
