### ISSUE TITLE
Cannot Equip Using Consoles

### ISSUE THREAD

**Issue by deca2708** [OpenKore/openkore#441]
I always got disconnected whenever I equip an item using console "eq 0", but not manually by clicking it on my xkore. My Openkore is newest, this has been an issue from old days ago and already fixed. But now this is another new problem with indonesian ragnarok new server, any help how?

**Comment by iqbalpetet** [comment]
did you already able to connect the openkore to idRo?

**Comment by deca2708** [comment]
udah, bayar orang bro, tapi itu juga botnya di limit 2 char doang.

**Comment by iqbalpetet** [comment]
@deca2708 japri di discord bro? gokillzz#6590

**Comment by deca2708** [comment]
solved thanks. wrong send packet. please change it on github default download please.

**Comment by itsrachelfish** [comment]
@deca2708 if you have a working version of openkore please make a fork of the project and submit a pull request :+1:

**Comment by deca2708** [comment]
on idro.pm send_equip A9 is changed to 0998

**Comment by starfall99** [comment]
@deca2708 kalo terjangkau ane jg minat
discord lhammerz #2561

**Comment by andi2204** [comment]
@deca2708 can you tell me the seller that can solve openkore for idro?
