### ISSUE TITLE
Cart problem on IRO

### ISSUE THREAD

**Issue by Xianzz** [OpenKore/openkore#443]
Getting a "you do not have a cart" on a merchant with a cart when typing cart command

**Comment by bunnyy00** [comment]
i have got the same problem,  when i type in command 'cart', it sayd you have no card ( instead of 'card')

**Comment by allanon** [comment]
On what server?

**Comment by Xianzz** [comment]
iro thor server

**Comment by bunnyy00** [comment]
Mine one is iRo Chaos

**Comment by allanon** [comment]
This is fixed by pull request #440 .
