### ISSUE TITLE
misc.pm error

### ISSUE THREAD

**Issue by deca2708** [OpenKore/openkore#444]
idro error after storage.

"Can't locate object method "storage" via package "Actor::You" at src /Misc.pm line 3250

need help, what to do?

**Comment by deca2708** [comment]
fyi this is newest openkore from here

**Comment by jegrek** [comment]
send me ur revpacket

**Comment by deca2708** [comment]
recv packet straight from github, its not modified

**Comment by jegrek** [comment]
u said idro ?

**Comment by deca2708** [comment]
ia bro, bro cm mau cari tau recvpacket kan buat jebol. haha. ga diubah kok.

fyi it's solved, i use the misc.pm from collectskin and just add the Storage_password 023B on the idro.pm(old problem, years ago already solved), but it seems that the **latest** misc.pm on github and is having an error I stated.

**Comment by jegrek** [comment]
seriusan bro ? pake revpacket yang lama ? gw masih nyangkut euy

sent lah

**Comment by deca2708** [comment]
gw bayar bro, gw ga nawarin, tapi kalo lu mau bayar juga add gw aja. deca#9299
