### ISSUE TITLE
[Private Server]How to cut a received packet into two when the server combines two packets into one?

### ISSUE THREAD

**Issue by simonpunk** [OpenKore/openkore#446]
Few days ago I managed to run OK on my private server, but now I got another problem. 
I am not sure but seems the server combines the storage packet into just one packet, what I found in that packet it sends to me contains '0995' followed by '0996' in just one packet, so, if I am right, it makes OK to overwrite the info of stackable items with nonstackable items. 

For example, in my storage: 
I have 1 white potion, 1 red potion, 1 orange potion  --> which all are stackable items.
I have 1 normal weapon --> which is nonstackable items.

when I open the storage using wxstart, it shows me having 1 normal weapon, 1 red potion, 1 orange potion, which likely means my first stackable item is overwrited by the nonstackable items, and what's more is that I can only get the nonstackble items from the storage.

So, if my assumption was right, how could I do the trick to make OK auto-separate into two packets when it reads '0995'???

Any suggestions would be highly appreciated!! Thank you.
my packet looks like this: 

`95:09:84:01:a8:6b:ab:c4:aa:ba:ac:4b:a4:d1:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:00:f6:01:00:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:02:00:f7:01:00:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:03:00:f8:01:00:19:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:04:00:fa:01:00:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:05:00:fe:01:00:e0:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:06:00:06:02:00:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:07:00:42:02:00:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:08:00:85:02:02:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:09:00:90:02:02:09:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:0a:00:ca:02:03:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:0b:00:eb:02:03:a8:05:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:0c:00:ec:02:03:27:05:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:0f:00:2d:10:06:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:10:00:5e:10:06:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:11:00:6d:10:06:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:
95:09:1c:00:a8:6b:ab:c4:aa:ba:ac:4b:a4:d1:00:00:00:00:00:00:00:00:00:00:00:00:00:00:96:09:5a:00:a8:6b:ab:c4:aa:ba:ac:4b:a4:d1:00:00:00:00:00:00:00:00:00:00:00:00:00:00:0d:00:61:09:04:40:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:0e:00:c5:09:04:04:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:96:09:1c:00:a8:6b:ab:c4:aa:ba:ac:4b:a4:d1:00:00:00:00:00:00:00:00:00:00:00:00:00:00:f2:00:11:00:58:02:b3:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:ff`

Any suggestions would be highly appreciated!! Thank you.

**Comment by c4c1n6kr3m1** [comment]
did u see 84:01 ? that's the length
try debug

**Comment by jaiqi0313** [comment]
in Receive.pm
find **$char->storage->clear;** and comment out

because you can see openkore get two 0995 packet
and second 0995 packet like nothing ( i dont know this packet mean )
if you no comment out **$char->storage->clear;** this line
that will be rewrite first packet msg  that it you cant see stackable items 

<code> 
sub storage_items_stackable {
	my ($self, $args) = @_;

	#$char->storage->clear;

	$self->_items_list({
		class => 'Actor::Item',
		hook => 'packet_storage',
		debug_str => 'Stackable Storage Item',
		items => [$self->parse_items_stackable($args)],
		getter => sub { $char->storage->getByServerIndex($_[0]{index}) },
		adder => sub { $char->storage->add($_[0]) },
		callback => sub {
			my ($local_item) = @_;

			$local_item->{amount} = $local_item->{amount} & ~0x80000000;
		},
	});

	$storageTitle = $args->{title} ? $args->{title} : undef;
}
<code/>

**Comment by moneyisgod** [comment]
Yeah you are absolutely right.
Wait for fixes

**Comment by alisonrag** [comment]
the len in packet is because of this. try to parse the packet 2 times

**Comment by Nipodemos** [comment]
closing since this is not an issue.
