### ISSUE TITLE
[Private Server] Clan system

### ISSUE THREAD

**Issue by magimagica** [OpenKore/openkore#449]
Test client: 2014-10-22bRagexe
Test Server: Localhost
Hash: https://github.com/OpenKore/openkore/commit/84e673d2afa09bfdafad28993f002298c617af73

I got this message when I join a clan

Packet Parser: Unknown switch: 098A
Packet Parser: Unknown switch: 0988
You are now: EFST_CLAN_INFO
You are now: EFST_SWORDCLAN

**Comment by Cozzie** [comment]
Openkore does not support private servers out of the box unfortunately.

**Comment by itsrachelfish** [comment]
@Cozzie There is an open pull request to add support for this servertype - https://github.com/OpenKore/openkore/pull/275

I think it's fine to leave this open because this server type is actually supported.

**Comment by m3kgin3er** [comment]
It's very strange 'cause not in rAthena and Cronus have this struct. How to proceed with these errors ?

**Comment by m3kgin3er** [comment]
https://rathena.org/board/topic/105463-clan-system/

**Comment by Fadreus** [comment]
#1935
