### ISSUE TITLE
One poseidon server for many bots.

### ISSUE THREAD

**Issue by arthurm93** [OpenKore/openkore#454]
Bot #1
Config.txt
poseidonServer 192.168.56.102
poseidonPort 24392
Poseidon.txt
ragnarokserver_ip=192.168.56.102
ragnarokserver_port=6902
queryserver_ip=192.168.56.102
queryserver_port=24392
Bot #2
Config.txt
poseidonServer 192.168.56.102
poseidonPort 24392

Ok, when bot#1 asks ragexe answers just fine then when bot#2 asks ragexe answers bot#2 but bot#1 gets disconnected, bot#1 connects again and asks but bot#2 disconnects.

Is there a fix? I mean it should work since ragexe can answer the queries and poseidon acknowledges more than 1 bot.

**Comment by lututui** [comment]
There's not. Connecting multiple bots to a single poseidon/ragnarok server pair will cause GameGuard to answer the query incorrectly for all of them.
