### ISSUE TITLE
(need Help) Stuck after get delphine key, server denied connection

### ISSUE THREAD

**Issue by billybud250** [OpenKore/openkore#457]
![untitled](https://cloud.githubusercontent.com/assets/26062971/23363050/3cab532c-fd2b-11e6-9319-9fbb595fe167.png)
help anyone i got stuck here after getting delphine key

thanks before

**Comment by walkietalkie89** [comment]
Base on https://github.com/OpenKore/openkore/issues/461

> The secure_key is encrypted (The header packet is 6B94, encrypted too).
> Encrypted method is using XOR Cipher.
> Flow gameguard:
>  Server send encrypted key -> Intercepted by mfc90g.dll, decrypt the key to Client
> Example:
> ```
>  HH = Header Packet
>  LL = Length Packet
>  KK = Packet Data
>  ------------HH HH LL LL PP PP PP PP PP PP PP PP PP PP PP PP PP PP PP PP
>  -----------------------------------------------------------------------
>  TCP sniff : 94 6B 62 59 08 5E A2 E8 A8 42 CE 10 BF 9C 50 57 28 CC 84 13 (Encrypted)
>  ----------------------- 4C 6E 72 5D 40 62 7E 51 44 66 7A 55 58 7A 66 49 (They using XOR gate to decrypt)
>  WPE sniff : DC 01 14 00 44 30 D0 B5 E8 20 B0 41 FB FA 2A 02 70 B6 E2 5A (Decrypted by mfc90.dll)
> ```
>  -----------------------------------------------------------------------
>  
>  
> Add 6B94 20 20 0 in recvpackets.txt (since header packet is encrypted)
> Add some global variable and some handler in src/Network/Receive/idRO.pm
> ```
>  use Globals qw(%config $messageSender %timeout $secureLoginKey);
>  '6B94' => ['secure_login_key', 'x2 a*', [qw(secure_key)]],
> ```
> Create custom sub to secure_login_key, add this
> ```
>  sub secure_login_key {
> 	 my ($self, $args) = @_;
> 	 my $deckey = "4C6E725D40627E5144667A55587A6649";
> 	 $secureLoginKey = $args->{secure_key} ^ pack("H*", $deckey);
> 	 debug sprintf("Secure login key: %s\n", getHex($secureLoginKey)), 'connection';
>  }
> ```

*Edited
@Cozzie @lututui @itsrachelfish  or other can u help me? just curious about botting on this server. any other winsock packet capturer than wpe/rpe?
i hate to comment on https://github.com/OpenKore/openkore/issues/460 because too many `u know`.

*Update 2017-03-07
Unable to capture recv when login (i'm using wpe/rpe).
i think gameguard intercept recv function and return no data from it (just assumption).

`opensource is always open`

**Comment by imamfirmansyah** [comment]
@walkietalkie89 Can you help me to give little bit clue to run wpe concurrently with rageaxe.exe?
I have followed this instruction using CC Proxy and Proxifier --  https://progamercity.net/aika-hack/2761-how-using-wpe-without-attach-aika-bypassing-gg.html
but de respon totally similar with smsniff application, I can't find DC 01 header like
`WPE sniff : DC 01 14 00 44 30 D0 B5 E8 20 B0 41 FB FA 2A 02 70 B6 E2 5A (Decrypted by mfc90.dll)`

**Comment by m3kgin3er** [comment]
OllyDbg 2.0 + OllySocketTrace

**Comment by alisonrag** [comment]
use #634
