### ISSUE TITLE
Conection issue (bRO)

### ISSUE THREAD

**Issue by Ingway** [OpenKore/openkore#46]
In today's update, the brazilian dristribution company LUG change the protection from ragexe, wich unable all standard users (without programming knowledge) to use openkore. Usually, after the weekly update, all we had to do is to use PackerBreaker on ragexe, which generated an alternative ragexe which we applyed the following perl script: 

[extrator.pl.txt](https://github.com/OpenKore/openkore/files/163323/extrator.pl.txt)

After that, we receive the src and tables folder, So all we need to do is paste then in openkore folder. But after this update, when we run openkore after doing this process, we receive the following error:

![Screenshot of error](http://s15.postimg.org/68htt4tl7/bot_error.jpg)

I'm not sure If I was supposed to ask this here, but I could't find the directions anywhere else. I'm also interested in perl programming (i'm still crawling on the field), and If there are recomendations to where learn more about perl and openkore I would apreciate very much. I have an deep desire to help the community to grow. Thank you very much!

**Comment by itsrachelfish** [comment]
You may want to get in contact with the people on the OpenKore Brasil forums: http://openkorebrasil.org/

They might know more about this issue specifically.

If you find a solution please let us know and we will incorporate it into the project ASAP.

**Comment by emsjustin** [comment]
Dude, They just change the keys... Please search in openkorebrasil.org

**Comment by Ingway** [comment]
Well, in the brazilian forum they reported that this extractor doesn't work anymore. They released the keys for the public. But what troubles me is How to do get those keys? Some ppl mention a debug process, but still information about this process is very scarce and we rely on very few people that know the process. This is known to be very unhealthy to the openkore community, because as then lose interest in openkore things get very complicated... If I could anyway learn about this, I would be very happy to share with then how to do that (in a very didatic way).

**Comment by emsjustin** [comment]
Old internacional forum had everything. The old extractor works fine, just need change keys. Use IDA or OllyDgb. In my opinion this isn' t the place to discuss this... Brazil had a forum to fix it...

**Comment by itsrachelfish** [comment]
I'd love to have more information on this available on the official OpenKore wiki. I don't speak Portuguese (yet!), but I'd be happy to help write a wiki article with detailed instructions. @emsjustin Let's talk on IRC some time?

**Comment by emsjustin** [comment]
Yeah, sure. I'd love to share everything I know

**Comment by Ingway** [comment]
itsrachelfish, that would solve our issue, the brazilian community would appreciate that!

**Comment by lututui** [comment]
> the brazilian dristribution company LUG change the protection from ragexe

They did not. Ragexe.exe (bRO) still uses MPress v2.19. The KMA keys were just shifted arround.

**Comment by larryxyopen** [comment]
Please Help me. The guys on openkore brasil forum don't want to help us, they just want to get money now. They are asking for money in exchange of remote control poseidon. Please show me how to update this by myself.

**Comment by marcelothebuilder** [comment]
@larryxyopen you don't need to buy it in order to use openkore. If I'm not wrong, they are providing a plugin that allows you to connect to bRO, and with XKore 2 you can bypass GameGuard checks.

**Comment by flacrasec** [comment]
still the miniposeidon wich is available there is still functional using the "gambiarra" mode.

**Comment by itsrachelfish** [comment]
Can someone here from bRO to test @lututui's changes?

https://github.com/OpenKore/openkore/pull/168

Thank you!

**Comment by itsrachelfish** [comment]
This has been fixed as of #168 :+1:
