### ISSUE TITLE
idRO packet tokenizer unknown switch:6b94

### ISSUE THREAD

**Issue by kimkimwalker** [OpenKore/openkore#465]
![2037319_20170302012103](https://cloud.githubusercontent.com/assets/26133687/23496675/f6fa1330-ff51-11e6-9863-3a5207d68bc5.png)

This packet tokenizer unknown switch 6b94 issue appear for idRO new Chaos after the server update.
help me please, can't bot

**Comment by RaynV** [comment]
Use sanqiba's way to bot

**Comment by scythewinder** [comment]
@RaynV maksudnya? Sanqiba's?

**Comment by kimkimwalker** [comment]
@RaynV what is sanqiba way?????? i don't understand

**Comment by dalvian** [comment]
J>Jasa BOT Testi bisa di DM , minat dm saya / email ke wohoo1237@gmail.com , bot per hari / per minggu  , masalah harga di bahas lewat dm

**Comment by kimkimwalker** [comment]
@dalvian sorry ni gan, jualan di kaskus aja jgn disini

**Comment by scythewinder** [comment]
@dalvian yang tai yah kayak begini. Hasil orang lain yg ngoprek, kayk elu cuma terima hibahan script trus nguangin buat keuntungan sendiri.

**Comment by kimkimwalker** [comment]
orang luar baca , bikin malu orang sini tau gan

**Comment by shinjiinue** [comment]
Makanya di share aja semua biar orang kaya gitu ngga ada. Hehehe.

**Comment by RagnarokUSer001** [comment]
@RaynV i get disconnected when i changed my equipment . can u help me?

**Comment by totalyn00b** [comment]
[quote]@RaynV i get disconnected when i changed my equipment . can u help me?[/quote]
@RagnarokUSer001 can u give me your openkore sir please :( im totalynoob

**Comment by vaniaAR** [comment]
Can someone give me tutorial for your openkore? I'm totally newbie

**Comment by mboodz** [comment]
I already change setting. but alwys wrong pasword. can you help me dude? add me in discord mboodz#7505 thank you

**Comment by RendhyOkta** [comment]
Daripada dijual mending share gratis. Copas ke folder openkore
https://ufile.io/fd8131

![image](https://cloud.githubusercontent.com/assets/26168169/23556559/f9d1a476-0067-11e7-83eb-61a7d6f22da0.png)

**Comment by AngDrew** [comment]
@RendhyOkta nyebar virus!!!

**Comment by drone123** [comment]
virus apaan nih?

**Comment by AngDrew** [comment]
@drone123 ntah pokoknya ga bisa di run avast ku detect itu virus.. ada installer dan ada wxstart dan start ga jelas installer nya exe.. ati"

**Comment by deca2708** [comment]
@ragnarokuser001 liat post an gw di github issues, ada packet yang harus diubah

**Comment by drone123** [comment]
saya udah berhasil menjebolnya dengan duit. wkwkwkwk. ada yg jual

**Comment by itsrachelfish** [comment]
Please stop promoting backdoored software. Selling copies of OpenKore without providing the source code is a violation of the OpenKore license.
