### ISSUE TITLE
Assertion failed! src/deps/Carp/Assert.pm

### ISSUE THREAD

**Issue by Mortimal** [OpenKore/openkore#469]
After fly wings.

> OpenKore version what-will-become-2.1
> Network state = 5
> Network handler = Network::DirectConnection
> SVN revision: unknown
> Loaded plugins:
>   plugins/alertsound.pl (alertsound; description: plays sounds on certain events)
>   plugins/bulkbuyer.pl (bulkbuyer; description: Buying bulk from the same npc)
>   plugins/macro/macro.pl (macro; description: allows usage of macros)
>   plugins/macroinclude.pl (macroinclude; description: On-Off !include in macros.txt. manticora)
>   plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
>   plugins/xconf.pl (xConf; description: commands for change items_control, mon_control, pickupitems)
> 
> Error message:
> Assertion failed!
>  at F:/Static/Openkore/Bot/TristanRO/src/deps/Carp/Assert.pm line 271
> 	Carp::Assert::assert('') called at src/InventoryList.pm line 240
> 	InventoryList::remove('InventoryList::Inventory=HASH(0x67d9c5c)', 'HASH(0x6b0115c)') called at src/Misc.pm line 1809
> 	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 1696
> 	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', 'HASH(0x68a5ae4)') called at src/Network/PacketParser.pm line 268
> 	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', '\x{fa}\x{7}\x{1}\x{0}\x{19}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/Network/Receive.pm line 137
> 	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', '\x{fa}\x{7}\x{1}\x{0}\x{19}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/Network/PacketParser.pm line 402
> 	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', 'Network::MessageTokenizer=HASH(0x3433e94)', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/functions.pl line 736
> 	main::mainLoop_initialized() called at src/functions.pl line 75
> 	main::mainLoop() called at src/Interface.pm line 75
> 	Interface::mainLoop('Interface::Console::Win32=HASH(0x436a884)') called at openkore.pl line 97
> 	main::__start() called at start.pl line 136
> 
> Stack trace:
> Assertion failed!
>  at F:/Static/Openkore/Bot/TristanRO/src/deps/Carp/Assert.pm line 271
> 	Carp::Assert::assert('') called at src/InventoryList.pm line 240
> 	InventoryList::remove('InventoryList::Inventory=HASH(0x67d9c5c)', 'HASH(0x6b0115c)') called at src/Misc.pm line 1809
> 	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 1696
> 	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', 'HASH(0x68a5ae4)') called at src/Network/PacketParser.pm line 268
> 	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', '\x{fa}\x{7}\x{1}\x{0}\x{19}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/Network/Receive.pm line 137
> 	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', '\x{fa}\x{7}\x{1}\x{0}\x{19}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/Network/PacketParser.pm line 402
> 	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', 'Network::MessageTokenizer=HASH(0x3433e94)', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/functions.pl line 736
> 	main::mainLoop_initialized() called at src/functions.pl line 75
> 	main::mainLoop() called at src/Interface.pm line 75
> 	Interface::mainLoop('Interface::Console::Win32=HASH(0x436a884)') called at openkore.pl line 97
> 	main::__start() called at start.pl line 136
>  at F:/Static/Openkore/Bot/TristanRO/src/deps/Carp/Assert.pm line 271
> 	Carp::Assert::assert('') called at src/InventoryList.pm line 240
> 	InventoryList::remove('InventoryList::Inventory=HASH(0x67d9c5c)', 'HASH(0x6b0115c)') called at src/Misc.pm line 1809
> 	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 1696
> 	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', 'HASH(0x68a5ae4)') called at src/Network/PacketParser.pm line 268
> 	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', '\x{fa}\x{7}\x{1}\x{0}\x{19}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/Network/Receive.pm line 137
> 	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', '\x{fa}\x{7}\x{1}\x{0}\x{19}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/Network/PacketParser.pm line 402
> 	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)', 'Network::MessageTokenizer=HASH(0x3433e94)', 'Network::Receive::kRO::RagexeRE_2013_08_07a=HASH(0x4728aa4)') called at src/functions.pl line 736
> 	main::mainLoop_initialized() called at src/functions.pl line 75
> 	main::mainLoop() called at src/Interface.pm line 75
> 	Interface::mainLoop('Interface::Console::Win32=HASH(0x436a884)') called at openkore.pl line 97
> 	main::__start() called at start.pl line 136

Also with some combination of items getting incorrect Arrows from storage or no seen them at all. Storage command shows them correct!

XKore 2 mode.

**Comment by SabadyshynV** [comment]
Not only in xkore 2, xkore 0 also

**Comment by Razalka** [comment]
still happened.
Assertion failed!

>  at C:/Rakki Openkore/openkore-rakkiRO-at-least-master/src/deps/Carp/Assert.pm line 271
> 	Carp::Assert::assert('') called at src/InventoryList.pm line 240
> 	InventoryList::remove('InventoryList::Inventory=HASH(0x5ea4d74)', 'HASH(0x61239fc)') called at src/Misc.pm line 1828
> 	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 1682
> 	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', 'HASH(0x6633d7c)') called at src/Network/PacketParser.pm line 267
> 	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', '\x{fa}\x{7}\x{1}\x{0}\x{4}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/Network/Receive.pm line 137
> 	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', '\x{fa}\x{7}\x{1}\x{0}\x{4}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/Network/PacketParser.pm line 401
> 	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', 'Network::MessageTokenizer=HASH(0x35fcbb4)', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/functions.pl line 737
> 	main::mainLoop_initialized() called at src/functions.pl line 75
> 	main::mainLoop() called at src/Interface.pm line 75
> 	Interface::mainLoop('Interface::Console::Win32=HASH(0x44f9e2c)') called at openkore.pl line 97
> 	main::__start() called at start.pl line 136
> 
> Stack trace:
> Assertion failed!
>  at C:/Rakki Openkore/openkore-rakkiRO-at-least-master/src/deps/Carp/Assert.pm line 271
> 	Carp::Assert::assert('') called at src/InventoryList.pm line 240
> 	InventoryList::remove('InventoryList::Inventory=HASH(0x5ea4d74)', 'HASH(0x61239fc)') called at src/Misc.pm line 1828
> 	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 1682
> 	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', 'HASH(0x6633d7c)') called at src/Network/PacketParser.pm line 267
> 	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', '\x{fa}\x{7}\x{1}\x{0}\x{4}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/Network/Receive.pm line 137
> 	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', '\x{fa}\x{7}\x{1}\x{0}\x{4}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/Network/PacketParser.pm line 401
> 	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', 'Network::MessageTokenizer=HASH(0x35fcbb4)', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/functions.pl line 737
> 	main::mainLoop_initialized() called at src/functions.pl line 75
> 	main::mainLoop() called at src/Interface.pm line 75
> 	Interface::mainLoop('Interface::Console::Win32=HASH(0x44f9e2c)') called at openkore.pl line 97
> 	main::__start() called at start.pl line 136
>  at C:/Rakki Openkore/openkore-rakkiRO-at-least-master/src/deps/Carp/Assert.pm line 271
> 	Carp::Assert::assert('') called at src/InventoryList.pm line 240
> 	InventoryList::remove('InventoryList::Inventory=HASH(0x5ea4d74)', 'HASH(0x61239fc)') called at src/Misc.pm line 1828
> 	Misc::inventoryItemRemoved(undef, 1) called at src/Network/Receive.pm line 1682
> 	Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', 'HASH(0x6633d7c)') called at src/Network/PacketParser.pm line 267
> 	Network::PacketParser::parse('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', '\x{fa}\x{7}\x{1}\x{0}\x{4}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/Network/Receive.pm line 137
> 	Network::Receive::parse('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', '\x{fa}\x{7}\x{1}\x{0}\x{4}\x{0}\x{1}\x{0}', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/Network/PacketParser.pm line 401
> 	Network::PacketParser::process('Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)', 'Network::MessageTokenizer=HASH(0x35fcbb4)', 'Network::Receive::kRO::RagexeRE_2015_11_04a=HASH(0x6626564)') called at src/functions.pl line 737
> 	main::mainLoop_initialized() called at src/functions.pl line 75
> 	main::mainLoop() called at src/Interface.pm line 75
> 	Interface::mainLoop('Interface::Console::Win32=HASH(0x44f9e2c)') called at openkore.pl line 97
> 	main::__start() called at start.pl line 136

**Comment by Henrybk** [comment]
Which server are you playing on, which version of openkore are you using?

**Comment by Razalka** [comment]
@Henrybk 
Openkore type : OpenKore what-will-become-2.1
Server : Rakki-RO (103.253.145.223/Ro.Rakki.org)
i used fork from @m3kgin3er and from this issue #497

**Comment by m3kgin3er** [comment]
But the error occurs in both sT, 2013 and 2015. Maybe it haven't nothing in common with recent changes.
I rly don't understand these logs . :P

**Comment by Razalka** [comment]
@m3kgin3er 
Email sent.

**Comment by lututui** [comment]
This happens when something gets removed from the inventory and we're not expecting it/not notified about it. I've never seen it happen on official servers, but it is quite common in some kRO serverTypes/private servers. I have run into it when using fly/butterfly wings (as @m3kgin3er (Skylord) mentioned), specially with "emergency" teleports but I don't know why

**Comment by m3kgin3er** [comment]
Oh yeah i never see it in official. ^^ good

Well so its good to read rAthena source. uaheuaheua

**Comment by m3kgin3er** [comment]
Can't reproduce this error.
![image](https://cloud.githubusercontent.com/assets/12580473/25559875/d1affb02-2d1a-11e7-9f8b-e06a282119e9.png)


AnkRO and RakkiRO tested.

**Comment by Slipxxliose** [comment]
@lututui : Thankz. After so much time the difference is between sakexe and ragexe. 
Inventory non stackable and another type of packets was not defined inside Sakexe.
Was already defined in Ragexe. Then i just needed to copy and paste.

I have the sure it will never occur anymore with priv.

**Comment by moneyisgod** [comment]
Finally.

Network::Receive::inventory_item_removed('Network::Receive::kRO::RagexeRE_2013_08_07a

Item is not being parsed.

**Comment by alisonrag** [comment]
continue in #2458
