### ISSUE TITLE
Duplicate information of items in storage (iRO)

### ISSUE THREAD

**Issue by CatInABush** [OpenKore/openkore#473]
Can anyone help with this bug? This bug just appeared some time ago and has been there since then.
When I open the storage for the first time, the storage looks something like this:

 0 Phracon x 98
 1 Steamed Tongue x 3
 2 Dragon Breath Cocktail x 3
 3 Hwergelmir's Tonic x 3
 4 Stew Of Immortality x 3
 5 Steamed Scorpion x 3
 6 Cooked Nine Tail's Tails x 3

Then, when I open the storage for the second time, the storage looks something like this:

 0 Phracon x 98
 1 Steamed Tongue x 3
 2 Dragon Breath Cocktail x 3
 3 Hwergelmir's Tonic x 3
 4 Stew Of Immortality x 3
 5 Steamed Scorpion x 3
 6 Cooked Nine Tail's Tails x 3
 7 Phracon x 98
 8 Steamed Tongue x 3
 9 Dragon Breath Cocktail x 3
10 Hwergelmir's Tonic x 3
11 Stew Of Immortality x 3
12 Steamed Scorpion x 3
13 Cooked Nine Tail's Tails x 3

After that, the items just keep adding to the end of the storage list, and this makes my macros work improperly because the conditions to trigger my macros rely on the number of certain kind of items in the storage. For example, after the first time opening my storage, the number of Phracons in the storage are 98, which is correct. But after the second time opening my storage, the number of Phracons in the storage are 98 + 98 = 196, which is incorrect.

Your help might benefit those who share the same problem as mine. Thank you!

**Comment by lututui** [comment]
This was fixed by #471. Please update your working copy.
