### ISSUE TITLE
Encrypted or Custom Packet Keys

### ISSUE THREAD

**Issue by Razalka** [OpenKore/openkore#474]
Is there any method to sniff or get the custom packet key ?
They change the default.
Or anything can explain the picture ?
Thanks 

 ![img_20170306_171333](https://cloud.githubusercontent.com/assets/25100730/23607602/fe9dd02e-0297-11e7-8d8e-244f0d01bf52.jpg)

**Comment by Nyxvanthcal** [comment]
First check if your server has the encryption enabled by default !
