### ISSUE TITLE
Problem extracting recvpackets.txt, new client.

### ISSUE THREAD

**Issue by chrislong93** [OpenKore/openkore#478]
Hi there guys,

I have tried using different methods of packet extraction like **JVC , Packet Extractor v3 , PEEK**... but **_all in vain._** 

JVC and Packet Extractor v3 both said "**_search for packet len map failed_**" , and when I tried using PEEK as instruction (Browse raglauncher.exe , click Generate) it does not show anything. The Output folder does not show anything related as in instruction.

I would like to ask for your help extracting the recvpackets.txt for this client. Its under 6mb, but when I used PE view , its timedate is around 2014

Here is the link https://www.dropbox.com/s/cwio23g2mih269s/RokVNLauncher.exe?dl=0

Thank you very much. The server homepage is www.rokvn.com.  

ChrisLong.

**Comment by chrislong93** [comment]
Anyone? Please help.

Link to download the 3 exe files. Only the Launcher exe is used to start the game, but cant extract lengths from it.

https://www.dropbox.com/s/ahv5l6pkixj2mcc/ROKVN%203%20exe.7z?dl=0

**Comment by chrislong93** [comment]
Please help guys. Still stuck at Timeout on Account Server :(  huhu

**Comment by m3kgin3er** [comment]
http://forums.openkore.com/viewtopic.php?f=6&t=211637

**Comment by alisonrag** [comment]
to many time without answer
