### ISSUE TITLE
idRO packet tokenizer unknown switch: A9A7

### ISSUE THREAD

**Issue by YusufFT09** [OpenKore/openkore#481]
Please Help me To Resolve this problem
![picture1](https://cloud.githubusercontent.com/assets/26310245/23767993/1bc2b5be-053d-11e7-9f79-597e754888fa.png)

**Comment by garrytabuty46** [comment]
Just read all post at #460 
Read all clue there.
So simple.

**Comment by YusufFT09** [comment]
@garrytabuty46 Its secure code diffrent to me .. its FCA6 , me A9A7 .. can you describe to me which one to solve this problem ? Please give me the way .

**Comment by c4c1n6kr3m1** [comment]
read that link!!!!!!!!!!!!!!!!!!!!
close this issue please
