### ISSUE TITLE
Bot Stop Moving at Payon 144, 85 when doing auto storage

### ISSUE THREAD

**Issue by litroendemic** [OpenKore/openkore#482]
so right now im botting in idRO server which use old payon map, i already replace the map (payon.dist) in fields folder with the old payon and rename it.

the problem is, whenever the autostorage/autobuy/autosell triggered from the config and bot calculate route from the hunting place to the npc, when the bot arrive at payon the bot not going the npc coordinate. It stuck at Payon 144, 85.

I tried to manual command to move to another coordinate, then the bot can continue do the autostorage/autobuy/autosell automatically with no problem.

Is there anyway to fix the route that bot takes to get to the npc ? i've already to tried using macro, but because im not familiar with macro, i still cant fix this problem.

here is my macro

> automacro check{
> 	location payon 144 85, payon 144 84, payon 144 86, payon 145 85, payon 145 84, payon 145 86
> 	timeout 15
> 	call move
> }
> 
> macro move {
> 	log i'm on payon
> 	do move payon 88 113
> }

what i want is, after i command my bot to move to payon 88 113, i want the bot the do the automatic check on autostorage/autosell/autobuy according to the config ive set

> sellAuto 1
> sellAuto_npc payon 79 124
> sellAuto_standpoint
> sellAuto_distance 8
> sellAuto_npc_steps s e

Thankyou if you can give me the solution whether to modify the route, or using macro.

**Comment by yosua11090** [comment]
so you saying, that you still can botting after maintenance?

**Comment by ivanhadiputra** [comment]
@yosua11090 nope, but still i want to solve this problem. Any suggestion?

**Comment by deca2708** [comment]
berat bro berapa? apa uda sesuai config untuk store/sell?

automacro check{
location payon 144 85, payon 144 84, payon 144 86, payon 145 85, payon 145 84, payon 145 86
timeout 15
call move
}

macro move {
log i'm on payon
do move payon 88 113
**do autostorage**
}

ato masi banyak lagi yg lain, mungkin ai manual

**Comment by ivanhadiputra** [comment]
@deca2708 thanks ! that "do autostorage" will ask the bot to do autostorage according to the config ? maybe next time i'll try it when my bot is up. Thanks a lot !

**Comment by deca2708** [comment]
kaga bro, do autostorage di macro move diatas jalan tiap automacro check ke trigger aja.

memang banyak titik2 yang bikin bot nyangkut ga tau kenapa dan ga tau gmn ngebenerinnya.
cuma bisa di akalin aja pake macro.

**Comment by ivanhadiputra** [comment]
@deca2708  oow, klo gitu hrs di macroin juga ya. Udh tau sih cara macroin storage/sell/buy. thankyou"

**Comment by and2and2** [comment]
Map field  is fld
