### ISSUE TITLE
Multi bot with use specific src folder

### ISSUE THREAD

**Issue by MrBaphomet** [OpenKore/openkore#485]
Hi, i want to ask about multi bot use specific src folder

I read this link http://forums.openkore.com/viewtopic.php?f=6&t=13

--control=path
--tables=path
--logs=path
--plugins=path
--fields=path

there are no src for multibot
can i use openkore multibot using multi src folder?

**Comment by deca2708** [comment]
u dont know how, bu just make different folders.. if your lazy turning on one by one make a .bat file

**Comment by itsrachelfish** [comment]
You should use the profiles plugin. https://wiki.wetfish.net/profiles
