### ISSUE TITLE
BUTUH BOT UNTUK RAGNAROK GRAVINDO?

### ISSUE THREAD

**Issue by musthang** [OpenKore/openkore#491]
Yang mau beli openkore buat BOT yg sudah fix jalan garansi setiap maintance,
buat yg cari zeny atau ransum,atau leveling.
contact wa 081210723769

**Comment by itsrachelfish** [comment]
This is not a complaints forum.

**Comment by cydh** [comment]
@itsrachelfish you can request Github's support team to delete this issue completely.
