### ISSUE TITLE
SMARTSNIFF DETECTED / CANNOT RUN TOGETHER WITH RAGNAROK.EXE

### ISSUE THREAD

**Issue by Flashbisa** [OpenKore/openkore#492]
Any Solutions??

**Comment by deca2708** [comment]
repent from botting :v

**Comment by musthang** [comment]
Yang mau beli openkore buat BOT yg sudah fix jalan per 14/03/2017 garansi setiap MT,
buat yg cari zeny atau ransum,atau leveling.
contact wa 081210723769

**Comment by cryp70n1c** [comment]
Use CCProxy.

**Comment by pejret** [comment]
@musthang scammer..becareful guys

**Comment by travianedan** [comment]
@pejret lu kena tipu ?

**Comment by desta89** [comment]
iye hati hati itu musthang scammer .. pembayaran nya via voucher pula.. haha .. beware guys musthang is a scammer

**Comment by grimdragonx** [comment]
Pake sniffer tools dr microsoft bs, clue dr agan @emoisback

**Comment by Flashbisa** [comment]
namanya apa brooo

**Comment by grimdragonx** [comment]
Ntar kalo ane share disini, bsk abis mt di blok lg

**Comment by Flashbisa** [comment]
email dong , flashbisa2@gmail.com bisik2 @grimdragonx

**Comment by travianedan** [comment]
[https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-9/17342747_685670234928154_7395775140525393270_n.jpg?oh=887eae15997231d16a1144c55c45e354&oe=5973B71C](url) already done with sniffing now what i have to do because this packet is change some one help me fix this out thanks

**Comment by Flashbisa** [comment]
@grimdragonx program dah dpt , terus yg mana bro? banyak bgt

**Comment by travianedan** [comment]
[https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-9/17342747_685670234928154_7395775140525393270_n.jpg?oh=887eae15997231d16a1144c55c45e354&oe=5973B71C](url) some one help me how next

**Comment by grimdragonx** [comment]
@flashbisa kan udh gw email

**Comment by abank21** [comment]
om @grimdragonx boleh dikirim ke email saya jg kah? saya hari ini nyari ngestak terus sama RO nya.
kalo boleh email ane jambanbocorr@gmail.com om.. thanks a lot.

**Comment by travianedan** [comment]
@grimdragonx  saya minat bro hartono.darma@gmx.com

**Comment by zhay89** [comment]
@grimdragonx sya minat jg kk zaturrizki89@gmail.com

**Comment by abank21** [comment]
please help dong gan, at least kasi tau aja nama programnya biar ane yg oprek sendiri nanti.. nyari hari ini ngestak terus ama RO nya T_T. Kalo ada yg berkenan tolong email ke ane aja namanya.. jambanbocorr@gmail.com. Thanks a lot

**Comment by aconx01** [comment]
@grimdragonx bro email saya ya, hoggunasu03@gmail.com
makasih

**Comment by grimdragonx** [comment]
Ntar dl, ane masih sibuk, setengah jam lg ane email

**Comment by lukmanhalim** [comment]
@grimdragonx om mau dong kirim ke email aku
mr.pocong2015@gmail.com

**Comment by abank21** [comment]
siapp om @grimdragonx !

**Comment by lukmanhalim** [comment]
siap om @grimdragonx

**Comment by v3rmouth** [comment]
@grimdragonx boleh donk om email jg nare1988@einrot.com

**Comment by antitesa** [comment]
@grimdragonx send ke an jg bang armagedontwin@gmail.com

Mksih sebelumnya .

**Comment by grimdragonx** [comment]
Send to all

**Comment by ChazyBoy** [comment]
@grimdragonx gan bias dikirimin ke Daniel.lim1012alltest@gmail.com juga.. thanks a lot ya gan

**Comment by GundulPacul** [comment]
@grimdragonx gan mau juga dong pacul027@gmail.com thanks before.

**Comment by smashmania** [comment]
@grimdragonx gan mau juga ya. makasi sebelum dan sesudahnya. smashmania000@gmail.com

**Comment by siPanda** [comment]
@grimdragonx tolong kirim jg gan ke ndasmuncang@gmail.com thx before 🙏

**Comment by EsTehAnget** [comment]
mungkin ada yg baik hati mau ngajarin permasalahan yg sekarang? ane jg mau belajar, krn selama ini dpt dari temen terus. septian.socmed@gmail.com 
makasih sebelumnya untuk siapapun yg bersedia

**Comment by lukmanhalim** [comment]
@grimdragonx blum ke kirim om

**Comment by grimdragonx** [comment]
Yg beberapa blm dpt, emailnya ndak terdaftar ndak ada

**Comment by EsTehAnget** [comment]
@grimdragonx ane boleh gan?

**Comment by lukmanhalim** [comment]
@grimdragonx oke om thx

**Comment by zundel89** [comment]
@grimdragonx gan ane minta jg donk kalo bole, trims banget jow_89@hotmail.com

**Comment by grimdragonx** [comment]
Send semua

**Comment by aconx01** [comment]
makasih @grimdragonx

**Comment by EsTehAnget** [comment]
@grimdragonx thx gan

**Comment by jnckl** [comment]
@grimdragonx mau jg donk gan

**Comment by grimdragonx** [comment]
Yang mau langsung kasih email

**Comment by zundel89** [comment]
@grimdragonx jow_89@hotmail.com gan trims

**Comment by jnckl** [comment]
@grimdragonx jancoklovsky@hotmail.com

**Comment by veinth** [comment]
@grimdragonx boleh donk bro  bagi2 bomb_range@yahoo.com

**Comment by nubiemks** [comment]
@grimdragonx bro.. udah dpt programnya tp bingung kodenya kok brubah lg yah.. minta tolong pencerahannya donk.. thanks sebelumnya ff1168aaa@gmail.com

**Comment by grimdragonx** [comment]
Gw cuman share tools, untuk selanjutnya ane blm tau, silahkan tanya suhu2 yg lain

**Comment by zundel89** [comment]
@grimdragonx ane belom kebagian toolsnya gan hehehe

**Comment by jnckl** [comment]
@grimdragonx gan, bagi nama tools nya donk jancoklovsky@hotmail.com

**Comment by grimdragonx** [comment]
Cek email lah, kalo udh ngasi email langsung gw send, kalo blm ya nunggu

**Comment by jnckl** [comment]
@grimdragonx thx juragan

**Comment by shatterdome** [comment]
@grimdragonx mau jg dong kak tools nya kl boleh, kirim ke kurokotetsuyaa3@gmaill.com
thanks kak

**Comment by garrytabuty46** [comment]
@grimdragonx Tools nya klo bole bro. ke garrytabuty46@gmail.com

**Comment by grimdragonx** [comment]
udh ane email

**Comment by veinth** [comment]
cara encrypted nya apa sudah ada solusi @grimdragonx ?

**Comment by grimdragonx** [comment]
@veinth belom, ane sibuk ngerjain project lain, nunggu para suhu ngasih clue lg

**Comment by shatterdome** [comment]
@grimdragonx blm masuk nih gan..maaf ane ada salah ketik, yg bener kurokotetsuyaa3@gmail.com
punten ya gan minta dikirim lagi.

**Comment by jnckl** [comment]
![sniff](https://cloud.githubusercontent.com/assets/26415784/23916937/57cbbb1e-0920-11e7-98f9-58d08213604d.png)

ini hasil sniff saya, ada kemiripan di bagian akir dengan sniff yg lama

**Comment by grimdragonx** [comment]
@shatterdome udh bener, ane copas kali itu, g ane ketik

@jnckl iya ada miripnya, cuman itu ada yg diencrypt

**Comment by jnckl** [comment]
@grimdragonx diencrypt itu d apain ya? hehe

**Comment by Susumelek45** [comment]
@grimdragonx tolong ane jg kirim ke email donk gan killua_zold@yahoo.com

**Comment by aconx01** [comment]
00 69
00 02

**Comment by aconx01** [comment]
@grimdragonx  ada discord ?

**Comment by grimdragonx** [comment]
@jnckl ente bs googling kan? cek aja di google

@aconx01 ada, buat apaan?

**Comment by aconx01** [comment]
@grimdragonx  mau tanya" sedikit

**Comment by grimdragonx** [comment]
@aconx01 tanya apaan? soal decrypt encrypt sniff packet? ane g begitu paham, ane cuman share tools, selebihnya blm lanjut lg

**Comment by Susumelek45** [comment]
@grimdragonx blm masuk gan di email ane 
Killua_zold@yahoo.com

**Comment by grimdragonx** [comment]
udah ane kirim, kalo blm masuk tungguin aja, sabar ngapa, dan ane tegasin sekali lagi, ane cuman share tools, selebihnya cari tau sendiri

**Comment by Doomsaurus** [comment]
@grimdragonx

boleh minta gan tools nya
doomsaurus@gmail.com

thanks be4

**Comment by Susumelek45** [comment]
Thx gan @grimdragonx

**Comment by shatterdome** [comment]
@grimdragonx ty ty gan, td emg salah tulis gw emailnya yg pertama hahaha, thanks :p

**Comment by apikdech** [comment]
tolong kirim juga dong gan apikvender@gmail.com 
makasi

**Comment by sausmie** [comment]
@grimdragonx  boleh mnta tools nya gan  sausmie@gmail.com    
makasih

**Comment by thenorak** [comment]
@grimdragonx minta kirim juga donk kak, moga2 rejeki trus si kaka' kim77christ@gmail.com

**Comment by tantan09** [comment]
@grimdragonx gan ane juga donk wachyoupras@gmail.com

**Comment by totalyn00b** [comment]
@grimdragonx boleh bos di send tools nya , ini kyknya yg di diencrypt cuma bagian login doang ya mastah? server nya ttp 5D 19 46 XXX. ane mau tanya apa bisa itu yg cara encrypt nya gmn ? soalnya packet dari smartsniff + wireshark beda padahal capture bareng .  
mohon pencerahannya d3nzz.ajib@gmail.com ,

**Comment by Maelvaria** [comment]
@grimdragonx tolong di send donk ke nicho.denny@gmail.com suhu . Thx b4

**Comment by ezralds** [comment]
@grimdragonx ane ikutan dong gan.. ezralds@gmail.com thanks a lot before...

**Comment by Eongs** [comment]
boleh dong minta filenya jg bos

**Comment by tereliye** [comment]
@grimdragonx kalo boleh dikirim jg saya gan jujuonwork@gmail.com makasih banyak ya

**Comment by person007** [comment]
smsrtsniff udah ga bisa lagi di win 10 ya ada solusinya ga gan... ane coba pake yang lain untuk win7 ada yang bisa tapi tdk sama dgn smsrtsniff   gan @grimdragonx  punya tool untuk di win10 gan send me 101buat101@gmail.com

**Comment by pusingkarena** [comment]
nama filenya itu microsoft network monitor, bs di download di https://www.microsoft.com/en-us/download/details.aspx?id=4865
dah bs liat packetnya tp masih bingung ubah hexnya di packetparse, barang kali ada yg bs tolong share ya

**Comment by Susumelek45** [comment]
Ada yg tau ndak ini smartsniff sama ro ndak bisa login bersamaan mohon info donk???

**Comment by tantan09** [comment]
saya stuck dsni g tau lagi langkah selanjutnya gan @grimdragonx 
![capture4](https://cloud.githubusercontent.com/assets/26406767/23932963/3a2569f6-0976-11e7-8244-279185a061a0.PNG)

**Comment by grimdragonx** [comment]
pada bs baca g sih? udh diblg gw cuman share tools, untuk selanjutnya lakuin sendiri, ane belom sempet ngutak ngatik lg

**Comment by Susumelek45** [comment]
Port 6900 ndak dpt

**Comment by pusingkarena** [comment]
port 6900 liat di description,yg teliti

**Comment by totalyn00b** [comment]
@grimdragonx @pusingkarena  plis bagi dong tool nya d3nzz.ajib@gmail.com

**Comment by grimdragonx** [comment]
itu udah ada yg share di atas

**Comment by itsrachelfish** [comment]
Please stop spamming github.
