### ISSUE TITLE
need help how i fix it unknown switch 0276

### ISSUE THREAD

**Issue by hideman012** [OpenKore/openkore#494]

**Comment by hideman012** [comment]
help me plz

**Comment by hideman012** [comment]
![image](https://cloud.githubusercontent.com/assets/22455156/23913520/d6307888-0915-11e7-9111-4220ce9907f2.png)

**Comment by aconx01** [comment]
coba itu ganti gak gan ?

**Comment by jompom** [comment]
What is the picture?
![capture](https://cloud.githubusercontent.com/assets/26416281/23915223/0bf22764-091b-11e7-937a-59e0d660a3f4.JPG)

**Comment by jompom** [comment]
Solution help help

**Comment by hideman012** [comment]
enlish plz

**Comment by itsrachelfish** [comment]
This is not a complaints forum.
