### ISSUE TITLE
Crash: src/Task/TalkNPC.pm line 170

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#495]
Server: iRo
OpenKore version what-will-become-2.1
@ai_seq = NPC macro
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2017_03_12
Loaded plugins:
  plugins/alertsound.pl (alertsound; description: plays sounds on certain events)
  plugins/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)

Error message:
Can't call method "name" on an undefined value at src/Task/TalkNPC.pm line 170.

Stack trace:
Can't call method "name" on an undefined value at src/Task/TalkNPC.pm line 170.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x44f8594)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		$self->setDone();
* 		message TF("Done talking with %s.\n", $self->{target}->name), "ai_npcTalk";

**Comment by Henrybk** [comment]
Plase give more information, were you using `talk` command, `talknpc` command (well if `NPC` was in AI queue then it most probably was `talknpc`), what were you trying to do?
Was it an auto-started conversation in which you tried to hook a macro to start with using talknpc?

If you still have this problem I would also ask you to test #397 it most probably will fix your problem.

**Comment by SabadyshynV** [comment]
it's assertion bug on $self->_assertStatus(INACTIVE, RUNNING) if DEBUG; in task.pm
i already got problems with that https://github.com/OpenKore/openkore/issues/469

**Comment by Glikadin** [comment]
This happened after the successful execution of the command "Autosell"  . Probably has something to do with command "Autostorage". The error does not always occur

**Comment by m3kgin3er** [comment]
Maybe it's trying to close an inexistent talk ?!

**Comment by alisonrag** [comment]
Maybe fixed in #907
