### ISSUE TITLE
Change New Payon to Old Payon 

### ISSUE THREAD

**Issue by gheghe** [OpenKore/openkore#496]
Any1 can solve my problem ?

my Ragnarok Server use Old Payon.. but, my openkore only have new payon.. i cant move >,<!

**Comment by SabadyshynV** [comment]
Exchange this 2 filenames....?

**Comment by SabadyshynV** [comment]
http://clip2net.com/s/3IwC6V7

**Comment by gheghe** [comment]
@SabadyshynV i dont have old_payon.fld.gz file

**Comment by SabadyshynV** [comment]
http://letmegooglethat.com/?q=old_payon.fld.gz

**Comment by gheghe** [comment]
Lol.. 3 days i search this fld and still cant change map.. my server maintenance now.. but.. thanks for ur help :*

**Comment by itsrachelfish** [comment]
@gheghe The files are in this repo. https://github.com/OpenKore/openkore/blob/master/fields/old_payon.fld.gz

Are you sure you're using the most recent version of openkore? You can download it by clicking the big green button!

![download-zip](https://cloud.githubusercontent.com/assets/1670549/24040485/0bda03a4-0acf-11e7-812f-533398f3cfcd.png)

**Comment by gheghe** [comment]
still cant change map.. ~.~

**Comment by itsrachelfish** [comment]
@gheghe 

1. Download the most recent version of openkore from github
2. Go to the fields folder
3. Rename "payon.fld.gz" to "new_payon.fld.gz"
4. Rename "old_payon.fld.gz" to "payon.fld.gz"
5. Restart openkore

xD
