### ISSUE TITLE
Update RagexeRE_2015_11_04a

### ISSUE THREAD

**Issue by Razalka** [OpenKore/openkore#497]
Please anyone can help update the kRO servertype to **RagexeRE_2015_11_04a** ?
The latest one was provided from @Nyxvanthcal (RagexeRE_2015_05_13a)(Packet version : 52)
Now the packet version is 55.

` 
//2015-11-04aRagexe
packet_ver: 55
packet_keys: 0x4C17382A,0x7ED174C9,0x29961E4F // [Winnie]
0x0369,7,actionrequest,2:6
0x083C,10,useskilltoid,2:4:6
0x0363,5,walktoxy,2
0x0886,6,ticksend,2
0x0928,5,changedir,2:4
0x0964,6,takeitem,2
0x0437,6,dropitem,2:4
0x088B,8,movetokafra,2:4
0x0364,8,movefromkafra,2:4
0x0438,10,useskilltopos,2:4:6:8
0x0366,90,useskilltoposinfo,2:4:6:8:10
0x0887,6,getcharnamerequest,2
0x0368,6,solvecharname,2
0x0838,12,searchstoreinfolistitemclick,2:6:10
0x0835,2,searchstoreinfonextpage,0
0x0819,-1,searchstoreinfo,2:4:5:9:13:14:15
0x0815,-1,reqtradebuyingstore,2:4:8:12
0x0436,6,reqclickbuyingstore,2
0x0817,2,reqclosebuyingstore,0
0x023B,-1,reqopenbuyingstore,2:4:8:9:89
0x0811,18,bookingregreq,2:4:6
//0x0939,8 CZ_JOIN_BATTLE_FIELD
0x093A,-1,itemlistwindowselected,2:4:8:12
0x0360,19,wanttoconnection,2:6:10:14:18
0x08A5,26,partyinvite2,2
//0x08A3,4 CZ_GANGSI_RANK
0x07EC,26,friendslistadd,2
0x088D,5,hommenu,2:4
0x0940,36,storagepassword,2:4:20  `

Thank you.

**Comment by Nyxvanthcal** [comment]
Which server is using this ?!

**Comment by Nyxvanthcal** [comment]
```
#############################################################################
#  OpenKore - Network subsystem												#
#  This module contains functions for sending messages to the server.		#
#																			#
#  This software is open source, licensed under the GNU General Public		#
#  License, version 2.														#
#  Basically, this means that you're allowed to modify and distribute		#
#  this software. However, if you distribute modified versions, you MUST	#
#  also distribute the source code.											#
#  See http://www.gnu.org/licenses/gpl.html for the full license.			#
#############################################################################
# bRO (Brazil)
package Network::Send::bRO;
use strict;
use base 'Network::Send::ServerType0';

sub new {
	my ($class) = @_;
	my $self = $class->SUPER::new(@_);
	
	my %packets = (
		'0369' => ['actor_action', 'a4 C', [qw(targetID type)]],
		'083C' => ['skill_use', 'v2 a4', [qw(lv skillID targetID)]],
		'0363' => ['character_move','a3', [qw(coords)]],
		'0886' => ['sync', 'V', [qw(time)]],
		'0928' => ['actor_look_at', 'v C', [qw(head body)]],
		'0964' => ['item_take', 'a4', [qw(ID)]],
		'0437' => ['item_drop', 'v2', [qw(index amount)]],
		'088B' => ['storage_item_add', 'v V', [qw(index amount)]],
		'0364' => ['storage_item_remove', 'v V', [qw(index amount)]],
		'0438' => ['skill_use_location', 'v4', [qw(lv skillID x y)]],
		'0887' => ['actor_info_request', 'a4', [qw(ID)]],
		'0336' => ['actor_name_request', 'a4', [qw(ID)]],
		'0929' => ['item_list_res', 'v V2 a*', [qw(len type action itemInfo)]],
		'0360' => ['map_login', 'a4 a4 a4 V C', [qw(accountID charID sessionID tick sex)]],
		'07EC' => ['party_join_request_by_name', 'Z24', [qw(partyName)]], #f
		'088D' => ['homunculus_command', 'v C', [qw(commandType, commandID)]], #f
		'0951' => ['storage_password'],
	);
	
	$self->{packet_list}{$_} = $packets{$_} for keys %packets;
	
	my %handlers = qw(
		master_login 02B0
		buy_bulk_vender 0801
		party_setting 07D7
	);
	
	while (my ($k, $v) = each %packets) { $handlers{$v->[0]} = $k}
	$self->{packet_lut}{$_} = $handlers{$_} for keys %handlers;
	#$self->cryptKeys(1079591486, 1148275821, 1759071601);

	return $self;
}

1;
```

Well i didn't found item list res and another! wait for edit

**Comment by Nyxvanthcal** [comment]
Already update some files in my dir !

**Comment by Nyxvanthcal** [comment]
@Nyxvanthcal/openkore

**Comment by Glowned** [comment]
Hello Nyxvanthcal,
Thanks for your work ! 

I'm facing an error using your files : 
"Can't reconstruct unknown packet 02B0 at src/Network/PacketParser.pm line 129."

**Comment by Nyxvanthcal** [comment]
Already updated ! Try again bro ! Thanks for your feedback ! I saw many things wrongs now i've already fixed it !

**Comment by Razalka** [comment]
Thanks for the update @Novishivsmoke , i will test it and provide the feedback asap.

**Comment by Razalka** [comment]
@Novishivsmoke 

Obfuscation packet ?

![nyx](https://cloud.githubusercontent.com/assets/25100730/24086861/a04d0546-0d49-11e7-8077-5934125cf665.JPG)

**Comment by Novishivsmoke** [comment]
Try changing the order of keys ! Follow the tutorial to extract the keys ! 

http://forums.openkore.com/viewtopic.php?f=6&t=211637

**Comment by Razalka** [comment]
So the developer said that he customs the keys and the version.
but he tells me the keys is exactly same with the version, so if i can get the version, i get the keys.
I got the version, and its correct, but not with the keys.
Exe version = 20151102 , but published 20151104 .. 
got it from PEEK , and extract the recvpackets from PEEK too.

I've read all the threads that you post in openkore forums, and learned a lot from it.
thank's SkyLord :smile:  
but stuck with this server :sad:

here's the exe with openkore server.txt.
https://drive.google.com/open?id=0B2t-24ZoJDCSLURCUkhiN2F5RVk

sorry for my bad english.

**Comment by Novishivsmoke** [comment]
Yes ! He added some kind of themida in keys function and i don't know how to bypass this. Looks like same used in bRO ragexe file ! 

> said that he custom the keys ! the keys is exactly same with the version

0x4C17382A,0x7ED174C9,0x29961E4F ! Well, if it doesn't worked ! It will won't work ! 

Try inverting the second number with the third and lets go ! If you've already tried, forget !

**Comment by Razalka** [comment]
I've tried the default keys from PEEK Extract same with you mention above , and inverting all of it, 321,312,213,231,123,132 and nothing changed.

oke, i will try to find another knowledge about themida lol
thanks before @Novishivsmoke :smile:

**Comment by Novishivsmoke** [comment]
Well if u know something to do with that talk me ! 
How did u have unpacked this thing ? or it came at this way ? 'cause looks like only one part crypted, the sub was selected. How he did it i don't know !

**Comment by Razalka** [comment]
He just tell me to fills the keys same with the "version" but in hex.
i tried it and tadaaaaa .... nothing happened :cry:

**Comment by Razalka** [comment]
@Novishivsmoke 
When i tried to fill src/Network/Receive/kRO/RagexeRE_2015_11_04a.pm with some packet desc.

![error1](https://cloud.githubusercontent.com/assets/25100730/24135041/80f3e8da-0e3a-11e7-8356-e654a131f3e4.JPG)

**Comment by Novishivsmoke** [comment]
Looks like u're forcing to enter in the game. I think it's impossible. I believe that this message of "Your coordinates".Try sniffing the map login packet and check if it receive any other Unknown packet parser! 
Could u upload the main exe file !?

**Comment by Razalka** [comment]
tried xkore 3 mode, logged in and after 1 minutes in game, there's so many unknown packet recorded and the packet changing so damn fast.
i'll try to make rebuild packet script in packetparser.

**Comment by Razalka** [comment]
here from xkore 3 mode.

![xkore3_1](https://cloud.githubusercontent.com/assets/25100730/24180331/ede57178-0ee6-11e7-987b-ee12af7c5b21.JPG)

![xkore3_2](https://cloud.githubusercontent.com/assets/25100730/24180329/ede43e16-0ee6-11e7-8329-bca9689d934c.JPG)

![xkore3_3](https://cloud.githubusercontent.com/assets/25100730/24180330/ede54450-0ee6-11e7-8785-32b839ab14fc.JPG)

**Comment by Novishivsmoke** [comment]
Yeah i was debugging here and the emulation part is awful ! i hate emulation ! i hate themida.
I don't know why this exe has 0x9D0 (gameguard_reply) inside him !

**Comment by Razalka** [comment]
this one didn't use the themida and gameguard (confirmed from the developer).
i got the packet key, but the developer only fill it with 1 key, its not like the default that have 3 keys.
0x26061990 is the packet key.
but if we fill only 1 packet key, the script will not work properly. And if we fill it 3 times with the same value, the server will reject it because they only use 1 key.
@_@

**Comment by Novishivsmoke** [comment]
Well since we can see that it jumps from 0x363 to EE70 ! then we can search for the algorithm ! i really don't know if i can find it outside emulation. I don't know how to bypass this kind of thing !

**Comment by Razalka** [comment]
the packet keys and recvpacket was right, but the server still denied the connection.
that't what makes me confused, they denied the connection.
if we problem with keys or the packet, only map timeout will show, not the denied connection.

**Comment by Razalka** [comment]
try to change the sent packet 006A to 25 bytes :rofl: 
![opkore rakki](https://cloud.githubusercontent.com/assets/25100730/24278687/de7a5e78-1077-11e7-97c3-031084f7ad19.JPG)

**Comment by Novishivsmoke** [comment]
Well i know a way to debug this encrypted shit. I've tested this late night (one day without sleep almost) and i've did something cool but no way where i've stopped ! 

The difference is : 

My way : I tried with a exe broken (PE header is wrong/crypted) and no way to get OEP.
Your way : The game will be running without shield ! 
But now when you do login, it calls the login sub with stack values correct, !

**Comment by Razalka** [comment]
The developer help us lol.
But its too late, we already have all this things.
The keys, version and another info they gave it me.

I thinks its rathena client bug, activating obfus packet with broken key (only 1 key define like the pic below)
And the client still got no error and works perfectly.
Diffed with nemo and they define 3 keys inside it @_@
The developer only activating, obfus packet, custom key and client hash.
No gameguard or themida and another encryption method.
I'll try to make custom dll to bypass this thing.

![img_20170326_124725](https://cloud.githubusercontent.com/assets/25100730/24328985/c9263252-1222-11e7-92fa-4b9ca21c4739.jpg)
![img_20170326_124652](https://cloud.githubusercontent.com/assets/25100730/24328986/c9275e0c-1222-11e7-9262-03c4660adbac.jpg)
![img_20170326_124657](https://cloud.githubusercontent.com/assets/25100730/24329020/d73cedd0-1223-11e7-8818-c6863ac4fcc0.jpg)

**Comment by Novishivsmoke** [comment]
Try using src/network/send.pm 👍 
sub encryptMessageID {
	my ($self, $r_message) = @_;
	my $messageID = unpack("v", $$r_message);
	
	if ($self->{encryption}->{crypt_key_3}) {
		if (sprintf("%04X",$messageID) eq $self->{packet_lut}{map_login}) {
			$self->{encryption}->{crypt_key} = $self->{encryption}->{crypt_key_1};
		} elsif ($self->{net}->getState() != Network::IN_GAME) {
			# Turn off keys
			$self->{encryption}->{crypt_key} = 0; return;
		}
			
		# Checking if Encryption is Activated
		if ($self->{encryption}->{crypt_key} > 0) {
			# Saving Last Informations for Debug Log
			my $oldMID = $messageID;
			my $oldKey = ($self->{encryption}->{crypt_key} >> 16) & 0x7FFF;
			
			# Calculating the Encryption Key
			$self->{encryption}->{crypt_key} = ($self->{encryption}->{crypt_key} * $self->{encryption}->{crypt_key_3} + $self->{encryption}->{crypt_key_2}) & 0xFFFFFFFF;
		
			# Xoring the Message ID
			$messageID = ($messageID ^ (($self->{encryption}->{crypt_key} >> 16) & 0x7FFF)) & 0xFFFF;
			$$r_message = pack("v", $messageID) . substr($$r_message, 2);

			# Debug Log	
			debug (sprintf("Encrypted MID : [%04X]->[%04X] / KEY : [0x%04X]->[0x%04X]\n", $oldMID, $messageID, $oldKey, ($self->{encryption}->{crypt_key} >> 16) & 0x7FFF), "sendPacket", 0) if $config{debugPacket_sent};
		}
	} else {
		use bytes;
		if ($self->{net}->getState() != Network::IN_GAME) {
			$enc_val1 = 0;
			$enc_val2 = 0;
			return;
		}

		my $messageID = unpack("v", $$r_message);
		if ($enc_val1 != 0 && $enc_val2 != 0) {
			# Prepare encryption
			$enc_val1 = ((0x000343FD * $enc_val1) + $enc_val2)& 0xFFFFFFFF;
			debug (sprintf("enc_val1 = %x", $enc_val1) . "\n", "sendPacket", 2);
			# Encrypt message ID
			$messageID = ($messageID ^ (($enc_val1 >> 16) & 0x7FFF)) & 0xFFFF;
			$$r_message = pack("v", $messageID) . substr($$r_message, 2);
		}
	} elsif ($self->{encryption}->{crypt_key_1}) {
			# Saving Last Informations for Debug Log
			my $oldMID = $messageID;
			my $oldKey = ($self->{encryption}->{crypt_key} >> 16) & 0x7FFF;
			
			# Calculating the Encryption Key
			$self->{encryption}->{crypt_key} = ($self->{encryption}->{crypt_key1} ^ 0x2606F7E0 & 0xFFFFFFFF;
		
			# Xoring the Message ID
			$messageID = ($messageID ^ (($self->{encryption}->{crypt_key} >> 16) & 0x7FFF)) & 0xFFFF;
			$$r_message = pack("v", $messageID) . substr($$r_message, 2);

			# Debug Log	

	}
}

**Comment by Novishivsmoke** [comment]
This is the algorithm : 

`int __thiscall sub_817910(int this, int a2, int a3)
{
  int v3; // esi@1
  int v4; // edx@1
  int v5; // ecx@1
  int v6; // edx@1
  int v7; // eax@3
  int result; // eax@7

  v3 = this;
  v4 = *(_DWORD *)(this + 16);
  v5 = *(_DWORD *)(this + 8);
  v6 = v4 - *(_DWORD *)(v3 + 12);
  if ( v5 + a2 > v6 )
  {
    if ( a2 + v5 - *(_DWORD *)(v3 + 4) > v6 )
    {
      sub_7269F0(2 * v6);
      v7 = *(_DWORD *)(v3 + 12);
      if ( v7 == *(_DWORD *)(v3 + 16) )
        v7 = 0;
      *(_DWORD *)v3 = v7;
    }
    memmove(*(_DWORD *)v3, *(_DWORD *)v3 + *(_DWORD *)(v3 + 4), *(_DWORD *)(v3 + 8) - *(_DWORD *)(v3 + 4));
    *(_DWORD *)(v3 + 8) -= *(_DWORD *)(v3 + 4);
    *(_DWORD *)(v3 + 4) = 0;
  }
  result = j_memcpy(*(_DWORD *)v3 + *(_DWORD *)(v3 + 8), a3, a2);
  *(_DWORD *)(v3 + 8) += a2;
  return result;
}`

**Comment by Novishivsmoke** [comment]
DE01128A for default purpose

**Comment by Razalka** [comment]
still denied bro

**Comment by Novishivsmoke** [comment]
I've already found the algorithm to the key ! 
It has a custom scheme to edit the packet EE70 ! I don't know the contents, but surely it's emulated ^^

**Comment by Razalka** [comment]
The server recognized unknown pakcet 66BD from the openkore.
I think i know how to penetrate it, give me 1 day. Hahahaha

**Comment by Novishivsmoke** [comment]
What ? ! 66BD -> come from what ? one day ?! only one ?!

**Comment by Razalka** [comment]
1 week sorry, i take my words back lol
there's 2 new unrecognized packet in the server 66BD & 6BBD.
i'll get the screenshot asap.
thanks for your help.
20 hours without sleep @_@ yesterday.
i'll post my progress asap .

**Comment by Razalka** [comment]
> Snif and What openkore send.
> ` 0C 5F B7 84 1E 00 6D 4A 02 00 A7 C0 8E 37 EA 8E 28 05 00 `

> Sniff and what client send.
> `EE 70 B7 84 1E 00 6D 4A 02 00 4F BE 49 28 FA D6 E4 14 01`

The openkore didn't send EE70 or the Map_login packet.
it's just like you said, the map_login/0360 packet jump into EE70.

andddd..
The client send request packet sync/8701 , doesn't like the openkore.

> Snif and What openkore send.
> ` no request `

> Sniff and what client send.
> `87 01 B7 84 1E 00 `

**Comment by Razalka** [comment]
The 6BBD  is encryption from maplogin 0360 then 70EE.
And now new another unknown packet in server,  70C6.

**Comment by Novishivsmoke** [comment]
Well you really need to debug the function . To get the sequence. 
I'll study in bRO how to get the keys in another way and i'll talk to you !

**Comment by Razalka** [comment]
well then, i'll learn it from you :smile:

**Comment by smallvill3** [comment]
sir, Novishivsmoke

'09CB' => ['skill_used_no_damage', 'v2 a4 a4 C', [qw(skillID amount targetID sourceID success)]], # 17
This receive packet handler i believe to be incomplete.

![untitled](https://cloud.githubusercontent.com/assets/26625329/24485984/2e082d32-153a-11e7-8140-53a66b40fe98.jpg)

**Comment by Razalka** [comment]
@smallvill3 
Try this.
'09CB' => ['skill_used_no_damage', 'v1 v1 a4 a4 C1', [qw(skillID amount targetID sourceID fail)]],

**Comment by smallvill3** [comment]
@Razalka 
Firstly i would thank you for your attention for this request. 
Still error.
![w](https://cloud.githubusercontent.com/assets/26625329/24491769/55ef9364-155b-11e7-8ab4-78b2f417c799.jpg)

**Comment by Razalka** [comment]
@smallvill3 
Its error casting timeout.

**Comment by smallvill3** [comment]
@Razalka 
im using default timeout.txt
How about the Unknown (user)?

**Comment by Razalka** [comment]
@smallvill3 
the unknown, it's from tables folder.
did you use the right recvpackets ?

**Comment by smallvill3** [comment]
I don't think its from the table folder.
if i change to
'09CB' => ['skill_used_no_damage', 'v3 a4 a4 C', [qw(skillID amount targetID sourceID success)]]

The result is
![untitled](https://cloud.githubusercontent.com/assets/26625329/24493165/6a30d766-1560-11e7-91cc-84ee5825d8de.jpg)

target user become unknown

**Comment by Razalka** [comment]
Use this reference.
http://openkore.com/index.php/Frequently_Asked_Questions
> Items and skills are shown as "Unknown #xxxxxxxx"
> Names are missing from table files. Update corresponding files manually or using files from other clients, or use skill handles, or just use displayed Unknowns as usual names.

**Comment by smallvill3** [comment]
User (target player) is not a skill or items sir.

**Comment by Razalka** [comment]
Did you already find or googling it before, sir ?

**Comment by smallvill3** [comment]
Yes, already did before. Nothing on 09CB yet.
Only 011A is supported. 
'011A' => ['skill_used_no_damage', 'v2 a4 a4 C', [qw(skillID amount targetID sourceID success)]]

**Comment by Razalka** [comment]
can you post your server config ?
and the server web ?

**Comment by smallvill3** [comment]
Sure,

> [GGamerzRO]
> ip 116.251.223.176
> port 6900
> private 1
> master_version 1
> version 45
> recvpackets ggamerzRO_20130807.txt
> serverType kRO_RagexeRE_2013_08_07a
> serverEncoding Western
> charBlockSize 144
> pinCode 1
> addTableFolders translated/kRO_english;kRO;kRO
> #clientHash 6e1d7aae3838cd7aec434cd10ef861e9

Website: gombak-gamerz.com

**Comment by Razalka** [comment]
why you dont try to use this servertype ?
kRO_RagexeRE_2015_11_04a from Novishivsmoke ?

**Comment by Razalka** [comment]
@smallvill3 
here's the solution.
http://forums.openkore.com/viewtopic.php?p=275220#p275220

**Comment by Novishivsmoke** [comment]
I have read in somewhere that 👍 

'011A' => ['skill_used_no_damage', > 2015 will add one param. lv id

Try using something like 👍 

'09CB' => ['skill_used_no_damage', 'v3 v a4 a4 C', [qw(skillID lvl amount targetID sourceID success)]],

Try this way, maybe won't work !

**Comment by Novishivsmoke** [comment]
# Calculating the Encryption 

$messageID = 0x360;

my $key1 = 0x4C17382A;
my $key3 = 0x7ED174C9;
my $key2 = 0x29961E4F;

$key1 = ($key1 * $key3 + $key2) & 0xFFFFFFFF;
		
# Xoring the Message ID
$messageID = ($messageID ^ (($key1 >> 16) & 0x7FFF)) & 0xFFFF;

print "MessageID = " . sprintf("%04X", $messageID);

<>;

**Comment by Novishivsmoke** [comment]
Wow you have problem with this packet, and i have problem with 0A0D packet
Believe me ! 

In this server, the packet is looking like with other. packet slice as imike lance said.
The 0A0D packet is inside 01D7 packet. Maybe not. I don't know. I'm receiving error with items_not_stackable !

**Comment by Novishivsmoke** [comment]
@smallvill3

According with : 

https://github.com/OpenKore/openkore/issues/516

Try : 

'09CB' => ['skill_used_no_damage', 'v a4 a4 a4 C', [qw(skillID amount targetID sourceID success)]], # 17

**Comment by Razalka** [comment]
@Novishivsmoke 
sorry for being late.
I'll try it asap.
Let me report it to you when im done.

**Comment by Razalka** [comment]
@Novishivsmoke 
Stabilize in the game.
![rakke succ](https://cloud.githubusercontent.com/assets/25100730/24645673/597ab7fc-1943-11e7-929a-1736167edd07.JPG)

but there's too many unknown switch.
they use the obfuscation packet, to randomize the packet.

**Comment by Razalka** [comment]
I think the openkore data should be update.
The OP sucessfully logged in and stay in the game, but there's some packet switch didn't work.
it's just like whisper chat, the char cannot move, always stuck during route.

**Comment by Razalka** [comment]
@Novishivsmoke 
I Already update the send and receive packet from your fork, and i already add some effect files to tables folder for "unknown effect".
Everything looks normal, without any error.
but there's 1 problem 1 can't solve.
the bot cannot move, it always stuck during route and no action.
already tried to change the actor packet, but there's no change.

**Comment by Novishivsmoke** [comment]
Well i have Walked a lot before. If he have done something updating the exe need to do this work again

**Comment by Razalka** [comment]
@m3kgin3er 
I already test that script a month ago, from your post in forum.
hahahahah.

I'll report it asap.
Thanks ^^

**Comment by m3kgin3er** [comment]
https://github.com/OpenKore/openkore/issues/533 recvpackets

**Comment by Razalka** [comment]
@m3kgin3er 
It's not working, different packet from this server.

**Comment by m3kgin3er** [comment]
nice

**Comment by Razalka** [comment]
@m3kgin3er 
Since the latest kRO sT from your fork is **2015_05_13a** and then jump to **2015_11_04a**, it's possible maybe there's some shuffling packet in sT beetween it ?
because the latest  sT use "base" from the previous one.

• **RagexeRE_2015_05_13a** (Updated by @m3kgin3er )
• **RagexeRE_2015_09_16** 
• **RagexeRE_2015_10_01b**
• **RagexeRE_2015_11_04a** (Updated by @m3kgin3er )

Thanks you @m3kgin3er , i learned a lot from you ^^.

**Comment by m3kgin3er** [comment]
Oh yeah it was not made to 2015-10-29 then could occur some error using.
According with 👍 
https://pastebin.com/wjUeuU8k

For 2015 clients should exists : 

"20150513a" => "0x0363",
"20150916" => "0x0969",
"20151001b" => "0x022d",
"20151104a" => "0x0360",

for 2014 : 

"20141016" => "0x086E",
"20141022b" => "0x093b",

Since the map packet changes, that it's important. And well, the map login changes. You can note ! I jump 3 steps because i've not saw servers using . Now that have some request, i can think in create , but everyone when asked, since there are not so much sT. And well it's all !

**Comment by Razalka** [comment]
@m3kgin3er 
nope, still cant move, maybe because i made change in my Openkore, and i'll try to download your fresh fork and try it again.
there's some undefined packet from the previous sT its like.

> 0x0A18,14   ZC_ACCEPT_ENTER3
> 0x0A28,3   ZC_ACK_OPENSTORE2
> 0x09FD,-1   ZC_NOTIFY_MOVEENTRY11
> 0x09FE,-1	   ZC_NOTIFY_NEWENTRY11
> 0x09FF,-1	  ZC_NOTIFY_STANDENTRY11

**Comment by m3kgin3er** [comment]
Rly that i've not inserted these packets ?

**Comment by Razalka** [comment]
surely thats not the reason, i just tell you those packet show in this server but it's undefine :smile:
if you can move, surely i will download your fork again and try it without edit anything ^^

**Comment by Razalka** [comment]
@m3kgin3er 
I've fresh download your fork, and just edit the server.txt
and here the error's.
![m3k1](https://cloud.githubusercontent.com/assets/25100730/24897153/0a920b70-1ec2-11e7-9fe9-23f5f0713908.JPG)
![m3k2](https://cloud.githubusercontent.com/assets/25100730/24897159/0cf5eb8e-1ec2-11e7-9c65-55e1f4c34d80.JPG)

**Comment by m3kgin3er** [comment]
Well, i'm downloading now Rakki-RO full . 'cause i'm trying to clicking right button above the item and well, its crashing my client. Anyway !

**Comment by rrrahl** [comment]
Hey i just tried it out with #533 and i have the exact same error as @Razalka

**Comment by m3kgin3er** [comment]
`----[ recv(748, 0x0019F190, 2048, 0x0) == 1690
D7 01 D9 84 1E 00 02 B1 04 00 00 91 09 1C 00 02  ×.Ù....±....	...
00 F7 01 00 01 00 00 00 00 00 00 00 00 00 00 00  .÷..............
00 00 00 00 00 00 01
===
0D 0A 76 
00 03 00 B1 04 05 -> 6
02 00 00 00 02 00 -> 12 
00 00 00 00 00 00 -> 18
00 00 00 00 00 00 -> 24
00 00 00 00 00 00 -> 30
00 00 00 00 00 00 -> 6
00 00 00 00 00 00 -> 12
00 00 00 00 00 00 -> 18
00 00 00 00 00 00 -> 24
00 00 00 01 04 00 -> 60
FD 08 04 10 00 00 -> 66
00 10 00 00 00 00 -> 72
00 00 00 00 00 00 -> 78
00 00 00 00 00 00 -> 84
00 00 00 00 00 00 -> 90
00 00 00 00 00 00 -> 96
00 00 00 00 00 00 -> 102
00 00 00 00 00 00 -> 108
00 00 00 00 00 00 -> 114
01 B0 00 18
===`

**Comment by Razalka** [comment]
@m3kgin3er 
Well, maybe the Openkore need a lot of update due to renewal system.

**Comment by m3kgin3er** [comment]
Or maybe i've done something wrong. I'll be checking it .

**Comment by m3kgin3er** [comment]
http://forums.openkore.com/viewtopic.php?f=9&t=211585

**Comment by Razalka** [comment]
Similar problem.

**Comment by m3kgin3er** [comment]
@Razalka 👍 
https://pastebin.com/gsjJMV33

082D solved problem. (recvpackets)

But 0A0D packet stills incorrect.

**Comment by Razalka** [comment]
@m3kgin3er 
i used that recvpackets, i got dc when trying to move.

**Comment by m3kgin3er** [comment]
Fixed for while. Maybe not showing item refine.

**Comment by Razalka** [comment]
@m3kgin3er 
Wait, i'll change it for you senpai

**Comment by m3kgin3er** [comment]
Well at first was to be swordsman. Just swordsman please...

Well, storage , you'll have problem yes ! Because i've not fixed this!

Try again bro !

**Comment by Razalka** [comment]
Pin code senpai ?

**Comment by m3kgin3er** [comment]
7547

**Comment by Razalka** [comment]
You're swordsman now.

**Comment by m3kgin3er** [comment]
Oh i saw so cute ! ^^ Add me later . I'm in prontera

**Comment by Razalka** [comment]
im on my way back to home, i'll add you when im home.

**Comment by m3kgin3er** [comment]
Ok thanks to work with us . 
Please close the thread. If the error persists, create another ! Thanks !

**Comment by Razalka** [comment]
Thank you senpai @m3kgin3er

**Comment by Razalka** [comment]
new error senpai @m3kgin3er 
![error 1](https://cloud.githubusercontent.com/assets/25100730/24955682/ab6f83c8-1fae-11e7-80bc-f4546fa393dc.PNG)

**Comment by m3kgin3er** [comment]
Maybe 0983 packet error. I don't know. While no time to solve this

**Comment by NNagatoYuki** [comment]
charBlockSize 147 
0983 packet error modify items_nonstackable type
I have solved.

**Comment by m3kgin3er** [comment]
Amazing. How do you did that ? 
How about '0983' packet error modify items_nonstackable type ?

Can u post the fix ? 
I've understand. When u teleport, it reload your inventory. But i don't understand the coalition since items_nonstackable type looks like working fine better than 0983.

**Comment by Razalka** [comment]
The problem is `Actor:Item` didn't recorded when removed from Inventoy.

`assert(UNIVERSAL::isa($item, 'Actor::Item')) if DEBUG;`

and here's the error.

`Carp::Assert::assert('')`

so, kore didn't assert the **Actor::Item**.

**Comment by Razalka** [comment]
Hello senpai @m3kgin3er 
new unknown switch appeared :smile:
![rakki_new_error](https://cloud.githubusercontent.com/assets/25100730/25272246/5dcab00c-26b1-11e7-830c-0d8fd3d44353.JPG)

**Comment by m3kgin3er** [comment]
Well it can be parsed 'cause its monster bar.
And well, it's added inside serverType0. I don't know why Kore is not reading this sT 0 but ok ! i don't know how to fix and i don't pretend to fix and i don't know who can fix it.

How kore should work  :

If i'm using 2015 sT, read packets from sT0 too.

How it's working : 

If i'm using 2015 sT, just read this packets and some another of sT0. But not 0A27 ¬¬???

**Comment by Razalka** [comment]
Hai senpai @m3kgin3er .
Sorry for late response.
about the teleport problem, maybe i'll check it next week coz im on overseas duty right now.

Hot topic's : idRO-Gravindo, it's a new challenge, i think i'll try to penetrate it there too :grin:

**Comment by m3kgin3er** [comment]
Fuck idRO and vpn

**Comment by m3kgin3er** [comment]
Okay using fly wing :

![image](https://cloud.githubusercontent.com/assets/12580473/25559870/b0c4ca26-2d1a-11e7-809e-055be247a365.png)


Can't reproduce fly wing error in RakkiRO and not in AnkRO. !

**Comment by thehaunted666** [comment]
Can you guys penetrate pRO new Thor and Loki. New server about 1 week OBT.
Ip 116.93.119.116
Port 6900
Master_version and Version is unknown.

**Comment by cesarskatelife** [comment]
Hello, I have the same problem, the map-login package should be 0360 but it does not work, now if instead of being 0360 it's 70EE I can log in and receive basic information such as stat points, friend list, etc ... before the 00B6-NPC Cancel package arrives. if someone can help I would appreciate it.

Use peek to get the revcpackets and also to sniff the packets.

ip 198.50.224.123
port 6900

![login](https://user-images.githubusercontent.com/25091512/37446094-139a3fe8-27fa-11e8-9196-66e33ab133dd.png)
![openkore](https://user-images.githubusercontent.com/25091512/37446100-1bc395de-27fa-11e8-851e-acfe510deefa.png)
