### ISSUE TITLE
How to fix dissconnected from Map server?

### ISSUE THREAD

**Issue by Aquzohr** [OpenKore/openkore#500]
my config i'm use old hmac_key, now isn't working anymore, how can i generate new hmac_key for my sever.

my Rag Client: [Download](https://www.dropbox.com/s/nn53k421sgmibyd/RagEXE.rar?dl=0)

i'm use openkore this: [click](https://github.com/DunstleOS/openkore)

this error: [click](http://imgur.com/a/uhHFI)

**Comment by sctnightcore** [comment]
TH : packet เข้ารหัสด้วยคีย์เฉพาะบางอย่าง
EN : Encrypted packet with some specific keys.
Now, no developers do this.

**Comment by windhamwong** [comment]
No more response from author. We need more data for this. closing.
