### ISSUE TITLE
How to fix invalid char specified Server idRO Chaos

### ISSUE THREAD

**Issue by grimdragonx** [OpenKore/openkore#501]
![char](https://cloud.githubusercontent.com/assets/26145272/24070346/4ac78bf2-0bee-11e7-8b71-663db0a7c120.jpg)

can someone help me how to fix this?

**Comment by itsrachelfish** [comment]
Hi there, thanks for the screenshot! :+1: 

What server are you connecting to?

**Comment by grimdragonx** [comment]
@itsrachelfish its idRO Chaos, can u help me?

**Comment by wimaian** [comment]
Same problem with me , encrypte the $msg in packetperser it a promble

**Comment by wimaian** [comment]
Gan ada disscord @grimdragonx  ?

**Comment by grimdragonx** [comment]
@wimaian GrimDragonX#5343

**Comment by wimaian** [comment]
@itsrachelfish can you help , how to fix that problem ?

**Comment by beesky** [comment]
http://www.nyit-nyit.net/threads/jual-bot-ro-gravindo-200k-diajarin-dikit-pasti-bisa.211209/

**Comment by grimdragonx** [comment]
@beesky lo bisa mati aja kagak? tau etika g sih?

**Comment by irsyad-id** [comment]
@grimdragonx 
because u used rebuilding packet method, 
u should fix your send.pm about character sex and position.

**Comment by grimdragonx** [comment]
@irsyad-id i already fix it but it still error

**Comment by grimdragonx** [comment]
it still invalid char specified, can someone help me? T_T

**Comment by gheghe** [comment]
Try more trick

**Comment by grimdragonx** [comment]
@gheghe yeah right very helpful

please if dont want to help, dont comment

**Comment by walkietalkie89** [comment]
@grimdragonx maybe this? **tables\servers.txt** `charBlockSize 144`

**Comment by grimdragonx** [comment]
It only gives u more error

**Comment by botgratis** [comment]
https://mega.nz/#!APoRUJxT!-ahJzOWjNgw7ksMILXBH0ErvVdU5f81Mc0MXJ6TRlLg

free working bot

**Comment by grimdragonx** [comment]
Wah thx bgt bro

**Comment by grimdragonx** [comment]
@botgratis sniffernya kagak bs bro @_@ kagak nongol apa2

**Comment by kemplung** [comment]
sialan pake share2an, langsung di fix lah tai

**Comment by orgmatileg** [comment]
ngakak wkwkkwkwkw

**Comment by gheghe** [comment]
Ati2 asal donlod..

**Comment by overweightcat** [comment]
Any clarifications already ?

**Comment by deca2708** [comment]
ohh ini toh yang bikin MT dadakan? katanya semalem ada MT dadakan? #teloletdulu

**Comment by orgmatileg** [comment]
om om ganteng kindly invite me to discord group please: luqiman #2770

**Comment by wimaian** [comment]
Blom tembus juga @grimdragonx  ? wadeh

**Comment by grimdragonx** [comment]
@wimaian belom bro, sniffnya salah mulu, udah pake berbagai macam padahal

**Comment by bedebah** [comment]
di share2 sgala ,, langsung update kan .. dongo sih ...

**Comment by SiKemot** [comment]
kindly invite me into group untuk sharing please.. 

@grimdragonx 
itu sniffer harus cari yg versi baru
stelah MT itu sniffer nya ga bs di pakai lagi (useless klo di utak atik trus)
