### ISSUE TITLE
iRO - Izlude \ Byalan Route

### ISSUE THREAD

**Issue by ksands99** [OpenKore/openkore#503]
Hi all,

Sorry this may have been covered previously, however, I am currently looking for a fix that will properly route the bot through Izlude (or Alberta -> Byalan).

I have read on the forums that updating the fields or portals.txt would "resolve" it; however, I had attempted a few of those, and still fails to path correctly. 

Please let me know of anything possible - thanks!

**Comment by SabadyshynV** [comment]
and what is wrong with **portals.txt**? update npc that travels you thats all

**Comment by ksands99** [comment]
I could be incorrect with what exactly is wrong; I am not all that experienced with the OpenKore system. Pretty much all I know for a fact, that going through Izlude (Considered Old Izlude), will not path correctly to Byalan.

**Comment by holoc** [comment]
Where exactly is your bot getting stuck? Does it talk to the correct sailor
npc?

**Comment by ksands99** [comment]
@holoc It does not. Sorry I've been busy. I'll get the coordinates soon.

**Comment by holoc** [comment]
I've run into this before as well. I just manually edited the coordinates in the tables/portals.txt for izlude to izlu2dun. I hope that helps.

**Comment by ksands99** [comment]
@holoc Sounds good - I'll attempt to do so. Still learning, but I appreciate the guidance!

**Comment by kokopoknat** [comment]
Can some one send their portals.txt in here? ive been trying to figure this problem too but i have been failing.. thanks in advance :)

**Comment by holoc** [comment]
@kokopoknat 
In portals.txt:
`izlude 197 205 izlu2dun 107 50 150 c r0`
You can verify the coordinates yourself by using /where in game where the Sailor NPC is located. and replace the first set of coordinates above.

**Comment by kokopoknat** [comment]
@holoc 

bro.. i already put that on portals.. and when i try to command the bot to go to iz_dun00.. he goes to the right side of izlude map... :\ 
any other suggestions?

**Comment by holoc** [comment]
@kokopokhat go in game or check your npc log for the coordinates of the sailor npc that warps you to the island and update the portals.txt accordingly... If you're playing on iro, it should be the same as above though.

**Comment by sumaskidot** [comment]
no solution yet?? looking for a solution tooo..

stuck at looping in and out at tool dealer... at izlude

**Comment by ChrstphrR** [comment]
Cleaning house...

This appears to be routing changes due to GMs/Admins changing the portal/NPC locations.
Better solutions (both on the codebase, and user initiated fixes) are detailed in issue #787 

Please follow up there.  Closing this issue as a duplicate.
