### ISSUE TITLE
Help to resolve unknown packet ABCD

### ISSUE THREAD

**Issue by k1nt4r0** [OpenKore/openkore#504]
i try to playing on a server with gepard shield
the problem is about encrypted packet.
i think the packet should be dc 01
but i got ABCD

**Comment by SabadyshynV** [comment]
Solution to gepard shield is not - aw sry we forgot to put it in openkore... u really need to know programing to do that -_-

**Comment by m3kgin3er** [comment]
close your thread :D

**Comment by alisonrag** [comment]
gepard are not supported
