### ISSUE TITLE
Timeout on Character Server, reconnecting. wait 30 seconds...

### ISSUE THREAD

**Issue by rossevelts** [OpenKore/openkore#505]
From yesterday OK is working.. But after relog i can't reconnecting again..
From 1 pm this day the hex is useless..
someone can give me clue for this issue?
Thankyou before

![bahan](https://cloud.githubusercontent.com/assets/26046989/24098545/7ffc3466-0d9d-11e7-9b85-26531dbc9635.png)

**Comment by gummyruler** [comment]
..
