### ISSUE TITLE
Unknown Switch 0983 and 0984 - Iro

### ISSUE THREAD

**Issue by hendra814** [OpenKore/openkore#507]
Using lastest Ok, from Github
connect into renewal server, it show Packet Parser: Unkwon switch: 0983 and sometime 0984.
and detail character at window bar it's show error for name character, base level and job level.

**Comment by walkietalkie89** [comment]
you should handle the switch actor_status_active to 0983 or 0984. and don't forget to add in your recvpackets.txt if not exist

**Comment by hendra814** [comment]
how to do that?
for revpacket it's already in there for last git hub

**Comment by walkietalkie89** [comment]
something like
```
sub new {
	my ($class) = @_;
	my $self = $class->SUPER::new(@_);
	my %packets = (
		#'0983' => ['actor_status_active', 'v a4 C V5', [qw(type ID flag total tick unknown1 unknown2 unknown3)]],
		#'0984' => ['actor_status_active', 'a4 v V5', [qw(ID type total tick unknown1 unknown2 unknown3)]],
	);

	foreach my $switch (keys %packets) {
		$self->{packet_list}{$switch} = $packets{$switch};
	}

	#my %handlers = qw(
	#	actor_status_active 0983
	#	actor_status_active 0984
	#);
	#$self->{packet_lut}{$_} = $handlers{$_} for keys %handlers;

	return $self;
}


```

**Comment by hendra814** [comment]
OK, I'll try it.

**Comment by ZaskarAlpha** [comment]
sir i'm confused and new to botting. where to i find this file?

**Comment by m3kgin3er** [comment]
Well, you should add these lines  : 
```
		'0983' => ['actor_status_active', 'v a4 C V5', [qw(type ID flag total tick unknown1 unknown2 unknown3)]],
		'0984' => ['actor_status_active', 'a4 v V5', [qw(ID type total tick unknown1 unknown2 unknown3)]],
```

**Comment by ZaskarAlpha** [comment]
I added those lines but it resulted in another problem. 

this it how it looks in my network file. btw it keeps on calculating lock map route. why is that. 
#########################################################################
#  OpenKore - Network subsystem
#  Copyright (c) 2006 OpenKore Team
#
#  This software is open source, licensed under the GNU General Public
#  License, version 2.
#  Basically, this means that you're allowed to modify and distribute
#  this software. However, if you distribute modified versions, you MUST
#  also distribute the source code.
#  See http://www.gnu.org/licenses/gpl.html for the full license.
#########################################################################
# Servertype overview: http://wiki.openkore.com/index.php/ServerType
package Network::Receive::iRO::Classic;

use strict;
use base qw(Network::Receive::ServerType0);

sub new {
	my ($class) = @_;
	my $self = $class->SUPER::new(@_);
	my %packets = (
		
'0078' => ['actor_exists', 'C a4 v14 a4 a2 v2 C2 a3 C3 v', [qw(object_type ID walk_speed opt1 opt2 option type hair_style weapon lowhead shield tophead midhead hair_color clothes_color head_dir guildID emblemID manner opt3 stance sex coords unknown1 unknown2 act lv)]], # 55 # standing
		
'007C' => ['actor_connected', 'C a4 v14 C2 a3 C2', [qw(object_type ID walk_speed opt1 opt2 option hair_style weapon lowhead type shield tophead midhead hair_color clothes_color head_dir stance sex coords unknown1 unknown2)]], # 42 # spawning
		
'0097' => ['private_message', 'v Z24 V Z*', [qw(len privMsgUser flag privMsg)]], # -1
		
'022C' => ['actor_moved', 'C a4 v3 V v5 V v5 a4 a2 v V C2 a6 C2 v',	[qw(object_type ID walk_speed opt1 opt2 option type hair_style weapon shield lowhead tick tophead midhead hair_color clothes_color head_dir guildID emblemID manner opt3 stance sex coords unknown1 unknown2 lv)]], # 65 # walking
	);

	foreach my $switch (keys %packets) {
		$self->{packet_list}{$switch} = $packets{$switch};
	}

	my %handlers = qw(
		received_characters 082D
	);
	$self->{packet_lut}{$_} = $handlers{$_} for keys %handlers;

	return $self;
}

1; 
'099D' => ['received_characters', 'x2 a*', [qw(charInfo)]],
'0983' => ['actor_status_active', 'v a4 C V5', [qw(type ID flag total tick unknown1 unknown2 unknown3)]],
'0984' => ['actor_status_active', 'a4 v V5', [qw(ID type total tick unknown1 unknown2 unknown3)]],

is this right??

**Comment by hendra814** [comment]
Because now i've got new error with lastest OK. so i'm decide to close this issue.

Thanks all.
