### ISSUE TITLE
BOT Gravindo Openkore Work 21-03-2017

### ISSUE THREAD

**Issue by arcFIT** [OpenKore/openkore#508]
BOT Gravindo Openkore Work 21-03-2017
Yang berminat BOT untuk server gravindo
saya jual dan tutorial cara nya dijamin mudah
WA 0812 1072 3769

**Comment by gheghe** [comment]
Ban ip this suck

**Comment by arcFIT** [comment]
BOT Gravindo Openkore Work 21-03-2017
Yang berminat BOT untuk server gravindo
saya jual dan tutorial cara nya dijamin mudah
WA 0812 1072 3769
