### ISSUE TITLE
Packet Parser: Unknown switch: 0A36

### ISSUE THREAD

**Issue by issueaccpost** [OpenKore/openkore#509]
while i am on my alchi with my homunculi 

everytime when i attack

Packet Parser: Unknown switch: 0A36

Server fro

**Comment by Razalka** [comment]
@issueaccpost 
Try add this in src/Network/Receive/fRO.pm

'0A36' => ['homunculus_property', 'Z24 C v16 V2 v2', [qw(name state level hunger intimacy accessory atk matk hit critical def mdef flee aspd hp hp_max sp sp_max exp exp_max points_skill attack_range)]],

**Comment by m3kgin3er** [comment]
It's already inside sT0.
