### ISSUE TITLE
Poseidon kRO_RagexeRE_2013_08_07a

### ISSUE THREAD

**Issue by Glowned** [OpenKore/openkore#510]
Hello,
I'm able to connect via openkore to a private server which uses a **kRO_RagexeRE_2013_08_07a** exe.
But it seems that there is a hackshield on it and i would like to use Poseidon , here is my issue : 

By default, there is no servertype matching this .exe in OpenKore. So i decided to create it myself, and all my tests resulted in a bug on the connection to the local ragnarok server (poseidon) : 

> CHARACTER_INFO size error !! character num : 1 CHARACTER_INFO size : 144

I have a guess on what it means, but i set my custom servertype to this charBlockSize, and the proper conf into poseidon.txt.

Poseidon.txt: 
```

# Ragnarok Server
# Here you'll define the IP Address and the Port where Poseidon
# will keep waiting for your ragnarok online client to connect.
ragnarokserver_ip=127.0.0.1
ragnarokserver_port=6900

# Query Server
# Here you'll define the IP Address and the Port where Poseidon
# will keep waiting for open kore to connect and send the GG/HS queries.
queryserver_ip=127.0.0.1
queryserver_port=24390

# Server Type
# Here you have to specify your current server type in order
# to the poseidon operate properly !
# The available server types for now are : Default, bRO_.* (check servertypes.txt)
# You should modify this if you're having problems with char list.
server_type=kRO_RagexeRE_2013_08_07a

# Char Block Size
# Here you can specify the desired CharBlockSize your client requires
# The available block sizes are : 106, 108, 112, 116, 128, 132 and 136
CharBlockSize=144

```

servertypes.txt : 

```

[Default]
decrypt_mid 0
charBlockSize 116
charListPacket 0x6b
maploginPacket 0000

[bRO_2016-11-01a]
decrypt_mid 1
decrypt_mid_keys 0x6D9253BB 0x7DB60BB3 0x3AD51C28
charBlockSize 124
charListPacket 0x82d
maploginPacket 0870

[bRO_2016-11-08a]
decrypt_mid 1
decrypt_mid_keys 0x17AC78C2 0x1ADE5C66 0x2A84793C
charBlockSize 124
charListPacket 0x82d
maploginPacket 088E

[tRO_2013-07-09a]
decrypt_mid 1
decrypt_mid_keys 0x6441767a 0x71020102 0x48c21f02 # K A M
charBlockSize 144

[kRO_RagexeRE_2013_08_07a]
decrypt_mid 1
dectypt_mid_keys 0x975EDB56 0x69F3DE78 0x7D27B6B5
charBlockSize 144

```

Note : I used the keys in my **/src/Network/Send/kRO/RagexeRE_2013_08_07a.pm** to fill the  the **decrypt_mid_keys**

I can't find any help on Google / Forums etc. I'm a good developer, but very weak when it concerns packets and other network things.. :( 

Thanks in advance !

**Comment by walkietalkie89** [comment]
is your **tables\servers.txt** `charBlockSize 144` too?

**Comment by Glowned** [comment]
yes, but the problem comes before the OpenKore connection, when i try to connect to poseidon server using the ragexe client.

**Comment by Novishivsmoke** [comment]
Did u set gameGuard variable in your config with what ? 

1 ? 2 ? 0 ? 3 ? 5 ? 1000 ?

**Comment by Glowned** [comment]
I set gameGuard variable to 1

**Comment by alisonrag** [comment]
poseidon only suport gameguard packets, you will need to rewrite the entire code for update to another shield
