### ISSUE TITLE
Failed to retrieve recvpackets 2015-05-13aRagexe

### ISSUE THREAD

**Issue by Skeec** [OpenKore/openkore#512]
Hello,
I was trying to extract recvpackets.txt with PEEK but it didn't work maybe due to themida obfuscation?
Well I can't find any support for newer exes.

Here is the [download](http://www.mediafire.com/file/3bk6i96pxi45d5c/2015-05-13aRagexe.exe)

Welp maybe anyone can help me?

Sincerly Yours

**Comment by Razalka** [comment]
`0064 55
0065 17
0066 3
0067 37
0068 46
0069 -1
006A 23
006B -1
006C 3
006D 149
006E 3
006F 2
0070 3
0071 28
0072 22
0073 11
0074 3
0075 -1
0076 9
0077 5
0078 55
0079 53
007A 58
007B 60
007C 44
007D 2
007E 105
007F 6
0080 7
0081 3
0082 2
0083 2
0084 2
0085 10
0086 16
0087 12
0088 10
0089 11
008A 29
008B 23
008C 14
008D -1
008E -1
0090 7
0091 22
0092 28
0093 2
0094 19
0095 30
0096 -1
0097 -1
0098 3
0099 -1
009A -1
009B 34
009C 9
009D 17
009E 17
009F 20
00A0 23
00A1 6
00A2 14
00A3 -1
00A4 -1
00A5 -1
00A6 -1
00A7 9
00A8 7
00A9 6
00AA 9
00AB 4
00AC 7
00AE -1
00AF 6
00B0 8
00B1 8
00B2 3
00B3 3
00B4 -1
00B5 6
00B6 6
00B7 -1
00B8 7
00B9 6
00BA 2
00BB 5
00BC 6
00BD 44
00BE 5
00BF 3
00C0 7
00C1 2
00C2 6
00C3 8
00C4 6
00C5 7
00C6 -1
00C7 -1
00C8 -1
00C9 -1
00CA 3
00CB 3
00CC 6
00CD 3
00CE 2
00CF 27
00D0 3
00D1 4
00D2 4
00D3 2
00D4 -1
00D5 -1
00D6 3
00D7 -1
00D8 6
00D9 14
00DA 3
00DB -1
00DC 28
00DD 29
00DE -1
00DF -1
00E0 30
00E1 30
00E2 26
00E3 2
00E4 6
00E5 26
00E6 3
00E7 3
00E8 8
00E9 19
00EA 5
00EB 2
00EC 3
00ED 2
00EE 2
00EF 2
00F0 3
00F1 2
00F2 6
00F3 -1
00F4 21
00F5 11
00F6 8
00F7 17
00F8 2
00F9 26
00FA 3
00FB -1
00FC 6
00FD 27
00FE 30
00FF 10
0100 2
0101 6
0102 6
0103 30
0104 79
0105 31
0106 10
0107 10
0108 -1
0109 -1
010A 4
010B 6
010C 6
010D 2
010E 11
010F -1
0110 10
0111 39
0112 4
0113 25
0114 31
0115 35
0116 17
0117 18
0118 2
0119 13
011A 15
011B 20
011C 68
011D 2
011E 3
011F 16
0120 6
0121 14
0122 -1
0123 -1
0124 21
0125 8
0126 8
0127 8
0128 8
0129 8
012A 2
012B 2
012C 3
012D 4
012E 2
012F -1
0130 6
0131 86
0132 6
0133 -1
0134 -1
0135 7
0136 -1
0137 6
0138 3
0139 16
013A 4
013B 4
013C 4
013D 6
013E 24
013F 26
0140 22
0141 14
0142 6
0143 10
0144 23
0145 19
0146 6
0147 39
0148 8
0149 9
014A 6
014B 27
014C -1
014D 2
014E 6
014F 6
0150 110
0151 6
0152 -1
0153 -1
0154 -1
0155 -1
0156 -1
0157 6
0159 54
015A 66
015B 54
015C 90
015D 42
015E 6
015F 42
0160 -1
0161 -1
0162 -1
0163 -1
0164 -1
0165 30
0166 -1
0167 3
0168 14
0169 3
016A 30
016B 10
016C 43
016D 14
016E 186
016F 182
0170 14
0171 30
0172 10
0173 3
0174 -1
0175 6
0176 106
0177 -1
0178 4
0179 5
017A 4
017B -1
017C 6
017D 7
017E -1
017F -1
0180 6
0181 3
0182 106
0183 10
0184 10
0185 34
0187 6
0188 8
0189 4
018A 4
018B 4
018C 29
018D -1
018E 10
018F 6
0190 23
0191 86
0192 24
0193 2
0194 30
0195 102
0196 9
0197 4
0198 8
0199 4
019A 14
019B 10
019C -1
019D 6
019E 2
019F 6
01A0 3
01A1 3
01A2 37
01A3 5
01A4 11
01A5 26
01A6 -1
01A7 4
01A8 4
01A9 6
01AA 10
01AB 12
01AC 6
01AD -1
01AE 4
01AF 4
01B0 11
01B1 7
01B2 -1
01B3 67
01B4 12
01B5 18
01B6 114
01B7 6
01B8 3
01B9 6
01BA 26
01BB 26
01BC 26
01BD 26
01BE 2
01BF 3
01C0 2
01C1 14
01C2 10
01C3 -1
01C4 22
01C5 22
01C6 4
01C7 2
01C8 13
01C9 97
01CA 3
01CB 9
01CC 9
01CD 30
01CE 6
01CF 28
01D0 8
01D1 14
01D2 10
01D3 35
01D4 6
01D5 -1
01D6 4
01D7 11
01D8 54
01D9 53
01DA 60
01DB 2
01DC -1
01DD 47
01DE 33
01DF 6
01E0 30
01E1 8
01E2 34
01E3 14
01E4 2
01E5 6
01E6 26
01E7 2
01E8 28
01E9 81
01EA 6
01EB 10
01EC 26
01ED 2
01EE -1
01EF -1
01F0 -1
01F1 -1
01F2 20
01F3 10
01F4 32
01F5 9
01F6 34
01F7 14
01F8 2
01F9 6
01FA 48
01FB 56
01FC -1
01FD 15
01FE 5
01FF 10
0200 26
0201 -1
0202 2
0203 10
0204 18
0205 26
0206 11
0207 34
0208 14
0209 36
020A 10
020D -1
020E 32
0212 26
0213 26
0214 42
0215 6
0216 6
0217 2
0218 2
0219 282
021A 282
021B 10
021C 10
021D 6
021E 6
021F 66
0220 10
0221 -1
0222 6
0223 8
0224 10
0225 2
0226 282
0227 18
0228 18
0229 15
022A 58
022B 57
022C 65
022D 2
022E 71
022F 5
0230 12
0231 26
0232 9
0233 11
0234 6
0235 -1
0236 10
0237 2
0238 282
0239 11
023A 4
023B -1
023C 6
023D 6
023E 8
023F 2
0240 -1
0241 6
0242 -1
0243 6
0244 6
0245 3
0246 4
0247 8
0248 -1
0249 3
024A 70
024B 4
024C 8
024D 12
024E 6
024F 10
0250 3
0251 34
0252 -1
0253 3
0254 3
0255 5
0256 5
0257 8
0258 2
0259 3
025A -1
025B 6
025C 4
025D 6
025E 4
025F 6
0260 6
0261 11
0262 11
0263 11
0264 20
0265 20
0266 30
0267 4
0268 4
0269 4
026A 4
026B 4
026C 4
026D 4
026F 2
0270 2
0271 40
0272 44
0273 30
0274 8
0275 37
0276 -1
0277 84
0278 2
0279 2
027A -1
027B 14
027C 60
027D 62
027E -1
027F 8
0280 12
0281 2
0282 284
0283 6
0284 14
0285 6
0286 4
0287 -1
0288 -1
0289 12
028A 18
028B -1
028C 46
028D 34
028E 4
028F 6
0290 4
0291 4
0292 2
0293 70
0294 10
0295 -1
0296 -1
0297 -1
0298 8
0299 6
029A 27
029B 80
029C 66
029D -1
029E 11
029F 3
02A2 8
02A5 8
02A6 -1
02A7 -1
02AA 4
02AB 36
02AC 6
02AD 8
02B0 85
02B1 -1
02B2 -1
02B3 107
02B4 6
02B5 -1
02B6 7
02B7 7
02B8 22
02B9 191
02BA 11
02BB 8
02BC 6
02C1 -1
02C2 -1
02C4 2
02C5 30
02C6 30
02C7 7
02C8 3
02C9 3
02CA 3
02CB 65
02CC 4
02CD 71
02CE 10
02CF 6
02D0 -1
02D1 -1
02D2 -1
02D3 4
02D4 29
02D5 2
02D6 6
02D7 -1
02D8 10
02D9 10
02DA 3
02DB -1
02DC -1
02DD 32
02DE 6
02DF 36
02E0 34
02E1 33
02E2 20
02E3 22
02E4 11
02E5 9
02E6 6
02E7 -1
02E8 -1
02E9 -1
02EA -1
02EB 13
02EC 67
02ED 59
02EE 60
02EF 8
02F0 10
02F1 2
02F2 2
02F3 -1
02F4 3
02F5 7
02F6 7
035C 2
035D -1
035E 2
035F 2
0360 19
0361 2
0362 2
0363 5
0364 8
0365 2
0366 90
0367 2
0368 6
0369 7
03DD 18
03DE 18
0436 6
0437 6
0438 10
0439 8
043D 8
043E -1
043F 25
0440 10
0441 4
0442 -1
0443 8
0444 -1
0445 10
0446 14
0447 2
0448 -1
0449 4
044A 6
044B 2
07D7 8
07D8 8
07D9 268
07DA 6
07DB 8
07DC 6
07DD 54
07DE 30
07DF 54
07E0 58
07E1 15
07E2 8
07E3 6
07E4 2
07E5 4
07E6 8
07E7 32
07E8 -1
07E9 5
07EA 2
07EB -1
07EC 26
07ED 10
07EE 6
07EF 8
07F0 6
07F1 18
07F2 8
07F3 6
07F4 3
07F5 6
07F6 14
07F7 -1
07F8 -1
07F9 -1
07FA 8
07FB 25
07FC 10
07FD -1
07FE 26
0800 -1
0801 -1
0802 2
0803 4
0804 14
0805 -1
0806 2
0807 4
0808 14
0809 50
080A 18
080B 6
080C 2
080D 3
080E 14
080F 20
0810 3
0811 18
0812 8
0813 -1
0814 86
0815 -1
0816 6
0817 2
0818 -1
0819 -1
081A 4
081B 10
081C 10
081D 22
081E 8
081F -1
0820 11
0821 2
0822 9
0823 -1
0824 6
0825 -1
0827 6
0828 14
0829 12
082A 10
082B 6
082C 10
082D -1
0835 2
0836 -1
0837 3
0838 12
0839 66
083A 5
083B 2
083C 10
083D 6
083E 26
0840 -1
0841 4
0842 6
0843 6
0844 2
0845 10
0846 4
0847 -1
0848 -1
0849 16
084A 2
084B 19
084C 10
084D 10
084E 5
084F 6
0850 7
0851 -1
0852 2
0853 -1
0854 -1
0855 6
0856 -1
0857 -1
0858 -1
0859 -1
085A 2
085B 2
085C 2
085D 2
085E 2
085F 2
0860 2
0861 2
0862 2
0863 2
0864 2
0865 2
0866 2
0867 2
0868 2
0869 2
086A 2
086B 2
086C 2
086D 2
086E 2
086F 2
0870 2
0871 2
0872 2
0873 2
0874 2
0875 2
0876 2
0877 2
0878 2
0879 2
087A 2
087B 2
087C 2
087D 2
087E 2
087F 2
0880 2
0881 2
0882 2
0883 2
0884 2
0885 2
0886 6
0887 6
0888 2
0889 2
088A 2
088B 8
088C 2
088D 5
088E 2
088F 2
0890 2
0891 2
0892 2
0893 2
0894 2
0895 2
0896 2
0897 2
0898 2
0899 2
089A 2
089B 2
089C 2
089D 2
089E 2
089F 2
08A0 2
08A1 2
08A2 2
08A3 4
08A4 2
08A5 26
08A6 2
08A7 2
08A8 2
08A9 2
08AA 2
08AB 2
08AC 2
08AD 2
08AF 10
08B0 17
08B1 -1
08B2 -1
08B3 -1
08B4 2
08B5 6
08B6 3
08B8 10
08B9 12
08BA 10
08BB 8
08BC 10
08BD 8
08BE 14
08BF 8
08C0 -1
08C1 2
08C2 2
08C3 10
08C4 8
08C5 6
08C6 4
08C7 -1
08C8 34
08C9 2
08CA -1
08CB -1
08CC 109
08CD 10
08CE 2
08CF 10
08D0 9
08D1 7
08D2 10
08D3 10
08D4 8
08D5 -1
08D6 6
08D7 28
08D8 27
08D9 30
08DA 26
08DB 27
08DC 26
08DD 27
08DE 27
08DF 50
08E0 51
08E1 51
08E2 27
08E3 149
08E4 6
08FC 30
08FD 6
08FE -1
08FF 24
0900 -1
0901 -1
0902 -1
0903 -1
0904 -1
0905 -1
0906 -1
0907 5
0908 5
090A 26
090D -1
090E 2
090F -1
0910 10
0911 30
0912 10
0913 30
0914 -1
0915 -1
0916 26
0917 2
0918 2
0919 2
091A 2
091B 2
091C 2
091D 2
091E 2
091F 2
0920 2
0921 2
0922 2
0923 2
0924 2
0925 2
0926 2
0927 2
0928 5
0929 2
092A 2
092B 2
092C 2
092D 2
092E 2
092F 2
0930 2
0931 2
0932 2
0933 2
0934 2
0935 2
0936 2
0937 2
0938 2
0939 8
093A -1
093B 2
093C 2
093D 2
093E 2
093F 2
0940 36
0941 2
0942 2
0943 2
0944 2
0945 2
0946 2
0947 2
0948 2
0949 2
094A 2
094B 2
094C 2
094D 2
094E 2
094F 2
0950 2
0951 2
0952 2
0953 2
0954 2
0955 2
0956 2
0957 2
0958 2
0959 2
095A 2
095B 2
095C 2
095D 2
095E 2
095F 2
0960 2
0961 2
0962 2
0963 2
0964 6
0965 2
0966 2
0967 2
0968 2
0969 2
096A 2
096B 4
096C 6
096D -1
096E -1
096F 7
0970 31
0971 6
0972 -1
0973 7
0974 2
0975 -1
0976 -1
0977 14
0978 6
0979 50
097A -1
097B -1
097C 4
097D 288
097E 12
097F -1
0980 7
0981 -1
0982 7
0983 29
0984 28
0985 -1
0986 10
0987 -1
0988 6
0989 2
098A -1
098B 2
098C 4
098D -1
098E -1
098F -1
0990 31
0991 -1
0992 -1
0993 -1
0994 -1
0995 -1
0996 -1
0997 -1
0998 8
0999 11
099A 9
099B 8
099C 6
099D -1
099E 12
099F -1
09A0 6
09A1 2
09A2 6
09A3 -1
09A4 18
09A5 7
09A6 12
09A7 10
09A8 16
09A9 10
09AA 16
09AB 6
09AC -1
09AD 10
09AE 17
09AF 4
09B0 8
09B1 4
09B2 8
09B3 4
09B4 6
09B5 2
09B6 6
09B7 4
09B8 6
09B9 4
09BA 2
09BB 6
09BC 6
09BD 2
09BE 2
09BF 4
09C1 10
09C2 -1
09C3 8
09C4 8
09C5 1042
09C6 -1
09C7 18
09C8 -1
09C9 -1
09CA -1
09CB 17
09CC -1
09CD 8
09CE 102
09CF -1
09D0 -1
09D1 14
09D2 -1
09D3 -1
09D4 2
09D5 -1
09D6 -1
09D7 -1
09D8 2
09D9 4
09DA -1
09DB -1
09DC -1
09DD -1
09DE -1
09DF 7
09E0 -1
09E1 8
09E2 8
09E3 8
09E4 8
09E5 18
09E6 22
09E7 3
09E8 11
09E9 2
09EA 11
09EB -1
09EC -1
09ED 3
09EE 11
09EF 11
09F0 -1
09F1 11
09F2 12
09F3 11
09F4 12
09F5 11
09F6 11
09F7 75
09F8 -1
09F9 143
09FA -1
09FB -1
09FC 6
09FD -1
09FE -1
09FF -1
0A00 269
0A01 3
0A02 4
0A03 2
0A04 6
0A05 53
0A06 6
0A07 9
0A08 26
0A09 45
0A0A 47
0A0B 47
0A0C 56
0A0D -1
0A0E 14
0A0F -1
0A10 -1
0A11 -1
0A12 27
0A13 26
0A14 10
0A15 12
0A16 26
0A17 6
0A18 14
0A19 2
0A1A 23
0A1B 2
0A1C -1
0A1D 2
0A1E 3
0A1F 2
0A20 21
0A21 3
0A22 5
0A23 -1
0A24 66
0A25 6
0A26 7
0A27 8
0A28 3
0A29 6
0A2A 6
0A2B 14
0A2C 12
0A2D -1
0A2E 6
0A2F 7
0A30 106
0A31 -1
0A32 2
0A33 7
0A34 6
0A35 4
0A36 7
0A37 57
0A38 3
0A39 36
0A3A 12
0A3B -1
0A3C -1
0A3D 18
0A3E -1
0A3F 9
0A40 11
0A41 18
0A42 43
0A43 85
0A44 -1
0A45 2
0A46 14
0A47 3
0A48 2
`

**Comment by Skeec** [comment]
Thank you you da real MVP :+1:

**Comment by Skeec** [comment]
Ow I still timeout on map server

**Comment by Razalka** [comment]
Try to find the guide to use the packet keys in openkore forums.
Timout on map server because the packet keys, not the recvpackets.

**Comment by Skeec** [comment]
I used them as storageEncryptKey in server.txt isnt that right?

**Comment by Razalka** [comment]
nope, that's different.
Follow this guide.
[http://forums.openkore.com/viewtopic.php?f=6&t=211637](url)

**Comment by Skeec** [comment]
The link is broken but I know where to put them but they're already in there src/Network/Receive/kRO/RagexeRE_2015_05_13a.pm
btw I'm using the fork of https://github.com/Novishivsmoke/openkore

Current setup is:
[epicRO] 
ip 188.165.199.187
port 6900
version 30
master_version 16
private 1
recvpackets recvpackets.txt
serverType kRO_RagexeRE_2015_05_13a
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2015_05_13a;translated;translated/kRO_english;kRO

**Comment by Razalka** [comment]
Find it here.
src/Network/Send/kRO/RagexeRE_2015_05_13a.pm

and find the packet keys script like this in the bottom.
`while (my ($k, $v) = each %packets) { $handlers{$v->[0]} = $k}

$self->{packet_lut}{$_} = $handlers{$_} for keys %handlers;
# $self->cryptKeys(?1657302281, ?288101181, ?1972653847);
return $self;
}

1;`

copy paste this script and remove the "#". 
`# $self->cryptKeys(0x62C86D09, 0x75944F17, 0x112C133D);`

**Comment by Skeec** [comment]
Tried that too still getting timeouts

**Comment by Razalka** [comment]
seriously ?
with that key ?
maybe your RO used a custom packet keys, try to find it out with packet sniffer.

**Comment by Skeec** [comment]
yeah with that key.

Can you help me? PEEK fails for me download is in first post and epicro.de is the website for the whole client.

**Comment by Razalka** [comment]
Tested.
use the recvpackets from me before, and try to logged in with/without the packet keys.
tried and successfully logged in.

![done](https://cloud.githubusercontent.com/assets/25100730/24277133/c5576a08-106d-11e7-9d6c-615146986ee2.JPG)

**Comment by chrislong93** [comment]
@Razalka 

Dear sir, I also am having a problem connecting to this particular server. The main reason is I think its because its a new client ,timestamp 2015. I have tried your recvpackets but havent been able to penetrate "Account Server" . Would you please kindly have a look? Thank you.

www.rokvn.com

https://www.dropbox.com/s/ahv5l6pkixj2mcc/ROKVN%203%20exe.7z?dl=0

There are 3 exes files in the zip, 1 launcher and 2 Ragexe . 

Thank you again !

**Comment by Razalka** [comment]
@chrislong93 
At least post your server.txt

**Comment by Fruitjes** [comment]
Hi @Razalka, i have the same Incomming Data Left Error like Skeec. You said you made a connection, can you tell us what you do or upload your version? maybe we missconfigured something somewhere bc we are noobs 👶

**Comment by Skeec** [comment]
Wow thats great you could log in but before Iwas just doing that I mean your recvpackets without the keys did you use my settings and the fork from https://github.com/Novishivsmoke/openkore?

**Comment by chrislong93** [comment]
@Razalka  

Here you are sir 

ip 103.9.159.142
port 7900
master_version 214 
version 53
serverType kRO_RagexeRE_2014_10_22b  
serverEncoding Western
recvpackets recvpackets.txt  (your recvpackets in the previous post)
charBlockSize 144
addTableFolders kRO;iRO

**Comment by Razalka** [comment]
@Skeec 
Yup , i used your setting with my recvpackets.
this the key.
`$self->cryptKeys(0x62C86D09,0x112C133D,0x75944F17);`
or you can just disable itu with "#" mark in front of the script, the OP still can logging in.

and here's the server, just delete recvpackets recvpackets.txt
> [epicRO] 
ip 188.165.199.187
port 6900
version 30
master_version 16
private 1
serverType kRO_RagexeRE_2015_05_13a
serverEncoding Western
charBlockSize 147
addTableFolders kRO/RagexeRE_2015_05_13a;translated;translated/kRO_english;kRO

**Comment by Razalka** [comment]
@chrislong93 
master_version 214 ?
try to follow this guide to find the right server connectivity.
[http://forums.openkore.com/viewtopic.php?f=6&t=211637](url)

**Comment by Fruitjes** [comment]
@Razalka it still wont work for me. 
maybe the src/Network/Send/kRO/RagexeRE_2015_05_13a.pm is wrong by us? (see below)
or where did you put your recvpackets.txt localy?


`package Network::Send::kRO::RagexeRE_2015_05_13a;

use strict;
use base qw(Network::Send::kRO::RagexeRE_2014_10_22b);

sub new {
my ($class) = @_;
my $self = $class->SUPER::new(@_);

	my %packets = (
	'0958' => ['item_take', 'a4', [qw(ID)]],
	'0885' => ['item_drop', 'v2', [qw(index amount)]],
	'0879' => ['storage_item_add', 'v V', [qw(index amount)]],
	'0864' => ['storage_item_remove', 'v V', [qw(index amount)]],
	'0438' => ['skill_use_location', 'v4', [qw(lv skillID x y)]],
	'0363' => ['map_login', 'a4 a4 a4 V C', [qw(accountID charID sessionID tick sex)]],
	'0924' => ['actor_look_at', 'v C', [qw(head body)]],
	'022D' => undef,
	'022D' => ['party_join_request_by_name', 'Z24', [qw(partyName)]],
	'08A8' => ['friend_request', 'a*', [qw(username)]],#26
	'0817' => ['homunculus_command', 'v C', [qw(commandType, commandID)]],
	'0923' => ['storage_password'],
	);

$self->{packet_list}{$_} = $packets{$_} for keys %packets;

my %handlers = qw(
	friend_request 08A8
	homunculus_command 0817
	item_drop 0885
	item_take 0958
	map_login 0363
	party_join_request_by_name 022D
	skill_use 083C
	skill_use_location 0438
	storage_item_add 0879
	storage_item_remove 0864
	storage_password 0923
);
while (my ($k, $v) = each %packets) { $handlers{$v->[0]} = $k}

$self->{packet_lut}{$_} = $handlers{$_} for keys %handlers;
#$self->cryptKeys(?1657302281, ?288101181, ?1972653847);
$self->cryptKeys(0x62C86D09, 0x75944F17,0x112C133D);
return $self;
}

1;
`

**Comment by Razalka** [comment]
@Fruitjes 
put the recvpackets here.
tables/kRO/RagexeRE_2015_05_13a.
overwrite the dafault one, or just rename it.
and use the server.txt from me above.

**Comment by chrislong93** [comment]
@Skeec 

Hi , where did you get the Send and Receive.pm for 2015  ? Thank you

**Comment by Skeec** [comment]
its in the fork

**Comment by Skeec** [comment]
@Razalka thank you its working now I have an unknown switch warning well its working now thank you
"""
Packet Parser: Unknown switch: 0A0C
"""

**Comment by chrislong93** [comment]
@Skeec 

I was about to tell you the same thing haha it works for your server epicRo

Im still waiting for my Rokvn huhu :(

**Comment by Skeec** [comment]
your master version and version are wrong you need to check them from your client

**Comment by chrislong93** [comment]
@Skeec  
Can you please not close the topic im still waiting for Razalka huhu :( 

I checked from both sides : GRF and WPE , tried different version and master version but not correct.
I have followed the connectivity guide.

Still tho :((( 

![image](https://cloud.githubusercontent.com/assets/26244945/24285944/415bec96-10a5-11e7-93ab-49710304bd6f.png)

**Comment by Skeec** [comment]
Open a new issue instead the problem is fixed now your screen just says you are connected

**Comment by chrislong93** [comment]
![image](https://cloud.githubusercontent.com/assets/26244945/24286030/b5d5bfb6-10a5-11e7-893b-9d3cbf488b3f.png)

@Skeec 

It stayed that way forever, the above bar on openkore says not connected :(  
Please kindly help

**Comment by chrislong93** [comment]
@Skeec 
Since I couldnt find login packets **64 00** or **02 B0**, I had to use GRF like I mentioned above.
It is not connected, it stays that way forever :( 

Please kindly help 
![image](https://cloud.githubusercontent.com/assets/26244945/24286143/5e8e4c68-10a6-11e7-9c94-f42bad516a44.png)

**Comment by Razalka** [comment]
@Skeec
Just add `0A0C -1` in the bottom of recvpackets.txt

@chrialong93
I'll check your exe.

**Comment by chrislong93** [comment]
@Razalka 
Thank you senpai !

**Comment by Marci7** [comment]
@Skeec @Fruitjes   
How did you solve the Problem?
Got still timeouts...

**Comment by Fruitjes** [comment]
I don't know, i can Test it later when im back home. But @skeec could upload his file. It seems working for him

⁣Gesendet mit TypeApp ​

**Comment by Skeec** [comment]
I used @Razalka files

**Comment by Fruitjes** [comment]
Working for me now. Thank you @Razalka

**Comment by chrislong93** [comment]
@Razalka  any news sir?

**Comment by Razalka** [comment]
Just be patient its friday night lol

**Comment by Razalka** [comment]
@chrislong93 
Your server is encrypted, and its's ubottable server.
even if you can login , there's must be a lot of unknown packet.
just forget it, its unbottable.
try using XKore 2/3 mode.

**Comment by ramaon** [comment]
@Razalka can you help me at idRO :)

**Comment by raidensna** [comment]
@Razalka is there any chance that you can help me to obtain the packet keys and crypt keys for the following private server? I have more tan 1 week trying to obtain them with no luck:

ip 104.248.237.34
port 6900
master_version 1
version 55
serverType kRO_RagexeRE_2018_05_02b
addTableFolders RO
charBlockSize 155
pinCode 1
serverEncoding Western
recvpackets recvpackets.txt
clientHash AE318C5D1FB0A19C400E0377D47A418C
sendCryptKeys ??????????
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
gameGuard 0

Attached the Ragexe.exe
https://wetransfer.com/downloads/fe9e216c269bd2a2ff1f4ee66ba837dd20191201031536/83e01cf20f409ef6c61d41fb0f2b1dc520191201031536/d63e1a

Already try with PEEK, Extractor V3, RO Tools, etc with no luck (Couldn't run Stripper I ignore if it still works)

Thanks in advance.
