### ISSUE TITLE
BOT Gravindo Openkore WORK 23-03-2017 GARANSI

### ISSUE THREAD

**Issue by arcFIT** [OpenKore/openkore#515]
**BOT Gravindo Openkore Work 23-03-2017 GARANSI
Yang berminat BOT untuk server gravindo
saya jual dan tutorial cara nya dijamin mudah
WA 0812 1072 3769**

**Comment by deca2708** [comment]
cius? no pict = hoax after mt

**Comment by deca2708** [comment]
video deng, soalnya GGnya buat dc2 bukan ga bisa masuk :v

**Comment by andros1987** [comment]
hebat nih pasti agan,, gak DC DC

**Comment by pejret** [comment]
100% scam.... Still using the same number since last week....

Do not buy anything from him....

**Comment by overweightcat** [comment]
no dc cause it's not even connected , yea rite

**Comment by EsTehAnget** [comment]
ada yg mau sharing ramean? syaratnya kudu aktif di group, biar ga ada penyusup... gimana?

**Comment by wimaian** [comment]
@EsTehAnget hmmm boleh , via apa ini grupnya ?

**Comment by person007** [comment]
bot jalan tapi dc dc hehehe.. yang jual nipu huhuhu

**Comment by kobay92** [comment]
@EsTehAnget yukk biar gk ada cepu hahhaa

**Comment by smyrnovisreal** [comment]
@EsTehAnget setuju bikin grup line dah / grup WA. saling sharing. ide bagus

**Comment by wimaian** [comment]
Share no hp nya gan

**Comment by Susumelek45** [comment]
Ngikut gan

**Comment by andros1987** [comment]
Bole gan invite ane di grup wa nya

**Comment by bedebah** [comment]
rekber DPR gan

**Comment by overweightcat** [comment]
ikut2 pak

**Comment by oudytheblackcat** [comment]
izin join pak

**Comment by EsTehAnget** [comment]
selama ga calculating route ga akan dc

**Comment by EsTehAnget** [comment]
bikin via apa nih ??

**Comment by Susumelek45** [comment]
Wa atau line aja gan ini saya saran aja

**Comment by Susumelek45** [comment]
Wa atau line aja gan ini saya saran aja

**Comment by desta89** [comment]
100% scam dont buy guys its a scam

**Comment by Vtric** [comment]
ini penipu gan jangan percaya..

**Comment by AmazingShin** [comment]
ikutan juga gan group nya biar bisa update tiap MT

**Comment by tronbone** [comment]
Ikut grup nya dong

**Comment by rendi05** [comment]
ikut grup . WA aja klo boleh

**Comment by rejekiwandy** [comment]
can someone just share their knowledge for free?
saya coba yang di kaskus

yang "line 406 | ganti sex (0 = female | 1 = male)"

sub sendMapLogin {
	my ($self, $accountID, $charID, $sessionID, $sex) = @_;
	my $msg;
	$sex = 1 if ($sex > 1 || $sex < 0); # Sex can only be 0 (female) or 1 (male)
	
	if ($self->{serverType} == 0 || $self->{serverType} == 21 || $self->{serverType} == 22) {
		$msg = $self->reconstruct({
			switch => 'map_login',
			accountID => $accountID,
			charID => $charID,
			sessionID => $sessionID,
			tick => getTickCount,
			sex => $sex,
		});

di tempat saya mala ketemu nya di line 505

kemudian 

line 413 | ganti slot (angka slot di game dikurang 1. contoh slot 4 = 3 di bot)

sub sendCharLogin {
	my ($self, $char) = @_;
	$self->sendToServer($self->reconstruct({switch => 'char_login', slot => 0}));
	debug "Sent sendCharLogin\n", "sendPacket", 2;
}

ada di line 498

setelah selesai dengan config dan siap untuk dijalankan

ntah bener apa ga yang dimaksud itu

kemudian

Navigasi ke openkore\src\Network\PacketParser.pm



Yang perlu di edit

Bagian ini Diedit setiap login

ok -> src -> Network -> PacketParser.pm

- line 233 = diganti sesuai hasil smsniff

- line 234 = diganti sesuai hasil smsniff 

- line 248 = diganti sesuai hasil smsniff 

- line 249 = diganti sesuai hasil smsniff 

- line 250 = diganti sesuai hasil smsniff 



Bagian ini Hanya diedit sekali

- line 238 = diganti setiap ganti id

- line 239 = diganti setiap ganti id

- line 240 = diganti setiap ganti id

- line 248 = diganti setiap ganti id

- line 249 = diganti setiap ganti id

- line 250 = diganti setiap ganti id

- line 251 = diganti setiap ganti id

- line 252 = diganti setiap ganti id



jalankan openkore melalui start.exe

mala line 233 ketemu nya 
	# RAW_MSG is the entire message, including packet switch
	my %args = (
		switch => $lastSwitch,
		RAW_MSG => $msg,
		RAW_MSG_SIZE => length($msg),
		KEYS => $handler->[2],
	);
	if ($handler->[1]) {
		@args{@{$handler->[2]}} = unpack("x2 $handler->[1]", $msg);
	}
	if (my $custom_parse = $self->can('parse_'.$handler->[0])) {
		$self->$custom_parse(\%args);
	}

	my $callback = $handleContainer->can($handler->[0]);
	if ($callback) {
		# Hook names can be made more uniform,
		# but the ones for Receive must be kept for compatibility anyway.
		# TODO: restrict to $Globals::packetParser and $Globals::messageSender?
		if ($self->{hook_prefix} eq 'Network::Receive') {
			Plugins::callHook("packet_pre/$handler->[0]", \%args);
		} else {
			Plugins::callHook("$self->{hook_prefix}/packet_pre/$handler->[0]", \%args);
		}
		Misc::checkValidity("Packet: " . $handler->[0] . " (pre)");

		# If return is set in a packet_pre handler, the packet will be ignored.
		unless($args{return}) {
			$handleContainer->$callback(\%args, @handleArguments);
		}

		Misc::checkValidity("Packet: " . $handler->[0]);
	} else {
		$handleContainer->unhandledMessage(\%args, @handleArguments);
	}

	if ($self->{hook_prefix} eq 'Network::Receive') {
		Plugins::callHook("packet/$handler->[0]", \%args);
	} else {
		Plugins::callHook("$self->{hook_prefix}/packet/$handler->[0]", \%args);
	}
	return \%args;
}

sub unhandledMessage {
	my ($self, $args) = @_;
	
	warning "Packet Parser: Unhandled Packet: $args->{switch} Handler: $self->{packet_list}{$args->{switch}}[0]\n";
	debug ("Unpacked: " . join(', ', @{$args}{@{$args->{KEYS}}}) . "\n"), "packetParser", 2 if $args->{KEYS};
}

ada yang bisa bantu?
thanks

**Comment by dzavo** [comment]
masalah nya cuman 1 si, sniff nya ga work smnjak mt trahir

**Comment by Flashbisa** [comment]
@dzavo itu mah masalah gampang boss , sniff mah tembus , bot mah jalan

masalah botter sekarang cuma 1 ---> abis botnya jalan tiap 30second DC
ada solusi master2?

**Comment by PMForPayment** [comment]
@Flashbisa link sniff nya dong bosku ~

**Comment by Flashbisa** [comment]
percuma boss , gw kasipun lu gak bakal bisa pake , gak semudah snif2 yang laen 

lu google aja snifftools pasti keluar kok

**Comment by rejekiwandy** [comment]
@Flashbisa : yang working di masukin repo dong bos 
dari awal saya join sampe sekarang belon bisa ngebot >.<
naseeb

**Comment by PMForPayment** [comment]
@Flashbisa bisikin Link nya bosku.. ngerti kok pake sniff nya

**Comment by smashmania** [comment]
sniff jalan cuma botnya 30detik or less dc.masi lom nemu pencerahannya

**Comment by PMForPayment** [comment]
@smashmania pake sniff yg mana ente bos ?

**Comment by kopetkuda** [comment]
bikin grup discord aja

**Comment by kopetkuda** [comment]
@rejekiwandy  saya coba bantu tapi situ masalahnya dmn? error / kasih ss . klo cmn kasih script kayak gitu trs gmn mau tau situ kendalanya dmn

**Comment by rossevelts** [comment]
@kopetkuda ada discord ? via discord aja.. disini bnyk pedagang receh..

**Comment by wimaian** [comment]
Ayok buat grup discord

**Comment by PMForPayment** [comment]
@kopetkuda selain discord ad gan ?

**Comment by PMForPayment** [comment]
@kopetkuda problem nya di kode togel. blm dpt Applikasi nya nih..

**Comment by kopetkuda** [comment]
situ main pake plugin delphin apa script diatas?

**Comment by PMForPayment** [comment]
@kopetkuda script di atas suhu..
PM dongs

**Comment by kopetkuda** [comment]
cara diatas pake sniff

**Comment by PMForPayment** [comment]
@kopetkuda nah iya, sniff ane udh gak works gan. coba sedot yg punya ente dongs

**Comment by kopetkuda** [comment]
google banyak om app semacam itu, wireshark juga bisa keknya, cari lah...

**Comment by PMForPayment** [comment]
@kopetkuda kalo si om yg works pake yg mana tuh????

**Comment by AmazingShin** [comment]
group discord nya apa yah? 

problemnya kan kalo masuk portal, atau mati, atau kill monster langsung DC yah. kalo login sih masih bisa pake sniff

**Comment by oudytheblackcat** [comment]
@rejekiwandy awalnya ane jg bingung soal itu. tp setelah menelusuri, sepertinya itu pke yg udah di edit packetparsernya (yg isinya edit/inject packet dari hasil sniff). klo utk yg sex menurut ane yg 7 line diatasnya char slot (logically, line 406 is 7 line above line 413).

nah, tp ane jg belum bisa masuk smpe situ. server info nya masih ga kebaca bener. yg udah bisa masuk, itu kenapa ya? apa hasil sniff yg didapet di dienkripsi juga?

**Comment by wimaian** [comment]
mana grupnya ne ?

**Comment by HansGiven** [comment]
Join Grup linenya dong @EsTehAnget

**Comment by kobay92** [comment]
liat di forum sebelah ktnya gini
 "udah bisa tp ribet, clue nya "cari monster aggresive"

**Comment by Vestralls** [comment]
@EsTehAnget grup linenya sekalian donk kalo boleh. Masi nub nih butuh belajar dari suhu2 sekalian

**Comment by wimaian** [comment]
hmmm , yang di snif skrg port 6000 kan ? -__-

**Comment by croscek** [comment]
bot still work,but if you move 1 cell,you will DC..now bot just for mercan/BS auto vending. .if you not move,bot can survive 24hours..just set in config autoattack,,autosit,,autotake item,,attackdistance,,attackmaxdistance,,autoattackparty,,randomwalk,,lockmap x/y,,you will survive in map with agresive monster. .my bot just sit,monster come ,he attack,,no monster he sit again. .just like that always. .dont forget,no autoloot. .
we waiting master fix this problem. .

**Comment by oudytheblackcat** [comment]
baru sadar snifftool yg ane pke cuma bisa intip permukaan aja. boleh tau sniff tool yg bisa intip smpe kedalem? boleh bisikin kesini : lokiyukir@gmail.com

Thx b4!

**Comment by itsrachelfish** [comment]
Please stop
