### ISSUE TITLE
Need support for packet recieved 09CB

### ISSUE THREAD

**Issue by smallvill3** [OpenKore/openkore#516]
Master of Openkore developer,
I need your help to support this packet **09CB**

> 0x09cb,17 // ZC_USE_SKILL2 (from rAthena)

> Non-damaging skill effect.
> 011a <skill id>.W <skill lv>.W <dst id>.L <src id>.L <result>.B (ZC_USE_SKILL)
> 09cb <skill id>.W <skill lv>.L <dst id>.L <src id>.L <result>.B (ZC_USE_SKILL2)

Openkore display this msg everytime when it finished casting a skills
"Casting is supposed to be finished now, but nothing happened."
![2e082d32-153a-11e7-8140-53a66b40fe98](https://cloud.githubusercontent.com/assets/26625329/24597051/d9ea3dfa-1875-11e7-9c24-0f7adafa78e3.jpg)

**Comment by smallvill3** [comment]
@Novishivsmoke 
I just figured it out after reading your last reply #497 (probably u have delete it) , previously you suggest to change to v3 v a4 a4 C, i tried it dint work.

Later i change to below, and its working finally.
No more warning msg, and the bot can now casting the buff skills with no delay.
The only missing in the msg is Level of skills, anyway 09CB is now working correctly.

![sucess](https://cloud.githubusercontent.com/assets/26625329/24596746/cf8fbaa8-1873-11e7-8d66-b8ea09c26b95.jpg)
'**09CB**' => ['skill_used_no_damage', 'v2 v a4 a4 C', [qw(skillID lv amount targetID sourceID success)]],

**Comment by Novishivsmoke** [comment]
Uau very nice i dont expected to work at this Way . Thanks for your help

**Comment by smallvill3** [comment]
@m3kgin3er 
You looks like you understand perl to me /heh
Anyway, its confirm that my recvpacket.txt have this value **09CB 17**
![untitled2](https://cloud.githubusercontent.com/assets/26625329/24855211/79906b0c-1e13-11e7-9dcf-a4ff3b75cbe8.jpg)

Hope that this is getting merge to Openkore.
Thanks

**Comment by a2362998** [comment]
[iRO] Packet Tokenizer: Unknown switch 09DB, 09DD 
i am having this problem guys   newbie here  how could fix it pls

**Comment by m3kgin3er** [comment]
Do you think that asking in the wrong place, someone will fix something for ya ?
:/ iRO

**Comment by xGine** [comment]
Tingin ko di maayos ng pag extract ng recvpackets sa client ung packet tokenizer error.  May magic na nangyayari encrypted ata hmmmmm.
