### ISSUE TITLE
Openkore really need to be updated?

### ISSUE THREAD

**Issue by k1nt4r0** [OpenKore/openkore#517]
i try to bot on a server with 2017 client, and the last support server type as i know is 2015?
the extractor doesnt work anymore too, maybe cause it is protected or need a new extractor.
i will upload the exe, and server.txt if someone really want to help.
thx

**Comment by walkietalkie89** [comment]
they can't help you, why? because u put _'if someone really want to help'_ without details of what server, what hv u done? what extractor? they can't read your mind. so ....

**Comment by k1nt4r0** [comment]
> ![peviewer](https://cloud.githubusercontent.com/assets/25668148/24291579/22448536-10bc-11e7-9d58-38a2cdc2f49c.png)

this is the PEView

`

> ![wpe](https://cloud.githubusercontent.com/assets/25668148/24291596/37f751b0-10bc-11e7-80c5-1a291e93ae7e.png)

this is what i got from WPE

`[******]
ip 158.69.123.38
port 6954
master_version 1
version 57
serverType kRO_RagexeRE_2013_08_07a
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
addTableFolders kRO/RagexeRE_2013_08_07a;iRO
charBlockSize 124
recvpackets ro.txt`

this is the lastest server info as i know

i cant even extract the recvpackets, client = 18mb size

**Comment by dclxjdc** [comment]
is this a private server?

**Comment by k1nt4r0** [comment]
yes sir, this is a private server

**Comment by k1nt4r0** [comment]
yes sir, this is a private server

> ![peviewer](https://cloud.githubusercontent.com/assets/25668148/24292021/0bf2c980-10be-11e7-9eb1-86c929ffdf43.png)

this is ther error message

**Comment by Slipxxliose** [comment]
Invalid connection information. Has your server some kind of shield ? harmony ?

**Comment by alisonrag** [comment]
openkore already have support to 08/2017- clients
