### ISSUE TITLE
What wrong have i done (Players recognized as NPC / Unknown

### ISSUE THREAD

**Issue by MtKahlui** [OpenKore/openkore#518]
[wcx.txt](https://github.com/OpenKore/openkore/files/867299/wcx.txt)
i extracted recvpackets with PEEK
clientinfo.xml is in the attaced file

and here is what i use for servers.txt 
```
ip 66.150.188.197
port 6900
master_version 0
version 30
private 1
serverEncoding Western
serverType 8_4
charBlockSize 144
[wcx.txt](https://github.com/OpenKore/openkore/files/867288/wcx.txt)

P.S. i dont know why github won't let me upload a zip file. please change the extension of the attached file to .zip


```
[wcx.txt](https://github.com/OpenKore/openkore/files/867312/wcx.txt)

**Comment by walkietalkie89** [comment]
serverType 8_4? are you already read this? http://www.openkore.com/index.php/ServerType

> Legacy
> 
> Numeric serverTypes (0-22, 8_1-8_5) are outdated and aren't being updated to follow server updates, so they probably will not work correctly - that's a real reason to update from OpenKore 2.0.7 and stop using them, if you don't want to update them by yourself. Don't complain that there's just "some problems" with them if you don't have solutions too.
> 
> They're kept in OpenKore for use with really outdated official and private servers.
> 
> serverType 0 is also used as a base for serverTypes for official servers (except kRO).

**Comment by MtKahlui** [comment]
i can login with 8 / 8_4 but not with kRO_RagexeRE_2014_10_22b
![image](https://cloud.githubusercontent.com/assets/26646400/24287562/23585e04-10b5-11e7-9609-07353d5aa74d.png)

**Comment by walkietalkie89** [comment]
it's weird according to your problem, maybe this is same to you?
http://forums.openkore.com/viewtopic.php?p=67676#p67676

**Comment by MtKahlui** [comment]
will try and read that. and i really have no idea on editing pm files

**Comment by SabadyshynV** [comment]
http://forums.openkore.com/viewtopic.php?p=275220#p275220

**Comment by MtKahlui** [comment]
amen to you brother. will now rush home to try that

**Comment by Razalka** [comment]
Seriously 8_4 ?

**Comment by MtKahlui** [comment]
@SabadyshynV the guide in the thread you linked worked.
i can now properly detect players. but there is still this unknown effect 
it is from a healer NPC from the game
![image](https://cloud.githubusercontent.com/assets/26646400/24318534/cad018fc-1141-11e7-8541-b757953256a0.png)

**Comment by SabadyshynV** [comment]
good that u have hid effect name... it helps...

**Comment by Novishivsmoke** [comment]
0x009b,34,wanttoconnection,7:15:25:29:33

RagexeRE_2008_08_27a.pm

**Comment by Razalka** [comment]
@MtKahlui 
Add this file to tables folder.
[effects.txt](https://github.com/OpenKore/openkore/files/902055/effects.txt)

**Comment by m3kgin3er** [comment]
If solved , can you close the thread ?!
