### ISSUE TITLE
connection private server Ragnarok ReturN Indonesia

### ISSUE THREAD

**Issue by KidOfAdvenrurer** [OpenKore/openkore#52]
have trouble prepare the things for botting in Return Ragnarok.
i can connect this server but error in char selection .
.
Client File = https://www.dropbox.com/s/0um15o1f2izieg0/Ragnarok.exe?dl=0

error =  http://s12.postimg.org/5e9pc0yh9/123123123123.png

any help. clue or advice would be very helpful

**Comment by KidOfAdvenrurer** [comment]
but still have a trouble extracting the recvpackets.txt

i've been tried many packet extractor tool (v3, peek, jcv, ect.) none works.
in jcv ro tools, it show something about .exe is being protected with gepard shield ..

**Comment by Cozzie** [comment]
Some servers obfuscate the packets I believe so you won't be able to extract it to prevent botting.

**Comment by KidOfAdvenrurer** [comment]
thanks for your advice , i still try to get recvpaket ..
