### ISSUE TITLE
XKore 2-3 with client 2015-05-13a

### ISSUE THREAD

**Issue by Skeec** [OpenKore/openkore#520]
Hey.

I tried using XKore, but running in some problems.

For XKore 2 the bot is up and running but the modified-client cannot connect to the XKore Instance so I can see what the bot is doing. It let me choose my character (with wrong gender) and right after logging into it dc's.

For XKore 3 when I log in I can see my correct character and he is online on the map but the XKore tries to connect like crazy: 
![image](https://cloud.githubusercontent.com/assets/20649209/24304758/d8431a98-10ba-11e7-99d3-5e2e00c2c91e.png)

Before you ask, I already ran everything with administrator privileges. 

Yours Skeec

**Comment by Glowned** [comment]
I have the same exact problem..

**Comment by sudruns** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26138408/24331549/9ce06bb6-1260-11e7-87c4-3b68ff250f16.png)
the same problem
xkore 2 or 3 not work

**Comment by sudruns** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26138408/24331602/b48fdade-1261-11e7-80ec-07a501a2529b.png)
the same problem
xkore 2 or 3 nothing work
waiting for someone kindly provide a solution

**Comment by Razalka** [comment]
@Skeec 
why xkore ?

**Comment by Skeec** [comment]
@Razalka It's better to react on gms when catched

**Comment by Razalka** [comment]
@Skeec 
Find the plugins for GM reaction.

**Comment by fchiao** [comment]
why not just use xk2?

**Comment by Glowned** [comment]
Xk2 sends directly packets to the server wherehas xk3 proxify every packet through the client which is less suspicious if the server has an automatic packet parser.

**Comment by fchiao** [comment]
I see, got it.

**Comment by linz86** [comment]
Is there anyone who can help me to make the bot idro works..
Please teach me..I will pay you for your kindness..please email me vinsensiusandy.0101@gmail.com

**Comment by Vestralls** [comment]
@Razalka can you help me with the idRO problem ? Bots disconnect if trying to move or pickup items. And when im running the ragnarok program (playing) , i cant run the xkore bots , it said that the program cant run along with ragnarok. Sry if i asked too much

**Comment by Novishivsmoke** [comment]
How are your settings ?

**Comment by Skeec** [comment]
well the server is now gepard protected I think it wont work now XKore 0? is that the 1 version?

**Comment by m3kgin3er** [comment]
I believe you've received a lot of 082D packets. As occurs normally it is called 3 times in RakkiRO ^^
When incorrect charBlockSize ^^

**Comment by m3kgin3er** [comment]
'0072' => ['received_characters', 'v a*', [qw(len charInfo)]], # struct unknown, this one is from XKore 2
