### ISSUE TITLE
Unknown Switch: 0A0D, 0A00, 0000, 09CB, 2001

### ISSUE THREAD

**Issue by Fruitjes** [OpenKore/openkore#522]
Hi, im using openkore for a support priest on epicro. the bot follows and upon start use agi up and blessing on himself but not on my char.
it sends out following errors.

Packet Parser: Unknown switch: 0A0D
Packet Parser: Unknown switch: 0A00
Packet Tokenizer: Unknown switch: 0000
Packet Parser: Unknown switch: 09CB
Packet Tokenizer: Unknown switch: 2001

my recvpackets:
[recvpackets_20150513a.txt](https://github.com/OpenKore/openkore/files/869084/recvpackets_20150513a.txt)

any idea?

**Comment by Novishivsmoke** [comment]
Close this issue and keep talking there !
