### ISSUE TITLE
Potongan paket : Switch tidak diketahui

### ISSUE THREAD

**Issue by zuperzell** [OpenKore/openkore#524]
![openkore](https://cloud.githubusercontent.com/assets/26440940/24322106/c1669446-118f-11e7-8e7f-379b253fd6d8.jpg)
any one can teach me how to fix this ? noob sorry, play RO long time ago ^^

**Comment by garrytabuty46** [comment]
Use english for the Issue Title.. this is international forum man.

**Comment by deca2708** [comment]
penjual bot sudah berguguran. rip.

**Comment by rejekiwandy** [comment]
@deca2708 tetep aja bos, masi banyak bot berkeliaran ^^
ntah dimana di bahasnya.. kaga kebagian ilmu nya >.<

**Comment by SabadyshynV** [comment]
English no?

**Comment by zhuarifp** [comment]
iya mau di update sampe mati pun ga sampe sejam kok w selalu liat ada bot bermunculan.

**Comment by m3kgin3er** [comment]
WE
DONT
SUPPORT
PROTECTED
SERVERS.
http://openkore.com/index.php/Unsupported_servers

**Comment by hellowin** [comment]
It's Indonesian @m3kgin3er, idRO, it was supported but idRO implemented new game guard mechanism by this year since idRO license already taken by other licensee.

But yeah, a lot of spam issues like this recently from Indonesian player, actually I can help to filtering it out but I have no right.

**Comment by ardian151** [comment]
bagi ilmu suhuuu
uda utak atuk 2 hari tetep aje pocket token pocket parcel
