### ISSUE TITLE
Old Developer here,

### ISSUE THREAD

**Issue by heero74** [OpenKore/openkore#525]
Been a while since I last checked Openkore so I did'nt know you guys already migrated to github, well either way just requesting to be added as a developer again.

heero74

**Comment by xraycrossx** [comment]
@heero74 sir would you give me your discord ID? i really want to chat with you sir

**Comment by zhuarifp** [comment]
i also want to study and learn from u heero74 :(

**Comment by Vestralls** [comment]
@heero74 would u like to help me solve the RO Bot issues ? Newb here , really could use a helpful hand. Tyvm :)

**Comment by itsrachelfish** [comment]
@heero74 Heya! Long time no see! Can you hop onto the #OpenKore IRC chat on freenode? We'll need to verify your account and then I can add you to the project as a developer :)

**Comment by heero74** [comment]
Well I tried to go online in IRC but it seems you were afk @itsrachelfish well if you want confirmation on who I am I sent a message to @kLabMouse in Skype just not sure if he still uses that application, after all its been close to a year since I last went to check Openkore. Well if you want more confirmation I left a message in Admins & Global Moderators section of forums.openkore.com, so just check there for now and we can continue our talk there.

**Comment by heero74** [comment]
@xraycrossx my discord in private so I can't give it out.
@zhuarifp sadly I can't be sure if I can help you much been a while since I last checked openkore
@Vestralls If you need help just submit a new issue I am sure the other devs will help you out.

**Comment by itsrachelfish** [comment]
@heero74 Thanks for sending the confirmation on the forums / IRC, I sent you an invite as a developer to the project. A few of the other developers are still around on IRC during the day so feel free to drop by if you ever want to talk!

**Comment by itsrachelfish** [comment]
Also, if you add your old sourceforge email to your github account you should be able to make your old contributions appear in your account :+1:
