### ISSUE TITLE
Incoming data left in the buffer (Investigating on bot detection)

### ISSUE THREAD

**Issue by Glowned** [OpenKore/openkore#528]
Hello,

I was running 5 bots from 5 differents IP in order to test the bot detection system on the private server i'm botting on.
They all ended like this : 
![image](https://cloud.githubusercontent.com/assets/4534941/24458724/11bf326a-149a-11e7-9b7f-1c28cc151d84.png)

Do you know what happened ? 
What did the admin used to know it was a bot ?

Thanks

**Comment by walkietalkie89** [comment]
Gepard shield? when you capture packet (WPE) are you disconnected too?
maybe something like custom packet.

**Comment by Glowned** [comment]
I have no problem capturing packets with WPE.
So it couldn't be gepard shield, isn't it ?
I will try to track this packet to extract the response.

**Comment by Razalka** [comment]
00B6 = NPC Cancel

**Comment by Glowned** [comment]
Hello,
This is a private server called Fragments of Yggdrasil: 
Here is the conf 

> [Fragments of Yggdrasil]
> ip 37.59.54.71
> port 6900
> master_version 2
> version 45
> serverType kRO_RagexeRE_2013_08_07a
> charBlockSize 144
> serverEncoding Western
> private 1
> addTableFolders iRO
> recvpackets rcvfoy.txt

I extracted the recvpackets with peek.

There are encryptions keys, set  : 

> $self->cryptKeys(0x975EDB56, 0x69F3DE78, 0x7D27B6B5);

I have noticed, while extracting the recvpackets, that there are packets called "shuffle packets". I know that some servers like TwRO use packet shuffling, is there a link ?

> 
> [Shuffle_Packets]
> 0x0369 = 0
> 0x083C = 1
> 0x0437 = 2
> 0x035F = 3
> 0x0202 = 4
> 0x07E4 = 5
> 0x0362 = 6
> 0x07EC = 7
> 0x0364 = 8
> 0x0438 = 9
> 0x0366 = 10
> 0x096A = 11
> 0x0368 = 12
> 0x0838 = 13
> 0x0835 = 14
> 0x0819 = 15
> 0x0811 = 16
> 0x0360 = 17
> 0x0817 = 18
> 0x0815 = 19
> 0x0365 = 20
> 0x0363 = 21
> 0x0281 = 22
> 0x022D = 23
> 0x0802 = 24
> 0x0436 = 25
> 0x023B = 26
> 0x0361 = 27
> 0x0887 = 28
> 

Thank you for the help ;)

**Comment by Razalka** [comment]
try use this servertype kRO_RagexeRE_2015_11_04a.

**Comment by Glowned** [comment]
@Razalka 

I tried, o also copied the crypt keys and i can't connect anymore : 
![image](https://cloud.githubusercontent.com/assets/4534941/24544388/61d4d2f4-1603-11e7-88dc-2fbb63c82c49.png)

Thanks

**Comment by m3kgin3er** [comment]
http://forums.openkore.com/viewtopic.php?f=6&t=211637

**Comment by newbiehardwork** [comment]
@m3kgin3er
Thank you you always help for newbie
