### ISSUE TITLE
Openkore crash

### ISSUE THREAD

**Issue by zyrox91** [OpenKore/openkore#53]
Shown as the picture, anyone please help?
![openkore](https://cloud.githubusercontent.com/assets/17803427/13725294/7f4e4724-e8d8-11e5-96cf-c8e33c3f8896.jpg)

**Comment by windhamwong** [comment]
Too many possibilities of reasons of crashing. Can you give some details on your settings?
It looks like it is running in private server. Private server may need special modification in order to support custom packets and anti-cheat systems.
