### ISSUE TITLE
Disconnect from the server every 12 seconds. What is the cause?

### ISSUE THREAD

**Issue by TanasanJJ7** [OpenKore/openkore#530]
Disconnect from the server every 12 seconds. What is the cause?
Which part to fix?
Thank you very much

![capture](https://cloud.githubusercontent.com/assets/16222517/24500344/30f9bc6a-156f-11e7-9e4d-8c2784d1dccc.JPG)

**Comment by kakEmma** [comment]
The same problem with OpenKore Indonesia

**Comment by cikdinz** [comment]
anyone can help solve like this problem ?

**Comment by BigGolem** [comment]
kakEmma, last night clue can you reshare it with us?

**Comment by TanasanJJ7** [comment]
I can share
But we must help each other develop and fix this problem.

So I can send you the file.

**Comment by dclxjdc** [comment]
@TanasanJJ7 
try to make a repo, we will try to take a look

**Comment by TanasanJJ7** [comment]
@dclxjdc I do not understand what you are meaningful.

**Comment by kimkimwalker** [comment]
any solve?

**Comment by shatterdome** [comment]
@TanasanJJ7 

Sir, i already try some code in tRO issue to fix this problem, but still disconnected after 10sec while character trying to move to another coordinate, maybe because i play in idRO Chaos (Ragnarok Indonesia) so that code from tRO issue doesn't work. 

Mind to help me to solving this problem ? you can send me an email to kurokotetsuyaa3@gmail.com

Anyway thanks :D

**Comment by walkietalkie89** [comment]
@shatterdome i think u out of topic..

**Comment by TanasanJJ7** [comment]
@shatterdome  Yes  your welcome

**Comment by TanasanJJ7** [comment]
@shatterdome  Can you understand Eac?  
But I know that openkore x0 - x3 is not working.

**Comment by person007** [comment]
Evo-BOT - AETHA BOT manusia BANGSAT tidak tau malu, BENALU dimana mana, manusia TOLOL, GOBLOK, MATI AJA LO..., NGACA DONG GOBLOK, TOLOL BACA BUKAN TEMPAT JUALAN, KELIHATAN KELUARGA BENALU, ORANGTUANYA PASTI TUKANG TIPU, ANAK JUGA TUKANG TIPU. HEI TOLOL SADAR INI BUKAN TEMPAT JUALAN TOLOL GOBLOK, BEGO MANUSIA TIDAK BEROTAK..... SERAKAH ...... PAKAI OTAK LU  UNTUK BACA LAGI GOBLOK GOBLOK  MAU SUKA NIPU,  PENIPU TOLOL..
