### ISSUE TITLE
Can OpenKore Botting Can Bypass Gepard?

### ISSUE THREAD

**Issue by peewee24** [OpenKore/openkore#534]
Help me with this..This Server have the latest Gepard

**Comment by walkietalkie89** [comment]
nope

**Comment by deca2708** [comment]
yes. my programmer already did this and alot of people already did too.
find someone you can pay, its a lot of work. unless they want to give charity.

**Comment by gwazwei** [comment]
@deca2708 how to find someone like that? call you tell me someone who already did this ?

**Comment by alisonrag** [comment]
Officialy openkore does not support servers with gepard shield
