### ISSUE TITLE
My Bot can't attack.

### ISSUE THREAD

**Issue by Vestralls** [OpenKore/openkore#539]
Hi , im not sure if im the one who made the mistake here but its kinda confusing. Here is the thing.
Im running 2 Assassin Bots , both with the same config. The only difference between each ID is the gender and the level. The weapon is the same Jamadhar. The Female one seems to be working just fine , but , the male one is just sitting and doesn't atk/retaliate. Both config is the same (i copy paste the female's config to male) , but im confused why the male Assassin doesn't atk (both autoatk 0)
Here is the config for auto atk,sit,walk: (both have the same config)
attackAuto 0
attackAuto_party 1
attackAuto_onlyWhenSafe 0
attackAuto_followTarget 1
attackAuto_inLockOnly 1
attackAuto_notInTown 1
attackDistance 1
attackDistanceAuto 1
attackMaxDistance 1
attackMaxRouteDistance 1
attackMaxRouteTime 4
attackMinPlayerDistance 2
attackMinPortalDistance 4
attackUseWeapon 1
attackNoGiveup 0
attackCanSnipe 0
attackCheckLOS 0
attackLooters 0
attackChangeTarget 1
aggressiveAntiKS 0
route_escape_reachedNoPortal 1
route_escape_randomWalk 1
route_escape_shout
route_avoidWalls 1
route_randomWalk 0
route_randomWalk_inTown 0
route_randomWalk_maxRouteTime 75
route_maxWarpFee
route_maxNpcTries 5
route_teleport 0
route_teleport_minDistance 150
route_teleport_maxTries 8
route_teleport_notInMaps
route_step 15
sitAuto_hp_lower 40
sitAuto_hp_upper 80
sitAuto_sp_lower 0
sitAuto_sp_upper 0
sitAuto_follow 0
sitAuto_over_50 0
sitAuto_idle 1
sitAuto_look
sitAuto_look_from_wall
sitTensionRelax 0

Will appreciate any advice to make things right :)

**Comment by lututui** [comment]
"attackAuto 0" makes it so your bot will only attack a mob if the mob attacks you first. If the map you're botting on only has passive mobs, we'll never have a mob to retaliate.

http://openkore.com/index.php/AttackAuto

**Comment by Vestralls** [comment]
Both in the same map btw, sorry forgot to mention :(

**Comment by ab9898** [comment]
change your auto attack

do you use xkore?
