### ISSUE TITLE
openKore compilation aborted

### ISSUE THREAD

**Issue by heitorPB** [OpenKore/openkore#549]
Hi

I decided to try openKore, so I downloaded the latest git version on my ArchLinux laptop and tried to run it:

> $ ./openkore.pl 
> Devel::StackTrace version 2 required--this is only version 1.13 at /usr/share/perl5/vendor_perl/Exception/Class/Base.pm line 9.
> BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Exception/Class/Base.pm line 9.
> Compilation failed in require at /usr/share/perl5/core_perl/base.pm line 100.
> 	...propagated at /usr/share/perl5/core_perl/base.pm line 109.
> BEGIN failed--compilation aborted at (eval 7) line 5.
> BEGIN failed--compilation aborted at /home/h/Games/openkore-master/src/Utils/Exceptions.pm line 51.
> Compilation failed in require at (eval 6) line 1.
> BEGIN failed--compilation aborted at (eval 6) line 1.
> Compilation failed in require at /home/h/Games/openkore-master/src/Translation.pm line 30.
> BEGIN failed--compilation aborted at /home/h/Games/openkore-master/src/Translation.pm line 30.
> Compilation failed in require at /home/h/Games/openkore-master/src/ErrorHandler.pm line 27.
> BEGIN failed--compilation aborted at /home/h/Games/openkore-master/src/ErrorHandler.pm line 27.
> Compilation failed in require at ./openkore.pl line 24.
> BEGIN failed--compilation aborted at ./openkore.pl line 24.

I have perl-devel-stacktrace 2.02-1 installed.

Have no idea how to make this work.

Also, I changed the makefile to explicitly use Python2 and it can compile everything. But the perl script does not run.

**Comment by wanjizheng** [comment]
same here. please help

**Comment by lututui** [comment]
Maybe this will help ya:
http://wiki.openkore.com/index.php/How_to_run_OpenKore#Requirements

**Comment by heitorPB** [comment]
I deleted src/deps/Devel and it worked.
THere is a conflict with the shipped version of Devel::StackTrace and the one from the official repositories.
