### ISSUE TITLE
Heal Bombing not recognizing Archer Skeleton

### ISSUE THREAD

**Issue by holoc** [OpenKore/openkore#553]
I'm using the following skill block code for heal bombing undead monsters:
```
attackSkillSlot Heal {
	lvl 6
	sp > 10%
	monsters Archer	Skeleton, Bongun, Evil Druid, Fire Pit, Firebug, Firelock Soldier, Ghoul, Injustice, Megalodon, Mummy, Munak, Orc Skeleton, Orc Zombie, Pirate Skeleton, Pitman, Skel Prisoner, Skel Worker, Skeleton, Soldier Skeleton, Sonia, Verit, Whisper (Immobile), Wraith, Yao Jun, Zombie, Zombie Master, Zombie Prisoner
}
```
My bot would be able to heal bomb the undead monsters on the map except for Archer Skeletons, where it would attempt to melee the Archer Skeleton with the wand weapon... 

I've noticed that in the game, the monster is named ArcherSkeleton, while in OpenKore console it appears to be `Archer	Skeleton` where the space appears to be a long blank space (about 3 blank spaces long) and in the OK logs, it shows `1028 Soldier Skeleton` (1 space), but when pasted to a text editor it shows what appears in the OpenKore console.

I've searched the forums and looks like someone else has had this issue as well before, but there has been no response to it here: http://forums.openkore.com/viewtopic.php?f=16&t=211472&p=274116&hilit=archer+skeleton#p274116

**Comment by Razalka** [comment]
@holoc 
Find tables/monsters.txt
See what kore recorded there for Archer Sekeleton, and copy it.

**Comment by holoc** [comment]
@Razalka I've tried that and it still does not work.

**Comment by Razalka** [comment]
@holoc 
try `Skel Archer`
it must be working.

**Comment by holoc** [comment]
@Razalka I tried Skel Archer as well it does not work.

**Comment by a2362998** [comment]
not works on mine too T T

**Comment by moneyisgod** [comment]
Very good. This is strange.

**Comment by moneyisgod** [comment]
No. There are two same monsters in the same field by the logic.But its not recognizing ArcherSkeleton? try Archer___Skeleton

**Comment by CooLowbro** [comment]
Same problem here. Tried all these:

> ArcherSkeleton 1 0 1
Archer Skeleton 1 0 1 #One Space
Archer	Skeleton 1 0 1 #One Tab
Archer  Skeleton 1 0 1 #Two Spaces
Archer__Skeleton 1 0 1
Archer   Skeleton 1 0 1 #Three Spaces
Archer___Skeleton 1 0 1
Archer		Skeleton 1 0 1 #Two Tabs<

Obs.: The Git editor's dont accept tabs character, or more than one space :/

**Comment by moneyisgod** [comment]
Its sample. Just use the bot and stand in front with this monster. Then close u kore and go to tables/your addTablesFolder/monster.txt

See the log and enable in u setting.

**Comment by CooLowbro** [comment]
Already did it. It appears on the log with one space only.
Solved the problem partially adding the monster id, but it should work with its name.
> 1016 1 0 1

**Comment by kaliwanagan** [comment]
Yes, the best way to resolve if kore doesn't recognize the mob name is to use the mob id (also works for items).

**Comment by fawkbr** [comment]
Agreed, just use 1016 instead of the name.
