### ISSUE TITLE
kRO_RagexeRE_2015_11_04a is error 

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#554]
https://www.img.in.th/images/d8b75eec9fd96ef80a2dbbc0b5ee8e6e.png

Error message:
'x' outside of string in unpack at src/Network/PacketParser.pm line 248.

**Comment by m3kgin3er** [comment]
Where did you download your bot ?!

**Comment by sctnightcore** [comment]
download for https://github.com/m3kgin3er/openkore-rakkiRO-at-least 
#Made by UnknowN6996 // (09 de Maio de 2017 [23h::26m::48s])
0187 6
0081 3
01C6 4
01C7 2
0064 55
0069 -1
006A 23
01DB 2
01DC -1
01DD 47
01FA 48
0204 18
01F1 -1
0200 26
01BE 2
01BF 3
0065 17
0066 3
0067 37
0970 31
020D -1
006B -1
006C 3
006D 149
006E 3
0071 28
0068 46
01FB 56
006F 2
0070 3
02CA 3
009B 34
0082 2
00A7 9
0190 23
00F3 -1
0089 11
007D 2
0090 7
0099 -1
019C -1
0085 10
00CC 6
00CE 2
00F5 11
0116 17
009F 20
00A9 6
00AB 4
00B8 7
00B9 6
00B2 3
00BA 2
00BB 5
00BF 3
00C1 2
00C5 7
00C8 -1
00C9 -1
0096 -1
00CF 27
00D0 3
00D3 2
00D5 -1
00D9 14
00DE -1
00E0 30
00E2 26
00E3 2
00E4 6
00E6 3
00E8 8
00EB 2
00ED 2
00EF 2
0094 19
00F7 17
0193 2
00F9 26
01E8 28
00FC 6
00FF 10
0102 6
0100 2
0103 30
0108 -1
0112 4
0072 22
0113 25
0118 2
011B 20
011D 2
0126 8
0127 8
0128 8
0129 8
012A 2
012E 2
012F -1
01B2 -1
0134 -1
0130 6
0138 3
013F 26
0140 22
0143 10
0146 6
0178 4
017A 4
017C 6
01FD 15
018A 4
018E 10
007E 105
0197 4
0198 8
01AE 4
025B 6
01AF 4
01B9 6
01CD 30
01CE 6
0443 8
01CF 28
01D0 8
01E1 8
01D1 14
01D2 10
008C 14
0095 30
0195 102
00A2 14
0175 6
0176 106
0079 53
019D 6
014C 6
014D 2
014E 6
014F 6
0150 110
01B6 114
0151 6
0152 6
0153 6
0154 6
0166 6
0155 6
0156 6
0157 6
0159 54
015A 66
015B 54
015C 90
015D 42
015E 6
015F 42
0160 42
0161 42
0162 42
0163 42
0164 42
0165 30
0167 3
0168 14
0169 3
016A 30
016B 10
0149 9
014A 6
014B 27
016E 186
016F 182
017E 182
017F 182
0165 30
0166 30
0167 3
0168 14
0169 3
016A 30
016B 10
016C 43
016C 43
016D 14
01F2 20
0170 14
0171 30
0172 10
0173 3
0174 3
0180 6
0181 3
0182 106
0183 10
0184 10
0185 34
019E 2
019F 6
01A0 3
01A1 3
01A2 37
01A3 5
01A4 11
01A5 26
01A6 26
01A7 4
01A8 4
01A9 6
01AA 10
01CA 3
01B0 11
01B1 7
01BA 26
01BB 26
01BC 26
01BD 26
01C0 2
01C1 14
01C2 10
01D3 35
01D5 35
01D4 6
01DF 6
01F3 10
0284 14
01FF 10
01ED 2
01E7 2
01B7 6
01F7 14
01E3 14
01CB 9
01F9 6
01E5 6
0201 6
0203 10
0205 26
0206 11
0207 34
0208 14
0209 36
020A 10
020E 32
0212 26
0213 26
0214 42
0215 6
0216 6
0217 2
0218 2
0225 2
0219 282
021A 282
0226 282
0282 284
021B 10
021C 10
0224 10
0280 12
0285 6
0286 4
021D 6
021E 6
021F 66
0222 6
0221 6
0220 10
0223 8
0073 11
0074 3
0075 3
0076 9
0077 5
0078 55
007A 58
007B 60
007C 44
007F 6
0080 7
0083 2
0084 2
0086 16
0087 12
0088 10
08CD 10
008A 29
008B 23
008D 23
008E 23
0091 22
0092 28
0093 2
0097 2
0098 3
009A 3
009C 9
009D 17
009E 17
00A0 23
00A1 6
00A3 6
00A4 6
00A5 6
00A6 6
00A8 7
00AA 9
00AC 7
00AE 7
00AF 6
00B0 8
00B1 8
00B3 3
00B4 3
00B5 6
00B6 6
00B7 6
00BC 6
00BD 44
00BE 5
00C0 7
00C2 6
00C3 8
00C4 6
00C6 6
00C7 6
00CA 3
00CB 3
00CD 3
00D1 4
00D2 4
00D4 4
00D6 3
00D7 3
00D8 6
00DA 3
00DB 3
00DC 28
00DD 29
00DF 29
00E1 30
00E5 26
00E7 3
00E9 19
00EA 5
00EC 3
00EE 2
00F0 3
00F1 2
00F2 6
00F4 21
00F6 8
00F8 2
00FA 3
00FB 3
00FD 27
00FE 30
0101 6
0104 79
0105 31
0106 10
0107 10
0109 10
010A 4
010B 6
010C 6
010D 2
010E 11
010F 11
02B1 11
02B2 11
02B5 11
0110 10
0111 39
0114 31
0115 35
0117 18
0119 13
0229 15
011A 15
011C 68
011E 3
011F 16
0120 6
0121 14
0122 14
0123 14
0124 21
0125 8
012B 2
012C 3
012D 4
0131 86
0132 6
0133 6
0135 7
0136 7
0137 6
0139 16
013A 4
013B 4
013C 4
013D 6
013E 24
0141 14
0142 6
0144 23
0145 19
0147 39
0148 8
0177 8
0179 5
017B 5
017D 7
0188 8
0189 4
018B 4
018C 29
018D 29
018F 6
0191 86
0192 24
0194 30
0196 9
028A 18
0199 4
019A 14
019B 10
01AB 12
01AC 6
01AD 6
025A 6
01B3 67
01B4 12
01B5 18
01B8 3
01C3 3
01C4 22
01C5 22
01C8 13
01C9 97
01CC 9
01D6 4
01D7 11
01D8 54
022A 58
01D9 53
022B 57
01DA 60
022C 65
01DE 33
01E0 30
01E2 34
01E4 2
01E6 26
01E9 81
01EA 6
01EB 10
01EC 26
01EE 26
01EF 26
01F0 26
01F4 32
01F5 9
01F6 34
0253 3
0254 3
01F8 2
01FC 2
01FE 5
0227 18
0228 18
0232 9
0233 11
0234 6
0230 12
022E 71
027D 62
0235 62
0239 11
022F 5
0231 26
0237 2
0238 282
0236 10
023A 4
023C 6
023D 6
023E 8
023F 2
0240 2
0241 6
0242 6
0243 6
0257 8
0244 6
0245 3
0246 4
0247 8
0248 8
0249 3
024A 70
024B 4
024C 8
024D 12
024E 6
024F 10
0250 3
0251 34
0252 34
0255 5
0256 5
0258 2
0259 3
025C 4
025D 6
025E 4
025F 6
0260 6
0261 11
0262 11
0263 11
0264 20
0265 20
0266 30
0267 4
0268 4
0269 4
026A 4
026B 4
026C 4
026D 4
026F 2
0270 2
0271 40
0272 44
0273 30
0274 8
0275 37
0276 37
0277 84
0278 2
0279 2
027A 2
027B 14
027C 60
027E 60
027F 8
0283 6
0287 6
0288 6
0289 12
0444 12
0445 10
028B 10
028C 46
028D 34
028E 4
028F 6
0290 4
0291 4
0292 2
0293 70
0294 10
0295 10
0296 10
0297 10
0298 8
0299 6
029A 27
029B 80
029C 66
029D 66
029E 11
029F 3
02A2 8
02A5 8
02A6 8
02A7 8
02AA 4
02AB 36
02AC 6
02AD 8
02B0 85
02B8 22
02BB 8
02B9 191
02BA 11
02BC 6
02B3 107
02B4 6
02B6 7
02B7 7
02C1 7
02C2 7
02C5 30
02C8 3
02C9 3
02C6 30
02C7 7
02CB 65
02CC 4
02CD 71
02CE 10
02CF 6
02D5 2
02D0 2
02D1 2
02D2 2
02D3 4
02D4 29
02D6 6
02D7 6
02D8 10
02D9 10
02DA 3
02DB 3
02DC 3
02DD 32
02DE 6
02DF 36
02E0 34
02E1 33
02E2 20
02E3 22
02E4 11
02E5 9
02E6 6
02E7 6
02E8 6
02E9 6
02EA 6
02EB 13
02EC 67
02ED 59
02EE 60
02EF 8
02F0 10
02F1 2
02F2 2
035C 2
035D 2
035E 2
03DD 18
03DE 18
0439 8
043D 8
043E 8
043F 25
0440 10
0441 4
0442 4
0443 8
0446 14
0448 14
0449 4
044A 6
044B 2
0447 2
07D7 8
07D8 8
07D9 268
07DA 6
07DB 8
07DC 6
07DD 54
07DE 30
07DF 54
07E0 58
07E1 15
07E2 8
07E3 6
07E6 8
07E5 4
07E8 4
07E7 32
07E9 5
07EA 2
07EB 2
07ED 10
07EE 6
07EF 8
07F0 6
07F1 18
07F2 8
07F3 6
07F4 3
07F5 6
07F6 14
07F7 14
07F8 14
07F9 14
07FA 8
07FB 25
07FC 10
07FD 10
07FE 26
0800 26
0801 26
0803 4
0804 14
0805 14
0806 2
0807 4
0808 14
0809 50
080A 18
080B 6
080C 2
080D 3
080E 14
080F 20
0810 3
0812 8
0813 8
0814 86
0816 6
0818 6
081A 4
0824 6
081B 10
081C 10
081D 22
081E 8
081F 8
0820 11
0821 2
0822 9
0823 9
0825 9
0836 9
0837 3
0839 66
083A 5
083B 2
083D 6
083E 26
0840 26
0841 4
0827 6
0828 14
0829 12
082A 10
082B 6
082C 10
0842 6
0843 6
0844 2
0845 10
0846 4
0847 4
0848 4
0849 16
084A 2
084B 19
084C 10
084D 10
084E 5
084F 6
0850 7
0855 6
0851 6
0852 2
0853 2
0854 2
0856 2
0857 2
0858 2
0859 2
08B1 2
082D 2
08B2 2
08AF 10
08B0 17
08B3 17
08B4 2
08B5 6
08B6 3
02F3 3
02F4 3
02F5 7
02F6 7
08B8 10
08B9 12
08BA 10
08BB 8
08BC 10
08BD 8
08BE 14
08BF 8
08C3 10
08C4 8
08C5 6
08C6 4
08C0 4
08C1 2
08C2 2
08C7 2
08C8 34
08C9 2
08CA 2
08CB 2
097B 2
08CC 109
08CE 2
08CF 10
08D0 9
08D1 7
08D2 10
08D3 10
08D4 8
08D5 8
08D6 6
08D7 28
08D8 27
08D9 30
08DA 26
08DB 27
08DC 26
08DD 27
08DE 27
08DF 50
08E0 51
08E1 51
08E2 27
08E3 149
08E4 6
08FC 30
08FD 6
08FE 6
08FF 24
0900 24
0901 24
0902 24
0903 24
0904 24
0905 24
0906 24
0907 5
0908 5
090A 26
090D 26
090E 2
0910 10
0911 30
0912 10
0913 30
0914 30
090F 30
0915 30
0916 26
096B 4
096C 6
096D 6
096E 6
096F 7
0971 6
0972 6
0973 7
0974 2
0975 2
0976 2
0977 14
0978 6
0979 50
097A 50
097C 4
097D 288
097E 12
097F 12
0980 7
0981 7
0982 7
0983 29
0984 28
0985 28
0986 10
0987 10
0988 6
0989 2
098A 2
098D 2
098E 2
098B 2
098C 4
098F 4
0990 31
0991 31
0992 31
0993 31
0994 31
0995 31
0996 31
0997 31
0998 8
0999 11
099A 9
099B 8
099C 6
099D 6
099E 12
099F 12
09A0 6
09A1 2
09A2 6
09A3 6
09A4 18
09A5 7
09AB 6
09A6 12
09A7 10
09A8 16
09A9 10
09AA 16
09AC 16
09AD 10
09AE 17
09AF 4
09B0 8
09B1 4
09B2 8
09B3 4
09B4 6
09B5 2
09B6 6
09B7 4
09B8 6
09B9 4
09BA 2
09BB 6
09BC 6
09BD 2
09BE 2
09BF 4
09C1 10
09C2 10
09C3 8
09C4 8
09C5 1042
09C6 1042
09C7 18
09C8 18
09C9 18
09CA 18
09CB 17
09CC 17
09CD 8
09CE 102
09CF 102
09D0 102
09D1 14
09D2 14
09D3 14
09D4 2
09D5 2
09D6 2
09D8 2
09D7 2
09D9 4
09DA 4
09DB 4
09DC 4
09DD 4
09DE 4
09DF 7
09E0 7
09E1 8
09E2 8
09E3 8
09E4 8
09E5 18
09E6 22
09E7 3
09E8 11
09E9 2
09EE 11
09EF 11
09F0 11
09F5 11
09F6 11
09EA 11
09EB 11
09F7 75
09EC 75
09ED 3
09F3 11
09F4 12
09F1 11
09F2 12
0A04 6
0A05 53
0A06 6
0A07 9
0A03 2
0A08 26
0A12 27
0A13 26
0A14 10
0A32 2
09F8 2
09F9 143
09FA 143
09FB 143
09FC 6
09FD 6
09FE 6
09FF 6
0A00 269
0A01 3
0A02 4
0A09 45
0A0A 47
0A0B 47
0A0C 56
0A0D 56
0A0F 56
0A10 56
0A11 56
0A0E 14
0A15 12
0A16 26
0A17 6
0A18 14
0A19 2
0A1A 23
0A1B 2
0A1C 2
0A1D 2
0A1E 3
0A1F 2
0A20 21
0A21 3
0A22 5
0A23 5
0A24 66
0A25 6
0A26 7
0A27 8
0A28 3
0A29 6
0A2A 6
0A2B 14
0A2C 12
0A2D 12
0A2E 6
0A2F 7
0A30 106
0A31 106
0A33 7
0A34 6
0A35 4
0A36 7
0A37 57
0A38 3
0A39 36
0A3A 12
0A3B 12
0A3C 12
0A3D 18
0A3E 18
0A3F 9
0A40 11
0A41 18
0A42 43
0A43 85
0A44 85
0A45 2
0A46 14
0A47 3
0A48 2

**Comment by sctnightcore** [comment]
@m3kgin3er How do we hide the work of ench.pl? 
https://www.img.in.th/images/810f9f5bee8e9f67a077fb19e5d72b7a.png

**Comment by m3kgin3er** [comment]
Sorry, its working. But my plugin have several errors.
Because i've edited this thing so many times.

But i hope i've fixed it .

**Comment by sctnightcore** [comment]
@m3kgin3er  is working <3

**Comment by m3kgin3er** [comment]
Close u thread pls ! Maybe u'll receive error using fly wings.

**Comment by LoseracK** [comment]
@sctnightcore won't u close u issue ?

**Comment by moneyisgod** [comment]
@sctnightcore close it haha
