### ISSUE TITLE
Server denied conection

### ISSUE THREAD

**Issue by tupaclol** [OpenKore/openkore#558]
Help:
Server denied conection.

[ReburnRO]
ip 63.143.54.78
port 6900
version 55
master_version 22
serverType kRO_RagexeRE_2015_11_04a
charBlockSize 147
recvpackets private.txt
addTableFolders Translated\kRO_english;kRO

Erro: https://drive.google.com/open?id=0BwgiqMDXNQOkcUVwOExLX3hfRlE
exe: https://drive.google.com/file/d/0BwgiqMDXNQOkUHFqb1BCVUtYd1k/view?usp=sharing

Recvpackets: `https://pastebin.com/4AP08B0s`

**Comment by m3kgin3er** [comment]
E sobre as chaves ? Quando se extraiu o recvpackets, você pegou as chaves ?

**Comment by tupaclol** [comment]
Thanks

**Comment by m3kgin3er** [comment]
Worked or not ?

**Comment by windhamwong** [comment]
We see no more response from author. closing.
