### ISSUE TITLE
Recvpackets NovaRO ? 2017-01-23

### ISSUE THREAD

**Issue by tupaclol** [OpenKore/openkore#561]
It is possible to extract recvpackets 2017-01-03 ?

**Comment by lututui** [comment]
If the Ragexe.exe isn't protected or compressed, yes. Even if it is compressed or protected, you should be able to if you manage to remove the compression/protection correctly.

Yommy and Neo's PEEK is quite the tool, have you tried it out?

**Comment by m3kgin3er** [comment]
I was thinking in create a database to get the keys and the packets of 2017 clients.
But no way to deduce what is what.

**Comment by alisonrag** [comment]
@sctnightcore  do you have this server information?

**Comment by sctnightcore** [comment]
nova ragnarok ! 
use with Ragnashield ! 
@alisonrag

**Comment by alisonrag** [comment]
shields are not supported
