### ISSUE TITLE
BOT ragnarok idRO Gravindo Chaos Server

### ISSUE THREAD

**Issue by anymons** [OpenKore/openkore#564]
I need someone help me to build bot for this server. too many indonesian people can break this RO. but they give price too expensive for me. about $300 / month and they promise can break every this Ragnarok Maintenance . its crazy right? cos i dont know who they are. and how if they cheats me? i try to make a deal with them with pay/days but they dont accept. i dont know why they do this? maybe want cheating many people. cos no one know who they are. if the reader in here Have/ can build BOT RO gravindo . please send Private massage to me or if you want i pay its oke but pay/days cos i dont know who are you and when this RO will be maintenance. this is data for this server. Sorry my english too bad. thanks

Indonesia - idRO: Chaos]
ip 202.93.25.81
port 6900
master_version 12
version 2
patchserver patchragnarok.gravindo.id
patchpath /patch02
serverType idRO
secureLogin 1
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 136
charDeleteDateType 1

**Comment by m3kgin3er** [comment]
Follow the other thread and wait for any response non-paid.

**Comment by anymons** [comment]
no one people in indonesia will give BOT free. cos you know what? cos in here too many leecher. want free but they sell it. and indonesian people economy not rich . so they will sell to get giveback. its oke i pay but i want pay/days cos i never know who they are. when this RO will be maintenance and they still can break the game.

**Comment by m3kgin3er** [comment]
I'll try to check if some VPN work with me. This week i'll talk with my brother and he 'll help me with this. By proxying. But its hard. But vpn looks hard too.

**Comment by anymons** [comment]
its oke dude. by the way  thanks to help. :)

**Comment by ov3rhead** [comment]
anyone sell the bot ? can contact me calvinoktavioro@gmail.com

**Comment by LoseracK** [comment]
@ov3rhead 
Check my last post 👍 
https://github.com/OpenKore/openkore/issues/519#issuecomment-298457327

**Comment by joserizal99** [comment]
lol 300$/month ? better buy direct item than botting

**Comment by johanskizo** [comment]
@LoseracK do you have email sir? i will support premium vpn for you :)

**Comment by BangRoJae** [comment]
BOT in idRO is just like DIAMOND. YOU CAN MAKE 10k - 15k US $ a month. If you can breach their security, better use for yourself, and sell the zeny in market through VISA / Pay Pal/ or any international payment. RMT is LEGAL in there. You can easily sell zeny without worrying about get busted. Demand is still high and good for zeny. Gravindo will release new server Loki at 23rd May 2017, and you better make a better deal rather than 300 US $.

**Comment by LoseracK** [comment]
Well i've already tried everything.

**Comment by BernardRayosoJr** [comment]
mga paps pa send nman sa akin unable to inject NetRedirect.dll
rayosomarkjherald@gmail.com

**Comment by apuk321** [comment]
maaf mau nanya apa ada yang bisa bantu saya tentang bot di ragnarok private server?
untuk server.txt nya
[PlayOdin]
ip 103.52.146.53
port 6900
master_version 12
version 55
serverType kRO_RagexeRE_2018_06_21a
serverEncoding Western
gameGuard 0
addTableFolders eA;kRO/RagexeRE_2018_06_21a;translated/kRO_english;kRO
charBlockSize 155
pinCode 1
charDeleteDateType 1
rankingSystemType 1
private 1
recvpackets recvpackets.txt
muncul error seperti ini pada saat di jalankan
![image](https://user-images.githubusercontent.com/26170183/120108282-b0c2b800-c18e-11eb-9eb6-7da936d98f67.png)

**Comment by faisalakmal** [comment]
hello dude, how to get info server? im using grf tools for get clientinfo but the file is encrypt
