### ISSUE TITLE
Noob here need some help Packet Tokenizer: Unknown switch: 0A27

### ISSUE THREAD

**Issue by Monteray-Jack** [OpenKore/openkore#565]
Playing on Chaos, there was just an update maybe this has something to do with it failing?

Now, what information do you need from me? and how do I find it?

Packet Tokenizer: Unknown switch: 0A27 (it seems to be connected to an occasional error about Unknown Status where my HP no longer updates)

**Comment by m3kgin3er** [comment]
You need extract the correct recvpackets of your server.

**Comment by Monteray-Jack** [comment]
I think I fixed it found something in the receivepackets.txt that was missing

**Comment by Monteray-Jack** [comment]
Thanks for any and al help
