### ISSUE TITLE
Openkore Ofline for testing

### ISSUE THREAD

**Issue by Zelecktor** [OpenKore/openkore#568]
Hello people.
Something that i found very interesting is to have an openkore offline for test purposes. The thing is that make, compile and do all shit to get a working server is a wasted work for testing a few things for botting purposes.
A few days ago i found this topic:
https://rathena.org/board/topic/109823-ragnarok-online-complete-offline-pack-2017-make-your-ro-server-in-less-then-5-minutes/
That allow to you open a fully rAthena Emulator updated at 2017 in just 3clicks. Easy and fast. But Openkore right now doesnt support the client, and still got several packet error with this emulator.
I would like to develop the correct server types to get openkore working on this emulator. If It it works, it  would help to develop new plugins, macros and bug fixes.

Thanks very much

**Comment by Zelecktor** [comment]
A pull request to add the server types and the local conection on servers.txt on the master branch would be awesome to allow more people test this.

**Comment by m3kgin3er** [comment]
There are no documentation about 2017 serverTypes. Only official servers.
It's not so hard to make a new serverType.
For example, give me one 2017 client !

**Comment by Zelecktor** [comment]
Hello
Thanks for helping, but on this case the emulator is updated at march 2017
The client is 2015-11-04a ragexe.exe

you can enter in the forum and download the zip kit (there is the emulator,
client, everything). 400MB aprox all that. if you need to crack somthing in
the folder that may be usefull to get the whole information.

2017-04-29 21:14 GMT-03:00 SkylorÐ <notifications@github.com>:

**Comment by walkietalkie89** [comment]
sory for you, but openkore didn't support private server, only official i think.
private server always change they packet in every version they made, it's endless work. so don't give up!

**Comment by Zelecktor** [comment]
but this one never changes, thats why i need help to develop a functional
conection. All people that would like to run an openkore offline can do it
easy and simple. Just a correct server type and its done.

2017-05-01 23:05 GMT-03:00 walkietalkie89 <notifications@github.com>:

**Comment by holoc** [comment]
@Zelecktor were you able to connect to this quick setup private server? I'm just using the default settings for localhost and OK not recognizing the packets and map I was currently on. I'll try later to see if I can extract the packets from the client and see if that'll work.

**Comment by Zelecktor** [comment]
Thanks, I hope this works, but in stead of extracting the packets (Already i did it, using peek master) there isnt a server type compatible with 2015-11-04a ragexe client. (already the emulator is compiled with those packets). Thats something that i dont know how to do.

**Comment by holoc** [comment]
@Zelecktor hmm, looks like this might be related? https://github.com/OpenKore/openkore/issues/497

**Comment by Zelecktor** [comment]
Yeah, but i couldnt find the files. Necessarily they have to add some lines to some files in the network src, some adds in server type 0 and the new files server type with the client packets. I know is difficult and is a kind of programation that i cant work

**Comment by moneyisgod** [comment]
http://forums.openkore.com/viewtopic.php?f=7&t=212121

**Comment by kaliwanagan** [comment]
looks great! @Zelecktor i hope you're still interested with this, because this would be a great way to test new ai routines (or fixes, like the one where kore tries to route first before attacking, which then exhibits a very botlike behavior).

@sctnightcore or @moneyisgod can we turn that into a github PR so we can merge?

**Comment by Zelecktor** [comment]
Yeah thanks so much for adding 2015 clients, i'll test it tomorrow and see if they works. Thanks very much

**Comment by moneyisgod** [comment]
@kaliwanagan 

Hi Sir.

Recently i've noticed that some private servers is giving problem when :

Attacks monster
But i know how to fix.

**Comment by sctnightcore** [comment]
The important thing is no server to test.
And my internet is very slow.
@kaliwanagan 
and 
![image](https://user-images.githubusercontent.com/23263315/28812312-5b4db4f2-76be-11e7-92ae-2b13a95b260d.png)
[100/100] You attack Monster Worm Tail (3) (Dmg: 89) (Delay: 390ms)
It does not show
I do not know why
