### ISSUE TITLE
just download the openkore here  and no attack  only walking around the map  pls help 

### ISSUE THREAD

**Issue by a2362998** [OpenKore/openkore#569]
need help pls  openkore no attack only waling around

**Comment by a2362998** [comment]
[iRO] Packet Tokenizer: Unknown switch 09DB, 09DD  need help pls guys    new in this game

**Comment by m3kgin3er** [comment]
http://forums.openkore.com/viewtopic.php?f=6&t=211637&p=274647#p274647

**Comment by a2362998** [comment]
what did u link m3kgin3er   i can't see anything from your link   help me pls

**Comment by fsinz** [comment]
@m3kgin3er dud how about DC when changed map, whats a problem.. or my packets wrong?

**Comment by m3kgin3er** [comment]
How about attackAuto in your config.txt ? 
DC when changed map ? that's new.
