### ISSUE TITLE
RECVPACKET iRO.

### ISSUE THREAD

**Issue by Mal2t** [OpenKore/openkore#577]
I've got message in RECVPACKET missing:

Packet Tokenizer: Unknown switch: 0A27
Packet Tokenizer: Unknown switch: 0A30
Packet Tokenizer: Unknown switch: 09F8

Can anyone update the latest recvpacket.txt for iRO or PM me to find out?

**Comment by Monteray-Jack** [comment]
For the 0A27 in recvpackets.txt towards the end make it look like this

0A10 -1 4 0
0A27 8 8 1 
0A2D -1 4 0

I had that a few week ago, so search for 0A10 and make sure 0A27 8 8 1 is after it,but before 0A2D

**Comment by Razalka** [comment]
You can update your own recvpackets by extract it from your RO client.
Use yommy packet extractor.

**Comment by Mal2t** [comment]
@Monteray-Jack THX so much.
@Razalka I used it and getting error "failed to find PACKET_CZ_ENTER". So how to do next?

**Comment by Monteray-Jack** [comment]
LOL I am trying to use it myself and I cannot even get as far as you Mal2t, all  I get is "DLLGen: Reference Location not found"

**Comment by Razalka** [comment]
The extractor is no need to be fully worked to extract the packet.
After the packet exct start, close it, it regenerate the recvpacket in thr output folder and you can move to the next process.

Btw, the ro client, its over 14mb or lower ?

**Comment by fortheoverlord** [comment]
@Razalka 

I tried yommy packet extractor for iro..
I browsed a file, and clicked on "extract lengths"
Error message： Dllgen: packet key pattens not found.
I tried all exe files in my ro file folder.
Also the ro client is 7,637 KB (ragexe.exe)
