### ISSUE TITLE
Recvpacket iRO Chaos (Unknown Switch)

### ISSUE THREAD

**Issue by Monteray-Jack** [OpenKore/openkore#578]
Packet Tokenizer: Unknown switch: 0A30
Packet Tokenizer: Unknown switch: 09F8

Edit : Also 0A24 now

ooh another Edit : and thanks to everyone and anyone who takes their own precious time to help me figure this out!!

**Comment by userix** [comment]
same problem here with latest update

**Comment by Monteray-Jack** [comment]
Yeah I am trying to figure out this whole packet extractor thing to no avail.....

**Comment by bradley02** [comment]
it is now been pulled into git and ready to be evaluated by mod.
additional unknown switch: 09FA

**Comment by Monteray-Jack** [comment]
So its being worked on?

**Comment by Monteray-Jack** [comment]
Kind of making me blasted crazy, I cannot figure out even the basics of using a packet extractor to update my receive packets trying to use PEEK and I cannot get it to do anything I wish of it.

Trying to educate myself to help myself (and others) but to no avail lol.

I think my missing packets are causing an Inventory is Empty issue and its driving me bonkers lol

**Comment by alisonrag** [comment]
just download the latest version
