### ISSUE TITLE
can anyone teach me? IdRo chaos 

### ISSUE THREAD

**Issue by asinasin** [OpenKore/openkore#579]
![please](https://cloud.githubusercontent.com/assets/28642526/25983335/593b5c5e-370e-11e7-96cb-5ab71c0b6a38.jpg)

**Comment by Monteray-Jack** [comment]
Is your server undergoing an update?

**Comment by asinasin** [comment]
Nope. can you explain why my openkore do that? its old openkore or something

**Comment by olandganteng** [comment]
@Monteray-Jack thats a new server from official IdRO
[Indonesia - idRO: Chaos]
ip 202.93.25.81
port 6900
master_version 12
version 2
patchserver patchragnarok.gravindo.id
patchpath /patch02
serverType iRO
secureLogin 1
secureLogin_type 0
secureLogin_requestCode 8E A4 56 45 64 EB 31 C5 5C DB A7 D1 06 FF 01 C8
#secureLogin_requestCode
secureLogin_account 1
serverEncoding Western
storageEncryptKey 0x050B6F79, 0x0202C179, 0x00E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x007D8D6B, 0x08CB9ED9
addTableFolders idRO
charBlockSize 144
charDeleteDateType 1

can you help us?

**Comment by GustomZ** [comment]
i just changed the IP and then it comes to connected with the client. but something blocked it.
The IP is : ip 202.93.25.70
port 6000
try it out
