### ISSUE TITLE
Quests not showing or recognized

### ISSUE THREAD

**Issue by DornFarah** [OpenKore/openkore#581]
Bounty Board quests aren't being recognized.
![quest list not showing](https://cloud.githubusercontent.com/assets/28642766/25988065/29fa6302-3729-11e7-8de3-8f55c421cc10.png)

I should have all the 70 - 100 Juno Board Quests listed here.

**Comment by bunnyy00** [comment]
Same problem

**Comment by tar14** [comment]
![image](https://cloud.githubusercontent.com/assets/28648866/25994757/60caab02-3739-11e7-9a60-ba5edc1fec82.png)

anyone can help me?

**Comment by DornFarah** [comment]
After getting the updated ServerType0 and recvpackets, the quest info now appears. Thank you. The only problem now is that it seems that the killcount isn't getting updated real-time; the character needs to relog for the killcount to get updated. 

Can anyone please provide guidance on how to fix that?

**Comment by alisonrag** [comment]
fixed in latest version
