### ISSUE TITLE
Can 2015 client use xkore2?

### ISSUE THREAD

**Issue by hotspicy945** [OpenKore/openkore#582]
charBlockSize 147

when I use xkore2,after select the role
I always disconnect@@

Can 2015 client use xkore2?

**Comment by SabadyshynV** [comment]
why not.... :/

**Comment by hotspicy945** [comment]
hi @SabadyshynV 

But I testing a few 2015 client server,always disconnect

I use debug 1 & debugPacket_received 1
got this message

[parseMsg] << Received packet:      007F - Received Sync [ 6 bytes]
[outgoing] Packet Tokenizer: Unknown outgoing switch: F792


then I disconnect

**Comment by hotspicy945** [comment]
OH,I uncareful to click the close issue@@
But the issue not be solved, so I reopened

**Comment by sctnightcore** [comment]
Now client 2015-2016 work for xkore 0 2 3  !

**Comment by windhamwong** [comment]
@hotspicy945 please provide more data if you are still encountering issues.
Also, please update your OpenKore. Please reopen if you can provide more data.
