### ISSUE TITLE
iRO Packet Tokenizer: Unknown switch: 09F9 , 0A24

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#583]
Have problem:
Unknown switch: 09F9
Unknown switch 0A24
Unknown switch: 0A30
This spoils the counting of killing mobs in bounty quests. 
09F9 makes quests impossible and talks with some NPC

**Comment by bradley02** [comment]
update your recvpackets to support 09F9
0A24 related to Achievement Sytem ignore it at the moment
0A30 it is already fixed., update yours

**Comment by Glikadin** [comment]
Hey , i have the last ubdate from https://github.com/OpenKore/openkore

**Comment by Monteray-Jack** [comment]
OK so 09F9 after 09DF 7 7 1? but what is after 09F9? should I just randomly try stuff in recvpackets like 7 7 1?

**Comment by Glikadin** [comment]
09F9:
```
[265]           S>c             0ms.            17:33:04 .722      19.05.17
-------------------------------------------------------------------------------
 TType: undef   Server: undef   Parse: off (auto)  EnCode: undef (auto)
------- 0  1  2  3  4  5  6  7 -  8  9  A  B  C  D  E  F    -------------------
TType íå îïðåäåëåí (îïèñàíèå)
000000 F9 09 29 EC 00 00 01 00 | 00 00 00 00 00 00 00 00     ù.)ì............
000010 00 00 00 00 00 00 00 00 | 00 00 00 00 00 00 00 00     ................
000020 00 00 00 00 00 00 00 00 | 00 00 00 00 00 00 00 00     ................
000030 00 00 00 00 00 00 00 00 | 00 00 00 00 00 00 00 00     ................
000040 00 00 00 00 00 00 00 00 | 00 00 00 00 00 00 00 00     ................
000050 00 00 00 00 00 00 00 00 | 00 00 00 00 00 00 00 00     ................
000060 00 00 00 00 00 00 00 00 | 00 00 00 00 00 00 00 00     ................
000070 00 00 00 00 00 00 00 00 | 00 00 00 00 00 00 00 00     ................
000080 00 00 00 00 00 00 00 00 | 00 00 00 00 00 00 00        ...............

```
I don `t know how to calculate the size. 
I can track other packages. It will be useful?

**Comment by Glikadin** [comment]
i take this ubdate: https://github.com/OpenKore/openkore/pull/586/commits/a0804be03e8e7f2b0fdf2a7b021c01a30016396f
Still need to fix: 09F9 and 09FA

**Comment by premier91** [comment]
do u guys mind share the unpack ragexe.exe file?

**Comment by ZaskarAlpha** [comment]
how did you fix packet tokenizer 0A30?

**Comment by premier91** [comment]
I'm not encounter that error, but for the latest update, I just follow this
guide from openkore.

http://forums.openkore.com/viewtopic.php?f=16&t=211887

**Comment by alisonrag** [comment]
just download the latest version
