### ISSUE TITLE
AI Get Stuck Not able to attack other monsters around

### ISSUE THREAD

**Issue by payne84** [OpenKore/openkore#584]
Hi Fox this is my first post to Github, I want to thanks you people for your great support.
After 16.1 update in IRO and after new supported system also openkore AI get stuck and not able to attack 
other monsters. it keep attacking dead monster even if "as" command is used in console.
Please help people, 
Thanks in Advance.

**Comment by bradley02** [comment]
maybe related to many unsupported packet that is why it doesnt clear the monster you kill.
try updating your openkore to the latest git and get updated recvpacket

**Comment by payne84** [comment]
Thanks a lot for reply sir.

I have downloaded latest openkore yet i am facing this problem, most of the problems are resolved with new openkore but still AI get stuck after killing 2 to 3 monsters and if they mobbed then chances are even high plz help regarding this problem.

Thank you so much....

**Comment by bradley02** [comment]
are you using wxstart?

**Comment by payne84** [comment]
Thanks for reply, i am using CUI only using start.exe but still facing problem have downloaded new updated 
openkore from github , i take it from master update.
should i try any other update??
plz help..

**Comment by payne84** [comment]
Hello Friends 
i have found that AI get stuck after message Packet Tokenizer Unknown Switch : 09FA
once i receive this message then bot stop attacking even if other monster attack it.
plz help bro there is no such issue with slave healer bot but with attacker bot its a major problem.

PLZ help people.

**Comment by Monteray-Jack** [comment]
Similar Issues here I think it may be related to this 

Timeout on Map Server, connecting to Account Server in 30 seconds...
Incoming data left in the buffer:
================================================
66 bytes   May 17 17:58:19 2017
  0>  DB 09 5C 00 05 96 D2 00    00 00 00 00 00 C8 00 05    ..\.............
 16>  00 00 00 00 00 00 00 34    04 00 00 00 00 00 00 00    .......4........
 32>  00 C8 2D 77 20 00 00 00    00 00 00 00 00 00 00 00    ..-w ...........
 48>  00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 16    ................
 64>  41 71                                                 Aq
Only 66 bytes in the buffer, when 09DB's packet length is supposed to be 146302516 (wrong recvpackets?)

I leave my openkore minimized and when I check is out sometimes I am kind of obviously dead  tho Kore shows full health and I see what appears to be a strong of enemy attacks happening so fast its a blur which doesnt make sense as I am already dead (which Kore will not recognize til I relog)

The recent update on iRO Chaos has me scratching my head

**Comment by payne84** [comment]
Thanks a lot for reply sir
I am not facing time out on server problem but i am facing problem AI gets stuck and trying to kill dead monster and keep attacking them even if it killed by other aggressive monsters. if multiple attackers in the party then it'll become constant problem.
PLZ people help me regarding this issue...

Thanks in advance.

**Comment by GustomZ** [comment]
can u email me please. i want to ask something thanks

2017-05-18 12:42 GMT+07:00 payne84 <notifications@github.com>:

**Comment by payne84** [comment]
Thanks for reply my email address is ramesh.gami511@gmail.com..
anything you want to ask I'll be there sir.

**Comment by payne84** [comment]
Plz resolve Unknown Packet Tokenizer Switch: 09FA
Due to this instances are also creating problems and character gets disconnected while getting in to the instances.
this switch is come up when you have bounty board killing quest or other monster killing quest like from grandpa, if you kill single monster from your quest no problem kore will give packet tokenizer : 09FA and your bot will function as normal but if you kill multiple monster from your quest then it get stuck plz people help regarding this issue.
Thanks in advance..

**Comment by a2362998** [comment]
nothing can help same shit again and again  they don't want to fix it

**Comment by payne84** [comment]
it has been resolved but you need to manually update the settings for openkore
if need more help mail me its on the top. thanks for support.
