### ISSUE TITLE
Cant login to IDRO gravindo server

### ISSUE THREAD

**Issue by GustomZ** [OpenKore/openkore#587]
Please someone help me to solve this problem. I think the gameguard blocked me. Please every master in here help me to solve this. Thanks before. or sent me an email to blazing.scythe@gmail.com
thanks a lot before.
![capture](https://cloud.githubusercontent.com/assets/20120511/26139636/56eea2e8-3afc-11e7-9c65-9cbf70a60f81.PNG)

**Comment by operacake** [comment]
sama gan

**Comment by rachmatagungpr** [comment]
does anyone solve this issue yet ? i got the same problem

**Comment by franksbean** [comment]
bot for idRO pls THK
