### ISSUE TITLE
help me find the crypted mid key

### ISSUE THREAD

**Issue by k1nt4r0** [OpenKore/openkore#588]
@LoseracK help me to find the crypted mid key sir for a private server
i try to use PEEK and it successfull but no mid key on the recvpackets.txt i extracted.

the client date : Nov 02 2015
and i use kRO_RagexeRE_2015_11_04a St
but when i login with openkore debug it say
Encrypted MID : [0360]->[5B78] / KEY : [ 0x45B9]->[0x5818]
and my openkore got 006A = "The server denied you connection."

**Comment by sctnightcore** [comment]
wait 
@k1nt4r0  server ?

**Comment by k1nt4r0** [comment]
this, privatero.net

**Comment by Slipxxliose** [comment]
Which keys are u using ?
