### ISSUE TITLE
openkore idRO stuck, where should i begin?

### ISSUE THREAD

**Issue by BIGCOW71** [OpenKore/openkore#589]
Checking for new portals... none found

Connecting to Account Server...
Connecting (202.93.25.81:6900)... connected
Secure Login...
Sending encoded password...
Timeout on Account Server, reconnecting. Wait 0 seconds...
Connecting to Account Server...
Connecting (202.93.25.81:6900)... connected
Secure Login...
Sending encoded password...

where should i begin to make it works?
gimme some clue to overcome this...
im totally noob

**Comment by haried** [comment]
more info for this

before 16 May 2017 MT, before starting BOT we need to sniff one by one and put it in OK > src > Network > PacketParser like this
![untitledasdasd](https://cloud.githubusercontent.com/assets/28757215/26206544/4bd9a060-3c0f-11e7-9711-2bd13bbd2075.jpg)
 but after 16 May MT we got different sniffing result
![untitled02](https://cloud.githubusercontent.com/assets/28757215/26206572/69a3605e-3c0f-11e7-908e-d9d681e57cc9.jpg)

what part I must change? Thanks before (sorry for bad english)

**Comment by thecupu** [comment]
@BIGCOW71 
dont screenshoot like that, someone can steal your ID

**Comment by BIGCOW71** [comment]
@thecupu i didnt screenshot anything
@haried km patokan sniff nya apa bro?
