### ISSUE TITLE
Avoid being banned

### ISSUE THREAD

**Issue by kokopoknat** [OpenKore/openkore#590]
any suggestions? nor is there a config to avoid getting banned?

**Comment by hexafluoride** [comment]
voting to reopen

**Comment by lututui** [comment]
avoid.txt
http://wiki.openkore.com/index.php/Avoid.txt
http://wiki.openkore.com/index.php/AvoidList

avoidGM on config.txt
http://wiki.openkore.com/index.php/AvoidGM_talk
http://wiki.openkore.com/index.php/AvoidGM_reconnect
http://wiki.openkore.com/index.php/AvoidGM_near_inTown
http://wiki.openkore.com/index.php/AvoidGM_near
http://wiki.openkore.com/index.php/AvoidGM_namePattern
http://wiki.openkore.com/index.php/AvoidGM_ignoreList

There's also allowedMaps.
http://openkore.com/index.php/AllowedMaps

**Comment by alisonrag** [comment]
In my point of view this section is for reporting errors and bugs.
Tutorials and help requests should be made in the forum~:
http://forums.openkore.com/
