### ISSUE TITLE
euRO packet tokenizer : unknown switch : 0990

### ISSUE THREAD

**Issue by Shinta63** [OpenKore/openkore#591]
Hello,

I've took the latest version of recvpackets.txt from code tab, but the message remains.
same error : packet tokenizer : unknown switch : 0990
If someone could help, thanks in advance

**Comment by Shinta63** [comment]
hello, I searched on different forums, and tested several tool, Peek (http://forums.openkore.com/viewtopic.php?f=36&t=207278)
& also followed http://wiki.openkore.com/index.php/Packet_Length_Extractor
but none are working with my .exe (euRO) => finish in getting "Search for Packet Len Map failed!"

is someone can help :) thanks

**Comment by Razalka** [comment]
Size of your exe, its over 14mb or not ?

**Comment by Shinta63** [comment]
no, my Ragexe.exe is 6829Ko

**Comment by sctnightcore** [comment]
NOW  : euRO is fRO !

**Comment by windhamwong** [comment]
I am sorry but the issue is 5 months ago. We will revisit all servers later on for fixing issues.
