### ISSUE TITLE
Kafra position at Prontera

### ISSUE THREAD

**Issue by hendra814** [OpenKore/openkore#594]
Since prontera map has change
all the kafra position has been changed too.
please change the kafra coordinate so bot will work for teleportation into another map.
Thanks

**Comment by Glikadin** [comment]
.../tables/portals.txt
[portals.txt](https://github.com/OpenKore/openkore/files/1030629/portals.txt)

**Comment by hendra814** [comment]
Bump
please update into github

**Comment by kaliwanagan** [comment]
Have you confirmed that it works?

**Comment by hendra814** [comment]
@kaliwanagan 

yes it's work for non VIP, because it's just change for non VIP

**Comment by kaliwanagan** [comment]
Alright thanks for confirming, we'll see if we have enough bandwidth to test this out over the weekend 👍

**Comment by alisonrag** [comment]
portals in prontera are now updated
just download the last version

**Comment by hendra814** [comment]
Thanks for the update

**Comment by hendra814** [comment]
Nothing changes
what a pitty
