### ISSUE TITLE
new bank system Unknown switch: 09AB  09A6 09A7 09A8  09A9 09AA

### ISSUE THREAD

**Issue by kou90258** [OpenKore/openkore#598]
Banking system
open bank_list Sent 09AB [ 6 bytes] > Received 09A6 [12 bytes]
[May 28 12:48:21 2017.18] Packet Parser: Unknown switch: 09AB
[May 28 12:48:21 2017.19] << Sent by RO client:    09AB [ 6 bytes]
[May 28 12:48:21 2017.19] ================================================
<< Sent by RO client:    09AB [6 bytes]   May 28 12:48:21 2017
  0>  AB 09 A8 FA 72 01                                     ....r.
[May 28 12:48:21 2017.19] Packet Parser: Unknown switch: 09AB
[May 28 12:48:21 2017.31] << Received packet:      09A6 [12 bytes]
[May 28 12:48:21 2017.31] ================================================
<< Received packet:      09A6 [12 bytes]   May 28 12:48:21 2017
  0>  A6 09 00 00 00 00 00 00    00 00 00 00                ............
[May 28 12:48:21 2017.31] Packet Parser: Unknown switch: 09A6

deposit  
Sent 09A7 [10 bytes] > 00B1 - Your Status Info (Exp, Job Exp, Zeny) [8 bytes] >Received 09A8 [16 bytes]

[May 28 12:48:25 2017.93] Packet Parser: Unknown switch: 09A7
[May 28 12:48:25 2017.94] << Sent by RO client:    09A7 [10 bytes]
[May 28 12:48:25 2017.94] ================================================
<< Sent by RO client:    09A7 [10 bytes]   May 28 12:48:25 2017
  0>  A7 09 A8 FA 72 01 01 00    00 00                      ....r.....
[May 28 12:48:25 2017.94] Packet Parser: Unknown switch: 09A7
[May 28 12:48:26 2017.11] << Received packet:      00B1 - Your Status Info (Exp, Job Exp, Zeny) [ 8 bytes]
[May 28 12:48:26 2017.16] ================================================
<< Received packet:      00B1 - Your Status Info (Exp, Job Exp, Zeny) [8 bytes]   May 28 12:48:26 2017
  0>  B1 00 14 00 13 1A 00 00                               ........
[May 28 12:48:26 2017.37] You lost 1 zeny.
[May 28 12:48:26 2017.25] << Received packet:      09A8 [16 bytes]
[May 28 12:48:26 2017.25] ================================================
<< Received packet:      09A8 [16 bytes]   May 28 12:48:26 2017
  0>  A8 09 00 00 01 00 00 00    00 00 00 00 13 1A 00 00    ................
[May 28 12:48:26 2017.25] Packet Parser: Unknown switch: 09A8

Withdrawals

Send 09A9  Received 09AA  00B1 - Your Status Info (Exp, Job Exp, Zeny) [8 bytes] 

[May 28 12:48:30 2017.37] Packet Parser: Unknown switch: 09A9
[May 28 12:48:30 2017.37] << Sent by RO client:    09A9 [10 bytes]
[May 28 12:48:30 2017.37] ================================================
<< Sent by RO client:    09A9 [10 bytes]   May 28 12:48:30 2017
  0>  A9 09 A8 FA 72 01 01 00    00 00                      ....r.....
[May 28 12:48:30 2017.38] Packet Parser: Unknown switch: 09A9
[May 28 12:48:30 2017.50] << Received packet:      00B1 - Your Status Info (Exp, Job Exp, Zeny) [ 8 bytes]
[May 28 12:48:30 2017.50] ================================================
<< Received packet:      00B1 - Your Status Info (Exp, Job Exp, Zeny) [8 bytes]   May 28 12:48:30 2017
  0>  B1 00 14 00 14 1A 00 00                               ........
[May 28 12:48:30 2017.50] You gained 1 zeny.
[May 28 12:48:30 2017.68] << Received packet:      09AA [16 bytes]
[May 28 12:48:30 2017.68] ================================================
<< Received packet:      09AA [16 bytes]   May 28 12:48:30 2017
  0>  AA 09 00 00 00 00 00 00    00 00 00 00 14 1A 00 00    ................
[May 28 12:48:30 2017.69] Packet Parser: Unknown switch: 09AA

**Comment by Slipxxliose** [comment]
U kiddin bRO O.O

**Comment by kaliwanagan** [comment]
@kou90258 can you tell us which server is this? and if you have an extra account in this server, how to access it?

No promises, but these are good information to have just in case a dev wants to tackle this on.
