### ISSUE TITLE
High CPU usage in Win10

### ISSUE THREAD

**Issue by windhamwong** [OpenKore/openkore#60]
testing environment:
version: OpenKore SVN 9014 (Not latest, but similar)
CPU: Intel i5-3320M CPU @ 2.6GHz (4CPUs)
exe: start.exe
hours: 12hours
map: Rainbow tower 3F (彩虹塔) (ecl_tdun03)
server: twRO

CPU goes 21 ~ 29% after 12hours runtime. RAM is around 183 ~ 229MB. The RAM usage seems like not limited by the system or compressed due to high usage. The user reported that it appears as an issue in Win10 only. It has no problem in Win7.

**Comment by windhamwong** [comment]
Now testing on my own machine, environment:
CPU: Intel i5-6600K CPU @ 3.5GHz
exe: start.exe
same control settings

**Comment by windhamwong** [comment]
Generally found out that lag caused by tons of timeout in aiv.

**Comment by itsrachelfish** [comment]
Can you explain what you mean and why you closed the issue?

You're saying the high CPU usage was being caused by lag? Why would this issue only affect windows 10 and not windows 7?

**Comment by windhamwong** [comment]
I was trying to redirect the issue into my another ticket, https://github.com/OpenKore/openkore/issues/63, however I don't have the power of doing that.
The major issue is related to status however Windows 10 and latest Perl version are also the keys of casuing high CPU and memory.
