### ISSUE TITLE
An error of openkore macros

### ISSUE THREAD

**Issue by hotspicy945** [OpenKore/openkore#601]
hi,I used the newest openkore and macro plugins

> *** OpenKore what-will-become-2.1 ( version ctime:2017_05_30 ) - Custom Ragnarok Online client ***

My control\macros.txt was UTF-8
but when I trade with other player always crashed

> Malformed UTF-8 character (fatal) at plugins/macro/Macro/Automacro.pm line 605.

this is my error message:

> OpenKore version what-will-become-2.1
> @ai_seq = deal
> Network state = 5
> Network handler = Network::DirectConnection
> Revision: ctime:2017_05_30
> Loaded plugins:
>   plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
>   plugins/macro/macro.pl (macro; description: allows usage of macros)
>   plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
> 
> Error message:
> Malformed UTF-8 character (fatal) at plugins/macro/Macro/Automacro.pm line 605.
> 
> Stack trace:
> Malformed UTF-8 character (fatal) at plugins/macro/Macro/Automacro.pm line 605.
>  at src/Interface/Wx.pm line 163
> 	Interface::Wx::mainLoop('Interface::Wx=HASH(0x43207cc)') called at openkore.pl line 97
> 	main::__start() called at start.pl line 136
> 
> In this line when out:
>   	my ($msg, $arg) = @_;
> * 	$$arg[4] =~ s/[\r\n]*$//;
>   	if (match($$arg[4],$msg)){

I did some test

If my macros.txt
# only have
<img src="http://imgur.com/HiobklY.jpg">

# or

<img src="http://imgur.com/acY3yws.jpg">

# These both OK , do not crashed

 

  

# But If I used console , it was be crashed
<img src="http://i.imgur.com/HtYQpnO.jpg">

And before I used openkore by version r8871 and it's old macros plugin
Didn't have this problem @@

Has anyone know how to fix it?
Thank you!

**Comment by Slipxxliose** [comment]
Malformed UTF-8 character (fatal)

save as UTF 8
