### ISSUE TITLE
clientSight not working as expected

### ISSUE THREAD

**Issue by sugoikore** [OpenKore/openkore#604]
I was looking into a way to make my bots inside the cities to consume less resources and found remembered about this option:
http://openkore.com/index.php/ClientSight

If I understood the text corret, if configured, I should not be able to see players, skills or any kind of actions outside of the configured clientSight, because it would ignore, but, this isn't working for me, I can see everyone on pl, see skills, monsters, items drops, chat and emotes (that is what I tested, not sure if there is more stuff to test).

**Comment by ramirobo94** [comment]
same problem here

**Comment by flacrasec** [comment]
@Henrybk @allanon @itsrachelfish @lututui @marcelothebuilder @farrainbow any of you know something about this please?

**Comment by kaliwanagan** [comment]
```
clientSight [<number>]
If this option is set, Kore will ignore actors (e.g. monsters, NPCs, players...) whose distance from you
 is greater than or equal to the specified number of blocks. If not specified, Openkore assumes a
 default value of 15.
Note. Some private servers will send actor packets at a ridiculous distance that the normal RO Client
 can't display, and use this for automated banning. This config option will make Kore ignore those
 actors and hopefully avoid auto-bans.
```
This isn't used for squelching messages, but rather so kore doesn't ask for the actor info from the actor (similar to you hovering your mouse on top of the character to find out what their name is).

Maybe you're more interested in http://openkore.com/index.php/SquelchDomains

**Comment by lututui** [comment]
Maybe [removeActorWithDistance](http://openkore.com/index.php/RemoveActorWithDistance) is what you're looking for
