### ISSUE TITLE
pRO

### ISSUE THREAD

**Issue by brithannica29** [OpenKore/openkore#607]
Not an Issue but I would like to know if this program would work on the upcoming Philippine Ragnarok. It is the same system with Thailand Ragnarok.

Any reply is highly appreciated.  Thanks.

**Comment by rollydavid0303** [comment]
Hi been asking this also. I know the fact that the host is same as the Thailand Ragnarok Host which electronics extreme. Tried botting on Thai RO to test found this server info from using wireshark

[ThaiRO]
ip 103.55.55.12
port 6900
master_version 215
version 18 00 00 00
serverType kRO_RagexeRE_2010_01_26a
charBlockSize 108
serverEncoding Western
recvpackets mush-recvpackets.txt
addTableFolders iRO

getting error on the rcv can anyone help us with this. thanks

**Comment by brithannica29** [comment]
How did you go with the config?

**Comment by rollydavid0303** [comment]
same as last time with the original server of pro. just added the server from the server folder 
![image](https://user-images.githubusercontent.com/29172237/26883102-cac9717e-4bce-11e7-8e77-28ccf5cb0afc.png)
