### ISSUE TITLE
Character can't hit the monsters

### ISSUE THREAD

**Issue by BIGCOW71** [OpenKore/openkore#608]
Hi all..

I have problem with my BOT, my BOT job is knight.
first I used two handed sword weapon, skill two handed quicken, bash lv 10 for any monsters
now I want to change it with Lance Weapon, and skill Pierce lv 10
but my BOT didn't respond, while using lance weapon he didn't want hit the monsters, if I changes it back to Two Handed Sword, They works.
I guess openkore had my previcious data, so I must delete it first?
can any one help me solve the problem?

sincerely Thank you

**Comment by bradley02** [comment]
check if your attackDistance meet what distance it should be or enable attackDistanceAuto.

**Comment by BIGCOW71** [comment]
@bradley02
 I already checked it sir, its totally fine, i already copied from another config which using the pierce skill (lance), but its still not working.
i assume openkore had my previous data character, so they still read its as Two handed sword instead of lance, so my character cant hit the monsters.
do you have other ideas?
CMIIW
Thanks Before
