### ISSUE TITLE
packet key for 20151104 dont work 

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#610]
[Packet_Keys]
1 = 0x4C17382A
2 = 0x7ED174C9
3 = 0x29961E4F

$self->cryptKeys(0x4C17382A,0x7ED174C9,0x29961E4F);

dont wonk

**Comment by Slipxxliose** [comment]
Try inverting the second key with the third.

**Comment by sctnightcore** [comment]
[Packet_Keys]
1 = 0x4C17382A
2 = 0x7ED174C9
3 = 0x29961E4F

$self->cryptKeys(0x4C17382A, 0x7ED174C9, 0x29961E4F); not working
$self->cryptKeys(0x4C17382A, 0x29961E4F, 0x7ED174C9); not working

**Comment by Slipxxliose** [comment]
https://github.com/Slipxxliose/openkore

Download my fork.
Use this serverType : 

`serverType kRO_RagexeRE_2015_10_01b`
