### ISSUE TITLE
WTB> Gravindo RO INDONESIA BOT

### ISSUE THREAD

**Issue by disqualify** [OpenKore/openkore#612]
hello is there anyone to sell gravindo RO bot or any tutorial that i can follow ? 
contact me with my email disqualify.wijaya@gmail.com

THANKS !

**Comment by gilbertdone** [comment]
Jual BOT Gravindo
Lock HWID
Cukup bayar 1x
GARANSI SELAMAnya
5ID = 500k
15ID = 1000k
CHAOS/LOKI pilih salah satu tdk bs dua2nya.
WA : 0813 8198 3646

**Comment by Newtonn123** [comment]
SCAMMER above^ beware of the owner of the number "0813 8198 3646"
Gave the money then ignores/blocks the buyer, he didn't even give the BOT. 

*Do note that he will ask for in-game currency/voucher instead of telling him his bank account.

**Comment by ChrstphrR** [comment]
The Issues portion of this github repository are for bugs, features, and code discussions.   This is totally inappropriate. 

Closed.
