### ISSUE TITLE
Thailand RO test Server for Philippines RO

### ISSUE THREAD

**Issue by rollydavid0303** [OpenKore/openkore#613]
Hi Anyone tried botting on the Thailand server? Ive been testing it for the Philippines RO Server which will be open mid june. Both Thailand and Philippines RO are host by electronics extreme thats why i choosen Thai RO for testing. Found this server info for Thai RO.

[ThaiRO]
ip 103.55.55.12
port 6900
master_version 215
version 18 00 00 00
serverType kRO_RagexeRE_2010_01_26a
charBlockSize 108
serverEncoding Western
recvpackets mush-recvpackets.txt
addTableFolders iRO

Im having a error

Unable to load the file mush-recvpackets.txt.
Press ENTER to exit this program.

thanks

**Comment by brithannica29** [comment]
Maybe it has something to do with the gameguard?

**Comment by rollydavid0303** [comment]
I think Thailand RO doesnt use any gameguard like harmony. its only using an easyanticheat when Im starting the game.

**Comment by rollydavid0303** [comment]
not like other server they are using harmony

**Comment by rollydavid0303** [comment]
same as last time with the original server of pro. just added the server from the server folder
![image](https://user-images.githubusercontent.com/29172237/26883166-ecddf230-4bce-11e7-922c-0e73e704c552.png)

**Comment by Sammm-pRO** [comment]
FF
