### ISSUE TITLE
The server has denied your connection.

### ISSUE THREAD

**Issue by MingFaiYau** [OpenKore/openkore#614]
Dear sir,..here is my server config.
[mlRO]
ip 106.106.167.36
port 2001
version 54
private 1
master_version 5
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
charBlockSize 147
addTableFolders twRO

1,I used UE Explorer , the time date stamp is 29/10/2015.
2,I used PEEK to find the "recvpackets.txt" and put it in twRO.
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1056893/recvpackets.txt)

and then it display The server has denied your connection.

After that i set $self->cryptKeys(0x2E885A91, 0x18670101, 0x0A7A61BE); in RagexeRE_2015_11_04a
keys was got in PEEK's ini..which i dont know correct or not..

but the denied message still exist..

Sent packet    : 0066    [ 3 bytes]  [Char Login]
<< Received packet:      020D [ 4 bytes]
<< Received packet:      08B9 [12 bytes]
login_pin_code_request: unknown flag 0
<< Received packet:      0071 - Received character ID and Map IP from Game
Login Server [28 bytes]
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 6D 7E 02 00 (163437)
MAP Name: iz_int.gat
MAP IP: 106.106.167.36
MAP Port: 2003
-----------------------------
Closing connection to Character Server
Disconnecting (106.106.167.36:2002)...disconnected
Connecting to Map Server...
Connecting (106.106.167.36:2003)... connected
Encrypted MID : [0360]->[1C65] / KEY : [0x2E88]->[0x1F05]
Sent packet    : 0360    [ 6 bytes]
<< Received packet:      006A - Connection Failed [23 bytes]
Disconnecting (106.106.167.36:2003)...disconnected
The server has denied your connection.

can anyone gvie me some hints what i should do?

**Comment by Slipxxliose** [comment]
Try using : 

$self->cryptKeys(0x2E885A91, 0x0A7A61BE, 0x18670101);

Supposing you've not inverted the order of keys before.

**Comment by sctnightcore** [comment]
Encrypted MID : [0360]->[564C] / KEY : [0x4C17]->[0x552C]
Sent packet    : 0360    [19 bytes]  
The server has denied your connection.
//2015-11-04aRagexe
packet_ver: 55
packet_keys: 0x4C17382A,0x7ED174C9,0x29961E4F // [Winnie]
	$self->cryptKeys(0x4C17382A, 0x7ED174C9, 0x29961E4F);  not working
        $self->cryptKeys(0x4C17382A, 0x29961E4F, 0x7ED174C9); not working

**Comment by Slipxxliose** [comment]
@sctnightcore this topic is not yours. Go to the forum.

@MingFaiYau Good luck !

**Comment by MingFaiYau** [comment]
@Slipxxliose 
thanks for reply, i tried reorder the 3 keys with 6 combination...but all fail.
here is my .ini which from PEEK
[PacketLengths_20151029.zip](https://github.com/OpenKore/openkore/files/1062827/PacketLengths_20151029.zip)

[Packet_Keys]
1 = 0x2E885A91
2 = 0x18670101
3 = 0x0A7A61BE

[Shuffle_Packets]
0x0369 = 0
0x083C = 1
0x0437 = 2
0x035F = 3
0x0202 = 4
0x07E4 = 5
0x0362 = 6
0x07EC = 7
0x0364 = 8
0x0438 = 9
0x0366 = 10
0x096A = 11
0x0368 = 12
0x0838 = 13
0x0835 = 14
0x0819 = 15
0x0811 = 16
0x0360 = 17
0x0817 = 18
0x0815 = 19
0x0365 = 20
0x0363 = 21
0x0281 = 22
0x022D = 23
0x0802 = 24
0x0436 = 25
0x023B = 26
0x0361 = 27
0x0860 = 28

Is the server encrypted?

when i use old server types which are 2013 version..it show "PIN code is correct."
but "login_pin_code_request: unknown flag 0" with 2014~2015 version ? It is the fail reason?.

Finally thanks for help again.

**Comment by Slipxxliose** [comment]
Well, i don't know if it will work, but edit manually the 0360 to 022D

**Comment by sctnightcore** [comment]
$self->cryptKeys(0x4C17382A, 0x7ED174C9, 0x29961E4F); not working
$self->cryptKeys(0x4C17382A, 0x29961E4F, 0x7ED174C9); not working 

[Packet_Keys]
1 = 0x4C17382A
2 = 0x7ED174C9
3 = 0x29961E4F

**Comment by MingFaiYau** [comment]
@Slipxxliose 
1, I change 0360 -> 002D in my recvpackets and the keys oder is $self->cryptKeys(0x2E885A91, 0x0A7A61BE, 0x18670101); 
---------------------------------------------------------------------------
1.1, I used 2015 11 04a , i can login the server , after that receive many unknow package and disconnect
Other players are not allowed to view your Equipment.
<< Received packet:      00B0 - Your Status Info [ 8 bytes]
<< Received packet:      097B [68 bytes]
Packet Parser: Unknown switch: 097B
<< Received packet:      014E [ 6 bytes]
You are not a guildmaster.
<< Received packet:      01B6 - Guild Info : 0150 [114 bytes]
<< Received packet:      014C - Guild Allies / Enemy List [ 4 bytes]
<< Received packet:      0166 - Guild Member Titles List [564 bytes]
<< Received packet:      0154 - Guild Members List [2916 bytes]
Encrypted MID : [0887]->[6501] / KEY : [0x0305]->[0x6D86]
Sent packet    : 0887    [ 2 bytes]
sit
Encrypted MID : [0369]->[44B1] / KEY : [0x6D86]->[0x47D8]
Sent packet    : 0369    [ 7 bytes]
Disconnected from Map Server, connecting to Account Server in 30 seconds...
---------------------------------------------------------------------------------------------------------
1.2, I used 2013 08 07a , when it going to login the map server...is display error 
Encrypted MID : [022D]->[4B99] / KEY : [0x2E88]->[0x49B4]
Sent packet    : 022D    [19 bytes]
<< Received packet:      0283 [ 6 bytes]
<< Received packet:      0A18 [14 bytes]
Packet Parser: Unknown switch: 0A18
<< Received packet:      0091 - Map Changed [22 bytes]
Incoming data left in the buffer:
================================================
256 bytes   Jun 9 11:10:41 2017
  0>  41 01 0D 00 00 00 28 00    00 00 06 00 00 00 41 01    A.....(.......A.
 16>  0E 00 00 00 01 00 00 00    08 00 00 00 41 01 0F 00    ............A...
 32>  00 00 01 00 00 00 02 00    00 00 41 01 10 00 00 00    ..........A.....
 48>  1E 00 00 00 04 00 00 00    41 01 11 00 00 00 63 00    ........A.....c.
 64>  00 00 14 00 00 00 41 01    12 00 00 00 2E 00 00 00    ......A.........
 80>  04 00 00 00 B0 00 31 00    8D 01 00 00 B0 00 32 00    ......1.......2.
 96>  CE 00 00 00 B0 00 35 00    B8 01 00 00 B0 00 29 00    ......5.......).
112>  A6 00 00 00 B0 00 2D 00    2E 00 00 00 B0 00 2E 00    ......-.........
128>  56 00 00 00 B0 00 2A 00    7D 00 00 00 B0 00 2E 00    V.....*.}.......
144>  56 00 00 00 B0 00 2D 00    2E 00 00 00 B0 00 33 00    V.....-.......3.
160>  06 00 00 00 B0 00 34 00    11 00 00 00 B0 00 2C 00    ......4.......,.
176>  6F 00 00 00 B0 00 2B 00    00 00 00 00 B0 00 2F 00    o.....+......./.
192>  50 00 00 00 B0 00 30 00    03 00 00 00 B0 00 30 00    P.....0.......0.
208>  03 00 00 00 B0 00 2F 00    50 00 00 00 3A 01 0F 00    ....../.P...:...
224>  B0 00 06 00 FC 0E 00 00    B0 00 08 00 DF 01 00 00    ................
240>  B0 00 05 00 FC 0E 00 00    B0 00 07 00 DF 01 00 00    ................
Disconnecting (106.106.167.36:2003)...disconnected
This program has encountered an unexpected problem. This is probably because

**Comment by Slipxxliose** [comment]
Sorry, my excuse.
But you shouldn't modify inside recvpackets. Please, extract the recvpackets again. 

Just use the 2013 and post an SCREENSHOT

**Comment by MingFaiYau** [comment]
![image](https://user-images.githubusercontent.com/28052105/26959957-0f65e7f8-4d06-11e7-9991-9ae7507757e5.png)

Here is my screenshot.
I used the original recvpackets.

**Comment by Slipxxliose** [comment]
Well, as i have time, i'll do it for you. Okay ?
Wait just 15 minutes.

**Comment by MingFaiYau** [comment]
Oh..thanks so much.
Anything i need to provide?

**Comment by Slipxxliose** [comment]
Well, i don't know if it worked.
Report with feedbacks, screenshots, if possible, of a message error or not!

**Comment by MingFaiYau** [comment]
here is the error.txt with using kRO_RagexeRE_2013_08_07a 
[errors.txt](https://github.com/OpenKore/openkore/files/1062988/errors.txt)

**Comment by Slipxxliose** [comment]
Man, read my last message again.
Forget 2013.

Use that i've told. read again. Use my fork. I've created your serverType i believe. Try again bro. try again

**Comment by sctnightcore** [comment]
server? @MingFaiYau

**Comment by MingFaiYau** [comment]
@Slipxxliose 
I can login now and won't disconnect 
thanks so much

**Comment by Slipxxliose** [comment]
You're welcome ^^

**Comment by MingFaiYau** [comment]
Thanks again..and i am going to close the post

**Comment by MingFaiYau** [comment]
[recvpackets.txt](https://github.com/OpenKore/openkore/files/1063004/recvpackets.txt)

Here is the recvpackets, i posted in http://pastebin.com/ 
server name : [mlRO]

**Comment by Slipxxliose** [comment]
Now can close ! :D

**Comment by kaotikus1** [comment]
HI, sir.. I am new to github, and also first time to use openkore.. I have read a lot of posts on github, and followed you already to keep track of whatever information I can get to learn how to make openkore work, but i sadly failed. Already did everything I possible can.. Now I really need some help.. I am trying to make the bot work on a private server, Odin-RO, which is a mid rate one.. I can provide any information you ask like my server.text, recvpackets etc.. I hope you can see this message..

thank you!

**Comment by harhail666** [comment]
![screenshot 11](https://user-images.githubusercontent.com/41236658/42733575-f1d97e9c-8865-11e8-96e5-b180df4f9557.png)

Guys, Can you also help im having the same problem this is the first time i try to use BOT please help me thanks in advance
