### ISSUE TITLE
iRO Packet Parser: Unknown switch: 0A30

### ISSUE THREAD

**Issue by ksheng91** [OpenKore/openkore#618]
Hi guys,

What could be wrong on this? And, how can I fix it? I tried to copy recvpackets.txt but it doesn't work.

![image](https://user-images.githubusercontent.com/23192163/26999045-2f5815b4-4dc3-11e7-9f57-1936678b4451.png)

Thank you.

**Comment by ksheng91** [comment]
Feel free to ask for more information, below is the recvpackets I am having for iRO.

# Generated by ROX_extractor at 2013-09-27 11:38:19
0437 7 7 0
0438 10 10 0
035F 5 5 0
0360 6 6 0
0361 5 5 0
0362 6 6 0
0363 6 6 0
0364 8 8 0
0365 8 8 0
0366 10 10 0
0367 90 90 0
0368 6 6 0
0369 6 6 0
083C 12 12 0
0838 2 2 0
0835 -1 15 0
0819 -1 12 0
0817 6 6 0
0815 2 2 0
0811 -1 89 0
0802 18 18 0
07EC 8 8 0
07E4 -1 12 0
0436 19 19 0
02C4 26 26 0
0281 4 4 0
0202 26 26 0
022D 5 5 0
023B 36 36 0
085A 2 2 0
085B 2 2 0
085C 2 2 0
085D 2 2 0
085E 2 2 0
085F 2 2 0
0860 2 2 0
0861 2 2 0
0862 2 2 0
0863 2 2 0
0864 2 2 0
0865 2 2 0
0866 2 2 0
0867 2 2 0
0868 2 2 0
0869 2 2 0
086A 2 2 0
086B 2 2 0
086C 2 2 0
086D 2 2 0
086E 2 2 0
086F 2 2 0
0870 2 2 0
0871 2 2 0
0872 2 2 0
0873 2 2 0
0874 2 2 0
0875 2 2 0
0876 2 2 0
0877 2 2 0
0878 2 2 0
0879 2 2 0
087A 2 2 0
087B 2 2 0
087C 2 2 0
087D 2 2 0
087E 2 2 0
087F 2 2 0
0880 2 2 0
0881 2 2 0
0882 2 2 0
0883 2 2 0
0917 2 2 0
0918 2 2 0
0919 2 2 0
091A 2 2 0
091B 2 2 0
091C 2 2 0
091D 2 2 0
091E 2 2 0
091F 2 2 0
0920 2 2 0
0921 2 2 0
0922 2 2 0
0923 2 2 0
0924 2 2 0
0925 2 2 0
0926 2 2 0
0927 2 2 0
0928 2 2 0
0929 2 2 0
092A 2 2 0
092B 2 2 0
092C 2 2 0
092D 2 2 0
092E 2 2 0
092F 2 2 0
0930 2 2 0
0931 2 2 0
0932 2 2 0
0933 2 2 0
0934 2 2 0
0935 2 2 0
0936 2 2 0
0937 2 2 0
0938 2 2 0
0939 2 2 0
093A 2 2 0
093B 2 2 0
093C 2 2 0
093D 2 2 0
093E 2 2 0
093F 2 2 0
0940 2 2 0
0884 2 2 0
0885 2 2 0
0886 2 2 0
0887 2 2 0
0888 2 2 0
0889 2 2 0
088A 2 2 0
088B 2 2 0
088C 2 2 0
088D 2 2 0
088E 2 2 0
088F 2 2 0
0890 2 2 0
0891 2 2 0
0892 2 2 0
0893 2 2 0
0894 2 2 0
0895 2 2 0
0896 2 2 0
0897 2 2 0
0898 2 2 0
0899 2 2 0
089A 2 2 0
089B 2 2 0
089C 2 2 0
089D 2 2 0
089E 2 2 0
089F 2 2 0
08A0 2 2 0
08A1 2 2 0
08A2 2 2 0
08A3 2 2 0
08A4 2 2 0
08A5 2 2 0
08A6 2 2 0
08A7 2 2 0
08A8 2 2 0
08A9 2 2 0
08AA 2 2 0
08AB 2 2 0
08AC 2 2 0
08AD 2 2 0
0941 2 2 0
0942 2 2 0
0943 2 2 0
0944 2 2 0
0945 2 2 0
0946 2 2 0
0947 2 2 0
0948 2 2 0
0949 2 2 0
094A 2 2 0
094B 2 2 0
094C 2 2 0
094D 2 2 0
094E 2 2 0
094F 2 2 0
0950 2 2 0
0951 2 2 0
0952 2 2 0
0953 2 2 0
0954 2 2 0
0955 2 2 0
0956 2 2 0
0957 2 2 0
0958 2 2 0
0959 2 2 0
095A 2 2 0
095B 2 2 0
095C 2 2 0
095D 2 2 0
095E 2 2 0
095F 2 2 0
0960 2 2 0
0961 2 2 0
0962 2 2 0
0963 2 2 0
0964 2 2 0
0965 2 2 0
0966 2 2 0
0967 2 2 0
0968 2 2 0
0969 2 2 0
096A 2 2 0
0187 6 6 0
0081 3 3 0
01C6 4 4 0
01C7 2 2 1
0064 55 55 0
0069 -1 47 0
006A 23 23 0
01DB 2 2 0
01DC -1 4 0
01DD 47 47 0
01FA 48 48 0
0204 18 18 0
01F1 -1 4 0
0200 26 26 0
01BE 2 2 0
01BF 3 3 0
0065 17 17 0
0066 3 3 0
0067 37 37 0
0970 31 31 0
020D -1 4 0
006B -1 4 0
006C 3 3 0
006D 147 147 0
006E 3 3 0
0071 28 28 0
0068 46 46 0
01FB 56 56 0
006F 2 2 0
0070 3 3 0
02CA 3 3 0
0072 19 19 0
0082 2 2 0
0085 5 5 0
0089 7 7 0
008C -1 4 0
007E 6 6 0
007D 2 2 0
0090 7 7 0
0099 -1 4 0
019C -1 4 0
009B 5 5 0
00CC 6 6 0
00CE 2 2 0
009F 6 6 0
00A2 6 6 0
00A7 8 8 0
00A9 6 6 0
00AB 4 4 0
00B8 7 7 0
00B9 6 6 0
00B2 3 3 0
00BA 2 2 0
00BB 5 5 0
00BF 3 3 0
00C1 2 2 0
00C5 7 7 0
00C8 -1 4 0
00C9 -1 4 0
0096 -1 28 0
00CF 27 27 0
00D0 3 3 0
00D3 2 2 0
00D5 -1 15 0
00D9 14 14 0
00DE -1 15 0
00E0 30 30 0
00E2 26 26 0
00E3 2 2 0
00E4 6 6 0
00E6 3 3 0
00E8 8 8 0
00EB 2 2 0
00ED 2 2 0
00EF 2 2 0
00F3 8 8 0
00F5 8 8 0
00F7 2 2 0
00F9 26 26 0
01E8 28 28 0
00FC 6 6 0
00FF 10 10 0
0102 6 6 0
0100 2 2 0
0103 30 30 0
0108 -1 4 0
0112 4 4 0
0113 10 10 0
0116 10 10 0
0118 2 2 0
011B 20 20 0
011D 2 2 0
0126 8 8 0
0127 8 8 0
0128 8 8 0
0129 8 8 0
012A 2 2 0
012E 2 2 0
012F -1 84 0
01B2 -1 85 0
0134 -1 8 0
0130 6 6 0
0138 3 3 0
013F 26 26 0
0140 22 22 0
0143 10 10 0
0146 6 6 0
0178 4 4 0
017A 4 4 0
017C 6 6 0
01FD 15 15 0
018A 4 4 0
018E 10 10 0
0190 90 90 0
0197 4 4 0
0198 8 8 0
01AE 4 4 0
025B 6 6 0
01AF 4 4 0
01B9 6 6 1
01CD 30 30 1
01CE 6 6 0
0443 8 8 0
01CF 28 28 1
01D0 8 8 1
01E1 8 8 1
01D1 14 14 1
01D2 10 10 1
0094 6 6 0
0095 30 30 1
0195 102 102 1
0193 6 6 0
0175 6 6 0
0176 106 106 0
0079 53 53 1
019D 6 6 0
014C -1 4 1
014D 2 2 0
014E 6 6 1
014F 6 6 0
0150 110 110 1
01B6 114 114 1
0151 6 6 0
0152 -1 12 1
0153 -1 4 0
0154 -1 4 1
0166 -1 4 1
0155 -1 4 0
0156 -1 4 1
0157 6 6 0
0159 54 54 0
015A 66 66 1
015B 54 54 0
015C 90 90 1
015D 42 42 0
015E 6 6 1
015F 42 42 1
0160 -1 4 1
0161 -1 4 0
0162 -1 6 1
0163 -1 4 1
0164 -1 4 1
0165 30 30 0
0167 3 3 1
0168 14 14 0
0169 3 3 1
016A 30 30 1
016B 10 10 0
0149 9 9 0
014A 6 6 1
014B 27 27 1
016E 186 186 0
016F 182 182 1
017E -1 4 0
017F -1 4 1
0165 30 30 0
0166 -1 4 1
0167 3 3 1
0168 14 14 0
0169 3 3 1
016A 30 30 1
016B 10 10 0
016C 43 43 1
016C 43 43 1
016D 14 14 1
01F2 20 20 1
0170 14 14 0
0171 30 30 1
0172 10 10 0
0173 3 3 1
0174 -1 4 1
0180 6 6 0
0181 3 3 1
0182 106 106 1
0183 10 10 0
0184 10 10 1
0185 34 34 1
019E 2 2 1
019F 6 6 0
01A0 3 3 1
01A1 3 3 0
01A2 37 37 1
01A3 5 5 1
01A4 11 11 1
01A5 26 26 0
01A6 -1 4 1
01A7 4 4 0
01A8 4 4 0
01A9 6 6 0
01AA 10 10 1
01CA 3 3 0
01B0 11 11 1
01B1 7 7 1
01BA 26 26 0
01BB 26 26 0
01BC 26 26 0
01BD 26 26 0
01C0 2 2 0
01C1 14 14 1
01C2 10 10 1
01D3 35 35 1
01D5 -1 8 0
01D4 6 6 1
01DF 6 6 0
01F3 10 10 1
0284 14 14 1
01FF 10 10 1
01ED 2 2 0
01E7 2 2 0
01B7 6 6 0
01F7 14 14 0
01E3 14 14 0
01CB 9 9 0
01F9 6 6 0
01E5 6 6 0
0201 -1 4 1
0203 10 10 0
0205 26 26 1
0206 11 11 1
0207 34 34 1
0208 14 14 0
0209 36 36 1
020A 10 10 1
020E 32 32 1
0212 26 26 0
0213 26 26 0
0214 42 42 1
0215 6 6 1
0216 6 6 1
0217 2 2 0
0218 2 2 0
0225 2 2 0
0219 282 282 1
021A 282 282 1
0226 282 282 1
0282 284 284 1
021B 10 10 1
021C 10 10 1
0224 10 10 1
0280 12 12 1
0285 6 6 1
0286 4 4 0
021D 6 6 0
021E 6 6 0
021F 66 66 1
0222 6 6 0
0221 -1 4 1
0220 10 10 1
0223 8 8 1
0073 11 11 1
0074 3 3 0
0075 -1 11 1
0076 9 9 1
0077 5 5 1
0078 55 55 1
007A 58 58 1
007B 60 60 1
007C 44 44 1
007F 6 6 1
0080 7 7 1
0083 2 2 1
0084 2 2 1
0086 16 16 1
0087 12 12 1
0088 10 10 1
08CD 10 10 1
008A 29 29 1
008B 23 23 1
008D -1 8 1
008E -1 4 1
0091 22 22 1
0092 28 28 1
0093 2 2 1
0097 -1 32 1
0098 3 3 1
009A -1 4 1
009C 9 9 1
009D 17 17 1
009E 17 17 1
00A0 23 23 1
00A1 6 6 1
00A3 -1 4 1
00A4 -1 4 1
00A5 -1 4 1
00A6 -1 4 1
00A8 7 7 1
00AA 9 9 1
00AC 7 7 1
00AE -1 4 1
00AF 6 6 1
00B0 8 8 1
00B1 8 8 1
00B3 3 3 0
00B4 -1 8 1
00B5 6 6 1
00B6 6 6 1
00B7 -1 8 1
00BC 6 6 1
00BD 44 44 1
00BE 5 5 1
00C0 7 7 1
00C2 6 6 1
00C3 8 8 1
00C4 6 6 1
00C6 -1 4 1
00C7 -1 4 1
00CA 3 3 1
00CB 3 3 1
00CD 3 3 1
00D1 4 4 1
00D2 4 4 1
00D4 -1 4 1
00D6 3 3 1
00D7 -1 17 1
00D8 6 6 1
00DA 3 3 1
00DB -1 8 1
00DC 28 28 1
00DD 29 29 1
00DF -1 17 1
00E1 30 30 1
00E5 26 26 1
00E7 3 3 1
00E9 19 19 1
00EA 5 5 1
00EC 3 3 1
00EE 2 2 1
00F0 3 3 1
00F1 2 2 1
00F2 6 6 1
00F4 21 21 1
00F6 8 8 1
00F8 2 2 1
00FA 3 3 1
00FB -1 28 1
00FD 27 27 1
00FE 30 30 1
0101 6 6 1
0104 79 79 1
0105 31 31 1
0106 10 10 1
0107 10 10 1
0109 -1 8 1
010A 4 4 1
010B 6 6 1
010C 6 6 1
010D 2 2 1
010E 11 11 1
010F -1 4 1
02B1 -1 8 1
02B2 -1 8 1
02B5 -1 6 1
0110 10 10 1
0111 39 39 1
0114 31 31 1
0115 35 35 1
0117 18 18 1
0119 13 13 1
0229 15 15 1
011A 15 15 1
011C 68 68 1
011E 3 3 1
011F 16 16 1
0120 6 6 1
0121 14 14 1
0122 -1 4 1
0123 -1 4 1
0124 21 21 1
0125 8 8 1
012B 2 2 1
012C 3 3 1
012D 4 4 1
0131 86 86 1
0132 6 6 1
0133 -1 8 1
0135 7 7 1
0136 -1 8 1
0137 6 6 1
0139 16 16 1
013A 4 4 1
013B 4 4 1
013C 4 4 1
013D 6 6 1
013E 24 24 1
0141 14 14 1
0142 6 6 1
0144 23 23 1
0145 19 19 1
0147 39 39 1
0148 8 8 1
0177 -1 4 1
0179 5 5 1
017B -1 4 1
017D 7 7 1
0188 8 8 1
0189 4 4 1
018B 4 4 0
018C 29 29 1
018D -1 4 1
018F 6 6 1
0191 86 86 1
0192 24 24 1
0194 30 30 1
0196 9 9 1
028A 18 18 1
0199 4 4 1
019A 14 14 1
019B 10 10 1
01AB 12 12 1
01AC 6 6 1
01AD -1 4 1
025A -1 4 1
01B3 67 67 1
01B4 12 12 1
01B5 18 18 0
01B8 3 3 1
01C3 -1 16 1
01C4 22 22 1
01C5 22 22 1
01C8 13 13 1
01C9 97 97 1
01CC 9 9 1
01D6 4 4 1
01D7 11 11 1
01D8 54 54 1
022A 58 58 1
01D9 53 53 1
022B 57 57 1
01DA 60 60 1
022C 65 65 1
01DE 33 33 1
01E0 30 30 1
01E2 34 34 1
01E4 2 2 1
01E6 26 26 1
01E9 81 81 1
01EA 6 6 1
01EB 10 10 1
01EC 26 26 1
01EE -1 4 1
01EF -1 4 1
01F0 -1 4 1
01F4 32 32 1
01F5 9 9 1
01F6 34 34 1
0253 3 3 1
0254 3 3 0
01F8 2 2 1
01FC -1 4 1
01FE 5 5 1
0227 18 18 0
0228 18 18 0
0232 9 9 0
0233 11 11 0
0234 6 6 0
0230 12 12 1
022E 71 71 1
027D 62 62 0
0235 -1 4 1
0239 11 11 1
022F 5 5 1
0231 26 26 0
0237 2 2 0
0238 282 282 1
0236 10 10 1
023A 4 4 0
023C 6 6 0
023D 6 6 0
023E 8 8 0
023F 2 2 0
0240 -1 8 1
0241 6 6 0
0242 -1 99 1
0243 6 6 0
0257 8 8 1
0244 6 6 0
0245 3 3 1
0246 4 4 0
0247 8 8 0
0248 -1 68 0
0249 3 3 1
024A 70 70 1
024B 4 4 0
024C 8 8 0
024D 12 12 0
024E 6 6 0
024F 10 10 0
0250 3 3 1
0251 34 34 0
0252 -1 12 1
0255 5 5 1
0256 5 5 1
0258 2 2 0
0259 3 3 0
025C 4 4 0
025D 6 6 1
025E 4 4 0
025F 6 6 1
0260 6 6 1
0261 11 11 0
0262 11 11 0
0263 11 11 0
0264 20 20 0
0265 20 20 0
0266 30 30 0
0267 4 4 0
0268 4 4 0
0269 4 4 0
026A 4 4 0
026B 4 4 0
026C 4 4 0
026D 4 4 0
026F 2 2 0
0270 2 2 0
0271 40 40 0
0272 44 44 0
0273 30 30 0
0274 8 8 1
0275 37 37 0
0276 -1 51 0
0277 84 84 0
0278 2 2 0
0279 2 2 0
027A -1 4 1
027B 14 14 0
027C 60 60 0
027E -1 6 0
027F 8 8 0
0283 6 6 1
0287 -1 8 1
0288 6 6 0
0289 8 8 1
0444 -1 8 1
0445 6 6 0
028B -1 4 0
028C 46 46 0
028D 34 34 0
028E 4 4 0
028F 6 6 0
0290 4 4 0
0291 4 4 1
0292 2 2 0
0293 70 70 1
0294 10 10 1
0295 -1 4 1
0296 -1 4 1
0297 -1 4 1
0298 8 8 1
0299 6 6 1
029A 27 27 1
029B 80 80 1
029C 66 66 0
029D -1 4 1
029E 11 11 1
029F 3 3 0
02A2 8 8 1
02A5 8 8 0
02A6 -1 10 0
02A7 -1 10 0
02AA 4 4 0
02AB 36 36 0
02AC 6 6 0
02AD 8 8 0
02B0 85 85 0
02B8 22 22 1
02BB 8 8 1
02B9 191 191 1
02BA 11 11 0
02BC 6 6 0
02B3 107 107 1
02B4 6 6 1
02B6 7 7 0
02B7 7 7 1
02C1 -1 12 1
02C2 -1 6 1
02C5 30 30 1
02C8 3 3 0
02C9 3 3 1
02C6 30 30 1
02C7 7 7 0
02CB 65 65 1
02CC 4 4 1
02CD 71 71 1
02CE 10 10 1
02CF 6 6 0
02D5 2 2 1
02D0 -1 4 1
02D1 -1 4 1
02D2 -1 4 1
02D3 4 4 1
02D4 29 29 1
02D6 6 6 0
02D7 -1 43 1
02D8 10 10 0
02D9 10 10 1
02DA 3 3 1
02DB -1 4 0
02DC -1 32 1
02DD 32 32 1
02DE 6 6 1
02DF 36 36 1
02E0 34 34 1
02E1 33 33 1
02E2 8 8 0
02E3 10 10 0
02E4 6 6 0
02E5 5 5 0
02E6 6 6 0
02E7 -1 6 1
02E8 -1 4 1
02E9 -1 4 1
02EA -1 4 1
02EB 13 13 1
02EC 67 67 1
02ED 59 59 1
02EE 60 60 1
02EF 8 8 1
02F0 10 10 1
02F1 2 2 0
02F2 2 2 1
035C 2 2 0
035D -1 16 0
035E 2 2 0
03DD 18 18 0
03DE 18 18 0
0439 8 8 0
043D 8 8 1
043E -1 4 1
043F 25 25 1
0440 10 10 1
0441 4 4 1
0442 -1 8 1
0443 8 8 0
0446 14 14 1
0448 -1 4 0
0449 4 4 0
044A 6 6 0
044B 2 2 0
0447 2 2 0
07D7 8 8 0
07D8 8 8 1
07D9 268 268 1
07DA 6 6 0
07DB 8 8 1
07DC 6 6 0
07DD 54 54 1
07DE 30 30 0
07DF 54 54 0
07E0 58 58 0
07E1 15 15 1
07E2 8 8 1
07E3 6 6 1
07E6 8 8 1
07E5 4 4 0
07E8 -1 4 0
07E7 32 32 0
07E9 5 5 0
07EA 2 2 0
07EB -1 8 1
07ED 10 10 1
07EE 6 6 0
07EF 8 8 1
07F0 6 6 0
07F1 18 18 1
07F2 8 8 1
07F3 6 6 1
07F4 3 3 0
07F5 6 6 0
07F6 14 14 1
07F7 -1 69 1
07F8 -1 62 1
07F9 -1 63 1
07FA 8 8 1
07FB 25 25 1
07FC 10 10 1
07FD -1 7 1
07FE 26 26 1
0800 -1 12 1
0801 -1 12 0
0803 4 4 1
0804 14 14 0
0805 -1 5 1
0806 2 2 0
0807 4 4 1
0808 14 14 0
0809 50 50 1
080A 18 18 1
080B 6 6 1
080C 2 2 0
080D 3 3 1
080E 14 14 1
080F 20 20 1
0810 3 3 1
0812 8 8 1
0813 -1 12 1
0814 86 86 1
0816 6 6 1
0818 -1 16 1
081A 4 4 1
0824 6 6 1
081B 10 10 1
081C 10 10 1
081D 22 22 1
081E 8 8 1
081F -1 9 1
0820 11 11 0
0821 2 2 0
0822 9 9 0
0823 -1 6 0
0825 -1 65 0
0826 4 4 0
0836 -1 7 0
0837 3 3 0
0839 66 66 1
083A 5 5 0
083B 2 2 0
083D 6 6 0
083E 26 26 0
0840 -1 4 0
0841 4 4 0
0827 6 6 0
0828 14 14 0
0829 12 12 0
082A 10 10 0
082B 6 6 0
082C 10 10 0
0842 6 6 0
0843 6 6 0
0844 2 2 0
0845 6 6 0
0846 4 4 0
0847 -1 6 0
0848 -1 6 0
0849 12 12 0
084A 2 2 0
084B 19 19 1
084C 10 10 0
084D 10 10 0
084E 5 5 0
084F 6 6 0
0850 7 7 0
0855 6 6 0
0851 -1 4 0
0852 2 2 0
0853 -1 4 0
0854 -1 4 0
0856 -1 71 1
0857 -1 65 1
0858 -1 64 1
0859 -1 45 1
08B1 -1 4 0
082D -1 29 0
08B2 -1 6 0
08AF 10 10 0
08B0 17 17 0
08B3 -1 8 0
08B4 2 2 0
08B5 6 6 0
08B6 3 3 0
02F3 -1 68 0
02F4 3 3 0
02F5 7 7 0
02F6 7 7 0
08B8 10 10 0
08B9 12 12 0
08BA 10 10 0
08BB 8 8 0
08BC 10 10 0
08BD 8 8 0
08BE 14 14 0
08BF 8 8 0
08C3 10 10 0
08C4 8 8 0
08C5 6 6 0
08C6 4 4 0
08C0 -1 10 0
08C1 2 2 0
08C2 2 2 0
08C7 -1 19 1
08C8 34 34 1
08C9 2 2 0
08CA -1 8 0
08CB -1 10 0
097B -1 16 0
08CC 109 109 0
08CE 2 2 0
08CF 10 10 0
08D0 9 9 1
08D1 7 7 1
08D2 10 10 1
08D3 10 10 0
08D4 8 8 0
08D5 -1 8 0
08D6 6 6 0
08D7 28 28 1
08D8 27 27 1
08D9 30 30 1
08DA 26 26 1
08DB 27 27 1
08DC 26 26 1
08DD 27 27 1
08DE 27 27 1
08DF 50 50 1
08E0 51 51 1
08E1 51 51 1
08E2 27 27 0
08E3 146 146 0
08E4 6 6 0
08FC 30 30 0
08FD 6 6 0
08FE -1 4 1
08FF 24 24 1
0900 -1 4 1
0901 -1 4 1
0902 -1 4 1
0903 -1 4 1
0904 -1 4 1
0905 -1 4 1
0906 -1 45 1
0907 5 5 0
0908 5 5 1
090A 26 26 1
090D -1 10 1
090E 2 2 0
0910 10 10 1
0911 30 30 1
0912 10 10 1
0913 30 30 1
0914 -1 80 1
090F -1 73 1
0915 -1 74 1
0916 26 26 1
096B 4 4 1
096C 6 6 1
096D -1 4 1
096E -1 4 1
096F 7 7 1
0971 6 6 1
0972 -1 9 1
0973 7 7 1
0974 2 2 1
0975 -1 28 1
0976 -1 28 1
0977 14 14 1
0978 6 6 0
0979 50 50 0
097A -1 8 1
097C 4 4 0
097D 288 288 1
097E 12 12 1
097F -1 8 1
0980 7 7 1
0981 -1 12 0
0982 7 7 0
0983 29 29 1
0984 28 28 1
0985 -1 4 1
0986 10 10 0
0987 -1 41 0
0988 6 6 0
0989 2 2 0
098A -1 74 0
098D -1 4 0
098E -1 28 0
098B 2 2 0
098C 4 4 0
098F -1 8 0
0990 31 31 1
0991 -1 4 1
0992 -1 4 1
0993 -1 4 1
0994 -1 4 1
0995 -1 28 1
0996 -1 28 1
0997 -1 45 1
0998 8 8 1
0999 11 11 1
099A 9 9 1
099B 8 8 1
099C 6 6 0
099D -1 4 0
099E 12 12 0
099F -1 22 1
09A0 6 6 0
09A1 2 2 0
09A2 6 6 0
09A3 -1 8 0
09A4 18 18 0
09A5 7 7 0
09AB 6 6 0
09A6 12 12 0
09A7 10 10 0
09A8 16 16 0
09A9 10 10 0
09AA 16 16 0
09AC -1 8 0
09AD 10 10 0
09AE 17 17 0
09AF 4 4 0
09B0 8 8 0
09B1 4 4 0
09B2 8 8 0
09B3 4 4 0
09B4 6 6 0
09B5 2 2 0
09B6 6 6 0
09B7 4 4 0
09B8 6 6 0
09B9 4 4 0
09BA 6 6 0
09BB 6 6 0
09BC 6 6 0
09BD 2 2 0
09BE 6 6 0
09BF 4 4 0
09C1 10 10 0
09C2 -1 4 0
09C3 8 8 0
09C4 8 8 0
09C5 1042 1042 0
09C6 -1 16 0
09C7 18 18 0
09C8 -1 13 0
09C9 -1 4 0
09CA -1 23 0
09CB 17 17 1
09DB -1 84 1
09DC -1 75 1
09DD -1 76 1
09DE -1 37 1
09DF 7 7 1
09F8 -1 8 0
09F9 143 143 0
09FA -1 4 0
0A09 45 45 0
0A0A 47 47 0
0A0B 47 47 0
0A0C 56 56 0
0A0D -1 4 0
0A0F -1 4 0
0A10 -1 4 0
0A23 -1 4 0
0A24 66 66 0
0A27 8 8 0
0A2D -1 4 0
0A30 106 106 0
0A3B -1 7 1

**Comment by ksheng91** [comment]
Hello? Anyone to help?

**Comment by alisonrag** [comment]
just download the latest version
