### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by Sixte44** [OpenKore/openkore#620]
.

**Comment by Slipxxliose** [comment]
Its so easy.
This youtube video is in PT-br.

1) Open notepad and paste this into : 
`start Ragexe.exe 1rag1 /account:../data/openkore.xml
exit`

**Comment by Sixte44** [comment]
Hi there, thanks for your anwser. I already did that, but when i want to connect with the openkore.bat, it says wrong password or login ( but its the same as the one in config.txt )

**Comment by Slipxxliose** [comment]
Well, has you disabled the secureAdminPassword, setting this value to 0 ? 
And then you can put the password to type in xKore2 inside config 'adminPassword', in example, we set to 1234.

Then i'll type my username, and type 1234 as password.

**Comment by Slipxxliose** [comment]
wt bro close this issue
