### ISSUE TITLE
BOT GRAVINDO FREE FOR ALL

### ISSUE THREAD

**Issue by gilbertdone** [OpenKore/openkore#621]
Waitress:	Well, there's egg and bacon; egg sausage and bacon; egg and spam; egg bacon and spam; egg bacon sausage and spam; spam bacon sausage and spam; spam egg spam spam bacon and spam; spam sausage spam spam bacon spam tomato and spam;
Vikings:	Spam spam spam spam...
Waitress:	...spam spam spam egg and spam; spam spam spam spam spam spam baked beans spam spam spam...
Vikings:	Spam! Lovely spam! Lovely spam!
Waitress:	...or Lobster Thermidor a Crevette with a mornay sauce served in a Provencale manner with shallots and aubergines garnished with truffle pate, brandy and with a fried egg on top and spam.
Wife:	Have you got anything without spam?
Waitress:	Well, there's spam egg sausage and spam, that's not got much spam in it.
Wife:	I don't want ANY spam!
Man:	Why can't she have egg bacon spam and sausage?
Wife:	THAT'S got spam in it!
Man:	Hasn't got as much spam in it as spam egg sausage and spam, has it?
Vikings:	Spam spam spam spam... (Crescendo through next few lines...)
Wife:	Could you do the egg bacon spam and sausage without the spam then?
Waitress:	Urgghh!
Wife:	What do you mean 'Urgghh'? I don't like spam!
Vikings:	Lovely spam! Wonderful spam!
Waitress:	Shut up!

**Comment by Newtonn123** [comment]
SCAMMER above^ beware of the owner of the number "0813 8198 3646"
Gave the money then ignores/blocks the buyer, he didn't even give the BOT.

*Do note that he will ask for in-game currency/voucher instead of telling him his bank account.

**Comment by ChrstphrR** [comment]
Now we have spammers on GitHub? 
Thanks for tipping off people Newtonn123.   But, we'll just close the issue... after  alter the original comment!

Closing "issue"
:hankey:
