### ISSUE TITLE
My Bot see monster and Player as NPC. And see NPC is nothing

### ISSUE THREAD

**Issue by phattakorn** [OpenKore/openkore#627]
[OPKwin]
ip 103.22.182.165
port 6900
version 46
master_version 7
charBlockSize 144
serverType 0
serverEncoding Thai
addTableFolders iRO
secureLogin 1
#secureLogin_type 0
#secureLogin_requestCode 
#secureLogin_account 0
pinCode 1
recvpackets recvpackets.txt

This above is my server.txt (Private Server) Please help!

**Comment by sctnightcore** [comment]
server ?

**Comment by phattakorn** [comment]
ragrenewal.com

**Comment by phattakorn** [comment]
Now, My bot can attack monster and talk with npc. 
Only one problem is cannot see inventory("Inventory Empty") and So, cannot  do autosell to NPC also.
I think because my bot cannot see any item..
Please help.

**Comment by sctnightcore** [comment]
link 
server ?

**Comment by phattakorn** [comment]
Ragrenewal.com

**Comment by the-leaf** [comment]
[GOODEV RO]
ip 103.22.182.165
port 6900
master_version 7
version 46
serverType kRO_RagexeRE_2013_03_20
secureLogin 0
secureLogin_type 0
secureLogin_account 0
secureLogin_requestCode
pauseCharServer 1
patchserver wpatch.ragnarok.in.th
patchpath /patch70
storageEncryptKey 0x0096C53C,0x0096C51C,0x0096C50C,0x0096C4FC,0x0096C4E8,0x0096C4D4,0x0096C4C0,0x00000119
serverEncoding Thai
addTableFolders GDRO
charBlockSize 144
pincode 1

**Comment by the-leaf** [comment]
http://www.mediafire.com/file/1851ta4hoqpu9xa/Super+OPK+GDV.rar

***Run wxstart.exe

**Comment by Slipxxliose** [comment]
well i recommend don't download this kore.

**Comment by sctnightcore** [comment]
[GOODEV RO]
ip 103.22.182.165
port 6900
master_version 7
version 46
serverType kRO_RagexeRE_2013_03_20
serverEncoding Thai
addTableFolders GDRO
charBlockSize 144

**Comment by Slipxxliose** [comment]
Well but i can presume that you dont know the correct timeStamp or you selected the last. 
Theres a patch in the forum.But before i post it, ill create sT missing that 4ept said its welcome.
