### ISSUE TITLE
Status active timeout issue

### ISSUE THREAD

**Issue by windhamwong** [OpenKore/openkore#63]
**Issue found in Network/Receive.pm**
`sub actor_status_active {`

The line:
`($args->{actor} = Actor::get($ID))->setStatus($status, $flag, $tick == 9999 ? undef : $tick);`

We can see that the status is set to undef when $tick == 9999. However, we see that this time tick variable can be higher than 9999, i.e. 240000 for 240s. So what makes the logic here stick with, undef when 9999?

**Comment by Henrybk** [comment]
If I remember correctly the  `$tick` being `9999` means it is a permanent effect, like sitting, cart, mount, etc, but i can't say for sure.

**Comment by windhamwong** [comment]
I see some statuses have no $tick. Are they doing the same thing?

**Comment by windhamwong** [comment]
I tried to do this way in Receive.pm
	($args->{actor} = Actor::get($ID))->setStatus($status, $flag, $tick) if ($tick != "" && $tick != 9999 && Actor::get($ID)->{name});
However the issue is still there. I am thinking that the Unknown monster has status but then destroyed and its timeout is still there and bugged.
Still need confirm

**Comment by windhamwong** [comment]
I have found a new $tick = 4294966996. No idea why but looks like this is prefixed or wrong unpack.

**Comment by Henrybk** [comment]
@windhamwong sorry for the delay haha, that timer looks like an almost full 4byte integer, maybe they changed the 9999 to that?

**Comment by AlexandreBR3N** [comment]
4294966996 is used in bRO.  But it's easy to identify since you can check by status durability.
