### ISSUE TITLE
How to run poseidon + ragnarok inside VirtualBox?

### ISSUE THREAD

**Issue by iamrichh** [OpenKore/openkore#630]
Hello, I already searched a lot, I know that's possible but I cannot make it to work.

Always when I try to run Poseidon + Ragnarok inside VirtualBox it returns me GG error 114.

If someone know how to do it, contact me please by email or by here.

Thanks for now.

**Comment by Cozzie** [comment]
This is an open source project, we do not support private support requests.

**Comment by lututui** [comment]
GameGuard doesn't run on VMs
