### ISSUE TITLE
The server has denied your connection.

### ISSUE THREAD

**Issue by scymastery** [OpenKore/openkore#631]
-

**Comment by sctnightcore** [comment]
$self->cryptKeys(402143769, 482689513, 292111604)

**Comment by scymastery** [comment]
![5123124512341231234123](https://user-images.githubusercontent.com/29628593/27443296-cd390292-579c-11e7-9830-b6cd4af595cf.png)

still the same m8

**Comment by sctnightcore** [comment]
@Slipxxliose

**Comment by scymastery** [comment]
![41231314123123](https://user-images.githubusercontent.com/29628593/27448422-f004b0de-57ae-11e7-9521-8acfae9de8f8.png)

@sctnightcore

**Comment by sctnightcore** [comment]
$self->cryptKeys(0x17F83A19, 0x1CC541E9, 0x116944F4); 

@Slipxxliose

**Comment by scymastery** [comment]
![412314124312313123](https://user-images.githubusercontent.com/29628593/27449420-8dc8084a-57b2-11e7-8dc0-260228d50378.png)
still can't bro >.<

**Comment by sctnightcore** [comment]
used PEViewer , the time date stamp is 15/09/2015. 

use kRO_RagexeRE_2015_11_04a

**Comment by scymastery** [comment]
![12415rwerqweqw](https://user-images.githubusercontent.com/29628593/27475200-7f1c234a-582e-11e7-85bb-9f52dda56ab3.png)

kRO_RagexeRE_2015_11_04a
$self->cryptKeys(402143769, 482689513, 292111604); not working
$self->cryptKeys(0x17F83A19, 0x1CC541E9, 0x116944F4); not working

**Comment by sctnightcore** [comment]
link you server? @scymastery

**Comment by sctnightcore** [comment]
Try using github.com/sctnightcore/openkore.
I do not know if it will work @scymastery  
RagexeRE_2015_09_16

**Comment by scymastery** [comment]
@sctnightcore http://nee-ro.com/

okay,i'll try it later m8

**Comment by scymastery** [comment]
works like charm, thanks m8
@sctnightcore can u teach me how to make own servertype >.<

**Comment by scymastery** [comment]
![423421312](https://user-images.githubusercontent.com/29628593/27511874-93fc80c6-5959-11e7-8bb6-e0b9487a1a61.png)
and everytime use skill , there's packet parser like this

**Comment by sctnightcore** [comment]
https://github.com/Slipxxliose/openkore 
@scymastery

**Comment by scymastery** [comment]
![5124123](https://user-images.githubusercontent.com/29628593/27515036-93cb65ac-59c4-11e7-830d-15b0f29ea9aa.png)

already try @sctnightcore  opk and @Slipxxliose opk, still have parser 09CA

**Comment by sctnightcore** [comment]
You try to hit the monsters. 

09CA = Skill around
