### ISSUE TITLE
i need bot for gepard

### ISSUE THREAD

**Issue by nitat1175** [OpenKore/openkore#632]
x0 
opk receive packet ABCD but i can't write opk send packet 1234 to gepard
if opk can send packet 1234 to gepard i think opk can connect to the sv. (but how?)

x3
i used proxifier+charles fix traffic for x3 but opk can't connect to the sv.

i tried so hard all the way i know..
please help me, tech me, give me the bot for gepard

ps. sorry i'm not good in english , thanks

**Comment by gummyruler** [comment]
...

**Comment by Slipxxliose** [comment]
It's very hard. I doubt if u will found someone!
