### ISSUE TITLE
Error Logging Into Character Server [idRO - Gravindo - Chaos]

### ISSUE THREAD

**Issue by ondraayyy** [OpenKore/openkore#634]
Hi, I am a new OpenKore User and I never had any experience about botting in this game.
I had problem logging into my character. This is the problem I am having

Checking for new portals... none found

Connecting to Account Server...
Connecting (128.241.92.162:6800)... connected
rebuilding packet here ..
rebuilding packet here ..
---------- Account Info ----------
Account ID: 187124     F4 DA 02 00
Sex:        Boy
Session ID: 17959      27 46 00 00
            0          00 00 00 00

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   CHAOS                 13796  202.93.25.70    6000
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (128.241.92.162:6800)...disconnected
Connecting to Character Server...
Selected server: CHAOS
Connecting (202.93.25.70:6000)... connected
char sex : 1fError logging into Character Server (invalid character specified)...
Disconnecting (202.93.25.70:6000)...disconnected
Connecting to Account Server...
Connecting (128.241.92.162:6800)... connected
rebuilding packet here ..
rebuilding packet here ..
---------- Account Info ----------
Account ID: 187124     F4 DA 02 00
Sex:        Boy
Session ID: 17959      27 46 00 00
            0          00 00 00 00

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   CHAOS                 13796  202.93.25.70    6000
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (128.241.92.162:6800)...disconnected
Connecting to Character Server...
Selected server: CHAOS
Connecting (202.93.25.70:6000)... connected
char sex : 1fError logging into Character Server (invalid character specified)...
Disconnecting (202.93.25.70:6000)...disconnected
Connecting to Account Server...
Connecting (128.241.92.162:6800)... connected
rebuilding packet here ..
rebuilding packet here ..
---------- Account Info ----------
Account ID: 187124     F4 DA 02 00
Sex:        Boy
Session ID: 17959      27 46 00 00
            0          00 00 00 00

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   CHAOS                 13796  202.93.25.70    6000
-----------------------------------------------------
Closing connection to Account Server
Disconnecting (128.241.92.162:6800)...disconnected
Connecting to Character Server...
Selected server: CHAOS
Connecting (202.93.25.70:6000)... connected
char sex : 1fError logging into Character Server (invalid character specified)...
Disconnecting (202.93.25.70:6000)...disconnected
Connecting to Account Server...
Connecting (128.241.92.162:6800)... connected
rebuilding packet here ..
rebuilding packet here ..

It's stuck on the logging into character server which is odd.
I'm playing on Indonesia RO server, and I've looked everywhere as to how do I overcome this issue. So I'm really hoping someone could help me fix this. I am willing to pay in Rupiah if someone could help me out here, thanks!

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by alisonrag** [comment]
lets concentrate the problem here:
references:
#595 
#589 
#587 
#579 
#575 
#564 
#563 
#529 
#519

**Comment by alisonrag** [comment]
#457

**Comment by alisonrag** [comment]
#1298
