### ISSUE TITLE
Bypass,Dual Login,BOT Ragnarok Gravindo

### ISSUE THREAD

**Issue by rhanfelta** [OpenKore/openkore#635]
be careful of scammers

**Comment by jackbrizuela** [comment]
email me. we need to talk. shyra.tan1990@gmail.com

**Comment by ToekangBacot** [comment]
Kasih video yang baru ada? kalo ada video 22 juni / sekarang. gua beli file .dll nya, tapi ksh video terbaru dulu ke gw, bukti .dll nya lancar,

**Comment by rhanfelta** [comment]
new video

https://youtu.be/FwqKvOzLlSY

**Comment by jackbrizuela** [comment]
i need a working bot on new pRO sever. then lets talk

**Comment by rhanfelta** [comment]
hey you already email me first and you dont want trade with steam wallet
code

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by jackbrizuela** [comment]
we can schedule a team viewer so i can see if that bot can run on roph,
then if it is. lets go il pay you
