### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#637]
1.attack Monster Not show damage
log
You are now attacking Monster Poporing (2)
You are now level 24
You gained a level!
You are now job level 20

2.packet parser : unknow switch :09CA

help me pls

**Comment by Slipxxliose** [comment]
09CA is about spell ? 
Well, what i have to say about attack monster ?
I've seen something about this in a server, and well it received some packet just hp_sp_changed.
But if you enable the debug to 1, or 2, in your config.txt, you can see the message of damage. I don't know why ^^

**Comment by sctnightcore** [comment]
How close ?

**Comment by Slipxxliose** [comment]
Well, i don't know too ¬¬ https://github.com/isaacs/github/issues/461 


search for close in this page. use ctrl+f, rly i don't know how to explain kkkkjjjj

**Comment by sctnightcore** [comment]
wtf LOL

**Comment by sctnightcore** [comment]
Close issue
