### ISSUE TITLE
Server has denied your connection - xileRO no gameguard

### ISSUE THREAD

**Issue by raruku06** [OpenKore/openkore#639]
Here is my server.txt
[XileRO]
ip 37.59.11.190
port 6901
private 1
master_version 18
version 20
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverType kRO_RagexeRE_2013_08_07a
Encoding Western
charBlockSize 112
addTableFolders xilero;eA;translated/kRO_english;

am i using the wrong server type ?

Much Appreciate for your help guys
thanks

**Comment by sctnightcore** [comment]
http://openkore.com/index.php/ServerType @raruku06 
http://openkore.com/index.php/Connectivity_Guide @raruku06

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com
