### ISSUE TITLE
pRO Bot issue (Packet Tokenizer or parser)

### ISSUE THREAD

**Issue by ravenrojo** [OpenKore/openkore#643]
this is what i knew about the recently  issue on this packet tokenizer or parser

![123123124124124](https://user-images.githubusercontent.com/29818279/27770297-b4eba5ee-5f6e-11e7-9b04-a93ef7e1df21.png)

(actual picture of the problem)

some ppl said its from RECVPACKET.TXT but i think it is not...

![image](https://user-images.githubusercontent.com/29818279/27770287-7302137a-5f6e-11e7-855f-bc55f0352f43.png)

credit: fclose

and some of the people in forum said that the recvpacket can ignore and just use the smallvill3 extracted packet the real problem is how the client sent and receive the packets from the server..

im currently trying my best to figure it out this issue...

**Comment by norielyo** [comment]
same with koolgithub. need feedback on this

**Comment by ravenrojo** [comment]
Try put the ragnarok files and openkore in the same location/drive
 with the winOs

**Comment by koolgithub** [comment]
they are in the same directory @ravenrojo

**Comment by d4xyjen** [comment]
@ravenrojo pa msg nmn sakin san ka makokontact need some information

**Comment by d4xyjen** [comment]
@ravenrojo gumamit ka pa ba ng winmm.dll?

**Comment by doom03** [comment]
![ragnarok error](https://user-images.githubusercontent.com/29853173/27780778-7dbd135c-5ffd-11e7-9a0c-671c945ccc82.png)

please help sir.

Generating session Admin Password...

Checking for new portals... none found


Connecting to Account Server...
Connecting (202.57.117.44:6900)... couldn't connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (error code 10060)

**Comment by robyisthename** [comment]
@doom03 

try mo baguhin ung sa config, ung xkore mo naka 0, gawin mong 1

**Comment by doom03** [comment]
@robyisthename 

ginawa ko na pre ganun parin... ganyan rin ba nging error sayo?

**Comment by weeetitit** [comment]
@ravenrojo  sir ano OS ng PC mo? malapit ka na konting tweaks nlng yan

**Comment by doom03** [comment]
@ravenrojo 

sir, win10 po

**Comment by ravenrojo** [comment]
gamit ko is WIN7 64 BIT SERVICE PACK 1... if ayaw try nyo gumamit ng VMware tapos dun kau mag restart ng mag restart haha

**Comment by ravenrojo** [comment]
@d4xyjen contact me here or email ravenrojo015@gmail.com

**Comment by plokislokis** [comment]
![ss3](https://user-images.githubusercontent.com/29620340/27810390-3cc61864-608c-11e7-84f6-bb4685b908cf.jpg)
Im stuck in this part.

**Comment by lobocop** [comment]
I think you need to login to the game first and create a pin. Then relaunch the bot

**Comment by jbersamin** [comment]
@ravenrojo  do you mind share your configs to me? I stuck at "Timed out at Account Server"

**Comment by liyahn143** [comment]
Im stuck to this help me </3
![pro](https://user-images.githubusercontent.com/29858958/27819590-8f0afe6e-60cd-11e7-8a4e-5408840e435a.png)

**Comment by WraithDead** [comment]
@liyahn143 are you really using openkore 2.0.7 ??

at least download the lattest openkore here https://github.com/OpenKore/openkore

**Comment by alvinmanaros** [comment]
Any solution for this? I already tried extracting new packets of ragexe.

![untitled](https://user-images.githubusercontent.com/9575939/27884760-fa660ce0-6207-11e7-850c-f0bb82159fb2.png)

**Comment by TinaKitty** [comment]
guys can I have a copy of your config? :3 Loki ph server..

**Comment by anaksunamun26** [comment]
I Hope someone who have more knowledge than me and in to programming would help me solve this issue..Im using difference SRC / networking for each kore..Bot are connected in game but as u can see they are not moving or attacking..Im thinking its not about the recvpackets anymore..![kore kore](https://user-images.githubusercontent.com/29833915/27946016-5c6407f6-6322-11e7-8a23-7e7a7a7144c9.png)

**Comment by weeetitit** [comment]
sir try mo using xkore0 then after mg connected silipin mo sa ragna if andun tlga chracter mo...skn kasi ng move ng try pa mg loot
![7](https://user-images.githubusercontent.com/29484809/27947174-5918b024-6327-11e7-974d-5523aa2788fb.jpg)

**Comment by jackdaniels111** [comment]
@ravenrojo Sir pa send ng server.txt mo. and ung revpacket mo. bjbenz17@gmail.com. TYI

**Comment by rakistangpup** [comment]
@ravenrojo  sir still working pa ba ung sayo?  baka pwede mo i share ung configs and setup ng openkore mo, salamat . please send me an email at rakistangpup@gmail.com . salamat.

**Comment by ravenrojo** [comment]
@weeetitit we also same progress as of now .. i think we need to reconfigure the src/network as aero012 said in the other forum... record each packet tokenizer and change it in send.pm and receive.pm as well as in recvpacket to recognize but its encrypted packet...

@anaksunamun26 can you teach me how to work in KORE 0.. im only using KORE 1 ... and i have the same problem but mine moving but not attacking nor looting..

**Comment by smartdial101** [comment]
@ravenrojo sir pashare naman server.txt mo thank you in advance sir

**Comment by smartdial101** [comment]
Mga paps pahelp naman please ayaw mag connect eh willing ako mag bayad via paypal pa email nalang smartdial@gmail.com TIA ![error](https://user-images.githubusercontent.com/30002787/27991629-4d42c390-64b0-11e7-9d73-501aafbaac13.png)

**Comment by bambiro23** [comment]
@weeetitit kita mo ba yung character na binobot mo kapag naka dual log ka?

**Comment by ymparolan** [comment]
mga boss pashare naman ng server.txt nyo yhamcuteness_2008@yahoo.com

**Comment by kaliwanagan** [comment]
Be careful sharing your personal email on public websites. It will come back and haunt you in the future.
