### ISSUE TITLE
0436 packet. tokenizer after. can't connect to map..

### ISSUE THREAD

**Issue by islarky88** [OpenKore/openkore#645]
these packets aren't on the recvpackets file. is there anyway to fix this?

![packet tokenizer](https://user-images.githubusercontent.com/29867302/27804141-e803230c-605f-11e7-8b1a-fd8f77c9b33a.JPG)

**Comment by Slipxxliose** [comment]
How surely is you about ur serverType date timestamp?

Read the connectivity guide. Anyway you need extract your recvpackets using PEEK. Use the forum

**Comment by kurbano1** [comment]
Hi @Slipxxliose 

Can you please share the forum link.

**Comment by Slipxxliose** [comment]
forums.openkore.com

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com
