### ISSUE TITLE
Re:start can't connect char slot 1

### ISSUE THREAD

**Issue by Cloudzin** [OpenKore/openkore#646]
Hello guys, im having a problem, when i try to use openkore on my char at slot 1 the bot dont read him and just closes, but when i chose from the slot 0 he just runs fine, anyone know how can i solve that?

thx.

**Comment by fahzrisoftyan** [comment]
can you give me bot please?

**Comment by sctnightcore** [comment]
charBlockSize 147

**Comment by Slipxxliose** [comment]
Not necessarily the 147. Read the wiki about charBlocksize

**Comment by sesh666** [comment]
its charBlockSize 145

**Comment by sesh666** [comment]
i tested

**Comment by Slipxxliose** [comment]
Good.  where  is the feedback? @cloudzin
