### ISSUE TITLE
Help with packet tokenizer

### ISSUE THREAD

**Issue by kmherrera25** [OpenKore/openkore#649]
![untitled](https://user-images.githubusercontent.com/29894545/27837984-4eb70c0c-611a-11e7-91de-a5d82b85a425.png)
stuck with what to do with E9B7

**Comment by sctnightcore** [comment]
server ?

**Comment by kmherrera25** [comment]
pRO it seems E9B7 have to do with with the account ID

**Comment by sctnightcore** [comment]
'0276' => ['account_server_info', 'x2 a4 a4 a4 x30 C1 x4 a*', [qw(sessionID accountID sessionID2 accountSex serverInfo)]],

**Comment by kmherrera25** [comment]
ok got rid of the tokenizer and parser error at the login page. now E9B7 shows up again when character is loaded
![asdsad](https://user-images.githubusercontent.com/29894545/27839827-02a2df46-6127-11e7-830d-96f5b191ab71.png)

**Comment by kmherrera25** [comment]
wait forgot i still dont have recvpckts for E9B7
