### ISSUE TITLE
iRO Re:Start recvpackets.txt Update

### ISSUE THREAD

**Issue by Victus** [OpenKore/openkore#668]
Hello,

I believe we need to update the recvpackets.txt file for Re:Start. I am running into the token errors and I have attempted to use the tools to extract it myself but it appears the tools are outdated and are no longer supported.

For example packet-extractor (Included with openkore) returns the error 'Search for Packet Len Map failed! when following the instructions provided via the git repo readme and wikipedia.

PEEK has outdated documentation, for example it says to "Click on Extract button and wait for it to finish" but it actually doesn't have an extract button, it does actually have Generate Recorder, Start Recorder, Restore Original and Extract Length but they all give DllGen: Packet Key Patterns not found and when you run RO with the modified client and tell it to connect to PEEK it cannot connect to localhost.

Any help would be greatly appreciated!

**Comment by Mercurial** [comment]
could it be that they have same anti bot / packet structures for pRO (new servers)?

**Comment by Victus** [comment]
Well I am not entirely sure of the pRO state but botting on Restart is working well for the most part, we are just running into packet errors on certain events. (In my situation it is when I use Hiding before my character reaches his walking destination)

**Comment by supahaka001** [comment]
where can i find/downoload hte whole config folder for ragnarok restart? thanks man

**Comment by alisonrag** [comment]
openkore now have support to Re Start
download and select the correct server
https://github.com/OpenKore/openkore/archive/master.zip
