### ISSUE TITLE
Automatic DC when talking to an NPC

### ISSUE THREAD

**Issue by FireflySkye** [OpenKore/openkore#669]
[iRO server]
The recent update makes my bot dc when it talk to the NPC. 

config.txt
npcTimeResponse 100 (set it to 1 still the same)
npcWrongStepsMethod 0

timeout.txt
ai_route_calcRoute 1
ai_route_npcTalk 100
ai_npcTalk 100

ugh..

![23](https://user-images.githubusercontent.com/19757768/28026486-2e5b079a-65d1-11e7-8c0c-234caf03af3d.png)

**Comment by Henrybk** [comment]
Are you using a profiles folder? They are not updated from github, if so please add these to your timeouts.txt

```
# These timeouts are used in npc conversation (Task::TalkNPC)
ai_npc_talk_wait_to_answer 1.5
ai_npc_talk_wait_after_close_to_cancel 0.5
ai_npc_talk_wait_after_cancel_to_destroy 0.5

```

**Comment by FireflySkye** [comment]
Didn't dc but new error
![234](https://user-images.githubusercontent.com/19757768/28031864-99da674c-65e3-11e7-8edd-d9b69d467bd7.png)

**Comment by Henrybk** [comment]
What console command are you using to talk to this npc? and which npc is it?

**Comment by FireflySkye** [comment]
move [insertmap] or when it autofollow. any NPC that can teleport. Gramps, Eden Teleporter etc.

**Comment by Henrybk** [comment]
Sorry for the inconvenience, many updates were made on openkore in the last day regarding this problem, would you please update your openkore to the last version, set `logConsole 1` and `debug 2` in `config.txt` and reproduce the error and after give me (post here) the `console.txt` generated in your `logs` folder.

This way I'll be able to take a closer look at the problem.

**Comment by ShishieYo** [comment]
up for this, wthe new update keep disconnecting us when talking to npcs.

**Comment by kaliwanagan** [comment]
```
Sorry for the inconvenience, many updates were made on openkore in the last day regarding this problem, would you please update your openkore to the last version, set logConsole 1 and debug 2 in config.txt and reproduce the error and after give me (post here) the console.txt generated in your logs folder.

This way I'll be able to take a closer look at the problem.
```
Did you do this?

**Comment by ShishieYo** [comment]
[console.txt](https://github.com/OpenKore/openkore/files/1140921/console.txt)

**Comment by angelwell1** [comment]
Hi sir.
I have same problem in lastest version. Hope you fix it, love you :x.

**Comment by ShishieYo** [comment]
I got Henrybk's TalkNPC.pm! hihi
It works now. :)
https://raw.githubusercontent.com/Henrybk/openkore/master/src/Task/TalkNPC.pm

**Comment by FireflySkye** [comment]
[console.txt](https://github.com/OpenKore/openkore/files/1141884/console.txt)

**Comment by Henrybk** [comment]
@FireflySkye How is your `autoTalkCont` set in `config.txt`? Also, your talk talk sequence seems wrong, your npc has 3 `next` interactions and you talk sequence onlt has 2.

I pointed it in this image:
https://i.gyazo.com/e428193f33973f4e39e2a2a0ad76539b.png

If your  `autoTalkCont` set in `config.txt` is set to `0` you could fix your problem by setting it to `1` or by fixing your talk sequence.

**Comment by ShishieYo** [comment]
@Henrybk While talking to kafra in payon archer village. it keeps on repeating and cancel talking. Im using yung talkNPC.pm.

**Comment by Henrybk** [comment]
@ShishieYo You seem to not have updated your `timeouts.txt`

**Comment by ShishieYo** [comment]
@Henrybk, I see.. I'll try the code you posted above.

**Comment by FireflySkye** [comment]
Here are my portals

#Eden Group
moc_para01 14 32 prontera 116 72 600 c c r0 c r0 c n
moc_para01 14 32 izlude 131 148 600 c c r0 c r1 c n
moc_para01 14 32 geffen 120 39 1200 c c r0 c r2 c n
moc_para01 14 32 payon 161 58 1200 c c r0 c r3 c n
moc_para01 14 32 morroc 156 47 1200 c c r0 c r4 c n
moc_para01 14 32 alberta 117 56 1800 c c r0 c r5 c n
moc_para01 14 32 aldebaran 168 112 2200 c c r0 c r6 c n
moc_para01 14 32 comodo 209 143 2200 c c r0 c r7 c n
moc_para01 14 32 umbala 100 154 2200 c c  r0 c r8 c n
moc_para01 14 32 juno 157 167 1800 c c r0 c r9 c n
moc_para01 14 32 einbroch 67 195 2200 c c r0 c r10 c n
moc_para01 14 32 lighthalzen 159 90 2200 c c r0 c r11 c n
moc_para01 14 32 hugel 98 150 2200 c c r0 c r12 c n
moc_para01 14 32 rachel 119 135 2200 c c r0 c r13 c n

works before... with no error.

I'm always using xKore 1, so I disable autoTalkCont to 0
Cause if I miss click an NPC I'll dc..

**Comment by FireflySkye** [comment]
here. Change my `autoTalkCont` to 1
[console.txt](https://github.com/OpenKore/openkore/files/1142028/console.txt)

**Comment by Henrybk** [comment]
In the first part of this last console you sent you did not have your autoTalkCont set to 1 when you talked to NPC Aperture#acolytewarp and in the second part you were using xKore 1.

Plase correct me if I am wrong.

We might have an issue with xKore but I have got to determine if the talk continuation is working properly, would you please set autoTalkCont to 1 and talk to NPC Aperture#acolytewarp using the same sequence you were using before?

**Comment by FireflySkye** [comment]
[console.txt](https://github.com/OpenKore/openkore/files/1143538/console.txt)

**Comment by Henrybk** [comment]
@FireflySkye You used the sequence `c c r0 c n` with only 1 response, but the npc needed 2 responses, the first one being

`#  Response
0  Yes
1  No
2  Cancel Chat`

and the second one being 
`#  Response
0  Prontera -> 600z
1  Izlude -> 600z
2  Geffen -> 1200z
3  Payon -> 1200z
4  Morroc -> 1200z
5  Alberta -> 1800z
6  Aldebaran -> 2200z
7  Comodo -> 2200z
8  Umbala -> 2200z
9  Juno -> 1800z
10 Einbroch -> 2200z
11 Lighthalzen -> 2200z
12 Hugel -> 2200z
13 Rachel -> 2200z
14 Cancel
15 Cancel Chat`

**Comment by FireflySkye** [comment]
Hmm. Sorry, I'm lost. 
my portal sequence is:
moc_para01 14 32 prontera 116 72 600 c c r0 c r0 c n

**Comment by hendra814** [comment]
Please cek my errror
[console.txt](https://github.com/OpenKore/openkore/files/1147388/console.txt)

**Comment by FireflySkye** [comment]
This is weird, I tried to teleport him to other (izlude) and it works 
portals
moc_para01 14 32 izlude 131 148 600 c c r0 c r1 c n

but for some reason prontera doesnt work
moc_para01 14 32 prontera 116 72 600 c c r0 c r0 c n

O_O. sigh

**Comment by hendra814** [comment]
Please revert back this update, it's so anoying...
when character died and back into any town it's get error when talk into kafra...

**Comment by FireflySkye** [comment]
They can't revert back. I'll just wait for the fix. For now, I disable all interaction to an NPC.

**Comment by kaliwanagan** [comment]
@FireflySkye or @hendra814 you can always checkout a particular commit version that works for you.

Once you find out which version it is, can you tell us here?

for example, one such commit version is: `d6eee2688d70a1bed9d156b4649a231db4072b34`

**Comment by hendra814** [comment]
how do i know what version i must commit to?
or i just checkout for all branch openkore and test it all.

**Comment by kaliwanagan** [comment]
@hendra814 yes, check out the master branch, do a `git log` and look at all the merge commits, and test them all.

If you find the merge commit that works, tell us here. It would be **super** useful to help us debug.

(btw, this is exactly what developers do :P it's just that we're not able to reproduce the bugs you're getting, that's why we have ask you to do it. hopefully you'd eventually be interested enough in dev work to start being able to contribute not just debugging skills, but programming skills too)

**Comment by kaliwanagan** [comment]
@hendra814 you cna just focus on the merge commits so it's easier for you to test. an example merge commit:

```
commit 8fc0c8f995ba166c42177ca4aebcf9fc12075781
Merge: 122aa3c43 8a3a1e4cd
```

It will have the word "Merge: " in the log.

**Comment by hendra814** [comment]
@kaliwanagan 
Sory i don't know what you mean, can you guide step by step to do it.

what i'm just doing is checkout from https://github.com/OpenKore/openkore.git
and pick fully recursive

But i've been tried with "Add-sub-for-AI-state-changes" and "Changes-to-plugin-loading-functions" branch and it's working to talk with kafra and doing teleport to another town without getting error

**Comment by kaliwanagan** [comment]
It's preferred that you use the command line.

First, do a `git log`
Then look for all commit logs that have the "Merge: " in them (like I pasted above)
Then do `git checkout 8fc0c8f995ba166c42177ca4aebcf9fc12075781` (replace the letters and numbers with the git commit hash that you want to checkout
Then run kore in the same folder. If you're still having problems, just checkout the next merge commit.

**Comment by FireflySkye** [comment]
Ugh. Totally lost.  @_@

**Comment by hendra814** [comment]
@kaliwanagan 
sorry not tell form the beginning
i'm use tortoise svn to update this Ok Git.

but i'm already succes found working OK to talk with NPC
it's commit 10245, here my prove
![untitled](https://user-images.githubusercontent.com/9587609/28246968-76c8e284-6a51-11e7-87b2-5e880ad2aa4f.jpg)

![untitled 2](https://user-images.githubusercontent.com/9587609/28246969-7fb4c39a-6a51-11e7-9e38-5b0d307dcab1.jpg)

**Comment by FireflySkye** [comment]
I kinda fix mine too. What I did is, 
`Show log > **Right Click** the Revision #10032 [March 14, 2017] > Revert to this revision`
then change my portals sequence from
`moc_para01 14 32 prontera 116 72 600 c c r0 c r0 c n`
to `moc_para01 14 32 prontera 116 72 600 c c c c r0 c r0 c n c`

and It works but got a lot of `Packet Tokenizer` thing.

![3456](https://user-images.githubusercontent.com/19757768/28247129-98423532-6a65-11e7-8fe7-098316f86a2e.png)

Sorry I don't know how to check the commit and merge

**Comment by FireflySkye** [comment]
OK I figure it out. I redownload a fresh openkore
**SVN Checkout** > URL of Repo: `https://github.com/OpenKore/openkore.git/trunk`
and then the portals.txt, if its a customize NPC sequence you have to put ever **talk cont** `c`

`moc_para01 14 32 prontera 116 72 600 c c r0 c r0 c n`
to `moc_para01 14 32 prontera 116 72 600 c c c c r0 c r0 c n c`

otherwise you'll get the error.

I think. it works now. finally :). Thanks for the help guys!

**Comment by kaliwanagan** [comment]
@FireflySkye @hendra814 can we confirm that the **latest** openkore works as well as using the correct talknpc sequence?

**Comment by hendra814** [comment]
@kaliwanagan 
work for teleport or changing map.
but for storage still got error, and for storage is it right to use steps  c r1 w1 c r0 w1 c

here the error
![untitled](https://user-images.githubusercontent.com/9587609/28249438-e2b06a5c-6a7f-11e7-87aa-7ac9f1e29261.jpg)

**Comment by kaliwanagan** [comment]
@Henrybk I think you might need to look at this :P

**Comment by hendra814** [comment]
@kaliwanagan 

Done and solved using lastest OK, for storage step use c r1 c r0 and npcWrongMethod 2

**Comment by Henrybk** [comment]
I will take a look at this :P

**Comment by Henrybk** [comment]
There was an issue with `autoTalkCont 1` and `w` or `a` npc steps, I'll get it fixed as soon as I can, the rest seems to be alright.
