### ISSUE TITLE
izlude to byalan iRO RESTART

### ISSUE THREAD

**Issue by ccococo** [OpenKore/openkore#674]
hi! i am playing in iRO restart and it is using the old izlude. i just downloaded the latest bot here and the problem is it is using the new izlude for its path to byalan so my bot is stuck going in and out of tool dealer or just wandering at the center of izlude. please help. ty. 

this is the coords in my portal.txt same as the coords of sailor in izlude of iRO restart.

izlude 201 181 izlu2dun 107 50 150 c r0

**Comment by ZaskarAlpha** [comment]
yes mine is stuck too. don't know how to fix the portals

**Comment by ccococo** [comment]
the sailor coords in portals.txt is correct. its just that the bot is using new izlude as a map. i replaced the izlude.fld into old izlude but it is still not working.

**Comment by Zexeta** [comment]
I also replaced with old izlude file and it still doesn't seem to be able to move through izlude without problems.

**Comment by Reynbow** [comment]
I can vouch for this. It's impossible to navigate Izlude, the bot just gets stuck. 
Even to manually click around in the map preview.

I've been trying to find a fix for this for the past couple days and I've got nothing to work.

**Comment by Zexeta** [comment]
tables\iRO\resnametable.txt

# After the Izlude Academy went in, the Izlude map changed.
#izlude.gat#izlude_a.gat#
#izlude_a.gat#izlude_a.gat#
#izlude_b.gat#izlude_a.gat#
#izlude_c.gat#izlude_a.gat#
#izlude_d.gat#izlude_a.gat#
#pvp_y_1-2.gat#izlude_a.gat#
#pvp_y_2-2.gat#izlude_a.gat#
#pvp_y_3-2.gat#izlude_a.gat#
#pvp_y_4-2.gat#izlude_a.gat#
#pvp_y_5-2.gat#izlude_a.gat#
#pvp_y_6-2.gat#izlude_a.gat#
#pvp_y_7-2.gat#izlude_a.gat#
#pvp_y_8-2.gat#izlude_a.gat#

Fixed mine fine, no need to change map files.  Just put a # in front of each line and save it.

**Comment by Reynbow** [comment]
Yeah, I tried that. Didn't work for me.

**Comment by kaliwanagan** [comment]
@Zexeta or @Reynbow do you mind sending in a PR so this can be fixed in the official repo?

**Comment by vraeleragon** [comment]
I actually googled it and saw it in openkore forum
go to tables\Old. Copy portals.txt and resnametable.txt and paste it in tables\iRO folder
I renamed the files to something else just in case something wrong. but so far it's still working.
it should work. It worked on mine. happy hunting! not sure why, but it works.
hey if someone actually knows why, please share why. Thanks!

**Comment by koynro** [comment]
In a related note, if I manually moved my character to the island and then kicked off from there and didn't die, I still needed to make the following changes in order to enter and exit the dungeon properly,

```
-iz_dun00 168 173 izlu2dun 108 83
+iz_dun00 168 170 izlu2dun 108 88
 
-izlu2dun 108 83 iz_dun00 168 173
+izlu2dun 108 83 iz_dun00 168 168
```

**Comment by alisonrag** [comment]
@Henrybk  @lututui  @allanon  can someone test this portals and make a PR?
