### ISSUE TITLE
configs for Ragnarok Re:Start

### ISSUE THREAD

**Issue by hainmcs** [OpenKore/openkore#675]
Is any1 able to post all the basic needed txts for the bot to work properly on this server?
Ive been trying to fix it myself but i still cast even leave town, was just trying to make bot farm Boas in moc fild13, just so i could test it, i just ran into errors constantly, was able to fix some of them, so if any1 already have all the basics set and could post it, that would be great
(im not asking for configs for that map i said, was just saying that i was gonna test the bot with something simple first and then change it later)
But, for example, now my bot go talk to kafra and just get stuck on the talk box, asks for me to type option, i even tested to tell it to open storage but it closes kafra and do it again...

Sorry if i was confusing with what i tried to say, i really dont know anything about programing, and basically just want files that come configured for the restart so it doesnt run on problems that often, like trying to go into a map that doesnt exist yet over and over again.

Thnaks.

**Comment by kaliwanagan** [comment]
Please stop making duplicate issues.

**Comment by hainmcs** [comment]
If its a duplicate can you link it to me?

But i think you misunderstood me, im talking about a full control folder that was modified for the restart version, because the normal one have many info that the classic version doesnt, like my char trying to reach a zone using a route that doesnt exist yet.

**Comment by kaliwanagan** [comment]
#678 
#646

And many others.

If you're asking for a config, there's http://openkore.com/index.php/Category:Config.txt and http://openkore.com/index.php/Manual

The forums has http://forums.openkore.com/viewtopic.php?f=16&t=211963&start=60

Seriously. Did you just make me your personal google?

**Comment by hainmcs** [comment]
No, i didnt make you my google, also, you once again misunderstood me.

Yes i did find the posts you linked, but thats has nothing to do with what i asked at all, thats the first thing i got actually, the server config to add to make the bot work, that wasnt what i was talking since the beginning tho.

I already read the full manual, and i actually got other manuals made by users trying to teach, guides on how to config properly.
You decide if you believe anything i say or not but i spent 5 hours trying to fix the configs so my bot would actually leave town, but he got stuck multiple ways many times, i managed to fix some but im new at this so i dont really know whats causing it even with the guides, i dont know how to locate the problem.

What i was asking for was, since theres clearly many ppl using bots already, if i could get a full control folder ready for something, lets say a hunt/farm bot, ready for restart, so i would still have to change some configs since the class of that config could be different, the map in that config, i would still have to do some changes, but at least its a working config, its easier to fix/change whats needed to be changed.

My guess on why the deafult control folder doesnt work properly is because all text files have many information about items, maps, and stuff like this that doesnt exist in the classic verion of ro yet, so the bot gets messed up on the restart server, that was my prime example of a problem i ran into, which i managed to fix with routweight, my bot was trying to reach the lockmap through a zone that doesnt exist yet, so he just kept walking in and out of the place that a portal should exist but doesnt, and would get stuck there forever, if the bot knew that map didnt exist to begin with, i wouldnt ever run into that problem.

I dont know why are you so agressive since the beginning, i had just created my account when i posted this and specified i havent messed with bots in years, not to mention you completly missed my point. Maybe you wanna call me a spoonfeed of some sort for asking for a full control folder with all files customized for restart, but i just see that as pratical... You dont have to be a dick all the time, just saying.

**Comment by alphonse9** [comment]
yeah this kaliwanagan is a dick just posting nonsense.
