### ISSUE TITLE
Indonesia Official new Server: Midgard.

### ISSUE THREAD

**Issue by ragnarok-id** [OpenKore/openkore#68]
Indonesia Official Server, idRO, has been created a new server since April 6, 2016 named Midgard. 
Other servers (include Thor, F&C, and Rebirth) has been merged with the new one.
Official news:
https://ragnarok.lytogame.com/berita/berita.asp?id=6805
http://forum.lytogame.com/showthread.php?t=97707
https://www.facebook.com/RagnarokOnlineIndonesia/photos/a.299818590044775.95372.265158683510766/1329607603732530/

**Comment by whitesmith82** [comment]
yup, i cant choose the character, help...

**Comment by winterwaltz** [comment]
Thx for member of Indonesian Forum Kaskus, they have been gave solution for this issue. I've created pull request for this issue. 
Credit for jungleboss: http://www.kaskus.co.id/show_post/57060a3456e6afae3e8b456d/7788/-

**Comment by whitesmith82** [comment]
thanks man

**Comment by itsrachelfish** [comment]
Pull request #69 has been merged, please test to confirm everything is working! :+1:

**Comment by ragnarok-id** [comment]
thx @itsrachelfish everything is OK but I forgot (missed) to ```git add tables/idRO/maps.txt```
i've recreate file tables/idRO/maps.txt using Notepad++ and encode with UTF-8 because i found issue
describes in pict below
![screenshot 134](https://cloud.githubusercontent.com/assets/13635906/14385603/8a283ddc-fdcb-11e5-9db9-61fa6cfe1f69.png)
How do you suggest, should I create new pull request?

**Comment by michaelpart** [comment]
please help me tutorial RO Clasic (Chaos) for bot. please help me master. i first try openkore. please help me. PM me intruction step. thx
