### ISSUE TITLE
last update: fatal error

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#696]
:(((((((
OpenKore version what-will-become-2.1
@ai_seq = NPC macro
Network state = 5
Network handler = Network::DirectConnection
Revision: ctime:2017_07_11
Loaded plugins:
  plugins/alertsound.pl (alertsound; description: plays sounds on certain events)
  plugins/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/busCommands.pl (busCommands; description: receive and send commands (and messages too) via BUS system)
  plugins/customCaption.pl (customCaption; description: customize OpenKore's window caption)
  plugins/killcountFix/killcountFix.pl (killcountFix; description: fixes killcount quest goals on some servers)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)
  plugins/spamblocker.pl (spamblocker; description: Spam Blocker Plugin)

Error message:
Can't locate object method "waitingForSteps" via package "Task::TalkNPC" at plugins/macro/Macro/Utilities.pm line 52.

Stack trace:
Can't locate object method "waitingForSteps" via package "Task::TalkNPC" at plugins/macro/Macro/Utilities.pm line 52.
 at src/Interface/Wx.pm line 163
	Interface::Wx::mainLoop('Interface::Wx=HASH(0x45a4994)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	return 1 if (AI::is('macro', 'deal'));
* 	return 1 if (AI::is('NPC') && $char->args->waitingForSteps);
  	return 0;

**This happens when the instruction is executed from macros.txt (do talknpc).**

**Comment by Glikadin** [comment]
timeouts.txt :
ai_npc_talk_wait_to_answer 1.5
ai_npc_talk_wait_after_close_to_cancel 0.5
ai_npc_talk_wait_after_cancel_to_destroy 0.5

**Comment by kaliwanagan** [comment]
@Glikadin if you're able to, can you join us in irc? You can use the webclient at https://webchat.freenode.net/?channels=openkore if you don't have your own IRC client.

**Comment by Glikadin** [comment]
I found a temporary solution:

.../plugins/macro/Macro/Utilities.pm                Line № 52

`#return 1 if (AI::is('NPC') && $char->args->waitingForSteps);`

**Comment by parasquid** [comment]
@Glikadin can you change `$char->args->waitingForSteps)`
to  `$char->args->{waitingForSteps})` (note the curly braces) and see if that works? (uncomment the line as well)

**Comment by kaliwanagan** [comment]
@Glikadin can you change $char->args->waitingForSteps)
to $char->args->{waitingForSteps}) (note the curly braces) and see if that works? (uncomment the line as well)

**Comment by Glikadin** [comment]
.../plugins/macro/Macro/Utilities.pm Line № 52

return 1 if (AI::is('NPC') && $char->args->{waitingForSteps});

Thx! Works correctly.

**Comment by kaliwanagan** [comment]
@Glikadin can you create a pull request for this bugfix? :P It's quite easy. Just fork openkore, clone your own fork, make the fix and then click on pull request.

Then you're officially a contributor :)

**Comment by alisonrag** [comment]
will be updated in #995
