### ISSUE TITLE
al de baran to lutie iRO restart

### ISSUE THREAD

**Issue by hainmcs** [OpenKore/openkore#697]
Hi, im trying to make bot go back to factory if i die or go back to town to sell and stuff, i already changed the santa cords, and i think i did the dialogue correctly but bot instantly goes into this:

Link Christmas: [Wind]
Link Christmas: Ho! Ho! Ho!
Link Christmas: Merry Christmas!!
Link Christmas: I wish everybody happiness!
------  (Link Christmas) ------
# Response
0  Inquire about Lutie.
1  Move to Lutie.
2  Cancel.
----------------------------------------
We have waited for too long after we sent a response to the npc.

I tried to look how to put a longer timeout for an specific case like this but didnt really find anything related, my thought was that the convo was happening too fast and because of delay bot just gives up

heres the portals.txt part ive got
aldebaran 168 168 xmas_fild01 78 68 0 c r1 c c c

**Comment by Henrybk** [comment]
Please add these values to your timeouts.txt if they are not yet there.

```
# These timeouts are used in npc conversation (Task::TalkNPC)
ai_npc_talk_wait_to_answer 1.5
ai_npc_talk_wait_after_close_to_cancel 0.5
ai_npc_talk_wait_after_cancel_to_destroy 0.5

```
