### ISSUE TITLE
iRO Re:Start Tool Dealer at Morocc

### ISSUE THREAD

**Issue by r421** [OpenKore/openkore#698]
Anyone having issue to sell item at Morocc near Kafra Employee? My bot confusing when set sellauto Morocc 147 102

**Comment by Zexeta** [comment]
Yes it kept pacing back and fourth, i had to set a stand position behind the tent and pray no ones standing in that position when it goes to sell.

**Comment by r421** [comment]
Ok noted.

Thanks
