### ISSUE TITLE
hi po pede po pa help ?  bka po my makaka2long ?

### ISSUE THREAD

**Issue by kenneth543** [OpenKore/openkore#699]
![desktop](https://user-images.githubusercontent.com/29980317/28246309-aa024062-6a49-11e7-9e87-2ab984b34854.png)

**Comment by ShaneAbara** [comment]
Sir baka pwede magpaturo ng config and server files tsaka nung NetRedirect.dll

**Comment by kenneth543** [comment]
up

**Comment by ShaneAbara** [comment]
Sir baka pwede mo mashare yung openkore folder mo? Repo mo sa github mo

**Comment by kenneth543** [comment]
any one can help me pleasE?
