### ISSUE TITLE
Remove links to SVN

### ISSUE THREAD

**Issue by itsrachelfish** [OpenKore/openkore#7]
All of the links to the project on SVN should be updated to point to GitHub instead.

Not a code issue, but making this issue here on GitHub anyway for project management / transparency reasons. If anyone wants to take initiative and update things feel free! Otherwise I'll take care of it tomorrow.

- [x] Wiki home page
- [x] Forum "links" section
- [x] IRC topic
- [x] Wiki SVN page
- [x] Other major wiki pages
- [x] SourceForge project page

**Comment by lututui** [comment]
Moved the **SVN** page to **[SVN (deprecated)](https://http://openkore.com/index.php/SVN_(deprecated))**
What should be done about the download links on some of the plugin pages, once they are all downloaded by default?

**Comment by itsrachelfish** [comment]
@lututui Thanks! I think the plugin links should be updated to point to the main "[plugins](https://github.com/OpenKore/openkore/tree/master/plugins)" folder for now, until more plugins are reviewed. It's not the most elegant solution, but it means we won't have to update all of the plugin links again when the files are inevitably moved around.

**Comment by parasquid** [comment]
I wonder if we should instead just move the wiki from the self-hosted version to Github?

That way we have a one-stop-shop for everything OpenKore related.

BTW :+1: for the move! I'm loving it :)

**Comment by itsrachelfish** [comment]
@parasquid I don't like the idea of putting all of our eggs into the GitHub basket. The current wiki has a lot of information on it and the templating / categorization options provided by MediaWiki are better than what's provided by Gollum.

I also really prefer the URL structure of hosting our own documentation, compare these two links:

http://openkore.com/AttackAuto
https://github.com/openkore/openkore/wiki/AttackAuto

By the way, @parasquid did you go by a different name on SourceForge / the forums?

**Comment by parasquid** [comment]
Ah, sounds like you know what you're doing :) I just thought that with all the server movements for the past few years, maybe it's time to place the content to a third party that's more likely to continue hosting the content for the foreseeable future.

I do go by a different name in sf and the forums, yes :) (there's a reason, and it's a secret :tongue: )

**Comment by itsrachelfish** [comment]
I did a search on the wiki for "SVN" and updated almost all of the pages that @lututui hadn't got to yet. Fortunately there are only 21 results. I'm calling this closed now.
