### ISSUE TITLE
ro re:start

### ISSUE THREAD

**Issue by restartowi** [OpenKore/openkore#700]
Am i doing something wrong here?

![22](https://user-images.githubusercontent.com/30212341/28247582-115cecb8-6a2b-11e7-9170-e877ef94918a.jpg)
 I know it's a bit small, hope you got good eyes

**Comment by r421** [comment]
try change to charblocksize 145 to your tables/servers.txt

#Re:Start
# http://playragnarok.com
[International - iRO: Re:Start]
ip 128.241.92.134
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 145
patchserver ropatch1.gravityus.com
patchpath /repatch

**Comment by kenneth543** [comment]
hai r421 sir can u help me in my post ?

**Comment by sctnightcore** [comment]
download new openkore on github <3

**Comment by alphonse9** [comment]
can u guys still bot on this RO?

**Comment by r421** [comment]
Yup

**Comment by tykez28** [comment]
![image](https://user-images.githubusercontent.com/29828183/29483538-31cbd264-84db-11e7-85d5-bc4087fc944f.png)

can you help me with this error after the patch
