### ISSUE TITLE
A warning appears when the title of the achievement system becomes more variable

### ISSUE THREAD

**Issue by kou90258** [OpenKore/openkore#701]
A warning appears when the title of the achievement system becomes more variable.

================================================
Jul 16 22:56:40 2017
Sent by RO client:    0A2E [ 6 bytes]
Recv 0A2E [6 bytes]

  0>  2E 0A E8 03 00 00                                     ......

================================================
Jul 16 22:56:40 2017
<< Received packet:      0A2F [ 7 bytes]
Recv 0A2F [7 bytes]

  0>  2F 0A 00 E8 03 00 00                                  .......

[Jul 16 23:01:40 2017.46] Packet Parser: Unknown switch: 0A2E
[Jul 16 23:01:40 2017.47] << Sent by RO client:    0A2E [ 6 bytes]
[Jul 16 23:01:40 2017.47] ================================================
<< Sent by RO client:    0A2E [6 bytes]   Jul 16 23:01:40 2017
  0>  2E 0A E8 03 00 00                                     ......
[Jul 16 23:01:40 2017.47] Packet Parser: Unknown switch: 0A2E
[Jul 16 23:01:40 2017.47] [encryptMessageID] Encrypted MID: [0A2E]->[1874] / KEY: [0x2603]->[0x125A]
[Jul 16 23:01:40 2017.47] Sent packet    : 0A2E    [ 6 bytes]  
[Jul 16 23:01:40 2017.53] << Received packet:      0A2F [ 7 bytes]
[Jul 16 23:01:40 2017.53] ================================================
<< Received packet:      0A2F [7 bytes]   Jul 16 23:01:40 2017
  0>  2F 0A 00 E8 03 00 00                                  /......
[Jul 16 23:01:40 2017.53] Packet Parser: Unknown switch: 0A2F

[Jul 16 23:01:46 2017.59] Packet Parser: Unknown switch: 0A2E
[Jul 16 23:01:46 2017.59] << Sent by RO client:    0A2E [ 6 bytes]
[Jul 16 23:01:46 2017.59] ================================================
<< Sent by RO client:    0A2E [6 bytes]   Jul 16 23:01:46 2017
  0>  2E 0A EB 03 00 00                                     ......
[Jul 16 23:01:46 2017.60] Packet Parser: Unknown switch: 0A2E
[Jul 16 23:01:46 2017.60] [encryptMessageID] Encrypted MID: [0A2E]->[2DFA] / KEY: [0x4ED6]->[0x27D4]
[Jul 16 23:01:46 2017.60] Sent packet    : 0A2E    [ 6 bytes]  
[Jul 16 23:01:46 2017.65] << Received packet:      0A2F [ 7 bytes]
[Jul 16 23:01:46 2017.65] ================================================
<< Received packet:      0A2F [7 bytes]   Jul 16 23:01:46 2017
  0>  2F 0A 00 EB 03 00 00                                  /......
[Jul 16 23:01:46 2017.65] Packet Parser: Unknown switch: 0A2F

**Comment by Henrybk** [comment]
Would you please explain with detail in which situation this happens? I can implement the packets in openkore if you help me with this information.

**Comment by kou90258** [comment]
The details of the use of xkore 2 + RO client running openkore, open the equipment column title with the mouse click the title, an unknown packet. Pictures and details are as follows.
![1](https://user-images.githubusercontent.com/25382808/28365361-de88449e-6cba-11e7-8c2c-a9b905d5d777.png)
![2](https://user-images.githubusercontent.com/25382808/28365369-e1dbfa28-6cba-11e7-804d-c3bdc3bc557f.png)
![3](https://user-images.githubusercontent.com/25382808/28365371-e3c9592a-6cba-11e7-9c28-369c212ce22d.png)

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com
