### ISSUE TITLE
How to talk to NPC when below HP?

### ISSUE THREAD

**Issue by Reynbow** [OpenKore/openkore#708]
When leveling a novice in the training grounds, I want the bot to talk to Brade, who's at 96,30 on all the novice maps.

I've tried adding this:

```
doCommand talknpc 96 30 c {
	hp < 25%
}
```

But if I'm not already near the NPC when I'm below 25% HP then it just says it can't find the NPC.
So I tried adding this:
```
doCommand move 90 30 {
	hp < 25%
}
```
But all that does is SPAM the console log with "attempting to move" and basically locks up the program. The character never moves.

Any help would be appreciated.

**Comment by Henrybk** [comment]
I could write an eventMacro for you that does that, but on macro plugin / doCommand that would prove very hard to do.

**Comment by Reynbow** [comment]
Anything you could do to help would be amazing. I keep having to look over and manually tell it to talk to the NPC :(

**Comment by koynro** [comment]
I am currently working on a macro to go through the entire zone and do all of the quests. 
This isn't 100% tested but something like this should do it

```automacro death_locker_novice_zone {
  location new_1-3
  hook in_game
  call {
    lock respawned_novice_zone
  }
}

automacro respawned_novice_zone {
  location new_1-3
  hook Network::Receive::map_changed
  run-once 1
  call {
    pause @rand(1,2)
    do talknpc 96 30
    pause @rand(1,2)
  }
}

automacro died_novice_zone {
  location new_1-3
  hook self_died
  call {
    release respawned_novice_zone
  }
}```

**Comment by Reynbow** [comment]
How do I use these Macros?

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by alisonrag** [comment]
Solved the problem using macro
