### ISSUE TITLE
Inside CDClient.DLL & Ragexe

### ISSUE THREAD

**Issue by ZeusXavier** [OpenKore/openkore#709]
Greetings!

Been following all the threads relating to the development of a relaunched openkore for roPH and it was a h3ll lot of work just to get into the map route problem. Which fortunately I was able to achieve without bugging you guys. If I understand everything correctly, the problem now is to have the character move around from map 1 to map 2 and etc. 

I have been trying to come up with a script something like what I saw with K1ngJ's video wherein he was also running a separate process to do the decryption of packets in realtime. However due to weeks of back reading and mixing everything around was not able to do so and totally drained my head. 

I am not really sure if this would help veteran devs in coming up with a hexed or unpacked exe file or maybe work something around cheatdefender but I am sharing this to everyone anyways. It's been years since I switched from programming to business management so please take it easy on me okies? :)

![cdclient](https://user-images.githubusercontent.com/30259158/28312413-9c30882a-6be5-11e7-8b37-54a39fb072d9.jpg)
![ragexe](https://user-images.githubusercontent.com/30259158/28312412-9c308a5a-6be5-11e7-8cec-ab4da0b5d7d2.jpg)

**Comment by windhamwong** [comment]
We might be interested in the CDClient.dll, but ultimately we don't want to do disassembling any file. Can you upload both of the files in somewhere, please?

**Comment by m01ses** [comment]
I guess you're in the right track trying to edit cdclient.dll. goodluck sir you can make it

**Comment by ZeusXavier** [comment]
@windhamwong These are coming from the game itself sir. If you have roPH installed you should have them too. But if not I wouldn't mind uploading them for those who wants to take a look but doesn't have roPH installed.

@m01ses Not sure what to really do next since my next target is creating or getting that realtime parser thing so I can start moving. Stuck with the character move part, although I have some ideas on how to go around the encryption part but not sure. I just woke up after 24 hours of reading everything in this forum. :( if someone can help me out that would really be great.

**Comment by m01ses** [comment]
Well im guesing with those packet tokenizer,  the code before coming from the ragexe.exe but now they change it, so i was thinking they change the cdclient.dll. if u can find other extractor of cdclient.dll maybe you can read it easily.

**Comment by ZeusXavier** [comment]
@m01ses actually everything we need is already inside openkore. Either they are no longer working or they just need to be recoded. But base on the codes I have reviewed it seems it just needs to be recoded to match with the new encryption and so on. The problem I have is that it makes my head spin working on assembly language. I can work my way but it would be better to have someone better do the coding. I'm just waiting for devs to provide me instructions on what I need to work on if they need anything that would help them with the new openkore for roPH

**Comment by jickoy** [comment]
nice..
