### ISSUE TITLE
035f Error help.

### ISSUE THREAD

**Issue by UnidentifiedPlayer** [OpenKore/openkore#710]
I already in without error in recvpacket however my character don't move. can you please give me an idea regarding to this 035f
![help1](https://user-images.githubusercontent.com/30266691/28325879-a4552f7a-6c11-11e7-8075-5f147d1624fa.jpg)

**Comment by moneyisgod** [comment]
What server is you playing ?!

**Comment by UnidentifiedPlayer** [comment]
@moneyisgod ragna ph

**Comment by ZeusXavier** [comment]
I had the same problem. But from the looks of it your bot is not displaying the exp and other information needed. Try opening your equips using openkore and it would say it has nothing. Therefore it's not logged in correctly that is why it's not able to calculate the route.

**Comment by m01ses** [comment]
Can you attach the recvpacket.txt?
