### ISSUE TITLE
RO Re:start Looting Issue

### ISSUE THREAD

**Issue by trustmejeb** [OpenKore/openkore#717]
Hello, I'm having a problem with looting on Re:start server. The bot refuses to loot anything no matter the config I use. I also tried manually picking up without success.

![image](https://user-images.githubusercontent.com/30283414/28353382-e5ac006e-6c31-11e7-91c8-b092c6a2188a.png)

![image](https://user-images.githubusercontent.com/30283414/28353410-0807ca1c-6c32-11e7-8e75-9b15834d737e.png)

config
itemsTakeAuto 2 
itemsTakeAuto_party 1
itemsGatherAuto 2
itemsMaxWeight 89
itemsMaxWeight_sellOrStore 48
itemsMaxNum_sellOrStore 99
cartMaxWeight 7900
itemsTakeAuto_new 1  - Tried 0 and 1
itemsTakeGreed 0

pickupitems
all 2 - tried 1

**Comment by kaliwanagan** [comment]
see #714
