### ISSUE TITLE
wxstart.exe crashes when i use xKore 1 on RO:restart, it just says "not responding"

### ISSUE THREAD

**Issue by koburaaa** [OpenKore/openkore#718]

**Comment by koburaaa** [comment]
XKore 0
XKore_port 6400
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName Ragexe.exe

and heres the server

#Re:Start
# http://playragnarok.com
[International - iRO: Re:Start]
ip 128.241.92.134
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 147
patchserver ropatch1.gravityus.com
patchpath /repatch


anything wrong i put it? i run them both on admin also btw.

**Comment by sctnightcore** [comment]
you can use x0 and x3 @koburaaa

**Comment by brylle0714** [comment]
guys how to use half bot?

**Comment by sctnightcore** [comment]
xkore 2 ? @brylle0714

**Comment by koburaaa** [comment]
I got this fix guys thank you. And found another one when i do multiple bot the other one stop responding how do you fix that

**Comment by brylle0714** [comment]
@sctnightcore  is that half bot then yes can u give me tut im using windows 10 64bit thnx

**Comment by sctnightcore** [comment]
idk for fix it HAHA

**Comment by kaliwanagan** [comment]
Let's not make this into a discussion.

**Comment by icewafu05** [comment]
@koburaaa  hi! can u teach me how u did it? please.. thank you!
