### ISSUE TITLE
Bot can't log in any more?

### ISSUE THREAD

**Issue by Reynbow** [OpenKore/openkore#721]
Getting this error since the latest update:

http://i.imgur.com/Yh4ZOZa.png

**Comment by sctnightcore** [comment]
#722

**Comment by sctnightcore** [comment]
#722

**Comment by Reynbow** [comment]
Ahhhh easy. Thanks!

**Comment by Xianmanuel2017** [comment]
so whats the new ip?

**Comment by koynro** [comment]
128.241.92.133 to 128.241.92.134 in tables/servers.txt

**Comment by beebeebee01** [comment]
guys. i need help. i did changed the ip from 134 to 133.
but when i open the wxstart, the software still use the 134 ip
what should i do ?
