### ISSUE TITLE
Ragnarok Re:start Moroc, and izlude problem. 

### ISSUE THREAD

**Issue by emanzx** [OpenKore/openkore#726]
I have problem with routing as map for Ragnarok Restart actually revert back to old midgard where the satan moroc is still not revived. and morroc field is still available.. so what happen now is.. your bot wont able to calculate route if you enter a map which is not available after the old raganarok.. 
Ok that is all the problem.. now I have a dirty solution for it. 

How?
in tables folder, there is old folder referring to old ragnarok info. So what you need to do is just to copy these few file from that folder to the iRO folder and paste it replace all file. 
Here are the file you should copy. 
maps
portals
portalsLOS
resnametable

That all I think that should be copied.. and this is dirty way of doing it. So this issues is to create awareness for the dev and helps all other botter comrades to fix this annoying problem.

**Comment by sctnightcore** [comment]
#729 portal moc_fild

**Comment by koynro** [comment]
Thanks for the update @sctnightcore

**Comment by koynro** [comment]
#674 already discussing the Izlude side of this. This issue can be closed @emanzx
