### ISSUE TITLE
Re:Start RO bot keeps auto-storaging when the bot is started/reconnecting

### ISSUE THREAD

**Issue by ZaskarAlpha** [OpenKore/openkore#728]
Here it is, I posted the issue in the forums but idk, maybe i'm the only one who is experiencing this but the bot cannot detect that he has the correct amount of Concentration Potion and Red Potion in the inventory. I mean when I close to bot and run start.exe again, he does autostorage bec. he thinks he has insufficient amount of potions but in fact it is not. I think its a problem with the items.txt or descriptions?

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by ZaskarAlpha** [comment]
so i figured it out. the timeouts.txt was loading the ai much faster than the inventory that's why it keeps going on the loop.
