### ISSUE TITLE
Taiwanese files in the master branch

### ISSUE THREAD

**Issue by itsrachelfish** [OpenKore/openkore#73]
Hi @windhamwong just wanted to let you know that you committed Taiwanese translated files to the master branch yesterday. https://github.com/OpenKore/openkore/commit/05f6a377d13a4bae54eeb084ade35fa5d63d775e

Now when anyone downloads the packaged openkore zip the files are no longer in english.

I am going to revert these changes, and please be more careful next time.

**Comment by windhamwong** [comment]
I just saw the revert. I thought master is locked but it is still my mistake that committing to the wrong branch. Sorry about that.
