### ISSUE TITLE
Process Improvement Request: Issue Template

### ISSUE THREAD

**Issue by koynro** [OpenKore/openkore#731]
I have been watching this repo over the past couple days as I get into ReStart and try to grind up a bit with OpenKore and a lot of people seem to be using these github issues as their personal help forum. I'm not sure how this community feels about that in general, but I think having a template with some requirements for issues formats, titles, and tags would help clean things up and streamline the solution process.

I'd like to see titles include the specific RO version if applicable, and a template to help users determine the type of issues they are having with a problem statement, debug info or other useful details to repeat the issue, etc.

Thoughts?

**Comment by kaliwanagan** [comment]
Sounds great.

I think the only problem here is enforcement.

**Comment by koynro** [comment]
Having a default template when a uswe hits new issue and noting 'if you do not follow this format your issue will be closed, use these other resources for questions, etc may help at least! 

Also thanks for tagging discussion, I probably should have done that given the nature of my request 😅

**Comment by sctnightcore** [comment]
nice ♥

**Comment by daniellorelyn** [comment]
can i have e ready to use bot?? i play in thor.. thank you..

**Comment by smallvill3** [comment]
We seriously need a police enforcement todo the cleanup.
Things getting so much mess since the pRO relaunch.

**Comment by kaliwanagan** [comment]
How do you propose we do this?

Unfortunately we also would want to get legitimate issues created by users. On the other hand, we don't want stupid idiots and the unwashed masses to spam the issue tracker.

**Comment by kaliwanagan** [comment]
I've found a way to block recently created accounts from creating new issues, but that requires someone to keep checking the limited access box once a day.

There's also the option of limiting access to those that have at least one commit in the repository, but that would also exclude people who have never contributed back through pull requests (and instead just post the diff files).

**Comment by koynro** [comment]
I'll try to throw together a template for issues being submit. Hopefully at least one layer of defense, and maybe organization/consistency improvements. If it still seems necessary blocking new users from making issues may be the next best bet. 
(I, for example, haven't contributed yet. I do intend to!)

**Comment by Cozzie** [comment]
The best method is to make the software easier to use, UX improvements reduce user errors and consequently support requests. Some of the issues should have self fixing components built in. I am going to open up a new discussion on how we can help on that.

**Comment by koynro** [comment]
Action Items:

- Update the 'Post in English' to be more polite / less controversial 
- Add link/docs on how to get the 'latest release'
- I realized that this is formatted all pretty in Markdown, but the 'New Issue' window is all raw formatting so it should probably be refactored with that in mind

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by Aiyaful** [comment]
I don't want to create another topic so I will post this here since this is same "improvement" but not process or request issue. I have a little knowledge in (not little but super tiny) coding so I don't know how to create this one. Can anyone create a check update(new update download on github) or autoupdate openkore so that a newbie will not always put an issue file or some people (annoying people) ask for a working bot. I always read issues and like to read issues and it's really annoying to find people asking for bots and not have patience to wait.
