### ISSUE TITLE
Kafra Storage VIP

### ISSUE THREAD

**Issue by Utpoia** [OpenKore/openkore#732]
Having problem with kafra storage just stuck in conversation after new VIP storage patch. Getting stuck in the normal or vip storage option. Thanks!

**Comment by ZaskarAlpha** [comment]
change NPC type 3

**Comment by lututui** [comment]
Not a bug, please properly set up [storageAuto_npc_type](http://openkore.com/index.php/StorageAuto_npc_type) and [storageAuto_npc_steps](http://openkore.com/index.php/StorageAuto_npc_steps) in your config.txt
