### ISSUE TITLE
RE:Start Server has denied your connection.

### ISSUE THREAD

**Issue by xdopie** [OpenKore/openkore#734]
Hello, I've been using xKore3 for a few days now and it was working completely fine until this morning when it said Server has denied your connection. Any help would be nicce

Here are my config:

# Please Read the Users Manual
# The Manual is located at http://wiki.openkore.com/index.php?title=Manual

######## Login options and server-specific options ########

master International - iRO: Re:Start
server 0
username xdopie
password 
loginPinCode
char 1

# Poseidon Settings (http://wiki.openkore.com/index.php/PoseidonServer)
# They must be the same as Query Server config in Poseidon.txt
poseidonServer 127.0.0.1
poseidonPort 24390

bindIp
forceMapIP

# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore
XKore 3
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe

# XKore 3 / Proxy configuration
XKore_listenIp 127.0.0.1
XKore_listenPort 6901
XKore_publicIp 127.0.0.1
XKore_ID

![openkore](https://user-images.githubusercontent.com/30277948/28446045-178db216-6d7d-11e7-80bc-fca7705972a4.png)

**Comment by sctnightcore** [comment]
download new openkore on github

**Comment by JohnCena2017** [comment]
Nothing happened to your account. You get this message sometimes when the login server is down.

**Comment by ZaskarAlpha** [comment]
its just the server being down. when you are banned, the message 
"the server is blocking your connection for dd/mm/yy" message comes up.
