### ISSUE TITLE
what do i need to use as server?? i cant search ragnarok online phillipine server  thor  or  LOKI

### ISSUE THREAD

**Issue by daniellorelyn** [OpenKore/openkore#736]

**Comment by daniellorelyn** [comment]
i mean i need master server..

**Comment by brylle0714** [comment]
@daniellorelyn  just put this on you server.txt

#[Philippines - pRO (EXE): Thor/Loki]
ip 116.93.119.116
port 6900
master_version 15
version 24
serverType pRO
secureLogin 0
secureLogin_type 0
secureLogin_requestCode
secureLogin_account 0
serverEncoding Western
gameGuard 0
storageEncryptKey 0x050B6F79, 0x0202C179, 0x0E20120, 0x04FA43E3, 0x0179B6C8, 0x05973DF2, 0x07D8D6B, 0x08CB9ED9
addTableFolders pRO
charBlockSize 144
pinCode 1

**Comment by daniellorelyn** [comment]
is it tables>> svn >> server.txt folder??

**Comment by daniellorelyn** [comment]
is it tables>> svn >> tmp >> server.txt folder??

**Comment by kaixe10** [comment]
pano to wala ng resive packet folder?

**Comment by kaixe10** [comment]
send me a bot na pwd sa PH TY kaixer1000@gmail.com

**Comment by daniellorelyn** [comment]
Should i delete the context of server.txt then paste that?? Im just renting computer.. So i need to setup a bot that works..

**Comment by kaixe10** [comment]
the IP add of the Loki and Thor did not work
