### ISSUE TITLE
Bot keeps dying to the zealotus hat npc while farming.

### ISSUE THREAD

**Issue by Dalamar6** [OpenKore/openkore#740]
I'm not sure why it's talking to it in the first place.
gl_prison1 137 138 Zealotus#hat

this shows up, it gets stuck and dies every time, conversation popup still there after loading the client

Zealotus#hat: [Zealotus]
Zealotus#hat: Resist, and you shall be
Zealotus#hat: punished! Grovel and kiss
Zealotus#hat: my feet, and perhaps you
Zealotus#hat: might be spared. Hohohohoho!
NPC Zealotus#hat (0): Type 'talk cont' to continue talking
------- Responses (Zealotus#hat) -------
#  Response
0  Oh, your highness!
1  Whatever.
2  Cancel Chat
----------------------------------------

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by kaliwanagan** [comment]
Would be really nice to know which server this is.

**Comment by Dalamar6** [comment]
Being the only bot on the map and lucky enough to get so high level, I'd prefer not to draw that kind of attention. How can I private message you? It's an official server.

I tested and it seems that just getting close to the npc makes it talk.

Currently using this as a macro, havent paid enough attention to know if its working.
automacro fix_zealotus {
console /your highness/
timeout 1
call fixzealotus
}

macro fixzealotus {
pause 1
do talk resp 2
do reload macros
release all
}

**Comment by kaliwanagan** [comment]
Yeah it seems the case. I think there's an old issue somewhere where kore gets confused when the server initiates conversation.

For now what you can do is to edit the fld file so kore will not route anywhere close to that npc.

**Comment by kaliwanagan** [comment]
see #38

**Comment by alisonrag** [comment]
continue in #38
