### ISSUE TITLE
Unable to setup shop

### ISSUE THREAD

**Issue by FireflySkye** [OpenKore/openkore#743]
![image](https://user-images.githubusercontent.com/19757768/28524707-76856208-7036-11e7-9d07-6dd481292c50.png)

I checked SVN update today and got some updates related to items.
Then run my vendor and its been hours and still not able to setup the shop. O_O

![image](https://user-images.githubusercontent.com/19757768/28525002-993168fa-7037-11e7-9819-0071057045ed.png)
Revision 10375 and 10376 works fine. Stop working properly at July 23.

=========
Good thing I haven't update my other bot folder >.<

**Comment by Henrybk** [comment]
I will take a look at this.

**Comment by Henrybk** [comment]
@FireflySkye Would you please try #745 to see if it works?

**Comment by FireflySkye** [comment]
Nope. Still not working.

======================
Other issue (not related to items/vending).

OpenKore version what-will-become-2.1
@ai_seq = look route follow
Network state = 5
Network handler = Network::XKore
Revision: ctime:2017_07_16
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)
  plugins/raiseSkill/raiseSkill.pl (raiseSkill; description: automatically raise character skills)
  plugins/raiseStat/raiseStat.pl (raiseStat; description: automatically raise character stats)

Error message:
Assertion (Argument head should be defined for packet actor_look_at) failed!
 at F:/Kafra/Kafra Support/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('', 'Argument head should be defined for packet actor_look_at') called at src/Network/PacketParser.pm line 192
	Network::PacketParser::reconstruct('Network::Send::iRO=HASH(0x6776adc)', 'HASH(0x6d59444)') called at src/Network/Send.pm line 600
	Network::Send::sendLook('Network::Send::iRO=HASH(0x6776adc)', 3, undef) called at src/AI/CoreLogic.pm line 372
	AI::CoreLogic::processLook() called at src/AI/CoreLogic.pm line 71
	AI::CoreLogic::iterate() called at src/functions.pl line 769
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4986114)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Stack trace:
Assertion (Argument head should be defined for packet actor_look_at) failed!
 at F:/Kafra/Kafra/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('', 'Argument head should be defined for packet actor_look_at') called at src/Network/PacketParser.pm line 192
	Network::PacketParser::reconstruct('Network::Send::iRO=HASH(0x6776adc)', 'HASH(0x6d59444)') called at src/Network/Send.pm line 600
	Network::Send::sendLook('Network::Send::iRO=HASH(0x6776adc)', 3, undef) called at src/AI/CoreLogic.pm line 372
	AI::CoreLogic::processLook() called at src/AI/CoreLogic.pm line 71
	AI::CoreLogic::iterate() called at src/functions.pl line 769
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4986114)') called at openkore.pl line 97
	main::__start() called at start.pl line 136
 at F:/Kafra/Kafra Support/src/deps/Carp/Assert.pm line 271
	Carp::Assert::assert('', 'Argument head should be defined for packet actor_look_at') called at src/Network/PacketParser.pm line 192
	Network::PacketParser::reconstruct('Network::Send::iRO=HASH(0x6776adc)', 'HASH(0x6d59444)') called at src/Network/Send.pm line 600
	Network::Send::sendLook('Network::Send::iRO=HASH(0x6776adc)', 3, undef) called at src/AI/CoreLogic.pm line 372
	AI::CoreLogic::processLook() called at src/AI/CoreLogic.pm line 71
	AI::CoreLogic::iterate() called at src/functions.pl line 769
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4986114)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

**Comment by Henrybk** [comment]
This other bug of your is fixed by #744
