### ISSUE TITLE
Deal Cancelled

### ISSUE THREAD

**Issue by FireflySkye** [OpenKore/openkore#756]
Unable to confirm a deal. Bot cancel it.
![image](https://user-images.githubusercontent.com/19757768/28580694-2a6d01d4-7115-11e7-9b6f-baccc74d32de.png)

**Comment by flacrasec** [comment]
@Henrybk yesterday i was noticing this issue

**Comment by flacrasec** [comment]
but the bug is at deal auto ;P

**Comment by Henrybk** [comment]
@FireflySkye Please test #760
