### ISSUE TITLE
timeout on map server. waiting action for the ragnarok online client - Please Help me to Fix this problem ( iRO - Re:start )

### ISSUE THREAD

**Issue by egugz** [OpenKore/openkore#757]
![ragna error](https://user-images.githubusercontent.com/30442205/28583232-211ddfa2-7171-11e7-9e57-20219e77792e.png)

**Comment by sctnightcore** [comment]
timeout ? 
You check that. Can i join the game ? 
If it does not work
download new openkore in github

**Comment by egugz** [comment]
I already try to download it again but same problem.. In my desktop computer is working, only in my laptop is not working.

**Comment by sctnightcore** [comment]
HAHA idk

**Comment by rhnbotfelt17** [comment]
BOT Ragnarok Gravindo (IND Server CHAOS/LOKI)
Demo Video:
https://www.youtube.com/watch?v=8xLIUQH3mKM


BOT Ragnarok pRO (Philippines Server LOKI/THOR)
Demo Video:
https://www.youtube.com/watch?v=J0k4BZDyxz0


More Information:
visit www.rhanfelta.blogspot.com

Bisa juga live demo via Team Viewer!

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by alisonrag** [comment]
Download latest version
