### ISSUE TITLE
 "New packet find tool " and edit servertybe 

### ISSUE THREAD

**Issue by sctnightcore** [OpenKore/openkore#763]
Like peek, it will look for a packet that does not match.
such as : 09DD 
i use https://github.com/MStr3am/PEEK   and   https://github.com/ThemonChan/PEEK get 09DD -1 
wpe : 09DD is 88 

What do i do next? 
I'm trying to update peek . I do not know That it will work

P.S private server 
 i love you all <3
Thanks for all the answers.
If the wrong information. Sorry

**Comment by moneyisgod** [comment]
Well it's -1 because it will never see 88, it can be 86, 92, 123, until 255.

You need discover which is this packet.

**Comment by sctnightcore** [comment]
ok sir

**Comment by moneyisgod** [comment]
https://github.com/Cronus-Emulator/Cronus/blob/master/src/map/packets_struct.h

Now you need discover WHEN this packet was implemented, or where could be used without do any error in Kore.

`#elif PACKETVER < 20131223
	idle_unitType = 0x915,
#elif PACKETVER < 20150513
	idle_unitType = 0x9dd,
#else
	idle_unitType = 0x915,
#endif`

Then we conclude that we can add this packet to sT > 2013 12 23.

**Comment by sctnightcore** [comment]
'0915' => ['actor_exists', ' is it ?

**Comment by sctnightcore** [comment]
> NPC Disappeared: Rocker (110052596)
<< Received packet:      0087 - You Move [12 bytes]
<< Received packet:      0087 - You Move
You're moving from (326, 200) to (332, 198) - distance 6.3
Move You - done
Route You - trimming down solution (81) by 8 steps
Route You - next step moving to (340, 198), index 15, 73 steps left
Move You - (re)trying
Sent packet    : 0437    [ 5 bytes]  
<< Received packet:      09DB [94 bytes]
<< Received packet:      09DB
Packet Parser: Unknown switch: 09DB
<< Received packet:      0087 - You Move [12 bytes]
<< Received packet:      0087 - You Move
You're moving from (328, 198) to (340, 198) - distance 12.0

**Comment by moneyisgod** [comment]
0915 is actor exists only when serverType < 20131223.

09DB is already inside sT0. But when it's used ? Need to check. I guess it's monster_information.
```
#elif PACKETVER < 20131223
	unit_walkingType = 0x914,
#elif PACKETVER < 20150513
	unit_walkingType = 0x9db,
#else
```
Just deal with the information.

**Comment by sctnightcore** [comment]
in error.txt
* 	unless ($args{actor}->isa('Actor') and $args{x} != 0 and $args{y} != 0) {
  		ArgumentException->throw(error => "Invalid arguments.");
@moneyisgod  
See 10 seconds of monster becoming npc.

**Comment by moneyisgod** [comment]
Man, i don't know actually how did u have done your patch. But i think you did some mistake in a part.

**Comment by rhnbotfelt17** [comment]
BOT Ragnarok Gravindo (IND Server CHAOS/LOKI)
Demo Video:
https://www.youtube.com/watch?v=8xLIUQH3mKM


BOT Ragnarok pRO (Philippines Server LOKI/THOR)
Demo Video:
https://www.youtube.com/watch?v=J0k4BZDyxz0


More Information:
visit www.rhanfelta.blogspot.com

Bisa juga live demo via Team Viewer!

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com

**Comment by kaliwanagan** [comment]
@sctnightcore i'm closing this for now :)
