### ISSUE TITLE
RO:RE Bot set worthless item as ammunitions

### ISSUE THREAD

**Issue by r421** [OpenKore/openkore#766]
Please refer to the [faqs](http://openkore.com/index.php/Frequently_Asked_Questions) (such as ["Packet Tokenizer"](http://openkore.com/index.php/Frequently_Asked_Questions#Packet_Tokenizer:_Unknown_switch:_xxxx)), [forum](http://forums.openkore.com), or [documentation wiki](http://openkore.com/index.php/Main_Page) for help using OpenKore.

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English

###### Summary: 
I change my old openkore to new openkore last night, what I change only config, items_control, macros, mon_controls and pickupitems. Today I saw bot trigger worthless item as ammunition so bot didn't sell the item.
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Impact:
![image](https://user-images.githubusercontent.com/26808551/28601042-8e6d0368-71e8-11e7-8ee5-8892d2bde9ba.png)

###### Expected Behavior:
Bot should not set worthless item as ammunition 

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by sctnightcore** [comment]
download new openkore is work @Henrybk

**Comment by r421** [comment]
thanks

**Comment by r421** [comment]
still not solve even pull new code. after fall back old version and it works again

**Comment by Henrybk** [comment]
@r421 Would you please test: https://github.com/OpenKore/openkore/pull/769

**Comment by rhnbotfelt17** [comment]
BOT Ragnarok Gravindo (IND Server CHAOS/LOKI)
Demo Video:
https://www.youtube.com/watch?v=8xLIUQH3mKM


BOT Ragnarok pRO (Philippines Server LOKI/THOR)
Demo Video:
https://www.youtube.com/watch?v=J0k4BZDyxz0


More Information:
visit www.rhanfelta.blogspot.com

Bisa juga live demo via Team Viewer!

**Comment by r421** [comment]
![image](https://user-images.githubusercontent.com/26808551/28726901-9fcb53bc-73f5-11e7-971a-1a4af00a9454.png)

Sorry late reply, just move to new openkore. Selling items it working purrrfect.. silver arrow is already put on but bot trigger still not wearing. any ideas? 

P/S:  I need to restart client to get it normal.

TQ

**Comment by kaliwanagan** [comment]
@r421 so we can close this now?

**Comment by r421** [comment]
sure, 
the solution is I put macro script to relog when it spam to equip.
Thanks
