### ISSUE TITLE
RO:RE stuck on Account Name Doesnt Exist

### ISSUE THREAD

**Issue by aDi-14** [OpenKore/openkore#771]
Hi,

I am using the server txt provided by sctnightcore 
[https://github.com/OpenKore/openkore/pull/722](url)

and i successfully connected to the server. However, I keep on getting the ACCOUNT NAME DOESNT EXIST error when i put my log in details and it keeps on asking my username but i am 100% sure i put the correct username.

But when I used it on RO itself, it works and my characters are intact. Is there anything that i Overlooked? Please help.

Thanks!

**Comment by sctnightcore** [comment]
@aDi-14  download new openkore on github <3 ty sir

**Comment by aDi-14** [comment]
@sctnightcore thanks for the reply

i did re-downloaded the latest openkore via github
[http://openkore.com/index.php/Main_Page](url)

[https://github.com/OpenKore/openkore](url)

however, i still am stuck with the ACCOUNT NAME DOESNT EXIST error. the zip size is around 44,813KB.

am i downloading at the wrong site?

**Comment by sctnightcore** [comment]
https://github.com/OpenKore/openkore << 

WOKR FOR IRO

**Comment by aDi-14** [comment]
@sctnightcore still of no avail. 

I downloaded via your link

Added the following for RESTART on server file at tables folder

[Ragnarok - Re:Start]
ip 128.241.92.133
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 145

still stuck at ACCOUNT NAME DOESNT EXIST. I am also trying to debug it but of no avail. Please advise.

Thanks!

**Comment by sctnightcore** [comment]
1.download new on github 
2.start bot 
P.S. Added the following for RESTART on server file at tables folder // dont add

**Comment by aDi-14** [comment]
@sctnightcore 

i downloaded the new on github. now, i cannot even log to the account server

![server error](https://user-images.githubusercontent.com/30463318/28651200-f44e5b30-72b2-11e7-9ebd-aa12badf0cbb.png)

**Comment by sctnightcore** [comment]
server down ? @aDi-14

**Comment by aDi-14** [comment]
@sctnightcore 

Server is Alive and Kicking.... For idk what reason, it became like this, even on my previous OpenKore (before downloading yours)

![server2](https://user-images.githubusercontent.com/30463318/28651350-f24f3f24-72b3-11e7-8ea9-a456df30cf6d.png)

**Comment by aDi-14** [comment]
@sctnightcore 

Got some work around. Here is the problem:
![server3](https://user-images.githubusercontent.com/30463318/28651762-4c6780fa-72b6-11e7-9597-7659b62b36c3.png)

**Comment by aDi-14** [comment]
@sctnightcore 

That IP Zone Asia block means that I cannot bot in this RO server even tho I'm here at Philippines? I was able to bot before on the prior RoPH, but now, i cannot even log-in to character select... Please help. Thanks a lot

**Comment by sctnightcore** [comment]
idk 
you can try x3 ?

**Comment by aDi-14** [comment]
thanks @sctnightcore for the assistance and tapping @kaliwanagan 

Hopefully @kaliwanagan can help me with this issue. once i get inside, i can configure my own bot. This entry process is the only one hindering me....

**Comment by kaliwanagan** [comment]
iRO is ip blocking users from asia.

Try a different server with the same username and see if you're able to us kore there.

**Comment by aDi-14** [comment]
Therefore there is no way to bot in Ro:Restart PH?

**Comment by oleokoong** [comment]
PH have local server, that why you cant bot?
Maybe you ca try something like VPN

**Comment by aDi-14** [comment]
i have used VPN, still no avail.

i know we all use the same IP add that @sctnightcore provided. that's why im wondering why i am stuck on the log-in screen that cannot recognize my log-in details

**Comment by aDi-14** [comment]
@oleokoong do you know the IP for the PH local server? maybe ill just play there instead of Restart

**Comment by oleokoong** [comment]
as i know openkore still not fully support PH server, they have gameguard or something protection
