### ISSUE TITLE
Toy Factory level 1 and 2 portals

### ISSUE THREAD

**Issue by xTriumph** [OpenKore/openkore#772]
Hello, i'm new to this openkore world, but it's very exciting to go through the config and figure out ways to make your bot do stuff.

Yesterday i decided to try to make the bot go to Lude, it was a ton of fun looking out how to change the Santa NPC location, make it go through the dialog and walk to xmas_dun. I managed to make my bot auto storage and use fly wings more precisely as well. But there's a problem that I "fixed" but it's not perfect yet. The portals of xmas_dun01 and 02 are in the same spot, and the portal of the second level is very crowded, and sometimes the bot gets stuck going in and out until he decides ( i think is random ) to move in a way that he doesn't go through the portal. To fix that i moved the portal x, y a little bit to the left, but he still gets stuck sometimes.

I've noticed that the char always get out of the portal in the right side, meaning that if i could program it to when he makes to the map he always go for a predefined path, and when he reaches the end of this path he starts to randomwalk he wouldn't get stuck. But i dont know how to do it.

Thanks.

**Comment by kaliwanagan** [comment]
You can create a macro or docommand block that moves to that particular location, then detect if kore is actually in that location which triggers the move through the portal.

You're already 80% there since you're already thinking about this programatically and computationally :)

**Comment by xTriumph** [comment]
@kaliwanagan Thanks for the tips, you pointed me at the right direction.
I've read the macros page on the wiki, very helpful ideed.
Now i'm testing the tiny macro that ive done for that. Some syntax if statement errors after i managed to get a working response from kore, but the servers are down anyway... cant be 100% if it's working. Here's the code:

macro tfacpath {
if ($.map = xmas_dun02) do walk 184, 131
log $.pos
}

But my questions are: How do i make it runs all the time checking my map? And after my bot completes the walk how do i make it randomwalk?

I know that this macro will not work as i planned, i would need to make it:
   -just when the bots changes the map, the macro would trigger.
   -if the if statement is true, he does the action
   -then, after doing the action it  start to randomwalk

But I don't have a clue how to do it. LOL
Thanks.

**Comment by sctnightcore** [comment]
> teleportAuto_unstuck 1

**Comment by kaliwanagan** [comment]
You can trigger anything you would type on the console from within the macro block. For example, if you want to clear the ai queue you can do `ai clear`

**Comment by c4c1n6kr3m1** [comment]
automacro

that's the next step to automize your code

http://wiki.openkore.com/index.php/Macro_plugin

**Comment by oleokoong** [comment]
you need automacro to trigger and run macro
trigger by condition or location or status

**Comment by xTriumph** [comment]
> teleportAuto_unstuck 1
> work bot for iRO ?
> i cannot login to server haha

Yeah, i'm testing it on the new iRO restart, i can login, but the server is always offline lol.

The unstuck command is helpful, but in this case the bot doesn't really get stuck, it never sends an error message. He's thinking that hes doing it's calculated path, but then he cross the portal and go back to dun01 doing a loop until he randomly decides to go to the right and not get stuck.

The macro would just assure that when he gets in the map, he always walk to the right, not crossing the portal when randomwalking.
