### ISSUE TITLE
Bot Gravindo Error Sending Encoded Password

### ISSUE THREAD

**Issue by BotGravind0** [OpenKore/openkore#782]
I've downloaded the Latest Version of Openkore, and tried to read every Issues but haven't found thee solution.

here is the picture..
![openkore sending encoded](https://user-images.githubusercontent.com/30513613/28698637-e9b5a608-736e-11e7-802d-0495c2d68a68.png)

I've tried the solution by using Sniff but still no luck

please give the guide step-by-step, I will give you what you need to solve this problem such as Ragexe.exe or the others.

any help would be appreciated. ( donation - Yes )

thanks

**Comment by rhnbotfelt17** [comment]
BOT Ragnarok Gravindo (IND Server CHAOS/LOKI)
Demo Video:
https://www.youtube.com/watch?v=8xLIUQH3mKM


BOT Ragnarok pRO (Philippines Server LOKI/THOR)
Demo Video:
https://www.youtube.com/watch?v=J0k4BZDyxz0


More Information:
visit www.rhanfelta.blogspot.com

Bisa juga live demo via Team Viewer!

**Comment by rhnbotfelt18** [comment]
PROMO BOT Ragnarok Hanya 300Ribu Untuk 2 Orang pembeli pertama berlaku hinggal tanggal 29/07/2017 pukul 12:00 WIB.

More Information:
 www.rhanfelta.blogspot.com
