### ISSUE TITLE
Unstorable item

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#799]
What about we update items_control to not store item based on rathena?
 I see every week peoples who cant store and open many topics just to solve this

Item Restrictions

Look on your db folder for a file called item_trade.txt and open it

Now, the pattern for a flag is:

Item ID, TradeMask, GM-Level Override

Item ID: the ID of your item.
TradeMask: Testrictions the item will have, such as being dropped, stored or traded. These values can be combined to achieve multiple effects.
1:Item can't be dropped 2:Item can't be traded (nor vended) 4:Item can only be traded with wedded partner 8:Item can't be sold to NPCs 16:Item can't be placed in the cart 32:Item can't be placed in the storage 64:Item can't be placed in the guild storage

GM-Level Override: This is the minimum GM level a player must have to avoid these restrictions.

**Comment by moneyisgod** [comment]
Hm it is amazing.
But since we can find servers with custom items, it can be useless. Since the user have to extract the items.txt, and then get item ID and Name.

But it would be a kind of AI since neither the players just know the item is not storable when they move the item to storage and it won't.

**Comment by sctnightcore** [comment]
Most Thai servers in Thailand. ~~lock grf file 
HAHA

**Comment by alisonrag** [comment]
@moneyisgod
We can implement in items_control and update ai to cover other cases

**Comment by alisonrag** [comment]
Get item_trade file here:
https://github.com/rathena/rathena/blob/master/db/re/item_trade.txt

Use this script:
https://codepaste.net/z8cn79

generate this:
https://codepaste.net/zkzs89

this file have only id and permissions.

the point now is:
should we add a double check (1 - item_name,  2 - item_id) in ai_storageAutoCheck() and processAutoStorage()?

**Comment by kaliwanagan** [comment]
Script looks good; I wonder if we need to create a repository for nice little tools like this so we can easily track them?

We can maybe have a folder for each utility, and a readme file in each folder to quickly explain what it does for which purpose.

I think the parsing of items_control.txt works with both ID and item name, so it would be good to do a strict check if they match. But it might cause some backwards compatibility issues, so I'd guess for a few months just show a deprecation warning?

**Comment by alisonrag** [comment]
About the repository:
will be a good stuff, many times a tryied to search scripts like this on internet and cant find something with a good quality.

The parser works fine with id, we just need to add a second check in ai routine for id.
In this case i think we can add a message, but we shouldn't remove the check for name, because of custom items like: "+8 SWORD [HYDRA CARD]" 

i will try to do something and pull a request.
