### ISSUE TITLE
Include compiled binaries in GitHub?

### ISSUE THREAD

**Issue by itsrachelfish** [OpenKore/openkore#8]
Should compiled binaries be included in the main GitHub repo? I'm thinking yes because it would mean people could simply click the "Download Zip" button and start using kore immediately, essentially equivalent to how the "openkore_ready" download site used to work.

**Comment by ya4ept** [comment]
I'm thinking yes

**Comment by jefferson-dab** [comment]
I have mixed feelings about it :smile:

If the aim is to have the master branch as the stable version (which by the way, ought to be a lot stabler now with Pull Requests) that's okay, I guess. Certainly, most (_all?_) Windows users don't build those from source anyway.

But there's also that [release](https://help.github.com/articles/creating-releases/) feature. This way it would be possible to release a zipped file with the source + the compiled stuff whenever there was enough stable commits to master. This would still keep the download->extract->run behavior and at the same time keep the repository free from the compiled binaries.

**Comment by Cozzie** [comment]
Yes, it is essential cause many users would like to have the latest dev version for bug fixes without jumping through hoops. UX is crucial here as most users would be lost in github.

**Comment by itsrachelfish** [comment]
Has been resolved as of #33
