### ISSUE TITLE
Connection error 100060 in iRO Restart

### ISSUE THREAD

**Issue by Arthurbe03** [OpenKore/openkore#800]
![error 100060](https://user-images.githubusercontent.com/30540238/28750325-a59db6e0-74bd-11e7-8e11-2c2d6b7c75b5.jpg)
I know that 3 pleople already posted this problem today and their post got closed by duplication, but i'm with this same problem and it started yesterday.
yes, i have already downloaded the recent openkore version like 30x times and i checked the ip server 30x times and it's the ip from the server.
if anyone can help or just post the the answer to this problem if it already exist, it will save my life
thanks by now

**Comment by oleokoong** [comment]
This is not openkore Issue, The IRO server Restart has been Ddos, now they active ddos mitigation, 
they limited connection to login server. 50% of my bot successfull to login
