### ISSUE TITLE
Broken item does not identified as [Broken]

### ISSUE THREAD

**Issue by smallvill3** [OpenKore/openkore#803]
Server name: GGamerzRO
Type: Private Server
serverType kRO_RagexeRE_2013_08_07a
Openkore version: Latest Git 30/7/2017

Issue:
Openkore does not properly identified my broken item as [Broken]

Game Client:
![1](https://user-images.githubusercontent.com/26625329/28752919-1a577cc4-755d-11e7-93be-081255a12ad4.JPG)

Console:
![2](https://user-images.githubusercontent.com/26625329/28752934-52ce7e7c-755d-11e7-9aaa-4d19b4fb8588.JPG)

**Comment by kaliwanagan** [comment]
Are you able to figure out how the packets are different?

**Comment by rhnbotfelt11** [comment]
pusing mau ngebot? Beli Zeny Mahal? Jasa joki juga mahal? mending ngebot sendiri aman bisa gb 100id ++ sampe lvl 99 bisa ngumpulin zeny cepat bahakan bisa jualan zeny.

Jual BOT Ragnarok Hanya 300Ribu berminat hubungi:081380644602 Mumpung harga promo

https://www.youtube.com/watch?v=8xLIUQH3mKM

**Comment by idrhnbot1** [comment]
Ayoo gan promo tinggal untuk 1 orang lagi sudah ada yg order 

Bukti pembelian promo kemarin:
https://image.ibb.co/b3buzk/IMAG0170.jpg

BOT Ragnarok No Limit No HWID bisa ngebot 100 ID++ dalam 1PC bisa di pakai PC laptop warnet tanpa batas.

Dari pada beli Zeny mending jualan Zeny,Dari pada Bayar jasa Joki Mahal Mending Joki pakai BOT bisa bikin lvl 99 100ID++ tanpa bayar joki

berminat hubungi:
081380644602

www.rhanfelta.blogspot.com

**Comment by moneyisgod** [comment]
Good night sir.
I've noted some changes that can conflict with 👍 
´´´
#elif PACKETVER < 20120925
	header = 0x2d4;
#elif PACKETVER < 20150226
	header = 0x990;

´´´
The thing is : 

equip_type changed from word to long ?
And then this 0x990 packet receive some extra params in the final.

**Comment by moneyisgod** [comment]
```
'02D4' => ['inventory_item_added', 'a2 v2 C3 a8 v C2 a4 v', [qw(ID amount nameID identified broken upgrade cards type_equip type fail expire unknown)]], # 29
'0990' => ['inventory_item_added', 'a2 v2 C3 a8 V C2 V v', [qw(ID amount nameID identified broken upgrade cards type_equip type fail expire bindOnEquipType)]],#31

/// 02d4 <index>.W <amount>.W <name id>.W <identified>.B <damaged>.B <refine>.B <card1>.W <card2>.W <card3>.W <card4>.W <equip location>.W <item type>.B <result>.B <expire time>.L <bindOnEquipType>.W (ZC_ITEM_PICKUP_ACK3)
/// 0990 <index>.W <amount>.W <name id>.W <identified>.B <damaged>.B <refine>.B <card1>.W <card2>.W <card3>.W <card4>.W <equip location>.L <item type>.B <result>.B <expire time>.L <bindOnEquipType>.W (ZC_ITEM_PICKUP_ACK_V5)
```

Looking emulator source, looks like everything is correct. O.O

**Comment by smallvill3** [comment]
@moneyisgod 
How can i create the useful info to fix this?

Are you interested to test and debug at my server?
I can provide you with GM account.

@kaliwanagan 
Cant figured out yet.

**Comment by moneyisgod** [comment]
```
16, 16, 16, 8, 8, 8, 32|16, 8, 8, 32, 16

Index = 16 = a2
Count = 16 = v2
Nameid = 16 = ? missing?
Identi = 8    \\
IsDmg = 8     == C3
Refine = 8   //
type_equip = 32 = 
type = 8 = V
result = 8 = C2
date = 32 = V
bind = 16 = v

type_equip = 20120925 >= 32 = a8
type_equip = else = 16
```
I had take my conclusion.
I guess it's missing one param. Need to on

**Comment by moneyisgod** [comment]
Yeah, please gimme a GM account with a Broken item. I'm waiting.

**Comment by smallvill3** [comment]
Your 1st solution seems to be more simple and easy fix.
Does official server produce the bug like this or just specific servertype?

**Comment by moneyisgod** [comment]
1 << 1 = 10bin = 2dec

then if identified is 

f(x) = x & 2
f(0) = 0 & 2= 0
f(1) = 1 & 2 = 0
f(2) = 2 & 2 = 2
f(3) = 2 & 3= 2

**Comment by smallvill3** [comment]
![capture](https://user-images.githubusercontent.com/26625329/29001565-59403012-7ac0-11e7-9486-729f1a416fa6.JPG)

After applied the 1st solution, my broken item now identified properly.
Thanks

**Comment by smallvill3** [comment]
So, how do you proposed the actual fix?

**Comment by moneyisgod** [comment]
Rly this parse items looks like complex. I dont understand it so good.

But i gave my points. But the misc is the exodia head.

**Comment by Fadreus** [comment]
Something related:
- Pet Egg (Named) appear as BROKEN too.

**Comment by moneyisgod** [comment]
?????????????????????????????????????????????

Looks like using two objects to assign values between themselves with the same function (hold item identify, last byte of packet ) is not a good idea.

**Comment by Fadreus** [comment]
I test in iRO.
Before
![image](https://user-images.githubusercontent.com/32188494/40567867-e2627a42-60a9-11e8-98e6-e326b9d727ab.png)
After
![image](https://user-images.githubusercontent.com/32188494/40567874-ec9df806-60a9-11e8-9097-707b3732d868.png)

**Comment by Fadreus** [comment]
I don't recall seeing it as BROKEN before (unless I put name on them).
Not sure if any pet egg hatched it will appear as such.
Don't have any other egg to test atm, all my pets are named.

**Comment by c4c1n6kr3m1** [comment]
yes, afaik
may be all official server will show BROKEN egg ?

**Comment by moneyisgod** [comment]
If you swap the Incubus and the Succubus in your inventory, you'll see that the first item will be broken. at least the first is Incubus ?


```
$item->{flag} will return 0
Then when $item->{flag} is checked it perform some logic to mark the item as broken based in "flag".

And it's done when items are parsed;

But the flag doesn't exists.
Than we have a problem even in stackable, as in nonstackable.

```

**Comment by c4c1n6kr3m1** [comment]
```
Kore sometimes uses "idenfitied" instead of "identified".
```
still not repaired
nice ‎observation

**Comment by alisonrag** [comment]
@moneyisgod
Item is defined by type in item struct, maybe we need update to ignore identified and broken when item is egg
ID nameID "type" type_equip equipped upgrade cards expire bindOnEquipType sprite_id num_options options identified

**Comment by c4c1n6kr3m1** [comment]
BROKEN egg is fine for me
that show the difference between hatched or not
unless you want to change "BROKEN" to "Hatched" , or something....
