### ISSUE TITLE
Any Update sa pRO? Thor/Loki?

### ISSUE THREAD

**Issue by Newbieman1234132** [OpenKore/openkore#804]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by rhnbotfelt11** [comment]
pusing mau ngebot? Beli Zeny Mahal? Jasa joki juga mahal? mending ngebot sendiri aman bisa gb 100id ++ sampe lvl 99 bisa ngumpulin zeny cepat bahakan bisa jualan zeny.

Jual BOT Ragnarok Hanya 300Ribu berminat hubungi:081380644602 Mumpung harga promo

https://www.youtube.com/watch?v=8xLIUQH3mKM

**Comment by Aiyaful** [comment]
please check [http://openkore.com/index.php/Main_Page](url) to know more. There are less devs than players waiting for the kore to work. They don't want the players to get banned instantly and blame the kore for it.

**Comment by idrhnbot1** [comment]
Ayoo gan promo tinggal untuk 1 orang lagi sudah ada yg order 

Bukti pembelian promo kemarin:
https://image.ibb.co/b3buzk/IMAG0170.jpg

BOT Ragnarok No Limit No HWID bisa ngebot 100 ID++ dalam 1PC bisa di pakai PC laptop warnet tanpa batas.

Dari pada beli Zeny mending jualan Zeny,Dari pada Bayar jasa Joki Mahal Mending Joki pakai BOT bisa bikin lvl 99 100ID++ tanpa bayar joki

berminat hubungi:
081380644602

www.rhanfelta.blogspot.com

**Comment by janwelocampo** [comment]
wait lang dude
