### ISSUE TITLE
Auto Stuck

### ISSUE THREAD

**Issue by faction** [OpenKore/openkore#810]
can someone help me ? it auto stuck when done buying stuff in npc then stuck on map for no reason

p/s sorry for my bad english

**Comment by alisonrag** [comment]
Server? Conditions to reproduce?

**Comment by rhnbotfelt11** [comment]
pusing mau ngebot? Beli Zeny Mahal? Jasa joki juga mahal? mending ngebot sendiri aman bisa gb 100id ++ sampe lvl 99 bisa ngumpulin zeny cepat bahakan bisa jualan zeny.

Jual BOT Ragnarok Hanya 300Ribu berminat hubungi:081380644602 Mumpung harga promo

https://www.youtube.com/watch?v=8xLIUQH3mKM

**Comment by oleokoong** [comment]
#770

**Comment by idrhnbot1** [comment]
Ayoo gan promo tinggal untuk 1 orang lagi sudah ada yg order 

Bukti pembelian promo kemarin:
https://image.ibb.co/b3buzk/IMAG0170.jpg

BOT Ragnarok No Limit No HWID bisa ngebot 100 ID++ dalam 1PC bisa di pakai PC laptop warnet tanpa batas.

Dari pada beli Zeny mending jualan Zeny,Dari pada Bayar jasa Joki Mahal Mending Joki pakai BOT bisa bikin lvl 99 100ID++ tanpa bayar joki

berminat hubungi:
081380644602

www.rhanfelta.blogspot.com

**Comment by alisonrag** [comment]
Fixeddl in #829
