### ISSUE TITLE
XileRO OS private server recvpackets

### ISSUE THREAD

**Issue by cloanx** [OpenKore/openkore#811]
i've been trying to connect to xile OS server,
having packet tokenizer error & sudden crashing.
unable to extract the recvpackets frm the exe. with PLE, i tried PEEK, v3 n v1
it says Packet Length Map is not found or failed.
here is the .exe
please help me to connect

[XileroOS]
ip 37.59.11.190
port 6901
master_version 18
version 20
serverType 8
charBlockSize 112
serverEncoding Western

here's the exe and patcher and sclientinfo..
client
https://www.dropbox.com/s/5vy322k1xfbfykk/XiLeRO%21.exe?dl=0
patcher
https://www.dropbox.com/s/q7lgrkum3ihj68m/XiLeRO.exe?dl=0
sclient
https://www.dropbox.com/s/9sr1zxjffqb9mpn/sclientinfo.xml?dl=0

**Comment by sctnightcore** [comment]
Well ...

**Comment by rhnbotfelt11** [comment]
pusing mau ngebot? Beli Zeny Mahal? Jasa joki juga mahal? mending ngebot sendiri aman bisa gb 100id ++ sampe lvl 99 bisa ngumpulin zeny cepat bahakan bisa jualan zeny.

Jual BOT Ragnarok Hanya 300Ribu berminat hubungi:081380644602 Mumpung harga promo

https://www.youtube.com/watch?v=8xLIUQH3mKM

**Comment by idrhnbot1** [comment]
Ayoo gan promo tinggal untuk 1 orang lagi sudah ada yg order 

Bukti pembelian promo kemarin:
https://image.ibb.co/b3buzk/IMAG0170.jpg

BOT Ragnarok No Limit No HWID bisa ngebot 100 ID++ dalam 1PC bisa di pakai PC laptop warnet tanpa batas.

Dari pada beli Zeny mending jualan Zeny,Dari pada Bayar jasa Joki Mahal Mending Joki pakai BOT bisa bikin lvl 99 100ID++ tanpa bayar joki

berminat hubungi:
081380644602

www.rhanfelta.blogspot.com

**Comment by idrhnbot2** [comment]
Ayoo Gan udah 2 Orang ambil promo di rhanfelta dan udah banyak yg lainya beli di rhanfelta sejak febuari
2017 Cek di blog ane gan untuk liat bukti pembelian lainya.

https://preview.ibb.co/n1FYAQ/DSC_0079.jpg

Beli Zeny Mahal? Jasa Joki Mahal? mending order bot di rhanfelta ajah
BOT Gravindo Ready bisa support multi BOT bisa ngebot 100id++ dalam 1PC bisa bikin lvl 99 100ID tanpa bayar joki mahal
cuman dapet 1 char, bisa jualan zeny juga lagi gak perlu beli zeny sama orang bisa stock zeny sendiri

cepetan gan cek di www.rhanfelta.blogspot.com mumpung masih ada promo untuk 1 pemebeli lagi.

Contact: 081380644602

**Comment by alisonrag** [comment]
closed because the issue owner has not replied for 25 days
