### ISSUE TITLE
Help: Packet Tokenizer: Unknown Switch: 0069

### ISSUE THREAD

**Issue by tupaclol** [OpenKore/openkore#814]
Erro: Packet: Tokenizer: Switch desconhecido: 0069

Server.txt:
[ReburnRO]
ip 63.143.54.78
port 6900
version 55
master_version 22
serverType kRO_RagexeRE_2015_11_04a
charBlockSize 147
recvpackets private.txt
addTableFolders Translated\kRO_english;kRO

**Comment by sctnightcore** [comment]
GG?
client date ?

**Comment by lututui** [comment]
Is [this ](http://www.reburnro.com/site/?module=main_c&action=info)the server?

**Comment by tupaclol** [comment]
@sctnightcore  no protect, 2015/11/02

**Comment by tupaclol** [comment]
@lututui yes

**Comment by lututui** [comment]
The website claims to use Gepard Shield

**Comment by moneyisgod** [comment]
kkkkkkk you can't extract the recvpackets because it have packet obfuscation auheauheh3uhu3

**Comment by idrhnbot1** [comment]
Ayoo gan promo tinggal untuk 1 orang lagi sudah ada yg order 

Bukti pembelian promo kemarin:
https://image.ibb.co/b3buzk/IMAG0170.jpg

BOT Ragnarok No Limit No HWID bisa ngebot 100 ID++ dalam 1PC bisa di pakai PC laptop warnet tanpa batas.

Dari pada beli Zeny mending jualan Zeny,Dari pada Bayar jasa Joki Mahal Mending Joki pakai BOT bisa bikin lvl 99 100ID++ tanpa bayar joki

berminat hubungi:
081380644602

www.rhanfelta.blogspot.com

**Comment by sctnightcore** [comment]
@tupaclol  no protect ? 
If you talk like that
1.Extracting recvpackets with peek

**Comment by Newbieman1234132** [comment]
Anyone Can help me in pRO?

**Comment by idrhnbot2** [comment]
Ayoo Gan udah 2 Orang ambil promo di rhanfelta dan udah banyak yg lainya beli di rhanfelta sejak febuari
2017 Cek di blog ane gan untuk liat bukti pembelian lainya.

https://preview.ibb.co/n1FYAQ/DSC_0079.jpg

Beli Zeny Mahal? Jasa Joki Mahal? mending order bot di rhanfelta ajah
BOT Gravindo Ready bisa support multi BOT bisa ngebot 100id++ dalam 1PC bisa bikin lvl 99 100ID tanpa bayar joki mahal
cuman dapet 1 char, bisa jualan zeny juga lagi gak perlu beli zeny sama orang bisa stock zeny sendiri

cepetan gan cek di www.rhanfelta.blogspot.com mumpung masih ada promo untuk 1 pemebeli lagi.

Contact: 081380644602
