### ISSUE TITLE
RO:restart 2/8/2017 cant log in? 

### ISSUE THREAD

**Issue by sinser** [OpenKore/openkore#819]
Hi, the bot cant log in to the game.......
may i know if the ip changed ? or any issue ?
because when i use client, able to log in.
here is my server.txt

[International - iRO: Re:Start]
ip 128.241.92.133
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 145
patchserver ropatch1.gravityus.com
patchpath /repatch

**Comment by idrhnbot2** [comment]
Ayoo Gan udah 2 Orang ambil promo di rhanfelta dan udah banyak yg lainya beli di rhanfelta sejak febuari
2017 Cek di blog ane gan untuk liat bukti pembelian lainya.

https://preview.ibb.co/n1FYAQ/DSC_0079.jpg

Beli Zeny Mahal? Jasa Joki Mahal? mending order bot di rhanfelta ajah
BOT Gravindo Ready bisa support multi BOT bisa ngebot 100id++ dalam 1PC bisa bikin lvl 99 100ID tanpa bayar joki mahal
cuman dapet 1 char, bisa jualan zeny juga lagi gak perlu beli zeny sama orang bisa stock zeny sendiri

cepetan gan cek di www.rhanfelta.blogspot.com mumpung masih ada promo untuk 1 pemebeli lagi.

Contact: 081380644602

**Comment by idrhnbot3** [comment]
Beli Zeny Mahal? Jasa Joki Bayar mahal cuman dpt 1ID?

Mending ngebot ajah gan bisa stock zeny sendiri bahkan jualan zeny sendiri, bisa bikin 100ID++ lvl 99 dalam waktu singkat dan langsung banyak ID. Cuman di www.rhanfelta.blogspot.com ayo gabung gan udah banyak bukti dan testi dari yang udah gabung

Contact: 081380644602
