### ISSUE TITLE
Unable to inject NetRedirect.DLL on xkore 1 WIN10 64BIT

### ISSUE THREAD

**Issue by V3T0R** [OpenKore/openkore#820]
OS: WIN 10 64-BIT

Have ran with admin rights, WIN 7/VISTA/XP comparability but still facing the unable to inject dll error.
Have done a search on forums (most reply comes with run as admin -> Win 7 compat) but it is still not working.

any help? 

Cheers!

**Comment by idrhnbot2** [comment]
Ayoo Gan udah 2 Orang ambil promo di rhanfelta dan udah banyak yg lainya beli di rhanfelta sejak febuari
2017 Cek di blog ane gan untuk liat bukti pembelian lainya.

https://preview.ibb.co/n1FYAQ/DSC_0079.jpg

Beli Zeny Mahal? Jasa Joki Mahal? mending order bot di rhanfelta ajah
BOT Gravindo Ready bisa support multi BOT bisa ngebot 100id++ dalam 1PC bisa bikin lvl 99 100ID tanpa bayar joki mahal
cuman dapet 1 char, bisa jualan zeny juga lagi gak perlu beli zeny sama orang bisa stock zeny sendiri

cepetan gan cek di www.rhanfelta.blogspot.com mumpung masih ada promo untuk 1 pemebeli lagi.

Contact: 081380644602

**Comment by idrhnbot3** [comment]
Beli Zeny Mahal? Jasa Joki Bayar mahal cuman dpt 1ID?

Mending ngebot ajah gan bisa stock zeny sendiri bahkan jualan zeny sendiri, bisa bikin 100ID++ lvl 99 dalam waktu singkat dan langsung banyak ID. Cuman di www.rhanfelta.blogspot.com ayo gabung gan udah banyak bukti dan testi dari yang udah gabung

Contact: 081380644602

**Comment by Newbieman1234132** [comment]
that is my problem too. :(

**Comment by k1nt4r0** [comment]
do u try to run ur both exe as admin?
mine is working well for xkore, but for some ro it isnt work

**Comment by V3T0R** [comment]
hi tried running both as admin, still giving injection error.

am on ragnarok PH atm

**Comment by Newbieman1234132** [comment]
Yes. I run as admin, but still injection error

Sent from Yahoo Mail. Get the app 

    On Monday, August 7, 2017 10:57 PM, V3T0R <notifications@github.com> wrote:
 

 hi tried running both as admin, still giving injection error.am on ragnarok PH atm—

**Comment by Newbieman1234132** [comment]
Yes. I run as admin, but still injection error 

Sent from Yahoo Mail. Get the app 

    On Sunday, August 6, 2017 7:41 PM, Kintaro <notifications@github.com> wrote:
 

 do u try to run ur both exe as admin?
mine is working well for xkore, but for some ro it isnt work—

**Comment by kaliwanagan** [comment]
ph ro is notyet supported.
