### ISSUE TITLE
HELP: How to get length of raw packet from encrypted packet ?

### ISSUE THREAD

**Issue by rianizm** [OpenKore/openkore#825]
Can someone enlighten me how to do it and what is the use of authmodule ?

**Comment by idrhnbot3** [comment]
Beli Zeny Mahal? Jasa Joki Bayar mahal cuman dpt 1ID?

Mending ngebot ajah gan bisa stock zeny sendiri bahkan jualan zeny sendiri, bisa bikin 100ID++ lvl 99 dalam waktu singkat dan langsung banyak ID. Cuman di www.rhanfelta.blogspot.com ayo gabung gan udah banyak bukti dan testi dari yang udah gabung

Contact: 081380644602
