### ISSUE TITLE
can i get monster given_name fast?

### ISSUE THREAD

**Issue by MingFaiYau** [OpenKore/openkore#830]
Hi all,

I want to find out the given_name of the monster...
i found that given_name is create in function actor_info ( in Receive.pm ), but it is quite slow...
can i make it find fast?...

can i found the name in other way?..
i hope someone can give me some advice, thanks a lot

**Comment by sctnightcore** [comment]
@мσиєyiรgσd

**Comment by alisonrag** [comment]
for what?

**Comment by MingFaiYau** [comment]
@alisonrag 
i am playing private server , it has a game which need to find out the real poring and it will make many different name poring..

**Comment by c4c1n6kr3m1** [comment]
ml
different name given , you will have "[name_given]"

**Comment by sctnightcore** [comment]
> void clif_name( struct block_list* src, struct block_list *bl, send_target target ){
	unsigned char buf[106];
	int cmd = 0x95;

	nullpo_retv(src);
	nullpo_retv(bl);

	WBUFW(buf,0) = cmd;
	WBUFL(buf,2) = bl->id;

	switch( bl->type )
	{
	case BL_PC:
		{
			struct map_session_data *sd = (struct map_session_data *)bl;
			struct party_data *p = NULL;

#if PACKETVER >= 20150513
			WBUFW(buf, 0) = cmd = 0xa30;
#else
			WBUFW(buf, 0) = cmd = 0x195;
#endif

[https://github.com/rathena/rathena/blob/master/src/map/clif.c](url)

**Comment by alisonrag** [comment]
if you use eventMacro:
http://openkore.com/index.php/EventMacro#Special_Keywords

```
&monster (<name|ID>)
Returns monster index of monster <name|ID>. If monster <name|ID> is not found, it returns -1.
```

**Comment by MingFaiYau** [comment]
@alisonrag thx for your suggestion,.
macro only can get the monster name..but not the name given...
