### ISSUE TITLE
Reacvpackets for private servers

### ISSUE THREAD

**Issue by mosienik** [OpenKore/openkore#832]
Hello dear developers of such an amazing tool :)

I want to clear for me some moments with recvpackets
Now I am playing on private server, and want to use openkore, but all tools I tried cannot extract recvpackets, or links for downloading are expired.
If it is possible, can u add recvpacket extract tools to git repo? And maybe create some manual on github wiki?
I was searching through 3 forums, 2 russian and one international, and like 99% links are expired and it is impossible to use those tools...

If it seems unconstructive - please close this issue and I will try to do my best to find out resolution.

Thank You in advance.

**Comment by sctnightcore** [comment]
http://forums.openkore.com/viewtopic.php?f=36&t=207278
Can help you for extractor packet 

But it is a good idea.

**Comment by mosienik** [comment]
I am trying to use this one extractor: https://github.com/ThemonChan/PEEK
But I am getting error:
"ExtractPacketLen : TypeError: Result of expression 'keys[0].packToHex' [undefined] is not a function"

I tried to look at code, and here is coming an error:
`	fp.writeline("Key1 = 0x" + convertToBE(keys[0].packToHex(4)));
	fp.writeline("Key2 = 0x" + convertToBE(keys[1].packToHex(4)));
	fp.writeline("Key3 = 0x" + convertToBE(keys[2].packToHex(4)));`

Looks like packToHex(4) return undefined, unfortunately I cannot debug it, but as I read in documentation - it is a valid expression

> (Number).packToHex(size) - packs a number to its little endian hex string with the size number of bytes used up size can be maximum 4. the number or expression needs to be in a bracket or a variable.
         e.g. (123456).packToHex(4) => " 40 E2 01 00"

Can You help me with this issue?

**Comment by mosienik** [comment]
And while I am using this one: https://github.com/sctnightcore/PEEK
I am getting error:

> DLLGen: Packet Key Patterns not found
That means I am gettind to this state:
`  if (offset === -1) {
    throw "Packet Key Patterns not found";
  }`
`  offset = exe.find(code, PTYPE_HEX, true, "\xAB", refOffset - 0x100, refOffset);
`

Is something wrong with my .exe file? Or am I missing some libraries?

Using windows 10, with lastst updates.

**Comment by mosienik** [comment]
I'm sorry, I used PEEK for .exe which is less then 6Mb.
I found a v3 extractor which is working good for .exe like mine.

I'm closing this issue cuz I am blind :)
