### ISSUE TITLE
iRO-Re:Start - Map change Locker

### ISSUE THREAD

**Issue by koynro** [OpenKore/openkore#835]
Travelling between Morocc and Morocc Ruins, it appears today's patch implemented a locking mechanism that will force you to respond actively in order to pass through a portal

```Your Coordinates: 155, 47
Calculating auto-buy route to: Morroc Ruins (moc_ruins): 99, 124
Unknown #50007: Do you want to move?
: Type 'talk cont' to continue talking
------ Responses (Unknown #50007) ------
#  Response
0  Yes
1  No
2  Cancel Chat
----------------------------------------
itself: Type 'talk resp #' to choose a response.
talk resp 0
itself: Done talking
---------Map  Info----------
MAP Name: moc_ruins.gat
MAP IP: 128.241.92.139
MAP Port: 4508
```

**Comment by sctnightcore** [comment]
r0 n

**Comment by c4c1n6kr3m1** [comment]
where? my novice free to enter moc_ruins

**Comment by sctnightcore** [comment]
-_- @c4c1n6kr3m1  
Probably somewhere on ro

**Comment by koynro** [comment]
Well, I just added these lines but of course when I try to pass though now it doesn't pop up right now.

I guess we'll see if it works if it starts happening again
