### ISSUE TITLE
Bot not connecting to iRO:restart server

### ISSUE THREAD

**Issue by Handymanalan** [OpenKore/openkore#836]
Is there an IP change that I am unaware of?
I can login and play normally but the bot can't connect.

Here's my log:

[Ragnarok - Re:Start]
ip 128.241.92.134
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 144

Should it be updated? Thanks

**Comment by EmanuelML** [comment]
Same problem here

**Comment by c4c1n6kr3m1** [comment]
can you guys check warpportal re:start forum first , before post ? 
or use ragnarok client

**Comment by EmanuelML** [comment]
But the server is working all night... Only the bot doesn't start...

**Comment by EmanuelML** [comment]
How do I update? I just download from the main page again?

**Comment by sctnightcore** [comment]
download new openkore on github  <3

**Comment by EmanuelML** [comment]
Still not working...

**Comment by sctnightcore** [comment]
server down ? idk

**Comment by EmanuelML** [comment]
It's on, but the bot still don't log in.

**Comment by sctnightcore** [comment]
You should download new openkore.

**Comment by EmanuelML** [comment]
I just did, still not working

**Comment by EmanuelML** [comment]
Is yours working?

**Comment by sctnightcore** [comment]
work ! 
 but  
You should redownload . Because it's updated a lot.

**Comment by EmanuelML** [comment]
Can you send me you server.txt?

**Comment by sctnightcore** [comment]
[International - iRO: Re:Start]
ip 128.241.92.133
port 6800
version 18
master_version 1
serverType iRO
addTableFolders iRO
serverEncoding Western
charBlockSize 145
patchserver ropatch1.gravityus.com
patchpath /repatch

**Comment by EmanuelML** [comment]
Changed and still don't work, don't know what's happening...

**Comment by wecotan** [comment]
We have the same problem. Not only in RE:Start but also in Renewal. I downloaded everything for several times but I still got error 10060.

**Comment by ZaskarAlpha** [comment]
Server was DDOS'ed. Close this topic pls.

**Comment by omnipresent666** [comment]
But regular login works. Is there no way to resolve this im getting Error 10061

**Comment by nestie23** [comment]
can you help me about this Thank You
![image](https://user-images.githubusercontent.com/31718702/30144949-e201147a-93c0-11e7-821a-cb2044ab3bff.png)
