### ISSUE TITLE
Can`t use xkore 1, it says is missing the NetRedirect.dll  I`m lost

### ISSUE THREAD

**Issue by Aanun** [OpenKore/openkore#837]
# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore
XKore 1
XKore_port 2350
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe

here it`s my config 
I start the client it says NetRedirect.dll is missing and then it crashes

**Comment by mosienik** [comment]
This things helped me:
1. Your openkore should have path with only eng letters, for example if You have russian locale, such as me, I should move my openkore to C:/, so now it is OK.
2. NetRedirect.dll should be in root of openkore folder
3. Try to start openkore as admin
4. Check .exe name

**Comment by kaliwanagan** [comment]
The issue template was there so we can help you with your problem easily.

Since you deleted that template without filling it out, I'm guessing your issue isn't of highest priority, so I'm just closing this (until you learn how to follow the rules).
