### ISSUE TITLE
[iRO RE:Start] RODEX Mail System: mail commands are disconnecting me

### ISSUE THREAD

**Issue by ytbro00** [OpenKore/openkore#840]
Hi there,

As RE:Start is using the new RODEX . I was wondering if it's possible to add a macro or plugin to mail the rare items and zeny (zeny for when it reaches a minimum for example, a million, send the rest to one of the main accounts and keep 100k for the bot itself.) instead of using the storage.  

I'm not sure if the "m" commands are the correct one.. Doesn't seem like it since the only working command is the mail send command ms (<receiver> <title> <message>) and mail open:  mo <mail #>.
The rest of the commands mi, mw, ma, md (untested), mr(untested) disconnects me as soon as I try to either open the inbox, write a message or add item / zeny.

Anyone have any idea on what the commands are or has someone already created a plugin?

**Comment by Henrybk** [comment]
I was the one who implemented the noew rodex system, it uses the command `rodex`.

By typing `rodex` into console you get the helpful explanation about the commands, I forgot to add it to the wiki.

**Comment by ytbro00** [comment]
I see. Thanks. I've been using the wrong commands all along. I'm not really experienced on making a plugin but I'll probably give it a try. Have only seen an old mail plugin on openkore forums. Would be nice to have it send all the stuff instead of doing everything manually.

**Comment by alisonrag** [comment]
implemmented on #691 
as henrybk said just use the command `rodex`.
