### ISSUE TITLE
NPCtalk stuck

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#848]
Hello, today i found my bots in stuck:

Map Change: aldeba_in.gat (94, 41)
Here are the shrimps, carrots and catnip!
- Responses (Cat Paw Shrimp Merchant) --
#  Response
0  Buy
1  Sell
2  Cancel
3  Cancel Chat
----------------------------------------
---------------- Store List (Unknown) ----------------
#  Name                    Type                  Price
0  Carrot                  Usable Heal             15z
1  Shrimp                  Usable Heal            500z
2  Nepeta Cataria          Usable Heal             15z
------------------------------------------------------
NPC Cat Paw Shrimp Merchant (0): Done talking
Done talking with NPC Cat Paw Shrimp Merchant (0).
Calculating auto-storage route to: Al De Baran(aldebaran): 143, 119
debug 2
Config 'debug' set to 2 (was 0)
Saving control\config_e1.txt...
AI: route storageAuto macro | 3
Move You - (re)trying
Sent move to: 94, 44
Move You - (re)trying
Sent move to: 94, 44
Move You - timeout

Openkore cant use "Done talkink" T____T
iRO

**Comment by Glikadin** [comment]
buyAuto Nepeta Cataria {
	minAmount
	maxAmount 9000
	npc aldeba_in 89 56
	npc_steps r0
	distance 8
	label BuyNepeta
	passive
}

macro_orphans terminate


ai_npc_talk_wait_to_answer 1.5
ai_npc_talk_wait_after_close_to_cancel 0.5
ai_npc_talk_wait_after_cancel_to_destroy 0.5

**Comment by moneyisgod** [comment]
> label BuyNepeta

How about ?

**Comment by Glikadin** [comment]
This is for the macro to control:

> do conf BuyNepeta.maxAmount 9000

**Comment by lututui** [comment]
npc_steps b

**Comment by Glikadin** [comment]
Iteration at Task::TalkNPC, current_talk_step '', next step 'x'.
NPC Cat Paw Shrimp Merchant (0): Initiating the talk
Sent talk: A8 C5 00 00
Received packet: 0095 Handler: actor_info
Received object info: Tool Dealer
NPC Info: Tool Dealer (1)
Received packet: 008D Handler: public_chat
Here are the shrimps, carrots and catnip!
Sent get player info: ID - 5C DE 00 00
Received packet: 00B7 Handler: npc_talk_responses
- Responses (Cat Paw Shrimp Merchant) --
#  Response
0  Buy
1  Sell
2  Cancel
3  Cancel Chat
----------------------------------------
Received packet: 0095 Handler: actor_info
Received object info: Inn Maid
NPC Info: Inn Maid (2)
AI: NPC buyAuto macro | 3
Iteration at Task::TalkNPC, current_talk_step 'select', next step 'r0'.
NPC Cat Paw Shrimp Merchant (0): Sending talk response #0
Sent talk respond: A8 C5 00 00, 1
Received packet: 00C6 Handler: npc_store_info
Item added to Store: Carrot - 15 z
Item added to Store: Shrimp - 500 z
Item added to Store: Nepeta Cataria - 15 z
---------------- Store List (Unknown) ----------------
#  Name                    Type                  Price
0  Carrot                  Usable Heal             15z
1  Shrimp                  Usable Heal            500z
2  Nepeta Cataria          Usable Heal             15z
------------------------------------------------------
Received packet: 00B6 Handler: npc_talk_close
NPC Cat Paw Shrimp Merchant (0): Done talking
NPC Cat Paw Shrimp Merchant (0): Sending talk cancel after NPC has done talking
Sent talk cancel: A8 C5 00 00
AI: NPC buyAuto macro | 3
Task::TalkNPC::conversation_end called at ai npc_talk 'close'.
Done talking with NPC Cat Paw Shrimp Merchant (0).
NPC Cat Paw Shrimp Merchant (0): Task::TalkNPC::DESTROY was called
AI: buyAuto macro | 2
AI: buyAuto macro | 2
Sent Sync
AI: buyAuto macro | 2
Received packet: 09DC Handler: actor_connected
Sent get player info: ID - BA 5A 4B 00
Received packet: 09DB Handler: actor_moved
Received packet: 007F Handler: received_sync
Received Sync
AI: buyAuto macro | 2
Received packet: 09DB Handler: actor_moved
Sent get player info: ID - BA 5A 4B 00
Received packet: 0095 Handler: actor_info
Received object info: JoySoiRebelde
Wiped old
Received packet: 0095 Handler: actor_info
Received object info: JoySoiRebelde
Received packet: 09DB Handler: actor_moved
AI: buyAuto macro | 2
Received packet: 009C Handler: actor_look_at
Player JoySoiRebelde (1) looks at 0, 0
Calculating auto-storage route to: Al De Baran(aldebaran): 143, 119
You on route to: Al De Baran(aldebaran): 143, 119
CalcMapRoute - initialized.
aldeba_in 94 38=aldebaran 197 70, 37
Map Solution Ready for traversal.
aldeba_in -> aldebaran -> aldebaran
Portal route within same map.
Route You Solution Ready!
Route You - next step moving to (94, 39), index 15, 17 steps left
Move You - (re)trying
Sent move to: 94, 39
Move You - (re)trying
Sent move to: 94, 39
AI: route storageAuto macro | 3
Move You - (re)trying
Sent move to: 94, 39
Move You - timeout
Route You - trimming down solution (17) by 1 steps
Route You - next step moving to (94, 38), index 15, 16 steps left
Move You - (re)trying
Sent move to: 94, 38
Move You - (re)trying
Sent move to: 94, 38
Move You - (re)trying
Sent move to: 94, 38
AI: route storageAuto macro | 3
Move You - timeout
Route You - not moving, decreasing step size to 12
Move You - (re)trying
Sent move to: 94, 41
Move You - (re)trying
Sent move to: 94, 41

**Comment by Glikadin** [comment]
Well, I realized I need to return the old version of openkore =\

**Comment by Glikadin** [comment]
I returned the old version and now everything is fine, thanks

**Comment by Glikadin** [comment]
I trying to use:

npc_steps r0 b
npc_steps r0 e
npc_steps r0 x

Ineffectively

**Comment by Glikadin** [comment]
Okay , i returned to old version of Openkore and wait fix. Thanks for the help (no)

**Comment by lututui** [comment]
Did you try **npc_steps b**?

**Comment by Glikadin** [comment]
Cat Paw Merchant
npc_steps r0

**Comment by Glikadin** [comment]
(Old version of Openkore buy correctly, but has many other problems)

Calculating auto-buy route to: Inside Al De Baran (aldeba_in): 89, 56
Map Change: aldeba_in.gat (94, 41)
Here are the shrimps, carrots and catnip!
- Responses (Cat Paw Shrimp Merchant) --
#  Response
0  Buy
1  Sell
2  Cancel
3  Cancel Chat
----------------------------------------
Cat Paw Shrimp Merchant: Type 'talk resp #' to choose a response.
-------- Store List (Cat Paw Shrimp Merchant) --------
#  Name                    Type                  Price
0  Carrot                  Usable Heal             15z
1  Shrimp                  Usable Heal            500z
2  Nepeta Cataria          Usable Heal             15z
------------------------------------------------------
Cat Paw Shrimp Merchant: Done talking
Done talking with Cat Paw Shrimp Merchant.
You lost 14,289 zeny.
Buy completed.

**Comment by alisonrag** [comment]
Fixed in #829
