### ISSUE TITLE
Unknown packet 0a27 and always disconnect when open storage at IDRO

### ISSUE THREAD

**Issue by hendra814** [OpenKore/openkore#85]
here my screen shoot, this problem at Midgard Server
![untitled](https://cloud.githubusercontent.com/assets/9587609/15035520/e6a3c266-12ac-11e6-9825-cbaa12d0cbef.JPG)

i'm solve with 0A27 8 8 1, copy from iRo

and for storage problem at src\network\send\idro.pm i'm adding this

> send_equip 00A9
> storage_password 023B
> sync 0360
> character_move 035F
> actor_info_request 0368
> actor_look_at 0361
> item_take 0362
> item_drop 0363
> storage_item_add 0364
> storage_item_remove 0365
> **storage_password 023B**
> skill_use_location 0366
> party_setting 07D7
> buy_bulk_vender 0801

hope this solution could solve another user.

Another unknown packet found
![untitled1](https://cloud.githubusercontent.com/assets/9587609/15035727/b92134d8-12af-11e6-9aaa-b7d694415c6a.JPG)

**Comment by itsrachelfish** [comment]
Thanks for reporting this bug! It looks like a simple fix that you, or anyone else who plays on idRO could create a pull request for. I would do it, but I can't test it myself because idRO blocks all non indonesian IP addresses :(

**Comment by cydh** [comment]
@hendra814 for storage u did it right, just it's already on master branch since 78a4780aefb5c7b76c85cbaca7af6dffdbc94dbc

For 0A27, from twRO/fRO did u mean? can't found it on iRO. So does with 0A3B.
Maybe I can make another PR for these changes
```diff
diff --git a/src/Network/Receive/idRO.pm b/src/Network/Receive/idRO.pm
index b0245d7..7c66cd6 100644
--- a/src/Network/Receive/idRO.pm
+++ b/src/Network/Receive/idRO.pm
@@ -30,6 +30,7 @@ sub new {
 		'0097' => ['private_message', 'v Z24 V Z*', [qw(len privMsgUser flag privMsg)]], # -1
 		'082D' => ['received_characters_info', 'x2 C5 x20', [qw(normal_slot premium_slot billing_slot producible_slot valid_slot)]],
 		'099D' => ['received_characters', 'x2 a*', [qw(charInfo)]],
+		'0A3B' => ['misc_effect', 'v a4 C v', [qw(len ID flag effect)]],
 	);
 
 	foreach my $switch (keys %packets) {
diff --git a/tables/idRO/recvpackets.txt b/tables/idRO/recvpackets.txt
index ba1a9be..3e2e861 100644
--- a/tables/idRO/recvpackets.txt
+++ b/tables/idRO/recvpackets.txt
@@ -1141,4 +1141,6 @@
 09C8 -1 13 0
 09C9 -1 4 0
 09CA 23 23 0
-09CB 17 17 1
\ No newline at end of file
+09CB 17 17 1
+0A27 8 8 1
+0A3B -1 12 1
```

**Comment by cydh** [comment]
the result is
````
Player Jobo (22) menggunakan efek: Unknown #12
Player Jobo (22) menggunakan efek: Unknown #12
Player Jobo (22) menggunakan efek: Unknown #12
Player Jobo (22) menggunakan efek: Unknown #12
Player Jobo (22) menggunakan efek: Unknown #12
Player Jobo (22) menggunakan efek: Unknown #12
Player Jobo (22) menggunakan efek: Unknown #12
````
the 12 is ID from data/luafiles514/lua files/hateffectinfo.lua.

````
	HAT_EF_DEMONSTRATION = 11,
	HAT_EF_Flutter_Butterfly = 12,
	HAT_EF_Angel_Fluttering = 13,
````

or maybe is it worth to add new file for this effect lookup? xD @itsrachelfish

**Comment by hendra814** [comment]
@cydh for 0A27 i'm get from http://collectskin.com/openkore/

**Comment by hendra814** [comment]
@cydh,

this fix, still not update into svn?

**Comment by cydh** [comment]
don't ask me why. I created PR #89

**Comment by itsrachelfish** [comment]
@hendra814 This fix has been merged into master on github (not svn).

Please clone this repo or download a new copy from [here](https://github.com/OpenKore/openkore/archive/master.zip) and let me know if your storage issue is fixed! :+1:

**Comment by hendra814** [comment]
@itsrachelfish , It's okay now.
but the issue 0A27 unknown paket showed again at  IRO chaos server.
should i create issue again for the IRO server?
