### ISSUE TITLE
Unable to input or paste non-English characters in console

### ISSUE THREAD

**Issue by kid4you** [OpenKore/openkore#851]
Summary:
Unable to input or paste non-English characters in console

Steps to Reproduce:
Nothing appears in the console command line if try to type or paste non-English languages.

**Comment by kaliwanagan** [comment]
Have you tried wxstart.exe ?

If you're using the windows console, this seems to be a windows console issue. Works fine with Linux.

**Comment by ChrstphrR** [comment]
Closed due to lack of follow-up/information needed to recreate the issue.
