### ISSUE TITLE
need answer

### ISSUE THREAD

**Issue by k1nt4r0** [OpenKore/openkore#854]
@lututui @Henrybk are really ragnarok already have the client of 2017
how about the bot? may it will release soon?

**Comment by sctnightcore** [comment]
server ? 
To gradually update 
There are too new packets.
I can create a servertybe to try.

**Comment by k1nt4r0** [comment]
[nova ragnarok](https://www.novaragnarok.com/?module=main), i see some1 trying to bot on that server
i see the problem maybe clientHash or maybe wrong sT
after i download it and try to find the right sT it showing up (2017)

**Comment by sctnightcore** [comment]
client date ? tell me ?

**Comment by alisonrag** [comment]
@k1nt4r0 
The support to severtype is made by peoples who are interessed
The last servertype supported is from year 2015

**Comment by sctnightcore** [comment]
RagexeRE_2017_05_17.pm
https://github.com/moneyisgod/SekaiRO-Patch-Openkore-
@k1nt4r0

**Comment by moneyisgod** [comment]
It only works because of 2014 sT hahaha

**Comment by k1nt4r0** [comment]
@sctnightcore the recvpackets cannot be extracted
@alisonrag yes, i try to looking for some1 who maybe interested to help it out :D

**Comment by kaliwanagan** [comment]
Please edit your title to something more descriptive. The next round I'm closing this if it doesn't tell what the issue is at first glance.

**Comment by k1nt4r0** [comment]
Uhm im sorry
