### ISSUE TITLE
How do I keep my bot from moving?

### ISSUE THREAD

**Issue by NewbieNoobs** [OpenKore/openkore#857]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by NewbieNoobs** [comment]
I'm connecting in pRO server using xkore

# 1 = hook into RO client, 2 = Act as stand-alone proxy, proxy = act as true proxy
# http://wiki.openkore.com/index.php/XKore
XKore 0
XKore_port 
XKore_dll NetRedirect.dll
XKore_autoAttachIfOneExe 1
XKore_silent 1
XKore_bypassBotDetection 0
XKore_exeName ragexe.exe

# XKore 2 / Proxy configuration
XKore_listenIp 
XKore_listenPort 
XKore_publicIp 
XKore_ID

lockMap moc_fild12
lockMap_x
lockMap_y
lockMap_randX
lockMap_randY

**Comment by kaliwanagan** [comment]
pRO is not supported right now.
