### ISSUE TITLE
Poseidon help

### ISSUE THREAD

**Issue by jemeizu** [OpenKore/openkore#859]
Hey everyone, I'm a bit of a noob when it comes to using openkore.

I'm currently playing on re:start ro.

Could someone please give me a noob friendly guide?  I don't understand the guide on the openkore wiki.

Thanks :)

**Comment by kaliwanagan** [comment]
Great job deleting the issue template so we can actually help you.

**Comment by lututui** [comment]
iRO RE:Start does not require Poseidon

**Comment by jemeizu** [comment]
@Kaliwanagan, is that sarcasm or are you actually being serious?
