### ISSUE TITLE
Timeout on Character Select Server, reconnecting...

### ISSUE THREAD

**Issue by Soijiru** [OpenKore/openkore#860]
###### Summary: 
I can't get passed the character selection because i get this error:

------------------------------------------
Connecting to Character Select Server...
Connecting (128.241.92.130:4500)... connected
Timeout on Character Select Server, reconnecting...
Connecting to Account Server...
Connecting (128.241.92.162:6800)... connected
Timeout on Account Server, reconnecting. Wait 30 seconds...

and it just keeps reconnecting.
I wonder if i have the wrong information for iRO

---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  493    128.241.92.155  4500
1   Chaos                 2434   128.241.92.130  4500
-----------------------------------------------------

But i really dont think so, because i log into the server.

Should I use something else to start the bot?
I tried start.exe and the wxstart.exe.

I used to work Bot back on the 2010/11. Is there any tricky line? Or some tutorial that i should be reading further?
Thank you

**Comment by kaliwanagan** [comment]
You deleted the issue template? How can we help if you don't give complete information?

**Comment by kaitoshion069** [comment]
can I ask you guys?

I use openkore but here what it said:

Connecting to Character Select Server...
Connecting (128.241.92.130:4500)... connected
Timeout on Character Select Server, reconnecting...

I waited it for a halfday but nothings happen, how/what should I do?

**Comment by sctnightcore** [comment]
@kaitoshion069  server ? 

if iRo , update openkore :p

**Comment by Fadreus** [comment]
That IP is IRO..

**Comment by kaitoshion069** [comment]
Thanks for responding guy, how can I update my openkore, I don't know how to use this tool @sctnightcore 
and yes I'm on IRo chaos server, and I want to use openkore because its really hard to play while I'm busy on working.

Really newbie here

**Comment by Fadreus** [comment]
@kaitoshion069 Just re-download is the easiest for beginner.
I'll tell you more on forum.
