### ISSUE TITLE
OPENKORE IS CLOSING

### ISSUE THREAD

**Issue by shidoshidoshido** [OpenKore/openkore#861]
Hi Everyone, 

I just downloaded the bot and I tried it in RO RESTART. However, the bot is working but it is closing.
i'm not sure if it is my antivirus or what but it is just running for 1 - 5mins. 

I just have an app called Restart on Crash so that it will open once the application is closed. is this expected? 

Thanks,
ShidoShidoShido

**Comment by kaliwanagan** [comment]
Great job deleting the issue template which was provided so we can actually help you.
