### ISSUE TITLE
Unable to load Plugins

### ISSUE THREAD

**Issue by FireflySkye** [OpenKore/openkore#863]
I updated my bot today.
new updates - Parser.pm

Cause problem, unable to load all plugins
I disable all plugins for now.
![image](https://user-images.githubusercontent.com/19757768/29026637-94347f54-7b31-11e7-8588-e4ca3a69b091.png)

**Comment by evildan23** [comment]
same at me

**Comment by mkaaquarius** [comment]
im having the same problem

**Comment by lovetiRO** [comment]
So, how to disable the plugins?

**Comment by mkaaquarius** [comment]
![gf](https://user-images.githubusercontent.com/21289401/29029262-ab2459ae-7bb9-11e7-8859-4b772eb2ff9c.jpg)

**Comment by iamtonysoft** [comment]
error was found at line 5 plugins/macro/Macro/Parser.pm

try to open it on notepad and edit those line and use this
**use encoding 'utf8';**

Note: this is a temporary fix. I just copy and paste the old line that was committed.

**Comment by evildan23** [comment]
couldn't connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (error code 10060)

**Comment by FireflySkye** [comment]
to disable plugin, go to sys.txt 
find this `loadPlugins 2` and change it to `loadPlugins 0`

**Comment by mkaaquarius** [comment]
its working now thanks :)

**Comment by moneyisgod** [comment]
@Henrybk

**Comment by lututui** [comment]
@FireflySkye Can you tell us the Perl version?

**Comment by alisonrag** [comment]
how about this issue ( #855 ) ?

**Comment by FireflySkye** [comment]
tested `loadPlugins 2` and it works again. Thank you.

**Comment by ChrstphrR** [comment]
Original user that opened issue seemingly has the issue solved with a later update to the code.

Anyone experiencing the same problem, please update your copy of Openkore's code -- and if problems persist, please open a new issue.
