### ISSUE TITLE
cannot connect on iph new loki please help

### ISSUE THREAD

**Issue by evildan23** [OpenKore/openkore#865]
couldn't connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (error code 10060)

![bot](https://user-images.githubusercontent.com/30799767/29031191-93ca0c06-7bb7-11e7-8aae-6a63f4f55401.jpg)

**Comment by ganggunggang** [comment]
Sir can you post your config pls tnx

**Comment by kaliwanagan** [comment]
Please follow the issue template.
