### ISSUE TITLE
stuck at looping in and out at tool dealer at izlude

### ISSUE THREAD

**Issue by MasterPuge** [OpenKore/openkore#873]
Please help me.. My location map is izlu2dun but My char stuck at looping in and out at tool dealer in izlude. The char not talking the sailor for warping in izlu2dun. I check the portal.txt is okey. please help me for solution for this problem. 
This is my portal.txt [ izlude 201 181 izlu2dun 107 50 150 c r0 ] . Thank you

**Comment by moneyisgod** [comment]
try only r0?

**Comment by lututui** [comment]
Try to lower **route_step** a bit in config.txt

**Comment by rrtsfarm** [comment]
exactly my problem. hope someone help us

**Comment by rrtsfarm** [comment]
tables\iRO\resnametable.txt

#After the Izlude Academy went in, the Izlude map changed.
#izlude.gat#izlude_a.gat#
#izlude_a.gat#izlude_a.gat#
#izlude_b.gat#izlude_a.gat#
#izlude_c.gat#izlude_a.gat#
#izlude_d.gat#izlude_a.gat#
#pvp_y_1-2.gat#izlude_a.gat#
#pvp_y_2-2.gat#izlude_a.gat#
#pvp_y_3-2.gat#izlude_a.gat#
#pvp_y_4-2.gat#izlude_a.gat#
#pvp_y_5-2.gat#izlude_a.gat#
#pvp_y_6-2.gat#izlude_a.gat#
#pvp_y_7-2.gat#izlude_a.gat#
#pvp_y_8-2.gat#izlude_a.gat#

Fixed mine fine, no need to change map files. Just put a # in front of each line and save it.

**Comment by alisonrag** [comment]
continue in #1006
