### ISSUE TITLE
Multiple bot in same folder error

### ISSUE THREAD

**Issue by koburaaa** [OpenKore/openkore#875]
seems like im having trouble making multiple bots work atm in i:RO restart. When i run wstart for the first bot it runs smoothly, but when i open the second(shortcut edited with paths and everything from the manual) it runs but it just stop responding. i need some help please

**Comment by ChrstphrR** [comment]
Without more details, regarding the OS, or examples of the shortcut you edited, it's going to be hard for anyone to assist.

*PLEASE DO NOT POST EXAMPLES THAT MAY SHOW _YOUR_ ACCOUNT DETAILS*
Caveat Emptor: We will not be responsible if you do provide actual account info here.

You can fake your examples that might show the account name in the paths by editing it to something else nonsensical, like say,  Pineapple, Strawberry, Banana, Avocado, Cherry, etc.   

But examples will be needed; just read them over carefully before you press "Comment".

Also, were you reading up on our wiki about specifying paths?
[http://openkore.com/index.php/Command_Line_Arguments](http://openkore.com/index.php/Command_Line_Arguments)

My own situation, I use linux, and specify paths using a shell script (*.sh) for each account, which supplies openkore the path to the control files, plugins, fields, and databases on the command line.

Tell us more about what you're using, and how you're trying to set up the multiple accounts.  It is possible!   I will keep this thread open a while longer, waiting for your followup.
