### ISSUE TITLE
Disconnect when porting back to town

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#878]
Auto-storaging due to excess weight
Teleporting to auto-storage
Permitted to use Teleport (26), level 2
You used Item: Butterfly Wing (4) x 1 - 7 left
Inventory Item Removed: Butterfly Wing (4) x 1
Packet Tokenizer: Unknown switch: 0AB8
Then the bot disconnects

TeleportAuto useSkill is set to 0 in config.

Happened on multiple bots in multiple areas.

**Comment by oleokoong** [comment]
Check your config at disconnect section

**Comment by lututui** [comment]
Which server?

**Comment by kaliwanagan** [comment]
Why do people keep on deleting the issue template :(

**Comment by Zexeta** [comment]
Sorry all my posts are about Re:start i thought people noticed that.   I didn't change any config settings. I simply updated the files with the recent changes and this started occurring.

**Comment by lututui** [comment]
0AB8 was already added to recvpackets (#706), you shouldn't be getting a Tokenizer warning about it
