### ISSUE TITLE
BOT Ragnarok Gravindo Buruan!

### ISSUE THREAD

**Issue by paramitapaypa** [OpenKore/openkore#879]
:(

**Comment by kaliwanagan** [comment]
Hey man, I know you run a business but the Github issue tracker isn't the place to do it. Can you please do this in the forums instead?

We're doing a lot of bugfixes and seriously, your marketing spam is making our lives worse.

Remember, what you're selling is still openkore and is still benefiting from our patches. So please help us by not spamming the issue tracker?
