### ISSUE TITLE
new setting for storageAuto_npc_type?

### ISSUE THREAD

**Issue by lordzpipo** [OpenKore/openkore#880]
as a title, 
since iRO got extra dialog for vip storage,
it will broken the autostorage feature, and we need to adjust
`storageAuto_npc_type 1` 
to
`storageAuto_npc_type 3`
`storageAuto_npc_steps c w1 r1 w1 c w3 r0` 

what my suggestion is addon 1 more type to fix this problem,
wish help

ps: server information, iRO-Chaos

**Comment by lututui** [comment]
bRO Valhalla main storage also uses storageAuto_npc_steps c r1 c r0 for most Kafras.

I don't think it should just be pushed back as storageAuto_npc_type 4 (that would be weird, right?)

Is this even necessary?
