### ISSUE TITLE
Ragnarok Re:Start OLD MAPS problem 

### ISSUE THREAD

**Issue by pussbacon** [OpenKore/openkore#881]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary: 
won't got to the dungeons that requires talking to the npc or have updated map
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Summary:
please do give me an advice on how to fix the new maps problem
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Benefits:
for god sake

**Comment by xTriumph** [comment]
Could you tell what maps/NPC are you trying to access/talk?

**Comment by pussbacon** [comment]
I can access all maps but there are places that my bots doesn't wanna go to maybe brcause I have new maps. Whenever my bot dies it will spawn back to al de and won't talk to santa in order to go in lutie. Also izlude to byalan isn't automatic as well 


Sent from Yahoo Mail for iPhone


On Wednesday, August 9, 2017, 11:06 AM, Lucas <notifications@github.com> wrote:


Could you tell what maps/NPC are you trying to access/talk?

**Comment by xTriumph** [comment]
The Santa NPC was updated, if you download the newest version it should work. When the server go online after the maintence I will work on the Byalan warp.

**Comment by gusbuster4025** [comment]
Hi i'm also having issue with ant hell which is on its classic location in moc_fild04 not the updated one in the renewal portal.txt file which is still cmd_fild08

**Comment by alisonrag** [comment]
update your openkore if you have any problem just talk to us and we will try to add portal fast as possible
