### ISSUE TITLE
[bug]talk "name" Ignoring some npc's

### ISSUE THREAD

**Issue by Guiim** [OpenKore/openkore#885]
Hi, maybe I'm doing something wrong, but I tried to use the talk command to talk to the soldier npc, located on payon 166,102, the command ignores it, and it does the dialog with the npc vendor tool.

Talk "soldier"
NPC Tool Vendor (0): Enter 'store' to buy or sell to sell

version
*** OpenKore what-will-become-2.1 ( version git:db005e2_2017-08-21 ctime:2017_08_02 ) - Custom Ragnarok Online client ***
***   http://www.openkore.com/   ***

The talk "name" command is only working for some npc's, in the example below I tried to use the payon kafra which is located in payon 181,104
He ignores it and initiates a dialogue with Smile Helper in 186,104

Talk "Kafra Employee"
Smile Helper: [Smile Gal]
Smile Helper: Hello! How are you?
Smile Helper: I am the Mr.Smile Supporter.
Smile Helper: How may I assist you?
NPC Smile Helper (0): Type 'talk cont' to continue the conversation.

**Comment by guilhermeferreira1** [comment]
Hi, maybe I'm doing something wrong, but I tried to use the talk command to talk to the sold npc, located on payon 166,102, the command ignores it, and it does the dialog with the npc vendor tool.

Talk "soldier"
NPC Tool Vendor (0): Enter 'store' to buy or sell to sell
