### ISSUE TITLE
Morroc west and northwest gate dialogue

### ISSUE THREAD

**Issue by Handymanalan** [OpenKore/openkore#887]
After the update whenever I want to go to the pyramid and Sphinx from Morroc, a dialogue pops up before I can get through the gate. Is there any method openkore can bypass that? Thanks all.

**Comment by xTriumph** [comment]
You would need to create a autoMacro for that, making your bot respond to the dialog.

**Comment by Handymanalan** [comment]
Thanks, but what is a autoMacro?

**Comment by Nipodemos** [comment]
a plugin called autoTalkDatabase may solve your issue: [https://github.com/Henrybk/Plugins/tree/master/autoTalkDatabase](url)
