### ISSUE TITLE
packet tokenizer encrypted packet received pRO Thor/Loki

### ISSUE THREAD

**Issue by zzzzllopob** [OpenKore/openkore#888]
![opekcoredasdas](https://user-images.githubusercontent.com/30696140/29158800-f457aaa0-7dde-11e7-8c66-064280ca4d7f.png)
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by kaliwanagan** [comment]
pRO is not yet supported.

**Comment by zzzzllopob** [comment]
Really?
Dami ko nakikita bot user ^_^

BTW thanks
