### ISSUE TITLE
Gravindo sex char 1f and invalid character specific

### ISSUE THREAD

**Issue by kelvinyusuf93** [OpenKore/openkore#889]
> Generating session Admin Password...
> 
> Checking for new portals... none found
> 
> 
> Connecting to Account Server...
> Connecting (202.93.25.81:6900)... connected
> Secure Login...
> rebuilding packet here ..
> ---------- Account Info ----------
> Account ID: XXXXXXXX
> Sex:        Laki-Laki
> Session ID: XXXXXXXX
> 
> ----------------------------------
> ---------------------- Servers ----------------------
> #   Name                  Users  IP              Port
> 0   LOKI                  1644   202.93.26.70    6000
> 1   CHAOS                 5566   202.93.25.70    6000
> -----------------------------------------------------
> Closing connection to Account Server
> Disconnecting (202.93.25.81:6900)...disconnected
> Connecting to Character Server...
> Selected server: CHAOS
> Connecting (202.93.25.70:6000)... connected
> char sex : 1fError logging into Character Server (invalid character specified)...
> Disconnecting (202.93.25.70:6000)...disconnected

hello guys, any solution or clue about my problem, i always got invalid character specified, and char sex 1f

in my network/send.pm
```
# TODO: $masterServer->{gameLogin_packet}?
sub sendGameLogin {
	my ($self, $accountID, $sessionID, $sessionID2, $sex) = @_;
    debug sprintf("char sex : %x",getHex($sex)) , "send_game_login" , 0;
	$self->sendToServer($self->reconstruct({
		switch => 'game_login',
		accountID => $accountID,
		sessionID => $sessionID,
		sessionID2 => $sessionID2,
		accountSex => 1, #nyang ini ganti seusai sex 1= cowo / 2 hode laknat formatnye "1" bakal cowo
	}));
	debug "Sent sendGameLogin\n", "sendPacket", 2;
}

sub sendCharLogin {
	my ($self, $char) = @_;
	$self->sendToServer($self->reconstruct({switch => 'char_login', slot => '0'})); #nyang ini bakal char slot selalu kurangin 1, misal char slot pertama kurangin 1 berarti isi '0' nah begono
	debug "Sent sendCharLogin\n", "sendPacket", 2;
}

sub sendMapLogin {
	my ($self, $accountID, $charID, $sessionID, $sex) = @_;
	my $msg;
	$sex = 0 if ($sex > 1 || $sex < 0); # Sex can only be 00 (female) or 01 (male)
	
	if ($self->{serverType} == 0 || $self->{serverType} == 21 || $self->{serverType} == 22) {
		$msg = $self->reconstruct({
			switch => 'map_login',
			accountID => $accountID,
			charID => $charID,
			sessionID => $sessionID,
			tick => getTickCount,
			sex => $sex,
		});
              } else { #oRO and pRO
		my $key;

		$key = pack("C*", 0xFA, 0x12, 0, 0x50, 0x83);
		$msg = pack("C*", 0x72, 0, 0, 0, 0) .
			$accountID .
			$key .
			$charID .
			pack("C*", 0xFF, 0xFF) .
			$sessionID .
			pack("V", getTickCount()) .
			pack("C", $sex);
	}

	$self->sendToServer($msg);
	debug "Sent sendMapLogin\n", "sendPacket", 2;
}
```

also in my servers.txt
charBlockSize 144

any solution or clue? i really appreciate.. thank you..

**# PLEASE NO JUNK**

**Comment by rhan4x** [comment]
[img]https://image.ibb.co/mXb19v/Untitled.jpg[/img]

Ayo gan pembeli yg di atas ajah udah ane bantu via teamviewer agan yg lain mana!!

Ayo gan sumber botnya langsung cuman di www|dot|rhanfelta|dot|blogspot|dot|com think smart gan dari pada beli zeny mahal-mahal mending stock sendiri ajah gan bisa jualan zeny sendiri juga lagi, dari pada bayar jasa joki mahal cuman dpt 1 char mending pake bot bisa bikin char lvl 99 100ID++ dalam 1 pc dalam waktu singkat.

Ayo gan mumpung masih ada promo khusus buat agan 1x lagi. sebelum harga promonya expired mumpung murah gan ayoo join di www|dot|rhanfelta|dot|blogspot|dot|com bot ragnarok bergaransi aman sumbernya langsung harga murah cuman buat agan.

update ane baru beli hp baru hp lama masih di ugd jadi udah bisa terima tlp sms lagi yg berminat contact ane ajah langsung.

|0813|8064|4602| / visit www|dot|rhanfelta|dot|blogspot|dot|com

**Comment by qasdreq99** [comment]
beli zeny mahal? jasa joki mahal cuman dpt 1 akun? mending ngebot ajh buruan ada promo cuman buat kamu kunjungi www.rhanfelta.blogspot.com bisa stock zeny sendiri bahkan jualan zeny sendiri ataupun bisa bikin 100ID++ lvl 99 dalam 1 pc dengan waktu sekejap gak perlu bayar jasa joki yg gk jelas ujung-ujungnya di hack!

Contact:
081380644602

**Comment by lututui** [comment]
@qasdreq99 Could you please stop? You are helping no one spamming

**Comment by fsinz** [comment]
@kelvinyusuf93 did u used sniping or dolphin plugin for bypass login ? cek ur PacketParser.pm/dolphin or mail me tempetahu1501@gmail.com
