### ISSUE TITLE
RE:Start unable to connect

### ISSUE THREAD

**Issue by euliesces** [OpenKore/openkore#890]
![image](https://user-images.githubusercontent.com/30886910/29177073-49daafcc-7e20-11e7-9d3c-5c6352219500.png)

Hi guys yesterday the bot is working fine now im receiving this error message

and yes i downloaded the latest openkore from github and still now working

**Comment by babis468** [comment]
Same problem since maintenance, i tried with this: ip 128.241.92.133 and 128.241.92.134.

**Comment by EmanuelML** [comment]
Try a VPN

I'm with this trouble: 2 of my bots are logging normally, but one of them only logs with a VPN

**Comment by babis468** [comment]
It works! Thanks a lot. However i can login in the game without vpn ._.

**Comment by EmanuelML** [comment]
Me too, I can login, and two of my bots work without VPN, I need VPN only to my 3° bot, dont know why...

**Comment by ipoonu** [comment]
I am actually having the same problem i can bot 3 to 5 accounts however once i close them i cannot login anymore then i have to wait for a few hours just to let them login again, i have tried to reinstall my OS a couple of times and they work all my accounts but then after a few days back to the same problem :(

**Comment by oleokoong** [comment]
look like the server limit the player to login in certain time.. before I quit restart.. I can bot maximum 14 id,, once bot more than 14.. it will dc the bot..

**Comment by euliesces** [comment]
any resolution guys?

**Comment by c4c1n6kr3m1** [comment]
may be you should ask warpportal ? heh

**Comment by rhan4x** [comment]
![untitled](https://user-images.githubusercontent.com/30954281/29240818-e36e83ee-7f96-11e7-9f42-efdb662a7d6e.jpg)


Ayo gan pembeli yg di atas ajah udah ane bantu via teamviewer agan yg lain mana!!

Ayo gan sumber botnya langsung cuman di www.rhanfelta.blogspot.com think smart gan dari pada beli zeny mahal-mahal mending stock sendiri ajah gan bisa jualan zeny sendiri juga lagi, dari pada bayar jasa joki mahal cuman dpt 1 char mending pake bot bisa bikin char lvl 99 100ID++ dalam 1 pc dalam waktu singkat.

Ayo gan mumpung masih ada promo khusus buat agan 1x lagi. sebelum harga promonya expired mumpung murah gan ayoo join di www.rhanfelta.blogspot.com bot ragnarok bergaransi aman sumbernya langsung harga murah cuman buat agan.

update ane baru beli hp baru hp lama masih di ugd jadi udah bisa terima tlp sms lagi yg berminat contact ane ajah langsung.

081380644602 / visit www.rhanfelta.blogspot.com

**Comment by ristrettojoe1** [comment]
I have the same problem. It's difficult to connect with the bot.

**Comment by ChrstphrR** [comment]
Have any of you tried the obvious, and tried the same account from the official GUI client, on the same connection/ip that you're using openkore from?

9 Comments, and not a single one has bothered to do the most basic of troubleshooting steps.

This space is for issues and steps to either provide more information to further explain the problem, provide steps to reproduce it...  or to probe with questions or provide information that leads to a resolution.

Me too posts are unhelpful.

And the utter lack of information about what version of openkore you're using while complaining about a lack of connection is unhelpful at best, lazy at worst.

The devs, helpers, and fellow users are not going to spoon feed you, nor are we interested in extracting the baseline information needed to reproduce a problem like we're pulling teeth one by one.

This issue will be closed if the original poster does not provide more information that will help solve the problem.

**Comment by ChrstphrR** [comment]
No follow up or clarification in 12 days from original poster.  Issue is closed for lack of information to reproduce the issue.
