### ISSUE TITLE
character login but in not map

### ISSUE THREAD

**Issue by ai3live** [OpenKore/openkore#891]
help. character login but not in map

**Comment by rhan4x** [comment]
![untitled](https://user-images.githubusercontent.com/30954281/29240818-e36e83ee-7f96-11e7-9f42-efdb662a7d6e.jpg)


Ayo gan pembeli yg di atas ajah udah ane bantu via teamviewer agan yg lain mana!!

Ayo gan sumber botnya langsung cuman di www.rhanfelta.blogspot.com think smart gan dari pada beli zeny mahal-mahal mending stock sendiri ajah gan bisa jualan zeny sendiri juga lagi, dari pada bayar jasa joki mahal cuman dpt 1 char mending pake bot bisa bikin char lvl 99 100ID++ dalam 1 pc dalam waktu singkat.

Ayo gan mumpung masih ada promo khusus buat agan 1x lagi. sebelum harga promonya expired mumpung murah gan ayoo join di www.rhanfelta.blogspot.com bot ragnarok bergaransi aman sumbernya langsung harga murah cuman buat agan.

update ane baru beli hp baru hp lama masih di ugd jadi udah bisa terima tlp sms lagi yg berminat contact ane ajah langsung.

081380644602 / visit www.rhanfelta.blogspot.com

**Comment by zxc4xa** [comment]
Update Bukti 14 Agustus 2017 Setelah Mainatnce Still Works:
![14 agustus 2017 after mt](https://user-images.githubusercontent.com/30999621/29262785-46da9098-8100-11e7-836a-8df8028d6b08.jpg)

Beli Zeny Mahal? Jasa Joki per ID Muahaalll bangeet? mending join ajah gan di www.rhanfelta.blogspot.com lebih dari puluhan orang udah Join, Jadilah Smart Gamer gan dengan join di rhanfelta bisa stock zeny sendiri gak perlu beli lagi sama orang bahkan bisa jualan zeny sendiri. agan pun bisa bikin 100ID++ lvl99 dalam 1PC dengan waktu singkat come on gan think smart!!

buruan gan mumpung masih ada slot promo cuman untuk agan!!

Visit : www.rhanfelta.blogspot.com
Contact: 081380644602
