### ISSUE TITLE
Very usefull plugin may contributors will new idea

### ISSUE THREAD

**Issue by k1nt4r0** [OpenKore/openkore#893]
@kaliwanagan @allanon @Henrybk @sctnightcore 
I read searching to make the autobuy bulk item working well without make the kore always stuck beetwen the kafra storage and seller npc.

and i found this : [bulkbuyer.pl](forums.openkore.com/viewtopic.php?f=34&t=211738)
i try this but with the newest corelogic, it give an error.
and i try to edit the corelogic manually with the tutorial for that plugin, it work well, but
if the partyAutoShare set as 1 it will being error

i think this plugin very usefull, i hope contributors will make it work perfectly :D

this plugin made by Mortimal
this is the plugin
[plugin.zip](https://github.com/OpenKore/openkore/files/1215685/plugin.zip)

and this is the corelogic that i edit by myself, it work but still have some error.
[CoreLogic.zip](https://github.com/OpenKore/openkore/files/1215687/CoreLogic.zip)

and maybe openkore can update it self automatic from github?

**Comment by alisonrag** [comment]
this plugin only send the buy command one time with all items you have configured
it's not much different from original buy.

**Comment by k1nt4r0** [comment]
@alisonrag  yes it make it clear, when i use it my kore never stuck between storaging and buying anymore, and buying item being more fast.
i think that concept very good if can being the deafult on ok?

**Comment by alisonrag** [comment]
@k1nt4r0 
In #829  the @Henrybk  have implemented the same system, we need just to wait for code review and approvation. We are close to fix this.

**Comment by k1nt4r0** [comment]
hmm, as i know @Henrybk is still trying to make the autobuy and sell system be better, lets wait :D 
btw, @alisonrag do you know how to auto update the openkore from github like svn?
i always update it by myself, copy and paste than try it to see how the change work, its tired haha

**Comment by rhan4x** [comment]
![untitled](https://user-images.githubusercontent.com/30954281/29240818-e36e83ee-7f96-11e7-9f42-efdb662a7d6e.jpg)


Ayo gan pembeli yg di atas ajah udah ane bantu via teamviewer agan yg lain mana!!

Ayo gan sumber botnya langsung cuman di www.rhanfelta.blogspot.com think smart gan dari pada beli zeny mahal-mahal mending stock sendiri ajah gan bisa jualan zeny sendiri juga lagi, dari pada bayar jasa joki mahal cuman dpt 1 char mending pake bot bisa bikin char lvl 99 100ID++ dalam 1 pc dalam waktu singkat.

Ayo gan mumpung masih ada promo khusus buat agan 1x lagi. sebelum harga promonya expired mumpung murah gan ayoo join di www.rhanfelta.blogspot.com bot ragnarok bergaransi aman sumbernya langsung harga murah cuman buat agan.

update ane baru beli hp baru hp lama masih di ugd jadi udah bisa terima tlp sms lagi yg berminat contact ane ajah langsung.

081380644602 / visit www.rhanfelta.blogspot.com

**Comment by alisonrag** [comment]
@k1nt4r0
I use Github desktop
https://desktop.github.com
You can easy clone and update

**Comment by sctnightcore** [comment]
well ..

**Comment by alisonrag** [comment]
Implemented in #829
