### ISSUE TITLE
coreLogic processAutoStorage/AutoSell/AutoBuy()

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#899]
###### Summary: 
In coreLogic we have:

>processAutoStorage();
Misc::checkValidity("AI (autostorage)");
processAutoSell();
Misc::checkValidity("AI (autosell)");
processAutoBuy();
Misc::checkValidity("AI (autobuy)");

why we have to force each other in subs?

example:
> if ($ai_v{'temp'}{'var'} && $config{storageAuto}) {
    AI::queue("storageAuto", {forcedBySell => 1});
} elsif (!$ai_v{'temp'}{'var2'} && $config{storageAuto}) {
    AI::queue("storageAuto", {forcedByBuy => 1});
}

###### Affected configuration(s)/ file(s):

> CoreLogic.pm
> AI.pm

###### Impact: 
possible looping bug

###### Expected Behavior: 
Autostorage\Autosell\AutoBuy start by AI without force

###### Actual Behavior: 
All tasks force each other to begin.

###### Steps to Reproduce:
just debug and try to sell,buy or store by AI

**Comment by c4c1n6kr3m1** [comment]
i only use autostorage , and too lazy to try autosell autobuy
what's the difference splitting the function or not ? what kind looping bug ?
what if making the order as an option ? if i use all of them, i will sell first, than store , than buy. But different people have different need

**Comment by koynro** [comment]
I'd like to see an order option as well. That would most ideal.

**Comment by rhan4x** [comment]
![untitled](https://user-images.githubusercontent.com/30954281/29240818-e36e83ee-7f96-11e7-9f42-efdb662a7d6e.jpg)


Ayo gan pembeli yg di atas ajah udah ane bantu via teamviewer agan yg lain mana!!

Ayo gan sumber botnya langsung cuman di www.rhanfelta.blogspot.com think smart gan dari pada beli zeny mahal-mahal mending stock sendiri ajah gan bisa jualan zeny sendiri juga lagi, dari pada bayar jasa joki mahal cuman dpt 1 char mending pake bot bisa bikin char lvl 99 100ID++ dalam 1 pc dalam waktu singkat.

Ayo gan mumpung masih ada promo khusus buat agan 1x lagi. sebelum harga promonya expired mumpung murah gan ayoo join di www.rhanfelta.blogspot.com bot ragnarok bergaransi aman sumbernya langsung harga murah cuman buat agan.

update ane baru beli hp baru hp lama masih di ugd jadi udah bisa terima tlp sms lagi yg berminat contact ane ajah langsung.

081380644602 / visit www.rhanfelta.blogspot.com

**Comment by zxc4xa** [comment]
Update Bukti 14 Agustus 2017 Setelah Mainatnce Still Works:
![14 agustus 2017 after mt](https://user-images.githubusercontent.com/30999621/29262785-46da9098-8100-11e7-836a-8df8028d6b08.jpg)

Beli Zeny Mahal? Jasa Joki per ID Muahaalll bangeet? mending join ajah gan di www.rhanfelta.blogspot.com lebih dari puluhan orang udah Join, Jadilah Smart Gamer gan dengan join di rhanfelta bisa stock zeny sendiri gak perlu beli lagi sama orang bahkan bisa jualan zeny sendiri. agan pun bisa bikin 100ID++ lvl99 dalam 1PC dengan waktu singkat come on gan think smart!!

buruan gan mumpung masih ada slot promo cuman untuk agan!!

Visit : www.rhanfelta.blogspot.com
Contact: 081380644602

**Comment by Homomorphic** [comment]
Not sure if this is related but since downloading the most recent update (i.e. dd66dd7c901fbb5f087ee0ff5875176dbb58bc6d) my bots have an infinite loop bug. 

When they get overweight or respawn they automatically start the buy/sell/store routine, which is what I want. However, they don't ever finish the routine. Instead they just infinitely loop between selling and storing until the kafra eventually eats all their zeny.

The same config worked just fine before the update. Maybe the issue you're pointing out here has created this bug?

Here is the relevant part of my `config.txt`:

```
sellAuto 1
sellAuto_npc payon_in02 87 34
sellAuto_standpoint payon_in02 82 41
sellAuto_distance 5
sellAuto_npc_steps s

storageAuto 1
storageAuto_npc pay_arche 55 123
storageAuto_distance 5
storageAuto_npc_type 3
storageAuto_npc_steps c r0 n
storageAuto_password
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 100
```
I can't for the life of me figure out what's wrong. I'm about to write my own macro to toggle them on/off one at a time so that this infinite loop goes away... being able to store and sell is pretty much essential for what I'm doing.

**Comment by lututui** [comment]
@Homomorphic Did you update your timeouts.txt? There are several new keys regarding storage/sell/buy

https://github.com/OpenKore/openkore/commit/dd66dd7c901fbb5f087ee0ff5875176dbb58bc6d#diff-542f08fdaa211722f8f3d071e2cbcabc
