### ISSUE TITLE
eventMacro Condition InInventoryID not working properly

### ISSUE THREAD

**Issue by Nipodemos** [OpenKore/openkore#906]
###### Summary: 
Sometimes, in random moments, the InInventoryID condition doesn't word well. Especially if it's cheking if there is 0 of the item
###### Affected configuration(s)/ file(s):
```
automacro EdenJoinMoveNpc {
	InInventoryID 6219 = 0
	exclusive 1
	BaseLevel >= 12
	NpcNotNear /Lenore|Lime/
	JobIDNot 0
	run-once 1
	call {
		do move moc_para01 &rand(33,35) &rand(25,27) 
	}
}
```
###### Impact:
This macro keeps running everytime (obsviosly respecting the run-once 1) even when has 1 of the item.
###### Expected Behavior:
Don't do nothing if item quantity is bigger than 0

**Comment by moneyisgod** [comment]
Try ==

**Comment by Nipodemos** [comment]
i'll try, thanks for the tip
@moneyisgod
