### ISSUE TITLE
Bot can't find way back to Morocc from moc_fild16

### ISSUE THREAD

**Issue by pudup** [OpenKore/openkore#912]
Bot keeps running back and forth between moc_fild15 and moc_fild16 and never makes it back to morocc for autostorage. Found some fixes online that said to use an old portals.txt file but all the links to it are outdated and I can't find it.

**Comment by lututui** [comment]
Which server?

**Comment by pudup** [comment]
Re:start

**Comment by zxc4xa** [comment]
Update Bukti 14 Agustus 2017 Setelah Mainatnce Still Works:
![14 agustus 2017 after mt](https://user-images.githubusercontent.com/30999621/29262785-46da9098-8100-11e7-836a-8df8028d6b08.jpg)

Beli Zeny Mahal? Jasa Joki per ID Muahaalll bangeet? mending join ajah gan di www.rhanfelta.blogspot.com lebih dari puluhan orang udah Join, Jadilah Smart Gamer gan dengan join di rhanfelta bisa stock zeny sendiri gak perlu beli lagi sama orang bahkan bisa jualan zeny sendiri. agan pun bisa bikin 100ID++ lvl99 dalam 1PC dengan waktu singkat come on gan think smart!!

buruan gan mumpung masih ada slot promo cuman untuk agan!!

Visit : www.rhanfelta.blogspot.com
Contact: 081380644602

**Comment by alisonrag** [comment]
Maybe update in #787

**Comment by ChrstphrR** [comment]
Closing this issue - more detail on the problem can be found in #787 as alisonrag mentioned.
