### ISSUE TITLE
auto Storage Kafra VIP help plz what is config?

### ISSUE THREAD

**Issue by Jeffgomz** [OpenKore/openkore#917]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by alisonrag** [comment]
storageAuto 1
storageAuto_npc **MAP XX YY**
storageAuto_distance 5
storageAuto_npc_type 3
storageAuto_npc_steps c r1 r0 n
storageAuto_password **PASSWORD**
storageEncryptKey
storageAuto_keepOpen 0
storageAuto_useChatCommand
storageAuto_notAfterDeath
relogAfterStorage 0
minStorageZeny 50

**Comment by pussbacon** [comment]
I have the same issue: Re:start there is a vip storage in which the bot have to choose whether use regular or vip storage

**Comment by Nipodemos** [comment]
storageAuto_npc_type 3
storageAuto_npc_steps c r1 r0 n
these lines that alisonrag showed, it will make work
