### ISSUE TITLE
pRO Character doesnt move (Ghost)

### ISSUE THREAD

**Issue by mhakulit** [OpenKore/openkore#918]
![image](https://user-images.githubusercontent.com/30317087/29248306-70e72536-8047-11e7-9058-9a0ad5fccd10.png)

![image](https://user-images.githubusercontent.com/30317087/29248297-3ac6ac06-8047-11e7-9bef-d8de4872f51b.png)

can someone help me to fix this problem ?
is this a recvpackets issue ?

**Comment by mhakulit** [comment]
@lututui hi sir can you help me with this problem ?

**Comment by romcel11** [comment]
As of now, there is no (official) smoothly working BOT for phRO.
Mos of us are (patiently) waiting for an official release.

**Comment by zxc4xa** [comment]
Update Bukti 14 Agustus 2017 Setelah Mainatnce Still Works:
![14 agustus 2017 after mt](https://user-images.githubusercontent.com/30999621/29262785-46da9098-8100-11e7-836a-8df8028d6b08.jpg)

Beli Zeny Mahal? Jasa Joki per ID Muahaalll bangeet? mending join ajah gan di www.rhanfelta.blogspot.com lebih dari puluhan orang udah Join, Jadilah Smart Gamer gan dengan join di rhanfelta bisa stock zeny sendiri gak perlu beli lagi sama orang bahkan bisa jualan zeny sendiri. agan pun bisa bikin 100ID++ lvl99 dalam 1PC dengan waktu singkat come on gan think smart!!

buruan gan mumpung masih ada slot promo cuman untuk agan!!

Visit : www.rhanfelta.blogspot.com
Contact: 081380644602

**Comment by zzzzllopob** [comment]
Bot is real ^_^
dami na ko nakikita bot user hahaha,,
sa pag galaw plang halata na
