### ISSUE TITLE
Help with this screen...

### ISSUE THREAD

**Issue by Crusnik05** [OpenKore/openkore#922]
Is it just mine that bugged, and show so much that message on openkore?
![untitled](https://user-images.githubusercontent.com/31002739/29266864-77aa5040-8110-11e7-8ccd-bab58207f8a1.png)

**Comment by alisonrag** [comment]
paste your config.txt just to try to reproduce

**Comment by Crusnik05** [comment]
nope, i use original timeout
just for config i use custom with plugins

Suddenly after update this bug come out.. lol

**Comment by lututui** [comment]
Did you update your timeouts.txt? It has a new key

**Comment by alisonrag** [comment]
I think you are using a plugin or maybe a macro to share, in AI if we spam he warning us with a error on console

**Comment by Crusnik05** [comment]
ah ok i try to fix that.. thx anyway..
