### ISSUE TITLE
Bot sometimes get 'stuck' in cities

### ISSUE THREAD

**Issue by b4po** [OpenKore/openkore#927]
I'm using the latest release and sometimes after death my bot stuck and can't find route. I tried clearing the AI, teleporting, relog, moving to other map and nothing work except restarting the bot.

The error text is broken too.  Now it just say "Cannot calculate a route from Geffen (120,39) to " just blank no destination

**Comment by k1nt4r0** [comment]
try reload portal.txt?

**Comment by b4po** [comment]
Tried reloading portal and same result. Still need to restart the bot. I just noticed this happen after the bot think portal is not there which it is and worked fine.

**Comment by ChrstphrR** [comment]
*Less helpful ranting about low-quality issues*
Without proper information about what version of Openkore, what OS, what server you're using, we can only guess that you've managed to compile Openkore onto grandpa's VIC-20, and are trying to win at Space Invaders, not play on a RO server.  At least, that's the guess I'm going to make at the moment.

*Helpful stuff (or, how I ask questions that will make you have to do stuff to help tell us more so maybe we could help you):*

Try using the official GUI client on the same warp/map to see what's really happening?
You can use /where to find out sorta-kinda what the portal coordinates are, and you can see if the portal has moved, or if there's a dialog/menu warp that is triggered.

Also, you give little to no information about what you're using (which version of Openkore?  have you used "version" to detail which build you're using?  had you tried backing up your account/control files, and updating Openkore to see if the problem resolves?  Did you tell us which "version" you updated to?
(Seriously, this *version* thing is a command you can type when using openkore, and it tells you stuff that might help us help you)

I want to help more, and have my suspicions about what is actually transpiring, but I refuse to beg for information that should be laid out in your first or second posting in the issue.  Also, your issue title was well chosen.

**Comment by ChrstphrR** [comment]
On reviewing other issues, you should read #787 @b4po  as it has more detail about code fixes, and user side fixes that deal with this problem.   

Closing this one as a duplicate, follow up in #787 please.
