### ISSUE TITLE
Kore dc when autobuy

### ISSUE THREAD

**Issue by k1nt4r0** [OpenKore/openkore#928]
@alisonrag @allanon @kaliwanagan @Henrybk
i just update my openkore today from openkore master github
and after update my bot run like ussually
but when the kore die and doing autobuy, it just say
`Done talking with the NPC.`
and got dc for 30s

any idea?

**Comment by oleokoong** [comment]
maybe related to relogafterstorage?

**Comment by k1nt4r0** [comment]
i dont think so, i try to active it and deactive it but still same,
when talk to tool dealer for buying items
the list of items is printed out, but after it
`Done talking with the NPC.`
and dc after about 2s.

**Comment by Henrybk** [comment]
Which server?

**Comment by k1nt4r0** [comment]
@Henrybk iro restart sir

**Comment by Nipodemos** [comment]
you shoul've put in npc the coordinates
The npc you trying to autobuy sell these three itens?

**Comment by k1nt4r0** [comment]
i did it, i just delete it for some reason
if i dont put the npc location, i cant say it dc on autobuy sir @Nipodemos

**Comment by alisonrag** [comment]
The npc you trying to autobuy sell these three itens?

**Comment by k1nt4r0** [comment]
yes, before i update the OK its work fine
after update it cant buy and got dc

**Comment by lututui** [comment]
Did you update your timeouts.txt?

**Comment by k1nt4r0** [comment]
@lututui yes, i update with the last complete rework
timeout.txt and everything posted on there i update it

**Comment by RogerKitKat** [comment]
My test openkore updated 08/16/2017
![test](https://user-images.githubusercontent.com/31075137/29374823-32a087ce-8289-11e7-810b-7f6f747c9549.jpg)

**Comment by k1nt4r0** [comment]
i just open my github desktop and i got new fetch item, if it still not working i will try to re-clone it
thx sir @RogerKitKat

**Comment by dv2y** [comment]
I'm still having problems with buyAuto. Character go to spawn, do autostorage, do autosell and just freezes. The only way o found correct that is to send "ai clear" on the console.

**Comment by k1nt4r0** [comment]
i just try it, and still same.
dc when buying

**Comment by alisonrag** [comment]
continue in #1006
