### ISSUE TITLE
Char Deletion

### ISSUE THREAD

**Issue by cydh** [OpenKore/openkore#93]
Afaik, the 'new' char deletion (that u request first, then get the deletion date) needs new delete packet. Can't get info from current kore.

So this is the packet that sends by client (from @rAthena)
````
<0829>.W <char id>.L <birth date:YYMMDD>.6B
````
the **birthdate**, may becomes email or another code depends on server's policy

**Comment by cydh** [comment]
I have this thing done @_@

**Comment by c4c1n6kr3m1** [comment]
i don't know about  0829
but iro use 098F and the length depend your data
