### ISSUE TITLE
Thief mushroom

### ISSUE THREAD

**Issue by pussbacon** [OpenKore/openkore#931]
Re:start
I'm trying to farm the mushroom for thief quest but my bot doesn't wanna attack the mushroom I tried putting on mon_control as Thief Mushroom 1 1 1 also removing all mushroom that has 0 0 0 it didn't work. Thanks in advance

**Comment by oleokoong** [comment]
Which server ? Make sure your monsters name is correct... I think it should be Mushroom

**Comment by ristrettojoe1** [comment]
Or you could attack all except those you don't want to:
Spore 0 0
Chonchon 0 0
Fabre 0 0
