### ISSUE TITLE
Ragnarok Re: Start Error Code 22 when reconneting

### ISSUE THREAD

**Issue by sparda824** [OpenKore/openkore#935]
Bot running for 2 hours+ then it auto disconnect but openkore could not reconnect having an error code 22 (openkore keeps on reconnecting but it always fail). Upon research it appears that it is a server configuration issue. Last week I don't have this problem. Did the Mods change their server configuration? If so, can someone provide me the new server info for restart? Thanks and god bless.

**Comment by lututui** [comment]
All server configuration is made on tables/servers.txt.

If any src was changed, and those changes affect iRO RE, you should update your openkore clone
