### ISSUE TITLE
Openkore not responding when opening second wxstart for multibot

### ISSUE THREAD

**Issue by koburaaa** [OpenKore/openkore#939]
the title says whats my problem, need help

**Comment by ChrstphrR** [comment]
Please bother to give details about your issue.    We are not dentists nor CIA operatives: we will not pull teeth one by one to get answers.

If you do not reply in a timely fashion, with proper and constructive details that will explain your problem you are experiencing, AND the means to recreate it, this issue will be closed.

**Comment by alisonrag** [comment]
Any updates?

**Comment by ChrstphrR** [comment]
Duplicate issue from the same user... leaving the original ticket open because OP bothered to detail more info there, but not follow up ( issue #875 )
