### ISSUE TITLE
"The server denied your connection for unknown reason". I appreciate any help

### ISSUE THREAD

**Issue by pidyong** [OpenKore/openkore#940]
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
* Check if an issue already exists for your request
* Please post in English if possible

###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```

**Comment by ChrstphrR** [comment]
If we have to extract every bit of info from you like pulling teeth on by one, this issue will be closed for lack of information.

Please actually fill out relevant portions of the template!
