### ISSUE TITLE
Auto Storage issues

### ISSUE THREAD

**Issue by pussbacon** [OpenKore/openkore#941]
So I have this item(novice potion) in which it's not storageable my bot keeps dcing when he tries to put it inside the storage I'm sure that the storage isn't full one more thing is on my second account when storaging not trash is not getting placed inside the storage please help me.
below is the example of the error
There are still steps to be done but the conversation has already ended (current step: r0).

Item added to inventory: Novice Potion (38) x 48 - Usable Heal
Inventory Item Removed: Novice Potion (32) x 48
Unable to store Novice Potion.
Character is still overweight after storageAuto (storage is full?)
Auto disconnecting on StorageFull!

**Comment by Nipodemos** [comment]
There are still steps to be done but the conversation has already ended (current step: r0).
Solution: Configurate 
storageAuto_npc_type 
storageAuto_npc_steps


tem added to inventory: Novice Potion (38) x 48 - Usable Heal
Inventory Item Removed: Novice Potion (32) x 48
Unable to store Novice Potion.
Solution: update openkore, this issue eis already solved.

**Comment by ChrstphrR** [comment]
A) You are not providing near enough detail for anyone to provide solid help on the issue you're having.
For all we know, you're playing WoW on a sentient potato using Frozbozz OS 193.2

B) Novice Potions on the servers I play on, have zero weight AND are not able to be placed in Storage.  If only we knew what server you were using, to sort your issue further.   Chances are, if you stop botting, and try to store Novice Potions on the same account on the official GUI client, you still will not be able to store your potions.

**Comment by pussbacon** [comment]
Sorry I'm playing Re:Start

**Comment by pussbacon** [comment]
I tried redownloading the whole thing and it came out the same @Nipodemos

**Comment by ChrstphrR** [comment]
Novice Potions on iRO Re:start cannot be put into storage.   Tested and confirmed.

You need to edit your items_control.txt file to keep that item in your inventory.  See that file itself, the comment header explains the format.

As well, you can find a link at our wiki explaining the file format [http://openkore.com/index.php/Items_control.txt](here)

**Comment by pussbacon** [comment]
Thanks everyone
