### ISSUE TITLE
ISVR_DISCONNECT

### ISSUE THREAD

**Issue by bebox123** [OpenKore/openkore#943]
Hi everyone! Anyone knows what does this mean?

**Comment by sctnightcore** [comment]
Do you have pictures? 
 idk -_-

**Comment by Nipodemos** [comment]
give more detais man... 
pictures, when this happen, what you were doing when this message appeared, anything so we can help you

**Comment by bebox123** [comment]
![untitled](https://user-images.githubusercontent.com/30216263/29430304-d60e2404-838b-11e7-8eff-5f7b1e17b536.png)

**Comment by sctnightcore** [comment]
server iRO ?

**Comment by bebox123** [comment]
Hi! Yeah, after the update yesterday that happened out of nowhere.

**Comment by bebox123** [comment]
And another issue is that sometimes my character won't attack the monster but when I try to relog it it is still in the map and the character will automatically attack the monster who attack him previously.

**Comment by sctnightcore** [comment]
@allanon  @Henrybk

**Comment by bebox123** [comment]
Actually i'm using the new openkore now and after the update yesterday that happened.

**Comment by sctnightcore** [comment]
![05](https://user-images.githubusercontent.com/23263315/29434147-109416a2-83cc-11e7-86b8-41fd581bff0c.PNG)
normal

**Comment by bebox123** [comment]
Sometimes it just shows off out of nowhere then my bot will slightly be disconnected then connect again. I don't know why.

**Comment by bebox123** [comment]
And it keeps on "You tried too long to move"

**Comment by bebox123** [comment]
![untitled](https://user-images.githubusercontent.com/30216263/29434467-0025b25c-839b-11e7-92b7-4a62a75407b6.png)
Still fresh just right now this happened.

**Comment by kaliwanagan** [comment]
Please follow the issue template.
