### ISSUE TITLE
Error while bot on same maps

### ISSUE THREAD

**Issue by sogen12** [OpenKore/openkore#947]
Hello, i get error while using openkore (bot) on some maps, here is the error: 
Error message:
Can't call method "baseName" on an undefined value at src/Network/Receive.pm line 526.

Stack trace:
Can't call method "baseName" on an undefined value at src/Network/Receive.pm line 526.
 at src/Network/Receive.pm line 526
	Network::Receive::actor_display called at src/Network/Receive.pm line 381
	Network::Receive::actor_display_compatibility('Network::Receive::iRO=HASH(0x614573c)', 'HASH(0x659c68c)') called at src/Network/PacketParser.pm line 275
	Network::PacketParser::parse('Network::Receive::iRO=HASH(0x614573c)', '\x{dd}\x{9}\\x{0}\x{6}l\x{c5}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0},\x{1}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}-\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{4}\x{8a}...', 'Network::Receive::iRO=HASH(0x614573c)') called at src/Network/Receive.pm line 137
	Network::Receive::parse('Network::Receive::iRO=HASH(0x614573c)', '\x{dd}\x{9}\\x{0}\x{6}l\x{c5}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0},\x{1}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}-\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{4}\x{8a}...', 'Network::Receive::iRO=HASH(0x614573c)') called at src/Network/PacketParser.pm line 409
	Network::PacketParser::process('Network::Receive::iRO=HASH(0x614573c)', 'Network::MessageTokenizer=HASH(0x38ea654)', 'Network::Receive::iRO=HASH(0x614573c)') called at src/functions.pl line 734
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x48add7c)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  			$actor->{appear_time} = time;
* 			my $exists = portalExists($field->baseName, \%coordsTo);
  			$actor->{source}{map} = $field->baseName;

and this one : 
Error message:
Can't call method "isCity" on an undefined value at src/AI/CoreLogic.pm line 3094.

Stack trace:
Can't call method "isCity" on an undefined value at src/AI/CoreLogic.pm line 3094.
 at src/AI/CoreLogic.pm line 3094
	AI::CoreLogic::processDcOnPlayer() called at src/AI/CoreLogic.pm line 121
	AI::CoreLogic::iterate() called at src/functions.pl line 769
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x49ca864)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	# Disconnect when a player is detected
* 	if (!$field->isCity && !AI::inQueue("storageAuto", "buyAuto") && $config{dcOnPlayer}
  		&& ($config{'lockMap'} eq "" || $field->baseName eq $config{'lockMap'})

I got this error when i tried to bot on Lasagna Dungeon ( New city of Doram's race), before this i think its just the new field which dont registered on Openkore, but after i look on fields folder there's a file Lasa_dun0x.rar and i extract it and become .fld, i think the problem's solved but its nothing, anyone know to fix this ? Thx in Advance.

**Comment by sctnightcore** [comment]
new map ? 
http://openkore.com/index.php/FLD_Creation_Guide

**Comment by sogen12** [comment]
Thats not the new map because in the field's folder, there's have the map file on EP15.1 (lasa_dun02.fld) and many more, Thx,

**Comment by sogen12** [comment]
If u look on Filed's Folder of the Openkore, There's have all maps with .fld and we dont need to create the new.fld because if we extract the file we have the new maps with .fld. So i think we dont to create the .fld again because there's not file with .gat or .rsw file.

**Comment by kaliwanagan** [comment]
You didn't even bother filling out the template. Why would we want to help you?
