### ISSUE TITLE
Create a ServerType

### ISSUE THREAD

**Issue by k1nt4r0** [OpenKore/openkore#948]
Can anyone teach or give a tutorial how to make a servertype?

**Comment by sctnightcore** [comment]
-_- 
You have to study by yourself.
If you need servertybe, I can create one.

@moneyisgod

**Comment by k1nt4r0** [comment]
ohh, for the truth i just wanna learn haha
the last servertype of 2017 that u tell me isnt work

**Comment by sctnightcore** [comment]
The receiving packet also has a problem. 
I think we should gradually do so from 2016 to 2017.
Now 20130513 also has a problem where rev is.

And the biggest problem is. "No servers to test"

**Comment by k1nt4r0** [comment]
which servertype u need to test?
i will help u to find
i see a server with 2016 sT needed to bot (Feb 1, 2016)
i just see it today,  the other problem of 2017 sT haha

**Comment by sctnightcore** [comment]
I want to help but I'm not busy
wait @moneyisgod

**Comment by k1nt4r0** [comment]
okay 👍

**Comment by kaliwanagan** [comment]
Closed for now, better ask this in the forums instead.
