### ISSUE TITLE
Re:Start Unhandled Packet: 02D5 Handler: ISVR_DISCONNECT

### ISSUE THREAD

**Issue by Zelecktor** [OpenKore/openkore#950]
An issue in iRO Re:start

Sometimes it appears this message
Packet Parser: Unhandled Packet: 02D5 Handler: ISVR_DISCONNECT

produces like a 5seconds lag and then all normal, sometimes produces disconect and error to synchronize to server with high ping (over 100ms) bots.
I downloaded the latest review (like 2hours ago to post this)

**Comment by sctnightcore** [comment]
![05](https://user-images.githubusercontent.com/23263315/29475552-70bbf5ae-848a-11e7-81ce-d552385edd87.PNG)
normal

**Comment by Zelecktor** [comment]
keep watching. It is normal for me too.
It appears sometimes, specially on lagged maps such payon or geffen.
