### ISSUE TITLE
We need to bot on Re:Start ASAP!

### ISSUE THREAD

**Issue by Zelecktor** [OpenKore/openkore#953]
As the title. The bot connects but in the last step of select character it disconect for an unknown reason. It seems like all ok but no conection on the character select.

On the maintenance i suspect a hidden packet that works as a key for log in. If some people wants to help, i can try to get all packets and compare it with the existent recvpackets and the iRO serverType.

**Comment by yoikodomo** [comment]
Actually, it select char is working and connecting. The problem is disconnection to Map Server.
![untitled](https://user-images.githubusercontent.com/29862118/29482257-bf01755a-84c0-11e7-88ea-2c5f8d0be742.png)

**Comment by michaelmagro** [comment]
Same problem here..

**Comment by sctnightcore** [comment]
well, @allanon

**Comment by friky2017** [comment]
I have the same problem, please say to me how repair this, help me please, thanks

**Comment by Mustardfreedom** [comment]
iRO has a new anti-botting shield implemented now. You will likely not be botting for some time, unless of course you are able to bypass the shield yourself.

**Comment by yoikodomo** [comment]
It's a bot. You bot your "not so important" account. I thought that's a common sense. But hey, thanks for calling us "retarded". Appreciate it.

**Comment by alphonse9** [comment]
calm down, we are here to help each other.

**Comment by Zelecktor** [comment]
@Mustardfreedom

> you are able to bypass the shield yourself

We are a comunity, we should help each others to bot, thats why we are here. In stead you should not use this repository. We will find the way to come back.

**Comment by kiuerty** [comment]
can i post that guy ID in  warportal forum? ahaha

**Comment by Mustardfreedom** [comment]
Yeah its a bot, but it still links that bot and all other accounts that you've logged on with from that IP address together.

**Comment by floydqwerty** [comment]
As long as it is connected to the game this will be more easier to dev team. seems like they just added a few hidden packets. I logged in after the maintenance and I think there is around 20MB or 200MB patch not sure is the size.

**Comment by Zelecktor** [comment]
It if difficult to see what they updated in game because there are compiled files.  Im pretty sure to get the hidden packets and see if they fix the problem.

**Comment by sctnightcore** [comment]
#955

**Comment by sctnightcore** [comment]
#955

**Comment by wolventear** [comment]
any update guys?. stuck on reconnecting to account server.

**Comment by sctnightcore** [comment]
WAIT !  WAIT !  WAIT !  WAIT !  WAIT !  WAIT !  

ok ?

**Comment by RevalEnna** [comment]
Just... openkore will fix it...

**Comment by RevalEnna** [comment]
Just wait... openkore will fix it...

**Comment by wolventear** [comment]
ahahaha..ok thanks sctnightcore......

**Comment by rrtsfarm** [comment]
yes lets wait, will be back in no time

**Comment by bertnunez** [comment]
Any update please.

**Comment by oleokoong** [comment]
Just hit subscribe and Wait OK?

**Comment by egugz** [comment]
Wahaha~ sometimes it's not easy to fix the problem. So we need to wait and trust to them.

**Comment by MasterPogi26** [comment]
Wahaha~ sometimes it's not easy to fix the problem. So we need to wait and trust to them. :)

**Comment by brylle0714** [comment]
best thing we do is wait! 👍

**Comment by ade182** [comment]
Did you guys have a discord or something , i really want to help.
Or could someone make a discord for this thing ?

**Comment by johnnyandrean** [comment]
looks like ragial already bypassed the new antibot system 👍

**Comment by wolfeye29** [comment]
how?

**Comment by Freakazoid0731** [comment]
any updates?

**Comment by tungbach1990** [comment]
I can log in game but cant do anything and get reconnect. Any know solution ?

**Comment by kenneth543** [comment]
aw bat ni delete ung mga comment sir ?

**Comment by zenzumie** [comment]
May nakakapagpagana na po, ang prob binura ung comment

**Comment by arfelgabani** [comment]
please share us here 

thnx

**Comment by alphonse9** [comment]
I think we should decrypt some packets and edit the send.pm i guess?

**Comment by arfelgabani** [comment]
why deleted the comments?

**Comment by MasterPogi26** [comment]
What happened to the problem? solve it or not already finish? :) I'm just asking :) thankz :)

**Comment by BatangKuneho** [comment]
got problem on map server automatically disconnected when got in into the map and reconnected in 60mins anyone solve this one ☝️

**Comment by alisonrag** [comment]
only comments with solution or tips will be accepted

**Comment by sinser** [comment]
is the problem solved ? i saw that the file have updated 10hours ago .....

**Comment by boom19** [comment]
then I guess all the changes would be on the src folder right?

**Comment by Moonslash13** [comment]
The problem is not solved yet, downloaded the most the most updated files, used it. Got into the server for 1 sec, character got disconnected immediately after. Tried to login manually and there was a popup saying, detected illegal use of program etc etc.

**Comment by Mustardfreedom** [comment]
Ragi.al is already up and running, you guys need to step your game up.

**Comment by ade182** [comment]
I need to know the progress , i really want to help but didnt know where to start

**Comment by kaliwanagan** [comment]
I'm temporarily limiting access to github only to those developers (if your name can be found anywhere in the contributor list in github, then you're considered a dev).

Behave kids. Remember the lessons of the marshmallow test.

**Comment by Zelecktor** [comment]
I make this rework and you may log in and bot normally, but it have some bugs on storage and some timeouts. Use it at your own risk you may get banned for 1hour if you run multiples bots (5 or more)

[Openkore Restart Working.zip](https://github.com/OpenKore/openkore/files/1237443/Openkore.Restart.Working.zip)

**Comment by ChrstphrR** [comment]
For the people wanting to know progress on connectivity to the iRO Re:Start server, you *may* want to poke around with this branch:

https://github.com/OpenKore/openkore/tree/iro_restart_packet_changes

Keep in mind, it IS a work in progress, and it IS experimental.  Use at your own risk.  Look both ways before crossing the street, etc., etc.

**Comment by Zelecktor** [comment]
> For the people wanting to know progress on connectivity to the iRO Re:Start server, you may want to poke around with this branch:

https://github.com/OpenKore/openkore/tree/iro_restart_packet_changes

Keep in mind, it IS a work in progress, and it IS experimental. Use at your own risk. Look both ways before crossing the street, etc., etc.

Ohhh i didnt see that branch. I tried to fix it by my own. Thanks for sharing

**Comment by bebox123** [comment]
Hi all!
Just wanted to share this, it does walk after death ( respawn ) but after a few seconds/minutes it will just stay on a random coordinates like 57,61 then just stay there for the rest of his life lol. I typed ai and ai clear in console = nothing happened. It will only move once an aggressive monster is approaching but without aggressive monsters = stucked. Sometimes it doesn't attack even if in mon_control.txt it is set to all 2.


![image](https://user-images.githubusercontent.com/30216263/29500118-656a9c1e-8615-11e7-8c56-4634abd323ad.png)

**Comment by LeHartx** [comment]
I tried running multiple .exe's and 1 of them has the error message of illegal programme detected.

**Comment by jepejepe** [comment]
![a](https://user-images.githubusercontent.com/31201253/29506084-6af4fae6-867c-11e7-8295-3b61c7905a19.PNG)

I downloaded the zip file from the iro restart packets branch just above. I copied the server.txt info and config.txt from my previous openkore files. Am I missing anything? Why is it still doing timeouts?

**Comment by kaliwanagan** [comment]
Before complaining that kore doesn't work, make sure you first see if you can actually connect with the original client.

iRO Restart seems to be very unstable for some reason.

**Comment by oleokoong** [comment]
@jepejepe  if you dont know what has been change in the github.. please run the bot without any previos file.
In this cases server.txt has been updated.

#Re:Start
# http://playragnarok.com
[International - iRO: Re:Start]
ip 128.241.92.133
port 6800
version 18
master_version 1
serverType iRO_Restart
addTableFolders iRO/Restart;iRO
serverEncoding Western
charBlockSize 145
patchserver ropatch1.gravityus.com
patchpath /repatch
sendCryptKeys 0x42780CC0, 0x67F86D28, 0x1CEB0ADC

**Comment by jepejepe** [comment]
@oleokoong yes i saw that was my mistake, i didnt see those settings since the upper most one was the bRO lol. much thanks :)

**Comment by kenneth543** [comment]
why i cannot connect ?

**Comment by MasterPogi26** [comment]
Please check this error

![untitled](https://user-images.githubusercontent.com/31151811/29508995-4917e7de-865f-11e7-916e-ac512c6ed488.png)

**Comment by rakistangpup** [comment]
![1](https://user-images.githubusercontent.com/21187231/29510077-24a018b2-868d-11e7-8e62-6f917def71b4.png)


Was able to connect, but after connecting to map, within half sec it was disconnected? Can anyone help me?

**Comment by phamtrong204** [comment]
@kaliwanagan I think it will be better when limiting comment for this issue!
Thanks.
<img width="629" alt="screen shot 2017-08-21 at 15 25 39" src="https://user-images.githubusercontent.com/6489256/29510270-6518c39c-8685-11e7-8730-00325505541f.png">

**Comment by wolventear** [comment]
same problem here. please help. Gets disconnected after few seconds being connected.

**Comment by kaliwanagan** [comment]
@phamtrong204 sounds good. I think it's mostly spam anyway.

Please continue discussing this in the forums. Better moderation there, and you don't spam everyone else.
