### ISSUE TITLE
Time out Map server

### ISSUE THREAD

**Issue by Jeffgomz** [OpenKore/openkore#954]
Received character ID and Map IP from Character Server
----------Game Info----------
Char ID: 86 65 02 00 (157062)
MAP Name: mjolnir_05.gat
MAP IP: 128.241.92.139
MAP Port: 4507
-----------------------------
Closing connection to Character Server
Disconnecting (128.241.92.138:4500)...disconnected
Connecting to Map Server...
Connecting (128.241.92.139:4507)... connected
Timeout on Map Server, connecting to Account Server...

**Comment by Nipodemos** [comment]
GIVE MORE DETAILS!!!
server?
when that happened?
openkore updated?

if it is re:start, openkore is not working Temporarily, since the server put a new anti-bot feature

**Comment by egugz** [comment]
a

**Comment by egugz** [comment]
a

**Comment by alisonrag** [comment]
iro have one issue yet, just focus ypur attemps here: #953

**Comment by brylle0714** [comment]
we are all in the same problem as of now.. maybe best thing to do is wait for the dev team .
