### ISSUE TITLE
Cant enter fourth character (Charblocksize 145)

### ISSUE THREAD

**Issue by Moonslash13** [OpenKore/openkore#964]
I have downloaded the latest folders for Openkore, when i am choosing my character, my fourth character is not in one of the options

My charblocksize is 145. Can anyone help?

**Comment by lututui** [comment]
server?

**Comment by Moonslash13** [comment]
Sorry didnt add in. Its IRO Restart:Odin server

**Comment by kaliwanagan** [comment]
Closed for now following the issue template.
