### ISSUE TITLE
iRO: ReStart Bot limited to three character selection?

### ISSUE THREAD

**Issue by NoobNeedHelp** [OpenKore/openkore#972]
Hello just wondering if anybody could help me with my problem, I currently have 5 characters on my account and when I run the bot it only give me the option to pick the first three characters on my account. (VIP account on iRO: ReStart).

Downloaded the latest openkore and charblocksize seems to be right.

Thanks :)

**Comment by alisonrag** [comment]
if someone have the same problem just wait for the fix

**Comment by alisonrag** [comment]
brace yourselves fix are coming:
#976
