### ISSUE TITLE
Bot stuck in cities

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#973]
Re:Start

This happened prior to the recent anti bot patch and still happens now.  Prior to the patch the bots would use kafra and the tool dealer in morocc then sit there spamming cannot calculate route.  I would either have to reload all or have the bot relog to fix this.  Sometimes i would even have to manually walk the bot myself.

My bots aren't high enough to be at the morocc part of my line up yet but this is currently happening in geffen.  They are going to the eastern kafra to store and then spamming cannot calculate route and just sitting there.  They also get stuck inside by the geffen tool dealer and don't really even attempt to calculate or anything.  I am running them in wxstart and the bot thats stuck inside geffen isn't even responsive to move commands either.

> Ready to start selling items
> Done talking with NPC Tool Dealer (0).
> Inventory Item Removed: Jellopy (6) x 1
> You gained 3 zeny.
> Inventory Item Removed: Fluff (7) x 1
> You gained 4 zeny.
> Inventory Item Removed: Sticky Mucus (8) x 145
> You gained 5,075 zeny.
> Inventory Item Removed: Powder of Butterfly (9) x 348
> You gained 15,660 zeny.
> Achievement 220030 added or updated.
> Inventory Item Removed: Snail's Shell (10) x 240
> You gained 7,680 zeny.
> [macro] automacro buysword2 triggered.
> Calculating route to: Izlude Town(izlude): 109, 151
> Inventory Item Removed: Garlet (11) x 96
> You gained 1,920 zeny.
> Inventory Item Removed: Iron Ore (12) x 5
> You gained 125 zeny.
> Inventory Item Removed: Shell (13) x 114
> You gained 798 zeny.
> Inventory Item Removed: Flower (14) x 29
> You gained 29 zeny.
> Inventory Item Removed: Green Herb (15) x 11
> You gained 55 zeny.
> Sell completed.
> Map Change: geffen_in.gat (70, 146)
> Map Change: geffen.gat (46, 88)
> Auto-buy: Red Potion
> Calculating auto-buy route to: Inside Geffen (geffen_in): 77, 167
> Map Change: geffen_in.gat (70, 138)
> Map Change: geffen_in.gat (70, 161)
> -------------- Store List (Tool Dealer) --------------
> #  Name                    Type                  Price
> 0  Arrow                   Arrow                    1z
> 1  Magnifier               Usable Special          40z
> 2  Red Potion              Usable Heal             50z
> 3  Orange Potion           Usable Heal            200z
> 4  Yellow potion           Usable Heal            550z
> 5  White Potion            Usable Heal           1200z
> 6  Green Potion            Usable Heal             40z
> 7  Concentration Potion    Usable Special         800z
> 8  Awakening Potion        Usable Special        1500z
> 9  Fly Wing                Usable Special          60z
> 10 Butterfly Wing          Usable Special         300z
> 11 Grampa Beard            Armor                 5000z
> ------------------------------------------------------
> Calculating route to: Inside Izlude(izlude_in): 68, 123
> Stuck at geffen_in (75,169), while walking from (75,169) to (70,158). Teleporting to unstuck.
> Stuck during route.
> Talking to NPC at (60, 127) using sequence: b b12,1 n
> Could not find an NPC at location (60,127).
> No such non-equipped Inventory Item: Bastard Sword [2]
> The NPC did not respond.
> Npc did not respond.
> Calculating auto-storage route to: Geffen(geffen): 203, 123

`

Here you can see it sold, triggered a macro to buy a weapon in inzlude, couldn't even make it out of the building and has since just been sitting here.  Reloading all did nothing and its unresponsive to move commands so i had to relog it to get it moving again.  As i mentioned in another report, it seems like the condition for autobuy/sell n such to trigger has been changed recently and it now goes off in the middle of macros which i suspect might be the cause of the problem this time, but there aren't any macros going off the other 10 times ive had to move these bots manually to get them on their lockmap.]

EDIT:
Now the very same bot is stuck in a endless storage/autosell loot.  It goes n does storage, then goes to sell even though there is nothing to sell or store and keeps repeating.  I feel like there is a serious problem with the recent npc buy updates.

**Comment by bebox123** [comment]
Try downloading again the updated one. Sometimes it really does have errors when you manually update it, well I experience it though.

**Comment by Zexeta** [comment]
Now the bot also got stuck inside prontera at the tool dealer a reload all fixed it.  Seems to be happening very often with NPC interaction.

**Comment by ChrstphrR** [comment]
Have you tried checking the portal locations actual locations manually ("portals" at the console in Openkore, or by sight with the official client using "/where"), and checking those vs the locations you have set for the same NPCs.

It's common for GMs and admins to change the NPC (portals are a special case, but are NPCs too) locations slightly to cause grief with bots, or watch behaviour to ban bots.  This could be happening on the *unknownunstatedserver* you are on.

**Comment by Zexeta** [comment]
I can check the portals when the servers come back up but i dont suspect they have anything to do with it.  The bot gets stuck at the kafra in geffen when its route takes it the entire way across the map to the opposite side.  I assume it would run into this stuck problem near the portal if they were the problem yes?  When i look at their location inside geffen_in and prt_in they are stuck right beside the tool dealer and don't even make an effort to move to the portal.

**Comment by Zexeta** [comment]
There is something all around screwy with the routing of the bot since the update to counter the anti bot protection.  Now the bot trying to get to orcsdun is loop porting to payon, back to pront, back to payon.  

prontera 146 89 izlude 94 103 2000 c r2 c r0
prontera 146 89 geffen 120 39 2000 c r2 c r1
prontera 146 89 payon 161 58 2000 c r2 c r2
prontera 146 89 morocc 156 47 2000 c r2 c r3
prontera 146 89 gef_fild10 52 1700 c r2 c r4
prontera 146 89 alberta 117 56 2000 c r2 c r5

That is in my portals which matches the kafra and for some reason its still doing the payon option while calculating a route to orcsdun.

**Comment by alisonrag** [comment]
continue in #1006
