### ISSUE TITLE
Autostorage/Overweight bug

### ISSUE THREAD

**Issue by YuPPing** [OpenKore/openkore#975]
AutStorage doesn't store all items as it suppose to store. Sometimes it opens and closes right away then start going to the **lockMap** (still being over weighted)

Kafra Employee: [Kafra Employee]
Kafra Employee: Welcome. Kafra is always here to help you.
Kafra Employee: How can I help you?
------ Responses (Kafra Employee) ------
#  Response
0  Use Storage Service
1  Use Cart Service
2  Quit
3  Cancel Chat
----------------------------------------
You are again: Overweight 50%
You are again: Overweight 50%
You lost 120 zeny.
Kafra Employee: [Kafra Employee]
Kafra Employee: Here, let me open
Kafra Employee: your Storage for you.
NPC Kafra Employee (0): Done talking
Done talking with NPC Kafra Employee (0).
Calculating lockMap route to: Undersea Tunnel(iz_dun03)
Storage closed.
Storage logged

Please Help~*

**Comment by r421** [comment]
Check your item control
<item name> <minimum> <storage> <sell> <cart add> <cart get>
Jellopy 0 1 <-- Store All Jellopy
Gold 0 0 1 <-- Sell All Gold

**Comment by ncplay91** [comment]
I have the same issue and I've already made sure that item control is at 0 0 1
and the issue persists... any fix for this?
