### ISSUE TITLE
Not in town

### ISSUE THREAD

**Issue by lYesterdaYl** [OpenKore/openkore#980]
Is there a way to change the value of towns? Like I want to add few maps in to "town" map, so I can use not in town function.

**Comment by c4c1n6kr3m1** [comment]
cities.txt on your tables folder

**Comment by lYesterdaYl** [comment]
can you please also tell where do I find the names of the rsw files? Thanks

**Comment by alisonrag** [comment]
In your grf file, or just type /where in ragnarok client and get the name of map
