### ISSUE TITLE
Not being able to run more than 15 kores?

### ISSUE THREAD

**Issue by LeHartx** [OpenKore/openkore#982]
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Steps to Reproduce: Running 14th openkore exe.

Also my PC specs are more than sufficient to run more than 15 kores at a time. I wish I could give more info but the logs don't tell anything except for the login part.

Server IP/Ports: https://gyazo.com/3c9d093c3c906be1543c00dbbfe0c0b7

**Comment by oleokoong** [comment]
Happen to me as well, should be server limited connection from ip

**Comment by ChrstphrR** [comment]
Do you really think that trimming down the bug report template to the minimum on an issue like this is helpful at all?

Throwing this back to the original issue poster.    No one is going to invest the time commitment into this until you bother detailing the environment you're running these supposed 15 instances at once.

Will be closed after 7 days if the OP does not come back with constructive details to explain and reproduce the problem, as there are SO MANY reasons why this may happen.

#NotAmusingInTheLeast
#FirstWorldProblems
#ObustructivelyAvoidingDoingTheDetailWorkNeededForABugReport

**Comment by ChrstphrR** [comment]
@oleokoong  Please refrain from posts on this that boil down to "Me too" with no added context.

**Comment by lututui** [comment]
The server is probably limiting the number of connections/ip

**Comment by kaliwanagan** [comment]
Awww @ChrstphrR is too lenient.

I was called an asshole by someone here, so maybe I should just live according to how people perceive me.

Closed because the template wasn't followed :)
