### ISSUE TITLE
Safengine CheatDefender crack request technician support thanks

### ISSUE THREAD

**Issue by kou90258** [OpenKore/openkore#983]
Taiwan in the 2017-08-18 14:30 to replace the new protective program "CheatDefender" system, the system and the Philippine server system is the same, and through the DrKNa crack this picture is key

![unknown](https://user-images.githubusercontent.com/25382808/29626040-1526cd34-8860-11e7-8b50-f05442f51225.png)

This code for the encryption
https://pastebin.com/krx7WcLd

Request encryption professional technician support decryption. if interested please contact DrKNa or to Discord group: https://discord.gg/kQX5b5u thank you.

forums.openkore.com
http://forums.openkore.com/viewtopic.php?f=55&t=212056

Taiwan use Game main program
http://dler.org/dl2/3015.php

**Comment by windhamwong** [comment]
Currently I am working on it. But yes, if someone wants to help and knows encryption, please help

**Comment by windhamwong** [comment]
I mark this as closed as we are currently working on this and do not need an extra issue ticket to track.

**Comment by YAO9423** [comment]
Taiwan in the 2017-08-18 14:30 to replace the new protective program "CheatDefender" system, the system and the Philippine server system is the same, and through the DrKNa crack this picture is key
