### ISSUE TITLE
Priest Skills Increase SP Recovery in config?

### ISSUE THREAD

**Issue by kidbreaker22** [OpenKore/openkore#987]
Hi!

I can't seem to find the ID for Increase SP Recovery for Priest.
I don't know if I'm truly blind or it's not there but what should I put in my skillsAddAuto_list ?

Thank you in advance!

**Comment by Nipodemos** [comment]
log in into your priest
type on console 
**skills**
and see the name of the skiil you want 😄

**Comment by kidbreaker22** [comment]
@Nipodemos Can I put the whole name instead of using the skill ID ?

**Comment by Kelberwitz** [comment]
`Increase SP Recovery` use this

**Comment by kidbreaker22** [comment]
@Kelberwitz Okay thank you
