### ISSUE TITLE
Re:tart autobuying problem.

### ISSUE THREAD

**Issue by Glikadin** [OpenKore/openkore#989]
Hello. Openkore last version.
Bot cant buy items and has stuck.

Console:
Task::TalkNPC::new has been called with sequence 'b e'.
Talking with NPC Butcher (0) at (105,99), ID 91 C3 00 00
Task::TalkNPC::addSteps has been called with value 'x'.
Task::TalkNPC::addSteps has been called with value 'b e'.
NPC Butcher (0): Initiating the talk
---------------- Store List (Butcher) ----------------
#  Name                    Type                  Price
0  Meat                    Usable Heal             50z
------------------------------------------------------
Task::TalkNPC::conversation_end called at ai npc_talk 'close'.
Done talking with NPC Butcher (0).
NPC Butcher (0): Task::TalkNPC::DESTROY was called
MecoPri has created a new group booking (index: )
Npc did not respond.
Calculating auto-storage route to: Izlude Town(izlude): 134, 88
You on route to: Izlude Town(izlude): 134, 88
Task::TalkNPC::new has been called with sequence 'b e'.
Talking with NPC Butcher (0) at (105,99), ID 91 C3 00 00
Task::TalkNPC::addSteps has been called with value 'x'.
Task::TalkNPC::addSteps has been called with value 'b e'.
NPC Butcher (0): Initiating the talk
Trying to auto close the conversation due to error.
Trying to auto close the conversation due to error.
Trying to auto close the conversation due to error.
Trying to auto close the conversation due to error.
Trying to auto close the conversation due to error.
Trying to auto close the conversation due to error.

Settings:

buyAuto Meat {
	minAmount 10
	maxAmount 100
	npc izlude 105 99
	zeny > 10000
	npc_steps b e
	distance 8
	disabled 0
	label BuyMeat
	passive
}

**Comment by troymark901** [comment]
@Glikadin do u have config for auto storage?

**Comment by troymark901** [comment]
![error](https://user-images.githubusercontent.com/30972158/29649915-188c5fa8-88a0-11e7-8706-ec9e64d096ab.JPG)
when you use fly wing get dc.

**Comment by godblesz** [comment]
![screenshot 2017-08-24 14 38 05](https://user-images.githubusercontent.com/31305000/29655209-6987cb9c-88da-11e7-98c3-b02e583e48c7.png)
Have same problem with autobuy but with different error
always talk to npc again after success autobuy and then disconnected

I used this setting

buyAuto red potion {
	npc xmas_in 40 38
	standpoint
	distance 3
	price
	minAmount
	maxAmount 100
	batchSize
	disable 0
}

**Comment by Glikadin** [comment]
Hello again. Was the solution found?

**Comment by godblesz** [comment]
nope,
still error

**Comment by alisonrag** [comment]
continue in #1006
