### ISSUE TITLE
sending raw packet to login is it possible?

### ISSUE THREAD

**Issue by XCBX** [OpenKore/openkore#99]
i played on a privateserver with encryption
i can sniff my login packet, and they are always the same.
can i send raw packet for username/password to login, like do send in macro?

**Comment by limelight16** [comment]
what kind of switch is that? ABCD? /heh

**Comment by XCBX** [comment]
/e4 not exactly but i cant seems to login and their client was protected so extracting recv.txt is nearly impossible
