### ISSUE TITLE
array on eventMacro does'nt support variables in index

### ISSUE THREAD

**Issue by Nipodemos** [OpenKore/openkore#990]
###### Summary: 
basiclly, i want to select a random value of index on a array, so that returns random texts.
but it doesn't have support for that. it dont work.
###### Impact:
i can't make my macro work as expected, and have to use other way, that its not cool =/
###### Expected Behavior:
make an array: @anwsers
push several answers to it
and then use an &rand in index to return a randon anwser
###### Actual Behavior:
it doesn't support the &rand, neither a variable
###### Steps to Reproduce:
```
automacro antiGM {
    PrivMsg /b.+t/i
    exclusive 1
    call {
		@awnsers = (i'm not a bot)
		&push (@awnsers, what)
		&push (@awnsers, you are crazy)
		&push (@awnsers, i dont even know what bot is )
		log $awnsers[0]
		log $awnsers[1]
		$sizeofarray = @awnsers
		$randNum= &rand(0,$sizeofarray )
		log number chosen is $randNum
		log answer chosen is : $awnsers[$randNum]
		log name of who sended the msg: $.PrivMsgLastName
		do pm $.PrivMsgLastName $awnsers[$randNum ]
	}
}
```
what prints:
```
[eventmacro log] i'm not a bot
[eventmacro log] what
[eventmacro log] number chosen is 2
[eventmacro log] answer chosen is :             #its blank
[eventmacro log] name of who sended the msg: normal person
```
and give an error in the end
is this a bug or is a non implemented feature?
@Henrybk  if you can see please

**Comment by Henrybk** [comment]
It should work, i will take a look later

**Comment by Nipodemos** [comment]
Downloaded openkore again, and tested with another macro.... it worked :sweat_smile: 
Sorry for the trouble, don't know what happened
