### ISSUE TITLE
Cannot Calculate route from...

### ISSUE THREAD

**Issue by kidbreaker22** [OpenKore/openkore#994]
Basically I get this message from console when my bot tries to go back to Toy Factory 2. It happens sometimes when bot dies and respawn at Aldebaran and it mostly happens when the bot accidently goes to the portal to Toy Factory 1. I tried fixing it by making an automacro when the map isn't xmas_dun02 it goes there by it doesn't work.

Here's my macro:
automacro NearEntranceHeal {
    hp < 30%
    exclusive 1
    run-once 1
    call {
        release FullyHeal
        do move xmas_dun02 135 132
        pause 1
        do sit
    }
}

automacro FullyHeal {
    hp = 100%
    status Blessing
    status Increase AGI
    status Impositio Manus
    status Kyrie Eleison
    exclusive 1
    run-once 1
    call {
        pause 1
        do stand 
        pause 1
        do move xmas_dun02 191 130
        pause 1
        release NearEntranceHeal
        stop
    }
}

automacro MapFix {
    location not xmas_dun02
    exclusive 1
    call {
        do move xmas_dun02 135 132
    }
}

![screenshot_20170824-123153](https://user-images.githubusercontent.com/31119522/29677805-4f0482d4-88ca-11e7-95ee-8096312af0e2.png)

**Comment by alisonrag** [comment]
in portals.txt maybe doesnt exists the full patch to xmas_dun02

try to save in aldebaran

**Comment by kidbreaker22** [comment]
The way I fix this problem is to hard close the openkore and reopen the bot, is there a way for me to do that in do command? So that I can just do that when the console says "Cannot calculate route from"

**Comment by Zexeta** [comment]
I am running into this problem with bots that worked great for weeks.  It all started with the recent updates to bypass the anti bot on re:start.

**Comment by alisonrag** [comment]
my fault, sorry. i swear that i readed alberta instead aldebaran.
sometimes i also get this error, we need to check the latest update in task route and try to find a solution.
is it always happen ?

**Comment by lututui** [comment]
I get this sometimes too. I find it to be very inconsistent too (at least I couldn't get to the bottom of it)

**Comment by kidbreaker22** [comment]
Not always but most of the time when I die or when I go to Toy Factory 1 this happens. And this only happened after the 1st Anti-Bot feature but then again I was changing my automacro so I'm not sure if it's my macro's fault or the openkore.

**Comment by koynro** [comment]
One thing I did notice is that your portals.txt will be updated with a path appended to the bottom. I tried setting portal discovery from default of 2 to 0 but that didn't seem to help.

**Comment by lututui** [comment]
> And this only happened after the 1st Anti-Bot feature but then again I was changing my automacro so I'm not sure if it's my macro's fault or the openkore.

It's not exclusive to iRO, I got this message on bRO Thor. I have no idea what's causing it nor how to reproduce it.

**Comment by flaiano** [comment]
Isto tem acontecido constantemente depois da ultima atualização do Openkore, usar apenas o comando reload all, ja resolve o problema e ele volta a funcionar normalmente.

https://cdn.discordapp.com/attachments/272070624157892618/350397309802119168/unknown.png

**Comment by flaiano** [comment]
apos utilizar o comando ai ai_v, tive esse resultado:

https://cdn.discordapp.com/attachments/272070624157892618/350399600227778562/unknown.png

**Comment by lututui** [comment]
> Isto tem acontecido constantemente depois da ultima atualização do Openkore, usar apenas o comando reload all, ja resolve o problema e ele volta a funcionar normalmente.
![image](https://user-images.githubusercontent.com/17522256/29691497-978e688a-8901-11e7-9cca-90797685c166.png)


"This has been happening quite often on newer versions of OpenKore, `reload all` fixes it for the time being and everything is back to normal"

>apos utilizar o comando ai ai_v, tive esse resultado:
![image](https://user-images.githubusercontent.com/17522256/29691519-b5c1a0ba-8901-11e7-9493-b978cf48a14c.png)
![image](https://user-images.githubusercontent.com/17522256/29691534-c815847a-8901-11e7-886a-39ef60ee3d58.png)

The command `ai ai_v` says:

**Comment by flaiano** [comment]
![image](https://user-images.githubusercontent.com/31326451/29702956-d92b5558-8949-11e7-8ddc-d74dbecab5ad.png)

**Comment by kipme** [comment]
Same thing happens to me too, made a little macro as a bandaid til we get the fix. Add this to your macros.txt

`
automacro reload {
	console /Cannot calculate a route from .* to/i
	call {
	do reload all
	}
}
`

**Comment by flaiano** [comment]
@lututui 

esta macro de cima, estava me dando um bug, que ele fechava o openkore, com a ajuda do pessoal, alterei para esta abaixo

automacro reload {
	console /Cannot calculate a route/
	call {
	do reload 10
	}
}

e agora esta funcionando normalmente.

**Comment by Yakbi** [comment]
The Openkore Console is closing when I'm using @kipme macro. Use this instead. 

> 
automacro restart {
console /Cannot calculate a route/
call {
do relog 5
pause 1
do reload all
}
}

**Comment by blakbord** [comment]
my openkore doesn't recognize this line
console /Cannot calculate a route/

I'm using eventMacro

**Comment by Nipodemos** [comment]
:roll_eyes: 
eventMacro doesn't have the console condition

you have to use macro plugin
@blakbord

**Comment by alisonrag** [comment]
use #1069 for a while
