### ISSUE TITLE
Issue- Anti-Botting on IRO servers. 

### ISSUE THREAD

**Issue by GeoBall** [OpenKore/openkore#997]
Forgive me if this has already been bypassed, but I could not find a relevant issue.
###### Summary: Cannot connect bots to IRO Ragnarok : Restart
Have tried using Xkore to bypass the anti-botting mechanism, it failed.

###### Impact:
Not able to bot.
###### Expected Behavior:
To log on and bot like normal
###### Actual Behavior:
Cannot connect to the map server, but gets through to the account server.
###### Steps to Reproduce:
Try connecting yourself.

**Comment by alisonrag** [comment]
everyone are boting o iro server, just download the latest version.
if you are talking about xKore we already have this issue:
#977

**Comment by GeoBall** [comment]
I thought I had the latest version because I recently downloaded it from Git-Hub. How often do they update? If ya know.

**Comment by alisonrag** [comment]
the updates in openkore are almost diary

**Comment by GeoBall** [comment]
Okay, thanks. I'll download the newest version and reapply my bots. Much appreciated!
